window.BILARA = window.BILARA || {};
window.BILARA["dn02"] = window.BILARA["dn02"] || {};
window.BILARA["dn02"]["vi"] = {
   "dn2:0.1": "Trường Bộ Kinh 2",
  "dn2:0.2": "Kinh Quả Sa-môn",

  "dn2:1.0": "1. Câu chuyện về vua và các đại thần",
  "dn2:1.1": "Tôi đã nghe như vầy—",
  "dn2:1.2": "Một thời, đức Phật ở tại Rājagaha (Vương Xá), trong vườn xoài của Jīvaka Komārabhacca, cùng với đại tăng đoàn gồm một ngàn hai trăm năm mươi vị Tỳ-kheo.",
  "dn2:1.3": "Lúc bấy giờ, vua nước Magadha là Ajātasattu, con bà Vedehī, vào ngày Bố-tát rằm, đêm trăng tròn sáng đẹp của mùa bốn tháng, đang ngồi trên lầu cao thượng hạng, được các đại thần vây quanh.",
  "dn2:1.4": "Khi ấy, vua Magadha Ajātasattu, con bà Vedehī, thốt lên lời cảm hứng trong ngày Bố-tát:",
  "dn2:1.5": "“Ôi, đêm trăng thật khả ái! Ôi, đêm trăng thật đẹp! Ôi, đêm trăng thật đáng chiêm ngưỡng! Ôi, đêm trăng thật thanh nhã! Ôi, đêm trăng thật rực rỡ!",
  "dn2:1.6": "Hôm nay ta nên đến thăm vị Sa-môn hay Bà-la-môn nào để khi đến thăm, tâm ta được tịnh tín?”",

  "dn2:2.1": "Khi ấy, một vị đại thần tâu vua Magadha Ajātasattu, con bà Vedehī:",
  "dn2:2.2": "“Tâu Đại vương, có Pūraṇa Kassapa là vị lãnh đạo một hội chúng, đứng đầu một nhóm, làm thầy của một nhóm, nổi tiếng, có danh vọng, là giáo chủ một phái, được nhiều người tôn trọng, lâu năm xuất gia, nhiều tuổi, cao niên.",
  "dn2:2.3": "Xin Đại vương hãy đến thăm Pūraṇa Kassapa.",
  "dn2:2.4": "Có thể khi Đại vương đến thăm Pūraṇa Kassapa, tâm Đại vương sẽ được tịnh tín.”",
  "dn2:2.5": "Nghe vậy, vua Magadha Ajātasattu, con bà Vedehī, im lặng.",

  "dn2:3.1": "Một vị đại thần khác cũng tâu vua Magadha Ajātasattu, con bà Vedehī:",
  "dn2:3.2": "“Tâu Đại vương, có Makkhali Gosāla là vị lãnh đạo một hội chúng… (cũng nổi tiếng, có danh vọng, giáo chủ một phái, được nhiều người tôn trọng, lâu năm xuất gia, nhiều tuổi).",
  "dn2:3.3": "Xin Đại vương hãy đến thăm Makkhali Gosāla.",
  "dn2:3.4": "Có thể khi Đại vương đến thăm Makkhali Gosāla, tâm Đại vương sẽ được tịnh tín.”",
  "dn2:3.5": "Nghe vậy, vua Magadha Ajātasattu, con bà Vedehī, im lặng.",

  "dn2:4.1": "Một vị đại thần khác lại tâu:",
  "dn2:4.2": "“Tâu Đại vương, có Ajita Kesakambala là vị lãnh đạo một hội chúng… nổi tiếng, có danh vọng, giáo chủ một phái, được nhiều người tôn trọng, lâu năm xuất gia, nhiều tuổi.",
  "dn2:4.3": "Xin Đại vương hãy đến thăm Ajita Kesakambala.",
  "dn2:4.4": "Có thể khi Đại vương đến thăm Ajita Kesakambala, tâm Đại vương sẽ được tịnh tín.”",
  "dn2:4.5": "Nghe vậy, vua Magadha Ajātasattu, con bà Vedehī, im lặng.",

  "dn2:5.1": "Một vị đại thần khác lại tâu:",
  "dn2:5.2": "“Tâu Đại vương, có Pakudha Kaccāyana là vị lãnh đạo một hội chúng… nổi tiếng, có danh vọng, giáo chủ một phái, được nhiều người tôn trọng, lâu năm xuất gia, nhiều tuổi.",
  "dn2:5.3": "Xin Đại vương hãy đến thăm Pakudha Kaccāyana.",
  "dn2:5.4": "Có thể khi Đại vương đến thăm Pakudha Kaccāyana, tâm Đại vương sẽ được tịnh tín.”",
  "dn2:5.5": "Nghe vậy, vua Magadha Ajātasattu, con bà Vedehī, im lặng.",

  "dn2:6.1": "Một vị đại thần khác lại tâu:",
  "dn2:6.2": "“Tâu Đại vương, có Sañcaya Belaṭṭhaputta là vị lãnh đạo một hội chúng… nổi tiếng, có danh vọng, giáo chủ một phái, được nhiều người tôn trọng, lâu năm xuất gia, nhiều tuổi.",
  "dn2:6.3": "Xin Đại vương hãy đến thăm Sañcaya Belaṭṭhaputta.",
  "dn2:6.4": "Có thể khi Đại vương đến thăm Sañcaya Belaṭṭhaputta, tâm Đại vương sẽ được tịnh tín.”",
  "dn2:6.5": "Nghe vậy, vua Magadha Ajātasattu, con bà Vedehī, im lặng.",

  "dn2:7.1": "Một vị đại thần khác lại tâu:",
  "dn2:7.2": "“Tâu Đại vương, có Nigaṇṭha Nāṭaputta là vị lãnh đạo một hội chúng… nổi tiếng, có danh vọng, giáo chủ một phái, được nhiều người tôn trọng, lâu năm xuất gia, nhiều tuổi.",
  "dn2:7.3": "Xin Đại vương hãy đến thăm Nigaṇṭha Nāṭaputta.",
  "dn2:7.4": "Có thể khi Đại vương đến thăm Nigaṇṭha Nāṭaputta, tâm Đại vương sẽ được tịnh tín.”",
  "dn2:7.5": "Nghe vậy, vua Magadha Ajātasattu, con bà Vedehī, im lặng.",
  "dn2:8.0": "2. Câu chuyện về Jīvaka Komārabhacca",
  "dn2:8.1": "Lúc bấy giờ, Jīvaka Komārabhacca đang ngồi im lặng không xa vua Magadha Ajātasattu, con bà Vedehī.",
  "dn2:8.2": "Khi ấy, vua Magadha Ajātasattu, con bà Vedehī, nói với Jīvaka Komārabhacca:",
  "dn2:8.3": "“Này hiền giả Jīvaka, sao ông im lặng?”",
  "dn2:8.4": "“Tâu Đại vương, đức Phật, bậc A-la-hán, bậc Chánh Đẳng Giác, hiện đang ở trong vườn xoài của chúng ta, cùng với đại tăng đoàn gồm một ngàn hai trăm năm mươi vị Tỳ-kheo.",
  "dn2:8.5": "Danh tiếng tốt đẹp này về đức Phật đã được truyền rộng:",
  "dn2:8.6": "‘Ngài là đức Phật, bậc A-la-hán, bậc Chánh Đẳng Giác, đầy đủ trí và hạnh, khéo đi, hiểu rõ thế gian, bậc tối thượng điều ngự người đáng được điều phục, thầy của trời và người, bậc Giác Ngộ, đức Phật.’",
  "dn2:8.7": "Xin Đại vương hãy đến thăm đức Phật.",
  "dn2:8.8": "Có thể khi Đại vương đến thăm đức Phật, tâm Đại vương sẽ được tịnh tín.”",
  "dn2:8.9": "“Vậy thì, này Jīvaka, hãy chuẩn bị voi cưỡi.”",

  "dn2:9.1": "“Vâng, thưa Đại vương.” Jīvaka vâng lời, cho chuẩn bị năm trăm thớt voi cái, cùng voi cưỡi dành cho vua, rồi tâu:",
  "dn2:9.2": "“Tâu Đại vương, voi cưỡi đã chuẩn bị xong,",
  "dn2:9.3": "xin Đại vương tùy thời.”",

  "dn2:10.1": "Bấy giờ, vua Magadha Ajātasattu cho mỗi người nữ lên một trong năm trăm voi cái, tự mình cưỡi voi lớn, đuốc được thắp sáng, từ Rājagaha đi ra với oai nghi lớn lao của bậc vương giả, hướng đến vườn xoài của Jīvaka.",
  "dn2:10.2": "Khi đến gần vườn xoài, vua bỗng cảm thấy sợ hãi, run rẩy, lông tóc dựng đứng.",
  "dn2:10.3": "Vua, sợ hãi và xúc động, nói với Jīvaka:",
  "dn2:10.4": "“Này Jīvaka, ông không lừa ta chứ?",
  "dn2:10.5": "Ông không đánh lừa ta chứ?",
  "dn2:10.6": "Ông không trao ta cho kẻ thù chứ?",
  "dn2:10.7": "Làm sao một đại tăng đoàn một ngàn hai trăm năm mươi vị Tỳ-kheo mà lại không có tiếng ho, không tiếng khạc, không tiếng động?”",
  "dn2:10.8": "“Đừng sợ, thưa Đại vương, đừng sợ.",
  "dn2:10.9": "Thần không lừa Đại vương;",
  "dn2:10.10": "không đánh lừa Đại vương;",
  "dn2:10.11": "không trao Đại vương cho kẻ thù.",
  "dn2:10.12": "Xin Đại vương tiến lên, kia là những ngọn đèn đang cháy nơi giảng đường tròn.”",

  "dn2:11.0": "3. Câu hỏi về quả của đời sống Sa-môn",
  "dn2:11.1": "Vua cưỡi voi đến nơi voi có thể đi, rồi xuống voi, đi bộ đến cửa giảng đường tròn và hỏi Jīvaka:",
  "dn2:11.2": "“Này Jīvaka, đức Phật ở đâu?”",
  "dn2:11.3": "“Tâu Đại vương, kia là đức Phật;",
  "dn2:11.4": "Ngài đang ngồi dựa vào cột giữa, quay mặt về phương đông, trước mặt là tăng đoàn.”",

  "dn2:12.1": "Vua đến gần đức Phật và đứng sang một bên.",
  "dn2:12.2": "Đứng sang một bên, vua nhìn tăng đoàn đang im lặng, an tịnh như mặt hồ trong, rồi thốt lên:",
  "dn2:12.3": "“Mong rằng hoàng tử Udayabhadda của ta cũng được sự an tịnh như thế này, như sự an tịnh mà tăng đoàn đang có.”",
  "dn2:12.4": "Đức Phật nói: “Đại vương đã nói theo lòng thương mến.”",
  "dn2:12.5": "“Bạch Thế Tôn, hoàng tử Udayabhadda là người con yêu quý của con.",
  "dn2:12.6": "Mong rằng hoàng tử được sự an tịnh như sự an tịnh mà tăng đoàn đang có.”",

  "dn2:13.1": "Rồi vua đảnh lễ đức Phật, chắp tay kính lễ tăng đoàn và ngồi xuống một bên.",
  "dn2:13.2": "Ngồi một bên, vua nói với đức Phật:",
  "dn2:13.3": "“Bạch Thế Tôn, con xin hỏi một điều;",
  "dn2:13.4": "nếu Thế Tôn cho phép con được hỏi.”",
  "dn2:13.5": "Đức Phật nói: “Hãy hỏi đi, Đại vương.”",

  "dn2:14.1": "Vua nói: “Bạch Thế Tôn, như các nghề nghiệp khác nhau trong đời,",
  "dn2:14.2": "như cưỡi voi, cưỡi ngựa, đánh xe, bắn cung, người hầu cận, chiến sĩ, vương tử, lính xung kích, dũng sĩ, chiến binh da giáp,",
  "dn2:14.3": "đầu bếp, thợ cắt tóc, thợ tắm, người nấu ăn, người kết vòng hoa, thợ giặt, thợ dệt, thợ đan, thợ gốm, kế toán, người đóng dấu, và các nghề tương tự khác—",
  "dn2:14.4": "họ sống bằng kết quả thấy được ngay trong đời này; họ nuôi sống và làm sung túc bản thân, cha mẹ, vợ con, bạn bè; họ còn có thể bố thí cúng dường cho Sa-môn và Bà-la-môn, tạo phước đưa đến quả vui, đưa đến cảnh tốt đẹp.",
  "dn2:14.5": "Vậy có thể nào, bạch Thế Tôn, chỉ ra được một quả của đời sống Sa-môn thấy được ngay trong đời này như thế không?”",

  "dn2:15.1": "Đức Phật hỏi: “Đại vương đã từng hỏi câu này với các Sa-môn hay Bà-la-môn khác chưa?”",
  "dn2:15.2": "Vua đáp: “Bạch Thế Tôn, con đã hỏi rồi.”",
  "dn2:15.3": "“Vậy họ đã trả lời thế nào? Nếu không phiền, hãy nói.”",
  "dn2:15.4": "“Bạch Thế Tôn, con không thấy phiền, khi đức Phật đang ngồi đây, hay trước mặt bậc như đức Phật.”",
  "dn2:15.5": "“Vậy thì, này Đại vương, hãy nói đi.”",
  "dn2:16.0": "3.1. Quan điểm của Pūraṇa Kassapa",
  "dn2:16.1": "“Bạch Thế Tôn, có một lần con đã đến gặp Pūraṇa Kassapa; sau khi đến, con đã chào hỏi và trao đổi xã giao với Pūraṇa Kassapa.",
  "dn2:16.2": "Sau khi nói những lời thân tình và đáng ghi nhớ, con ngồi xuống một bên. Ngồi xuống một bên, bạch Thế Tôn, con đã nói với Pūraṇa Kassapa như sau:",
  "dn2:16.3": "‘Này Kassapa, cũng như các nghề nghiệp khác nhau trong đời,",
  "dn2:16.4": "như là người cưỡi voi, cưỡi ngựa, đánh xe, bắn cung, người hầu cận, chiến sĩ, vương tử, lính xung kích, dũng sĩ, chiến binh mặc giáp da, con của nữ tỳ, đầu bếp, thợ cắt tóc, người tắm rửa, người nấu ăn, người kết vòng hoa, thợ giặt, thợ dệt, thợ đan, thợ gốm, người tính toán, người đóng dấu, và các nghề tương tự khác — họ sống bằng kết quả nghề nghiệp thấy được ngay trong đời này;",
  "dn2:16.5": "nhờ đó họ làm cho bản thân được an vui, đầy đủ; làm cho cha mẹ được an vui, đầy đủ; làm cho vợ con được an vui, đầy đủ; làm cho bạn bè, thân hữu được an vui, đầy đủ; và còn thiết lập sự cúng dường cao thượng đến các Sa-môn và Bà-la-môn, đưa đến quả vui, đưa đến cảnh tốt đẹp.",
  "dn2:16.6": "Vậy này Kassapa, có thể nào cũng chỉ ra được một quả của đời sống Sa-môn thấy được ngay trong đời này như thế không?’",
  "dn2:17.1": "Khi được hỏi như vậy, bạch Thế Tôn, Pūraṇa Kassapa đã nói với con như sau:",
  "dn2:17.2": "‘Tâu Đại vương, dù tự mình làm hay khiến người khác làm, dù chém giết hay bảo người khác chém giết, dù nấu nướng hay bảo người khác nấu nướng, dù gây buồn khổ hay bảo người khác gây buồn khổ, dù làm khổ mình hay làm khổ người khác, dù giết hại sinh mạng, lấy của không cho, phá cửa đột nhập, cướp bóc, đột nhập từng nhà, đứng chặn đường, thông dâm với vợ người khác, nói dối — làm như vậy cũng không tạo ra điều ác. Dù có dùng bánh xe sắc bén càn quét toàn bộ chúng sinh trên trái đất này thành một đống thịt, một khối thịt, cũng không vì thế mà có tội ác, không có sự phát sinh của tội ác.",
  "dn2:17.3": "Dù có đi dọc bờ nam sông Hằng mà giết hại, tàn sát, chém giết, nấu nướng, cũng không vì thế mà có tội ác, không có sự phát sinh của tội ác.",
  "dn2:17.4": "Dù có đi dọc bờ bắc sông Hằng mà bố thí, khuyến khích bố thí, tế lễ hay khiến người khác tế lễ, cũng không vì thế mà có phước, không có sự phát sinh của phước.",
  "dn2:17.5": "Bố thí, tự chế, giữ gìn, nói lời chân thật — không có phước, không có sự phát sinh của phước.’",
  "dn2:18.1": "“Bạch Thế Tôn, khi được con hỏi về quả của đời sống Sa-môn thấy được ngay trong đời này, Pūraṇa Kassapa lại trả lời bằng thuyết ‘không có hành động tạo nghiệp’.",
  "dn2:18.2": "Cũng như khi được hỏi về trái xoài lại trả lời về trái mít, hay khi được hỏi về trái mít lại trả lời về trái xoài;",
  "dn2:18.3": "cũng vậy, bạch Thế Tôn, khi được hỏi về quả của đời sống Sa-môn thấy được ngay trong đời này, Pūraṇa Kassapa lại trả lời bằng thuyết ‘không có hành động tạo nghiệp’.",
  "dn2:18.4": "Khi ấy con nghĩ như sau:",
   "dn2:18.5": "‘Làm sao một người như ta lại có thể nghĩ đến việc chê trách hay hạ thấp một Sa-môn hay Bà-la-môn đang sống trong quốc độ của mình?’",
  "dn2:18.6": "Vì vậy, bạch Thế Tôn, con không tán thành cũng không phản đối lời nói của Pūraṇa Kassapa.",
  "dn2:18.7": "Không tán thành cũng không phản đối, trong lòng không hoan hỷ, nhưng cũng không thốt ra lời bất mãn, chỉ ghi nhận lời ấy, không công kích, rồi đứng dậy rời khỏi chỗ ngồi mà đi.",
  "dn2:19.0": "3.2. Quan điểm của Makkhali Gosāla",
  "dn2:19.1": "“Bạch Thế Tôn, có một lần con đã đến gặp Makkhali Gosāla; sau khi đến, con đã chào hỏi và nói những lời xã giao với ông ta.",
  "dn2:19.2": "Sau khi nói những lời thân tình và đáng ghi nhớ, con ngồi xuống một bên. Ngồi xuống một bên, bạch Thế Tôn, con đã nói với Makkhali Gosāla rằng:",
  "dn2:19.3": "‘Này Gosāla, cũng như các nghề nghiệp khác nhau trong đời …",
  "dn2:19.4": "có thể nào, này Gosāla, cũng chỉ ra được một quả của đời sống Sa-môn thấy được ngay trong đời này như thế không?’",
  "dn2:20.1": "Khi được hỏi như vậy, bạch Thế Tôn, Makkhali Gosāla đã nói với con như sau:",
  "dn2:20.2": "‘Tâu Đại vương, không có nguyên nhân, không có điều kiện đưa đến sự nhiễm ô của các chúng sinh; không do nguyên nhân, không do điều kiện mà các chúng sinh bị nhiễm ô.",
  "dn2:20.3": "Không có nguyên nhân, không có điều kiện đưa đến sự thanh tịnh của các chúng sinh;",
  "dn2:20.4": "không do nguyên nhân, không do điều kiện mà các chúng sinh được thanh tịnh.’",
   "dn2:20.5": "Không có tự mình làm, không có người khác làm, không có nỗ lực của con người, không có sức mạnh, không có tinh tấn, không có ý chí, không có cố gắng của con người.",
  "dn2:20.6": "Tất cả chúng sinh, tất cả sinh vật, tất cả loài hữu tình đều không tự chủ, không có năng lực, không có tinh tấn; họ bị chi phối bởi định mệnh và sự phối hợp hoàn cảnh, rồi phải cảm thọ khổ và vui trong sáu loại sinh.",
  "dn2:20.7": "Có một trăm bốn mươi vạn loại sinh khởi, sáu mươi và sáu trăm loại khác, năm trăm nghiệp và năm nghiệp, ba nghiệp, nghiệp và nửa nghiệp, sáu mươi hai con đường, sáu mươi hai trung kiếp, sáu loại sinh, tám địa vị con người, bốn mươi chín trăm Ajīvaka, bốn mươi chín trăm du sĩ, bốn mươi chín trăm chỗ ở của rồng, hai mươi trăm căn, ba mươi trăm địa ngục, ba mươi sáu giới trần, bảy bào thai có tưởng, bảy bào thai không tưởng, bảy bào thai của Nigaṇṭha, bảy trời, bảy người, bảy quỷ, bảy hồ, bảy trăm hồ, bảy vực, bảy trăm vực, bảy giấc mộng, bảy trăm giấc mộng, tám mươi bốn ngàn đại kiếp — trong đó kẻ ngu và người trí sau khi chạy vòng luân hồi sẽ chấm dứt khổ đau.",
  "dn2:20.8": "Ở đây không có chuyện: ‘Nhờ giới hạnh, nghi lễ, khổ hạnh hay đời sống phạm hạnh này mà ta sẽ làm cho nghiệp chưa chín được chín, hay làm cho nghiệp đã chín được tiêu diệt.’ Không có chuyện như vậy.",
  "dn2:20.9": "Khổ và vui đã được đong đo sẵn, luân hồi có giới hạn; không có tăng hay giảm, không có cao hay thấp.",
  "dn2:20.10": "Giống như cuộn chỉ bị ném ra sẽ tự nó tuôn ra cho đến khi hết;",
  "dn2:20.11": "cũng vậy, kẻ ngu và người trí sau khi chạy vòng luân hồi sẽ tự kết thúc khổ đau.’",
  "dn2:21.1": "Bạch Thế Tôn, khi được hỏi về quả của đời sống Sa-môn thấy được ngay trong đời này, Makkhali Gosāla lại trả lời bằng thuyết thanh lọc qua luân hồi.",
  "dn2:21.2": "Cũng như khi được hỏi về trái xoài lại trả lời về trái mít, hay khi được hỏi về trái mít lại trả lời về trái xoài;",
  "dn2:21.3": "cũng vậy, bạch Thế Tôn, khi được hỏi về quả của đời sống Sa-môn thấy được ngay trong đời này, Makkhali Gosāla lại trả lời bằng thuyết thanh lọc qua luân hồi.",
  "dn2:21.4": "Khi ấy con nghĩ như sau:",
  "dn2:21.5": "‘Làm sao một người như ta lại có thể nghĩ đến việc chê trách hay hạ thấp một Sa-môn hay Bà-la-môn đang sống trong quốc độ của mình?’",
  "dn2:21.6": "Vì vậy, bạch Thế Tôn, con không tán thành cũng không phản đối lời nói của Makkhali Gosāla.",
  "dn2:21.7": "Không tán thành cũng không phản đối, trong lòng không hoan hỷ nhưng cũng không thốt ra lời bất mãn, chỉ ghi nhận lời ấy, không công kích, rồi đứng dậy rời khỏi chỗ ngồi mà đi.",
  "dn2:22.0": "3.3. Quan điểm của Ajita Kesakambala",
  "dn2:22.1": "“Một thời, bạch Thế Tôn, con đã đi đến gặp Ajita Kesakambala; đến nơi, con trao đổi lời chào hỏi thân thiện với ông Ajita Kesakambala.",
  "dn2:22.2": "Sau khi nói chuyện xã giao và thăm hỏi, con ngồi xuống một bên. Khi đã ngồi xuống một bên, con nói với Ajita Kesakambala rằng:",
  "dn2:22.3": "‘Cũng như các ngành nghề khác nhau trên đời …",
  "dn2:22.4": "có thể chăng, này Ajita, trình bày một kết quả của đời sống Sa-môn có thể thấy ngay trong hiện tại như vậy không?’",
  "dn2:23.1": "Khi được hỏi như vậy, bạch Thế Tôn, Ajita Kesakambala nói với con rằng:",
  "dn2:23.2": "‘Thưa Đại vương, không có bố thí, không có cúng tế, không có lễ hiến; không có quả và dị thục của các nghiệp thiện hay bất thiện; không có đời này, không có đời sau; không có mẹ, không có cha; không có chúng sinh hóa sinh; không có Sa-môn hay Bà-la-môn nào trên đời sống đúng đắn, hành trì chân chánh, tự mình chứng ngộ bằng thắng trí rồi tuyên bố về đời này và đời sau.",
  "dn2:23.3": "Con người này chỉ là bốn đại hợp thành. Khi chết, đất trở về với đất, nước trở về với nước, lửa trở về với lửa, gió trở về với gió; các căn hòa vào hư không.",
  "dn2:23.4": "Bốn người khiêng cáng, là người thứ năm, mang xác chết đi.",
  "dn2:23.5": "Dấu chân chỉ còn thấy đến tận nghĩa địa.",
  "dn2:23.6": "Xương trắng như màu chim bồ câu, và các lễ tế chỉ còn là tro tàn.",
  "dn2:23.7": "Bố thí chỉ là lời nói của kẻ ngu đặt ra.’",
   "dn2:23.8": "Những lời của những ai chủ trương có sự tồn tại (thuyết hữu) chỉ là lời nói rỗng tuếch, hư dối, vô nghĩa.",
  "dn2:23.9": "Kẻ ngu và người trí, khi thân hoại mạng chung, đều bị đoạn diệt, tiêu vong; sau khi chết không còn tồn tại nữa.’",
  "dn2:24.1": "Như vậy, bạch Thế Tôn, Ajita Kesakambala khi được hỏi về quả của đời sống Sa-môn có thể thấy ngay trong hiện tại, đã trả lời bằng thuyết đoạn diệt.",
  "dn2:24.2": "Ví như, bạch Thế Tôn, khi được hỏi về trái xoài lại trả lời về trái mít, hoặc khi được hỏi về trái mít lại trả lời về trái xoài;",
  "dn2:24.3": "cũng vậy, khi được hỏi về quả của đời sống Sa-môn có thể thấy ngay trong hiện tại, Ajita Kesakambala lại trả lời bằng thuyết đoạn diệt.",
  "dn2:24.4": "Lúc ấy, bạch Thế Tôn, con nghĩ rằng:",
  "dn2:24.5": "‘Làm sao một người như ta lại có thể nghĩ đến việc chê trách hay hạ thấp một Sa-môn hay Bà-la-môn đang sống trong quốc độ của mình?’",
  "dn2:24.6": "Vì vậy, bạch Thế Tôn, con không tán thành cũng không phản đối lời nói của Ajita Kesakambala.",
  "dn2:24.7": "Không tán thành cũng không phản đối, trong lòng không hoan hỷ nhưng cũng không thốt ra lời bất mãn, chỉ ghi nhận lời ấy, không công kích, rồi đứng dậy rời khỏi chỗ ngồi mà đi.",
  "dn2:25.0": "3.4. Quan điểm của Pakudha Kaccāyana",
   "dn2:25.1": "“Một thời, bạch Thế Tôn, con đã đi đến gặp Pakudha Kaccāyana; đến nơi, con trao đổi lời chào hỏi thân thiện với ông Pakudha Kaccāyana.",
  "dn2:25.2": "Sau khi nói chuyện xã giao và thăm hỏi, con ngồi xuống một bên. Khi đã ngồi xuống một bên, con nói với Pakudha Kaccāyana rằng:",
  "dn2:25.3": "‘Cũng như các ngành nghề khác nhau trên đời …",
  "dn2:25.4": "có thể chăng, này Kaccāyana, trình bày một kết quả của đời sống Sa-môn có thể thấy ngay trong hiện tại như vậy không?’",
  "dn2:26.1": "Khi được hỏi như vậy, bạch Thế Tôn, Pakudha Kaccāyana nói với con rằng:",
  "dn2:26.2": "‘Thưa Đại vương, có bảy thực thể này là không do làm ra, không do tạo tác, không do sáng tạo, không do ai tạo, bất sinh, vững chắc như đỉnh núi, đứng yên như cột trụ.",
  "dn2:26.3": "Chúng không dao động, không biến đổi, không làm hại lẫn nhau, cũng không đủ điều kiện để mang lại cho nhau khổ hay lạc hay cả khổ lẫn lạc.",
  "dn2:26.4": "Bảy thực thể ấy là gì?",
  "dn2:26.5": "Thể đất, thể nước, thể lửa, thể gió, lạc, khổ, và mạng sống là thứ bảy—",
  "dn2:26.6": "bảy thực thể này là không do làm ra, không do tạo tác, không do sáng tạo, không do ai tạo, bất sinh, vững chắc như đỉnh núi, đứng yên như cột trụ.",
  "dn2:26.7": "Chúng không dao động, không biến đổi, không làm hại lẫn nhau, cũng không đủ điều kiện để mang lại cho nhau khổ hay lạc hay cả khổ lẫn lạc.",
  "dn2:26.8": "Trong đó không có kẻ giết hay người bị giết, không có người nghe hay người làm cho nghe, không có người biết hay người làm cho biết.",
  "dn2:26.9": "Ngay cả người dùng gươm bén chặt đầu ai đó, cũng không ai tước đoạt mạng sống của ai;",
  "dn2:26.10": "chỉ là lưỡi gươm đi xuyên qua khoảng giữa bảy thực thể ấy mà thôi.’",
  "dn2:27.1": "Như vậy, bạch Thế Tôn, Pakudha Kaccāyana khi được hỏi về quả của đời sống Sa-môn có thể thấy ngay trong hiện tại, lại trả lời chuyện khác với điều được hỏi.",
  "dn2:27.2": "Ví như, bạch Thế Tôn, khi được hỏi về trái xoài lại trả lời về trái mít, hoặc khi được hỏi về trái mít lại trả lời về trái xoài;",
  "dn2:27.3": "cũng vậy, khi được hỏi về quả của đời sống Sa-môn có thể thấy ngay trong hiện tại, Pakudha Kaccāyana lại trả lời chuyện khác.",
  "dn2:27.4": "Lúc ấy, bạch Thế Tôn, con nghĩ rằng:",
  "dn2:27.5": "‘Làm sao một người như ta lại có thể nghĩ đến việc chê trách hay hạ thấp một Sa-môn hay Bà-la-môn đang sống trong quốc độ của mình?’",
  "dn2:27.6": "Vì vậy, bạch Thế Tôn, con không tán thành cũng không phản đối lời nói của Pakudha Kaccāyana.",
  "dn2:27.7": "Không tán thành cũng không phản đối, trong lòng không hoan hỷ nhưng cũng không thốt ra lời bất mãn, chỉ ghi nhận lời ấy, không công kích, rồi đứng dậy rời khỏi chỗ ngồi mà đi.",
  "dn2:28.0": "3.5. Quan điểm của Nigaṇṭha Nātaputta",
  "dn2:28.1": "Một thời, bạch Thế Tôn, con đã đi đến gặp Nigaṇṭha Nātaputta; đến nơi, con trao đổi lời chào hỏi thân thiện với ông Nigaṇṭha Nātaputta.",
  "dn2:28.2": "Sau khi nói chuyện xã giao và thăm hỏi, con ngồi xuống một bên. Khi đã ngồi xuống một bên, con nói với Nigaṇṭha Nātaputta rằng:",
  "dn2:28.3": "‘Cũng như các ngành nghề khác nhau trên đời, này Agnivessana …",
  "dn2:28.4": "có thể chăng, này Agnivessana, trình bày một kết quả của đời sống Sa-môn có thể thấy ngay trong hiện tại như vậy không?’",
  "dn2:29.1": "Khi được hỏi như vậy, bạch Thế Tôn, Nigaṇṭha Nātaputta nói với con rằng:",
  "dn2:29.2": "‘Ở đây, thưa Đại vương, một Nigaṇṭha được bảo hộ bởi sự chế ngự bốn phương diện.",
  "dn2:29.3": "Và thế nào là một Nigaṇṭha được bảo hộ bởi sự chế ngự bốn phương diện?",
  "dn2:29.4": "Ở đây, thưa Đại vương, Nigaṇṭha ấy được ngăn giữ đối với mọi loại nước, được ràng buộc đối với mọi loại nước, được gột sạch khỏi mọi loại nước, và được thấm nhuần bởi mọi loại nước.",
  "dn2:29.5": "Như vậy, thưa Đại vương, một Nigaṇṭha được bảo hộ bởi sự chế ngự bốn phương diện.",
  "dn2:29.6": "Khi nào, thưa Đại vương, một Nigaṇṭha được bảo hộ như vậy bởi sự chế ngự bốn phương diện,",
  "dn2:29.7": "thì được gọi là vị đã đạt tự chủ, đã khéo tự chủ và an trú trong tự chủ.’",
  "dn2:30.1": "Như vậy, bạch Thế Tôn, Nigaṇṭha Nātaputta khi được hỏi về quả của đời sống Sa-môn có thể thấy ngay trong hiện tại, lại trả lời bằng sự chế ngự bốn phương diện.",
  "dn2:30.2": "Ví như, bạch Thế Tôn, khi được hỏi về trái xoài lại trả lời về trái mít, hoặc khi được hỏi về trái mít lại trả lời về trái xoài;",
  "dn2:30.3": "cũng vậy, khi được hỏi về quả của đời sống Sa-môn có thể thấy ngay trong hiện tại, Nigaṇṭha Nātaputta lại trả lời bằng sự chế ngự bốn phương diện.",
  "dn2:30.4": "Lúc ấy, bạch Thế Tôn, con nghĩ rằng:",
   "dn2:30.5": "‘Làm sao một người như ta lại có thể nghĩ đến việc chê trách hay hạ thấp một Sa-môn hay Bà-la-môn đang sống trong quốc độ của mình?’",
  "dn2:30.6": "Vì vậy, bạch Thế Tôn, con không tán thành cũng không phản đối lời nói của Nigaṇṭha Nātaputta.",
  "dn2:30.7": "Không tán thành cũng không phản đối, trong lòng không hoan hỷ nhưng cũng không thốt ra lời bất mãn, chỉ ghi nhận lời ấy, không công kích, rồi đứng dậy rời khỏi chỗ ngồi mà đi.",
  "dn2:31.0": "3.6. Quan điểm của Sañcaya Belaṭṭhaputta",
  "dn2:31.1": "Một thời, bạch Thế Tôn, con đã đi đến gặp Sañcaya Belaṭṭhaputta; đến nơi, con trao đổi lời chào hỏi thân thiện với ông Sañcaya Belaṭṭhaputta.",
  "dn2:31.2": "Sau khi nói chuyện xã giao và thăm hỏi, con ngồi xuống một bên. Khi đã ngồi xuống một bên, con nói với Sañcaya Belaṭṭhaputta rằng:",
  "dn2:31.3": "‘Cũng như các ngành nghề khác nhau trên đời, này Sañcaya …",
  "dn2:31.4": "có thể chăng, này Sañcaya, trình bày một kết quả của đời sống Sa-môn có thể thấy ngay trong hiện tại như vậy không?’",
  "dn2:32.1": "Khi được hỏi như vậy, bạch Thế Tôn, Sañcaya Belaṭṭhaputta nói với con rằng:",
  "dn2:32.2": "‘Nếu ngài hỏi ta: “Có đời sau chăng?” Nếu ta cho rằng có đời sau, ta sẽ trả lời ngài rằng có đời sau.",
  "dn2:32.3": "Nhưng ta không nói là như vậy; ta cũng không nói là khác vậy; ta cũng không nói là không phải vậy; ta cũng không nói là không; ta cũng không nói là vừa không vừa không phải không.",
  "dn2:32.4": "Nếu hỏi: “Không có đời sau chăng?” …’",
   "dn2:32.5": "‘Vừa có vừa không có đời sau …",
  "dn2:32.6": "Không phải có mà cũng không phải không có đời sau …",
  "dn2:32.7": "Có chúng sinh tái sinh (hóa sinh) …",
  "dn2:32.8": "Không có chúng sinh tái sinh …",
  "dn2:32.9": "Vừa có vừa không có chúng sinh tái sinh …",
  "dn2:32.10": "Không phải có mà cũng không phải không có chúng sinh tái sinh …",
  "dn2:32.11": "Có quả báo, có kết quả của các nghiệp thiện và bất thiện …",
  "dn2:32.12": "Không có quả báo, không có kết quả của các nghiệp thiện và bất thiện …",
  "dn2:32.13": "Vừa có vừa không có quả báo của các nghiệp thiện và bất thiện …",
  "dn2:32.14": "Không phải có mà cũng không phải không có quả báo của các nghiệp thiện và bất thiện …",
  "dn2:32.15": "Như Lai tồn tại sau khi chết …",
  "dn2:32.16": "Như Lai không tồn tại sau khi chết …",
  "dn2:32.17": "Như Lai vừa tồn tại vừa không tồn tại sau khi chết …",
  "dn2:32.18": "Như Lai không phải tồn tại mà cũng không phải không tồn tại sau khi chết. Nếu ngài hỏi ta như vậy, và nếu ta cho là như vậy, ta sẽ trả lời ngài như vậy.",
  "dn2:32.19": "Nhưng ta không nói là như vậy; ta cũng không nói là khác vậy; ta cũng không nói là không phải vậy; ta cũng không nói là không; ta cũng không nói là vừa không vừa không phải không.’",
  "dn2:33.1": "Như vậy, bạch Thế Tôn, khi được hỏi về kết quả của đời sống Sa-môn có thể thấy ngay trong hiện tại, Sañcaya Belaṭṭhaputta đã trả lời bằng cách lảng tránh.",
  "dn2:33.2": "Cũng như, bạch Thế Tôn, khi được hỏi về quả xoài lại trả lời về quả mít, hay khi được hỏi về quả mít lại trả lời về quả xoài;",
  "dn2:33.3": "cũng vậy, khi được hỏi về kết quả của đời sống Sa-môn có thể thấy ngay trong hiện tại, Sañcaya Belaṭṭhaputta đã trả lời bằng cách lảng tránh.",
  "dn2:33.4": "Khi ấy, bạch Thế Tôn, con nghĩ rằng:",
    "dn2:33.5": "‘Vị này trong số các Sa-môn và Bà-la-môn ấy thật là người ngu nhất, mê lầm nhất.",
  "dn2:33.6": "Làm sao khi được hỏi về kết quả của đời sống Sa-môn có thể thấy ngay trong hiện tại lại trả lời bằng cách lảng tránh như vậy?’",
  "dn2:33.7": "Khi ấy, bạch Thế Tôn, con nghĩ rằng:",
  "dn2:33.8": "‘Làm sao một người như ta lại có thể nghĩ đến việc chê trách hay hạ thấp một Sa-môn hay Bà-la-môn đang sống trong quốc độ của mình?’",
  "dn2:33.9": "Vì vậy, bạch Thế Tôn, con không tán thành cũng không phản đối lời nói của Sañcaya Belaṭṭhaputta.",
  "dn2:33.10": "Không tán thành cũng không phản đối, trong lòng không hoan hỷ nhưng cũng không thốt ra lời bất mãn, chỉ ghi nhận lời ấy, không công kích, rồi đứng dậy rời khỏi chỗ ngồi mà đi.",
  "dn2:34.0.1": "4. Kết quả của đời sống Sa-môn",
  "dn2:34.0.2": "4.1. Kết quả thứ nhất có thể thấy ngay trong hiện tại",
  "dn2:34.1": "Vì vậy, bạch Thế Tôn, nay con hỏi Thế Tôn:",
  "dn2:34.2": "‘Cũng như các ngành nghề khác nhau trên đời, bạch Thế Tôn,",
  "dn2:34.3": "như là người cưỡi voi, người cưỡi ngựa, đánh xe, cung thủ, lính hầu, người hầu cận, người phân phát lương thực, võ sĩ, vương tử, chiến sĩ xung phong, dũng sĩ, chiến binh mặc giáp da, con của nữ tỳ,",
  "dn2:34.4": "đầu bếp, thợ cạo, người tắm rửa, thợ nấu ăn, người kết vòng hoa, thợ giặt, thợ dệt, thợ đan, thợ gốm, kế toán, thợ đóng dấu, hay bất cứ ngành nghề nào tương tự như vậy — họ sống bằng kết quả nghề nghiệp thấy ngay trong hiện tại;",
  "dn2:34.5": "nhờ đó họ làm cho bản thân được an vui, được đầy đủ; làm cho cha mẹ được an vui, được đầy đủ; làm cho vợ con được an vui, được đầy đủ; làm cho bạn bè, thân quyến được an vui, được đầy đủ; và còn thiết lập cúng dường cao thượng đến các Sa-môn, Bà-la-môn, đưa đến phước báo an lạc và sanh lên cõi trời.",
  "dn2:34.6": "Có thể chăng, bạch Thế Tôn, cũng trình bày một kết quả của đời sống Sa-môn có thể thấy ngay trong hiện tại như vậy?’",
  "dn2:34.7": "‘Có thể được, này Đại vương.’",
    "dn2:34.8": "“Vậy thì, này Đại vương, Ta sẽ hỏi lại Đại vương về chính vấn đề này. Đại vương thấy thế nào thì hãy trả lời như vậy.”",
  "dn2:35.1": "“Này Đại vương, Đại vương nghĩ sao:",
  "dn2:35.2": "Ở đây có một người là nô lệ, làm công cho Đại vương, dậy sớm, ngủ muộn, luôn sẵn sàng làm theo lệnh, cư xử vừa lòng, nói lời dễ nghe, luôn nhìn sắc mặt chủ.",
  "dn2:35.3": "Người ấy nghĩ rằng:",
  "dn2:35.4": "‘Thật kỳ diệu thay, thật hi hữu thay là sự dẫn dắt của phước, là quả báo của phước.",
  "dn2:35.5": "Vị vua Ma-kiệt-đà Ajātasattu, con của bà Vedehī, cũng là con người; ta cũng là con người.",
  "dn2:35.6": "Vị vua Ma-kiệt-đà Ajātasattu ấy được đầy đủ và hưởng thụ năm loại dục lạc, như thể là một vị trời.",
  "dn2:35.7": "Còn ta lại là nô lệ, làm công cho ông, dậy sớm, ngủ muộn, luôn sẵn sàng làm theo lệnh, cư xử vừa lòng, nói lời dễ nghe, luôn nhìn sắc mặt chủ.",
  "dn2:35.8": "Ước gì ta có thể làm các việc phước thiện.",
  "dn2:35.9": "Hay là ta cạo bỏ râu tóc, khoác y ca-sa, rời bỏ gia đình, xuất gia sống đời không nhà?’",
  "dn2:35.10": "Sau một thời gian, người ấy cạo bỏ râu tóc, khoác y ca-sa, rời bỏ gia đình, xuất gia sống đời không nhà.",
  "dn2:35.11": "Sau khi xuất gia như vậy, người ấy sống chế ngự thân, chế ngự lời nói, chế ngự ý nghĩ; biết đủ với thức ăn và y phục; vui thích trong đời sống viễn ly.",
  "dn2:35.12": "Rồi có người tâu với Đại vương như sau:",
  "dn2:35.13": "‘Tâu Đại vương, xin Đại vương biết rằng người nô lệ, làm công cho Đại vương, dậy sớm, ngủ muộn, luôn sẵn sàng làm theo lệnh, cư xử vừa lòng, nói lời dễ nghe, luôn nhìn sắc mặt chủ ấy,",
  "dn2:35.14": "nay đã cạo bỏ râu tóc, khoác y ca-sa, rời bỏ gia đình, xuất gia sống đời không nhà.",
  "dn2:35.15": "Sau khi xuất gia như vậy, người ấy sống chế ngự thân, chế ngự lời nói, chế ngự ý nghĩ; biết đủ với thức ăn và y phục; vui thích trong đời sống viễn ly.’",
  "dn2:35.16": "Này Đại vương, Đại vương có nói như thế này không:",
   "dn2:35.17": "‘Hãy gọi người ấy lại cho ta; để người ấy trở lại làm nô lệ, làm công cho ta, dậy sớm, ngủ muộn, luôn sẵn sàng làm theo lệnh, cư xử vừa lòng, nói lời dễ nghe, luôn nhìn sắc mặt chủ’ — Đại vương có nói như vậy không?”",
  "dn2:36.1": "“Thưa không, bạch Thế Tôn.",
  "dn2:36.2": "Trái lại, chính chúng con sẽ đảnh lễ người ấy, đứng dậy chào người ấy, mời người ấy ngồi, thỉnh người ấy nhận y áo, vật thực, chỗ ở, thuốc men khi bệnh; và còn sắp đặt sự che chở, bảo hộ đúng pháp cho người ấy.”",
  "dn2:36.3": "“Này Đại vương, Đại vương nghĩ sao:",
  "dn2:36.4": "Trong trường hợp như vậy, có phải là một kết quả của đời sống Sa-môn có thể thấy ngay trong hiện tại hay không?”",
  "dn2:36.5": "“Quả thật, bạch Thế Tôn, trong trường hợp như vậy là một kết quả của đời sống Sa-môn có thể thấy ngay trong hiện tại.”",
  "dn2:36.6": "“Này Đại vương, đó là kết quả thứ nhất của đời sống Sa-môn có thể thấy ngay trong hiện tại mà Ta đã trình bày.”",
  "dn2:37.0": "4.2. Kết quả thứ hai có thể thấy ngay trong hiện tại",
  "dn2:37.1": "“Bạch Thế Tôn, có thể trình bày thêm một kết quả khác của đời sống Sa-môn có thể thấy ngay trong hiện tại như vậy không?”",
  "dn2:37.2": "“Có thể, này Đại vương.",
  "dn2:37.3": "Vậy thì, này Đại vương, Ta sẽ hỏi lại Đại vương về chính vấn đề này. Đại vương thấy thế nào thì hãy trả lời như vậy.",
  "dn2:37.4": "Này Đại vương, Đại vương nghĩ sao:",
  "dn2:37.5": "Ở đây có một người là nông dân, gia chủ, người làm lụng, tích trữ của cải.",
  "dn2:37.6": "Người ấy nghĩ rằng:",
  "dn2:37.7": "‘Thật kỳ diệu thay, thật hi hữu thay là sự dẫn dắt của phước, là quả báo của phước.",
  "dn2:37.8": "Vị vua Ma-kiệt-đà Ajātasattu, con của bà Vedehī, cũng là con người; ta cũng là con người.",
  "dn2:37.9": "Vị vua Ma-kiệt-đà Ajātasattu ấy được đầy đủ và hưởng thụ năm loại dục lạc, như thể là một vị trời.",
  "dn2:37.10": "Còn ta lại là nông dân, gia chủ, người làm lụng, tích trữ của cải.",
  "dn2:37.11": "Ước gì ta có thể làm các việc phước thiện.",
  "dn2:37.12": "Hay là ta cạo bỏ râu tóc, khoác y ca-sa, rời bỏ gia đình, xuất gia sống đời không nhà?’",
  "dn2:37.13": "Sau một thời gian, người ấy từ bỏ ít hay nhiều tài sản, từ bỏ ít hay nhiều bà con quyến thuộc, cạo bỏ râu tóc, khoác y ca-sa, rời bỏ gia đình, xuất gia sống đời không nhà.",
  "dn2:37.14": "Sau khi xuất gia như vậy, người ấy sống chế ngự thân, chế ngự lời nói, chế ngự ý nghĩ; biết đủ với thức ăn và y phục; vui thích trong đời sống viễn ly.",
  "dn2:37.15": "Rồi có người tâu với Đại vương như sau:",
  "dn2:37.16": "‘Tâu Đại vương, xin Đại vương biết rằng người nông dân, gia chủ, người làm lụng, tích trữ của cải ấy,",
  "dn2:37.17": "nay đã cạo bỏ râu tóc, khoác y ca-sa, rời bỏ gia đình, xuất gia sống đời không nhà.",
  "dn2:37.18": "Sau khi xuất gia như vậy, người ấy sống chế ngự thân, chế ngự lời nói, chế ngự ý nghĩ; biết đủ với thức ăn và y phục; vui thích trong đời sống viễn ly.’",
  "dn2:37.19": "Này Đại vương, Đại vương có nói như thế này không:",
  "dn2:37.20": "‘Hãy gọi người ấy lại cho ta; để người ấy trở lại làm nông dân, gia chủ, người làm lụng, tích trữ của cải’?”",
  "dn2:38.1": "“Thưa không, bạch Thế Tôn.",
    "dn2:38.2": "“Trái lại, chính chúng con sẽ đảnh lễ người ấy, đứng dậy chào người ấy, mời người ấy ngồi, thỉnh người ấy nhận y áo, vật thực, chỗ ở, thuốc men khi bệnh; và còn sắp đặt sự che chở, bảo hộ đúng pháp cho người ấy.”",
  "dn2:38.3": "“Này Đại vương, Đại vương nghĩ sao?",
  "dn2:38.4": "Trong trường hợp như vậy, có phải là một kết quả của đời sống Sa-môn có thể thấy ngay trong hiện tại hay không?”",
  "dn2:38.5": "“Quả thật, bạch Thế Tôn, trong trường hợp như vậy là một kết quả của đời sống Sa-môn có thể thấy ngay trong hiện tại.”",
  "dn2:38.6": "“Này Đại vương, đó là kết quả thứ hai của đời sống Sa-môn có thể thấy ngay trong hiện tại mà Ta đã trình bày.”",
  "dn2:39.0": "4.3. Kết quả cao thượng hơn của đời sống Sa-môn",
  "dn2:39.1": "“Bạch Thế Tôn, có thể trình bày thêm một kết quả của đời sống Sa-môn có thể thấy ngay trong hiện tại, cao thượng và vi diệu hơn những kết quả đã nói không?”",
  "dn2:39.2": "“Có thể, này Đại vương.",
  "dn2:39.3": "Vậy thì, này Đại vương, hãy lắng nghe, khéo tác ý, Ta sẽ nói.”",
  "dn2:39.4": "“Vâng, bạch Thế Tôn.” Vua Ma-kiệt-đà Ajātasattu, con của bà Vedehī, đáp lời Thế Tôn.",
  "dn2:39.5": "Thế Tôn nói như sau:",
  "dn2:40.1": "“Này Đại vương, ở đây Như Lai xuất hiện ở đời: bậc A-la-hán, Chánh Đẳng Giác, đầy đủ minh và hạnh, Thiện Thệ, bậc hiểu rõ thế gian, bậc vô thượng điều ngự những người đáng được điều phục, thầy của chư thiên và loài người, Phật, Thế Tôn.",
  "dn2:40.2": "Ngài tự mình chứng ngộ với thắng trí và tuyên thuyết về thế giới này cùng với chư thiên, ma vương, Phạm thiên, cùng quần chúng gồm Sa-môn, Bà-la-môn, chư thiên và loài người.",
  "dn2:40.3": "Ngài thuyết Pháp có phần đầu tốt đẹp, phần giữa tốt đẹp, phần cuối tốt đẹp, đầy đủ ý nghĩa và văn tự, trình bày đời sống phạm hạnh hoàn toàn đầy đủ và thanh tịnh.",
  "dn2:41.1": "Người gia chủ, hoặc con của gia chủ, hoặc một người sinh trong gia đình nào khác, nghe Pháp ấy.",
  "dn2:41.2": "Sau khi nghe Pháp ấy, vị ấy khởi lòng tin nơi Như Lai.",
  "dn2:41.3": "Được đầy đủ lòng tin ấy, vị ấy suy nghĩ:",
  "dn2:41.4": "‘Đời sống tại gia chật hẹp, là con đường bụi bặm; xuất gia là không gian rộng mở.",
  "dn2:41.5": "Thật không dễ cho người sống tại gia có thể sống đời phạm hạnh hoàn toàn đầy đủ, hoàn toàn thanh tịnh, trọn vẹn như vỏ ốc được đánh bóng.",
  "dn2:41.6": "Vậy ta hãy cạo bỏ râu tóc, khoác áo ca-sa, từ bỏ gia đình, sống đời không gia đình.’",
  "dn2:41.7": "Sau một thời gian, vị ấy từ bỏ ít hay nhiều tài sản, từ bỏ ít hay nhiều bà con thân thuộc, cạo bỏ râu tóc, khoác áo ca-sa, từ bỏ gia đình, sống đời không gia đình.",
  "dn2:42.1": "Sau khi xuất gia như vậy, vị ấy sống được chế ngự bởi sự phòng hộ theo giới bổn (Pātimokkha), đầy đủ oai nghi và hạnh kiểm, thấy sợ hãi trong những lỗi nhỏ nhặt; chấp nhận và tu học các học giới; đầy đủ thân hành và khẩu hành thiện lành; nuôi mạng thanh tịnh; thành tựu giới hạnh; phòng hộ các căn; đầy đủ chánh niệm và tỉnh giác; biết đủ.”",
  "dn2:43.0.1": "4.3.1. Giới",
  "dn2:43.0.2": "4.3.1.1. Tiểu giới",
  "dn2:43.1": "Thế nào, này Đại vương, Tỳ-kheo thành tựu giới hạnh?",
  "dn2:43.2": "Ở đây, này Đại vương, Tỳ-kheo từ bỏ sát sinh, sống tránh xa sát sinh; bỏ gậy, bỏ kiếm; biết hổ thẹn, có lòng từ; sống thương tưởng và lợi ích cho tất cả chúng sinh.",
  "dn2:43.3": "Đây là một phần giới của vị ấy.",
  "dn2:43.4": "Từ bỏ lấy của không cho, sống tránh xa lấy của không cho; chỉ nhận những gì được cho, mong đợi những gì được cho; sống thanh tịnh, không trộm cắp.",
  "dn2:43.5": "Đây là một phần giới của vị ấy.",
  "dn2:43.6": "Từ bỏ đời sống không phạm hạnh, sống đời phạm hạnh; sống ly dục, tránh xa hành vi dâm dục thế tục.",
  "dn2:43.7": "Đây là một phần giới của vị ấy.",
  "dn2:44.1": "Từ bỏ nói dối, sống tránh xa nói dối; nói lời chân thật, giữ vững sự thật, đáng tin cậy, không lừa dối đời.",
  "dn2:44.2": "Đây là một phần giới của vị ấy.",
  "dn2:44.3": "Từ bỏ nói hai lưỡi, sống tránh xa nói hai lưỡi; nghe chuyện ở đây không đem nói nơi kia để gây chia rẽ, nghe chuyện nơi kia không đem nói ở đây để gây chia rẽ; là người hòa giải những ai chia rẽ, củng cố những ai hòa hợp; ưa thích hòa hợp, vui thích hòa hợp, hoan hỷ trong hòa hợp; nói lời đưa đến hòa hợp.",
  "dn2:44.4": "Đây là một phần giới của vị ấy.",
  "dn2:44.5": "Từ bỏ lời nói thô ác, vị ấy sống tránh xa lời nói thô ác; chỉ nói những lời hiền hòa, êm dịu, dễ nghe, khả ái, đi vào lòng người, nhã nhặn, được nhiều người ưa thích và hoan hỷ.",
  "dn2:44.6": "Đây là một phần giới của vị ấy.",
  "dn2:44.7": "Từ bỏ nói chuyện phù phiếm, vị ấy sống tránh xa nói chuyện phù phiếm; nói đúng thời, nói sự thật, nói điều lợi ích, nói về Pháp, nói về Luật; nói lời có giá trị, đúng lúc, có căn cứ, có giới hạn, đem lại lợi ích.",
  "dn2:44.8": "Đây là một phần giới của vị ấy.",
  "dn2:45.1": "Vị ấy tránh xa việc làm tổn hại các loại hạt giống và cây cỏ.",
  "dn2:45.2": "Vị ấy chỉ ăn một bữa trong ngày, không ăn ban đêm, tránh xa ăn phi thời.",
  "dn2:45.3": "Vị ấy tránh xa múa, hát, nhạc và các trò giải trí.",
  "dn2:45.4": "Vị ấy tránh xa đeo vòng hoa, dùng hương thơm, phấn sáp, trang điểm và làm đẹp thân thể.",
  "dn2:45.5": "Vị ấy tránh xa giường cao, giường lớn, chỗ nằm sang trọng.",
  "dn2:45.6": "Vị ấy tránh xa nhận vàng bạc.",
  "dn2:45.7": "Vị ấy tránh xa nhận lúa gạo còn sống.",
  "dn2:45.8": "Vị ấy tránh xa nhận thịt sống.",
  "dn2:45.9": "Vị ấy tránh xa nhận phụ nữ và thiếu nữ.",
  "dn2:45.10": "Vị ấy tránh xa nhận nô tỳ và nô lệ.",
   "dn2:45.11": "Vị ấy tránh xa việc nhận dê và cừu.",
  "dn2:45.12": "Vị ấy tránh xa việc nhận gà và heo.",
  "dn2:45.13": "Vị ấy tránh xa việc nhận voi, bò, ngựa và la.",
  "dn2:45.14": "Vị ấy tránh xa việc nhận ruộng đất và tài sản.",
  "dn2:45.15": "Vị ấy tránh xa việc làm sứ giả, môi giới hay đưa tin.",
  "dn2:45.16": "Vị ấy tránh xa mua bán.",
  "dn2:45.17": "Vị ấy tránh xa gian lận về cân, đo và đong.",
  "dn2:45.18": "Vị ấy tránh xa hối lộ, lừa dối, gian trá và mánh khóe.",
  "dn2:45.19": "Vị ấy tránh xa chém giết, sát hại, trói buộc, cướp đoạt và dùng bạo lực.",
  "dn2:45.20": "Đây là một phần giới của vị ấy.",
  "dn2:45.21": "Phần Tiểu Giới (Cūḷasīla) kết thúc.",
    "dn2:46.0": "4.3.1.2. Trung Giới (Majjhimasīla)",
  "dn2:46.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi lại dấn thân vào việc gieo trồng các loại hạt giống và cây cỏ.",
  "dn2:46.2": "Như là: hạt từ rễ, hạt từ thân, hạt từ nhánh, hạt từ ngọn, và các loại hạt nói chung; vị ấy tránh xa các việc làm liên hệ đến hạt giống và cây cỏ như vậy.",
  "dn2:46.3": "Đây là một phần giới của vị ấy.",
  "dn2:47.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi lại dấn thân vào việc tích trữ và sử dụng của cải.",
  "dn2:47.2": "Như là: tích trữ thức ăn, đồ uống, y phục, xe cộ, chỗ nằm, hương liệu, thực phẩm.",
  "dn2:47.3": "Vị ấy tránh xa các việc tích trữ và sử dụng như vậy.",
  "dn2:47.4": "Đây là một phần giới của vị ấy.",
  "dn2:48.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi lại dấn thân vào việc xem các trò giải trí.",
  "dn2:48.2": "Như là: múa, hát, nhạc, kịch, kể chuyện, diễn trò, nhào lộn, biểu diễn, đánh trống, thổi sáo, đấu voi, đấu ngựa, đấu trâu, đấu bò, đấu dê, đấu cừu, đấu gà, đấu chim, đánh gậy, đấu vật, duyệt binh, xem quân đội bày trận, xem chiến trận…",
  "dn2:48.3": "Vị ấy tránh xa các việc xem những trò giải trí như vậy.",
  "dn2:48.4": "Đây là một phần giới của vị ấy.",
  "dn2:49.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi lại dấn thân vào các trò chơi cờ bạc, giải trí phóng dật.",
  "dn2:49.2": "Như là: các loại cờ bàn, trò chơi trên bảng, trò xúc xắc, trò nhảy ô, trò tung que, trò tính điểm, trò bắn cung nhỏ, trò đoán chữ, trò tính nhẩm và các trò tương tự.",
  "dn2:49.3": "Vị ấy tránh xa các trò chơi cờ bạc và phóng dật như vậy.",
  "dn2:49.4": "Đây là một phần giới của vị ấy.",
  "dn2:50.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi lại dấn thân vào việc dùng giường cao, giường lớn.",
  "dn2:50.2": "Như là: ghế dài, giường sang trọng, nệm len, nệm thêu, nệm lông, nệm nhiều lớp, nệm bọc da thú, thảm trải giường có mái che, gối đỏ hai đầu…",
  "dn2:50.3": "Vị ấy tránh xa các loại giường cao, giường lớn như vậy.",
  "dn2:50.4": "Đây là một phần giới của vị ấy.",
  "dn2:51.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi lại dấn thân vào việc trang điểm và làm đẹp.",
  "dn2:51.2": "Như là: xoa bóp, tắm rửa, chải chuốt, soi gương, trang điểm mắt, dùng vòng hoa, hương thơm, phấn son, trang sức tay, cài tóc, cầm gậy, mang ống đựng, mang kiếm, mang dù, mang giày đẹp, đội khăn, đeo ngọc, quạt lông, mặc y phục trắng có tua dài…",
  "dn2:51.3": "Vị ấy tránh xa các việc trang điểm và làm đẹp như vậy.",
  "dn2:51.4": "Đây là một phần giới của vị ấy.",
  "dn2:52.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi lại dấn thân vào những câu chuyện tầm thường, vô ích.",
  "dn2:52.2": "Như là: chuyện vua chúa, chuyện trộm cướp, chuyện quan lại, chuyện quân đội, chuyện sợ hãi, chuyện chiến tranh, chuyện ăn uống, chuyện y phục, chuyện giường chiếu, chuyện vòng hoa, chuyện hương liệu, chuyện bà con, chuyện xe cộ, chuyện làng xóm, thị trấn, thành phố, quốc độ, chuyện phụ nữ, chuyện anh hùng, chuyện ngoài đường, chuyện bến nước, chuyện người đã chết, chuyện tạp nhạp, chuyện về thế gian, chuyện biển cả, chuyện có – không trong đời…",
  "dn2:52.3": "Vị ấy tránh xa những câu chuyện tầm thường như vậy.",
  "dn2:52.4": "Đây là một phần giới của vị ấy.",
  "dn2:53.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi lại dấn thân vào những cuộc tranh luận hơn thua.",
  "dn2:53.2": "Như là: “Ngươi không hiểu Pháp và Luật này, ta mới hiểu; làm sao ngươi hiểu được; ngươi thực hành sai, ta thực hành đúng; lời ta hợp lý, lời ngươi không hợp; điều nên nói trước ngươi lại nói sau; điều nên nói sau ngươi lại nói trước; lập luận của ngươi đã bị đảo lộn; ngươi đã bị bắt bẻ; ngươi đã bị thua; hãy tự gỡ rối nếu có thể”…",
  "dn2:53.3": "Vị ấy tránh xa những cuộc tranh luận hơn thua như vậy.",
  "dn2:53.4": "Đây là một phần giới của vị ấy.",
  "dn2:54.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi lại dấn thân vào việc làm sứ giả, môi giới, đưa tin.",
  "dn2:54.2": "Như là: đi thay cho vua, đại thần, chiến sĩ, bà-la-môn, gia chủ, hoàng tử—‘hãy đi đến đây, hãy đến kia, hãy mang cái này, hãy đem cái kia về’…",
  "dn2:54.3": "Vị ấy tránh xa những việc làm sứ giả, môi giới như vậy.",
  "dn2:54.4": "Đây là một phần giới của vị ấy.",
  "dn2:55.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi lại gian xảo, khéo nói để cầu lợi, xem tướng, nịnh bợ, mưu cầu lợi này để được lợi khác; vị ấy tránh xa những sự gian trá và khéo léo cầu lợi như vậy.",
  "dn2:55.2": "Đây là một phần giới của vị ấy.",
  "dn2:55.3": "Phần Trung Giới (Majjhimasīla) kết thúc.",
   "dn2:56.0": "4.3.1.3. Đại Giới (Mahāsīla)",
  "dn2:56.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi sống bằng tà mạng, hành nghề các loại thuật thế gian.",
  "dn2:56.2": "Như là: xem tướng thân, đoán điềm, giải mộng, xem dấu hiệu, đoán điềm chuột cắn, cúng lửa bằng các loại vật liệu khác nhau, xem chi thể, xem đất đai, xem binh pháp, cầu thần linh, gọi hồn, làm bùa chú, bắt rắn, giải độc, trừ bò cạp, trừ chuột, xem chim, xem quạ, đoán hướng bay, hộ thân bằng chú, bùa tên, vòng bẫy thú…",
  "dn2:56.3": "Vị ấy tránh xa việc sống bằng các nghề tà mạng và thuật thế gian như vậy.",
  "dn2:56.4": "Đây là một phần giới của vị ấy.",
  "dn2:57.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi sống bằng tà mạng, hành nghề các loại thuật thế gian.",
  "dn2:57.2": "Như là: xem tướng ngọc, tướng y phục, tướng gậy, tướng vũ khí, tướng kiếm, tướng tên, tướng cung, tướng binh khí, tướng phụ nữ, tướng đàn ông, tướng thiếu niên, tướng thiếu nữ, tướng nô lệ nam, nô lệ nữ, tướng voi, ngựa, trâu, bò, dê, cừu, gà, chim, kỳ đà, rùa, thú rừng…",
  "dn2:57.3": "Vị ấy tránh xa việc sống bằng các nghề tà mạng và thuật thế gian như vậy.",
  "dn2:57.4": "Đây là một phần giới của vị ấy.",
  "dn2:58.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi sống bằng tà mạng, hành nghề các loại thuật thế gian.",
  "dn2:58.2": "Như là: đoán vua sẽ xuất chinh hay không xuất chinh; vua trong nước sẽ tiến hay lui; vua ngoài nước sẽ tiến hay lui; vua này thắng, vua kia bại…",
  "dn2:58.3": "Vị ấy tránh xa việc sống bằng các nghề tà mạng và thuật thế gian như vậy.",
  "dn2:58.4": "Đây là một phần giới của vị ấy.",
  "dn2:59.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi sống bằng tà mạng, hành nghề các loại thuật thế gian.",
  "dn2:59.2": "Như là: đoán nguyệt thực, nhật thực, sao bị che; sự vận hành đúng hay lệch của mặt trăng, mặt trời và các vì sao; sao băng; lửa cháy phương trời; động đất; sấm trời; sự xuất hiện, biến mất, ô nhiễm hay trong sáng của mặt trăng, mặt trời, các vì sao; và đoán các hậu quả của những hiện tượng ấy…",
  "dn2:59.3": "Vị ấy tránh xa việc sống bằng các nghề tà mạng và thuật thế gian như vậy.",
  "dn2:59.4": "Đây là một phần giới của vị ấy.",
  "dn2:60.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi sống bằng tà mạng, hành nghề các loại thuật thế gian.",
  "dn2:60.2": "Như là: đoán sẽ mưa nhiều hay ít, được mùa hay mất mùa, an ổn hay hiểm nguy, bệnh tật hay khỏe mạnh; làm ấn chú, tính toán, suy đoán, làm thơ, luận thuyết thế tục (lokāyata)…",
  "dn2:60.3": "Vị ấy tránh xa việc sống bằng các nghề tà mạng và thuật thế gian như vậy.",
  "dn2:60.4": "Đây là một phần giới của vị ấy.",
  "dn2:61.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi sống bằng tà mạng, hành nghề các loại thuật thế gian.",
  "dn2:61.2": "Như là: làm bùa gọi, bùa giải, bùa trói, bùa mở, làm cho hợp, làm cho tan, làm cho được yêu mến, làm cho bị ghét bỏ, làm cho sẩy thai, đọc chú trói lưỡi, khóa hàm, đọc chú vào tay, vào hàm, vào tai; hỏi gương, hỏi thiếu nữ, hỏi chư thiên; thờ mặt trời, thờ thần lớn; cúng lửa, cầu phúc…",
  "dn2:61.3": "Vị ấy tránh xa việc sống bằng các nghề tà mạng và thuật thế gian như vậy.",
  "dn2:61.4": "Đây là một phần giới của vị ấy.",
  "dn2:62.1": "Cũng như có những sa-môn, bà-la-môn khác thọ dụng các món ăn do tín thí cúng dường rồi sống bằng tà mạng, hành nghề các loại thuật thế gian.",
  "dn2:62.2": "Như là: làm phép an lành, phát nguyện, trừ tà, cầu phúc, cầu mưa, cầu hết mưa; xem đất, làm lễ trên đất; súc miệng, tắm rửa nghi lễ, cúng tế; gây nôn, tẩy xổ, trị bệnh phần trên, phần dưới, tẩy đầu; nhỏ tai, nhỏ mắt, nhỏ mũi; bôi thuốc; châm cứu; giải phẫu; chữa bệnh trẻ em; cho thuốc từ rễ cây; bào chế dược liệu…",
  "dn2:62.3": "Vị ấy tránh xa việc sống bằng các nghề tà mạng và thuật thế gian như vậy.",
  "dn2:62.4": "Đây là một phần giới của vị ấy.",
  "dn2:63.1": "Này Đại vương, vị Tỳ-kheo thành tựu giới như vậy không thấy có gì phải sợ hãi từ bất cứ phương diện nào do sự phòng hộ giới.",
  "dn2:63.2": "Cũng như, này Đại vương, một vị vua thuộc dòng Sát-đế-lỵ đã được quán đảnh, đã dẹp yên kẻ thù, không còn sợ hãi từ phía địch thủ;",
  "dn2:63.3": "cũng vậy, này Đại vương, vị Tỳ-kheo thành tựu giới như vậy không thấy có gì phải sợ hãi do sự phòng hộ giới.",
  "dn2:63.4": "Vị ấy, nhờ thành tựu uẩn giới cao quý này, cảm thọ niềm an lạc nội tâm không lỗi lầm.",
  "dn2:63.5": "Như vậy, này Đại vương, vị Tỳ-kheo là người thành tựu giới.",
  "dn2:63.6": "Phần Đại Giới (Mahāsīla) kết thúc.",
   "dn2:64.0.1": "4.3.2. Định",
  "dn2:64.0.2": "4.3.2.1. Phòng hộ các căn",
  "dn2:64.1": "Và này Đại vương, thế nào là vị Tỳ-kheo phòng hộ các căn?",
  "dn2:64.2": "Ở đây, này Đại vương, vị Tỳ-kheo khi mắt thấy sắc, không nắm giữ tướng chung, không nắm giữ tướng riêng.",
  "dn2:64.3": "Vì nếu sống không phòng hộ căn mắt, thì tham ái, ưu phiền cùng các pháp ác, bất thiện có thể xâm nhập; nên vị ấy thực hành để phòng hộ, giữ gìn căn mắt, thành tựu sự phòng hộ nơi căn mắt.",
  "dn2:64.4": "Khi tai nghe tiếng…",
  "dn2:64.5": "khi mũi ngửi hương…",
  "dn2:64.6": "khi lưỡi nếm vị…",
  "dn2:64.7": "khi thân xúc chạm…",
  "dn2:64.8": "khi ý nhận biết pháp, không nắm giữ tướng chung, không nắm giữ tướng riêng.",
  "dn2:64.9": "Vì nếu sống không phòng hộ căn ý, thì tham ái, ưu phiền cùng các pháp ác, bất thiện có thể xâm nhập; nên vị ấy thực hành để phòng hộ, giữ gìn căn ý, thành tựu sự phòng hộ nơi căn ý.",
  "dn2:64.10": "Thành tựu sự phòng hộ cao quý này nơi các căn, vị ấy cảm thọ niềm an lạc nội tâm không bị nhiễm ô.",
  "dn2:64.11": "Như vậy, này Đại vương, vị Tỳ-kheo là người phòng hộ các căn.",
    "dn2:65.0": "4.3.2.2. Chánh niệm và tỉnh giác",
  "dn2:65.1": "Và này Đại vương, thế nào là vị Tỳ-kheo thành tựu chánh niệm và tỉnh giác?",
  "dn2:65.2": "Ở đây, này Đại vương, vị Tỳ-kheo khi đi tới hay đi lui đều tỉnh giác; khi nhìn thẳng hay nhìn quanh đều tỉnh giác; khi co tay duỗi tay đều tỉnh giác; khi mang y, cầm bát và mặc y đều tỉnh giác; khi ăn, uống, nhai, nếm đều tỉnh giác; khi đại tiện, tiểu tiện đều tỉnh giác; khi đi, đứng, ngồi, nằm, thức, nói và im lặng đều tỉnh giác.",
  "dn2:65.3": "Như vậy, này Đại vương, vị Tỳ-kheo thành tựu chánh niệm và tỉnh giác.",
  "dn2:66.0": "4.3.2.3. Biết đủ",
  "dn2:66.1": "Và này Đại vương, thế nào là vị Tỳ-kheo biết đủ?",
  "dn2:66.2": "Ở đây, này Đại vương, vị Tỳ-kheo biết đủ với y phục chỉ để che thân và với vật thực chỉ để nuôi bụng. Đi đến đâu, vị ấy chỉ mang theo những vật cần thiết ấy.",
  "dn2:66.3": "Ví như, này Đại vương, chim bay đến đâu cũng chỉ mang theo đôi cánh của mình;",
  "dn2:66.4": "cũng vậy, này Đại vương, vị Tỳ-kheo biết đủ với y phục để che thân và vật thực để nuôi bụng. Đi đến đâu, vị ấy chỉ mang theo những vật cần thiết ấy.",
  "dn2:66.5": "Như vậy, này Đại vương, vị Tỳ-kheo là người biết đủ.",
  "dn2:67.0": "4.3.2.4. Đoạn trừ năm chướng ngại",
  "dn2:67.1": "Vị ấy, này Đại vương, đã thành tựu giới cao quý, đã thành tựu phòng hộ các căn, đã thành tựu chánh niệm và tỉnh giác, đã thành tựu sự biết đủ cao quý ấy,",
  "dn2:67.2": "liền chọn trú xứ vắng vẻ: rừng, gốc cây, núi, hang núi, động đá, bãi tha ma, rừng sâu, khoảng đất trống, hay đống rơm.",
  "dn2:67.3": "Sau khi đi khất thực và dùng bữa xong, vị ấy ngồi kiết già, lưng thẳng, an trú chánh niệm trước mặt.",
  "dn2:68.1": "Vị ấy đoạn trừ tham dục đối với đời, sống với tâm không tham, và làm cho tâm được thanh tịnh khỏi tham dục.",
  "dn2:68.2": "Đoạn trừ sân hận và ác ý, sống với tâm không sân, đầy lòng từ đối với tất cả chúng sinh, và làm cho tâm được thanh tịnh khỏi sân hận và ác ý.",
  "dn2:68.3": "Đoạn trừ hôn trầm và buồn ngủ, sống không hôn trầm, hướng tâm đến ánh sáng, có chánh niệm và tỉnh giác, và làm cho tâm được thanh tịnh khỏi hôn trầm và buồn ngủ.",
  "dn2:68.4": "Đoạn trừ trạo cử và hối hận, sống không dao động, nội tâm an tịnh, và làm cho tâm được thanh tịnh khỏi trạo cử và hối hận.",
  "dn2:68.5": "Đoạn trừ nghi ngờ, vượt qua hoài nghi, không còn phân vân đối với các pháp thiện, và làm cho tâm được thanh tịnh khỏi nghi ngờ.",
  "dn2:69.1": "Ví như, này Đại vương, một người vay nợ để làm ăn.",
  "dn2:69.2": "Công việc của người ấy thành công.",
  "dn2:69.3": "Người ấy trả hết nợ cũ, lại còn dư tiền để nuôi vợ con.",
  "dn2:69.4": "Người ấy nghĩ rằng:",
  "dn2:69.5": "‘Trước đây ta vay nợ để làm ăn.",
  "dn2:69.6": "Nay công việc của ta đã thành tựu.",
  "dn2:69.7": "Ta đã trả hết các món nợ cũ, lại còn dư để nuôi vợ con.’",
  "dn2:69.8": "Do nhân ấy, người ấy khởi lên hoan hỷ và đạt được niềm vui.",
  "dn2:70.1": "Ví như, này Đại vương, một người bị bệnh, đau đớn, bệnh nặng; ăn uống không tiêu, thân thể không có sức lực.",
  "dn2:70.2": "Sau một thời gian, người ấy khỏi bệnh; ăn uống tiêu hóa được và thân thể có sức lực.",
  "dn2:70.3": "Người ấy nghĩ rằng:",
  "dn2:70.4": "‘Trước đây ta bị bệnh, đau đớn, bệnh nặng;",
  "dn2:70.5": "ăn uống không tiêu, thân thể không có sức lực.",
  "dn2:70.6": "Nay ta đã khỏi bệnh;",
  "dn2:70.7": "ăn uống tiêu hóa được và thân thể có sức lực.’",
  "dn2:70.8": "Do nhân ấy, người ấy khởi lên hoan hỷ và đạt được niềm vui.",
  "dn2:71.1": "Ví như, này Đại vương, một người bị giam trong ngục.",
  "dn2:71.2": "Sau một thời gian, người ấy được thoát khỏi ngục tù, an toàn, không sợ hãi, và không mất mát tài sản gì.",
  "dn2:71.3": "Người ấy nghĩ rằng:",
  "dn2:71.4": "‘Trước đây ta bị giam trong ngục, nay ta đã được thoát khỏi ngục tù, an toàn, không sợ hãi.",
  "dn2:71.5": "Ta không mất mát tài sản gì.’",
  "dn2:71.6": "Do nhân ấy, người ấy khởi lên hoan hỷ và đạt được niềm vui.",
  "dn2:72.1": "Ví như, này Đại vương, một người là nô lệ, không tự chủ, lệ thuộc người khác, không được tự do đi lại.",
  "dn2:72.2": "Sau một thời gian, người ấy được giải thoát khỏi thân phận nô lệ, trở thành người tự chủ, không lệ thuộc, được tự do đi lại.",
  "dn2:72.3": "Người ấy nghĩ rằng:",
  "dn2:72.4": "‘Trước đây ta là nô lệ, không tự chủ, lệ thuộc người khác, không được tự do đi lại.",
  "dn2:72.5": "Nay ta đã thoát khỏi thân phận nô lệ, tự chủ, không lệ thuộc, được tự do đi lại.’",
  "dn2:72.6": "Do nhân ấy, người ấy khởi lên hoan hỷ và đạt được niềm vui.",
  "dn2:73.1": "Ví như, này Đại vương, một người giàu có, đầy đủ tài sản, đi qua con đường hoang mạc đầy đói khát và hiểm nguy.",
  "dn2:73.2": "Sau một thời gian, người ấy vượt qua được hoang mạc ấy, đến nơi làng mạc an toàn, không còn hiểm nguy.",
  "dn2:73.3": "Người ấy nghĩ rằng:",
  "dn2:73.4": "‘Trước đây ta là người giàu có, đầy đủ tài sản, đã đi vào con đường hoang mạc đầy đói khát và hiểm nguy.",
  "dn2:73.5": "Nay ta đã vượt qua hoang mạc ấy an toàn, đến được làng mạc yên ổn, không còn hiểm nguy.’",
  "dn2:73.6": "Do nhân ấy, người ấy khởi lên hoan hỷ và đạt được niềm vui.",
  "dn2:74.1": "Cũng vậy, này Đại vương, vị Tỳ-kheo khi năm triền cái chưa được đoạn trừ thì tự thấy chúng trong mình như là nợ nần, như bệnh tật, như ngục tù, như thân phận nô lệ, như con đường hoang mạc hiểm nguy.",
  "dn2:74.2": "Và như không nợ nần, như khỏe mạnh, như được giải thoát khỏi ngục tù, như người tự do, như vùng đất an ổn;",
  "dn2:74.3": "cũng vậy, này Đại vương, khi năm triền cái đã được đoạn trừ, vị Tỳ-kheo tự thấy chúng đã được đoạn trừ trong mình.",
  "dn2:74.4": "Khi thấy năm triền cái đã được đoạn trừ nơi mình, hoan hỷ sinh khởi; do hoan hỷ nên hỷ lạc sinh; tâm có hỷ thì thân được an tịnh; thân an tịnh cảm thọ lạc; người có lạc thì tâm được định.",
  "dn2:75.0": "4.3.2.5. Sơ thiền",
  "dn2:75.1": "Vị ấy, ly dục, ly các pháp bất thiện, chứng và an trú Sơ thiền, có tầm có tứ, hỷ lạc do ly dục sinh.",
  "dn2:75.2": "Vị ấy thấm nhuần, tẩm ướt, làm tràn đầy và bao phủ thân này bằng hỷ lạc do ly dục sinh, không một chỗ nào trong toàn thân không được hỷ lạc ấy thấm đến.",
  "dn2:76.1": "Ví như, này Đại vương, một người thợ tắm khéo léo hay đệ tử thợ tắm, đổ bột tắm vào chậu đồng rồi rưới nước vào, nhào trộn cho đến khi viên bột tắm thấm nước từ trong ra ngoài, đầy đủ ẩm nhuận mà không chảy nhỏ giọt;",
  "dn2:76.2": "cũng vậy, này Đại vương, vị Tỳ-kheo thấm nhuần, tẩm ướt, làm tràn đầy và bao phủ thân này bằng hỷ lạc do ly dục sinh, không một chỗ nào trong toàn thân không được hỷ lạc ấy thấm đến.",
  "dn2:76.3": "Đây cũng là quả của đời sống xuất gia có thể thấy ngay trong hiện tại, thù thắng và cao quý hơn các quả trước.",
  "dn2:77.0": "4.3.2.6. Nhị thiền",
  "dn2:77.1": "Lại nữa, này Đại vương, vị Tỳ-kheo do lắng dịu tầm và tứ, đạt đến nội tịnh, nhất tâm, không tầm không tứ, hỷ lạc do định sinh, chứng và an trú Nhị thiền.",
  "dn2:77.2": "Vị ấy thấm nhuần, tẩm ướt, làm tràn đầy và bao phủ thân này bằng hỷ lạc do định sinh, không một chỗ nào trong toàn thân không được hỷ lạc ấy thấm đến.",
  "dn2:78.1": "Ví như, này Đại vương, một hồ nước sâu, nước từ trong lòng đất vọt lên; không có dòng nước chảy vào từ phương đông, tây, nam hay bắc, và mưa cũng không đổ xuống đều đặn;",
  "dn2:78.2": "nhưng từ chính hồ ấy, dòng nước mát phun lên, làm thấm nhuần, tràn đầy và bao phủ toàn hồ bằng nước mát, không một chỗ nào trong hồ không được nước mát thấm đến;",
  "dn2:78.3": "cũng vậy, này Đại vương, vị Tỳ-kheo thấm nhuần, tẩm ướt, làm tràn đầy và bao phủ thân này bằng hỷ lạc do định sinh, không một chỗ nào trong toàn thân không được hỷ lạc ấy thấm đến.",
  "dn2:78.4": "Đây cũng là quả của đời sống xuất gia có thể thấy ngay trong hiện tại, thù thắng và cao quý hơn các quả trước.",
   "dn2:79.0": "4.3.2.7. Tam thiền",
  "dn2:79.1": "Lại nữa, này Đại vương, vị Tỳ-kheo do ly hỷ, an trú xả, có chánh niệm và tỉnh giác, cảm thọ lạc nơi thân — điều mà các bậc Thánh nói: ‘Vị ấy xả, chánh niệm, an trú lạc’ — chứng và an trú Tam thiền.",
  "dn2:79.2": "Vị ấy thấm nhuần, tẩm ướt, làm tràn đầy và bao phủ thân này bằng lạc không còn hỷ, không một chỗ nào trong toàn thân không được lạc ấy thấm đến.",
  "dn2:80.1": "Ví như, này Đại vương, trong hồ sen xanh, sen hồng hay sen trắng, có những hoa sen sinh trong nước, lớn lên trong nước, chìm ngập trong nước và được nuôi dưỡng từ trong nước; từ gốc đến ngọn, chúng được nước mát thấm nhuần, tràn đầy và bao phủ, không chỗ nào của hoa sen không được nước mát thấm đến;",
  "dn2:80.2": "cũng vậy, này Đại vương, vị Tỳ-kheo thấm nhuần, tẩm ướt, làm tràn đầy và bao phủ thân này bằng lạc không còn hỷ, không một chỗ nào trong toàn thân không được lạc ấy thấm đến.",
  "dn2:80.3": "Đây cũng là quả của đời sống xuất gia có thể thấy ngay trong hiện tại, thù thắng và cao quý hơn các quả trước.",
  "dn2:81.0": "4.3.2.8. Tứ thiền",
  "dn2:81.1": "Lại nữa, này Đại vương, vị Tỳ-kheo do đoạn trừ lạc và đoạn trừ khổ, do trước đó hỷ và ưu đã chấm dứt, chứng và an trú Tứ thiền, không khổ không lạc, với xả niệm thanh tịnh.",
  "dn2:81.2": "Vị ấy ngồi thấm nhuần toàn thân này bằng tâm thanh tịnh và trong sáng, không một chỗ nào trong toàn thân không được tâm thanh tịnh và trong sáng ấy bao phủ.",
  "dn2:82.1": "Ví như, này Đại vương, một người ngồi trùm kín thân mình bằng tấm vải trắng từ đầu đến chân, không chỗ nào trong toàn thân không được vải trắng bao phủ;",
  "dn2:82.2": "cũng vậy, này Đại vương, vị Tỳ-kheo ngồi thấm nhuần toàn thân này bằng tâm thanh tịnh và trong sáng, không một chỗ nào trong toàn thân không được tâm thanh tịnh và trong sáng ấy bao phủ.",
  "dn2:82.3": "Đây cũng là quả của đời sống xuất gia có thể thấy ngay trong hiện tại, thù thắng và cao quý hơn các quả trước.",
   "dn2:83.0.1": "4.3.3. Tám loại trí",
  "dn2:83.0.2": "4.3.3.1. Trí tuệ quán sát",
  "dn2:83.1": "Khi tâm đã được định như vậy, thanh tịnh, trong sáng, không cấu uế, không nhiễm ô, nhu nhuyến, dễ sử dụng, vững chắc và bất động, vị ấy hướng tâm, nghiêng tâm đến trí và sự thấy biết.",
  "dn2:83.2": "Vị ấy biết như thật:",
  "dn2:83.3": "‘Thân này của ta là sắc, do bốn đại tạo thành, do cha mẹ sinh ra, được nuôi lớn bằng cơm cháo, có tính chất vô thường, phải được che đậy, xoa bóp, rồi sẽ tan rã và hoại diệt;",
  "dn2:83.4": "còn thức này của ta thì nương nơi đây, gắn liền nơi đây.’",
  "dn2:84.1": "Ví như, này Đại vương, một viên ngọc lưu ly đẹp, thuần tịnh, có tám cạnh, được mài giũa khéo léo, trong suốt, sáng sạch, không vẩn đục, đầy đủ mọi vẻ hoàn hảo.",
  "dn2:84.2": "Trong đó có xỏ một sợi chỉ màu xanh, hoặc vàng, hoặc đỏ, hoặc trắng, hoặc màu vàng nhạt.",
  "dn2:84.3": "Một người có mắt sáng cầm viên ngọc ấy trên tay và quan sát:",
  "dn2:84.4": "‘Đây là viên ngọc lưu ly đẹp, thuần tịnh, có tám cạnh, được mài giũa khéo léo, trong suốt, sáng sạch, không vẩn đục, đầy đủ mọi vẻ hoàn hảo;",
  "dn2:84.5": "và trong đó có xỏ sợi chỉ màu xanh, hoặc vàng, hoặc đỏ, hoặc trắng, hoặc vàng nhạt.’",
  "dn2:84.6": "Cũng vậy, này Đại vương, khi tâm đã được định như vậy, thanh tịnh, trong sáng, không cấu uế, không nhiễm ô, nhu nhuyến, dễ sử dụng, vững chắc và bất động, vị Tỳ-kheo hướng tâm, nghiêng tâm đến trí và sự thấy biết.",
  "dn2:84.7": "Vị ấy biết như thật:",
  "dn2:84.8": "‘Thân này của ta là sắc, do bốn đại tạo thành, do cha mẹ sinh ra, được nuôi lớn bằng cơm cháo, có tính chất vô thường, phải được che đậy, xoa bóp, rồi sẽ tan rã và hoại diệt;",
  "dn2:84.9": "còn thức này của ta thì nương nơi đây, gắn liền nơi đây.’",
  "dn2:84.10": "Đây cũng là quả của đời sống xuất gia có thể thấy ngay trong hiện tại, thù thắng và cao quý hơn các quả trước.",
   "dn2:85.0": "4.3.3.2. Trí về thần thông thân do ý tạo",
  "dn2:85.1": "Khi tâm đã được định như vậy, thanh tịnh, trong sáng, không cấu uế, không nhiễm ô, nhu nhuyến, dễ sử dụng, vững chắc và bất động, vị ấy hướng tâm, nghiêng tâm đến việc tạo ra một thân do ý tạo.",
  "dn2:85.2": "Vị ấy từ thân này tạo ra một thân khác có sắc, do ý tạo, đầy đủ các chi phần, không thiếu căn nào.",
  "dn2:86.1": "Ví như, này Đại vương, một người rút lõi cỏ ra khỏi bẹ cỏ.",
  "dn2:86.2": "Người ấy nghĩ rằng:",
  "dn2:86.3": "‘Đây là bẹ cỏ, đây là lõi cỏ; bẹ cỏ là một, lõi cỏ là một; chính từ bẹ cỏ mà lõi cỏ được rút ra.’",
  "dn2:86.4": "Hoặc như, này Đại vương, một người rút thanh kiếm ra khỏi vỏ.",
  "dn2:86.5": "Người ấy nghĩ rằng:",
  "dn2:86.6": "‘Đây là kiếm, đây là vỏ; kiếm là một, vỏ là một; chính từ vỏ mà kiếm được rút ra.’",
  "dn2:86.7": "Hoặc như, này Đại vương, một người lấy con rắn ra khỏi giỏ.",
  "dn2:86.8": "Người ấy nghĩ rằng:",
  "dn2:86.9": "‘Đây là rắn, đây là giỏ; rắn là một, giỏ là một; chính từ giỏ mà rắn được lấy ra.’",
  "dn2:86.10": "Cũng vậy, này Đại vương, khi tâm đã được định như vậy, thanh tịnh, trong sáng, không cấu uế, không nhiễm ô, nhu nhuyến, dễ sử dụng, vững chắc và bất động, vị Tỳ-kheo hướng tâm, nghiêng tâm đến việc tạo ra một thân do ý tạo.",
  "dn2:86.11": "Vị ấy từ thân này tạo ra một thân khác có sắc, do ý tạo, đầy đủ các chi phần, không thiếu căn nào.",
  "dn2:86.12": "Đây cũng là quả của đời sống xuất gia có thể thấy ngay trong hiện tại, thù thắng và cao quý hơn các quả trước.",
  "dn2:87.0": "4.3.3.3. Trí về các loại thần thông",
  "dn2:87.1": "Khi tâm đã được định như vậy, thanh tịnh, trong sáng, không cấu uế, không nhiễm ô, nhu nhuyến, dễ sử dụng, vững chắc và bất động, vị ấy hướng tâm, nghiêng tâm đến các loại thần thông.",
  "dn2:87.2": "Vị ấy chứng nghiệm nhiều loại thần thông khác nhau: một thân mà hiện thành nhiều thân, nhiều thân mà trở lại thành một; hiện hình rồi biến mất; đi xuyên qua tường, qua thành, qua núi như đi trong hư không không bị ngăn ngại; trồi lên lặn xuống trong đất như trong nước; đi trên nước mà không chìm như đi trên đất; ngồi kiết già bay giữa hư không như chim có cánh; lấy tay chạm và xoa mặt trăng, mặt trời — những vật có đại thần lực, đại oai lực như vậy; cho đến thân này có thể đi đến cõi Phạm thiên.",
  "dn2:88.1": "Ví như, này Đại vương, một người thợ gốm khéo tay hay học trò thợ gốm, với đất sét đã được nhào luyện kỹ, muốn làm loại đồ gốm nào thì làm và hoàn thành đúng như ý.",
  "dn2:88.2": "Hoặc như, này Đại vương, một người thợ ngà khéo tay hay học trò thợ ngà, với ngà đã được chế tác kỹ, muốn làm vật dụng nào bằng ngà thì làm và hoàn thành đúng như ý.",
  "dn2:88.3": "Hoặc như, này Đại vương, một người thợ vàng khéo tay hay học trò thợ vàng, với vàng đã được luyện kỹ, muốn làm vật dụng nào bằng vàng thì làm và hoàn thành đúng như ý.",
  "dn2:88.4": "Cũng vậy, này Đại vương, khi tâm đã được định như vậy, thanh tịnh, trong sáng, không cấu uế, không nhiễm ô, nhu nhuyến, dễ sử dụng, vững chắc và bất động, vị Tỳ-kheo hướng tâm, nghiêng tâm đến các loại thần thông.",
  "dn2:88.5": "Vị ấy chứng nghiệm nhiều loại thần thông khác nhau: một thân mà hiện thành nhiều thân, nhiều thân mà trở lại thành một; hiện hình rồi biến mất; đi xuyên qua tường, qua thành, qua núi như đi trong hư không không bị ngăn ngại; trồi lên lặn xuống trong đất như trong nước; đi trên nước mà không chìm như đi trên đất; ngồi kiết già bay giữa hư không như chim có cánh; lấy tay chạm và xoa mặt trăng, mặt trời — những vật có đại thần lực, đại oai lực như vậy; cho đến thân này có thể đi đến cõi Phạm thiên.",
  "dn2:88.6": "Đây cũng là quả của đời sống xuất gia có thể thấy ngay trong hiện tại, thù thắng và cao quý hơn các quả trước.",
  "dn2:89.0": "4.3.3.4. Trí về thiên nhĩ",
  "dn2:89.1": "Khi tâm đã được định như vậy, thanh tịnh, trong sáng, không cấu uế, không nhiễm ô, nhu nhuyến, dễ sử dụng, vững chắc và bất động, vị ấy hướng tâm, nghiêng tâm đến thiên nhĩ.",
  "dn2:89.2": "Với thiên nhĩ thanh tịnh, vượt quá tai người thường, vị ấy nghe được cả hai loại âm thanh: của chư thiên và của loài người, dù ở xa hay ở gần.",
  "dn2:90.1": "Ví như, này Đại vương, một người đang đi trên đường xa nghe tiếng trống lớn, tiếng trống nhỏ, tiếng tù và hay tiếng nhạc cụ; người ấy biết rõ: ‘đây là tiếng trống lớn’, ‘đây là tiếng trống nhỏ’, ‘đây là tiếng tù và hay tiếng nhạc cụ’.",
  "dn2:90.2": "Cũng vậy, này Đại vương, khi tâm đã được định như vậy, thanh tịnh, trong sáng, không cấu uế, không nhiễm ô, nhu nhuyến, dễ sử dụng, vững chắc và bất động, vị Tỳ-kheo hướng tâm, nghiêng tâm đến thiên nhĩ.",
  "dn2:90.3": "Với thiên nhĩ thanh tịnh, vượt quá tai người thường, vị ấy nghe được cả hai loại âm thanh: của chư thiên và của loài người, dù ở xa hay ở gần.",
  "dn2:90.4": "Đây cũng là quả của đời sống xuất gia có thể thấy ngay trong hiện tại, thù thắng và cao quý hơn các quả trước.",
  "dn2:91.0": "4.3.3.5. Trí biết tâm người khác",
  "dn2:91.1": "Khi tâm đã được định như vậy, thanh tịnh, trong sáng, không cấu uế, không nhiễm ô, nhu nhuyến, dễ sử dụng, vững chắc và bất động, vị ấy hướng tâm, nghiêng tâm đến trí biết tâm người khác.",
  "dn2:91.2": "Vị ấy biết tâm của chúng sinh khác, của người khác bằng cách thấu rõ tâm với tâm:",
  "dn2:91.3": "tâm có tham thì biết: ‘tâm có tham’;",
  "dn2:91.4": "tâm không tham thì biết: ‘tâm không tham’;",
  "dn2:91.5": "tâm có sân thì biết: ‘tâm có sân’;",
  "dn2:91.6": "tâm không sân thì biết: ‘tâm không sân’;",
  "dn2:91.7": "tâm có si thì biết: ‘tâm có si’;",
  "dn2:91.8": "tâm không si thì biết: ‘tâm không si’;",
  "dn2:91.9": "tâm bị thu hẹp thì biết: ‘tâm bị thu hẹp’;",
  "dn2:91.10": "tâm tán loạn thì biết: ‘tâm tán loạn’;",
  "dn2:91.11": "tâm rộng lớn thì biết: ‘tâm rộng lớn’;",
  "dn2:91.12": "tâm không rộng lớn thì biết: ‘tâm không rộng lớn’;",
  "dn2:91.13": "tâm còn có trạng thái cao hơn thì biết: ‘tâm còn có trạng thái cao hơn’;",
  "dn2:91.14": "tâm không còn trạng thái cao hơn thì biết: ‘tâm không còn trạng thái cao hơn’;",
  "dn2:91.15": "tâm định tĩnh thì biết: ‘tâm định tĩnh’;",
  "dn2:91.16": "tâm không định tĩnh thì biết: ‘tâm không định tĩnh’;",
  "dn2:91.17": "tâm giải thoát thì biết: ‘tâm giải thoát’;",
  "dn2:91.18": "tâm chưa giải thoát thì biết: ‘tâm chưa giải thoát’.",
   "dn2:92.1": "Ví như, này Đại vương, một phụ nữ hay một người đàn ông trẻ tuổi, ưa trang sức, khi soi mặt mình trong gương trong sạch, sáng rõ, hay trong chậu nước trong veo, nếu có vết nhơ thì biết: ‘có vết nhơ’, nếu không có vết nhơ thì biết: ‘không có vết nhơ’.",
  "dn2:92.2": "Cũng vậy, này Đại vương, vị Tỳ-kheo với tâm đã được định như vậy, thanh tịnh, trong sáng, không cấu uế, không nhiễm ô, nhu nhuyến, dễ sử dụng, vững chắc và bất động, hướng tâm, nghiêng tâm đến trí biết tâm người khác.",
  "dn2:92.3": "Vị ấy biết tâm của chúng sinh khác, của người khác bằng cách thấu rõ tâm với tâm:",
  "dn2:92.4": "tâm có tham thì biết: ‘tâm có tham’;",
  "dn2:92.5": "tâm không tham thì biết: ‘tâm không tham’;",
  "dn2:92.6": "tâm có sân thì biết: ‘tâm có sân’;",
  "dn2:92.7": "tâm không sân thì biết: ‘tâm không sân’;",
  "dn2:92.8": "tâm có si thì biết: ‘tâm có si’;",
  "dn2:92.9": "tâm không si thì biết: ‘tâm không si’;",
  "dn2:92.10": "tâm bị thu hẹp thì biết: ‘tâm bị thu hẹp’;",
  "dn2:92.11": "tâm tán loạn thì biết: ‘tâm tán loạn’;",
  "dn2:92.12": "tâm rộng lớn thì biết: ‘tâm rộng lớn’;",
  "dn2:92.13": "tâm không rộng lớn thì biết: ‘tâm không rộng lớn’;",
  "dn2:92.14": "tâm còn trạng thái cao hơn thì biết: ‘tâm còn trạng thái cao hơn’;",
  "dn2:92.15": "tâm không còn trạng thái cao hơn thì biết: ‘tâm không còn trạng thái cao hơn’;",
  "dn2:92.16": "tâm định tĩnh thì biết: ‘tâm định tĩnh’;",
  "dn2:92.17": "tâm không định tĩnh thì biết: ‘tâm không định tĩnh’;",
  "dn2:92.18": "tâm đã giải thoát thì biết: ‘tâm đã giải thoát’;",
  "dn2:92.19": "tâm chưa giải thoát thì biết: ‘tâm chưa giải thoát’.",
  "dn2:92.20": "Đây cũng là quả của đời sống xuất gia có thể thấy ngay trong hiện tại, cao thượng và vi diệu hơn những quả trước.",
  "dn2:93.0": "4.3.3.6. Trí nhớ các đời trước",
  "dn2:93.1": "Với tâm đã được định như vậy, thanh tịnh, trong sáng, không cấu uế, không nhiễm ô, nhu nhuyến, dễ sử dụng, vững chắc và bất động, vị ấy hướng tâm, nghiêng tâm đến trí nhớ các đời trước.",
  "dn2:93.2": "Vị ấy nhớ lại nhiều đời sống trước đây với nhiều hình thức khác nhau, như: một đời, hai đời, ba đời, bốn đời, năm đời, mười đời, hai mươi đời, ba mươi đời, bốn mươi đời, năm mươi đời, một trăm đời, một ngàn đời, một trăm ngàn đời, nhiều kiếp thế giới hoại, nhiều kiếp thế giới thành, nhiều kiếp thế giới hoại rồi thành: ‘Ở đời ấy ta có tên như vậy, họ như vậy, dung mạo như vậy, ăn uống như vậy, cảm thọ khổ vui như vậy, thọ mạng đến chừng ấy; từ đó qua đời, sinh về nơi kia; tại đó ta có tên như vậy… rồi từ đó qua đời, sinh về đây.’ Như vậy, với đầy đủ tướng trạng và chi tiết, vị ấy nhớ lại nhiều đời sống trước.",
  "dn2:94.1": "Ví như, này Đại vương, một người từ làng mình đi đến một làng khác, rồi từ làng ấy lại đi đến một làng khác nữa. Sau đó người ấy trở về chính làng của mình. Người ấy nghĩ: ‘Ta từ làng mình đến làng kia; tại đó ta đã đứng như vậy, ngồi như vậy, nói như vậy, im lặng như vậy; rồi từ làng ấy ta đến làng nọ; tại đó ta cũng đã đứng như vậy, ngồi như vậy, nói như vậy, im lặng như vậy; nay ta từ làng ấy trở về chính làng mình.’",
  "dn2:94.2": "Cũng vậy, này Đại vương, vị Tỳ-kheo với tâm đã được định như vậy… hướng tâm đến trí nhớ các đời trước.",
  "dn2:94.3": "Vị ấy nhớ lại nhiều đời sống trước đây… ‘Ở đời ấy ta có tên như vậy… rồi từ đó qua đời, sinh về đây.’ Như vậy, với đầy đủ tướng trạng và chi tiết, vị ấy nhớ lại nhiều đời sống trước.",
  "dn2:94.4": "Đây cũng là quả của đời sống xuất gia có thể thấy ngay trong hiện tại, cao thượng và vi diệu hơn những quả trước.",
  "dn2:95.0": "4.3.3.7. Trí thiên nhãn",
  "dn2:95.1": "Với tâm đã được định như vậy, thanh tịnh, trong sáng, không cấu uế, không nhiễm ô, nhu nhuyến, dễ sử dụng, vững chắc và bất động, vị ấy hướng tâm, nghiêng tâm đến trí biết sự chết và tái sinh của chúng sinh.",
  "dn2:95.2": "Vị ấy với mắt trời trong sạch, vượt quá mắt người, thấy các chúng sinh chết đi và sinh lại, kẻ thấp kẻ cao, người đẹp kẻ xấu, đi đến cảnh lành hay cảnh dữ; biết rõ chúng sinh tùy theo nghiệp của mình: ‘Những chúng sinh này có thân làm điều xấu, lời nói điều xấu, ý nghĩ điều xấu, phỉ báng bậc thánh, có cái thấy sai, chấp theo hành động do cái thấy sai; sau khi thân hoại mạng chung, họ sinh vào cảnh dữ, chỗ khổ, nơi đọa lạc, địa ngục. Còn những chúng sinh kia có thân làm điều lành, lời nói điều lành, ý nghĩ điều lành, không phỉ báng bậc thánh, có cái thấy đúng, chấp theo hành động do cái thấy đúng; sau khi thân hoại mạng chung, họ sinh vào cảnh lành, cõi trời.’ Như vậy, với mắt trời trong sạch vượt quá mắt người, vị ấy thấy chúng sinh chết đi và sinh lại, kẻ thấp kẻ cao, người đẹp kẻ xấu, đi đến cảnh lành hay cảnh dữ; biết rõ chúng sinh tùy theo nghiệp của mình.",
  "dn2:96.1": "Ví như, này Đại vương, tại ngã tư có một tòa lầu cao. Ở đó, một người có mắt đứng nhìn thấy người vào nhà, người ra khỏi nhà, người đi trên đường, người ngồi giữa ngã tư. Người ấy nghĩ: ‘Những người này vào nhà, những người kia ra khỏi nhà, những người này đi trên đường, những người kia ngồi giữa ngã tư.’",
  "dn2:96.2": "Cũng vậy, này Đại vương, vị Tỳ-kheo với tâm đã được định như vậy… hướng tâm đến trí biết sự chết và tái sinh của chúng sinh.",
  "dn2:96.3": "Vị ấy với mắt trời trong sạch vượt quá mắt người, thấy chúng sinh chết đi và sinh lại, kẻ thấp kẻ cao, người đẹp kẻ xấu, đi đến cảnh lành hay cảnh dữ; biết rõ chúng sinh tùy theo nghiệp của mình: ‘Những chúng sinh này… sinh vào cảnh dữ… Những chúng sinh kia… sinh vào cảnh lành, cõi trời.’ Như vậy, vị ấy biết rõ chúng sinh tùy theo nghiệp của mình.",
  "dn2:96.4": "Đây cũng là quả của đời sống xuất gia có thể thấy ngay trong hiện tại, cao thượng và vi diệu hơn những quả trước.",
  "dn2:97.0": "4.3.3.8. Trí đoạn trừ các lậu hoặc",
  "dn2:97.1": "Với tâm đã được định như vậy, thanh tịnh, trong sáng, không cấu uế, không nhiễm ô, nhu nhuyến, dễ sử dụng, vững chắc và bất động, vị ấy hướng tâm, nghiêng tâm đến trí đoạn trừ các lậu hoặc.",
  "dn2:97.2": "Vị ấy biết đúng như thật: ‘Đây là khổ’; biết đúng như thật: ‘Đây là nguồn gốc của khổ’; biết đúng như thật: ‘Đây là sự chấm dứt khổ’; biết đúng như thật: ‘Đây là con đường đưa đến chấm dứt khổ.’",
  "dn2:97.3": "Vị ấy biết đúng như thật: ‘Đây là các lậu hoặc’; biết đúng như thật: ‘Đây là nguồn gốc của lậu hoặc’; biết đúng như thật: ‘Đây là sự chấm dứt lậu hoặc’; biết đúng như thật: ‘Đây là con đường đưa đến chấm dứt lậu hoặc.’",
  "dn2:97.4": "Do biết như vậy, thấy như vậy, tâm vị ấy được giải thoát khỏi lậu hoặc do dục, được giải thoát khỏi lậu hoặc do hữu, được giải thoát khỏi lậu hoặc do vô minh.",
  "dn2:97.5": "Khi được giải thoát, khởi lên sự biết: ‘Đã giải thoát.’",
  "dn2:97.6": "Vị ấy biết: ‘Sinh đã tận, đời sống phạm hạnh đã hoàn thành, việc cần làm đã làm xong, không còn trở lại trạng thái này nữa.’",
  "dn2:98.1": "Ví như, này Đại vương, trên sườn núi có một hồ nước trong sạch, sáng rõ, không đục. Một người có mắt đứng bên bờ thấy vỏ sò, đá sỏi và đàn cá đang bơi hoặc đứng yên. Người ấy nghĩ: ‘Hồ nước này trong sạch, sáng rõ, không đục; trong đó có vỏ sò, đá sỏi và đàn cá đang bơi hoặc đứng yên.’",
  "dn2:98.2": "Cũng vậy, này Đại vương, vị Tỳ-kheo với tâm đã được định như vậy… hướng tâm đến trí đoạn trừ các lậu hoặc.",
  "dn2:98.3": "Vị ấy biết đúng như thật: ‘Đây là khổ… Đây là con đường đưa đến chấm dứt khổ.’",
  "dn2:98.4": "Vị ấy biết đúng như thật: ‘Đây là các lậu hoặc… Đây là con đường đưa đến chấm dứt lậu hoặc.’",
  "dn2:98.5": "Do biết như vậy, thấy như vậy, tâm vị ấy được giải thoát khỏi lậu hoặc do dục, do hữu, do vô minh.",
  "dn2:98.6": "Khi được giải thoát, khởi lên sự biết: ‘Đã giải thoát.’",
  "dn2:98.7": "Vị ấy biết: ‘Sinh đã tận, đời sống phạm hạnh đã hoàn thành, việc cần làm đã làm xong, không còn trở lại trạng thái này nữa.’",
  "dn2:98.8": "Đây là quả của đời sống xuất gia có thể thấy ngay trong hiện tại, cao thượng và vi diệu hơn những quả trước.",
  "dn2:98.9": "Và, này Đại vương, ngoài quả xuất gia có thể thấy ngay trong hiện tại này, không có quả nào cao hơn hay vi diệu hơn nữa.",
  "dn2:99.0": "5. Vua Ajātasattu tuyên bố quy y",
  "dn2:99.1": "Khi được nói vậy, vua nước Magadha là Ajātasattu, con của bà Vedehī, bạch Thế Tôn:",
  "dn2:99.2": "“Thật là tuyệt vời, bạch Thế Tôn, thật là tuyệt vời, bạch Thế Tôn!",
  "dn2:99.3": "Ví như, bạch Thế Tôn, người ta dựng lại vật bị úp xuống, mở ra điều bị che kín, chỉ đường cho người lạc lối, thắp đèn giữa bóng tối để người có mắt thấy được hình sắc; cũng vậy, Thế Tôn đã dùng nhiều cách làm sáng tỏ giáo pháp.",
  "dn2:99.4": "Con xin quy y Thế Tôn, quy y Pháp và quy y Tăng.",
  "dn2:99.5": "Xin Thế Tôn ghi nhận con từ nay trọn đời là người cư sĩ đã quy y.",
  "dn2:99.6": "Bạch Thế Tôn, con đã phạm lỗi, vì ngu si, vì mê lầm, vì bất thiện mà con đã giết cha mình là vị vua đúng pháp, trị nước theo pháp, chỉ vì quyền lực.",
  "dn2:99.7": "Xin Thế Tôn nhận cho con lỗi ấy là lỗi, để con được giữ mình trong tương lai.”",
  "dn2:100.1": "“Đúng vậy, này Đại vương, ông đã phạm lỗi vì ngu si, vì mê lầm, vì bất thiện, khi ông giết cha mình là vị vua đúng pháp, trị nước theo pháp.",
  "dn2:100.2": "Nhưng vì ông đã thấy lỗi là lỗi và sửa đổi đúng theo pháp, nên chúng tôi chấp nhận cho ông.",
  "dn2:100.3": "Này Đại vương, đó là sự tiến bộ trong giáo luật của bậc thánh: ai thấy lỗi là lỗi, sửa đổi đúng theo pháp và giữ mình trong tương lai.”",
  "dn2:101.1": "Khi được nói vậy, vua nước Magadha là Ajātasattu, con của bà Vedehī, bạch Thế Tôn:",
  "dn2:101.2": "“Bạch Thế Tôn, nay chúng con xin phép ra về, vì còn nhiều việc, nhiều trách nhiệm.”",
  "dn2:101.3": "“Này Đại vương, ông hãy làm điều ông thấy là thích hợp.”",
  "dn2:101.4": "Rồi vua Magadha Ajātasattu, con bà Vedehī, hoan hỷ tán thán lời Thế Tôn, đứng dậy khỏi chỗ ngồi, đảnh lễ Thế Tôn, đi vòng bên phải và ra về.",
  "dn2:102.1": "Sau khi vua Ajātasattu vừa đi không bao lâu, Thế Tôn gọi các Tỳ-kheo:",
  "dn2:102.2": "“Này các Tỳ-kheo, vị vua này đã bị thương tổn.",
  "dn2:102.3": "Này các Tỳ-kheo, vị vua này đã bị hủy hoại.",
  "dn2:102.4": "Này các Tỳ-kheo, nếu vị vua này đã không tước đoạt mạng sống của cha mình – vị vua đúng pháp, trị nước theo pháp – thì ngay tại chỗ ngồi này, pháp nhãn không bụi, không nhơ đã có thể sinh khởi nơi ông ấy.”",
  "dn2:102.5": "Thế Tôn đã nói như vậy.",
  "dn2:102.6": "Các Tỳ-kheo hoan hỷ tán thán lời Thế Tôn.",
  "dn2:102.7": "Kinh Quả của đời sống xuất gia, bài thứ hai, chấm dứt.",
}
window.BILARA["dn02"]["vi"]["dn02:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
