window.BILARA = window.BILARA || {};
window.BILARA["dn07"] = window.BILARA["dn07"] || {};
window.BILARA["dn07"]["vi"] = {
  "dn7:0.1": "Trường Bộ Kinh 7 ",
  "dn7:0.2": "Kinh Jāliya ",
  "dn7:1.1": "Tôi nghe như vầy ",
  "dn7:1.2": "một thời Thế Tôn trú tại Kosambī, trong khu vườn Ghosita. ",
  "dn7:1.3": "Lúc bấy giờ có hai vị xuất gia ",
  "dn7:1.4": "du sĩ Muṇḍiya và Jāliya, đệ tử của Dārupattika, đi đến chỗ Thế Tôn; sau khi đến, họ chào hỏi thân thiện với Thế Tôn. ",
  "dn7:1.5": "Sau khi nói lên những lời thăm hỏi thân tình đáng ghi nhớ, họ đứng sang một bên. Đứng sang một bên, hai vị xuất gia ấy bạch Thế Tôn: ",
  "dn7:1.6": "“Này hiền giả Gotama, mạng sống và thân thể là một, hay mạng sống là một thứ còn thân thể là một thứ khác?” ",
  "dn7:1.7": "“Vậy này các hiền giả, hãy lắng nghe, khéo tác ý, ta sẽ nói.”",
  "dn7:1.8": "“Thưa hiền giả, vâng vậy,” hai vị xuất gia ấy vâng đáp Thế Tôn. ",
  "dn7:1.9": "Thế Tôn nói như sau: ",
  "dn7:2.1": "“Này các hiền giả, ở đây Như Lai xuất hiện ở đời, là bậc A-la-hán, Chánh Đẳng Giác … ",
  "dn7:2.2": "Như vậy, này các hiền giả, vị tỳ-kheo thành tựu giới. ",
  "dn7:2.3": "… ",
  "dn7:2.4": "chứng và an trú thiền thứ nhất. ",
  "dn7:2.5": "Này các hiền giả, vị tỳ-kheo nào biết như vậy, thấy như vậy, có thích hợp chăng để nói rằng: ",
  "dn7:2.6": "‘mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’? ",
  "dn7:2.7": "Này các hiền giả, vị tỳ-kheo ấy biết như vậy, thấy như vậy, có thể nói như thế. ",
  "dn7:2.8": "‘Mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’. ",
  "dn7:2.9": "Nhưng này các hiền giả, ta biết như vậy, thấy như vậy. ",
  "dn7:2.10": "Tuy thế ta không nói rằng: ",
  "dn7:2.11": "‘mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’ … ",
  "dn7:3.1": "thiền thứ hai … ",
  "dn7:3.2": "thiền thứ ba … ",
  "dn7:3.3": "chứng và an trú thiền thứ tư. ",
  "dn7:3.4": "Này các hiền giả, vị tỳ-kheo nào biết như vậy, thấy như vậy, có thích hợp chăng để nói rằng: ",
  "dn7:3.5": "‘mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’? ",
  "dn7:3.6": "Này các hiền giả, vị tỳ-kheo ấy biết như vậy, thấy như vậy, có thể nói như thế: ",
  "dn7:3.7": "‘mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’. ",
  "dn7:3.8": "Nhưng này các hiền giả, ta biết như vậy, thấy như vậy. ",
  "dn7:3.9": "Tuy thế ta không nói rằng: ",
  "dn7:3.10": "‘mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’ … ",
  "dn7:4.1": "hướng tâm, nghiêng tâm đến tri kiến … ",
  "dn7:4.2": "này các hiền giả, vị tỳ-kheo nào biết như vậy, thấy như vậy, có thích hợp chăng để nói rằng: ",
  "dn7:4.3": "‘mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’? ",
  "dn7:4.4": "Này các hiền giả, vị tỳ-kheo ấy biết như vậy, thấy như vậy, có thể nói như thế: ",
  "dn7:4.5": "‘mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’. ",
  "dn7:4.6": "Nhưng này các hiền giả, ta biết như vậy, thấy như vậy. ",
  "dn7:4.7": "Tuy thế ta không nói rằng: ",
  "dn7:4.8": "‘mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’ … ",
  "dn7:5.1": "… biết rằng: ‘không còn trạng thái này nữa’. ",
  "dn7:5.2": "Này các hiền giả, vị tỳ-kheo nào biết như vậy, thấy như vậy, có thích hợp chăng để nói rằng: ",
  "dn7:5.3": "‘mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’? ",
  "dn7:5.4": "Này các hiền giả, vị tỳ-kheo ấy biết như vậy, thấy như vậy, không thích hợp để nói rằng: ",
  "dn7:5.5": "‘mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’. ",
  "dn7:5.6": "Nhưng này các hiền giả, ta biết như vậy, thấy như vậy. ",
  "dn7:5.7": "Tuy thế ta không nói rằng: ",
  "dn7:5.8": "‘mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’.” ",
  "dn7:5.9": "Thế Tôn đã nói như vậy. ",
  "dn7:5.10": "Hai vị xuất gia ấy hoan hỷ tín thọ lời Thế Tôn dạy. ",
  "dn7:5.11": "Kinh Jāliya thứ bảy chấm dứt. "
}
window.BILARA["dn07"]["vi"]["dn07:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
