window.BILARA = window.BILARA || {};
window.BILARA["dn08"] = window.BILARA["dn08"] || {};
window.BILARA["dn08"]["vi"] = {
  "dn8:0.1": "Trường Bộ Kinh 8 ",
  "dn8:0.2": "Kinh Đại Sư Tử Hống ",
  "dn8:1.1": "Tôi nghe như vầy—",
  "dn8:1.2": "Một thời, Thế Tôn trú tại Uruññā, ở khu rừng nai Kaṇṇakatthala. ",
  "dn8:1.3": "Bấy giờ, lõa thể Kassapa đi đến chỗ Thế Tôn; sau khi đến, ông trao đổi những lời chào hỏi thân thiện với Thế Tôn. ",
  "dn8:1.4": "Sau khi nói lên những lời thăm hỏi thân tình đáng ghi nhớ, ông đứng sang một bên. Đứng sang một bên, lõa thể Kassapa bạch Thế Tôn rằng: ",
  "dn8:2.1": "“Tôi có nghe như vầy, thưa Gotama: ",
  "dn8:2.2": "‘Sa-môn Gotama chê trách mọi khổ hạnh, hoàn toàn chỉ trích và phê phán mọi người tu khổ hạnh sống kham khổ.’ ",
  "dn8:2.3": "Những ai nói như vậy: ‘Sa-môn Gotama chê trách mọi khổ hạnh, hoàn toàn chỉ trích và phê phán mọi người tu khổ hạnh sống kham khổ’, có phải họ nói đúng lời của Tôn giả Gotama, không vu khống Tôn giả Gotama bằng điều không thật, có trình bày đúng pháp thuận pháp, và không khiến bất cứ ai tranh luận đúng pháp có cớ để chỉ trích chăng? ",
  "dn8:2.4": "Vì chúng tôi không muốn vu khống Tôn giả Gotama.”",
  "dn8:3.1": "“Này Kassapa, những ai nói như vậy: ‘Sa-môn Gotama chê trách mọi khổ hạnh, hoàn toàn chỉ trích và phê phán mọi người tu khổ hạnh sống kham khổ’, họ không nói đúng lời của Ta, mà còn vu khống Ta bằng điều không thật, không đúng sự thật. ",
  "dn8:3.2": "Ở đây, này Kassapa, Ta thấy với thiên nhãn thanh tịnh siêu nhân một số người tu khổ hạnh sống kham khổ, sau khi thân hoại mạng chung, sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "dn8:3.3": "Nhưng ở đây, này Kassapa, Ta cũng thấy với thiên nhãn thanh tịnh siêu nhân một số người tu khổ hạnh sống kham khổ, sau khi thân hoại mạng chung, sinh vào thiện thú, cõi trời. ",
  "dn8:3.4": "Ở đây, này Kassapa, Ta thấy với thiên nhãn thanh tịnh siêu nhân một số người tu khổ hạnh sống ít khổ, sau khi thân hoại mạng chung, sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "dn8:3.5": "Nhưng ở đây, này Kassapa, Ta cũng thấy với thiên nhãn thanh tịnh siêu nhân một số người tu khổ hạnh sống ít khổ, sau khi thân hoại mạng chung, sinh vào thiện thú, cõi trời. ",
  "dn8:3.6": "Này Kassapa, khi Ta biết như thật sự đến, sự đi, sự chết và sự tái sinh của những người tu khổ hạnh ấy như vậy, thì làm sao Ta lại chê trách mọi khổ hạnh, hay hoàn toàn chỉ trích và phê phán mọi người tu khổ hạnh sống kham khổ được? ",
  "dn8:4.1": "Này Kassapa, có những sa-môn, bà-la-môn là bậc hiền trí, khéo léo, tinh thông các học thuyết của người khác, như người bắn trúng sợi lông. Ta nghĩ họ đi đây đi đó để phá vỡ các kiến chấp bằng trí tuệ của mình. ",
  "dn8:4.2": "Với họ, có những điểm Ta đồng ý, có những điểm Ta không đồng ý. ",
  "dn8:4.3": "Điều gì họ nói trong một số trường hợp là ‘tốt’, thì Ta cũng nói trong một số trường hợp là ‘tốt’. ",
  "dn8:4.4": "Điều gì họ nói trong một số trường hợp là ‘không tốt’, thì Ta cũng nói trong một số trường hợp là ‘không tốt’. ",
  "dn8:4.5": "Điều gì họ nói trong một số trường hợp là ‘tốt’, thì Ta nói trong một số trường hợp là ‘không tốt’. ",
  "dn8:4.6": "Điều gì họ nói trong một số trường hợp là ‘không tốt’, thì Ta nói trong một số trường hợp là ‘tốt’. ",
  "dn8:4.7": "Điều gì Ta nói trong một số trường hợp là ‘tốt’, thì người khác cũng nói trong một số trường hợp là ‘tốt’. ",
  "dn8:4.8": "Điều gì Ta nói trong một số trường hợp là ‘không tốt’, thì người khác cũng nói trong một số trường hợp là ‘không tốt’. ",
  "dn8:4.9": "Điều gì Ta nói trong một số trường hợp là ‘không tốt’, thì người khác nói trong một số trường hợp là ‘tốt’. ",
  "dn8:4.10": "Điều gì Ta nói trong một số trường hợp là ‘tốt’, thì người khác nói trong một số trường hợp là ‘không tốt’. ",
  "dn8:5.0": "1. Lời nói để chất vấn ",
  "dn8:5.1": "Rồi Ta đến gần họ và nói như vầy: ",
  "dn8:5.2": "‘Này các hiền giả, những điểm nào giữa chúng ta không đồng ý, hãy để những điểm ấy sang một bên. ",
  "dn8:5.3": "Còn ở những điểm đồng ý, tại đó người trí khi chất vấn, khảo sát và bàn luận về thầy với thầy, hay về tăng với tăng, sẽ nói rằng: ",
  "dn8:5.4": "“Những pháp nào của chư vị là bất thiện, được gọi là bất thiện, có lỗi, được gọi là có lỗi, không nên thực hành, được gọi là không nên thực hành, không xứng bậc thánh, được gọi là không xứng bậc thánh, đen tối, được gọi là đen tối—",
  "dn8:5.5": "ai là người đã từ bỏ hoàn toàn những pháp ấy mà sống, sa-môn Gotama hay các vị giáo chủ của các nhóm khác?” ",
  "dn8:6.1": "Này Kassapa, có trường hợp người trí khi chất vấn, khảo sát và bàn luận sẽ nói như vầy: ",
  "dn8:6.2": "‘Những pháp nào của chư vị là bất thiện, được gọi là bất thiện, có lỗi, được gọi là có lỗi, không nên thực hành, được gọi là không nên thực hành, không xứng bậc thánh, được gọi là không xứng bậc thánh, đen tối, được gọi là đen tối—",
  "dn8:6.3": "sa-môn Gotama là người đã từ bỏ hoàn toàn những pháp ấy mà sống, chứ không phải các vị giáo chủ khác.’ ",
  "dn8:6.4": "Như vậy, này Kassapa, người trí khi chất vấn, khảo sát và bàn luận sẽ phần nhiều tán thán Ta trong trường hợp ấy. ",
  "dn8:7.1": "Lại nữa, này Kassapa, người trí khi chất vấn, khảo sát và bàn luận về thầy với thầy, hay về tăng với tăng: ",
  "dn8:7.2": "‘Những pháp nào của chư vị là thiện, được gọi là thiện, không lỗi, được gọi là không lỗi, nên thực hành, được gọi là nên thực hành, xứng bậc thánh, được gọi là xứng bậc thánh, trắng sạch, được gọi là trắng sạch—",
  "dn8:7.3": "ai là người đã thọ trì trọn vẹn những pháp ấy mà sống, sa-môn Gotama hay các vị giáo chủ của các nhóm khác?’ ",
  "dn8:8.1": "Này Kassapa, có trường hợp người trí khi chất vấn, khảo sát và bàn luận sẽ nói như vầy: ",
  "dn8:8.2": "‘Những pháp nào của chư vị là thiện, được gọi là thiện, không lỗi, được gọi là không lỗi, nên thực hành, được gọi là nên thực hành, xứng bậc thánh, được gọi là xứng bậc thánh, trắng sạch, được gọi là trắng sạch—",
  "dn8:8.3": "sa-môn Gotama là người đã thọ trì trọn vẹn những pháp ấy mà sống, chứ không phải các vị giáo chủ khác.’ ",
  "dn8:8.4": "Như vậy, này Kassapa, người trí khi chất vấn, khảo sát và bàn luận sẽ phần nhiều tán thán Ta trong trường hợp ấy. ",
  "dn8:9.1": "Lại nữa, này Kassapa, người trí khi chất vấn, khảo sát và bàn luận về thầy với thầy, hay về tăng với tăng: ",
  "dn8:9.2": "‘Những pháp nào của chư vị là bất thiện, được gọi là bất thiện, có lỗi, được gọi là có lỗi, không nên thực hành, được gọi là không nên thực hành, không xứng bậc thánh, được gọi là không xứng bậc thánh, đen tối, được gọi là đen tối—",
  "dn8:9.3": "ai là người đã từ bỏ hoàn toàn những pháp ấy mà sống, tăng đoàn đệ tử của Gotama hay tăng đoàn đệ tử của các giáo chủ khác?’ ",
  "dn8:10.1": "Này Kassapa, có trường hợp người trí khi chất vấn, khảo sát và bàn luận sẽ nói như vầy: ",
  "dn8:10.2": "‘Những pháp nào của chư vị là bất thiện, được gọi là bất thiện, có lỗi, được gọi là có lỗi, không nên thực hành, được gọi là không nên thực hành, không xứng bậc thánh, được gọi là không xứng bậc thánh, đen tối, được gọi là đen tối—",
  "dn8:10.3": "tăng đoàn đệ tử của Gotama là người đã từ bỏ hoàn toàn những pháp ấy mà sống, chứ không phải tăng đoàn đệ tử của các giáo chủ khác.’ ",
  "dn8:10.4": "Như vậy, này Kassapa, người trí khi chất vấn, khảo sát và bàn luận sẽ phần nhiều tán thán chúng Ta trong trường hợp ấy. ",
  "dn8:11.1": "Lại nữa, này Kassapa, người trí khi chất vấn, khảo sát và bàn luận về thầy với thầy, hay về tăng với tăng. ",
  "dn8:11.2": "‘Những pháp nào của chư vị là thiện, được gọi là thiện, không lỗi, được gọi là không lỗi, nên thực hành, được gọi là nên thực hành, xứng bậc thánh, được gọi là xứng bậc thánh, trắng sạch, được gọi là trắng sạch—",
  "dn8:11.3": "ai là người đã thọ trì trọn vẹn những pháp ấy mà sống, tăng đoàn đệ tử của Gotama hay tăng đoàn đệ tử của các giáo chủ khác?’ ",
  "dn8:12.1": "Này Kassapa, có trường hợp người trí khi chất vấn, khảo sát và bàn luận sẽ nói như vầy: ",
  "dn8:12.2": "‘Những pháp nào của chư vị là thiện, được gọi là thiện, không lỗi, được gọi là không lỗi, nên thực hành, được gọi là nên thực hành, xứng bậc thánh, được gọi là xứng bậc thánh, trắng sạch, được gọi là trắng sạch—",
  "dn8:12.3": "tăng đoàn đệ tử của Gotama là người đã thọ trì trọn vẹn những pháp ấy mà sống, chứ không phải tăng đoàn đệ tử của các giáo chủ khác.’ ",
  "dn8:12.4": "Như vậy, này Kassapa, người trí khi chất vấn, khảo sát và bàn luận sẽ phần nhiều tán thán chúng Ta trong trường hợp ấy. ",
  "dn8:13.0": "2. Thánh đạo tám ngành ",
  "dn8:13.1": "Này Kassapa, có con đường, có lộ trình thực hành, mà ai thực hành đúng theo đó sẽ tự mình biết, tự mình thấy rằng: ",
  "dn8:13.2": "‘Chính sa-môn Gotama là người nói đúng thời, nói sự thật, nói điều lợi ích, nói pháp, nói luật.’ ",
  "dn8:13.3": "Này Kassapa, thế nào là con đường, thế nào là lộ trình thực hành mà ai thực hành đúng theo đó sẽ tự mình biết, tự mình thấy rằng: ",
  "dn8:13.4": "‘Chính sa-môn Gotama là người nói đúng thời, nói sự thật, nói điều lợi ích, nói pháp, nói luật’? ",
  "dn8:13.5": "Chính là Thánh đạo tám ngành này. ",
  "dn8:13.6": "Tức là: chánh kiến, chánh tư duy, chánh ngữ, chánh nghiệp, chánh mạng, chánh tinh tấn, chánh niệm, chánh định. ",
  "dn8:13.7": "Này Kassapa, đây là con đường, đây là lộ trình thực hành mà ai thực hành đúng theo đó sẽ tự mình biết, tự mình thấy: ‘Chính sa-môn Gotama là người nói đúng thời, nói sự thật, nói điều lợi ích, nói pháp, nói luật.’”",
  "dn8:14.0": "3. Luận về các cách hành xác ",
  "dn8:14.1": "Khi được nói vậy, lõa thể Kassapa bạch Thế Tôn rằng: ",
  "dn8:14.2": "“Này hiền giả Gotama, những cách hành xác này cũng được các sa-môn, bà-la-môn ấy xem là sa-môn hạnh và bà-la-môn hạnh. ",
  "dn8:14.3": "Có người sống lõa thể, sống phóng túng, liếm tay, không đến khi được mời, không đứng lại khi được mời, không nhận đồ được mang đến, không nhận đồ làm riêng cho mình, không nhận lời mời. ",
  "dn8:14.4": "Vị ấy không nhận từ miệng nồi, không nhận từ miệng chảo, không nhận giữa hai người, không nhận giữa cây gậy, không nhận giữa chày, không nhận từ hai người đang ăn, không nhận từ người có thai, không nhận từ người đang cho con bú, không nhận từ người đang ở với đàn ông, không nhận ở chỗ có hô gọi, không nhận ở chỗ có chó đứng chực, không nhận ở chỗ ruồi bu kín, không ăn cá, không ăn thịt, không uống rượu, không uống men say, không uống nước vo gạo. ",
  "dn8:14.5": "Vị ấy hoặc chỉ nhận ở một nhà, một miếng; hoặc nhận ở hai nhà, hai miếng … hoặc nhận ở bảy nhà, bảy miếng; ",
  "dn8:14.6": "hoặc sống bằng một lần bố thí, sống bằng hai lần bố thí … sống bằng bảy lần bố thí; ",
  "dn8:14.7": "hoặc ăn một ngày một bữa, hoặc hai ngày một bữa … hoặc bảy ngày một bữa. Như vậy, vị ấy sống chuyên tâm theo hạnh ăn theo kỳ, cho đến nửa tháng mới ăn một lần. ",
  "dn8:14.8": "Này hiền giả Gotama, những cách hành xác này cũng được các sa-môn, bà-la-môn ấy xem là sa-môn hạnh và bà-la-môn hạnh. ",
  "dn8:14.9": "Hoặc vị ấy ăn rau, hoặc ăn kê, hoặc ăn lúa hoang, hoặc ăn da vụn, hoặc ăn rong rêu, hoặc ăn cám, hoặc ăn nước vo gạo, hoặc ăn bã dầu, hoặc ăn cỏ, hoặc ăn phân bò; vị ấy sống bằng rễ và quả trong rừng, ăn trái rụng. ",
  "dn8:14.10": "Này hiền giả Gotama, những cách hành xác này cũng được các sa-môn, bà-la-môn ấy xem là sa-môn hạnh và bà-la-môn hạnh. ",
  "dn8:14.11": "Hoặc vị ấy mặc vải gai, mặc vải thô, mặc vải liệm xác, mặc y phấn tảo, mặc vỏ cây, mặc da thú, mặc tấm da thú, mặc áo cỏ kusa, mặc áo vỏ cây, mặc áo bằng ván, mặc chăn tóc người, mặc chăn lông thú, mặc áo bằng lông cánh cú, ",
  "dn8:14.12": "hoặc nhổ tóc và râu, chuyên tâm theo hạnh nhổ tóc và râu, ",
  "dn8:14.13": "hoặc thường đứng, từ bỏ ngồi, ",
  "dn8:14.14": "hoặc ngồi chồm hổm, chuyên tâm theo hạnh ngồi chồm hổm, ",
  "dn8:14.15": "hoặc nằm trên gai, lấy giường gai làm chỗ nằm, ",
  "dn8:14.16": "hoặc nằm trên ván, hoặc nằm trên đất trần, ",
  "dn8:14.17": "hoặc chỉ nằm một bên, ",
  "dn8:14.18": "để bụi bặm cáu ghét bám đầy người, ",
  "dn8:14.19": "hoặc sống ngoài trời, ",
  "dn8:14.20": "nằm bất cứ chỗ nào được trải ra, ",
  "dn8:14.21": "hoặc ăn những món ghê tởm, chuyên tâm theo hạnh ăn đồ ghê tởm, ",
  "dn8:14.22": "hoặc không uống nước, chuyên tâm theo hạnh không uống nước, ",
  "dn8:14.23": "hoặc chuyên tâm theo hạnh xuống nước tắm ba lần mỗi chiều.” ",
  "dn8:15.0": "4. Luận về sự vô ích của các cách hành xác ",
  "dn8:15.1": "“Này Kassapa, dù có sống lõa thể, sống phóng túng, liếm tay … cho đến sống chuyên tâm theo hạnh ăn theo kỳ, cho đến nửa tháng mới ăn một lần. ",
  "dn8:15.2": "Nhưng nếu vị ấy chưa tu tập, chưa chứng đạt thành tựu về giới, thành tựu về tâm, thành tựu về tuệ, thì vị ấy vẫn còn xa sa-môn hạnh, còn xa bà-la-môn hạnh. ",
  "dn8:15.3": "Nhưng khi nào, này Kassapa, vị tỳ-kheo tu tập tâm từ không oán, không hại, và do đoạn tận các lậu hoặc, ngay trong hiện tại tự mình với thắng trí chứng ngộ, thành tựu và an trú vô lậu tâm giải thoát, tuệ giải thoát, ",
  "dn8:15.4": "thì này Kassapa, vị tỳ-kheo ấy được gọi là sa-môn, cũng được gọi là bà-la-môn. ",
  "dn8:15.5": "Này Kassapa, dù có ăn rau, ăn kê … cho đến sống bằng rễ và quả trong rừng, ăn trái rụng. ",
  "dn8:15.6": "Nhưng nếu vị ấy chưa tu tập, chưa chứng đạt thành tựu về giới, thành tựu về tâm, thành tựu về tuệ. ",
  "dn8:15.7": "Thì vị ấy vẫn còn xa sa-môn hạnh, còn xa bà-la-môn hạnh. ",
  "dn8:15.8": "Nhưng khi nào, này Kassapa, vị tỳ-kheo tu tập tâm từ không oán, không hại, và do đoạn tận các lậu hoặc, ngay trong hiện tại tự mình với thắng trí chứng ngộ, thành tựu và an trú vô lậu tâm giải thoát, tuệ giải thoát, ",
  "dn8:15.9": "thì này Kassapa, vị tỳ-kheo ấy được gọi là sa-môn, cũng được gọi là bà-la-môn. ",
  "dn8:15.10": "Này Kassapa, dù có mặc vải gai, mặc vải thô … ",
  "dn8:15.11": "Vị ấy còn sống chuyên chú thực hành việc xuống nước tắm đến ba lần vào buổi chiều.",
  "dn8:15.12": "Nhưng nơi vị ấy, thành tựu về giới, thành tựu về tâm, thành tựu về tuệ chưa được tu tập, chưa được chứng ngộ.",
  "dn8:15.13": "Khi ấy, vị ấy còn xa Sa-môn hạnh, còn xa Phạm hạnh.",
  "dn8:15.14": "Nhưng này Kassapa, khi nào vị tỳ-kheo tu tập tâm từ không oán, không hại, và do đoạn tận các lậu hoặc, ngay trong hiện tại tự mình với thắng trí chứng ngộ, thành tựu và an trú vô lậu tâm giải thoát, tuệ giải thoát,",
  "dn8:15.15": "thì này Kassapa, vị tỳ-kheo ấy được gọi là Sa-môn, cũng được gọi là Bà-la-môn.”",
  "dn8:16.1": "Khi được nói vậy, Kassapa lõa thể bạch Thế Tôn rằng:",
  "dn8:16.2": "“Thưa Tôn giả Gotama, Sa-môn hạnh thật khó làm, Phạm hạnh thật khó làm.”",
  "dn8:16.3": "“Này Kassapa, trong đời người ta thường nói: ‘Sa-môn hạnh khó làm, Phạm hạnh khó làm.’",
  "dn8:16.4": "Này Kassapa, dù có là người lõa thể, sống phóng túng, liếm tay … chỉ chuyên chú thực hành hạnh ăn theo phiên, nửa tháng mới ăn một lần,",
  "dn8:16.5": "nếu chỉ với chừng ấy, với sự khổ hạnh ấy mà thành Sa-môn hay thành Bà-la-môn, khó làm, rất khó làm, thì lời nói này đã không hợp lý rằng:",
  "dn8:16.6": "‘Sa-môn hạnh khó làm, Phạm hạnh khó làm.’",
  "dn8:16.7": "Và điều ấy một gia chủ, hay con trai gia chủ, thậm chí một nữ tỳ gánh nước, cũng có thể làm được:",
  "dn8:16.8": "‘Nào, ta sẽ là người lõa thể, sống phóng túng, liếm tay … chỉ chuyên chú thực hành hạnh ăn theo phiên, nửa tháng mới ăn một lần.’",
  "dn8:16.9": "Nhưng này Kassapa, chính vì ngoài mức ấy, ngoài sự khổ hạnh ấy, Sa-môn hạnh hay Phạm hạnh là điều khó làm, rất khó làm, nên lời nói này là hợp lý rằng:",
  "dn8:16.10": "‘Sa-môn hạnh khó làm, Phạm hạnh khó làm.’",
  "dn8:16.11": "Khi nào, này Kassapa, vị tỳ-kheo tu tập tâm từ không oán, không hại, và do đoạn tận các lậu hoặc, ngay trong hiện tại tự mình với thắng trí chứng ngộ, thành tựu và an trú vô lậu tâm giải thoát, tuệ giải thoát,",
  "dn8:16.12": "thì này Kassapa, vị tỳ-kheo ấy được gọi là Sa-môn, cũng được gọi là Bà-la-môn.",
  "dn8:16.13": "Này Kassapa, dù có là người ăn rau, ăn hạt kê … sống bằng rễ cây và trái rừng, ăn các trái rụng,",
  "dn8:16.14": "nếu chỉ với chừng ấy, với sự khổ hạnh ấy mà thành Sa-môn hay thành Bà-la-môn, khó làm, rất khó làm, thì lời nói này đã không hợp lý rằng:",
  "dn8:16.15": "‘Sa-môn hạnh khó làm, Phạm hạnh khó làm.’",
  "dn8:16.16": "Và điều ấy một gia chủ, hay con trai gia chủ, thậm chí một nữ tỳ gánh nước, cũng có thể làm được:",
  "dn8:16.17": "‘Nào, ta sẽ là người ăn rau, hay ăn hạt kê … sống bằng rễ cây và trái rừng, ăn các trái rụng.’",
  "dn8:16.18": "Nhưng này Kassapa, chính vì ngoài mức ấy, ngoài sự khổ hạnh ấy, Sa-môn hạnh hay Phạm hạnh là điều khó làm, rất khó làm, nên lời nói này là hợp lý rằng:",
  "dn8:16.19": "‘Sa-môn hạnh khó làm, Phạm hạnh khó làm.’",
  "dn8:16.20": "Khi nào, này Kassapa, vị tỳ-kheo tu tập tâm từ không oán, không hại, và do đoạn tận các lậu hoặc, ngay trong hiện tại tự mình với thắng trí chứng ngộ, thành tựu và an trú vô lậu tâm giải thoát, tuệ giải thoát,",
  "dn8:16.21": "thì này Kassapa, vị tỳ-kheo ấy được gọi là Sa-môn, cũng được gọi là Bà-la-môn.",
  "dn8:16.22": "Này Kassapa, dù có mặc vải gai, mặc cả vải thô … còn chuyên chú thực hành việc xuống nước tắm đến ba lần vào buổi chiều,",
  "dn8:16.23": "nếu chỉ với chừng ấy, với sự khổ hạnh ấy mà thành Sa-môn hay thành Bà-la-môn, khó làm, rất khó làm, thì lời nói này đã không hợp lý rằng:",
  "dn8:16.24": "‘Sa-môn hạnh khó làm, Phạm hạnh khó làm.’",
  "dn8:16.25": "Và điều ấy một gia chủ, hay con trai gia chủ, thậm chí một nữ tỳ gánh nước, cũng có thể làm được:",
  "dn8:16.26": "‘Nào, ta sẽ mặc vải gai, mặc cả vải thô … còn chuyên chú thực hành việc xuống nước tắm đến ba lần vào buổi chiều.’",
  "dn8:16.27": "Nhưng này Kassapa, chính vì ngoài mức ấy, ngoài sự khổ hạnh ấy, Sa-môn hạnh hay Phạm hạnh là điều khó làm, rất khó làm, nên lời nói này là hợp lý rằng:",
  "dn8:16.28": "‘Sa-môn hạnh khó làm, Phạm hạnh khó làm.’",
  "dn8:16.29": "Khi nào, này Kassapa, vị tỳ-kheo tu tập tâm từ không oán, không hại, và do đoạn tận các lậu hoặc, ngay trong hiện tại tự mình với thắng trí chứng ngộ, thành tựu và an trú vô lậu tâm giải thoát, tuệ giải thoát,",
  "dn8:16.30": "thì này Kassapa, vị tỳ-kheo ấy được gọi là Sa-môn, cũng được gọi là Bà-la-môn.”",
  "dn8:17.1": "Khi được nói vậy, Kassapa lõa thể bạch Thế Tôn rằng:",
  "dn8:17.2": "“Thưa Tôn giả Gotama, Sa-môn thật khó biết, Bà-la-môn thật khó biết.”",
  "dn8:17.3": "“Này Kassapa, trong đời người ta thường nói: ‘Sa-môn khó biết, Bà-la-môn khó biết.’",
  "dn8:17.4": "Này Kassapa, dù có là người lõa thể, sống phóng túng, liếm tay … chỉ chuyên chú thực hành hạnh ăn theo phiên, nửa tháng mới ăn một lần,",
  "dn8:17.5": "nếu chỉ với chừng ấy, với sự khổ hạnh ấy mà Sa-môn hay Bà-la-môn là điều khó biết, rất khó biết, thì lời nói này đã không hợp lý rằng:",
  "dn8:17.6": "‘Sa-môn khó biết, Bà-la-môn khó biết.’",
  "dn8:17.7": "Và điều ấy một gia chủ, hay con trai gia chủ, thậm chí một nữ tỳ gánh nước, cũng có thể biết được:",
  "dn8:17.8": "‘Người này là kẻ lõa thể, sống phóng túng, liếm tay … chỉ chuyên chú thực hành hạnh ăn theo phiên, nửa tháng mới ăn một lần.’",
  "dn8:17.9": "Nhưng này Kassapa, chính vì ngoài mức ấy, ngoài sự khổ hạnh ấy, Sa-môn hay Bà-la-môn là điều khó biết, rất khó biết, nên lời nói này là hợp lý rằng:",
  "dn8:17.10": "‘Sa-môn khó biết, Bà-la-môn khó biết.’",
  "dn8:17.11": "Khi nào, này Kassapa, vị tỳ-kheo tu tập tâm từ không oán, không hại, và do đoạn tận các lậu hoặc, ngay trong hiện tại tự mình với thắng trí chứng ngộ, thành tựu và an trú vô lậu tâm giải thoát, tuệ giải thoát,",
  "dn8:17.12": "thì này Kassapa, vị tỳ-kheo ấy được gọi là Sa-môn, cũng được gọi là Bà-la-môn.",
  "dn8:17.13": "Này Kassapa, dù có là người ăn rau, ăn hạt kê … sống bằng rễ cây và trái rừng, ăn các trái rụng,",
  "dn8:17.14": "nếu chỉ với chừng ấy, với sự khổ hạnh ấy mà Sa-môn hay Bà-la-môn là điều khó biết, rất khó biết, thì lời nói này đã không hợp lý rằng:",
  "dn8:17.15": "‘Sa-môn khó biết, Bà-la-môn khó biết.’",
  "dn8:17.16": "Và điều ấy một gia chủ, hay con trai gia chủ, thậm chí một nữ tỳ gánh nước, cũng có thể biết được:",
  "dn8:17.17": "‘Người này là kẻ ăn rau hay ăn hạt kê … sống bằng rễ cây và trái rừng, ăn các trái rụng.’",
  "dn8:17.18": "Nhưng này Kassapa, chính vì ngoài mức ấy, ngoài sự khổ hạnh ấy, Sa-môn hay Bà-la-môn là điều khó biết, rất khó biết, nên lời nói này là hợp lý rằng:",
  "dn8:17.19": "‘Sa-môn khó biết, Bà-la-môn khó biết.’",
  "dn8:17.20": "Khi nào, này Kassapa, vị tỳ-kheo tu tập tâm từ không oán, không hại, và do đoạn tận các lậu hoặc, ngay trong hiện tại tự mình với thắng trí chứng ngộ, thành tựu và an trú vô lậu tâm giải thoát, tuệ giải thoát,",
  "dn8:17.21": "thì này Kassapa, vị tỳ-kheo ấy được gọi là Sa-môn, cũng được gọi là Bà-la-môn.",
  "dn8:17.22": "Này Kassapa, dù có mặc vải gai, mặc cả vải thô … còn chuyên chú thực hành việc xuống nước tắm đến ba lần vào buổi chiều,",
  "dn8:17.23": "nếu chỉ với chừng ấy, với sự khổ hạnh ấy mà Sa-môn hay Bà-la-môn là điều khó biết, rất khó biết, thì lời nói này đã không hợp lý rằng:",
  "dn8:17.24": "‘Sa-môn khó biết, Bà-la-môn khó biết.’",
  "dn8:17.25": "Và điều ấy một gia chủ, hay con trai gia chủ, thậm chí một nữ tỳ gánh nước, cũng có thể biết được:",
  "dn8:17.26": "‘Người này mặc vải gai, mặc cả vải thô … còn chuyên chú thực hành việc xuống nước tắm đến ba lần vào buổi chiều.’",
  "dn8:17.27": "Nhưng này Kassapa, chính vì ngoài mức ấy, ngoài sự khổ hạnh ấy, Sa-môn hay Bà-la-môn là điều khó biết, rất khó biết, nên lời nói này là hợp lý rằng:",
  "dn8:17.28": "‘Sa-môn khó biết, Bà-la-môn khó biết.’",
  "dn8:17.29": "Khi nào, này Kassapa, vị tỳ-kheo tu tập tâm từ không oán, không hại, và do đoạn tận các lậu hoặc, ngay trong hiện tại tự mình với thắng trí chứng ngộ, thành tựu và an trú vô lậu tâm giải thoát, tuệ giải thoát,",
  "dn8:17.30": "thì này Kassapa, vị tỳ-kheo ấy được gọi là Sa-môn, cũng được gọi là Bà-la-môn.”",
  "dn8:18.0": "5. Thành tựu giới, định, tuệ",
  "dn8:18.1": "Khi được nói vậy, Kassapa lõa thể bạch Thế Tôn rằng:",
  "dn8:18.2": "“Nhưng thưa Tôn giả Gotama, thế nào là thành tựu giới, thế nào là thành tựu tâm, thế nào là thành tựu tuệ?”",
  "dn8:18.3": "“Này Kassapa, ở đây Như Lai xuất hiện ở đời, là bậc A-la-hán, Chánh Đẳng Giác …",
  "dn8:18.4": "thấy sợ hãi trong những lỗi nhỏ nhặt, thọ trì học tập trong các học giới, đầy đủ thiện hạnh về thân và khẩu, nuôi mạng thanh tịnh, thành tựu giới, phòng hộ các căn, đầy đủ chánh niệm tỉnh giác, biết đủ.",
  "dn8:18.5": "Và này Kassapa, thế nào là vị tỳ-kheo thành tựu giới?",
  "dn8:18.6": "Này Kassapa, ở đây vị tỳ-kheo từ bỏ sát sinh, tránh xa sát sinh, bỏ trượng, bỏ kiếm, biết tàm quý, có lòng từ, sống thương xót lợi ích cho tất cả chúng sinh.",
  "dn8:18.7": "Điều này thuộc về thành tựu giới của vị ấy …",
  "dn8:19.1": "Lại như có những Sa-môn, Bà-la-môn thọ dụng các món ăn do tín thí cúng dường, nhưng lại nuôi mạng bằng tà mạng, bằng các loại thuật số thấp hèn như vậy.",
  "dn8:19.2": "Tức là: làm lễ cầu an, làm lễ cầu may … chú thuật về các dược thảo,",
  "dn8:19.3": "vị ấy tránh xa việc nuôi mạng tà vạy bằng các loại thuật số thấp hèn như vậy.",
  "dn8:19.4": "Điều này thuộc về thành tựu giới của vị ấy.",
  "dn8:19.5": "Này Kassapa, vị tỳ-kheo thành tựu giới như vậy không thấy có sợ hãi từ đâu, do sự phòng hộ bởi giới.",
  "dn8:19.6": "Ví như, này Kassapa, một vị vua Sát-đế-lỵ đã làm lễ quán đảnh, đã dẹp yên các địch thủ, không thấy có sợ hãi từ đâu do phía kẻ thù;",
  "dn8:19.7": "cũng vậy, này Kassapa, vị tỳ-kheo thành tựu giới như vậy không thấy có sợ hãi từ đâu, do sự phòng hộ bởi giới.",
  "dn8:19.8": "Vị ấy, đầy đủ uẩn giới thánh này, cảm nhận lạc thọ không lỗi lầm ở nội tâm.",
  "dn8:19.9": "Này Kassapa, như vậy là vị tỳ-kheo thành tựu giới.",
  "dn8:19.10": "Này Kassapa, đây là thành tựu giới …",
  "dn8:19.11": "vị ấy chứng và an trú sơ thiền.",
  "dn8:19.12": "Điều này thuộc về thành tựu tâm của vị ấy …",
  "dn8:19.13": "nhị thiền …",
  "dn8:19.14": "tam thiền …",
  "dn8:19.15": "vị ấy chứng và an trú tứ thiền.",
  "dn8:19.16": "Điều này thuộc về thành tựu tâm của vị ấy.",
  "dn8:19.17": "Này Kassapa, đây là thành tựu tâm.",
  "dn8:20.1": "Với tâm định tĩnh như vậy …",
  "dn8:20.2": "vị ấy hướng tâm, nghiêng tâm đến trí và kiến …",
  "dn8:20.3": "điều này thuộc về thành tựu tuệ của vị ấy …",
  "dn8:20.4": "vị ấy biết: ‘Không còn trở lui trạng thái này nữa.’",
  "dn8:20.5": "Điều này thuộc về thành tựu tuệ của vị ấy.",
  "dn8:20.6": "Này Kassapa, đây là thành tựu tuệ.",
  "dn8:20.7": "Và này Kassapa, ngoài thành tựu giới này, thành tựu tâm này, thành tựu tuệ này, không có thành tựu giới nào khác, thành tựu tâm nào khác, thành tựu tuệ nào khác cao hơn hay thù thắng hơn.",
  "dn8:21.0": "6. Luận về tiếng rống sư tử",
  "dn8:21.1": "Này Kassapa, có một số Sa-môn, Bà-la-môn chủ trương về giới.",
  "dn8:21.2": "Họ dùng nhiều cách để tán thán giới.",
  "dn8:21.3": "Này Kassapa, trong phạm vi giới tối thượng của bậc Thánh, Ta không thấy ai ngang bằng với Ta, huống chi hơn Ta.",
  "dn8:21.4": "Hơn nữa, chính Ta còn vượt trội trong phương diện tăng thượng giới.",
  "dn8:21.5": "Này Kassapa, có một số sa-môn, bà-la-môn chủ trương sự ghê sợ điều ác.",
  "dn8:21.6": "Họ dùng nhiều cách để tán thán sự ghê sợ điều ác.",
  "dn8:21.7": "Này Kassapa, trong phạm vi sự ghê sợ điều ác tối thượng của bậc Thánh, Ta không thấy ai ngang bằng với Ta, huống chi hơn Ta.",
  "dn8:21.8": "Hơn nữa, chính Ta còn vượt trội trong phương diện tăng thượng ghê sợ điều ác.",
  "dn8:21.9": "Này Kassapa, có một số sa-môn, bà-la-môn chủ trương trí tuệ.",
  "dn8:21.10": "Họ dùng nhiều cách để tán thán trí tuệ.",
  "dn8:21.11": "Này Kassapa, trong phạm vi trí tuệ tối thượng của bậc Thánh, Ta không thấy ai ngang bằng với Ta, huống chi hơn Ta.",
  "dn8:21.12": "Hơn nữa, chính Ta còn vượt trội trong phương diện tăng thượng tuệ.",
  "dn8:21.13": "Này Kassapa, có một số sa-môn, bà-la-môn chủ trương giải thoát.",
  "dn8:21.14": "Họ dùng nhiều cách để tán thán giải thoát.",
  "dn8:21.15": "Này Kassapa, trong phạm vi giải thoát tối thượng của bậc Thánh, Ta không thấy ai ngang bằng với Ta, huống chi hơn Ta.",
  "dn8:21.16": "Hơn nữa, chính Ta còn vượt trội trong phương diện tăng thượng giải thoát.",
  "dn8:22.1": "Này Kassapa, có thể xảy ra trường hợp các du sĩ ngoại đạo nói như vầy:",
  "dn8:22.2": "‘Sa-môn Gotama có thốt lên tiếng rống sư tử, nhưng chỉ thốt lên trong chỗ trống vắng, không thốt lên giữa hội chúng.’",
  "dn8:22.3": "Với họ, các ông nên nói: ‘Chớ nói như vậy.’",
  "dn8:22.4": "Này Kassapa, hãy nói với họ như vầy: ‘Sa-môn Gotama có thốt lên tiếng rống sư tử, và cũng thốt lên giữa hội chúng.’",
  "dn8:22.5": "Này Kassapa, có thể xảy ra trường hợp các du sĩ ngoại đạo nói như vầy:",
  "dn8:22.6": "‘Sa-môn Gotama có thốt lên tiếng rống sư tử, có thốt lên giữa hội chúng, nhưng không thốt lên một cách tự tin.’",
  "dn8:22.7": "Với họ, các ông nên nói: ‘Chớ nói như vậy.’",
  "dn8:22.8": "Này Kassapa, hãy nói với họ như vầy: ‘Sa-môn Gotama có thốt lên tiếng rống sư tử, có thốt lên giữa hội chúng, và thốt lên một cách tự tin.’",
  "dn8:22.9": "Này Kassapa, có thể xảy ra trường hợp các du sĩ ngoại đạo nói như vầy:",
  "dn8:22.10": "‘Sa-môn Gotama có thốt lên tiếng rống sư tử, có thốt lên giữa hội chúng, có thốt lên một cách tự tin, nhưng không ai hỏi Ngài câu hỏi nào …",
  "dn8:22.11": "người ta có hỏi Ngài câu hỏi; nhưng khi được hỏi, Ngài không trả lời câu hỏi của họ …",
  "dn8:22.12": "khi được hỏi, Ngài có trả lời câu hỏi của họ; nhưng với lời giải đáp ấy, Ngài không làm cho tâm họ hoan hỷ …",
  "dn8:22.13": "với lời giải đáp ấy, Ngài có làm cho tâm họ hoan hỷ; nhưng họ không cho là đáng nghe …",
  "dn8:22.14": "họ cho là đáng nghe; nhưng sau khi nghe, họ không sinh lòng tin tưởng …",
  "dn8:22.15": "sau khi nghe, họ có sinh lòng tin tưởng; nhưng họ không biểu lộ sự tín thành …",
  "dn8:22.16": "họ có biểu lộ sự tín thành; nhưng họ không thực hành đúng theo đó …",
  "dn8:22.17": "họ có thực hành đúng theo đó; nhưng khi đã thực hành, họ không thành tựu.’",
  "dn8:22.18": "Với họ, các ông nên nói: ‘Chớ nói như vậy.’",
  "dn8:22.19": "Này Kassapa, hãy nói với họ như vầy: ‘Sa-môn Gotama có thốt lên tiếng rống sư tử, có thốt lên giữa hội chúng, có thốt lên một cách tự tin, người ta có hỏi Ngài câu hỏi, khi được hỏi Ngài có trả lời câu hỏi của họ, với lời giải đáp ấy Ngài làm cho tâm họ hoan hỷ, họ cho là đáng nghe, sau khi nghe họ sinh lòng tin tưởng, họ biểu lộ sự tín thành, họ thực hành đúng theo đó, và khi đã thực hành, họ thành tựu.’",
  "dn8:23.0": "7. Luận về thời gian thử thách đối với người từ ngoại đạo đến",
  "dn8:23.1": "Này Kassapa, có một thời Ta trú tại Rājagaha, trên núi Gijjhakūṭa.",
  "dn8:23.2": "Tại đó, một vị tu khổ hạnh phạm hạnh tên là Nigrodha đã hỏi Ta về tăng thượng ghê sợ điều ác.",
  "dn8:23.3": "Khi được hỏi về tăng thượng ghê sợ điều ác, Ta đã trả lời cho ông ấy.",
  "dn8:23.4": "Và khi Ta đã giải đáp, ông ấy hoan hỷ, vui mừng tột bậc.",
  "dn8:23.5": "‘Bạch Thế Tôn, ai mà sau khi nghe Pháp của Thế Tôn lại không hoan hỷ, vui mừng tột bậc?",
  "dn8:23.6": "Chính con nữa, bạch Thế Tôn, sau khi nghe Pháp của Thế Tôn, cũng hoan hỷ, vui mừng tột bậc.",
  "dn8:23.7": "Thật vi diệu thay, bạch Thế Tôn, thật vi diệu thay, bạch Thế Tôn.",
  "dn8:23.8": "Ví như, bạch Thế Tôn, người ta dựng đứng lại vật bị úp xuống, mở ra vật bị che kín, chỉ đường cho người lạc lối, đem đèn vào trong bóng tối để những ai có mắt có thể thấy các sắc; cũng vậy, Thế Tôn đã dùng nhiều cách thuyết rõ Chánh pháp.",
  "dn8:23.9": "Con xin quy y Thế Tôn, quy y Pháp và quy y Tỳ-kheo Tăng.",
  "dn8:23.10": "Bạch Thế Tôn, mong con được xuất gia trong sự hiện diện của Thế Tôn, mong được thọ đại giới.’",
  "dn8:24.1": "‘Này Kassapa, người nào trước đây thuộc ngoại đạo mà trong pháp luật này mong được xuất gia, mong được thọ đại giới, thì phải sống thử thách bốn tháng; sau bốn tháng, nếu các Tỳ-kheo hài lòng, họ cho xuất gia, cho thọ đại giới để thành Tỳ-kheo.",
  "dn8:24.2": "Tuy vậy, trong trường hợp này Ta biết có sự sai khác giữa các hạng người.’",
  "dn8:24.3": "‘Bạch Thế Tôn, nếu những người trước đây thuộc ngoại đạo mà trong pháp luật này mong được xuất gia, mong được thọ đại giới, phải sống thử thách bốn tháng; sau bốn tháng, nếu các Tỳ-kheo hài lòng, họ cho xuất gia, cho thọ đại giới để thành Tỳ-kheo, thì con sẽ sống thử thách bốn năm; sau bốn năm, mong các Tỳ-kheo hài lòng cho con xuất gia, cho con thọ đại giới để thành Tỳ-kheo.’",
  "dn8:24.4": "Rồi Kassapa lõa thể đã được xuất gia trong sự hiện diện của Thế Tôn, đã được thọ đại giới.",
  "dn8:24.5": "Không bao lâu sau khi thọ đại giới, Tôn giả Kassapa sống một mình, viễn ly, không phóng dật, nhiệt tâm, tinh cần, chẳng bao lâu đã tự mình với thắng trí chứng ngộ, chứng đạt và an trú ngay trong hiện tại cứu cánh vô thượng của phạm hạnh, vì mục đích ấy mà các thiện nam tử chân chánh từ bỏ gia đình, sống không gia đình, xuất gia.",
  "dn8:24.6": "Ngài đã tự biết: ‘Sanh đã tận, phạm hạnh đã thành, việc cần làm đã làm xong, không còn trở lui trạng thái này nữa.’",
  "dn8:24.7": "Và Tôn giả Kassapa đã trở thành một vị A-la-hán.",
  "dn8:24.8": "Kinh Đại Sư Tử Hống thứ tám chấm dứt."
}
window.BILARA["dn08"]["vi"]["dn08:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
