window.BILARA = window.BILARA || {};
window.BILARA["dn11"] = window.BILARA["dn11"] || {};
window.BILARA["dn11"]["vi"] = {
  "dn11:0.1": "Trường Bộ Kinh 11 ",
  "dn11:0.2": "Kinh Kevaṭṭa ",
  "dn11:1.1": "Tôi nghe như vầy—",
  "dn11:1.2": "một thời Thế Tôn trú tại Nāḷandā, trong vườn xoài của Pāvārika. ",
  "dn11:1.3": "Bấy giờ Kevaṭṭa, con trai một gia chủ, đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, Kevaṭṭa, con trai gia chủ, bạch Thế Tôn rằng: ",
  "dn11:1.4": "“Bạch Thế Tôn, thành Nāḷandā này phồn thịnh, sung túc, đông dân, đầy người, và có lòng tin sâu đậm nơi Thế Tôn. ",
  "dn11:1.5": "Lành thay, bạch Thế Tôn, xin Thế Tôn chỉ định một vị tỳ-kheo thực hiện thần thông vượt ngoài pháp của loài người; ",
  "dn11:1.6": "như vậy thành Nāḷandā này sẽ càng thêm tín kính Thế Tôn hơn nữa.”",
  "dn11:1.7": "Khi được nói vậy, Thế Tôn bảo Kevaṭṭa, con trai gia chủ rằng: ",
  "dn11:1.8": "“Này Kevaṭṭa, Ta không thuyết dạy các tỳ-kheo pháp như vầy: ",
  "dn11:1.9": "‘Này các tỳ-kheo, hãy đi làm phép lạ thần thông vượt ngoài pháp của loài người cho các cư sĩ mặc y trắng xem.’”",
  "dn11:2.1": "Lần thứ hai, Kevaṭṭa, con trai gia chủ, bạch Thế Tôn rằng: ",
  "dn11:2.2": "“Bạch Thế Tôn, con không ép buộc Thế Tôn; ",
  "dn11:2.3": "nhưng con chỉ nói rằng: ",
  "dn11:2.4": "‘Bạch Thế Tôn, thành Nāḷandā này phồn thịnh, sung túc, đông dân, đầy người, và có lòng tin sâu đậm nơi Thế Tôn. ",
  "dn11:2.5": "Lành thay, bạch Thế Tôn, xin Thế Tôn chỉ định một vị tỳ-kheo thực hiện thần thông vượt ngoài pháp của loài người; ",
  "dn11:2.6": "như vậy thành Nāḷandā này sẽ càng thêm tín kính Thế Tôn hơn nữa.’”",
  "dn11:2.7": "Lần thứ hai, Thế Tôn bảo Kevaṭṭa, con trai gia chủ rằng: ",
  "dn11:2.8": "“Này Kevaṭṭa, Ta không thuyết dạy các tỳ-kheo pháp như vầy: ",
  "dn11:2.9": "‘Này các tỳ-kheo, hãy đi làm phép lạ thần thông vượt ngoài pháp của loài người cho các cư sĩ mặc y trắng xem.’”",
  "dn11:3.1": "Lần thứ ba, Kevaṭṭa, con trai gia chủ, bạch Thế Tôn rằng: ",
  "dn11:3.2": "“Bạch Thế Tôn, con không ép buộc Thế Tôn; ",
  "dn11:3.3": "nhưng con chỉ nói rằng: ",
  "dn11:3.4": "‘Bạch Thế Tôn, thành Nāḷandā này phồn thịnh, sung túc, đông dân, đầy người, và có lòng tin sâu đậm nơi Thế Tôn. ",
  "dn11:3.5": "Lành thay, bạch Thế Tôn, xin Thế Tôn chỉ định một vị tỳ-kheo thực hiện thần thông vượt ngoài pháp của loài người. ",
  "dn11:3.6": "Như vậy thành Nāḷandā này sẽ càng thêm tín kính Thế Tôn hơn nữa.’”",
  "dn11:3.7.0": "1. Phép lạ thần thông ",
  "dn11:3.8": "“Này Kevaṭṭa, có ba loại phép lạ này do Ta tự mình chứng ngộ với thắng trí và tuyên thuyết. ",
  "dn11:3.9": "Ba loại ấy là gì? ",
  "dn11:3.10": "Phép lạ thần thông, phép lạ biết tâm, và phép lạ giáo huấn. ",
  "dn11:4.1": "Và này Kevaṭṭa, thế nào là phép lạ thần thông? ",
  "dn11:4.2": "Ở đây, này Kevaṭṭa, một vị tỳ-kheo chứng đạt nhiều loại thần thông khác nhau—một thân hiện thành nhiều thân, nhiều thân hiện thành một thân; hiện ra rồi biến mất; đi xuyên qua tường, xuyên qua thành, xuyên qua núi không bị ngăn ngại như đi trong hư không; trồi lên lặn xuống trong đất như trong nước; đi trên nước không chìm như đi trên đất; ngồi kiết già bay giữa hư không như chim có cánh; dùng tay chạm đến, xoa được mặt trăng và mặt trời, những vật có đại thần lực, đại oai lực như vậy; thân có thể tự tại cho đến cõi Phạm thiên. ",
  "dn11:4.3": "Rồi một người nào đó có lòng tin, có tín tâm, thấy vị tỳ-kheo ấy chứng đạt nhiều loại thần thông khác nhau—một thân hiện thành nhiều thân, nhiều thân hiện thành một thân; hiện ra rồi biến mất; đi xuyên qua tường, xuyên qua thành, xuyên qua núi không bị ngăn ngại như đi trong hư không; trồi lên lặn xuống trong đất như trong nước; đi trên nước không chìm như đi trên đất; ngồi kiết già bay giữa hư không như chim có cánh; dùng tay chạm đến, xoa được mặt trăng và mặt trời, những vật có đại thần lực, đại oai lực như vậy; thân có thể tự tại cho đến cõi Phạm thiên. ",
  "dn11:4.4": "Người ấy liền thuật lại cho một người khác không có lòng tin, không có tín tâm rằng: ",
  "dn11:4.5": "‘Thật kỳ diệu thay, thưa bạn, thật hy hữu thay, thưa bạn, thần lực lớn lao, oai lực lớn lao của vị sa-môn! ",
  "dn11:4.6": "Tôi đã thấy một vị tỳ-kheo chứng đạt nhiều loại thần thông khác nhau—một thân hiện thành nhiều thân, nhiều thân hiện thành một thân … cho đến thân có thể tự tại cho đến cõi Phạm thiên.’ ",
  "dn11:5.1": "Người không có lòng tin, không có tín tâm ấy có thể nói với người có lòng tin, có tín tâm kia như vầy: ",
  "dn11:5.2": "‘Này bạn, có một loại chú thuật tên là Gandhārī. ",
  "dn11:5.3": "Nhờ đó vị tỳ-kheo ấy chứng đạt nhiều loại thần thông khác nhau—một thân hiện thành nhiều thân, nhiều thân hiện thành một thân … cho đến thân có thể tự tại cho đến cõi Phạm thiên.’ ",
  "dn11:5.4": "Này Kevaṭṭa, ông nghĩ sao, ",
  "dn11:5.5": "người không có lòng tin, không có tín tâm ấy có nói với người có lòng tin, có tín tâm kia như vậy không?”",
  "dn11:5.6": "“Thưa có, bạch Thế Tôn.”",
  "dn11:5.7": "“Này Kevaṭṭa, thấy rõ sự nguy hại trong phép lạ thần thông này, Ta chán ngán, hổ thẹn, ghê sợ đối với phép lạ thần thông. ",
  "dn11:6.0": "2. Phép lạ biết tâm ",
  "dn11:6.1": "Và này Kevaṭṭa, thế nào là phép lạ biết tâm? ",
  "dn11:6.2": "Ở đây, này Kevaṭṭa, một vị tỳ-kheo nói rõ được tâm của các chúng sinh khác, của các cá nhân khác, nói rõ được trạng thái tâm, nói rõ được điều đang suy nghĩ, nói rõ được điều đang tư duy: ",
  "dn11:6.3": "‘Tâm của ông là như vậy, tâm của ông là thế kia, tâm của ông là như thế đó.’ ",
  "dn11:6.4": "Rồi một người nào đó có lòng tin, có tín tâm, thấy vị tỳ-kheo ấy nói rõ được tâm của các chúng sinh khác, của các cá nhân khác, nói rõ được trạng thái tâm, nói rõ được điều đang suy nghĩ, nói rõ được điều đang tư duy: ",
  "dn11:6.5": "‘Tâm của ông là như vậy, tâm của ông là thế kia, tâm của ông là như thế đó.’ ",
  "dn11:6.6": "Người ấy liền thuật lại cho một người khác không có lòng tin, không có tín tâm rằng: ",
  "dn11:6.7": "‘Thật kỳ diệu thay, thưa bạn, thật hy hữu thay, thưa bạn, thần lực lớn lao, oai lực lớn lao của vị sa-môn! ",
  "dn11:6.8": "Tôi đã thấy một vị tỳ-kheo nói rõ được tâm của các chúng sinh khác, của các cá nhân khác, nói rõ được trạng thái tâm, nói rõ được điều đang suy nghĩ, nói rõ được điều đang tư duy: ",
  "dn11:6.9": "“Tâm của ông là như vậy, tâm của ông là thế kia, tâm của ông là như thế đó.”’ ",
  "dn11:7.1": "Người không có lòng tin, không có tín tâm ấy có thể nói với người có lòng tin, có tín tâm kia như vầy: ",
  "dn11:7.2": "‘Này bạn, có một loại chú thuật tên là Maṇikā; ",
  "dn11:7.3": "nhờ đó vị tỳ-kheo ấy nói rõ được tâm của các chúng sinh khác, của các cá nhân khác, nói rõ được trạng thái tâm, nói rõ được điều đang suy nghĩ, nói rõ được điều đang tư duy: ",
  "dn11:7.4": "“Tâm của ông là như vậy, tâm của ông là thế kia, tâm của ông là như thế đó.”’ ",
  "dn11:7.5": "Này Kevaṭṭa, ông nghĩ sao, ",
  "dn11:7.6": "người không có lòng tin, không có tín tâm ấy có nói với người có lòng tin, có tín tâm kia như vậy không?”",
  "dn11:7.7": "“Thưa có, bạch Thế Tôn.”",
  "dn11:7.8": "“Này Kevaṭṭa, thấy rõ sự nguy hại trong phép lạ biết tâm này, Ta chán ngán, hổ thẹn, ghê sợ đối với phép lạ biết tâm. ",
  "dn11:8.0": "3. Phép lạ giáo huấn ",
  "dn11:8.1": "Và này Kevaṭṭa, thế nào là phép lạ giáo huấn? ",
  "dn11:8.2": "Ở đây, này Kevaṭṭa, một vị tỳ-kheo giáo huấn như vầy: ",
  "dn11:8.3": "‘Hãy suy nghĩ như vậy, đừng suy nghĩ như vậy; hãy tác ý như vậy, đừng tác ý như vậy; hãy từ bỏ điều này, hãy thành tựu và an trú trong điều này.’ ",
  "dn11:8.4": "Này Kevaṭṭa, đó gọi là phép lạ giáo huấn. ",
  "dn11:9-66.1": "Lại nữa, này Kevaṭṭa, ở đây Như Lai xuất hiện ở đời, là bậc A-la-hán, Chánh Đẳng Giác … ",
  "dn11:9-66.2": "Như vậy, này Kevaṭṭa, vị tỳ-kheo thành tựu giới hạnh … ",
  "dn11:9-66.3": "chứng và an trú thiền thứ nhất. ",
  "dn11:9-66.4": "Điều này cũng được gọi là phép lạ giáo huấn … ",
  "dn11:9-66.5": "thiền thứ hai … ",
  "dn11:9-66.6": "thiền thứ ba … ",
  "dn11:9-66.7": "chứng và an trú thiền thứ tư. ",
  "dn11:9-66.8": "Điều này cũng được gọi là phép lạ giáo huấn … ",
  "dn11:9-66.9": "hướng tâm, dẫn tâm đến tri kiến … ",
  "dn11:9-66.10": "điều này cũng được gọi là phép lạ giáo huấn … ",
  "dn11:9-66.11": "vị ấy biết rằng không còn trở lui trạng thái này nữa … ",
  "dn11:9-66.12": "điều này cũng được gọi là phép lạ giáo huấn. ",
  "dn11:67.1": "Này Kevaṭṭa, đó là ba loại phép lạ do Ta tự mình chứng ngộ với thắng trí và tuyên thuyết. ",
  "dn11:67.2.0": "4. Câu chuyện vị tỳ-kheo tìm nơi diệt tận của các đại chủng ",
  "dn11:67.3": "Này Kevaṭṭa, thuở xưa, ngay trong chúng tỳ-kheo này, một vị tỳ-kheo nọ khởi lên ý nghĩ như sau: ",
  "dn11:67.4": "‘Bốn đại chủng này diệt tận không còn dư tàn ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại?’ ",
  "dn11:68.1": "Rồi này Kevaṭṭa, vị tỳ-kheo ấy nhập một loại định như vậy, khiến khi tâm đã định tĩnh thì con đường đi đến chư thiên hiện ra. ",
  "dn11:68.2": "Rồi này Kevaṭṭa, vị tỳ-kheo ấy đi đến chỗ chư thiên Tứ Đại Vương; sau khi đến, nói với chư thiên Tứ Đại Vương rằng: ",
  "dn11:68.3": "‘Thưa chư hiền, bốn đại chủng này diệt tận không còn dư tàn ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại?’ ",
  "dn11:68.4": "Khi được hỏi vậy, này Kevaṭṭa, chư thiên Tứ Đại Vương nói với vị tỳ-kheo ấy rằng: ",
  "dn11:68.5": "‘Này tỳ-kheo, chúng tôi cũng không biết: ",
  "dn11:68.6": "“Bốn đại chủng này diệt tận không còn dư tàn ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại.” ",
  "dn11:68.7": "Nhưng này tỳ-kheo, có bốn vị Đại Vương cao thắng và thù diệu hơn chúng tôi. ",
  "dn11:68.8": "Các vị ấy có thể biết điều này: ",
  "dn11:68.9": "“Bốn đại chủng này diệt tận không còn dư tàn ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại.”’ ",
  "dn11:69.1": "Rồi này Kevaṭṭa, vị tỳ-kheo ấy đi đến chỗ bốn vị Đại Vương; sau khi đến, nói với bốn vị Đại Vương rằng: ",
  "dn11:69.2": "‘Thưa chư hiền, bốn đại chủng này diệt tận không còn dư tàn ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại?’ ",
  "dn11:69.3": "Khi được hỏi vậy, này Kevaṭṭa, bốn vị Đại Vương nói với vị tỳ-kheo ấy rằng: ",
  "dn11:69.4": "‘Này tỳ-kheo, chúng tôi cũng không biết: ",
  "dn11:69.5": "“Bốn đại chủng này diệt tận không còn dư tàn ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại.” ",
  "dn11:69.6": "Nhưng này tỳ-kheo, có chư thiên Tam Thập Tam cao thắng và thù diệu hơn chúng tôi. ",
  "dn11:69.7": "Các vị ấy có thể biết điều này: ",
  "dn11:69.8": "“Bốn đại chủng này diệt tận không còn dư tàn ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại.”’ ",
  "dn11:70.1": "Rồi này Kevaṭṭa, vị tỳ-kheo ấy đi đến chỗ chư thiên Tam Thập Tam; sau khi đến, nói với chư thiên Tam Thập Tam rằng: ",
  "dn11:70.2": "‘Này hiền hữu, bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại?’",
  "dn11:70.3": "Khi được nói vậy, này Kevaṭṭa, chư thiên cõi Tāvatiṁsa nói với vị tỳ-kheo ấy rằng:",
  "dn11:70.4": "‘Chúng tôi cũng không biết, này tỳ-kheo:",
  "dn11:70.5": "“bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại”.",
  "dn11:70.6": "Này tỳ-kheo, có Thiên chủ Đế Thích tên là Sakka, cao thắng và thù diệu hơn chúng tôi.",
  "dn11:70.7": "Vị ấy có thể biết điều này:",
  "dn11:70.8": "“bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại”’.",
  "dn11:71.1": "Rồi này Kevaṭṭa, vị tỳ-kheo ấy đi đến chỗ Thiên chủ Đế Thích Sakka; đến nơi, vị ấy nói với Thiên chủ Đế Thích Sakka rằng:",
  "dn11:71.2": "‘Này hiền hữu, bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại?’",
  "dn11:71.3": "Khi được nói vậy, này Kevaṭṭa, Thiên chủ Đế Thích Sakka nói với vị tỳ-kheo ấy rằng:",
  "dn11:71.4": "‘Ta cũng không biết, này tỳ-kheo:",
  "dn11:71.5": "“bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại”.",
  "dn11:72.1": "Này tỳ-kheo, có chư thiên tên là Yāmā …",
  "dn11:73.1": "có thiên tử tên là Suyāma …",
  "dn11:74.1": "có chư thiên tên là Tusitā …",
  "dn11:75.1": "có thiên tử tên là Santussita …",
  "dn11:76.1": "có chư thiên tên là Nimmānaratī …",
  "dn11:77.1": "có thiên tử tên là Sunimmita …",
  "dn11:77.2": "có chư thiên tên là Paranimmitavasavattī …",
  "dn11:78.1": "có thiên tử tên là Vasavattī, cao thắng và thù diệu hơn chúng tôi.",
  "dn11:78.2": "Vị ấy có thể biết điều này:",
  "dn11:78.3": "“bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại”’.",
  "dn11:79.1": "Rồi này Kevaṭṭa, vị tỳ-kheo ấy đi đến chỗ thiên tử Vasavattī; đến nơi, vị ấy nói với thiên tử Vasavattī rằng:",
  "dn11:79.2": "‘Này hiền hữu, bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại?’",
  "dn11:79.3": "Khi được nói vậy, này Kevaṭṭa, thiên tử Vasavattī nói với vị tỳ-kheo ấy rằng:",
  "dn11:79.4": "‘Ta cũng không biết, này tỳ-kheo:",
  "dn11:79.5": "“bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại”.",
  "dn11:79.6": "Này tỳ-kheo, có chư thiên tên là Brahmakāyikā, cao thắng và thù diệu hơn chúng tôi.",
  "dn11:79.7": "Các vị ấy có thể biết điều này:",
  "dn11:79.8": "“bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại”’.",
  "dn11:80.1": "Rồi này Kevaṭṭa, vị tỳ-kheo ấy nhập một định như vậy, khiến khi tâm đã định thì con đường dẫn đến Phạm thiên hiện ra.",
  "dn11:80.2": "Rồi này Kevaṭṭa, vị tỳ-kheo ấy đi đến chỗ chư thiên Brahmakāyikā; đến nơi, vị ấy nói với chư thiên Brahmakāyikā rằng:",
  "dn11:80.3": "‘Này hiền hữu, bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại?’",
  "dn11:80.4": "Khi được nói vậy, này Kevaṭṭa, chư thiên Brahmakāyikā nói với vị tỳ-kheo ấy rằng:",
  "dn11:80.5": "‘Chúng tôi cũng không biết, này tỳ-kheo:",
  "dn11:80.6": "“bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại”.",
  "dn11:80.7": "Này tỳ-kheo, có Phạm thiên, Đại Phạm thiên, bậc thắng phục, không bị ai thắng phục, toàn kiến, tự tại, chủ tể, hóa chủ, tối thượng, người sắp đặt, người điều ngự, cha của những gì đã sinh và sẽ sinh, cao thắng và thù diệu hơn chúng tôi.",
  "dn11:80.8": "Vị ấy có thể biết điều này:",
  "dn11:80.9": "“bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại”’.",
  "dn11:80.10": "‘Nhưng này hiền hữu, hiện giờ Đại Phạm thiên ấy ở đâu?’",
  "dn11:80.11": "‘Chúng tôi cũng không biết, này tỳ-kheo, Phạm thiên ở đâu, theo đường nào, hay tại chỗ nào;",
  "dn11:80.12": "nhưng này tỳ-kheo, khi các điềm hiện ra, ánh sáng phát sinh, hào quang xuất hiện, thì Phạm thiên sẽ hiện ra; vì đó là điềm báo trước cho sự hiện ra của Phạm thiên, tức là ánh sáng phát sinh, hào quang xuất hiện’.",
  "dn11:81.1": "Rồi này Kevaṭṭa, chẳng bao lâu sau Đại Phạm thiên ấy hiện ra.",
  "dn11:81.2": "Rồi này Kevaṭṭa, vị tỳ-kheo ấy đi đến chỗ Đại Phạm thiên ấy; đến nơi, vị ấy nói với Đại Phạm thiên ấy rằng:",
  "dn11:81.3": "‘Này hiền hữu, bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại?’",
  "dn11:81.4": "Khi được nói vậy, này Kevaṭṭa, Đại Phạm thiên ấy nói với vị tỳ-kheo ấy rằng:",
  "dn11:81.5": "‘Này tỳ-kheo, ta là Phạm thiên, Đại Phạm thiên, bậc thắng phục, không bị ai thắng phục, toàn kiến, tự tại, chủ tể, hóa chủ, tối thượng, người sắp đặt, người điều ngự, cha của những gì đã sinh và sẽ sinh’.",
  "dn11:82.1": "Lần thứ hai, này Kevaṭṭa, vị tỳ-kheo ấy nói với Đại Phạm thiên ấy rằng:",
  "dn11:82.2": "‘Này hiền hữu, tôi không hỏi ngài như vậy:",
  "dn11:82.3": "“ngài là Phạm thiên, Đại Phạm thiên, bậc thắng phục, không bị ai thắng phục, toàn kiến, tự tại, chủ tể, hóa chủ, tối thượng, người sắp đặt, người điều ngự, cha của những gì đã sinh và sẽ sinh”.",
  "dn11:82.4": "Mà này hiền hữu, tôi hỏi ngài như sau:",
  "dn11:82.5": "“bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại”?’",
  "dn11:82.6": "Lần thứ hai, này Kevaṭṭa, Đại Phạm thiên ấy nói với vị tỳ-kheo ấy rằng:",
  "dn11:82.7": "‘Này tỳ-kheo, ta là Phạm thiên, Đại Phạm thiên, bậc thắng phục, không bị ai thắng phục, toàn kiến, tự tại, chủ tể, hóa chủ, tối thượng, người sắp đặt, người điều ngự, cha của những gì đã sinh và sẽ sinh’.",
  "dn11:83.1": "Lần thứ ba, này Kevaṭṭa, vị tỳ-kheo ấy nói với Đại Phạm thiên ấy rằng:",
  "dn11:83.2": "‘Này hiền hữu, tôi không hỏi ngài như vậy:",
  "dn11:83.3": "“ngài là Phạm thiên, Đại Phạm thiên, bậc thắng phục, không bị ai thắng phục, toàn kiến, tự tại, chủ tể, hóa chủ, tối thượng, người sắp đặt, người điều ngự, cha của những gì đã sinh và sẽ sinh”.",
  "dn11:83.4": "Mà này hiền hữu, tôi hỏi ngài như sau:",
  "dn11:83.5": "“bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại”?’",
  "dn11:83.6": "Rồi này Kevaṭṭa, Đại Phạm thiên ấy nắm cánh tay vị tỳ-kheo ấy, đưa ra một bên và nói với vị tỳ-kheo ấy rằng:",
  "dn11:83.7": "‘Này tỳ-kheo, các chư thiên Brahmakāyikā này nghĩ về ta như sau: “Không có gì Phạm thiên không biết, không có gì Phạm thiên không thấy, không có gì Phạm thiên không hay, không có gì Phạm thiên không chứng”.",
  "dn11:83.8": "Vì thế ta đã không trả lời trước mặt họ.",
  "dn11:83.9": "Này tỳ-kheo, chính ta cũng không biết bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại.",
  "dn11:83.10": "Vậy nên, này tỳ-kheo, chính ngươi đã làm điều sai, chính ngươi đã lầm lỗi, khi bỏ qua Thế Tôn ấy mà đi tìm kiếm bên ngoài lời giải đáp cho câu hỏi này.",
  "dn11:83.11": "Hãy đi đi, này tỳ-kheo, đến chính Thế Tôn ấy mà hỏi câu hỏi này; Thế Tôn trả lời cho ngươi thế nào, hãy ghi nhớ như vậy’.",
  "dn11:84.1": "Rồi này Kevaṭṭa, vị tỳ-kheo ấy—ví như một người lực lưỡng co cánh tay đang duỗi ra, hay duỗi cánh tay đang co lại; cũng vậy, vị ấy biến mất khỏi cõi Phạm thiên và hiện ra trước mặt Ta.",
  "dn11:84.2": "Rồi này Kevaṭṭa, vị tỳ-kheo ấy đảnh lễ Ta rồi ngồi xuống một bên. Khi đã ngồi xuống một bên, vị tỳ-kheo ấy nói với Ta rằng:",
  "dn11:84.3": "‘Bạch Thế Tôn, bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại?’",
  "dn11:85.0": "4.1. Ví dụ con chim dò bờ",
  "dn11:85.1": "Khi được nói vậy, này Kevaṭṭa, Ta nói với vị tỳ-kheo ấy rằng—",
  "dn11:85.2": "Này tỳ-kheo, thuở xưa có những thương nhân đi biển mang theo một con chim dò bờ rồi cho thuyền đi vào đại dương.",
  "dn11:85.3": "Khi thuyền không còn thấy bờ, họ thả con chim dò bờ ra.",
  "dn11:85.4": "Nó bay về hướng đông, bay về hướng nam, bay về hướng tây, bay về hướng bắc, bay lên trên, bay theo các hướng phụ.",
  "dn11:85.5": "Nếu nó thấy bờ ở bất cứ phía nào, nó sẽ bay thẳng đến đó.",
  "dn11:85.6": "Nhưng nếu nó không thấy bờ ở bất cứ phía nào, nó lại quay về chính con thuyền ấy.",
  "dn11:85.7": "Cũng vậy, này tỳ-kheo, từ đây cho đến cõi Phạm thiên, ngươi tìm kiếm lời giải đáp cho câu hỏi này mà không đạt được, rồi lại quay về chính nơi Ta.",
  "dn11:85.8": "Này tỳ-kheo, câu hỏi ấy không nên được hỏi như vậy:",
  "dn11:85.9": "‘Bạch Thế Tôn, bốn đại này diệt tận không còn dư sót ở đâu, tức là địa đại, thủy đại, hỏa đại, phong đại?’",
  "dn11:85.10": "Mà này tỳ-kheo, câu hỏi ấy nên được hỏi như sau:",
  "dn11:85.11": "‘Ở đâu nước và đất,",
  "dn11:85.12": "lửa gió không chạm tới;",
  "dn11:85.13": "Ở đâu dài và ngắn,",
  "dn11:85.14": "nhỏ và lớn, đẹp và xấu;",
  "dn11:85.15": "Ở đâu danh và sắc,",
  "dn11:85.16": "đều chấm dứt không còn dư sót?’",
  "dn11:85.17": "Ở đây, lời giải đáp là:",
  "dn11:85.18": "‘Thức không hiển lộ,",
  "dn11:85.19": "vô biên, chiếu sáng khắp nơi;",
  "dn11:85.20": "Ở đây nước và đất,",
  "dn11:85.21": "lửa gió không chạm tới.",
  "dn11:85.22": "Ở đây dài và ngắn,",
  "dn11:85.23": "nhỏ và lớn, đẹp và xấu;",
  "dn11:85.24": "Ở đây danh và sắc,",
  "dn11:85.25": "đều chấm dứt không còn dư sót;",
  "dn11:85.26": "Do thức diệt tận,",
  "dn11:85.27": "mọi thứ ấy đều chấm dứt tại đây’”.",
  "dn11:85.28": "Thế Tôn đã nói như vậy.",
  "dn11:85.29": "Kevaṭṭa, con trai người gia chủ, hoan hỷ tín thọ lời Thế Tôn dạy.",
  "dn11:85.30": "Kinh Kevaṭṭa, thứ mười một, chấm dứt."
}
window.BILARA["dn11"]["vi"]["dn11:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
