window.BILARA = window.BILARA || {};
window.BILARA["dn13"] = window.BILARA["dn13"] || {};
window.BILARA["dn13"]["vi"] = {
  "dn13:0.1": "Trường Bộ Kinh 13 ",
  "dn13:0.2": "Kinh Tam Minh ",
  "dn13:1.1": "Tôi nghe như vầy—",
  "dn13:1.2": "Một thời, Thế Tôn du hành trong xứ Kosala cùng với đại chúng Tỳ-kheo khoảng năm trăm vị, và đã đến một làng Bà-la-môn của dân Kosala tên là Manasākaṭa. ",
  "dn13:1.3": "Tại đó, Thế Tôn trú ở Manasākaṭa, phía bắc Manasākaṭa, bên bờ sông Aciravatī, trong vườn xoài. ",
  "dn13:2.1": "Lúc bấy giờ, có nhiều vị Bà-la-môn đại phú hào nổi tiếng, nổi tiếng đang cư trú tại Manasākaṭa, như là—",
  "dn13:2.2": "Bà-la-môn Caṅkī, Bà-la-môn Tārukkha, Bà-la-môn Pokkharasāti, Bà-la-môn Jāṇusoṇi, Bà-la-môn Todeyya, và những vị Bà-la-môn đại phú hào nổi tiếng, nổi tiếng khác nữa. ",
  "dn13:3.1": "Bấy giờ, hai thanh niên Vāseṭṭha và Bhāradvāja trong khi đi dạo kinh hành, đi qua đi lại, đã khởi lên cuộc bàn luận về đường đúng và đường sai. ",
  "dn13:4.1": "Rồi thanh niên Vāseṭṭha nói như vầy: ",
  "dn13:4.2": "“Chính đây mới là con đường thẳng, đây là con đường trực tiếp, đưa đến giải thoát, dẫn người thực hành theo đó đến cộng trú với Phạm thiên, tức con đường được Bà-la-môn Pokkharasāti thuyết giảng.” ",
  "dn13:5.1": "Thanh niên Bhāradvāja cũng nói như vầy: ",
  "dn13:5.2": "“Chính đây mới là con đường thẳng, đây là con đường trực tiếp, đưa đến giải thoát, dẫn người thực hành theo đó đến cộng trú với Phạm thiên, tức con đường được Bà-la-môn Tārukkha thuyết giảng.” ",
  "dn13:6.1": "Thanh niên Vāseṭṭha không thể thuyết phục thanh niên Bhāradvāja, và thanh niên Bhāradvāja cũng không thể thuyết phục thanh niên Vāseṭṭha. ",
  "dn13:7.1": "Rồi thanh niên Vāseṭṭha nói với thanh niên Bhāradvāja: ",
  "dn13:7.2": "“Này Bhāradvāja, sa-môn Gotama, người con dòng họ Sakya, xuất gia từ dòng họ Sakya, hiện đang trú tại Manasākaṭa, phía bắc Manasākaṭa, bên bờ sông Aciravatī, trong vườn xoài. ",
  "dn13:7.3": "Và tiếng tốt đẹp này về Tôn giả Gotama đã được truyền đi như sau: ",
  "dn13:7.4": "‘Ngài là bậc Thế Tôn, A-la-hán, Chánh Đẳng Giác, đầy đủ minh và hạnh, Thiện Thệ, bậc hiểu rõ thế gian, bậc vô thượng điều ngự những người đáng được điều phục, bậc Đạo Sư của chư thiên và loài người, Phật, Thế Tôn.’ ",
  "dn13:7.5": "Nào, này Bhāradvāja, chúng ta hãy đến gặp sa-môn Gotama; sau khi đến, chúng ta sẽ hỏi sa-môn Gotama về vấn đề này. ",
  "dn13:7.6": "Sa-môn Gotama trả lời cho chúng ta thế nào, chúng ta sẽ ghi nhận như vậy.” ",
  "dn13:7.7": "“Vâng, này bạn,” thanh niên Bhāradvāja đáp lời thanh niên Vāseṭṭha. ",
  "dn13:8.0": "1. Bàn luận về đường đúng và đường sai ",
  "dn13:8.1": "Rồi hai thanh niên Vāseṭṭha và Bhāradvāja đi đến chỗ Thế Tôn; sau khi đến, họ chào hỏi thân thiện với Thế Tôn. ",
  "dn13:8.2": "Sau khi nói lên những lời chào hỏi thân tình đáng ghi nhớ, họ ngồi xuống một bên. Khi đã ngồi xuống một bên, thanh niên Vāseṭṭha bạch Thế Tôn như sau: ",
  "dn13:8.3": "“Thưa Tôn giả Gotama, ở đây, trong khi chúng tôi đi dạo kinh hành, đi qua đi lại, đã khởi lên cuộc bàn luận về đường đúng và đường sai. ",
  "dn13:8.4": "Tôi nói như vầy: ",
  "dn13:8.5": "‘Chính đây mới là con đường thẳng, đây là con đường trực tiếp, đưa đến giải thoát, dẫn người thực hành theo đó đến cộng trú với Phạm thiên, tức con đường được Bà-la-môn Pokkharasāti thuyết giảng.’ ",
  "dn13:8.6": "Thanh niên Bhāradvāja nói như vầy: ",
  "dn13:8.7": "‘Chính đây mới là con đường thẳng, đây là con đường trực tiếp, đưa đến giải thoát, dẫn người thực hành theo đó đến cộng trú với Phạm thiên, tức con đường được Bà-la-môn Tārukkha thuyết giảng.’ ",
  "dn13:8.8": "Ở đây, thưa Tôn giả Gotama, có sự tranh chấp, có sự tranh luận, có sự bất đồng quan điểm.” ",
  "dn13:9.1": "“Vậy là, này Vāseṭṭha, ông nói như vầy: ",
  "dn13:9.2": "‘Chính đây mới là con đường thẳng, đây là con đường trực tiếp, đưa đến giải thoát, dẫn người thực hành theo đó đến cộng trú với Phạm thiên, tức con đường được Bà-la-môn Pokkharasāti thuyết giảng.’ ",
  "dn13:9.3": "Còn thanh niên Bhāradvāja nói như vầy: ",
  "dn13:9.4": "‘Chính đây mới là con đường thẳng, đây là con đường trực tiếp, đưa đến giải thoát, dẫn người thực hành theo đó đến cộng trú với Phạm thiên, tức con đường được Bà-la-môn Tārukkha thuyết giảng.’ ",
  "dn13:9.5": "Vậy thì, này Vāseṭṭha, các ông tranh chấp về điều gì, tranh luận về điều gì, bất đồng quan điểm về điều gì?” ",
  "dn13:10.1": "“Về đường đúng và đường sai, thưa Tôn giả Gotama. ",
  "dn13:10.2": "Dù vậy, thưa Tôn giả Gotama, các Bà-la-môn vẫn chỉ bày nhiều con đường khác nhau: các Bà-la-môn Adḍhariya, các Bà-la-môn Tittiriya, các Bà-la-môn Chandoka, các Bà-la-môn Bavhārijjha; nhưng tất cả những con đường ấy đều đưa đến giải thoát, đều dẫn người thực hành theo đó đến cộng trú với Phạm thiên. ",
  "dn13:10.3": "Ví như, thưa Tôn giả Gotama, không xa một làng hay một thị trấn, dù có nhiều con đường khác nhau, nhưng tất cả những con đường ấy đều hội tụ về làng ấy; ",
  "dn13:10.4": "cũng vậy, thưa Tôn giả Gotama, dù các Bà-la-môn chỉ bày nhiều con đường khác nhau: các Bà-la-môn Adḍhariya, các Bà-la-môn Tittiriya, các Bà-la-môn Chandoka, các Bà-la-môn Bavhārijjha; nhưng tất cả những con đường ấy đều đưa đến giải thoát, đều dẫn người thực hành theo đó đến cộng trú với Phạm thiên.” ",
  "dn13:11.0": "2. Tra vấn thanh niên Vāseṭṭha ",
  "dn13:11.1": "“Ông nói rằng chúng đều dẫn đến sao, này Vāseṭṭha?” ",
  "dn13:11.2": "“Vâng, thưa Tôn giả Gotama, tôi nói rằng chúng đều dẫn đến.” ",
  "dn13:11.3": "“Ông nói rằng chúng đều dẫn đến sao, này Vāseṭṭha?” ",
  "dn13:11.4": "“Vâng, thưa Tôn giả Gotama, tôi nói rằng chúng đều dẫn đến.” ",
  "dn13:11.5": "“Ông nói rằng chúng đều dẫn đến sao, này Vāseṭṭha?” ",
  "dn13:11.6": "“Vâng, thưa Tôn giả Gotama, tôi nói rằng chúng đều dẫn đến.” ",
  "dn13:12.1": "“Nhưng này Vāseṭṭha, trong số các Bà-la-môn thông ba Vệ-đà ấy, có lấy một Bà-la-môn nào đã trực tiếp thấy Phạm thiên chăng?” ",
  "dn13:12.2": "“Không có việc ấy, thưa Tôn giả Gotama.” ",
  "dn13:12.3": "“Nhưng này Vāseṭṭha, trong số các Bà-la-môn thông ba Vệ-đà ấy, có lấy một vị thầy nào đã trực tiếp thấy Phạm thiên chăng?” ",
  "dn13:12.4": "“Không có việc ấy, thưa Tôn giả Gotama.” ",
  "dn13:12.5": "“Nhưng này Vāseṭṭha, trong số các Bà-la-môn thông ba Vệ-đà ấy, có lấy một vị thầy của thầy nào đã trực tiếp thấy Phạm thiên chăng?” ",
  "dn13:12.6": "“Không có việc ấy, thưa Tôn giả Gotama.” ",
  "dn13:12.7": "“Nhưng này Vāseṭṭha, trong số các Bà-la-môn thông ba Vệ-đà ấy, cho đến bảy đời thầy tổ, có ai đã trực tiếp thấy Phạm thiên chăng?” ",
  "dn13:12.8": "“Không có việc ấy, thưa Tôn giả Gotama.” ",
  "dn13:13.1": "“Nhưng này Vāseṭṭha, còn các vị tiên nhân thời xưa của các Bà-la-môn thông ba Vệ-đà, là những người sáng tác thần chú, truyền bá thần chú, mà ngày nay các Bà-la-môn thông ba Vệ-đà vẫn ca tụng, vẫn tụng đọc, lặp lại lời đã nói, đọc lại điều đã được đọc, tức là Aṭṭhaka, Vāmaka, Vāmadeva, Vessāmitta, Yamataggi, Aṅgīrasa, Bhāradvāja, Vāseṭṭha, Kassapa, Bhagu—",
  "dn13:13.2": "các vị ấy có từng nói như vầy chăng: ",
  "dn13:13.3": "‘Chúng tôi biết điều ấy, chúng tôi thấy điều ấy, nơi nào là Phạm thiên, đường nào đến Phạm thiên, Phạm thiên ở đâu’?” ",
  "dn13:13.4": "“Không có việc ấy, thưa Tôn giả Gotama.” ",
  "dn13:14.1": "“Vậy là, này Vāseṭṭha, trong số các Bà-la-môn thông ba Vệ-đà, không có lấy một Bà-la-môn nào đã trực tiếp thấy Phạm thiên. ",
  "dn13:14.2": "Không có lấy một vị thầy nào trong số các Bà-la-môn thông ba Vệ-đà đã trực tiếp thấy Phạm thiên. ",
  "dn13:14.3": "Không có lấy một vị thầy của thầy nào trong số các Bà-la-môn thông ba Vệ-đà đã trực tiếp thấy Phạm thiên. ",
  "dn13:14.4": "Không có ai trong số các Bà-la-môn thông ba Vệ-đà, cho đến bảy đời thầy tổ, đã trực tiếp thấy Phạm thiên. ",
  "dn13:14.5": "Ngay cả các vị tiên nhân thời xưa của các Bà-la-môn thông ba Vệ-đà, là những người sáng tác thần chú, truyền bá thần chú, mà ngày nay các Bà-la-môn thông ba Vệ-đà vẫn ca tụng, vẫn tụng đọc, lặp lại lời đã nói, đọc lại điều đã được đọc, tức là Aṭṭhaka, Vāmaka, Vāmadeva, Vessāmitta, Yamataggi, Aṅgīrasa, Bhāradvāja, Vāseṭṭha, Kassapa, Bhagu, các vị ấy cũng không nói như vầy: ",
  "dn13:14.6": "‘Chúng tôi biết điều ấy, chúng tôi thấy điều ấy, nơi nào là Phạm thiên, đường nào đến Phạm thiên, Phạm thiên ở đâu.’ ",
  "dn13:14.7": "Thế mà chính các Bà-la-môn thông ba Vệ-đà ấy lại nói như vầy: ",
  "dn13:14.8": "‘Điều mà chúng tôi không biết, điều mà chúng tôi không thấy, chúng tôi lại chỉ dạy con đường để cộng trú với điều ấy. ",
  "dn13:14.9": "Chính đây mới là con đường thẳng, đây là con đường trực tiếp, đưa đến giải thoát, dẫn người thực hành theo đó đến cộng trú với Phạm thiên.’ ",
  "dn13:14.10": "Ông nghĩ sao, này Vāseṭṭha, ",
  "dn13:14.11": "trong trường hợp như vậy, lời nói của các Bà-la-môn thông ba Vệ-đà chẳng phải là không có căn cứ sao?” ",
  "dn13:14.12": "“Chắc chắn là vậy, thưa Tôn giả Gotama, trong trường hợp như vậy, lời nói của các Bà-la-môn thông ba Vệ-đà là không có căn cứ.” ",
  "dn13:15.1": "“Lành thay, này Vāseṭṭha. Này Vāseṭṭha, việc các Bà-la-môn thông ba Vệ-đà chỉ dạy con đường để cộng trú với điều mà họ không biết, không thấy, rằng: ‘Chính đây mới là con đường thẳng, đây là con đường trực tiếp, đưa đến giải thoát, dẫn người thực hành theo đó đến cộng trú với Phạm thiên’—điều ấy không thể có được. ",
  "dn13:15.2": "Ví như, này Vāseṭṭha, một chuỗi người mù nắm nhau nối tiếp, người đầu không thấy, người giữa không thấy, người cuối cũng không thấy; ",
  "dn13:15.3": "cũng vậy, này Vāseṭṭha, ta cho rằng lời nói của các Bà-la-môn thông ba Vệ-đà giống như một chuỗi người mù: người đầu không thấy, người giữa không thấy, người cuối cũng không thấy. ",
  "dn13:15.4": "Lời nói ấy của các Bà-la-môn thông ba Vệ-đà chỉ thành ra đáng cười mà thôi, chỉ là danh suông mà thôi, chỉ là rỗng không mà thôi, chỉ là trống rỗng mà thôi. ",
  "dn13:16.1": "Ông nghĩ sao, này Vāseṭṭha, ",
  "dn13:16.2": "các Bà-la-môn thông ba Vệ-đà có thấy mặt trăng và mặt trời không, cũng như nhiều người khác thấy; và nơi mặt trăng mặt trời mọc lên, nơi chúng lặn xuống, họ cầu khẩn, tán dương, chắp tay cung kính lễ bái và đi theo sự vận hành của chúng chăng?” ",
  "dn13:16.3": "“Vâng, thưa Tôn giả Gotama, các Bà-la-môn thông ba Vệ-đà thấy mặt trăng và mặt trời, cũng như nhiều người khác thấy; và nơi mặt trăng mặt trời mọc lên, nơi chúng lặn xuống, họ cầu khẩn, tán dương, chắp tay cung kính lễ bái và đi theo sự vận hành của chúng.” ",
  "dn13:17.1": "“Ông nghĩ sao, này Vāseṭṭha, ",
  "dn13:17.2": "đối với mặt trăng và mặt trời mà các Bà-la-môn thông ba Vệ-đà thấy, cũng như nhiều người khác thấy; nơi chúng mọc lên, nơi chúng lặn xuống, họ cầu khẩn, tán dương, chắp tay cung kính lễ bái và đi theo sự vận hành của chúng—các Bà-la-môn thông ba Vệ-đà có thể chỉ dạy con đường để cộng trú với mặt trăng và mặt trời rằng: ",
  "dn13:17.3": "‘Chính đây mới là con đường thẳng, đây là con đường trực tiếp, đưa đến giải thoát, dẫn người thực hành theo đó đến cộng trú với mặt trăng và mặt trời’ chăng?” ",
  "dn13:17.4": "“Không có việc ấy, thưa Tôn giả Gotama.” ",
  "dn13:18.1": "“Vậy là, này Vāseṭṭha, đối với mặt trăng và mặt trời mà các Bà-la-môn thông ba Vệ-đà thấy, cũng như nhiều người khác thấy; nơi chúng mọc lên, nơi chúng lặn xuống, họ cầu khẩn, tán dương, chắp tay cung kính lễ bái và đi theo sự vận hành của chúng, ngay cả đối với những thứ ấy họ cũng không thể chỉ dạy con đường để cộng trú với mặt trăng và mặt trời rằng: ",
  "dn13:18.2": "‘Chính đây mới là con đường thẳng, đây là con đường trực tiếp, đưa đến giải thoát, dẫn người thực hành theo đó đến cộng trú với mặt trăng và mặt trời.’ ",
  "dn13:18.3": "Huống nữa, các Bà-la-môn thông ba Vệ-đà chưa từng trực tiếp thấy Phạm thiên. ",
  "dn13:18.4": "Các vị thầy của các Bà-la-môn thông ba Vệ-đà cũng chưa từng trực tiếp thấy Phạm thiên. ",
  "dn13:18.5": "Các vị thầy của thầy của các Bà-la-môn thông ba Vệ-đà cũng chưa từng trực tiếp thấy Phạm thiên. ",
  "dn13:18.6": "Cho đến bảy đời thầy tổ của các Bà-la-môn thông ba Vệ-đà cũng chưa từng trực tiếp thấy Phạm thiên. ",
  "dn13:18.7": "Ngay cả các vị tiên nhân thời xưa của các Bà-la-môn thông ba Vệ-đà, là những người sáng tác thần chú, truyền bá thần chú, mà ngày nay các Bà-la-môn thông ba Vệ-đà vẫn ca tụng, vẫn tụng đọc, lặp lại lời đã nói, đọc lại điều đã được đọc, tức là Aṭṭhaka, Vāmaka, Vāmadeva, Vessāmitta, Yamataggi, Aṅgīrasa, Bhāradvāja, Vāseṭṭha, Kassapa, Bhagu, các vị ấy cũng không nói như vầy: ",
  "dn13:18.8": "‘Chúng tôi biết điều ấy, chúng tôi thấy điều ấy, nơi nào là Phạm thiên, đường nào đến Phạm thiên, Phạm thiên ở đâu.’ ",
  "dn13:18.9": "Thế mà chính các Bà-la-môn thông ba Vệ-đà ấy lại nói như vầy: ",
  "dn13:18.10": "‘Điều mà chúng tôi không biết, điều mà chúng tôi không thấy, chúng tôi lại chỉ dạy con đường để cộng trú với điều ấy—chính đây mới là con đường thẳng, đây là con đường trực tiếp, đưa đến giải thoát, dẫn người thực hành theo đó đến cộng trú với Phạm thiên.’ ",
  "dn13:18.11": "Ông nghĩ sao, này Vāseṭṭha, ",
  "dn13:18.12": "trong trường hợp như vậy, lời nói của các Bà-la-môn thông ba Vệ-đà chẳng phải là không có căn cứ sao?” ",
  "dn13:18.13": "“Chắc chắn là vậy, thưa Tôn giả Gotama, trong trường hợp như vậy, lời nói của các Bà-la-môn thông ba Vệ-đà là không có căn cứ.” ",
  "dn13:18.14": "“Lành thay, này Vāseṭṭha. Này Vāseṭṭha, việc các Bà-la-môn thông ba Vệ-đà chỉ dạy con đường để cộng trú với điều mà họ không biết, không thấy, rằng: ‘Chính đây mới là con đường thẳng, đây là con đường trực tiếp, đưa đến giải thoát, dẫn người thực hành theo đó đến cộng trú với Phạm thiên’—điều ấy không thể có được. ",
  "dn13:19.0": "2.1. Ví dụ người đẹp trong xứ ",
  "dn13:19.1": "Ví như, này Vāseṭṭha, có người nói như vầy: ",
  "dn13:19.2": "‘Ta yêu người đẹp nhất trong xứ này, ta khao khát nàng ấy.’ ",
  "dn13:19.3": "Người ta sẽ nói với người ấy như vầy: ",
  "dn13:19.4": "‘Này anh kia, người đẹp trong xứ mà anh yêu và khao khát ấy, anh có biết nàng là—",
  "dn13:19.5": "thuộc giai cấp Sát-đế-lỵ, hay Bà-la-môn, hay Phệ-xá, hay Thủ-đà-la không?’ ",
  "dn13:19.6": "Được hỏi vậy, người ấy sẽ đáp: ‘Không’.",
  "dn13:19.7": "Người ta sẽ nói với người ấy như sau:",
  "dn13:19.8": "‘Này anh kia, người đẹp nhất xứ mà anh mong muốn, khao khát ấy, anh có biết người đẹp nhất xứ đó—tên là gì, thuộc dòng họ nào, cao hay thấp hay tầm thước, da đen hay da ngăm hay da màu vàng sẫm, ở làng nào hay thị trấn nào hay thành phố nào chăng?’",
  "dn13:19.9": "Được hỏi vậy, người ấy sẽ đáp: ‘Không’.",
  "dn13:19.10": "Người ta sẽ nói với người ấy như sau:",
  "dn13:19.11": "‘Này anh kia, vậy là anh mong muốn, khao khát một người mà anh không biết, không thấy sao?’",
  "dn13:19.12": "Được hỏi vậy, người ấy sẽ đáp: ‘Vâng’.",
  "dn13:19.13": "Này Vāseṭṭha, ông nghĩ sao,",
  "dn13:19.14": "trong trường hợp như vậy, lời nói của người ấy chẳng phải là không có cơ sở sao?”",
  "dn13:19.15": "“Thưa Tôn giả Gotama, đúng vậy, trong trường hợp như vậy, lời nói của người ấy là không có cơ sở.”",
  "dn13:20.1": "“Cũng vậy, này Vāseṭṭha, các Bà-la-môn thông ba Vệ-đà chưa từng trực tiếp thấy Phạm thiên; các vị thầy của những Bà-la-môn thông ba Vệ-đà ấy cũng chưa từng trực tiếp thấy Phạm thiên; các thầy của thầy họ cũng chưa từng trực tiếp thấy Phạm thiên.",
  "dn13:20.2": "Cho đến bảy đời thầy tổ của những Bà-la-môn thông ba Vệ-đà ấy cũng chưa từng trực tiếp thấy Phạm thiên.",
  "dn13:20.3": "Ngay cả các vị tiên nhân thời xưa của những Bà-la-môn thông ba Vệ-đà, là những người sáng tác thần chú, truyền bá thần chú, mà các Bà-la-môn thông ba Vệ-đà ngày nay ca tụng, tuyên đọc, lặp lại lời đã nói, tụng đọc lời đã tụng, như Aṭṭhaka, Vāmaka, Vāmadeva, Vessāmitta, Yamataggi, Aṅgīrasa, Bhāradvāja, Vāseṭṭha, Kassapa, Bhagu, các vị ấy cũng không nói như sau:",
  "dn13:20.4": "‘Chúng tôi biết điều ấy, chúng tôi thấy điều ấy: Phạm thiên ở đâu, đi bằng đường nào đến Phạm thiên, hay Phạm thiên ở chỗ nào.’",
  "dn13:20.5": "Thế mà các Bà-la-môn thông ba Vệ-đà ấy lại nói như sau:",
  "dn13:20.6": "‘Điều chúng tôi không biết, điều chúng tôi không thấy, chúng tôi lại chỉ dạy con đường để cùng ở với điều ấy—đây chính là con đường thẳng, đây là đường trực tiếp, đưa ra khỏi, dẫn người thực hành đến cùng ở với Phạm thiên.’",
  "dn13:20.7": "Này Vāseṭṭha, ông nghĩ sao, trong trường hợp như vậy, lời nói của các Bà-la-môn thông ba Vệ-đà chẳng phải là không có cơ sở sao?”",
  "dn13:20.8": "“Thưa Tôn giả Gotama, đúng vậy, trong trường hợp như vậy, lời nói của các Bà-la-môn thông ba Vệ-đà là không có cơ sở.”",
  "dn13:20.9": "“Lành thay, này Vāseṭṭha, việc các Bà-la-môn thông ba Vệ-đà không biết, không thấy mà lại chỉ dạy con đường để cùng ở với điều ấy, rằng: ‘Đây chính là con đường thẳng, đây là đường trực tiếp, đưa ra khỏi, dẫn người thực hành đến cùng ở với Phạm thiên’—điều ấy không thể có được.",
  "dn13:21.0": "2.2. Ví dụ cái thang",
  "dn13:21.1": "Ví như, này Vāseṭṭha, có người làm một cái thang ở ngã tư đường để leo lên lầu.",
  "dn13:21.2": "Người ta sẽ nói với người ấy như sau:",
  "dn13:21.3": "‘Này anh kia, cái lầu mà anh làm thang để leo lên đó, anh có biết nó ở hướng đông, hay hướng nam, hay hướng tây, hay hướng bắc; cao hay thấp hay vừa phải chăng?’",
  "dn13:21.4": "Được hỏi vậy, người ấy sẽ đáp: ‘Không’.",
  "dn13:22.1": "Người ta sẽ nói với người ấy như sau:",
  "dn13:22.2": "‘Này anh kia, vậy là anh làm thang để leo lên một cái lầu mà anh không biết, không thấy sao?’",
  "dn13:22.3": "Được hỏi vậy, người ấy sẽ đáp: ‘Vâng’.",
  "dn13:22.4": "Này Vāseṭṭha, ông nghĩ sao,",
  "dn13:22.5": "trong trường hợp như vậy, lời nói của người ấy chẳng phải là không có cơ sở sao?”",
  "dn13:22.6": "“Thưa Tôn giả Gotama, đúng vậy, trong trường hợp như vậy, lời nói của người ấy là không có cơ sở.”",
  "dn13:22.7": "“Cũng vậy, này Vāseṭṭha, các Bà-la-môn thông ba Vệ-đà chưa từng trực tiếp thấy Phạm thiên; các vị thầy của những Bà-la-môn thông ba Vệ-đà ấy cũng chưa từng trực tiếp thấy Phạm thiên; các thầy của thầy họ cũng chưa từng trực tiếp thấy Phạm thiên; cho đến bảy đời thầy tổ của những Bà-la-môn thông ba Vệ-đà ấy cũng chưa từng trực tiếp thấy Phạm thiên.",
  "dn13:22.8": "Ngay cả các vị tiên nhân thời xưa của những Bà-la-môn thông ba Vệ-đà, là những người sáng tác thần chú, truyền bá thần chú, mà các Bà-la-môn thông ba Vệ-đà ngày nay ca tụng, tuyên đọc, lặp lại lời đã nói, tụng đọc lời đã tụng, như Aṭṭhaka, Vāmaka, Vāmadeva, Vessāmitta, Yamataggi, Aṅgīrasa, Bhāradvāja, Vāseṭṭha, Kassapa, Bhagu, các vị ấy cũng không nói như sau—",
  "dn13:22.9": "‘Chúng tôi biết điều ấy, chúng tôi thấy điều ấy: Phạm thiên ở đâu, đi bằng đường nào đến Phạm thiên, hay Phạm thiên ở chỗ nào.’",
  "dn13:22.10": "Thế mà các Bà-la-môn thông ba Vệ-đà ấy lại nói như sau:",
  "dn13:22.11": "‘Điều chúng tôi không biết, điều chúng tôi không thấy, chúng tôi chỉ dạy con đường để cùng ở với điều ấy; đây chính là con đường thẳng, đây là đường trực tiếp, đưa ra khỏi, dẫn người thực hành đến cùng ở với Phạm thiên.’",
  "dn13:22.12": "Này Vāseṭṭha, ông nghĩ sao, trong trường hợp như vậy, lời nói của các Bà-la-môn thông ba Vệ-đà chẳng phải là không có cơ sở sao?”",
  "dn13:22.13": "“Thưa Tôn giả Gotama, đúng vậy, trong trường hợp như vậy, lời nói của các Bà-la-môn thông ba Vệ-đà là không có cơ sở.”",
  "dn13:23.1": "“Lành thay, này Vāseṭṭha, việc các Bà-la-môn thông ba Vệ-đà không biết, không thấy mà lại chỉ dạy con đường để cùng ở với điều ấy: ‘Đây chính là con đường thẳng, đây là đường trực tiếp, đưa ra khỏi, dẫn người thực hành đến cùng ở với Phạm thiên’—điều ấy không thể có được.",
  "dn13:24.0": "2.3. Ví dụ sông Aciravatī",
  "dn13:24.1": "Ví như, này Vāseṭṭha, sông Aciravatī này đầy nước, nước ngang bờ, đến nỗi quạ cũng có thể uống được.",
  "dn13:24.2": "Rồi có một người đến, muốn sang bờ bên kia, tìm bờ bên kia, hướng đến bờ bên kia, mong vượt qua bờ bên kia.",
  "dn13:24.3": "Người ấy đứng ở bờ này mà gọi bờ bên kia:",
  "dn13:24.4": "‘Này bờ bên kia, hãy đến đây! Này bờ bên kia, hãy đến đây!’",
  "dn13:24.5": "Này Vāseṭṭha, ông nghĩ sao,",
  "dn13:24.6": "do nhân gọi mời, hay do nhân cầu khẩn, hay do nhân mong cầu, hay do nhân tán thán của người ấy mà bờ bên kia của sông Aciravatī có đến bờ này chăng?”",
  "dn13:24.7": "“Không, thưa Tôn giả Gotama.”",
  "dn13:25.1": "“Cũng vậy, này Vāseṭṭha, các Bà-la-môn thông ba Vệ-đà từ bỏ những pháp làm nên Bà-la-môn, lại sống theo những pháp không làm nên Bà-la-môn, rồi nói như sau:",
  "dn13:25.2": "‘Chúng ta cầu gọi Inda, chúng ta cầu gọi Soma, chúng ta cầu gọi Varuṇa, chúng ta cầu gọi Īsāna, chúng ta cầu gọi Pajāpati, chúng ta cầu gọi Brahmā, chúng ta cầu gọi Mahiddhi, chúng ta cầu gọi Yama.’",
  "dn13:25.3": "Này Vāseṭṭha, các Bà-la-môn thông ba Vệ-đà ấy từ bỏ những pháp làm nên Bà-la-môn, lại sống theo những pháp không làm nên Bà-la-môn, mà cho rằng do nhân gọi mời, hay do nhân cầu khẩn, hay do nhân mong cầu, hay do nhân tán thán, sau khi thân hoại mạng chung họ sẽ được đi đến cùng ở với Phạm thiên—điều ấy không thể có được.",
  "dn13:26.1": "Ví như, này Vāseṭṭha, sông Aciravatī này đầy nước, nước ngang bờ, đến nỗi quạ cũng có thể uống được.",
  "dn13:26.2": "Rồi có một người đến, muốn sang bờ bên kia, tìm bờ bên kia, hướng đến bờ bên kia, mong vượt qua bờ bên kia.",
  "dn13:26.3": "Người ấy đứng ở bờ này, bị trói chặt hai tay ra sau lưng bằng một sợi dây bền chắc.",
  "dn13:26.4": "Này Vāseṭṭha, ông nghĩ sao,",
  "dn13:26.5": "người ấy có thể từ bờ này của sông Aciravatī đi sang bờ bên kia chăng?”",
  "dn13:26.6": "“Không, thưa Tôn giả Gotama.”",
  "dn13:27.1": "“Cũng vậy, này Vāseṭṭha, năm dục công đức này trong giáo pháp của bậc Thánh cũng được gọi là dây trói, cũng được gọi là xiềng buộc.",
  "dn13:27.2": "Năm là gì?",
  "dn13:27.3": "Các sắc do mắt nhận biết, khả ái, đáng yêu, vừa ý, dễ mến, liên hệ đến dục, khơi dậy tham ái.",
  "dn13:27.4": "Các tiếng do tai nhận biết …",
  "dn13:27.5": "các mùi do mũi nhận biết …",
  "dn13:27.6": "các vị do lưỡi nhận biết …",
  "dn13:27.7": "các xúc do thân nhận biết, khả ái, đáng yêu, vừa ý, dễ mến, liên hệ đến dục, khơi dậy tham ái.",
  "dn13:27.8": "Này Vāseṭṭha, năm dục công đức này trong giáo pháp của bậc Thánh cũng được gọi là dây trói, cũng được gọi là xiềng buộc.",
  "dn13:27.9": "Này Vāseṭṭha, các Bà-la-môn thông ba Vệ-đà bị dính mắc, mê đắm, chìm đắm trong năm dục công đức này, không thấy sự nguy hại, không có trí tuệ về sự xuất ly, mà thọ hưởng chúng.",
  "dn13:28.1": "Này Vāseṭṭha, các Bà-la-môn thông ba Vệ-đà ấy từ bỏ những pháp làm nên Bà-la-môn, lại sống theo những pháp không làm nên Bà-la-môn, bị dính mắc, mê đắm, chìm đắm trong năm dục công đức, không thấy sự nguy hại, không có trí tuệ về sự xuất ly, mà thọ hưởng chúng, bị trói buộc bởi dây trói của dục, mà cho rằng sau khi thân hoại mạng chung họ sẽ được đi đến cùng ở với Phạm thiên—điều ấy không thể có được.",
  "dn13:29.1": "Ví như, này Vāseṭṭha, sông Aciravatī này đầy nước, nước ngang bờ, đến nỗi quạ cũng có thể uống được.",
  "dn13:29.2": "Rồi có một người đến, muốn sang bờ bên kia, tìm bờ bên kia, hướng đến bờ bên kia, mong vượt qua bờ bên kia.",
  "dn13:29.3": "Người ấy ở bờ này, trùm kín đầu mà nằm xuống.",
  "dn13:29.4": "Này Vāseṭṭha, ông nghĩ sao,",
  "dn13:29.5": "người ấy có thể từ bờ này của sông Aciravatī đi sang bờ bên kia chăng?”",
  "dn13:29.6": "“Không, thưa Tôn giả Gotama.”",
  "dn13:30.1": "“Cũng vậy, này Vāseṭṭha, năm triền cái này trong giáo pháp của bậc Thánh cũng được gọi là che lấp, cũng được gọi là triền cái, cũng được gọi là trói buộc, cũng được gọi là bao phủ.",
  "dn13:30.2": "Năm là gì?",
  "dn13:30.3": "Triền cái tham dục, triền cái sân hận, triền cái hôn trầm thụy miên, triền cái trạo cử hối quá, triền cái nghi.",
  "dn13:30.4": "Này Vāseṭṭha, năm triền cái này trong giáo pháp của bậc Thánh cũng được gọi là che lấp, cũng được gọi là triền cái, cũng được gọi là trói buộc, cũng được gọi là bao phủ.",
  "dn13:30.5": "Này Vāseṭṭha, các Bà-la-môn thông ba Vệ-đà bị năm triền cái này che phủ, ngăn kín, trói buộc, bao bọc.",
  "dn13:30.6": "Này Vāseṭṭha, các Bà-la-môn thông ba Vệ-đà ấy từ bỏ những pháp làm nên Bà-la-môn, lại sống theo những pháp không làm nên Bà-la-môn, bị năm triền cái che phủ, ngăn kín, trói buộc, bao bọc, mà cho rằng sau khi thân hoại mạng chung họ sẽ được đi đến cùng ở với Phạm thiên—điều ấy không thể có được.",
  "dn13:31.0": "3. Lời bàn đối chiếu",
  "dn13:31.1": "Này Vāseṭṭha, ông nghĩ sao,",
  "dn13:31.2": "ông đã nghe các Bà-la-môn già cả, cao niên, các thầy và thầy của thầy nói rằng Phạm thiên có sở hữu hay không sở hữu chăng?”",
  "dn13:31.3": "“Không sở hữu, thưa Tôn giả Gotama.”",
  "dn13:31.4": "“Có tâm sân hận hay không có tâm sân hận?”",
  "dn13:31.5": "“Không có tâm sân hận, thưa Tôn giả Gotama.”",
  "dn13:31.6": "“Có tâm ác ý hay không có tâm ác ý?”",
  "dn13:31.7": "“Không có tâm ác ý, thưa Tôn giả Gotama.”",
  "dn13:31.8": "“Có tâm nhiễm ô hay không có tâm nhiễm ô?”",
  "dn13:31.9": "“Không có tâm nhiễm ô, thưa Tôn giả Gotama.”",
  "dn13:31.10": "“Tự tại hay không tự tại?”",
  "dn13:31.11": "“Tự tại, thưa Tôn giả Gotama.”",
  "dn13:32.1": "“Này Vāseṭṭha, ông nghĩ sao,",
  "dn13:32.2": "các Bà-la-môn thông ba Vệ-đà có sở hữu hay không sở hữu?”",
  "dn13:32.3": "“Có sở hữu, thưa Tôn giả Gotama.”",
  "dn13:32.4": "“Có tâm sân hận hay không có tâm sân hận?”",
  "dn13:32.5": "“Có tâm sân hận, thưa Tôn giả Gotama.”",
  "dn13:32.6": "“Có tâm ác ý hay không có tâm ác ý?”",
  "dn13:32.7": "“Có tâm ác ý, thưa Tôn giả Gotama.”",
  "dn13:32.8": "“Có tâm nhiễm ô hay không có tâm nhiễm ô?”",
  "dn13:32.9": "“Có tâm nhiễm ô, thưa Tôn giả Gotama.”",
  "dn13:32.10": "“Tự tại hay không tự tại?”",
  "dn13:32.11": "“Không tự tại, thưa Tôn giả Gotama.”",
  "dn13:33.1": "“Này Vāseṭṭha, người ta nói các Bà-la-môn thông ba Vệ-đà là có sở hữu, còn Phạm thiên là không sở hữu.",
  "dn13:33.2": "Vậy thì các Bà-la-môn thông ba Vệ-đà có sở hữu ấy có tương ưng, có hòa hợp với Phạm thiên không sở hữu chăng?”",
  "dn13:33.3": "“Thưa Tôn giả Gotama, không.”",
  "dn13:34.1": "“Lành thay, này Vāseṭṭha, vậy thì các Bà-la-môn thông ba Vệ-đà có sở hữu ấy, sau khi thân hoại mạng chung, sẽ được cộng trú với Phạm thiên không sở hữu — điều ấy không thể có.",
  "dn13:35.1": "Này Vāseṭṭha, người ta nói các Bà-la-môn thông ba Vệ-đà có tâm sân hận, còn Phạm thiên là không sân hận…",
  "dn13:35.2": "các Bà-la-môn thông ba Vệ-đà có tâm ác ý, còn Phạm thiên là không ác ý…",
  "dn13:35.3": "các Bà-la-môn thông ba Vệ-đà có tâm nhiễm ô, còn Phạm thiên là không nhiễm ô…",
  "dn13:35.4": "các Bà-la-môn thông ba Vệ-đà không tự tại, còn Phạm thiên là tự tại. Vậy thì các Bà-la-môn thông ba Vệ-đà không tự tại ấy có tương ưng, có hòa hợp với Phạm thiên tự tại chăng?”",
  "dn13:35.5": "“Thưa Tôn giả Gotama, không.”",
  "dn13:36.1": "“Lành thay, này Vāseṭṭha, vậy thì các Bà-la-môn thông ba Vệ-đà không tự tại ấy, sau khi thân hoại mạng chung, sẽ được cộng trú với Phạm thiên tự tại — điều ấy không thể có.",
  "dn13:36.2": "Ở đây, này Vāseṭṭha, chính các Bà-la-môn thông ba Vệ-đà ấy ngồi lún xuống, đã lún xuống rồi thì rơi vào khốn quẫn, ta nghĩ họ còn lội qua một cách tệ hại hơn nữa.",
  "dn13:36.3": "Vì vậy, này các Bà-la-môn thông ba Vệ-đà, điều này được gọi là sa mạc của ba Vệ-đà, cũng được gọi là hoang địa của ba Vệ-đà, cũng được gọi là tai họa của ba Vệ-đà.”",
  "dn13:37.1": "Khi được nói vậy, thanh niên Bà-la-môn Vāseṭṭha bạch Thế Tôn:",
  "dn13:37.2": "“Con có nghe rằng Sa-môn Gotama biết con đường đưa đến cộng trú với Phạm thiên.”",
  "dn13:37.3": "“Này Vāseṭṭha, ông nghĩ sao?",
  "dn13:37.4": "Làng Manasākaṭa ở gần đây hay ở xa đây?”",
  "dn13:37.5": "“Thưa Tôn giả Gotama, làng Manasākaṭa ở gần đây, không xa đây.”",
  "dn13:37.6": "“Này Vāseṭṭha, ông nghĩ sao,",
  "dn13:37.7": "ở đây có một người sinh ra và lớn lên tại Manasākaṭa.",
  "dn13:37.8": "Người ấy vừa mới rời Manasākaṭa, người ta hỏi đường đến Manasākaṭa.",
  "dn13:37.9": "Này Vāseṭṭha, người sinh ra và lớn lên tại Manasākaṭa ấy, khi được hỏi đường đến Manasākaṭa, có thể nào lại do dự hay lúng túng chăng?”",
  "dn13:37.10": "“Thưa Tôn giả Gotama, không.”",
  "dn13:37.11": "“Vì sao vậy?”",
  "dn13:37.12": "“Thưa Tôn giả Gotama, vì người ấy sinh ra và lớn lên tại Manasākaṭa, nên tất cả các con đường đến Manasākaṭa đều được người ấy biết rõ.”",
  "dn13:38.1": "“Này Vāseṭṭha, người sinh ra và lớn lên tại Manasākaṭa ấy, khi được hỏi đường đến Manasākaṭa, có thể còn do dự hay lúng túng; nhưng Như Lai thì không như vậy khi được hỏi về cõi Phạm thiên hay về con đường thực hành đưa đến cõi Phạm thiên.",
  "dn13:38.2": "Này Vāseṭṭha, Ta biết Phạm thiên, biết cõi Phạm thiên, biết con đường đưa đến cõi Phạm thiên, và biết rõ người thực hành như thế nào thì được sinh lên cõi Phạm thiên.”",
  "dn13:39.1": "Khi được nói vậy, thanh niên Bà-la-môn Vāseṭṭha bạch Thế Tôn:",
  "dn13:39.2": "“Con có nghe rằng Sa-môn Gotama thuyết dạy con đường đưa đến cộng trú với Phạm thiên.”",
  "dn13:39.3": "“Mong Tôn giả Gotama thuyết dạy cho chúng con con đường đưa đến cộng trú với Phạm thiên. Mong Tôn giả Gotama cứu độ dân chúng Bà-la-môn.”",
  "dn13:39.4": "“Vậy thì, này Vāseṭṭha, hãy lắng nghe, hãy khéo tác ý, Ta sẽ nói.”",
  "dn13:39.5": "“Vâng, thưa Tôn giả.” Thanh niên Bà-la-môn Vāseṭṭha vâng đáp Thế Tôn.",
  "dn13:40-75.0": "4. Thuyết giảng con đường đến cõi Phạm thiên",
  "dn13:40-75.1": "Thế Tôn nói như sau:",
  "dn13:40-75.2": "“Này Vāseṭṭha, ở đây Như Lai xuất hiện ở đời, là bậc A-la-hán, Chánh Đẳng Giác…",
  "dn13:40-75.3": "Này Vāseṭṭha, như vậy vị tỳ-kheo thành tựu giới hạnh…",
  "dn13:40-75.4": "Khi thấy nơi mình năm triền cái này đã được đoạn trừ, hân hoan sinh khởi; do hân hoan nên hỷ sinh; người có tâm hỷ thì thân được khinh an; thân khinh an thì cảm thọ lạc; người có lạc thì tâm được định tĩnh.",
  "dn13:76.1": "Vị ấy an trú, biến mãn một phương với tâm câu hữu với từ. Cũng vậy phương thứ hai. Cũng vậy phương thứ ba. Cũng vậy phương thứ tư. Như vậy, trên, dưới, ngang, khắp mọi nơi, đối với tất cả như đối với chính mình, vị ấy an trú biến mãn toàn thế giới với tâm câu hữu với từ, rộng lớn, cao thượng, vô lượng, không oán, không ác ý.",
  "dn13:77.1": "Ví như, này Vāseṭṭha, một người thổi tù và khỏe mạnh có thể dễ dàng làm cho âm thanh vang đến bốn phương;",
  "dn13:77.2": "cũng vậy, này Vāseṭṭha, với tâm giải thoát do từ được tu tập như thế, bất cứ nghiệp hữu hạn nào cũng không còn tồn tại ở đó, không còn đứng vững ở đó.",
  "dn13:77.3": "Đây cũng là con đường đưa đến cộng trú với Phạm thiên.",
  "dn13:78.1": "Lại nữa, này Vāseṭṭha, vị tỳ-kheo an trú biến mãn với tâm câu hữu với bi…",
  "dn13:78.2": "với tâm câu hữu với hỷ…",
  "dn13:78.3": "với tâm câu hữu với xả, biến mãn một phương. Cũng vậy phương thứ hai. Cũng vậy phương thứ ba. Cũng vậy phương thứ tư. Như vậy, trên, dưới, ngang, khắp mọi nơi, đối với tất cả như đối với chính mình, vị ấy an trú biến mãn toàn thế giới với tâm câu hữu với xả, rộng lớn, cao thượng, vô lượng, không oán, không ác ý.",
  "dn13:79.1": "Ví như, này Vāseṭṭha, một người thổi tù và khỏe mạnh có thể dễ dàng làm cho âm thanh vang đến bốn phương;",
  "dn13:79.2": "cũng vậy, này Vāseṭṭha, với tâm giải thoát do xả được tu tập như thế, bất cứ nghiệp hữu hạn nào cũng không còn tồn tại ở đó, không còn đứng vững ở đó.",
  "dn13:79.3": "Đây cũng là con đường đưa đến cộng trú với Phạm thiên.",
  "dn13:80.1": "“Này Vāseṭṭha, ông nghĩ sao,",
  "dn13:80.2": "vị tỳ-kheo an trú như vậy là có sở hữu hay không sở hữu?”",
  "dn13:80.3": "“Thưa Tôn giả Gotama, không sở hữu.”",
  "dn13:80.4": "“Là có tâm sân hận hay không sân hận?”",
  "dn13:80.5": "“Thưa Tôn giả Gotama, không sân hận.”",
  "dn13:80.6": "“Là có tâm ác ý hay không ác ý?”",
  "dn13:80.7": "“Thưa Tôn giả Gotama, không ác ý.”",
  "dn13:80.8": "“Là có tâm nhiễm ô hay không nhiễm ô?”",
  "dn13:80.9": "“Thưa Tôn giả Gotama, không nhiễm ô.”",
  "dn13:80.10": "“Là tự tại hay không tự tại?”",
  "dn13:80.11": "“Thưa Tôn giả Gotama, tự tại.”",
  "dn13:81.1": "“Này Vāseṭṭha, người ta nói vị tỳ-kheo là không sở hữu, và Phạm thiên cũng là không sở hữu.",
  "dn13:81.2": "Vậy thì vị tỳ-kheo không sở hữu có tương ưng, có hòa hợp với Phạm thiên không sở hữu chăng?”",
  "dn13:81.3": "“Thưa Tôn giả Gotama, có.”",
  "dn13:81.4": "“Lành thay, này Vāseṭṭha, vậy thì vị tỳ-kheo không sở hữu ấy, sau khi thân hoại mạng chung, sẽ được cộng trú với Phạm thiên không sở hữu — điều ấy có thể có.",
  "dn13:81.5": "Này Vāseṭṭha, người ta nói vị tỳ-kheo là không sân hận, và Phạm thiên cũng là không sân hận…",
  "dn13:81.6": "vị tỳ-kheo là không ác ý, và Phạm thiên cũng là không ác ý…",
  "dn13:81.7": "vị tỳ-kheo là không nhiễm ô, và Phạm thiên cũng là không nhiễm ô…",
  "dn13:81.8": "vị tỳ-kheo là tự tại, và Phạm thiên cũng là tự tại. Vậy thì vị tỳ-kheo tự tại có tương ưng, có hòa hợp với Phạm thiên tự tại chăng?”",
  "dn13:81.9": "“Thưa Tôn giả Gotama, có.”",
  "dn13:81.10": "“Lành thay, này Vāseṭṭha, vậy thì vị tỳ-kheo tự tại ấy, sau khi thân hoại mạng chung, sẽ được cộng trú với Phạm thiên tự tại — điều ấy có thể có.”",
  "dn13:82.1": "Khi được nói vậy, hai thanh niên Bà-la-môn Vāseṭṭha và Bhāradvāja bạch Thế Tôn:",
  "dn13:82.2": "“Thật vi diệu, thưa Tôn giả Gotama, thật vi diệu, thưa Tôn giả Gotama.",
  "dn13:82.3": "Ví như, thưa Tôn giả Gotama, người ta dựng đứng lại vật bị lật úp, mở ra vật bị che kín, chỉ đường cho kẻ lạc lối, đem đèn vào chỗ tối để những ai có mắt có thể thấy các sắc; cũng vậy, Chánh pháp đã được Tôn giả Gotama dùng nhiều phương cách trình bày sáng tỏ.",
  "dn13:82.4": "Chúng con xin quy y Tôn giả Gotama, quy y Pháp và quy y Tăng chúng tỳ-kheo.",
  "dn13:82.5": "Mong Tôn giả Gotama nhận chúng con là cư sĩ tại gia từ nay cho đến trọn đời đã quy y.”",
  "dn13:82.6": "Kinh Tevijja thứ mười ba đến đây chấm dứt.",
  "dn13:82.7": "Phẩm Giới Uẩn đến đây chấm dứt.",
  "dn13:83.0": "Kệ tóm tắt",
  "dn13:83.1": "Phạm võng, Sa-môn quả, Ambaṭṭha,",
  "dn13:83.2": "Soṇadaṇḍa, Kūṭadanta, Mahāli, Jāliya;",
  "dn13:83.3": "Sīha, Poṭṭhapāda, Subha, Kevaṭṭa,",
  "dn13:83.4": "Lohicca, Tevijja là mười ba.",
  "dn13:83.5": "Bản Pāḷi phẩm Giới Uẩn đến đây chấm dứt."
}
window.BILARA["dn13"]["vi"]["dn13:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
