window.BILARA = window.BILARA || {};
window.BILARA["dn17"] = window.BILARA["dn17"] || {};
window.BILARA["dn17"]["vi"] = {
  "dn17:0.1": "Trường Bộ Kinh 17 ",
  "dn17:0.2": "Kinh Đại Thiện Kiến ",
  "dn17:1.1.1": "Tôi nghe như vầy—",
  "dn17:1.1.2": "Một thời, Thế Tôn trú tại Kusinārā, trong rừng cây sāla của dân Mallā ở Upavattana, giữa hai cây sāla song đôi, vào lúc sắp nhập Niết-bàn. ",
  "dn17:1.2.1": "Bấy giờ, Tôn giả Ānanda đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Ānanda bạch Thế Tôn: ",
  "dn17:1.2.2": "“Bạch Thế Tôn, xin đừng nhập Niết-bàn tại thị trấn nhỏ bé này, nơi hoang vắng này, nơi nhánh nhóc này. ",
  "dn17:1.2.3": "Bạch Thế Tôn, còn có những đại thành khác. ",
  "dn17:1.2.4": "Tức là: Campā, Rājagaha, Sāvatthi, Sāketa, Kosambī, Bārāṇasī; ",
  "dn17:1.2.5": "xin Thế Tôn hãy nhập Niết-bàn tại đó. ",
  "dn17:1.2.6": "Ở đó có nhiều đại hào tộc Sát-đế-lỵ, đại hào tộc Bà-la-môn, đại hào tộc gia chủ kính tín Như Lai; họ sẽ cúng dường xá-lợi của Như Lai.”",
  "dn17:1.3.1": "“Này Ānanda, chớ nói như vậy; này Ānanda, chớ nói như vậy: ",
  "dn17:1.3.2": "‘thị trấn nhỏ bé, nơi hoang vắng, nơi nhánh nhóc’.",
  "dn17:1.3.3.0": "1. Kinh đô Kusāvatī ",
  "dn17:1.3.4": "Này Ānanda, thuở xưa có vua tên là Mahāsudassana, một vị Sát-đế-lỵ đã làm lễ quán đảnh, chinh phục bốn phương, chiến thắng toàn cõi, đạt được sự vững bền trong quốc độ. ",
  "dn17:1.3.5": "Này Ānanda, Kusinārā này chính là kinh đô tên Kusāvatī của vua Mahāsudassana. ",
  "dn17:1.3.6": "Chiều dài từ đông sang tây là mười hai do-tuần, chiều rộng từ bắc xuống nam là bảy do-tuần. ",
  "dn17:1.3.7": "Này Ānanda, kinh đô Kusāvatī phồn thịnh, sung túc, đông dân, đầy người qua lại và lương thực dồi dào. ",
  "dn17:1.3.8": "Ví như, này Ānanda, kinh đô Āḷakamandā của chư thiên phồn thịnh, sung túc, đông đúc, đầy các dạ-xoa và lương thực dồi dào; ",
  "dn17:1.3.9": "cũng vậy, này Ānanda, kinh đô Kusāvatī phồn thịnh, sung túc, đông dân, đầy người qua lại và lương thực dồi dào. ",
  "dn17:1.3.10": "Này Ānanda, kinh đô Kusāvatī ngày đêm không vắng mười thứ âm thanh, tức là: ",
  "dn17:1.3.11": "tiếng voi, tiếng ngựa, tiếng xe, tiếng trống, tiếng mudiṅga, tiếng đàn, tiếng hát, tiếng ốc, tiếng chập chõa, tiếng vỗ tay, và thứ mười là tiếng: ‘Hãy ăn đi, hãy uống đi, hãy nhai đi!’ ",
  "dn17:1.4.1": "Này Ānanda, kinh đô Kusāvatī được bao quanh bởi bảy lớp thành. ",
  "dn17:1.4.2": "Một lớp thành bằng vàng, một lớp bằng bạc, một lớp bằng lưu ly, một lớp bằng pha lê, một lớp bằng hồng ngọc, một lớp bằng mã não, một lớp bằng đủ mọi châu báu. ",
  "dn17:1.5.1": "Này Ānanda, kinh đô Kusāvatī có các cổng thuộc bốn màu. ",
  "dn17:1.5.2": "Một cổng bằng vàng, một cổng bằng bạc, một cổng bằng lưu ly, một cổng bằng pha lê. ",
  "dn17:1.5.3": "Ở mỗi cổng có bảy cây trụ được chôn xuống, cao bằng ba người, chôn sâu bằng ba người, và cao lên mười hai người. ",
  "dn17:1.5.4": "Một trụ bằng vàng, một trụ bằng bạc, một trụ bằng lưu ly, một trụ bằng pha lê, một trụ bằng hồng ngọc, một trụ bằng mã não, một trụ bằng đủ mọi châu báu. ",
  "dn17:1.6.1": "Này Ānanda, kinh đô Kusāvatī được bao quanh bởi bảy hàng cây cọ. ",
  "dn17:1.6.2": "Một hàng cây cọ bằng vàng, một hàng bằng bạc, một hàng bằng lưu ly, một hàng bằng pha lê, một hàng bằng hồng ngọc, một hàng bằng mã não, một hàng bằng đủ mọi châu báu. ",
  "dn17:1.6.3": "Cây cọ bằng vàng có thân bằng vàng, lá và quả bằng bạc. ",
  "dn17:1.6.4": "Cây cọ bằng bạc có thân bằng bạc, lá và quả bằng vàng. ",
  "dn17:1.6.5": "Cây cọ bằng lưu ly có thân bằng lưu ly, lá và quả bằng pha lê. ",
  "dn17:1.6.6": "Cây cọ bằng pha lê có thân bằng pha lê, lá và quả bằng lưu ly. ",
  "dn17:1.6.7": "Cây cọ bằng hồng ngọc có thân bằng hồng ngọc, lá và quả bằng mã não. ",
  "dn17:1.6.8": "Cây cọ bằng mã não có thân bằng mã não, lá và quả bằng hồng ngọc. ",
  "dn17:1.6.9": "Cây cọ bằng đủ mọi châu báu có thân bằng đủ mọi châu báu, lá và quả cũng bằng đủ mọi châu báu. ",
  "dn17:1.6.10": "Này Ānanda, khi những hàng cây cọ ấy bị gió lay động thì phát ra âm thanh êm dịu, khả ái, dễ chịu, mê lòng. ",
  "dn17:1.6.11": "Ví như, này Ānanda, âm thanh của nhạc cụ năm phần, được chỉnh khéo, gõ khéo, do những người thiện xảo hòa tấu, thì êm dịu, khả ái, dễ chịu, mê lòng; ",
  "dn17:1.6.12": "cũng vậy, này Ānanda, khi những hàng cây cọ ấy bị gió lay động thì phát ra âm thanh êm dịu, khả ái, dễ chịu, mê lòng. ",
  "dn17:1.6.13": "Này Ānanda, những kẻ cờ bạc, say sưa, khát rượu ở kinh đô Kusāvatī thời ấy đã vui chơi theo âm thanh của những hàng cây cọ bị gió lay động ấy. ",
  "dn17:1.7.0.1": "2. Đầy đủ bảy báu ",
  "dn17:1.7.0.2": "2.1. Luân bảo ",
  "dn17:1.7.1": "Này Ānanda, vua Mahāsudassana đầy đủ bảy báu và bốn thần lực. ",
  "dn17:1.7.2": "Bảy báu ấy là những gì? ",
  "dn17:1.7.3": "Này Ānanda, vào ngày bố-tát rằm, khi vua Mahāsudassana đã gội đầu, đang giữ ngày bố-tát, và đã lên lầu thượng điện, ",
  "dn17:1.7.4": "thì thiên luân bảo hiện ra, có một ngàn căm, có vành, có trục, đầy đủ mọi tướng. ",
  "dn17:1.7.5": "Thấy vậy, vua Mahāsudassana nghĩ rằng: ",
  "dn17:1.7.6": "‘Ta có nghe rằng: vị vua Sát-đế-lỵ đã làm lễ quán đảnh nào, vào ngày bố-tát rằm, sau khi gội đầu, đang giữ ngày bố-tát, đã lên lầu thượng điện, mà thiên luân bảo hiện ra, có một ngàn căm, có vành, có trục, đầy đủ mọi tướng, thì vị ấy là Chuyển luân vương. ",
  "dn17:1.7.7": "Hay là ta là Chuyển luân vương chăng?’ ",
  "dn17:1.8.1": "Bấy giờ, này Ānanda, vua Mahāsudassana từ chỗ ngồi đứng dậy, vắt thượng y lên một bên vai, tay trái cầm bình vàng, tay phải rảy nước lên luân bảo và nói: ",
  "dn17:1.8.2": "‘Xin luân bảo tôn quý hãy chuyển vận, xin luân bảo tôn quý hãy chinh phục.’ ",
  "dn17:1.8.3": "Bấy giờ, này Ānanda, luân bảo ấy chuyển về phương đông; vua Mahāsudassana cũng theo sau cùng với bốn binh chủng. Này Ānanda, ở nơi nào luân bảo dừng lại, thì tại nơi ấy vua Mahāsudassana cùng bốn binh chủng đến trú. ",
  "dn17:1.9.1": "Này Ānanda, những vị vua đối địch ở phương đông đến gặp vua Mahāsudassana và nói như sau: ",
  "dn17:1.9.2": "‘Xin đến, thưa Đại vương, hoan nghênh Đại vương; thưa Đại vương, đây là của Đại vương; xin Đại vương giáo huấn, thưa Đại vương.’ ",
  "dn17:1.9.3": "Vua Mahāsudassana nói như sau: ",
  "dn17:1.9.4": "‘Không được sát sinh, không được lấy của không cho, không được tà hạnh trong các dục, không được nói dối, không được uống rượu, và hãy dùng thức ăn đúng mức.’ ",
  "dn17:1.9.5": "Này Ānanda, những vị vua đối địch ở phương đông ấy trở thành người đi theo vua Mahāsudassana. ",
  "dn17:1.10.1": "Bấy giờ, này Ānanda, luân bảo ấy lặn xuống biển phía đông rồi hiện lên, chuyển về phương nam … ",
  "dn17:1.10.2": "lặn xuống biển phía nam rồi hiện lên, chuyển về phương tây … ",
  "dn17:1.10.3": "lặn xuống biển phía tây rồi hiện lên, chuyển về phương bắc; vua Mahāsudassana cũng theo sau cùng với bốn binh chủng. ",
  "dn17:1.10.4": "Này Ānanda, ở nơi nào luân bảo dừng lại, thì tại nơi ấy vua Mahāsudassana cùng bốn binh chủng đến trú. ",
  "dn17:1.10.5": "Này Ānanda, những vị vua đối địch ở phương bắc đến gặp vua Mahāsudassana và nói như sau: ",
  "dn17:1.10.6": "‘Xin đến, thưa Đại vương, hoan nghênh Đại vương; thưa Đại vương, đây là của Đại vương; xin Đại vương giáo huấn, thưa Đại vương.’ ",
  "dn17:1.10.7": "Vua Mahāsudassana nói như sau: ",
  "dn17:1.10.8": "‘Không được sát sinh, không được lấy của không cho, không được tà hạnh trong các dục, không được nói dối, không được uống rượu, và hãy dùng thức ăn đúng mức.’ ",
  "dn17:1.10.9": "Này Ānanda, những vị vua đối địch ở phương bắc ấy trở thành người đi theo vua Mahāsudassana. ",
  "dn17:1.11.1": "Bấy giờ, này Ānanda, luân bảo ấy sau khi chinh phục toàn cõi đất đến tận bờ biển, trở về kinh đô Kusāvatī, đứng tại cổng nội cung của vua Mahāsudassana, ở nơi xử việc, như thể được treo lơ lửng, làm rực rỡ nội cung của vua Mahāsudassana. ",
  "dn17:1.11.2": "Này Ānanda, vua Mahāsudassana đã có luân bảo như vậy hiện ra. ",
  "dn17:1.12.0": "2.2. Tượng bảo ",
  "dn17:1.12.1": "Lại nữa, này Ānanda, tượng bảo hiện ra cho vua Mahāsudassana, ",
  "dn17:1.12.2": "toàn thân trắng, có bảy chỗ chống, có thần lực, đi được trên hư không, là long tượng chúa tên Uposatha. ",
  "dn17:1.12.3": "Thấy vậy, tâm vua Mahāsudassana hoan hỷ: ",
  "dn17:1.12.4": "‘Thật là tốt đẹp thay trong các loài voi, nếu nó được thuần phục.’ ",
  "dn17:1.12.5": "Bấy giờ, này Ānanda, tượng bảo ấy—ví như voi chiến thuần chủng, đã được huấn luyện khéo từ lâu; cũng vậy, nó đi đến chỗ thuần phục. ",
  "dn17:1.12.6": "Thuở xưa, này Ānanda, vua Mahāsudassana muốn thử chính tượng bảo ấy, vào buổi sáng sớm đã cưỡi lên nó, đi khắp mặt đất đến tận bờ biển, rồi trở về kinh đô Kusāvatī và dùng điểm tâm. ",
  "dn17:1.12.7": "Này Ānanda, vua Mahāsudassana đã có tượng bảo như vậy hiện ra. ",
  "dn17:1.13.0": "2.3. Mã bảo ",
  "dn17:1.13.1": "Lại nữa, này Ānanda, mã bảo hiện ra cho vua Mahāsudassana, ",
  "dn17:1.13.2": "toàn thân trắng, đầu đen, bờm như cỏ muñja, có thần lực, đi được trên hư không, là ngựa chúa tên Valāhaka. ",
  "dn17:1.13.3": "Thấy vậy, tâm vua Mahāsudassana hoan hỷ: ",
  "dn17:1.13.4": "‘Thật là tốt đẹp thay trong các loài ngựa, nếu nó được thuần phục.’ ",
  "dn17:1.13.5": "Bấy giờ, này Ānanda, mã bảo ấy, ví như ngựa thuần chủng tốt đẹp, đã được huấn luyện khéo từ lâu; cũng vậy, nó đi đến chỗ thuần phục. ",
  "dn17:1.13.6": "Thuở xưa, này Ānanda, vua Mahāsudassana muốn thử chính mã bảo ấy, vào buổi sáng sớm đã cưỡi lên nó, đi khắp mặt đất đến tận bờ biển, rồi trở về kinh đô Kusāvatī và dùng điểm tâm. ",
  "dn17:1.13.7": "Này Ānanda, vua Mahāsudassana đã có mã bảo như vậy hiện ra. ",
  "dn17:1.14.0": "2.4. Châu bảo ",
  "dn17:1.14.1": "Lại nữa, này Ānanda, châu bảo hiện ra cho vua Mahāsudassana. ",
  "dn17:1.14.2": "Đó là viên ngọc lưu ly đẹp đẽ, thuần tịnh, có tám mặt, được mài giũa khéo, trong suốt, sáng ngời, không vẩn đục, đầy đủ mọi vẻ tốt đẹp. ",
  "dn17:1.14.3": "Này Ānanda, ánh sáng của châu bảo ấy chiếu khắp một do-tuần xung quanh. ",
  "dn17:1.14.4": "Thuở xưa, này Ānanda, vua Mahāsudassana muốn thử chính châu bảo ấy, đã cho chỉnh đốn bốn binh chủng, treo viên ngọc lên đầu cờ, rồi tiến đi trong đêm tối mịt mùng. ",
  "dn17:1.14.5": "Này Ānanda, những làng mạc ở chung quanh, nhờ ánh sáng ấy mà làm việc, tưởng là ban ngày. ",
  "dn17:1.14.6": "Này Ānanda, vua Mahāsudassana đã có châu bảo như vậy hiện ra. ",
  "dn17:1.15.0": "2.5. Nữ bảo ",
  "dn17:1.15.1": "Lại nữa, này Ānanda, nữ bảo hiện ra cho vua Mahāsudassana, ",
  "dn17:1.15.2": "xinh đẹp, dễ nhìn, khả ái, đầy đủ vẻ đẹp tuyệt hảo; không quá cao, không quá thấp, không quá gầy, không quá mập, không quá đen, không quá trắng; vượt hơn sắc đẹp loài người nhưng chưa đạt đến sắc đẹp chư thiên. ",
  "dn17:1.15.3": "Này Ānanda, xúc chạm thân thể của nữ bảo ấy như bông gòn hay tơ bông mềm mại. ",
  "dn17:1.15.4": "Này Ānanda, vào lúc lạnh thì thân nàng ấm, vào lúc nóng thì thân nàng mát. ",
  "dn17:1.15.5": "Này Ānanda, từ thân nữ bảo ấy tỏa ra hương chiên-đàn, từ miệng tỏa ra hương sen xanh. ",
  "dn17:1.15.6": "Này Ānanda, nữ bảo ấy dậy trước vua Mahāsudassana, nằm sau, vâng lời sai bảo, cư xử vừa ý, nói lời khả ái. ",
  "dn17:1.15.7": "Này Ānanda, nữ bảo ấy ngay cả trong tâm cũng không trái ý vua Mahāsudassana, huống nữa là bằng thân. ",
  "dn17:1.15.8": "Này Ānanda, vua Mahāsudassana đã có nữ bảo như vậy hiện ra. ",
  "dn17:1.16.0": "2.6. Bảo vật gia chủ",
  "dn17:1.16.1": "Lại nữa, này Ānanda, bảo vật gia chủ xuất hiện nơi vua Mahāsudassana.",
  "dn17:1.16.2": "Người ấy có thiên nhãn do quả nghiệp tạo thành, nhờ đó thấy được kho tàng, dù có chủ hay không có chủ.",
  "dn17:1.16.3": "Người ấy đến gần vua Mahāsudassana và thưa như sau:",
  "dn17:1.16.4": "‘Tâu đại vương, xin ngài cứ an tâm, tôi sẽ lo liệu việc tài sản cho ngài bằng của cải.’",
  "dn17:1.16.5": "Thuở xưa, này Ānanda, vua Mahāsudassana muốn thử chính bảo vật gia chủ ấy, bèn xuống thuyền, đi vào giữa dòng sông Hằng, rồi nói với bảo vật gia chủ rằng:",
  "dn17:1.16.6": "‘Này gia chủ, ta cần vàng bạc.’",
  "dn17:1.16.7": "‘Vậy thì, thưa đại vương, xin cho thuyền ghé vào một bờ.’",
  "dn17:1.16.8": "‘Này gia chủ, ta cần vàng bạc ngay tại đây.’",
  "dn17:1.16.9": "Bấy giờ, này Ānanda, bảo vật gia chủ ấy dùng cả hai tay vốc nước lên, lấy ra một chum đầy vàng bạc, rồi thưa với vua Mahāsudassana rằng:",
  "dn17:1.16.10": "‘Như vậy đã đủ chưa, thưa đại vương? Đã làm xong đến mức ấy chưa, thưa đại vương? Đã cúng dường đến mức ấy chưa, thưa đại vương?’",
  "dn17:1.16.11": "Vua Mahāsudassana nói như sau:",
  "dn17:1.16.12": "‘Như vậy là đủ rồi, này gia chủ. Đã làm xong đến mức ấy rồi, này gia chủ. Đã cúng dường đến mức ấy rồi, này gia chủ.’",
  "dn17:1.16.13": "Này Ānanda, vua Mahāsudassana có được bảo vật gia chủ như vậy.",
  "dn17:1.17.0": "2.7. Bảo vật quân sư",
  "dn17:1.18.1": "Lại nữa, này Ānanda, bảo vật quân sư xuất hiện nơi vua Mahāsudassana,",
  "dn17:1.18.2": "là người trí tuệ, khéo léo, thông minh, có khả năng hướng dẫn vua Mahāsudassana trong việc nên tiến tới, khiến tiến tới; việc nên tránh xa, khiến tránh xa; việc nên thiết lập, khiến thiết lập.",
  "dn17:1.18.3": "Người ấy đến gần vua Mahāsudassana và thưa như sau:",
  "dn17:1.18.4": "‘Tâu đại vương, xin ngài cứ an tâm, tôi sẽ chỉ dạy.’",
  "dn17:1.18.5": "Này Ānanda, vua Mahāsudassana có được bảo vật quân sư như vậy.",
  "dn17:1.18.6": "Này Ānanda, vua Mahāsudassana đầy đủ bảy báu này.",
  "dn17:1.18.7.0": "3. Thành tựu bốn thần lực",
  "dn17:1.18.8": "Này Ānanda, vua Mahāsudassana thành tựu bốn thần lực.",
  "dn17:1.18.9": "Bốn thần lực ấy là gì?",
  "dn17:1.18.10": "Ở đây, này Ānanda, vua Mahāsudassana có dung sắc đẹp đẽ, dễ nhìn, khả ái, đầy đủ vẻ đẹp tối thượng của làn da, vượt hẳn những người khác.",
  "dn17:1.18.11": "Này Ānanda, vua Mahāsudassana thành tựu thần lực thứ nhất này.",
  "dn17:1.19.1": "Lại nữa, này Ānanda, vua Mahāsudassana sống lâu, tồn tại lâu dài, vượt hẳn những người khác.",
  "dn17:1.19.2": "Này Ānanda, vua Mahāsudassana thành tựu thần lực thứ hai này.",
  "dn17:1.20.1": "Lại nữa, này Ānanda, vua Mahāsudassana ít bệnh, ít não, có tiêu hóa điều hòa, không quá lạnh, không quá nóng, vượt hẳn những người khác.",
  "dn17:1.20.2": "Này Ānanda, vua Mahāsudassana thành tựu thần lực thứ ba này.",
  "dn17:1.21.1": "Lại nữa, này Ānanda, vua Mahāsudassana được các bà-la-môn và gia chủ yêu mến, quý thích.",
  "dn17:1.21.2": "Ví như, này Ānanda, người cha được các con yêu mến, quý thích;",
  "dn17:1.21.3": "cũng vậy, này Ānanda, vua Mahāsudassana được các bà-la-môn và gia chủ yêu mến, quý thích.",
  "dn17:1.21.4": "Và này Ānanda, các bà-la-môn và gia chủ cũng được vua Mahāsudassana yêu mến, quý thích.",
  "dn17:1.21.5": "Ví như, này Ānanda, các con được cha yêu mến, quý thích;",
  "dn17:1.21.6": "cũng vậy, này Ānanda, các bà-la-môn và gia chủ cũng được vua Mahāsudassana yêu mến, quý thích.",
  "dn17:1.21.7": "Thuở xưa, này Ānanda, vua Mahāsudassana cùng bốn binh chủng đi ra ngự viên.",
  "dn17:1.21.8": "Bấy giờ, này Ānanda, các bà-la-môn và gia chủ đến gần vua Mahāsudassana và thưa rằng:",
  "dn17:1.21.9": "‘Tâu đại vương, xin đi chậm lại, để chúng tôi được nhìn ngài lâu hơn.’",
  "dn17:1.21.10": "Này Ānanda, vua Mahāsudassana cũng bảo người đánh xe rằng:",
  "dn17:1.21.11": "‘Này người đánh xe, hãy cho xe đi chậm lại, để ta được nhìn các bà-la-môn và gia chủ lâu hơn.’",
  "dn17:1.21.12": "Này Ānanda, vua Mahāsudassana thành tựu thần lực thứ tư này.",
  "dn17:1.21.13": "Này Ānanda, vua Mahāsudassana thành tựu bốn thần lực này.",
  "dn17:1.22.0": "4. Ao sen và cung điện Pháp",
  "dn17:1.22.1": "Bấy giờ, này Ānanda, vua Mahāsudassana nghĩ rằng:",
  "dn17:1.22.2": "‘Hay là ta cho xây những ao sen trong các khoảng giữa hàng cọ này, cứ mỗi trăm cung một ao.’",
  "dn17:1.22.3": "Này Ānanda, vua Mahāsudassana đã cho xây những ao sen trong các khoảng giữa hàng cọ ấy, cứ mỗi trăm cung một ao.",
  "dn17:1.22.4": "Và này Ānanda, những ao sen ấy được xây bằng gạch bốn màu:",
  "dn17:1.22.5": "một loại gạch bằng vàng, một loại bằng bạc, một loại bằng lưu ly, một loại bằng pha lê.",
  "dn17:1.22.6": "Và này Ānanda, trong những ao sen ấy có bốn bậc thang thuộc bốn màu,",
  "dn17:1.22.7": "một bậc bằng vàng, một bậc bằng bạc, một bậc bằng lưu ly, một bậc bằng pha lê.",
  "dn17:1.22.8": "Bậc thang bằng vàng có các trụ bằng vàng, còn các thanh ngang và tay vịn bằng bạc.",
  "dn17:1.22.9": "Bậc thang bằng bạc có các trụ bằng bạc, còn các thanh ngang và tay vịn bằng vàng.",
  "dn17:1.22.10": "Bậc thang bằng lưu ly có các trụ bằng lưu ly, còn các thanh ngang và tay vịn bằng pha lê.",
  "dn17:1.22.11": "Bậc thang bằng pha lê có các trụ bằng pha lê, còn các thanh ngang và tay vịn bằng lưu ly.",
  "dn17:1.22.12": "Và này Ānanda, những ao sen ấy được bao quanh bởi hai hàng lan can, một hàng bằng vàng, một hàng bằng bạc.",
  "dn17:1.22.13": "Lan can bằng vàng có các trụ bằng vàng, còn các thanh ngang và tay vịn bằng bạc.",
  "dn17:1.22.14": "Lan can bằng bạc có các trụ bằng bạc, còn các thanh ngang và tay vịn bằng vàng.",
  "dn17:1.23.1": "Bấy giờ, này Ānanda, vua Mahāsudassana nghĩ rằng:",
  "dn17:1.23.2": "‘Hay là ta cho trồng trong những ao sen này các loại hoa như vậy: hoa súng xanh, sen hồng, sen trắng, sen thơm, bạch liên, nở suốt bốn mùa, không ngăn cấm đối với mọi người.’",
  "dn17:1.23.3": "Này Ānanda, vua Mahāsudassana đã cho trồng trong những ao sen ấy các loại hoa như vậy: hoa súng xanh, sen hồng, sen trắng, sen thơm, bạch liên, nở suốt bốn mùa, không ngăn cấm đối với mọi người.",
  "dn17:1.23.4": "Bấy giờ, này Ānanda, vua Mahāsudassana nghĩ rằng:",
  "dn17:1.23.5": "‘Hay là ta đặt những người tắm rửa ở bờ các ao sen này, để họ tắm cho những người qua lại.’",
  "dn17:1.23.6": "Này Ānanda, vua Mahāsudassana đã đặt những người tắm rửa ở bờ các ao sen ấy, và họ đã tắm cho những người qua lại.",
  "dn17:1.23.7": "Bấy giờ, này Ānanda, vua Mahāsudassana nghĩ rằng:",
  "dn17:1.23.8": "‘Hay là ta thiết lập tại bờ các ao sen này sự bố thí như sau—",
  "dn17:1.23.9": "thức ăn cho người cần thức ăn, đồ uống cho người cần đồ uống, y phục cho người cần y phục, xe cộ cho người cần xe cộ, chỗ nằm cho người cần chỗ nằm, phụ nữ cho người cần phụ nữ, bạc cho người cần bạc, vàng cho người cần vàng.’",
  "dn17:1.23.10": "Này Ānanda, vua Mahāsudassana đã thiết lập tại bờ các ao sen ấy sự bố thí như sau—",
  "dn17:1.23.11": "thức ăn cho người cần thức ăn, đồ uống cho người cần đồ uống, y phục cho người cần y phục, xe cộ cho người cần xe cộ, chỗ nằm cho người cần chỗ nằm, phụ nữ cho người cần phụ nữ, bạc cho người cần bạc, vàng cho người cần vàng.",
  "dn17:1.24.1": "Bấy giờ, này Ānanda, các bà-la-môn và gia chủ mang theo nhiều tài sản, đến gần vua Mahāsudassana và thưa rằng:",
  "dn17:1.24.2": "‘Tâu đại vương, đây là nhiều tài sản được mang đến chỉ để dâng lên ngài, xin ngài nhận lấy.’",
  "dn17:1.24.3": "‘Thôi, này các vị, ta cũng có nhiều tài sản được tích lũy bằng thuế khóa hợp pháp; các vị hãy giữ lấy số ấy, và còn có thể mang thêm nữa.’",
  "dn17:1.24.4": "Bị vua từ chối, họ lui sang một bên và suy nghĩ như sau:",
  "dn17:1.24.5": "‘Thật không thích hợp cho chúng ta nếu lại mang những tài sản này trở về nhà mình. ",
  "dn17:1.24.6": "Hay là chúng ta xây cho vua Mahāsudassana một dinh thự.’",
  "dn17:1.24.7": "Họ đến gần vua Mahāsudassana và thưa rằng:",
  "dn17:1.24.8": "‘Tâu đại vương, chúng tôi sẽ xây cho ngài một dinh thự.’",
  "dn17:1.24.9": "Này Ānanda, vua Mahāsudassana im lặng nhận lời.",
  "dn17:1.25.1": "Bấy giờ, này Ānanda, Sakka, vua của chư thiên, biết được ý nghĩ trong tâm của vua Mahāsudassana, liền bảo thiên tử Vissakamma rằng:",
  "dn17:1.25.2": "‘Này hiền giả Vissakamma, hãy đi xây cho vua Mahāsudassana một dinh thự, gọi là cung điện Pháp.’",
  "dn17:1.25.3": "‘Vâng, thưa tôn giả,’ này Ānanda, thiên tử Vissakamma đáp lời Sakka, vua của chư thiên. Rồi cũng như người lực sĩ co cánh tay đang duỗi lại hay duỗi cánh tay đang co ra; cũng vậy, vị ấy biến mất khỏi cõi trời Ba Mươi Ba và hiện ra trước mặt vua Mahāsudassana.",
  "dn17:1.25.4": "Bấy giờ, này Ānanda, thiên tử Vissakamma nói với vua Mahāsudassana rằng:",
  "dn17:1.25.5": "‘Tâu đại vương, tôi sẽ xây cho ngài một dinh thự, gọi là cung điện Pháp.’",
  "dn17:1.25.6": "Này Ānanda, vua Mahāsudassana im lặng nhận lời.",
  "dn17:1.25.7": "Này Ānanda, thiên tử Vissakamma đã xây cho vua Mahāsudassana một dinh thự, gọi là cung điện Pháp.",
  "dn17:1.25.8": "Này Ānanda, cung điện Pháp dài một do-tuần theo hướng đông tây, và rộng nửa do-tuần theo hướng bắc nam.",
  "dn17:1.25.9": "Này Ānanda, nền của cung điện Pháp cao ba lần chiều cao một người, được xây bằng gạch bốn màu:",
  "dn17:1.25.10": "một loại gạch bằng vàng, một loại bằng bạc, một loại bằng lưu ly, một loại bằng pha lê.",
  "dn17:1.26.1": "Này Ānanda, cung điện Pháp có tám mươi bốn ngàn cột thuộc bốn màu:",
  "dn17:1.26.2": "một cột bằng vàng, một cột bằng bạc, một cột bằng lưu ly, một cột bằng pha lê.",
  "dn17:1.26.3": "Này Ānanda, cung điện Pháp được lát bằng các tấm ván bốn màu:",
  "dn17:1.26.4": "một tấm bằng vàng, một tấm bằng bạc, một tấm bằng lưu ly, một tấm bằng pha lê.",
  "dn17:1.26.5": "Này Ānanda, cung điện Pháp có hai mươi bốn bậc thang thuộc bốn màu:",
  "dn17:1.26.6": "một bậc bằng vàng, một bậc bằng bạc, một bậc bằng lưu ly, một bậc bằng pha lê.",
  "dn17:1.26.7": "Bậc thang bằng vàng có các trụ bằng vàng, còn các thanh ngang và tay vịn bằng bạc.",
  "dn17:1.26.8": "Bậc thang bằng bạc có các trụ bằng bạc, còn các thanh ngang và tay vịn bằng vàng.",
  "dn17:1.26.9": "Bậc thang bằng lưu ly có các trụ bằng lưu ly, còn các thanh ngang và tay vịn bằng pha lê.",
  "dn17:1.26.10": "Bậc thang bằng pha lê có các trụ bằng pha lê, còn các thanh ngang và tay vịn bằng lưu ly.",
  "dn17:1.26.11": "Này Ānanda, trong cung điện Pháp có tám mươi bốn ngàn lầu gác thuộc bốn màu:",
  "dn17:1.26.12": "một lầu bằng vàng, một lầu bằng bạc, một lầu bằng lưu ly, một lầu bằng pha lê.",
  "dn17:1.26.13": "Trong lầu gác bằng vàng, một chiếc giường bằng bạc đã được bày ra; trong lầu gác bằng bạc, một chiếc giường bằng vàng đã được bày ra; trong lầu gác bằng lưu ly, một chiếc giường bằng ngà đã được bày ra; trong lầu gác bằng pha lê, một chiếc giường bằng gỗ quý đã được bày ra.",
  "dn17:1.26.14": "Ở cửa lầu gác bằng vàng có một cây ta-la bằng bạc đứng đó; thân cây bằng bạc, lá và quả bằng vàng.",
  "dn17:1.26.15": "Ở cửa lầu gác bằng bạc có một cây ta-la bằng vàng đứng đó; thân cây bằng vàng, lá và quả bằng bạc.",
  "dn17:1.26.16": "Ở cửa lầu gác bằng lưu ly có một cây ta-la bằng pha lê đứng đó; thân cây bằng pha lê, lá và quả bằng lưu ly.",
  "dn17:1.26.17": "Ở cửa lầu gác bằng pha lê có một cây ta-la bằng lưu ly đứng đó; thân cây bằng lưu ly, lá và quả bằng pha lê.",
  "dn17:1.27.1": "Rồi này Ānanda, vua Mahāsudassana nghĩ rằng:",
  "dn17:1.27.2": "‘Hay là ta cho dựng một rừng ta-la hoàn toàn bằng vàng ở cửa lầu gác Mahāviyūha, nơi ta sẽ ngồi nghỉ ban ngày.’",
  "dn17:1.27.3": "Này Ānanda, vua Mahāsudassana đã cho dựng một rừng ta-la hoàn toàn bằng vàng ở cửa lầu gác Mahāviyūha, nơi ngài ngồi nghỉ ban ngày.",
  "dn17:1.28.1": "Này Ānanda, cung điện Dhamma được bao quanh bởi hai hàng lan can, một bằng vàng, một bằng bạc.",
  "dn17:1.28.2": "Ở lan can bằng vàng có các cột bằng vàng, còn các thanh ngang và đỉnh chóp bằng bạc.",
  "dn17:1.28.3": "Ở lan can bằng bạc có các cột bằng bạc, còn các thanh ngang và đỉnh chóp bằng vàng.",
  "dn17:1.29.1": "Này Ānanda, cung điện Dhamma được bao quanh bởi hai tấm lưới chuông nhỏ—",
  "dn17:1.29.2": "một tấm bằng vàng, một tấm bằng bạc.",
  "dn17:1.29.3": "Ở tấm lưới bằng vàng có các chuông nhỏ bằng bạc, ở tấm lưới bằng bạc có các chuông nhỏ bằng vàng.",
  "dn17:1.29.4": "Này Ānanda, khi những tấm lưới chuông ấy lay động theo gió, âm thanh phát ra thật du dương, khả ái, êm tai, mê ly.",
  "dn17:1.29.5": "Ví như này Ānanda, âm thanh của nhạc cụ năm phần, được chỉnh khéo, gõ khéo, do những nhạc công thiện nghệ hòa tấu, thật du dương, khả ái, êm tai, mê ly;",
  "dn17:1.29.6": "cũng vậy, này Ānanda, khi những tấm lưới chuông ấy lay động theo gió, âm thanh phát ra thật du dương, khả ái, êm tai, mê ly.",
  "dn17:1.29.7": "Này Ānanda, những kẻ nghiện ngập, say sưa, khát rượu ở kinh đô Kusāvatī lúc bấy giờ đã được những âm thanh của các tấm lưới chuông lay động theo gió ấy làm cho thỏa thích.",
  "dn17:1.29.8": "Này Ānanda, khi hoàn thành, cung điện Dhamma chói sáng khó nhìn, làm lóa mắt.",
  "dn17:1.29.9": "Ví như này Ānanda, vào tháng cuối mùa mưa, trong tiết trời mùa thu, khi bầu trời quang đãng không mây, mặt trời vươn lên giữa hư không chói sáng khó nhìn, làm lóa mắt;",
  "dn17:1.29.10": "cũng vậy, này Ānanda, cung điện Dhamma chói sáng khó nhìn, làm lóa mắt.",
  "dn17:1.30.1": "Rồi này Ānanda, vua Mahāsudassana nghĩ rằng:",
  "dn17:1.30.2": "‘Hay là ta cho xây phía trước cung điện Dhamma một hồ sen tên là Dhamma.’",
  "dn17:1.30.3": "Này Ānanda, vua Mahāsudassana đã cho xây phía trước cung điện Dhamma một hồ sen tên là Dhamma.",
  "dn17:1.30.4": "Này Ānanda, hồ sen Dhamma dài một do-tuần theo hướng đông tây, rộng nửa do-tuần theo hướng bắc nam.",
  "dn17:1.30.5": "Này Ānanda, hồ sen Dhamma được xây bằng gạch bốn màu—",
  "dn17:1.30.6": "một loại gạch bằng vàng, một loại bằng bạc, một loại bằng lưu ly, một loại bằng pha lê.",
  "dn17:1.31.1": "Này Ānanda, hồ sen Dhamma có hai mươi bốn bậc thang thuộc bốn màu—",
  "dn17:1.31.2": "một bậc bằng vàng, một bậc bằng bạc, một bậc bằng lưu ly, một bậc bằng pha lê.",
  "dn17:1.31.3": "Ở bậc thang bằng vàng có các cột bằng vàng, còn các thanh ngang và đỉnh chóp bằng bạc.",
  "dn17:1.31.4": "Ở bậc thang bằng bạc có các cột bằng bạc, còn các thanh ngang và đỉnh chóp bằng vàng.",
  "dn17:1.31.5": "Ở bậc thang bằng lưu ly có các cột bằng lưu ly, còn các thanh ngang và đỉnh chóp bằng pha lê.",
  "dn17:1.31.6": "Ở bậc thang bằng pha lê có các cột bằng pha lê, còn các thanh ngang và đỉnh chóp bằng lưu ly.",
  "dn17:1.31.7": "Này Ānanda, hồ sen Dhamma được bao quanh bởi hai hàng lan can—một bằng vàng, một bằng bạc.",
  "dn17:1.31.8": "Ở lan can bằng vàng có các cột bằng vàng, còn các thanh ngang và đỉnh chóp bằng bạc.",
  "dn17:1.31.9": "Ở lan can bằng bạc có các cột bằng bạc, còn các thanh ngang và đỉnh chóp bằng vàng.",
  "dn17:1.32.1": "Này Ānanda, hồ sen Dhamma được bao quanh bởi bảy hàng cây ta-la—",
  "dn17:1.32.2": "một hàng bằng vàng, một hàng bằng bạc, một hàng bằng lưu ly, một hàng bằng pha lê, một hàng bằng hồng ngọc, một hàng bằng mã não, một hàng bằng đủ mọi châu báu.",
  "dn17:1.32.3": "Cây ta-la bằng vàng có thân bằng vàng, lá và quả bằng bạc.",
  "dn17:1.32.4": "Cây ta-la bằng bạc có thân bằng bạc, lá và quả bằng vàng.",
  "dn17:1.32.5": "Cây ta-la bằng lưu ly có thân bằng lưu ly, lá và quả bằng pha lê.",
  "dn17:1.32.6": "Cây ta-la bằng pha lê có thân bằng pha lê, lá và quả bằng lưu ly.",
  "dn17:1.32.7": "Cây ta-la bằng hồng ngọc có thân bằng hồng ngọc, lá và quả bằng mã não.",
  "dn17:1.32.8": "Cây ta-la bằng mã não có thân bằng mã não, lá và quả bằng hồng ngọc.",
  "dn17:1.32.9": "Cây ta-la bằng đủ mọi châu báu có thân bằng đủ mọi châu báu, lá và quả cũng bằng đủ mọi châu báu.",
  "dn17:1.32.10": "Này Ānanda, khi những hàng cây ta-la ấy lay động theo gió, âm thanh phát ra thật du dương, khả ái, êm tai, mê ly.",
  "dn17:1.32.11": "Ví như này Ānanda, âm thanh của nhạc cụ năm phần, được chỉnh khéo, gõ khéo, do những nhạc công thiện nghệ hòa tấu, thật du dương, khả ái, êm tai, mê ly;",
  "dn17:1.32.12": "cũng vậy, này Ānanda, khi những hàng cây ta-la ấy lay động theo gió, âm thanh phát ra thật du dương, khả ái, êm tai, mê ly.",
  "dn17:1.32.13": "Này Ānanda, những kẻ nghiện ngập, say sưa, khát rượu ở kinh đô Kusāvatī lúc bấy giờ đã được những âm thanh của các hàng cây ta-la lay động theo gió ấy làm cho thỏa thích.",
  "dn17:1.33.1": "Này Ānanda, khi cung điện Dhamma đã hoàn thành và hồ sen Dhamma cũng đã hoàn thành, vua Mahāsudassana làm cho những vị sa-môn được xem là sa-môn và những vị bà-la-môn được xem là bà-la-môn lúc bấy giờ thỏa mãn với mọi dục lạc, rồi bước lên cung điện Dhamma.",
  "dn17:1.33.2": "Phần tụng đọc thứ nhất.",
  "dn17:2.1.0": "5. Thành tựu thiền",
  "dn17:2.1.1": "Rồi này Ānanda, vua Mahāsudassana nghĩ rằng:",
  "dn17:2.1.2": "‘Do nghiệp gì mà nay ta có được quả này, có được dị thục của nghiệp này, khiến ta hiện giờ có đại thần lực, đại uy lực như vậy?’",
  "dn17:2.1.3": "Rồi này Ānanda, vua Mahāsudassana nghĩ rằng:",
  "dn17:2.1.4": "‘Nay ta có được quả này, có được dị thục của nghiệp này, khiến ta hiện giờ có đại thần lực, đại uy lực như vậy, là do ba nghiệp, đó là—",
  "dn17:2.1.5": "bố thí, điều phục và tự chế.’",
  "dn17:2.2.1": "Rồi này Ānanda, vua Mahāsudassana đi đến lầu gác Mahāviyūha; đến nơi, đứng ở cửa lầu gác Mahāviyūha, ngài thốt lên lời cảm hứng:",
  "dn17:2.2.2": "‘Hãy dừng lại, tầm dục; hãy dừng lại, tầm sân; hãy dừng lại, tầm hại.",
  "dn17:2.2.3": "Đến đây thôi, tầm dục; đến đây thôi, tầm sân; đến đây thôi, tầm hại.’",
  "dn17:2.3.1": "Rồi này Ānanda, vua Mahāsudassana bước vào lầu gác Mahāviyūha, ngồi trên chiếc giường bằng vàng, ly dục, ly các pháp bất thiện, chứng và an trú sơ thiền, một trạng thái hỷ lạc do ly sinh, có tầm có tứ.",
  "dn17:2.3.2": "Do tầm và tứ lắng dịu, ngài chứng và an trú nhị thiền, trạng thái hỷ lạc do định sinh, nội tĩnh nhất tâm, không tầm không tứ.",
  "dn17:2.3.3": "Do ly hỷ, ngài an trú xả, chánh niệm tỉnh giác, thân cảm nhận lạc thọ mà các bậc Thánh gọi là: ‘xả niệm lạc trú’, ngài chứng và an trú tam thiền.",
  "dn17:2.3.4": "Do đoạn lạc, đoạn khổ, do hỷ ưu đã diệt từ trước, ngài chứng và an trú tứ thiền, không khổ không lạc, thanh tịnh bởi xả niệm.",
  "dn17:2.4.1": "Rồi này Ānanda, vua Mahāsudassana từ lầu gác Mahāviyūha đi ra, bước vào lầu gác bằng vàng, ngồi trên chiếc giường bằng bạc,",
  "dn17:2.4.2": "an trú với tâm câu hữu với từ, thấm nhuần một phương. Cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư. Như vậy, trên, dưới, ngang, khắp mọi nơi, đối với tất cả như đối với chính mình, ngài an trú biến mãn toàn thế giới với tâm câu hữu với từ, rộng lớn, cao thượng, vô lượng, không oán, không hại.",
  "dn17:2.4.3": "Với tâm câu hữu với bi …",
  "dn17:2.4.4": "với tâm câu hữu với hỷ …",
  "dn17:2.4.5": "với tâm câu hữu với xả, ngài thấm nhuần một phương. Cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư. Như vậy, trên, dưới, ngang, khắp mọi nơi, đối với tất cả như đối với chính mình, ngài an trú biến mãn toàn thế giới với tâm câu hữu với xả, rộng lớn, cao thượng, vô lượng, không oán, không hại.",
  "dn17:2.5.0": "6. Tám mươi bốn ngàn thành phố v.v.",
  "dn17:2.5.1": "Này Ānanda, vua Mahāsudassana có tám mươi bốn ngàn thành phố, đứng đầu là kinh đô Kusāvatī;",
  "dn17:2.5.2": "có tám mươi bốn ngàn cung điện, đứng đầu là cung điện Dhamma;",
  "dn17:2.5.3": "có tám mươi bốn ngàn lầu gác, đứng đầu là lầu gác Mahāviyūha;",
  "dn17:2.5.4": "có tám mươi bốn ngàn giường, bằng vàng, bằng bạc, bằng ngà, bằng gỗ quý, trải nệm len dài, trải nệm len trắng, trải nệm thêu hoa, phủ tấm trải bằng da sơn dương quý, có màn che phía trên, có gối đỏ ở hai đầu;",
  "dn17:2.5.5": "có tám mươi bốn ngàn voi, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là voi chúa Uposatha;",
  "dn17:2.5.6": "có tám mươi bốn ngàn ngựa, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là ngựa chúa Valāhaka;",
  "dn17:2.5.7": "có tám mươi bốn ngàn xe, bọc da sư tử, bọc da cọp, bọc da báo, bọc chăn lông vàng nhạt, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là cỗ xe báu Vejayanta;",
  "dn17:2.5.8": "có tám mươi bốn ngàn ngọc báu, đứng đầu là ngọc như ý;",
  "dn17:2.5.9": "có tám mươi bốn ngàn phụ nữ, đứng đầu là hoàng hậu Subhaddā;",
  "dn17:2.5.10": "có tám mươi bốn ngàn gia chủ, đứng đầu là gia chủ báu;",
  "dn17:2.5.11": "có tám mươi bốn ngàn sát-đế-lỵ làm tùy tùng, đứng đầu là vị tướng quân báu;",
  "dn17:2.5.12": "có tám mươi bốn ngàn bò cái, cho sữa dồi dào, mang đồ đựng bằng đồng;",
  "dn17:2.5.13": "có tám mươi bốn ngàn kho vải, gồm vải gai mịn, vải bông mịn, vải tơ mịn, vải len mịn;",
  "dn17:2.5.14": "này Ānanda, vua Mahāsudassana có tám mươi bốn ngàn nồi cơm, sáng chiều đều được dâng thức ăn.",
  "dn17:2.6.1": "Này Ānanda, lúc bấy giờ tám mươi bốn ngàn voi của vua Mahāsudassana sáng chiều đều đến chầu hầu.",
  "dn17:2.6.2": "Rồi này Ānanda, vua Mahāsudassana nghĩ rằng:",
  "dn17:2.6.3": "‘Tám mươi bốn ngàn voi này của ta sáng chiều đều đến chầu hầu; hay là cứ mỗi trăm năm trôi qua, bốn mươi hai ngàn voi lại đến chầu hầu một lần.’",
  "dn17:2.6.4": "Rồi này Ānanda, vua Mahāsudassana gọi vị tướng quân báu:",
  "dn17:2.6.5": "‘Này hiền tướng quân báu, tám mươi bốn ngàn voi này của ta sáng chiều đều đến chầu hầu; vậy thì, này hiền tướng quân báu, cứ mỗi trăm năm trôi qua, bốn mươi hai ngàn voi hãy đến chầu hầu một lần.’",
  "dn17:2.6.6": "‘Vâng, thưa Đại vương,’ này Ānanda, vị tướng quân báu đáp lời vua Mahāsudassana.",
  "dn17:2.6.7": "Rồi này Ānanda, sau một thời gian, cứ mỗi trăm năm trôi qua, bốn mươi hai ngàn voi lại đến chầu hầu một lần.",
  "dn17:2.7.0": "7. Hoàng hậu Subhaddā đến yết kiến",
  "dn17:2.7.1": "Rồi này Ānanda, sau nhiều năm, nhiều trăm năm, nhiều ngàn năm, hoàng hậu Subhaddā nghĩ rằng:",
  "dn17:2.7.2": "‘Đã lâu ta không gặp vua Mahāsudassana. Hay là ta đến yết kiến vua Mahāsudassana.’",
  "dn17:2.7.3": "Rồi này Ānanda, hoàng hậu Subhaddā bảo các cung nữ:",
  "dn17:2.7.4": "‘Nào các ngươi, hãy gội đầu và mặc y phục màu vàng.",
  "dn17:2.7.5": "Đã lâu chúng ta không gặp vua Mahāsudassana, chúng ta sẽ đến yết kiến vua Mahāsudassana.’",
  "dn17:2.7.6": "‘Vâng, thưa phu nhân,’ này Ānanda, các cung nữ vâng lời hoàng hậu Subhaddā, gội đầu, mặc y phục màu vàng, rồi đi đến chỗ hoàng hậu Subhaddā.",
  "dn17:2.8.1": "Rồi này Ānanda, hoàng hậu Subhaddā bảo vị tướng quân báu:",
  "dn17:2.8.2": "‘Này hiền tướng quân báu, hãy chuẩn bị bốn binh chủng; đã lâu chúng ta không gặp vua Mahāsudassana, chúng ta sẽ đến yết kiến vua Mahāsudassana.’",
  "dn17:2.8.3": "‘Vâng, thưa hoàng hậu’, này Ānanda, bảo vật tướng quân đáp lời hoàng hậu Subhaddā như vậy, cho chuẩn bị bốn binh chủng rồi tâu với hoàng hậu Subhaddā: ",
  "dn17:2.8.4": "‘Thưa hoàng hậu, quân đội bốn binh chủng đã được chuẩn bị, ",
  "dn17:2.8.5": "nay bà thấy lúc nào thích hợp thì xin cứ làm.’ ",
  "dn17:2.8.6": "Rồi này Ānanda, hoàng hậu Subhaddā cùng với quân đội bốn binh chủng và hậu cung đi đến pháp điện; đến nơi, bước lên pháp điện rồi đi đến đại lầu các Mahāviyūha. ",
  "dn17:2.8.7": "Đến nơi, bà vịn cột cửa của đại lầu các Mahāviyūha mà đứng. ",
  "dn17:2.8.8": "Rồi này Ānanda, vua Mahāsudassana nghe tiếng động, ",
  "dn17:2.8.9": "nghĩ rằng: ‘Sao lại có tiếng ồn của một đám đông lớn như vậy?’ Khi đi ra khỏi đại lầu các Mahāviyūha, vua thấy hoàng hậu Subhaddā đang đứng vịn cột cửa; thấy vậy, vua nói với hoàng hậu Subhaddā: ",
  "dn17:2.8.10": "‘Hoàng hậu, hãy đứng ngay đó, đừng vào.’ ",
  "dn17:2.9.1": "Rồi này Ānanda, vua Mahāsudassana gọi một người đàn ông: ",
  "dn17:2.9.2": "‘Này người kia, hãy đi đem chiếc giường bằng vàng ra khỏi đại lầu các Mahāviyūha và dọn nó trong rừng cọ toàn bằng vàng.’ ",
  "dn17:2.9.3": "‘Vâng, thưa đại vương’, này Ānanda, người ấy đáp lời vua Mahāsudassana như vậy, rồi đem chiếc giường bằng vàng ra khỏi đại lầu các Mahāviyūha và dọn nó trong rừng cọ toàn bằng vàng. ",
  "dn17:2.9.4": "Rồi này Ānanda, vua Mahāsudassana nằm xuống theo thế nằm sư tử, nghiêng hông bên phải, chân này gác lên chân kia, tỉnh giác chánh niệm. ",
  "dn17:2.10.1": "Rồi này Ānanda, hoàng hậu Subhaddā nghĩ rằng: ",
  "dn17:2.10.2": "‘Các căn của vua Mahāsudassana thật sáng suốt, sắc da thanh tịnh, trong sáng; chắc hẳn vua Mahāsudassana sắp mệnh chung rồi.’ Rồi bà nói với vua Mahāsudassana: ",
  "dn17:2.10.3": "‘Tâu đại vương, đây là tám mươi bốn ngàn thành, đứng đầu là kinh đô Kusāvatī. ",
  "dn17:2.10.4": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống. ",
  "dn17:2.10.5": "Tâu đại vương, đây là tám mươi bốn ngàn cung điện, đứng đầu là pháp điện. ",
  "dn17:2.10.6": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống. ",
  "dn17:2.10.7": "Tâu đại vương, đây là tám mươi bốn ngàn lầu các, đứng đầu là đại lầu các Mahāviyūha. ",
  "dn17:2.10.8": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống. ",
  "dn17:2.10.9": "Tâu đại vương, đây là tám mươi bốn ngàn giường, bằng vàng, bằng bạc, bằng ngà, bằng gỗ quý, trải nệm len dài, trải tấm phủ trắng, trải tấm thêu hoa, trải da linh dương quý, có tấm phủ phía trên, có gối đỏ ở cả hai đầu. ",
  "dn17:2.10.10": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống. ",
  "dn17:2.10.11": "Tâu đại vương, đây là tám mươi bốn ngàn voi, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là voi chúa Uposatha. ",
  "dn17:2.10.12": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống. ",
  "dn17:2.10.13": "Tâu đại vương, đây là tám mươi bốn ngàn ngựa, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là ngựa chúa Valāhaka. ",
  "dn17:2.10.14": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống. ",
  "dn17:2.10.15": "Tâu đại vương, đây là tám mươi bốn ngàn xe, bọc da sư tử, bọc da cọp, bọc da báo, bọc chăn lông vàng nhạt, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là chiến xa Vejayanta. ",
  "dn17:2.10.16": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống. ",
  "dn17:2.10.17": "Tâu đại vương, đây là tám mươi bốn ngàn châu báu, đứng đầu là bảo châu. ",
  "dn17:2.10.18": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống. ",
  "dn17:2.10.19": "Tâu đại vương, đây là tám mươi bốn ngàn phụ nữ, đứng đầu là nữ bảo. ",
  "dn17:2.10.20": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống. ",
  "dn17:2.10.21": "Tâu đại vương, đây là tám mươi bốn ngàn gia chủ, đứng đầu là gia chủ bảo. ",
  "dn17:2.10.22": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống. ",
  "dn17:2.10.23": "Tâu đại vương, đây là tám mươi bốn ngàn chiến sĩ Sát-đế-lỵ tùy tùng, đứng đầu là bảo vật tướng quân. ",
  "dn17:2.10.24": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống. ",
  "dn17:2.10.25": "Tâu đại vương, đây là tám mươi bốn ngàn bò cái, cho sữa dồi dào, có thùng đựng bằng đồng. ",
  "dn17:2.10.26": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống. ",
  "dn17:2.10.27": "Tâu đại vương, đây là tám mươi bốn ngàn kho y phục bằng vải gai mịn, vải bông mịn, lụa mịn, len mịn. ",
  "dn17:2.10.28": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống. ",
  "dn17:2.10.29": "Tâu đại vương, đây là tám mươi bốn ngàn mâm cơm nấu sẵn, sáng chiều đều được dâng thức ăn. ",
  "dn17:2.10.30": "Xin đại vương khởi lòng lưu luyến đối với chúng, hãy mong sống.’ ",
  "dn17:2.11.1": "Khi được nói vậy, này Ānanda, vua Mahāsudassana nói với hoàng hậu Subhaddā: ",
  "dn17:2.11.2": "‘Hoàng hậu, từ lâu nàng đã đối xử với ta bằng những điều khả ái, đáng yêu, thân thương, vừa ý; ",
  "dn17:2.11.3": "thế mà nay vào lúc cuối cùng, nàng lại đối xử với ta bằng những điều không khả ái, không đáng yêu, không thân thương, không vừa ý.’ ",
  "dn17:2.11.4": "‘Tâu đại vương, vậy thiếp phải đối xử với ngài thế nào?’ ",
  "dn17:2.11.5": "‘Hoàng hậu, hãy đối xử với ta như thế này: ",
  "dn17:2.11.6": "“Tâu đại vương, đối với tất cả những gì thân yêu và vừa ý, ắt có chia lìa, biệt ly, đổi khác. Xin đại vương chớ mệnh chung trong sự luyến chấp; chết trong luyến chấp là khổ, và chết trong luyến chấp là điều bị chê trách. ",
  "dn17:2.11.7": "Tâu đại vương, đây là tám mươi bốn ngàn thành, đứng đầu là kinh đô Kusāvatī. ",
  "dn17:2.11.8": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.11.9": "Tâu đại vương, đây là tám mươi bốn ngàn cung điện, đứng đầu là pháp điện. ",
  "dn17:2.11.10": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.11.11": "Tâu đại vương, đây là tám mươi bốn ngàn lầu các, đứng đầu là đại lầu các Mahāviyūha. ",
  "dn17:2.11.12": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.11.13": "Tâu đại vương, đây là tám mươi bốn ngàn giường, bằng vàng, bằng bạc, bằng ngà, bằng gỗ quý, trải nệm len dài, trải tấm phủ trắng, trải tấm thêu hoa, trải da linh dương quý, có tấm phủ phía trên, có gối đỏ ở cả hai đầu. ",
  "dn17:2.11.14": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.11.15": "Tâu đại vương, đây là tám mươi bốn ngàn voi, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là voi chúa Uposatha. ",
  "dn17:2.11.16": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.11.17": "Tâu đại vương, đây là tám mươi bốn ngàn ngựa, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là ngựa chúa Valāhaka. ",
  "dn17:2.11.18": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.11.19": "Tâu đại vương, đây là tám mươi bốn ngàn xe, bọc da sư tử, bọc da cọp, bọc da báo, bọc chăn lông vàng nhạt, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là chiến xa Vejayanta. ",
  "dn17:2.11.20": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.11.21": "Tâu đại vương, đây là tám mươi bốn ngàn châu báu, đứng đầu là bảo châu. ",
  "dn17:2.11.22": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.11.23": "Tâu đại vương, đây là tám mươi bốn ngàn phụ nữ, đứng đầu là hoàng hậu Subhaddā. ",
  "dn17:2.11.24": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.11.25": "Tâu đại vương, đây là tám mươi bốn ngàn gia chủ, đứng đầu là gia chủ bảo. ",
  "dn17:2.11.26": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.11.27": "Tâu đại vương, đây là tám mươi bốn ngàn chiến sĩ Sát-đế-lỵ tùy tùng, đứng đầu là bảo vật tướng quân. ",
  "dn17:2.11.28": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.11.29": "Tâu đại vương, đây là tám mươi bốn ngàn bò cái, cho sữa dồi dào, có thùng đựng bằng đồng. ",
  "dn17:2.11.30": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.11.31": "Tâu đại vương, đây là tám mươi bốn ngàn kho y phục bằng vải gai mịn, vải bông mịn, lụa mịn, len mịn. ",
  "dn17:2.11.32": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.11.33": "Tâu đại vương, đây là tám mươi bốn ngàn mâm cơm nấu sẵn, sáng chiều đều được dâng thức ăn. ",
  "dn17:2.11.34": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống.”’ ",
  "dn17:2.12.1": "Khi được nói vậy, này Ānanda, hoàng hậu Subhaddā khóc lớn, nước mắt tuôn trào. ",
  "dn17:2.12.2": "Rồi này Ānanda, hoàng hậu Subhaddā lau nước mắt rồi nói với vua Mahāsudassana: ",
  "dn17:2.12.3": "‘Tâu đại vương, đối với tất cả những gì thân yêu và vừa ý, ắt có chia lìa, biệt ly, đổi khác. Xin đại vương chớ mệnh chung trong sự luyến chấp; chết trong luyến chấp là khổ, và chết trong luyến chấp là điều bị chê trách. ",
  "dn17:2.12.4": "Tâu đại vương, đây là tám mươi bốn ngàn thành, đứng đầu là kinh đô Kusāvatī. ",
  "dn17:2.12.5": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.12.6": "Tâu đại vương, đây là tám mươi bốn ngàn cung điện, đứng đầu là pháp điện. ",
  "dn17:2.12.7": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.12.8": "Tâu đại vương, đây là tám mươi bốn ngàn lầu các, đứng đầu là đại lầu các Mahāviyūha. ",
  "dn17:2.12.9": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.12.10": "Tâu đại vương, đây là tám mươi bốn ngàn giường, bằng vàng, bằng bạc, bằng ngà, bằng gỗ quý, trải nệm len dài, trải tấm phủ trắng, trải tấm thêu hoa, trải da linh dương quý, có tấm phủ phía trên, có gối đỏ ở cả hai đầu. ",
  "dn17:2.12.11": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.12.12": "Tâu đại vương, đây là tám mươi bốn ngàn voi, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là voi chúa Uposatha. ",
  "dn17:2.12.13": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.12.14": "Tâu đại vương, đây là tám mươi bốn ngàn ngựa, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là ngựa chúa Valāhaka. ",
  "dn17:2.12.15": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.12.16": "Tâu đại vương, đây là tám mươi bốn ngàn xe, bọc da sư tử, bọc da cọp, bọc da báo, bọc chăn lông vàng nhạt, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là chiến xa Vejayanta. ",
  "dn17:2.12.17": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.12.18": "Tâu đại vương, đây là tám mươi bốn ngàn châu báu, đứng đầu là bảo châu. ",
  "dn17:2.12.19": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.12.20": "Tâu đại vương, đây là tám mươi bốn ngàn phụ nữ, đứng đầu là nữ bảo. ",
  "dn17:2.12.21": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.12.22": "Tâu đại vương, đây là tám mươi bốn ngàn gia chủ, đứng đầu là gia chủ bảo. ",
  "dn17:2.12.23": "Đối với chúng, xin đại vương hãy từ bỏ lòng ham muốn, chớ lưu luyến mạng sống. ",
  "dn17:2.12.24": "Tâu đại vương, đây là tám mươi bốn ngàn chiến sĩ Sát-đế-lỵ tùy tùng, đứng đầu là bảo vật tướng quân. ",
  "dn17:2.12.25": "Ở đây, thưa Đại vương, hãy từ bỏ lòng ham muốn, chớ luyến tiếc mạng sống.",
  "dn17:2.12.26": "Đây là tám mươi bốn ngàn con bò sữa của ngài, thưa Đại vương, đang cho sữa và có đồ đựng bằng đồng.",
  "dn17:2.12.27": "Ở đây, thưa Đại vương, hãy từ bỏ lòng ham muốn, chớ luyến tiếc mạng sống.",
  "dn17:2.12.28": "Đây là tám mươi bốn ngàn kho vải của ngài, thưa Đại vương, gồm vải gai mịn, vải bông mịn, vải tơ mịn và vải len mịn.",
  "dn17:2.12.29": "Ở đây, thưa Đại vương, hãy từ bỏ lòng ham muốn, chớ luyến tiếc mạng sống.",
  "dn17:2.12.30": "Đây là tám mươi bốn ngàn nồi cơm của ngài, thưa Đại vương, mà mỗi sáng mỗi chiều đều được dâng thức ăn.",
  "dn17:2.12.31": "Ở đây, thưa Đại vương, hãy từ bỏ lòng ham muốn, chớ luyến tiếc mạng sống.",
  "dn17:2.13.0": "8. Sinh lên cõi Phạm thiên",
  "dn17:2.13.1": "Bấy giờ, này Ānanda, không bao lâu sau vua Mahāsudassana mệnh chung.",
  "dn17:2.13.2": "Ví như, này Ānanda, một gia chủ hay con trai gia chủ sau khi ăn món ăn ngon thì cảm thấy khoan khoái vì bữa ăn; cũng vậy, này Ānanda, cảm thọ lúc lâm chung của vua Mahāsudassana là như thế.",
  "dn17:2.13.3": "Và sau khi mạng chung, này Ānanda, vua Mahāsudassana được sinh vào cõi lành, cõi Phạm thiên.",
  "dn17:2.13.4": "Này Ānanda, vua Mahāsudassana đã vui chơi trò chơi vương tử suốt tám mươi bốn ngàn năm.",
  "dn17:2.13.5": "Suốt tám mươi bốn ngàn năm, ngài làm phó vương.",
  "dn17:2.13.6": "Suốt tám mươi bốn ngàn năm, ngài trị vì vương quốc.",
  "dn17:2.13.7": "Suốt tám mươi bốn ngàn năm, khi còn là cư sĩ, ngài sống phạm hạnh trong cung điện Dhamma.",
  "dn17:2.13.8": "Vị ấy sau khi tu tập bốn phạm trú, khi thân hoại mạng chung, đã sinh lên cõi Phạm thiên.",
  "dn17:2.14.1": "Này Ānanda, có thể ông nghĩ như sau:",
  "dn17:2.14.2": "‘Chắc hẳn vào thời ấy có một vị vua Mahāsudassana khác’,",
  "dn17:2.14.3": "nhưng này Ānanda, không nên thấy như vậy. Ta vào thời ấy chính là vua Mahāsudassana.",
  "dn17:2.14.4": "Tám mươi bốn ngàn thành phố ấy, đứng đầu là kinh đô Kusāvatī, là của Ta; tám mươi bốn ngàn cung điện ấy, đứng đầu là cung điện Dhamma, là của Ta; tám mươi bốn ngàn lầu gác ấy, đứng đầu là lầu gác Mahāviyūha, là của Ta; tám mươi bốn ngàn bảo tọa ấy, bằng vàng, bằng bạc, bằng ngà, bằng gỗ quý, trải thảm len dài, trải thảm trắng, trải thảm hoa, phủ da linh dương quý, có tấm che phía trên và gối đỏ ở hai đầu, là của Ta; tám mươi bốn ngàn voi ấy, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là voi chúa Uposatha, là của Ta; tám mươi bốn ngàn ngựa ấy, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là ngựa chúa Valāhaka, là của Ta; tám mươi bốn ngàn xe ấy, bọc da sư tử, bọc da cọp, bọc da beo, bọc len màu vàng nhạt, trang sức bằng vàng, cờ vàng, phủ lưới vàng, đứng đầu là xe Vejayanta, là của Ta; tám mươi bốn ngàn châu báu ấy, đứng đầu là ngọc báu, là của Ta; tám mươi bốn ngàn phụ nữ ấy, đứng đầu là hoàng hậu Subhaddā, là của Ta; tám mươi bốn ngàn gia chủ ấy, đứng đầu là gia chủ báu, là của Ta; tám mươi bốn ngàn sát-đế-lỵ ấy, là những người tùy tùng, đứng đầu là vị tướng quân báu, là của Ta; tám mươi bốn ngàn con bò sữa ấy, đang cho sữa và có đồ đựng bằng đồng, là của Ta; tám mươi bốn ngàn kho vải ấy, gồm vải gai mịn, vải bông mịn, vải tơ mịn và vải len mịn, là của Ta; tám mươi bốn ngàn nồi cơm ấy, mà mỗi sáng mỗi chiều đều được dâng thức ăn, là của Ta.",
  "dn17:2.15.1": "Nhưng này Ānanda, trong số tám mươi bốn ngàn thành phố ấy, chỉ có một thành phố là nơi Ta cư ngụ vào thời ấy, tức là kinh đô Kusāvatī.",
  "dn17:2.15.2": "Nhưng này Ānanda, trong số tám mươi bốn ngàn cung điện ấy, chỉ có một cung điện là nơi Ta cư ngụ vào thời ấy, tức là cung điện Dhamma.",
  "dn17:2.15.3": "Nhưng này Ānanda, trong số tám mươi bốn ngàn lầu gác ấy, chỉ có một lầu gác là nơi Ta cư ngụ vào thời ấy, tức là lầu gác Mahāviyūha.",
  "dn17:2.15.4": "Nhưng này Ānanda, trong số tám mươi bốn ngàn bảo tọa ấy, chỉ có một bảo tọa là thứ Ta dùng vào thời ấy, tức là bảo tọa bằng vàng, hoặc bằng bạc, hoặc bằng ngà, hoặc bằng gỗ quý.",
  "dn17:2.15.5": "Nhưng này Ānanda, trong số tám mươi bốn ngàn voi ấy, chỉ có một con voi là thứ Ta cưỡi vào thời ấy, tức là voi chúa Uposatha.",
  "dn17:2.15.6": "Nhưng này Ānanda, trong số tám mươi bốn ngàn ngựa ấy, chỉ có một con ngựa là thứ Ta cưỡi vào thời ấy, tức là ngựa chúa Valāhaka.",
  "dn17:2.15.7": "Nhưng này Ānanda, trong số tám mươi bốn ngàn xe ấy, chỉ có một cỗ xe là thứ Ta cưỡi vào thời ấy, tức là xe Vejayanta.",
  "dn17:2.15.8": "Nhưng này Ānanda, trong số tám mươi bốn ngàn phụ nữ ấy, chỉ có một người phụ nữ là người hầu cận Ta vào thời ấy, hoặc là một nữ sát-đế-lỵ hoặc là một nữ thương gia.",
  "dn17:2.15.9": "Nhưng này Ānanda, trong số tám mươi bốn ngàn kho vải ấy, chỉ có một đôi y phục là thứ Ta mặc vào thời ấy, hoặc bằng vải gai mịn, hoặc bằng vải bông mịn, hoặc bằng vải tơ mịn, hoặc bằng vải len mịn.",
  "dn17:2.15.10": "Nhưng này Ānanda, trong số tám mươi bốn ngàn nồi cơm ấy, chỉ có một nồi cơm là thứ Ta ăn, tối đa là cơm gạo hảo hạng cùng với món canh.",
  "dn17:2.16.1": "Hãy xem, này Ānanda, tất cả các hành ấy đều đã qua, đã diệt, đã biến đổi.",
  "dn17:2.16.2": "Các hành là vô thường như vậy, này Ānanda;",
  "dn17:2.16.3": "các hành là không bền chắc như vậy, này Ānanda;",
  "dn17:2.16.4": "các hành là không đáng nương cậy như vậy, này Ānanda.",
  "dn17:2.16.5": "Chừng ấy cũng đủ, này Ānanda, để nhàm chán đối với tất cả các hành, đủ để ly tham, đủ để giải thoát.",
  "dn17:2.17.1": "Này Ānanda, Ta nhớ rõ rằng tại chỗ này Ta đã sáu lần bỏ thân, và mỗi lần đều là một vị vua, một Chuyển luân vương, bậc chân chánh, pháp vương, chinh phục bốn phương, đạt được sự vững mạnh trong quốc độ, đầy đủ bảy báu; đây là lần bỏ thân thứ bảy.",
  "dn17:2.17.2": "Nhưng này Ānanda, Ta không thấy một nơi nào khác trong thế gian này cùng với chư thiên, Ma vương, Phạm thiên, trong quần sinh gồm sa-môn, bà-la-môn, chư thiên và loài người, mà ở đó Như Lai sẽ bỏ thân lần thứ tám.",
  "dn17:2.17.3": "Thế Tôn đã nói như vậy.",
  "dn17:2.17.4": "Nói xong, bậc Thiện Thệ lại nói thêm lời này:",
  "dn17:2.17.5": "“Thật vậy, các hành là vô thường,",
  "dn17:2.17.6": "có tính chất sinh rồi diệt;",
  "dn17:2.17.7": "đã sinh lên rồi thì diệt mất,",
  "dn17:2.17.8": "sự lắng dịu của chúng là an lạc.”",
  "dn17:2.17.9": "Kinh Đại Thiện Kiến, thứ tư, đã hoàn tất."
}
window.BILARA["dn17"]["vi"]["dn17:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
