window.BILARA = window.BILARA || {};
window.BILARA["dn18"] = window.BILARA["dn18"] || {};
window.BILARA["dn18"]["vi"] = {
  "dn18:0.1": "Trường Bộ Kinh 18 ",
  "dn18:0.2": "Kinh Janavasabha ",
  "dn18:1.0": "1. Thuyết giảng về những người ở Nātika ",
  "dn18:1.1": "Tôi nghe như vầy—",
  "dn18:1.2": "Một thời Thế Tôn trú tại Nātika, ở ngôi nhà gạch. ",
  "dn18:1.3": "Lúc bấy giờ, Thế Tôn tuyên thuyết về chỗ tái sinh của những cận sự nam đã qua đời, mệnh chung, ở khắp các xứ: Kāsi, Kosala, Vajji, Malla, Ceti, Vaṁsa, Kuru, Pañcāla, Maccha, Sūrasena: ",
  "dn18:1.4": "“Người này sinh về chỗ kia, người kia sinh về chỗ nọ. ",
  "dn18:1.5": "Hơn năm mươi cận sự nam ở Nātika đã qua đời, mệnh chung; do đoạn tận năm hạ phần kiết sử, họ hóa sinh, tại đó nhập Niết-bàn, không còn trở lui từ thế giới ấy. ",
  "dn18:1.6": "Hơn chín mươi cận sự nam ở Nātika đã qua đời, mệnh chung; do đoạn tận ba kiết sử, làm mỏng tham, sân, si, họ là bậc Nhất lai, chỉ còn trở lại thế gian này một lần nữa rồi sẽ chấm dứt khổ đau. ",
  "dn18:1.7": "Hơn năm trăm cận sự nam ở Nātika đã qua đời, mệnh chung; do đoạn tận ba kiết sử, họ là bậc Dự lưu, không còn đọa xứ, nhất định hướng đến giác ngộ.”",
  "dn18:2.1": "Các cận sự nam ở Nātika nghe rằng: ",
  "dn18:2.2": "“Nghe nói Thế Tôn tuyên thuyết về chỗ tái sinh của những cận sự nam đã qua đời, mệnh chung, ở khắp các xứ: Kāsi, Kosala, Vajji, Malla, Ceti, Vaṁsa, Kuru, Pañcāla, Maccha, Sūrasena: ",
  "dn18:2.3": "‘Người này sinh về chỗ kia, người kia sinh về chỗ nọ. ",
  "dn18:2.4": "Hơn năm mươi cận sự nam ở Nātika đã qua đời, mệnh chung; do đoạn tận năm hạ phần kiết sử, họ hóa sinh, tại đó nhập Niết-bàn, không còn trở lui từ thế giới ấy. ",
  "dn18:2.5": "Hơn chín mươi cận sự nam ở Nātika đã qua đời, mệnh chung; do đoạn tận ba kiết sử, làm mỏng tham, sân, si, họ là bậc Nhất lai, chỉ còn trở lại thế gian này một lần nữa rồi sẽ chấm dứt khổ đau. ",
  "dn18:2.6": "Hơn năm trăm cận sự nam ở Nātika đã qua đời, mệnh chung; do đoạn tận ba kiết sử, họ là bậc Dự lưu, không còn đọa xứ, nhất định hướng đến giác ngộ.’”",
  "dn18:2.7": "Và các cận sự nam ở Nātika hoan hỷ, vui mừng, hân hoan, tâm sinh hỷ lạc khi nghe Thế Tôn giải đáp câu hỏi ấy. ",
  "dn18:3.1": "Tôn giả Ānanda nghe rằng: ",
  "dn18:3.2": "“Nghe nói Thế Tôn tuyên thuyết về chỗ tái sinh của những cận sự nam đã qua đời, mệnh chung, ở khắp các xứ: Kāsi, Kosala, Vajji, Malla, Ceti, Vaṁsa, Kuru, Pañcāla, Maccha, Sūrasena: ",
  "dn18:3.3": "‘Người này sinh về chỗ kia, người kia sinh về chỗ nọ. ",
  "dn18:3.4": "Hơn năm mươi cận sự nam ở Nātika đã qua đời, mệnh chung; do đoạn tận năm hạ phần kiết sử, họ hóa sinh, tại đó nhập Niết-bàn, không còn trở lui từ thế giới ấy. ",
  "dn18:3.5": "Hơn chín mươi cận sự nam ở Nātika đã qua đời, mệnh chung; do đoạn tận ba kiết sử, làm mỏng tham, sân, si, họ là bậc Nhất lai, chỉ còn trở lại thế gian này một lần nữa rồi sẽ chấm dứt khổ đau. ",
  "dn18:3.6": "Hơn năm trăm cận sự nam ở Nātika đã qua đời, mệnh chung; do đoạn tận ba kiết sử, họ là bậc Dự lưu, không còn đọa xứ, nhất định hướng đến giác ngộ.’ ",
  "dn18:3.7": "Và các cận sự nam ở Nātika hoan hỷ, vui mừng, hân hoan, tâm sinh hỷ lạc khi nghe Thế Tôn giải đáp câu hỏi ấy.”",
  "dn18:4.0": "2. Lời suy nghĩ của Ānanda ",
  "dn18:4.1": "Rồi tôn giả Ānanda nghĩ như sau: ",
  "dn18:4.2": "“Những cận sự nam xứ Magadha này cũng có nhiều người đã lâu năm và đã qua đời, mệnh chung. ",
  "dn18:4.3": "Ta nghĩ rằng xứ Aṅga và Magadha hẳn đã vắng những cận sự nam Aṅga-Magadha đã qua đời, mệnh chung. ",
  "dn18:4.4": "Họ cũng là những người có lòng tin nơi Phật, có lòng tin nơi Pháp, có lòng tin nơi Tăng, thành tựu đầy đủ giới hạnh. ",
  "dn18:4.5": "Nhưng những người ấy đã qua đời, mệnh chung mà chưa được Thế Tôn tuyên thuyết; ",
  "dn18:4.6": "nếu được tuyên thuyết về họ thì thật tốt, nhiều người sẽ sinh lòng tin, từ đó sẽ đi đến thiện thú. ",
  "dn18:4.7": "Vị này cũng từng là vua xứ Magadha, Seniya Bimbisāra, một vị vua chân chánh, trị nước theo pháp, đem lợi ích cho các bà-la-môn, gia chủ, dân thị thành và dân thôn quê. ",
  "dn18:4.8": "Lại nữa, người ta vẫn thường ca ngợi rằng: ",
  "dn18:4.9": "‘Vị pháp vương chân chánh ấy đã làm cho chúng ta được an vui rồi mới qua đời; chúng ta đã sống an ổn trong quốc độ của vị pháp vương chân chánh ấy.’ ",
  "dn18:4.10": "Vị ấy cũng là người có lòng tin nơi Phật, có lòng tin nơi Pháp, có lòng tin nơi Tăng, thành tựu đầy đủ giới hạnh. ",
  "dn18:4.11": "Lại nữa, người ta còn nói rằng: ",
  "dn18:4.12": "‘Cho đến lúc lâm chung, vua Magadha Seniya Bimbisāra vẫn còn ca ngợi Thế Tôn rồi mới qua đời.’ ",
  "dn18:4.13": "Vị ấy đã qua đời, mệnh chung mà chưa được Thế Tôn tuyên thuyết. ",
  "dn18:4.14": "Nếu được tuyên thuyết về vị ấy thì thật tốt, nhiều người sẽ sinh lòng tin, từ đó sẽ đi đến thiện thú. ",
  "dn18:4.15": "Vả lại, sự giác ngộ của Thế Tôn là ở xứ Magadha. ",
  "dn18:4.16": "Nơi nào Thế Tôn giác ngộ là ở xứ Magadha, thì làm sao tại đó Thế Tôn lại không tuyên thuyết về chỗ tái sinh của những cận sự nam xứ Magadha đã qua đời, mệnh chung? ",
  "dn18:4.17": "Nếu Thế Tôn không tuyên thuyết về chỗ tái sinh của những cận sự nam xứ Magadha đã qua đời, mệnh chung, thì các cận sự nam xứ Magadha sẽ buồn lòng; ",
  "dn18:4.18": "mà nếu các cận sự nam xứ Magadha buồn lòng như vậy, thì làm sao Thế Tôn lại không tuyên thuyết về họ?” ",
  "dn18:5.1": "Sau khi một mình suy nghĩ kín đáo về các cận sự nam xứ Magadha như vậy, đến gần sáng, tôn giả Ānanda từ chỗ ngồi đứng dậy, đi đến chỗ Thế Tôn; đến nơi, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Khi đã ngồi xuống một bên, tôn giả Ānanda bạch Thế Tôn: ",
  "dn18:5.2": "“Bạch Thế Tôn, con có nghe rằng: ",
  "dn18:5.3": "‘Nghe nói Thế Tôn tuyên thuyết về chỗ tái sinh của những cận sự nam đã qua đời, mệnh chung, ở khắp các xứ: Kāsi, Kosala, Vajji, Malla, Ceti, Vaṁsa, Kuru, Pañcāla, Maccha, Sūrasena: ",
  "dn18:5.4": "“Người này sinh về chỗ kia, người kia sinh về chỗ nọ. ",
  "dn18:5.5": "Hơn năm mươi cận sự nam ở Nātika đã qua đời, mệnh chung; do đoạn tận năm hạ phần kiết sử, họ hóa sinh, tại đó nhập Niết-bàn, không còn trở lui từ thế giới ấy. ",
  "dn18:5.6": "Hơn chín mươi cận sự nam ở Nātika đã qua đời, mệnh chung; do đoạn tận ba kiết sử, làm mỏng tham, sân, si, họ là bậc Nhất lai, chỉ còn trở lại thế gian này một lần nữa rồi sẽ chấm dứt khổ đau. ",
  "dn18:5.7": "Hơn năm trăm cận sự nam ở Nātika đã qua đời, mệnh chung; do đoạn tận ba kiết sử, họ là bậc Dự lưu, không còn đọa xứ, nhất định hướng đến giác ngộ. ",
  "dn18:5.8": "Và các cận sự nam ở Nātika hoan hỷ, vui mừng, hân hoan, tâm sinh hỷ lạc khi nghe Thế Tôn giải đáp câu hỏi ấy.’”",
  "dn18:5.9": "Bạch Thế Tôn, những cận sự nam xứ Magadha này cũng có nhiều người đã lâu năm và đã qua đời, mệnh chung. ",
  "dn18:5.10": "Con nghĩ rằng xứ Aṅga và Magadha hẳn đã vắng những cận sự nam Aṅga-Magadha đã qua đời, mệnh chung. ",
  "dn18:5.11": "Bạch Thế Tôn, họ cũng là những người có lòng tin nơi Phật, có lòng tin nơi Pháp, có lòng tin nơi Tăng, thành tựu đầy đủ giới hạnh; nhưng những người ấy đã qua đời, mệnh chung mà chưa được Thế Tôn tuyên thuyết. ",
  "dn18:5.12": "Nếu được tuyên thuyết về họ thì thật tốt, nhiều người sẽ sinh lòng tin, từ đó sẽ đi đến thiện thú. ",
  "dn18:5.13": "Bạch Thế Tôn, vị này cũng từng là vua xứ Magadha, Seniya Bimbisāra, một vị vua chân chánh, trị nước theo pháp, đem lợi ích cho các bà-la-môn, gia chủ, dân thị thành và dân thôn quê. ",
  "dn18:5.14": "Lại nữa, người ta vẫn thường ca ngợi rằng: ",
  "dn18:5.15": "‘Vị pháp vương chân chánh ấy đã làm cho chúng ta được an vui rồi mới qua đời. ",
  "dn18:5.16": "Chúng ta đã sống an ổn trong quốc độ của vị pháp vương chân chánh ấy.’ ",
  "dn18:6.1": "Vị ấy cũng là người có lòng tin nơi Phật, có lòng tin nơi Pháp, có lòng tin nơi Tăng, thành tựu đầy đủ giới hạnh. ",
  "dn18:6.2": "Lại nữa, người ta còn nói rằng: ",
  "dn18:6.3": "‘Cho đến lúc lâm chung, vua Magadha Seniya Bimbisāra vẫn còn ca ngợi Thế Tôn rồi mới qua đời.’ ",
  "dn18:6.4": "Vị ấy đã qua đời, mệnh chung mà chưa được Thế Tôn tuyên thuyết; ",
  "dn18:6.5": "nếu được tuyên thuyết về vị ấy thì thật tốt, nhiều người sẽ sinh lòng tin, từ đó sẽ đi đến thiện thú. ",
  "dn18:6.6": "Bạch Thế Tôn, sự giác ngộ của Thế Tôn là ở xứ Magadha. ",
  "dn18:6.7": "Nơi nào sự giác ngộ của Thế Tôn là ở xứ Magadha, thì làm sao tại đó Thế Tôn lại không tuyên thuyết về chỗ tái sinh của những cận sự nam xứ Magadha đã qua đời, mệnh chung? ",
  "dn18:6.8": "Nếu Thế Tôn không tuyên thuyết về chỗ tái sinh của những cận sự nam xứ Magadha đã qua đời, mệnh chung, thì các cận sự nam xứ Magadha sẽ buồn lòng; ",
  "dn18:6.9": "mà nếu các cận sự nam xứ Magadha buồn lòng như vậy, thì làm sao Thế Tôn lại không tuyên thuyết về họ?”",
  "dn18:6.10": "Nói xong lời thưa hỏi ấy trước mặt Thế Tôn về các cận sự nam xứ Magadha, tôn giả Ānanda từ chỗ ngồi đứng dậy, đảnh lễ Thế Tôn, đi nhiễu bên phải rồi ra về. ",
  "dn18:7.1": "Rồi sau khi tôn giả Ānanda đi không bao lâu, vào buổi sáng, Thế Tôn đắp y, cầm y bát đi vào Nātika khất thực. ",
  "dn18:7.2": "Sau khi đi khất thực ở Nātika, dùng bữa xong, từ chỗ khất thực trở về, Thế Tôn rửa chân, vào ngôi nhà gạch, rồi vì các cận sự nam xứ Magadha mà chú tâm, tác ý, đem hết tâm tư quán xét, và ngồi xuống chỗ đã soạn sẵn: ",
  "dn18:7.3": "“Ta sẽ biết được đường đi, cảnh giới đời sau của họ, họ đã đi đến đâu, đời sau của họ ra sao.”",
  "dn18:7.4": "Và Thế Tôn đã thấy các cận sự nam xứ Magadha: ",
  "dn18:7.5": "“Họ đã đi đến đâu, đời sau của họ ra sao.”",
  "dn18:7.6": "Rồi vào buổi chiều, sau khi từ chỗ tĩnh cư đứng dậy, Thế Tôn ra khỏi ngôi nhà gạch, ngồi xuống chỗ đã soạn sẵn trong bóng mát phía sau tinh xá. ",
  "dn18:8.1": "Rồi tôn giả Ānanda đi đến chỗ Thế Tôn; đến nơi, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Khi đã ngồi xuống một bên, tôn giả Ānanda bạch Thế Tôn: ",
  "dn18:8.2": "“Bạch Thế Tôn, hôm nay Thế Tôn trông thật an tịnh, sắc mặt của Thế Tôn sáng rỡ, các căn thanh tịnh. ",
  "dn18:8.3": "Chắc hẳn hôm nay, bạch Thế Tôn, Thế Tôn đã an trú trong một sự an trú tịch tĩnh?”",
  "dn18:9.1": "“Này Ānanda, chính sau khi ông thưa hỏi trước mặt Ta về các cận sự nam xứ Magadha rồi từ chỗ ngồi đứng dậy ra đi, thì Ta sau khi đi khất thực ở Nātika, dùng bữa xong, từ chỗ khất thực trở về, rửa chân, vào ngôi nhà gạch, rồi vì các cận sự nam xứ Magadha mà chú tâm, tác ý, đem hết tâm tư quán xét, và ngồi xuống chỗ đã soạn sẵn: ",
  "dn18:9.2": "‘Ta sẽ biết được đường đi, cảnh giới đời sau của họ, họ đã đi đến đâu, đời sau của họ ra sao.’ ",
  "dn18:9.3": "Này Ānanda, Ta đã thấy các cận sự nam xứ Magadha: ‘Họ đã đi đến đâu, đời sau của họ ra sao.’ ",
  "dn18:9.4.0": "3. Dạ-xoa Janavasabha ",
  "dn18:9.5": "Rồi này Ānanda, một vị dạ-xoa vô hình cất tiếng lên rằng: ",
  "dn18:9.6": "‘Bạch Thế Tôn, con là Janavasabha; ",
  "dn18:9.7": "bạch Thiện Thệ, con là Janavasabha.’ ",
  "dn18:9.8": "Này Ānanda, trước đây ông có từng nghe một danh xưng như vậy chăng, tức là Janavasabha?”",
  "dn18:9.9": "“Bạch Thế Tôn, trước đây con chưa từng nghe một danh xưng như vậy, tức là Janavasabha; nhưng bạch Thế Tôn, khi nghe danh xưng ‘Janavasabha’, lông con dựng đứng. ",
  "dn18:9.10": "Bạch Thế Tôn, khi ấy con nghĩ rằng: ",
  "dn18:9.11": "‘Chắc hẳn đó không phải là một vị dạ-xoa tầm thường, vì có một danh xưng được đặt thật khéo như vậy, tức là Janavasabha.’”",
  "dn18:10.1": "“Ngay sau khi âm thanh ấy xuất hiện, này Ānanda, một vị dạ-xoa có dung sắc rực rỡ hiện ra trước mặt Ta. ",
  "dn18:10.2": "Vị ấy lại cất tiếng lần thứ hai: ",
  "dn18:10.3": "‘Bạch Thế Tôn, con là Bimbisāra; ",
  "dn18:10.4": "bạch Thiện Thệ, con là Bimbisāra. ",
  "dn18:10.5": "Bạch Thế Tôn, đây là lần thứ bảy con được sinh vào cộng trú với Đại vương Vessavaṇa; từ đó mệnh chung, con có thể trở thành vua loài người. ",
  "dn18:10.6": "Bảy lần từ đây, bảy lần từ kia, ",
  "dn18:10.7": "mười bốn đời luân hồi; ",
  "dn18:10.8": "con nhớ rõ các chỗ ở, ",
  "dn18:10.9": "nơi trước kia con đã sống. ",
  "dn18:10.10": "Bạch Thế Tôn, từ lâu con biết mình không rơi vào đọa xứ, và nay niềm hy vọng về quả Nhất lai của con đã được xác lập.’”",
  "dn18:10.11": "“Thật vi diệu thay đối với tôn giả dạ-xoa Janavasabha, thật hy hữu thay đối với tôn giả dạ-xoa Janavasabha. ",
  "dn18:10.12": "‘Bạch Thế Tôn, từ lâu con biết mình không bị đọa xứ, không rơi vào ác thú’, và lại nói: ‘niềm hy vọng của con được an trú nơi quả Nhất lai’; vậy do nhân gì mà Tôn giả dạ-xoa Janavasabha lại biết được một sự chứng đắc thù thắng lớn lao như vậy?”",
  "dn18:11.1": "“Bạch Thế Tôn, không ở nơi nào khác ngoài giáo pháp của Ngài, bạch Thiện Thệ, không ở nơi nào khác ngoài giáo pháp của Ngài; ",
  "dn18:11.2": "từ khi con có lòng tịnh tín tuyệt đối đối với Thế Tôn, từ khi ấy, bạch Thế Tôn, từ lâu con biết mình không bị đọa xứ, không rơi vào ác thú, và niềm hy vọng của con được an trú nơi quả Nhất lai. ",
  "dn18:11.3": "Ở đây, bạch Thế Tôn, con được Đại vương Vessavaṇa sai đi đến chỗ Đại vương Virūḷhaka vì một công việc nào đó. Trên đường đi, con thấy Thế Tôn vào trú xá Giñjakāvasatha, ngồi chú tâm, tác ý, hướng trọn tâm đến các thị giả người Magadha: ",
  "dn18:11.4": "‘Ta sẽ biết được cảnh giới tái sinh của họ ở đời sau, họ sẽ đi đến cảnh giới nào sau khi thân hoại mạng chung.’ ",
  "dn18:11.5": "Điều ấy thật không có gì lạ, bạch Thế Tôn, vì con đã được nghe tận mặt, nhận tận mặt trong hội chúng ấy khi Đại vương Vessavaṇa nói rằng: ",
  "dn18:11.6": "‘Họ sẽ đi đến cảnh giới nào sau khi thân hoại mạng chung.’ ",
  "dn18:11.7": "Khi ấy, bạch Thế Tôn, con nghĩ rằng: ",
  "dn18:11.8": "‘Ta sẽ được gặp Thế Tôn và sẽ trình việc này lên Thế Tôn.’ ",
  "dn18:11.9": "Bạch Thế Tôn, đây là hai nhân duyên khiến con đến yết kiến Thế Tôn. ",
  "dn18:12.0": "4. Hội chúng chư thiên",
  "dn18:12.1": "Bạch Thế Tôn, vào những ngày trước đây, vào ngày bố-tát rằm, đêm trăng tròn viên mãn, là lúc bắt đầu mùa an cư mưa, toàn thể chư thiên cõi Ba mươi ba tụ hội và ngồi lại trong hội trường Sudhammā. ",
  "dn18:12.2": "Một đại hội chư thiên lớn ngồi khắp chung quanh, và bốn vị Đại vương ngồi ở bốn phương. ",
  "dn18:12.3": "Ở phương đông, Đại vương Dhataraṭṭha ngồi quay mặt về phương tây, dẫn đầu chư thiên; ",
  "dn18:12.4": "ở phương nam, Đại vương Virūḷhaka ngồi quay mặt về phương bắc, dẫn đầu chư thiên; ",
  "dn18:12.5": "ở phương tây, Đại vương Virūpakkha ngồi quay mặt về phương đông, dẫn đầu chư thiên; ",
  "dn18:12.6": "ở phương bắc, Đại vương Vessavaṇa ngồi quay mặt về phương nam, dẫn đầu chư thiên. ",
  "dn18:12.7": "Bạch Thế Tôn, khi toàn thể chư thiên cõi Ba mươi ba tụ hội và ngồi lại trong hội trường Sudhammā, khi đại hội chư thiên lớn ngồi khắp chung quanh, và bốn vị Đại vương ngồi ở bốn phương, thì đó là chỗ ngồi của họ; ",
  "dn18:12.8": "còn chỗ ngồi của chúng con ở phía sau. ",
  "dn18:12.9": "Những vị chư thiên nào, bạch Thế Tôn, đã sống phạm hạnh dưới Thế Tôn và nay mới sinh lên cõi Ba mươi ba, thì họ vượt hơn các chư thiên khác cả về dung sắc lẫn uy danh. ",
  "dn18:12.10": "Do vậy, bạch Thế Tôn, chư thiên cõi Ba mươi ba hoan hỷ, vui mừng, hân hoan phấn khởi: ",
  "dn18:12.11": "‘Thật vậy, các thiên chúng được đầy thêm, còn chúng asura thì suy giảm.’ ",
  "dn18:13.1": "Bấy giờ, bạch Thế Tôn, Thiên chủ Sakka, vua của chư thiên, biết được niềm hoan hỷ của chư thiên cõi Ba mươi ba, liền tùy hỷ bằng những bài kệ này: ",
  "dn18:13.2": "“Thật vậy, chư thiên hoan hỷ, ",
  "dn18:13.3": "Ba mươi ba cùng với Inda; ",
  "dn18:13.4": "đảnh lễ Như Lai, ",
  "dn18:13.5": "và Chánh pháp khéo được thuyết. ",
  "dn18:13.6": "Thấy các chư thiên mới, ",
  "dn18:13.7": "có dung sắc, có uy danh; ",
  "dn18:13.8": "đã sống phạm hạnh ",
  "dn18:13.9": "dưới bậc Thiện Thệ mà đến đây. ",
  "dn18:13.10": "Họ vượt hơn các vị khác, ",
  "dn18:13.11": "về dung sắc, uy danh và thọ mạng; ",
  "dn18:13.12": "là đệ tử của bậc đại tuệ, ",
  "dn18:13.13": "đã đạt đến thắng diệu ở đây. ",
  "dn18:13.14": "Thấy điều này, họ hoan hỷ, ",
  "dn18:13.15": "Ba mươi ba cùng với Inda; ",
  "dn18:13.16": "đảnh lễ Như Lai, ",
  "dn18:13.17": "và Chánh pháp khéo được thuyết.” ",
  "dn18:13.18": "Do vậy, bạch Thế Tôn, chư thiên cõi Ba mươi ba lại càng thêm hoan hỷ, vui mừng, hân hoan phấn khởi: ",
  "dn18:13.19": "‘Thật vậy, các thiên chúng được đầy thêm, còn chúng asura thì suy giảm.’ ",
  "dn18:14.1": "Bấy giờ, bạch Thế Tôn, sau khi suy nghĩ và bàn luận về mục đích vì đó mà chư thiên cõi Ba mươi ba tụ hội và ngồi lại trong hội trường Sudhammā, bốn vị Đại vương ấy cũng phát biểu về vấn đề ấy. Sau khi nhận lời chỉ dạy, bốn vị Đại vương ấy cũng ở lại trong vấn đề ấy, ",
  "dn18:14.2": "đứng yên tại chỗ ngồi riêng của mình, không rời đi. ",
  "dn18:14.3": "Các vị vua ấy, sau khi nghe lời nói, ",
  "dn18:14.4": "và tiếp nhận lời giáo huấn, ",
  "dn18:14.5": "với tâm hết sức trong sáng, ",
  "dn18:14.6": "đã đứng lại tại chỗ ngồi của mình. ",
  "dn18:15.1": "Bấy giờ, bạch Thế Tôn, ở phương bắc xuất hiện một ánh sáng lớn, một hào quang hiện ra, vượt hẳn oai lực của chư thiên. ",
  "dn18:15.2": "Khi ấy, bạch Thế Tôn, Thiên chủ Sakka, vua của chư thiên, nói với chư thiên cõi Ba mươi ba: ",
  "dn18:15.3": "‘Này chư hiền, khi các điềm tướng như vậy xuất hiện, ánh sáng lớn khởi lên, hào quang hiện ra, thì Phạm thiên sẽ xuất hiện. Vì đây là điềm báo trước cho sự hiện ra của Phạm thiên, tức là ánh sáng khởi lên và hào quang hiện ra.’ ",
  "dn18:15.4": "Khi các điềm tướng xuất hiện, ",
  "dn18:15.5": "Phạm thiên sẽ hiện ra; ",
  "dn18:15.6": "đó là điềm báo của Phạm thiên, ",
  "dn18:15.7": "một hào quang rộng lớn, vĩ đại. ",
  "dn18:16.0": "5. Luận về Sanaṅkumāra",
  "dn18:16.1": "Bấy giờ, bạch Thế Tôn, chư thiên cõi Ba mươi ba ngồi xuống tại chỗ ngồi riêng của mình: ",
  "dn18:16.2": "‘Chúng ta sẽ biết ánh sáng này là gì, kết quả của nó sẽ ra sao; chỉ sau khi tự mình chứng kiến, chúng ta mới ra đi.’ ",
  "dn18:16.3": "Cả bốn vị Đại vương cũng ngồi xuống tại chỗ ngồi riêng của mình: ",
  "dn18:16.4": "‘Chúng ta sẽ biết ánh sáng này là gì, kết quả của nó sẽ ra sao; chỉ sau khi tự mình chứng kiến, chúng ta mới ra đi.’ ",
  "dn18:16.5": "Nghe vậy, chư thiên cõi Ba mươi ba nhất tâm an trú: ",
  "dn18:16.6": "‘Chúng ta sẽ biết ánh sáng này là gì, kết quả của nó sẽ ra sao; chỉ sau khi tự mình chứng kiến, chúng ta mới ra đi.’ ",
  "dn18:17.1": "Bạch Thế Tôn, khi Phạm thiên Sanaṅkumāra hiện ra giữa chư thiên cõi Ba mươi ba, ngài hiện ra sau khi hóa hiện một thân hình thô rõ. ",
  "dn18:17.2": "Nhưng, bạch Thế Tôn, sắc tướng tự nhiên của Phạm thiên thì chư thiên cõi Ba mươi ba không thể thấy được bằng mắt. ",
  "dn18:17.3": "Bạch Thế Tôn, khi Phạm thiên Sanaṅkumāra hiện ra giữa chư thiên cõi Ba mươi ba, ngài vượt hơn các chư thiên khác cả về dung sắc lẫn uy danh. ",
  "dn18:17.4": "Ví như, bạch Thế Tôn, một hình thể bằng vàng vượt hơn hình thể loài người; ",
  "dn18:17.5": "cũng vậy, bạch Thế Tôn, khi Phạm thiên Sanaṅkumāra hiện ra giữa chư thiên cõi Ba mươi ba, ngài vượt hơn các chư thiên khác cả về dung sắc lẫn uy danh. ",
  "dn18:17.6": "Bạch Thế Tôn, khi Phạm thiên Sanaṅkumāra hiện ra giữa chư thiên cõi Ba mươi ba, trong hội chúng ấy không có vị chư thiên nào đảnh lễ, đứng dậy chào, hay mời ngồi. ",
  "dn18:17.7": "Tất cả đều im lặng, chắp tay, ngồi xếp bằng: ",
  "dn18:17.8": "‘Hôm nay Phạm thiên Sanaṅkumāra muốn ngồi lên chỗ ngồi của vị thiên nào, thì ngài sẽ ngồi lên chỗ ngồi của vị thiên ấy.’ ",
  "dn18:17.9": "Bạch Thế Tôn, vị chư thiên nào được Phạm thiên Sanaṅkumāra ngồi lên chỗ ngồi của mình, vị ấy đạt được cảm thọ thù thắng; vị ấy đạt được niềm hoan hỷ thù thắng. ",
  "dn18:18.1": "Ví như, bạch Thế Tôn, một vị vua Sát-đế-lỵ đã được quán đảnh, vừa mới đăng quang, thì đạt được cảm thọ thù thắng, đạt được niềm hoan hỷ thù thắng; ",
  "dn18:18.2": "cũng vậy, bạch Thế Tôn, vị chư thiên nào được Phạm thiên Sanaṅkumāra ngồi lên chỗ ngồi của mình, vị ấy đạt được cảm thọ thù thắng; vị ấy đạt được niềm hoan hỷ thù thắng. ",
  "dn18:18.3": "Rồi, bạch Thế Tôn, Phạm thiên Sanaṅkumāra hóa hiện một thân hình thô rõ, mang dáng vẻ một thiếu niên năm búi tóc, hiện ra giữa chư thiên cõi Ba mươi ba. ",
  "dn18:18.4": "Ngài bay lên hư không và ngồi xếp bằng giữa khoảng trời. ",
  "dn18:18.5": "Ví như, bạch Thế Tôn, một người lực lưỡng có thể ngồi xếp bằng trên một chiếc giường được trải sẵn hay trên một mặt đất bằng phẳng; ",
  "dn18:18.6": "cũng vậy, bạch Thế Tôn, Phạm thiên Sanaṅkumāra bay lên hư không, ngồi xếp bằng giữa khoảng trời, rồi biết được niềm hoan hỷ của chư thiên cõi Ba mươi ba, liền tùy hỷ bằng những bài kệ này: ",
  "dn18:18.7": "“Thật vậy, chư thiên hoan hỷ, ",
  "dn18:18.8": "Ba mươi ba cùng với Inda; ",
  "dn18:18.9": "đảnh lễ Như Lai, ",
  "dn18:18.10": "và Chánh pháp khéo được thuyết. ",
  "dn18:18.11": "Thấy các chư thiên mới, ",
  "dn18:18.12": "có dung sắc, có uy danh; ",
  "dn18:18.13": "đã sống phạm hạnh ",
  "dn18:18.14": "dưới bậc Thiện Thệ mà đến đây. ",
  "dn18:18.15": "Họ vượt hơn các vị khác, ",
  "dn18:18.16": "về dung sắc, uy danh và thọ mạng; ",
  "dn18:18.17": "là đệ tử của bậc đại tuệ, ",
  "dn18:18.18": "đã đạt đến thắng diệu ở đây. ",
  "dn18:18.19": "Thấy điều này, họ hoan hỷ, ",
  "dn18:18.20": "Ba mươi ba cùng với Inda; ",
  "dn18:18.21": "đảnh lễ Như Lai, ",
  "dn18:18.22": "và Chánh pháp khéo được thuyết.” ",
  "dn18:19.1": "Bạch Thế Tôn, Phạm thiên Sanaṅkumāra đã nói ý nghĩa ấy; ",
  "dn18:19.2": "và khi Phạm thiên Sanaṅkumāra nói ý nghĩa ấy, giọng nói của ngài có đủ tám đặc tính: rõ ràng, dễ nhận biết, êm dịu, dễ nghe, mạch lạc, không lẫn lộn, trầm hùng và vang dội. ",
  "dn18:19.3": "Nhưng, bạch Thế Tôn, Phạm thiên Sanaṅkumāra chỉ làm cho hội chúng ấy hiểu được bằng giọng nói của mình; âm thanh của ngài không vang ra ngoài hội chúng. ",
  "dn18:19.4": "Bạch Thế Tôn, ai có giọng nói đầy đủ tám đặc tính như vậy thì được gọi là ‘phạm âm’. ",
  "dn18:20.1": "Bấy giờ, bạch Thế Tôn, Phạm thiên Sanaṅkumāra hóa hiện ba mươi ba thân, ngồi xếp bằng trên từng chỗ ngồi riêng của chư thiên cõi Ba mươi ba, rồi nói với chư thiên cõi Ba mươi ba: ",
  "dn18:20.2": "‘Chư vị chư thiên cõi Ba mươi ba nghĩ thế nào, Thế Tôn ấy đã thực hành vì lợi ích cho số đông, vì hạnh phúc cho số đông, vì lòng thương tưởng thế gian, vì lợi ích, an lạc cho chư thiên và loài người đến mức nào. ",
  "dn18:20.3": "Này chư vị, bất cứ ai quy y Phật, quy y Pháp, quy y Tăng, và thành tựu viên mãn các giới, sau khi thân hoại mạng chung, có người sinh vào cộng trú với chư thiên cõi Hóa Tự Tại Tha Hóa, có người sinh vào cộng trú với chư thiên cõi Hóa Lạc, có người sinh vào cộng trú với chư thiên cõi Đâu-suất, có người sinh vào cộng trú với chư thiên cõi Dạ-ma, có người sinh vào cộng trú với chư thiên cõi Ba mươi ba, có người sinh vào cộng trú với chư thiên cõi Tứ Đại Vương. ",
  "dn18:20.4": "Những ai làm đầy đủ thiên chúng thấp nhất, thì làm đầy đủ chúng Càn-thát-bà.’ ",
  "dn18:21.1": "Bạch Thế Tôn, Phạm thiên Sanaṅkumāra đã nói ý nghĩa này;",
  "dn18:21.2": "bạch Thế Tôn, khi Phạm thiên Sanaṅkumāra nói ý nghĩa này, chư thiên chỉ nghĩ rằng:",
  "dn18:21.3": "“vị đang ngồi trên tòa của ta này chỉ một mình đang nói.”",
  "dn18:21.4": "Khi một vị đang nói,",
  "dn18:21.5": "tất cả đều nói theo do được hóa hiện;",
  "dn18:21.6": "khi một vị im lặng ngồi,",
  "dn18:21.7": "tất cả vị ấy đều trở nên im lặng.",
  "dn18:21.8": "Khi ấy chư thiên nghĩ rằng,",
  "dn18:21.9": "chư thiên Tam thập tam cùng với Đế Thích:",
  "dn18:21.10": "“Vị đang ở trên tòa của ta này,",
  "dn18:21.11": "chỉ một mình đang nói.”",
  "dn18:22.1": "Rồi bạch Thế Tôn, Phạm thiên Sanaṅkumāra thu nhiếp tự thân thành một, sau khi thu nhiếp tự thân thành một, ngồi trên tòa của Sakka, vua của chư thiên, rồi nói với chư thiên Tam thập tam:",
  "dn18:22.2.0": "6. Tu tập thần túc",
  "dn18:22.3": "“Này chư tôn giả chư thiên Tam thập tam, chư vị nghĩ thế nào, bốn thần túc này đã được Thế Tôn, bậc biết, bậc thấy, bậc A-la-hán, bậc Chánh Đẳng Giác khéo tuyên thuyết để thành tựu thần lực, để làm cho thần lực sung mãn, để biến hóa thần thông. ",
  "dn18:22.4": "Bốn là gì?",
  "dn18:22.5": "Ở đây, này chư vị, vị tỳ-kheo tu tập thần túc có đầy đủ định do dục và các hành tinh tấn. ",
  "dn18:22.6": "Tu tập thần túc có đầy đủ định do tinh tấn và các hành tinh tấn. ",
  "dn18:22.7": "Tu tập thần túc có đầy đủ định do tâm và các hành tinh tấn. ",
  "dn18:22.8": "Tu tập thần túc có đầy đủ định do quán sát và các hành tinh tấn. ",
  "dn18:22.9": "Này chư vị, bốn thần túc này đã được Thế Tôn, bậc biết, bậc thấy, bậc A-la-hán, bậc Chánh Đẳng Giác khéo tuyên thuyết để thành tựu thần lực, để làm cho thần lực sung mãn, để biến hóa thần thông. ",
  "dn18:22.10": "Này chư vị, bất cứ sa-môn hay bà-la-môn nào trong thời quá khứ đã chứng nghiệm nhiều loại thần thông, tất cả đều do tu tập và làm cho sung mãn chính bốn thần túc này. ",
  "dn18:22.11": "Này chư vị, bất cứ sa-môn hay bà-la-môn nào trong thời vị lai sẽ chứng nghiệm nhiều loại thần thông, tất cả cũng đều do tu tập và làm cho sung mãn chính bốn thần túc này. ",
  "dn18:22.12": "Này chư vị, bất cứ sa-môn hay bà-la-môn nào trong hiện tại đang chứng nghiệm nhiều loại thần thông, tất cả cũng đều do tu tập và làm cho sung mãn chính bốn thần túc này. ",
  "dn18:22.13": "Này chư thiên Tam thập tam, chư vị có thấy nơi ta cũng có thần lực như vậy chăng?”",
  "dn18:22.14": "“Thưa có, Đại Phạm.”",
  "dn18:22.15": "“Ta cũng vậy, chính do tu tập và làm cho sung mãn bốn thần túc này mà có đại thần lực, đại oai lực như vậy.”",
  "dn18:23.1": "Bạch Thế Tôn, Phạm thiên Sanaṅkumāra đã nói ý nghĩa này.",
  "dn18:23.2": "Bạch Thế Tôn, sau khi nói ý nghĩa này, Phạm thiên Sanaṅkumāra nói với chư thiên Tam thập tam:",
  "dn18:23.3.0": "7. Chứng đắc ba cơ hội",
  "dn18:23.4": "“Này chư tôn giả chư thiên Tam thập tam, chư vị nghĩ thế nào, ba sự chứng đắc cơ hội này đã được Thế Tôn, bậc biết, bậc thấy, bậc A-la-hán, bậc Chánh Đẳng Giác giác ngộ để đạt đến an lạc. ",
  "dn18:23.5": "Ba là gì?",
  "dn18:23.6": "Ở đây, này chư vị, có người sống nhiễm trước các dục, nhiễm trước các pháp bất thiện. ",
  "dn18:23.7": "Về sau, người ấy được nghe diệu pháp, tác ý như lý, thực hành đúng pháp. ",
  "dn18:23.8": "Do được nghe diệu pháp, tác ý như lý, thực hành đúng pháp, người ấy sống không nhiễm trước các dục, không nhiễm trước các pháp bất thiện. ",
  "dn18:23.9": "Khi người ấy không nhiễm trước các dục, không nhiễm trước các pháp bất thiện, lạc khởi lên; từ lạc, hỷ càng tăng thêm. ",
  "dn18:23.10": "Ví như, này chư vị, từ hoan hỷ mà vui mừng sinh khởi;",
  "dn18:23.11": "cũng vậy, này chư vị, khi không nhiễm trước các dục, không nhiễm trước các pháp bất thiện, lạc khởi lên; từ lạc, hỷ càng tăng thêm. ",
  "dn18:23.12": "Này chư vị, đây là sự chứng đắc cơ hội thứ nhất đã được Thế Tôn, bậc biết, bậc thấy, bậc A-la-hán, bậc Chánh Đẳng Giác giác ngộ để đạt đến an lạc. ",
  "dn18:24.1": "Lại nữa, này chư vị, ở đây có người các thân hành thô còn chưa lắng dịu, các khẩu hành thô còn chưa lắng dịu, các tâm hành thô còn chưa lắng dịu. ",
  "dn18:24.2": "Về sau, người ấy được nghe diệu pháp, tác ý như lý, thực hành đúng pháp. ",
  "dn18:24.3": "Do được nghe diệu pháp, tác ý như lý, thực hành đúng pháp, các thân hành thô của người ấy được lắng dịu, các khẩu hành thô được lắng dịu, các tâm hành thô được lắng dịu. ",
  "dn18:24.4": "Do các thân hành thô được lắng dịu, các khẩu hành thô được lắng dịu, các tâm hành thô được lắng dịu, lạc khởi lên; từ lạc, hỷ càng tăng thêm. ",
  "dn18:24.5": "Ví như, này chư vị, từ hoan hỷ mà vui mừng sinh khởi;",
  "dn18:24.6": "cũng vậy, này chư vị, do các thân hành thô được lắng dịu, các khẩu hành thô được lắng dịu, các tâm hành thô được lắng dịu, lạc khởi lên; từ lạc, hỷ càng tăng thêm. ",
  "dn18:24.7": "Này chư vị, đây là sự chứng đắc cơ hội thứ hai đã được Thế Tôn, bậc biết, bậc thấy, bậc A-la-hán, bậc Chánh Đẳng Giác giác ngộ để đạt đến an lạc. ",
  "dn18:25.1": "Lại nữa, này chư vị, ở đây có người không như thật biết: “Đây là thiện”, không như thật biết: “Đây là bất thiện”. ",
  "dn18:25.2": "Không như thật biết: “Đây là có lỗi, đây là không lỗi; đây nên thực hành, đây không nên thực hành; đây là thấp kém, đây là cao thượng; đây là phần tương ưng với đen và trắng.”",
  "dn18:25.3": "Về sau, người ấy được nghe diệu pháp, tác ý như lý, thực hành đúng pháp. ",
  "dn18:25.4": "Do được nghe diệu pháp, tác ý như lý, thực hành đúng pháp, người ấy như thật biết: “Đây là thiện”, như thật biết: “Đây là bất thiện”. ",
  "dn18:25.5": "Như thật biết: “Đây là có lỗi, đây là không lỗi; đây nên thực hành, đây không nên thực hành; đây là thấp kém, đây là cao thượng; đây là phần tương ưng với đen và trắng.”",
  "dn18:25.6": "Với người biết như vậy, thấy như vậy, vô minh được đoạn trừ, minh sinh khởi. ",
  "dn18:25.7": "Do vô minh phai diệt, do minh sinh khởi, lạc khởi lên; từ lạc, hỷ càng tăng thêm. ",
  "dn18:25.8": "Ví như, này chư vị, từ hoan hỷ mà vui mừng sinh khởi;",
  "dn18:25.9": "cũng vậy, này chư vị, do vô minh phai diệt, do minh sinh khởi, lạc khởi lên; từ lạc, hỷ càng tăng thêm. ",
  "dn18:25.10": "Này chư vị, đây là sự chứng đắc cơ hội thứ ba đã được Thế Tôn, bậc biết, bậc thấy, bậc A-la-hán, bậc Chánh Đẳng Giác giác ngộ để đạt đến an lạc. ",
  "dn18:25.11": "Này chư vị, ba sự chứng đắc cơ hội này đã được Thế Tôn, bậc biết, bậc thấy, bậc A-la-hán, bậc Chánh Đẳng Giác giác ngộ để đạt đến an lạc.”",
  "dn18:26.1": "Bạch Thế Tôn, Phạm thiên Sanaṅkumāra đã nói ý nghĩa này,",
  "dn18:26.2": "bạch Thế Tôn, sau khi nói ý nghĩa này, Phạm thiên Sanaṅkumāra nói với chư thiên Tam thập tam:",
  "dn18:26.3.0": "8. Bốn niệm xứ",
  "dn18:26.4": "“Này chư tôn giả chư thiên Tam thập tam, chư vị nghĩ thế nào, bốn niệm xứ này đã được Thế Tôn, bậc biết, bậc thấy, bậc A-la-hán, bậc Chánh Đẳng Giác khéo tuyên thuyết để đạt đến thiện pháp. ",
  "dn18:26.5": "Bốn là gì?",
  "dn18:26.6": "Ở đây, này chư vị, vị tỳ-kheo sống quán thân trên thân ở nội thân, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời. ",
  "dn18:26.7": "Trong khi sống quán thân trên thân ở nội thân, vị ấy tại đó được định tĩnh đúng đắn, được tịnh tín đúng đắn. ",
  "dn18:26.8": "Vị ấy, do tại đó được định tĩnh đúng đắn, được tịnh tín đúng đắn, phát sinh tri kiến đối với thân của người khác ở bên ngoài. ",
  "dn18:26.9": "Sống quán thọ trên các cảm thọ ở nội thân …",
  "dn18:26.10": "phát sinh tri kiến đối với các cảm thọ của người khác ở bên ngoài. ",
  "dn18:26.11": "Sống quán tâm trên tâm ở nội tâm …",
  "dn18:26.12": "phát sinh tri kiến đối với tâm của người khác ở bên ngoài. ",
  "dn18:26.13": "Sống quán pháp trên các pháp ở nội pháp, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời. ",
  "dn18:26.14": "Trong khi sống quán pháp trên các pháp ở nội pháp, vị ấy tại đó được định tĩnh đúng đắn, được tịnh tín đúng đắn. ",
  "dn18:26.15": "Vị ấy, do tại đó được định tĩnh đúng đắn, được tịnh tín đúng đắn, phát sinh tri kiến đối với các pháp của người khác ở bên ngoài. ",
  "dn18:26.16": "Này chư vị, bốn niệm xứ này đã được Thế Tôn, bậc biết, bậc thấy, bậc A-la-hán, bậc Chánh Đẳng Giác khéo tuyên thuyết để đạt đến thiện pháp.”",
  "dn18:27.1": "Bạch Thế Tôn, Phạm thiên Sanaṅkumāra đã nói ý nghĩa này.",
  "dn18:27.2": "Bạch Thế Tôn, sau khi nói ý nghĩa này, Phạm thiên Sanaṅkumāra nói với chư thiên Tam thập tam:",
  "dn18:27.3.0": "9. Bảy tư lương của định",
  "dn18:27.4": "“Này chư tôn giả chư thiên Tam thập tam, chư vị nghĩ thế nào, bảy tư lương của định này đã được Thế Tôn, bậc biết, bậc thấy, bậc A-la-hán, bậc Chánh Đẳng Giác khéo tuyên thuyết để tu tập chánh định, để viên mãn chánh định. ",
  "dn18:27.5": "Bảy là gì?",
  "dn18:27.6": "Chánh kiến, chánh tư duy, chánh ngữ, chánh nghiệp, chánh mạng, chánh tinh tấn, chánh niệm. ",
  "dn18:27.7": "Này chư vị, sự nhất tâm của tâm được hỗ trợ bởi bảy chi phần này được gọi là thánh chánh định, có cận y, cũng gọi là có tư lương. ",
  "dn18:27.8": "Này chư vị, từ chánh kiến sinh ra chánh tư duy, từ chánh tư duy sinh ra chánh ngữ, từ chánh ngữ sinh ra chánh nghiệp. Từ chánh nghiệp sinh ra chánh mạng, từ chánh mạng sinh ra chánh tinh tấn, từ chánh tinh tấn sinh ra chánh niệm, từ chánh niệm sinh ra chánh định, từ chánh định sinh ra chánh trí, từ chánh trí sinh ra chánh giải thoát. ",
  "dn18:27.9": "Này chư vị, nếu ai nói đúng thì nên nói rằng:",
  "dn18:27.10": "‘Pháp được Thế Tôn khéo thuyết, thiết thực hiện tại, không có thời gian, đến để mà thấy, có khả năng hướng thượng, người trí tự mình giác hiểu; các cửa bất tử đã mở ra’, thì đó là nói đúng. ",
  "dn18:27.11": "Vì này chư vị, Pháp được Thế Tôn khéo thuyết, thiết thực hiện tại, không có thời gian, đến để mà thấy, có khả năng hướng thượng, người trí tự mình giác hiểu; các cửa bất tử đã mở ra. ",
  "dn18:27.12": "Này chư vị, bất cứ ai có lòng tịnh tín bất động đối với Phật, có lòng tịnh tín bất động đối với Pháp, có lòng tịnh tín bất động đối với Tăng, đầy đủ các giới được bậc Thánh ái kính, và những người hóa sinh này đã được pháp luật điều phục, hơn hai mươi bốn vạn người hầu cận xứ Magadha đã qua đời, sau khi đoạn tận ba kiết sử, là bậc Dự lưu, không còn đọa xứ, chắc chắn hướng đến giác ngộ. ",
  "dn18:27.13": "Ở đây cũng có những vị Nhất lai. ",
  "dn18:27.14": "Còn quần chúng khác ở đây,",
  "dn18:27.15": "ta nghĩ là thuộc phần phước;",
  "dn18:27.16": "ta không thể tính đếm được,",
  "dn18:27.17": "vì hổ thẹn đối với lời nói dối.”",
  "dn18:28.1": "Bạch Thế Tôn, Phạm thiên Sanaṅkumāra đã nói ý nghĩa này; khi Phạm thiên Sanaṅkumāra nói ý nghĩa này, nơi tâm của Đại vương Vessavaṇa khởi lên suy nghĩ như sau:",
  "dn18:28.2": "“Thật vi diệu thay, này chư vị, thật hy hữu thay, này chư vị, sẽ có một bậc Đạo sư cao cả như vậy, sẽ có sự thuyết pháp cao cả như vậy, sẽ có những chứng đắc đặc biệt cao cả như vậy được hiển lộ.”",
  "dn18:28.3": "Rồi bạch Thế Tôn, Phạm thiên Sanaṅkumāra biết được tâm tư suy nghĩ của Đại vương Vessavaṇa bằng tâm, liền nói với Đại vương Vessavaṇa như sau:",
  "dn18:28.4": "“Đại vương Vessavaṇa nghĩ thế nào? Trong thời quá khứ cũng đã có một bậc Đạo sư cao cả như vậy, có sự thuyết pháp cao cả như vậy, có những chứng đắc đặc biệt cao cả như vậy được hiển lộ. ",
  "dn18:28.5": "Trong thời vị lai cũng sẽ có một bậc Đạo sư cao cả như vậy, có sự thuyết pháp cao cả như vậy, có những chứng đắc đặc biệt cao cả như vậy được hiển lộ.”",
  "dn18:29.1": "Bạch Thế Tôn, ý nghĩa này đã được Phạm thiên Sanaṅkumāra nói với chư thiên Tam thập tam; ý nghĩa này Đại vương Vessavaṇa đã nghe trực tiếp, tiếp nhận trực tiếp khi Phạm thiên Sanaṅkumāra nói với chư thiên Tam thập tam, rồi tự mình thuật lại trong hội chúng.”",
  "dn18:29.2": "Ý nghĩa này, Dạ-xoa Janavasabha đã nghe trực tiếp, tiếp nhận trực tiếp khi Đại vương Vessavaṇa tự mình nói trong hội chúng, rồi trình lên Thế Tôn. ",
  "dn18:29.3": "Ý nghĩa này, Thế Tôn sau khi nghe trực tiếp, tiếp nhận trực tiếp từ Dạ-xoa Janavasabha, và tự mình chứng biết, đã nói lại cho Tôn giả Ānanda; ý nghĩa này, Tôn giả Ānanda sau khi nghe trực tiếp, tiếp nhận trực tiếp từ Thế Tôn, đã nói lại cho các tỳ-kheo, tỳ-kheo-ni, nam cư sĩ và nữ cư sĩ. ",
  "dn18:29.4": "Do vậy, phạm hạnh này được hưng thịnh, phát triển, rộng lớn, phổ biến, lan rộng, được khéo tuyên dương cho chư thiên và loài người. ",
  "dn18:29.5": "Kinh Janavasabha thứ năm chấm dứt."
}
window.BILARA["dn18"]["vi"]["dn18:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
