window.BILARA = window.BILARA || {};
window.BILARA["dn22"] = window.BILARA["dn22"] || {};
window.BILARA["dn22"]["vi"] = {
  "dn22:0.1": "Trường Bộ Kinh 22 ",
  "dn22:0.2": "Kinh Đại Niệm Xứ ",
  "dn22:1.1": "Tôi nghe như vầy—",
  "dn22:1.2": "Một thời, Thế Tôn trú ở xứ Kuru, tại thị trấn của người Kuru tên là Kammāsadhamma. ",
  "dn22:1.3": "Tại đó, Thế Tôn gọi các Tỳ-kheo: ",
  "dn22:1.4": "“Này các Tỳ-kheo.” ",
  "dn22:1.5": "Các Tỳ-kheo ấy vâng đáp Thế Tôn: “Bạch Thế Tôn.” ",
  "dn22:1.6": "Thế Tôn nói như sau: ",
  "dn22:1.7": "“Này các Tỳ-kheo, đây là con đường độc nhất đưa đến sự thanh tịnh cho chúng sinh, vượt qua sầu bi, diệt trừ khổ ưu, thành tựu chánh đạo, chứng ngộ Niết-bàn, tức là bốn niệm xứ. ",
  "dn22:1.8": "Bốn niệm xứ là gì? ",
  "dn22:1.9": "Ở đây, này các Tỳ-kheo, vị Tỳ-kheo sống quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời, ",
  "dn22:1.10": "sống quán thọ trên các cảm thọ, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời, ",
  "dn22:1.11": "sống quán tâm trên tâm, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời, ",
  "dn22:1.12": "sống quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời. ",
  "dn22:1.13": "Phần tóm lược đã xong. ",
  "dn22:2.0.1": "1. Quán thân ",
  "dn22:2.0.2": "1.1. Phần quán thân về hơi thở ",
  "dn22:2.1": "Và này các Tỳ-kheo, thế nào là vị Tỳ-kheo sống quán thân trên thân? ",
  "dn22:2.2": "Ở đây, này các Tỳ-kheo, vị Tỳ-kheo đi đến rừng, hay đến gốc cây, hay đến ngôi nhà trống, ngồi xuống, xếp bằng, giữ thân ngay thẳng, an trú niệm trước mặt. ",
  "dn22:2.3": "Vị ấy chánh niệm khi thở vào, chánh niệm khi thở ra. ",
  "dn22:2.4": "Khi thở vào dài, vị ấy biết: ‘Tôi thở vào dài’; khi thở ra dài, vị ấy biết: ‘Tôi thở ra dài’. ",
  "dn22:2.5": "Khi thở vào ngắn, vị ấy biết: ‘Tôi thở vào ngắn’; khi thở ra ngắn, vị ấy biết: ‘Tôi thở ra ngắn’. ",
  "dn22:2.6": "Vị ấy tập: ‘Tôi sẽ thở vào cảm nhận toàn thân’; vị ấy tập: ‘Tôi sẽ thở ra cảm nhận toàn thân’. ",
  "dn22:2.7": "Vị ấy tập: ‘Tôi sẽ thở vào làm lắng dịu hành thân’; vị ấy tập: ‘Tôi sẽ thở ra làm lắng dịu hành thân’. ",
  "dn22:2.8": "Ví như, này các Tỳ-kheo, một người thợ tiện khéo hay người học việc của thợ tiện, khi kéo dài thì biết: ‘Tôi kéo dài’, khi kéo ngắn thì biết: ‘Tôi kéo ngắn’; ",
  "dn22:2.9": "cũng vậy, này các Tỳ-kheo, vị Tỳ-kheo khi thở vào dài biết: ‘Tôi thở vào dài’, khi thở ra dài biết: ‘Tôi thở ra dài’, khi thở vào ngắn biết: ‘Tôi thở vào ngắn’, khi thở ra ngắn biết: ‘Tôi thở ra ngắn’. ",
  "dn22:2.10": "Vị ấy tập: ‘Tôi sẽ thở vào cảm nhận toàn thân’; vị ấy tập: ‘Tôi sẽ thở ra cảm nhận toàn thân’; vị ấy tập: ‘Tôi sẽ thở vào làm lắng dịu hành thân’; vị ấy tập: ‘Tôi sẽ thở ra làm lắng dịu hành thân’. ",
  "dn22:2.11": "Như vậy, vị ấy sống quán thân trên thân ở nội thân, hay sống quán thân trên thân ở ngoại thân, hay sống quán thân trên thân ở cả nội thân và ngoại thân. ",
  "dn22:2.12": "Vị ấy sống quán pháp sinh khởi nơi thân, hay sống quán pháp hoại diệt nơi thân, hay sống quán pháp sinh khởi và hoại diệt nơi thân. ",
  "dn22:2.13": "Hoặc niệm được an trú nơi vị ấy rằng: ‘Có thân đây’, chỉ đến mức đủ cho trí biết và chánh niệm; vị ấy sống không nương tựa, không chấp thủ bất cứ gì ở đời. ",
  "dn22:2.14": "Như vậy, này các Tỳ-kheo, vị Tỳ-kheo sống quán thân trên thân. ",
  "dn22:2.15": "Phần hơi thở đã xong. ",
  "dn22:3.0": "1.2. Phần quán thân về oai nghi ",
  "dn22:3.1": "Lại nữa, này các Tỳ-kheo, vị Tỳ-kheo khi đi biết: ‘Tôi đang đi’; khi đứng biết: ‘Tôi đang đứng’; khi ngồi biết: ‘Tôi đang ngồi’; khi nằm biết: ‘Tôi đang nằm’; ",
  "dn22:3.2": "thân được đặt trong tư thế nào, vị ấy biết rõ như vậy. ",
  "dn22:3.3": "Như vậy, vị ấy sống quán thân trên thân ở nội thân, hay sống quán thân trên thân ở ngoại thân, hay sống quán thân trên thân ở cả nội thân và ngoại thân. ",
  "dn22:3.4": "Vị ấy sống quán pháp sinh khởi nơi thân, hay sống quán pháp hoại diệt nơi thân, hay sống quán pháp sinh khởi và hoại diệt nơi thân. ",
  "dn22:3.5": "Hoặc niệm được an trú nơi vị ấy rằng: ‘Có thân đây’, chỉ đến mức đủ cho trí biết và chánh niệm; vị ấy sống không nương tựa, không chấp thủ bất cứ gì ở đời. ",
  "dn22:3.6": "Như vậy, này các Tỳ-kheo, vị Tỳ-kheo sống quán thân trên thân. ",
  "dn22:3.7": "Phần oai nghi đã xong. ",
  "dn22:4.0": "1.3. Phần quán thân về tỉnh giác ",
  "dn22:4.1": "Lại nữa, này các Tỳ-kheo, vị Tỳ-kheo khi bước tới bước lui đều tỉnh giác; khi nhìn thẳng nhìn quanh đều tỉnh giác; khi co tay duỗi tay đều tỉnh giác; khi mang y, bát và y phục đều tỉnh giác; khi ăn, uống, nhai, nếm đều tỉnh giác; khi đại tiện, tiểu tiện đều tỉnh giác; khi đi, đứng, ngồi, ngủ, thức, nói, im lặng đều tỉnh giác. ",
  "dn22:4.2": "Như vậy, ở nội thân … ",
  "dn22:4.3": "Như vậy, này các Tỳ-kheo, vị Tỳ-kheo sống quán thân trên thân. ",
  "dn22:4.4": "Phần tỉnh giác đã xong. ",
  "dn22:5.0": "1.4. Phần quán thân về quán bất tịnh ",
  "dn22:5.1": "Lại nữa, này các Tỳ-kheo, vị Tỳ-kheo quán sát chính thân này từ bàn chân trở lên, từ đỉnh tóc trở xuống, được bao bọc bởi da, đầy dẫy nhiều thứ bất tịnh: ",
  "dn22:5.2": "‘Trong thân này có tóc, lông, móng, răng, da, thịt, gân, xương, tủy xương, thận, tim, gan, màng hoành, lá lách, phổi, ruột, màng ruột, dạ dày, phân, mật, đờm, mủ, máu, mồ hôi, mỡ, nước mắt, mỡ đặc, nước miếng, nước mũi, dịch khớp, nước tiểu’. ",
  "dn22:5.3": "Ví như, này các Tỳ-kheo, một cái bao có hai miệng, đầy các loại hạt khác nhau, như gạo lúa, lúa tẻ, đậu xanh, đậu lớn, mè, gạo trắng. Một người có mắt mở bao ấy ra và quán sát: ‘Đây là gạo lúa, đây là lúa tẻ, đây là đậu xanh, đây là đậu lớn, đây là mè, đây là gạo trắng’. ",
  "dn22:5.4": "Cũng vậy, này các Tỳ-kheo, vị Tỳ-kheo quán sát chính thân này từ bàn chân trở lên, từ đỉnh tóc trở xuống, được bao bọc bởi da, đầy dẫy nhiều thứ bất tịnh: ",
  "dn22:5.5": "‘Trong thân này có tóc, lông … nước tiểu’. ",
  "dn22:5.6": "Như vậy, ở nội thân … ",
  "dn22:5.7": "Như vậy, này các Tỳ-kheo, vị Tỳ-kheo sống quán thân trên thân. ",
  "dn22:5.8": "Phần quán bất tịnh đã xong. ",
  "dn22:6.0": "1.5. Phần quán thân về các đại ",
  "dn22:6.1": "Lại nữa, này các Tỳ-kheo, vị Tỳ-kheo quán sát chính thân này theo vị trí, theo cách được đặt, dưới khía cạnh các đại: ",
  "dn22:6.2": "‘Trong thân này có địa đại, thủy đại, hỏa đại, phong đại’. ",
  "dn22:6.3": "Ví như, này các Tỳ-kheo, một người đồ tể khéo hay người học việc của người đồ tể, sau khi giết một con bò, ngồi xuống ở ngã tư đường, chia nó ra từng phần; ",
  "dn22:6.4": "cũng vậy, này các Tỳ-kheo, vị Tỳ-kheo quán sát chính thân này theo vị trí, theo cách được đặt, dưới khía cạnh các đại: ",
  "dn22:6.5": "‘Trong thân này có địa đại, thủy đại, hỏa đại, phong đại’. ",
  "dn22:6.6": "Như vậy, vị ấy sống quán thân trên thân ở nội thân … ",
  "dn22:6.7": "Như vậy, này các Tỳ-kheo, vị Tỳ-kheo sống quán thân trên thân. ",
  "dn22:6.8": "Phần quán các đại đã xong. ",
  "dn22:7.0": "1.6. Phần quán thân về chín giai đoạn nơi nghĩa địa ",
  "dn22:7.1": "Lại nữa, này các Tỳ-kheo, vị Tỳ-kheo như thấy một xác chết bị quăng bỏ ở bãi tha ma, đã chết một ngày, hai ngày hay ba ngày, trương phồng, xanh đen, rữa nát. ",
  "dn22:7.2": "Vị ấy liên hệ đến chính thân này: ",
  "dn22:7.3": "‘Thân này của ta cũng có tính chất như vậy, sẽ thành như vậy, không vượt khỏi như vậy’. ",
  "dn22:7.4": "Như vậy, ở nội thân … ",
  "dn22:7.5": "Như vậy, này các Tỳ-kheo, vị Tỳ-kheo sống quán thân trên thân. ",
  "dn22:8.1": "Lại nữa, này các Tỳ-kheo, vị Tỳ-kheo như thấy một xác chết bị quăng bỏ ở bãi tha ma, bị quạ ăn, hay bị diều hâu ăn, hay bị kên kên ăn, hay bị chó ăn, hay bị cọp ăn, hay bị beo ăn, hay bị chó rừng ăn, hay bị nhiều loài sinh vật khác ăn. ",
  "dn22:8.2": "Vị ấy liên hệ đến chính thân này: ",
  "dn22:8.3": "‘Thân này của ta cũng có tính chất như vậy, sẽ thành như vậy, không vượt khỏi như vậy’. ",
  "dn22:8.4": "Như vậy, ở nội thân … ",
  "dn22:8.5": "Như vậy, này các Tỳ-kheo, vị Tỳ-kheo sống quán thân trên thân. ",
  "dn22:9.1": "Lại nữa, này các Tỳ-kheo, vị Tỳ-kheo như thấy một xác chết bị quăng bỏ ở bãi tha ma, chỉ còn bộ xương còn dính thịt và máu, được gân nối kết … ",
  "dn22:9.2": "Bộ xương không còn thịt nhưng còn dính máu, được gân nối kết … ",
  "dn22:9.3": "Bộ xương không còn thịt và máu, được gân nối kết … ",
  "dn22:9.4": "Các xương rời nhau, vung vãi khắp các hướng và hướng phụ; chỗ này xương bàn tay, chỗ kia xương bàn chân, chỗ kia xương cổ chân, chỗ kia xương ống chân, chỗ kia xương đùi, chỗ kia xương hông, chỗ kia xương sườn, chỗ kia xương sống, chỗ kia xương vai, chỗ kia xương cổ, chỗ kia xương hàm, chỗ kia xương răng, chỗ kia sọ đầu. ",
  "dn22:9.5": "Vị ấy liên hệ đến chính thân này: ",
  "dn22:9.6": "‘Thân này của ta cũng có tính chất như vậy, sẽ thành như vậy, không vượt khỏi như vậy’. ",
  "dn22:9.7": "Như vậy, ở nội thân … ",
  "dn22:9.8": "vị ấy sống quán thân trên thân. ",
  "dn22:10.1": "Lại nữa, này các Tỳ-kheo, vị Tỳ-kheo như thấy một xác chết bị quăng bỏ ở bãi tha ma, các xương trắng như màu vỏ sò … ",
  "dn22:10.2": "Các xương chất thành đống, đã hơn một năm … ",
  "dn22:10.3": "Các xương mục nát, thành bột. ",
  "dn22:10.4": "Vị ấy liên hệ đến chính thân này: ",
  "dn22:10.5": "‘Thân này của ta cũng có tính chất như vậy, sẽ thành như vậy, không vượt khỏi như vậy’. ",
  "dn22:10.6": "Như vậy, vị ấy sống quán thân trên thân ở nội thân, hay sống quán thân trên thân ở ngoại thân, hay sống quán thân trên thân ở cả nội thân và ngoại thân. ",
  "dn22:10.7": "Vị ấy sống quán pháp sinh khởi nơi thân, hay sống quán pháp hoại diệt nơi thân, hay sống quán pháp sinh khởi và hoại diệt nơi thân. ",
  "dn22:10.8": "Hoặc niệm được an trú nơi vị ấy rằng: ‘Có thân đây’, chỉ đến mức đủ cho trí biết và chánh niệm; vị ấy sống không nương tựa, không chấp thủ bất cứ gì ở đời. ",
  "dn22:10.9": "Như vậy, này các Tỳ-kheo, vị Tỳ-kheo sống quán thân trên thân. ",
  "dn22:10.10": "Phần chín giai đoạn nơi nghĩa địa đã xong. ",
  "dn22:10.11": "Mười bốn pháp quán thân đã xong. ",
  "dn22:11.0": "2. Quán thọ ",
  "dn22:11.1": "Và này các Tỳ-kheo, thế nào là vị Tỳ-kheo sống quán thọ trên các cảm thọ? ",
  "dn22:11.2": "Ở đây, này các Tỳ-kheo, khi cảm giác lạc thọ, vị ấy biết: ‘Tôi cảm giác lạc thọ’. ",
  "dn22:11.3": "Khi cảm giác khổ thọ, vị ấy biết: ‘Tôi cảm giác khổ thọ’. ",
  "dn22:11.4": "Khi cảm giác thọ không khổ không lạc, vị ấy biết: ‘Tôi cảm giác thọ không khổ không lạc’. ",
  "dn22:11.5": "Khi cảm giác lạc thọ có vật chất, vị ấy biết: ‘Tôi cảm giác lạc thọ có vật chất’. ",
  "dn22:11.6": "Khi cảm giác lạc thọ không vật chất, vị ấy biết: ‘Tôi cảm giác lạc thọ không vật chất’. ",
  "dn22:11.7": "Khi cảm thọ cảm giác khổ có dính líu vật chất, vị ấy biết: ‘Tôi cảm thọ cảm giác khổ có dính líu vật chất.’",
  "dn22:11.8": "Khi cảm thọ cảm giác khổ không dính líu vật chất, vị ấy biết: ‘Tôi cảm thọ cảm giác khổ không dính líu vật chất.’",
  "dn22:11.9": "Khi cảm thọ cảm giác không khổ không lạc có dính líu vật chất, vị ấy biết: ‘Tôi cảm thọ cảm giác không khổ không lạc có dính líu vật chất.’",
  "dn22:11.10": "Khi cảm thọ cảm giác không khổ không lạc không dính líu vật chất, vị ấy biết: ‘Tôi cảm thọ cảm giác không khổ không lạc không dính líu vật chất.’",
  "dn22:11.11": "Như vậy, vị ấy sống quán cảm thọ trên các cảm thọ ở nội thân, hay sống quán cảm thọ trên các cảm thọ ở ngoại thân, hay sống quán cảm thọ trên các cảm thọ cả ở nội thân lẫn ngoại thân.",
  "dn22:11.12": "Hay vị ấy sống quán tính sinh khởi trên các cảm thọ, hay sống quán tính hoại diệt trên các cảm thọ, hay sống quán tính sinh khởi và hoại diệt trên các cảm thọ.",
  "dn22:11.13": "Hoặc niệm được an trú nơi vị ấy rằng: ‘Có cảm thọ’, chỉ nhằm mục đích biết và ghi nhận, và vị ấy sống không nương tựa, không chấp thủ bất cứ gì ở đời.",
  "dn22:11.14": "Này các Tỳ-kheo, vị Tỳ-kheo sống quán cảm thọ trên các cảm thọ là như vậy.",
  "dn22:11.15": "Phần quán cảm thọ đã xong.",
  "dn22:12.0": "3. Quán tâm",
  "dn22:12.1": "Và này các Tỳ-kheo, thế nào là vị Tỳ-kheo sống quán tâm trên tâm?",
  "dn22:12.2": "Ở đây, này các Tỳ-kheo, khi tâm có tham, vị Tỳ-kheo biết: ‘Tâm có tham.’",
  "dn22:12.3": "Khi tâm không tham, vị ấy biết: ‘Tâm không tham.’",
  "dn22:12.4": "Khi tâm có sân, vị ấy biết: ‘Tâm có sân.’",
  "dn22:12.5": "Khi tâm không sân, vị ấy biết: ‘Tâm không sân.’",
  "dn22:12.6": "Khi tâm có si, vị ấy biết: ‘Tâm có si.’",
  "dn22:12.7": "Khi tâm không si, vị ấy biết: ‘Tâm không si.’",
  "dn22:12.8": "Khi tâm co rút, vị ấy biết: ‘Tâm co rút.’",
  "dn22:12.9": "Khi tâm tán loạn, vị ấy biết: ‘Tâm tán loạn.’",
  "dn22:12.10": "Khi tâm quảng đại, vị ấy biết: ‘Tâm quảng đại.’",
  "dn22:12.11": "Khi tâm không quảng đại, vị ấy biết: ‘Tâm không quảng đại.’",
  "dn22:12.12": "Khi tâm còn có thể vượt hơn, vị ấy biết: ‘Tâm còn có thể vượt hơn.’",
  "dn22:12.13": "Khi tâm không thể vượt hơn, vị ấy biết: ‘Tâm không thể vượt hơn.’",
  "dn22:12.14": "Khi tâm định tĩnh, vị ấy biết: ‘Tâm định tĩnh.’",
  "dn22:12.15": "Khi tâm không định tĩnh, vị ấy biết: ‘Tâm không định tĩnh.’",
  "dn22:12.16": "Khi tâm giải thoát, vị ấy biết: ‘Tâm giải thoát.’",
  "dn22:12.17": "Khi tâm không giải thoát, vị ấy biết: ‘Tâm không giải thoát.’",
  "dn22:12.18": "Như vậy, vị ấy sống quán tâm trên tâm ở nội thân, hay sống quán tâm trên tâm ở ngoại thân, hay sống quán tâm trên tâm cả ở nội thân lẫn ngoại thân.",
  "dn22:12.19": "Hay vị ấy sống quán tính sinh khởi trên tâm, hay sống quán tính hoại diệt trên tâm, hay sống quán tính sinh khởi và hoại diệt trên tâm.",
  "dn22:12.20": "Hoặc niệm được an trú nơi vị ấy rằng: ‘Có tâm’, chỉ nhằm mục đích biết và ghi nhận, và vị ấy sống không nương tựa, không chấp thủ bất cứ gì ở đời.",
  "dn22:12.21": "Này các Tỳ-kheo, vị Tỳ-kheo sống quán tâm trên tâm là như vậy.",
  "dn22:12.22": "Phần quán tâm đã xong.",
  "dn22:13.0.1": "4. Quán pháp",
  "dn22:13.0.2": "4.1. Phần quán pháp về năm triền cái",
  "dn22:13.1": "Và này các Tỳ-kheo, thế nào là vị Tỳ-kheo sống quán pháp trên các pháp?",
  "dn22:13.2": "Ở đây, này các Tỳ-kheo, vị Tỳ-kheo sống quán pháp trên các pháp đối với năm triền cái.",
  "dn22:13.3": "Và này các Tỳ-kheo, thế nào là vị Tỳ-kheo sống quán pháp trên các pháp đối với năm triền cái?",
  "dn22:13.4": "Ở đây, này các Tỳ-kheo, khi có dục tham ở nội tâm, vị Tỳ-kheo biết: ‘Nội tâm tôi có dục tham’; khi không có dục tham ở nội tâm, vị ấy biết: ‘Nội tâm tôi không có dục tham’; vị ấy biết rõ cách dục tham chưa sinh được sinh khởi; vị ấy biết rõ cách dục tham đã sinh được đoạn trừ; vị ấy biết rõ cách dục tham đã được đoạn trừ sẽ không sinh khởi trở lại trong tương lai.",
  "dn22:13.5": "Khi có sân ở nội tâm, vị ấy biết: ‘Nội tâm tôi có sân’; khi không có sân ở nội tâm, vị ấy biết: ‘Nội tâm tôi không có sân’; vị ấy biết rõ cách sân chưa sinh được sinh khởi; vị ấy biết rõ cách sân đã sinh được đoạn trừ; vị ấy biết rõ cách sân đã được đoạn trừ sẽ không sinh khởi trở lại trong tương lai.",
  "dn22:13.6": "Khi có hôn trầm thụy miên ở nội tâm, vị ấy biết: ‘Nội tâm tôi có hôn trầm thụy miên’; khi không có hôn trầm thụy miên ở nội tâm, vị ấy biết: ‘Nội tâm tôi không có hôn trầm thụy miên’; vị ấy biết rõ cách hôn trầm thụy miên chưa sinh được sinh khởi; vị ấy biết rõ cách hôn trầm thụy miên đã sinh được đoạn trừ; vị ấy biết rõ cách hôn trầm thụy miên đã được đoạn trừ sẽ không sinh khởi trở lại trong tương lai.",
  "dn22:13.7": "Khi có trạo cử hối quá ở nội tâm, vị ấy biết: ‘Nội tâm tôi có trạo cử hối quá’; khi không có trạo cử hối quá ở nội tâm, vị ấy biết: ‘Nội tâm tôi không có trạo cử hối quá’; vị ấy biết rõ cách trạo cử hối quá chưa sinh được sinh khởi; vị ấy biết rõ cách trạo cử hối quá đã sinh được đoạn trừ; vị ấy biết rõ cách trạo cử hối quá đã được đoạn trừ sẽ không sinh khởi trở lại trong tương lai.",
  "dn22:13.8": "Khi có nghi ở nội tâm, vị ấy biết: ‘Nội tâm tôi có nghi’; khi không có nghi ở nội tâm, vị ấy biết: ‘Nội tâm tôi không có nghi’; vị ấy biết rõ cách nghi chưa sinh được sinh khởi; vị ấy biết rõ cách nghi đã sinh được đoạn trừ; vị ấy biết rõ cách nghi đã được đoạn trừ sẽ không sinh khởi trở lại trong tương lai.",
  "dn22:13.9": "Như vậy, vị ấy sống quán pháp trên các pháp ở nội thân, hay sống quán pháp trên các pháp ở ngoại thân, hay sống quán pháp trên các pháp cả ở nội thân lẫn ngoại thân.",
  "dn22:13.10": "Hay vị ấy sống quán tính sinh khởi trên các pháp, hay sống quán tính hoại diệt trên các pháp, hay sống quán tính sinh khởi và hoại diệt trên các pháp.",
  "dn22:13.11": "Hoặc niệm được an trú nơi vị ấy rằng: ‘Có các pháp’, chỉ nhằm mục đích biết và ghi nhận, và vị ấy sống không nương tựa, không chấp thủ bất cứ gì ở đời.",
  "dn22:13.12": "Này các Tỳ-kheo, vị Tỳ-kheo sống quán pháp trên các pháp đối với năm triền cái là như vậy.",
  "dn22:13.13": "Phần về triền cái đã xong.",
  "dn22:14.0": "4.2. Phần quán pháp về các uẩn",
  "dn22:14.1": "Lại nữa, này các Tỳ-kheo, vị Tỳ-kheo sống quán pháp trên các pháp đối với năm thủ uẩn.",
  "dn22:14.2": "Và này các Tỳ-kheo, thế nào là vị Tỳ-kheo sống quán pháp trên các pháp đối với năm thủ uẩn?",
  "dn22:14.3": "Ở đây, này các Tỳ-kheo, vị Tỳ-kheo:",
  "dn22:14.4": "‘Đây là sắc, đây là sự sinh khởi của sắc, đây là sự đoạn diệt của sắc;",
  "dn22:14.5": "đây là thọ, đây là sự sinh khởi của thọ, đây là sự đoạn diệt của thọ;",
  "dn22:14.6": "đây là tưởng, đây là sự sinh khởi của tưởng, đây là sự đoạn diệt của tưởng;",
  "dn22:14.7": "đây là các hành, đây là sự sinh khởi của các hành, đây là sự đoạn diệt của các hành;",
  "dn22:14.8": "đây là thức, đây là sự sinh khởi của thức, đây là sự đoạn diệt của thức’,",
  "dn22:14.9": "như vậy, vị ấy sống quán pháp trên các pháp ở nội thân, hay sống quán pháp trên các pháp ở ngoại thân, hay sống quán pháp trên các pháp cả ở nội thân lẫn ngoại thân.",
  "dn22:14.10": "Hay vị ấy sống quán tính sinh khởi trên các pháp, hay sống quán tính hoại diệt trên các pháp, hay sống quán tính sinh khởi và hoại diệt trên các pháp.",
  "dn22:14.11": "Hoặc niệm được an trú nơi vị ấy rằng: ‘Có các pháp’, chỉ nhằm mục đích biết và ghi nhận, và vị ấy sống không nương tựa, không chấp thủ bất cứ gì ở đời.",
  "dn22:14.12": "Này các Tỳ-kheo, vị Tỳ-kheo sống quán pháp trên các pháp đối với năm thủ uẩn là như vậy.",
  "dn22:14.13": "Phần về các uẩn đã xong.",
  "dn22:15.0": "4.3. Phần quán pháp về các xứ",
  "dn22:15.1": "Lại nữa, này các Tỳ-kheo, vị Tỳ-kheo sống quán pháp trên các pháp đối với sáu nội ngoại xứ.",
  "dn22:15.2": "Và này các Tỳ-kheo, thế nào là vị Tỳ-kheo sống quán pháp trên các pháp đối với sáu nội ngoại xứ?",
  "dn22:15.3": "Ở đây, này các Tỳ-kheo, vị ấy biết mắt, biết các sắc, và biết kiết sử sinh khởi do duyên cả hai; vị ấy biết rõ cách kiết sử chưa sinh được sinh khởi; vị ấy biết rõ cách kiết sử đã sinh được đoạn trừ; vị ấy biết rõ cách kiết sử đã được đoạn trừ sẽ không sinh khởi trở lại trong tương lai.",
  "dn22:15.4": "Vị ấy biết tai, biết các tiếng, và biết kiết sử sinh khởi do duyên cả hai; vị ấy biết rõ cách kiết sử chưa sinh được sinh khởi; vị ấy biết rõ cách kiết sử đã sinh được đoạn trừ; vị ấy biết rõ cách kiết sử đã được đoạn trừ sẽ không sinh khởi trở lại trong tương lai.",
  "dn22:15.5": "Vị ấy biết mũi, biết các mùi, và biết kiết sử sinh khởi do duyên cả hai; vị ấy biết rõ cách kiết sử chưa sinh được sinh khởi; vị ấy biết rõ cách kiết sử đã sinh được đoạn trừ; vị ấy biết rõ cách kiết sử đã được đoạn trừ sẽ không sinh khởi trở lại trong tương lai.",
  "dn22:15.6": "Vị ấy biết lưỡi, biết các vị, và biết kiết sử sinh khởi do duyên cả hai; vị ấy biết rõ cách kiết sử chưa sinh được sinh khởi; vị ấy biết rõ cách kiết sử đã sinh được đoạn trừ; vị ấy biết rõ cách kiết sử đã được đoạn trừ sẽ không sinh khởi trở lại trong tương lai.",
  "dn22:15.7": "Vị ấy biết thân, biết các xúc chạm, và biết kiết sử sinh khởi do duyên cả hai; vị ấy biết rõ cách kiết sử chưa sinh được sinh khởi; vị ấy biết rõ cách kiết sử đã sinh được đoạn trừ; vị ấy biết rõ cách kiết sử đã được đoạn trừ sẽ không sinh khởi trở lại trong tương lai.",
  "dn22:15.8": "Vị ấy biết ý, biết các pháp, và biết kiết sử sinh khởi do duyên cả hai; vị ấy biết rõ cách kiết sử chưa sinh được sinh khởi; vị ấy biết rõ cách kiết sử đã sinh được đoạn trừ; vị ấy biết rõ cách kiết sử đã được đoạn trừ sẽ không sinh khởi trở lại trong tương lai.",
  "dn22:15.9": "Như vậy, vị ấy sống quán pháp trên các pháp ở nội thân, hay sống quán pháp trên các pháp ở ngoại thân, hay sống quán pháp trên các pháp cả ở nội thân lẫn ngoại thân.",
  "dn22:15.10": "Hay vị ấy sống quán tính sinh khởi trên các pháp, hay sống quán tính hoại diệt trên các pháp, hay sống quán tính sinh khởi và hoại diệt trên các pháp.",
  "dn22:15.11": "Hoặc niệm được an trú nơi vị ấy rằng: ‘Có các pháp’, chỉ nhằm mục đích biết và ghi nhận, và vị ấy sống không nương tựa, không chấp thủ bất cứ gì ở đời.",
  "dn22:15.12": "Này các Tỳ-kheo, vị Tỳ-kheo sống quán pháp trên các pháp đối với sáu nội ngoại xứ là như vậy.",
  "dn22:15.13": "Phần về các xứ đã xong.",
  "dn22:16.0": "4.4. Phần quán pháp về các giác chi",
  "dn22:16.1": "Lại nữa, này các Tỳ-kheo, vị Tỳ-kheo sống quán pháp trên các pháp đối với bảy giác chi.",
  "dn22:16.2": "Và này các Tỳ-kheo, thế nào là vị Tỳ-kheo sống quán pháp trên các pháp đối với bảy giác chi?",
  "dn22:16.3": "Ở đây, này các Tỳ-kheo, khi có niệm giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi có niệm giác chi’; khi không có niệm giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi không có niệm giác chi’; vị ấy biết rõ cách niệm giác chi chưa sinh được sinh khởi; vị ấy biết rõ cách niệm giác chi đã sinh được tu tập cho viên mãn.",
  "dn22:16.4": "Khi có trạch pháp giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi có trạch pháp giác chi’; khi không có trạch pháp giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi không có trạch pháp giác chi’; vị ấy biết rõ cách trạch pháp giác chi chưa sinh được sinh khởi; vị ấy biết rõ cách trạch pháp giác chi đã sinh được tu tập cho viên mãn.",
  "dn22:16.5": "Khi có tinh tấn giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi có tinh tấn giác chi’; khi không có tinh tấn giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi không có tinh tấn giác chi’; vị ấy biết rõ cách tinh tấn giác chi chưa sinh được sinh khởi; vị ấy biết rõ cách tinh tấn giác chi đã sinh được tu tập cho viên mãn.",
  "dn22:16.6": "Khi có hỷ giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi có hỷ giác chi’; khi không có hỷ giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi không có hỷ giác chi’; vị ấy biết rõ cách hỷ giác chi chưa sinh được sinh khởi; vị ấy biết rõ cách hỷ giác chi đã sinh được tu tập cho viên mãn.",
  "dn22:16.7": "Khi có khinh an giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi có khinh an giác chi’; khi không có khinh an giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi không có khinh an giác chi’; vị ấy biết rõ cách khinh an giác chi chưa sinh được sinh khởi; vị ấy biết rõ cách khinh an giác chi đã sinh được tu tập cho viên mãn.",
  "dn22:16.8": "Khi có định giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi có định giác chi’; khi không có định giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi không có định giác chi’; vị ấy biết rõ cách định giác chi chưa sinh được sinh khởi; vị ấy biết rõ cách định giác chi đã sinh được tu tập cho viên mãn.",
  "dn22:16.9": "Khi có xả giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi có xả giác chi’; khi không có xả giác chi ở nội tâm, vị ấy biết: ‘Nội tâm tôi không có xả giác chi’; vị ấy biết rõ cách xả giác chi chưa sinh được sinh khởi; vị ấy biết rõ cách xả giác chi đã sinh được tu tập cho viên mãn.",
  "dn22:16.10": "Như vậy, vị ấy sống quán pháp trên các pháp ở nội thân, hay sống quán pháp trên các pháp ở ngoại thân, hay sống quán pháp trên các pháp cả ở nội thân lẫn ngoại thân.",
  "dn22:16.11": "Hay vị ấy sống quán tính sinh khởi trên các pháp, hay sống quán tính hoại diệt trên các pháp, hay sống quán tính sinh khởi và hoại diệt trên các pháp.",
  "dn22:16.12": "Hoặc niệm được an trú nơi vị ấy rằng: ‘Có các pháp’, chỉ nhằm mục đích biết và ghi nhận, và vị ấy sống không nương tựa, không chấp thủ bất cứ gì ở đời.",
  "dn22:16.13": "Này các Tỳ-kheo, vị Tỳ-kheo sống quán pháp trên các pháp đối với bảy giác chi là như vậy.",
  "dn22:16.14": "Phần về các giác chi đã xong.",
  "dn22:17.0": "4.5. Phần quán pháp về các sự thật",
  "dn22:17.1": "Lại nữa, này các Tỳ-kheo, vị Tỳ-kheo sống quán pháp trên các pháp đối với bốn Thánh đế.",
  "dn22:17.2": "Và này các Tỳ-kheo, thế nào là vị Tỳ-kheo sống quán pháp trên các pháp đối với bốn Thánh đế?",
  "dn22:17.3": "Ở đây, này các Tỳ-kheo, vị ấy như thật biết: ‘Đây là khổ’; như thật biết: ‘Đây là nguyên nhân của khổ’; như thật biết: ‘Đây là sự diệt khổ’; như thật biết: ‘Đây là con đường đưa đến sự diệt khổ.’",
  "dn22:17.4": "Phần tụng đọc thứ nhất đã xong.",
  "dn22:18.0": "4.5.1. Giải thích Khổ đế",
  "dn22:18.1": "Và này các Tỳ-kheo, thế nào là Khổ Thánh đế?",
  "dn22:18.2": "Sinh là khổ, già là khổ, chết là khổ, sầu bi khổ ưu não là khổ, phải gần gũi điều không ưa là khổ, phải xa lìa điều mình ưa là khổ, mong cầu mà không được cũng là khổ; tóm lại, năm thủ uẩn là khổ.",
  "dn22:18.3": "Và này các Tỳ-kheo, thế nào là sinh?",
  "dn22:18.4": "Sự sinh ra, được sinh thành, nhập thai, hiện hữu, sự xuất hiện của các uẩn, sự thành tựu các xứ của các loài hữu tình trong từng loại hữu tình ấy,",
  "dn22:18.5": "Này các Tỳ-kheo, đây được gọi là sinh.",
  "dn22:18.6": "Và này các Tỳ-kheo, thế nào là già?",
  "dn22:18.7": "Sự già nua của các loài hữu tình trong từng loại hữu tình ấy, sự lão suy, răng gãy, tóc bạc, da nhăn, tuổi thọ suy giảm, các căn chín muồi,",
  "dn22:18.8": "này các Tỳ-kheo, đây được gọi là già.",
  "dn22:18.9": "Và này các Tỳ-kheo, thế nào là chết?",
  "dn22:18.10": "Sự từ bỏ, sự qua đời, sự tan rã, sự biến mất, sự tử vong, cái chết, sự mãn phần, sự tan hoại của các uẩn, sự vứt bỏ thi thể, sự đoạn diệt mạng căn của các loài hữu tình khỏi từng loại hữu tình ấy,",
  "dn22:18.11": "này các Tỳ-kheo, đây được gọi là chết.",
  "dn22:18.12": "Và này các Tỳ-kheo, thế nào là sầu?",
  "dn22:18.13": "Này các Tỳ-kheo, sự sầu muộn, sự buồn rầu, trạng thái sầu khổ trong lòng, nỗi ưu sầu nội tâm của người gặp phải một tai họa nào đó, bị chạm phải bởi một pháp khổ nào đó,",
  "dn22:18.14": "này các Tỳ-kheo, đây được gọi là sầu.",
  "dn22:18.15": "Và này các Tỳ-kheo, thế nào là than?",
  "dn22:18.16": "Này các Tỳ-kheo, sự than van, sự ai oán, sự than khóc, sự bi ai, trạng thái than van, trạng thái ai oán của người gặp phải một tai họa nào đó, bị chạm phải bởi một pháp khổ nào đó,",
  "dn22:18.17": "này các Tỳ-kheo, đây được gọi là than.",
  "dn22:18.18": "Và này các Tỳ-kheo, thế nào là khổ?",
  "dn22:18.19": "Này các Tỳ-kheo, khổ thân, sự không dễ chịu nơi thân, cảm thọ khổ không dễ chịu do xúc chạm nơi thân sinh ra,",
  "dn22:18.20": "này các Tỳ-kheo, đây được gọi là khổ.",
  "dn22:18.21": "Và này các Tỳ-kheo, thế nào là ưu?",
  "dn22:18.22": "Này các Tỳ-kheo, khổ tâm, sự không dễ chịu nơi tâm, cảm thọ khổ không dễ chịu do xúc chạm nơi ý sinh ra,",
  "dn22:18.23": "này các Tỳ-kheo, đây được gọi là ưu.",
  "dn22:18.24": "Và này các Tỳ-kheo, thế nào là não?",
  "dn22:18.25": "Này các Tỳ-kheo, sự bức bách, sự não hại, trạng thái bức bách, trạng thái não hại của người gặp phải một tai họa nào đó, bị chạm phải bởi một pháp khổ nào đó,",
  "dn22:18.26": "này các Tỳ-kheo, đây được gọi là não.",
  "dn22:18.27": "Và này các Tỳ-kheo, thế nào là khổ vì phải gặp điều không ưa?",
  "dn22:18.28": "Ở đây, những sắc, tiếng, mùi, vị, xúc, pháp nào là không đáng mong muốn, không đáng yêu, không vừa ý đối với người ấy; hoặc những người nào mong điều bất lợi cho người ấy, mong điều không lợi ích cho người ấy, mong điều không an vui cho người ấy, mong điều không an ổn cho người ấy; sự gặp gỡ, hội họp, tụ hội, hòa lẫn với những điều ấy,",
  "dn22:18.29": "này các Tỳ-kheo, đây được gọi là khổ vì phải gặp điều không ưa.",
  "dn22:18.30": "Và này các Tỳ-kheo, thế nào là khổ vì phải xa lìa điều ưa thích?",
  "dn22:18.31": "Ở đây, những sắc, tiếng, mùi, vị, xúc, pháp nào là đáng mong muốn, đáng yêu, vừa ý đối với người ấy; hoặc những người nào mong lợi ích cho người ấy, mong điều tốt lành cho người ấy, mong điều an vui cho người ấy, mong điều an ổn cho người ấy, như mẹ, cha, anh em trai, chị em gái, bạn bè, đồng liêu, bà con huyết thống; sự không gặp gỡ, không hội họp, không tụ hội, không hòa lẫn với những điều ấy,",
  "dn22:18.32": "này các Tỳ-kheo, đây được gọi là khổ vì phải xa lìa điều ưa thích.",
  "dn22:18.33": "Và này các Tỳ-kheo, thế nào là điều mong cầu mà không được cũng là khổ?",
  "dn22:18.34": "Này các Tỳ-kheo, nơi các chúng sinh có bản chất phải sinh, khởi lên ước muốn như vầy:",
  "dn22:18.35": "‘Ôi, mong sao chúng ta không phải là những kẻ có bản chất phải sinh, và mong sao sinh đừng đến với chúng ta.’",
  "dn22:18.36": "Nhưng điều ấy không thể đạt được bằng ước muốn,",
  "dn22:18.37": "điều này cũng là điều mong cầu mà không được, nên cũng là khổ.",
  "dn22:18.38": "Này các Tỳ-kheo, nơi các chúng sinh có bản chất phải già, khởi lên ước muốn như vầy:",
  "dn22:18.39": "‘Ôi, mong sao chúng ta không phải là những kẻ có bản chất phải già, và mong sao già đừng đến với chúng ta.’",
  "dn22:18.40": "Nhưng điều ấy không thể đạt được bằng ước muốn; điều này cũng là điều mong cầu mà không được, nên cũng là khổ.",
  "dn22:18.41": "Này các Tỳ-kheo, nơi các chúng sinh có bản chất phải bệnh, khởi lên ước muốn như vầy: ‘Ôi, mong sao chúng ta không phải là những kẻ có bản chất phải bệnh, và mong sao bệnh đừng đến với chúng ta.’",
  "dn22:18.42": "Nhưng điều ấy không thể đạt được bằng ước muốn; điều này cũng là điều mong cầu mà không được, nên cũng là khổ.",
  "dn22:18.43": "Này các Tỳ-kheo, nơi các chúng sinh có bản chất phải chết, khởi lên ước muốn như vầy: ‘Ôi, mong sao chúng ta không phải là những kẻ có bản chất phải chết, và mong sao cái chết đừng đến với chúng ta.’",
  "dn22:18.44": "Nhưng điều ấy không thể đạt được bằng ước muốn; điều này cũng là điều mong cầu mà không được, nên cũng là khổ.",
  "dn22:18.45": "Này các Tỳ-kheo, nơi các chúng sinh có bản chất phải sầu, than, khổ, ưu, não, khởi lên ước muốn như vầy: ‘Ôi, mong sao chúng ta không phải là những kẻ có bản chất phải sầu, than, khổ, ưu, não, và mong sao sầu, than, khổ, ưu, não đừng đến với chúng ta.’",
  "dn22:18.46": "Nhưng điều ấy không thể đạt được bằng ước muốn,",
  "dn22:18.47": "điều này cũng là điều mong cầu mà không được, nên cũng là khổ.",
  "dn22:18.48": "Và này các Tỳ-kheo, tóm lại, năm thủ uẩn là khổ gồm những gì?",
  "dn22:18.49": "Đó là: sắc thủ uẩn, thọ thủ uẩn, tưởng thủ uẩn, hành thủ uẩn, thức thủ uẩn.",
  "dn22:18.50": "Này các Tỳ-kheo, đó được gọi là tóm lại năm thủ uẩn là khổ.",
  "dn22:18.51": "Này các Tỳ-kheo, đây được gọi là Khổ Thánh đế.",
  "dn22:19.0": "4.5.2. Giải thích Tập đế",
  "dn22:19.1": "Và này các Tỳ-kheo, thế nào là Thánh đế về nguồn gốc của khổ?",
  "dn22:19.2": "Chính là ái này, đưa đến tái sinh, đi cùng với hỷ và tham, hoan hỷ chỗ này chỗ kia, tức là:",
  "dn22:19.3": "dục ái, hữu ái, phi hữu ái.",
  "dn22:19.4": "Nhưng này các Tỳ-kheo, ái ấy khi sinh khởi thì sinh khởi ở đâu, khi an trú thì an trú ở đâu?",
  "dn22:19.5": "Trong đời, cái gì là khả ái, khả lạc, thì ái ấy khi sinh khởi sinh khởi ở đó, khi an trú an trú ở đó.",
  "dn22:19.6": "Và trong đời, cái gì là khả ái, khả lạc?",
  "dn22:19.7": "Mắt trong đời là khả ái, khả lạc; ái ấy khi sinh khởi sinh khởi ở đó, khi an trú an trú ở đó.",
  "dn22:19.8": "Tai trong đời …",
  "dn22:19.9": "Mũi trong đời …",
  "dn22:19.10": "Lưỡi trong đời …",
  "dn22:19.11": "Thân trong đời …",
  "dn22:19.12": "Ý trong đời là khả ái, khả lạc; ái ấy khi sinh khởi sinh khởi ở đó, khi an trú an trú ở đó.",
  "dn22:19.13": "Các sắc trong đời …",
  "dn22:19.14": "Các tiếng trong đời …",
  "dn22:19.15": "Các mùi trong đời …",
  "dn22:19.16": "Các vị trong đời …",
  "dn22:19.17": "Các xúc trong đời …",
  "dn22:19.18": "Các pháp trong đời là khả ái, khả lạc; ái ấy khi sinh khởi sinh khởi ở đó, khi an trú an trú ở đó.",
  "dn22:19.19": "Nhãn thức trong đời …",
  "dn22:19.20": "Nhĩ thức trong đời …",
  "dn22:19.21": "Tỷ thức trong đời …",
  "dn22:19.22": "Thiệt thức trong đời …",
  "dn22:19.23": "Thân thức trong đời …",
  "dn22:19.24": "Ý thức trong đời là khả ái, khả lạc; ái ấy khi sinh khởi sinh khởi ở đó, khi an trú an trú ở đó.",
  "dn22:19.25": "Nhãn xúc trong đời …",
  "dn22:19.26": "Nhĩ xúc trong đời …",
  "dn22:19.27": "Tỷ xúc trong đời …",
  "dn22:19.28": "Thiệt xúc trong đời …",
  "dn22:19.29": "Thân xúc trong đời …",
  "dn22:19.30": "Ý xúc trong đời là khả ái, khả lạc; ái ấy khi sinh khởi sinh khởi ở đó, khi an trú an trú ở đó.",
  "dn22:19.31": "Cảm thọ do nhãn xúc sinh trong đời …",
  "dn22:19.32": "Cảm thọ do nhĩ xúc sinh trong đời …",
  "dn22:19.33": "Cảm thọ do tỷ xúc sinh trong đời …",
  "dn22:19.34": "Cảm thọ do thiệt xúc sinh trong đời …",
  "dn22:19.35": "Cảm thọ do thân xúc sinh trong đời …",
  "dn22:19.36": "Cảm thọ do ý xúc sinh trong đời là khả ái, khả lạc; ái ấy khi sinh khởi sinh khởi ở đó, khi an trú an trú ở đó.",
  "dn22:19.37": "Tưởng về sắc trong đời …",
  "dn22:19.38": "Tưởng về tiếng trong đời …",
  "dn22:19.39": "Tưởng về mùi trong đời …",
  "dn22:19.40": "Tưởng về vị trong đời …",
  "dn22:19.41": "Tưởng về xúc trong đời …",
  "dn22:19.42": "Tưởng về pháp trong đời là khả ái, khả lạc; ái ấy khi sinh khởi sinh khởi ở đó, khi an trú an trú ở đó.",
  "dn22:19.43": "Tư về sắc trong đời …",
  "dn22:19.44": "Tư về tiếng trong đời …",
  "dn22:19.45": "Tư về mùi trong đời …",
  "dn22:19.46": "Tư về vị trong đời …",
  "dn22:19.47": "Tư về xúc trong đời …",
  "dn22:19.48": "Tư về pháp trong đời là khả ái, khả lạc; ái ấy khi sinh khởi sinh khởi ở đó, khi an trú an trú ở đó.",
  "dn22:19.49": "Ái đối với sắc trong đời …",
  "dn22:19.50": "Ái đối với tiếng trong đời …",
  "dn22:19.51": "Ái đối với mùi trong đời …",
  "dn22:19.52": "Ái đối với vị trong đời …",
  "dn22:19.53": "Ái đối với xúc chạm ở đời …",
  "dn22:19.54": "Ái đối với các pháp ở đời là điều khả ái, khả lạc; tại đây ái ấy khi khởi lên thì khởi lên, khi an trú thì an trú tại đây.",
  "dn22:19.55": "Tầm về sắc ở đời …",
  "dn22:19.56": "Tầm về tiếng ở đời …",
  "dn22:19.57": "Tầm về hương ở đời …",
  "dn22:19.58": "Tầm về vị ở đời …",
  "dn22:19.59": "Tầm về xúc chạm ở đời …",
  "dn22:19.60": "Tầm về các pháp ở đời là điều khả ái, khả lạc; tại đây ái ấy khi khởi lên thì khởi lên, khi an trú thì an trú tại đây.",
  "dn22:19.61": "Tứ về sắc ở đời …",
  "dn22:19.62": "Tứ về tiếng ở đời …",
  "dn22:19.63": "Tứ về hương ở đời …",
  "dn22:19.64": "Tứ về vị ở đời …",
  "dn22:19.65": "Tứ về xúc chạm ở đời …",
  "dn22:19.66": "Tứ về các pháp ở đời là điều khả ái, khả lạc; tại đây ái ấy khi khởi lên thì khởi lên, khi an trú thì an trú tại đây.",
  "dn22:19.67": "Này các Tỳ-kheo, đây được gọi là Thánh đế về khổ tập.",
  "dn22:20.0": "4.5.3. Giải thích Thánh đế về diệt",
  "dn22:20.1": "Và này các Tỳ-kheo, thế nào là Thánh đế về khổ diệt?",
  "dn22:20.2": "Chính là sự ly tham, đoạn diệt không dư tàn đối với ái ấy; là xả bỏ, từ bỏ, giải thoát, không chấp trước.",
  "dn22:20.3": "Và này các Tỳ-kheo, ái ấy được đoạn trừ ở đâu thì bị đoạn trừ, được diệt tận ở đâu thì bị diệt tận?",
  "dn22:20.4": "Điều gì ở đời là khả ái, khả lạc, tại đó ái ấy khi được đoạn trừ thì bị đoạn trừ, khi được diệt tận thì bị diệt tận.",
  "dn22:20.5": "Và cái gì ở đời là khả ái, khả lạc?",
  "dn22:20.6": "Mắt ở đời là điều khả ái, khả lạc; tại đây ái ấy khi được đoạn trừ thì bị đoạn trừ, khi được diệt tận thì bị diệt tận.",
  "dn22:20.7": "Tai ở đời …",
  "dn22:20.8": "Mũi ở đời …",
  "dn22:20.9": "Lưỡi ở đời …",
  "dn22:20.10": "Thân ở đời …",
  "dn22:20.11": "Ý ở đời là điều khả ái, khả lạc; tại đây ái ấy khi được đoạn trừ thì bị đoạn trừ, khi được diệt tận thì bị diệt tận.",
  "dn22:20.12": "Các sắc ở đời …",
  "dn22:20.13": "Các tiếng ở đời …",
  "dn22:20.14": "Các hương ở đời …",
  "dn22:20.15": "Các vị ở đời …",
  "dn22:20.16": "Các xúc chạm ở đời …",
  "dn22:20.17": "Các pháp ở đời là điều khả ái, khả lạc; tại đây ái ấy khi được đoạn trừ thì bị đoạn trừ, khi được diệt tận thì bị diệt tận.",
  "dn22:20.18": "Nhãn thức ở đời …",
  "dn22:20.19": "Nhĩ thức ở đời …",
  "dn22:20.20": "Tỷ thức ở đời …",
  "dn22:20.21": "Thiệt thức ở đời …",
  "dn22:20.22": "Thân thức ở đời …",
  "dn22:20.23": "Ý thức ở đời là điều khả ái, khả lạc; tại đây ái ấy khi được đoạn trừ thì bị đoạn trừ, khi được diệt tận thì bị diệt tận.",
  "dn22:20.24": "Nhãn xúc ở đời …",
  "dn22:20.25": "Nhĩ xúc ở đời …",
  "dn22:20.26": "Tỷ xúc ở đời …",
  "dn22:20.27": "Thiệt xúc ở đời …",
  "dn22:20.28": "Thân xúc ở đời …",
  "dn22:20.29": "Ý xúc ở đời là điều khả ái, khả lạc; tại đây ái ấy khi được đoạn trừ thì bị đoạn trừ, khi được diệt tận thì bị diệt tận.",
  "dn22:20.30": "Cảm thọ do nhãn xúc sinh ở đời …",
  "dn22:20.31": "Cảm thọ do nhĩ xúc sinh ở đời …",
  "dn22:20.32": "Cảm thọ do tỷ xúc sinh ở đời …",
  "dn22:20.33": "Cảm thọ do thiệt xúc sinh ở đời …",
  "dn22:20.34": "Cảm thọ do thân xúc sinh ở đời …",
  "dn22:20.35": "Cảm thọ do ý xúc sinh ở đời là điều khả ái, khả lạc; tại đây ái ấy khi được đoạn trừ thì bị đoạn trừ, khi được diệt tận thì bị diệt tận.",
  "dn22:20.36": "Tưởng về sắc ở đời …",
  "dn22:20.37": "Tưởng về tiếng ở đời …",
  "dn22:20.38": "Tưởng về hương ở đời …",
  "dn22:20.39": "Tưởng về vị ở đời …",
  "dn22:20.40": "Tưởng về xúc chạm ở đời …",
  "dn22:20.41": "Tưởng về các pháp ở đời là điều khả ái, khả lạc; tại đây ái ấy khi được đoạn trừ thì bị đoạn trừ, khi được diệt tận thì bị diệt tận.",
  "dn22:20.42": "Tư về sắc ở đời …",
  "dn22:20.43": "Tư về tiếng ở đời …",
  "dn22:20.44": "Tư về hương ở đời …",
  "dn22:20.45": "Tư về vị ở đời …",
  "dn22:20.46": "Tư về xúc chạm ở đời …",
  "dn22:20.47": "Tư về các pháp ở đời là điều khả ái, khả lạc; tại đây ái ấy khi được đoạn trừ thì bị đoạn trừ, khi được diệt tận thì bị diệt tận.",
  "dn22:20.48": "Ái đối với sắc ở đời …",
  "dn22:20.49": "Ái đối với tiếng ở đời …",
  "dn22:20.50": "Ái đối với hương ở đời …",
  "dn22:20.51": "Ái đối với vị ở đời …",
  "dn22:20.52": "Ái đối với xúc chạm ở đời …",
  "dn22:20.53": "Ái đối với các pháp ở đời là điều khả ái, khả lạc; tại đây ái ấy khi được đoạn trừ thì bị đoạn trừ, khi được diệt tận thì bị diệt tận.",
  "dn22:20.54": "Tầm về sắc ở đời …",
  "dn22:20.55": "Tầm về tiếng ở đời …",
  "dn22:20.56": "Tầm về hương ở đời …",
  "dn22:20.57": "Tầm về vị ở đời …",
  "dn22:20.58": "Tầm về xúc chạm ở đời …",
  "dn22:20.59": "Tầm về các pháp ở đời là điều khả ái, khả lạc; tại đây ái ấy khi được đoạn trừ thì bị đoạn trừ, khi được diệt tận thì bị diệt tận.",
  "dn22:20.60": "Tứ về sắc ở đời …",
  "dn22:20.61": "Tứ về tiếng ở đời …",
  "dn22:20.62": "Tứ về hương ở đời …",
  "dn22:20.63": "Tứ về vị ở đời …",
  "dn22:20.64": "Tứ về xúc chạm ở đời …",
  "dn22:20.65": "Tứ về các pháp ở đời là điều khả ái, khả lạc; tại đây ái ấy khi được đoạn trừ thì bị đoạn trừ, khi được diệt tận thì bị diệt tận.",
  "dn22:20.66": "Này các Tỳ-kheo, đây được gọi là Thánh đế về khổ diệt.",
  "dn22:21.0": "4.5.4. Giải thích Thánh đế về đạo",
  "dn22:21.1": "Và này các Tỳ-kheo, thế nào là Thánh đế về con đường đưa đến khổ diệt?",
  "dn22:21.2": "Chính là Thánh đạo tám ngành này, tức là—",
  "dn22:21.3": "chánh kiến, chánh tư duy, chánh ngữ, chánh nghiệp, chánh mạng, chánh tinh tấn, chánh niệm, chánh định.",
  "dn22:21.4": "Và này các Tỳ-kheo, thế nào là chánh kiến?",
  "dn22:21.5": "Này các Tỳ-kheo, đó là tri kiến về khổ, tri kiến về khổ tập, tri kiến về khổ diệt, tri kiến về con đường đưa đến khổ diệt.",
  "dn22:21.6": "Này các Tỳ-kheo, đây được gọi là chánh kiến.",
  "dn22:21.7": "Và này các Tỳ-kheo, thế nào là chánh tư duy?",
  "dn22:21.8": "Tư duy xuất ly, tư duy không sân, tư duy không hại.",
  "dn22:21.9": "Này các Tỳ-kheo, đây được gọi là chánh tư duy.",
  "dn22:21.10": "Và này các Tỳ-kheo, thế nào là chánh ngữ?",
  "dn22:21.11": "Từ bỏ nói dối, từ bỏ nói hai lưỡi, từ bỏ nói lời thô ác, từ bỏ nói lời phù phiếm.",
  "dn22:21.12": "Này các Tỳ-kheo, đây được gọi là chánh ngữ.",
  "dn22:21.13": "Và này các Tỳ-kheo, thế nào là chánh nghiệp?",
  "dn22:21.14": "Từ bỏ sát sinh, từ bỏ lấy của không cho, từ bỏ tà hạnh trong các dục.",
  "dn22:21.15": "Này các Tỳ-kheo, đây được gọi là chánh nghiệp.",
  "dn22:21.16": "Và này các Tỳ-kheo, thế nào là chánh mạng?",
  "dn22:21.17": "Ở đây, này các Tỳ-kheo, vị Thánh đệ tử từ bỏ tà mạng, nuôi sống bằng chánh mạng.",
  "dn22:21.18": "Này các Tỳ-kheo, như vậy gọi là chánh mạng.",
  "dn22:21.19": "Và này các Tỳ-kheo, thế nào là chánh tinh tấn?",
  "dn22:21.20": "Ở đây, này các Tỳ-kheo, vị Tỳ-kheo khởi lên ý muốn, nỗ lực, phát khởi tinh tấn, thúc đẩy tâm, cố gắng để các pháp ác, bất thiện chưa sinh không sinh khởi;",
  "dn22:21.21": "khởi lên ý muốn, nỗ lực, phát khởi tinh tấn, thúc đẩy tâm, cố gắng để đoạn trừ các pháp ác, bất thiện đã sinh;",
  "dn22:21.22": "khởi lên ý muốn, nỗ lực, phát khởi tinh tấn, thúc đẩy tâm, cố gắng để các pháp thiện chưa sinh được sinh khởi;",
  "dn22:21.23": "khởi lên ý muốn, nỗ lực, phát khởi tinh tấn, thúc đẩy tâm, cố gắng để các pháp thiện đã sinh được an trú, không bị quên mất, được tăng trưởng, rộng lớn, tu tập và viên mãn.",
  "dn22:21.24": "Này các Tỳ-kheo, như vậy gọi là chánh tinh tấn.",
  "dn22:21.25": "Và này các Tỳ-kheo, thế nào là chánh niệm?",
  "dn22:21.26": "Ở đây, này các Tỳ-kheo, vị Tỳ-kheo sống quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời;",
  "dn22:21.27": "sống quán thọ trên các cảm thọ, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời;",
  "dn22:21.28": "sống quán tâm trên tâm, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời;",
  "dn22:21.29": "sống quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời.",
  "dn22:21.30": "Này các Tỳ-kheo, như vậy gọi là chánh niệm.",
  "dn22:21.31": "Và này các Tỳ-kheo, thế nào là chánh định?",
  "dn22:21.32": "Ở đây, này các Tỳ-kheo, vị Tỳ-kheo ly dục, ly các pháp bất thiện, chứng và an trú thiền thứ nhất, một trạng thái hỷ lạc do ly sinh, có tầm có tứ.",
  "dn22:21.33": "Do tầm và tứ lắng dịu, vị ấy chứng và an trú thiền thứ hai, nội tâm tịnh tín, nhất tâm, không tầm không tứ, hỷ lạc do định sinh.",
  "dn22:21.34": "Do ly hỷ, vị ấy trú xả, chánh niệm, tỉnh giác, và thân cảm nhận lạc thọ; vị ấy chứng và an trú thiền thứ ba mà các bậc Thánh nói rằng: ‘Xả niệm, chánh niệm, an trú lạc’.",
  "dn22:21.35": "Do đoạn trừ lạc và đoạn trừ khổ, do hỷ ưu đã diệt từ trước, vị ấy chứng và an trú thiền thứ tư, không khổ không lạc, thanh tịnh bởi xả niệm.",
  "dn22:21.36": "Này các Tỳ-kheo, như vậy gọi là chánh định.",
  "dn22:21.37": "Này các Tỳ-kheo, đây gọi là Thánh đế về con đường đưa đến sự diệt khổ.",
  "dn22:21.38": "Như vậy, vị ấy sống quán pháp trên các pháp nơi nội thân, hay sống quán pháp trên các pháp nơi ngoại thân, hay sống quán pháp trên các pháp nơi cả nội và ngoại thân.",
  "dn22:21.39": "Hoặc sống quán pháp tánh sinh khởi nơi các pháp, hoặc sống quán pháp tánh hoại diệt nơi các pháp, hoặc sống quán pháp tánh sinh khởi và hoại diệt nơi các pháp.",
  "dn22:21.40": "Hoặc niệm được an trú nơi vị ấy rằng: ‘Có các pháp’, chỉ nhằm chánh trí và chánh niệm; vị ấy sống không nương tựa, không chấp thủ một vật gì ở đời.",
  "dn22:21.41": "Này các Tỳ-kheo, như vậy vị Tỳ-kheo sống quán pháp trên các pháp đối với bốn Thánh đế.",
  "dn22:21.42": "Phần về các sự thật đã hoàn tất.",
  "dn22:21.43": "Phép quán pháp đã hoàn tất.",
  "dn22:22.1": "Này các Tỳ-kheo, bất cứ ai tu tập bốn niệm xứ này như vậy trong bảy năm, người ấy có thể mong đợi một trong hai quả:",
  "dn22:22.2": "hoặc chứng chánh trí ngay trong hiện tại, hoặc nếu còn dư y thì chứng quả Bất lai.",
  "dn22:22.3": "Này các Tỳ-kheo, hãy để bảy năm sang một bên.",
  "dn22:22.4": "Này các Tỳ-kheo, bất cứ ai tu tập bốn niệm xứ này như vậy trong sáu năm …",
  "dn22:22.5": "năm năm …",
  "dn22:22.6": "bốn năm …",
  "dn22:22.7": "ba năm …",
  "dn22:22.8": "hai năm …",
  "dn22:22.9": "một năm …",
  "dn22:22.10": "Này các Tỳ-kheo, hãy để một năm sang một bên.",
  "dn22:22.11": "Này các Tỳ-kheo, bất cứ ai tu tập bốn niệm xứ này như vậy trong bảy tháng, người ấy có thể mong đợi một trong hai quả:",
  "dn22:22.12": "hoặc chứng chánh trí ngay trong hiện tại, hoặc nếu còn dư y thì chứng quả Bất lai.",
  "dn22:22.13": "Này các Tỳ-kheo, hãy để bảy tháng sang một bên.",
  "dn22:22.14": "Này các Tỳ-kheo, bất cứ ai tu tập bốn niệm xứ này như vậy trong sáu tháng …",
  "dn22:22.15": "năm tháng …",
  "dn22:22.16": "bốn tháng …",
  "dn22:22.17": "ba tháng …",
  "dn22:22.18": "hai tháng …",
  "dn22:22.19": "một tháng …",
  "dn22:22.20": "nửa tháng …",
  "dn22:22.21": "Này các Tỳ-kheo, hãy để nửa tháng sang một bên.",
  "dn22:22.22": "Này các Tỳ-kheo, bất cứ ai tu tập bốn niệm xứ này như vậy trong bảy ngày, người ấy có thể mong đợi một trong hai quả:",
  "dn22:22.23": "hoặc chứng chánh trí ngay trong hiện tại, hoặc nếu còn dư y thì chứng quả Bất lai.",
  "dn22:22.24": "Này các Tỳ-kheo, đây là con đường độc nhất đưa đến sự thanh tịnh cho chúng sinh, vượt qua sầu bi, diệt trừ khổ ưu, thành tựu chánh đạo, chứng ngộ Niết-bàn, tức là bốn niệm xứ.",
  "dn22:22.25": "Điều gì đã được nói như vậy, chính là y cứ vào điều này mà được nói.",
  "dn22:22.26": "Thế Tôn đã nói như vậy.",
  "dn22:22.27": "Các vị Tỳ-kheo ấy hoan hỷ tín thọ lời Thế Tôn dạy.",
  "dn22:22.28": "Đại Niệm Xứ Kinh, phần thứ chín, đã hoàn tất."
}
window.BILARA["dn22"]["vi"]["dn22:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
