window.BILARA = window.BILARA || {};
window.BILARA["dn26"] = window.BILARA["dn26"] || {};
window.BILARA["dn26"]["vi"] = {
  "dn26:0.1": "Trường Bộ Kinh 26 ",
  "dn26:0.2": "Kinh Chuyển Luân Vương ",
  "dn26:1.0": "1. Tự mình là hòn đảo, tự mình là nơi nương tựa ",
  "dn26:1.1": "Tôi nghe như vầy—",
  "dn26:1.2": "một thời Thế Tôn trú ở xứ Magadha, tại Mātulā. ",
  "dn26:1.3": "Tại đó, Thế Tôn gọi các Tỳ-kheo: ",
  "dn26:1.4": "“Này các Tỳ-kheo.” ",
  "dn26:1.5": "“Bạch Thế Tôn,” các Tỳ-kheo ấy vâng đáp Thế Tôn. ",
  "dn26:1.6": "Thế Tôn nói như sau: ",
  "dn26:1.7": "“Này các Tỳ-kheo, hãy sống tự mình là hòn đảo, tự mình là nơi nương tựa, không nương tựa một gì khác; lấy Pháp làm hòn đảo, lấy Pháp làm nơi nương tựa, không nương tựa một gì khác. ",
  "dn26:1.8": "Và này các Tỳ-kheo, thế nào là vị Tỳ-kheo sống tự mình là hòn đảo, tự mình là nơi nương tựa, không nương tựa một gì khác; lấy Pháp làm hòn đảo, lấy Pháp làm nơi nương tựa, không nương tựa một gì khác? ",
  "dn26:1.9": "Ở đây, này các Tỳ-kheo, vị Tỳ-kheo sống quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời. ",
  "dn26:1.10": "Trên các cảm thọ, vị ấy sống quán cảm thọ … ",
  "dn26:1.11": "Trên tâm, vị ấy sống quán tâm … ",
  "dn26:1.12": "Trên các pháp, vị ấy sống quán pháp, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời. ",
  "dn26:1.13": "Như vậy, này các Tỳ-kheo, vị Tỳ-kheo sống tự mình là hòn đảo, tự mình là nơi nương tựa, không nương tựa một gì khác; lấy Pháp làm hòn đảo, lấy Pháp làm nơi nương tựa, không nương tựa một gì khác. ",
  "dn26:1.14": "Này các Tỳ-kheo, hãy đi trong cảnh giới của mình, trong lãnh vực của tổ phụ mình. ",
  "dn26:1.15": "Này các Tỳ-kheo, khi đi trong cảnh giới của mình, trong lãnh vực của tổ phụ mình, Ma vương không có cơ hội, Ma vương không có đối tượng. ",
  "dn26:1.16": "Này các Tỳ-kheo, chính do nhân thọ trì các pháp thiện mà công đức này được tăng trưởng như vậy. ",
  "dn26:2.0": "2. Vua Chuyển Luân Daḷhanemi ",
  "dn26:2.1": "Thuở xưa, này các Tỳ-kheo, có vua tên là Daḷhanemi, là vị Chuyển Luân Vương, trị vì đúng pháp, là Pháp vương, chinh phục bốn phương, đất nước được an định, đầy đủ bảy báu. ",
  "dn26:2.2": "Bảy báu ấy của vua là những gì? ",
  "dn26:2.3": "Đó là luân báu, tượng báu, mã báu, ngọc báu, nữ báu, gia chủ báu, và thứ bảy là tướng quân báu. ",
  "dn26:2.4": "Lại nữa, vua có hơn một ngàn người con, dũng mãnh, oai hùng, có khả năng nghiền nát quân địch. ",
  "dn26:2.5": "Vua chinh phục và cư trú trên quả đất này cho đến tận bờ biển, không dùng gậy, không dùng đao kiếm, mà bằng Chánh pháp. ",
  "dn26:3.1": "Rồi này các Tỳ-kheo, sau nhiều năm, nhiều trăm năm, nhiều ngàn năm, vua Daḷhanemi gọi một người đến và bảo: ",
  "dn26:3.2": "‘Này người kia, khi nào ngươi thấy thiên luân bảo đã xê dịch, rời khỏi chỗ của nó, thì hãy báo cho ta biết.’ ",
  "dn26:3.3": "‘Vâng, thưa Đại vương,’ người ấy vâng lời vua Daḷhanemi. ",
  "dn26:3.4": "Rồi này các Tỳ-kheo, sau nhiều năm, nhiều trăm năm, nhiều ngàn năm, người ấy thấy thiên luân bảo đã xê dịch, rời khỏi chỗ của nó. Thấy vậy, người ấy đến chỗ vua Daḷhanemi, sau khi đến liền tâu vua Daḷhanemi rằng: ",
  "dn26:3.5": "‘Tâu Đại vương, xin Đại vương biết cho, thiên luân bảo của Đại vương đã xê dịch, rời khỏi chỗ của nó.’ ",
  "dn26:3.6": "Rồi này các Tỳ-kheo, vua Daḷhanemi cho gọi thái tử trưởng đến và nói: ",
  "dn26:3.7": "‘Này con yêu quý, nghe nói thiên luân bảo của ta đã xê dịch, rời khỏi chỗ của nó. ",
  "dn26:3.8": "Ta lại từng nghe rằng—",
  "dn26:3.9": "khi thiên luân bảo của một vị Chuyển Luân Vương xê dịch, rời khỏi chỗ của nó, thì vị vua ấy không còn sống lâu nữa. ",
  "dn26:3.10": "Ta đã hưởng đủ các dục của loài người; nay đã đến lúc ta đi tìm các dục cõi trời. ",
  "dn26:3.11": "Này con yêu quý, con hãy tiếp nhận quả đất này cho đến tận bờ biển. ",
  "dn26:3.12": "Còn ta sẽ cạo bỏ râu tóc, khoác y ca-sa, từ bỏ gia đình, xuất gia không gia đình.’ ",
  "dn26:3.13": "Rồi này các Tỳ-kheo, vua Daḷhanemi sau khi khéo dạy bảo thái tử trưởng về vương quyền, liền cạo bỏ râu tóc, khoác y ca-sa, từ bỏ gia đình, xuất gia không gia đình. ",
  "dn26:3.14": "Và này các Tỳ-kheo, sau khi vị vua ẩn sĩ ấy xuất gia được bảy ngày, thiên luân bảo biến mất. ",
  "dn26:4.1": "Rồi này các Tỳ-kheo, có một người đến chỗ vị vua Sát-đế-lỵ đã làm lễ quán đảnh, sau khi đến liền tâu vị vua Sát-đế-lỵ đã làm lễ quán đảnh ấy rằng: ",
  "dn26:4.2": "‘Tâu Đại vương, xin Đại vương biết cho, thiên luân bảo đã biến mất.’ ",
  "dn26:4.3": "Rồi này các Tỳ-kheo, vị vua Sát-đế-lỵ đã làm lễ quán đảnh, khi thiên luân bảo biến mất, trở nên không vui và cảm nhận sự không vui ấy. ",
  "dn26:4.4": "Vị ấy đi đến chỗ vua ẩn sĩ, sau khi đến liền thưa vua ẩn sĩ rằng: ",
  "dn26:4.5": "‘Tâu Đại vương, xin Đại vương biết cho, thiên luân bảo đã biến mất.’ ",
  "dn26:4.6": "Khi được nói vậy, này các Tỳ-kheo, vua ẩn sĩ nói với vị vua Sát-đế-lỵ đã làm lễ quán đảnh rằng: ",
  "dn26:4.7": "‘Này con yêu quý, chớ vì thiên luân bảo biến mất mà không vui, chớ cảm nhận sự không vui ấy; vì này con yêu quý, thiên luân bảo ấy không phải là gia tài tổ tiên truyền lại cho con. ",
  "dn26:4.8": "Này con yêu quý, hãy thực hành theo Thánh pháp của vị Chuyển Luân Vương. ",
  "dn26:4.9": "Có khả năng là, khi con thực hành theo Thánh pháp của vị Chuyển Luân Vương, vào ngày bố-tát mười lăm, sau khi tắm đầu, thọ trì bố-tát, lên ngự trên lầu thượng điện, thiên luân bảo sẽ hiện ra cho con, có một ngàn căm, có vành, có trục, đầy đủ mọi tướng.’ ",
  "dn26:5.0": "2.1. Thánh pháp của vị Chuyển Luân Vương ",
  "dn26:5.1": "‘Thưa Đại vương, thế nào là Thánh pháp của vị Chuyển Luân Vương?’ ",
  "dn26:5.2": "‘Vậy thì, con thân, hãy nương nơi pháp, tôn kính pháp, trọng pháp, quý pháp, thờ kính pháp, cung kính pháp; lấy pháp làm cờ, lấy pháp làm ngọn, lấy pháp làm tối thượng; hãy thiết lập sự che chở, bảo vệ và gìn giữ đúng pháp đối với nội cung, quân đội, các vua chư hầu, các bà-la-môn và gia chủ, dân thị thành và thôn quê, các sa-môn bà-la-môn, cùng các loài thú và chim.",
  "dn26:5.3": "Và này con thân, chớ để điều phi pháp xảy ra trong quốc độ của con.",
  "dn26:5.4": "Và này con thân, những ai trong quốc độ của con còn nghèo thiếu, con hãy cấp tài sản cho họ.",
  "dn26:5.5": "Và này con thân, những sa-môn bà-la-môn nào trong quốc độ của con đã từ bỏ say đắm và phóng dật, an trú trong nhẫn nhục và nhu hòa, tự điều phục mình, tự làm lắng dịu mình, tự làm tịch diệt mình, con hãy thỉnh thoảng đến hỏi han và tìm hiểu họ:",
  "dn26:5.6": "“Bạch các ngài, điều gì là thiện, điều gì là bất thiện, điều gì có lỗi, điều gì không lỗi, điều gì nên làm, điều gì không nên làm, điều gì nếu con làm sẽ lâu dài đưa đến bất lợi và khổ đau, hay điều gì nếu con làm sẽ lâu dài đưa đến lợi ích và an lạc?”",
  "dn26:5.7": "Nghe họ xong, điều gì là bất thiện thì con hãy tránh xa, điều gì là thiện thì con hãy thọ trì và thực hành.",
  "dn26:5.8": "Này con thân, đó gọi là pháp hành của bậc Thánh vương Chuyển luân.’",
  "dn26:5.9.0": "2.2. Sự xuất hiện của bánh xe báu",
  "dn26:5.10": "‘Vâng, tâu thiên tử’, này các Tỳ-kheo, vị vua Sát-đế-lỵ đã làm lễ quán đảnh lên ngôi, sau khi vâng lời dạy của phụ vương, đã thực hành theo pháp hành của bậc Thánh vương Chuyển luân.",
  "dn26:5.11": "Khi vị ấy đang thực hành theo pháp hành của bậc Thánh vương Chuyển luân, vào ngày bố-tát rằm, sau khi đã gội đầu, giữ ngày bố-tát, và lên lầu đài thượng hạng,",
  "dn26:5.12": "thì bánh xe báu thần diệu hiện ra, có một ngàn căm, có vành, có trục, đầy đủ mọi tướng tốt.",
  "dn26:5.13": "Thấy vậy, vị vua Sát-đế-lỵ đã làm lễ quán đảnh lên ngôi nghĩ rằng:",
  "dn26:5.14": "‘Ta có nghe rằng: vị vua Sát-đế-lỵ đã làm lễ quán đảnh lên ngôi nào, vào ngày bố-tát rằm, sau khi đã gội đầu, giữ ngày bố-tát, và lên lầu đài thượng hạng, nếu bánh xe báu thần diệu hiện ra, có một ngàn căm, có vành, có trục, đầy đủ mọi tướng tốt, thì vị ấy là vua Chuyển luân.",
  "dn26:5.15": "Phải chăng ta là vua Chuyển luân?’",
  "dn26:6.1": "Rồi này các Tỳ-kheo, vị vua Sát-đế-lỵ đã làm lễ quán đảnh lên ngôi ấy từ chỗ ngồi đứng dậy, vắt thượng y lên một vai, tay trái cầm bình nước, tay phải rảy nước lên bánh xe báu:",
  "dn26:6.2": "‘Xin bánh xe báu tôn quý hãy chuyển vận, xin bánh xe báu tôn quý hãy chinh phục.’",
  "dn26:6.3": "Rồi này các Tỳ-kheo, bánh xe báu ấy chuyển về phương đông, và vua Chuyển luân đi theo ngay sau cùng với bốn binh chủng. Này các Tỳ-kheo, ở nơi nào bánh xe báu dừng lại, tại đó vua Chuyển luân cùng với bốn binh chủng đến trú ngụ.",
  "dn26:6.4": "Này các Tỳ-kheo, những vị vua đối địch ở phương đông ấy đến yết kiến vua Chuyển luân và thưa rằng:",
  "dn26:6.5": "‘Xin mời, thưa Đại vương, hoan nghênh Đại vương, thưa Đại vương, đây là lãnh thổ của Đại vương, xin Đại vương giáo huấn, thưa Đại vương.’",
  "dn26:6.6": "Vua Chuyển luân nói như sau:",
  "dn26:6.7": "‘Không được sát sinh, không được lấy của không cho, không được tà hạnh trong các dục, không được nói dối, không được uống rượu, và hãy dùng vật thực đúng mức.’",
  "dn26:6.8": "Này các Tỳ-kheo, những vị vua đối địch ở phương đông ấy trở thành người thuận theo vua Chuyển luân.",
  "dn26:7.1": "Rồi này các Tỳ-kheo, bánh xe báu ấy lặn xuống biển phía đông rồi hiện lên, chuyển sang phương nam …",
  "dn26:7.2": "lặn xuống biển phía nam rồi hiện lên, chuyển sang phương tây, và vua Chuyển luân đi theo ngay sau cùng với bốn binh chủng.",
  "dn26:7.3": "Này các Tỳ-kheo, ở nơi nào bánh xe báu dừng lại, tại đó vua Chuyển luân cùng với bốn binh chủng đến trú ngụ.",
  "dn26:7.4": "Này các Tỳ-kheo, những vị vua đối địch ở phương tây ấy đến yết kiến vua Chuyển luân và thưa rằng:",
  "dn26:7.5": "‘Xin mời, thưa Đại vương, hoan nghênh Đại vương, thưa Đại vương, đây là lãnh thổ của Đại vương, xin Đại vương giáo huấn, thưa Đại vương.’",
  "dn26:7.6": "Vua Chuyển luân nói như sau:",
  "dn26:7.7": "‘Không được sát sinh, không được lấy của không cho, không được tà hạnh trong các dục, không được nói dối, không được uống rượu, và hãy dùng vật thực đúng mức.’",
  "dn26:7.8": "Này các Tỳ-kheo, những vị vua đối địch ở phương tây ấy trở thành người thuận theo vua Chuyển luân.",
  "dn26:7.9": "Rồi này các Tỳ-kheo, bánh xe báu ấy lặn xuống biển phía tây rồi hiện lên, chuyển sang phương bắc, và vua Chuyển luân đi theo ngay sau cùng với bốn binh chủng.",
  "dn26:7.10": "Này các Tỳ-kheo, ở nơi nào bánh xe báu dừng lại, tại đó vua Chuyển luân cùng với bốn binh chủng đến trú ngụ.",
  "dn26:7.11": "Này các Tỳ-kheo, những vị vua đối địch ở phương bắc ấy đến yết kiến vua Chuyển luân và thưa rằng:",
  "dn26:7.12": "‘Xin mời, thưa Đại vương, hoan nghênh Đại vương, thưa Đại vương, đây là lãnh thổ của Đại vương, xin Đại vương giáo huấn, thưa Đại vương.’",
  "dn26:7.13": "Vua Chuyển luân nói như sau:",
  "dn26:7.14": "‘Không được sát sinh, không được lấy của không cho, không được tà hạnh trong các dục, không được nói dối, không được uống rượu, và hãy dùng vật thực đúng mức.’",
  "dn26:7.15": "Này các Tỳ-kheo, những vị vua đối địch ở phương bắc ấy trở thành người thuận theo vua Chuyển luân.",
  "dn26:7.16": "Rồi này các Tỳ-kheo, bánh xe báu ấy sau khi chinh phục toàn cõi đất đến tận bờ biển, lại trở về chính kinh đô ấy, đứng tại cổng nội cung của vua Chuyển luân, ở trước pháp đình, như thể được treo lơ lửng, làm rực rỡ nội cung của vua Chuyển luân.",
  "dn26:8.0": "3. Chuyện các vị Chuyển luân vương tiếp theo",
  "dn26:8.1": "Vị vua Chuyển luân thứ hai cũng vậy …",
  "dn26:8.2": "Vị vua Chuyển luân thứ ba cũng vậy …",
  "dn26:8.3": "Vị vua Chuyển luân thứ tư cũng vậy …",
  "dn26:8.4": "Vị vua Chuyển luân thứ năm cũng vậy …",
  "dn26:8.5": "Vị vua Chuyển luân thứ sáu cũng vậy …",
  "dn26:8.6": "Này các Tỳ-kheo, vị vua Chuyển luân thứ bảy, sau nhiều năm, nhiều trăm năm, nhiều ngàn năm, gọi một người đến và bảo:",
  "dn26:8.7": "‘Này người kia, khi nào ngươi thấy bánh xe báu thần diệu ấy sa sút, rời khỏi vị trí, thì hãy báo cho ta biết.’",
  "dn26:8.8": "‘Vâng, tâu thiên tử’, này các Tỳ-kheo, người ấy vâng lời vua Chuyển luân.",
  "dn26:8.9": "Này các Tỳ-kheo, sau nhiều năm, nhiều trăm năm, nhiều ngàn năm, người ấy thấy bánh xe báu thần diệu đã sa sút, rời khỏi vị trí.",
  "dn26:8.10": "Thấy vậy, người ấy đi đến chỗ vua Chuyển luân; đến nơi, thưa với vua Chuyển luân rằng:",
  "dn26:8.11": "‘Tâu thiên tử, xin ngài biết cho, bánh xe báu thần diệu của ngài đã sa sút, rời khỏi vị trí.’",
  "dn26:8.12": "Rồi này các Tỳ-kheo, vua Chuyển luân gọi thái tử trưởng đến và nói như sau:",
  "dn26:8.13": "‘Này con yêu, nghe nói thiên luân bảo của ta đã xê dịch, rời khỏi chỗ của nó; ta lại từng nghe rằng—",
  "dn26:8.14": "khi thiên luân bảo của vị vua Chuyển luân xê dịch, rời khỏi chỗ của nó, thì vị vua ấy không còn sống lâu nữa. ",
  "dn26:8.15": "Các dục của loài người ta đã hưởng đủ rồi, nay đã đến lúc ta tìm cầu các dục cõi trời. Này con yêu, con hãy tiếp nhận cai trị cõi đất này cho đến tận bờ biển. ",
  "dn26:8.16": "Còn ta sẽ cạo bỏ râu tóc, khoác y ca-sa, từ bỏ gia đình, xuất gia không gia đình.’",
  "dn26:8.17": "Rồi này các Tỳ-kheo, vua Chuyển luân sau khi khéo dạy bảo thái tử trưởng về vương quyền, liền cạo bỏ râu tóc, khoác y ca-sa, từ bỏ gia đình, xuất gia không gia đình. ",
  "dn26:8.18": "Này các Tỳ-kheo, sau khi vị vua hiền xuất gia được bảy ngày, thiên luân bảo biến mất. ",
  "dn26:9.1": "Rồi này các Tỳ-kheo, có một người đến chỗ vị vua Sát-đế-lỵ đã làm lễ quán đảnh; đến rồi thưa với vị vua Sát-đế-lỵ đã làm lễ quán đảnh rằng:",
  "dn26:9.2": "‘Tâu Đại vương, xin Đại vương biết cho, thiên luân bảo đã biến mất.’",
  "dn26:9.3": "Rồi này các Tỳ-kheo, khi thiên luân bảo biến mất, vị vua Sát-đế-lỵ đã làm lễ quán đảnh lấy làm không vui. Vị ấy cảm nhận sự không vui ấy;",
  "dn26:9.4": "nhưng lại không đến hỏi vị vua hiền về pháp hành cao quý của bậc Chuyển luân. ",
  "dn26:9.5": "Vị ấy chỉ cai trị quốc độ theo cách riêng của mình. ",
  "dn26:9.6": "Khi vị ấy cai trị quốc độ theo cách ấy, các vùng trong nước không được hưng thịnh như trước, không giống như dưới thời các vị vua trước kia sống đúng theo pháp hành cao quý của bậc Chuyển luân. ",
  "dn26:9.7": "Rồi này các Tỳ-kheo, các đại thần, quần thần, quan coi sổ sách, đại thần, các tướng lĩnh, quan giữ cửa và các cố vấn tụ họp lại rồi tâu với vị vua Sát-đế-lỵ đã làm lễ quán đảnh rằng:",
  "dn26:9.8": "‘Tâu Đại vương, khi Đại vương chỉ cai trị quốc độ theo cách riêng của mình, các vùng trong nước không được hưng thịnh như trước, không giống như dưới thời các vị vua trước kia sống đúng theo pháp hành cao quý của bậc Chuyển luân. ",
  "dn26:9.9": "Trong lãnh thổ của Đại vương hiện có các đại thần, quần thần, quan coi sổ sách, đại thần, các tướng lĩnh, quan giữ cửa, các cố vấn, cùng chúng tôi và những người khác là những người gìn giữ pháp hành cao quý của bậc Chuyển luân. ",
  "dn26:9.10": "Vậy xin Đại vương hãy hỏi chúng tôi về pháp hành cao quý của bậc Chuyển luân. ",
  "dn26:9.11": "Khi được Đại vương hỏi, chúng tôi sẽ trình bày pháp hành cao quý của bậc Chuyển luân ấy.’",
  "dn26:10.0": "4. Câu chuyện về sự suy giảm tuổi thọ, dung sắc v.v.",
  "dn26:10.1": "Rồi này các Tỳ-kheo, vị vua Sát-đế-lỵ đã làm lễ quán đảnh cho triệu tập các đại thần, quần thần, quan coi sổ sách, đại thần, các tướng lĩnh, quan giữ cửa và các cố vấn lại, rồi hỏi về pháp hành cao quý của bậc Chuyển luân. ",
  "dn26:10.2": "Khi được hỏi, họ trình bày pháp hành cao quý của bậc Chuyển luân ấy. ",
  "dn26:10.3": "Nghe họ nói xong, vị ấy có thiết lập sự che chở, bảo vệ, phòng hộ đúng pháp, nhưng lại không cấp tài sản cho những người nghèo. ",
  "dn26:10.4": "Khi tài sản không được cấp cho người nghèo, sự nghèo khổ tăng trưởng mạnh. ",
  "dn26:10.5": "Khi nghèo khổ tăng trưởng mạnh, có một người lấy của không cho của người khác, tức là trộm cắp. ",
  "dn26:10.6": "Người ta bắt người ấy. ",
  "dn26:10.7": "Bắt rồi dẫn đến trình vị vua Sát-đế-lỵ đã làm lễ quán đảnh:",
  "dn26:10.8": "‘Tâu Đại vương, người này đã lấy của không cho của người khác, tức là trộm cắp.’",
  "dn26:10.9": "Khi được nói vậy, này các Tỳ-kheo, vị vua Sát-đế-lỵ đã làm lễ quán đảnh nói với người ấy rằng:",
  "dn26:10.10": "‘Này người kia, có thật ngươi đã lấy của không cho của người khác, tức là trộm cắp chăng?’",
  "dn26:10.11": "‘Thưa thật, Đại vương.’",
  "dn26:10.12": "‘Vì lý do gì?’",
  "dn26:10.13": "‘Thưa Đại vương, vì tôi không sống nổi.’",
  "dn26:10.14": "Rồi này các Tỳ-kheo, vị vua Sát-đế-lỵ đã làm lễ quán đảnh cấp tài sản cho người ấy:",
  "dn26:10.15": "‘Này người kia, với số tài sản này, ngươi hãy nuôi sống bản thân, phụng dưỡng cha mẹ, nuôi dưỡng vợ con, đầu tư vào công việc làm ăn, và thiết lập sự cúng dường thù thắng đến các Sa-môn, Bà-la-môn, đem lại quả báo an lạc, dẫn đến cõi trời.’",
  "dn26:10.16": "‘Vâng, thưa Đại vương,’ này các Tỳ-kheo, người ấy vâng lời vị vua Sát-đế-lỵ đã làm lễ quán đảnh. ",
  "dn26:11.1": "Rồi này các Tỳ-kheo, lại có một người khác lấy của không cho của người khác, tức là trộm cắp. ",
  "dn26:11.2": "Người ta bắt người ấy. ",
  "dn26:11.3": "Bắt rồi dẫn đến trình vị vua Sát-đế-lỵ đã làm lễ quán đảnh:",
  "dn26:11.4": "‘Tâu Đại vương, người này đã lấy của không cho của người khác, tức là trộm cắp.’",
  "dn26:11.5": "Khi được nói vậy, này các Tỳ-kheo, vị vua Sát-đế-lỵ đã làm lễ quán đảnh nói với người ấy rằng:",
  "dn26:11.6": "‘Này người kia, có thật ngươi đã lấy của không cho của người khác, tức là trộm cắp chăng?’",
  "dn26:11.7": "‘Thưa thật, Đại vương.’",
  "dn26:11.8": "‘Vì lý do gì?’",
  "dn26:11.9": "‘Thưa Đại vương, vì tôi không sống nổi.’",
  "dn26:11.10": "Rồi này các Tỳ-kheo, vị vua Sát-đế-lỵ đã làm lễ quán đảnh cấp tài sản cho người ấy:",
  "dn26:11.11": "‘Này người kia, với số tài sản này, ngươi hãy nuôi sống bản thân, phụng dưỡng cha mẹ, nuôi dưỡng vợ con, đầu tư vào công việc làm ăn, và thiết lập sự cúng dường thù thắng đến các Sa-môn, Bà-la-môn, đem lại quả báo an lạc, dẫn đến cõi trời.’",
  "dn26:11.12": "‘Vâng, thưa Đại vương,’ này các Tỳ-kheo, người ấy vâng lời vị vua Sát-đế-lỵ đã làm lễ quán đảnh. ",
  "dn26:12.1": "Này các Tỳ-kheo, mọi người nghe rằng:",
  "dn26:12.2": "‘Này các ông, nghe nói những ai lấy của không cho của người khác, tức là trộm cắp, thì được vua cấp tài sản.’",
  "dn26:12.3": "Nghe vậy, họ nghĩ rằng:",
  "dn26:12.4": "‘Hay là chúng ta cũng lấy của không được cho của người khác, tức là trộm cắp.’",
  "dn26:12.5": "Rồi này các Tỳ-kheo, một người nào đó đã lấy của không được cho của người khác, tức là trộm cắp.",
  "dn26:12.6": "Người ta bắt được người ấy.",
  "dn26:12.7": "Bắt xong, họ dẫn đến trình vua Sát-đế-lỵ đã làm lễ quán đảnh:",
  "dn26:12.8": "‘Tâu đại vương, người này đã lấy của không được cho của người khác, tức là trộm cắp.’",
  "dn26:12.9": "Khi được nói vậy, này các Tỳ-kheo, vua Sát-đế-lỵ đã làm lễ quán đảnh nói với người ấy:",
  "dn26:12.10": "‘Này người kia, có thật ngươi đã lấy của không được cho của người khác, tức là trộm cắp chăng?’",
  "dn26:12.11": "‘Thật vậy, tâu đại vương.’",
  "dn26:12.12": "‘Vì lý do gì?’",
  "dn26:12.13": "‘Tâu đại vương, vì tôi không sống nổi.’",
  "dn26:12.14": "Rồi này các Tỳ-kheo, vua Sát-đế-lỵ đã làm lễ quán đảnh nghĩ rằng:",
  "dn26:12.15": "‘Nếu ta cứ ban tài sản cho bất cứ ai lấy của không được cho của người khác, tức là trộm cắp, thì như vậy nạn trộm cắp này sẽ gia tăng.",
  "dn26:12.16": "Hay là ta nên trừng trị nghiêm khắc người này, tiêu diệt tận gốc, chém đầu nó.’",
  "dn26:12.17": "Rồi này các Tỳ-kheo, vua Sát-đế-lỵ đã làm lễ quán đảnh ra lệnh cho người hầu:",
  "dn26:12.18": "‘Vậy thì này các ngươi, hãy trói chặt người này hai tay quặt ra sau bằng dây thừng chắc, cạo đầu bằng dao cạo, đánh trống vang rền, dẫn đi từ đường này sang đường khác, từ ngã tư này sang ngã tư khác, rồi đưa ra cửa nam, ở phía nam thành mà xử tử nghiêm khắc, tiêu diệt tận gốc, chém đầu nó.’",
  "dn26:12.19": "‘Vâng, tâu đại vương.’ Này các Tỳ-kheo, những người ấy vâng lệnh vua Sát-đế-lỵ đã làm lễ quán đảnh, trói chặt người ấy hai tay quặt ra sau bằng dây thừng chắc, cạo đầu bằng dao cạo, đánh trống vang rền, dẫn đi từ đường này sang đường khác, từ ngã tư này sang ngã tư khác, rồi đưa ra cửa nam, ở phía nam thành mà xử tử nghiêm khắc, tiêu diệt tận gốc, chém đầu người ấy.",
  "dn26:13.1": "Này các Tỳ-kheo, dân chúng nghe rằng:",
  "dn26:13.2": "‘Này các ông, những ai lấy của không được cho của người khác, tức là trộm cắp, thì vua xử tử nghiêm khắc, tiêu diệt tận gốc, chém đầu họ.’",
  "dn26:13.3": "Nghe vậy, họ nghĩ rằng:",
  "dn26:13.4": "‘Hay là chúng ta cũng cho làm những vũ khí sắc bén; sau khi cho làm những vũ khí sắc bén, những ai mà chúng ta sẽ lấy của không được cho, tức là trộm cắp, thì chúng ta sẽ xử tử nghiêm khắc họ, tiêu diệt tận gốc, chém đầu họ.’",
  "dn26:13.5": "Họ cho làm những vũ khí sắc bén; sau khi cho làm những vũ khí sắc bén, họ bắt đầu tàn sát cả làng mạc, bắt đầu tàn sát cả thị trấn, bắt đầu tàn sát cả thành phố, bắt đầu cướp bóc trên đường.",
  "dn26:13.6": "Những ai mà họ lấy của không được cho, tức là trộm cắp, thì họ xử tử nghiêm khắc, tiêu diệt tận gốc, chém đầu những người ấy.",
  "dn26:14.1": "Như vậy, này các Tỳ-kheo, khi tài sản không được cấp cho những người nghèo, thì nghèo đói tăng trưởng; khi nghèo đói tăng trưởng, trộm cắp tăng trưởng; khi trộm cắp tăng trưởng, vũ khí tăng trưởng; khi vũ khí tăng trưởng, sát sinh tăng trưởng; khi sát sinh tăng trưởng, thọ mạng của các chúng sinh ấy giảm sút, dung sắc cũng giảm sút.",
  "dn26:14.2": "Khi thọ mạng và dung sắc của họ giảm sút như vậy, thì con cháu của những người sống tám mươi ngàn năm chỉ còn sống bốn mươi ngàn năm.",
  "dn26:14.3": "Này các Tỳ-kheo, khi loài người sống bốn mươi ngàn năm, có một người nào đó lấy của không được cho của người khác, tức là trộm cắp.",
  "dn26:14.4": "Người ta bắt được người ấy.",
  "dn26:14.5": "Bắt xong, họ dẫn đến trình vua Sát-đế-lỵ đã làm lễ quán đảnh:",
  "dn26:14.6": "‘Tâu đại vương, người này đã lấy của không được cho của người khác, tức là trộm cắp.’",
  "dn26:14.7": "Khi được nói vậy, này các Tỳ-kheo, vua Sát-đế-lỵ đã làm lễ quán đảnh nói với người ấy:",
  "dn26:14.8": "‘Này người kia, có thật ngươi đã lấy của không được cho của người khác, tức là trộm cắp chăng?’",
  "dn26:14.9": "‘Không, tâu đại vương,’ người ấy cố ý nói dối.",
  "dn26:15.1": "Như vậy, này các Tỳ-kheo, khi tài sản không được cấp cho những người nghèo, thì nghèo đói tăng trưởng. Khi nghèo đói tăng trưởng, trộm cắp tăng trưởng; khi trộm cắp tăng trưởng, vũ khí tăng trưởng. Khi vũ khí tăng trưởng, sát sinh tăng trưởng; khi sát sinh tăng trưởng, nói dối tăng trưởng; khi nói dối tăng trưởng, thọ mạng của các chúng sinh ấy giảm sút, dung sắc cũng giảm sút.",
  "dn26:15.2": "Khi thọ mạng và dung sắc của họ giảm sút như vậy, thì con cháu của những người sống bốn mươi ngàn năm chỉ còn sống hai mươi ngàn năm.",
  "dn26:15.3": "Này các Tỳ-kheo, khi loài người sống hai mươi ngàn năm, có một người nào đó lấy của không được cho của người khác, tức là trộm cắp.",
  "dn26:15.4": "Một người khác tố cáo người ấy với vua Sát-đế-lỵ đã làm lễ quán đảnh:",
  "dn26:15.5": "‘Tâu đại vương, người tên như thế này đã lấy của không được cho của người khác, tức là trộm cắp,’ và đã nói lời ly gián.",
  "dn26:16.1": "Như vậy, này các Tỳ-kheo, khi tài sản không được cấp cho những người nghèo, thì nghèo đói tăng trưởng. Khi nghèo đói tăng trưởng, trộm cắp tăng trưởng; khi trộm cắp tăng trưởng, vũ khí tăng trưởng; khi vũ khí tăng trưởng, sát sinh tăng trưởng; khi sát sinh tăng trưởng, nói dối tăng trưởng; khi nói dối tăng trưởng, nói lời ly gián tăng trưởng; khi nói lời ly gián tăng trưởng, thọ mạng của các chúng sinh ấy giảm sút, dung sắc cũng giảm sút.",
  "dn26:16.2": "Khi thọ mạng và dung sắc của họ giảm sút như vậy, thì con cháu của những người sống hai mươi ngàn năm chỉ còn sống mười ngàn năm.",
  "dn26:17.1": "Này các Tỳ-kheo, khi loài người sống mười ngàn năm, có lúc chúng sinh đẹp đẽ, có lúc chúng sinh xấu xí.",
  "dn26:17.2": "Trong đó, những chúng sinh xấu xí ganh ghét những chúng sinh đẹp đẽ, nên phạm vào tà hạnh với vợ người khác.",
  "dn26:17.3": "Như vậy, này các Tỳ-kheo, khi tài sản không được cấp cho những người nghèo, thì nghèo đói tăng trưởng. Khi nghèo đói tăng trưởng … tà hạnh trong các dục tăng trưởng; khi tà hạnh trong các dục tăng trưởng, thọ mạng của các chúng sinh ấy giảm sút, dung sắc cũng giảm sút.",
  "dn26:17.4": "Khi thọ mạng và dung sắc của họ giảm sút như vậy, thì con cháu của những người sống mười ngàn năm chỉ còn sống năm ngàn năm.",
  "dn26:17.5": "Này các Tỳ-kheo, khi loài người sống năm ngàn năm, có hai pháp tăng trưởng—",
  "dn26:17.6": "ác khẩu và nói lời phù phiếm.",
  "dn26:17.7": "Khi hai pháp ấy tăng trưởng, thọ mạng của các chúng sinh ấy giảm sút, dung sắc cũng giảm sút.",
  "dn26:17.8": "Khi thọ mạng và dung sắc của họ giảm sút như vậy, thì con cháu của những người sống năm ngàn năm, có hạng sống hai ngàn năm trăm năm, có hạng sống hai ngàn năm.",
  "dn26:17.9": "Này các Tỳ-kheo, khi loài người sống hai ngàn năm trăm năm, tham lam và sân hận tăng trưởng.",
  "dn26:17.10": "Khi tham lam và sân hận tăng trưởng, thọ mạng của các chúng sinh ấy giảm sút, dung sắc cũng giảm sút.",
  "dn26:17.11": "Khi thọ mạng và dung sắc của họ giảm sút như vậy, thì con cháu của những người sống hai ngàn năm trăm năm chỉ còn sống một ngàn năm.",
  "dn26:17.12": "Này các Tỳ-kheo, khi loài người sống một ngàn năm, tà kiến tăng trưởng.",
  "dn26:17.13": "Khi tà kiến tăng trưởng, thọ mạng của những chúng sinh ấy giảm sút, dung sắc cũng giảm sút.",
  "dn26:17.14": "Khi thọ mạng của họ giảm sút, dung sắc của họ giảm sút, thì những người sống một ngàn năm sinh ra những người con sống năm trăm năm.",
  "dn26:17.15": "Này các Tỳ-kheo, khi loài người sống năm trăm năm, có ba pháp tăng trưởng—",
  "dn26:17.16": "dục vọng phi pháp, tham lam bất chính, phi pháp tà vạy.",
  "dn26:17.17": "Khi ba pháp ấy tăng trưởng, thọ mạng của những chúng sinh ấy giảm sút, dung sắc cũng giảm sút.",
  "dn26:17.18": "Khi thọ mạng của họ giảm sút, dung sắc của họ giảm sút, thì trong những người sống năm trăm năm, có người sinh con sống hai trăm năm mươi năm, có người sinh con sống hai trăm năm.",
  "dn26:17.19": "Này các Tỳ-kheo, khi loài người sống hai trăm năm mươi năm, những pháp này tăng trưởng.",
  "dn26:17.20": "Không kính mẹ, không kính cha, không kính Sa-môn, không kính Bà-la-môn, không tôn trọng bậc trưởng thượng trong gia tộc.",
  "dn26:18.1": "Như vậy, này các Tỳ-kheo, khi của cải không được cấp cho người nghèo, thì nghèo đói tăng trưởng.",
  "dn26:18.2": "Khi nghèo đói tăng trưởng, trộm cắp tăng trưởng.",
  "dn26:18.3": "Khi trộm cắp tăng trưởng, gươm giáo tăng trưởng.",
  "dn26:18.4": "Khi gươm giáo tăng trưởng, sát sinh tăng trưởng.",
  "dn26:18.5": "Khi sát sinh tăng trưởng, nói dối tăng trưởng.",
  "dn26:18.6": "Khi nói dối tăng trưởng, nói hai lưỡi tăng trưởng.",
  "dn26:18.7": "Khi nói hai lưỡi tăng trưởng, tà hạnh trong các dục tăng trưởng.",
  "dn26:18.8": "Khi tà hạnh trong các dục tăng trưởng, hai pháp tăng trưởng: lời nói thô ác và nói nhảm.",
  "dn26:18.9": "Khi hai pháp ấy tăng trưởng, tham lam và sân hận tăng trưởng.",
  "dn26:18.10": "Khi tham lam và sân hận tăng trưởng, tà kiến tăng trưởng.",
  "dn26:18.11": "Khi tà kiến tăng trưởng, ba pháp tăng trưởng: dục vọng phi pháp, tham lam bất chính, phi pháp tà vạy.",
  "dn26:18.12": "Khi ba pháp ấy tăng trưởng, những pháp này tăng trưởng: không kính mẹ, không kính cha, không kính Sa-môn, không kính Bà-la-môn, không tôn trọng bậc trưởng thượng trong gia tộc.",
  "dn26:18.13": "Khi những pháp ấy tăng trưởng, thọ mạng của những chúng sinh ấy giảm sút, dung sắc cũng giảm sút.",
  "dn26:18.14": "Khi thọ mạng của họ giảm sút, dung sắc của họ giảm sút, thì những người sống hai trăm năm mươi năm sinh ra những người con sống một trăm năm.",
  "dn26:19.0": "5. Thời kỳ sống mười năm",
  "dn26:19.1": "Này các Tỳ-kheo, sẽ có một thời mà con cái của những người này sẽ sống mười năm.",
  "dn26:19.2": "Này các Tỳ-kheo, khi loài người sống mười năm, các bé gái năm tuổi sẽ có thể lấy chồng.",
  "dn26:19.3": "Này các Tỳ-kheo, khi loài người sống mười năm, những vị ngon này sẽ biến mất, đó là—",
  "dn26:19.4": "bơ sữa, bơ tươi, dầu, mật, đường mía, muối.",
  "dn26:19.5": "Này các Tỳ-kheo, khi loài người sống mười năm, kê dại sẽ là món ăn thượng hạng.",
  "dn26:19.6": "Này các Tỳ-kheo, cũng như hiện nay cơm gạo ngon với thịt là món ăn thượng hạng;",
  "dn26:19.7": "cũng vậy, này các Tỳ-kheo, khi loài người sống mười năm, kê dại sẽ là món ăn thượng hạng.",
  "dn26:19.8": "Này các Tỳ-kheo, khi loài người sống mười năm, mười thiện nghiệp đạo sẽ hoàn toàn biến mất, còn mười ác nghiệp đạo sẽ cực kỳ lan tràn.",
  "dn26:19.9": "Này các Tỳ-kheo, khi loài người sống mười năm, đến cả điều thiện cũng sẽ không có, huống nữa là người làm điều thiện.",
  "dn26:19.10": "Này các Tỳ-kheo, khi loài người sống mười năm, những ai không kính mẹ, không kính cha, không kính Sa-môn, không kính Bà-la-môn, không tôn trọng bậc trưởng thượng trong gia tộc, những người ấy sẽ được tôn kính và ca ngợi.",
  "dn26:19.11": "Này các Tỳ-kheo, cũng như hiện nay những ai kính mẹ, kính cha, kính Sa-môn, kính Bà-la-môn, tôn trọng bậc trưởng thượng trong gia tộc thì được tôn kính và ca ngợi;",
  "dn26:19.12": "cũng vậy, này các Tỳ-kheo, khi loài người sống mười năm, những ai không kính mẹ, không kính cha, không kính Sa-môn, không kính Bà-la-môn, không tôn trọng bậc trưởng thượng trong gia tộc, những người ấy sẽ được tôn kính và ca ngợi.",
  "dn26:20.1": "Này các Tỳ-kheo, khi loài người sống mười năm, sẽ không còn phân biệt đây là mẹ, đây là dì, đây là vợ của cậu, đây là vợ của thầy, đây là vợ của bậc đáng kính.",
  "dn26:20.2": "Thế gian sẽ đi đến chỗ hỗn loạn như dê cừu, gà, heo, chó và chó rừng.",
  "dn26:20.3": "Này các Tỳ-kheo, khi loài người sống mười năm, giữa những chúng sinh ấy sẽ khởi lên sự oán hận dữ dội đối với nhau, sân hận dữ dội, tâm ác dữ dội, ý muốn giết hại dữ dội.",
  "dn26:20.4": "Mẹ đối với con, con đối với mẹ;",
  "dn26:20.5": "cha đối với con, con đối với cha;",
  "dn26:20.6": "anh đối với em gái, em gái đối với anh, sẽ khởi lên sự oán hận dữ dội, sân hận dữ dội, tâm ác dữ dội, ý muốn giết hại dữ dội.",
  "dn26:20.7": "Này các Tỳ-kheo, cũng như người thợ săn khi thấy con nai thì khởi lên sự oán hận dữ dội, sân hận dữ dội, tâm ác dữ dội, ý muốn giết hại dữ dội;",
  "dn26:20.8": "cũng vậy, này các Tỳ-kheo, khi loài người sống mười năm, giữa những chúng sinh ấy sẽ khởi lên sự oán hận dữ dội đối với nhau, sân hận dữ dội, tâm ác dữ dội, ý muốn giết hại dữ dội.",
  "dn26:20.9": "Mẹ đối với con, con đối với mẹ;",
  "dn26:20.10": "cha đối với con, con đối với cha;",
  "dn26:20.11": "anh đối với em gái, em gái đối với anh, sẽ khởi lên sự oán hận dữ dội, sân hận dữ dội, tâm ác dữ dội, ý muốn giết hại dữ dội.",
  "dn26:21.1": "Này các Tỳ-kheo, khi loài người sống mười năm, sẽ có thời kỳ bảy ngày gươm giáo nổi lên.",
  "dn26:21.2": "Họ sẽ nhận nhau như thú rừng.",
  "dn26:21.3": "Những vũ khí bén nhọn sẽ hiện ra trong tay họ.",
  "dn26:21.4": "Họ sẽ dùng vũ khí bén nhọn ấy mà giết hại lẫn nhau, nghĩ rằng: ‘Đây là thú, đây là thú.’",
  "dn26:21.5": "Rồi này các Tỳ-kheo, khi ấy một số chúng sinh sẽ nghĩ như sau:",
  "dn26:21.6": "‘Chớ để chúng ta giết ai, và chớ để ai giết chúng ta. Hay là chúng ta đi vào bụi cỏ rậm, hoặc rừng rậm, hoặc lùm cây rậm, hoặc nơi hiểm trở bên sông, hoặc chỗ núi non gồ ghề, rồi sống bằng rễ và trái cây trong rừng.’",
  "dn26:21.7": "Họ đi vào bụi cỏ rậm, hoặc rừng rậm, hoặc lùm cây rậm, hoặc nơi hiểm trở bên sông, hoặc chỗ núi non gồ ghề, và sẽ sống bằng rễ và trái cây trong rừng suốt bảy ngày.",
  "dn26:21.8": "Sau khi bảy ngày ấy trôi qua, họ từ bụi cỏ rậm, rừng rậm, lùm cây rậm, nơi hiểm trở bên sông, chỗ núi non gồ ghề đi ra, ôm lấy nhau, cùng cất tiếng vui mừng và an ủi nhau:",
  "dn26:21.9": "‘Này bạn, còn thấy anh sống; này bạn, còn thấy anh sống!’",
  "dn26:21.10.0": "6. Bàn về sự tăng trưởng tuổi thọ và dung sắc",
  "dn26:21.11": "Rồi này các Tỳ-kheo, những chúng sinh ấy sẽ nghĩ như sau:",
  "dn26:21.12": "‘Chính vì chấp nhận các pháp bất thiện mà chúng ta đã rơi vào sự diệt vong lâu dài của bà con thân thuộc như vậy.",
  "dn26:21.13": "Hay là chúng ta làm điều thiện.",
  "dn26:21.14": "Chúng ta nên làm điều thiện gì?",
  "dn26:21.15": "Hay là chúng ta từ bỏ sát sinh, thọ trì và sống theo pháp thiện này.’",
  "dn26:21.16": "Họ sẽ từ bỏ sát sinh, thọ trì và sống theo pháp thiện này.",
  "dn26:21.17": "Do thọ trì các pháp thiện, họ sẽ tăng trưởng cả về tuổi thọ lẫn dung sắc.",
  "dn26:21.18": "Khi họ tăng trưởng cả về tuổi thọ lẫn dung sắc, thì những người sống mười năm sẽ có con sống hai mươi năm.",
  "dn26:22.1": "Rồi này các Tỳ-kheo, những chúng sinh ấy sẽ nghĩ như sau:",
  "dn26:22.2": "‘Do thọ trì các pháp thiện, chúng ta tăng trưởng cả về tuổi thọ lẫn dung sắc.",
  "dn26:22.3": "Hay là chúng ta làm điều thiện nhiều hơn nữa.",
  "dn26:22.4": "Chúng ta nên làm điều thiện gì?",
  "dn26:22.5": "Hay là chúng ta từ bỏ lấy của không cho…",
  "dn26:22.6": "từ bỏ tà hạnh trong các dục…",
  "dn26:22.7": "từ bỏ nói dối…",
  "dn26:22.8": "từ bỏ nói lời chia rẽ…",
  "dn26:22.9": "từ bỏ nói lời thô ác…",
  "dn26:22.10": "từ bỏ nói lời phù phiếm…",
  "dn26:22.11": "từ bỏ tham lam…",
  "dn26:22.12": "từ bỏ sân hận…",
  "dn26:22.13": "từ bỏ tà kiến…",
  "dn26:22.14": "từ bỏ ba pháp—",
  "dn26:22.15": "dục tham phi pháp, lòng tham bất chính, phi pháp tà vạy…",
  "dn26:22.16": "hay là chúng ta hiếu kính mẹ, hiếu kính cha, kính trọng sa-môn, kính trọng bà-la-môn, tôn kính các bậc trưởng thượng trong gia tộc, thọ trì và sống theo pháp thiện này.’",
  "dn26:22.17": "Họ sẽ hiếu kính mẹ, hiếu kính cha, kính trọng sa-môn, kính trọng bà-la-môn, tôn kính các bậc trưởng thượng trong gia tộc, thọ trì và sống theo pháp thiện này.",
  "dn26:22.18": "Do thọ trì các pháp thiện, họ sẽ tăng trưởng cả về tuổi thọ lẫn dung sắc.",
  "dn26:22.19": "Khi họ tăng trưởng cả về tuổi thọ lẫn dung sắc, thì những người sống hai mươi năm sẽ có con sống bốn mươi năm…",
  "dn26:22.20": "những người sống bốn mươi năm sẽ có con sống tám mươi năm…",
  "dn26:22.21": "những người sống tám mươi năm sẽ có con sống một trăm sáu mươi năm…",
  "dn26:22.22": "những người sống một trăm sáu mươi năm sẽ có con sống ba trăm hai mươi năm…",
  "dn26:22.23": "những người sống ba trăm hai mươi năm sẽ có con sống sáu trăm bốn mươi năm.",
  "dn26:22.24": "Những người sống sáu trăm bốn mươi năm sẽ có con sống hai ngàn năm…",
  "dn26:22.25": "những người sống hai ngàn năm sẽ có con sống bốn ngàn năm…",
  "dn26:22.26": "những người sống bốn ngàn năm sẽ có con sống tám ngàn năm…",
  "dn26:22.27": "những người sống tám ngàn năm sẽ có con sống hai mươi ngàn năm…",
  "dn26:23.1": "những người sống hai mươi ngàn năm sẽ có con sống bốn mươi ngàn năm…",
  "dn26:23.2": "những người sống bốn mươi ngàn năm sẽ có con sống tám mươi ngàn năm…",
  "dn26:23.3": "Này các Tỳ-kheo, khi loài người sống tám mươi ngàn năm, thì các thiếu nữ mới năm trăm tuổi đã có thể lấy chồng.",
  "dn26:23.4.0": "7. Sự xuất hiện của vua Saṅkha",
  "dn26:23.5": "Này các Tỳ-kheo, khi loài người sống tám mươi ngàn năm, sẽ chỉ có ba thứ bệnh: ham muốn, đói khát và già yếu.",
  "dn26:23.6": "Này các Tỳ-kheo, khi loài người sống tám mươi ngàn năm, cõi Diêm-phù-đề này sẽ hưng thịnh và phồn vinh, làng mạc, thị trấn và kinh đô ở gần nhau đến mức gà có thể bay từ nơi này sang nơi kia.",
  "dn26:23.7": "Này các Tỳ-kheo, khi loài người sống tám mươi ngàn năm, cõi Diêm-phù-đề này sẽ dày đặc người ở khắp nơi, như thể một rừng lau hay một rừng sậy.",
  "dn26:23.8": "Này các Tỳ-kheo, khi loài người sống tám mươi ngàn năm, thành Ba-la-nại sẽ là kinh đô tên là Ketumatī, hưng thịnh, phồn vinh, đông dân, chật kín người và sung túc.",
  "dn26:23.9": "Này các Tỳ-kheo, khi loài người sống tám mươi ngàn năm, trong cõi Diêm-phù-đề này sẽ có tám mươi bốn ngàn thành phố, lấy kinh đô Ketumatī làm đứng đầu.",
  "dn26:24.1": "Này các Tỳ-kheo, khi loài người có tuổi thọ tám mươi ngàn năm, tại kinh đô Ketumatī sẽ xuất hiện một vị vua tên là Saṅkha, bậc Chuyển luân vương, trị vì đúng pháp, là Pháp vương, chinh phục bốn phương, thống nhất quốc độ, đầy đủ bảy báu.",
  "dn26:24.2": "Bảy báu ấy sẽ là như sau:",
  "dn26:24.3": "luân bảo, tượng bảo, mã bảo, ngọc bảo, nữ bảo, gia chủ bảo, và báu thứ bảy là tướng quân bảo.",
  "dn26:24.4": "Lại nữa, vị ấy sẽ có hơn một ngàn người con, dũng mãnh, anh hùng, hình dung oai vệ, có khả năng nghiền nát quân địch.",
  "dn26:24.5": "Vị ấy sẽ chinh phục và cai trị quả đất này cho đến tận bờ biển bằng chánh pháp, không dùng gậy gộc, không dùng đao kiếm.",
  "dn26:25.0": "8. Sự xuất hiện của đức Phật Metteyya",
  "dn26:25.1": "Này các Tỳ-kheo, khi loài người có tuổi thọ tám mươi ngàn năm, một đức Thế Tôn tên là Metteyya sẽ xuất hiện ở đời, là bậc A-la-hán, Chánh Đẳng Giác, đầy đủ minh và hạnh, Thiện Thệ, bậc hiểu biết thế gian, bậc Vô thượng Điều Ngự Trượng Phu, bậc Đạo Sư của chư thiên và loài người, là Phật, là Thế Tôn.",
  "dn26:25.2": "Cũng như nay Ta xuất hiện ở đời, là bậc A-la-hán, Chánh Đẳng Giác, đầy đủ minh và hạnh, Thiện Thệ, bậc hiểu biết thế gian, bậc Vô thượng Điều Ngự Trượng Phu, bậc Đạo Sư của chư thiên và loài người, là Phật, là Thế Tôn.",
  "dn26:25.3": "Vị ấy sẽ tự mình chứng ngộ với thắng trí rồi tuyên thuyết thế giới này cùng với chư thiên, Ma vương, Phạm thiên, cùng quần sinh gồm sa-môn, bà-la-môn, chư thiên và loài người; cũng như nay Ta tự mình chứng ngộ với thắng trí rồi tuyên thuyết thế giới này cùng với chư thiên, Ma vương, Phạm thiên, cùng quần sinh gồm sa-môn, bà-la-môn, chư thiên và loài người.",
  "dn26:25.4": "Vị ấy sẽ thuyết pháp thiện ở đoạn đầu, thiện ở đoạn giữa, thiện ở đoạn cuối, đầy đủ ý nghĩa, đầy đủ văn cú, và sẽ chỉ bày phạm hạnh hoàn toàn viên mãn, thanh tịnh.",
  "dn26:25.5": "Cũng như nay Ta thuyết pháp thiện ở đoạn đầu, thiện ở đoạn giữa, thiện ở đoạn cuối, đầy đủ ý nghĩa, đầy đủ văn cú, và chỉ bày phạm hạnh hoàn toàn viên mãn, thanh tịnh.",
  "dn26:25.6": "Vị ấy sẽ nhiếp hộ một Tăng đoàn Tỳ-kheo gồm nhiều ngàn vị, cũng như nay Ta nhiếp hộ một Tăng đoàn Tỳ-kheo gồm nhiều trăm vị.",
  "dn26:26.1": "Rồi này các Tỳ-kheo, vua tên Saṅkha ấy, đối với cây tế đàn do vua Mahāpanāda cho dựng lên,",
  "dn26:26.2": "sau khi cho dựng cây tế đàn ấy lên, cư ngụ trong đó, rồi đem bố thí và xả bỏ nó, ban tặng các vật thí cho các sa-môn, bà-la-môn, người nghèo khổ, lữ khách, người xin ăn; rồi đến trước đức Thế Tôn Metteyya, bậc A-la-hán, Chánh Đẳng Giác, cạo bỏ râu tóc, khoác y ca-sa, từ bỏ gia đình, xuất gia sống không gia đình.",
  "dn26:26.3": "Sau khi xuất gia như vậy, sống một mình, viễn ly, không phóng dật, nhiệt tâm, tinh cần, chẳng bao lâu vị ấy sẽ tự mình với thắng trí chứng ngộ, chứng đạt và an trú ngay trong hiện tại cứu cánh vô thượng của phạm hạnh, vì mục đích ấy mà các thiện nam tử chân chánh từ bỏ gia đình, xuất gia sống không gia đình.",
  "dn26:27.1": "Này các Tỳ-kheo, hãy sống tự mình là hòn đảo cho mình, tự mình là chỗ nương tựa cho mình, không nương tựa một gì khác; lấy Pháp làm hòn đảo, lấy Pháp làm chỗ nương tựa, không nương tựa một gì khác.",
  "dn26:27.2": "Và này các Tỳ-kheo, thế nào là một Tỳ-kheo sống tự mình là hòn đảo cho mình, tự mình là chỗ nương tựa cho mình, không nương tựa một gì khác; lấy Pháp làm hòn đảo, lấy Pháp làm chỗ nương tựa, không nương tựa một gì khác?",
  "dn26:27.3": "Ở đây, này các Tỳ-kheo, một Tỳ-kheo sống quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời.",
  "dn26:27.4": "Quán thọ trên các cảm thọ …",
  "dn26:27.5": "quán tâm trên tâm …",
  "dn26:27.6": "quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời.",
  "dn26:27.7": "Như vậy, này các Tỳ-kheo, một Tỳ-kheo sống tự mình là hòn đảo cho mình, tự mình là chỗ nương tựa cho mình, không nương tựa một gì khác; lấy Pháp làm hòn đảo, lấy Pháp làm chỗ nương tựa, không nương tựa một gì khác.",
  "dn26:28.0": "9. Lời dạy về sự tăng trưởng tuổi thọ, dung sắc v.v. của Tỳ-kheo",
  "dn26:28.1": "Này các Tỳ-kheo, hãy hành trì trong cảnh giới của mình, trong lãnh vực của tổ phụ mình.",
  "dn26:28.2": "Này các Tỳ-kheo, khi hành trì trong cảnh giới của mình, trong lãnh vực của tổ phụ mình, các ông sẽ tăng trưởng về tuổi thọ, tăng trưởng về dung sắc, tăng trưởng về an lạc, tăng trưởng về tài sản, tăng trưởng về sức mạnh.",
  "dn26:28.3": "Và này các Tỳ-kheo, thế nào là sự tăng trưởng tuổi thọ của một Tỳ-kheo?",
  "dn26:28.4": "Ở đây, này các Tỳ-kheo, một Tỳ-kheo tu tập thần túc có định do dục, cùng với các hành tinh tấn,",
  "dn26:28.5": "tu tập thần túc có định do tinh tấn, cùng với các hành tinh tấn,",
  "dn26:28.6": "tu tập thần túc có định do tâm, cùng với các hành tinh tấn,",
  "dn26:28.7": "tu tập thần túc có định do quán sát, cùng với các hành tinh tấn.",
  "dn26:28.8": "Do bốn thần túc này được tu tập, được làm cho sung mãn, nếu muốn, vị ấy có thể sống trọn một kiếp hay phần còn lại của một kiếp.",
  "dn26:28.9": "Đó, này các Tỳ-kheo, là sự tăng trưởng tuổi thọ của một Tỳ-kheo.",
  "dn26:28.10": "Và này các Tỳ-kheo, thế nào là sự tăng trưởng dung sắc của một Tỳ-kheo?",
  "dn26:28.11": "Ở đây, này các Tỳ-kheo, một Tỳ-kheo có giới, sống được chế ngự bởi sự chế ngự của giới bổn Pātimokkha, đầy đủ oai nghi và chánh hạnh, thấy sợ hãi trong những lỗi nhỏ nhặt, thọ trì và học tập trong các học giới.",
  "dn26:28.12": "Đó, này các Tỳ-kheo, là sự tăng trưởng dung sắc của một Tỳ-kheo.",
  "dn26:28.13": "Và này các Tỳ-kheo, thế nào là sự tăng trưởng an lạc của một Tỳ-kheo?",
  "dn26:28.14": "Ở đây, này các Tỳ-kheo, một Tỳ-kheo ly dục, ly các pháp bất thiện, chứng và an trú sơ thiền, một trạng thái hỷ lạc do viễn ly sanh, có tầm có tứ.",
  "dn26:28.15": "Do sự lắng dịu của tầm và tứ … nhị thiền …",
  "dn26:28.16": "tam thiền …",
  "dn26:28.17": "chứng và an trú tứ thiền.",
  "dn26:28.18": "Đó, này các Tỳ-kheo, là sự tăng trưởng an lạc của một Tỳ-kheo.",
  "dn26:28.19": "Và này các Tỳ-kheo, thế nào là sự tăng trưởng tài sản của một Tỳ-kheo?",
  "dn26:28.20": "Ở đây, này các Tỳ-kheo, một Tỳ-kheo an trú biến mãn một phương với tâm câu hữu với từ; cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư. Như vậy, trên, dưới, ngang, khắp mọi nơi, đối với tất cả như đối với chính mình, vị ấy an trú biến mãn toàn thế giới với tâm câu hữu với từ, rộng lớn, cao thượng, vô lượng, không oán, không hại.",
  "dn26:28.21": "Với tâm câu hữu với bi …",
  "dn26:28.22": "với tâm câu hữu với hỷ …",
  "dn26:28.23": "với tâm câu hữu với xả, vị ấy an trú biến mãn một phương; cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư. Như vậy, trên, dưới, ngang, khắp mọi nơi, đối với tất cả như đối với chính mình, vị ấy an trú biến mãn toàn thế giới với tâm câu hữu với xả, rộng lớn, cao thượng, vô lượng, không oán, không hại.",
  "dn26:28.24": "Đó, này các Tỳ-kheo, là sự tăng trưởng tài sản của một Tỳ-kheo.",
  "dn26:28.25": "Và này các Tỳ-kheo, thế nào là sự tăng trưởng sức mạnh của một Tỳ-kheo?",
  "dn26:28.26": "Ở đây, này các Tỳ-kheo, một Tỳ-kheo do đoạn tận các lậu hoặc, tự mình với thắng trí chứng ngộ, chứng đạt và an trú ngay trong hiện tại tâm giải thoát, tuệ giải thoát không còn lậu hoặc.",
  "dn26:28.27": "Đó, này các Tỳ-kheo, là sự tăng trưởng sức mạnh của một Tỳ-kheo.",
  "dn26:28.28": "Này các Tỳ-kheo, Ta không thấy một thế lực nào khác, dù chỉ một, lại khó chống cự như thế lực của Ma vương này.",
  "dn26:28.29": "Này các Tỳ-kheo, chính vì thọ trì các pháp thiện mà công đức này được tăng trưởng như vậy.",
  "dn26:28.30": "Thế Tôn đã nói như vậy.",
  "dn26:28.31": "Các Tỳ-kheo ấy hoan hỷ tín thọ lời Thế Tôn dạy.",
  "dn26:28.32": "Kinh Chuyển Luân Vương thứ ba đã chấm dứt."
}
window.BILARA["dn26"]["vi"]["dn26:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
