window.BILARA = window.BILARA || {};
window.BILARA["dn29"] = window.BILARA["dn29"] || {};
window.BILARA["dn29"]["vi"] = {
  "dn29:0.1": "Trường Bộ Kinh 29 ",
  "dn29:0.2": "Kinh Hoan Hỷ ",
  "dn29:1.1": "Tôi nghe như vầy—",
  "dn29:1.2": "Một thời, Thế Tôn sống giữa dân Sakya, tại Vedhaññā của người Sakya, trong tòa nhà ở vườn xoài của họ. ",
  "dn29:1.3": "Lúc bấy giờ, Ni-kiền-tử Nāṭaputta vừa mới qua đời tại Pāvā. ",
  "dn29:1.4": "Sau khi ông ta chết, các Ni-kiền-tử bị chia rẽ, thành hai phe, sinh chuyện cãi vã, sinh chuyện tranh chấp, rơi vào tranh luận, dùng lời lẽ sắc bén công kích lẫn nhau: ",
  "dn29:1.5": "“Anh không hiểu pháp và luật này, tôi mới hiểu pháp và luật này. Làm sao anh có thể hiểu pháp và luật này được? Anh thực hành sai, tôi thực hành đúng. Lời tôi ăn khớp, lời anh không ăn khớp. Điều nên nói trước thì anh lại nói sau, điều nên nói sau thì anh lại nói trước. Điều anh suy tính kỹ đã bị đảo lộn. Lập luận của anh đã bị bác bỏ. Anh đã bị bắt lỗi rồi. Hãy đi mà gỡ thế bí trong tranh luận đi, hoặc tự giải thích đi nếu làm nổi.” ",
  "dn29:1.6": "Tôi nghĩ rằng giữa các Ni-kiền-tử, đệ tử của Nāṭaputta, chỉ toàn là cảnh công kích nhau. ",
  "dn29:1.7": "Ngay cả những đệ tử tại gia của Ni-kiền-tử Nāṭaputta, mặc y trắng, cũng chán ngán, nguội lạnh, quay lưng với các Ni-kiền-tử, đệ tử của Nāṭaputta, vì pháp và luật được giảng dạy tệ hại, trình bày không khéo, không đưa đến giải thoát, không đưa đến lắng dịu, không phải do bậc Giác Ngộ chân chánh tuyên thuyết, đã bị chia rẽ, không còn chỗ nương tựa. ",
  "dn29:2.1": "Bấy giờ, sa-di Cunda sau khi an cư mùa mưa ở Pāvā xong, đi đến Sāmagāma, đến gặp tôn giả Ānanda; đến nơi, đảnh lễ tôn giả Ānanda rồi ngồi xuống một bên. Ngồi xuống một bên, sa-di Cunda nói với tôn giả Ānanda: ",
  "dn29:2.2": "“Bạch ngài, Ni-kiền-tử Nāṭaputta vừa mới qua đời tại Pāvā. ",
  "dn29:2.3": "Sau khi ông ta chết, các Ni-kiền-tử bị chia rẽ, thành hai phe … đã bị chia rẽ, không còn chỗ nương tựa.”",
  "dn29:2.4": "Khi được nói vậy, tôn giả Ānanda nói với sa-di Cunda: ",
  "dn29:2.5": "“Này hiền giả Cunda, đây là một câu chuyện đáng đem đến trình lên Thế Tôn. ",
  "dn29:2.6": "Nào, hiền giả Cunda, chúng ta hãy đi đến gặp Thế Tôn; đến rồi, chúng ta sẽ trình việc này lên Thế Tôn.”",
  "dn29:2.7": "“Vâng, bạch ngài,” sa-di Cunda đáp lời tôn giả Ānanda. ",
  "dn29:3.1": "Rồi tôn giả Ānanda và sa-di Cunda đi đến gặp Thế Tôn; đến nơi, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, tôn giả Ānanda thưa với Thế Tôn: ",
  "dn29:3.2": "“Bạch Thế Tôn, sa-di Cunda này đã nói như sau: ‘Bạch ngài, Ni-kiền-tử Nāṭaputta vừa mới qua đời tại Pāvā, ",
  "dn29:3.3": "sau khi ông ta chết, các Ni-kiền-tử bị chia rẽ … đã bị chia rẽ, không còn chỗ nương tựa.’”",
  "dn29:4.0": "1. Pháp và luật do người không phải bậc Giác Ngộ chân chánh tuyên thuyết ",
  "dn29:4.1": "“Đúng vậy, Cunda, đó là điều xảy ra khi pháp và luật được giảng dạy tệ hại, trình bày không khéo, không đưa đến giải thoát, không đưa đến lắng dịu, do người không phải bậc Giác Ngộ chân chánh tuyên thuyết. ",
  "dn29:4.2": "Ở đây, này Cunda, có vị thầy không phải bậc Giác Ngộ chân chánh, và pháp được giảng dạy tệ hại, trình bày không khéo, không đưa đến giải thoát, không đưa đến lắng dịu, do người không phải bậc Giác Ngộ chân chánh tuyên thuyết, ",
  "dn29:4.3": "và đệ tử trong pháp ấy lại không sống thực hành đúng theo pháp, không thực hành thích hợp, không sống thuận theo pháp, mà còn đi lệch khỏi pháp ấy. ",
  "dn29:4.4": "Người ấy nên được nói như sau: ",
  "dn29:4.5": "‘Này hiền giả, thật là điều bất hạnh cho ông, thật là điều ông nhận được không khéo, ",
  "dn29:4.6": "vì thầy của ông không phải bậc Giác Ngộ chân chánh, và pháp được giảng dạy tệ hại, trình bày không khéo, không đưa đến giải thoát, không đưa đến lắng dịu, do người không phải bậc Giác Ngộ chân chánh tuyên thuyết. ",
  "dn29:4.7": "Vậy mà ông lại không sống thực hành đúng theo pháp ấy, không thực hành thích hợp, không sống thuận theo pháp, còn đi lệch khỏi pháp ấy.’ ",
  "dn29:4.8": "Như vậy, này Cunda, ở đó vị thầy đáng bị chê trách, pháp cũng đáng bị chê trách, và đệ tử cũng đáng bị chê trách như thế. ",
  "dn29:4.9": "Này Cunda, nếu ai nói với một đệ tử như vậy rằng: ",
  "dn29:4.10": "‘Mong tôn giả cứ thực hành như vậy, đúng như pháp mà thầy của ông đã dạy và đặt ra,’ ",
  "dn29:4.11": "người khuyên, điều được khuyên, và người đã được khuyên rồi thực hành theo như thế, tất cả đều tạo ra nhiều điều không lành. ",
  "dn29:4.12": "Vì sao vậy? ",
  "dn29:4.13": "Vì, này Cunda, đó là điều xảy ra khi pháp và luật được giảng dạy tệ hại, trình bày không khéo, không đưa đến giải thoát, không đưa đến lắng dịu, do người không phải bậc Giác Ngộ chân chánh tuyên thuyết. ",
  "dn29:5.1": "Nhưng ở đây, này Cunda, có vị thầy không phải bậc Giác Ngộ chân chánh, và pháp được giảng dạy tệ hại, trình bày không khéo, không đưa đến giải thoát, không đưa đến lắng dịu, do người không phải bậc Giác Ngộ chân chánh tuyên thuyết, ",
  "dn29:5.2": "còn đệ tử trong pháp ấy lại sống thực hành đúng theo pháp, thực hành thích hợp, sống thuận theo pháp, giữ gìn và sống theo pháp ấy. ",
  "dn29:5.3": "Người ấy nên được nói như sau: ",
  "dn29:5.4": "‘Này hiền giả, thật là điều bất hạnh cho ông, thật là điều ông nhận được không khéo, vì thầy của ông không phải bậc Giác Ngộ chân chánh, và pháp được giảng dạy tệ hại, trình bày không khéo, không đưa đến giải thoát, không đưa đến lắng dịu, do người không phải bậc Giác Ngộ chân chánh tuyên thuyết. ",
  "dn29:5.5": "Thế mà ông lại sống thực hành đúng theo pháp ấy, thực hành thích hợp, sống thuận theo pháp, giữ gìn và sống theo pháp ấy.’ ",
  "dn29:5.6": "Như vậy, này Cunda, ở đó vị thầy đáng bị chê trách, pháp cũng đáng bị chê trách, và đệ tử cũng đáng bị chê trách như thế. ",
  "dn29:5.7": "Này Cunda, nếu ai nói với một đệ tử như vậy rằng: ",
  "dn29:5.8": "‘Chắc chắn tôn giả đang đi đúng đường và sẽ đạt được điều đúng đắn,’ ",
  "dn29:5.9": "người khen, điều được khen, và người được khen rồi càng thêm nỗ lực, tất cả đều tạo ra nhiều điều không lành. ",
  "dn29:5.10": "Vì sao vậy? ",
  "dn29:5.11": "Vì, này Cunda, đó là điều xảy ra khi pháp và luật được giảng dạy tệ hại, trình bày không khéo, không đưa đến giải thoát, không đưa đến lắng dịu, do người không phải bậc Giác Ngộ chân chánh tuyên thuyết. ",
  "dn29:6.0": "2. Pháp và luật do bậc Giác Ngộ chân chánh tuyên thuyết ",
  "dn29:6.1": "Nhưng ở đây, này Cunda, có vị thầy là bậc Giác Ngộ chân chánh, và pháp được khéo giảng, khéo trình bày, đưa đến giải thoát, đưa đến lắng dịu, do bậc Giác Ngộ chân chánh tuyên thuyết, ",
  "dn29:6.2": "còn đệ tử trong pháp ấy lại không sống thực hành đúng theo pháp, không thực hành thích hợp, không sống thuận theo pháp, mà còn đi lệch khỏi pháp ấy. ",
  "dn29:6.3": "Người ấy nên được nói như sau: ",
  "dn29:6.4": "‘Này hiền giả, thật là điều bất hạnh cho ông, thật là điều ông nhận được không khéo, vì thầy của ông là bậc Giác Ngộ chân chánh, và pháp được khéo giảng, khéo trình bày, đưa đến giải thoát, đưa đến lắng dịu, do bậc Giác Ngộ chân chánh tuyên thuyết. ",
  "dn29:6.5": "Vậy mà ông lại không sống thực hành đúng theo pháp ấy, không thực hành thích hợp, không sống thuận theo pháp, còn đi lệch khỏi pháp ấy.’ ",
  "dn29:6.6": "Này Cunda, trong trường hợp ấy, bậc Đạo sư đáng được khen ngợi, pháp cũng đáng được khen ngợi, còn đệ tử như vậy thì đáng bị chê trách.",
  "dn29:6.7": "Này Cunda, nếu có ai nói với một đệ tử như vậy rằng:",
  "dn29:6.8": "‘Mong tôn giả hãy thực hành đúng như pháp mà bậc Đạo sư của thầy đã giảng dạy và chỉ bày.’",
  "dn29:6.9": "Người khuyên bảo, điều được khuyên bảo, và người đã được khuyên bảo rồi thực hành đúng theo đó — tất cả những người ấy đều tạo được nhiều phước.",
  "dn29:6.10": "Vì sao vậy?",
  "dn29:6.11": "Vì này Cunda, trong pháp và luật được khéo giảng, được trình bày rõ ràng, có khả năng đưa đến giải thoát, đưa đến an lắng, do bậc Chánh Đẳng Giác tuyên thuyết, thì là như vậy.",
  "dn29:7.1": "Này Cunda, ở đây có bậc Đạo sư là bậc Chánh Đẳng Giác, pháp được khéo giảng, được trình bày rõ ràng, có khả năng đưa đến giải thoát, đưa đến an lắng, do bậc Chánh Đẳng Giác tuyên thuyết,",
  "dn29:7.2": "và người đệ tử sống thực hành đúng pháp, thuận theo pháp ấy, sống đúng đắn, hành xử theo pháp, thọ trì và sống theo pháp ấy.",
  "dn29:7.3": "Người ấy nên được nói rằng:",
  "dn29:7.4": "‘Này hiền giả, thầy thật có lợi ích, thầy thật khéo được lợi ích,",
  "dn29:7.5": "vì Đạo sư của thầy là bậc Chánh Đẳng Giác, pháp được khéo giảng, được trình bày rõ ràng, có khả năng đưa đến giải thoát, đưa đến an lắng, do bậc Chánh Đẳng Giác tuyên thuyết.",
  "dn29:7.6": "Và thầy sống thực hành đúng pháp ấy, thuận theo pháp, sống đúng đắn, hành xử theo pháp, thọ trì và sống theo pháp ấy.’",
  "dn29:7.7": "Này Cunda, trong trường hợp ấy, bậc Đạo sư đáng được khen ngợi, pháp cũng đáng được khen ngợi, và đệ tử như vậy cũng đáng được khen ngợi.",
  "dn29:7.8": "Này Cunda, nếu có ai nói với một đệ tử như vậy rằng:",
  "dn29:7.9": "‘Chắc chắn tôn giả đang thực hành đúng đường và sẽ thành tựu con đường chân chánh.’",
  "dn29:7.10": "Người khen ngợi, điều được khen ngợi, và người được khen rồi càng thêm tinh tấn — tất cả những người ấy đều tạo được nhiều phước.",
  "dn29:7.11": "Vì sao vậy?",
  "dn29:7.12": "Vì này Cunda, trong pháp và luật được khéo giảng, được trình bày rõ ràng, có khả năng đưa đến giải thoát, đưa đến an lắng, do bậc Chánh Đẳng Giác tuyên thuyết, thì là như vậy.",
  "dn29:8.0": "3. Trường hợp Đạo sư khiến đệ tử hối tiếc",
  "dn29:8.1": "Này Cunda, ở đây một bậc Đạo sư xuất hiện ở đời, là bậc A-la-hán, Chánh Đẳng Giác; pháp được khéo giảng, được trình bày rõ ràng, có khả năng đưa đến giải thoát, đưa đến an lắng, do bậc Chánh Đẳng Giác tuyên thuyết,",
  "dn29:8.2": "nhưng các đệ tử của vị ấy trong chánh pháp chưa hiểu rõ ý nghĩa, và đời sống phạm hạnh trọn vẹn cũng chưa được trình bày rõ ràng, mở bày sáng tỏ, đầy đủ mọi mặt, có đủ dấu hiệu, được làm sáng tỏ rộng rãi cho đến chư thiên và loài người.",
  "dn29:8.3": "Rồi vị Đạo sư ấy biến mất.",
  "dn29:8.4": "Này Cunda, một vị Đạo sư như vậy, sau khi qua đời, là điều khiến các đệ tử hối tiếc.",
  "dn29:8.5": "Vì sao vậy?",
  "dn29:8.6": "‘Đạo sư của chúng ta đã xuất hiện ở đời, là bậc A-la-hán, Chánh Đẳng Giác; pháp được khéo giảng, được trình bày rõ ràng, có khả năng đưa đến giải thoát, đưa đến an lắng, do bậc Chánh Đẳng Giác tuyên thuyết; nhưng chúng ta trong chánh pháp chưa hiểu rõ ý nghĩa, và đời sống phạm hạnh trọn vẹn của chúng ta cũng chưa được trình bày rõ ràng, mở bày sáng tỏ, đầy đủ mọi mặt, có đủ dấu hiệu, được làm sáng tỏ rộng rãi cho đến chư thiên và loài người.",
  "dn29:8.7": "Rồi Đạo sư của chúng ta đã biến mất.’",
  "dn29:8.8": "Này Cunda, một vị Đạo sư như vậy, sau khi qua đời, là điều khiến các đệ tử hối tiếc.",
  "dn29:9.0": "4. Trường hợp Đạo sư không khiến đệ tử hối tiếc",
  "dn29:9.1": "Này Cunda, ở đây một bậc Đạo sư xuất hiện ở đời, là bậc A-la-hán, Chánh Đẳng Giác. Pháp được khéo giảng, được trình bày rõ ràng, có khả năng đưa đến giải thoát, đưa đến an lắng, do bậc Chánh Đẳng Giác tuyên thuyết.",
  "dn29:9.2": "Các đệ tử của vị ấy hiểu rõ ý nghĩa trong chánh pháp, và đời sống phạm hạnh trọn vẹn của họ được trình bày rõ ràng, mở bày sáng tỏ, đầy đủ mọi mặt, có đủ dấu hiệu, được làm sáng tỏ rộng rãi cho đến chư thiên và loài người.",
  "dn29:9.3": "Rồi vị Đạo sư ấy biến mất.",
  "dn29:9.4": "Này Cunda, một vị Đạo sư như vậy, sau khi qua đời, không phải là điều khiến các đệ tử hối tiếc.",
  "dn29:9.5": "Vì sao vậy?",
  "dn29:9.6": "‘Đạo sư của chúng ta đã xuất hiện ở đời, là bậc A-la-hán, Chánh Đẳng Giác.",
  "dn29:9.7": "Pháp được khéo giảng, được trình bày rõ ràng, có khả năng đưa đến giải thoát, đưa đến an lắng, do bậc Chánh Đẳng Giác tuyên thuyết.",
  "dn29:9.8": "Chúng ta đã hiểu rõ ý nghĩa trong chánh pháp, và đời sống phạm hạnh trọn vẹn của chúng ta đã được trình bày rõ ràng, mở bày sáng tỏ, đầy đủ mọi mặt, có đủ dấu hiệu, được làm sáng tỏ rộng rãi cho đến chư thiên và loài người.",
  "dn29:9.9": "Rồi Đạo sư của chúng ta đã biến mất.’",
  "dn29:9.10": "Này Cunda, một vị Đạo sư như vậy, sau khi qua đời, không phải là điều khiến các đệ tử hối tiếc.",
  "dn29:10.0": "5. Bàn về sự chưa trọn vẹn của đời sống phạm hạnh và những điều liên hệ",
  "dn29:10.1": "Này Cunda, dù đời sống phạm hạnh có đủ những yếu tố này, nhưng nếu vị Đạo sư không phải là bậc trưởng lão, nhiều năm kinh nghiệm, xuất gia đã lâu, tuổi tác đã cao,",
  "dn29:10.2": "thì đời sống phạm hạnh ấy vẫn chưa trọn vẹn ở phương diện đó.",
  "dn29:10.3": "Nhưng này Cunda, khi đời sống phạm hạnh có đủ những yếu tố này, và vị Đạo sư là bậc trưởng lão, nhiều năm kinh nghiệm, xuất gia đã lâu, tuổi tác đã cao,",
  "dn29:10.4": "thì đời sống phạm hạnh ấy trọn vẹn ở phương diện đó.",
  "dn29:11.1": "Này Cunda, dù đời sống phạm hạnh có đủ những yếu tố này, và vị Đạo sư là bậc trưởng lão, nhiều năm kinh nghiệm, xuất gia đã lâu, tuổi tác đã cao, nhưng nếu các vị tỳ-kheo đệ tử trưởng lão của vị ấy không phải là những người thông thạo, được rèn luyện, vững vàng, đã đạt đến an ổn khỏi ách nạn,",
  "dn29:11.2": "không đủ khả năng trình bày chánh pháp, không đủ khả năng khéo bác bỏ những luận thuyết đối nghịch đã khởi lên bằng đúng pháp, rồi giảng dạy pháp có sức thuyết phục,",
  "dn29:11.3": "thì đời sống phạm hạnh ấy vẫn chưa trọn vẹn ở phương diện đó.",
  "dn29:12.1": "Nhưng này Cunda, khi đời sống phạm hạnh có đủ những yếu tố này, vị Đạo sư là bậc trưởng lão, nhiều năm kinh nghiệm, xuất gia đã lâu, tuổi tác đã cao, và các vị tỳ-kheo đệ tử trưởng lão của vị ấy là những người thông thạo, được rèn luyện, vững vàng, đã đạt đến an ổn khỏi ách nạn,",
  "dn29:12.2": "đủ khả năng trình bày chánh pháp, đủ khả năng khéo bác bỏ những luận thuyết đối nghịch đã khởi lên bằng đúng pháp, rồi giảng dạy pháp có sức thuyết phục,",
  "dn29:12.3": "thì đời sống phạm hạnh ấy trọn vẹn ở phương diện đó.",
  "dn29:12.4": "Này Cunda, dù đời sống phạm hạnh có đủ những yếu tố này, vị Đạo sư là bậc trưởng lão, nhiều năm kinh nghiệm, xuất gia đã lâu, tuổi tác đã cao, và các vị tỳ-kheo đệ tử trưởng lão của vị ấy là những người thông thạo, được rèn luyện, vững vàng, đã đạt đến an ổn khỏi ách nạn.",
  "dn29:12.5": "Đủ sức trình bày chánh pháp, đủ sức khéo bác bỏ những luận thuyết đối nghịch đã khởi lên bằng đúng pháp, rồi thuyết pháp có sức thuyết phục.",
  "dn29:12.6": "Nhưng vị ấy không có các tỳ-kheo đệ tử bậc trung …",
  "dn29:12.7": "Vị ấy có các tỳ-kheo đệ tử bậc trung, nhưng không có các tỳ-kheo đệ tử mới xuất gia …",
  "dn29:12.8": "Vị ấy có các tỳ-kheo đệ tử mới xuất gia, nhưng không có các tỳ-kheo-ni đệ tử trưởng lão …",
  "dn29:12.9": "Vị ấy có các tỳ-kheo-ni đệ tử trưởng lão, nhưng không có các tỳ-kheo-ni đệ tử bậc trung …",
  "dn29:12.10": "Vị ấy có các tỳ-kheo-ni đệ tử bậc trung, nhưng không có các tỳ-kheo-ni đệ tử mới xuất gia …",
  "dn29:12.11": "Vị ấy có các tỳ-kheo-ni đệ tử mới xuất gia, nhưng không có các nam cư sĩ đệ tử mặc áo trắng, sống phạm hạnh …",
  "dn29:12.12": "Vị ấy có các nam cư sĩ đệ tử mặc áo trắng, sống phạm hạnh, nhưng không có các nam cư sĩ đệ tử mặc áo trắng, sống hưởng dục …",
  "dn29:12.13": "Vị ấy có các nam cư sĩ đệ tử mặc áo trắng, sống hưởng dục, nhưng không có các nữ cư sĩ đệ tử mặc áo trắng, sống phạm hạnh …",
  "dn29:12.14": "Vị ấy có các nữ cư sĩ đệ tử mặc áo trắng, sống phạm hạnh, nhưng không có các nữ cư sĩ đệ tử mặc áo trắng, sống hưởng dục …",
  "dn29:12.15": "Vị ấy có các nữ cư sĩ đệ tử mặc áo trắng, sống hưởng dục, nhưng đời sống phạm hạnh ấy chưa hưng thịnh, chưa phát triển, chưa rộng lớn, chưa được nhiều người biết đến, chưa lan rộng, chưa được chư thiên và loài người biết rõ …",
  "dn29:12.16": "Đời sống phạm hạnh của vị ấy có hưng thịnh, phát triển, rộng lớn, được nhiều người biết đến, lan rộng, được chư thiên và loài người biết rõ, nhưng chưa đạt đến đỉnh cao về lợi dưỡng và danh tiếng.",
  "dn29:12.17": "Như vậy, đời sống phạm hạnh ấy còn chưa trọn đủ ở phương diện đó.",
  "dn29:13.1": "Nhưng này Cunda, khi đời sống phạm hạnh có đủ những yếu tố ấy, và có bậc Đạo sư là vị trưởng lão, lâu năm, xuất gia đã lâu, đã đến tuổi cao, thì vị ấy có các tỳ-kheo đệ tử trưởng lão, thành thạo, được rèn luyện, vững vàng, đã đạt an ổn khỏi trói buộc.",
  "dn29:13.2": "Đủ sức trình bày chánh pháp, đủ sức khéo bác bỏ những luận thuyết đối nghịch đã khởi lên bằng đúng pháp, rồi thuyết pháp có sức thuyết phục.",
  "dn29:13.3": "Vị ấy có các tỳ-kheo đệ tử bậc trung …",
  "dn29:13.4": "vị ấy có các tỳ-kheo đệ tử mới xuất gia …",
  "dn29:13.5": "vị ấy có các tỳ-kheo-ni đệ tử trưởng lão …",
  "dn29:13.6": "vị ấy có các tỳ-kheo-ni đệ tử bậc trung …",
  "dn29:13.7": "vị ấy có các tỳ-kheo-ni đệ tử mới xuất gia …",
  "dn29:13.8": "vị ấy có các nam cư sĩ đệ tử … là người tại gia mặc áo trắng, sống phạm hạnh.",
  "dn29:13.9": "Vị ấy có các nam cư sĩ đệ tử là người tại gia mặc áo trắng, sống hưởng dục …",
  "dn29:13.10": "vị ấy có các nữ cư sĩ đệ tử là người tại gia mặc áo trắng, sống phạm hạnh …",
  "dn29:13.11": "vị ấy có các nữ cư sĩ đệ tử là người tại gia mặc áo trắng, sống hưởng dục …",
  "dn29:13.12": "và đời sống phạm hạnh của vị ấy hưng thịnh, phát triển, rộng lớn, được nhiều người biết đến, lan rộng, được chư thiên và loài người biết rõ, lại đạt đến đỉnh cao về lợi dưỡng và danh tiếng.",
  "dn29:13.13": "Như vậy, đời sống phạm hạnh ấy là trọn đủ ở phương diện đó.",
  "dn29:14.1": "Còn ta, này Cunda, hiện nay là bậc Đạo sư xuất hiện ở đời, là bậc A-la-hán, bậc Chánh Đẳng Giác.",
  "dn29:14.2": "Pháp đã được khéo giảng, được trình bày rõ ràng, đưa đến giải thoát, đưa đến lắng dịu, do bậc Chánh Đẳng Giác tuyên thuyết.",
  "dn29:14.3": "Các đệ tử của ta đã được chỉ dạy về ý nghĩa trong chánh pháp, và đối với họ, đời sống phạm hạnh trọn vẹn đã được bày rõ, mở ra rõ ràng, gồm đủ mọi mặt, có sức thuyết phục, cho đến được chư thiên và loài người biết rõ.",
  "dn29:14.4": "Còn ta, này Cunda, hiện nay là bậc Đạo sư trưởng lão, lâu năm, xuất gia đã lâu, đã đến tuổi cao.",
  "dn29:15.1": "Này Cunda, hiện nay ta có các tỳ-kheo đệ tử trưởng lão, thành thạo, được rèn luyện, vững vàng, đã đạt an ổn khỏi trói buộc.",
  "dn29:15.2": "Đủ sức trình bày chánh pháp, đủ sức khéo bác bỏ những luận thuyết đối nghịch đã khởi lên bằng đúng pháp, rồi thuyết pháp có sức thuyết phục.",
  "dn29:15.3": "Này Cunda, hiện nay ta có các tỳ-kheo đệ tử bậc trung …",
  "dn29:15.4": "này Cunda, hiện nay ta có các tỳ-kheo đệ tử mới xuất gia …",
  "dn29:15.5": "này Cunda, hiện nay ta có các tỳ-kheo-ni đệ tử trưởng lão …",
  "dn29:15.6": "này Cunda, hiện nay ta có các tỳ-kheo-ni đệ tử bậc trung …",
  "dn29:15.7": "này Cunda, hiện nay ta có các tỳ-kheo-ni đệ tử mới xuất gia …",
  "dn29:15.8": "này Cunda, hiện nay ta có các nam cư sĩ đệ tử là người tại gia mặc áo trắng, sống phạm hạnh …",
  "dn29:15.9": "này Cunda, hiện nay ta có các nam cư sĩ đệ tử là người tại gia mặc áo trắng, sống hưởng dục …",
  "dn29:15.10": "này Cunda, hiện nay ta có các nữ cư sĩ đệ tử là người tại gia mặc áo trắng, sống phạm hạnh …",
  "dn29:15.11": "này Cunda, hiện nay ta có các nữ cư sĩ đệ tử là người tại gia mặc áo trắng, sống hưởng dục …",
  "dn29:15.12": "này Cunda, hiện nay đời sống phạm hạnh của ta hưng thịnh, phát triển, rộng lớn, được nhiều người biết đến, lan rộng, được chư thiên và loài người biết rõ.",
  "dn29:16.1": "Này Cunda, trong tất cả các bậc Đạo sư hiện nay xuất hiện ở đời, ta không thấy một vị Đạo sư nào khác đạt đến đỉnh cao về lợi dưỡng và danh tiếng như ta.",
  "dn29:16.2": "Còn này Cunda, trong tất cả các hội chúng hay đoàn thể hiện nay xuất hiện ở đời;",
  "dn29:16.3": "ta không thấy một hội chúng nào khác đạt đến đỉnh cao về lợi dưỡng và danh tiếng như hội chúng tỳ-kheo này, này Cunda.",
  "dn29:16.4": "Nếu ai nói đúng, nói chân chánh rằng:",
  "dn29:16.5": "‘Đời sống phạm hạnh đã được khéo giảng, đầy đủ mọi mặt, trọn vẹn mọi mặt, không thiếu không dư, hoàn toàn viên mãn, được làm cho sáng tỏ rõ ràng’,",
  "dn29:16.6": "thì người ấy nói đúng, nói chân chánh chính là nói điều này:",
  "dn29:16.7": "‘Đời sống phạm hạnh đã đầy đủ mọi mặt … được làm cho sáng tỏ rõ ràng’.",
  "dn29:16.8": "Này Cunda, Udaka, con của Rāma, thường nói lời như sau:",
  "dn29:16.9": "‘Thấy mà không thấy’.",
  "dn29:16.10": "Thế nào là thấy mà không thấy?",
  "dn29:16.11": "Người ấy thấy sống dao cạo được mài khéo, rất bén, nhưng không thấy lưỡi dao của nó.",
  "dn29:16.12": "Điều này được gọi là:",
  "dn29:16.13": "‘Thấy mà không thấy’.",
  "dn29:16.14": "Nhưng điều mà Udaka Rāmaputta đã nói, này Cunda, là thấp kém, tầm thường, thuộc hạng người thường, không cao thượng, không đưa đến lợi ích, chỉ nhắm đến dao cạo mà thôi.",
  "dn29:16.15": "Còn điều mà, này Cunda, khi nói đúng người ta có thể nói rằng:",
  "dn29:16.16": "‘Thấy mà không thấy’, thì chính là điều này, khi nói đúng người ta có thể nói rằng:",
  "dn29:16.17": "‘Thấy mà không thấy’.",
  "dn29:16.18": "Thế nào là thấy mà không thấy?",
  "dn29:16.19": "Người ấy thấy rằng đời sống phạm hạnh này đầy đủ mọi mặt, trọn vẹn mọi mặt, không thiếu không thừa, được khéo giảng dạy, hoàn toàn viên mãn, được trình bày rõ ràng.",
  "dn29:16.20": "Người ấy không thấy rằng: ‘Nếu bỏ bớt điều này ở đây thì nó sẽ trong sạch hơn’.",
  "dn29:16.21": "Người ấy không thấy rằng: ‘Nếu thêm điều này ở đây thì nó sẽ trọn vẹn hơn’.",
  "dn29:16.22": "Điều này được gọi là, này Cunda:",
  "dn29:16.23": "‘Thấy mà không thấy’.",
  "dn29:16.24": "Còn điều mà, này Cunda, khi nói đúng người ta có thể nói rằng:",
  "dn29:16.25": "‘Đầy đủ mọi mặt …",
  "dn29:16.26": "đời sống phạm hạnh được trình bày rõ ràng’.",
  "dn29:16.27": "Thì chính là điều này, khi nói đúng người ta có thể nói rằng:",
  "dn29:16.28": "‘Đời sống phạm hạnh này đầy đủ mọi mặt, trọn vẹn mọi mặt, không thiếu không thừa, được khéo giảng dạy, hoàn toàn viên mãn, được trình bày rõ ràng’.",
  "dn29:17.0": "6. Những pháp cần được cùng nhau tụng đọc",
  "dn29:17.1": "Vậy nên, này Cunda, những pháp nào Ta đã giảng dạy do tự mình chứng biết, thì tất cả các ông phải cùng nhau họp lại, cùng nhau tụng đọc, đối chiếu nghĩa với nghĩa, lời với lời, chớ tranh cãi, để đời sống phạm hạnh này được lâu dài, bền vững, vì lợi ích cho nhiều người, vì hạnh phúc cho nhiều người, vì thương đời, vì lợi ích, vì an vui cho chư thiên và loài người.",
  "dn29:17.2": "Và này Cunda, những pháp nào Ta đã giảng dạy do tự mình chứng biết, mà tất cả các ông phải cùng nhau họp lại, cùng nhau tụng đọc, đối chiếu nghĩa với nghĩa, lời với lời, chớ tranh cãi, để đời sống phạm hạnh này được lâu dài, bền vững, vì lợi ích cho nhiều người, vì hạnh phúc cho nhiều người, vì thương đời, vì lợi ích, vì an vui cho chư thiên và loài người?",
  "dn29:17.3": "Đó là: bốn niệm xứ, bốn chánh cần, bốn thần túc, năm căn, năm lực, bảy giác chi, con đường thánh tám ngành.",
  "dn29:17.4": "Này Cunda, đó là những pháp Ta đã giảng dạy do tự mình chứng biết.",
  "dn29:17.5": "Ở đó, tất cả các ông phải cùng nhau họp lại, cùng nhau tụng đọc, đối chiếu nghĩa với nghĩa, lời với lời, chớ tranh cãi, để đời sống phạm hạnh này được lâu dài, bền vững, vì lợi ích cho nhiều người, vì hạnh phúc cho nhiều người, vì thương đời, vì lợi ích, vì an vui cho chư thiên và loài người.",
  "dn29:18.0": "7. Cách khuyên bảo",
  "dn29:18.1": "Và này Cunda, khi các ông đang sống hòa hợp, vui vẻ, không tranh cãi, cùng học tập, nếu có một vị đồng phạm hạnh nào nói pháp giữa Tăng chúng,",
  "dn29:18.2": "nếu khi ấy các ông nghĩ rằng:",
  "dn29:18.3": "‘Vị tôn giả này hiểu sai nghĩa và sắp đặt lời cũng sai’,",
  "dn29:18.4": "thì không nên tán thành cũng không nên phản đối vị ấy. Không tán thành, không phản đối, nên nói với vị ấy như sau:",
  "dn29:18.5": "‘Này hiền giả, đối với nghĩa này, những lời này hay những lời kia, cái nào thích hợp hơn? Và đối với những lời này, nghĩa này hay nghĩa kia, cái nào thích hợp hơn?’",
  "dn29:18.6": "Nếu vị ấy nói rằng:",
  "dn29:18.7": "‘Này hiền giả, đối với nghĩa này, chính những lời này là thích hợp hơn, chứ không phải những lời kia; và đối với những lời này, chính nghĩa này là thích hợp hơn, chứ không phải nghĩa kia’,",
  "dn29:18.8": "thì không nên đề cao cũng không nên chê bai vị ấy. Không đề cao, không chê bai, hãy khéo khuyên bảo vị ấy để vị ấy hiểu rõ nghĩa ấy và những lời ấy.",
  "dn29:19.1": "Lại nữa, này Cunda, nếu có một vị đồng phạm hạnh khác nói pháp giữa Tăng chúng,",
  "dn29:19.2": "nếu khi ấy các ông nghĩ rằng:",
  "dn29:19.3": "‘Vị tôn giả này hiểu sai nghĩa, nhưng sắp đặt lời đúng’,",
  "dn29:19.4": "thì không nên tán thành cũng không nên phản đối vị ấy. Không tán thành, không phản đối, nên nói với vị ấy như sau:",
  "dn29:19.5": "‘Này hiền giả, đối với những lời này, nghĩa này hay nghĩa kia, cái nào thích hợp hơn?’",
  "dn29:19.6": "Nếu vị ấy nói rằng:",
  "dn29:19.7": "‘Này hiền giả, đối với những lời này, chính nghĩa này là thích hợp hơn, chứ không phải nghĩa kia’,",
  "dn29:19.8": "thì không nên đề cao cũng không nên chê bai vị ấy. Không đề cao, không chê bai, hãy khéo khuyên bảo vị ấy để vị ấy hiểu rõ chính nghĩa ấy.",
  "dn29:20.1": "Lại nữa, này Cunda, nếu có một vị đồng phạm hạnh khác nói pháp giữa Tăng chúng,",
  "dn29:20.2": "nếu khi ấy các ông nghĩ rằng:",
  "dn29:20.3": "‘Vị tôn giả này hiểu đúng nghĩa, nhưng sắp đặt lời sai’,",
  "dn29:20.4": "thì không nên tán thành cũng không nên phản đối vị ấy. Không tán thành, không phản đối, nên nói với vị ấy như sau:",
  "dn29:20.5": "‘Này hiền giả, đối với nghĩa này, những lời này hay những lời kia, cái nào thích hợp hơn?’",
  "dn29:20.6": "Nếu vị ấy nói rằng:",
  "dn29:20.7": "‘Này hiền giả, đối với nghĩa này, chính những lời này là thích hợp hơn, chứ không phải những lời kia’,",
  "dn29:20.8": "Vị ấy không nên bị tâng bốc, cũng không nên bị chê bai; không tâng bốc, không chê bai, mà chính phải khéo léo làm cho vị ấy hiểu rõ, dựa trên chính những lời ấy.",
  "dn29:21.1": "Lại nữa, này Cunda, nếu có một vị đồng phạm hạnh nói pháp giữa Tăng chúng.",
  "dn29:21.2": "Nếu ở đó các ông nghĩ rằng:",
  "dn29:21.3": "‘Vị tôn giả này nắm đúng ý nghĩa và cũng sắp đặt ngôn từ đúng đắn.’",
  "dn29:21.4": "Thì lời nói ‘lành thay’ của vị ấy cần được hoan hỷ đón nhận và tán đồng;",
  "dn29:21.5": "sau khi hoan hỷ đón nhận và tán đồng lời nói ‘lành thay’ của vị ấy, nên nói với vị ấy như sau:",
  "dn29:21.6": "‘Chúng tôi thật có lợi, này hiền giả, chúng tôi thật khéo được lợi, này hiền giả,",
  "dn29:21.7": "vì chúng tôi được thấy một vị đồng phạm hạnh như tôn giả, đầy đủ ý nghĩa và đầy đủ lời lẽ như vậy.’",
  "dn29:22.0": "8. Lý do cho phép dùng vật dụng",
  "dn29:22.1": "Này Cunda, ta không chỉ thuyết pháp để ngăn chặn các lậu hoặc trong đời này.",
  "dn29:22.2": "Nhưng này Cunda, ta cũng không chỉ thuyết pháp để dứt trừ các lậu hoặc ở đời sau.",
  "dn29:22.3": "Này Cunda, ta thuyết pháp vừa để ngăn chặn các lậu hoặc trong đời này,",
  "dn29:22.4": "vừa để dứt trừ các lậu hoặc ở đời sau.",
  "dn29:22.5": "Vậy nên, này Cunda, y áo mà ta cho phép các ông dùng, như thế là đủ cho các ông",
  "dn29:22.6": "chỉ để chống lạnh, chống nóng, chống sự xúc chạm của ruồi, muỗi, gió, nắng và các loài bò sát, chỉ để che đậy phần kín vì lòng biết hổ thẹn.",
  "dn29:22.7": "Đồ ăn khất thực mà ta cho phép các ông dùng, như thế là đủ cho các ông",
  "dn29:22.8": "chỉ để duy trì và nuôi sống thân này, để chấm dứt sự hành hạ, để nâng đỡ đời sống phạm hạnh, nghĩ rằng: ‘Ta sẽ diệt trừ cảm thọ cũ và không làm phát sinh cảm thọ mới; như vậy ta sẽ sống được, không lỗi lầm và an ổn.’",
  "dn29:22.9": "Chỗ ở mà ta cho phép các ông dùng, như thế là đủ cho các ông",
  "dn29:22.10": "chỉ để chống lạnh, chống nóng, chống sự xúc chạm của ruồi, muỗi, gió, nắng và các loài bò sát, chỉ để tránh những nguy hại do thời tiết và để ưa thích sống yên tĩnh một mình.",
  "dn29:22.11": "Thuốc men và vật dụng chữa bệnh mà ta cho phép các ông dùng, như thế là đủ cho các ông",
  "dn29:22.12": "chỉ để trị các cảm thọ đau đớn do bệnh đã sinh khởi, nhằm đạt đến trạng thái không bệnh là cao nhất.",
  "dn29:23.0": "9. Theo đuổi khoái lạc",
  "dn29:23.1": "Này Cunda, có trường hợp các du sĩ ngoại đạo có thể nói như sau:",
  "dn29:23.2": "‘Các sa môn con cháu họ Thích sống theo đuổi khoái lạc.’",
  "dn29:23.3": "Này Cunda, với các du sĩ ngoại đạo nói như vậy, các ông nên nói với họ như sau:",
  "dn29:23.4": "‘Này hiền giả, theo đuổi khoái lạc ấy là loại nào?",
  "dn29:23.5": "Vì có nhiều cách theo đuổi khoái lạc, nhiều loại khác nhau.’",
  "dn29:23.6": "Này Cunda, có bốn cách theo đuổi khoái lạc thấp kém, tầm thường, thuộc hạng phàm phu, không cao quý, không đưa đến lợi ích, không đưa đến chán lìa, không đưa đến phai nhạt, không đưa đến chấm dứt, không đưa đến lắng dịu, không đưa đến thắng trí, không đưa đến giác ngộ, không đưa đến Niết-bàn.",
  "dn29:23.7": "Bốn cách ấy là gì?",
  "dn29:23.8": "Ở đây, này Cunda, có kẻ ngu giết hại chúng sinh hết lần này đến lần khác để tự làm mình vui thích, thỏa mãn.",
  "dn29:23.9": "Đó là cách theo đuổi khoái lạc thứ nhất.",
  "dn29:23.10": "Lại nữa, này Cunda, ở đây có kẻ lấy của không cho hết lần này đến lần khác để tự làm mình vui thích, thỏa mãn.",
  "dn29:23.11": "Đó là cách theo đuổi khoái lạc thứ hai.",
  "dn29:23.12": "Lại nữa, này Cunda, ở đây có kẻ nói dối hết lần này đến lần khác để tự làm mình vui thích, thỏa mãn.",
  "dn29:23.13": "Đó là cách theo đuổi khoái lạc thứ ba.",
  "dn29:23.14": "Lại nữa, này Cunda, ở đây có kẻ sống đắm mình, gắn chặt trong năm thứ dục lạc.",
  "dn29:23.15": "Đó là cách theo đuổi khoái lạc thứ tư.",
  "dn29:23.16": "Này Cunda, đó là bốn cách theo đuổi khoái lạc thấp kém, tầm thường, thuộc hạng phàm phu, không cao quý, không đưa đến lợi ích, không đưa đến chán lìa, không đưa đến phai nhạt, không đưa đến chấm dứt, không đưa đến lắng dịu, không đưa đến thắng trí, không đưa đến giác ngộ, không đưa đến Niết-bàn.",
  "dn29:24.1": "Này Cunda, có trường hợp các du sĩ ngoại đạo có thể nói như sau:",
  "dn29:24.2": "‘Các sa môn con cháu họ Thích sống theo đuổi bốn cách khoái lạc này.’",
  "dn29:24.3": "Các ông nên nói với họ: ‘Đừng nói như vậy.’",
  "dn29:24.4": "Nếu họ nói như thế thì là nói không đúng, vu khống bằng điều không thật, không có thực.",
  "dn29:24.5": "Này Cunda, có bốn cách theo đuổi khoái lạc đưa thẳng đến chán lìa, phai nhạt, chấm dứt, lắng dịu, thắng trí, giác ngộ và Niết-bàn.",
  "dn29:24.6": "Bốn cách ấy là gì?",
  "dn29:24.7": "Ở đây, này Cunda, vị tỳ-kheo lìa các dục, lìa các pháp bất thiện, chứng và an trú tầng thiền thứ nhất, có tầm có tứ, có niềm vui và sự an lạc do lìa dục sinh ra.",
  "dn29:24.8": "Đó là cách theo đuổi khoái lạc thứ nhất.",
  "dn29:24.9": "Lại nữa, này Cunda, vị tỳ-kheo do lắng yên tầm và tứ … chứng và an trú tầng thiền thứ hai.",
  "dn29:24.10": "Đó là cách theo đuổi khoái lạc thứ hai.",
  "dn29:24.11": "Lại nữa, này Cunda, vị tỳ-kheo do ly tham đối với niềm vui … chứng và an trú tầng thiền thứ ba.",
  "dn29:24.12": "Đó là cách theo đuổi khoái lạc thứ ba.",
  "dn29:24.13": "Lại nữa, này Cunda, vị tỳ kheo do từ bỏ lạc, từ bỏ khổ… chứng và an trú thiền thứ tư.",
  "dn29:24.14": "Đây là sự theo đuổi khoái lạc thứ tư.",
  "dn29:24.15": "Này Cunda, bốn sự theo đuổi khoái lạc này đưa đến chán lìa hoàn toàn, ly tham, diệt tận, an tịnh, thắng trí, giác ngộ, niết bàn.",
  "dn29:24.16": "Này Cunda, có thể xảy ra trường hợp các du sĩ ngoại đạo nói như vầy:",
  "dn29:24.17": "‘Các sa môn con cháu dòng Sakya sống theo bốn sự theo đuổi khoái lạc này.’",
  "dn29:24.18": "Khi họ nói vậy, các ông nên đáp lại như vầy:",
  "dn29:24.19": "‘Các vị nói như vậy là nói đúng, không vu khống các ông bằng điều không thật, không có.’",
  "dn29:25.0": "10. Lợi ích của sự theo đuổi khoái lạc",
  "dn29:25.1": "Này Cunda, có thể xảy ra trường hợp các du sĩ ngoại đạo nói như vầy:",
  "dn29:25.2": "‘Này các hiền giả, những người sống theo bốn sự theo đuổi khoái lạc này có thể mong đợi bao nhiêu kết quả, bao nhiêu lợi ích?’",
  "dn29:25.3": "Này Cunda, với các du sĩ ngoại đạo nói như vậy, nên đáp lại như vầy:",
  "dn29:25.4": "‘Này các hiền giả, những người sống theo bốn sự theo đuổi khoái lạc này có thể mong đợi bốn kết quả, bốn lợi ích.",
  "dn29:25.5": "Bốn là những gì?",
  "dn29:25.6": "Này các hiền giả, ở đây vị tỳ kheo do đoạn tận ba kiết sử, trở thành bậc nhập lưu, không còn rơi vào đọa xứ, chắc chắn hướng đến giác ngộ.",
  "dn29:25.7": "Đây là kết quả thứ nhất, lợi ích thứ nhất.",
  "dn29:25.8": "Lại nữa, này các hiền giả, vị tỳ kheo do đoạn tận ba kiết sử, làm mỏng tham, sân, si, trở thành bậc nhất lai, chỉ còn trở lại đời này một lần nữa rồi chấm dứt khổ đau.",
  "dn29:25.9": "Đây là kết quả thứ hai, lợi ích thứ hai.",
  "dn29:25.10": "Lại nữa, này các hiền giả, vị tỳ kheo do đoạn tận năm hạ phần kiết sử, được hóa sinh, tại đó nhập niết bàn, không còn trở lui thế gian này nữa.",
  "dn29:25.11": "Đây là kết quả thứ ba, lợi ích thứ ba.",
  "dn29:25.12": "Lại nữa, này các hiền giả, vị tỳ kheo do đoạn tận các lậu hoặc, ngay trong đời này tự mình với thắng trí chứng ngộ, đạt đến và an trú tâm giải thoát không còn lậu hoặc, tuệ giải thoát.",
  "dn29:25.13": "Đây là kết quả thứ tư, lợi ích thứ tư.",
  "dn29:25.14": "Này các hiền giả, những người sống theo bốn sự theo đuổi khoái lạc này có thể mong đợi bốn kết quả này, bốn lợi ích này.’",
  "dn29:26.0": "11. Chín điều bậc lậu tận không thể làm",
  "dn29:26.1": "Này Cunda, có thể xảy ra trường hợp các du sĩ ngoại đạo nói như vầy:",
  "dn29:26.2": "‘Các sa môn con cháu dòng Sakya sống không có nền tảng.’",
  "dn29:26.3": "Này Cunda, với các du sĩ ngoại đạo nói như vậy, nên đáp lại như vầy:",
  "dn29:26.4": "‘Này các hiền giả, có những pháp do Thế Tôn, bậc biết, bậc thấy, bậc A-la-hán, bậc Chánh Đẳng Giác, giảng dạy và chế định cho các đệ tử, không được vượt qua suốt đời.",
  "dn29:26.5": "Ví như một cột trụ hay cột sắt có chân cắm sâu, được chôn rất chắc, không lay chuyển, không rung động;",
  "dn29:26.6": "cũng vậy, này các hiền giả, có những pháp do Thế Tôn, bậc biết, bậc thấy, bậc A-la-hán, bậc Chánh Đẳng Giác, giảng dạy và chế định cho các đệ tử, không được vượt qua suốt đời.",
  "dn29:26.7": "Này các hiền giả, vị tỳ kheo là bậc A-la-hán, lậu hoặc đã tận, đời sống phạm hạnh đã thành, việc cần làm đã làm xong, gánh nặng đã đặt xuống, mục đích mình đã đạt, trói buộc của hữu đã dứt sạch, nhờ chánh trí mà giải thoát, thì không thể phạm vào chín điều.",
  "dn29:26.8": "Này các hiền giả, vị tỳ kheo lậu hoặc đã tận không thể cố ý tước đoạt mạng sống của một sinh vật; không thể lấy của không cho, thành trộm cắp; không thể hành dâm; không thể cố ý nói dối; không thể hưởng thụ các dục được cất chứa như khi còn là người tại gia trước đây; không thể thiên vị vì ưa thích; không thể thiên vị vì ghét bỏ; không thể thiên vị vì mê lầm; không thể thiên vị vì sợ hãi.",
  "dn29:26.9": "Này các hiền giả, vị tỳ kheo là bậc A-la-hán, lậu hoặc đã tận, đời sống phạm hạnh đã thành, việc cần làm đã làm xong, gánh nặng đã đặt xuống, mục đích mình đã đạt, trói buộc của hữu đã dứt sạch, nhờ chánh trí mà giải thoát, thì không thể phạm vào chín điều này.’",
  "dn29:27.0": "12. Trả lời câu hỏi",
  "dn29:27.1": "Này Cunda, có thể xảy ra trường hợp các du sĩ ngoại đạo nói như vầy:",
  "dn29:27.2": "‘Sa môn Gotama nói đến tri kiến vượt mức khi nói về thời quá khứ, nhưng không nói đến tri kiến vượt mức khi nói về thời vị lai; vậy điều ấy là gì, điều ấy như thế nào?’",
  "dn29:27.3": "Các du sĩ ngoại đạo ấy, như những kẻ ngu si, chưa khéo léo, lại nghĩ rằng phải dùng một loại tri kiến bị dẫn đi chỗ khác để trình bày một loại tri kiến bị dẫn đi chỗ khác.",
  "dn29:27.4": "Này Cunda, khi nói về thời quá khứ, Như Lai có trí nhớ theo dấu.",
  "dn29:27.5": "Ngài muốn nhớ lại đến mức nào thì nhớ lại đến mức ấy.",
  "dn29:27.6": "Còn khi nói về thời vị lai, nơi Như Lai khởi lên trí do giác ngộ sinh ra:",
  "dn29:27.7": "‘Đây là đời sống cuối cùng, nay không còn tái sinh nữa.’",
  "dn29:28.1": "Này Cunda, nếu thuộc về quá khứ mà là điều không thật, không đúng, không có ích, thì Như Lai không trả lời điều ấy.",
  "dn29:28.2": "Này Cunda, nếu thuộc về quá khứ mà là điều thật, đúng, nhưng không có ích, thì Như Lai cũng không trả lời điều ấy.",
  "dn29:28.3": "Này Cunda, nếu thuộc về quá khứ mà là điều thật, đúng, có ích, thì Như Lai biết đúng thời để trả lời câu hỏi ấy.",
  "dn29:28.4": "Này Cunda, nếu thuộc về vị lai mà là điều không thật, không đúng, không có ích, thì Như Lai không trả lời điều ấy… biết đúng thời để trả lời câu hỏi ấy.",
  "dn29:28.5": "Này Cunda, nếu thuộc về hiện tại mà là điều không thật, không đúng, không có ích, thì Như Lai không trả lời điều ấy.",
  "dn29:28.6": "Này Cunda, nếu thuộc về hiện tại mà là điều thật, đúng, nhưng không có ích, thì Như Lai cũng không trả lời điều ấy.",
  "dn29:28.7": "Này Cunda, nếu thuộc về hiện tại mà là điều thật, đúng, có ích, thì Như Lai biết đúng thời để trả lời câu hỏi ấy.",
  "dn29:28.8": "Vì vậy, này Cunda, đối với các pháp quá khứ, vị lai và hiện tại, Như Lai là người nói đúng thời, nói sự thật, nói điều có ích, nói pháp, nói giới luật; vì thế được gọi là ‘Như Lai’.",
  "dn29:29.1": "Này Cunda, trong thế gian này cùng với chư thiên, ma vương, phạm thiên, cùng quần chúng sa môn, bà la môn, chư thiên và loài người, điều gì được thấy, được nghe, được cảm nhận, được nhận biết, được đạt đến, được tìm cầu, được suy xét bằng tâm, tất cả đều đã được Như Lai giác ngộ trọn vẹn,",
  "dn29:29.2": "vì thế được gọi là ‘Như Lai’.",
  "dn29:29.3": "Và này Cunda, trong đêm Như Lai chứng ngộ giác ngộ hoàn toàn vô thượng, cho đến đêm Như Lai nhập Niết-bàn không còn dư tàn chấp thủ, điều gì Như Lai nói, trình bày, chỉ dạy trong khoảng giữa hai đêm ấy, tất cả đều đúng như vậy, không khác đi, ",
  "dn29:29.4": "nên được gọi là ‘Như Lai’. ",
  "dn29:29.5": "Này Cunda, Như Lai nói sao làm vậy, làm sao nói vậy. ",
  "dn29:29.6": "Vì nói sao làm vậy, làm sao nói vậy, nên được gọi là ‘Như Lai’. ",
  "dn29:29.7": "Này Cunda, trong thế gian này cùng với chư thiên, ma vương, phạm thiên, cùng quần chúng sa-môn, bà-la-môn, chư thiên và loài người, Như Lai là bậc vượt hơn tất cả, không ai vượt hơn, thấy biết khác biệt, tự tại, nên được gọi là ‘Như Lai’. ",
  "dn29:30.0": "13. Những điều không được trả lời ",
  "dn29:30.1": "Này Cunda, có trường hợp các du sĩ ngoại đạo có thể nói như vầy: ",
  "dn29:30.2": "‘Này hiền hữu, sau khi chết Như Lai còn tồn tại chăng? Chỉ điều này là thật, ngoài ra đều sai lầm chăng?’ ",
  "dn29:30.3": "Này Cunda, với các du sĩ ngoại đạo nói như vậy, nên trả lời như sau: ",
  "dn29:30.4": "‘Này hiền hữu, điều ấy Thế Tôn không trả lời: ",
  "dn29:30.5": "“Sau khi chết Như Lai còn tồn tại, chỉ điều này là thật, ngoài ra đều sai lầm.”’ ",
  "dn29:30.6": "Này Cunda, có trường hợp các du sĩ ngoại đạo có thể nói như vầy: ",
  "dn29:30.7": "‘Này hiền hữu, vậy sau khi chết Như Lai không còn tồn tại chăng? Chỉ điều này là thật, ngoài ra đều sai lầm chăng?’ ",
  "dn29:30.8": "Này Cunda, với các du sĩ ngoại đạo nói như vậy, nên trả lời như sau: ",
  "dn29:30.9": "‘Này hiền hữu, điều này nữa Thế Tôn cũng không trả lời: ",
  "dn29:30.10": "“Sau khi chết Như Lai không còn tồn tại, chỉ điều này là thật, ngoài ra đều sai lầm.”’ ",
  "dn29:30.11": "Này Cunda, có trường hợp các du sĩ ngoại đạo có thể nói như vầy: ",
  "dn29:30.12": "‘Này hiền hữu, vậy sau khi chết Như Lai vừa còn tồn tại vừa không còn tồn tại chăng? Chỉ điều này là thật, ngoài ra đều sai lầm chăng?’ ",
  "dn29:30.13": "Này Cunda, với các du sĩ ngoại đạo nói như vậy, nên trả lời như sau: ",
  "dn29:30.14": "‘Này hiền hữu, điều ấy Thế Tôn không trả lời: ",
  "dn29:30.15": "“Sau khi chết Như Lai vừa còn tồn tại vừa không còn tồn tại, chỉ điều này là thật, ngoài ra đều sai lầm.”’ ",
  "dn29:30.16": "Này Cunda, có trường hợp các du sĩ ngoại đạo có thể nói như vầy: ",
  "dn29:30.17": "‘Này hiền hữu, vậy sau khi chết Như Lai không phải còn tồn tại cũng không phải không còn tồn tại chăng? Chỉ điều này là thật, ngoài ra đều sai lầm chăng?’ ",
  "dn29:30.18": "Này Cunda, với các du sĩ ngoại đạo nói như vậy, nên trả lời như sau: ",
  "dn29:30.19": "‘Này hiền hữu, điều này nữa Thế Tôn cũng không trả lời: ",
  "dn29:30.20": "“Sau khi chết Như Lai không phải còn tồn tại cũng không phải không còn tồn tại, chỉ điều này là thật, ngoài ra đều sai lầm.”’ ",
  "dn29:31.1": "Này Cunda, có trường hợp các du sĩ ngoại đạo có thể nói như vầy: ",
  "dn29:31.2": "‘Này hiền hữu, vì sao Sa-môn Gotama không trả lời điều ấy?’ ",
  "dn29:31.3": "Này Cunda, với các du sĩ ngoại đạo nói như vậy, nên trả lời như sau: ",
  "dn29:31.4": "‘Này hiền hữu, vì điều ấy không gắn với lợi ích, không gắn với pháp, không thuộc căn bản của đời sống phạm hạnh, không đưa đến chán lìa, không đưa đến buông bỏ, không đưa đến chấm dứt, không đưa đến lắng dịu, không đưa đến thắng tri, không đưa đến giác ngộ, không đưa đến Niết-bàn, nên Thế Tôn không trả lời điều ấy.’ ",
  "dn29:32.0": "14. Những điều được trả lời ",
  "dn29:32.1": "Này Cunda, có trường hợp các du sĩ ngoại đạo có thể nói như vầy: ",
  "dn29:32.2": "‘Này hiền hữu, vậy Sa-môn Gotama đã trả lời điều gì?’ ",
  "dn29:32.3": "Này Cunda, với các du sĩ ngoại đạo nói như vậy, nên trả lời như sau: ",
  "dn29:32.4": "‘Này hiền hữu, “đây là khổ” là điều Thế Tôn đã trả lời; “đây là nguồn gốc của khổ” là điều Thế Tôn đã trả lời; “đây là sự chấm dứt của khổ” là điều Thế Tôn đã trả lời; “đây là con đường đưa đến chấm dứt khổ” là điều Thế Tôn đã trả lời.’ ",
  "dn29:33.1": "Này Cunda, có trường hợp các du sĩ ngoại đạo có thể nói như vầy: ",
  "dn29:33.2": "‘Này hiền hữu, vì sao Sa-môn Gotama đã trả lời điều ấy?’ ",
  "dn29:33.3": "Này Cunda, với các du sĩ ngoại đạo nói như vậy, nên trả lời như sau: ",
  "dn29:33.4": "‘Này hiền hữu, vì điều ấy gắn với lợi ích, gắn với pháp, thuộc căn bản của đời sống phạm hạnh, chắc chắn đưa đến chán lìa, buông bỏ, chấm dứt, lắng dịu, thắng tri, giác ngộ, Niết-bàn. Vì vậy Thế Tôn đã trả lời điều ấy.’ ",
  "dn29:34.0": "15. Nương vào các quan điểm về quá khứ ",
  "dn29:34.1": "Này Cunda, những chỗ nương tựa của các quan điểm liên hệ đến quá khứ ấy, ta cũng đã giải rõ cho các ông, theo cách chúng cần được giải rõ. ",
  "dn29:34.2": "Còn những điều không nên giải rõ theo cách ấy, lẽ nào ta lại giải rõ như vậy cho các ông? ",
  "dn29:34.3": "Này Cunda, những chỗ nương tựa của các quan điểm liên hệ đến tương lai ấy, ta cũng đã giải rõ cho các ông, theo cách chúng cần được giải rõ. ",
  "dn29:34.4": "Còn những điều không nên giải rõ theo cách ấy, lẽ nào ta lại giải rõ như vậy cho các ông? ",
  "dn29:34.5": "Và này Cunda, những chỗ nương tựa của các quan điểm liên hệ đến quá khứ nào là những điều ta đã giải rõ cho các ông, theo cách chúng cần được giải rõ? ",
  "dn29:34.6": "Còn những điều không nên giải rõ theo cách ấy, lẽ nào ta lại giải rõ như vậy cho các ông? ",
  "dn29:34.7": "Này Cunda, có một số sa-môn, bà-la-môn nói như vầy, có quan điểm như vầy: ",
  "dn29:34.8": "‘Bản ngã và thế giới là thường còn, chỉ điều này là thật, ngoài ra đều sai lầm.’ ",
  "dn29:34.9": "Này Cunda, lại có một số sa-môn, bà-la-môn nói như vầy, có quan điểm như vầy: ",
  "dn29:34.10": "‘Bản ngã và thế giới là không thường còn …pe… ",
  "dn29:34.11": "ngã và thế gian là thường còn và không thường còn…",
  "dn29:34.12": "ngã và thế gian không phải thường còn cũng không phải không thường còn…",
  "dn29:34.13": "ngã và thế gian do tự mình làm ra…",
  "dn29:34.14": "ngã và thế gian do cái khác làm ra…",
  "dn29:34.15": "ngã và thế gian do tự mình làm ra và do cái khác làm ra…",
  "dn29:34.16": "ngã và thế gian không do tự mình làm ra, không do cái khác làm ra, mà sinh khởi ngẫu nhiên; chỉ đây mới là thật, ngoài ra đều sai lầm.",
  "dn29:34.17": "khổ vui là thường còn…",
  "dn29:34.18": "khổ vui là không thường còn…",
  "dn29:34.19": "khổ vui là thường còn và không thường còn…",
  "dn29:34.20": "khổ vui không phải thường còn cũng không phải không thường còn…",
  "dn29:34.21": "khổ vui do tự mình làm ra…",
  "dn29:34.22": "khổ vui do cái khác làm ra…",
  "dn29:34.23": "khổ vui do tự mình làm ra và do cái khác làm ra…",
  "dn29:34.24": "khổ vui không do tự mình làm ra, không do cái khác làm ra, mà sinh khởi ngẫu nhiên; chỉ đây mới là thật, ngoài ra đều sai lầm.",
  "dn29:35.1": "Này Cunda, ở đây có những sa môn, bà la môn chủ trương như vầy, thấy như vầy:",
  "dn29:35.2": "‘ngã và thế gian là thường còn; chỉ đây mới là thật, ngoài ra đều sai lầm.’",
  "dn29:35.3": "Ta đến gặp họ rồi nói như vầy:",
  "dn29:35.4": "‘Này hiền giả, có phải điều này được nói là:",
  "dn29:35.5": "“ngã và thế gian là thường còn” chăng?’",
  "dn29:35.6": "Và điều họ nói như vầy:",
  "dn29:35.7": "‘chỉ đây mới là thật, ngoài ra đều sai lầm.’",
  "dn29:35.8": "Ta không chấp nhận điều ấy của họ.",
  "dn29:35.9": "Vì sao vậy?",
  "dn29:35.10": "Vì ở đây, này Cunda, có một số chúng sinh nhận biết khác đi.",
  "dn29:35.11": "Ngay cả với cách nói này, này Cunda, ta cũng không thấy mình ngang bằng với ai, huống gì hơn.",
  "dn29:35.12": "Nhưng ở đây, chính ta là người hơn, tức là ở chỗ nêu bày vượt lên.",
  "dn29:36.1": "Này Cunda, ở đây có những sa môn, bà la môn chủ trương như vầy, thấy như vầy:",
  "dn29:36.2": "‘ngã và thế gian là không thường còn…",
  "dn29:36.3": "ngã và thế gian là thường còn và không thường còn…",
  "dn29:36.4": "ngã và thế gian không phải thường còn cũng không phải không thường còn…",
  "dn29:36.5": "ngã và thế gian do tự mình làm ra…",
  "dn29:36.6": "ngã và thế gian do cái khác làm ra…",
  "dn29:36.7": "ngã và thế gian do tự mình làm ra và do cái khác làm ra…",
  "dn29:36.8": "ngã và thế gian không do tự mình làm ra, không do cái khác làm ra, mà sinh khởi ngẫu nhiên…",
  "dn29:36.9": "khổ vui là thường còn…",
  "dn29:36.10": "khổ vui là không thường còn…",
  "dn29:36.11": "khổ vui là thường còn và không thường còn…",
  "dn29:36.12": "khổ vui không phải thường còn cũng không phải không thường còn…",
  "dn29:36.13": "khổ vui do tự mình làm ra…",
  "dn29:36.14": "khổ vui do cái khác làm ra…",
  "dn29:36.15": "khổ vui do tự mình làm ra và do cái khác làm ra…",
  "dn29:36.16": "khổ vui không do tự mình làm ra, không do cái khác làm ra, mà sinh khởi ngẫu nhiên; chỉ đây mới là thật, ngoài ra đều sai lầm.’",
  "dn29:36.17": "Ta đến gặp họ rồi nói như vầy:",
  "dn29:36.18": "‘Này hiền giả, có phải điều này được nói là:",
  "dn29:36.19": "“khổ vui không do tự mình làm ra, không do cái khác làm ra, mà sinh khởi ngẫu nhiên” chăng?’",
  "dn29:36.20": "Và điều họ nói như vầy:",
  "dn29:36.21": "‘chỉ đây mới là thật, ngoài ra đều sai lầm.’",
  "dn29:36.22": "Ta không chấp nhận điều ấy của họ.",
  "dn29:36.23": "Vì sao vậy?",
  "dn29:36.24": "Vì ở đây, này Cunda, có một số chúng sinh nhận biết khác đi.",
  "dn29:36.25": "Ngay cả với cách nói này, này Cunda, ta cũng không thấy ai ngang bằng với mình, huống gì hơn.",
  "dn29:36.26": "Trái lại, ở điểm này chính ta là người vượt hơn, tức là ở chỗ chỉ bày vượt trội.",
  "dn29:36.27": "Này Cunda, đó là những chỗ nương tựa của các quan điểm liên hệ đến quá khứ, đã được ta giải đáp cho các ông đúng như cần phải giải đáp.",
  "dn29:36.28": "Còn những gì không nên giải đáp theo cách ấy, sao ta lại giải đáp cho các ông như vậy?",
  "dn29:37.0": "16. Chỗ nương tựa của các quan điểm liên hệ đến tương lai",
  "dn29:37.1": "Và này Cunda, thế nào là những chỗ nương tựa của các quan điểm liên hệ đến tương lai, đã được ta giải đáp cho các ông đúng như cần phải giải đáp?",
  "dn29:37.2": "Còn những gì không nên giải đáp theo cách ấy, sao ta lại giải đáp cho các ông như vậy?",
  "dn29:37.3": "Này Cunda, có một số sa môn, bà la môn nói như vầy, thấy như vầy:",
  "dn29:37.4": "‘Tự ngã là có sắc, không bệnh, sau khi chết vẫn còn; chỉ đây là thật, ngoài ra đều sai lầm.’",
  "dn29:37.5": "Lại nữa, này Cunda, có một số sa môn, bà la môn nói như vầy, thấy như vầy:",
  "dn29:37.6": "‘Tự ngã là không sắc …",
  "dn29:37.7": "Tự ngã vừa có sắc vừa không sắc …",
  "dn29:37.8": "Tự ngã không phải có sắc cũng không phải không sắc …",
  "dn29:37.9": "Tự ngã có tưởng …",
  "dn29:37.10": "Tự ngã không có tưởng …",
  "dn29:37.11": "Tự ngã không phải có tưởng cũng không phải không có tưởng …",
  "dn29:37.12": "Tự ngã bị đoạn diệt, tiêu mất, không còn sau khi chết; chỉ đây là thật, ngoài ra đều sai lầm.’",
  "dn29:38.1": "Ở đây, này Cunda, đối với những sa môn, bà la môn nói như vầy, thấy như vầy:",
  "dn29:38.2": "‘Tự ngã là có sắc, không bệnh, sau khi chết vẫn còn; chỉ đây là thật, ngoài ra đều sai lầm.’",
  "dn29:38.3": "Ta đến gặp họ rồi nói như vầy:",
  "dn29:38.4": "‘Này hiền hữu, có thật là điều này được nói rằng:",
  "dn29:38.5": "“Tự ngã là có sắc, không bệnh, sau khi chết vẫn còn” chăng?’",
  "dn29:38.6": "Và điều họ nói như vậy là:",
  "dn29:38.7": "‘Chỉ đây là thật, ngoài ra đều sai lầm.’",
  "dn29:38.8": "Điều ấy ta không chấp nhận.",
  "dn29:38.9": "Vì sao vậy?",
  "dn29:38.10": "Vì ở đây, này Cunda, vẫn có một số chúng sinh có nhận biết khác như thế.",
  "dn29:38.11": "Ngay cả với cách nói này, này Cunda, ta cũng không thấy ai ngang bằng với mình, huống gì hơn.",
  "dn29:38.12": "Trái lại, ở điểm này chính ta là người vượt hơn, tức là ở chỗ chỉ bày vượt trội.",
  "dn29:39.1": "Ở đây, này Cunda, đối với những sa môn, bà la môn nói như vầy, thấy như vầy:",
  "dn29:39.2": "‘Tự ngã là không sắc …",
  "dn29:39.3": "Tự ngã vừa có sắc vừa không sắc …",
  "dn29:39.4": "Tự ngã không phải có sắc cũng không phải không sắc …",
  "dn29:39.5": "Tự ngã có tưởng …",
  "dn29:39.6": "Tự ngã không có tưởng …",
  "dn29:39.7": "Tự ngã không phải có tưởng cũng không phải không có tưởng …",
  "dn29:39.8": "Tự ngã bị đoạn diệt, tiêu mất, không còn sau khi chết; chỉ đây là thật, ngoài ra đều sai lầm.’",
  "dn29:39.9": "Ta đến gặp họ rồi nói như vầy:",
  "dn29:39.10": "‘Này hiền hữu, có thật là điều này được nói rằng:",
  "dn29:39.11": "“Tự ngã bị đoạn diệt, tiêu mất, không còn sau khi chết” chăng?’",
  "dn29:39.12": "Và điều họ, này Cunda, nói như vậy là:",
  "dn29:39.13": "‘Chỉ đây là thật, ngoài ra đều sai lầm.’",
  "dn29:39.14": "Điều ấy ta không chấp nhận.",
  "dn29:39.15": "Vì sao vậy?",
  "dn29:39.16": "Vì ở đây, này Cunda, vẫn có một số chúng sinh có nhận biết khác như thế.",
  "dn29:39.17": "Ngay cả với cách nói này, này Cunda, ta cũng không thấy ai ngang bằng với mình, huống gì hơn.",
  "dn29:39.18": "Trái lại, ở điểm này chính ta là người vượt hơn, tức là ở chỗ chỉ bày vượt trội.",
  "dn29:39.19": "Này Cunda, đó là những chỗ nương tựa của các quan điểm liên hệ đến tương lai, đã được ta giải đáp cho các ông đúng như cần phải giải đáp.",
  "dn29:39.20": "Còn những gì không nên giải đáp theo cách ấy, sao ta lại giải đáp cho các ông như vậy?",
  "dn29:40.1": "Và này Cunda, để từ bỏ và vượt qua những chỗ nương tựa của các quan điểm liên hệ đến quá khứ này và những chỗ nương tựa của các quan điểm liên hệ đến tương lai này, ta đã giảng dạy và chỉ bày bốn niệm xứ như vậy.",
  "dn29:40.2": "Bốn điều ấy là gì?",
  "dn29:40.3": "Ở đây, này Cunda, vị tỳ kheo sống quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, đã dẹp bỏ tham muốn và buồn phiền đối với đời.",
  "dn29:40.4": "Quán cảm thọ trên các cảm thọ …",
  "dn29:40.5": "Quán tâm trên tâm …",
  "dn29:40.6": "Quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, đã dẹp bỏ tham muốn và buồn phiền đối với đời.",
  "dn29:40.7": "Và này Cunda, để đoạn trừ, vượt qua những chỗ nương tựa của các quan điểm liên hệ đến quá khứ ấy và những chỗ nương tựa của các quan điểm liên hệ đến tương lai ấy. Như vậy, Ta đã giảng dạy, đã chỉ bày bốn niệm xứ này.”",
  "dn29:41.1": "Lúc bấy giờ, tôn giả Upavāṇa đang đứng phía sau Thế Tôn, quạt hầu Thế Tôn.",
  "dn29:41.2": "Rồi tôn giả Upavāṇa bạch Thế Tôn:",
  "dn29:41.3": "“Thật kỳ diệu, bạch Thế Tôn, thật lạ thường, bạch Thế Tôn.",
  "dn29:41.4": "Pháp môn này thật làm cho người ta sinh lòng tin, bạch Thế Tôn;",
  "dn29:41.5": "pháp môn này thật rất làm cho người ta sinh lòng tin, bạch Thế Tôn, pháp môn này tên là gì?”",
  "dn29:41.6": "“Vậy thì, này Upavāṇa, ông hãy ghi nhớ pháp môn này chính là ‘Làm phát sinh lòng tin’.”",
  "dn29:41.7": "Thế Tôn nói như vậy.",
  "dn29:41.8": "Tôn giả Upavāṇa hoan hỷ, vui nhận lời dạy của Thế Tôn.",
  "dn29:41.9": "Kinh Pāsādika chấm dứt, bài thứ sáu."
}
window.BILARA["dn29"]["vi"]["dn29:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
