window.BILARA = window.BILARA || {};
window.BILARA["dn34"] = window.BILARA["dn34"] || {};
window.BILARA["dn34"]["vi"] = {
  "dn34:0.1": "Trường Bộ Kinh 34",
  "dn34:0.2": "Kinh Tăng Thượng Thập Pháp",
  "dn34:1.1.1": "Tôi nghe như vầy—",
  "dn34:1.1.2": "Một thời, Thế Tôn ở tại Campā, bên bờ hồ Gaggarā, cùng với đại chúng tỳ-kheo gồm khoảng năm trăm vị tỳ-kheo.",
  "dn34:1.1.3": "Tại đó, tôn giả Sāriputta gọi các tỳ-kheo:",
  "dn34:1.1.4": "“Này các hiền giả tỳ-kheo.”",
  "dn34:1.1.5": "Các tỳ-kheo ấy đáp lời tôn giả Sāriputta: “Thưa hiền giả.”",
  "dn34:1.1.6": "Tôn giả Sāriputta nói như sau:",
  "dn34:1.1.7": "“Tôi sẽ giảng pháp tăng thượng đến mười,",
  "dn34:1.1.8": "là pháp đưa đến chứng đạt niết-bàn;",
  "dn34:1.1.9": "để chấm dứt khổ đau,",
  "dn34:1.1.10": "tháo mở mọi trói buộc.",
  "dn34:1.2.0": "1. Một pháp",
  "dn34:1.2.1": "Này các hiền giả, có một pháp rất lợi ích, một pháp cần được tu tập, một pháp cần được hiểu rõ, một pháp cần được từ bỏ, một pháp thuộc phần suy giảm, một pháp thuộc phần vượt trội, một pháp khó thấu đạt, một pháp cần được khởi lên, một pháp cần được thắng tri, một pháp cần được chứng ngộ.",
  "dn34:1.2.2": "Một pháp rất lợi ích là pháp nào?",
  "dn34:1.2.3": "Không phóng dật trong các pháp lành.",
  "dn34:1.2.4": "Đó là một pháp rất lợi ích.",
  "dn34:1.2.5": "Một pháp cần được tu tập là pháp nào?",
  "dn34:1.2.6": "Niệm về thân đi cùng an lạc.",
  "dn34:1.2.7": "Đó là một pháp cần được tu tập.",
  "dn34:1.2.8": "Một pháp cần được hiểu rõ là pháp nào?",
  "dn34:1.2.9": "Xúc có lậu hoặc, đáng chấp thủ.",
  "dn34:1.2.10": "Đó là một pháp cần được hiểu rõ.",
  "dn34:1.2.11": "Một pháp cần được từ bỏ là pháp nào?",
  "dn34:1.2.12": "Ngã mạn.",
  "dn34:1.2.13": "Đó là một pháp cần được từ bỏ.",
  "dn34:1.2.14": "Một pháp thuộc phần suy giảm là pháp nào?",
  "dn34:1.2.15": "Tác ý không đúng đắn.",
  "dn34:1.2.16": "Đó là một pháp thuộc phần suy giảm.",
  "dn34:1.2.17": "Một pháp thuộc phần vượt trội là pháp nào?",
  "dn34:1.2.18": "Tác ý đúng đắn.",
  "dn34:1.2.19": "Đó là một pháp thuộc phần vượt trội.",
  "dn34:1.2.20": "Một pháp khó thấu đạt là pháp nào?",
  "dn34:1.2.21": "Định tâm liền kề.",
  "dn34:1.2.22": "Đó là một pháp khó thấu đạt.",
  "dn34:1.2.23": "Một pháp cần được khởi lên là pháp nào?",
  "dn34:1.2.24": "Trí không lay chuyển.",
  "dn34:1.2.25": "Đó là một pháp cần được khởi lên.",
  "dn34:1.2.26": "Một pháp cần được thắng tri là pháp nào?",
  "dn34:1.2.27": "Tất cả chúng sinh tồn tại nhờ thức ăn.",
  "dn34:1.2.28": "Đó là một pháp cần được thắng tri.",
  "dn34:1.2.29": "Một pháp cần được chứng ngộ là pháp nào?",
  "dn34:1.2.30": "Giải thoát tâm không lay chuyển.",
  "dn34:1.2.31": "Đó là một pháp cần được chứng ngộ.",
  "dn34:1.2.32": "Như vậy, mười pháp này là có thật, chân thật, đúng như vậy, không sai khác, không khác đi, được Như Lai chánh giác hoàn toàn.",
  "dn34:1.3.0": "2. Hai pháp",
  "dn34:1.3.1": "Có hai pháp rất lợi ích, hai pháp cần được tu tập, hai pháp cần được hiểu rõ, hai pháp cần được từ bỏ, hai pháp thuộc phần suy giảm, hai pháp thuộc phần vượt trội, hai pháp khó thấu đạt, hai pháp cần được khởi lên, hai pháp cần được thắng tri, hai pháp cần được chứng ngộ.",
  "dn34:1.3.2": "Hai pháp rất lợi ích là những pháp nào?",
  "dn34:1.3.3": "Niệm và tỉnh giác.",
  "dn34:1.3.4": "Đó là hai pháp rất lợi ích.",
  "dn34:1.3.5": "Hai pháp nào cần được tu tập?",
  "dn34:1.3.6": "Chỉ và quán.",
  "dn34:1.3.7": "Đó là hai pháp cần được tu tập.",
  "dn34:1.3.8": "Hai pháp nào cần được hiểu thấu?",
  "dn34:1.3.9": "Danh và sắc.",
  "dn34:1.3.10": "Đó là hai pháp cần được hiểu thấu.",
  "dn34:1.3.11": "Hai pháp nào cần được từ bỏ?",
  "dn34:1.3.12": "Vô minh và ái hữu.",
  "dn34:1.3.13": "Đó là hai pháp cần được từ bỏ.",
  "dn34:1.3.14": "Hai pháp nào thuộc về phần sa sút?",
  "dn34:1.3.15": "Khó dạy và bạn xấu.",
  "dn34:1.3.16": "Đó là hai pháp thuộc về phần sa sút.",
  "dn34:1.3.17": "Hai pháp nào thuộc về phần vượt trội?",
  "dn34:1.3.18": "Dễ dạy và bạn lành.",
  "dn34:1.3.19": "Đó là hai pháp thuộc về phần vượt trội.",
  "dn34:1.3.20": "Hai pháp nào khó thấu hiểu?",
  "dn34:1.3.21": "Nhân nào và duyên nào khiến chúng sinh bị ô nhiễm, và nhân nào và duyên nào khiến chúng sinh được trong sạch.",
  "dn34:1.3.22": "Đó là hai pháp khó thấu hiểu.",
  "dn34:1.3.23": "Hai pháp nào cần được khởi lên?",
  "dn34:1.3.24": "Hai loại trí—",
  "dn34:1.3.25": "trí về sự đoạn diệt, trí về sự không sinh khởi.",
  "dn34:1.3.26": "Đó là hai pháp cần được khởi lên.",
  "dn34:1.3.27": "Hai pháp nào cần được thắng tri?",
  "dn34:1.3.28": "Hai giới—",
  "dn34:1.3.29": "giới hữu vi và giới vô vi.",
  "dn34:1.3.30": "Đó là hai pháp cần được thắng tri.",
  "dn34:1.3.31": "Hai pháp nào cần được chứng ngộ?",
  "dn34:1.3.32": "Minh và giải thoát.",
  "dn34:1.3.33": "Đó là hai pháp cần được chứng ngộ.",
  "dn34:1.3.34": "Như vậy, hai mươi pháp này là chân thật, đúng thật, như thật, không sai khác, không khác đi, đã được Như Lai tự mình giác ngộ trọn vẹn.",
  "dn34:1.4.0": "3. Ba pháp",
  "dn34:1.4.1": "Ba pháp có nhiều lợi ích, ba pháp cần được tu tập … ba pháp cần được chứng ngộ.",
  "dn34:1.4.2": "Ba pháp nào có nhiều lợi ích?",
  "dn34:1.4.3": "Gần gũi người chân chánh, nghe chánh pháp, thực hành đúng theo pháp.",
  "dn34:1.4.4": "Đó là ba pháp có nhiều lợi ích.",
  "dn34:1.4.5": "Ba pháp nào cần được tu tập?",
  "dn34:1.4.6": "Ba loại định—",
  "dn34:1.4.7": "định có tầm có tứ, định không tầm chỉ còn tứ, định không tầm không tứ.",
  "dn34:1.4.8": "Đó là ba pháp cần được tu tập.",
  "dn34:1.4.9": "Ba pháp nào cần được hiểu thấu?",
  "dn34:1.4.10": "Ba cảm thọ—",
  "dn34:1.4.11": "cảm thọ vui, cảm thọ khổ, cảm thọ không khổ không vui.",
  "dn34:1.4.12": "Đó là ba pháp cần được hiểu thấu.",
  "dn34:1.4.13": "Ba pháp nào cần được từ bỏ?",
  "dn34:1.4.14": "Ba ái—",
  "dn34:1.4.15": "ái dục, ái hữu, ái phi hữu.",
  "dn34:1.4.16": "Đó là ba pháp cần được từ bỏ.",
  "dn34:1.4.17": "Ba pháp nào thuộc về phần sa sút?",
  "dn34:1.4.18": "Ba gốc bất thiện—",
  "dn34:1.4.19": "tham là gốc bất thiện, sân là gốc bất thiện, si là gốc bất thiện.",
  "dn34:1.4.20": "Đó là ba pháp thuộc phần sa sút.",
  "dn34:1.4.21": "Ba pháp nào thuộc phần vượt trội?",
  "dn34:1.4.22": "Ba gốc lành là:",
  "dn34:1.4.23": "không tham là gốc lành, không sân là gốc lành, không si là gốc lành.",
  "dn34:1.4.24": "Đó là ba pháp thuộc phần vượt trội.",
  "dn34:1.4.25": "Ba pháp nào khó thấu hiểu?",
  "dn34:1.4.26": "Ba giới thoát ra là:",
  "dn34:1.4.27": "xuất ly là lối thoát ra khỏi các dục; vô sắc là lối thoát ra khỏi các sắc; còn bất cứ điều gì đã thành, có tạo tác, do duyên mà sinh, thì sự diệt của nó là lối thoát ra khỏi nó.",
  "dn34:1.4.28": "Đó là ba pháp khó thấu hiểu.",
  "dn34:1.4.29": "Ba pháp nào cần được làm cho sinh khởi?",
  "dn34:1.4.30": "Ba loại trí là:",
  "dn34:1.4.31": "trí về phần quá khứ, trí về phần vị lai, trí về phần hiện tại.",
  "dn34:1.4.32": "Đó là ba pháp cần được làm cho sinh khởi.",
  "dn34:1.4.33": "Ba pháp nào cần được thắng tri?",
  "dn34:1.4.34": "Ba giới là:",
  "dn34:1.4.35": "giới dục, giới sắc, giới vô sắc.",
  "dn34:1.4.36": "Đó là ba pháp cần được thắng tri.",
  "dn34:1.4.37": "Ba pháp nào cần được chứng ngộ?",
  "dn34:1.4.38": "Ba minh là:",
  "dn34:1.4.39": "trí nhớ các đời sống trước là minh, trí biết sự chết và tái sinh của chúng sinh là minh, trí biết sự đoạn tận các lậu hoặc là minh.",
  "dn34:1.4.40": "Đó là ba pháp cần được chứng ngộ.",
  "dn34:1.4.41": "Như vậy, ba mươi pháp này là có thật, chân thật, đúng như vậy, không sai khác, được Như Lai tự mình giác ngộ trọn vẹn.",
  "dn34:1.5.0": "4. Bốn pháp",
  "dn34:1.5.1": "Bốn pháp có nhiều lợi ích, bốn pháp cần được tu tập … bốn pháp cần được chứng ngộ.",
  "dn34:1.5.2": "Bốn pháp nào có nhiều lợi ích?",
  "dn34:1.5.3": "Bốn bánh xe là:",
  "dn34:1.5.4": "sống ở nơi thích hợp, nương tựa người tốt, tự đặt mình đúng hướng, và trước đây đã làm phước.",
  "dn34:1.5.5": "Đó là bốn pháp có nhiều lợi ích.",
  "dn34:1.5.6": "Bốn pháp nào cần được tu tập?",
  "dn34:1.5.7": "Bốn niệm xứ là:",
  "dn34:1.5.8": "Này các hiền giả, ở đây vị tỳ kheo sống quán thân trên thân, nhiệt tâm, tỉnh giác, có chánh niệm, đã dẹp bỏ tham muốn và buồn phiền đối với đời.",
  "dn34:1.5.9": "Đối với các cảm thọ …",
  "dn34:1.5.10": "đối với tâm …",
  "dn34:1.5.11": "đối với các pháp, vị ấy sống quán pháp trên các pháp, nhiệt tâm, tỉnh giác, có chánh niệm, đã dẹp bỏ tham muốn và buồn phiền đối với đời.",
  "dn34:1.5.12": "Đó là bốn pháp cần được tu tập.",
  "dn34:1.5.13": "Bốn pháp nào cần được hiểu rõ trọn vẹn?",
  "dn34:1.5.14": "Bốn món nuôi dưỡng là:",
  "dn34:1.5.15": "đồ ăn vật chất, thô hay tế; xúc là thứ hai; tác ý của tâm là thứ ba; thức là thứ tư.",
  "dn34:1.5.16": "Đó là bốn pháp cần được hiểu rõ trọn vẹn.",
  "dn34:1.5.17": "Bốn pháp nào cần được từ bỏ?",
  "dn34:1.5.18": "Bốn dòng nước cuốn là:",
  "dn34:1.5.19": "dòng nước cuốn của dục, dòng nước cuốn của hiện hữu, dòng nước cuốn của tà kiến, dòng nước cuốn của vô minh.",
  "dn34:1.5.20": "Đó là bốn pháp cần được từ bỏ.",
  "dn34:1.5.21": "Bốn pháp nào thuộc phần sa sút?",
  "dn34:1.5.22": "Bốn sự trói buộc là:",
  "dn34:1.5.23": "trói buộc bởi dục, trói buộc bởi hiện hữu, trói buộc bởi tà kiến, trói buộc bởi vô minh.",
  "dn34:1.5.24": "Đó là bốn pháp thuộc phần sa sút.",
  "dn34:1.5.25": "Bốn pháp nào thuộc phần vượt trội?",
  "dn34:1.5.26": "Bốn sự không còn trói buộc là:",
  "dn34:1.5.27": "không còn bị trói buộc bởi dục, không còn bị trói buộc bởi hiện hữu, không còn bị trói buộc bởi tà kiến, không còn bị trói buộc bởi vô minh.",
  "dn34:1.5.28": "Đây là bốn pháp thuộc phần thù thắng.",
  "dn34:1.5.29": "Bốn pháp nào khó thấu suốt?",
  "dn34:1.5.30": "Bốn định —",
  "dn34:1.5.31": "định thuộc phần sa sút, định thuộc phần an trụ, định thuộc phần thù thắng, định thuộc phần đột phá.",
  "dn34:1.5.32": "Đây là bốn pháp khó thấu suốt.",
  "dn34:1.5.33": "Bốn pháp nào cần được làm khởi lên?",
  "dn34:1.5.34": "Bốn trí —",
  "dn34:1.5.35": "trí về pháp, trí theo sự liên hệ, trí bao quát, trí theo quy ước.",
  "dn34:1.5.36": "Đây là bốn pháp cần được làm khởi lên.",
  "dn34:1.5.37": "Bốn pháp nào cần được thắng tri?",
  "dn34:1.5.38": "Bốn sự thật của bậc thánh —",
  "dn34:1.5.39": "sự thật của bậc thánh về khổ, sự thật của bậc thánh về nguồn gốc của khổ, sự thật của bậc thánh về sự chấm dứt khổ, sự thật của bậc thánh về con đường đưa đến chấm dứt khổ.",
  "dn34:1.5.40": "Đây là bốn pháp cần được thắng tri.",
  "dn34:1.5.41": "Bốn pháp nào cần được tự mình chứng ngộ?",
  "dn34:1.5.42": "Bốn quả của đời sống xuất gia —",
  "dn34:1.5.43": "quả dự lưu, quả nhất lai, quả bất lai, quả A-la-hán.",
  "dn34:1.5.44": "Đây là bốn pháp cần được tự mình chứng ngộ.",
  "dn34:1.5.45": "Như vậy, bốn mươi pháp này là có thật, chân thật, đúng như vậy, không sai khác, được Như Lai giác ngộ trọn vẹn một cách đúng đắn.",
  "dn34:1.6.0": "5. Năm pháp",
  "dn34:1.6.1": "Năm pháp có nhiều lợi ích … năm pháp cần được tự mình chứng ngộ.",
  "dn34:1.6.2": "Năm pháp nào có nhiều lợi ích?",
  "dn34:1.6.3": "Năm chi phần của sự tinh cần —",
  "dn34:1.6.4": "Này các hiền giả, ở đây vị tỳ-kheo có lòng tin, tin nơi sự giác ngộ của Như Lai:",
  "dn34:1.6.5": "‘Thế Tôn ấy thật là bậc Ứng Cúng, bậc Chánh Đẳng Giác, đầy đủ trí và hạnh, khéo đi, hiểu rõ đời, bậc dẫn dắt người cần được điều phục không ai hơn, bậc thầy của chư thiên và loài người, bậc Giác Ngộ, Thế Tôn.’",
  "dn34:1.6.6": "Vị ấy ít bệnh, ít não, có sức tiêu hóa điều hòa, không quá lạnh, không quá nóng, vừa phải, chịu đựng được sự tinh cần.",
  "dn34:1.6.7": "Vị ấy không gian dối, không lừa gạt, bộc lộ đúng như thật về mình với bậc Đạo Sư hoặc với các vị đồng phạm hạnh có trí.",
  "dn34:1.6.8": "Vị ấy sống với tinh tấn được khơi dậy để từ bỏ các pháp bất thiện, để thành tựu các pháp thiện, có sức mạnh, nỗ lực vững chắc, không buông bỏ gánh nặng trong các pháp thiện.",
  "dn34:1.6.9": "Vị ấy có trí, đầy đủ trí tuệ đưa đến thấy sự sinh và diệt, là trí tuệ của bậc thánh, thấu suốt, đưa đến chấm dứt khổ một cách đúng đắn.",
  "dn34:1.6.10": "Đây là năm pháp có nhiều lợi ích.",
  "dn34:1.6.11": "Năm pháp nào cần được tu tập?",
  "dn34:1.6.12": "Chánh định có năm chi —",
  "dn34:1.6.13": "tràn đầy hỷ, tràn đầy lạc, tràn đầy tâm, tràn đầy ánh sáng, tướng để quán xét lại.",
  "dn34:1.6.14": "Đây là năm pháp cần được tu tập.",
  "dn34:1.6.15": "Năm pháp nào cần được hiểu rõ trọn vẹn?",
  "dn34:1.6.16": "Năm uẩn chấp thủ —",
  "dn34:1.6.17": "sắc uẩn chấp thủ, thọ uẩn chấp thủ, tưởng uẩn chấp thủ, hành uẩn chấp thủ, thức uẩn chấp thủ.",
  "dn34:1.6.18": "Đây là năm pháp cần được hiểu rõ trọn vẹn.",
  "dn34:1.6.19": "Năm pháp nào cần được từ bỏ?",
  "dn34:1.6.20": "Năm chướng ngại —",
  "dn34:1.6.21": "chướng ngại do tham muốn dục lạc, chướng ngại do sân, chướng ngại do hôn trầm và buồn ngủ, chướng ngại do dao động và hối quá, chướng ngại do nghi.",
  "dn34:1.6.22": "Đây là năm pháp cần được từ bỏ.",
  "dn34:1.6.23": "Năm pháp nào thuộc phần sa sút?",
  "dn34:1.6.24": "Năm sự chai cứng của tâm —",
  "dn34:1.6.25": "Này các hiền giả, ở đây vị tỳ-kheo nghi ngờ, phân vân đối với bậc Đạo Sư, không quyết tin, không trong sáng.",
  "dn34:1.6.26": "Này các hiền giả, vị tỳ-kheo nào nghi ngờ, phân vân đối với bậc Đạo Sư, không quyết tin, không trong sáng, thì tâm vị ấy không hướng đến nhiệt tâm, chuyên cần, bền bỉ, tinh tấn.",
  "dn34:1.6.27": "Người nào có tâm không hướng đến nhiệt tâm, chuyên cần, bền bỉ, tinh tấn,",
  "dn34:1.6.28": "đây là sự chai cứng thứ nhất của tâm.",
  "dn34:1.6.29": "Lại nữa, này các hiền giả, vị tỳ-kheo nghi ngờ, phân vân đối với pháp …",
  "dn34:1.6.30": "nghi ngờ, phân vân đối với tăng đoàn …",
  "dn34:1.6.31": "nghi ngờ, phân vân đối với sự học tập …",
  "dn34:1.6.32": "vị ấy nổi giận với các bạn đồng tu, không vui lòng, lòng bị tổn thương, sinh ra cứng nhắc. Này hiền giả, vị tỳ kheo nào nổi giận với các bạn đồng tu, không vui lòng, lòng bị tổn thương, sinh ra cứng nhắc, thì tâm vị ấy không hướng đến tinh cần, chuyên tâm, bền bỉ, nỗ lực.",
  "dn34:1.6.33": "Người mà tâm không hướng đến tinh cần, chuyên tâm, bền bỉ, nỗ lực.",
  "dn34:1.6.34": "Đây là sự cứng nhắc của tâm thứ năm.",
  "dn34:1.6.35": "Đây là năm pháp đưa đến sa sút.",
  "dn34:1.6.36": "Thế nào là năm pháp đưa đến vượt trội?",
  "dn34:1.6.37": "Năm căn là—",
  "dn34:1.6.38": "căn tin, căn tinh tấn, căn niệm, căn định, căn tuệ.",
  "dn34:1.6.39": "Đây là năm pháp đưa đến vượt trội.",
  "dn34:1.6.40": "Thế nào là năm pháp khó thấu suốt?",
  "dn34:1.6.41": "Năm giới vực đưa đến thoát ra—",
  "dn34:1.6.42": "Này hiền giả, ở đây vị tỳ kheo khi tác ý đến dục thì tâm không lao vào dục, không trong sáng, không đứng vững, không giải thoát.",
  "dn34:1.6.43": "Nhưng khi vị ấy tác ý đến xuất ly thì tâm lao vào xuất ly, trở nên trong sáng, đứng vững, được giải thoát.",
  "dn34:1.6.44": "Tâm ấy của vị ấy đã đi đúng hướng, được tu tập tốt, được an lập vững vàng, được giải thoát tốt, lìa khỏi các dục.",
  "dn34:1.6.45": "Những lậu hoặc, bức bối, nóng bức nào sinh khởi do duyên dục, vị ấy được giải thoát khỏi chúng. Vị ấy không còn cảm thọ cảm giác ấy.",
  "dn34:1.6.46": "Đây được gọi là sự thoát ra khỏi các dục.",
  "dn34:1.6.47": "Lại nữa, này hiền giả, ở đây vị tỳ kheo khi tác ý đến sân thì tâm không lao vào sân, không trong sáng, không đứng vững, không giải thoát.",
  "dn34:1.6.48": "Nhưng khi vị ấy tác ý đến không sân thì tâm lao vào không sân, trở nên trong sáng, đứng vững, được giải thoát.",
  "dn34:1.6.49": "Tâm ấy của vị ấy đã đi đúng hướng, được tu tập tốt, được an lập vững vàng, được giải thoát tốt, lìa khỏi sân.",
  "dn34:1.6.50": "Những lậu hoặc, bức bối, nóng bức nào sinh khởi do duyên sân, vị ấy được giải thoát khỏi chúng. Vị ấy không còn cảm thọ cảm giác ấy.",
  "dn34:1.6.51": "Đây được gọi là sự thoát ra khỏi sân.",
  "dn34:1.6.52": "Lại nữa, này hiền giả, ở đây vị tỳ kheo khi tác ý đến hại thì tâm không lao vào hại, không trong sáng, không đứng vững, không giải thoát.",
  "dn34:1.6.53": "Nhưng khi vị ấy tác ý đến không hại thì tâm lao vào không hại, trở nên trong sáng, đứng vững, được giải thoát.",
  "dn34:1.6.54": "Tâm ấy của vị ấy đã đi đúng hướng, được tu tập tốt, được an lập vững vàng, được giải thoát tốt, lìa khỏi hại.",
  "dn34:1.6.55": "Những lậu hoặc, bức bối, nóng bức nào sinh khởi do duyên hại, vị ấy được giải thoát khỏi chúng. Vị ấy không còn cảm thọ cảm giác ấy.",
  "dn34:1.6.56": "Đây được gọi là sự thoát ra khỏi hại.",
  "dn34:1.6.57": "Lại nữa, này hiền giả, ở đây vị tỳ kheo khi tác ý đến sắc thì tâm không lao vào các sắc, không trong sáng, không đứng vững, không giải thoát.",
  "dn34:1.6.58": "Nhưng khi vị ấy tác ý đến vô sắc thì tâm lao vào vô sắc, trở nên trong sáng, đứng vững, được giải thoát.",
  "dn34:1.6.59": "Tâm ấy của vị ấy đã đi đúng hướng, được tu tập tốt, được an lập vững vàng, được giải thoát tốt, lìa khỏi các sắc.",
  "dn34:1.6.60": "Những lậu hoặc, bức bối, nóng bức nào sinh khởi do duyên sắc, vị ấy được giải thoát khỏi chúng. Vị ấy không còn cảm thọ cảm giác ấy.",
  "dn34:1.6.61": "Đây được gọi là sự thoát ra khỏi các sắc.",
  "dn34:1.6.62": "Lại nữa, này hiền giả, ở đây vị tỳ kheo khi tác ý đến thân kiến thì tâm không lao vào thân kiến, không trong sáng, không đứng vững, không giải thoát.",
  "dn34:1.6.63": "Nhưng khi vị ấy tác ý đến sự diệt của thân kiến thì tâm lao vào sự diệt của thân kiến, trở nên trong sáng, đứng vững, được giải thoát.",
  "dn34:1.6.64": "Tâm ấy của vị ấy đã đi đúng hướng, được tu tập tốt, được an lập vững vàng, được giải thoát tốt, lìa khỏi thân kiến.",
  "dn34:1.6.65": "Những lậu hoặc, bức bối, nóng bức nào sinh khởi do duyên thân kiến, vị ấy được giải thoát khỏi chúng. Vị ấy không còn cảm thọ cảm giác ấy.",
  "dn34:1.6.66": "Đây được gọi là sự thoát ra khỏi thân kiến.",
  "dn34:1.6.67": "Đây là năm pháp khó thấu suốt.",
  "dn34:1.6.68": "Thế nào là năm pháp cần được làm phát sinh?",
  "dn34:1.6.69": "Chánh định có năm mặt hiểu biết:",
  "dn34:1.6.70": "‘Định này đem lại an lạc ngay hiện tại và về sau cho quả an lạc’, tri kiến ấy tự mình sinh khởi.",
  "dn34:1.6.71": "‘Định này là bậc thánh, không dính vị đời’, tri kiến ấy tự mình sinh khởi.",
  "dn34:1.6.72": "‘Định này không được thực hành bởi hạng người xấu’, tri kiến ấy tự mình sinh khởi.",
  "dn34:1.6.73": "‘Định này lặng yên, cao quý, đạt được sự lắng dịu, đạt đến nhất tâm, không phải trạng thái do gò ép, đè nén các hành mà thành’, tri kiến ấy tự mình sinh khởi.",
  "dn34:1.6.74": "‘Ta vào định này với chánh niệm, và ra khỏi định này với chánh niệm’, tri kiến ấy tự mình sinh khởi.",
  "dn34:1.6.75": "Đây là năm pháp cần được làm phát sinh.",
  "dn34:1.6.76": "Thế nào là năm pháp cần được thắng tri?",
  "dn34:1.6.77": "Năm chỗ mở ra giải thoát là—",
  "dn34:1.6.78": "Này hiền giả, ở đây bậc Đạo sư thuyết pháp cho vị tỳ kheo, hoặc một vị đồng tu đáng kính nào đó thuyết pháp.",
  "dn34:1.6.79": "Này hiền giả, khi bậc Đạo sư thuyết pháp cho vị tỳ kheo, hoặc một vị đồng tu đáng kính nào đó thuyết pháp, thì vị ấy cảm nhận được ý nghĩa trong pháp ấy và cảm nhận được pháp.",
  "dn34:1.6.80": "Khi cảm nhận được ý nghĩa và cảm nhận được pháp, niềm vui sinh khởi nơi vị ấy; do có niềm vui, hỷ sinh khởi; tâm có hỷ thì thân được lắng dịu; thân lắng dịu thì cảm thấy an lạc; người an lạc thì tâm được định tĩnh.",
  "dn34:1.6.81": "Đây là chỗ mở ra giải thoát thứ nhất.",
  "dn34:1.6.82": "Lại nữa, này các hiền giả, vị tỳ-kheo không phải chỉ được bậc Đạo sư thuyết pháp, hay một vị đồng phạm hạnh đáng kính nào đó thuyết pháp, mà còn đem pháp đã được nghe, đã được học, giảng rộng cho người khác.",
  "dn34:1.6.83": "Này các hiền giả, vị tỳ-kheo càng giảng rộng cho người khác pháp đã được nghe, đã được học như thế nào, thì vị ấy càng cảm nhận được ý nghĩa trong pháp ấy và cảm nhận được pháp ấy như thế ấy.",
  "dn34:1.6.84": "Với vị cảm nhận được ý nghĩa và cảm nhận được pháp ấy, niềm vui khởi lên; do vui mừng nên hỷ sinh; với tâm có hỷ, thân được lắng dịu; thân lắng dịu thì cảm thấy an lạc; người an lạc thì tâm được định tĩnh.",
  "dn34:1.6.85": "Đây là cửa giải thoát thứ hai.",
  "dn34:1.6.86": "Lại nữa, này các hiền giả, vị tỳ-kheo không phải chỉ được bậc Đạo sư thuyết pháp, hay một vị đồng phạm hạnh đáng kính nào đó thuyết pháp, cũng không phải đem pháp đã được nghe, đã được học, giảng rộng cho người khác. Nhưng vị ấy tụng đọc rộng rãi pháp đã được nghe, đã được học.",
  "dn34:1.6.87": "Này các hiền giả, vị tỳ-kheo càng tụng đọc rộng rãi pháp đã được nghe, đã được học như thế nào, thì vị ấy càng cảm nhận được ý nghĩa trong pháp ấy và cảm nhận được pháp ấy như thế ấy.",
  "dn34:1.6.88": "Với vị cảm nhận được ý nghĩa và cảm nhận được pháp ấy, niềm vui khởi lên; do vui mừng nên hỷ sinh; với tâm có hỷ, thân được lắng dịu; thân lắng dịu thì cảm thấy an lạc; người an lạc thì tâm được định tĩnh.",
  "dn34:1.6.89": "Đây là cửa giải thoát thứ ba.",
  "dn34:1.6.90": "Lại nữa, này các hiền giả, vị tỳ-kheo không phải chỉ được bậc Đạo sư thuyết pháp, hay một vị đồng phạm hạnh đáng kính nào đó thuyết pháp, cũng không đem pháp đã được nghe, đã được học, giảng rộng cho người khác, cũng không tụng đọc rộng rãi pháp đã được nghe, đã được học.",
  "dn34:1.6.91": "Nhưng vị ấy dùng tâm suy xét, quán sát, xem xét kỹ bằng ý đối với pháp đã được nghe, đã được học.",
  "dn34:1.6.92": "Này các hiền giả, vị tỳ-kheo càng dùng tâm suy xét, quán sát, xem xét kỹ bằng ý đối với pháp đã được nghe, đã được học như thế nào, thì vị ấy càng cảm nhận được ý nghĩa trong pháp ấy và cảm nhận được pháp ấy như thế ấy.",
  "dn34:1.6.93": "Với vị cảm nhận được ý nghĩa và cảm nhận được pháp ấy, niềm vui khởi lên; do vui mừng nên hỷ sinh; với tâm có hỷ, thân được lắng dịu; thân lắng dịu thì cảm thấy an lạc; người an lạc thì tâm được định tĩnh.",
  "dn34:1.6.94": "Đây là cửa giải thoát thứ tư.",
  "dn34:1.6.95": "Lại nữa, này các hiền giả, vị tỳ-kheo không phải chỉ được bậc Đạo sư thuyết pháp, hay một vị đồng phạm hạnh đáng kính nào đó thuyết pháp, cũng không đem pháp đã được nghe, đã được học, giảng rộng cho người khác, cũng không tụng đọc rộng rãi pháp đã được nghe, đã được học, cũng không dùng tâm suy xét, quán sát, xem xét kỹ bằng ý đối với pháp đã được nghe, đã được học;",
  "dn34:1.6.96": "nhưng vị ấy khéo nắm lấy một đề mục định nào đó, khéo tác ý, khéo giữ gìn, khéo thấu suốt bằng trí.",
  "dn34:1.6.97": "Này các hiền giả, vị tỳ-kheo càng khéo nắm lấy một đề mục định nào đó, khéo tác ý, khéo giữ gìn, khéo thấu suốt bằng trí như thế nào, thì vị ấy càng cảm nhận được ý nghĩa trong pháp ấy và cảm nhận được pháp ấy như thế ấy.",
  "dn34:1.6.98": "Với vị cảm nhận được ý nghĩa và cảm nhận được pháp ấy, niềm vui khởi lên; do vui mừng nên hỷ sinh; với tâm có hỷ, thân được lắng dịu; thân lắng dịu thì cảm thấy an lạc; người an lạc thì tâm được định tĩnh.",
  "dn34:1.6.99": "Đây là cửa giải thoát thứ năm.",
  "dn34:1.6.100": "Năm pháp này cần được thắng tri.",
  "dn34:1.6.101": "Năm pháp nào cần được chứng ngộ?",
  "dn34:1.6.102": "Năm nhóm pháp—",
  "dn34:1.6.103": "nhóm giới, nhóm định, nhóm tuệ, nhóm giải thoát, nhóm tri kiến về giải thoát.",
  "dn34:1.6.104": "Năm pháp này cần được chứng ngộ.",
  "dn34:1.6.105": "Như vậy, năm mươi pháp này là có thật, chân thật, đúng như vậy, không sai khác, được Như Lai tự mình giác ngộ trọn vẹn một cách đúng đắn.",
  "dn34:1.7.0": "6. Sáu pháp",
  "dn34:1.7.1": "Sáu pháp có nhiều lợi ích … sáu pháp cần được chứng ngộ.",
  "dn34:1.7.2": "Sáu pháp nào có nhiều lợi ích?",
  "dn34:1.7.3": "Sáu pháp đáng ghi nhớ.",
  "dn34:1.7.4": "Ở đây, này các hiền giả, vị tỳ-kheo có hành động thân đầy lòng thương đối với các vị đồng phạm hạnh, cả trước mặt lẫn sau lưng,",
  "dn34:1.7.5": "pháp này cũng là pháp đáng ghi nhớ, làm cho mến nhau, làm cho kính nhau, đưa đến đoàn kết, không tranh cãi, hòa hợp, đồng nhất.",
  "dn34:1.7.6": "Lại nữa, này các hiền giả, vị tỳ-kheo có hành động lời nói đầy lòng thương … đồng nhất.",
  "dn34:1.7.7": "Lại nữa, này các hiền giả, vị tỳ-kheo có hành động ý nghĩ đầy lòng thương … đồng nhất.",
  "dn34:1.7.8": "Lại nữa, này các hiền giả, vị tỳ-kheo đối với những lợi dưỡng đúng pháp, có được đúng pháp, cho đến chỉ là chút ít trong bát, vị ấy không hưởng riêng mà cùng chia sẻ chung với các vị đồng phạm hạnh có giới, pháp này cũng là pháp đáng ghi nhớ … đưa đến đồng nhất.",
  "dn34:1.7.9": "Lại nữa, này các hiền giả, vị tỳ-kheo sống cùng chung giới với các vị đồng phạm hạnh, cả trước mặt lẫn sau lưng, đối với những giới không sứt mẻ, không rách, không đốm, không tì vết, đưa đến tự do, được người có trí khen ngợi, không bị chấp thủ, đưa đến định, pháp này cũng là pháp đáng ghi nhớ … đưa đến đồng nhất.",
  "dn34:1.7.10": "Lại nữa, này các hiền giả, vị tỳ-kheo sống cùng chung cái thấy với các vị đồng phạm hạnh, cả trước mặt lẫn sau lưng, với cái thấy thuộc bậc thánh, đưa ra khỏi, dẫn người thực hành đúng đến chỗ diệt khổ hoàn toàn,",
  "dn34:1.7.11": "pháp này cũng là pháp đáng ghi nhớ, làm cho mến nhau, làm cho kính nhau, đưa đến đoàn kết, không tranh cãi, hòa hợp, đồng nhất.",
  "dn34:1.7.12": "Đây là sáu pháp có nhiều lợi ích.",
  "dn34:1.7.13": "Sáu pháp nào cần được tu tập?",
  "dn34:1.7.14": "Sáu chỗ nhớ nghĩ—",
  "dn34:1.7.15": "nhớ nghĩ đến Phật, nhớ nghĩ đến Pháp, nhớ nghĩ đến Tăng, nhớ nghĩ đến giới, nhớ nghĩ đến sự buông xả, nhớ nghĩ đến chư thiên.",
  "dn34:1.7.16": "Đây là sáu pháp cần được tu tập.",
  "dn34:1.7.17": "Sáu pháp nào cần được hiểu rõ?",
  "dn34:1.7.18": "Sáu xứ bên trong—",
  "dn34:1.7.19": "xứ mắt, xứ tai, xứ mũi, xứ lưỡi, xứ thân, xứ ý.",
  "dn34:1.7.20": "Đây là sáu pháp cần được hiểu rõ.",
  "dn34:1.7.21": "Sáu pháp nào cần được đoạn trừ?",
  "dn34:1.7.22": "Sáu nhóm khát ái—",
  "dn34:1.7.23": "khát ái đối với sắc, khát ái đối với tiếng, khát ái đối với mùi, khát ái đối với vị, khát ái đối với sự chạm xúc, khát ái đối với các pháp.",
  "dn34:1.7.24": "Đây là sáu pháp cần được đoạn trừ.",
  "dn34:1.7.25": "Sáu pháp nào thuộc phần suy giảm?",
  "dn34:1.7.26": "Sáu điều không kính trọng—",
  "dn34:1.7.27": "Này hiền hữu, ở đây vị tỳ-kheo sống không kính trọng, không tôn trọng bậc Đạo Sư. Đối với Pháp … đối với Tăng … đối với học giới … đối với sự không phóng dật … đối với sự tiếp đón, vị ấy sống không kính trọng, không tôn trọng.",
  "dn34:1.7.28": "Đây là sáu pháp đưa đến sa sút.",
  "dn34:1.7.29": "Thế nào là sáu pháp đưa đến vượt trội?",
  "dn34:1.7.30": "Sáu điều kính trọng—",
  "dn34:1.7.31": "Này hiền hữu, ở đây vị tỳ-kheo sống có kính trọng, có tôn trọng bậc Đạo Sư. Đối với Pháp … đối với Tăng … đối với học giới … đối với sự không phóng dật … đối với sự tiếp đón, vị ấy sống có kính trọng, có tôn trọng.",
  "dn34:1.7.32": "Đây là sáu pháp đưa đến vượt trội.",
  "dn34:1.7.33": "Thế nào là sáu pháp khó thấu hiểu?",
  "dn34:1.7.34": "Sáu giới đưa đến xuất ly—",
  "dn34:1.7.35": "Này hiền hữu, ở đây vị tỳ-kheo có thể nói như vầy:",
  "dn34:1.7.36": "‘Thật vậy, tâm giải thoát do từ của tôi đã được tu tập, được làm cho nhiều, được lấy làm cỗ xe, được lấy làm nền tảng, được thiết lập, được quen dùng, được khéo khởi lên,",
  "dn34:1.7.37": "thế mà sân hận vẫn chiếm ngự tâm tôi.’",
  "dn34:1.7.38": "Vị ấy cần được nói rằng: ‘Chớ có nói vậy, thưa hiền giả, chớ nói như thế, chớ vu cho Thế Tôn. Vu cho Thế Tôn như vậy là không đúng, vì Thế Tôn không nói như thế.",
  "dn34:1.7.39": "Này hiền hữu, không có chuyện, không có khả năng rằng khi tâm giải thoát do từ đã được tu tập, được làm cho nhiều, được lấy làm cỗ xe, được lấy làm nền tảng, được thiết lập, được quen dùng, được khéo khởi lên,",
  "dn34:1.7.40": "mà sân hận vẫn chiếm ngự tâm người ấy. Không có trường hợp ấy.",
  "dn34:1.7.41": "Vì này hiền hữu, đây là lối thoát khỏi sân hận, tức là tâm giải thoát do từ.’",
  "dn34:1.7.42": "Này hiền hữu, ở đây vị tỳ-kheo có thể nói như vầy:",
  "dn34:1.7.43": "‘Thật vậy, tâm giải thoát do bi của tôi đã được tu tập, được làm cho nhiều, được lấy làm cỗ xe, được lấy làm nền tảng, được thiết lập, được quen dùng, được khéo khởi lên.",
  "dn34:1.7.44": "Thế mà sự hại tâm vẫn chiếm ngự tâm tôi.’",
  "dn34:1.7.45": "Vị ấy cần được nói rằng: ‘Chớ có nói vậy, thưa hiền giả, chớ nói như thế, chớ vu cho Thế Tôn …",
  "dn34:1.7.46": "vì này hiền hữu, đây là lối thoát khỏi sự hại tâm, tức là tâm giải thoát do bi.’",
  "dn34:1.7.47": "Này hiền hữu, ở đây vị tỳ-kheo có thể nói như vầy:",
  "dn34:1.7.48": "‘Thật vậy, tâm giải thoát do hỷ của tôi đã được tu tập …",
  "dn34:1.7.49": "thế mà sự không vui vẫn chiếm ngự tâm tôi.’",
  "dn34:1.7.50": "Vị ấy cần được nói rằng: ‘Chớ có nói vậy, thưa hiền giả, chớ nói như thế …",
  "dn34:1.7.51": "vì này hiền hữu, đây là lối thoát khỏi sự không vui, tức là tâm giải thoát do hỷ.’",
  "dn34:1.7.52": "Này hiền hữu, ở đây vị tỳ-kheo có thể nói như vầy:",
  "dn34:1.7.53": "‘Thật vậy, tâm giải thoát do xả của tôi đã được tu tập …",
  "dn34:1.7.54": "thế mà tham ái vẫn chiếm ngự tâm tôi.’",
  "dn34:1.7.55": "Vị ấy cần được nói rằng: ‘Chớ có nói vậy, thưa hiền giả, chớ nói như thế …",
  "dn34:1.7.56": "vì này hiền hữu, đây là lối thoát khỏi tham ái, tức là tâm giải thoát do xả.’",
  "dn34:1.7.57": "Này hiền hữu, ở đây vị tỳ-kheo có thể nói như vầy:",
  "dn34:1.7.58": "‘Thật vậy, tâm giải thoát vô tướng của tôi đã được tu tập …",
  "dn34:1.7.59": "thế mà thức của tôi vẫn chạy theo tướng.’",
  "dn34:1.7.60": "Vị ấy cần được nói rằng: ‘Chớ có nói vậy, thưa hiền giả, chớ nói như thế …",
  "dn34:1.7.61": "vì này hiền hữu, đây là lối thoát khỏi mọi tướng, tức là tâm giải thoát vô tướng.’",
  "dn34:1.7.62": "Này hiền hữu, ở đây vị tỳ-kheo có thể nói như vầy:",
  "dn34:1.7.63": "‘Cái nghĩ “ta là” nơi tôi đã hết, tôi không còn thấy “cái này là tôi” nữa,",
  "dn34:1.7.64": "thế mà mũi tên nghi ngờ, phân vân vẫn chiếm ngự tâm tôi.’",
  "dn34:1.7.65": "Vị ấy cần được nói rằng: ‘Chớ có nói vậy, thưa hiền giả, chớ nói như thế, chớ vu cho Thế Tôn. Vu cho Thế Tôn như vậy là không đúng, vì Thế Tôn không nói như thế.",
  "dn34:1.7.66": "Này hiền hữu, không có chuyện, không có khả năng rằng khi cái nghĩ “ta là” đã hết, khi không còn thấy “cái này là tôi”,",
  "dn34:1.7.67": "mà mũi tên nghi ngờ, phân vân vẫn chiếm ngự tâm người ấy. Không có trường hợp ấy.",
  "dn34:1.7.68": "Vì này hiền hữu, đây là lối thoát khỏi mũi tên nghi ngờ, phân vân, tức là nhổ tận gốc ngã mạn “ta là”.’",
  "dn34:1.7.69": "Đây là sáu pháp khó thấu hiểu.",
  "dn34:1.7.70": "Thế nào là sáu pháp cần được làm phát sinh?",
  "dn34:1.7.71": "Sáu cách an trú thường xuyên.",
  "dn34:1.7.72": "Này hiền hữu, ở đây vị tỳ-kheo khi mắt thấy sắc thì không vui cũng không buồn, sống xả, có chánh niệm, tỉnh giác.",
  "dn34:1.7.73": "Khi tai nghe tiếng …",
  "dn34:1.7.74": "khi mũi ngửi mùi …",
  "dn34:1.7.75": "khi lưỡi nếm vị …",
  "dn34:1.7.76": "sau khi thân chạm xúc chạm … ",
  "dn34:1.7.77": "sau khi ý nhận biết pháp, vị ấy không vui cũng không buồn, sống với tâm xả, chánh niệm, tỉnh giác. ",
  "dn34:1.7.78": "Sáu pháp này cần được làm khởi lên. ",
  "dn34:1.7.79": "Sáu pháp nào cần được thắng tri? ",
  "dn34:1.7.80": "Sáu điều không gì hơn—",
  "dn34:1.7.81": "không gì hơn về thấy, không gì hơn về nghe, không gì hơn về được lợi ích, không gì hơn về học tập, không gì hơn về phụng sự, không gì hơn về nhớ nghĩ. ",
  "dn34:1.7.82": "Sáu pháp này cần được thắng tri. ",
  "dn34:1.7.83": "Sáu pháp nào cần được chứng ngộ? ",
  "dn34:1.7.84": "Sáu thắng trí—",
  "dn34:1.7.85": "Này các hiền giả, ở đây vị tỳ kheo chứng được nhiều loại thần thông: một thân hiện thành nhiều thân, nhiều thân hiện thành một thân; hiện ra rồi biến mất; đi xuyên qua vách, xuyên qua tường, xuyên qua núi không bị ngăn ngại như đi trong hư không; trồi lên lặn xuống trong đất như ở trong nước; đi trên nước mà không chìm như đi trên đất; ngồi kiết già bay trên hư không như chim có cánh; dùng tay chạm đến, sờ đến mặt trăng và mặt trời, những vị có thần lực lớn, oai lực lớn như vậy; dùng thân đi lại tự tại cho đến cõi Phạm thiên. ",
  "dn34:1.7.86": "Với thiên nhĩ thanh tịnh, vượt quá tai người, vị ấy nghe được cả hai loại tiếng, tiếng chư thiên và tiếng loài người, dù xa hay gần. ",
  "dn34:1.7.87": "Vị ấy biết được tâm của các chúng sinh, của các người khác, lấy tâm dò biết tâm, ",
  "dn34:1.7.88": "biết tâm có tham là tâm có tham … ",
  "dn34:1.7.89": "biết tâm chưa giải thoát là tâm chưa giải thoát. ",
  "dn34:1.7.90": "Vị ấy nhớ lại được nhiều đời sống trước đây, như là: một đời … như vậy vị ấy nhớ lại được nhiều đời sống trước đây cùng với hình tướng và chi tiết. ",
  "dn34:1.7.91": "Với thiên nhãn thanh tịnh, vượt quá mắt người, vị ấy thấy các chúng sinh chết đi và sinh lại, kẻ thấp người cao, đẹp kẻ xấu, đi đến chỗ lành hay chỗ dữ; vị ấy biết các chúng sinh đi theo nghiệp của mình … ",
  "dn34:1.7.92": "Do đoạn tận các lậu hoặc, vị ấy ngay trong đời này tự mình với thắng trí chứng ngộ và an trú trong giải thoát tâm không còn lậu hoặc, giải thoát nhờ tuệ. ",
  "dn34:1.7.93": "Sáu pháp này cần được chứng ngộ. ",
  "dn34:1.7.94": "Như vậy, sáu mươi pháp này là có thật, chân thật, đúng như vậy, không sai khác, được Như Lai giác ngộ trọn vẹn một cách đúng đắn. ",
  "dn34:1.8.0": "7. Bảy pháp ",
  "dn34:1.8.1": "Bảy pháp có nhiều lợi ích … bảy pháp cần được chứng ngộ. ",
  "dn34:1.8.2": "Bảy pháp nào có nhiều lợi ích? ",
  "dn34:1.8.3": "Bảy tài sản của bậc thánh—",
  "dn34:1.8.4": "tài sản là lòng tin, tài sản là giới, tài sản là biết hổ thẹn, tài sản là biết sợ điều xấu, tài sản là học rộng nghe nhiều, tài sản là buông xả, tài sản là trí tuệ. ",
  "dn34:1.8.5": "Bảy pháp này có nhiều lợi ích. ",
  "dn34:1.8.6": "Bảy pháp nào cần được tu tập? ",
  "dn34:1.8.7": "Bảy chi giác ngộ—",
  "dn34:1.8.8": "niệm là chi giác ngộ, trạch pháp là chi giác ngộ, tinh tấn là chi giác ngộ, hỷ là chi giác ngộ, khinh an là chi giác ngộ, định là chi giác ngộ, xả là chi giác ngộ. ",
  "dn34:1.8.9": "Bảy pháp này cần được tu tập. ",
  "dn34:1.8.10": "Bảy pháp nào cần được hiểu rõ trọn vẹn? ",
  "dn34:1.8.11": "Bảy chỗ an trú của thức—",
  "dn34:1.8.12": "Này các hiền giả, có những chúng sinh thân khác nhau, tưởng khác nhau, như loài người, một số chư thiên và một số chúng sinh ở cõi khổ. ",
  "dn34:1.8.13": "Đây là chỗ an trú thứ nhất của thức. ",
  "dn34:1.8.14": "Này các hiền giả, có những chúng sinh thân khác nhau nhưng tưởng giống nhau, như chư thiên thuộc Phạm chúng mới sinh lần đầu. ",
  "dn34:1.8.15": "Đây là chỗ an trú thứ hai của thức. ",
  "dn34:1.8.16": "Này các hiền giả, có những chúng sinh thân giống nhau nhưng tưởng khác nhau, như chư thiên Quang Âm. ",
  "dn34:1.8.17": "Đây là chỗ an trú thứ ba của thức. ",
  "dn34:1.8.18": "Này các hiền giả, có những chúng sinh thân giống nhau, tưởng giống nhau, như chư thiên Biến Tịnh. ",
  "dn34:1.8.19": "Đây là chỗ an trú thứ tư của thức. ",
  "dn34:1.8.20": "Này các hiền giả, có những chúng sinh do vượt hẳn mọi tưởng về sắc … nghĩ rằng: ‘hư không là vô biên’, nên đạt đến xứ hư không vô biên. ",
  "dn34:1.8.21": "Đây là chỗ an trú thứ năm của thức. ",
  "dn34:1.8.22": "Này các hiền giả, có những chúng sinh do vượt hẳn xứ hư không vô biên, nghĩ rằng: ‘thức là vô biên’, nên đạt đến xứ thức vô biên. ",
  "dn34:1.8.23": "Đây là chỗ an trú thứ sáu của thức. ",
  "dn34:1.8.24": "Này các hiền giả, có những chúng sinh do vượt hẳn xứ thức vô biên, nghĩ rằng: ‘không có gì cả’, nên đạt đến xứ không có gì. ",
  "dn34:1.8.25": "Đây là chỗ an trú thứ bảy của thức. ",
  "dn34:1.8.26": "Bảy pháp này cần được hiểu rõ trọn vẹn. ",
  "dn34:1.8.27": "Bảy pháp nào cần được đoạn trừ? ",
  "dn34:1.8.28": "Bảy tùy miên—",
  "dn34:1.8.29": "tùy miên tham dục, tùy miên sân, tùy miên tà kiến, tùy miên nghi, tùy miên ngã mạn, tùy miên tham hữu, tùy miên vô minh. ",
  "dn34:1.8.30": "Bảy pháp này cần được đoạn trừ. ",
  "dn34:1.8.31": "Bảy pháp nào đưa đến sa sút?",
  "dn34:1.8.32": "Bảy pháp không chân chánh—",
  "dn34:1.8.33": "Này hiền giả, ở đây vị tỳ kheo không có lòng tin, không biết hổ thẹn, không biết sợ điều xấu, ít học, biếng nhác, thất niệm, thiếu trí tuệ.",
  "dn34:1.8.34": "Đó là bảy pháp đưa đến sa sút.",
  "dn34:1.8.35": "Bảy pháp nào đưa đến vượt trội?",
  "dn34:1.8.36": "Bảy pháp chân chánh—",
  "dn34:1.8.37": "Này hiền giả, ở đây vị tỳ kheo có lòng tin, biết hổ thẹn, biết sợ điều xấu, học rộng, tinh cần, chánh niệm vững vàng, có trí tuệ.",
  "dn34:1.8.38": "Đó là bảy pháp đưa đến vượt trội.",
  "dn34:1.8.39": "Bảy pháp nào khó thấu hiểu?",
  "dn34:1.8.40": "Bảy pháp của bậc chân nhân—",
  "dn34:1.8.41": "Này hiền giả, ở đây vị tỳ kheo biết pháp, biết nghĩa, biết mình, biết chừng mực, biết thời, biết hội chúng, biết người.",
  "dn34:1.8.42": "Đó là bảy pháp khó thấu hiểu.",
  "dn34:1.8.43": "Bảy pháp nào cần được làm khởi lên?",
  "dn34:1.8.44": "Bảy tưởng—",
  "dn34:1.8.45": "tưởng vô thường, tưởng vô ngã, tưởng bất tịnh, tưởng nguy hại, tưởng từ bỏ, tưởng ly tham, tưởng diệt.",
  "dn34:1.8.46": "Đó là bảy pháp cần được làm khởi lên.",
  "dn34:1.8.47": "Bảy pháp nào cần được thắng tri?",
  "dn34:1.8.48": "Bảy nền tảng của sự dứt sạch—",
  "dn34:1.8.49": "Này hiền giả, ở đây vị tỳ kheo có ước muốn mạnh mẽ trong việc thọ trì học pháp, và về sau vẫn không mất lòng yêu mến đối với việc thọ trì học pháp.",
  "dn34:1.8.50": "Có ước muốn mạnh mẽ trong việc tìm hiểu pháp, và về sau vẫn không mất lòng yêu mến đối với việc tìm hiểu pháp.",
  "dn34:1.8.51": "Có ước muốn mạnh mẽ trong việc dẹp bỏ ham muốn, và về sau vẫn không mất lòng yêu mến đối với việc dẹp bỏ ham muốn.",
  "dn34:1.8.52": "Có ước muốn mạnh mẽ trong việc sống tách riêng, và về sau vẫn không mất lòng yêu mến đối với việc sống tách riêng.",
  "dn34:1.8.53": "Có ước muốn mạnh mẽ trong việc khởi lên tinh tấn, và về sau vẫn không mất lòng yêu mến đối với việc khởi lên tinh tấn.",
  "dn34:1.8.54": "Có ước muốn mạnh mẽ trong việc khéo giữ chánh niệm, và về sau vẫn không mất lòng yêu mến đối với việc khéo giữ chánh niệm.",
  "dn34:1.8.55": "Có ước muốn mạnh mẽ trong việc thấu đạt chánh kiến, và về sau vẫn không mất lòng yêu mến đối với việc thấu đạt chánh kiến.",
  "dn34:1.8.56": "Đó là bảy pháp cần được thắng tri.",
  "dn34:1.8.57": "Bảy pháp nào cần được chứng ngộ?",
  "dn34:1.8.58": "Bảy sức mạnh của vị đã dứt sạch lậu hoặc—",
  "dn34:1.8.59": "Này hiền giả, đối với vị tỳ kheo đã dứt sạch lậu hoặc, tất cả các hành được thấy rõ đúng như thật bằng chánh trí là vô thường.",
  "dn34:1.8.60": "Này hiền giả, việc vị tỳ kheo đã dứt sạch lậu hoặc thấy rõ đúng như thật bằng chánh trí rằng tất cả các hành là vô thường, đó cũng là một sức mạnh của vị ấy; nương vào sức mạnh ấy, vị tỳ kheo đã dứt sạch lậu hoặc tuyên bố sự đoạn tận các lậu hoặc rằng: ‘Các lậu hoặc của ta đã dứt sạch.’",
  "dn34:1.8.61": "Lại nữa, này hiền giả, đối với vị tỳ kheo đã dứt sạch lậu hoặc, các dục được thấy rõ đúng như thật bằng chánh trí là giống như hố than hừng.",
  "dn34:1.8.62": "Này hiền giả … ‘Các lậu hoặc của ta đã dứt sạch.’",
  "dn34:1.8.63": "Lại nữa, này hiền giả, đối với vị tỳ kheo đã dứt sạch lậu hoặc, tâm hướng đến viễn ly, nghiêng về viễn ly, đổ về viễn ly, an trú trong viễn ly, vui thích xuất ly, đã vượt qua hoàn toàn mọi pháp làm chỗ đứng cho lậu hoặc.",
  "dn34:1.8.64": "Này hiền giả … ‘Các lậu hoặc của ta đã dứt sạch.’",
  "dn34:1.8.65": "Lại nữa, này hiền giả, đối với vị tỳ kheo đã dứt sạch lậu hoặc, bốn niệm xứ đã được tu tập, được khéo tu tập.",
  "dn34:1.8.66": "Này hiền giả … ‘Các lậu hoặc của ta đã dứt sạch.’",
  "dn34:1.8.67": "Lại nữa, này hiền giả, đối với vị tỳ kheo đã dứt sạch lậu hoặc, năm căn đã được tu tập, được khéo tu tập.",
  "dn34:1.8.68": "Này hiền giả … ‘Các lậu hoặc của ta đã dứt sạch.’",
  "dn34:1.8.69": "Lại nữa, này hiền giả, đối với vị tỳ kheo đã dứt sạch lậu hoặc, bảy giác chi đã được tu tập, được khéo tu tập.",
  "dn34:1.8.70": "Này hiền giả … ‘Các lậu hoặc của ta đã dứt sạch.’",
  "dn34:1.8.71": "Lại nữa, này hiền giả, đối với vị tỳ kheo đã dứt sạch lậu hoặc, con đường thánh tám ngành đã được tu tập, được khéo tu tập.",
  "dn34:1.8.72": "Này hiền giả, việc vị tỳ kheo đã dứt sạch lậu hoặc tu tập con đường thánh tám ngành, khéo tu tập con đường thánh tám ngành, đó cũng là một sức mạnh của vị ấy; nương vào sức mạnh ấy, vị tỳ kheo đã dứt sạch lậu hoặc tuyên bố sự đoạn tận các lậu hoặc rằng:",
  "dn34:1.8.73": "‘Các lậu hoặc của ta đã dứt sạch.’",
  "dn34:1.8.74": "Đó là bảy pháp cần được chứng ngộ.",
  "dn34:1.8.75": "Như vậy là bảy mươi pháp này, có thật, chân thật, đúng như vậy, không sai khác, đã được Như Lai tự mình giác ngộ trọn vẹn.",
  "dn34:1.8.76": "Phần tụng đọc thứ nhất đã xong.",
  "dn34:2.1.0": "8. Tám pháp",
  "dn34:2.1.1": "Tám pháp có nhiều lợi ích … tám pháp cần được chứng ngộ.",
  "dn34:2.1.2": "Tám pháp nào có nhiều lợi ích?",
  "dn34:2.1.3": "Tám nhân, tám duyên đưa đến việc đạt được trí tuệ ban đầu của đời sống phạm hạnh khi chưa đạt được, và khi đã đạt được thì đưa đến tăng trưởng hơn nữa, rộng lớn, tu tập và viên mãn.",
  "dn34:2.1.4": "Tám điều là gì?",
  "dn34:2.1.5": "Này hiền giả, ở đây vị tỳ-kheo sống nương tựa bậc Đạo Sư hoặc một vị đồng phạm hạnh đáng kính nào đó, đối với vị ấy có lòng hổ thẹn và sợ điều xấu mạnh mẽ, cùng với tình thương và sự kính trọng.",
  "dn34:2.1.6": "Đây là nhân thứ nhất, duyên thứ nhất, đưa đến việc đạt được trí tuệ thuộc đời sống phạm hạnh lúc ban đầu khi chưa đạt được; và khi đã đạt được thì đưa đến tăng trưởng, rộng lớn, tu tập và viên mãn.",
  "dn34:2.1.7": "Lại nữa, vị ấy sống nương tựa bậc Đạo Sư hoặc một vị đồng phạm hạnh đáng kính nào đó, đối với vị ấy có lòng hổ thẹn và sợ điều xấu mạnh mẽ, cùng với tình thương và sự kính trọng. Theo thời, vị ấy đến gần để hỏi han, thưa hỏi:",
  "dn34:2.1.8": "‘Bạch ngài, điều này là thế nào?",
  "dn34:2.1.9": "Ý nghĩa của điều này là gì?’",
  "dn34:2.1.10": "Các vị tôn giả ấy làm sáng tỏ điều chưa sáng tỏ, làm rõ điều chưa rõ ràng, và đối với nhiều pháp còn là chỗ nghi ngờ, các vị ấy giúp dứt nghi.",
  "dn34:2.1.11": "Đây là nhân thứ hai, duyên thứ hai, đưa đến việc đạt được trí tuệ thuộc đời sống phạm hạnh lúc ban đầu khi chưa đạt được; và khi đã đạt được thì đưa đến tăng trưởng, rộng lớn, tu tập và viên mãn.",
  "dn34:2.1.12": "Rồi sau khi nghe pháp ấy, vị ấy thành tựu sự lắng dịu theo hai mặt: lắng dịu thân và lắng dịu tâm.",
  "dn34:2.1.13": "Đây là nhân thứ ba, duyên thứ ba, đưa đến việc đạt được trí tuệ thuộc đời sống phạm hạnh lúc ban đầu khi chưa đạt được; và khi đã đạt được thì đưa đến tăng trưởng, rộng lớn, tu tập và viên mãn.",
  "dn34:2.1.14": "Lại nữa, này hiền giả, vị tỳ-kheo có giới, sống phòng hộ theo giới bổn, đầy đủ oai nghi và chỗ lui tới, thấy sợ trong những lỗi nhỏ nhặt, thọ trì và học tập trong các điều học.",
  "dn34:2.1.15": "Đây là nhân thứ tư, duyên thứ tư, đưa đến việc đạt được trí tuệ thuộc đời sống phạm hạnh lúc ban đầu khi chưa đạt được; và khi đã đạt được thì đưa đến tăng trưởng, rộng lớn, tu tập và viên mãn.",
  "dn34:2.1.16": "Lại nữa, này hiền giả, vị tỳ-kheo nghe nhiều, giữ được điều đã nghe, tích lũy điều đã nghe. Những pháp nào tốt đẹp ở đầu, tốt đẹp ở giữa, tốt đẹp ở cuối, có nghĩa, có lời, trình bày đời sống phạm hạnh trọn vẹn đầy đủ và trong sạch, thì những pháp như vậy vị ấy được nghe nhiều, ghi nhớ, quen thuộc bằng lời, suy xét bằng tâm, và thấu suốt khéo bằng thấy biết.",
  "dn34:2.1.17": "Đây là nhân thứ năm, duyên thứ năm, đưa đến việc đạt được trí tuệ thuộc đời sống phạm hạnh lúc ban đầu khi chưa đạt được; và khi đã đạt được thì đưa đến tăng trưởng, rộng lớn, tu tập và viên mãn.",
  "dn34:2.1.18": "Lại nữa, này hiền giả, vị tỳ-kheo sống tinh cần, để từ bỏ các pháp bất thiện, để làm cho các pháp thiện sinh khởi; vững mạnh, kiên trì nỗ lực, không bỏ gánh nặng đối với các pháp thiện.",
  "dn34:2.1.19": "Đây là nhân thứ sáu, duyên thứ sáu, đưa đến việc đạt được trí tuệ thuộc đời sống phạm hạnh lúc ban đầu khi chưa đạt được; và khi đã đạt được thì đưa đến tăng trưởng, rộng lớn, tu tập và viên mãn.",
  "dn34:2.1.20": "Lại nữa, này hiền giả, vị tỳ-kheo có chánh niệm, đầy đủ sự khéo léo cao nhất về chánh niệm. Việc đã làm từ lâu, lời đã nói từ lâu, vị ấy vẫn nhớ và nhớ lại được.",
  "dn34:2.1.21": "Đây là nhân thứ bảy, duyên thứ bảy, đưa đến việc đạt được trí tuệ thuộc đời sống phạm hạnh lúc ban đầu khi chưa đạt được; và khi đã đạt được thì đưa đến tăng trưởng, rộng lớn, tu tập và viên mãn.",
  "dn34:2.1.22": "Lại nữa, này hiền giả, vị tỳ-kheo sống quán sự sinh diệt trong năm uẩn chấp thủ:",
  "dn34:2.1.23": "‘Đây là sắc, đây là sự sinh khởi của sắc, đây là sự hoại diệt của sắc;",
  "dn34:2.1.24": "đây là cảm thọ, đây là sự sinh khởi của cảm thọ, đây là sự hoại diệt của cảm thọ;",
  "dn34:2.1.25": "đây là tưởng, đây là sự sinh khởi của tưởng, đây là sự hoại diệt của tưởng;",
  "dn34:2.1.26": "đây là các hành, đây là sự sinh khởi của các hành, đây là sự hoại diệt của các hành;",
  "dn34:2.1.27": "đây là thức, đây là sự sinh khởi của thức, đây là sự hoại diệt của thức.’",
  "dn34:2.1.28": "Đây là nhân thứ tám, duyên thứ tám, đưa đến việc đạt được trí tuệ thuộc đời sống phạm hạnh lúc ban đầu khi chưa đạt được; và khi đã đạt được thì đưa đến tăng trưởng, rộng lớn, tu tập và viên mãn.",
  "dn34:2.1.29": "Đây là tám pháp có nhiều lợi ích.",
  "dn34:2.1.30": "Tám pháp nào cần được tu tập?",
  "dn34:2.1.31": "Đó là con đường thánh tám ngành, tức là:",
  "dn34:2.1.32": "chánh kiến, chánh tư duy, chánh ngữ, chánh nghiệp, chánh mạng, chánh tinh tấn, chánh niệm, chánh định.",
  "dn34:2.1.33": "Đây là tám pháp cần được tu tập.",
  "dn34:2.1.34": "Tám pháp nào cần được hiểu rõ?",
  "dn34:2.1.35": "Tám pháp ở đời:",
  "dn34:2.1.36": "được lợi và mất lợi, có danh và mất danh, bị chê và được khen, vui và khổ.",
  "dn34:2.1.37": "Đây là tám pháp cần được hiểu rõ.",
  "dn34:2.1.38": "Tám pháp nào cần được từ bỏ?",
  "dn34:2.1.39": "Tám điều sai lạc:",
  "dn34:2.1.40": "tà kiến, tà tư duy, tà ngữ, tà nghiệp, tà mạng, tà tinh tấn, tà niệm, tà định.",
  "dn34:2.1.41": "Đây là tám pháp cần được từ bỏ.",
  "dn34:2.1.42": "Tám pháp nào thuộc phần sa sút?",
  "dn34:2.1.43": "Tám nền tảng của sự lười biếng.",
  "dn34:2.1.44": "Này hiền giả, ở đây vị tỳ-kheo có việc phải làm,",
  "dn34:2.1.45": "vị ấy nghĩ rằng:",
  "dn34:2.1.46": "‘Ta sẽ phải làm việc; nhưng khi làm việc thì thân ta sẽ mệt, thôi ta nằm xuống.’",
  "dn34:2.1.47": "Vị ấy nằm xuống, không khởi lên tinh tấn để đạt điều chưa đạt, chứng điều chưa chứng, thực hiện điều chưa tự mình chứng ngộ.",
  "dn34:2.1.48": "Đây là nền tảng thứ nhất của sự lười biếng.",
  "dn34:2.1.49": "Lại nữa, này hiền giả, vị tỳ-kheo đã làm xong việc.",
  "dn34:2.1.50": "Vị ấy nghĩ rằng:",
  "dn34:2.1.51": "‘Ta đã làm việc xong; nhưng khi làm việc thì thân ta đã mệt, thôi ta nằm xuống.’",
  "dn34:2.1.52": "Vị ấy nằm xuống, không khởi lên tinh tấn …",
  "dn34:2.1.53": "Đây là nền tảng thứ hai của sự lười biếng.",
  "dn34:2.1.54": "Lại nữa, này hiền giả, vị tỳ-kheo phải đi đường.",
  "dn34:2.1.55": "Vị ấy nghĩ như vầy:",
  "dn34:2.1.56": "‘Ta sẽ phải đi đường; nhưng khi đi đường, thân ta sẽ mệt mỏi; thôi, ta hãy nằm xuống.’",
  "dn34:2.1.57": "Vị ấy nằm xuống, không khởi lên tinh tấn …",
  "dn34:2.1.58": "Đây là nền tảng biếng nhác thứ ba.",
  "dn34:2.1.59": "Lại nữa, này hiền giả, vị tỳ-kheo đã đi đường xong.",
  "dn34:2.1.60": "Vị ấy nghĩ như vầy:",
  "dn34:2.1.61": "‘Ta đã đi đường; nhưng khi đi đường, thân ta đã mệt mỏi; thôi, ta hãy nằm xuống.’",
  "dn34:2.1.62": "Vị ấy nằm xuống, không khởi lên tinh tấn …",
  "dn34:2.1.63": "Đây là nền tảng biếng nhác thứ tư.",
  "dn34:2.1.64": "Lại nữa, này hiền giả, vị tỳ-kheo đi khất thực trong làng hay thị trấn, không kiếm được đủ thức ăn, dù thô hay ngon, cho vừa nhu cầu.",
  "dn34:2.1.65": "Vị ấy nghĩ như vầy:",
  "dn34:2.1.66": "‘Ta đi khất thực trong làng hay thị trấn, đã không kiếm được đủ thức ăn, dù thô hay ngon, cho vừa nhu cầu. Vì vậy thân ta mệt mỏi, không làm việc được; thôi, ta hãy nằm xuống.’ …",
  "dn34:2.1.67": "Đây là nền tảng biếng nhác thứ năm.",
  "dn34:2.1.68": "Lại nữa, này hiền giả, vị tỳ-kheo đi khất thực trong làng hay thị trấn, kiếm được đủ thức ăn, dù thô hay ngon, cho vừa nhu cầu.",
  "dn34:2.1.69": "Vị ấy nghĩ như vầy:",
  "dn34:2.1.70": "‘Ta đi khất thực trong làng hay thị trấn, đã kiếm được đủ thức ăn, dù thô hay ngon, cho vừa nhu cầu. Vì vậy thân ta nặng nề, không làm việc được, như thể đầy ắp thịt; thôi, ta hãy nằm xuống.’",
  "dn34:2.1.71": "Vị ấy nằm xuống …",
  "dn34:2.1.72": "Đây là nền tảng biếng nhác thứ sáu.",
  "dn34:2.1.73": "Lại nữa, này hiền giả, vị tỳ-kheo mắc một chứng bệnh nhẹ. Vị ấy nghĩ như vầy:",
  "dn34:2.1.74": "‘Ta đang mắc chứng bệnh nhẹ này; có cớ để nằm xuống; thôi, ta hãy nằm xuống.’",
  "dn34:2.1.75": "Vị ấy nằm xuống …",
  "dn34:2.1.76": "Đây là nền tảng biếng nhác thứ bảy.",
  "dn34:2.1.77": "Lại nữa, này hiền giả, vị tỳ-kheo vừa mới khỏi bệnh, mới đứng dậy sau cơn bệnh không bao lâu.",
  "dn34:2.1.78": "Vị ấy nghĩ như vầy:",
  "dn34:2.1.79": "‘Ta vừa mới khỏi bệnh, mới đứng dậy sau cơn bệnh không bao lâu.",
  "dn34:2.1.80": "Thân ta còn yếu, không làm việc được; thôi, ta hãy nằm xuống.’",
  "dn34:2.1.81": "Vị ấy nằm xuống …",
  "dn34:2.1.82": "Đây là nền tảng biếng nhác thứ tám.",
  "dn34:2.1.83": "Đây là tám pháp đưa đến sa sút.",
  "dn34:2.1.84": "Thế nào là tám pháp đưa đến vượt trội?",
  "dn34:2.1.85": "Đó là tám nền tảng khởi lên tinh tấn.",
  "dn34:2.1.86": "Ở đây, này hiền giả, vị tỳ-kheo có việc phải làm. Vị ấy nghĩ như vầy:",
  "dn34:2.1.87": "‘Ta sẽ phải làm việc; nhưng khi làm việc, không dễ để chú tâm đến lời dạy của chư Phật; thôi, ta hãy khởi lên tinh tấn để đạt điều chưa đạt, chứng điều chưa chứng, tự mình thấy rõ điều chưa thấy rõ.’",
  "dn34:2.1.88": "Vị ấy khởi lên tinh tấn để đạt điều chưa đạt, chứng điều chưa chứng, tự mình thấy rõ điều chưa thấy rõ.",
  "dn34:2.1.89": "Đây là nền tảng khởi lên tinh tấn thứ nhất.",
  "dn34:2.1.90": "Lại nữa, này hiền giả, vị tỳ-kheo đã làm xong việc.",
  "dn34:2.1.91": "Vị ấy nghĩ như vầy:",
  "dn34:2.1.92": "‘Ta đã làm xong việc; nhưng khi làm việc, ta đã không thể chú tâm đến lời dạy của chư Phật; thôi, ta hãy khởi lên tinh tấn …",
  "dn34:2.1.93": "Đây là nền tảng khởi lên tinh tấn thứ hai.",
  "dn34:2.1.94": "Lại nữa, này hiền giả, vị tỳ-kheo phải đi đường.",
  "dn34:2.1.95": "Vị ấy nghĩ như vầy:",
  "dn34:2.1.96": "‘Ta sẽ phải đi đường; nhưng khi đi đường, không dễ để chú tâm đến lời dạy của chư Phật; thôi, ta hãy khởi lên tinh tấn …",
  "dn34:2.1.97": "Đây là nền tảng khởi lên tinh tấn thứ ba.",
  "dn34:2.1.98": "Lại nữa, này hiền giả, vị tỳ-kheo đã đi đường xong.",
  "dn34:2.1.99": "Vị ấy nghĩ như vầy:",
  "dn34:2.1.100": "‘Ta đã đi đường; nhưng khi đi đường, ta đã không thể chú tâm đến lời dạy của chư Phật; thôi, ta hãy khởi lên tinh tấn …",
  "dn34:2.1.101": "Đây là nền tảng khởi lên tinh tấn thứ tư.",
  "dn34:2.1.102": "Lại nữa, này hiền giả, vị tỳ-kheo đi khất thực trong làng hay thị trấn, không kiếm được đủ thức ăn, dù thô hay ngon, cho vừa nhu cầu.",
  "dn34:2.1.103": "Vị ấy nghĩ như vầy:",
  "dn34:2.1.104": "‘Khi tôi đi khất thực trong làng hay thị trấn, tôi không được đầy đủ thức ăn, dù thô hay ngon, theo nhu cầu. Vì vậy thân tôi nhẹ nhàng, dễ sử dụng. Nào, tôi sẽ khởi lên tinh tấn …",
  "dn34:2.1.105": "Đây là nền tảng khởi phát thứ năm.",
  "dn34:2.1.106": "Lại nữa, này các hiền giả, khi vị tỳ-kheo đi khất thực trong làng hay thị trấn, vị ấy được đầy đủ thức ăn, dù thô hay ngon, theo nhu cầu.",
  "dn34:2.1.107": "Vị ấy nghĩ như vầy:",
  "dn34:2.1.108": "‘Khi tôi đi khất thực trong làng hay thị trấn, tôi đã được đầy đủ thức ăn, dù thô hay ngon, theo nhu cầu.",
  "dn34:2.1.109": "Vì vậy thân tôi khỏe mạnh, dễ sử dụng. Nào, tôi sẽ khởi lên tinh tấn …",
  "dn34:2.1.110": "Đây là nền tảng khởi phát thứ sáu.",
  "dn34:2.1.111": "Lại nữa, này các hiền giả, vị tỳ-kheo mắc một cơn bệnh nhẹ.",
  "dn34:2.1.112": "Vị ấy nghĩ như vầy:",
  "dn34:2.1.113": "‘Tôi đang mắc một cơn bệnh nhẹ này; nhưng có thể bệnh này sẽ nặng thêm. Nào, tôi sẽ khởi lên tinh tấn …",
  "dn34:2.1.114": "Đây là nền tảng khởi phát thứ bảy.",
  "dn34:2.1.115": "Lại nữa, này các hiền giả, vị tỳ-kheo vừa mới khỏi bệnh, mới bình phục không bao lâu.",
  "dn34:2.1.116": "Vị ấy nghĩ như vầy:",
  "dn34:2.1.117": "‘Tôi vừa mới khỏi bệnh, mới bình phục không bao lâu; nhưng có thể bệnh ấy sẽ tái phát. Nào, tôi sẽ khởi lên tinh tấn để đạt được điều chưa đạt, chứng được điều chưa chứng, tự mình thấy rõ điều chưa thấy rõ.’",
  "dn34:2.1.118": "Vị ấy khởi lên tinh tấn để đạt được điều chưa đạt, chứng được điều chưa chứng, tự mình thấy rõ điều chưa thấy rõ.",
  "dn34:2.1.119": "Đây là nền tảng khởi phát thứ tám.",
  "dn34:2.1.120": "Đây là tám pháp đưa đến sự vượt trội.",
  "dn34:2.1.121": "Tám pháp nào là khó thấu đạt?",
  "dn34:2.1.122": "Tám lúc không thuận tiện, không đúng thời để sống đời phạm hạnh.",
  "dn34:2.1.123": "Ở đây, này các hiền giả, Như Lai xuất hiện ở đời, là bậc A-la-hán, bậc Chánh Đẳng Giác; và pháp được giảng dạy là pháp đưa đến lắng dịu, đưa đến tắt hẳn, đưa đến giác ngộ, do bậc Thiện Thệ tuyên thuyết.",
  "dn34:2.1.124": "Nhưng người này lại sinh vào địa ngục.",
  "dn34:2.1.125": "Đây là lúc không thuận tiện thứ nhất, không đúng thời để sống đời phạm hạnh.",
  "dn34:2.1.126": "Lại nữa, này các hiền giả, Như Lai xuất hiện ở đời, là bậc A-la-hán, bậc Chánh Đẳng Giác; và pháp được giảng dạy là pháp đưa đến lắng dịu, đưa đến tắt hẳn, đưa đến giác ngộ, do bậc Thiện Thệ tuyên thuyết.",
  "dn34:2.1.127": "Nhưng người này lại sinh vào loài súc sinh.",
  "dn34:2.1.128": "Đây là lúc không thuận tiện thứ hai, không đúng thời để sống đời phạm hạnh.",
  "dn34:2.1.129": "Lại nữa …",
  "dn34:2.1.130": "sinh vào cõi ngạ quỷ.",
  "dn34:2.1.131": "Đây là lúc không thuận tiện thứ ba, không đúng thời để sống đời phạm hạnh.",
  "dn34:2.1.132": "Lại nữa …",
  "dn34:2.1.133": "sinh vào một cõi trời sống lâu nào đó.",
  "dn34:2.1.134": "Đây là lúc không thuận tiện thứ tư, không đúng thời để sống đời phạm hạnh.",
  "dn34:2.1.135": "Lại nữa …",
  "dn34:2.1.136": "sinh ra ở các vùng biên địa, giữa những người man dã, không biết đạo lý, nơi không có đường đến với các tỳ-kheo, tỳ-kheo-ni, nam cư sĩ, nữ cư sĩ.",
  "dn34:2.1.137": "Đây là lúc không thuận tiện thứ năm, không đúng thời để sống đời phạm hạnh.",
  "dn34:2.1.138": "Lại nữa …",
  "dn34:2.1.139": "người này sinh ra ở các xứ trung tâm, nhưng lại có tà kiến, thấy biết sai lệch:",
  "dn34:2.1.140": "‘Không có bố thí, không có cúng dường, không có tế lễ; không có quả, không có kết quả của các nghiệp lành dữ; không có đời này, không có đời sau; không có mẹ, không có cha; không có chúng sinh hóa sinh; không có ở đời những vị sa-môn, bà-la-môn sống đúng đường, hành đúng cách, tự mình với thắng trí chứng ngộ rồi tuyên bố đời này và đời sau.’",
  "dn34:2.1.141": "Đây là lúc không thuận tiện thứ sáu, không đúng thời để sống đời phạm hạnh.",
  "dn34:2.1.142": "Lại nữa …",
  "dn34:2.1.143": "người này sinh ra ở các xứ trung tâm, nhưng lại ngu tối, đần độn, câm ngọng, không đủ khả năng hiểu nghĩa lời nói hay hay dở.",
  "dn34:2.1.144": "Đây là lúc không thuận tiện thứ bảy, không đúng thời để sống đời phạm hạnh.",
  "dn34:2.1.145": "Lại nữa …",
  "dn34:2.1.146": "người này sinh ra ở các xứ trung tâm, lại có trí, không đần độn, không câm ngọng, có khả năng hiểu nghĩa lời nói hay hay dở.",
  "dn34:2.1.147": "Đây là lúc không thuận tiện thứ tám, không đúng thời để sống đời phạm hạnh.",
  "dn34:2.1.148": "Đây là tám pháp khó thấu đạt.",
  "dn34:2.1.149": "Tám pháp nào cần được làm phát sinh?",
  "dn34:2.1.150": "Tám suy nghĩ của bậc lớn là:",
  "dn34:2.1.151": "Pháp này dành cho người ít muốn, không dành cho người nhiều ham muốn.",
  "dn34:2.1.152": "Pháp này dành cho người biết đủ, không dành cho người không biết đủ.",
  "dn34:2.1.153": "Pháp này dành cho người sống tách riêng, không dành cho người thích tụ tập.",
  "dn34:2.1.154": "Pháp này dành cho người tinh cần, không dành cho người biếng nhác.",
  "dn34:2.1.155": "Pháp này dành cho người có chánh niệm vững vàng, không dành cho người thất niệm.",
  "dn34:2.1.156": "Pháp này dành cho người tâm định tĩnh, không dành cho người tâm không định tĩnh.",
  "dn34:2.1.157": "Pháp này dành cho người có trí tuệ, không dành cho người kém trí.",
  "dn34:2.1.158": "Pháp này dành cho người không rối ren lan man, không dành cho người thích rối ren lan man. Đó là tám pháp cần được làm cho sinh khởi.",
  "dn34:2.1.159": "Tám pháp nào cần được hiểu rõ?",
  "dn34:2.1.160": "Tám cảnh giới vượt thắng—",
  "dn34:2.1.161": "Một người còn nhận biết sắc ở trong, thấy các sắc ở ngoài, nhỏ, đẹp hoặc xấu, nghĩ rằng: ‘Ta thắng vượt chúng, ta biết và ta thấy’—",
  "dn34:2.1.162": "người ấy có nhận thức như vậy.",
  "dn34:2.1.163": "Đây là cảnh giới vượt thắng thứ nhất.",
  "dn34:2.1.164": "Một người còn nhận biết sắc ở trong, thấy các sắc ở ngoài, vô lượng, đẹp hoặc xấu, nghĩ rằng: ‘Ta thắng vượt chúng, ta biết và ta thấy’—",
  "dn34:2.1.165": "người ấy có nhận thức như vậy.",
  "dn34:2.1.166": "Đây là cảnh giới vượt thắng thứ hai.",
  "dn34:2.1.167": "Một người không còn nhận biết sắc ở trong, thấy các sắc ở ngoài, nhỏ, đẹp hoặc xấu, nghĩ rằng: ‘Ta thắng vượt chúng, ta biết và ta thấy’—",
  "dn34:2.1.168": "người ấy có nhận thức như vậy.",
  "dn34:2.1.169": "Đây là cảnh giới vượt thắng thứ ba.",
  "dn34:2.1.170": "Một người không còn nhận biết sắc ở trong, thấy các sắc ở ngoài, vô lượng, đẹp hoặc xấu, nghĩ rằng: ‘Ta thắng vượt chúng, ta biết và ta thấy’—",
  "dn34:2.1.171": "người ấy có nhận thức như vậy.",
  "dn34:2.1.172": "Đây là cảnh giới vượt thắng thứ tư.",
  "dn34:2.1.173": "Một người không còn nhận biết sắc ở trong, thấy các sắc ở ngoài màu xanh, xanh màu, hiện ra xanh, ánh xanh.",
  "dn34:2.1.174": "Ví như hoa lanh màu xanh, xanh màu, hiện ra xanh, ánh xanh; hoặc như tấm vải Ba-la-nại được đánh bóng cả hai mặt, màu xanh, xanh màu, hiện ra xanh, ánh xanh;",
  "dn34:2.1.175": "cũng vậy, một người không còn nhận biết sắc ở trong, thấy các sắc ở ngoài màu xanh, xanh màu, hiện ra xanh, ánh xanh, nghĩ rằng: ‘Ta thắng vượt chúng, ta biết và ta thấy’, người ấy có nhận thức như vậy.",
  "dn34:2.1.176": "Đây là cảnh giới vượt thắng thứ năm.",
  "dn34:2.1.177": "Một người không còn nhận biết sắc ở trong, thấy các sắc ở ngoài màu vàng, vàng màu, hiện ra vàng, ánh vàng.",
  "dn34:2.1.178": "Ví như hoa kim hương màu vàng, vàng màu, hiện ra vàng, ánh vàng; hoặc như tấm vải Ba-la-nại được đánh bóng cả hai mặt, màu vàng, vàng màu, hiện ra vàng, ánh vàng;",
  "dn34:2.1.179": "cũng vậy, một người không còn nhận biết sắc ở trong, thấy các sắc ở ngoài màu vàng, vàng màu, hiện ra vàng, ánh vàng, nghĩ rằng: ‘Ta thắng vượt chúng, ta biết và ta thấy’, người ấy có nhận thức như vậy.",
  "dn34:2.1.180": "Đây là cảnh giới vượt thắng thứ sáu.",
  "dn34:2.1.181": "Một người không còn nhận biết sắc ở trong, thấy các sắc ở ngoài màu đỏ, đỏ màu, hiện ra đỏ, ánh đỏ.",
  "dn34:2.1.182": "Ví như hoa bần-đầu-sanh màu đỏ, đỏ màu, hiện ra đỏ, ánh đỏ; hoặc như tấm vải Ba-la-nại được đánh bóng cả hai mặt, màu đỏ, đỏ màu, hiện ra đỏ, ánh đỏ;",
  "dn34:2.1.183": "cũng vậy, một người không còn nhận biết sắc ở trong, thấy các sắc ở ngoài màu đỏ, đỏ màu, hiện ra đỏ, ánh đỏ, nghĩ rằng: ‘Ta thắng vượt chúng, ta biết và ta thấy’, người ấy có nhận thức như vậy.",
  "dn34:2.1.184": "Đây là cảnh giới vượt thắng thứ bảy.",
  "dn34:2.1.185": "Một người không còn nhận biết sắc ở trong, thấy các sắc ở ngoài màu trắng, trắng màu, hiện ra trắng, ánh trắng.",
  "dn34:2.1.186": "Ví như sao mai màu trắng, trắng màu, hiện ra trắng, ánh trắng; hoặc như tấm vải Ba-la-nại được đánh bóng cả hai mặt, màu trắng, trắng màu, hiện ra trắng, ánh trắng;",
  "dn34:2.1.187": "cũng vậy, một người không còn nhận biết sắc ở trong, thấy các sắc ở ngoài màu trắng, trắng màu, hiện ra trắng, ánh trắng, nghĩ rằng: ‘Ta thắng vượt chúng, ta biết và ta thấy’, người ấy có nhận thức như vậy.",
  "dn34:2.1.188": "Đây là cảnh giới vượt thắng thứ tám.",
  "dn34:2.1.189": "Đó là tám pháp cần được hiểu rõ.",
  "dn34:2.1.190": "Tám pháp nào cần được chứng ngộ?",
  "dn34:2.1.191": "Tám giải thoát—",
  "dn34:2.1.192": "Có sắc, vị ấy thấy các sắc.",
  "dn34:2.1.193": "Đây là giải thoát thứ nhất.",
  "dn34:2.1.194": "Một người không còn nhận biết sắc ở trong, thấy các sắc ở ngoài.",
  "dn34:2.1.195": "Đây là giải thoát thứ hai.",
  "dn34:2.1.196": "Vị ấy chuyên chú vào cái đẹp.",
  "dn34:2.1.197": "Đây là giải thoát thứ ba.",
  "dn34:2.1.198": "Vượt hẳn mọi nhận biết về sắc, chấm dứt mọi nhận biết về ngăn ngại, không tác ý đến các nhận biết sai khác, nghĩ rằng: ‘Hư không là vô biên’, vị ấy chứng và an trú trong cảnh giới hư không vô biên.",
  "dn34:2.1.199": "Đây là giải thoát thứ tư.",
  "dn34:2.1.200": "Vượt hẳn cảnh giới hư không vô biên, nghĩ rằng: ‘Thức là vô biên’, vị ấy chứng và an trú trong cảnh giới thức vô biên.",
  "dn34:2.1.201": "Đây là giải thoát thứ năm.",
  "dn34:2.1.202": "Vượt hẳn cảnh giới thức vô biên, nghĩ rằng: ‘Không có gì cả’, vị ấy chứng và an trú trong cảnh giới không có gì cả.",
  "dn34:2.1.203": "Đây là giải thoát thứ sáu.",
  "dn34:2.1.204": "Vượt hẳn xứ không có gì, vị ấy chứng và an trú trong xứ không phải tưởng cũng không phải không tưởng.",
  "dn34:2.1.205": "Đây là giải thoát thứ bảy.",
  "dn34:2.1.206": "Vượt hẳn xứ không phải tưởng cũng không phải không tưởng, vị ấy chứng và an trú trong sự diệt của tưởng và thọ.",
  "dn34:2.1.207": "Đây là giải thoát thứ tám.",
  "dn34:2.1.208": "Đây là tám pháp cần được tự mình chứng ngộ.",
  "dn34:2.1.209": "Như vậy, tám mươi pháp này là có thật, chân thật, đúng như vậy, không sai khác, được Như Lai giác ngộ trọn vẹn một cách đúng đắn.",
  "dn34:2.2.0": "9. Chín pháp",
  "dn34:2.2.1": "Chín pháp có nhiều lợi ích … chín pháp cần được tự mình chứng ngộ.",
  "dn34:2.2.2": "Thế nào là chín pháp có nhiều lợi ích?",
  "dn34:2.2.3": "Chín pháp lấy sự tác ý đúng đắn làm gốc: do tác ý đúng đắn nên niềm vui sinh khởi, do có niềm vui nên hỷ sinh khởi, do tâm có hỷ nên thân được lắng dịu, do thân lắng dịu nên cảm nhận an lạc, người an lạc thì tâm được định tĩnh, khi tâm định tĩnh thì biết và thấy như thật, do biết và thấy như thật nên chán lìa, do chán lìa nên ly tham, do ly tham nên giải thoát.",
  "dn34:2.2.4": "Đây là chín pháp có nhiều lợi ích.",
  "dn34:2.2.5": "Thế nào là chín pháp cần được tu tập?",
  "dn34:2.2.6": "Chín phần của sự tinh cần hướng đến thanh tịnh:",
  "dn34:2.2.7": "thanh tịnh giới là phần của sự tinh cần hướng đến thanh tịnh, thanh tịnh tâm là phần của sự tinh cần hướng đến thanh tịnh, thanh tịnh thấy biết là phần của sự tinh cần hướng đến thanh tịnh, thanh tịnh vượt qua nghi là phần của sự tinh cần hướng đến thanh tịnh, thanh tịnh thấy biết về đường và không phải đường là phần của sự tinh cần hướng đến thanh tịnh, thanh tịnh thấy biết về con đường thực hành là phần của sự tinh cần hướng đến thanh tịnh, thanh tịnh thấy biết là phần của sự tinh cần hướng đến thanh tịnh, thanh tịnh trí tuệ là phần của sự tinh cần hướng đến thanh tịnh, thanh tịnh giải thoát là phần của sự tinh cần hướng đến thanh tịnh.",
  "dn34:2.2.8": "Đây là chín pháp cần được tu tập.",
  "dn34:2.2.9": "Thế nào là chín pháp cần được hiểu rõ?",
  "dn34:2.2.10": "Chín chỗ ở của chúng sinh:",
  "dn34:2.2.11": "Này các hiền giả, có những chúng sinh thân khác nhau, tưởng khác nhau, như loài người, một số chư thiên và một số chúng sinh ở cõi khổ.",
  "dn34:2.2.12": "Đây là chỗ ở của chúng sinh thứ nhất.",
  "dn34:2.2.13": "Này các hiền giả, có những chúng sinh thân khác nhau nhưng tưởng giống nhau, như các vị trời thuộc Phạm chúng thiên mới sinh lần đầu.",
  "dn34:2.2.14": "Đây là chỗ ở của chúng sinh thứ hai.",
  "dn34:2.2.15": "Này các hiền giả, có những chúng sinh thân giống nhau nhưng tưởng khác nhau, như các vị trời Quang Âm.",
  "dn34:2.2.16": "Đây là chỗ ở của chúng sinh thứ ba.",
  "dn34:2.2.17": "Này các hiền giả, có những chúng sinh thân giống nhau, tưởng cũng giống nhau, như các vị trời Biến Tịnh.",
  "dn34:2.2.18": "Đây là chỗ ở của chúng sinh thứ tư.",
  "dn34:2.2.19": "Này các hiền giả, có những chúng sinh không có tưởng, không cảm nhận, như các vị trời Vô Tưởng.",
  "dn34:2.2.20": "Đây là chỗ ở của chúng sinh thứ năm.",
  "dn34:2.2.21": "Này các hiền giả, có những chúng sinh do vượt hẳn mọi tưởng về sắc, do sự lắng dứt của tưởng về chướng ngại, do không tác ý đến tưởng sai khác, nghĩ rằng: ‘Hư không là vô biên’, nên đạt đến xứ hư không vô biên.",
  "dn34:2.2.22": "Đây là chỗ ở của chúng sinh thứ sáu.",
  "dn34:2.2.23": "Này các hiền giả, có những chúng sinh do vượt hẳn xứ hư không vô biên, nghĩ rằng: ‘Thức là vô biên’, nên đạt đến xứ thức vô biên.",
  "dn34:2.2.24": "Đây là chỗ ở của chúng sinh thứ bảy.",
  "dn34:2.2.25": "Này các hiền giả, có những chúng sinh do vượt hẳn xứ thức vô biên, nghĩ rằng: ‘Không có gì cả’, nên đạt đến xứ không có gì.",
  "dn34:2.2.26": "Đây là chỗ ở của chúng sinh thứ tám.",
  "dn34:2.2.27": "Này các hiền giả, có những chúng sinh do vượt hẳn xứ không có gì, nên đạt đến xứ không phải tưởng cũng không phải không tưởng.",
  "dn34:2.2.28": "Đây là chỗ ở của chúng sinh thứ chín.",
  "dn34:2.2.29": "Đây là chín pháp cần được hiểu rõ.",
  "dn34:2.2.30": "Thế nào là chín pháp cần được từ bỏ?",
  "dn34:2.2.31": "Chín pháp lấy ái làm gốc:",
  "dn34:2.2.32": "Do duyên ái nên có tìm cầu, do duyên tìm cầu nên có đạt được, do duyên đạt được nên có phân định, do duyên phân định nên có ham muốn và say đắm, do duyên ham muốn và say đắm nên có dính chặt, do duyên dính chặt nên có chấp giữ, do duyên chấp giữ nên có keo kiệt, do duyên keo kiệt nên có giữ gìn phòng hộ; vì việc giữ gìn phòng hộ mà phát sinh cầm gậy, cầm dao, tranh cãi, xung đột, tranh chấp, cãi vã, nói xấu, nói dối và nhiều pháp ác bất thiện khác.",
  "dn34:2.2.33": "Đây là chín pháp cần được từ bỏ.",
  "dn34:2.2.34": "Thế nào là chín pháp đưa đến sa sút?",
  "dn34:2.2.35": "Chín điều làm khởi lên oán giận:",
  "dn34:2.2.36": "‘Người ấy đã làm hại tôi’, nên ôm lòng oán giận,",
  "dn34:2.2.37": "‘Người ấy đang làm hại tôi’, nên ôm lòng oán giận,",
  "dn34:2.2.38": "‘Người ấy sẽ làm hại tôi’, nên ôm lòng oán giận;",
  "dn34:2.2.39": "‘Người ấy đã làm hại người tôi thương mến và vừa ý’, nên ôm lòng oán giận …",
  "dn34:2.2.40": "‘Người ấy đang làm hại’, nên ôm lòng oán giận …",
  "dn34:2.2.41": "‘Người ấy sẽ làm hại’, nên ôm lòng oán giận;",
  "dn34:2.2.42": "‘Người ấy đã làm lợi cho người tôi không ưa, không vừa ý’, nên ôm lòng oán giận …",
  "dn34:2.2.43": "‘Người ấy đang làm lợi’, nên ôm lòng oán giận …",
  "dn34:2.2.44": "‘Nó sẽ làm hại ta’ nên ôm lòng oán giận.",
  "dn34:2.2.45": "Chín pháp này đưa đến sa sút.",
  "dn34:2.2.46": "Chín pháp nào đưa đến vượt trội?",
  "dn34:2.2.47": "Chín cách dẹp bỏ oán giận:",
  "dn34:2.2.48": "‘Nó đã làm hại ta, chuyện ấy ở đây có ích gì?’ vị ấy dẹp bỏ oán giận;",
  "dn34:2.2.49": "‘Nó đang làm hại ta, chuyện ấy ở đây có ích gì?’ vị ấy dẹp bỏ oán giận;",
  "dn34:2.2.50": "‘Nó sẽ làm hại ta, chuyện ấy ở đây có ích gì?’ vị ấy dẹp bỏ oán giận;",
  "dn34:2.2.51": "‘Nó đã làm hại người ta thương mến, người ta vừa ý …",
  "dn34:2.2.52": "đang làm hại …",
  "dn34:2.2.53": "sẽ làm hại, chuyện ấy ở đây có ích gì?’ vị ấy dẹp bỏ oán giận;",
  "dn34:2.2.54": "‘Nó đã làm điều lợi ích cho người ta không thương, không vừa ý …",
  "dn34:2.2.55": "đang làm điều lợi ích …",
  "dn34:2.2.56": "sẽ làm điều lợi ích, chuyện ấy ở đây có ích gì?’ vị ấy dẹp bỏ oán giận.",
  "dn34:2.2.57": "Chín pháp này đưa đến vượt trội.",
  "dn34:2.2.58": "Chín pháp nào khó thấu hiểu?",
  "dn34:2.2.59": "Chín sự sai khác—",
  "dn34:2.2.60": "Do sự sai khác của các giới mà phát sinh sự sai khác của xúc; do sự sai khác của xúc mà phát sinh sự sai khác của cảm thọ; do sự sai khác của cảm thọ mà phát sinh sự sai khác của tưởng; do sự sai khác của tưởng mà phát sinh sự sai khác của suy nghĩ; do sự sai khác của suy nghĩ mà phát sinh sự sai khác của ý muốn; do sự sai khác của ý muốn mà phát sinh sự sai khác của nung nấu; do sự sai khác của nung nấu mà phát sinh sự sai khác của tìm cầu; do sự sai khác của tìm cầu mà phát sinh sự sai khác của đạt được (…).",
  "dn34:2.2.61": "Chín pháp này khó thấu hiểu.",
  "dn34:2.2.62": "Chín pháp nào cần được làm phát sinh?",
  "dn34:2.2.63": "Chín tưởng—",
  "dn34:2.2.64": "tưởng về bất tịnh, tưởng về cái chết, tưởng về sự nhơ chán trong đồ ăn, tưởng không thích thú với toàn thế gian, tưởng vô thường, tưởng khổ trong cái vô thường, tưởng vô ngã trong cái khổ, tưởng từ bỏ, tưởng ly tham.",
  "dn34:2.2.65": "Chín pháp này cần được làm phát sinh.",
  "dn34:2.2.66": "Chín pháp nào cần được thắng tri?",
  "dn34:2.2.67": "Chín an trú tuần tự—",
  "dn34:2.2.68": "Này các hiền giả, ở đây vị tỳ kheo lìa các dục, lìa các pháp bất thiện, chứng và an trú thiền thứ nhất, có tầm có tứ, có hỷ lạc do lìa dục sinh.",
  "dn34:2.2.69": "Do lắng yên tầm và tứ … chứng và an trú thiền thứ hai.",
  "dn34:2.2.70": "Do phai nhạt hỷ … chứng và an trú thiền thứ ba.",
  "dn34:2.2.71": "Do dứt lạc … chứng và an trú thiền thứ tư.",
  "dn34:2.2.72": "Vượt hẳn mọi tưởng về sắc … chứng và an trú không vô biên xứ.",
  "dn34:2.2.73": "Vượt hẳn không vô biên xứ, nghĩ rằng ‘thức là vô biên’, vị ấy chứng và an trú thức vô biên xứ.",
  "dn34:2.2.74": "Vượt hẳn thức vô biên xứ, nghĩ rằng ‘không có gì’, vị ấy chứng và an trú vô sở hữu xứ.",
  "dn34:2.2.75": "Vượt hẳn vô sở hữu xứ, vị ấy chứng và an trú phi tưởng phi phi tưởng xứ.",
  "dn34:2.2.76": "Vượt hẳn phi tưởng phi phi tưởng xứ, vị ấy chứng và an trú diệt thọ tưởng.",
  "dn34:2.2.77": "Chín pháp này cần được thắng tri.",
  "dn34:2.2.78": "Chín pháp nào cần được chứng ngộ?",
  "dn34:2.2.79": "Chín sự diệt tuần tự—",
  "dn34:2.2.80": "Với người nhập thiền thứ nhất, tưởng về dục được diệt.",
  "dn34:2.2.81": "Với người nhập thiền thứ hai, tầm và tứ được diệt.",
  "dn34:2.2.82": "Với người nhập thiền thứ ba, hỷ được diệt.",
  "dn34:2.2.83": "Với người nhập thiền thứ tư, hơi thở vào và hơi thở ra được diệt.",
  "dn34:2.2.84": "Với người nhập không vô biên xứ, tưởng về sắc được diệt.",
  "dn34:2.2.85": "Với người nhập thức vô biên xứ, tưởng về không vô biên xứ được diệt.",
  "dn34:2.2.86": "Với người nhập vô sở hữu xứ, tưởng về thức vô biên xứ được diệt.",
  "dn34:2.2.87": "Với người nhập phi tưởng phi phi tưởng xứ, tưởng về vô sở hữu xứ được diệt.",
  "dn34:2.2.88": "Với người nhập diệt thọ tưởng, tưởng và thọ được diệt.",
  "dn34:2.2.89": "Chín pháp này cần được chứng ngộ.",
  "dn34:2.2.90": "Như vậy, chín mươi pháp này là có thật, chân thật, đúng như vậy, không sai khác, không khác đi, đã được Như Lai tự mình giác ngộ trọn vẹn.",
  "dn34:2.3.0": "10. Mười pháp",
  "dn34:2.3.1": "Mười pháp có nhiều lợi ích … mười pháp cần được chứng ngộ.",
  "dn34:2.3.2": "Mười pháp nào có nhiều lợi ích?",
  "dn34:2.3.3": "Mười pháp làm chỗ nương tựa—",
  "dn34:2.3.4": "Này hiền giả, ở đây vị tỳ kheo có giới, sống phòng hộ với sự phòng hộ của giới bổn, đầy đủ hạnh kiểm và chỗ lui tới, thấy sợ trong những lỗi nhỏ nhặt, thọ trì và học tập trong các điều học.",
  "dn34:2.3.5": "Này hiền giả, vị tỳ kheo có giới … học tập trong các điều học.",
  "dn34:2.3.6": "Đây cũng là một pháp làm chỗ nương tựa.",
  "dn34:2.3.7": "Lại nữa, này hiền giả, vị tỳ kheo nghe nhiều … được thấu suốt khéo bằng chánh kiến.",
  "dn34:2.3.8": "Này hiền giả, vị tỳ kheo nghe nhiều …",
  "dn34:2.3.9": "đây cũng là một pháp làm chỗ nương tựa.",
  "dn34:2.3.10": "Lại nữa, này hiền giả, vị tỳ kheo có bạn lành, có bạn đồng hành lành, có người cùng sống lành.",
  "dn34:2.3.11": "Này hiền giả, vị tỳ kheo … có người cùng sống lành.",
  "dn34:2.3.12": "Đây cũng là một pháp làm chỗ nương tựa.",
  "dn34:2.3.13": "Lại nữa, này hiền giả, vị tỳ kheo dễ dạy, có đủ những pháp khiến dễ dạy, kham nhẫn, khéo tiếp nhận lời chỉ dạy.",
  "dn34:2.3.14": "Này hiền giả, vị tỳ kheo … khéo tiếp nhận lời chỉ dạy.",
  "dn34:2.3.15": "Đây cũng là một pháp làm chỗ nương tựa.",
  "dn34:2.3.16": "Lại nữa, này hiền giả, vị tỳ kheo đối với những việc cần làm lớn nhỏ cho các vị đồng phạm hạnh thì khéo léo, không lười biếng, có đủ sự xem xét để tìm cách làm việc ấy, có khả năng làm, có khả năng sắp xếp.",
  "dn34:2.3.17": "Này hiền giả, vị tỳ kheo … có khả năng sắp xếp.",
  "dn34:2.3.18": "Đây cũng là một pháp làm chỗ nương tựa.",
  "dn34:2.3.19": "Lại nữa, này hiền giả, vị tỳ kheo yêu thích pháp, ưa nói về pháp, rất hoan hỷ trong pháp và luật cao hơn.",
  "dn34:2.3.20": "Này hiền giả, vị tỳ kheo … rất hoan hỷ trong pháp và luật cao hơn.",
  "dn34:2.3.21": "Đây cũng là một pháp làm chỗ nương tựa.",
  "dn34:2.3.22": "Lại nữa, này hiền giả, vị tỳ kheo biết đủ với bất cứ loại y áo, đồ ăn khất thực, chỗ ở, và thuốc men vật dụng chữa bệnh nào.",
  "dn34:2.3.23": "Này hiền giả, vị tỳ kheo …",
  "dn34:2.3.24": "đây cũng là một pháp làm chỗ nương tựa.",
  "dn34:2.3.25": "Lại nữa, này hiền giả, vị tỳ kheo sống tinh cần tinh tấn … trong các pháp lành.",
  "dn34:2.3.26": "Này hiền giả, vị tỳ kheo …",
  "dn34:2.3.27": "đây cũng là một pháp làm chỗ nương tựa.",
  "dn34:2.3.28": "Lại nữa, này hiền giả, vị tỳ kheo có chánh niệm, đầy đủ sự khéo léo tối thượng về chánh niệm, việc đã làm từ lâu, lời đã nói từ lâu cũng nhớ lại và ghi nhớ được.",
  "dn34:2.3.29": "Này hiền giả, vị tỳ kheo …",
  "dn34:2.3.30": "đây cũng là một pháp làm chỗ nương tựa.",
  "dn34:2.3.31": "Lại nữa, này hiền giả, vị tỳ kheo có trí tuệ, đầy đủ trí tuệ đưa đến thấy sự sinh và diệt, là bậc thánh, thấu suốt, đưa đến chấm dứt khổ một cách đúng đắn.",
  "dn34:2.3.32": "Này hiền giả, vị tỳ kheo …",
  "dn34:2.3.33": "đây cũng là một pháp làm chỗ nương tựa.",
  "dn34:2.3.34": "Mười pháp này rất lợi ích.",
  "dn34:2.3.35": "Mười pháp nào cần được tu tập?",
  "dn34:2.3.36": "Mười đề mục biến xứ—",
  "dn34:2.3.37": "Có người nhận biết biến xứ đất ở trên, ở dưới, ngang khắp, không hai, vô lượng.",
  "dn34:2.3.38": "Có người nhận biết biến xứ nước …",
  "dn34:2.3.39": "Có người nhận biết biến xứ lửa …",
  "dn34:2.3.40": "Có người nhận biết biến xứ gió …",
  "dn34:2.3.41": "Có người nhận biết biến xứ màu xanh …",
  "dn34:2.3.42": "Có người nhận biết biến xứ màu vàng …",
  "dn34:2.3.43": "Có người nhận biết biến xứ màu đỏ …",
  "dn34:2.3.44": "Có người nhận biết biến xứ màu trắng …",
  "dn34:2.3.45": "Có người nhận biết biến xứ hư không …",
  "dn34:2.3.46": "Có người nhận biết biến xứ thức ở trên, ở dưới, ngang khắp, không hai, vô lượng.",
  "dn34:2.3.47": "Mười pháp này cần được tu tập.",
  "dn34:2.3.48": "Mười pháp nào cần được hiểu rõ?",
  "dn34:2.3.49": "Mười xứ—",
  "dn34:2.3.50": "xứ mắt, xứ sắc, xứ tai, xứ tiếng, xứ mũi, xứ mùi, xứ lưỡi, xứ vị, xứ thân, xứ xúc chạm.",
  "dn34:2.3.51": "Mười pháp này cần được hiểu rõ.",
  "dn34:2.3.52": "Mười pháp nào cần được từ bỏ?",
  "dn34:2.3.53": "Mười điều sai lạc—",
  "dn34:2.3.54": "tà kiến, tư duy sai lạc, lời nói sai lạc, hành động sai lạc, nghề sống sai lạc, tinh tấn sai lạc, niệm sai lạc, định sai lạc, hiểu biết sai lạc, giải thoát sai lạc.",
  "dn34:2.3.55": "Đây là mười pháp cần phải từ bỏ.",
  "dn34:2.3.56": "Mười pháp nào đưa đến sa sút?",
  "dn34:2.3.57": "Mười đường nghiệp bất thiện—",
  "dn34:2.3.58": "sát sinh, lấy của không cho, tà hạnh trong dục, nói dối, nói hai lưỡi, nói lời thô ác, nói chuyện phù phiếm, tham lam, ác ý, tà kiến.",
  "dn34:2.3.59": "Đây là mười pháp đưa đến sa sút.",
  "dn34:2.3.60": "Mười pháp nào đưa đến đặc biệt hơn?",
  "dn34:2.3.61": "Mười đường nghiệp thiện—",
  "dn34:2.3.62": "tránh sát sinh, tránh lấy của không cho, tránh tà hạnh trong dục, tránh nói dối, tránh nói hai lưỡi, tránh nói lời thô ác, tránh nói chuyện phù phiếm, không tham lam, không ác ý, chánh kiến.",
  "dn34:2.3.63": "Đây là mười pháp đưa đến đặc biệt hơn.",
  "dn34:2.3.64": "Mười pháp nào khó thấu hiểu?",
  "dn34:2.3.65": "Mười chỗ ở của bậc thánh—",
  "dn34:2.3.66": "Này các hiền giả, ở đây vị tỳ-kheo đã dứt bỏ năm phần, đầy đủ sáu phần, có một sự phòng hộ, có bốn chỗ nương tựa, đã gạt bỏ các chân lý riêng lẻ, đã lắng dịu sự tìm cầu, có ý nghĩ không vẩn đục, thân hành an tịnh, tâm khéo giải thoát, trí khéo giải thoát.",
  "dn34:2.3.67": "Và này các hiền giả, thế nào là vị tỳ-kheo đã dứt bỏ năm phần?",
  "dn34:2.3.68": "Này các hiền giả, ở đây vị tỳ-kheo đã đoạn trừ dục tham, đã đoạn trừ ác ý, đã đoạn trừ hôn trầm thụy miên, đã đoạn trừ trạo cử hối quá, đã đoạn trừ nghi.",
  "dn34:2.3.69": "Như vậy, này các hiền giả, vị tỳ-kheo đã dứt bỏ năm phần.",
  "dn34:2.3.70": "Và này các hiền giả, thế nào là vị tỳ-kheo đầy đủ sáu phần?",
  "dn34:2.3.71": "Này các hiền giả, ở đây vị tỳ-kheo khi mắt thấy sắc thì không vui cũng không buồn, sống với tâm xả, có niệm, tỉnh giác.",
  "dn34:2.3.72": "Khi tai nghe tiếng …",
  "dn34:2.3.73": "khi mũi ngửi mùi …",
  "dn34:2.3.74": "khi lưỡi nếm vị …",
  "dn34:2.3.75": "khi thân chạm xúc chạm …",
  "dn34:2.3.76": "khi ý nhận biết pháp thì không vui cũng không buồn, sống với tâm xả, có niệm, tỉnh giác.",
  "dn34:2.3.77": "Như vậy, này các hiền giả, vị tỳ-kheo đầy đủ sáu phần.",
  "dn34:2.3.78": "Và này các hiền giả, thế nào là vị tỳ-kheo có một sự phòng hộ?",
  "dn34:2.3.79": "Này các hiền giả, ở đây vị tỳ-kheo đầy đủ tâm được phòng hộ bởi niệm.",
  "dn34:2.3.80": "Như vậy, này các hiền giả, vị tỳ-kheo có một sự phòng hộ.",
  "dn34:2.3.81": "Và này các hiền giả, thế nào là vị tỳ-kheo có bốn chỗ nương tựa?",
  "dn34:2.3.82": "Này các hiền giả, ở đây vị tỳ-kheo có suy xét rồi mới dùng một điều, có suy xét rồi mới chịu đựng một điều, có suy xét rồi mới tránh né một điều, có suy xét rồi mới trừ bỏ một điều.",
  "dn34:2.3.83": "Như vậy, này các hiền giả, vị tỳ-kheo có bốn chỗ nương tựa.",
  "dn34:2.3.84": "Và này các hiền giả, thế nào là vị tỳ-kheo đã gạt bỏ các chân lý riêng lẻ?",
  "dn34:2.3.85": "Này các hiền giả, ở đây những chân lý riêng lẻ của các sa-môn, bà-la-môn khác nhau trong đời, tất cả những điều ấy nơi vị tỳ-kheo đều đã bị đẩy lui, gạt bỏ, nhổ bỏ, mửa bỏ, buông bỏ, từ bỏ.",
  "dn34:2.3.86": "Như vậy, này các hiền giả, vị tỳ-kheo đã gạt bỏ các chân lý riêng lẻ.",
  "dn34:2.3.87": "Và này các hiền giả, thế nào là vị tỳ-kheo đã lắng dịu sự tìm cầu?",
  "dn34:2.3.88": "Này các hiền giả, ở đây nơi vị tỳ-kheo, sự tìm cầu dục đã được đoạn trừ, sự tìm cầu hiện hữu đã được đoạn trừ, sự tìm cầu đời sống phạm hạnh đã được lắng dịu.",
  "dn34:2.3.89": "Như vậy, này các hiền giả, vị tỳ-kheo đã lắng dịu sự tìm cầu.",
  "dn34:2.3.90": "Và này các hiền giả, thế nào là vị tỳ-kheo có ý nghĩ không vẩn đục?",
  "dn34:2.3.91": "Này các hiền giả, ở đây nơi vị tỳ-kheo, ý nghĩ về dục đã được đoạn trừ, ý nghĩ ác ý đã được đoạn trừ, ý nghĩ hại người đã được đoạn trừ.",
  "dn34:2.3.92": "Như vậy, này các hiền giả, vị tỳ-kheo có ý nghĩ không vẩn đục.",
  "dn34:2.3.93": "Và này các hiền giả, thế nào là vị tỳ-kheo có thân hành an tịnh?",
  "dn34:2.3.94": "Này các hiền giả, ở đây vị tỳ-kheo do từ bỏ lạc, từ bỏ khổ, do hỷ và ưu đã diệt mất từ trước, chứng và an trú thiền thứ tư, không khổ không lạc, thanh tịnh nhờ xả niệm.",
  "dn34:2.3.95": "Như vậy, này các hiền giả, vị tỳ-kheo có thân hành an tịnh.",
  "dn34:2.3.96": "Và này các hiền giả, thế nào là vị tỳ-kheo có tâm khéo giải thoát?",
  "dn34:2.3.97": "Này các hiền giả, ở đây tâm vị tỳ-kheo được giải thoát khỏi tham, được giải thoát khỏi sân, được giải thoát khỏi si.",
  "dn34:2.3.98": "Như vậy, này các hiền giả, vị tỳ-kheo có tâm khéo giải thoát.",
  "dn34:2.3.99": "Và này các hiền giả, thế nào là vị tỳ-kheo có trí khéo giải thoát?",
  "dn34:2.3.100": "Này các hiền giả, vị tỳ-kheo biết rõ: ‘Tham của ta đã được đoạn trừ, đã bị chặt tận gốc, đã làm như gốc cây thốt nốt, không còn hiện hữu, về sau không còn sinh khởi nữa’.",
  "dn34:2.3.101": "‘Sân của ta đã được đoạn trừ …",
  "dn34:2.3.102": "về sau không còn sinh khởi nữa’, vị ấy biết rõ như vậy.",
  "dn34:2.3.103": "‘Si mê đã được đoạn trừ …",
  "dn34:2.3.104": "và biết rằng về sau nó sẽ không còn sinh khởi nữa.’",
  "dn34:2.3.105": "Này các hiền giả, như vậy vị tỳ kheo là người có trí tuệ khéo giải thoát.",
  "dn34:2.3.106": "Mười pháp này khó thấu hiểu.",
  "dn34:2.3.107": "Mười pháp nào cần được làm cho sinh khởi?",
  "dn34:2.3.108": "Mười tưởng —",
  "dn34:2.3.109": "tưởng về sự bất tịnh, tưởng về cái chết, tưởng về sự nhơ nhớp trong đồ ăn, tưởng không thích thú với toàn bộ thế gian, tưởng về vô thường, tưởng về khổ trong cái vô thường, tưởng về vô ngã trong cái khổ, tưởng về từ bỏ, tưởng về phai nhạt, tưởng về chấm dứt.",
  "dn34:2.3.110": "Mười pháp này cần được làm cho sinh khởi.",
  "dn34:2.3.111": "Mười pháp nào cần được thắng tri?",
  "dn34:2.3.112": "Mười nền tảng đưa đến hao mòn —",
  "dn34:2.3.113": "Ở người có chánh kiến, tà kiến bị mòn sạch.",
  "dn34:2.3.114": "Và nhiều pháp ác, bất thiện sinh khởi do duyên tà kiến, nơi vị ấy cũng bị mòn sạch.",
  "dn34:2.3.115": "Ở người có chánh tư duy, tà tư duy …",
  "dn34:2.3.116": "ở người có chánh ngữ, tà ngữ …",
  "dn34:2.3.117": "ở người có chánh nghiệp, tà nghiệp …",
  "dn34:2.3.118": "ở người có chánh mạng, tà mạng …",
  "dn34:2.3.119": "ở người có chánh tinh tấn, tà tinh tấn …",
  "dn34:2.3.120": "ở người có chánh niệm, tà niệm …",
  "dn34:2.3.121": "ở người có chánh định, tà định …",
  "dn34:2.3.122": "Ở người có chánh trí, tà trí bị mòn sạch.",
  "dn34:2.3.123": "Ở người có chánh giải thoát, tà giải thoát bị mòn sạch.",
  "dn34:2.3.124": "Và nhiều pháp ác, bất thiện sinh khởi do duyên tà giải thoát, nơi vị ấy cũng bị mòn sạch.",
  "dn34:2.3.125": "Mười pháp này cần được thắng tri.",
  "dn34:2.3.126": "Mười pháp nào cần được chứng ngộ?",
  "dn34:2.3.127": "Mười pháp vô học —",
  "dn34:2.3.128": "chánh kiến vô học, chánh tư duy vô học, chánh ngữ vô học, chánh nghiệp vô học, chánh mạng vô học, chánh tinh tấn vô học, chánh niệm vô học, chánh định vô học, chánh trí vô học, chánh giải thoát vô học.",
  "dn34:2.3.129": "Mười pháp này cần được chứng ngộ.",
  "dn34:2.3.130": "Như vậy, một trăm pháp này là có thật, chân thật, đúng như vậy, không sai khác, được Như Lai tự mình giác ngộ hoàn toàn đúng đắn.”",
  "dn34:2.3.131": "Tôn giả Xá Lợi Phất đã nói như vậy.",
  "dn34:2.3.132": "Các vị tỳ kheo hoan hỷ, vui mừng trước lời dạy của tôn giả Xá Lợi Phất.",
  "dn34:2.3.133": "Kinh Thập Thượng đã chấm dứt, là kinh thứ mười một.",
  "dn34:2.3.134": "Phẩm Pāthika đã chấm dứt.",
  "dn34:2.4.0": "Tóm tắt phẩm ấy:",
  "dn34:2.4.1": "Pāthika và Udumbara,",
  "dn34:2.4.2": "Chuyển luân vương và Aggañña;",
  "dn34:2.4.3": "Sampasādaniya và Pāsādika,",
  "dn34:2.4.4": "Đại nhân tướng.",
  "dn34:2.4.5": "Siṅgāla, Āṭānāṭiya,",
  "dn34:2.4.6": "Saṅgīti và Dasuttara;",
  "dn34:2.4.7": "Với mười một bài kinh,",
  "dn34:2.4.8": "được gọi là phẩm Pāthika.",
  "dn34:2.4.9": "Bản Pāḷi của phẩm Pāthika đã chấm dứt.",
  "dn34:2.4.10": "Được trang nghiêm với ba phẩm, toàn bộ",
  "dn34:2.4.11": "Trường Bộ Kinh đã hoàn tất."
}
window.BILARA["dn34"]["vi"]["dn34:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
