window.BILARA = window.BILARA || {};
window.BILARA["mn02"] = window.BILARA["mn02"] || {};
window.BILARA["mn02"]["vi"] = {
  "mn2:0.1": "Trung Bộ Kinh 2",
  "mn2:0.2": "Kinh Mọi Dòng Chảy Ngầm",
  "mn2:1.1": "Tôi nghe như vầy—",
  "mn2:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, tại Kỳ Viên, trong vườn của ông Cấp Cô Độc.",
  "mn2:1.3": "Khi ấy, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn2:1.4": "“Này các Tỳ Kheo.”",
  "mn2:1.5": "Các Tỳ Kheo ấy thưa với Đức Thế Tôn: “Dạ, bạch Ngài.”",
  "mn2:1.6": "Đức Thế Tôn nói như vầy:",
  "mn2:2.1": "“Này các Tỳ Kheo, Ta sẽ giảng cho các ông cách ngăn giữ mọi dòng chảy ngầm.",
  "mn2:2.2": "Hãy nghe đây, khéo để tâm, Ta sẽ nói.”",
  "mn2:2.3": "“Dạ, bạch Ngài,” các Tỳ Kheo ấy đáp lời Đức Thế Tôn.",
  "mn2:2.4": "Đức Thế Tôn nói như vầy:",
  "mn2:3.1": "“Này các Tỳ Kheo, Ta nói rằng sự dứt sạch các dòng chảy ngầm là nhờ người biết, người thấy, không phải nhờ người không biết, không thấy.",
  "mn2:3.2": "Và này các Tỳ Kheo, Ta nói sự dứt sạch các dòng chảy ngầm là nhờ biết gì, thấy gì?",
  "mn2:3.3": "Đó là để tâm đúng cách và để tâm sai cách.",
  "mn2:3.4": "Này các Tỳ Kheo, khi để tâm sai cách, những dòng chảy ngầm chưa sinh thì sinh lên, những dòng chảy ngầm đã sinh thì lớn mạnh thêm;",
  "mn2:3.5": "còn này các Tỳ Kheo, khi để tâm đúng cách, những dòng chảy ngầm chưa sinh thì không sinh lên, những dòng chảy ngầm đã sinh thì được dứt bỏ.",
  "mn2:4.1": "Này các Tỳ Kheo, có những dòng chảy ngầm cần dứt bỏ nhờ thấy rõ, có những dòng chảy ngầm cần dứt bỏ nhờ ngăn giữ, có những dòng chảy ngầm cần dứt bỏ nhờ dùng đúng mức, có những dòng chảy ngầm cần dứt bỏ nhờ chịu đựng, có những dòng chảy ngầm cần dứt bỏ nhờ tránh xa, có những dòng chảy ngầm cần dứt bỏ nhờ xua tan, có những dòng chảy ngầm cần dứt bỏ nhờ vun bồi.",
  "mn2:5.0": "1. Những dòng chảy ngầm cần dứt bỏ nhờ thấy rõ",
  "mn2:5.1": "Và này các Tỳ Kheo, thế nào là những dòng chảy ngầm cần dứt bỏ nhờ thấy rõ?",
  "mn2:5.2": "Ở đây, này các Tỳ Kheo, kẻ thường chưa nghe học, là người phàm, không gặp bậc cao quý, không rành điều của bậc cao quý, không được rèn dạy trong điều của bậc cao quý; không gặp người tốt, không rành điều của người tốt, không được rèn dạy trong điều của người tốt—",
  "mn2:5.3": "không biết rõ điều nào nên để tâm, không biết rõ điều nào không nên để tâm.",
  "mn2:5.4": "Vì không biết rõ điều nào nên để tâm, không biết rõ điều nào không nên để tâm, nên người ấy để tâm vào những điều không nên để tâm, và không để tâm vào những điều nên để tâm.",
  "mn2:6.1": "Và này các Tỳ Kheo, những điều nào là không nên để tâm mà người ấy lại để tâm?",
  "mn2:6.2": "Này các Tỳ Kheo, khi người ấy để tâm vào những điều ấy, nếu dòng chảy ngầm của ham muốn giác quan chưa sinh thì sinh lên, nếu đã sinh thì lớn mạnh thêm;",
  "mn2:6.3": "nếu dòng chảy ngầm của muốn tiếp tục có mặt chưa sinh thì sinh lên, nếu đã sinh thì lớn mạnh thêm;",
  "mn2:6.4": "nếu dòng chảy ngầm của không sáng biết chưa sinh thì sinh lên, nếu đã sinh thì lớn mạnh thêm—",
  "mn2:6.5": "đó là những điều không nên để tâm mà người ấy lại để tâm.",
  "mn2:6.6": "Và này các Tỳ Kheo, những điều nào là nên để tâm mà người ấy lại không để tâm?",
  "mn2:6.7": "Này các Tỳ Kheo, khi người ấy để tâm vào những điều ấy, nếu dòng chảy ngầm của ham muốn giác quan chưa sinh thì không sinh lên, nếu đã sinh thì được dứt bỏ;",
  "mn2:6.8": "nếu sự rỉ chảy của lòng ham sống chưa sinh thì không sinh, nếu đã sinh thì được dứt bỏ;",
  "mn2:6.9": "nếu sự rỉ chảy của sự không biết rõ chưa sinh thì không sinh, nếu đã sinh thì được dứt bỏ—",
  "mn2:6.10": "đó là những điều cần nhớ biết rõ, mà vị ấy lại không nhớ biết rõ.",
  "mn2:7.1": "Do để tâm đến những điều không nên để tâm, và không để tâm đến những điều nên để tâm, các sự rỉ chảy chưa sinh thì sinh lên, các sự rỉ chảy đã sinh thì lớn thêm.",
  "mn2:7.2": "Vị ấy để tâm không khéo như vầy:",
  "mn2:7.3": "‘Ta có mặt trong quãng thời gian đã qua chăng? Hay ta không có mặt trong quãng thời gian đã qua? Ta đã là gì trong quãng thời gian đã qua? Ta đã như thế nào trong quãng thời gian đã qua? Sau khi là gì, ta đã thành gì trong quãng thời gian đã qua?",
  "mn2:7.4": "Ta sẽ có mặt trong quãng thời gian sắp tới chăng? Hay ta sẽ không có mặt trong quãng thời gian sắp tới? Ta sẽ là gì trong quãng thời gian sắp tới? Ta sẽ như thế nào trong quãng thời gian sắp tới? Sau khi là gì, ta sẽ thành gì trong quãng thời gian sắp tới?’",
  "mn2:7.5": "Hoặc ngay trong quãng thời gian hiện nay, vị ấy ngờ vực về mình rằng:",
  "mn2:7.6": "‘Ta có thật là có mặt không? Hay ta không có mặt? Ta là gì? Ta là như thế nào? Chúng sinh này từ đâu đến? Rồi sẽ đi về đâu?’",
  "mn2:8.1": "Khi vị ấy để tâm không khéo như vậy, một trong sáu lối thấy sẽ sinh lên.",
  "mn2:8.2": "Hoặc nơi vị ấy sinh lên lối thấy cho là thật chắc rằng: ‘Ta có cái ta’;",
  "mn2:8.3": "hoặc nơi vị ấy sinh lên lối thấy cho là thật chắc rằng: ‘Ta không có cái ta’;",
  "mn2:8.4": "hoặc nơi vị ấy sinh lên lối thấy cho là thật chắc rằng: ‘Chính nhờ cái ta mà ta biết cái ta’;",
  "mn2:8.5": "hoặc nơi vị ấy sinh lên lối thấy cho là thật chắc rằng: ‘Chính nhờ cái ta mà ta biết cái không phải ta’;",
  "mn2:8.6": "hoặc nơi vị ấy sinh lên lối thấy cho là thật chắc rằng: ‘Chính nhờ cái không phải ta mà ta biết cái ta’;",
  "mn2:8.7": "hoặc vị ấy có lối thấy như vầy:",
  "mn2:8.8": "‘Cái ta này của tôi là kẻ nói, kẻ cảm nhận, kẻ ở chỗ này chỗ kia gặt lấy kết quả của những việc làm tốt xấu. Cái ta này của tôi là thường còn, bền chắc, mãi mãi, không mang tính đổi khác, và sẽ đứng y như vậy suốt đời đời.’",
  "mn2:8.9": "Này các Tỳ Kheo, đó được gọi là mớ lối thấy, bụi rậm của lối thấy, nơi hoang vắng của lối thấy, sự vặn vẹo của lối thấy, sự vùng vẫy của lối thấy, sự trói buộc bởi lối thấy.",
  "mn2:8.10": "Này các Tỳ Kheo, kẻ phàm thường ít nghe, bị trói buộc bởi lối thấy, không thoát khỏi sinh ra, già đi, chết, buồn thương, than khóc, khổ đau, lòng buồn bã và bức bối;",
  "mn2:8.11": "ta nói rằng người ấy không thoát khỏi sự khổ đau.",
  "mn2:9.1": "Còn này các Tỳ Kheo, người học trò của bậc cao quý,",
  "mn2:9.2": "đã gặp các bậc cao quý, rành điều của bậc cao quý, được khéo dạy trong điều của bậc cao quý; đã gặp người tốt, rành điều của người tốt, được khéo dạy trong điều của người tốt—",
  "mn2:9.3": "biết rõ những điều nên để tâm và biết rõ những điều không nên để tâm.",
  "mn2:9.4": "Vị ấy, khi biết rõ những điều nên để tâm và những điều không nên để tâm, thì không để tâm đến những điều không nên để tâm, và để tâm đến những điều nên để tâm.",
  "mn2:10.1": "Và này các Tỳ Kheo, những điều nào là những điều không nên để tâm mà vị ấy không để tâm đến?",
  "mn2:10.2": "Này các Tỳ Kheo, những điều mà khi để tâm đến, sự rỉ chảy của lòng ham muốn chưa sinh thì sinh lên, hoặc đã sinh thì lớn thêm;",
  "mn2:10.3": "sự rỉ chảy của lòng ham sống chưa sinh thì sinh lên, hoặc đã sinh thì lớn thêm;",
  "mn2:10.4": "sự rỉ chảy của sự không biết rõ chưa sinh thì sinh lên, hoặc đã sinh thì lớn thêm—",
  "mn2:10.5": "đó là những điều không nên để tâm, mà vị ấy không để tâm đến.",
  "mn2:10.6": "Và này các Tỳ Kheo, những điều nào là những điều nên để tâm mà vị ấy để tâm đến?",
  "mn2:10.7": "Này các Tỳ Kheo, khi để tâm đúng vào những điều cần để tâm, thì ham muốn giác quan chưa sinh sẽ không sinh, và nếu đã sinh thì sẽ dứt.",
  "mn2:10.8": "sự muốn tiếp tục hiện hữu chưa sinh sẽ không sinh, và nếu đã sinh thì sẽ dứt.",
  "mn2:10.9": "sự mù mờ chưa sinh sẽ không sinh, và nếu đã sinh thì sẽ dứt—",
  "mn2:10.10": "đó là những điều cần để tâm đúng.",
  "mn2:10.11": "Do không để tâm đến những điều không nên để tâm, và để tâm đến những điều nên để tâm, nên các thứ rỉ chảy chưa sinh sẽ không sinh, và các thứ rỉ chảy đã sinh sẽ dứt.",
  "mn2:11.1": "Vị ấy để tâm đúng như thật rằng: ‘Đây là sự khổ đau’, để tâm đúng như thật rằng: ‘Đây là nguồn gốc của sự khổ đau’, để tâm đúng như thật rằng: ‘Đây là sự chấm dứt khổ đau’, để tâm đúng như thật rằng: ‘Đây là con đường đưa đến chỗ chấm dứt khổ đau’.",
  "mn2:11.2": "Khi vị ấy để tâm đúng như vậy, thì ba trói buộc được dứt bỏ—",
  "mn2:11.3": "cái thấy chấp thân này là mình, sự ngờ vực, và sự nắm giữ cứng nhắc vào giới cấm và nghi thức.",
  "mn2:11.4": "Này các Tỳ Kheo, những thứ này được gọi là các thứ rỉ chảy cần dứt bỏ nhờ thấy rõ.",
  "mn2:12.0": "2. Các thứ rỉ chảy cần dứt bỏ nhờ giữ gìn",
  "mn2:12.1": "Và này các Tỳ Kheo, thế nào là các thứ rỉ chảy cần dứt bỏ nhờ giữ gìn?",
  "mn2:12.2": "Ở đây, này các Tỳ Kheo, một Tỳ Kheo suy xét kỹ rồi sống giữ gìn cửa mắt.",
  "mn2:12.3": "Này các Tỳ Kheo, nếu sống không giữ gìn cửa mắt thì những thứ rỉ chảy, bực bội và nung đốt có thể sinh khởi; còn khi sống giữ gìn cửa mắt thì những thứ rỉ chảy, bực bội và nung đốt ấy không có.",
  "mn2:12.4": "Suy xét kỹ rồi sống giữ gìn cửa tai …",
  "mn2:12.5": "sống giữ gìn cửa mũi …",
  "mn2:12.6": "sống giữ gìn cửa lưỡi …",
  "mn2:12.7": "sống giữ gìn cửa thân …",
  "mn2:12.8": "sống giữ gìn cửa ý.",
  "mn2:12.9": "Này các Tỳ Kheo, nếu sống không giữ gìn cửa ý thì những thứ rỉ chảy, bực bội và nung đốt có thể sinh khởi; còn khi sống giữ gìn cửa ý thì những thứ rỉ chảy, bực bội và nung đốt ấy không có.",
  "mn2:12.10": "Này các Tỳ Kheo, nếu sống không giữ gìn thì những thứ rỉ chảy, bực bội và nung đốt có thể sinh khởi; còn khi sống giữ gìn thì những thứ rỉ chảy, bực bội và nung đốt ấy không có.",
  "mn2:12.11": "Này các Tỳ Kheo, những thứ này được gọi là các thứ rỉ chảy cần dứt bỏ nhờ giữ gìn.",
  "mn2:13.0": "3. Các thứ rỉ chảy cần dứt bỏ nhờ dùng đúng cách",
  "mn2:13.1": "Và này các Tỳ Kheo, thế nào là các thứ rỉ chảy cần dứt bỏ nhờ dùng đúng cách?",
  "mn2:13.2": "Ở đây, này các Tỳ Kheo, một Tỳ Kheo suy xét kỹ rồi dùng y áo:",
  "mn2:13.3": "‘chỉ để ngăn lạnh, ngăn nóng, ngăn sự đụng chạm của ruồi, muỗi, gió, nắng và các loài bò sát, và chỉ để che phần kín đáng hổ thẹn’.",
  "mn2:14.1": "Suy xét kỹ rồi dùng đồ ăn khất thực:",
  "mn2:14.2": "‘không phải để vui đùa, không phải để say sưa, không phải để làm dáng, không phải để làm đẹp, mà chỉ để thân này đứng vững và sống được, để chặn sự tổn hại, để nâng đỡ đời sống trong sạch; nghĩ rằng: nhờ vậy ta sẽ làm lắng dịu cảm giác khó chịu cũ và không làm sinh ra cảm giác khó chịu mới; như thế ta sẽ sống được, không lỗi lầm, và ở yên ổn’.",
  "mn2:15.1": "Suy xét kỹ rồi dùng chỗ ở:",
  "mn2:15.2": "‘chỉ để ngăn lạnh, ngăn nóng, ngăn sự đụng chạm của ruồi, muỗi, gió, nắng và các loài bò sát, và chỉ để tránh hiểm nguy do thời tiết, có chỗ ở vắng để ngồi yên’.",
  "mn2:16.1": "Suy xét kỹ rồi dùng thuốc men và vật dụng cần cho người bệnh:",
  "mn2:16.2": "chỉ để ngăn bớt những cảm giác đau đớn đã sinh ra, và để sống không bị hại.",
  "mn2:17.1": "Này các Tỳ Kheo, những dòng rỉ chảy, sự bứt rứt, sự nung nấu nào sẽ sinh ra nơi người không dùng đúng cách, thì nơi người dùng đúng cách, những dòng rỉ chảy, sự bứt rứt, sự nung nấu ấy không có.",
  "mn2:17.2": "Này các Tỳ Kheo, đó gọi là những dòng rỉ chảy cần dứt bằng cách dùng đúng cách.",
  "mn2:18.0": "4. Những dòng rỉ chảy cần dứt bằng cách chịu đựng",
  "mn2:18.1": "Và này các Tỳ Kheo, thế nào là những dòng rỉ chảy cần dứt bằng cách chịu đựng?",
  "mn2:18.2": "Ở đây, này các Tỳ Kheo, một Tỳ Kheo suy xét kỹ càng, khéo thấy gốc ngọn, rồi chịu đựng được lạnh, nóng, đói, khát; chịu đựng được sự chạm đụng của ruồi, muỗi, gió, nắng, loài bò sát; chịu đựng được những lời nói xấu ác, khó nghe, khó chịu; chịu đựng được những cảm giác nơi thân đã sinh ra, đau đớn, dữ dội, nhói buốt, gay gắt, khó chịu, không vừa ý, có thể cướp mạng.",
  "mn2:18.3": "Này các Tỳ Kheo, những dòng rỉ chảy, sự bứt rứt, sự nung nấu nào sẽ sinh ra nơi người không chịu đựng, thì nơi người chịu đựng, những dòng rỉ chảy, sự bứt rứt, sự nung nấu ấy không có.",
  "mn2:18.4": "Này các Tỳ Kheo, đó gọi là những dòng rỉ chảy cần dứt bằng cách chịu đựng.",
  "mn2:19.0": "5. Những dòng rỉ chảy cần dứt bằng cách tránh xa",
  "mn2:19.1": "Và này các Tỳ Kheo, thế nào là những dòng rỉ chảy cần dứt bằng cách tránh xa?",
  "mn2:19.2": "Ở đây, này các Tỳ Kheo, một Tỳ Kheo suy xét kỹ càng, khéo thấy gốc ngọn, rồi tránh xa con voi dữ, tránh xa con ngựa dữ, tránh xa con bò đực dữ, tránh xa con chó dữ, tránh xa rắn, gốc cây, chỗ đầy gai góc, hố sâu, vực thẳm, cống nước bẩn, hầm lầy.",
  "mn2:19.3": "Nếu ngồi ở chỗ không nên ngồi, đi lại ở nơi không nên lui tới, gần gũi bạn xấu, thì các bạn sống đời sạch tốt có hiểu biết sẽ xem người ấy là đang ở trong chỗ xấu. Vì vậy, vị ấy suy xét kỹ càng, khéo thấy gốc ngọn, rồi tránh chỗ ngồi không nên ngồi ấy, tránh nơi không nên lui tới ấy, tránh những bạn xấu ấy.",
  "mn2:19.4": "Này các Tỳ Kheo, những dòng rỉ chảy, sự bứt rứt, sự nung nấu nào sẽ sinh ra nơi người không tránh xa, thì nơi người tránh xa, những dòng rỉ chảy, sự bứt rứt, sự nung nấu ấy không có.",
  "mn2:19.5": "Này các Tỳ Kheo, đó gọi là những dòng rỉ chảy cần dứt bằng cách tránh xa.",
  "mn2:20.0": "6. Những dòng rỉ chảy cần dứt bằng cách xua tan",
  "mn2:20.1": "Và này các Tỳ Kheo, thế nào là những dòng rỉ chảy cần dứt bằng cách xua tan?",
  "mn2:20.2": "Ở đây, này các Tỳ Kheo, một Tỳ Kheo suy xét kỹ càng, khéo thấy gốc ngọn, không chấp nhận ý nghĩ ham muốn đã sinh ra, từ bỏ nó, xua tan nó, dẹp sạch nó, làm cho nó không còn nữa; không chấp nhận ý nghĩ giận dữ đã sinh ra, từ bỏ nó, xua tan nó, dẹp sạch nó, làm cho nó không còn nữa; không chấp nhận ý nghĩ làm hại đã sinh ra, từ bỏ nó, xua tan nó, dẹp sạch nó, làm cho nó không còn nữa; những điều xấu ác, không lành nào vừa sinh lên, vị ấy cũng không chấp nhận, từ bỏ, xua tan, dẹp sạch, làm cho chúng không còn nữa.",
  "mn2:20.3": "Này các Tỳ Kheo, những dòng rỉ chảy, sự bứt rứt, sự nung nấu nào sẽ sinh ra nơi người không xua tan, thì nơi người xua tan, những dòng rỉ chảy, sự bứt rứt, sự nung nấu ấy không có.",
  "mn2:20.4": "Này các Tỳ Kheo, đó gọi là những dòng rỉ chảy cần dứt bằng cách xua tan.",
  "mn2:21.0": "7. Những dòng rỉ chảy cần dứt bằng cách vun bồi",
  "mn2:21.1": "Và này các Tỳ Kheo, thế nào là những dòng rỉ chảy cần dứt bằng cách vun bồi?",
  "mn2:21.2": "Ở đây, này các Tỳ Kheo, một Tỳ Kheo suy xét kỹ càng, khéo thấy gốc ngọn, rồi vun bồi yếu tố tỉnh biết rõ đưa đến giác ngộ, nương nơi lìa xa, nương nơi nhạt dần ham muốn, nương nơi chấm dứt, hướng đến buông bỏ;",
  "mn2:21.3": "suy xét kỹ càng, khéo thấy gốc ngọn, rồi vun bồi yếu tố xem xét kỹ điều đang xảy ra đưa đến giác ngộ;",
  "mn2:21.4": "vun bồi yếu tố siêng năng đưa đến giác ngộ;",
  "mn2:21.5": "vun bồi yếu tố niềm vui đưa đến giác ngộ;",
  "mn2:21.6": "vun bồi yếu tố lắng dịu đưa đến giác ngộ;",
  "mn2:21.7": "vun bồi yếu tố tâm yên vững đưa đến giác ngộ;",
  "mn2:21.8": "vun bồi yếu tố giữ tâm bình thản đưa đến giác ngộ, nương nơi lìa xa, nương nơi nhạt dần ham muốn, nương nơi chấm dứt, hướng đến buông bỏ.",
  "mn2:21.9": "Này các Tỳ Kheo, những dòng rỉ chảy, sự bứt rứt, sự nung nấu nào sẽ sinh ra nơi người không vun bồi, thì nơi người vun bồi, những dòng rỉ chảy, sự bứt rứt, sự nung nấu ấy không có.",
  "mn2:21.10": "Này các Tỳ Kheo, đó gọi là những dòng rỉ chảy cần dứt bằng cách vun bồi.",
  "mn2:22.1": "Này các Tỳ Kheo, khi nào vị Tỳ Kheo đã dứt bỏ được những dòng rỉ chảy cần dứt bỏ bằng thấy rõ, đã dứt bỏ được những dòng rỉ chảy cần dứt bỏ bằng giữ gìn, đã dứt bỏ được những dòng rỉ chảy cần dứt bỏ bằng dùng đúng cách, đã dứt bỏ được những dòng rỉ chảy cần dứt bỏ bằng chịu đựng, đã dứt bỏ được những dòng rỉ chảy cần dứt bỏ bằng tránh xa, đã dứt bỏ được những dòng rỉ chảy cần dứt bỏ bằng xua tan, đã dứt bỏ được những dòng rỉ chảy cần dứt bỏ bằng vun bồi;",
  "mn2:22.2": "thì này các Tỳ Kheo, vị ấy được gọi là vị Tỳ Kheo sống với sự giữ gìn trọn vẹn đối với mọi dòng rỉ chảy, đã chặt đứt lòng ham muốn, đã tháo bỏ mọi trói buộc, do hiểu thấu đáo thói hơn thua nên đã làm cho sự khổ đau đi đến chỗ cùng tận.",
  "mn2:22.3": "Đức Thế Tôn nói như vậy.",
  "mn2:22.4": "Các Tỳ Kheo ấy vui mừng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn2:22.5": "Bài kinh Mọi Dòng Rỉ Chảy, phần thứ hai, đến đây là xong."
}
window.BILARA["mn02"]["vi"]["mn02:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";