window.BILARA = window.BILARA || {};
window.BILARA["mn03"] = window.BILARA["mn03"] || {};
window.BILARA["mn03"]["vi"] = {
  "mn3:0.1": "Trung Bộ Kinh 3",
  "mn3:0.2": "Kinh Người Thừa Hưởng Lời Dạy",
  "mn3:1.1": "Tôi nghe như vầy—",
  "mn3:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, trong rừng Kỳ Đà, tại vườn của ông Cấp Cô Độc.",
  "mn3:1.3": "Tại đó, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn3:1.4": "“Này các Tỳ Kheo.”",
  "mn3:1.5": "Các Tỳ Kheo ấy thưa với Đức Thế Tôn: “Dạ, bạch Ngài.”",
  "mn3:1.6": "Đức Thế Tôn nói điều này:",
  "mn3:2.1": "“Này các Tỳ Kheo, hãy là người thừa hưởng lời dạy của Ta, đừng là người thừa hưởng đồ nuôi thân.",
  "mn3:2.2": "Ta có lòng thương các ông:",
  "mn3:2.3": "‘Làm sao để các học trò của Ta là người thừa hưởng lời dạy, không phải người thừa hưởng đồ nuôi thân.’",
  "mn3:2.4": "Này các Tỳ Kheo, nếu các ông là người thừa hưởng đồ nuôi thân của Ta, không phải người thừa hưởng lời dạy, thì các ông cũng sẽ bị chê vì điều đó:",
  "mn3:2.5": "‘Các học trò của bậc thầy sống như người thừa hưởng đồ nuôi thân, không phải người thừa hưởng lời dạy.’",
  "mn3:2.6": "Và Ta cũng sẽ bị chê vì điều đó:",
  "mn3:2.7": "‘Các học trò của bậc thầy sống như người thừa hưởng đồ nuôi thân, không phải người thừa hưởng lời dạy.’",
  "mn3:2.8": "Nhưng này các Tỳ Kheo, nếu các ông là người thừa hưởng lời dạy của Ta, không phải người thừa hưởng đồ nuôi thân, thì các ông sẽ không bị chê vì điều đó:",
  "mn3:2.9": "‘Các học trò của bậc thầy sống như người thừa hưởng lời dạy, không phải người thừa hưởng đồ nuôi thân.’",
  "mn3:2.10": "Và Ta cũng sẽ không bị chê vì điều đó:",
  "mn3:2.11": "‘Các học trò của bậc thầy sống như người thừa hưởng lời dạy, không phải người thừa hưởng đồ nuôi thân.’",
  "mn3:2.12": "Vậy nên, này các Tỳ Kheo, hãy là người thừa hưởng lời dạy của Ta, đừng là người thừa hưởng đồ nuôi thân.",
  "mn3:2.13": "Ta có lòng thương các ông:",
  "mn3:2.14": "‘Làm sao để các học trò của Ta là người thừa hưởng lời dạy, không phải người thừa hưởng đồ nuôi thân.’",
  "mn3:3.1": "Này các Tỳ Kheo, ở đây, giả sử Ta đã ăn xong, đã được mời đủ, đã no đầy, đã dùng xong, đã thấy vừa ý, đã đủ theo nhu cầu;",
  "mn3:3.2": "và còn có đồ ăn khất thực dư ra, thuộc phần phải bỏ đi.",
  "mn3:3.3": "Rồi có hai Tỳ Kheo đến, đang bị đói và mệt lả chi phối.",
  "mn3:3.4": "Khi ấy Ta sẽ nói như vầy:",
  "mn3:3.5": "‘Này các Tỳ Kheo, Ta đã ăn xong, đã được mời đủ, đã no đầy, đã dùng xong, đã thấy vừa ý, đã đủ theo nhu cầu;",
  "mn3:3.6": "và ở đây còn có phần đồ ăn khất thực này dư ra, thuộc phần phải bỏ đi.",
  "mn3:3.7": "Nếu các ông muốn thì hãy ăn. Còn nếu các ông không ăn, thì bây giờ Ta sẽ đổ nó ở chỗ ít cỏ xanh, hoặc dìm nó xuống nước không có sinh vật.’",
  "mn3:3.8": "Khi ấy, một Tỳ Kheo nghĩ như vầy:",
  "mn3:3.9": "‘Đức Thế Tôn đã ăn xong, đã từ chối thêm, đã no đủ, đã dùng xong, đã thấy vừa ý;",
  "mn3:3.10": "và phần đồ ăn khất thực này của Đức Thế Tôn là phần dư, là thứ sẽ phải bỏ đi.",
  "mn3:3.11": "Nếu chúng ta không ăn, thì bây giờ Đức Thế Tôn sẽ đổ nó ở chỗ ít cỏ xanh, hoặc đổ xuống nước không có sinh vật.",
  "mn3:3.12": "Nhưng Đức Thế Tôn đã nói rằng:",
  "mn3:3.13": "“Này các Tỳ Kheo, hãy là người thừa hưởng điều lành, đừng là người thừa hưởng đồ ăn vật chất.”",
  "mn3:3.14": "Mà trong các thứ vật chất, đồ ăn khất thực này là một thứ như vậy.",
  "mn3:3.15": "Hay là ta không ăn phần đồ ăn khất thực này, rồi cứ mang cái đói và sự yếu sức này mà sống qua ngày đêm này?’",
  "mn3:3.16": "Vị ấy không ăn phần đồ ăn khất thực ấy, và cứ mang cái đói cùng sự yếu sức ấy mà sống qua ngày đêm đó.",
  "mn3:3.17": "Rồi vị Tỳ Kheo thứ hai nghĩ rằng:",
  "mn3:3.18": "‘Đức Thế Tôn đã ăn xong, đã từ chối thêm, đã no đủ, đã dùng xong, đã thấy vừa ý;",
  "mn3:3.19": "và phần đồ ăn khất thực này của Đức Thế Tôn là phần dư, là thứ sẽ phải bỏ đi.",
  "mn3:3.20": "Nếu chúng ta không ăn, thì bây giờ Đức Thế Tôn sẽ đổ nó ở chỗ ít cỏ xanh, hoặc đổ xuống nước không có sinh vật.",
  "mn3:3.21": "Hay là ta ăn phần đồ ăn khất thực này, xua đi cái đói và sự yếu sức, rồi sống qua ngày đêm này?’",
  "mn3:3.22": "Vị ấy ăn phần đồ ăn khất thực ấy, xua đi cái đói và sự yếu sức, rồi sống qua ngày đêm đó.",
  "mn3:3.23": "Này các Tỳ Kheo, dù vị Tỳ Kheo ấy ăn phần đồ ăn khất thực đó, xua đi cái đói và sự yếu sức, rồi sống qua ngày đêm đó, nhưng vị Tỳ Kheo trước vẫn đáng quý hơn và đáng khen hơn đối với Ta.",
  "mn3:3.24": "Vì sao vậy?",
  "mn3:3.25": "Vì điều ấy sẽ đưa vị Tỳ Kheo đó về lâu về dài đến chỗ ít muốn, biết đủ, gọt mòn bớt, dễ nuôi, và gắng sức.",
  "mn3:3.26": "Vậy nên, này các Tỳ Kheo, hãy là người thừa hưởng điều lành, đừng là người thừa hưởng đồ ăn vật chất.",
  "mn3:3.27": "Ta thương các ông:",
  "mn3:3.28": "‘Làm sao để các học trò của Ta là người thừa hưởng điều lành, không phải là người thừa hưởng đồ ăn vật chất.’”",
  "mn3:4.1": "Đức Thế Tôn nói như vậy.",
  "mn3:4.2": "Nói xong, Đấng Khéo Đi đứng dậy khỏi chỗ ngồi và đi vào chỗ ở.",
  "mn3:4.3": "Lúc ấy, ngài Xá Lợi Phất, không bao lâu sau khi Đức Thế Tôn rời đi, gọi các Tỳ Kheo:",
  "mn3:4.4": "“Này các hiền hữu Tỳ Kheo.”",
  "mn3:4.5": "Các Tỳ Kheo ấy đáp lại ngài Xá Lợi Phất:",
  "mn3:4.6": "“Thưa hiền hữu.” Ngài Xá Lợi Phất nói điều này:",
  "mn3:5.1": "“Này các hiền hữu, đến mức nào thì khi bậc thầy sống riêng vắng lặng, các học trò không học theo sự sống riêng vắng lặng ấy, và đến mức nào thì khi bậc thầy sống riêng vắng lặng, các học trò học theo sự sống riêng vắng lặng ấy?”",
  "mn3:5.2": "“Này hiền hữu, chúng tôi từ xa đến gần ngài Xá Lợi Phất để hiểu nghĩa lời nói này.",
  "mn3:5.3": "Lành thay, mong chính ngài Xá Lợi Phất nói rõ nghĩa của lời nói này;",
  "mn3:5.4": "nghe ngài Xá Lợi Phất xong, các Tỳ Kheo sẽ ghi nhớ.”",
  "mn3:5.5": "“Vậy, này các huynh, hãy nghe đây, khéo để tâm, tôi sẽ nói.”",
  "mn3:5.6": "“Vâng, này huynh.” Các Tỳ Kheo ấy đã đáp lời ngài Xá Lợi Phất như vậy.",
  "mn3:5.7": "Ngài Xá Lợi Phất nói điều này:",
  "mn3:6.1": "“Này các huynh, đến mức nào thì, khi bậc Thầy sống riêng vắng lặng, các học trò lại không học theo sự sống riêng vắng lặng?",
  "mn3:6.2": "Này các huynh, ở đây, khi bậc Thầy sống riêng vắng lặng, các học trò không học theo sự sống riêng vắng lặng,",
  "mn3:6.3": "và những điều nào bậc Thầy nói là cần buông bỏ, thì họ lại không buông bỏ những điều ấy,",
  "mn3:6.4": "họ sống dễ duôi, lơi lỏng, đi đầu trong việc sa sút, bỏ rơi gánh nặng của đời sống riêng vắng lặng.",
  "mn3:6.5": "Này các huynh, ở đây các Tỳ Kheo lớn tuổi đáng bị chê ở ba mặt.",
  "mn3:6.6": "‘Khi bậc Thầy sống riêng vắng lặng, các học trò không học theo sự sống riêng vắng lặng’—",
  "mn3:6.7": "do mặt thứ nhất này mà các Tỳ Kheo lớn tuổi đáng bị chê.",
  "mn3:6.8": "‘Những điều nào bậc Thầy nói là cần buông bỏ, thì họ lại không buông bỏ những điều ấy’—",
  "mn3:6.9": "do mặt thứ hai này mà các Tỳ Kheo lớn tuổi đáng bị chê.",
  "mn3:6.10": "‘Họ sống dễ duôi, lơi lỏng, đi đầu trong việc sa sút, bỏ rơi gánh nặng của đời sống riêng vắng lặng’—",
  "mn3:6.11": "do mặt thứ ba này mà các Tỳ Kheo lớn tuổi đáng bị chê.",
  "mn3:6.12": "Này các huynh, các Tỳ Kheo lớn tuổi đáng bị chê ở ba mặt này.",
  "mn3:6.13": "Này các huynh, các Tỳ Kheo tuổi vừa …",
  "mn3:6.14": "các Tỳ Kheo mới đáng bị chê ở ba mặt.",
  "mn3:6.15": "‘Khi bậc Thầy sống riêng vắng lặng, các học trò không học theo sự sống riêng vắng lặng’—",
  "mn3:6.16": "do mặt thứ nhất này mà các Tỳ Kheo mới đáng bị chê.",
  "mn3:6.17": "‘Những điều nào bậc Thầy nói là cần buông bỏ, thì họ lại không buông bỏ những điều ấy’—",
  "mn3:6.18": "do mặt thứ hai này mà các Tỳ Kheo mới đáng bị chê.",
  "mn3:6.19": "‘Họ sống dễ duôi, lơi lỏng, đi đầu trong việc sa sút, bỏ rơi gánh nặng của đời sống riêng vắng lặng’—",
  "mn3:6.20": "do mặt thứ ba này mà các Tỳ Kheo mới đáng bị chê.",
  "mn3:6.21": "Này các huynh, các Tỳ Kheo mới đáng bị chê ở ba mặt này.",
  "mn3:6.22": "Này các huynh, đến mức ấy thì, khi bậc Thầy sống riêng vắng lặng, các học trò không học theo sự sống riêng vắng lặng.",
  "mn3:7.1": "Còn này các huynh, đến mức nào thì, khi bậc Thầy sống riêng vắng lặng, các học trò học theo sự sống riêng vắng lặng?",
  "mn3:7.2": "Này các huynh, ở đây, khi bậc Thầy sống riêng vắng lặng, các học trò học theo sự sống riêng vắng lặng—",
  "mn3:7.3": "những điều nào bậc Thầy nói là cần buông bỏ, thì họ buông bỏ những điều ấy;",
  "mn3:7.4": "họ không sống dễ duôi, không lơi lỏng, không bỏ rơi gánh nặng vì sa sút, mà đi đầu trong đời sống riêng vắng lặng.",
  "mn3:7.5": "Này các huynh, ở đây các Tỳ Kheo lớn tuổi đáng được khen ở ba mặt.",
  "mn3:7.6": "‘Khi Đức Thế Tôn sống tách riêng, các đệ tử cũng học theo nếp sống tách riêng’—",
  "mn3:7.7": "do điểm thứ nhất này mà các Tỳ Kheo lớn tuổi được khen ngợi.",
  "mn3:7.8": "‘Những điều nào Đức Thế Tôn dạy phải bỏ đi, thì họ cũng bỏ những điều ấy’—",
  "mn3:7.9": "do điểm thứ hai này mà các Tỳ Kheo lớn tuổi được khen ngợi.",
  "mn3:7.10": "‘Họ không sống buông lung, không chểnh mảng, không bỏ dở giữa chừng, và đi đầu trong nếp sống tách riêng’—",
  "mn3:7.11": "do điểm thứ ba này mà các Tỳ Kheo lớn tuổi được khen ngợi.",
  "mn3:7.12": "Này các hiền giả, các Tỳ Kheo lớn tuổi được khen ngợi nhờ ba điểm này.",
  "mn3:7.13": "Này các hiền giả, còn các Tỳ Kheo tuổi vừa …",
  "mn3:7.14": "các Tỳ Kheo mới cũng được khen ngợi nhờ ba điểm.",
  "mn3:7.15": "‘Khi Đức Thế Tôn sống tách riêng, các đệ tử cũng học theo nếp sống tách riêng’—",
  "mn3:7.16": "do điểm thứ nhất này mà các Tỳ Kheo mới được khen ngợi.",
  "mn3:7.17": "‘Những điều nào Đức Thế Tôn dạy phải bỏ đi, thì họ cũng bỏ những điều ấy’—",
  "mn3:7.18": "do điểm thứ hai này mà các Tỳ Kheo mới được khen ngợi.",
  "mn3:7.19": "‘Họ không sống buông lung, không chểnh mảng, không bỏ dở giữa chừng, và đi đầu trong nếp sống tách riêng’—",
  "mn3:7.20": "do điểm thứ ba này mà các Tỳ Kheo mới được khen ngợi.",
  "mn3:7.21": "Này các hiền giả, các Tỳ Kheo mới được khen ngợi nhờ ba điểm này.",
  "mn3:7.22": "Đến mức này, này các hiền giả, khi Đức Thế Tôn sống tách riêng, các đệ tử cũng học theo nếp sống tách riêng.",
  "mn3:8.1": "Này các hiền giả, tham muốn là xấu, giận dữ cũng là xấu.",
  "mn3:8.2": "Để dứt bỏ tham muốn và dứt bỏ giận dữ, có một con đường ở giữa, làm cho thấy rõ, làm cho hiểu rõ, đưa đến lắng yên, đến biết thẳng, đến tỉnh thức trọn vẹn, đến tắt hẳn.",
  "mn3:8.3": "Này các hiền giả, con đường ở giữa nào làm cho thấy rõ, làm cho hiểu rõ, đưa đến lắng yên, đến biết thẳng, đến tỉnh thức trọn vẹn, đến tắt hẳn?",
  "mn3:8.4": "Chính là con đường thánh gồm tám phần này, đó là—",
  "mn3:8.5": "thấy đúng, nghĩ đúng, nói đúng, làm đúng, sống đúng, gắng sức đúng, nhớ biết rõ đúng, tâm yên vững đúng.",
  "mn3:8.6": "Này các hiền giả, đó là con đường ở giữa làm cho thấy rõ, làm cho hiểu rõ, đưa đến lắng yên, đến biết thẳng, đến tỉnh thức trọn vẹn, đến tắt hẳn.",
  "mn3:9-15.1": "Này các hiền giả, nóng giận là xấu, ôm hờn cũng là xấu …",
  "mn3:9-15.2": "coi thường người khác là xấu, chống đối cũng là xấu,",
  "mn3:9-15.3": "ganh tị là xấu, keo kiệt cũng là xấu,",
  "mn3:9-15.4": "dối trá là xấu, lừa gạt cũng là xấu,",
  "mn3:9-15.5": "cứng đầu là xấu, hiếu thắng cũng là xấu,",
  "mn3:9-15.6": "tự cao là xấu, quá tự cao cũng là xấu,",
  "mn3:9-15.7": "say sưa tự đắc là xấu, buông lung cũng là xấu.",
  "mn3:9-15.8": "Và để dứt bỏ say đắm, để dứt bỏ buông lung, có con đường ở giữa, làm cho thấy rõ, làm cho hiểu rõ, đưa đến lắng yên, đến biết thẳng, đến tỉnh sáng trọn vẹn, đến tắt hẳn.",
  "mn3:9-15.9": "Này các hiền giả, con đường ở giữa ấy là gì, con đường làm cho thấy rõ, làm cho hiểu rõ, đưa đến lắng yên, đến biết thẳng, đến tỉnh sáng trọn vẹn, đến tắt hẳn?",
  "mn3:9-15.10": "Chính là con đường thánh gồm tám phần này, đó là—",
  "mn3:9-15.11": "thấy đúng, nghĩ đúng, nói đúng, làm đúng, sống đúng, siêng năng đúng, nhớ biết rõ đúng, tâm yên vững đúng.",
  "mn3:9-15.12": "Này các hiền giả, đó là con đường ở giữa, làm cho thấy rõ, làm cho hiểu rõ, đưa đến lắng yên, đến biết thẳng, đến tỉnh sáng trọn vẹn, đến tắt hẳn.”",
  "mn3:9-15.13": "Đại đức Xá Lợi Phất đã nói như vậy.",
  "mn3:9-15.14": "Các Tỳ Kheo vui mừng, hoan hỷ với lời Đại đức Xá Lợi Phất đã nói.",
  "mn3:9-15.15": "Kinh Người thừa hưởng lời dạy, bài thứ ba, đến đây là xong."
}
window.BILARA["mn03"]["vi"]["mn03:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";