window.BILARA = window.BILARA || {};
window.BILARA["mn07"] = window.BILARA["mn07"] || {};
window.BILARA["mn07"]["vi"] = {
  "mn7:0.1": "Trung Bộ Kinh 7",
  "mn7:0.2": "Kinh Tấm Vải",
  "mn7:1.1": "Tôi nghe như vầy—",
  "mn7:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, trong rừng Kỳ Đà, tại vườn của ông Cấp Cô Độc.",
  "mn7:1.3": "Tại đó, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn7:1.4": "“Này các Tỳ Kheo.”",
  "mn7:1.5": "Các Tỳ Kheo ấy thưa với Đức Thế Tôn: “Dạ, bạch Ngài.”",
  "mn7:1.6": "Đức Thế Tôn nói như vầy:",
  "mn7:2.1": "“Này các Tỳ Kheo, ví như một tấm vải dơ, bám đầy vết bẩn;",
  "mn7:2.2": "nếu người thợ nhuộm đem nó nhuộm màu nào đi nữa—màu xanh, màu vàng, màu đỏ, hay màu đỏ sẫm—thì màu của nó cũng xấu, không trong sạch.",
  "mn7:2.3": "Vì sao vậy?",
  "mn7:2.4": "Vì tấm vải không sạch, này các Tỳ Kheo.",
  "mn7:2.5": "Cũng vậy, này các Tỳ Kheo, khi lòng bị nhơ bẩn, thì có thể chờ đợi một nơi đến xấu.",
  "mn7:2.6": "Này các Tỳ Kheo, ví như một tấm vải sạch, sáng trong;",
  "mn7:2.7": "nếu người thợ nhuộm đem nó nhuộm màu nào đi nữa—màu xanh, màu vàng, màu đỏ, hay màu đỏ sẫm—thì màu của nó sẽ đẹp, trong sạch.",
  "mn7:2.8": "Vì sao vậy?",
  "mn7:2.9": "Vì tấm vải sạch, này các Tỳ Kheo.",
  "mn7:2.10": "Cũng vậy, này các Tỳ Kheo, khi lòng không nhơ bẩn, thì có thể chờ đợi một nơi đến tốt.",
  "mn7:3.1": "Và này các Tỳ Kheo, những thứ làm nhơ bẩn lòng là gì?",
  "mn7:3.2": "Tham muốn lệch lạc và lòng ham muốn quá mức là thứ làm nhơ bẩn lòng, ác ý là thứ làm nhơ bẩn lòng, giận dữ là thứ làm nhơ bẩn lòng, ôm hận là thứ làm nhơ bẩn lòng, coi thường người là thứ làm nhơ bẩn lòng, ganh đua là thứ làm nhơ bẩn lòng, ghen tức là thứ làm nhơ bẩn lòng, bỏn xẻn là thứ làm nhơ bẩn lòng, giả dối là thứ làm nhơ bẩn lòng, lừa trá là thứ làm nhơ bẩn lòng, cứng đầu là thứ làm nhơ bẩn lòng, hung hăng là thứ làm nhơ bẩn lòng, tự cao là thứ làm nhơ bẩn lòng, quá tự cao là thứ làm nhơ bẩn lòng, say mình là thứ làm nhơ bẩn lòng, buông lung là thứ làm nhơ bẩn lòng.",
  "mn7:4.1": "Này các Tỳ Kheo, vị Tỳ Kheo ấy biết rõ: ‘Tham muốn lệch lạc và lòng ham muốn quá mức là thứ làm nhơ bẩn lòng’; biết vậy rồi, vị ấy bỏ thứ làm nhơ bẩn lòng ấy đi.",
  "mn7:4.2": "‘Ác ý là thứ làm nhơ bẩn lòng’;",
  "mn7:4.3": "biết vậy rồi, vị ấy bỏ thứ làm nhơ bẩn lòng ấy đi.",
  "mn7:4.4": "‘Giận dữ là thứ làm nhơ bẩn lòng’;",
  "mn7:4.5": "biết vậy rồi, vị ấy bỏ thứ làm nhơ bẩn lòng ấy đi.",
  "mn7:4.6": "‘Ôm hận là thứ làm nhơ bẩn lòng’;",
  "mn7:4.7": "biết vậy rồi, vị ấy bỏ thứ làm nhơ bẩn lòng ấy đi.",
  "mn7:4.8": "‘Coi thường người là thứ làm nhơ bẩn lòng’;",
  "mn7:4.9": "biết vậy rồi, vị ấy bỏ thứ làm nhơ bẩn lòng ấy đi.",
  "mn7:4.10": "‘Ganh đua là thứ làm nhơ bẩn lòng’;",
  "mn7:4.11": "Khi biết như vậy, vị ấy buông bỏ sự khinh chê là vết nhơ của lòng.",
  "mn7:4.12": "‘Ganhtị là vết nhơ của lòng’—",
  "mn7:4.13": "khi biết như vậy, vị ấy buông bỏ lòng ganh tị là vết nhơ của lòng.",
  "mn7:4.14": "‘Bủn xỉn là vết nhơ của lòng’—",
  "mn7:4.15": "khi biết như vậy, vị ấy buông bỏ tính bủn xỉn là vết nhơ của lòng.",
  "mn7:4.16": "‘Dối trá là vết nhơ của lòng’—",
  "mn7:4.17": "khi biết như vậy, vị ấy buông bỏ sự dối trá là vết nhơ của lòng.",
  "mn7:4.18": "‘Lừa lọc là vết nhơ của lòng’—",
  "mn7:4.19": "khi biết như vậy, vị ấy buông bỏ sự lừa lọc là vết nhơ của lòng.",
  "mn7:4.20": "‘Cứng đầu là vết nhơ của lòng’—",
  "mn7:4.21": "khi biết như vậy, vị ấy buông bỏ tính cứng đầu là vết nhơ của lòng.",
  "mn7:4.22": "‘Hiếu thắng là vết nhơ của lòng’—",
  "mn7:4.23": "khi biết như vậy, vị ấy buông bỏ tính hiếu thắng là vết nhơ của lòng.",
  "mn7:4.24": "‘Tự cao là vết nhơ của lòng’—",
  "mn7:4.25": "khi biết như vậy, vị ấy buông bỏ lòng tự cao là vết nhơ của lòng.",
  "mn7:4.26": "‘Quá tự cao là vết nhơ của lòng’—",
  "mn7:4.27": "khi biết như vậy, vị ấy buông bỏ lòng quá tự cao là vết nhơ của lòng.",
  "mn7:4.28": "‘Say sưa với mình là vết nhơ của lòng’—",
  "mn7:4.29": "khi biết như vậy, vị ấy buông bỏ sự say sưa với mình là vết nhơ của lòng.",
  "mn7:4.30": "‘Buông lung là vết nhơ của lòng’—",
  "mn7:4.31": "khi biết như vậy, vị ấy buông bỏ sự buông lung là vết nhơ của lòng.",
  "mn7:5.1": "Này các Tỳ Kheo, khi nào một Tỳ Kheo biết rằng: ‘Tham muốn lệch lạc và lòng ham muốn quá mức là vết nhơ của lòng’—và vì biết như vậy, tham muốn lệch lạc và lòng ham muốn quá mức, là vết nhơ của lòng, đã được buông bỏ,",
  "mn7:5.2": "‘Ác ý là vết nhơ của lòng’—",
  "mn7:5.3": "khi biết như vậy, ác ý là vết nhơ của lòng đã được buông bỏ;",
  "mn7:5.4": "‘Giận dữ là vết nhơ của lòng’—",
  "mn7:5.5": "khi biết như vậy, giận dữ là vết nhơ của lòng đã được buông bỏ;",
  "mn7:5.6": "‘Ôm hận là vết nhơ của lòng’—",
  "mn7:5.7": "khi biết như vậy, ôm hận là vết nhơ của lòng đã được buông bỏ;",
  "mn7:5.8": "‘Coi thường người là vết nhơ của lòng’—",
  "mn7:5.9": "khi biết như vậy, coi thường người là vết nhơ của lòng đã được buông bỏ;",
  "mn7:5.10": "‘Tánh ganh đua là thứ làm bẩn tâm’—",
  "mn7:5.11": "biết vậy, thứ làm bẩn tâm là tánh ganh đua được dứt bỏ;",
  "mn7:5.12": "‘Ghen ghét là thứ làm bẩn tâm’—",
  "mn7:5.13": "biết vậy, thứ làm bẩn tâm là ghen ghét được dứt bỏ;",
  "mn7:5.14": "‘Keo kiệt là thứ làm bẩn tâm’—",
  "mn7:5.15": "biết vậy, thứ làm bẩn tâm là keo kiệt được dứt bỏ;",
  "mn7:5.16": "‘Dối trá là thứ làm bẩn tâm’—",
  "mn7:5.17": "biết vậy, thứ làm bẩn tâm là dối trá được dứt bỏ;",
  "mn7:5.18": "‘Lừa lọc là thứ làm bẩn tâm’—",
  "mn7:5.19": "biết vậy, thứ làm bẩn tâm là lừa lọc được dứt bỏ;",
  "mn7:5.20": "‘Cứng đầu là thứ làm bẩn tâm’—",
  "mn7:5.21": "biết vậy, thứ làm bẩn tâm là cứng đầu được dứt bỏ;",
  "mn7:5.22": "‘Chống đối là thứ làm bẩn tâm’—",
  "mn7:5.23": "biết vậy, thứ làm bẩn tâm là chống đối được dứt bỏ;",
  "mn7:5.24": "‘Tự cao là thứ làm bẩn tâm’—",
  "mn7:5.25": "biết vậy, thứ làm bẩn tâm là tự cao được dứt bỏ;",
  "mn7:5.26": "‘Quá tự cao là thứ làm bẩn tâm’—",
  "mn7:5.27": "biết vậy, thứ làm bẩn tâm là quá tự cao được dứt bỏ;",
  "mn7:5.28": "‘Say mình là thứ làm bẩn tâm’—",
  "mn7:5.29": "biết vậy, thứ làm bẩn tâm là say mình được dứt bỏ;",
  "mn7:5.30": "‘Buông lung là thứ làm bẩn tâm’—",
  "mn7:5.31": "biết vậy, thứ làm bẩn tâm là buông lung được dứt bỏ.",
  "mn7:5.32": "Vị ấy có lòng tin vững chắc nơi Đức Thế Tôn:",
  "mn7:5.33": "‘Đức Thế Tôn là bậc đáng được cúng dường, tự mình hiểu trọn vẹn, đủ hiểu biết và nết sống, đã đi đến nơi tốt lành, hiểu rõ đời, là người dẫn dắt không ai hơn được cho những người cần được rèn luyện, là bậc thầy của chư thiên và loài người, là bậc Giác Ngộ, là Đức Thế Tôn’;",
  "mn7:6.1": "có lòng tin vững chắc nơi lời dạy:",
  "mn7:6.2": "‘Lời dạy được Đức Thế Tôn khéo chỉ bày, có thể thấy ngay trong đời này, không phải chờ lâu, mời đến mà thấy, có thể đưa vào lòng mà sống theo, người có hiểu biết tự mình nhận ra’;",
  "mn7:7.1": "có lòng tin vững chắc nơi Tăng chúng:",
  "mn7:7.2": "‘Tăng chúng đệ tử của Đức Thế Tôn sống tốt đẹp, sống ngay thẳng, sống đúng đường, sống phải lẽ; tức là bốn đôi, tám hạng người. Tăng chúng đệ tử của Đức Thế Tôn xứng đáng được cúng dường, được tiếp đón, được dâng tặng, được chắp tay kính lễ, là ruộng phước không gì hơn cho đời’;",
  "mn7:8.1": "Khi những thứ ấy nơi vị ấy đã được nhổ bỏ, đã mửa ra, đã dứt hẳn, đã buông hẳn, thì vị ấy biết rõ: ‘Ta có lòng tin vững chắc nơi Đức Thế Tôn’, và vị ấy đạt được niềm vui vì điều lợi ích, đạt được niềm vui vì lời dạy, đạt được sự mừng sáng hợp với lời dạy.",
  "mn7:8.2": "Khi lòng mừng sáng khởi lên, niềm vui sinh ra; khi trong lòng có niềm vui, thân được lắng dịu; khi thân lắng dịu, vị ấy cảm nhận sự dễ chịu; khi dễ chịu, tâm trở nên yên vững;",
  "mn7:9.1": "‘đối với lời dạy …",
  "mn7:10.1": "đối với Tăng, tôi có lòng tin vững chắc, không lay chuyển’ — vị ấy có được niềm vui vì hiểu ra ý nghĩa, có được niềm vui vì hiểu ra lời dạy, có được sự mừng sáng gắn với lời dạy;",
  "mn7:10.2": "khi mừng sáng thì niềm vui sinh ra, khi trong lòng có niềm vui thì thân lắng dịu, thân đã lắng dịu thì cảm nhận sự dễ chịu, khi dễ chịu thì lòng yên vững.",
  "mn7:11.1": "‘Những gì nơi tôi đã bị dứt bỏ, đã mửa ra, đã buông ra, đã rời hẳn’ — vị ấy có được niềm vui vì hiểu ra ý nghĩa, có được niềm vui vì hiểu ra lời dạy, có được sự mừng sáng gắn với lời dạy;",
  "mn7:11.2": "khi mừng sáng thì niềm vui sinh ra, khi trong lòng có niềm vui thì thân lắng dịu, thân đã lắng dịu thì cảm nhận sự dễ chịu, khi dễ chịu thì lòng yên vững.",
  "mn7:12.1": "Này các Tỳ Kheo, vị Tỳ Kheo ấy có nết sống như vậy, có tâm như vậy, có sự hiểu rõ như vậy, dù ăn cơm gạo ngon cùng với nhiều món canh và nhiều món ăn kèm đủ loại, việc ấy cũng không thành chướng ngại cho vị ấy.",
  "mn7:12.2": "Cũng như, này các Tỳ Kheo, một tấm vải dơ bẩn, bám đầy vết nhơ, khi gặp nước trong thì trở nên sạch sẽ, sáng sạch; hay vàng khi đưa vào lò thì trở nên sạch, sáng sạch;",
  "mn7:12.3": "cũng vậy, này các Tỳ Kheo, vị Tỳ Kheo ấy có nết sống như vậy, có tâm như vậy, có sự hiểu rõ như vậy, dù ăn cơm gạo ngon cùng với nhiều món canh và nhiều món ăn kèm đủ loại, việc ấy cũng không thành chướng ngại cho vị ấy.",
  "mn7:13.1": "Vị ấy sống trùm khắp một phương với tấm lòng thương yêu; cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư. Như vậy, khắp trên, dưới, ngang, khắp mọi nơi, đối với tất cả mọi loài trong toàn thế gian, vị ấy sống trùm khắp với tấm lòng thương yêu rộng lớn, cao rộng, không lường, không thù hằn, không ác ý.",
  "mn7:14.1": "Với tấm lòng thương xót …",
  "mn7:15.1": "Với tấm lòng vui theo điều lành của người …",
  "mn7:16.1": "Với tấm lòng bình thản, vị ấy sống trùm khắp một phương; cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư. Như vậy, khắp trên, dưới, ngang, khắp mọi nơi, đối với tất cả mọi loài trong toàn thế gian, vị ấy sống trùm khắp với tấm lòng bình thản rộng lớn, cao rộng, không lường, không thù hằn, không ác ý.",
  "mn7:17.1": "Vị ấy hiểu rõ: ‘Có cái này, có cái thấp kém, có cái cao hơn, và còn có lối ra vượt khỏi chỗ còn gắn với nhận ra này.’",
  "mn7:18.1": "Với người biết như vậy, thấy như vậy, lòng được buông khỏi dòng rỉ chảy của ham muốn giác quan, cũng được buông khỏi dòng rỉ chảy của muốn tiếp tục có mặt, cũng được buông khỏi dòng rỉ chảy của không thấy rõ.",
  "mn7:18.2": "Khi đã được buông ra, vị ấy biết: ‘Đã được buông ra.’",
  "mn7:18.3": "Vị ấy hiểu rõ: ‘Sinh đã dứt, đời sống phạm hạnh đã sống xong, việc cần làm đã làm xong, không còn trở lui trạng thái này nữa.’",
  "mn7:18.4": "Này các Tỳ Kheo, điều này được gọi là:",
  "mn7:18.5": "‘vị Tỳ Kheo đã tắm rửa bên trong bằng sự tắm rửa ở bên trong.’",
  "mn7:19.1": "Lúc ấy, bà-la-môn Sundarikabhāradvāja đang ngồi không xa Đức Thế Tôn.",
  "mn7:19.2": "Rồi bà-la-môn Sundarikabhāradvāja thưa với Đức Thế Tôn:",
  "mn7:19.3": "“Thưa ngài Gotama, ngài có đi đến sông Bāhukā để tắm không?”",
  "mn7:19.4": "“Này bà-la-môn, sông Bāhukā có ích gì?",
  "mn7:19.5": "Sông Bāhukā sẽ làm được gì?”",
  "mn7:19.6": "“Thưa ngài Gotama, sông Bāhukā được nhiều người trong đời xem là linh thiêng, thưa ngài Gotama, sông Bāhukā được nhiều người xem là đem lại điều lành; ở sông Bāhukā, nhiều người rửa trôi việc xấu mình đã làm.”",
  "mn7:20.1": "Rồi Đức Thế Tôn nói với bà-la-môn Sundarikabhāradvāja bằng kệ:",
  "mn7:20.2": "“Sông Bāhukā, sông Adhikakka,",
  "mn7:20.3": "sông Gayā, sông Sundarikā nữa,",
  "mn7:20.4": "sông Sarassatī và Payāga,",
  "mn7:20.5": "cùng cả sông Bāhumatī;",
  "mn7:20.6": "người ngu cứ nhảy xuống mãi,",
  "mn7:20.7": "Việc xấu đen tối không thể rửa sạch.",
  "mn7:20.8": "Sông Sundarikā làm được gì,",
  "mn7:20.9": "sông Payāgā hay sông Bāhukā làm được gì;",
  "mn7:20.10": "với người ôm lòng thù, đã làm điều sai quấy,",
  "mn7:20.11": "thì sông đâu rửa sạch được người làm điều ác.",
  "mn7:20.12": "Với người trong sạch thì ngày nào cũng là ngày tốt,",
  "mn7:20.13": "với người trong sạch thì ngày giữ mình trong sạch lúc nào cũng có,",
  "mn7:20.14": "với người trong sạch, làm việc sạch sẽ,",
  "mn7:20.15": "thì việc giữ nếp sống tốt luôn thành tựu.",
  "mn7:20.16": "Này Bà-la-môn, hãy tắm ngay ở đây,",
  "mn7:20.17": "hãy làm cho mọi loài đều được yên ổn.",
  "mn7:20.18": "Nếu ông không nói dối,",
  "mn7:20.19": "nếu ông không hại mạng sống,",
  "mn7:20.20": "nếu ông không lấy của không cho,",
  "mn7:20.21": "có lòng tin và không keo kiệt,",
  "mn7:20.22": "thì ông đi Gayā để làm gì,",
  "mn7:20.23": "cả giếng nước của ông cũng là Gayā rồi.",
  "mn7:21.1": "Khi được nói vậy, Bà-la-môn Sundarikabhāradvāja thưa với Đức Thế Tôn:",
  "mn7:21.2": "“Thật hay quá, thưa ngài Gotama, thật hay quá, thưa ngài Gotama.",
  "mn7:21.3": "Cũng như dựng vật bị úp xuống lên, mở ra vật bị che kín, chỉ đường cho người lạc lối, đem đèn dầu vào chỗ tối để người có mắt thấy được hình sắc; cũng vậy, ngài Gotama đã bày rõ lẽ thật bằng nhiều cách.",
  "mn7:21.4": "Con xin nương tựa nơi ngài Gotama, nơi lời dạy, và nơi đoàn Tỳ Kheo.",
  "mn7:21.5": "Mong con được xuất gia với ngài Gotama, mong được nhận vào sống đời không nhà.”",
  "mn7:22.1": "Bà-la-môn Sundarikabhāradvāja đã được xuất gia với Đức Thế Tôn, đã được nhận vào sống đời không nhà.",
  "mn7:22.2": "Không bao lâu sau khi được nhận vào, Tỳ Kheo Bhāradvāja sống một mình, tách riêng, siêng năng, bền chí, dốc lòng, chẳng bao lâu đã tự mình biết rõ, tự mình thấy rõ, ngay trong đời này đạt đến mục đích cao nhất mà những người con trai trong các gia đình chân chánh rời nhà sống đời không nhà vì mục đích ấy.",
  "mn7:22.3": "Vị ấy tự biết: “Sự sinh đã dứt, nếp sống phạm hạnh đã trọn, việc cần làm đã làm xong, không còn trở lui đời này nữa.”",
  "mn7:22.4": "Và Tỳ Kheo Bhāradvāja đã là một vị đã sạch hết lậu hoặc.",
  "mn7:22.5": "Kinh Tấm Vải, bài thứ bảy, chấm dứt."
}
window.BILARA["mn07"]["vi"]["mn07:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";