window.BILARA = window.BILARA || {};
window.BILARA["mn109"] = window.BILARA["mn109"] || {};
window.BILARA["mn109"]["vi"] = {
  "mn109:0.1": "Trung Bộ Kinh 109",
  "mn109:0.2": "Kinh Trăng Tròn Lớn",
  "mn109:1.1": "Tôi nghe như vầy—",
  "mn109:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, tại vườn phía đông, trong lầu của mẹ ông Migāra.",
  "mn109:2.1": "Lúc ấy, đúng ngày bố-tát, ngày rằm, đêm trăng tròn, Đức Thế Tôn ngồi ngoài trời, có chúng Tỳ Kheo vây quanh.",
  "mn109:3.1": "Bấy giờ, một Tỳ Kheo đứng dậy khỏi chỗ ngồi, vắt y qua một bên vai, chắp tay hướng về Đức Thế Tôn và thưa rằng:",
  "mn109:3.2": "“Bạch Thế Tôn, con muốn hỏi Đức Thế Tôn một điều, nếu Đức Thế Tôn cho phép con hỏi.”",
  "mn109:3.3": "“Vậy thì, này Tỳ Kheo, hãy ngồi tại chỗ của mình và hỏi điều gì ông muốn.”",
  "mn109:3.4": "Rồi vị Tỳ Kheo ấy ngồi tại chỗ của mình và thưa với Đức Thế Tôn:",
  "mn109:4.1": "“Bạch Thế Tôn, có phải đây là năm nhóm bị nắm giữ, đó là—",
  "mn109:4.2": "nhóm thân, nhóm cảm nhận, nhóm ghi nhận, nhóm các hoạt động của tâm, nhóm sự nhận biết?”",
  "mn109:4.3": "“Đúng vậy, này Tỳ Kheo, đây là năm nhóm bị nắm giữ, đó là—",
  "mn109:4.4": "nhóm thân, nhóm cảm nhận, nhóm ghi nhận, nhóm các hoạt động của tâm, nhóm sự nhận biết.”",
  "mn109:4.5": "“Lành thay, bạch Thế Tôn.” Vị Tỳ Kheo ấy vui mừng đón nhận lời Đức Thế Tôn dạy, rồi hỏi thêm:",
  "mn109:5.1": "“Nhưng bạch Thế Tôn, năm nhóm bị nắm giữ này lấy gì làm gốc?”",
  "mn109:5.2": "“Này Tỳ Kheo, năm nhóm bị nắm giữ này lấy sự muốn làm gốc.”",
  "mn109:6.1": "“Bạch Thế Tôn, sự nắm giữ ấy có phải chính là năm nhóm bị nắm giữ đó không, hay sự nắm giữ là cái gì khác ngoài năm nhóm bị nắm giữ ấy?”",
  "mn109:6.2": "“Này Tỳ Kheo, sự nắm giữ ấy không phải chính là năm nhóm bị nắm giữ đó, mà cũng không phải là cái gì khác ngoài năm nhóm bị nắm giữ ấy.",
  "mn109:6.3": "Này Tỳ Kheo, sự ham muốn dính mắc đối với năm nhóm bị nắm giữ ấy, đó là sự nắm giữ ở đó.”",
  "mn109:7.1": "“Nhưng bạch Thế Tôn, có thể có sự khác nhau về ham muốn dính mắc đối với năm nhóm bị nắm giữ chăng?”",
  "mn109:7.2": "“Có thể có, này Tỳ Kheo,” Đức Thế Tôn nói.",
  "mn109:7.3": "“Ở đây, này Tỳ Kheo, có người nghĩ như vầy:",
  "mn109:7.4": "‘Mong rằng trong thời tới, tôi sẽ có thân như thế này, sẽ có cảm nhận như thế này, sẽ có ghi nhận như thế này, sẽ có các hoạt động của tâm như thế này, sẽ có sự nhận biết như thế này.’",
  "mn109:7.5": "Này Tỳ Kheo, như vậy là có sự khác nhau về ham muốn dính mắc đối với năm nhóm bị nắm giữ.”",
  "mn109:8.1": "“Nhưng bạch Thế Tôn, đến mức nào thì được gọi là các nhóm?”",
  "mn109:8.2": "“Này Tỳ Kheo, bất cứ thân nào, thuộc quá khứ, tương lai hay hiện tại, ở trong hay ở ngoài, thô hay mịn, thấp kém hay tốt đẹp, xa hay gần—đó gọi là nhóm thân.",
  "mn109:8.3": "Bất cứ cảm nhận nào, thuộc quá khứ, tương lai hay hiện tại, ở trong hay ở ngoài, thô hay mịn, thấp kém hay tốt đẹp, xa hay gần—đó gọi là nhóm cảm nhận.",
  "mn109:8.4": "Bất cứ ghi nhận nào, thuộc quá khứ, tương lai hay hiện tại, ở trong hay ở ngoài, thô hay mịn, thấp kém hay tốt đẹp, xa hay gần—đó gọi là nhóm ghi nhận.",
  "mn109:8.5": "Bất cứ các hoạt động nào của tâm, thuộc quá khứ, tương lai hay hiện tại, ở trong hay ở ngoài, thô hay mịn, thấp kém hay tốt đẹp, xa hay gần—đó gọi là nhóm các hoạt động của tâm.",
  "mn109:8.6": "Bất cứ sự nhận biết nào, thuộc quá khứ, tương lai hay hiện tại, ở trong hay ở ngoài, thô hay mịn, thấp kém hay tốt đẹp, xa hay gần—đó gọi là nhóm sự nhận biết.”",
  "mn109:8.7": "Đến mức này, này Tỳ Kheo, là cách gọi năm nhóm bám chấp là các nhóm.",
  "mn109:9.1": "“Bạch Thế Tôn, do đâu, nhờ đâu mà gọi là nhóm thân này?",
  "mn109:9.2": "Do đâu, nhờ đâu mà gọi là nhóm cảm giác?",
  "mn109:9.3": "Do đâu, nhờ đâu mà gọi là nhóm ghi nhận?",
  "mn109:9.4": "Do đâu, nhờ đâu mà gọi là nhóm các hoạt động của tâm?",
  "mn109:9.5": "Do đâu, nhờ đâu mà gọi là nhóm sự nhận biết?”",
  "mn109:9.6": "“Này Tỳ Kheo, bốn thể lớn là do đâu, bốn thể lớn là nhờ đâu mà gọi là nhóm thân này.",
  "mn109:9.7": "Sự đụng chạm là do đâu, sự đụng chạm là nhờ đâu mà gọi là nhóm cảm giác.",
  "mn109:9.8": "Sự đụng chạm là do đâu, sự đụng chạm là nhờ đâu mà gọi là nhóm ghi nhận.",
  "mn109:9.9": "Sự đụng chạm là do đâu, sự đụng chạm là nhờ đâu mà gọi là nhóm các hoạt động của tâm.",
  "mn109:9.10": "Này Tỳ Kheo, danh và thân là do đâu, danh và thân là nhờ đâu mà gọi là nhóm sự nhận biết.”",
  "mn109:10.1": "“Nhưng bạch Thế Tôn, khi nào thì có cái thấy chấp thân này là ta?”",
  "mn109:10.2": "“Này Tỳ Kheo, ở đây, người thường không nghe học, không gặp bậc cao quý, không rành lời dạy của bậc cao quý, không được rèn luyện trong lời dạy của bậc cao quý, không gặp người lành, không rành nếp sống của người lành, không được rèn luyện trong nếp sống của người lành,",
  "mn109:10.3": "nghĩ thân này là ta, hay nghĩ ta có thân này, hay nghĩ thân này ở trong ta, hay nghĩ ta ở trong thân này;",
  "mn109:10.4": "nghĩ cảm giác là ta, hay nghĩ ta có cảm giác, hay nghĩ cảm giác ở trong ta, hay nghĩ ta ở trong cảm giác;",
  "mn109:10.5": "nghĩ sự ghi nhận là ta, hay nghĩ ta có sự ghi nhận, hay nghĩ sự ghi nhận ở trong ta, hay nghĩ ta ở trong sự ghi nhận;",
  "mn109:10.6": "nghĩ các hoạt động của tâm là ta, hay nghĩ ta có các hoạt động của tâm, hay nghĩ các hoạt động của tâm ở trong ta, hay nghĩ ta ở trong các hoạt động của tâm;",
  "mn109:10.7": "nghĩ sự nhận biết là ta, hay nghĩ ta có sự nhận biết, hay nghĩ sự nhận biết ở trong ta, hay nghĩ ta ở trong sự nhận biết.",
  "mn109:10.8": "Này Tỳ Kheo, như vậy là có cái thấy chấp thân này là ta.”",
  "mn109:11.1": "“Nhưng bạch Thế Tôn, khi nào thì không có cái thấy chấp thân này là ta?”",
  "mn109:11.2": "“Này Tỳ Kheo, ở đây, người nghe học nhiều, là học trò của bậc cao quý, gặp bậc cao quý, rành lời dạy của bậc cao quý, được rèn luyện khéo trong lời dạy của bậc cao quý, gặp người lành, rành nếp sống của người lành, được rèn luyện khéo trong nếp sống của người lành,",
  "mn109:11.3": "không nghĩ thân này là ta, không nghĩ ta có thân này, không nghĩ thân này ở trong ta, không nghĩ ta ở trong thân này;",
  "mn109:11.4": "không nghĩ cảm giác là ta, không nghĩ ta có cảm giác, không nghĩ cảm giác ở trong ta, không nghĩ ta ở trong cảm giác;",
  "mn109:11.5": "không nghĩ sự ghi nhận là ta, không nghĩ ta có sự ghi nhận, không nghĩ sự ghi nhận ở trong ta, không nghĩ ta ở trong sự ghi nhận;",
  "mn109:11.6": "không nghĩ các hoạt động của tâm là ta, không nghĩ ta có các hoạt động của tâm, không nghĩ các hoạt động của tâm ở trong ta, không nghĩ ta ở trong các hoạt động của tâm;",
  "mn109:11.7": "không nghĩ sự nhận biết là ta, không nghĩ ta có sự nhận biết, không nghĩ sự nhận biết ở trong ta, không nghĩ ta ở trong sự nhận biết.",
  "mn109:11.8": "Này Tỳ Kheo, như vậy là không có cái thấy chấp thân này là ta.”",
  "mn109:12.1": "“Bạch Thế Tôn, cái ngọt của thân này là gì, mặt hại là gì, lối ra khỏi là gì?",
  "mn109:12.2": "Cái ngọt của cảm giác là gì, mặt hại là gì, lối ra khỏi là gì?",
  "mn109:12.3": "Cái ngọt của sự ghi nhận là gì, mặt hại là gì, lối ra khỏi là gì?”",
  "mn109:12.4": "Này Tỳ Kheo, nơi các hoạt động của tâm, đâu là vị ngọt, đâu là mặt hại, đâu là lối ra?",
  "mn109:12.5": "Nơi sự nhận biết, đâu là vị ngọt, đâu là mặt hại, đâu là lối ra?",
  "mn109:12.6": "Này Tỳ Kheo, niềm vui và sự mừng thích nào khởi lên do nương vào sắc, đó là vị ngọt trong sắc.",
  "mn109:12.7": "Sắc là không bền, là khổ đau, có tính đổi khác; đó là mặt hại trong sắc.",
  "mn109:12.8": "Sự dẹp bỏ lòng ưa thích và mê đắm đối với sắc, sự buông hẳn lòng ưa thích và mê đắm ấy, đó là lối ra khỏi sắc.",
  "mn109:12.9": "Này Tỳ Kheo, niềm vui và sự mừng thích nào khởi lên do nương vào cảm giác, đó là vị ngọt trong cảm giác. ",
  "mn109:12.10": "Này Tỳ Kheo, niềm vui và sự mừng thích nào khởi lên do nương vào sự ghi nhận, đó là vị ngọt trong sự ghi nhận. ",
  "mn109:12.11": "Này Tỳ Kheo, niềm vui và sự mừng thích nào khởi lên do nương vào các hoạt động của tâm, đó là vị ngọt trong các hoạt động của tâm. ",
  "mn109:12.12": "Này Tỳ Kheo, niềm vui và sự mừng thích nào khởi lên do nương vào sự nhận biết, đó là vị ngọt trong sự nhận biết.",
  "mn109:12.13": "Sự nhận biết là không bền, là khổ đau, có tính đổi khác; đó là mặt hại trong sự nhận biết.",
  "mn109:12.14": "Sự dẹp bỏ lòng ưa thích và mê đắm đối với sự nhận biết, sự buông hẳn lòng ưa thích và mê đắm ấy, đó là lối ra khỏi sự nhận biết.",
  "mn109:13.1": "Bạch Thế Tôn, biết thế nào, thấy thế nào, để đối với thân có sự nhận biết này và đối với mọi dấu hiệu ở bên ngoài, những ngầm chứa của ý nghĩ \"ta là\", \"của ta\", và thói hơn thua về ta không còn nữa?",
  "mn109:13.2": "Này Tỳ Kheo, bất cứ sắc nào, thuộc quá khứ, tương lai hay hiện tại, ở trong hay ở ngoài, thô hay mịn, kém hay tốt, xa hay gần, mọi sắc đều được thấy đúng như thật bằng sự hiểu rõ đúng đắn rằng: \"Cái này không phải của tôi, tôi không phải là cái này, cái này không phải là mình thật của tôi\".",
  "mn109:13.3": "Bất cứ cảm giác nào …",
  "mn109:13.4": "bất cứ sự ghi nhận nào …",
  "mn109:13.5": "bất cứ các hoạt động của tâm nào …",
  "mn109:13.6": "bất cứ sự nhận biết nào, thuộc quá khứ, tương lai hay hiện tại, ở trong hay ở ngoài, thô hay mịn, kém hay tốt, xa hay gần, mọi sự nhận biết đều được thấy đúng như thật bằng sự hiểu rõ đúng đắn rằng: \"Cái này không phải của tôi, tôi không phải là cái này, cái này không phải là mình thật của tôi\".",
  "mn109:13.7": "Này Tỳ Kheo, biết như vậy, thấy như vậy, thì đối với thân có sự nhận biết này và đối với mọi dấu hiệu ở bên ngoài, những ngầm chứa của ý nghĩ \"ta là\", \"của ta\", và thói hơn thua về ta không còn nữa.",
  "mn109:14.1": "Rồi một Tỳ Kheo khởi lên ý nghĩ như sau:",
  "mn109:14.2": "\"Vậy thì, này bạn, sắc không phải mình thật, cảm giác không phải mình thật, sự ghi nhận không phải mình thật, các hoạt động của tâm không phải mình thật, sự nhận biết không phải mình thật;",
  "mn109:14.3": "thì những việc làm do cái không phải mình thật làm ra sẽ chạm đến ai?\"",
  "mn109:14.4": "Rồi Đức Thế Tôn biết được ý nghĩ trong tâm vị Tỳ Kheo ấy, liền gọi các Tỳ Kheo:",
  "mn109:14.5": "\"Này các Tỳ Kheo, có thể có chuyện một kẻ rỗng không nào đó, không biết, bị mù mờ che lấp, với tâm bị cơn khát muốn sai khiến, lại nghĩ rằng mình có thể vượt khỏi lời dạy của bậc Thầy như sau:",
  "mn109:14.6": "‘Vậy thì, này bạn, sắc không phải mình thật, cảm giác không phải mình thật, sự ghi nhận không phải mình thật, các hoạt động của tâm không phải mình thật, sự nhận biết không phải mình thật;",
  "mn109:14.7": "thì những việc làm do cái không phải mình thật làm ra sẽ chạm đến ai?’",
  "mn109:14.8": "Này các Tỳ Kheo, Ta đã dạy và uốn nắn các ông kỹ lưỡng về từng điều.",
  "mn109:15.1": "Các Tỳ Kheo nghĩ sao,",
  "mn109:15.2": "sắc là bền chắc hay không bền chắc?",
  "mn109:15.3": "“Không bền chắc, bạch Thế Tôn.”",
  "mn109:15.4": "“Cái gì không bền chắc, cái đó là khổ đau hay là dễ chịu?”",
  "mn109:15.5": "“Thưa Thế Tôn, là khổ đau.”",
  "mn109:15.6": "“Cái gì không bền, là khổ đau, có tính đổi khác, thì có hợp để nhìn như vầy không:",
  "mn109:15.7": "‘Cái này là của tôi, cái này là tôi, cái này là mình của tôi’?”",
  "mn109:15.8": "“Thưa Thế Tôn, không.”",
  "mn109:16.1": "“Các Tỳ Kheo nghĩ sao,",
  "mn109:16.2": "cảm giác ...",
  "mn109:16.3": "sự ghi nhận ...",
  "mn109:16.4": "các hoạt động của tâm ...",
  "mn109:16.5": "sự nhận biết là bền hay không bền?”",
  "mn109:16.6": "“Thưa Thế Tôn, không bền.”",
  "mn109:16.7": "“Cái gì không bền, thì là khổ đau hay dễ chịu?”",
  "mn109:16.8": "“Thưa Thế Tôn, là khổ đau.”",
  "mn109:16.9": "“Cái gì không bền, là khổ đau, có tính đổi khác, thì có hợp để nhìn như vầy không:",
  "mn109:16.10": "‘Cái này là của tôi, cái này là tôi, cái này là mình của tôi’?”",
  "mn109:16.11": "“Thưa Thế Tôn, không.”",
  "mn109:16.12": "“Vậy nên, này các Tỳ Kheo, bất cứ thân nào, thuộc quá khứ, tương lai hay hiện nay, ở trong hay ở ngoài, thô hay nhỏ nhiệm, kém hay tốt đẹp, xa hay gần, mọi thân đều phải được thấy đúng như thật bằng sự hiểu rõ đúng đắn rằng: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải là mình của tôi’.",
  "mn109:17.1": "Bất cứ cảm giác nào ...",
  "mn109:17.2": "bất cứ sự ghi nhận nào ...",
  "mn109:17.3": "bất cứ các hoạt động của tâm nào ...",
  "mn109:17.4": "bất cứ sự nhận biết nào, thuộc quá khứ, tương lai hay hiện nay, ở trong hay ở ngoài, thô hay nhỏ nhiệm, kém hay tốt đẹp, xa hay gần, mọi sự nhận biết đều phải được thấy đúng như thật bằng sự hiểu rõ đúng đắn rằng: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải là mình của tôi’.",
  "mn109:17.5": "Thấy như vậy, này các Tỳ Kheo, người nghe nhiều, là học trò bậc thánh, chán lìa cả thân, chán lìa cả cảm giác, chán lìa cả sự ghi nhận, chán lìa cả các hoạt động của tâm, chán lìa cả sự nhận biết;",
  "mn109:18.1": "do chán lìa nên lòng phai nhạt dính mắc, do phai nhạt dính mắc nên được buông thoát. Khi đã được buông thoát, thì biết rằng: ‘Đã buông thoát’.",
  "mn109:18.2": "Vị ấy hiểu rõ: ‘Sự sinh đã dứt, đời sống trong sạch đã sống xong, việc cần làm đã làm xong, không còn trở lui trạng thái này nữa’.“",
  "mn109:18.3": "Đức Thế Tôn nói như vậy.",
  "mn109:18.4": "Các Tỳ Kheo vui mừng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn109:18.5": "Và trong khi lời giải bày này đang được nói ra, tâm của khoảng sáu mươi vị Tỳ Kheo đã được buông thoát khỏi các dòng rỉ chảy nhờ không còn nắm giữ.",
  "mn109:18.6": "Kinh Trăng Tròn Lớn, bài thứ chín, đến đây là xong."
}
window.BILARA["mn109"]["vi"]["mn109:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
