window.BILARA = window.BILARA || {};
window.BILARA["mn103"] = window.BILARA["mn103"] || {};
window.BILARA["mn103"]["vi"] = {
  "mn103:0.1": "Trung Bộ Kinh 103",
  "mn103:0.2": "Kinh Vì Sao",
  "mn103:1.1": "Tôi nghe như vầy—",
  "mn103:1.2": "Một thời, Đức Thế Tôn ở tại Pisinārā, trong khu rừng Baliharaṇa.",
  "mn103:1.3": "Tại đó, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn103:1.4": "“Này các Tỳ Kheo.”",
  "mn103:1.5": "Các Tỳ Kheo ấy thưa với Đức Thế Tôn: “Dạ, bạch Ngài.”",
  "mn103:1.6": "Đức Thế Tôn nói như vầy:",
  "mn103:2.1": "“Này các Tỳ Kheo, các ông nghĩ sao về Ta:",
  "mn103:2.2": "‘Sa-môn Gotama nói lời dạy vì áo mặc, hay Sa-môn Gotama nói lời dạy vì đồ ăn xin được, hay Sa-môn Gotama nói lời dạy vì chỗ ở, hay Sa-môn Gotama nói lời dạy vì mong được đời này đời khác’?”",
  "mn103:2.3": "“Bạch Ngài, chúng con không nghĩ về Đức Thế Tôn như vậy:",
  "mn103:2.4": "‘Sa-môn Gotama nói lời dạy vì áo mặc, hay Sa-môn Gotama nói lời dạy vì đồ ăn xin được, hay Sa-môn Gotama nói lời dạy vì chỗ ở, hay Sa-môn Gotama nói lời dạy vì mong được đời này đời khác’.”",
  "mn103:2.5": "“Này các Tỳ Kheo, vậy các ông không nghĩ về Ta như vầy:",
  "mn103:2.6": "‘Sa-môn Gotama nói lời dạy vì áo mặc …",
  "mn103:2.7": "hay Sa-môn Gotama nói lời dạy vì mong được đời này đời khác’;",
  "mn103:2.8": "vậy thì các ông nghĩ về Ta ra sao?”",
  "mn103:2.9": "“Bạch Ngài, chúng con nghĩ về Đức Thế Tôn như vầy:",
  "mn103:2.10": "‘Đức Thế Tôn đầy lòng thương, mong điều lành cho chúng con;",
  "mn103:2.11": "vì lòng thương ấy mà Ngài nói lời dạy’.”",
  "mn103:2.12": "“Này các Tỳ Kheo, nếu các ông nghĩ về Ta như vầy:",
  "mn103:2.13": "‘Đức Thế Tôn đầy lòng thương, mong điều lành;",
  "mn103:2.14": "vì lòng thương ấy mà Ngài nói lời dạy’,",
  "mn103:3.1": "thì này các Tỳ Kheo, những điều Ta đã tự mình biết rõ rồi chỉ dạy cho các ông, đó là—",
  "mn103:3.2": "bốn nền nhớ biết rõ, bốn sự gắng sức đúng, bốn nền tảng cho năng lực mầu nhiệm, năm sức nhận ra, năm sức mạnh, bảy phần đưa đến giác ngộ, con đường thánh gồm tám phần; ở đây, tất cả các ông phải cùng nhau học, sống hòa hợp, vui vẻ với nhau, không cãi nhau.",
  "mn103:4.1": "Này các Tỳ Kheo, trong khi các ông đang sống hòa hợp, vui vẻ với nhau, không cãi nhau, cùng nhau học như vậy, có thể có hai Tỳ Kheo nói khác nhau về lời dạy cao hơn.",
  "mn103:5.1": "Trong trường hợp ấy, nếu các ông nghĩ rằng:",
  "mn103:5.2": "‘Hai vị đáng kính này khác nhau cả về ý nghĩa lẫn lời nói’, thì các ông nên đến vị Tỳ Kheo nào mà các ông cho là dễ nói hơn, rồi nói với vị ấy như vầy:",
  "mn103:5.3": "‘Thưa các vị đáng kính, hai vị khác nhau cả về ý nghĩa lẫn lời nói.",
  "mn103:5.4": "Xin các vị đáng kính hãy biết điều này—",
  "mn103:5.5": "rằng hai vị khác nhau cả về ý nghĩa lẫn lời nói.’",
  "mn103:5.6": "Xin chư vị đừng rơi vào tranh cãi.",
  "mn103:5.7": "Rồi với nhóm Tỳ Kheo đứng về một phía kia, vị Tỳ Kheo nào các vị cho là dễ nói hơn thì hãy đến gặp vị ấy và nói như sau:",
  "mn103:5.8": "‘Thưa chư vị, điều được nói ra khác nhau cả về ý nghĩa lẫn lời nói.",
  "mn103:5.9": "Xin chư vị cũng biết điều này—",
  "mn103:5.10": "rằng khác nhau cả về ý nghĩa lẫn lời nói.",
  "mn103:5.11": "Xin chư vị đừng rơi vào tranh cãi.’",
  "mn103:5.12": "Như vậy, điều nắm sai phải được giữ là nắm sai, điều nắm đúng phải được giữ là nắm đúng.",
  "mn103:5.13": "Sau khi giữ điều nắm sai là nắm sai, và giữ điều nắm đúng là nắm đúng, thì điều Đức Thế Tôn dạy và nếp sống theo khuôn phép phải được nói ra.",
  "mn103:6.1": "Nếu các vị nghĩ như vầy:",
  "mn103:6.2": "‘Các vị ấy khác nhau về ý nghĩa, nhưng lời nói thì hợp nhau’, thì vị Tỳ Kheo nào các vị cho là dễ nói hơn, hãy đến gặp vị ấy và nói như sau:",
  "mn103:6.3": "‘Thưa chư vị, các vị khác nhau về ý nghĩa, nhưng lời nói thì hợp nhau.",
  "mn103:6.4": "Xin chư vị cũng biết điều này—",
  "mn103:6.5": "rằng khác nhau về ý nghĩa, nhưng lời nói thì hợp nhau.",
  "mn103:6.6": "Xin chư vị đừng rơi vào tranh cãi.’",
  "mn103:6.7": "Rồi với nhóm Tỳ Kheo đứng về một phía kia, vị Tỳ Kheo nào các vị cho là dễ nói hơn thì hãy đến gặp vị ấy và nói như sau:",
  "mn103:6.8": "‘Thưa chư vị, các vị khác nhau về ý nghĩa, nhưng lời nói thì hợp nhau.",
  "mn103:6.9": "Xin chư vị cũng biết điều này—",
  "mn103:6.10": "rằng khác nhau về ý nghĩa, nhưng lời nói thì hợp nhau.",
  "mn103:6.11": "Xin chư vị đừng rơi vào tranh cãi.’",
  "mn103:6.12": "Như vậy, điều nắm sai phải được giữ là nắm sai, điều nắm đúng phải được giữ là nắm đúng.",
  "mn103:6.13": "Sau khi giữ điều nắm sai là nắm sai, và giữ điều nắm đúng là nắm đúng, thì điều Đức Thế Tôn dạy và nếp sống theo khuôn phép phải được nói ra.",
  "mn103:7.1": "Nếu các vị nghĩ như vầy:",
  "mn103:7.2": "‘Các vị ấy hợp nhau về ý nghĩa, nhưng lời nói thì khác nhau’, thì vị Tỳ Kheo nào các vị cho là dễ nói hơn, hãy đến gặp vị ấy và nói như sau:",
  "mn103:7.3": "‘Thưa chư vị, các vị hợp nhau về ý nghĩa, nhưng lời nói thì khác nhau.",
  "mn103:7.4": "Xin chư vị cũng biết điều này—",
  "mn103:7.5": "rằng hợp nhau về ý nghĩa, nhưng lời nói thì khác nhau.",
  "mn103:7.6": "Nhưng chuyện này chỉ là nhỏ thôi, đó là lời nói.",
  "mn103:7.7": "Xin chư vị đừng vì chuyện nhỏ ấy mà rơi vào tranh cãi.’",
  "mn103:7.8": "Rồi với nhóm Tỳ Kheo đứng về một phía kia, vị Tỳ Kheo nào các vị cho là dễ nói hơn thì hãy đến gặp vị ấy và nói như sau:",
  "mn103:7.9": "‘Thưa chư vị, các vị hợp nhau về ý nghĩa, nhưng lời nói thì khác nhau.",
  "mn103:7.10": "Các vị hãy biết thêm điều này:",
  "mn103:7.11": "nếu xét về nghĩa thì hợp nhau, nhưng lời nói thì khác nhau.",
  "mn103:7.12": "Nhưng điều ấy chỉ là chuyện nhỏ, tức là khác nhau ở lời nói.",
  "mn103:7.13": "Xin các vị đừng vì chuyện nhỏ ấy mà cãi nhau.",
  "mn103:7.14": "Như vậy, điều nắm đúng thì phải ghi nhớ là đã nắm đúng, điều nắm sai thì phải ghi nhớ là đã nắm sai.",
  "mn103:7.15": "Sau khi ghi nhớ điều nắm đúng là đã nắm đúng, điều nắm sai là đã nắm sai, thì điều Đức Thế Tôn dạy và nếp sống tu học phải được nói ra.",
  "mn103:8.1": "Ở đây, nếu các vị nghĩ rằng:",
  "mn103:8.2": "‘Các vị ấy thật ra hợp nhau cả về nghĩa lẫn lời nói’, thì các vị nên đến gặp vị Tỳ Kheo nào mà các vị cho là dễ nghe lời hơn, rồi nói với vị ấy như sau:",
  "mn103:8.3": "‘Các vị ấy thật ra hợp nhau cả về nghĩa lẫn lời nói.",
  "mn103:8.4": "Các vị hãy biết thêm điều này:",
  "mn103:8.5": "là họ hợp nhau cả về nghĩa lẫn lời nói.",
  "mn103:8.6": "Xin các vị đừng cãi nhau.’",
  "mn103:8.7": "Rồi đối với các Tỳ Kheo khác đứng về một phía, các vị nên đến gặp vị Tỳ Kheo nào mà các vị cho là dễ nghe lời hơn, rồi nói với vị ấy như sau:",
  "mn103:8.8": "‘Các vị ấy thật ra hợp nhau cả về nghĩa lẫn lời nói.",
  "mn103:8.9": "Các vị hãy biết thêm điều này:",
  "mn103:8.10": "là họ hợp nhau cả về nghĩa lẫn lời nói.",
  "mn103:8.11": "Xin các vị đừng cãi nhau.’",
  "mn103:8.12": "Như vậy, điều nắm đúng thì phải ghi nhớ là đã nắm đúng.",
  "mn103:8.13": "Sau khi ghi nhớ điều nắm đúng là đã nắm đúng, thì điều Đức Thế Tôn dạy và nếp sống tu học phải được nói ra.",
  "mn103:9.1": "Này các Tỳ Kheo, khi các vị sống hòa thuận, vui vẻ với nhau, không cãi nhau, đang học tập, nếu có một Tỳ Kheo nào đó phạm lỗi, vượt quá điều nên giữ,",
  "mn103:10.1": "thì này các Tỳ Kheo, không nên vội trách cứ. Phải xem xét người ấy:",
  "mn103:10.2": "‘Làm vậy thì cả ta sẽ không làm đau ai, và người kia cũng không bị tổn hại; vì người ấy không nóng giận, không ôm giận, không chấp chặt cái thấy của mình, dễ buông bỏ; và ta có thể kéo người ấy ra khỏi điều xấu, đặt vào điều lành.’",
  "mn103:10.3": "Này các Tỳ Kheo, nếu nghĩ như vậy, thì nói với người ấy là đúng lúc.",
  "mn103:11.1": "Nhưng này các Tỳ Kheo, nếu nghĩ rằng:",
  "mn103:11.2": "‘Ta thì sẽ không làm đau ai, nhưng người kia sẽ bị tổn hại; vì người ấy nóng giận, ôm giận, không chấp chặt cái thấy của mình, dễ buông bỏ; và ta có thể kéo người ấy ra khỏi điều xấu, đặt vào điều lành.",
  "mn103:11.3": "Nhưng sự tổn hại cho người kia ấy chỉ là chuyện nhỏ.",
  "mn103:11.4": "Còn điều này mới lớn hơn nhiều:",
  "mn103:11.5": "ta có thể kéo người ấy ra khỏi điều xấu, đặt vào điều lành.’",
  "mn103:11.6": "Này các Tỳ Kheo, nếu nghĩ như vậy, thì nói với người ấy là đúng lúc.",
  "mn103:12.1": "Nhưng này các Tỳ Kheo, nếu nghĩ rằng:",
  "mn103:12.2": "‘Ta sẽ bị phiền, nhưng người kia không bị hại. Vì người ấy không giận, không ôm lòng hờn, bám chặt vào cái thấy của mình, khó buông ra. Và ta có thể kéo người ấy ra khỏi điều xấu, đặt vào điều lành.",
  "mn103:12.3": "Nhưng việc này, tức là ta bị phiền, chỉ là chút ít.",
  "mn103:12.4": "Còn điều lớn hơn chính là:",
  "mn103:12.5": "ta có thể kéo người ấy ra khỏi điều xấu, đặt vào điều lành.’",
  "mn103:12.6": "Này các Tỳ Kheo, nếu nghĩ như vậy thì nên lên tiếng.",
  "mn103:13.1": "Nhưng này các Tỳ Kheo, nếu nghĩ như vầy:",
  "mn103:13.2": "‘Ta sẽ bị phiền, và người kia cũng sẽ bị hại. Vì người ấy hay giận, hay ôm lòng hờn, bám chặt vào cái thấy của mình, khó buông ra. Nhưng ta có thể kéo người ấy ra khỏi điều xấu, đặt vào điều lành.",
  "mn103:13.3": "Nhưng việc này, tức là ta bị phiền và người kia bị hại, chỉ là chút ít.",
  "mn103:13.4": "Còn điều lớn hơn chính là:",
  "mn103:13.5": "ta có thể kéo người ấy ra khỏi điều xấu, đặt vào điều lành.’",
  "mn103:13.6": "Này các Tỳ Kheo, nếu nghĩ như vậy thì nên lên tiếng.",
  "mn103:14.1": "Nhưng này các Tỳ Kheo, nếu nghĩ như vầy:",
  "mn103:14.2": "‘Ta sẽ bị phiền, và người kia cũng sẽ bị hại. Vì người ấy hay giận, hay ôm lòng hờn, bám chặt vào cái thấy của mình, khó buông ra. Và ta không thể kéo người ấy ra khỏi điều xấu, đặt vào điều lành.’",
  "mn103:14.3": "Này các Tỳ Kheo, với hạng người như vậy thì nên để yên, giữ tâm bình thản, chứ không được khinh thường.",
  "mn103:15.1": "Này các Tỳ Kheo, khi các thầy sống hòa hợp, vui vẻ với nhau, không cãi nhau, cùng học theo đường tu, nếu giữa nhau có lời qua tiếng lại, có sự va chạm vì cái thấy, có bực bội trong lòng, không vừa ý, không vui lòng,",
  "mn103:15.2": "thì trong mỗi bên, các thầy nên chọn vị Tỳ Kheo nào dễ nghe lời hơn, rồi đến nói với vị ấy như vầy:",
  "mn103:15.3": "‘Này hiền giả, giữa chúng ta là những người đang sống hòa hợp, vui vẻ với nhau, không cãi nhau, cùng học theo đường tu, nay đã nổi lên lời qua tiếng lại, sự va chạm vì cái thấy, bực bội trong lòng, không vừa ý, không vui lòng. Biết như vậy, người sống đời tu sẽ chê trách.’",
  "mn103:15.4": "Này các Tỳ Kheo, nếu trả lời đúng thì vị Tỳ Kheo ấy nên trả lời như vầy:",
  "mn103:15.5": "‘Này hiền giả, giữa chúng ta là những người đang sống hòa hợp, vui vẻ với nhau, không cãi nhau, cùng học theo đường tu, nay đã nổi lên lời qua tiếng lại, sự va chạm vì cái thấy, bực bội trong lòng, không vừa ý, không vui lòng. Biết như vậy, người sống đời tu sẽ chê trách.",
  "mn103:15.6": "Này hiền giả, nếu không bỏ điều này thì không thể tự mình thấy được sự tắt hẳn.’",
  "mn103:15.7": "Này các Tỳ Kheo, nếu trả lời đúng thì vị Tỳ Kheo ấy nên trả lời như vầy:",
  "mn103:15.8": "‘Này hiền giả, nếu không bỏ điều này thì không thể tự mình thấy được sự tắt hẳn.’",
  "mn103:16.1": "Rồi với bên kia cũng vậy, trong mỗi bên các thầy nên chọn vị Tỳ Kheo nào dễ nghe lời hơn, rồi đến nói với vị ấy như vầy:",
  "mn103:16.2": "‘Này hiền giả, giữa chúng ta là những người đang sống hòa hợp, vui vẻ với nhau, không cãi nhau, cùng học theo đường tu, nay đã nổi lên lời qua tiếng lại, sự va chạm vì cái thấy, bực bội trong lòng, không vừa ý, không vui lòng. Biết như vậy, người sống đời tu sẽ chê trách.’",
  "mn103:16.3": "Này các Tỳ Kheo, nếu trả lời đúng thì vị Tỳ Kheo ấy nên trả lời như vầy:",
  "mn103:16.4": "‘Này hiền giả, giữa chúng ta là những người đang sống hòa hợp, vui vẻ với nhau, không cãi nhau, cùng học theo đường tu, nay đã nổi lên lời qua tiếng lại, sự va chạm vì cái thấy, bực bội trong lòng, không vừa ý, không vui lòng. Biết như vậy, người sống đời tu sẽ chê trách.",
  "mn103:16.5": "Này hiền giả, nếu không bỏ điều này thì không thể tự mình thấy được sự tắt hẳn.’",
  "mn103:16.6": "Này các Tỳ Kheo, nếu trả lời đúng thì vị Tỳ Kheo ấy nên trả lời như vầy:",
  "mn103:16.7": "‘Này hiền giả, nếu không bỏ điều này thì không thể tự mình thấy được sự tắt hẳn.’",
  "mn103:17.1": "Này các Tỳ Kheo, nếu rồi người khác hỏi vị Tỳ Kheo ấy như vầy:",
  "mn103:17.2": "‘Có phải nhờ vị Tỳ Kheo đáng kính này mà các Tỳ Kheo ấy đã rời điều xấu và đứng vững trong điều lành không?’",
  "mn103:17.3": "Này các Tỳ Kheo, khi trả lời đúng, một Tỳ Kheo nên trả lời như vầy:",
  "mn103:17.4": "‘Này các bạn, ở đây tôi đã đi đến chỗ Đức Thế Tôn. Đức Thế Tôn đã chỉ dạy cho tôi lẽ phải. Sau khi nghe lẽ phải ấy, tôi đã nói lại cho các Tỳ Kheo ấy.",
  "mn103:17.5": "Khi nghe lẽ phải ấy, các Tỳ Kheo ấy đã rời điều xấu và đứng vững trong điều lành.’",
  "mn103:17.6": "Này các Tỳ Kheo, khi trả lời như vậy, vị Tỳ Kheo ấy không tự nâng mình lên, cũng không chê người khác, lại còn trả lời thuận với lẽ phải, và không khiến một người cùng sống theo lẽ phải nào có cớ để chê trách trong chuyện tranh cãi qua lại.”",
  "mn103:17.7": "Đức Thế Tôn nói như vậy.",
  "mn103:17.8": "Các Tỳ Kheo ấy vui mừng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn103:17.9": "Kinh Kinti thứ ba đã xong."
}
window.BILARA["mn103"]["vi"]["mn103:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
