window.BILARA = window.BILARA || {};
window.BILARA["mn106"] = window.BILARA["mn106"] || {};
window.BILARA["mn106"]["vi"] = {
  "mn106:0.1": "Trung Bộ Kinh 106",
  "mn106:0.2": "Kinh Con Đường Thích Hợp Để Đạt Tới Cảnh Giới Không Lay Động",
  "mn106:1.1": "Tôi nghe như vầy—",
  "mn106:1.2": "Một thời, Đức Thế Tôn ở xứ Kuru, tại một làng của dân Kuru tên là Kammāsadamma.",
  "mn106:1.3": "Tại đó, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn106:1.4": "“Này các Tỳ Kheo.”",
  "mn106:1.5": "Các Tỳ Kheo ấy thưa với Đức Thế Tôn: “Dạ, bạch Ngài.”",
  "mn106:1.6": "Đức Thế Tôn nói như sau:",
  "mn106:2.1": "“Này các Tỳ Kheo, các thú vui giác quan là đổi thay, rỗng không, giả dối, có tính lừa gạt.",
  "mn106:2.2": "Này các Tỳ Kheo, đó chỉ là trò gạt bày ra, là lời nói của kẻ dại.",
  "mn106:2.3": "Những thú vui giác quan trong đời này, và những thú vui giác quan ở đời sau;",
  "mn106:2.4": "những ý nghĩ về thú vui giác quan trong đời này, và những ý nghĩ về thú vui giác quan ở đời sau—",
  "mn106:2.5": "cả hai thứ ấy đều thuộc phần của Ma Vương, là vùng của Ma Vương, là mồi của Ma Vương, là chỗ kiếm ăn của Ma Vương.",
  "mn106:2.6": "Chính tại đó mà lòng ham muốn, sự ghét bỏ, và sự chống đối, là những điều xấu ác, không lành trong tâm, sinh khởi.",
  "mn106:2.7": "Chính những điều ấy trở thành chướng ngại cho người học trò bậc thánh đang rèn luyện ở đây.",
  "mn106:3.1": "Ở đây, này các Tỳ Kheo, người học trò bậc thánh suy xét như sau:",
  "mn106:3.2": "‘Những thú vui giác quan trong đời này, và những thú vui giác quan ở đời sau;",
  "mn106:3.3": "những ý nghĩ về thú vui giác quan trong đời này, và những ý nghĩ về thú vui giác quan ở đời sau—",
  "mn106:3.4": "cả hai thứ ấy đều thuộc phần của Ma Vương, là vùng của Ma Vương, là mồi của Ma Vương, là chỗ kiếm ăn của Ma Vương.",
  "mn106:3.5": "Chính tại đó mà lòng ham muốn, sự ghét bỏ, và sự chống đối, là những điều xấu ác, không lành trong tâm, sinh khởi,",
  "mn106:3.6": "chính những điều ấy trở thành chướng ngại cho người học trò bậc thánh đang rèn luyện ở đây.",
  "mn106:3.7": "Hay là ta sống với một tấm lòng rộng lớn, cao vượt, thắng qua đời, rồi đặt tâm vững trên đó.",
  "mn106:3.8": "Vì khi ta sống với một tấm lòng rộng lớn, cao vượt, thắng qua đời, rồi đặt tâm vững trên đó, thì những điều xấu ác, không lành trong tâm như lòng ham muốn, sự ghét bỏ, và sự chống đối sẽ không còn.",
  "mn106:3.9": "Khi chúng được dứt bỏ, tâm ta sẽ không còn nhỏ hẹp, mà thành rộng lớn, được khéo rèn luyện.’",
  "mn106:3.10": "Người ấy sống như vậy, thường ở trong trạng thái ấy, thì tâm hướng về cảnh giới đó trở nên trong sáng.",
  "mn106:3.11": "Khi tâm đã trong sáng, thì ngay trong hiện tại hoặc người ấy đạt tới cảnh giới không lay động, hoặc nhờ sự hiểu rõ mà nghiêng hẳn về đó.",
  "mn106:3.12": "Khi thân tan rã, sau khi chết, có thể xảy ra việc dòng biết của người ấy đi tới cảnh giới không lay động.",
  "mn106:3.13": "Này các Tỳ Kheo, đây được gọi là con đường thực hành thứ nhất thích hợp để đạt tới cảnh giới không lay động.",
  "mn106:4.1": "Lại nữa, này các Tỳ Kheo, người học trò bậc thánh suy xét như sau:",
  "mn106:4.2": "‘Những thú vui giác quan trong đời này, và những thú vui giác quan ở đời sau;",
  "mn106:4.3": "và cái thấy ghi nhận về dục ở đời này, và cái thấy ghi nhận về dục ở đời sau;",
  "mn106:4.4": "bất cứ sắc nào, mọi sắc, cùng bốn thứ lớn, và sắc nương vào bốn thứ lớn ấy.",
  "mn106:4.5": "Vị ấy sống như vậy, thường ở nhiều với điều ấy, thì lòng hướng về cảnh ấy trở nên trong sáng.",
  "mn106:4.6": "Khi lòng đã trong sáng, thì ngay bây giờ hoặc vị ấy vào cảnh không lay động, hoặc nhờ hiểu rõ mà nghiêng hẳn về đó.",
  "mn106:4.7": "Khi thân tan rã, sau khi chết, có thể có trường hợp sự nhận biết dẫn theo hướng ấy sẽ đi đến cảnh không lay động.",
  "mn106:4.8": "Này các Tỳ Kheo, đây được gọi là cách thực hành thứ hai thích hợp để đi đến cảnh không lay động.",
  "mn106:5.1": "Lại nữa, này các Tỳ Kheo, người nghe theo bậc thánh suy xét như vầy:",
  "mn106:5.2": "‘Những dục ở đời này, và những dục ở đời sau;",
  "mn106:5.3": "những cái thấy ghi nhận về dục ở đời này, và những cái thấy ghi nhận về dục ở đời sau;",
  "mn106:5.4": "những sắc ở đời này, và những sắc ở đời sau;",
  "mn106:5.5": "những cái thấy ghi nhận về sắc ở đời này, và những cái thấy ghi nhận về sắc ở đời sau—",
  "mn106:5.6": "cả hai thứ ấy đều không bền.",
  "mn106:5.7": "Cái gì không bền thì không đáng để vui thích, không đáng để ca ngợi, không đáng để nắm chặt.’",
  "mn106:5.8": "Vị ấy sống như vậy, thường ở nhiều với điều ấy, thì lòng hướng về cảnh ấy trở nên trong sáng.",
  "mn106:5.9": "Khi lòng đã trong sáng, thì ngay bây giờ hoặc vị ấy vào cảnh không lay động, hoặc nhờ hiểu rõ mà nghiêng hẳn về đó.",
  "mn106:5.10": "Khi thân tan rã, sau khi chết, có thể có trường hợp sự nhận biết dẫn theo hướng ấy sẽ đi đến cảnh không lay động.",
  "mn106:5.11": "Này các Tỳ Kheo, đây được gọi là cách thực hành thứ ba thích hợp để đi đến cảnh không lay động.",
  "mn106:6.1": "Lại nữa, này các Tỳ Kheo, người nghe theo bậc thánh suy xét như vầy:",
  "mn106:6.2": "‘Những dục ở đời này, và những dục ở đời sau;",
  "mn106:6.3": "những cái thấy ghi nhận về dục ở đời này, và những cái thấy ghi nhận về dục ở đời sau;",
  "mn106:6.4": "những sắc ở đời này, và những sắc ở đời sau;",
  "mn106:6.5": "những cái thấy ghi nhận về sắc ở đời này, và những cái thấy ghi nhận về sắc ở đời sau;",
  "mn106:6.6": "và cái thấy ghi nhận về không lay động—",
  "mn106:6.7": "tất cả những cái thấy ghi nhận ấy.",
  "mn106:6.8": "Nơi nào tất cả những cái thấy ghi nhận ấy lặng dứt không còn sót lại, đó là yên ổn, đó là cao đẹp—",
  "mn106:6.9": "tức là cảnh không có gì cả.’",
  "mn106:6.10": "Vị ấy sống như vậy, thường ở nhiều với điều ấy, thì lòng hướng về cảnh ấy trở nên trong sáng.",
  "mn106:6.11": "Khi lòng đã trong sáng, thì ngay bây giờ hoặc vị ấy vào cảnh không có gì cả, hoặc nhờ hiểu rõ mà nghiêng hẳn về đó.",
  "mn106:6.12": "Khi thân tan rã, sau khi chết, có thể có trường hợp sự nhận biết dẫn theo hướng ấy sẽ đi đến cảnh không có gì cả.",
  "mn106:6.13": "Này các Tỳ Kheo, đây được gọi là cách thực hành thứ nhất thích hợp để đi đến cảnh không có gì cả.",
  "mn106:7.1": "Rồi nữa, này các Tỳ Kheo, người đệ tử bậc thánh đi vào rừng, hay đến dưới gốc cây, hay vào chỗ vắng, rồi suy xét như vầy:",
  "mn106:7.2": "‘Chỗ này trống không có cái ta, cũng không có cái gì thuộc về ta.’",
  "mn106:7.3": "Với người sống như vậy, thường ở như vậy, lòng hướng đến cảnh ấy thì trở nên trong sáng, tin chắc.",
  "mn106:7.4": "Khi lòng đã trong sáng, tin chắc, thì ngay trong hiện tại hoặc là vị ấy vào cảnh không có gì cả, hoặc là nhờ hiểu rõ mà nghiêng hẳn về đó.",
  "mn106:7.5": "Khi thân tan rã, sau khi chết, có thể có trường hợp dòng nhận biết dẫn đi theo đó sẽ đi đến cảnh không có gì cả.",
  "mn106:7.6": "Này các Tỳ Kheo, đây được gọi là cách đi thứ hai thích hợp để vào cảnh không có gì cả.",
  "mn106:8.1": "Rồi nữa, này các Tỳ Kheo, người đệ tử bậc thánh suy xét như vầy:",
  "mn106:8.2": "‘Ta không là cái gì của bất cứ nơi nào, của bất cứ ai; và ở bất cứ nơi nào, trong bất cứ thứ gì, cũng không có gì là của ta.’",
  "mn106:8.3": "Với người sống như vậy, thường ở như vậy, lòng hướng đến cảnh ấy thì trở nên trong sáng, tin chắc.",
  "mn106:8.4": "Khi lòng đã trong sáng, tin chắc, thì ngay trong hiện tại hoặc là vị ấy vào cảnh không có gì cả, hoặc là nhờ hiểu rõ mà nghiêng hẳn về đó.",
  "mn106:8.5": "Khi thân tan rã, sau khi chết, có thể có trường hợp dòng nhận biết dẫn đi theo đó sẽ đi đến cảnh không có gì cả.",
  "mn106:8.6": "Này các Tỳ Kheo, đây được gọi là cách đi thứ ba thích hợp để vào cảnh không có gì cả.",
  "mn106:9.1": "Rồi nữa, này các Tỳ Kheo, người đệ tử bậc thánh suy xét như vầy:",
  "mn106:9.2": "‘Những ham muốn thuộc đời này, và những ham muốn thuộc đời sau;",
  "mn106:9.3": "những ghi nhận về ham muốn thuộc đời này, và những ghi nhận về ham muốn thuộc đời sau;",
  "mn106:9.4": "những hình sắc thuộc đời này, và những hình sắc thuộc đời sau;",
  "mn106:9.5": "những ghi nhận về hình sắc thuộc đời này, và những ghi nhận về hình sắc thuộc đời sau;",
  "mn106:9.6": "những ghi nhận về cảnh bất động, và những ghi nhận về cảnh không có gì cả—",
  "mn106:9.7": "tất cả đều là ghi nhận.",
  "mn106:9.8": "Nơi nào tất cả những thứ ấy lặng dứt không còn sót lại, đó là yên ổn, đó là cao quý—",
  "mn106:9.9": "tức là cảnh không phải còn ghi nhận mà cũng không phải không còn ghi nhận.’",
  "mn106:9.10": "Với người sống như vậy, thường ở như vậy, lòng hướng đến cảnh ấy thì trở nên trong sáng, tin chắc.",
  "mn106:9.11": "Khi lòng đã trong sáng, tin chắc, thì ngay trong hiện tại hoặc là vị ấy vào cảnh không phải còn ghi nhận mà cũng không phải không còn ghi nhận, hoặc là nhờ hiểu rõ mà nghiêng hẳn về đó.",
  "mn106:9.12": "Khi thân tan rã, sau khi chết, có thể có trường hợp dòng nhận biết dẫn đi theo đó sẽ đi đến cảnh không phải còn ghi nhận mà cũng không phải không còn ghi nhận.",
  "mn106:9.13": "Này các Tỳ Kheo, đây được gọi là cách đi thích hợp để vào cảnh không phải còn ghi nhận mà cũng không phải không còn ghi nhận.”",
  "mn106:10.1": "Khi được nói vậy, ngài A Nan thưa với Đức Thế Tôn như vầy:",
  "mn106:10.2": "“Bạch Thế Tôn, ở đây một Tỳ Kheo sống như vầy:",
  "mn106:10.3": "‘Nó không là của vị ấy, nó cũng không là của ta; nó sẽ không có, nó sẽ không là của ta; cái gì đang có, đã thành ra rồi—ta buông bỏ cái đó.’",
  "mn106:10.4": "Vị ấy đạt được sự nhìn bằng lòng bình thản như vậy.",
  "mn106:10.5": "Bạch Thế Tôn, vị Tỳ Kheo ấy có thể tắt hẳn không còn gì nữa chăng, hay là không thể tắt hẳn không còn gì nữa?”",
  "mn106:10.6": "“Này A-nan, có Tỳ Kheo ở đây được tắt hẳn, có Tỳ Kheo ở đây không được tắt hẳn.”",
  "mn106:10.7": "“Bạch Đức Thế Tôn, do đâu, vì sao có Tỳ Kheo ở đây được tắt hẳn, có Tỳ Kheo ở đây không được tắt hẳn?”",
  "mn106:10.8": "“Này A-nan, ở đây một Tỳ Kheo sống như vầy:",
  "mn106:10.9": "‘Cái ấy không có; cái ấy không thuộc về tôi. Cái ấy sẽ không có; cái ấy sẽ không thuộc về tôi. Cái gì đang có, cái gì đã thành, tôi buông nó đi.’",
  "mn106:10.10": "Vị ấy nhờ vậy đạt được sự giữ tâm bình thản.",
  "mn106:10.11": "Vị ấy ưa thích sự giữ tâm bình thản ấy, khen ngợi nó, bám chặt vào đó.",
  "mn106:10.12": "Khi vị ấy ưa thích, khen ngợi, bám chặt vào sự giữ tâm bình thản ấy, thì sự nhận biết của vị ấy nương vào đó, nắm lấy đó.",
  "mn106:10.13": "Này A-nan, Tỳ Kheo còn nắm giữ thì không được tắt hẳn.”",
  "mn106:11.1": "“Nhưng bạch Đức Thế Tôn, vị Tỳ Kheo ấy khi đang nắm giữ thì nắm giữ ở đâu?”",
  "mn106:11.2": "“Này A-nan, là cảnh không có tưởng rõ mà cũng không phải không có tưởng.”",
  "mn106:11.3": "“Bạch Đức Thế Tôn, có phải vị Tỳ Kheo ấy khi đang nắm giữ là nắm giữ chỗ cao nhất của sự nắm giữ không?”",
  "mn106:11.4": "“Đúng vậy, này A-nan, vị Tỳ Kheo ấy khi đang nắm giữ là nắm giữ chỗ cao nhất của sự nắm giữ.",
  "mn106:11.5": "Này A-nan, đây chính là chỗ cao nhất của sự nắm giữ, đó là—",
  "mn106:11.6": "cảnh không có tưởng rõ mà cũng không phải không có tưởng.",
  "mn106:12.1": "Này A-nan, ở đây một Tỳ Kheo sống như vầy:",
  "mn106:12.2": "‘Cái ấy không có; cái ấy không thuộc về tôi. Cái ấy sẽ không có; cái ấy sẽ không thuộc về tôi. Cái gì đang có, cái gì đã thành, tôi buông nó đi.’",
  "mn106:12.3": "Vị ấy nhờ vậy đạt được sự giữ tâm bình thản.",
  "mn106:12.4": "Vị ấy không ưa thích sự giữ tâm bình thản ấy, không khen ngợi nó, không bám chặt vào đó.",
  "mn106:12.5": "Khi vị ấy không ưa thích, không khen ngợi, không bám chặt vào sự giữ tâm bình thản ấy, thì sự nhận biết của vị ấy không nương vào đó, không nắm lấy đó.",
  "mn106:12.6": "Này A-nan, Tỳ Kheo không còn nắm giữ thì được tắt hẳn.”",
  "mn106:13.1": "“Thật lạ thay, bạch Đức Thế Tôn, thật chưa từng có, bạch Đức Thế Tôn.",
  "mn106:13.2": "Bạch Đức Thế Tôn, nhờ nương cái này rồi buông cái này, Đức Thế Tôn đã chỉ dạy cách vượt khỏi dòng cuốn trôi cho chúng con.",
  "mn106:13.3": "Nhưng bạch Đức Thế Tôn, sự mở ra cao quý là gì?”",
  "mn106:13.4": "“Này A-nan, ở đây người học trò cao quý suy xét như vầy:",
  "mn106:13.5": "‘Những ham muốn trong đời này, những ham muốn ở đời sau;",
  "mn106:13.6": "những ghi nhận về ham muốn trong đời này, những ghi nhận về ham muốn ở đời sau;",
  "mn106:13.7": "những hình sắc trong đời này, những hình sắc ở đời sau;",
  "mn106:13.8": "những ghi nhận về hình sắc trong đời này, những ghi nhận về hình sắc ở đời sau;",
  "mn106:13.9": "những ghi nhận về cảnh bất động, những ghi nhận về cảnh không có gì, những ghi nhận về cảnh không có tưởng rõ mà cũng không phải không có tưởng—",
  "mn106:13.10": "tất cả những thứ ấy đều là thân này, trong chừng mực còn gọi là thân này.",
  "mn106:13.11": "Đó là chỗ không chết, tức là tâm được buông ra vì không còn nắm giữ.",
  "mn106:14.1": "Này Ānanda, như vậy, Ta đã chỉ bày con đường thích hợp để đạt tới cảnh giới không lay động, đã chỉ bày con đường thích hợp để đạt tới cảnh giới không có gì, đã chỉ bày con đường thích hợp để đạt tới cảnh giới không còn nhận ra mà cũng không phải không nhận ra, đã chỉ bày cách nương vào từng bước để vượt qua dòng cuốn trôi, đã chỉ bày sự giải thoát cao quý.",
  "mn106:15.1": "Này Ānanda, điều gì một bậc thầy cần làm cho hàng đệ tử, vì muốn điều lành cho họ, vì thương tưởng họ, thì Ta đã làm cho các ông rồi.",
  "mn106:15.2": "Này Ānanda, đây là gốc cây, đây là những căn nhà trống. Hãy ngồi lặng mà soi xét, này Ānanda, chớ buông lung, chớ để về sau phải hối tiếc. Đó là lời dạy của Ta cho các ông.",
  "mn106:15.3": "Đức Thế Tôn nói như vậy.",
  "mn106:15.4": "Tôn giả Ānanda vui mừng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn106:15.5": "Kinh Con Đường Thích Hợp Để Đạt Tới Cảnh Giới Không Lay Động, bài thứ sáu, đến đây là hết."
}
window.BILARA["mn106"]["vi"]["mn106:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
