window.BILARA = window.BILARA || {};
window.BILARA["mn10"] = window.BILARA["mn10"] || {};
window.BILARA["mn10"]["vi"] = {
  "mn10:0.1": "Trung Bộ Kinh 10",
  "mn10:0.2": "Kinh Nền Tảng Của Sự Nhớ Biết Rõ",
  "mn10:1.1": "Tôi nghe như vầy—",
  "mn10:1.2": "Một thời, Đức Thế Tôn ở xứ Kuru, tại một thị trấn của người Kuru tên là Kammāsadamma.",
  "mn10:1.3": "Tại đó, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn10:1.4": "“Này các Tỳ Kheo.”",
  "mn10:1.5": "Các Tỳ Kheo ấy đáp lời Đức Thế Tôn: “Dạ, bạch Ngài.”",
  "mn10:1.6": "Đức Thế Tôn nói như sau:",
  "mn10:2.1": "“Này các Tỳ Kheo, đây là con đường duy nhất đưa chúng sinh đến chỗ trong sạch, vượt qua sầu than khóc lóc, chấm dứt khổ đau và buồn bã, đạt đến lối đi đúng, tự mình thấy ra niết-bàn, đó là bốn nền tảng của sự nhớ biết rõ.",
  "mn10:3.1": "Bốn điều ấy là gì?",
  "mn10:3.2": "Này các Tỳ Kheo, ở đây, một Tỳ Kheo sống quán thân trên thân, tha thiết, hiểu rõ, nhớ biết rõ, dẹp bỏ lòng ham muốn và buồn bã đối với đời;",
  "mn10:3.3": "sống quán cảm giác trên cảm giác, tha thiết, hiểu rõ, nhớ biết rõ, dẹp bỏ lòng ham muốn và buồn bã đối với đời;",
  "mn10:3.4": "sống quán tâm trên tâm, tha thiết, hiểu rõ, nhớ biết rõ, dẹp bỏ lòng ham muốn và buồn bã đối với đời;",
  "mn10:3.5": "sống quán các điều trên các điều, tha thiết, hiểu rõ, nhớ biết rõ, dẹp bỏ lòng ham muốn và buồn bã đối với đời.",
  "mn10:3.6": "Phần nêu gọn đã xong.",
  "mn10:4.0.1": "1. Quán thân",
  "mn10:4.0.2": "1.1. Phần quán thân về hơi thở vào ra",
  "mn10:4.1": "Và này các Tỳ Kheo, thế nào là một Tỳ Kheo sống quán thân trên thân?",
  "mn10:4.2": "Này các Tỳ Kheo, ở đây, một Tỳ Kheo đi vào rừng, hay đến gốc cây, hay vào một chỗ trống vắng, rồi ngồi xuống, xếp chân bằng tròn, giữ thân ngay thẳng, đặt sự nhớ biết rõ trước mặt.",
  "mn10:4.3": "Vị ấy nhớ biết rõ khi thở vào, nhớ biết rõ khi thở ra.",
  "mn10:4.4": "Khi thở vào dài, vị ấy biết rõ: “Tôi thở vào dài”; khi thở ra dài, vị ấy biết rõ: “Tôi thở ra dài”;",
  "mn10:4.5": "khi thở vào ngắn, vị ấy biết rõ: “Tôi thở vào ngắn”; khi thở ra ngắn, vị ấy biết rõ: “Tôi thở ra ngắn”.",
  "mn10:4.6": "Vị ấy tự rèn: “Tôi sẽ thở vào cảm nhận toàn thân”; vị ấy tự rèn: “Tôi sẽ thở ra cảm nhận toàn thân”.",
  "mn10:4.7": "Vị ấy tự rèn: “Tôi sẽ thở vào làm lắng yên hoạt động của thân”; vị ấy tự rèn: “Tôi sẽ thở ra làm lắng yên hoạt động của thân”.",
  "mn10:4.8": "Này các Tỳ Kheo, cũng như một người thợ tiện khéo, hay người học việc của thợ tiện, khi kéo dài thì biết rõ: “Tôi kéo dài”, khi kéo ngắn thì biết rõ: “Tôi kéo ngắn”;",
  "mn10:4.9": "cũng vậy, này các Tỳ Kheo, khi thở vào dài, vị Tỳ Kheo biết rõ: “Tôi thở vào dài”; khi thở ra dài, vị ấy biết rõ: “Tôi thở ra dài”; khi thở vào ngắn, vị ấy biết rõ: “Tôi thở vào ngắn”; khi thở ra ngắn, vị ấy biết rõ: “Tôi thở ra ngắn”;",
  "mn10:4.10": "vị ấy tự rèn: “Tôi sẽ thở vào cảm nhận toàn thân”; vị ấy tự rèn: “Tôi sẽ thở ra cảm nhận toàn thân”;",
  "mn10:4.11": "vị ấy tự rèn: “Tôi sẽ thở vào làm lắng yên hoạt động của thân”; vị ấy tự rèn: “Tôi sẽ thở ra làm lắng yên hoạt động của thân”.",
  "mn10:5.1": "Như vậy, vị ấy sống quán thân trên thân ở bên trong, hay sống quán thân trên thân ở bên ngoài, hay sống quán thân trên thân cả bên trong lẫn bên ngoài;",
  "mn10:5.2": "hay sống nhìn thân theo mặt sinh khởi, hay sống nhìn thân theo mặt tan đi, hay sống nhìn thân theo cả mặt sinh khởi và tan đi.",
  "mn10:5.3": "Hoặc nơi vị ấy, sự nhớ biết rõ hiện rõ rằng: ‘có thân này’. Chỉ đến mức biết mà thôi, chỉ đến mức nhớ biết rõ mà thôi. Vị ấy sống không nương tựa, không nắm giữ bất cứ gì ở đời.",
  "mn10:5.4": "Này các Tỳ Kheo, Tỳ Kheo sống như vậy, nhìn thân nơi thân.",
  "mn10:5.5": "Phần quán hơi thở vào ra đến đây là xong.",
  "mn10:6.0": "1.2. Phần quán thân trong các dáng đi đứng nằm ngồi",
  "mn10:6.1": "Lại nữa, này các Tỳ Kheo, khi đi, Tỳ Kheo biết rõ: ‘tôi đang đi’; khi đứng, biết rõ: ‘tôi đang đứng’; khi ngồi, biết rõ: ‘tôi đang ngồi’; khi nằm, biết rõ: ‘tôi đang nằm’.",
  "mn10:6.2": "Thân được đặt ở dáng nào, vị ấy biết rõ thân ở dáng ấy.",
  "mn10:7.1": "Như vậy, vị ấy sống nhìn thân nơi thân ở trong thân, hay sống nhìn thân nơi thân ở ngoài thân, hay sống nhìn thân nơi thân cả trong lẫn ngoài;",
  "mn10:7.2": "hay sống nhìn sự sinh khởi nơi thân, hay sống nhìn sự tan đi nơi thân, hay sống nhìn cả sự sinh khởi và sự tan đi nơi thân.",
  "mn10:7.3": "Hoặc nơi vị ấy, sự nhớ biết rõ hiện rõ rằng: ‘có thân này’. Chỉ đến mức biết mà thôi, chỉ đến mức nhớ biết rõ mà thôi. Vị ấy sống không nương tựa, không nắm giữ bất cứ gì ở đời.",
  "mn10:7.4": "Này các Tỳ Kheo, Tỳ Kheo sống như vậy, nhìn thân nơi thân.",
  "mn10:7.5": "Phần quán các dáng đi đứng nằm ngồi đến đây là xong.",
  "mn10:8.0": "1.3. Phần biết rõ trong mọi việc khi quán thân",
  "mn10:8.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo khi bước tới hay bước lui đều biết rõ; khi nhìn thẳng hay nhìn quanh đều biết rõ; khi co tay chân hay duỗi tay chân đều biết rõ; khi mang y, bưng bát, mặc áo đều biết rõ; khi ăn, uống, nhai, nếm đều biết rõ; khi đi đại tiện, tiểu tiện đều biết rõ; khi đi, đứng, ngồi, ngủ, thức, nói, im lặng đều biết rõ.",
  "mn10:9.1": "Như vậy, vị ấy sống nhìn thân nơi thân ở trong thân …",
  "mn10:9.2": "Này các Tỳ Kheo, Tỳ Kheo sống như vậy, nhìn thân nơi thân.",
  "mn10:9.3": "Phần biết rõ đến đây là xong.",
  "mn10:10.0": "1.4. Phần để tâm xem thân là không sạch",
  "mn10:10.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo xem xét chính thân này, từ bàn chân trở lên, từ đỉnh đầu trở xuống, được da bọc kín, đầy những thứ không sạch đủ loại:",
  "mn10:10.2": "‘trong thân này có tóc, lông, móng, răng, da, thịt, gân, xương, tủy xương, thận, tim, gan, màng ngăn, lá lách, phổi, ruột, màng ruột, đồ ăn trong bụng, phân, mật, đờm, mủ, máu, mồ hôi, mỡ, nước mắt, mỡ đặc, nước miếng, nước mũi, nước khớp, nước tiểu’.",
  "mn10:10.3": "Ví như, này các Tỳ Kheo, một cái bao có hai miệng, đầy nhiều thứ hạt khác nhau, như lúa, gạo, đậu xanh, đậu lớn, mè, gạo đã xay; một người mắt sáng mở bao ấy ra và xem: ‘đây là lúa, đây là gạo, đây là đậu xanh, đây là đậu lớn, đây là mè, đây là gạo đã xay’.",
  "mn10:10.4": "Cũng vậy, này các Tỳ Kheo, Tỳ Kheo xem xét chính thân này, từ bàn chân trở lên, từ đỉnh đầu trở xuống, được da bọc kín, đầy những thứ không sạch đủ loại:",
  "mn10:10.5": "‘trong thân này có tóc, lông … nước tiểu’.",
  "mn10:11.1": "Như vậy, vị ấy sống nhìn thân nơi thân ở trong thân …",
  "mn10:11.2": "Này các Tỳ Kheo, Tỳ Kheo sống như vậy, nhìn thân nơi thân.",
  "mn10:11.3": "Phần để tâm xem thân là không sạch đến đây là xong.",
  "mn10:12.0": "1.5. Phần để tâm xem thân theo các phần chất",
  "mn10:12.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo xem xét chính thân này theo đúng chỗ của nó, theo cách nó được đặt, bằng các phần chất:",
  "mn10:12.2": "‘trong thân này có phần đất, phần nước, phần lửa, phần gió’.",
  "mn10:12.3": "Ví như, này các Tỳ Kheo, một người mổ bò khéo tay, hay học trò của người mổ bò, giết một con bò rồi ngồi ở ngã tư lớn, xẻ nó ra thành từng phần.",
  "mn10:12.4": "Cũng vậy, này các Tỳ Kheo, Tỳ Kheo xem xét chính thân này theo đúng chỗ của nó, theo cách nó được đặt, bằng các phần chất:",
  "mn10:12.5": "‘Trong thân này có phần đất, phần nước, phần lửa, phần gió.’",
  "mn10:13.1": "Như vậy, vị ấy sống nhìn thân nơi thân ở bên trong …",
  "mn10:13.2": "Này các Tỳ Kheo, vị Tỳ Kheo sống nhìn thân nơi thân như vậy.",
  "mn10:13.3": "Phần để tâm vào các phần đã xong.",
  "mn10:14.0": "1.6. Phần nhìn thân qua bãi tha ma",
  "mn10:14.1": "Lại nữa, này các Tỳ Kheo, ví như một vị Tỳ Kheo thấy một xác chết bị quăng ở bãi tha ma, đã một ngày, hai ngày, hay ba ngày, đang trương lên, đổi màu xanh bầm, và rữa nát chảy mủ.",
  "mn10:14.2": "Vị ấy đem thân này mà so lại:",
  "mn10:14.3": "‘Thân này cũng có tính như vậy, sẽ thành ra như vậy, không vượt khỏi như vậy.’",
  "mn10:15.1": "Như vậy, vị ấy sống nhìn thân nơi thân ở bên trong …",
  "mn10:15.2": "Này các Tỳ Kheo, vị Tỳ Kheo sống nhìn thân nơi thân như vậy.",
  "mn10:16.1": "Lại nữa, này các Tỳ Kheo, ví như một vị Tỳ Kheo thấy một xác chết bị quăng ở bãi tha ma, bị quạ rỉa, bị diều hâu rỉa, bị kên kên rỉa, bị chó rừng rỉa, bị chó nhà rỉa, bị cọp rỉa, bị beo rỉa, bị chồn rỉa, hay bị nhiều loài vật nhỏ rỉa ăn.",
  "mn10:16.2": "Vị ấy đem thân này mà so lại:",
  "mn10:16.3": "‘Thân này cũng có tính như vậy, sẽ thành ra như vậy, không vượt khỏi như vậy.’",
  "mn10:17.1": "Như vậy, vị ấy sống nhìn thân nơi thân ở bên trong …",
  "mn10:17.2": "Này các Tỳ Kheo, vị Tỳ Kheo sống nhìn thân nơi thân như vậy.",
  "mn10:18-23.1": "Lại nữa, này các Tỳ Kheo, ví như một vị Tỳ Kheo thấy một xác chết bị quăng ở bãi tha ma, chỉ còn bộ xương còn dính thịt và máu, được gân nối lại …",
  "mn10:18-23.2": "Bộ xương không còn thịt, còn dính máu, được gân nối lại …",
  "mn10:18-23.3": "Bộ xương không còn thịt không còn máu, được gân nối lại …",
  "mn10:24.1": "Các khúc xương rời nhau, văng tản mác khắp các hướng: chỗ này xương bàn tay, chỗ kia xương bàn chân, chỗ kia xương mắt cá, chỗ kia xương ống chân, chỗ kia xương đùi, chỗ kia xương hông, chỗ kia xương sườn, chỗ kia xương sống, chỗ kia xương vai, chỗ kia xương cổ, chỗ kia xương hàm, chỗ kia xương răng, chỗ kia sọ đầu.",
  "mn10:24.2": "Vị ấy đem thân này mà so lại:",
  "mn10:24.3": "‘Thân này cũng có tính như vậy, sẽ thành ra như vậy, không vượt khỏi như vậy.’",
  "mn10:25.1": "Như vậy, vị ấy sống nhìn thân nơi thân ở bên trong …",
  "mn10:25.2": "Này các Tỳ Kheo, vị Tỳ Kheo sống nhìn thân nơi thân như vậy.",
  "mn10:26-28.1": "Lại nữa, này các Tỳ Kheo, ví như một vị Tỳ Kheo thấy một xác chết bị quăng ở bãi tha ma, xương trắng như màu vỏ ốc …",
  "mn10:29.1": "Xương chất thành đống, đã hơn ba năm …",
  "mn10:30.1": "Xương mục nát, thành bột.",
  "mn10:30.2": "Vị ấy đem thân này mà so lại:",
  "mn10:30.3": "‘Thân này cũng có tính như vậy, sẽ thành ra như vậy, không vượt khỏi như vậy.’",
  "mn10:31.1": "Như vậy, vị ấy sống nhìn thân nơi thân ở bên trong, hay sống nhìn thân nơi thân ở bên ngoài, hay sống nhìn thân nơi thân cả bên trong lẫn bên ngoài;",
  "mn10:31.2": "hay sống nhìn tính sinh khởi nơi thân, hay sống nhìn tính tan hoại nơi thân, hay sống nhìn cả tính sinh khởi và tan hoại nơi thân.",
  "mn10:31.3": "Hoặc nơi vị ấy, sự nhớ biết rõ hiện rõ rằng: ‘có thân’. Chỉ vừa đủ để hiểu rõ, chỉ vừa đủ để nhớ biết rõ. Vị ấy sống không nương tựa, không nắm giữ gì ở đời.",
  "mn10:31.4": "Này các Tỳ Kheo, vị Tỳ Kheo sống như vậy, nhìn thân nơi thân.",
  "mn10:31.5": "Phần chín cách nhìn xác chết ở bãi tha ma đến đây là xong.",
  "mn10:31.6": "Mười bốn cách nhìn thân đến đây là xong.",
  "mn10:32.0": "2. Nhìn cảm giác",
  "mn10:32.1": "Này các Tỳ Kheo, thế nào là vị Tỳ Kheo sống nhìn cảm giác nơi các cảm giác?",
  "mn10:32.2": "Ở đây, này các Tỳ Kheo, khi cảm nhận cảm giác dễ chịu, vị Tỳ Kheo hiểu rõ: ‘Tôi đang cảm nhận cảm giác dễ chịu’.",
  "mn10:32.3": "Khi cảm nhận cảm giác đau đớn, vị ấy hiểu rõ: ‘Tôi đang cảm nhận cảm giác đau đớn’.",
  "mn10:32.4": "Khi cảm nhận cảm giác không đau đớn cũng không dễ chịu, vị ấy hiểu rõ: ‘Tôi đang cảm nhận cảm giác không đau đớn cũng không dễ chịu’.",
  "mn10:32.5": "Khi cảm nhận cảm giác dễ chịu còn dính với vật chất nuôi thích thú, vị ấy hiểu rõ: ‘Tôi đang cảm nhận cảm giác dễ chịu còn dính với vật chất nuôi thích thú’.",
  "mn10:32.6": "Khi cảm nhận cảm giác dễ chịu không dính với vật chất nuôi thích thú, vị ấy hiểu rõ: ‘Tôi đang cảm nhận cảm giác dễ chịu không dính với vật chất nuôi thích thú’.",
  "mn10:32.7": "Khi cảm nhận cảm giác đau đớn còn dính với vật chất nuôi thích thú, vị ấy hiểu rõ: ‘Tôi đang cảm nhận cảm giác đau đớn còn dính với vật chất nuôi thích thú’.",
  "mn10:32.8": "Khi cảm nhận cảm giác đau đớn không dính với vật chất nuôi thích thú, vị ấy hiểu rõ: ‘Tôi đang cảm nhận cảm giác đau đớn không dính với vật chất nuôi thích thú’.",
  "mn10:32.9": "Khi cảm nhận cảm giác không đau đớn cũng không dễ chịu còn dính với vật chất nuôi thích thú, vị ấy hiểu rõ: ‘Tôi đang cảm nhận cảm giác không đau đớn cũng không dễ chịu còn dính với vật chất nuôi thích thú’.",
  "mn10:32.10": "Khi cảm nhận cảm giác không đau đớn cũng không dễ chịu không dính với vật chất nuôi thích thú, vị ấy hiểu rõ: ‘Tôi đang cảm nhận cảm giác không đau đớn cũng không dễ chịu không dính với vật chất nuôi thích thú’.",
  "mn10:33.1": "Như vậy, vị ấy sống nhìn cảm giác nơi các cảm giác ở trong mình, hoặc sống nhìn cảm giác nơi các cảm giác ở ngoài mình, hoặc sống nhìn cảm giác nơi các cảm giác cả ở trong mình lẫn ở ngoài mình;",
  "mn10:33.2": "hoặc sống nhìn sự sinh khởi nơi các cảm giác, hoặc sống nhìn sự tan đi nơi các cảm giác, hoặc sống nhìn cả sự sinh khởi và sự tan đi nơi các cảm giác.",
  "mn10:33.3": "Hoặc nơi vị ấy, sự nhớ biết rõ hiện rõ rằng: ‘có cảm giác’. Chỉ vừa đủ để hiểu rõ, chỉ vừa đủ để nhớ biết rõ. Vị ấy sống không nương tựa, không nắm giữ gì ở đời.",
  "mn10:33.4": "Này các Tỳ Kheo, vị Tỳ Kheo sống như vậy, nhìn cảm giác nơi các cảm giác.",
  "mn10:33.5": "Phần nhìn cảm giác đến đây là xong.",
  "mn10:34.0": "3. Nhìn tâm",
  "mn10:34.1": "Này các Tỳ Kheo, thế nào là vị Tỳ Kheo sống nhìn tâm nơi tâm?",
  "mn10:34.2": "Ở đây, này các Tỳ Kheo, khi tâm còn ham muốn, vị Tỳ Kheo hiểu rõ: ‘Tâm còn ham muốn’.",
  "mn10:34.3": "Khi tâm đã lìa ham muốn, vị ấy hiểu rõ: ‘Tâm đã lìa ham muốn’.",
  "mn10:34.4": "Khi tâm còn bực bội ghét bỏ, vị ấy hiểu rõ: ‘Tâm còn bực bội ghét bỏ’.",
  "mn10:34.5": "Khi tâm đã lìa bực bội ghét bỏ, vị ấy hiểu rõ: ‘Tâm đã lìa bực bội ghét bỏ’.",
  "mn10:34.6": "Khi tâm còn mờ mịt không thấy rõ, vị ấy hiểu rõ: ‘Tâm còn mờ mịt không thấy rõ’.",
  "mn10:34.7": "Khi tâm đã lìa mờ mịt không thấy rõ, vị ấy hiểu rõ: ‘Tâm đã lìa mờ mịt không thấy rõ’.",
  "mn10:34.8": "Khi tâm co rút, vị ấy hiểu rõ: ‘Tâm co rút’.",
  "mn10:34.9": "Khi tâm tán loạn, vị ấy hiểu rõ: ‘Tâm tán loạn’.",
  "mn10:34.10": "Vị ấy biết rõ: “Tâm rộng lớn.”",
  "mn10:34.11": "Vị ấy biết rõ: “Tâm không rộng lớn.”",
  "mn10:34.12": "Vị ấy biết rõ: “Tâm còn có gì cao hơn.”",
  "mn10:34.13": "Vị ấy biết rõ: “Tâm không có gì cao hơn.”",
  "mn10:34.14": "Vị ấy biết rõ: “Tâm yên vững.”",
  "mn10:34.15": "Vị ấy biết rõ: “Tâm không yên vững.”",
  "mn10:34.16": "Vị ấy biết rõ: “Tâm đã được buông mở.”",
  "mn10:34.17": "Vị ấy biết rõ: “Tâm chưa được buông mở.”",
  "mn10:35.1": "Như vậy, vị ấy sống nhìn tâm nơi tâm ở trong mình, hay sống nhìn tâm nơi tâm ở ngoài, hay sống nhìn tâm nơi tâm cả ở trong mình lẫn ở ngoài.",
  "mn10:35.2": "Vị ấy sống nhìn sự sinh lên trong tâm, hay sống nhìn sự tan đi trong tâm, hay sống nhìn cả sự sinh lên và tan đi trong tâm.",
  "mn10:35.3": "Hoặc sự nhớ biết rõ nơi vị ấy được đặt vững rằng: “Có tâm đây.” Chỉ đến mức đủ để thấy rõ, đủ để nhớ biết rõ, vị ấy sống không nương tựa, không nắm giữ gì ở đời.",
  "mn10:35.4": "Này các Tỳ Kheo, vị Tỳ Kheo sống nhìn tâm nơi tâm là như vậy.",
  "mn10:35.5": "Phần nhìn tâm đã xong.",
  "mn10:36.0.1": "4. Nhìn các việc",
  "mn10:36.0.2": "4.1. Phần nhìn năm thứ che lấp",
  "mn10:36.1": "Này các Tỳ Kheo, thế nào là vị Tỳ Kheo sống nhìn các việc nơi các việc?",
  "mn10:36.2": "Ở đây, này các Tỳ Kheo, vị Tỳ Kheo sống nhìn các việc nơi các việc trong năm thứ che lấp.",
  "mn10:36.3": "Nhưng này các Tỳ Kheo, thế nào là vị Tỳ Kheo sống nhìn các việc nơi các việc trong năm thứ che lấp?",
  "mn10:36.4": "Ở đây, này các Tỳ Kheo, khi trong mình có lòng ham muốn dục lạc, vị ấy biết rõ: “Trong tôi có lòng ham muốn dục lạc”; khi trong mình không có lòng ham muốn dục lạc, vị ấy biết rõ: “Trong tôi không có lòng ham muốn dục lạc.” Vị ấy cũng biết rõ cách lòng ham muốn dục lạc chưa sinh nay sinh lên; biết rõ cách lòng ham muốn dục lạc đã sinh được buông bỏ; và biết rõ cách lòng ham muốn dục lạc đã được buông bỏ sẽ không sinh lên nữa về sau.",
  "mn10:36.5": "Khi trong mình có lòng ghét bực, vị ấy biết rõ: “Trong tôi có lòng ghét bực”; khi trong mình không có lòng ghét bực, vị ấy biết rõ: “Trong tôi không có lòng ghét bực.” Vị ấy cũng biết rõ cách lòng ghét bực chưa sinh nay sinh lên; biết rõ cách lòng ghét bực đã sinh được buông bỏ; và biết rõ cách lòng ghét bực đã được buông bỏ sẽ không sinh lên nữa về sau.",
  "mn10:36.6": "Khi trong mình có sự lười nhác buồn ngủ, vị ấy biết rõ: “Trong tôi có sự lười nhác buồn ngủ”; khi trong mình không có sự lười nhác buồn ngủ, vị ấy biết rõ: “Trong tôi không có sự lười nhác buồn ngủ.” Vị ấy cũng biết rõ cách sự lười nhác buồn ngủ chưa sinh nay sinh lên; biết rõ cách sự lười nhác buồn ngủ đã sinh được buông bỏ; và biết rõ cách sự lười nhác buồn ngủ đã được buông bỏ sẽ không sinh lên nữa về sau.",
  "mn10:36.7": "Khi trong mình có sự xao động và cắn rứt, vị ấy biết rõ: “Trong tôi có sự xao động và cắn rứt”; khi trong mình không có sự xao động và cắn rứt, vị ấy biết rõ: “Trong tôi không có sự xao động và cắn rứt.” Vị ấy cũng biết rõ cách sự xao động và cắn rứt chưa sinh nay sinh lên; biết rõ cách sự xao động và cắn rứt đã sinh được buông bỏ; và biết rõ cách sự xao động và cắn rứt đã được buông bỏ sẽ không sinh lên nữa về sau.",
  "mn10:36.8": "Khi trong mình có sự ngờ vực, vị ấy biết rõ: “Trong tôi có sự ngờ vực”; khi trong mình không có sự ngờ vực, vị ấy biết rõ: “Trong tôi không có sự ngờ vực.” Vị ấy cũng biết rõ cách sự ngờ vực chưa sinh nay sinh lên; biết rõ cách sự ngờ vực đã sinh được buông bỏ; và biết rõ cách sự ngờ vực đã được buông bỏ sẽ không sinh lên nữa về sau.",
  "mn10:37.1": "Như vậy, vị ấy sống nhìn các việc nơi các việc ở trong mình, hay sống nhìn các việc nơi các việc ở ngoài, hay sống nhìn các việc nơi các việc cả ở trong mình lẫn ở ngoài.",
  "mn10:37.2": "Vị ấy sống nhìn sự sinh lên trong các việc, hay sống nhìn sự tan đi trong các việc, hay sống nhìn cả sự sinh lên và tan đi trong các việc.",
  "mn10:37.3": "Hoặc sự nhớ biết rõ nơi vị ấy được đặt vững rằng: “Có các việc đây.” Chỉ đến mức đủ để thấy rõ, đủ để nhớ biết rõ, vị ấy sống không nương tựa, không nắm giữ gì ở đời.",
  "mn10:37.4": "Này các Tỳ Kheo, vị Tỳ Kheo sống nhìn các việc nơi các việc trong năm thứ che lấp là như vậy.",
  "mn10:37.5": "Phần về năm thứ che lấp đã xong.",
  "mn10:38.0": "4.2. Phần nhìn năm nhóm bị nắm giữ",
  "mn10:38.1": "Lại nữa, này các Tỳ Kheo, vị Tỳ Kheo sống nhìn các việc nơi các việc trong năm nhóm bị nắm giữ.",
  "mn10:38.2": "Này các Tỳ Kheo, thế nào là một Tỳ Kheo sống quán xét các việc nơi các việc, đối với năm nhóm bị nắm giữ?",
  "mn10:38.3": "Ở đây, này các Tỳ Kheo, một Tỳ Kheo:",
  "mn10:38.4": "‘đây là thân sắc, đây là sự sinh khởi của thân sắc, đây là sự tan mất của thân sắc;",
  "mn10:38.5": "đây là cảm giác, đây là sự sinh khởi của cảm giác, đây là sự tan mất của cảm giác;",
  "mn10:38.6": "đây là sự ghi nhận, đây là sự sinh khởi của sự ghi nhận, đây là sự tan mất của sự ghi nhận;",
  "mn10:38.7": "đây là các hoạt động của tâm, đây là sự sinh khởi của các hoạt động của tâm, đây là sự tan mất của các hoạt động của tâm;",
  "mn10:38.8": "đây là sự nhận biết, đây là sự sinh khởi của sự nhận biết, đây là sự tan mất của sự nhận biết’.",
  "mn10:39.1": "Như vậy, vị ấy sống quán xét các việc nơi các việc ở trong mình, hay sống quán xét các việc nơi các việc ở ngoài mình, hay sống quán xét các việc nơi các việc cả trong lẫn ngoài;",
  "mn10:39.2": "hay sống quán xét tính sinh khởi nơi các việc, hay sống quán xét tính tan hoại nơi các việc, hay sống quán xét cả tính sinh khởi và tính tan hoại nơi các việc.",
  "mn10:39.3": "Hoặc sự nhớ biết rõ được đặt vững nơi vị ấy rằng: ‘có các việc’. Chỉ đến mức hiểu biết và nhớ biết rõ mà thôi, vị ấy sống không nương tựa, và không nắm giữ bất cứ gì ở đời.",
  "mn10:39.4": "Này các Tỳ Kheo, như vậy là một Tỳ Kheo sống quán xét các việc nơi các việc, đối với năm nhóm bị nắm giữ.",
  "mn10:39.5": "Phần về các nhóm đến đây là hết.",
  "mn10:40.0": "4.3. Phần quán xét các việc về sáu chỗ trong và ngoài",
  "mn10:40.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo sống quán xét các việc nơi các việc, đối với sáu chỗ trong và ngoài.",
  "mn10:40.2": "Này các Tỳ Kheo, thế nào là một Tỳ Kheo sống quán xét các việc nơi các việc, đối với sáu chỗ trong và ngoài?",
  "mn10:40.3": "Ở đây, này các Tỳ Kheo, một Tỳ Kheo biết rõ mắt, biết rõ hình sắc, biết rõ sự trói buộc sinh lên do nương cả hai thứ ấy; biết rõ cách sự trói buộc chưa sinh được sinh lên; biết rõ cách sự trói buộc đã sinh được dứt bỏ; biết rõ cách sự trói buộc đã dứt bỏ không còn sinh lên về sau.",
  "mn10:40.4": "Biết rõ tai, biết rõ tiếng, biết rõ sự trói buộc sinh lên do nương cả hai thứ ấy; biết rõ cách sự trói buộc chưa sinh được sinh lên; biết rõ cách sự trói buộc đã sinh được dứt bỏ; biết rõ cách sự trói buộc đã dứt bỏ không còn sinh lên về sau.",
  "mn10:40.5": "Biết rõ mũi, biết rõ mùi, biết rõ sự trói buộc sinh lên do nương cả hai thứ ấy; biết rõ cách sự trói buộc chưa sinh được sinh lên; biết rõ cách sự trói buộc đã sinh được dứt bỏ; biết rõ cách sự trói buộc đã dứt bỏ không còn sinh lên về sau.",
  "mn10:40.6": "Biết rõ lưỡi, biết rõ vị, biết rõ sự trói buộc sinh lên do nương cả hai thứ ấy; biết rõ cách sự trói buộc chưa sinh được sinh lên; biết rõ cách sự trói buộc đã sinh được dứt bỏ; biết rõ cách sự trói buộc đã dứt bỏ không còn sinh lên về sau.",
  "mn10:40.7": "Biết rõ thân, biết rõ sự chạm xúc, biết rõ sự trói buộc sinh lên do nương cả hai thứ ấy; biết rõ cách sự trói buộc chưa sinh được sinh lên; biết rõ cách sự trói buộc đã sinh được dứt bỏ; biết rõ cách sự trói buộc đã dứt bỏ không còn sinh lên về sau.",
  "mn10:40.8": "Biết rõ ý, biết rõ các việc, biết rõ sự trói buộc sinh lên do nương cả hai thứ ấy; biết rõ cách sự trói buộc chưa sinh được sinh lên; biết rõ cách sự trói buộc đã sinh được dứt bỏ; biết rõ cách sự trói buộc đã dứt bỏ không còn sinh lên về sau.",
  "mn10:41.1": "Như vậy, vị ấy sống quán xét các việc nơi các việc ở trong mình, hay sống quán xét các việc nơi các việc ở ngoài mình, hay sống quán xét các việc nơi các việc cả trong lẫn ngoài;",
  "mn10:41.2": "hay sống quán xét tính sinh khởi nơi các việc, hay sống quán xét tính tan hoại nơi các việc, hay sống quán xét cả tính sinh khởi và tính tan hoại nơi các việc.",
  "mn10:41.3": "Hoặc sự nhớ biết rõ được đặt vững nơi vị ấy rằng: ‘có các việc’. Chỉ đến mức hiểu biết và nhớ biết rõ mà thôi, vị ấy sống không nương tựa và không nắm giữ bất cứ gì ở đời.",
  "mn10:41.4": "Này các Tỳ Kheo, như vậy là một Tỳ Kheo sống quán xét các việc nơi các việc, đối với sáu chỗ trong và ngoài.",
  "mn10:41.5": "Phần về sáu chỗ đến đây là hết.",
  "mn10:42.0": "4.4. Phần quán xét các việc về bảy phần đưa đến giác ngộ",
  "mn10:42.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo sống quán xét các việc nơi các việc, đối với bảy phần đưa đến giác ngộ.",
  "mn10:42.2": "Này các Tỳ Kheo, thế nào là một Tỳ Kheo sống quán xét các việc nơi các việc, đối với bảy phần đưa đến giác ngộ?",
  "mn10:42.3": "Ở đây, này các Tỳ Kheo, khi trong mình có phần nhớ biết rõ đưa đến giác ngộ, vị ấy biết rõ: ‘trong mình có phần nhớ biết rõ đưa đến giác ngộ’; khi trong mình không có phần nhớ biết rõ đưa đến giác ngộ, vị ấy biết rõ: ‘trong mình không có phần nhớ biết rõ đưa đến giác ngộ’; vị ấy biết rõ cách phần nhớ biết rõ đưa đến giác ngộ chưa sinh được sinh lên, và biết rõ cách phần nhớ biết rõ đưa đến giác ngộ đã sinh được làm cho trọn vẹn.",
  "mn10:42.4": "Khi trong lòng có yếu tố giác ngộ là sự xem xét kỹ các điều, vị ấy biết: ‘Trong lòng tôi có sự xem xét kỹ các điều’; khi trong lòng không có yếu tố giác ngộ là sự xem xét kỹ các điều, vị ấy biết: ‘Trong lòng tôi không có sự xem xét kỹ các điều’; vị ấy biết cách làm cho sự xem xét kỹ các điều chưa sinh khởi được sinh khởi, và biết cách làm cho sự xem xét kỹ các điều đã sinh khởi được vun bồi cho trọn vẹn.",
  "mn10:42.5": "Khi trong lòng có yếu tố giác ngộ là sự gắng sức, vị ấy biết: ‘Trong lòng tôi có sự gắng sức’; khi trong lòng không có yếu tố giác ngộ là sự gắng sức, vị ấy biết: ‘Trong lòng tôi không có sự gắng sức’; vị ấy biết cách làm cho sự gắng sức chưa sinh khởi được sinh khởi, và biết cách làm cho sự gắng sức đã sinh khởi được vun bồi cho trọn vẹn.",
  "mn10:42.6": "Khi trong lòng có yếu tố giác ngộ là niềm vui, vị ấy biết: ‘Trong lòng tôi có niềm vui’; khi trong lòng không có yếu tố giác ngộ là niềm vui, vị ấy biết: ‘Trong lòng tôi không có niềm vui’; vị ấy biết cách làm cho niềm vui chưa sinh khởi được sinh khởi, và biết cách làm cho niềm vui đã sinh khởi được vun bồi cho trọn vẹn.",
  "mn10:42.7": "Khi trong lòng có yếu tố giác ngộ là sự lắng dịu, vị ấy biết: ‘Trong lòng tôi có sự lắng dịu’; khi trong lòng không có yếu tố giác ngộ là sự lắng dịu, vị ấy biết: ‘Trong lòng tôi không có sự lắng dịu’; vị ấy biết cách làm cho sự lắng dịu chưa sinh khởi được sinh khởi, và biết cách làm cho sự lắng dịu đã sinh khởi được vun bồi cho trọn vẹn.",
  "mn10:42.8": "Khi trong lòng có yếu tố giác ngộ là tâm yên vững, vị ấy biết: ‘Trong lòng tôi có tâm yên vững’; khi trong lòng không có yếu tố giác ngộ là tâm yên vững, vị ấy biết: ‘Trong lòng tôi không có tâm yên vững’; vị ấy biết cách làm cho tâm yên vững chưa sinh khởi được sinh khởi, và biết cách làm cho tâm yên vững đã sinh khởi được vun bồi cho trọn vẹn.",
  "mn10:42.9": "Khi trong lòng có yếu tố giác ngộ là sự nhìn với lòng bình thản, vị ấy biết: ‘Trong lòng tôi có sự nhìn với lòng bình thản’; khi trong lòng không có yếu tố giác ngộ là sự nhìn với lòng bình thản, vị ấy biết: ‘Trong lòng tôi không có sự nhìn với lòng bình thản’; vị ấy biết cách làm cho sự nhìn với lòng bình thản chưa sinh khởi được sinh khởi, và biết cách làm cho sự nhìn với lòng bình thản đã sinh khởi được vun bồi cho trọn vẹn.",
  "mn10:43.1": "Như vậy, vị ấy sống nhìn các điều nơi trong lòng, hoặc sống nhìn các điều nơi bên ngoài, hoặc sống nhìn các điều cả nơi trong lòng lẫn bên ngoài.",
  "mn10:43.2": "Vị ấy sống nhìn các điều theo mặt sinh khởi, hoặc sống nhìn các điều theo mặt tan đi, hoặc sống nhìn các điều theo cả mặt sinh khởi và tan đi.",
  "mn10:43.3": "Hoặc nơi vị ấy, sự nhớ biết rõ được đặt vững với ý nghĩ: ‘Có các điều’. Chỉ vừa đủ cho sự biết rõ và sự nhớ biết rõ, vị ấy sống không nương tựa, không nắm giữ bất cứ gì ở đời.",
  "mn10:43.4": "Này các Tỳ Kheo, đó là cách một Tỳ Kheo sống nhìn các điều nơi các yếu tố đưa đến giác ngộ.",
  "mn10:43.5": "Phần về các yếu tố đưa đến giác ngộ đến đây là xong.",
  "mn10:44.0": "4.5. Phần về nhìn các điều nơi bốn sự thật của bậc cao quý",
  "mn10:44.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo sống nhìn các điều nơi bốn sự thật của bậc cao quý.",
  "mn10:44.2": "Và này các Tỳ Kheo, thế nào là một Tỳ Kheo sống nhìn các điều nơi bốn sự thật của bậc cao quý?",
  "mn10:44.3": "Ở đây, này các Tỳ Kheo, một Tỳ Kheo biết đúng như thật: ‘Đây là sự khổ đau’, biết đúng như thật: ‘Đây là nguồn gốc của sự khổ đau’, biết đúng như thật: ‘Đây là sự chấm dứt của sự khổ đau’, biết đúng như thật: ‘Đây là con đường đưa đến sự chấm dứt của sự khổ đau’.",
  "mn10:45.1": "Như vậy, vị ấy sống nhìn các điều nơi trong lòng, hoặc sống nhìn các điều nơi bên ngoài, hoặc sống nhìn các điều cả nơi trong lòng lẫn bên ngoài.",
  "mn10:45.2": "Vị ấy sống nhìn các điều theo mặt sinh khởi, hoặc sống nhìn các điều theo mặt tan đi, hoặc sống nhìn các điều theo cả mặt sinh khởi và tan đi.",
  "mn10:45.3": "Hoặc nơi vị ấy, sự nhớ biết rõ được đặt vững với ý nghĩ: ‘Có các điều’. Chỉ vừa đủ cho sự biết rõ và sự nhớ biết rõ, vị ấy sống không nương tựa, không nắm giữ bất cứ gì ở đời.",
  "mn10:45.4": "Này các Tỳ Kheo, đó là cách một Tỳ Kheo sống nhìn các điều nơi bốn sự thật của bậc cao quý.",
  "mn10:45.5": "Phần về các sự thật đến đây là xong.",
  "mn10:45.6": "Phần nhìn các điều đến đây là xong.",
  "mn10:46.1": "Này các Tỳ Kheo, bất cứ ai vun bồi bốn nền tảng nhớ biết rõ này theo cách ấy trong bảy năm, người ấy có thể chờ đợi một trong hai kết quả:",
  "mn10:46.2": "hoặc ngay trong đời này đạt được sự hiểu biết rốt ráo, hoặc nếu còn sót lại phần nắm giữ thì sẽ không còn trở lại cõi này nữa.",
  "mn10:46.3": "Này các Tỳ Kheo, thôi đừng nói đến bảy năm.",
  "mn10:46.4": "Này các Tỳ Kheo, bất cứ ai vun bồi bốn nền tảng nhớ biết rõ này theo cách ấy trong sáu năm…",
  "mn10:46.5": "năm năm…",
  "mn10:46.6": "bốn năm…",
  "mn10:46.7": "ba năm…",
  "mn10:46.8": "hai năm…",
  "mn10:46.9": "một năm…",
  "mn10:46.10": "Thôi, này các Tỳ Kheo, cứ nói là một năm.",
  "mn10:46.11": "Này các Tỳ Kheo, bất cứ ai làm cho bốn cách đặt tâm nhớ biết rõ này lớn mạnh như vậy trong bảy tháng, thì có thể mong một trong hai kết quả:",
  "mn10:46.12": "hoặc ngay trong đời này tự mình biết rõ; hoặc nếu còn phần bám víu sót lại thì sẽ không trở lui đời này nữa.",
  "mn10:46.13": "Thôi, này các Tỳ Kheo, cứ nói là bảy tháng.",
  "mn10:46.14": "Này các Tỳ Kheo, bất cứ ai làm cho bốn cách đặt tâm nhớ biết rõ này lớn mạnh như vậy trong sáu tháng…",
  "mn10:46.15": "năm tháng…",
  "mn10:46.16": "bốn tháng…",
  "mn10:46.17": "ba tháng…",
  "mn10:46.18": "hai tháng…",
  "mn10:46.19": "một tháng…",
  "mn10:46.20": "nửa tháng…",
  "mn10:46.21": "Thôi, này các Tỳ Kheo, cứ nói là nửa tháng.",
  "mn10:46.22": "Này các Tỳ Kheo, bất cứ ai làm cho bốn cách đặt tâm nhớ biết rõ này lớn mạnh như vậy trong bảy ngày, thì có thể mong một trong hai kết quả:",
  "mn10:46.23": "hoặc ngay trong đời này tự mình biết rõ, hoặc nếu còn phần bám víu sót lại thì sẽ không trở lui đời này nữa.",
  "mn10:47.1": "Này các Tỳ Kheo, đây là con đường một lối đưa chúng sinh đến chỗ trong sạch, vượt qua buồn than khóc lóc, làm cho khổ đau và nỗi buồn trong lòng chấm dứt, đạt đến lẽ đúng, tự mình làm cho tắt hẳn.",
  "mn10:47.2": "Điều đã được nói như vậy là được nói dựa vào điều này.",
  "mn10:47.3": "Đức Thế Tôn nói như vậy.",
  "mn10:47.4": "Các Tỳ Kheo ấy vui mừng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn10:47.5": "Kinh Đặt Tâm Nhớ Biết Rõ đã xong, bài thứ mười.",
  "mn10:47.6": "Phẩm Gốc Rễ và Cách Trình Bày đã xong, phần đầu tiên.",
  "mn10:48.0": "Bài tóm tắt:",
  "mn10:48.1": "Gốc rễ, giữ gìn, phần thừa hưởng điều lành,",
  "mn10:48.2": "sợ hãi, không nhơ bẩn, điều mong mỏi, nền tảng;",
  "mn10:48.3": "gọt mòn, thấy đúng, đặt tâm nhớ biết rõ,",
  "mn10:48.4": "phẩm hay nhất, không gì sánh bằng, khéo trọn vẹn."
}
window.BILARA["mn10"]["vi"]["mn10:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";