window.BILARA = window.BILARA || {};
window.BILARA["mn119"] = window.BILARA["mn119"] || {};
window.BILARA["mn119"]["vi"] = {
  "mn119:0.1": "Trung Bộ Kinh 119",
  "mn119:0.2": "Kinh Nhớ Biết Rõ Nơi Thân",
  "mn119:1.1": "Tôi nghe như vầy—",
  "mn119:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, tại Kỳ Viên, vườn của ông Cấp Cô Độc.",
  "mn119:2.1": "Khi ấy, có nhiều Tỳ Kheo sau buổi ăn, đi khất thực trở về, đang ngồi tụ họp trong nhà hội, thì câu chuyện này khởi lên giữa họ:",
  "mn119:2.2": "“Lạ thay, các hiền giả, thật ít có thay, các hiền giả.",
  "mn119:2.3": "Đức Thế Tôn ấy, bậc biết rõ, thấy rõ, bậc đáng kính, bậc tự mình giác ngộ trọn vẹn, đã nói rằng sự nhớ biết rõ nơi thân, khi được làm cho lớn mạnh, được thực hành nhiều, thì cho quả lớn, lợi ích lớn.”",
  "mn119:2.4": "Câu chuyện giữa các Tỳ Kheo ấy còn đang dang dở, thì Đức Thế Tôn vào buổi chiều, sau khi ra khỏi chỗ ở yên một mình, đi đến nhà hội. Đến nơi, Ngài ngồi xuống chỗ đã dọn sẵn.",
  "mn119:2.5": "Ngồi xuống rồi, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn119:2.6": "“Này các Tỳ Kheo, lúc này các ông đang ngồi nói chuyện gì, và câu chuyện nào của các ông còn đang dang dở?”",
  "mn119:2.7": "“Bạch Thế Tôn, ở đây, chúng con sau buổi ăn, đi khất thực trở về, đang ngồi tụ họp trong nhà hội, thì câu chuyện này khởi lên giữa chúng con:",
  "mn119:2.8": "‘Lạ thay, các hiền giả, thật ít có thay, các hiền giả.",
  "mn119:2.9": "Đức Thế Tôn ấy, bậc biết rõ, thấy rõ, bậc đáng kính, bậc tự mình giác ngộ trọn vẹn, đã nói rằng sự nhớ biết rõ nơi thân, khi được làm cho lớn mạnh, được thực hành nhiều, thì cho quả lớn, lợi ích lớn.’",
  "mn119:2.10": "Đó là câu chuyện của chúng con còn đang dang dở, thì Đức Thế Tôn đến.”",
  "mn119:3.1": "“Này các Tỳ Kheo, thế nào là sự nhớ biết rõ nơi thân được làm cho lớn mạnh, được thực hành nhiều, để cho quả lớn, lợi ích lớn?",
  "mn119:4.1": "Ở đây, này các Tỳ Kheo, một Tỳ Kheo đi vào rừng, hay đến gốc cây, hay vào căn nhà trống, rồi ngồi xuống, xếp bằng, giữ thân ngay thẳng, đặt sự nhớ biết rõ trước mặt.",
  "mn119:4.2": "Vị ấy nhớ biết rõ khi thở vào, nhớ biết rõ khi thở ra;",
  "mn119:4.3": "khi thở vào dài, vị ấy biết rõ: ‘Tôi thở vào dài’; khi thở ra dài, vị ấy biết rõ: ‘Tôi thở ra dài’;",
  "mn119:4.4": "khi thở vào ngắn, vị ấy biết rõ: ‘Tôi thở vào ngắn’; khi thở ra ngắn, vị ấy biết rõ: ‘Tôi thở ra ngắn’;",
  "mn119:4.5": "vị ấy tự rèn luyện: ‘Tôi sẽ thở vào, cảm nhận toàn thân’; vị ấy tự rèn luyện: ‘Tôi sẽ thở ra, cảm nhận toàn thân’;",
  "mn119:4.6": "vị ấy tự rèn luyện: ‘Tôi sẽ thở vào, làm lắng dịu các hoạt động của thân’; vị ấy tự rèn luyện: ‘Tôi sẽ thở ra, làm lắng dịu các hoạt động của thân’.",
  "mn119:4.7": "Khi vị ấy sống như vậy, không buông lung, tha thiết, dốc lòng, thì những nghĩ ngợi vương chuyện nhà đời đều lắng mất.",
  "mn119:4.8": "Khi chúng lắng mất, tâm vị ấy đứng vững bên trong, lắng xuống, gom lại một mối, yên vững.",
  "mn119:4.9": "Như vậy, này các Tỳ Kheo, là Tỳ Kheo làm cho lớn mạnh sự nhớ biết rõ nơi thân.",
  "mn119:5.1": "Lại nữa, này các Tỳ Kheo, khi đi, vị Tỳ Kheo biết rõ: ‘Tôi đang đi’; khi đứng, vị ấy biết rõ: ‘Tôi đang đứng’; khi ngồi, vị ấy biết rõ: ‘Tôi đang ngồi’; khi nằm, vị ấy biết rõ: ‘Tôi đang nằm’.",
  "mn119:5.2": "Thân được đặt ở tư thế nào, vị ấy biết rõ thân ở tư thế ấy.",
  "mn119:5.3": "Khi vị ấy sống như vậy, không buông lung, tha thiết, dốc lòng, thì những nghĩ ngợi vương chuyện nhà đời đều lắng mất.",
  "mn119:5.4": "Khi chúng lắng mất, tâm vị ấy đứng vững bên trong, lắng xuống, gom lại một mối, yên vững.",
  "mn119:5.5": "Cũng vậy, này các Tỳ Kheo, là Tỳ Kheo làm cho lớn mạnh sự nhớ biết rõ nơi thân.",
  "mn119:6.1": "Lại nữa, này các Tỳ Kheo, vị Tỳ Kheo khi bước tới hay bước lui đều biết rõ; khi nhìn thẳng hay nhìn quanh đều biết rõ; khi co tay chân hay duỗi tay chân đều biết rõ; khi mang y, bát và áo đều biết rõ; khi ăn, uống, nhai, nếm đều biết rõ; khi đi đại tiện, tiểu tiện đều biết rõ; khi đi, đứng, ngồi, ngủ, thức, nói, im lặng đều biết rõ.",
  "mn119:6.2": "Vị ấy sống không lơ là, siêng năng, dốc lòng như vậy, nên những nghĩ ngợi ngọt bùi gắn với đời sống trong nhà đều lắng xuống.",
  "mn119:6.3": "Khi những điều ấy lắng xuống, tâm vị ấy yên ngay bên trong, lặng hẳn, gom lại thành một, vững vàng.",
  "mn119:6.4": "Này các Tỳ Kheo, Tỳ Kheo tu tập sự nhớ biết rõ nơi thân là như vậy.",
  "mn119:7.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo quán xét chính thân này, từ bàn chân trở lên, từ đỉnh đầu trở xuống, bọc kín bởi da, đầy những thứ nhơ bẩn đủ loại:",
  "mn119:7.2": "Trong thân này có tóc, lông, móng, răng, da, thịt, gân, xương, tủy xương, thận, tim, gan, màng ngăn, lá lách, phổi, ruột, màng ruột, đồ ăn trong bụng, phân, mật, đờm, mủ, máu, mồ hôi, mỡ, nước mắt, mỡ đặc, nước miếng, nước mũi, nước khớp, nước tiểu.",
  "mn119:7.3": "Cũng như, này các Tỳ Kheo, một cái bị hai đầu miệng, đựng đầy nhiều thứ hạt khác nhau, như là:",
  "mn119:7.4": "thóc, gạo, đậu xanh, đậu đen, mè, gạo trắng,",
  "mn119:7.5": "một người sáng mắt mở ra và nhìn kỹ:",
  "mn119:7.6": "Đây là thóc, đây là gạo, đây là đậu xanh, đây là đậu đen, đây là mè, đây là gạo trắng.",
  "mn119:7.7": "Cũng vậy, này các Tỳ Kheo, Tỳ Kheo quán xét chính thân này, từ bàn chân trở lên, từ đỉnh đầu trở xuống, bọc kín bởi da, đầy những thứ nhơ bẩn đủ loại:",
  "mn119:7.8": "Trong thân này có tóc, lông, móng, răng, da, thịt, gân, xương, tủy xương, thận, tim, gan, màng ngăn, lá lách, phổi, ruột, màng ruột, đồ ăn trong bụng, phân, mật, đờm, mủ, máu, mồ hôi, mỡ, nước mắt, mỡ đặc, nước miếng, nước mũi, nước khớp, nước tiểu.",
  "mn119:7.9": "Vị ấy sống không lơ là, siêng năng, dốc lòng như vậy, nên những nghĩ ngợi ngọt bùi gắn với đời sống trong nhà đều lắng xuống.",
  "mn119:7.10": "Khi những điều ấy lắng xuống, tâm vị ấy yên ngay bên trong, lặng hẳn, gom lại thành một, vững vàng.",
  "mn119:7.11": "Này các Tỳ Kheo, Tỳ Kheo tu tập sự nhớ biết rõ nơi thân là như vậy.",
  "mn119:8.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo quán xét chính thân này theo chỗ nó đứng, theo cách nó được đặt, xét theo từng phần chất:",
  "mn119:8.2": "Trong thân này có phần đất, phần nước, phần lửa, phần gió.",
  "mn119:8.3": "Cũng như, này các Tỳ Kheo, một người mổ bò khéo tay, hay học trò của người mổ bò, giết một con bò rồi ngồi ở ngã tư lớn, xẻ nó ra thành từng phần;",
  "mn119:8.4": "cũng vậy, này các Tỳ Kheo, Tỳ Kheo quán xét chính thân này theo chỗ nó đứng, theo cách nó được đặt, xét theo từng phần chất:",
  "mn119:8.5": "Trong thân này có phần đất, phần nước, phần lửa, phần gió.",
  "mn119:8.6": "Vị ấy sống không lơ là, siêng năng, dốc lòng như vậy, nên những nghĩ ngợi ngọt bùi gắn với đời sống trong nhà đều lắng xuống.",
  "mn119:8.7": "Khi những điều ấy lắng xuống, tâm vị ấy yên ngay bên trong, lặng hẳn, gom lại thành một, vững vàng.",
  "mn119:8.8": "Này các Tỳ Kheo, Tỳ Kheo tu tập sự nhớ biết rõ nơi thân là như vậy.",
  "mn119:9.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo như thấy một xác chết bị quăng ở bãi tha ma, đã một ngày, hai ngày, hay ba ngày, trương phồng lên, đổi màu xanh bầm, rỉ mủ.",
  "mn119:9.2": "Vị ấy đem thân này so vào:",
  "mn119:9.3": "Thân này cũng có tính chất như vậy, sẽ thành ra như vậy, không vượt khỏi như vậy.",
  "mn119:9.4": "Vị ấy sống không lơ là, siêng năng, dốc lòng như vậy, nên những nghĩ ngợi ngọt bùi gắn với đời sống trong nhà đều lắng xuống.",
  "mn119:9.5": "Khi những điều ấy lắng xuống, tâm vị ấy yên ngay bên trong, lặng hẳn, gom lại thành một, vững vàng.",
  "mn119:9.6": "Này các Tỳ Kheo, Tỳ Kheo tu tập sự nhớ biết rõ nơi thân là như vậy.",
  "mn119:10.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo như thấy một xác chết bị quăng ở bãi tha ma, bị quạ rỉa, bị diều hâu rỉa, bị kên kên rỉa, bị chó rừng rỉa, bị chó rỉa, bị beo rỉa, bị cọp rỉa, bị chồn rỉa, hay bị nhiều loài vật nhỏ khác rỉa ăn.",
  "mn119:10.2": "Vị ấy đem thân này so vào:",
  "mn119:10.3": "‘Thân này cũng có tính chất như vậy, sẽ thành ra như vậy, không vượt khỏi như vậy.’",
  "mn119:10.4": "Vị ấy sống không lơ là như vậy …",
  "mn119:10.5": "Này các Tỳ Kheo, như vậy là Tỳ Kheo làm cho sự nhớ biết rõ nơi thân lớn lên.",
  "mn119:11-14.1": "Lại nữa, này các Tỳ Kheo, ví như một Tỳ Kheo thấy một xác chết bị quăng ở bãi tha ma, chỉ còn bộ xương còn dính thịt và máu, được gân nối lại …",
  "mn119:11-14.2": "bộ xương không còn thịt, còn dính máu, được gân nối lại …",
  "mn119:11-14.3": "bộ xương không còn thịt và máu, chỉ còn gân nối lại …",
  "mn119:11-14.4": "các khúc xương rời nhau, văng tản mát khắp các hướng: chỗ này xương bàn tay, chỗ kia xương bàn chân, chỗ kia xương mắt cá, chỗ kia xương ống chân, chỗ kia xương đùi, chỗ kia xương hông, chỗ kia xương sườn, chỗ kia xương sống, chỗ kia xương vai, chỗ kia xương cổ, chỗ kia xương hàm, chỗ kia xương răng, chỗ kia sọ đầu.",
  "mn119:11-14.5": "Vị ấy đem so với chính thân này:",
  "mn119:11-14.6": "‘Thân này cũng có tính chất như vậy, sẽ thành ra như vậy, không vượt khỏi như vậy.’",
  "mn119:11-14.7": "Vị ấy sống không lơ là như vậy …",
  "mn119:11-14.8": "Này các Tỳ Kheo, như vậy là Tỳ Kheo làm cho sự nhớ biết rõ nơi thân lớn lên.",
  "mn119:15-17.1": "Lại nữa, này các Tỳ Kheo, ví như một Tỳ Kheo thấy một xác chết bị quăng ở bãi tha ma—",
  "mn119:15-17.2": "xương trắng như màu vỏ sò …",
  "mn119:15-17.3": "xương chất thành đống, đã hơn ba năm …",
  "mn119:15-17.4": "xương mục nát, thành bột.",
  "mn119:15-17.5": "Vị ấy đem so với chính thân này:",
  "mn119:15-17.6": "‘Thân này cũng có tính chất như vậy, sẽ thành ra như vậy, không vượt khỏi như vậy.’",
  "mn119:15-17.7": "Vị ấy sống không lơ là như vậy …",
  "mn119:15-17.8": "…",
  "mn119:15-17.9": "Này các Tỳ Kheo, như vậy là Tỳ Kheo làm cho sự nhớ biết rõ nơi thân lớn lên.",
  "mn119:18.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo lìa các ham muốn giác quan … vào và an trú tầng thiền thứ nhất.",
  "mn119:18.2": "Vị ấy thấm nhuần, làm ướt đẫm, làm đầy tràn, phủ khắp chính thân này bằng niềm vui và sự dễ chịu do lìa riêng mà sinh ra; không có chỗ nào trong toàn thân không được niềm vui và sự dễ chịu do lìa riêng ấy thấm tới.",
  "mn119:18.3": "Này các Tỳ Kheo, ví như một người tắm khéo hay người học việc của người tắm đổ bột tắm vào chậu đồng rồi rưới nước vào, nhào trộn cho thật đều, khiến cục bột tắm ấy thấm ướt, ngấm nước khắp trong ngoài, nhưng không chảy nhỏ giọt;",
  "mn119:18.4": "cũng vậy, này các Tỳ Kheo, Tỳ Kheo thấm nhuần, làm ướt đẫm, làm đầy tràn, phủ khắp chính thân này bằng niềm vui và sự dễ chịu do lìa riêng mà sinh ra; không có chỗ nào trong toàn thân không được niềm vui và sự dễ chịu do lìa riêng ấy thấm tới.",
  "mn119:18.5": "Vị ấy sống không lơ là như vậy …",
  "mn119:18.6": "…",
  "mn119:18.7": "Này các Tỳ Kheo, như vậy là Tỳ Kheo làm cho sự nhớ biết rõ nơi thân lớn lên.",
  "mn119:19.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo khi sự nghĩ lời và xét kỹ đã lắng xuống … vào và an trú tầng thiền thứ hai.",
  "mn119:19.2": "Vị ấy thấm nhuần, làm ướt đẫm, làm đầy tràn, phủ khắp chính thân này bằng niềm vui và sự dễ chịu do tâm yên vững sinh ra; không có chỗ nào trong toàn thân không được niềm vui và sự dễ chịu do tâm yên vững sinh ra ấy thấm tới.",
  "mn119:19.3": "Này các Tỳ Kheo, ví như một hồ nước sâu, nước từ trong lòng đất trào lên. Hồ ấy không có dòng nước chảy vào từ phía đông, không có dòng nước chảy vào từ phía tây, không có dòng nước chảy vào từ phía bắc, không có dòng nước chảy vào từ phía nam; và trời cũng không mưa đúng lúc. Nhưng từ chính hồ ấy, những mạch nước mát trào lên, thấm nhuần, làm ướt đẫm, làm đầy tràn, phủ khắp hồ nước ấy bằng nước mát; không có chỗ nào trong toàn hồ không được nước mát thấm tới;",
  "mn119:19.4": "Cũng vậy, này các Tỳ Kheo, Tỳ Kheo thấm đẫm, chan hòa, làm đầy, phủ khắp chính thân này bằng niềm vui và sự dễ chịu do tâm yên vững sinh ra; không có chỗ nào trong toàn thân không được niềm vui và sự dễ chịu do tâm yên vững sinh ra ấy thấm tới.",
  "mn119:19.5": "Vị ấy sống không buông lung như vậy …",
  "mn119:19.6": "Cũng vậy, này các Tỳ Kheo, Tỳ Kheo làm cho sự nhớ biết rõ nơi thân lớn lên.",
  "mn119:20.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo do niềm vui lắng xuống … đạt tới tầng lặng sâu thứ ba và an trú.",
  "mn119:20.2": "Vị ấy thấm đẫm, chan hòa, làm đầy, phủ khắp chính thân này bằng sự dễ chịu không còn niềm vui rộn ràng; không có chỗ nào trong toàn thân không được sự dễ chịu không còn niềm vui rộn ràng ấy thấm tới.",
  "mn119:20.3": "Ví như, này các Tỳ Kheo, trong hồ sen xanh, hồ sen hồng, hay hồ sen trắng, có những bông sen xanh, sen hồng, hay sen trắng sinh ra trong nước, lớn lên trong nước, vươn lên từ nước, được nước mát nuôi từ gốc đến ngọn; từ đầu ngọn cho đến tận rễ, chúng được nước mát thấm đẫm, chan hòa, làm đầy, phủ khắp, không có chỗ nào trong toàn bộ những bông sen xanh, sen hồng, hay sen trắng ấy không được nước mát thấm tới.",
  "mn119:20.4": "Cũng vậy, này các Tỳ Kheo, Tỳ Kheo thấm đẫm, chan hòa, làm đầy, phủ khắp chính thân này bằng sự dễ chịu không còn niềm vui rộn ràng; không có chỗ nào trong toàn thân không được sự dễ chịu không còn niềm vui rộn ràng ấy thấm tới.",
  "mn119:20.5": "Vị ấy sống không buông lung như vậy …",
  "mn119:20.6": "Cũng vậy, này các Tỳ Kheo, Tỳ Kheo làm cho sự nhớ biết rõ nơi thân lớn lên.",
  "mn119:21.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo do buông cả sự dễ chịu … đạt tới tầng lặng sâu thứ tư và an trú.",
  "mn119:21.2": "Vị ấy ngồi, phủ khắp chính thân này bằng một tấm lòng trong sạch, sáng trong; không có chỗ nào trong toàn thân không được tấm lòng trong sạch, sáng trong ấy phủ tới.",
  "mn119:21.3": "Ví như, này các Tỳ Kheo, một người ngồi trùm kín từ đầu bằng tấm vải trắng, không có chỗ nào trong toàn thân người ấy không được tấm vải trắng phủ tới.",
  "mn119:21.4": "Cũng vậy, này các Tỳ Kheo, Tỳ Kheo ngồi, phủ khắp chính thân này bằng một tấm lòng trong sạch, sáng trong; không có chỗ nào trong toàn thân không được tấm lòng trong sạch, sáng trong ấy phủ tới.",
  "mn119:21.5": "Khi vị ấy sống như vậy, không buông lung, hăng hái, dốc lòng, thì những nghĩ ngợi đượm mùi đời sống tại gia được dứt bỏ.",
  "mn119:21.6": "Do những điều ấy được dứt bỏ, tâm vị ấy đứng vững ở bên trong, lắng xuống, gom lại một mối, yên vững.",
  "mn119:21.7": "Cũng vậy, này các Tỳ Kheo, Tỳ Kheo làm cho sự nhớ biết rõ nơi thân lớn lên.",
  "mn119:22.1": "Này các Tỳ Kheo, với bất cứ ai đã làm cho sự nhớ biết rõ nơi thân lớn lên, làm cho nhiều lên, thì mọi điều lành nào đưa tới sự biết rõ đều nằm gọn trong đó.",
  "mn119:22.2": "Ví như, này các Tỳ Kheo, với bất cứ ai đã chạm tới biển lớn bằng tâm, thì mọi con suối nhỏ nào chảy ra biển đều nằm gọn trong đó.",
  "mn119:22.3": "Cũng vậy, này các Tỳ Kheo, với bất cứ ai đã làm cho sự nhớ biết rõ nơi thân lớn lên, làm cho nhiều lên, thì mọi điều lành nào đưa tới sự biết rõ đều nằm gọn trong đó.",
  "mn119:23.1": "Này các Tỳ Kheo, với bất cứ ai chưa làm cho sự nhớ biết rõ nơi thân lớn lên, chưa làm cho nhiều lên, thì Ma vương tìm được chỗ chen vào, tìm được chỗ bám.",
  "mn119:23.2": "Ví như, này các Tỳ Kheo, một người ném một cục đá nặng vào một đống đất sét ướt.",
  "mn119:23.3": "Các Tỳ Kheo nghĩ sao,",
  "mn119:23.4": "có phải cục đá nặng ấy sẽ tìm được chỗ lún vào trong đống đất sét ướt không?",
  "mn119:23.5": "“Thưa có, bạch Thế Tôn.”",
  "mn119:23.6": "“Cũng vậy, này các Tỳ Kheo, với bất cứ ai chưa làm cho sự nhớ biết rõ nơi thân lớn lên, chưa làm cho nhiều lên, thì Ma vương tìm được chỗ chen vào, tìm được chỗ bám.",
  "mn119:24.1": "Ví như, này các Tỳ Kheo, có một đống củi khô,",
  "mn119:24.2": "rồi một người đến, cầm thanh gỗ quay lửa trên tay:",
  "mn119:24.3": "‘Ta sẽ làm cho lửa bật ra, ta sẽ làm cho sức nóng hiện ra.’",
  "mn119:24.4": "Các Tỳ Kheo nghĩ sao,",
  "mn119:24.5": "người ấy lấy thanh gỗ quay lửa cọ xát vào đống củi khô ấy, có làm cho lửa bật ra, có làm cho sức nóng hiện ra không?”",
  "mn119:24.6": "“Dạ, bạch Đức Thế Tôn.”",
  "mn119:24.7": "“Cũng vậy, này các Tỳ Kheo, với bất cứ ai không làm cho sự nhớ biết rõ nơi thân lớn lên, không thường xuyên vun bồi, thì Ma vương có chỗ chen vào, Ma vương có chỗ bám vào nơi người ấy.",
  "mn119:25.1": "Ví như, này các Tỳ Kheo, một cái vò nước trống không, rỗng tuếch, được đặt trên giá;",
  "mn119:25.2": "rồi có người mang một gánh nước đến.",
  "mn119:25.3": "Các ông nghĩ sao, này các Tỳ Kheo,",
  "mn119:25.4": "người ấy có thể đổ nước vào đó không?”",
  "mn119:25.5": "“Dạ, bạch Đức Thế Tôn.”",
  "mn119:25.6": "“Cũng vậy, này các Tỳ Kheo, với bất cứ ai không làm cho sự nhớ biết rõ nơi thân lớn lên, không thường xuyên vun bồi, thì Ma vương có chỗ chen vào, Ma vương có chỗ bám vào nơi người ấy.",
  "mn119:26.1": "Này các Tỳ Kheo, với bất cứ ai đã làm cho sự nhớ biết rõ nơi thân lớn lên, đã thường xuyên vun bồi, thì Ma vương không có chỗ chen vào, Ma vương không có chỗ bám vào nơi người ấy.",
  "mn119:26.2": "Ví như, này các Tỳ Kheo, một người ném một cuộn chỉ nhẹ vào một tấm ván làm bằng gỗ chắc.",
  "mn119:26.3": "Các ông nghĩ sao, này các Tỳ Kheo,",
  "mn119:26.4": "người ấy có thể làm cho cuộn chỉ nhẹ ấy cắm vào tấm ván gỗ chắc đó không?”",
  "mn119:26.5": "“Thưa không, bạch Đức Thế Tôn.”",
  "mn119:26.6": "“Cũng vậy, này các Tỳ Kheo, với bất cứ ai đã làm cho sự nhớ biết rõ nơi thân lớn lên, đã thường xuyên vun bồi, thì Ma vương không có chỗ chen vào, Ma vương không có chỗ bám vào nơi người ấy.",
  "mn119:27.1": "Ví như, này các Tỳ Kheo, gỗ còn ướt, còn nhựa;",
  "mn119:27.2": "rồi có người mang thanh gỗ để quay lửa đến và nghĩ rằng:",
  "mn119:27.3": "‘Ta sẽ làm cho lửa bật ra, ta sẽ làm cho sức nóng hiện ra.’",
  "mn119:27.4": "Các ông nghĩ sao, này các Tỳ Kheo,",
  "mn119:27.5": "người ấy lấy thanh gỗ quay lửa ấy mà cọ xát vào khúc gỗ ướt còn nhựa đó, có thể làm cho lửa bật ra, làm cho sức nóng hiện ra không?”",
  "mn119:27.6": "“Thưa không, bạch Đức Thế Tôn.”",
  "mn119:27.7": "“Cũng vậy, này các Tỳ Kheo, với bất cứ ai đã làm cho sự nhớ biết rõ nơi thân lớn lên, đã thường xuyên vun bồi, thì Ma vương không có chỗ chen vào, Ma vương không có chỗ bám vào nơi người ấy.",
  "mn119:28.1": "Ví như, này các Tỳ Kheo, một cái vò nước đầy nước, đầy tới miệng, đến mức quạ cũng có thể uống, được đặt trên giá;",
  "mn119:28.2": "rồi có người mang một gánh nước đến.",
  "mn119:28.3": "Các ông nghĩ sao, này các Tỳ Kheo,",
  "mn119:28.4": "người ấy có thể đổ thêm nước vào đó không?”",
  "mn119:28.5": "“Thưa không, bạch Đức Thế Tôn.”",
  "mn119:28.6": "“Cũng vậy, này các Tỳ Kheo, với bất cứ ai đã làm cho sự nhớ biết rõ nơi thân lớn lên, đã thường xuyên vun bồi, thì Ma vương không có chỗ chen vào, Ma vương không có chỗ bám vào nơi người ấy.",
  "mn119:29.1": "Này các Tỳ Kheo, với bất cứ ai đã làm cho sự nhớ biết rõ nơi thân lớn lên, đã thường xuyên vun bồi, nếu người ấy hướng tâm đến điều gì cần tự mình biết rõ và thấy rõ, để tự mình biết rõ và thấy rõ điều ấy, thì ngay ở đó người ấy có thể tự mình chạm tới, khi có đủ chỗ dựa.",
  "mn119:29.2": "Ví như, này các Tỳ Kheo, một cái vò nước đầy nước, đầy tới miệng, đến mức quạ cũng có thể uống, được đặt trên giá.",
  "mn119:29.3": "Một người khỏe mạnh kéo nó nghiêng về phía nào, thì nước sẽ chảy ra về phía ấy.”",
  "mn119:29.4": "“Dạ, bạch Thế Tôn.”",
  "mn119:29.5": "“Cũng vậy, này các Tỳ Kheo, bất kỳ ai làm cho sự nhớ biết rõ nơi thân được vun bồi, được làm cho nhiều lên, thì khi người ấy hướng lòng đến điều gì cần tự mình biết rõ và thấy rõ, người ấy có thể tự mình chạm đến điều ấy, khi có nền tảng thích hợp.”",
  "mn119:30.1": "“Ví như, này các Tỳ Kheo, trên một khoảng đất bằng có một ao vuông, có bờ đắp kín, đầy nước, nước ngang miệng bờ, đến mức quạ cũng có thể uống được.",
  "mn119:30.2": "Nếu một người khỏe mạnh mở bờ ở phía nào, nước có chảy ra theo phía ấy không?”",
  "mn119:30.3": "“Dạ, bạch Thế Tôn.”",
  "mn119:30.4": "“Cũng vậy, này các Tỳ Kheo, bất kỳ ai làm cho sự nhớ biết rõ nơi thân được vun bồi, được làm cho nhiều lên, thì khi người ấy hướng lòng đến điều gì cần tự mình biết rõ và thấy rõ, người ấy có thể tự mình chạm đến điều ấy, khi có nền tảng thích hợp.",
  "mn119:31.1": "Ví như, này các Tỳ Kheo, ở một ngã tư lớn trên nền đất tốt, có một cỗ xe ngựa thuần chủng đã thắng sẵn, đứng đó, roi thúc đặt ngay tầm tay.",
  "mn119:31.2": "Rồi một người đánh xe khéo léo, giỏi điều phục ngựa, leo lên xe, tay trái cầm dây cương, tay phải cầm roi, có thể cho xe chạy đi hướng nào mình muốn, đến nơi nào mình muốn, cũng có thể quay xe lại.",
  "mn119:31.3": "Cũng vậy, này các Tỳ Kheo, bất kỳ ai làm cho sự nhớ biết rõ nơi thân được vun bồi, được làm cho nhiều lên, thì khi người ấy hướng lòng đến điều gì cần tự mình biết rõ và thấy rõ, người ấy có thể tự mình chạm đến điều ấy, khi có nền tảng thích hợp.",
  "mn119:32.1": "Này các Tỳ Kheo, khi sự nhớ biết rõ nơi thân được thực hành, được vun bồi, được làm cho nhiều lên, được dùng như cỗ xe, được đặt làm nền, được làm cho đứng vững, được quen thuộc, được khởi lên khéo léo, thì có thể mong đợi mười điều lợi ích.",
  "mn119:33.1": "Người ấy chịu đựng được sự không vui, không bị sự không vui lấn át; khi sự không vui khởi lên, người ấy sống vượt qua nó.",
  "mn119:34.1": "Người ấy chịu đựng được sợ hãi kinh hoàng, không bị sợ hãi kinh hoàng lấn át; khi sợ hãi kinh hoàng khởi lên, người ấy sống vượt qua nó.",
  "mn119:35.1": "Người ấy chịu đựng được lạnh, nóng, đói, khát, sự chạm xúc của ruồi, muỗi, gió, nắng, loài bò sát; chịu đựng được những lời nói xấu ác, khó nghe; và có thể nhẫn chịu những cảm giác nơi thân đã khởi lên, đau đớn, dữ dội, nhói buốt, gay gắt, khó chịu, không vừa ý, như muốn cướp mạng.",
  "mn119:36.1": "Người ấy đạt được theo ý muốn, không khó khăn, không nhọc nhằn, bốn tầng lắng sâu thuộc tâm cao hơn, là cách sống an vui ngay trong đời này.",
  "mn119:37.1": "Người ấy tự mình trải biết nhiều loại năng lực khác thường: một thân hiện thành nhiều thân, nhiều thân hiện thành một thân; hiện ra … cho đến dùng thân đi lại tự tại cả đến cõi Phạm thiên.",
  "mn119:38.1": "Với tai trời trong sạch, vượt hơn tai người thường, người ấy nghe được cả hai loại tiếng, tiếng cõi trời và tiếng loài người, dù ở xa hay ở gần …",
  "mn119:39.1": "Người ấy dùng lòng mình biết rõ lòng của chúng sinh khác, người khác.",
  "mn119:39.2": "Có lòng còn dính mắc, biết rõ: ‘lòng này còn dính mắc’,",
  "mn119:39.3": "hay lòng đã rời dính mắc …",
  "mn119:39.4": "hay lòng còn giận dữ …",
  "mn119:39.5": "hay lòng đã hết giận dữ …",
  "mn119:39.6": "hay lòng còn mờ tối …",
  "mn119:39.7": "hay lòng đã hết mờ tối …",
  "mn119:39.8": "hay lòng co rút …",
  "mn119:39.9": "hay lòng tán loạn …",
  "mn119:39.10": "hay lòng rộng lớn …",
  "mn119:39.11": "hay lòng không rộng lớn …",
  "mn119:39.12": "hay lòng còn có thể vượt lên hơn nữa …",
  "mn119:39.13": "hay lòng không còn gì cao hơn nữa …",
  "mn119:39.14": "hay lòng yên vững …",
  "mn119:39.15": "hay tâm không yên vững …",
  "mn119:39.16": "hay tâm đã được buông thoát …",
  "mn119:39.17": "hay tâm chưa được buông thoát, vị ấy biết rõ: ‘Tâm chưa được buông thoát.’",
  "mn119:40.1": "Vị ấy nhớ lại nhiều đời sống trước đây theo nhiều cách, như là: một đời, hai đời … như vậy vị ấy nhớ lại nhiều đời sống trước đây với từng nét và từng chi tiết.",
  "mn119:41.1": "Với mắt trời trong sạch, vượt hơn mắt người thường, vị ấy thấy chúng sinh chết đi, sinh ra lại, kẻ thấp kém, người cao đẹp, kẻ đẹp đẽ, người xấu xí, đi về chỗ lành, rơi vào chỗ dữ; vị ấy biết rõ chúng sinh đi theo việc mình đã làm.",
  "mn119:42.1": "Do các dòng chảy ngầm đã dứt sạch, vị ấy ngay trong đời này tự mình biết rõ, tự mình chạm tới và an trú trong sự buông thoát của lòng và sự buông thoát nhờ hiểu rõ, không còn các dòng chảy ngầm.",
  "mn119:43.1": "Này các Tỳ Kheo, khi sự nhớ biết rõ nơi thân được dùng thường xuyên, được nuôi lớn, được làm cho nhiều lên, được lấy làm cỗ xe, được lấy làm nền, được dựng vững, được làm cho quen, được khéo bắt đầu, thì có thể mong đợi mười lợi ích này.",
  "mn119:43.2": "Đức Thế Tôn nói như vậy.",
  "mn119:43.3": "Các Tỳ Kheo vui mừng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn119:43.4": "Kinh Nhớ Biết Rõ Nơi Thân chấm dứt, bài thứ chín."
}
window.BILARA["mn119"]["vi"]["mn119:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
