window.BILARA = window.BILARA || {};
window.BILARA["mn115"] = window.BILARA["mn115"] || {};
window.BILARA["mn115"]["vi"] = {
  "mn115:0.1": "Trung Bộ Kinh 115",
  "mn115:0.2": "Kinh Nhiều Mặt Cấu Thành",
  "mn115:1.1": "Tôi nghe như vầy—",
  "mn115:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, trong rừng Kỳ Đà, tại vườn của ông Cấp Cô Độc.",
  "mn115:1.3": "Tại đó, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn115:1.4": "“Này các Tỳ Kheo.”",
  "mn115:1.5": "Các Tỳ Kheo ấy thưa với Đức Thế Tôn: “Dạ, bạch Ngài.”",
  "mn115:1.6": "Đức Thế Tôn nói như vầy:",
  "mn115:2.1": "“Này các Tỳ Kheo, mọi nỗi sợ hãi nào khởi lên, tất cả đều khởi lên từ người dại, không khởi lên từ người khôn;",
  "mn115:2.2": "mọi tai hại nào khởi lên, tất cả đều khởi lên từ người dại, không khởi lên từ người khôn;",
  "mn115:2.3": "mọi việc rối ren nào khởi lên, tất cả đều khởi lên từ người dại, không khởi lên từ người khôn.",
  "mn115:2.4": "Ví như, này các Tỳ Kheo, khi lửa bén vào một căn chòi bằng sậy hay một căn chòi bằng cỏ, nó có thể đốt luôn cả những ngôi nhà có nóc nhọn đã được trát trong ngoài, kín gió, then cài chắc chắn, cửa nẻo đóng kín;",
  "mn115:2.5": "cũng vậy, này các Tỳ Kheo, mọi nỗi sợ hãi nào khởi lên, tất cả đều khởi lên từ người dại, không khởi lên từ người khôn;",
  "mn115:2.6": "mọi tai hại nào khởi lên, tất cả đều khởi lên từ người dại, không khởi lên từ người khôn;",
  "mn115:2.7": "mọi việc rối ren nào khởi lên, tất cả đều khởi lên từ người dại, không khởi lên từ người khôn.",
  "mn115:2.8": "Vậy nên, này các Tỳ Kheo, người dại là kẻ có sợ hãi, người khôn là kẻ không có sợ hãi;",
  "mn115:2.9": "người dại là kẻ có tai hại, người khôn là kẻ không có tai hại;",
  "mn115:2.10": "người dại là kẻ có rối ren, người khôn là kẻ không có rối ren.",
  "mn115:2.11": "Này các Tỳ Kheo, từ người khôn không có sợ hãi, không có tai hại, không có rối ren.",
  "mn115:2.12": "Vậy nên, này các Tỳ Kheo, các ông hãy học như sau: ‘Chúng ta sẽ là người khôn, biết xem xét kỹ’;",
  "mn115:2.13": "này các Tỳ Kheo, các ông nên học như vậy.”",
  "mn115:3.1": "Khi được nói vậy, ngài A Nan thưa với Đức Thế Tôn:",
  "mn115:3.2": "“Bạch Ngài, đến mức nào thì một Tỳ Kheo khôn được gọi là ‘người biết xem xét kỹ’?”",
  "mn115:3.3": "“Này A Nan, khi một Tỳ Kheo khéo biết các mặt cấu thành, khéo biết các cửa tiếp xúc, khéo biết sự nương nhau mà sinh khởi, khéo biết điều có thể và điều không thể—",
  "mn115:3.4": "đến mức ấy, này A Nan, một Tỳ Kheo khôn được gọi là ‘người biết xem xét kỹ’.”",
  "mn115:4.1": "“Nhưng bạch Ngài, đến mức nào thì được gọi là ‘một Tỳ Kheo khéo biết các mặt cấu thành’?”",
  "mn115:4.2": "“Này A Nan, có mười tám mặt cấu thành này—",
  "mn115:4.3": "mắt, hình sắc, sự thấy biết do mắt;",
  "mn115:4.4": "tai, tiếng, sự nghe biết do tai;",
  "mn115:4.5": "mũi, mùi, sự ngửi biết do mũi;",
  "mn115:4.6": "yếu tố lưỡi, yếu tố vị, yếu tố biết bằng lưỡi;",
  "mn115:4.7": "yếu tố thân, yếu tố chạm xúc, yếu tố biết bằng thân;",
  "mn115:4.8": "yếu tố ý, yếu tố những gì được ý biết, yếu tố biết bằng ý.",
  "mn115:4.9": "Này A-nan, khi nào vị ấy biết và thấy rõ mười tám yếu tố này—",
  "mn115:4.10": "đến mức ấy cũng đủ để nói: ‘Tỳ Kheo khéo rõ các yếu tố’.",
  "mn115:5.1": "“Nhưng, bạch Thế Tôn, còn cách nào khác nữa để có thể nói rằng: ‘Tỳ Kheo khéo rõ các yếu tố’ không?”",
  "mn115:5.2": "“Có, này A-nan.",
  "mn115:5.3": "Này A-nan, có sáu yếu tố này—",
  "mn115:5.4": "yếu tố đất, yếu tố nước, yếu tố lửa, yếu tố gió, yếu tố khoảng trống, yếu tố biết.",
  "mn115:5.5": "Này A-nan, khi nào vị ấy biết và thấy rõ sáu yếu tố này—",
  "mn115:5.6": "đến mức ấy cũng đủ để nói: ‘Tỳ Kheo khéo rõ các yếu tố’.",
  "mn115:6.1": "“Nhưng, bạch Thế Tôn, còn cách nào khác nữa để có thể nói rằng: ‘Tỳ Kheo khéo rõ các yếu tố’ không?”",
  "mn115:6.2": "“Có, này A-nan.",
  "mn115:6.3": "Này A-nan, có sáu yếu tố này—",
  "mn115:6.4": "yếu tố dễ chịu, yếu tố đau đớn, yếu tố vui trong lòng, yếu tố buồn trong lòng, yếu tố bình thản, yếu tố không biết rõ.",
  "mn115:6.5": "Này A-nan, khi nào vị ấy biết và thấy rõ sáu yếu tố này—",
  "mn115:6.6": "đến mức ấy cũng đủ để nói: ‘Tỳ Kheo khéo rõ các yếu tố’.",
  "mn115:7.1": "“Nhưng, bạch Thế Tôn, còn cách nào khác nữa để có thể nói rằng: ‘Tỳ Kheo khéo rõ các yếu tố’ không?”",
  "mn115:7.2": "“Có, này A-nan.",
  "mn115:7.3": "Này A-nan, có sáu yếu tố này—",
  "mn115:7.4": "yếu tố ham muốn giác quan, yếu tố lìa bỏ ham muốn giác quan, yếu tố bực bội, yếu tố không bực bội, yếu tố làm hại, yếu tố không làm hại.",
  "mn115:7.5": "Này A-nan, khi nào vị ấy biết và thấy rõ sáu yếu tố này—",
  "mn115:7.6": "đến mức ấy cũng đủ để nói: ‘Tỳ Kheo khéo rõ các yếu tố’.",
  "mn115:8.1": "“Nhưng, bạch Thế Tôn, còn cách nào khác nữa để có thể nói rằng: ‘Tỳ Kheo khéo rõ các yếu tố’ không?”",
  "mn115:8.2": "“Có, này A-nan.",
  "mn115:8.3": "Này A-nan, có ba yếu tố này—",
  "mn115:8.4": "yếu tố ham muốn giác quan, yếu tố sắc thân, yếu tố không có sắc thân.",
  "mn115:8.5": "Này A-nan, khi nào vị ấy biết và thấy rõ ba yếu tố này—",
  "mn115:8.6": "đến mức ấy cũng đủ để nói: ‘Tỳ Kheo khéo rõ các yếu tố’.",
  "mn115:9.1": "“Nhưng, bạch Thế Tôn, còn cách nào khác nữa để có thể nói rằng: ‘Tỳ Kheo khéo rõ các yếu tố’ không?”",
  "mn115:9.2": "“Có thể vậy, này A-nan.",
  "mn115:9.3": "Này A-nan, có hai giới này—",
  "mn115:9.4": "giới do tạo thành và giới không do tạo thành.",
  "mn115:9.5": "Này A-nan, khi nào vị ấy biết và thấy hai giới này—",
  "mn115:9.6": "thì như vậy cũng đủ để nói rằng: ‘Tỳ Kheo khéo biết về các giới’.”",
  "mn115:10.1": "“Nhưng đến mức nào, bạch Đức Thế Tôn, thì được gọi là ‘Tỳ Kheo khéo biết về các chỗ’?”",
  "mn115:10.2": "“Này A-nan, có sáu chỗ bên trong và bên ngoài này—",
  "mn115:10.3": "mắt và hình sắc, tai và tiếng, mũi và mùi, lưỡi và vị, thân và sự chạm đụng, ý và các việc trong tâm.",
  "mn115:10.4": "Này A-nan, khi nào vị ấy biết và thấy sáu chỗ bên trong và bên ngoài này—",
  "mn115:10.5": "thì như vậy đủ để nói rằng: ‘Tỳ Kheo khéo biết về các chỗ’.”",
  "mn115:11.1": "“Nhưng đến mức nào, bạch Đức Thế Tôn, thì được gọi là ‘Tỳ Kheo khéo biết về nương nhau mà sinh khởi’?”",
  "mn115:11.2": "“Ở đây, này A-nan, một Tỳ Kheo hiểu rõ như vầy:",
  "mn115:11.3": "‘Cái này có thì cái kia có, cái này sinh lên thì cái kia sinh lên,",
  "mn115:11.4": "cái này không có thì cái kia không có, cái này dừng thì cái kia dừng, đó là—",
  "mn115:11.5": "do không sáng tỏ nên có các hoạt động của tâm,",
  "mn115:11.6": "do các hoạt động của tâm nên có sự nhận biết,",
  "mn115:11.7": "do sự nhận biết nên có tên gọi và hình vóc,",
  "mn115:11.8": "do tên gọi và hình vóc nên có sáu chỗ,",
  "mn115:11.9": "do sáu chỗ nên có sự đụng chạm,",
  "mn115:11.10": "do sự đụng chạm nên có cảm nhận,",
  "mn115:11.11": "do cảm nhận nên có ham muốn,",
  "mn115:11.12": "do ham muốn nên có nắm giữ,",
  "mn115:11.13": "do nắm giữ nên có trở thành,",
  "mn115:11.14": "do trở thành nên có sinh ra,",
  "mn115:11.15": "do sinh ra nên có già chết, buồn, than khóc, khổ đau, bứt rứt trong lòng và quẫn bách sinh ra.",
  "mn115:11.16": "Như vậy là sự sinh khởi của cả khối khổ đau này.",
  "mn115:11.17": "Nhưng do không sáng tỏ phai hẳn và dừng hẳn, không còn sót, nên các hoạt động của tâm dừng,",
  "mn115:11.18": "do các hoạt động của tâm dừng nên sự nhận biết dừng,",
  "mn115:11.19": "do sự nhận biết dừng nên tên gọi và hình vóc dừng,",
  "mn115:11.20": "do tên gọi và hình vóc dừng nên sáu chỗ dừng,",
  "mn115:11.21": "Do sáu cửa giác quan lắng dứt nên sự đụng chạm lắng dứt,",
  "mn115:11.22": "do sự đụng chạm lắng dứt nên cảm nhận lắng dứt,",
  "mn115:11.23": "do cảm nhận lắng dứt nên sự ham muốn lắng dứt,",
  "mn115:11.24": "do sự ham muốn lắng dứt nên sự nắm giữ lắng dứt,",
  "mn115:11.25": "do sự nắm giữ lắng dứt nên sự trở thành lắng dứt,",
  "mn115:11.26": "do sự trở thành lắng dứt nên sự sinh ra lắng dứt,",
  "mn115:11.27": "do sự sinh ra lắng dứt nên già, chết, buồn, than khóc, khổ đau, bứt rứt và quẫn bách đều lắng dứt.",
  "mn115:11.28": "Như vậy là toàn bộ khối khổ đau này lắng dứt.’",
  "mn115:11.29": "Đến mức này, này A-nan, có thể nói: ‘Tỳ Kheo khéo hiểu duyên nương nhau mà sinh khởi.’”",
  "mn115:12.1": "“Nhưng, bạch Thế Tôn, đến mức nào thì có thể nói: ‘Tỳ Kheo khéo biết điều nào có thể, điều nào không thể’?”",
  "mn115:12.2": "“Này A-nan, ở đây một Tỳ Kheo biết rõ: ‘Không thể có chuyện, không có cách nào, một người có thấy đúng lại cho bất cứ cái gì được tạo thành là bền mãi; chuyện ấy không có.’",
  "mn115:12.3": "Và vị ấy biết rõ: ‘Nhưng có thể có chuyện người thường cho một cái gì được tạo thành là bền mãi; chuyện ấy có thể có.’",
  "mn115:12.4": "Vị ấy biết rõ: ‘Không thể có chuyện, không có cách nào, một người có thấy đúng lại cho bất cứ cái gì được tạo thành là vui sướng; chuyện ấy không có.’",
  "mn115:12.5": "Và vị ấy biết rõ: ‘Nhưng có thể có chuyện người thường cho một cái gì được tạo thành là vui sướng; chuyện ấy có thể có.’",
  "mn115:12.6": "Vị ấy biết rõ: ‘Không thể có chuyện, không có cách nào, một người có thấy đúng lại cho bất cứ điều gì là mình; chuyện ấy không có.’",
  "mn115:12.7": "Và vị ấy biết rõ: ‘Nhưng có thể có chuyện người thường cho một điều gì đó là mình; chuyện ấy có thể có.’",
  "mn115:13.1": "Vị ấy biết rõ: ‘Không thể có chuyện, không có cách nào, một người có thấy đúng lại giết mẹ mình; chuyện ấy không có.’",
  "mn115:13.2": "Và vị ấy biết rõ: ‘Nhưng có thể có chuyện người thường giết mẹ mình; chuyện ấy có thể có.’",
  "mn115:13.3": "Vị ấy biết rõ: ‘Không thể có chuyện, không có cách nào, một người có thấy đúng lại giết cha mình …",
  "mn115:13.4": "giết một bậc đã dứt sạch ô nhiễm; chuyện ấy có thể có.’",
  "mn115:13.5": "Vị ấy biết rõ: ‘Không thể có chuyện, không có cách nào, một người có thấy đúng lại với lòng dữ làm chảy máu Như Lai; chuyện ấy không có.’",
  "mn115:13.6": "Và vị ấy biết rõ: ‘Nhưng có thể có chuyện người thường với lòng dữ làm chảy máu Như Lai; chuyện ấy có thể có.’",
  "mn115:13.7": "Vị ấy biết rõ: ‘Không thể có chuyện, không có cách nào, một người có thấy đúng lại chia rẽ Tăng chúng; chuyện ấy không có.’",
  "mn115:13.8": "Và vị ấy biết rõ: ‘Nhưng có thể có chuyện người thường chia rẽ Tăng chúng; chuyện ấy có thể có.’",
  "mn115:13.9": "Vị ấy biết rõ: ‘Không thể có chuyện, không có cách nào, một người có thấy đúng lại theo một bậc thầy khác; chuyện ấy không có.’",
  "mn115:13.10": "Và vị ấy biết rõ: ‘Nhưng có thể có chuyện người thường theo một bậc thầy khác; chuyện ấy có thể có.’",
  "mn115:14.1": "Vị ấy biết rõ: ‘Không thể có chuyện, không có cách nào, trong một thế giới lại cùng lúc xuất hiện hai bậc Giác Ngộ trọn vẹn, tự mình biết khắp, không trước không sau; chuyện ấy không có.’",
  "mn115:14.2": "Và vị ấy biết rõ: ‘Nhưng có thể có chuyện trong một thế giới chỉ có một bậc Giác Ngộ trọn vẹn, tự mình biết khắp xuất hiện; chuyện ấy có thể có.’",
  "mn115:14.3": "Vị ấy biết rõ: ‘Không thể có chuyện, không có cách nào, trong một thế giới lại cùng lúc xuất hiện hai vua chuyển luân, không trước không sau; chuyện ấy không có.’",
  "mn115:14.4": "Và vị ấy biết rõ: ‘Nhưng có thể có chuyện trong một thế giới chỉ có một vua chuyển luân xuất hiện; chuyện ấy có thể có.’",
  "mn115:15.1": "Người ấy hiểu rõ: ‘Không thể có chuyện một người nữ là bậc A-la-hán, bậc Giác Ngộ trọn vẹn; chuyện ấy không có.’",
  "mn115:15.2": "Người ấy hiểu rõ: ‘Có thể có chuyện một người nam là bậc A-la-hán, bậc Giác Ngộ trọn vẹn; chuyện ấy có.’",
  "mn115:15.3": "Người ấy hiểu rõ: ‘Không thể có chuyện một người nữ là vua chuyển luân; chuyện ấy không có.’",
  "mn115:15.4": "Người ấy hiểu rõ: ‘Có thể có chuyện một người nam là vua chuyển luân; chuyện ấy có.’",
  "mn115:15.5": "Người ấy hiểu rõ: ‘Không thể có chuyện một người nữ làm vua cõi trời Đế Thích, làm Ma vương, làm Phạm thiên; chuyện ấy không có.’",
  "mn115:15.6": "Người ấy hiểu rõ: ‘Có thể có chuyện một người nam làm vua cõi trời Đế Thích, làm Ma vương, làm Phạm thiên; chuyện ấy có.’",
  "mn115:16.1": "Người ấy hiểu rõ: ‘Không thể có chuyện việc làm xấu bằng thân lại đưa đến kết quả vừa ý, đáng ưa, dễ chịu; chuyện ấy không có.’",
  "mn115:16.2": "Người ấy hiểu rõ: ‘Có thể có chuyện việc làm xấu bằng thân đưa đến kết quả không vừa ý, không đáng ưa, khó chịu; chuyện ấy có.’",
  "mn115:16.3": "Người ấy hiểu rõ: ‘Không thể có chuyện việc làm xấu bằng lời nói ...’",
  "mn115:16.4": "‘Không thể có chuyện việc làm xấu bằng ý lại đưa đến kết quả vừa ý, đáng ưa, dễ chịu; chuyện ấy không có.’",
  "mn115:16.5": "Người ấy hiểu rõ: ‘Có thể có chuyện việc làm xấu bằng lời nói ...’",
  "mn115:16.6": "‘Có thể có chuyện việc làm xấu bằng ý đưa đến kết quả không vừa ý, không đáng ưa, khó chịu; chuyện ấy có.’",
  "mn115:17.1": "Người ấy hiểu rõ: ‘Không thể có chuyện việc làm lành bằng thân lại đưa đến kết quả không vừa ý, không đáng ưa, khó chịu; chuyện ấy không có.’",
  "mn115:17.2": "Người ấy hiểu rõ: ‘Có thể có chuyện việc làm lành bằng thân đưa đến kết quả vừa ý, đáng ưa, dễ chịu; chuyện ấy có.’",
  "mn115:17.3": "Người ấy hiểu rõ: ‘Không thể có chuyện việc làm lành bằng lời nói ...’",
  "mn115:17.4": "‘Không thể có chuyện việc làm lành bằng ý lại đưa đến kết quả không vừa ý, không đáng ưa, khó chịu; chuyện ấy không có.’",
  "mn115:17.5": "Người ấy hiểu rõ: ‘Có thể có chuyện việc làm lành bằng lời nói ...’",
  "mn115:17.6": "‘Có thể có chuyện việc làm lành bằng ý đưa đến kết quả vừa ý, đáng ưa, dễ chịu; chuyện ấy có.’",
  "mn115:18.1": "Người ấy hiểu rõ: ‘Không thể có chuyện người sống với việc làm xấu bằng thân, do đó, vì đó, khi thân tan rã, sau khi chết, lại sinh vào cõi lành, cõi trời; chuyện ấy không có.’",
  "mn115:18.2": "Người ấy hiểu rõ: ‘Có thể có chuyện người sống với việc làm xấu bằng thân, do đó, vì đó, khi thân tan rã, sau khi chết, sinh vào cảnh khổ, chốn dữ, chỗ sa đọa, địa ngục; chuyện ấy có.’",
  "mn115:19.1": "Người ấy hiểu rõ: ‘Không thể có chuyện người sống với việc làm xấu bằng lời nói ...’",
  "mn115:19.2": "‘Không thể có chuyện người sống với việc làm xấu bằng ý, do đó, vì đó, khi thân tan rã, sau khi chết, lại sinh vào cõi lành, cõi trời; chuyện ấy không có.’",
  "mn115:19.3": "Người ấy hiểu rõ: ‘Có thể có chuyện người sống với việc làm xấu bằng lời nói ...’",
  "mn115:19.4": "‘Có thể có chuyện người sống với việc làm xấu bằng ý, do đó, vì đó, khi thân tan rã, sau khi chết, sinh vào cảnh khổ, chốn dữ, chỗ sa đọa, địa ngục; chuyện ấy có.’",
  "mn115:19.5": "Người ấy hiểu rõ: ‘Không thể có chuyện người sống với việc làm lành bằng thân, do đó, vì đó, khi thân tan rã, sau khi chết, lại sinh vào cảnh khổ, chốn dữ, chỗ sa đọa, địa ngục; chuyện ấy không có.’",
  "mn115:19.6": "Người ấy hiểu rõ: ‘Có thể có chuyện người sống với việc làm lành bằng thân, do đó, vì đó, khi thân tan rã, sau khi chết, sinh vào cõi lành, cõi trời; chuyện ấy có.’",
  "mn115:19.7": "Người ấy hiểu rõ: ‘Không thể có chuyện người sống với việc làm lành bằng lời nói ...’",
  "mn115:19.8": "‘Không thể có chuyện người sống với việc làm lành bằng ý, do đó, vì đó, khi thân tan rã, sau khi chết, lại sinh vào cảnh khổ, chốn dữ, chỗ sa đọa, địa ngục; chuyện ấy không có.’",
  "mn115:19.9": "Người ấy hiểu rõ: ‘Có thể có chuyện người sống với việc làm lành bằng lời nói ...’",
  "mn115:19.10": "‘Có thể có chuyện người sống với việc làm lành bằng ý, do đó, vì đó, khi thân tan rã, sau khi chết, sinh vào cõi lành, cõi trời; chuyện ấy có.’",
  "mn115:19.11": "Đến mức này, này A-nan, cũng đủ để nói rằng: ‘Tỳ Kheo khéo biết điều gì có thể có và điều gì không thể có.’",
  "mn115:20.1": "Khi được nói vậy, ngài A-nan thưa với Đức Thế Tôn rằng:",
  "mn115:20.2": "“Thật lạ lùng, bạch Thế Tôn, thật ít có, bạch Thế Tôn.",
  "mn115:20.3": "Bạch Thế Tôn, bài chỉ dạy này tên là gì?”",
  "mn115:20.4": "“Vậy thì, này A-nan, con hãy ghi nhớ bài chỉ dạy này là ‘Nhiều phần’, cũng hãy ghi nhớ là ‘Bốn vòng xoay’, cũng hãy ghi nhớ là ‘Gương soi lẽ thật’, cũng hãy ghi nhớ là ‘Trống vang của cái không chết’, cũng hãy ghi nhớ là ‘Chiến thắng hơn hết trong cuộc chiến’.”",
  "mn115:20.5": "Đức Thế Tôn nói như vậy.",
  "mn115:20.6": "Ngài A-nan vui lòng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn115:20.7": "Kinh Nhiều phần, bài thứ năm, đến đây là xong."
}
window.BILARA["mn115"]["vi"]["mn115:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
