window.BILARA = window.BILARA || {};
window.BILARA["mn112"] = window.BILARA["mn112"] || {};
window.BILARA["mn112"]["vi"] = {
  "mn112:0.1": "Trung Bộ Kinh 112",
  "mn112:0.2": "Kinh Sáu Cách Xét Trong Sạch",
  "mn112:1.1": "Tôi nghe như vầy—",
  "mn112:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, tại Kỳ Viên, trong vườn của ông Cấp Cô Độc.",
  "mn112:1.3": "Tại đó, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn112:1.4": "“Này các Tỳ Kheo.”",
  "mn112:1.5": "Các Tỳ Kheo ấy thưa với Đức Thế Tôn: “Dạ, bạch Đức Thế Tôn.”",
  "mn112:1.6": "Đức Thế Tôn nói như vầy:",
  "mn112:2.1": "“Này các Tỳ Kheo, ở đây có một Tỳ Kheo tự nói về mình rằng:",
  "mn112:2.2": "‘Sự sinh ra đã dứt, đời sống phạm hạnh đã sống xong, việc cần làm đã làm xong, không còn trở lui trạng thái này nữa, tôi biết rõ như vậy.’",
  "mn112:3.1": "Này các Tỳ Kheo, lời nói của vị Tỳ Kheo ấy không nên vội mừng, cũng không nên chê bỏ.",
  "mn112:3.2": "Không vội mừng, không chê bỏ, mà nên hỏi như sau:",
  "mn112:3.3": "Này hiền giả, đối với cái được nghe …",
  "mn112:3.4": "Bốn cách ấy là gì?",
  "mn112:3.5": "Nói về cái được thấy như cái được thấy, nói về cái được nghe như cái được nghe, nói về cái được cảm nhận như cái được cảm nhận, nói về cái được biết như cái được biết—",
  "mn112:3.6": "này hiền giả, đó là bốn cách nói đã được Đức Thế Tôn, bậc biết rõ, thấy rõ, bậc đáng kính, bậc tự mình giác ngộ trọn vẹn, chỉ dạy đúng đắn.",
  "mn112:3.7": "Vậy thì, với sự biết thế nào, với sự thấy thế nào, mà đối với bốn cách nói này, tâm của ngài được buông ra khỏi các dòng rỉ chảy vì không còn nắm giữ?’",
  "mn112:4.1": "Này các Tỳ Kheo, với một Tỳ Kheo đã dứt sạch các dòng rỉ chảy, đã sống xong đời sống phạm hạnh, đã làm xong việc cần làm, đã đặt gánh nặng xuống, đã đạt tới điều tốt đẹp cho mình, đã dứt sạch trói buộc của đời sống, đã được buông ra nhờ biết đúng trọn vẹn, thì đây là cách trả lời hợp với lẽ:",
  "mn112:4.2": "‘Này hiền giả, đối với cái được thấy, tôi sống không đến gần, không lùi xa, không nương tựa, không bị buộc dính, được buông ra, không bị trói cột, với tâm không còn bờ mé.",
  "mn112:4.4": "Này hiền giả, đối với cái được cảm nhận …",
  "mn112:4.5": "Này hiền giả, đối với cái được biết, tôi sống không đến gần, không lùi xa, không nương tựa, không bị buộc dính, được buông ra, không bị trói cột, với tâm không còn bờ mé.",
  "mn112:4.6": "Này hiền giả, với sự biết như vậy, với sự thấy như vậy, đối với bốn cách nói này, tâm tôi được buông ra khỏi các dòng rỉ chảy vì không còn nắm giữ.’",
  "mn112:5.1": "Này các Tỳ Kheo, lời nói của vị Tỳ Kheo ấy rằng ‘Lành thay’ thì nên vui nhận và tán thành.",
  "mn112:5.2": "Sau khi vui nhận và tán thành lời nói ‘Lành thay’, nên hỏi thêm câu nữa:",
  "mn112:5.3": "‘Này hiền giả, có năm nhóm bị nắm giữ đã được Đức Thế Tôn, bậc biết rõ, thấy rõ, bậc đáng kính, bậc tự mình giác ngộ trọn vẹn, chỉ dạy đúng đắn.",
  "mn112:5.4": "Năm nhóm ấy là gì?",
  "mn112:5.5": "Đó là: nhóm thân bị nắm giữ, nhóm cảm giác bị nắm giữ, nhóm ghi nhận bị nắm giữ, nhóm các hoạt động của tâm bị nắm giữ, nhóm sự nhận biết bị nắm giữ—",
  "mn112:5.6": "này hiền giả, đó là năm nhóm bị nắm giữ đã được Đức Thế Tôn, bậc biết rõ, thấy rõ, bậc đáng kính, bậc tự mình giác ngộ trọn vẹn, chỉ dạy đúng đắn.",
  "mn112:5.7": "Vậy thì, với sự biết thế nào, với sự thấy thế nào, mà đối với năm nhóm bị nắm giữ này, tâm của ngài được buông ra khỏi các dòng rỉ chảy vì không còn nắm giữ?’",
  "mn112:6.1": "Này các Tỳ Kheo, với vị Tỳ Kheo đã dứt sạch các lậu hoặc, đã sống xong đời sống tu, đã làm xong việc cần làm, đã đặt gánh nặng xuống, đã đạt tới điều tốt đẹp cho mình, đã dứt sạch trói buộc của đời sống, đã được giải thoát nhờ hiểu đúng như thật, thì đây là lời nói hợp với lẽ để tự nói lên sự hiểu biết của mình:",
  "mn112:6.2": "‘Này hiền giả, tôi biết sắc là yếu ớt, phai tàn, không đáng nương tựa; nên những bám víu, nắm giữ, chỗ tâm đứng lại, dính mắc và xu hướng ngầm nơi sắc, do chúng hết đi, phai tàn, lặng dứt, buông ra, thả xuống, tôi biết tâm tôi đã được giải thoát.",
  "mn112:6.3": "Này hiền giả, tôi biết cảm giác …",
  "mn112:6.4": "Này hiền giả, tôi biết tưởng …",
  "mn112:6.5": "Này hiền giả, tôi biết các hoạt động của tâm …",
  "mn112:6.6": "Này hiền giả, tôi biết sự nhận biết là yếu ớt, phai tàn, không đáng nương tựa; nên những bám víu, nắm giữ, chỗ tâm đứng lại, dính mắc và xu hướng ngầm nơi sự nhận biết, do chúng hết đi, phai tàn, lặng dứt, buông ra, thả xuống, tôi biết tâm tôi đã được giải thoát.",
  "mn112:6.7": "Này hiền giả, do biết như vậy, thấy như vậy, đối với năm nhóm bị nắm giữ này, vì không còn chấp lấy nên tâm tôi được giải thoát khỏi các lậu hoặc.’",
  "mn112:7.1": "Này các Tỳ Kheo, lời nói của vị Tỳ Kheo ấy: ‘Lành thay’ cần được vui nhận và tán thành.",
  "mn112:7.2": "Sau khi vui nhận và tán thành lời nói: ‘Lành thay’, nên hỏi thêm câu hỏi cao hơn.",
  "mn112:7.3": "‘Này hiền giả, có sáu thể tính này đã được Đức Thế Tôn, bậc biết rõ, thấy rõ, bậc A-la-hán, bậc tự mình giác ngộ trọn vẹn, chỉ bày đúng đắn.",
  "mn112:7.4": "Sáu là những gì?",
  "mn112:7.5": "Thể cứng, thể nước, thể nóng, thể động, thể trống không, thể nhận biết—",
  "mn112:7.6": "này hiền giả, đó là sáu thể tính đã được Đức Thế Tôn, bậc biết rõ, thấy rõ, bậc A-la-hán, bậc tự mình giác ngộ trọn vẹn, chỉ bày đúng đắn.",
  "mn112:7.7": "Này hiền giả, vị đáng kính biết thế nào, thấy thế nào mà đối với sáu thể tính này, vì không còn chấp lấy nên tâm được giải thoát khỏi các lậu hoặc?’",
  "mn112:8.1": "Này các Tỳ Kheo, với vị Tỳ Kheo đã dứt sạch các lậu hoặc, đã sống xong đời sống tu, đã làm xong việc cần làm, đã đặt gánh nặng xuống, đã đạt tới điều tốt đẹp cho mình, đã dứt sạch trói buộc của đời sống, đã được giải thoát nhờ hiểu đúng như thật, thì đây là lời nói hợp với lẽ để tự nói lên sự hiểu biết của mình:",
  "mn112:8.2": "‘Này hiền giả, tôi không xem thể cứng là mình, cũng không xem mình là cái nương trên thể cứng.",
  "mn112:8.3": "Và những bám víu, nắm giữ, chỗ tâm đứng lại, dính mắc và xu hướng ngầm nương trên thể cứng, do chúng hết đi, phai tàn, lặng dứt, buông ra, thả xuống, tôi biết tâm tôi đã được giải thoát.",
  "mn112:8.4": "Này hiền giả, tôi không xem thể nước là mình …",
  "mn112:8.5": "Này hiền giả, tôi không xem thể nóng là mình …",
  "mn112:8.6": "Này hiền giả, tôi không xem thể động là mình …",
  "mn112:8.7": "Này hiền giả, tôi không xem thể trống không là mình …",
  "mn112:8.8": "Này hiền giả, tôi không xem thể nhận biết là mình, cũng không xem mình là cái nương trên thể nhận biết.",
  "mn112:8.9": "Và những bám víu, nắm giữ, chỗ tâm đứng lại, dính mắc và xu hướng ngầm nương trên thể nhận biết, do chúng hết đi, phai tàn, lặng dứt, buông ra, thả xuống, tôi biết tâm tôi đã được giải thoát.",
  "mn112:8.10": "Này hiền giả, do biết như vậy, thấy như vậy, đối với sáu thể tính này, vì không còn chấp lấy nên tâm tôi được giải thoát khỏi các lậu hoặc.’",
  "mn112:9.1": "Này các Tỳ Kheo, lời nói của vị Tỳ Kheo ấy: ‘Lành thay’ cần được vui nhận và tán thành.",
  "mn112:9.2": "Sau khi vui nhận và tán thành lời nói: ‘Lành thay’, nên hỏi thêm câu hỏi cao hơn.",
  "mn112:9.3": "‘Này hiền giả, lại có sáu chỗ bên trong và bên ngoài này đã được Đức Thế Tôn, bậc biết rõ, thấy rõ, bậc A-la-hán, bậc tự mình giác ngộ trọn vẹn, chỉ bày đúng đắn.",
  "mn112:9.4": "Sáu là những gì?",
  "mn112:9.5": "Mắt và hình sắc, tai và tiếng, mũi và mùi, lưỡi và vị, thân và cái chạm, ý và các điều được ý biết—",
  "mn112:9.6": "này hiền giả, đó là sáu chỗ bên trong và bên ngoài đã được Đức Thế Tôn, bậc biết rõ, thấy rõ, bậc A-la-hán, bậc tự mình giác ngộ trọn vẹn, chỉ bày đúng đắn.’",
  "mn112:9.7": "Nhưng thưa ngài, biết thế nào, thấy thế nào mà đối với sáu chỗ tiếp xúc bên trong và bên ngoài này, tâm được buông ra, không còn nắm giữ, thoát khỏi các dòng rỉ chảy?",
  "mn112:10.1": "Này các Tỳ Kheo, với vị Tỳ Kheo đã dứt sạch các dòng rỉ chảy, đã sống xong đời sống tu, đã làm xong việc cần làm, đã đặt gánh nặng xuống, đã đạt tới điều tốt đẹp của mình, đã dứt sạch trói buộc của đời sống, đã được buông ra nhờ hiểu đúng, thì đây là cách trả lời hợp với lẽ:",
  "mn112:10.2": "‘Thưa hiền giả, đối với mắt, hình sắc, sự thấy bằng mắt, và những gì được sự thấy bằng mắt nhận ra, mọi ưa thích, mọi say đắm, mọi thích thú, mọi khát khao, cùng mọi cách vin vào, mọi nắm giữ, mọi chỗ tâm đứng lại, bám chặt và ngấm ngầm nằm sâu, khi những thứ ấy tàn hết, phai hết, dứt hẳn, được buông ra, được thả xuống, thì tôi biết rõ: tâm tôi đã được buông ra.",
  "mn112:10.3": "Thưa hiền giả, đối với tai, tiếng, sự nghe bằng tai …",
  "mn112:10.4": "thưa hiền giả, đối với mũi, mùi, sự ngửi bằng mũi …",
  "mn112:10.5": "thưa hiền giả, đối với lưỡi, vị, sự nếm bằng lưỡi …",
  "mn112:10.6": "thưa hiền giả, đối với thân, sự chạm, sự biết qua thân …",
  "mn112:10.7": "thưa hiền giả, đối với ý, những gì ý nhận ra, sự biết bằng ý, và những gì được sự biết bằng ý nhận ra, mọi ưa thích, mọi say đắm, mọi thích thú, mọi khát khao, cùng mọi cách vin vào, mọi nắm giữ, mọi chỗ tâm đứng lại, bám chặt và ngấm ngầm nằm sâu, khi những thứ ấy tàn hết, phai hết, dứt hẳn, được buông ra, được thả xuống, thì tôi biết rõ: tâm tôi đã được buông ra.’",
  "mn112:10.8": "Thưa hiền giả, biết như vậy, thấy như vậy, đối với sáu chỗ tiếp xúc bên trong và bên ngoài này, tâm tôi được buông ra, không còn nắm giữ, thoát khỏi các dòng rỉ chảy.’",
  "mn112:11.1": "Này các Tỳ Kheo, lời nói của vị Tỳ Kheo ấy: ‘Lành thay’ cần được vui nhận và tán thành.",
  "mn112:11.2": "Sau khi vui nhận và tán thành lời nói: ‘Lành thay’, nên hỏi thêm câu nữa:",
  "mn112:11.3": "‘Nhưng thưa ngài, biết thế nào, thấy thế nào mà trong thân này có sự nhận biết, và đối với mọi dấu hiệu ở bên ngoài, cái nghĩ “ta”, cái nghĩ “của ta”, và thói ngầm hơn thua đều bị nhổ sạch?’",
  "mn112:12.1": "Này các Tỳ Kheo, với vị Tỳ Kheo đã dứt sạch các dòng rỉ chảy, đã sống xong đời sống tu, đã làm xong việc cần làm, đã đặt gánh nặng xuống, đã đạt tới điều tốt đẹp của mình, đã dứt sạch trói buộc của đời sống, đã được buông ra nhờ hiểu đúng, thì đây là cách trả lời hợp với lẽ:",
  "mn112:12.2": "‘Trước kia, thưa hiền giả, khi còn sống ở nhà, tôi là người không thấy rõ.",
  "mn112:12.3": "Rồi Đức Thế Tôn hoặc một người học theo Đức Thế Tôn đã chỉ bày lẽ thật cho tôi.",
  "mn112:12.4": "Sau khi nghe lẽ thật ấy, tôi có lòng tin nơi Đức Thế Tôn.",
  "mn112:12.5": "Có được lòng tin ấy rồi, tôi suy nghĩ như vầy:",
  "mn112:12.6": "“Đời sống ở nhà chật hẹp, đầy bụi bặm; đời sống ra đi là khoảng trời rộng mở.",
  "mn112:12.7": "Sống ở nhà không dễ gì sống trọn vẹn, sống thật trong sạch, sống đời giữ mình như vỏ ốc được mài nhẵn.",
  "mn112:12.8": "Hay là ta cạo bỏ tóc râu, khoác áo nhuộm màu đất, rời nhà, sống không nhà.”",
  "mn112:13.1": "Thưa hiền giả, rồi sau một thời gian, tôi bỏ lại ít của cải hay nhiều của cải, bỏ lại ít bà con hay nhiều bà con, cạo bỏ tóc râu, khoác áo nhuộm màu đất, rời nhà, sống không nhà.",
  "mn112:13.2": "Sau khi ra đi như vậy, tôi sống theo nếp học và nếp sống của các Tỳ Kheo, từ bỏ giết hại, tránh xa giết hại, bỏ gậy, bỏ dao, biết hổ thẹn, có lòng thương, sống thương xót vì điều lành cho mọi loài có sự sống.",
  "mn112:13.3": "Từ bỏ lấy của không cho, tránh xa lấy của không cho, chỉ nhận cái được cho, mong cái được cho, tự sống trong sạch, không trộm cướp.",
  "mn112:13.4": "Từ bỏ lối sống không trong sạch, tôi sống đời giữ mình, sống xa, tránh hẳn việc trai gái của người đời.",
  "mn112:13.5": "Từ bỏ nói dối, tránh xa nói dối, tôi nói thật, gắn với sự thật, vững chắc, đáng tin, không lừa dối đời.",
  "mn112:13.6": "Từ bỏ lời nói chia rẽ, tránh xa lời nói chia rẽ; nghe ở đây, tôi không đem nói ở kia để làm họ tan rẽ; nghe ở kia, tôi không đem nói ở đây để làm người này tan rẽ. Như vậy, tôi nối lại những người đã rạn nứt, giúp thêm cho những người đang thuận hòa, ưa sự thuận hòa, vui với sự thuận hòa, thích sự thuận hòa, và nói lời đưa đến thuận hòa.",
  "mn112:13.7": "Từ bỏ lời nói thô ác, tránh xa lời nói thô ác; tôi nói những lời êm dịu, lọt tai, dễ mến, chạm lòng, nhã nhặn, được nhiều người ưa thích, nhiều người vừa ý.",
  "mn112:13.8": "Từ bỏ nói nhảm, tránh xa nói nhảm; tôi nói đúng lúc, nói điều thật, nói điều có ích, nói đúng lẽ thật, nói đúng nếp sống; lời nói có chừng mực, có nền nếp, có ích, đúng lúc.",
  "mn112:14.1": "Tôi tránh làm hại hạt giống và cây cỏ, ăn một bữa một ngày, không ăn ban đêm, tránh ăn không đúng giờ.",
  "mn112:14.2": "Tôi tránh xem múa, hát, nhạc, và các trò diễn.",
  "mn112:14.3": "Tôi đã tránh xa việc dùng vòng hoa, hương thơm, dầu thơm, đồ làm đẹp và đồ trang sức.",
  "mn112:14.4": "Tôi đã tránh xa giường cao và giường sang trọng.",
  "mn112:14.5": "Tôi đã tránh xa việc nhận vàng bạc,",
  "mn112:14.6": "đã tránh xa việc nhận lúa thóc còn sống,",
  "mn112:14.7": "đã tránh xa việc nhận thịt sống;",
  "mn112:14.8": "đã tránh xa việc nhận đàn bà và thiếu nữ,",
  "mn112:14.9": "đã tránh xa việc nhận tôi trai tớ gái,",
  "mn112:14.10": "đã tránh xa việc nhận dê và cừu,",
  "mn112:14.11": "đã tránh xa việc nhận gà và heo,",
  "mn112:14.12": "đã tránh xa việc nhận voi, bò, ngựa và ngựa cái,",
  "mn112:14.13": "đã tránh xa việc nhận ruộng vườn đất đai.",
  "mn112:14.14": "Tôi đã tránh xa việc làm sứ giả, chạy việc cho người,",
  "mn112:14.15": "đã tránh xa việc mua bán,",
  "mn112:14.16": "đã tránh xa việc dùng cân giả, đồng giả, đồ đong giả,",
  "mn112:14.17": "đã tránh xa việc hối lộ, lừa gạt, bịp bợm và gian trá,",
  "mn112:14.18": "đã tránh xa việc chém giết, đánh đập, trói buộc, cướp đoạt, cướp giật và ép lấy bằng sức mạnh.",
  "mn112:14.19": "Tôi sống biết đủ với y để che thân và đồ ăn xin được để nuôi bụng. Tôi đi đến đâu cũng chỉ mang theo những thứ ấy.",
  "mn112:14.20": "Như chim có cánh bay đến đâu cũng chỉ mang theo đôi cánh của mình,",
  "mn112:14.21": "cũng vậy, này hiền giả, tôi sống biết đủ với y để che thân và đồ ăn xin được để nuôi bụng. Tôi đi đến đâu cũng chỉ mang theo những thứ ấy.",
  "mn112:14.22": "Nhờ đầy đủ nếp sống tốt đẹp cao quý này, tôi cảm nhận niềm vui trong lòng không có gì phải chê trách.",
  "mn112:15.1": "Khi mắt thấy hình sắc, tôi không nắm lấy tướng chung, không nắm lấy tướng riêng;",
  "mn112:15.2": "vì nếu sống không giữ gìn mắt thì lòng ham muốn và buồn bực, những điều xấu ác không lành, có thể tràn vào, nên tôi thực hành để giữ gìn; tôi giữ gìn mắt, tôi khéo canh giữ mắt.",
  "mn112:15.3": "Khi tai nghe tiếng …",
  "mn112:15.4": "khi mũi ngửi mùi …",
  "mn112:15.5": "khi lưỡi nếm vị …",
  "mn112:15.6": "khi thân chạm xúc chạm …",
  "mn112:15.7": "khi ý biết điều được nhận biết, tôi không nắm lấy tướng chung, không nắm lấy tướng riêng;",
  "mn112:15.8": "vì nếu sống không giữ gìn ý thì lòng ham muốn và buồn bực, những điều xấu ác không lành, có thể tràn vào, nên tôi thực hành để giữ gìn; tôi giữ gìn ý, tôi khéo canh giữ ý.",
  "mn112:15.9": "Nhờ đầy đủ sự giữ gìn các cửa giác quan cao quý này, tôi cảm nhận niềm vui trong lòng không pha tạp.",
  "mn112:16.1": "Khi bước tới bước lui, tôi đều biết rõ; khi nhìn thẳng nhìn quanh, tôi đều biết rõ; khi co tay duỗi tay, tôi đều biết rõ; khi mang y, bát và áo ngoài, tôi đều biết rõ; khi ăn, uống, nhai, nếm, tôi đều biết rõ; khi đi tiêu đi tiểu, tôi đều biết rõ; khi đi, đứng, ngồi, nằm, thức, nói, im lặng, tôi đều biết rõ.",
  "mn112:16.2": "Vị ấy có đủ nếp sống tốt đẹp của bậc cao quý, có đủ sự biết vừa đủ tốt đẹp của bậc cao quý, có đủ sự giữ gìn các cửa nhận biết tốt đẹp của bậc cao quý, có đủ sự nhớ biết rõ ràng tốt đẹp của bậc cao quý,",
  "mn112:16.3": "đã tìm đến chỗ ở vắng vẻ: rừng, gốc cây, núi, hang núi, động trong núi, bãi tha ma, khu rừng hoang, chỗ trống ngoài trời, đống rơm.",
  "mn112:16.4": "Sau bữa ăn, khi đi khất thực trở về, vị ấy ngồi xuống, xếp chân bằng tròn, giữ thân ngay thẳng, đặt sự nhớ biết rõ ở trước mặt.",
  "mn112:17.1": "Vị ấy bỏ lòng ham muốn ở đời, sống với lòng không còn ham muốn, gột sạch tâm khỏi lòng ham muốn.",
  "mn112:17.2": "Bỏ sự dữ dằn và bực bội, vị ấy sống với lòng không dữ, thương xót và mong điều lành cho mọi loài có sự sống, gột sạch tâm khỏi sự dữ dằn và bực bội.",
  "mn112:17.3": "Bỏ sự lười nhác và buồn ngủ, vị ấy sống không còn lười nhác buồn ngủ, hướng tâm về ánh sáng, nhớ biết rõ ràng, gột sạch tâm khỏi sự lười nhác và buồn ngủ.",
  "mn112:17.4": "Bỏ sự xao động và cắn rứt, vị ấy sống không xao động, tâm lắng yên ở bên trong, gột sạch tâm khỏi sự xao động và cắn rứt.",
  "mn112:17.5": "Bỏ sự ngờ vực, vị ấy sống đã vượt qua ngờ vực, không còn phân vân đối với những điều lành, gột sạch tâm khỏi sự ngờ vực.",
  "mn112:18.1": "Sau khi bỏ năm thứ che lấp này, là những vết nhơ của tâm, làm yếu đi sự hiểu rõ,",
  "mn112:18.2": "vị ấy lìa các ham muốn, lìa các điều xấu ác, vào và an trú tầng lặng yên thứ nhất, có suy xét, có xem xét, có niềm vui và sự dễ chịu do lìa ra mà sinh.",
  "mn112:18.3": "Khi suy xét và xem xét lắng xuống, tâm trong sáng bên trong, gom lại thành một khối vững yên, không còn suy xét, không còn xem xét, có niềm vui và sự dễ chịu do tâm yên vững mà sinh, vị ấy vào và an trú tầng lặng yên thứ hai…",
  "mn112:18.4": "tầng lặng yên thứ ba…",
  "mn112:18.5": "vị ấy vào và an trú tầng lặng yên thứ tư.",
  "mn112:19.1": "Khi tâm đã yên vững như vậy, trong sạch, sáng rõ, không nhơ bợn, sạch các vết bẩn, mềm mại, dễ dùng, đứng vững, đạt tới không lay động, vị ấy hướng tâm đến sự hiểu rõ về việc dứt sạch các dòng chảy ngầm.",
  "mn112:19.2": "Vị ấy hiểu đúng như thật: ‘Đây là sự khổ đau’; hiểu đúng như thật: ‘Đây là nguồn gốc của sự khổ đau’; hiểu đúng như thật: ‘Đây là sự dứt sự khổ đau’; hiểu đúng như thật: ‘Đây là con đường đưa đến sự dứt sự khổ đau’;",
  "mn112:19.3": "hiểu đúng như thật: ‘Đây là các dòng chảy ngầm’; hiểu đúng như thật: ‘Đây là nguồn gốc của các dòng chảy ngầm’; hiểu đúng như thật: ‘Đây là sự dứt các dòng chảy ngầm’; hiểu đúng như thật: ‘Đây là con đường đưa đến sự dứt các dòng chảy ngầm’.",
  "mn112:20.1": "Với tôi, khi biết như vậy, thấy như vậy, tâm được buông khỏi dòng chảy ngầm của ham muốn, tâm được buông khỏi dòng chảy ngầm của sự tiếp nối đời sống, tâm được buông khỏi dòng chảy ngầm của không biết rõ.",
  "mn112:20.2": "Khi tâm đã được buông ra, sự hiểu biết khởi lên: ‘Tâm đã được buông ra’.",
  "mn112:20.3": "Tôi hiểu rõ: ‘Sự sinh đã dứt, đời sống phạm hạnh đã sống xong, việc cần làm đã làm xong, không còn trở lui trạng thái này nữa’.",
  "mn112:20.4": "Này các bạn, với tôi, khi biết như vậy, thấy như vậy, trong thân này có sự nhận biết và đối với mọi dấu hiệu ở bên ngoài, thói ngầm của cái “ta”, cái “của ta”, và sự hơn thua đã bị nhổ sạch.’",
  "mn112:21.1": "Này các Tỳ Kheo, lời nói của vị Tỳ Kheo ấy cần được tán thành và vui nhận rằng: ‘Lành thay’.",
  "mn112:21.2": "Sau khi tán thành và vui nhận lời nói ấy rằng: ‘Lành thay’, nên nói với vị ấy như sau:",
  "mn112:21.3": "‘Thật là phần tốt cho chúng tôi, này bạn, thật là khéo được cho chúng tôi, này bạn,",
  "mn112:21.4": "khi chúng tôi được thấy một người cùng sống đời trong sạch như ngài như vậy.’”",
  "mn112:21.5": "Đức Thế Tôn nói như vậy.",
  "mn112:21.6": "Các Tỳ Kheo vui mừng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn112:21.7": "Kinh Sáu Cách Làm Trong Sạch, bài thứ hai, đến đây là hết."
}
window.BILARA["mn112"]["vi"]["mn112:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
