window.BILARA = window.BILARA || {};
window.BILARA["mn122"] = window.BILARA["mn122"] || {};
window.BILARA["mn122"]["vi"] = {
  "mn122:0.1": "Trung Bộ Kinh 122",
  "mn122:0.2": "Kinh Trống Rỗng Lớn",
  "mn122:1.1": "Tôi nghe như vầy—",
  "mn122:1.2": "Một thời, Đức Thế Tôn ở giữa dân Sakka, tại Kapilavatthu, trong vườn Nigrodha.",
  "mn122:2.1": "Rồi vào buổi sáng, Đức Thế Tôn mặc y, cầm bát và áo choàng, đi vào Kapilavatthu để khất thực.",
  "mn122:2.2": "Sau khi đi khất thực trong Kapilavatthu, ăn xong và từ chỗ khất thực trở về, Đức Thế Tôn đi đến chỗ ở của người Sakka tên Kālakhemaka để nghỉ trưa.",
  "mn122:2.3": "Lúc ấy, trong chỗ ở của người Sakka tên Kālakhemaka, nhiều chỗ nằm chỗ ngồi đã được dọn sẵn.",
  "mn122:2.4": "Đức Thế Tôn thấy trong chỗ ở của người Sakka tên Kālakhemaka có nhiều chỗ nằm chỗ ngồi đã được dọn sẵn.",
  "mn122:2.5": "Thấy vậy, Đức Thế Tôn nghĩ rằng:",
  "mn122:2.6": "“Trong chỗ ở của người Sakka tên Kālakhemaka có nhiều chỗ nằm chỗ ngồi đã được dọn sẵn.",
  "mn122:2.7": "Chắc là có nhiều Tỳ Kheo đang ở đây.”",
  "mn122:2.8": "Lúc ấy, ngài Ānanda đang cùng với nhiều Tỳ Kheo may y tại chỗ ở của người Sakka tên Ghaṭā.",
  "mn122:2.9": "Rồi vào buổi chiều, Đức Thế Tôn ra khỏi chỗ ở yên một mình, đi đến chỗ ở của người Sakka tên Ghaṭā; đến nơi, Ngài ngồi xuống chỗ ngồi đã dọn sẵn.",
  "mn122:2.10": "Khi đã ngồi xuống, Đức Thế Tôn gọi ngài Ānanda:",
  "mn122:2.11": "“Này Ānanda, trong chỗ ở của người Sakka tên Kālakhemaka có nhiều chỗ nằm chỗ ngồi đã được dọn sẵn.",
  "mn122:2.12": "Có phải nhiều Tỳ Kheo đang ở đó không?”",
  "mn122:2.13": "“Bạch Thế Tôn, trong chỗ ở của người Sakka tên Kālakhemaka có nhiều chỗ nằm chỗ ngồi đã được dọn sẵn.",
  "mn122:2.14": "Có nhiều Tỳ Kheo đang ở đó.",
  "mn122:2.15": "Bạch Thế Tôn, đây là lúc may y.”",
  "mn122:3.1": "“Này Ānanda, một Tỳ Kheo ưa đông người, thích ở giữa đám đông, gắn bó với việc sống đông người, ưa hội nhóm, thích hội nhóm, vui với hội nhóm, thì không xứng hợp.",
  "mn122:3.2": "Này Ānanda, một Tỳ Kheo như vậy, ưa đông người, thích ở giữa đám đông, gắn bó với việc sống đông người, ưa hội nhóm, thích hội nhóm, vui với hội nhóm, mà lại có thể đạt được niềm vui do lìa bỏ, niềm vui do sống riêng, niềm vui do lắng yên, niềm vui do tỉnh biết trọn vẹn, đạt được thứ niềm vui ấy theo ý mình, không khó, không nhọc—điều ấy không thể có.",
  "mn122:3.3": "Còn Tỳ Kheo nào sống một mình, tách khỏi đám đông, thì có thể mong đợi điều này: vị ấy sẽ đạt được niềm vui do lìa bỏ, niềm vui do sống riêng, niềm vui do lắng yên, niềm vui do tỉnh biết trọn vẹn, đạt được thứ niềm vui ấy theo ý mình, không khó, không nhọc—điều ấy có thể có.",
  "mn122:4.1": "Này Ānanda, một Tỳ Kheo ưa đông người, thích ở giữa đám đông, gắn bó với việc sống đông người, ưa hội nhóm, thích hội nhóm, vui với hội nhóm, mà lại có thể sống sau khi đạt đến sự mở thoát của lòng do thương mến trong chốc lát, hay sự mở thoát không lay chuyển—điều ấy không thể có.",
  "mn122:4.2": "Còn Tỳ Kheo nào sống một mình, tách khỏi đám đông, thì có thể mong đợi điều này: vị ấy sẽ sống sau khi đạt đến sự mở thoát của lòng do thương mến trong chốc lát, hay sự mở thoát không lay chuyển—điều ấy có thể có.",
  "mn122:5.1": "Này Ānanda, Ta không thấy một hình sắc nào mà khi người ta say đắm, mê thích nó, thì lúc nó đổi khác, biến khác, lại không sinh ra buồn rầu, than khóc, khổ đau, bứt rứt và tuyệt vọng.",
  "mn122:6.1": "Này Ānanda, đây là cách ở mà Như Lai đã tự mình biết trọn vẹn, đó là—",
  "mn122:6.2": "không để tâm đến mọi dấu hiệu, mà sống an trú trong sự trống rỗng ở bên trong.",
  "mn122:6.3": "Này Ānanda, khi Như Lai đang sống theo cách ở này, nếu có các Tỳ Kheo, Tỳ Kheo Ni, nam cư sĩ, nữ cư sĩ, các vua, quan lớn của vua, người tu theo đường khác, hay học trò của họ đến gặp,",
  "mn122:6.4": "thì này Ānanda, với lòng nghiêng hẳn về sống riêng, hướng về sống riêng, đổ dồn về sống riêng, đã tách khỏi đám đông, vui với lìa bỏ, đã dứt sạch mọi thứ làm chỗ bám cho dòng rỉ chảy của lòng, Như Lai chỉ nói những lời đưa đến khuyên rời đi mà thôi.",
  "mn122:7.1": "Vậy nên, này Ānanda, nếu một Tỳ Kheo mong rằng:",
  "mn122:7.2": "‘hãy an trú với sự trống không ở bên trong’, này Ānanda, vì vậy Tỳ Kheo phải đặt tâm mình vững ở bên trong, làm cho lắng xuống, gom lại một mối, làm cho yên vững.",
  "mn122:7.3": "Và này Ānanda, thế nào là Tỳ Kheo đặt tâm mình vững ở bên trong, làm cho lắng xuống, gom lại một mối, làm cho yên vững?",
  "mn122:8.1": "Này Ānanda, ở đây Tỳ Kheo lìa các ham muốn giác quan, lìa các điều xấu ác trong tâm … bước vào và an trú tầng thiền thứ nhất …",
  "mn122:8.2": "tầng thiền thứ hai …",
  "mn122:8.3": "tầng thiền thứ ba …",
  "mn122:8.4": "bước vào và an trú tầng thiền thứ tư.",
  "mn122:8.5": "Như vậy, này Ānanda, Tỳ Kheo đặt tâm mình vững ở bên trong, làm cho lắng xuống, gom lại một mối, làm cho yên vững.",
  "mn122:9.1": "Vị ấy hướng tâm đến sự trống không ở bên trong.",
  "mn122:9.2": "Khi vị ấy hướng tâm đến sự trống không ở bên trong, tâm không lao vào đó, không trong sáng lên, không đứng vững, không buông mở ra.",
  "mn122:9.3": "Khi sự việc là như vậy, này Ānanda, Tỳ Kheo hiểu rõ như vầy:",
  "mn122:9.4": "‘Khi ta hướng tâm đến sự trống không ở bên trong, tâm ta không lao vào đó, không trong sáng lên, không đứng vững, không buông mở ra.’",
  "mn122:9.5": "Như vậy, vị ấy biết rõ ngay tại đó.",
  "mn122:9.6": "Vị ấy hướng tâm đến sự trống không ở bên ngoài …",
  "mn122:9.7": "vị ấy hướng tâm đến sự trống không ở cả bên trong lẫn bên ngoài …",
  "mn122:9.8": "vị ấy hướng tâm đến cảnh giới không lay động.",
  "mn122:9.9": "Khi vị ấy hướng tâm đến cảnh giới không lay động, tâm không lao vào đó, không trong sáng lên, không đứng vững, không buông mở ra.",
  "mn122:9.10": "Khi sự việc là như vậy, này Ānanda, Tỳ Kheo hiểu rõ như vầy:",
  "mn122:9.11": "‘Khi ta hướng tâm đến cảnh giới không lay động, tâm ta không lao vào đó, không trong sáng lên, không đứng vững, không buông mở ra.’",
  "mn122:9.12": "Như vậy, vị ấy biết rõ ngay tại đó.",
  "mn122:10.1": "Vì vậy, này Ānanda, Tỳ Kheo phải ngay nơi dấu hiệu của trạng thái tâm yên vững trước đó mà đặt tâm mình vững ở bên trong, làm cho lắng xuống, gom lại một mối, làm cho yên vững.",
  "mn122:10.2": "Vị ấy hướng tâm đến sự trống không ở bên trong.",
  "mn122:10.3": "Khi vị ấy hướng tâm đến sự trống không ở bên trong, tâm lao vào đó, trong sáng lên, đứng vững, buông mở ra.",
  "mn122:10.4": "Khi sự việc là như vậy, này Ānanda, Tỳ Kheo hiểu rõ như vầy:",
  "mn122:10.5": "‘Khi ta hướng tâm đến sự trống không ở bên trong, tâm ta lao vào đó, trong sáng lên, đứng vững, buông mở ra.’",
  "mn122:10.6": "Như vậy, vị ấy biết rõ ngay tại đó.",
  "mn122:10.7": "Vị ấy hướng tâm đến sự trống không ở bên ngoài …",
  "mn122:10.8": "vị ấy hướng tâm đến sự trống không ở cả bên trong lẫn bên ngoài …",
  "mn122:10.9": "vị ấy hướng tâm đến cảnh giới không lay động.",
  "mn122:10.10": "Khi vị ấy hướng tâm đến cảnh giới không lay động, tâm lao vào đó, trong sáng lên, đứng vững, buông mở ra.",
  "mn122:10.11": "Khi sự việc là như vậy, này Ānanda, Tỳ Kheo hiểu rõ như vầy:",
  "mn122:10.12": "‘Khi ta để tâm đến chỗ không lay động, thì tâm ta lao vào chỗ không lay động, trở nên trong sáng, đứng vững, được buông ra’—vị ấy biết rõ như vậy.",
  "mn122:10.13": "Như vậy, vị ấy tỉnh táo biết rõ trong việc ấy.",
  "mn122:11.1": "Này Ānanda, nếu Tỳ Kheo ấy sống như vậy mà tâm nghiêng về đi kinh hành, thì vị ấy đi kinh hành:",
  "mn122:11.2": "‘Khi ta đi kinh hành như vậy, lòng ham muốn và buồn bực, những điều xấu ác không khéo, sẽ không chảy tràn vào ta’—vị ấy biết vậy.",
  "mn122:11.3": "Như vậy, vị ấy tỉnh táo biết rõ trong việc ấy.",
  "mn122:11.4": "Này Ānanda, nếu Tỳ Kheo ấy sống như vậy mà tâm nghiêng về đứng, thì vị ấy đứng:",
  "mn122:11.5": "‘Khi ta đứng như vậy, lòng ham muốn và buồn bực, những điều xấu ác không khéo, sẽ không chảy tràn vào ta’—vị ấy biết vậy.",
  "mn122:11.6": "Như vậy, vị ấy tỉnh táo biết rõ trong việc ấy.",
  "mn122:11.7": "Này Ānanda, nếu Tỳ Kheo ấy sống như vậy mà tâm nghiêng về ngồi, thì vị ấy ngồi:",
  "mn122:11.8": "‘Khi ta ngồi như vậy, lòng ham muốn và buồn bực, những điều xấu ác không khéo, sẽ không chảy tràn vào ta’—vị ấy biết vậy.",
  "mn122:11.9": "Như vậy, vị ấy tỉnh táo biết rõ trong việc ấy.",
  "mn122:11.10": "Này Ānanda, nếu Tỳ Kheo ấy sống như vậy mà tâm nghiêng về nằm, thì vị ấy nằm:",
  "mn122:11.11": "‘Khi ta nằm như vậy, lòng ham muốn và buồn bực, những điều xấu ác không khéo, sẽ không chảy tràn vào ta’—vị ấy biết vậy.",
  "mn122:11.12": "Như vậy, vị ấy tỉnh táo biết rõ trong việc ấy.",
  "mn122:12.1": "Này Ānanda, nếu Tỳ Kheo ấy sống như vậy mà tâm nghiêng về nói chuyện, thì vị ấy nghĩ:",
  "mn122:12.2": "‘Ta sẽ không nói những chuyện thấp kém, tầm thường, theo lối người đời, không phải lối bậc cao quý, không đưa đến ích lợi, không đưa đến chán ngán, không đưa đến lìa ham muốn, không đưa đến dứt hẳn, không đưa đến lắng yên, không đưa đến biết rõ, không đưa đến tỉnh ngộ trọn vẹn, không đưa đến tắt hẳn; như là chuyện vua chúa, chuyện trộm cướp, chuyện quan lớn, chuyện quân lính, chuyện sợ hãi, chuyện chiến tranh, chuyện ăn uống, chuyện đồ mặc, chuyện chỗ nằm, chuyện vòng hoa, chuyện mùi thơm, chuyện bà con, chuyện xe cộ, chuyện làng xóm, chuyện chợ búa, chuyện thành thị, chuyện xứ sở, chuyện đàn bà, chuyện rượu chè, chuyện ngoài đường, chuyện bến nước, chuyện người đã chết, chuyện lặt vặt đủ thứ, chuyện nguồn gốc trời đất, chuyện biển cả, chuyện có hay không có đời sau’—vị ấy biết vậy.",
  "mn122:12.3": "Như vậy, vị ấy tỉnh táo biết rõ trong việc ấy.",
  "mn122:12.4": "Còn những lời nói này, này Ānanda, giúp gọt mòn các thói xấu, hợp với việc gỡ che mờ trong lòng, chỉ đưa đến chán ngán, lìa ham muốn, dứt hẳn, lắng yên, biết rõ, tỉnh ngộ trọn vẹn, tắt hẳn; như là nói về ít muốn, nói về biết đủ, nói về ở riêng, nói về không tụ tập, nói về gắng sức, nói về nết tốt, nói về tâm yên vững, nói về sự hiểu rõ, nói về được buông ra, nói về thấy biết rằng mình đã được buông ra—‘Ta sẽ nói những lời như vậy’—vị ấy biết vậy.",
  "mn122:12.5": "Như vậy, vị ấy tỉnh táo biết rõ trong việc ấy.",
  "mn122:13.1": "Này Ānanda, nếu Tỳ Kheo ấy sống như vậy mà tâm nghiêng về nghĩ ngợi, thì vị ấy nghĩ:",
  "mn122:13.2": "‘Ta sẽ không nghĩ những ý nghĩ thấp kém, tầm thường, theo lối người đời, không phải lối bậc cao quý, không đưa đến ích lợi, không đưa đến chán ngán, không đưa đến lìa ham muốn, không đưa đến dứt hẳn, không đưa đến lắng yên, không đưa đến biết rõ, không đưa đến tỉnh ngộ trọn vẹn, không đưa đến tắt hẳn; như là ý nghĩ ham muốn giác quan, ý nghĩ giận dữ, ý nghĩ làm hại’—vị ấy biết vậy.",
  "mn122:13.3": "Như vậy, vị ấy tỉnh táo biết rõ trong việc ấy.",
  "mn122:13.4": "Còn những ý nghĩ này, này Ānanda, là của bậc cao quý, đưa ra khỏi trói buộc, dẫn người thực hành đến chỗ dứt sạch khổ đau một cách đúng đắn; như là ý nghĩ lìa bỏ, ý nghĩ không giận dữ, ý nghĩ không làm hại—‘Ta sẽ nghĩ những ý nghĩ như vậy’—vị ấy biết vậy.",
  "mn122:13.5": "Như vậy, vị ấy tỉnh táo biết rõ trong việc ấy.",
  "mn122:14.1": "Này Ānanda, có năm thứ vui thích giác quan này.",
  "mn122:14.2": "Năm thứ ấy là gì?",
  "mn122:14.3": "Những hình sắc do mắt nhận ra, dễ chịu, đáng ưa, vừa ý, hấp dẫn, gắn với ham muốn giác quan, khơi lòng mê đắm;",
  "mn122:14.4": "những tiếng do tai nhận ra …",
  "mn122:14.5": "những mùi do mũi nhận ra …",
  "mn122:14.6": "những vị do lưỡi nhận ra …",
  "mn122:14.7": "những thứ chạm xúc nhận ra qua thân, vừa ý, đáng thích, hợp lòng, dễ mến, gắn với ham muốn giác quan, khơi dậy say đắm—",
  "mn122:14.8": "Này Ānanda, đó là năm thứ vui giác quan.",
  "mn122:15.1": "Ở đây, một Tỳ Kheo phải thường xuyên tự xem lại tâm mình:",
  "mn122:15.2": "‘Trong năm thứ vui giác quan này, ở bất cứ cửa nào, có sự lay động nào của tâm khởi lên trong ta không?’",
  "mn122:15.3": "Này Ānanda, nếu khi tự xem lại, Tỳ Kheo biết rõ như vầy:",
  "mn122:15.4": "‘Trong năm thứ vui giác quan này, ở một cửa nào đó, có sự lay động của tâm khởi lên trong ta’,",
  "mn122:15.5": "thì khi đúng là như vậy, này Ānanda, Tỳ Kheo biết rõ như vầy:",
  "mn122:15.6": "‘Sự ham thích và say đắm đối với năm thứ vui giác quan này trong ta vẫn chưa dứt bỏ.’",
  "mn122:15.7": "Như vậy, vị ấy tỉnh rõ về điều ấy.",
  "mn122:15.8": "Nhưng này Ānanda, nếu khi tự xem lại, Tỳ Kheo biết rõ như vầy:",
  "mn122:15.9": "‘Trong năm thứ vui giác quan này, ở bất cứ cửa nào, không có sự lay động nào của tâm khởi lên trong ta’,",
  "mn122:15.10": "thì khi đúng là như vậy, này Ānanda, Tỳ Kheo biết rõ như vầy:",
  "mn122:15.11": "‘Sự ham thích và say đắm đối với năm thứ vui giác quan này trong ta đã dứt bỏ.’",
  "mn122:15.12": "Như vậy, vị ấy tỉnh rõ về điều ấy.",
  "mn122:16.1": "Này Ānanda, đây là năm nhóm bị nắm giữ mà một Tỳ Kheo phải sống quán sát sự sinh lên và tan đi nơi đó:",
  "mn122:16.2": "‘đây là thân sắc, đây là sự sinh lên của thân sắc, đây là sự tan mất của thân sắc;",
  "mn122:16.3": "đây là cảm giác …",
  "mn122:16.4": "đây là sự ghi nhận …",
  "mn122:16.5": "đây là các hoạt động của tâm …",
  "mn122:16.6": "đây là sự nhận biết, đây là sự sinh lên của sự nhận biết, đây là sự tan mất của sự nhận biết.’",
  "mn122:17.1": "Khi vị ấy sống quán sát sự sinh lên và tan đi trong năm nhóm bị nắm giữ này, thì ý nghĩ ‘ta là’ đối với năm nhóm bị nắm giữ ấy được dứt bỏ.",
  "mn122:17.2": "Khi đúng là như vậy, này Ānanda, Tỳ Kheo biết rõ như vầy:",
  "mn122:17.3": "‘Ý nghĩ “ta là” đối với năm nhóm bị nắm giữ này trong ta đã được dứt bỏ.’",
  "mn122:17.4": "Như vậy, vị ấy tỉnh rõ về điều ấy.",
  "mn122:18.1": "Này Ānanda, đây là những điều hoàn toàn lành, đưa đến điều lành, thuộc bậc thánh, vượt khỏi đời, ma xấu không chen vào được.",
  "mn122:19.1": "Này Ānanda, ông nghĩ sao,",
  "mn122:19.2": "người học trò vì thấy lợi ích gì mà nên theo sát bậc thầy, dù bị đuổi đi?’",
  "mn122:19.3": "‘Bạch Thế Tôn, những lời dạy của chúng con lấy Đức Thế Tôn làm gốc, lấy Đức Thế Tôn làm người dẫn đường, lấy Đức Thế Tôn làm chỗ nương tựa. Thật tốt là chính Đức Thế Tôn làm sáng tỏ nghĩa của lời nói này. Nghe Đức Thế Tôn xong, các Tỳ Kheo sẽ ghi nhớ.’",
  "mn122:20.1": "‘Này Ānanda, người học trò không nên theo sát bậc thầy chỉ vì kinh, vì lời tụng, vì phần giảng giải. ",
  "mn122:20.2": "Vì sao vậy?",
  "mn122:20.3": "Này A Nan, từ lâu nay ông đã nghe nhiều điều lành, đã ghi nhớ, đã quen nói lại, đã xem xét kỹ trong lòng, đã thấu rõ bằng cái thấy của mình.",
  "mn122:20.4": "Và này A Nan, những lời nói giúp gọt mòn các thói xấu, hợp với việc gỡ bỏ các thứ che lấp trong lòng, đưa thẳng đến chán lìa, nhạt ham muốn, dứt hẳn, lắng yên, biết rõ, tự mình tỉnh ngộ, và tắt hẳn, như: nói về ít muốn, nói về biết đủ, nói về sống riêng vắng, nói về không tụ họp dính mắc, nói về gắng sức, nói về nết sống đúng, nói về tâm yên vững, nói về sự hiểu rõ, nói về sự giải thoát, nói về cái thấy biết rằng mình đã được giải thoát; vì những lời nói như vậy, người học trò xứng đáng theo sát bậc thầy, dù bị xua đuổi đi nữa.",
  "mn122:21.1": "Khi là như vậy, này A Nan, thì có tai hại từ bậc thầy, có tai hại từ học trò, có tai hại từ người cùng sống đời trong sạch.",
  "mn122:22.1": "Và này A Nan, thế nào là tai hại từ bậc thầy?",
  "mn122:22.2": "Này A Nan, ở đây có một vị thầy ưa ở chỗ nghỉ riêng vắng: rừng, gốc cây, núi, hang núi, động trong núi, bãi tha ma, chốn rừng sâu, nơi trống ngoài trời, hay đống rơm.",
  "mn122:22.3": "Khi vị ấy sống tách riêng như vậy, thì các bà la môn, người chủ nhà, người thị trấn và người quê vùng quanh tìm đến vị ấy.",
  "mn122:22.4": "Khi các bà la môn, người chủ nhà, người thị trấn và người quê vùng quanh tìm đến, vị ấy lại thích thú mê đắm trong đó, sinh lòng thèm muốn, rồi quay về nếp sống đông đúc nhiều việc.",
  "mn122:22.5": "Này A Nan, đó gọi là vị thầy gây tai hại.",
  "mn122:22.6": "Do tai hại từ bậc thầy ấy, các điều xấu ác, không lành, làm nhơ bẩn, dẫn đến tái sinh, có buộc ràng, cho quả khổ đau, đưa đến sinh, già, chết về sau, liền tràn ngập người ấy.",
  "mn122:22.7": "Này A Nan, như vậy là tai hại từ bậc thầy.",
  "mn122:23.1": "Và này A Nan, thế nào là tai hại từ học trò?",
  "mn122:23.2": "Này A Nan, học trò của chính vị thầy ấy, muốn làm lớn thêm nếp sống riêng vắng của thầy,",
  "mn122:23.3": "nên ưa ở chỗ nghỉ riêng vắng: rừng, gốc cây, núi, hang núi, động trong núi, bãi tha ma, chốn rừng sâu, nơi trống ngoài trời, hay đống rơm.",
  "mn122:23.4": "Khi vị ấy sống tách riêng như vậy, thì các bà la môn, người chủ nhà, người thị trấn và người quê vùng quanh tìm đến vị ấy.",
  "mn122:23.5": "Khi các bà la môn, người chủ nhà, người thị trấn và người quê vùng quanh tìm đến, vị ấy lại thích thú mê đắm trong đó, sinh lòng thèm muốn, rồi quay về nếp sống đông đúc nhiều việc.",
  "mn122:23.6": "Này A Nan, đó gọi là học trò gây tai hại.",
  "mn122:23.7": "Do tai hại từ học trò ấy, các điều xấu ác, không lành, làm nhơ bẩn, dẫn đến tái sinh, có buộc ràng, cho quả khổ đau, đưa đến sinh, già, chết về sau, liền tràn ngập người ấy.",
  "mn122:23.8": "Này A Nan, như vậy là tai hại từ học trò.",
  "mn122:24.1": "Và này A Nan, thế nào là tai hại từ người cùng sống đời trong sạch?",
  "mn122:24.2": "Này A Nan, ở đây, Như Lai ra đời, là bậc đáng kính, tự mình tỉnh ngộ trọn vẹn, đủ hiểu biết và nết sống, khéo đi đến bờ bên kia, rõ biết đời, là người dẫn dắt bậc nhất cho những ai cần được rèn luyện, là thầy của chư thiên và loài người, là bậc Giác Ngộ, Đức Thế Tôn.",
  "mn122:24.3": "Vị ấy ưa ở chỗ nghỉ riêng vắng: rừng, gốc cây, núi, hang núi, động trong núi, bãi tha ma, chốn rừng sâu, nơi trống ngoài trời, hay đống rơm.",
  "mn122:24.4": "Khi vị ấy sống tách riêng như vậy, thì các bà la môn, người chủ nhà, người thị trấn và người quê vùng quanh tìm đến vị ấy.",
  "mn122:24.5": "Khi các bà la môn, người chủ nhà, người thị trấn và người quê vùng quanh tìm đến, vị ấy không thích thú mê đắm trong đó, không sinh lòng thèm muốn, không quay về nếp sống đông đúc nhiều việc.",
  "mn122:24.6": "Nhưng này A Nan, học trò của chính vị thầy ấy, muốn làm lớn thêm nếp sống riêng vắng của thầy,",
  "mn122:24.7": "nên ưa ở chỗ nghỉ riêng vắng: rừng, gốc cây, núi, hang núi, động trong núi, bãi tha ma, chốn rừng sâu, nơi trống ngoài trời, hay đống rơm.",
  "mn122:24.8": "Khi vị ấy sống tách riêng như vậy, thì các bà la môn, người chủ nhà, người thị trấn và người quê vùng quanh tìm đến vị ấy.",
  "mn122:24.9": "Khi các bà la môn, người chủ nhà, người thị trấn và người quê vùng quanh tìm đến, vị ấy lại thích thú mê đắm trong đó, sinh lòng thèm muốn, rồi quay về nếp sống đông đúc nhiều việc.",
  "mn122:24.10": "Này A Nan, đó gọi là người cùng sống đời trong sạch gây tai hại.",
  "mn122:24.11": "Do tai hại từ người cùng sống đời trong sạch ấy, các điều xấu ác, không lành, làm nhơ bẩn, dẫn đến tái sinh, có buộc ràng, cho quả khổ đau, đưa đến sinh, già, chết về sau, liền tràn ngập người ấy.",
  "mn122:24.12": "Này A Nan, như vậy là tai hại từ người cùng sống đời trong sạch.",
  "mn122:24.13": "Này A-nan, trong đó, sự hại do thầy, và sự hại do người học, thì sự hại đối với đời sống sống trong sạch cùng nhau do hai điều ấy còn cho quả khổ đau hơn, cay đắng hơn, và còn đưa đến sa ngã.",
  "mn122:25.1": "Vậy nên, này A-nan, hãy đối xử với Ta như với người bạn, chớ như với kẻ thù.",
  "mn122:25.2": "Điều ấy sẽ đem lại lợi ích và sự yên vui cho các ông lâu dài.",
  "mn122:25.3": "Và này A-nan, thế nào là người học đối xử với bậc thầy như với kẻ thù, không như với người bạn?",
  "mn122:25.4": "Ở đây, này A-nan, bậc thầy vì thương xót, vì mong điều lành, nên nói lời dạy cho người học:",
  "mn122:25.5": "‘Điều này là vì lợi ích cho các ông, điều này là vì sự yên vui cho các ông.’",
  "mn122:25.6": "Nhưng người học ấy không chịu lắng nghe, không ghé tai nghe, không hướng lòng đến để hiểu, và lại làm trái lời dạy của thầy.",
  "mn122:25.7": "Này A-nan, như vậy là người học đối xử với bậc thầy như với kẻ thù, không như với người bạn.",
  "mn122:26.1": "Và này A-nan, thế nào là người học đối xử với bậc thầy như với người bạn, không như với kẻ thù?",
  "mn122:26.2": "Ở đây, này A-nan, bậc thầy vì thương xót, vì mong điều lành, nên nói lời dạy cho người học:",
  "mn122:26.3": "‘Điều này là vì lợi ích cho các ông, điều này là vì sự yên vui cho các ông.’",
  "mn122:26.4": "Người học ấy chịu lắng nghe, ghé tai nghe, hướng lòng đến để hiểu, và không làm trái lời dạy của thầy.",
  "mn122:26.5": "Này A-nan, như vậy là người học đối xử với bậc thầy như với người bạn, không như với kẻ thù.",
  "mn122:26.6": "Vậy nên, này A-nan, hãy đối xử với Ta như với người bạn, chớ như với kẻ thù.",
  "mn122:26.7": "Điều ấy sẽ đem lại lợi ích và sự yên vui cho các ông lâu dài.",
  "mn122:27.1": "Này A-nan, Ta sẽ không thúc ép các ông như người thợ gốm nắn đồ đất còn ướt khi nó vẫn chỉ là đất ướt.",
  "mn122:27.2": "Này A-nan, Ta sẽ răn nhắc mãi,",
  "mn122:27.3": "nói rõ mãi, này A-nan.",
  "mn122:27.4": "Cái gì là phần chắc thật thì sẽ đứng vững.",
  "mn122:27.5": "Đức Thế Tôn đã nói như vậy.",
  "mn122:27.6": "Tôn giả A-nan vui mừng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn122:27.7": "Kinh Nói Về Trống Không Lớn chấm dứt, bài thứ hai."
}
window.BILARA["mn122"]["vi"]["mn122:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
