window.BILARA = window.BILARA || {};
window.BILARA["mn12"] = window.BILARA["mn12"] || {};
window.BILARA["mn12"]["vi"] = {
  "mn12:0.1": "Trung Bộ Kinh 12 ",
  "mn12:0.2": "Kinh Tiếng Gầm Sư Tử Lớn ",
  "mn12:1.1": "Tôi nghe như vầy—",
  "mn12:1.2": "Có một thời Đức Thế Tôn ở tại Vesāli, ngoài thành, trong một khu rừng ở Aparapura. ",
  "mn12:2.1": "Lúc bấy giờ, Sunakkhatta, con trai người Licchavi, mới rời bỏ nếp sống theo lời dạy và nề nếp này. ",
  "mn12:2.2": "Người ấy nói như vầy giữa đám đông ở Vesāli: ",
  "mn12:2.3": "“Sa-môn Gotama không có sự biết và thấy vượt hơn mức người thường, xứng bậc cao quý. ",
  "mn12:2.4": "Sa-môn Gotama chỉ giảng lời dạy do suy luận mà ra, theo sau sự xét tìm, do tự mình nghĩ ra. ",
  "mn12:2.5": "Nhưng điều mà lời dạy ấy được nói ra vì nó, thì dẫn người làm theo đúng như vậy đến chỗ dứt hẳn khổ đau.”",
  "mn12:3.1": "Rồi Tôn giả Sāriputta vào buổi sáng sớm, đắp y, mang bát và áo choàng, đi vào Vesāli để khất thực. ",
  "mn12:3.2": "Tôn giả Sāriputta nghe Sunakkhatta, con trai người Licchavi, đang nói như vầy giữa đám đông ở Vesāli: ",
  "mn12:3.3": "“Sa-môn Gotama không có sự biết và thấy vượt hơn mức người thường, xứng bậc cao quý. ",
  "mn12:3.4": "Sa-môn Gotama chỉ giảng lời dạy do suy luận mà ra, theo sau sự xét tìm, do tự mình nghĩ ra. ",
  "mn12:3.5": "Nhưng điều mà lời dạy ấy được nói ra vì nó, thì dẫn người làm theo đúng như vậy đến chỗ dứt hẳn khổ đau.”",
  "mn12:3.6": "Rồi Tôn giả Sāriputta đi khất thực ở Vesāli xong, sau bữa ăn, khi đã đi khất thực trở về, liền đến chỗ Đức Thế Tôn; đến nơi, đảnh lễ Đức Thế Tôn rồi ngồi xuống một bên. Khi đã ngồi xuống một bên, Tôn giả Sāriputta thưa với Đức Thế Tôn như vầy: ",
  "mn12:3.7": "“Bạch Thế Tôn, Sunakkhatta, con trai người Licchavi, mới rời bỏ nếp sống theo lời dạy và nề nếp này. ",
  "mn12:3.8": "Người ấy nói như vầy giữa đám đông ở Vesāli: ",
  "mn12:3.9": "‘Sa-môn Gotama không có sự biết và thấy vượt hơn mức người thường, xứng bậc cao quý. ",
  "mn12:3.10": "Sa-môn Gotama chỉ giảng lời dạy do suy luận mà ra, theo sau sự xét tìm, do tự mình nghĩ ra. ",
  "mn12:3.11": "Nhưng điều mà lời dạy ấy được nói ra vì nó, thì dẫn người làm theo đúng như vậy đến chỗ dứt hẳn khổ đau.’”",
  "mn12:4.1": "“Này Sāriputta, Sunakkhatta là kẻ hay giận, một người uổng công. ",
  "mn12:4.2": "Chính vì giận mà người ấy đã nói lời ấy. ",
  "mn12:4.3": "Này Sāriputta, Sunakkhatta, kẻ uổng công ấy, nghĩ rằng: ‘Ta sẽ nói xấu’, nhưng lại chỉ nói lên điều tốt đẹp về Như Lai. ",
  "mn12:4.4": "Này Sāriputta, đó thật là lời khen dành cho Như Lai, khi có người nói rằng: ",
  "mn12:4.5": "‘Nhưng điều mà lời dạy ấy được nói ra vì nó, thì dẫn người làm theo đúng như vậy đến chỗ dứt hẳn khổ đau.’ ",
  "mn12:5.1": "Này Sāriputta, điều này nữa, kẻ uổng công Sunakkhatta ấy cũng sẽ không có được sự hiểu đúng về Ta: ",
  "mn12:5.2": "‘Đức Thế Tôn là bậc đáng được cúng dường, tự mình giác ngộ trọn vẹn, đầy đủ hiểu biết và nết sống, khéo đi đến nơi an lành, biết rõ đời, là người dẫn dắt bậc nhất đối với những ai cần được rèn luyện, là bậc thầy của chư thiên và loài người, là bậc đã tỉnh thức, là Đức Thế Tôn.’ ",
  "mn12:6.1": "Này Sāriputta, điều này nữa, kẻ uổng công Sunakkhatta ấy cũng sẽ không có được sự hiểu đúng về Ta: ",
  "mn12:6.2": "‘Đức Thế Tôn tự mình trải biết nhiều loại năng lực khác thường: một thân mà hiện ra nhiều thân, nhiều thân mà trở lại một thân; hiện ra, biến mất; đi xuyên qua vách, qua thành, qua núi không bị ngăn ngại, như đi trong hư không; chui xuống rồi trồi lên khỏi đất như ở trong nước; đi trên nước mà không chìm như đi trên đất; ngồi xếp bằng mà bay trong hư không như chim có cánh; dùng tay sờ chạm và vuốt được cả mặt trăng mặt trời, những thứ có sức mạnh lớn, oai lực lớn như vậy; cho đến dùng thân làm chủ được cả cõi Phạm thiên.’ ",
  "mn12:7.1": "Này Sāriputta, điều này nữa, kẻ uổng công Sunakkhatta ấy cũng sẽ không có được sự hiểu đúng về Ta: ",
  "mn12:7.2": "‘Đức Thế Tôn có tai trời trong sạch, vượt hơn tai người, nên nghe được cả hai loại tiếng—tiếng cõi trời và tiếng loài người, dù ở xa hay ở gần.’",
  "mn12:8.1": "Này Sāriputta, ngay cả điều này nữa, kẻ uổng người như Sunakkhatta cũng sẽ không có lòng tin nơi Ta rằng:",
  "mn12:8.2": "‘Đức Thế Tôn biết rõ tâm của chúng sinh khác, của từng người khác, dùng tâm mà dò biết tâm.",
  "mn12:8.3": "Người có tâm còn ham muốn, Ngài biết rõ: “Tâm này còn ham muốn”;",
  "mn12:8.4": "người có tâm đã hết ham muốn, Ngài biết rõ: “Tâm này đã hết ham muốn”;",
  "mn12:8.5": "người có tâm còn giận dữ, Ngài biết rõ: “Tâm này còn giận dữ”;",
  "mn12:8.6": "người có tâm đã hết giận dữ, Ngài biết rõ: “Tâm này đã hết giận dữ”;",
  "mn12:8.7": "người có tâm còn mê mờ, Ngài biết rõ: “Tâm này còn mê mờ”;",
  "mn12:8.8": "người có tâm đã hết mê mờ, Ngài biết rõ: “Tâm này đã hết mê mờ”;",
  "mn12:8.9": "người có tâm co rút, Ngài biết rõ: “Tâm này co rút”;",
  "mn12:8.10": "người có tâm tán loạn, Ngài biết rõ: “Tâm này tán loạn”;",
  "mn12:8.11": "người có tâm rộng lớn, Ngài biết rõ: “Tâm này rộng lớn”;",
  "mn12:8.12": "người có tâm không rộng lớn, Ngài biết rõ: “Tâm này không rộng lớn”;",
  "mn12:8.13": "người có tâm còn có gì cao hơn, Ngài biết rõ: “Tâm này còn có gì cao hơn”;",
  "mn12:8.14": "người có tâm không gì cao hơn, Ngài biết rõ: “Tâm này không gì cao hơn”;",
  "mn12:8.15": "người có tâm yên vững, Ngài biết rõ: “Tâm này yên vững”;",
  "mn12:8.16": "người có tâm không yên vững, Ngài biết rõ: “Tâm này không yên vững”;",
  "mn12:8.17": "người có tâm đã được buông mở, Ngài biết rõ: “Tâm này đã được buông mở”;",
  "mn12:8.18": "người có tâm chưa được buông mở, Ngài biết rõ: “Tâm này chưa được buông mở”.’",
  "mn12:9.1": "Này Sāriputta, có mười sức mạnh của Như Lai. Nhờ có đủ mười sức mạnh ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:9.2": "Mười điều ấy là gì?",
  "mn12:10.1": "Này Sāriputta, ở đây Như Lai biết đúng như thật điều gì là có thể, và điều gì là không thể.",
  "mn12:10.2": "Này Sāriputta, việc Như Lai biết đúng như thật điều gì là có thể, và điều gì là không thể, đó cũng là một sức mạnh của Như Lai. Nhờ nương vào sức mạnh ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:11.1": "Lại nữa, này Sāriputta, Như Lai biết đúng như thật kết quả của những việc làm đã gây tạo trong quá khứ, tương lai và hiện nay, theo từng trường hợp và theo từng nguyên do.",
  "mn12:11.2": "Này Sāriputta, việc Như Lai biết đúng như thật kết quả của những việc làm đã gây tạo trong quá khứ, tương lai và hiện nay, theo từng trường hợp và theo từng nguyên do, đó cũng là một sức mạnh của Như Lai. Nhờ nương vào sức mạnh ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:12.1": "Lại nữa, này Sāriputta, Như Lai biết đúng như thật con đường đưa đến mọi nơi.",
  "mn12:12.2": "Này Sāriputta, việc Như Lai biết đúng như thật con đường đưa đến mọi nơi, đó cũng là một sức mạnh của Như Lai. Nhờ nương vào sức mạnh ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:13.1": "Lại nữa, này Sāriputta, Như Lai biết đúng như thật thế gian có nhiều cõi, nhiều loại cõi.",
  "mn12:13.2": "Này Sāriputta, việc Như Lai biết đúng như thật thế gian có nhiều cõi, nhiều loại cõi, đó cũng là một sức mạnh của Như Lai. Nhờ nương vào sức mạnh ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:14.1": "Lại nữa, này Sāriputta, Như Lai biết đúng như thật chúng sinh có nhiều khuynh hướng ưa thích khác nhau.",
  "mn12:14.2": "Này Sāriputta, việc Đức Thế Tôn biết đúng như thật khuynh hướng khác nhau của các loài, điều ấy cũng là một sức mạnh của Như Lai. Nhờ sức mạnh ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:15.1": "Lại nữa, này Sāriputta, Đức Thế Tôn biết đúng như thật mức mạnh yếu khác nhau trong các căn của những loài khác, những người khác.",
  "mn12:15.2": "Này Sāriputta, việc Đức Thế Tôn biết đúng như thật mức mạnh yếu khác nhau trong các căn của những loài khác, những người khác, điều ấy cũng là một sức mạnh của Như Lai. Nhờ sức mạnh ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:16.1": "Lại nữa, này Sāriputta, Đức Thế Tôn biết đúng như thật sự nhơ bẩn, sự trong sạch, và sự ra khỏi các tầng lặng sâu, các sự mở thoát, tâm yên vững, và các cảnh an trú.",
  "mn12:16.2": "Này Sāriputta, việc Đức Thế Tôn biết đúng như thật sự nhơ bẩn, sự trong sạch, và sự ra khỏi các tầng lặng sâu, các sự mở thoát, tâm yên vững, và các cảnh an trú, điều ấy cũng là một sức mạnh của Như Lai. Nhờ sức mạnh ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:17.1": "Lại nữa, này Sāriputta, Đức Thế Tôn nhớ lại được nhiều kiểu đời sống trước đây, như là: một đời, hai đời, ba đời, bốn đời, năm đời, mười đời, hai mươi đời, ba mươi đời, bốn mươi đời, năm mươi đời, một trăm đời, một ngàn đời, một trăm ngàn đời, nhiều thời kỳ thế gian co lại, nhiều thời kỳ thế gian mở ra, nhiều thời kỳ thế gian co lại rồi mở ra: ‘Ở chỗ kia, ta có tên như thế ấy, thuộc dòng họ như thế ấy, có dáng vẻ như thế ấy, ăn uống như thế ấy, nếm trải vui buồn như thế ấy, sống đến mức ấy. Từ chỗ ấy mất đi, ta sinh ra ở chỗ khác. Ở chỗ ấy nữa, ta có tên như thế ấy, thuộc dòng họ như thế ấy, có dáng vẻ như thế ấy, ăn uống như thế ấy, nếm trải vui buồn như thế ấy, sống đến mức ấy. Từ chỗ ấy mất đi, ta sinh ra ở đây.’ Như vậy, với từng nét riêng và từng chi tiết, Đức Thế Tôn nhớ lại được nhiều kiểu đời sống trước đây.",
  "mn12:17.2": "Này Sāriputta, việc Đức Thế Tôn nhớ lại được nhiều kiểu đời sống trước đây, như là: một đời, hai đời … với từng nét riêng và từng chi tiết, nhớ lại được nhiều kiểu đời sống trước đây, điều ấy cũng là một sức mạnh của Như Lai. Nhờ sức mạnh ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:18.1": "Lại nữa, này Sāriputta, với mắt trời trong sạch, vượt hơn mắt người thường, Đức Thế Tôn thấy các loài chết đi rồi sinh lại, kẻ thấp kẻ cao, người đẹp người xấu, kẻ đi về chỗ lành người đi về chỗ dữ; Ngài biết các loài đi theo việc mình đã làm: ‘Quả thật, những loài này sống ác bằng thân, sống ác bằng lời, sống ác bằng ý, chê bai những bậc cao quý, thấy sai, làm theo cái thấy sai. Sau khi thân tan rã, sau khi chết, họ sinh vào chỗ dữ, đường dữ, chỗ sa đọa, địa ngục. Còn những loài này sống lành bằng thân, sống lành bằng lời, sống lành bằng ý, không chê bai những bậc cao quý, thấy đúng, làm theo cái thấy đúng. Sau khi thân tan rã, sau khi chết, họ sinh vào chỗ lành, cõi trời.’ Như vậy, với mắt trời trong sạch, vượt hơn mắt người thường, Đức Thế Tôn thấy các loài chết đi rồi sinh lại, kẻ thấp kẻ cao, người đẹp người xấu, kẻ đi về chỗ lành người đi về chỗ dữ; Ngài biết các loài đi theo việc mình đã làm.",
  "mn12:18.2": "Này Sāriputta, việc Đức Thế Tôn với mắt trời trong sạch, vượt hơn mắt người thường, thấy các loài chết đi rồi sinh lại, kẻ thấp kẻ cao, người đẹp người xấu, kẻ đi về chỗ lành người đi về chỗ dữ; biết các loài đi theo việc mình đã làm: ‘Quả thật, những loài này sống ác bằng thân, sống ác bằng lời, sống ác bằng ý, chê bai những bậc cao quý, thấy sai, làm theo cái thấy sai. Sau khi thân tan rã, sau khi chết, họ sinh vào chỗ dữ, đường dữ, chỗ sa đọa, địa ngục. Còn những loài này sống lành bằng thân, sống lành bằng lời, sống lành bằng ý, không chê bai những bậc cao quý, thấy đúng, làm theo cái thấy đúng. Sau khi thân tan rã, sau khi chết, họ sinh vào chỗ lành, cõi trời.’ Như vậy, với mắt trời trong sạch, vượt hơn mắt người thường, Đức Thế Tôn thấy các loài chết đi rồi sinh lại, kẻ thấp kẻ cao, người đẹp người xấu, kẻ đi về chỗ lành người đi về chỗ dữ; Ngài biết các loài đi theo việc mình đã làm. Điều ấy cũng là một sức mạnh của Như Lai. Nhờ sức mạnh ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:19.1": "Lại nữa, này Sāriputta, do các dòng rỉ chảy đã dứt sạch, Đức Thế Tôn tự mình biết rõ, tự mình chạm đến và an trú ngay trong đời này với sự mở thoát của lòng và sự mở thoát nhờ hiểu rõ, không còn dòng rỉ chảy.",
  "mn12:19.2": "Này Sāriputta, việc Đức Thế Tôn do các dòng rỉ chảy đã dứt sạch, tự mình biết rõ, tự mình chạm đến và an trú ngay trong đời này với sự mở thoát của lòng và sự mở thoát nhờ hiểu rõ, không còn dòng rỉ chảy, điều ấy cũng là một sức mạnh của Như Lai. Nhờ sức mạnh ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:20.1": "Này Sāriputta, đó là mười sức mạnh của Như Lai. Nhờ có những sức mạnh ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:21.1": "Này Sāriputta, nếu có người nói về Ta, người biết như vậy, thấy như vậy, rằng:",
  "mn12:21.2": "‘Sa-môn Gotama không có sự biết và thấy đặc biệt nào cao hơn mức người thường, xứng với bậc cao quý;",
  "mn12:21.3": "Sa-môn Gotama chỉ giảng dạy điều được gọt giũa bởi suy nghĩ, theo sau sự dò xét, do tự mình nghĩ ra’,",
  "mn12:21.4": "thì này Sāriputta, nếu người ấy không bỏ lời nói ấy, không bỏ ý nghĩ ấy, không buông cái thấy ấy, thì sẽ bị quăng vào địa ngục như bị mang đến đặt xuống ở đó.",
  "mn12:21.5": "Này Sāriputta, cũng như một Tỳ Kheo đầy đủ nết sống, đầy đủ tâm yên vững, đầy đủ sự hiểu rõ, có thể ngay trong đời này đạt đến sự biết rốt ráo, Ta nói việc ấy chắc thật như vậy.",
  "mn12:21.6": "Nếu người ấy không bỏ lời nói ấy, không bỏ ý nghĩ ấy, không buông cái thấy ấy, thì sẽ bị quăng vào địa ngục như bị mang đến đặt xuống ở đó.",
  "mn12:22.1": "Này Sāriputta, đây là bốn điều không run sợ của Như Lai. Nhờ có bốn điều không run sợ ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:22.2": "Bốn điều ấy là gì?",
  "mn12:23.1": "‘Ông tự nhận là bậc tự mình giác ngộ trọn vẹn, nhưng những điều này ông chưa hiểu thấu.’ Này Sāriputta, Ta không thấy một dấu hiệu nào để một sa-môn, một bà-la-môn, một vị trời, Ma vương, Phạm thiên, hay bất cứ ai trong đời, có thể chất vấn Ta đúng lẽ về việc ấy.",
  "mn12:23.2": "Này Sāriputta, vì không thấy dấu hiệu ấy, Ta sống trong yên ổn, không sợ hãi, và vững vàng.",
  "mn12:24.1": "‘Ông tự nhận là người đã dứt sạch các dòng rỉ chảy, nhưng những dòng rỉ chảy này nơi ông vẫn chưa dứt sạch.’ Này Sāriputta, Ta không thấy một dấu hiệu nào để một sa-môn, một bà-la-môn, một vị trời, Ma vương, Phạm thiên, hay bất cứ ai trong đời, có thể chất vấn Ta đúng lẽ về việc ấy.",
  "mn12:24.2": "Này Sāriputta, vì không thấy dấu hiệu ấy, Ta sống trong yên ổn, không sợ hãi, và vững vàng.",
  "mn12:25.1": "‘Những điều ông nói là chướng ngại, nếu ai làm theo thì không đến nỗi thành chướng ngại.’ Này Sāriputta, Ta không thấy một dấu hiệu nào để một sa-môn, một bà-la-môn, một vị trời, Ma vương, Phạm thiên, hay bất cứ ai trong đời, có thể chất vấn Ta đúng lẽ về việc ấy.",
  "mn12:25.2": "Này Sāriputta, vì không thấy dấu hiệu ấy, Ta sống trong yên ổn, không sợ hãi, và vững vàng.",
  "mn12:26.1": "‘Điều ông giảng dạy vì mục đích ấy, nếu ai làm theo thì không đưa đến chấm dứt hẳn sự khổ đau một cách đúng đắn.’ Này Sāriputta, Ta không thấy một dấu hiệu nào để một sa-môn, một bà-la-môn, một vị trời, Ma vương, Phạm thiên, hay bất cứ ai trong đời, có thể chất vấn Ta đúng lẽ về việc ấy.",
  "mn12:26.2": "Này Sāriputta, vì không thấy dấu hiệu ấy, Ta sống trong yên ổn, không sợ hãi, và vững vàng.",
  "mn12:27.1": "Này Sāriputta, đó là bốn điều không run sợ của Như Lai. Nhờ có bốn điều không run sợ ấy, Như Lai nhận lấy chỗ đứng của bậc đầu đàn, cất tiếng rống sư tử giữa các hội chúng, làm cho bánh xe đời sống phạm hạnh lăn đi.",
  "mn12:28.1": "Này Sāriputta, nếu có người nói về Ta, người biết như vậy, thấy như vậy, rằng:",
  "mn12:28.2": "‘Sa-môn Gotama không có điều gì vượt hơn người thường, không có sự biết và thấy đặc biệt xứng bậc cao quý; Sa-môn Gotama chỉ nói điều mình nghĩ ra bằng suy luận, theo điều mình tự xét rồi tự nói ra’—",
  "mn12:28.3": "Này Sāriputta, ai không bỏ lời nói ấy, không bỏ ý nghĩ ấy, không buông cái thấy ấy, thì như bị đem đặt xuống, người ấy sẽ rơi vào địa ngục.",
  "mn12:28.4": "Cũng như, này Sāriputta, một Tỳ Kheo đầy đủ nết tốt, tâm yên vững, sự hiểu rõ, có thể ngay trong đời này đạt đến chỗ biết rõ trọn vẹn; cũng chắc thật như vậy, này Sāriputta, Ta nói điều này.",
  "mn12:28.5": "Ai không bỏ lời nói ấy, không bỏ ý nghĩ ấy, không buông cái thấy ấy, thì như bị đem đặt xuống, người ấy sẽ rơi vào địa ngục.",
  "mn12:29.1": "Này Sāriputta, có tám hội chúng này.",
  "mn12:29.2": "Tám là những hội chúng nào?",
  "mn12:29.3": "Hội chúng vua chúa, hội chúng bà-la-môn, hội chúng người chủ nhà, hội chúng sa-môn, hội chúng chư thiên thuộc bốn vị vua lớn, hội chúng chư thiên cõi Ba Mươi Ba, hội chúng của Ma vương, hội chúng Phạm thiên—",
  "mn12:29.4": "này Sāriputta, đó là tám hội chúng ấy.",
  "mn12:29.5": "Này Sāriputta, Như Lai có đủ bốn điều vững dạ này nên đến gần và bước vào tám hội chúng ấy.",
  "mn12:29.6": "Này Sāriputta, Ta nhớ rõ rằng Ta đã đến gần hàng trăm hội chúng vua chúa.",
  "mn12:29.7": "Ở đó, Ta đã từng ngồi chung, từng trò chuyện, và từng cùng bàn luận.",
  "mn12:29.8": "Này Sāriputta, Ta không thấy một dấu hiệu nào cho rằng ở đó nỗi sợ hay sự ngại ngùng sẽ đến với Ta.",
  "mn12:29.9": "Này Sāriputta, vì không thấy dấu hiệu ấy, Ta sống yên ổn, không sợ hãi, lòng vững dạ.",
  "mn12:30.1": "Này Sāriputta, Ta nhớ rõ rằng Ta đã đến gần hàng trăm hội chúng bà-la-môn…",
  "mn12:30.2": "hội chúng người chủ nhà…",
  "mn12:30.3": "hội chúng sa-môn…",
  "mn12:30.4": "hội chúng chư thiên thuộc bốn vị vua lớn…",
  "mn12:30.5": "hội chúng chư thiên cõi Ba Mươi Ba…",
  "mn12:30.6": "hội chúng của Ma vương…",
  "mn12:30.7": "hội chúng Phạm thiên.",
  "mn12:30.8": "Ở đó, Ta đã từng ngồi chung, từng trò chuyện, và từng cùng bàn luận.",
  "mn12:30.9": "Này Sāriputta, Ta không thấy một dấu hiệu nào cho rằng ở đó nỗi sợ hay sự ngại ngùng sẽ đến với Ta.",
  "mn12:30.10": "Này Sāriputta, vì không thấy dấu hiệu ấy, Ta sống yên ổn, không sợ hãi, lòng vững dạ.",
  "mn12:31.1": "Này Sāriputta, ai biết Ta như vậy, thấy Ta như vậy, mà lại nói thế này:",
  "mn12:31.2": "‘Sa-môn Gotama không có điều gì vượt hơn người thường, không có sự biết và thấy đặc biệt xứng bậc cao quý; Sa-môn Gotama chỉ nói điều mình nghĩ ra bằng suy luận, theo điều mình tự xét rồi tự nói ra’—",
  "mn12:31.3": "này Sāriputta, ai không bỏ lời nói ấy, không bỏ ý nghĩ ấy, không buông cái thấy ấy, thì như bị đem đặt xuống, người ấy sẽ rơi vào địa ngục.",
  "mn12:31.4": "Cũng như, này Sāriputta, một Tỳ Kheo đầy đủ nết tốt, tâm yên vững, sự hiểu rõ, có thể ngay trong đời này đạt đến chỗ biết rõ trọn vẹn; cũng chắc thật như vậy, này Sāriputta, Ta nói điều này.",
  "mn12:31.5": "Ai không bỏ lời nói ấy, không bỏ ý nghĩ ấy, không buông cái thấy ấy, thì như bị đem đặt xuống, người ấy sẽ rơi vào địa ngục.",
  "mn12:32.1": "Này Sāriputta, có bốn cách sinh ra này.",
  "mn12:32.2": "Bốn là những cách nào?",
  "mn12:32.3": "Có bốn cách sinh ra: sinh từ trứng, sinh từ bào thai, sinh từ chỗ ẩm ướt, và sinh ra liền.",
  "mn12:33.1": "Này Sāriputta, thế nào là sinh từ trứng?",
  "mn12:33.2": "Này Sāriputta, những loài nào chui ra khỏi vỏ trứng mà sinh ra—",
  "mn12:33.3": "đó gọi là sinh từ trứng, này Sāriputta.",
  "mn12:33.4": "Này Sāriputta, thế nào là sinh từ bào thai?",
  "mn12:33.5": "Này Sāriputta, những loài nào chui ra khỏi bọc thai mà sinh ra—",
  "mn12:33.6": "đó gọi là sinh từ bào thai, này Sāriputta.",
  "mn12:33.7": "Này Sāriputta, thế nào là sinh từ chỗ ẩm ướt?",
  "mn12:33.8": "Này Sāriputta, những loài nào sinh ra trong cá thối, trong xác thối, trong cháo hư, trong hố phân, hay trong chỗ bùn lầy—",
  "mn12:33.9": "đó gọi là sinh từ chỗ ẩm ướt, này Sāriputta.",
  "mn12:33.10": "Này Sāriputta, thế nào là sinh ra liền?",
  "mn12:33.11": "Chư thiên, chúng ở địa ngục, một số người, và một số loài rơi vào cảnh dữ—",
  "mn12:33.12": "đó gọi là sinh ra liền, này Sāriputta.",
  "mn12:33.13": "Này Sāriputta, đó là bốn cách sinh ra.",
  "mn12:34.1": "Này Sāriputta, nếu có người biết ta như vậy, thấy ta như vậy, mà lại nói rằng:",
  "mn12:34.2": "‘Sa môn Gotama không có sự biết và thấy đặc biệt nào vượt hơn mức người thường, xứng bậc cao quý; sa môn Gotama chỉ dùng suy luận mà giảng dạy điều đúng, theo sau sự dò xét, do tự mình nghĩ ra’,",
  "mn12:34.3": "thì này Sāriputta, nếu người ấy không bỏ lời nói ấy, không bỏ ý nghĩ ấy, không buông cái thấy ấy, thì sẽ bị đặt vào địa ngục như bị mang đến đặt xuống ở đó.",
  "mn12:34.4": "Ví như, này Sāriputta, một Tỳ Kheo đầy đủ nết tốt, tâm yên vững, và sự hiểu rõ, có thể ngay trong đời này đạt đến chỗ biết rõ trọn vẹn; cũng chắc chắn như vậy, này Sāriputta, ta nói điều này.",
  "mn12:34.5": "Nếu không bỏ lời nói ấy, không bỏ ý nghĩ ấy, không buông cái thấy ấy, thì sẽ bị đặt vào địa ngục như bị mang đến đặt xuống ở đó.",
  "mn12:35.1": "Này Sāriputta, có năm đường đi đến.",
  "mn12:35.2": "Năm là những gì?",
  "mn12:35.3": "Địa ngục, loài vật, cõi ngạ quỷ, loài người, và chư thiên.",
  "mn12:36.1": "Này Sāriputta, ta biết địa ngục, biết con đường đưa đến địa ngục, và biết cách sống đưa đến địa ngục;",
  "mn12:36.2": "ta cũng biết người sống theo cách nào thì khi thân tan rã, sau khi chết, sẽ rơi vào cõi dữ, chỗ xấu, chỗ sa xuống, địa ngục.",
  "mn12:36.3": "Này Sāriputta, ta biết loài vật, biết con đường đưa đến loài vật, và biết cách sống đưa đến loài vật;",
  "mn12:36.4": "ta cũng biết người sống theo cách nào thì khi thân tan rã, sau khi chết, sẽ sinh vào loài vật.",
  "mn12:36.5": "Này Sāriputta, ta biết cõi ngạ quỷ, biết con đường đưa đến cõi ngạ quỷ, và biết cách sống đưa đến cõi ngạ quỷ;",
  "mn12:36.6": "ta cũng biết người sống theo cách nào thì khi thân tan rã, sau khi chết, sẽ sinh vào cõi ngạ quỷ.",
  "mn12:36.7": "Này Sāriputta, ta biết loài người, biết con đường đưa đến cõi người, và biết cách sống đưa đến cõi người;",
  "mn12:36.8": "ta cũng biết người sống theo cách nào thì khi thân tan rã, sau khi chết, sẽ sinh vào loài người.",
  "mn12:36.9": "Này Sāriputta, Ta biết chư thiên, biết con đường đưa đến cõi trời, và biết cách sống đưa đến cõi trời;",
  "mn12:36.10": "Ta cũng biết người sống theo cách nào thì khi thân tan rã, sau khi chết, sẽ sinh vào nơi lành, cõi trời.",
  "mn12:36.11": "Này Sāriputta, Ta biết Niết-bàn, biết con đường đưa đến Niết-bàn, và biết cách sống đưa đến Niết-bàn;",
  "mn12:36.12": "Ta cũng biết người sống theo cách nào thì do dứt sạch các lậu hoặc, ngay trong đời này, tự mình biết rõ, tự mình thấy rõ rồi an trú trong sự giải thoát của tâm, sự giải thoát nhờ hiểu rõ, không còn lậu hoặc.",
  "mn12:37.1": "Này Sāriputta, ở đây, có người Ta dùng tâm dò biết tâm họ như sau:",
  "mn12:37.2": "người này sống như vậy, đi đứng làm việc như vậy, và đang đi trên con đường như vậy, nên khi thân tan rã, sau khi chết, sẽ sinh vào cảnh xấu, nơi khổ sở, chỗ sa đọa, địa ngục.",
  "mn12:37.3": "Rồi một thời gian sau, Ta thấy người ấy bằng mắt trời, trong sáng, vượt hơn mắt người, rằng khi thân tan rã, sau khi chết, người ấy đã sinh vào cảnh xấu, nơi khổ sở, chỗ sa đọa, địa ngục, đang chịu toàn những cảm giác đau đớn dữ dội, gay gắt.",
  "mn12:37.4": "Ví như, này Sāriputta, có một hố than sâu hơn chiều cao một người, đầy than hồng, không lửa bốc, không khói bay.",
  "mn12:37.5": "Rồi có một người đi đến, bị nắng đốt, bị nóng bức hành hạ, mệt lả, khát khô, đi trên một con đường chỉ dẫn thẳng đến chính hố than ấy.",
  "mn12:37.6": "Một người có mắt thấy người đó thì nói rằng:",
  "mn12:37.7": "‘Người này đang sống như vậy, đi đứng làm việc như vậy, và đang đi trên con đường như vậy, nên sẽ đi đến chính hố than này.’",
  "mn12:37.8": "Rồi một thời gian sau, người ấy thấy người kia đã rơi vào hố than đó, đang chịu toàn những cảm giác đau đớn dữ dội, gay gắt.",
  "mn12:37.9": "Cũng vậy, này Sāriputta, ở đây, có người Ta dùng tâm dò biết tâm họ như sau:",
  "mn12:37.10": "người này sống như vậy, đi đứng làm việc như vậy, và đang đi trên con đường như vậy, nên khi thân tan rã, sau khi chết, sẽ sinh vào cảnh xấu, nơi khổ sở, chỗ sa đọa, địa ngục.",
  "mn12:37.11": "Rồi một thời gian sau, Ta thấy người ấy bằng mắt trời, trong sáng, vượt hơn mắt người, rằng khi thân tan rã, sau khi chết, người ấy đã sinh vào cảnh xấu, nơi khổ sở, chỗ sa đọa, địa ngục, đang chịu toàn những cảm giác đau đớn dữ dội, gay gắt.",
  "mn12:38.1": "Này Sāriputta, lại nữa, ở đây, có người Ta dùng tâm dò biết tâm họ như sau:",
  "mn12:38.2": "người này sống như vậy, đi đứng làm việc như vậy, và đang đi trên con đường như vậy, nên khi thân tan rã, sau khi chết, sẽ sinh vào loài vật.",
  "mn12:38.3": "Rồi một thời gian sau, Ta thấy người ấy bằng mắt trời, trong sáng, vượt hơn mắt người, rằng khi thân tan rã, sau khi chết, người ấy đã sinh vào loài vật, đang chịu những cảm giác đau đớn dữ dội, gay gắt.",
  "mn12:38.4": "Ví như, này Sāriputta, có một hố phân sâu hơn chiều cao một người, đầy phân.",
  "mn12:38.5": "Rồi có một người đi đến, bị nắng đốt, bị nóng bức hành hạ, mệt lả, khát khô, đi trên một con đường chỉ dẫn thẳng đến chính hố phân ấy.",
  "mn12:38.6": "Một người có mắt thấy người đó thì nói rằng:",
  "mn12:38.7": "‘Người này đang sống như vậy, đi đứng làm việc như vậy, và đang đi trên con đường như vậy, nên sẽ đi đến chính hố phân này.’",
  "mn12:38.8": "Rồi một thời gian sau, người ấy thấy người kia đã rơi vào hố phân đó, đang chịu những cảm giác đau đớn dữ dội, gay gắt.",
  "mn12:38.9": "Cũng vậy, này Sāriputta, ở đây, có người Ta dùng tâm dò biết tâm họ như sau:",
  "mn12:38.10": "người này sống như vậy, đi đứng làm việc như vậy, và đang đi trên con đường như vậy, nên khi thân tan rã, sau khi chết, sẽ sinh vào loài vật.",
  "mn12:38.11": "Rồi một thời gian sau, Ta thấy người ấy bằng mắt trời, trong sáng, vượt hơn mắt người, rằng khi thân tan rã, sau khi chết, người ấy đã sinh vào loài vật, đang chịu những cảm giác đau đớn dữ dội, gay gắt.",
  "mn12:39.1": "Này Sāriputta, lại nữa, ở đây, có người Ta dùng tâm dò biết tâm họ như sau:",
  "mn12:39.2": "người này sống như vậy, đi đứng làm việc như vậy, và đang đi trên con đường như vậy, nên khi thân tan rã, sau khi chết, sẽ sinh vào cõi ngạ quỷ.",
  "mn12:39.3": "Rồi một thời gian sau, Ta thấy người ấy bằng mắt trời, trong sáng, vượt hơn mắt người, rằng khi thân tan rã, sau khi chết, người ấy đã sinh vào cõi ngạ quỷ, đang chịu rất nhiều đau đớn.",
  "mn12:39.4": "Ví như, này Sāriputta, có một cây mọc trên chỗ đất gồ ghề, lá cành thưa thớt, bóng lốm đốm.",
  "mn12:39.5": "Rồi có một người đi đến, bị nắng đốt, bị hơi nóng hành hạ, mệt lả, khát khô, thiếu nước, đi theo một con đường thẳng, nhắm đúng đến cây ấy.",
  "mn12:39.6": "Người có mắt thấy người ấy thì nói như vầy:",
  "mn12:39.7": "‘Người này đi như thế, bước như thế, đã lên đúng con đường ấy, thì sẽ đến chính cây này.’",
  "mn12:39.8": "Rồi sau một thời gian, người ấy thấy người kia đang ngồi hay nằm dưới bóng cây ấy, đang cảm nhận nhiều đau đớn.",
  "mn12:39.9": "Cũng vậy, này Sāriputta, ở đây ta dùng tâm biết rõ tâm của một người như vầy:",
  "mn12:39.10": "‘Người này sống như thế, đi như thế, đã lên con đường ấy, thì khi thân tan rã, sau khi chết, sẽ sinh vào cõi ngạ quỷ.’",
  "mn12:39.11": "Rồi sau một thời gian, ta thấy người ấy bằng mắt trời, trong sạch, vượt hơn mắt người, rằng khi thân tan rã, sau khi chết, người ấy đã sinh vào cõi ngạ quỷ, đang cảm nhận nhiều đau đớn.",
  "mn12:40.1": "Lại nữa, này Sāriputta, ở đây ta dùng tâm biết rõ tâm của một người như vầy:",
  "mn12:40.2": "‘Người này sống như thế, đi như thế, đã lên con đường ấy, thì khi thân tan rã, sau khi chết, sẽ sinh lại giữa loài người.’",
  "mn12:40.3": "Rồi sau một thời gian, ta thấy người ấy bằng mắt trời, trong sạch, vượt hơn mắt người, rằng khi thân tan rã, sau khi chết, người ấy đã sinh lại giữa loài người, đang cảm nhận nhiều điều dễ chịu.",
  "mn12:40.4": "Ví như, này Sāriputta, có một cây mọc trên nền đất bằng, lá cành sum suê, bóng mát dày kín.",
  "mn12:40.5": "Rồi có một người đi đến, bị nắng đốt, bị hơi nóng hành hạ, mệt lả, khát khô, thiếu nước, đi theo một con đường thẳng, nhắm đúng đến cây ấy.",
  "mn12:40.6": "Người có mắt thấy người ấy thì nói như vầy:",
  "mn12:40.7": "‘Người này đi như thế, bước như thế, đã lên đúng con đường ấy, thì sẽ đến chính cây này.’",
  "mn12:40.8": "Rồi sau một thời gian, người ấy thấy người kia đang ngồi hay nằm dưới bóng cây ấy, đang cảm nhận nhiều điều dễ chịu.",
  "mn12:40.9": "Cũng vậy, này Sāriputta, ở đây ta dùng tâm biết rõ tâm của một người như vầy:",
  "mn12:40.10": "‘Người này sống như thế, đi như thế, đã lên con đường ấy, thì khi thân tan rã, sau khi chết, sẽ sinh lại giữa loài người.’",
  "mn12:40.11": "Rồi sau một thời gian, ta thấy người ấy bằng mắt trời, trong sạch, vượt hơn mắt người, rằng khi thân tan rã, sau khi chết, người ấy đã sinh lại giữa loài người, đang cảm nhận nhiều điều dễ chịu.",
  "mn12:41.1": "Lại nữa, này Sāriputta, ở đây ta dùng tâm biết rõ tâm của một người như vầy:",
  "mn12:41.2": "‘Người này sống như thế, đi như thế, đã lên con đường ấy, thì khi thân tan rã, sau khi chết, sẽ sinh vào cõi lành, cõi trời.’",
  "mn12:41.3": "Rồi sau một thời gian, ta thấy người ấy bằng mắt trời, trong sạch, vượt hơn mắt người, rằng khi thân tan rã, sau khi chết, người ấy đã sinh vào cõi lành, cõi trời, đang cảm nhận toàn là điều dễ chịu.",
  "mn12:41.4": "Ví như, này Sāriputta, có một tòa nhà cao, trong đó có phòng trên gác được trét láng kỹ, kín gió, then cài chắc chắn, cửa sổ đóng lại.",
  "mn12:41.5": "Ở đó có một giường dài trải nệm lông, phủ tấm trải đẹp, đắp tấm phủ mềm, có mái che phía trên, có gối đỏ ở cả hai đầu.",
  "mn12:41.6": "Rồi có một người đi đến, bị nắng đốt, bị hơi nóng hành hạ, mệt lả, khát khô, thiếu nước, đi theo một con đường thẳng, nhắm đúng đến tòa nhà ấy.",
  "mn12:41.7": "Người có mắt thấy người ấy thì nói như vầy:",
  "mn12:41.8": "‘Người này đi như thế, bước như thế, đã lên đúng con đường ấy, thì sẽ đến chính tòa nhà này.’",
  "mn12:41.9": "Rồi sau một thời gian, người ấy thấy người kia đang ngồi hay nằm trong tòa nhà ấy, trong phòng trên gác ấy, trên giường ấy, đang cảm nhận toàn là điều dễ chịu.",
  "mn12:41.10": "Cũng vậy, này Sāriputta, ở đây ta dùng tâm biết rõ tâm của một người như vầy:",
  "mn12:41.11": "‘Người này sống như thế, đi như thế, đã lên con đường ấy, thì khi thân tan rã, sau khi chết, sẽ sinh vào cõi lành, cõi trời.’",
  "mn12:41.12": "Rồi sau một thời gian, ta thấy người ấy bằng mắt trời, trong sạch, vượt hơn mắt người, rằng khi thân tan rã, sau khi chết, người ấy đã sinh vào cõi lành, cõi trời, đang cảm nhận toàn là điều dễ chịu.",
  "mn12:42.1": "Này Xá Lợi Phất, ở đây ta dùng tâm biết thấu tâm của một người nào đó như sau:",
  "mn12:42.2": "người này đang đi theo như vậy, đang sống như vậy, đã bước lên con đường ấy, nên sẽ nhờ dứt sạch các lậu hoặc mà tự mình biết rõ, tự mình chạm tới và an trú trong sự giải thoát của tâm, sự giải thoát nhờ hiểu rõ, không còn lậu hoặc, ngay trong đời này.",
  "mn12:42.3": "Rồi sau một thời gian, ta thấy người ấy đã nhờ dứt sạch các lậu hoặc mà tự mình biết rõ, tự mình chạm tới và an trú trong sự giải thoát của tâm, sự giải thoát nhờ hiểu rõ, không còn lậu hoặc, ngay trong đời này, và đang cảm nhận một sự dễ chịu trọn vẹn.",
  "mn12:42.4": "Cũng như, này Xá Lợi Phất, có một hồ nước trong, nước ngon, mát, sạch, có bờ xuống dễ dàng, rất đáng ưa.",
  "mn12:42.5": "Không xa hồ ấy có một bụi rừng rậm.",
  "mn12:42.6": "Rồi có một người đi đến, bị nắng đốt, bị nóng bức hành hạ, mệt lả, khát khô, đang đi theo con đường thẳng hướng ngay đến hồ nước ấy.",
  "mn12:42.7": "Một người có mắt thấy người ấy thì nói rằng:",
  "mn12:42.8": "‘Người này đang đi như vậy, đang sống như vậy, đã bước lên con đường ấy, nên sẽ đến chính hồ nước này.’",
  "mn12:42.9": "Rồi sau một thời gian, người ấy lội xuống hồ, tắm rửa, uống nước, làm lắng dịu hết mọi mệt nhọc, rã rời và nóng bức, rồi đi lên, ngồi hay nằm trong bụi rừng ấy, cảm nhận một sự dễ chịu trọn vẹn.",
  "mn12:42.10": "Cũng vậy, này Xá Lợi Phất, ở đây ta dùng tâm biết thấu tâm của một người nào đó như sau:",
  "mn12:42.11": "‘Người này đang đi theo như vậy, đang sống như vậy, đã bước lên con đường ấy, nên sẽ nhờ dứt sạch các lậu hoặc mà tự mình biết rõ, tự mình chạm tới và an trú trong sự giải thoát của tâm, sự giải thoát nhờ hiểu rõ, không còn lậu hoặc, ngay trong đời này.’",
  "mn12:42.12": "Rồi sau một thời gian, ta thấy người ấy đã nhờ dứt sạch các lậu hoặc mà tự mình biết rõ, tự mình chạm tới và an trú trong sự giải thoát của tâm, sự giải thoát nhờ hiểu rõ, không còn lậu hoặc, ngay trong đời này, và đang cảm nhận một sự dễ chịu trọn vẹn.",
  "mn12:42.13": "Này Xá Lợi Phất, đó là năm nẻo đi.",
  "mn12:43.1": "Này Xá Lợi Phất, nếu có người biết ta như vậy, thấy ta như vậy, mà lại nói rằng:",
  "mn12:43.2": "‘Sa môn Gotama không có gì vượt hơn mức người thường, không có sự biết và thấy riêng của bậc cao quý.",
  "mn12:43.3": "Sa môn Gotama chỉ dùng suy nghĩ mà giảng dạy điều mình nêu ra, chỉ theo lối dò xét, chỉ do tự mình nghĩ ra thôi.’",
  "mn12:43.4": "Này Xá Lợi Phất, người ấy nếu không bỏ lời nói ấy, không bỏ ý nghĩ ấy, không buông cái thấy ấy, thì sẽ bị quăng vào địa ngục như thể bị mang đến đặt xuống ở đó.",
  "mn12:43.5": "Cũng như một Tỳ Kheo đầy đủ nết tốt, tâm yên vững, sự hiểu rõ, có thể ngay trong đời này đạt tới sự biết rốt ráo; này Xá Lợi Phất, ta nói việc ấy chắc thật là như vậy.",
  "mn12:43.6": "Người kia nếu không bỏ lời nói ấy, không bỏ ý nghĩ ấy, không buông cái thấy ấy, thì sẽ bị quăng vào địa ngục như thể bị mang đến đặt xuống ở đó.",
  "mn12:44.1": "Này Xá Lợi Phất, ta nhớ rõ rằng ta đã từng sống đời phạm hạnh đủ bốn phần:",
  "mn12:44.2": "ta từng là người khổ hạnh, khổ hạnh đến mức cùng cực; từng sống thô sơ, thô sơ đến mức cùng cực; từng tránh né điều nhơ bẩn, tránh né đến mức cùng cực; từng sống riêng vắng, riêng vắng đến mức cùng cực.",
  "mn12:45.1": "Trong đó, này Xá Lợi Phất, sự khổ hạnh của ta là thế này: ta sống trần truồng, bỏ hết lề thói thường, lấy tay liếm sạch bát tay mình; không nhận lời mời đến ăn, không đứng chờ để được mời; không nhận đồ được mang đến, không nhận đồ làm riêng cho mình, không nhận lời mời.",
  "mn12:45.2": "Ta không nhận từ miệng nồi, không nhận từ miệng chảo, không nhận ở giữa hai người, không nhận ở giữa cây gậy, không nhận ở giữa chày giã, không nhận từ hai người đang ăn, không nhận từ người đang mang thai, không nhận từ người đang cho con bú, không nhận từ người đang ở với đàn ông, không nhận ở chỗ có hô gọi góp phần, không nhận ở chỗ có chó đứng chờ, không nhận ở chỗ ruồi bu kín; ta không ăn cá, không ăn thịt, không uống rượu men, không uống rượu nấu, không uống nước vo gạo.",
  "mn12:45.3": "Ta có khi chỉ đến một nhà, chỉ nhận một miếng; có khi đến hai nhà, nhận hai miếng... có khi đến bảy nhà, nhận bảy miếng.",
  "mn12:45.4": "Ta sống nhờ một lần cho, sống nhờ hai lần cho... sống nhờ bảy lần cho.",
  "mn12:45.5": "Ta có khi một ngày mới ăn một lần, có khi hai ngày mới ăn một lần... có khi bảy ngày mới ăn một lần; như vậy ta sống theo lối ăn theo kỳ, cho đến nửa tháng mới ăn một lần.",
  "mn12:45.6": "Ta có khi ăn rau, ăn kê, ăn lúa hoang, ăn da vụn, ăn rong rêu, ăn cám gạo, ăn nước vo gạo, ăn bã mè, ăn cỏ, ăn phân bò; ta sống bằng rễ quả trong rừng, ăn trái rụng.",
  "mn12:45.7": "Ta mặc vải gai, mặc vải thô, mặc vải liệm xác, mặc vải nhặt từ đống rác, mặc áo bằng vỏ cây, mặc da thú, mặc tấm da thú, mặc áo cỏ kusa, mặc áo vỏ cây, mặc áo bằng tấm gỗ, mặc áo dệt bằng tóc người, mặc áo dệt bằng lông đuôi ngựa, mặc áo bằng cánh chim cú.",
  "mn12:45.8": "Ta cũng nhổ tóc nhổ râu, chuyên sống theo lối nhổ tóc nhổ râu.",
  "mn12:45.9": "Ta cũng đứng mãi, từ chối ngồi xuống.",
  "mn12:45.10": "Ta còn ngồi chồm hổm, dốc sức giữ thế ngồi ấy;",
  "mn12:45.11": "ta còn nằm trên ổ gai, lấy ổ gai làm chỗ nằm;",
  "mn12:45.12": "ta còn sống chuyên lao mình xuống nước ngày ba lần—",
  "mn12:45.13": "như vậy, ta sống dốc sức hành hạ và giày vò thân mình bằng nhiều cách như thế.",
  "mn12:45.14": "Này Sāriputta, đó là cách khổ hạnh của ta.",
  "mn12:46.1": "Này Sāriputta, khi ấy sự thô nhám của ta là thế này—",
  "mn12:46.2": "bụi đất và cáu ghét bám đầy trên thân ta suốt nhiều năm, đóng thành từng mảng.",
  "mn12:46.3": "Này Sāriputta, cũng như gốc cây tinduka để lâu nhiều năm thì bám đầy bụi đất, đóng thành từng mảng; cũng vậy, bụi đất và cáu ghét bám đầy trên thân ta suốt nhiều năm, đóng thành từng mảng.",
  "mn12:46.4": "Nhưng này Sāriputta, ta không hề nghĩ rằng:",
  "mn12:46.5": "‘Ước gì ta lấy tay chà sạch lớp bụi đất và cáu ghét này, hay người khác lấy tay chà sạch nó cho ta.’",
  "mn12:46.6": "Này Sāriputta, ta không hề nghĩ như vậy.",
  "mn12:46.7": "Này Sāriputta, đó là sự thô nhám của ta.",
  "mn12:47.1": "Này Sāriputta, khi ấy sự ghê sợ điều ác của ta là thế này—",
  "mn12:47.2": "ta bước tới với nhớ biết rõ, ta bước lui với nhớ biết rõ, đến mức lòng thương của ta cũng hiện rõ đối với từng giọt nước:",
  "mn12:47.3": "‘Mong sao ta đừng làm hại những sinh vật nhỏ bé sống trong đó.’",
  "mn12:47.4": "Này Sāriputta, đó là sự ghê sợ điều ác của ta.",
  "mn12:48.1": "Này Sāriputta, khi ấy sự sống riêng một mình của ta là thế này—",
  "mn12:48.2": "ta đi sâu vào một vùng rừng nào đó và sống ở đó.",
  "mn12:48.3": "Khi ta thấy người chăn bò, người giữ súc vật, người cắt cỏ, người kiếm củi, hay người làm việc trong rừng, thì ta đi từ rừng này sang rừng khác, từ chỗ rậm này sang chỗ rậm khác, từ chỗ trũng này sang chỗ trũng khác, từ chỗ cao này sang chỗ cao khác.",
  "mn12:48.4": "Vì sao vậy?",
  "mn12:48.5": "Để họ không thấy ta, và ta cũng không thấy họ.",
  "mn12:48.6": "Này Sāriputta, cũng như con nai sống trong rừng, khi thấy người thì chạy từ rừng này sang rừng khác, từ chỗ rậm này sang chỗ rậm khác, từ chỗ trũng này sang chỗ trũng khác, từ chỗ cao này sang chỗ cao khác;",
  "mn12:48.7": "cũng vậy, này Sāriputta, khi ta thấy người chăn bò, người giữ súc vật, người cắt cỏ, người kiếm củi, hay người làm việc trong rừng, thì ta đi từ rừng này sang rừng khác, từ chỗ rậm này sang chỗ rậm khác, từ chỗ trũng này sang chỗ trũng khác, từ chỗ cao này sang chỗ cao khác.",
  "mn12:48.8": "Vì sao vậy?",
  "mn12:48.9": "Để họ không thấy ta, và ta cũng không thấy họ.",
  "mn12:48.10": "Này Sāriputta, đó là sự sống riêng một mình của ta.",
  "mn12:49.1": "Này Sāriputta, rồi ta đến những bãi nhốt bò, nơi bò đã đứng đó và người chăn đã đi khỏi; ở đó ta đến gần bằng cách chống trên bốn chi, rồi ăn phân của những con bê còn non đang bú sữa.",
  "mn12:49.2": "Này Sāriputta, chừng nào phân và nước tiểu của chính ta còn chưa hết, thì ta còn ăn cả phân và nước tiểu của chính mình.",
  "mn12:49.3": "Này Sāriputta, đó là cách ăn rất ghê gớm của ta.",
  "mn12:50.1": "Này Sāriputta, rồi ta đi sâu vào một bụi rừng đáng sợ nào đó và sống ở đó.",
  "mn12:50.2": "Này Sāriputta, ở một bụi rừng đáng sợ, khi sự đáng sợ hiện lên như vậy—",
  "mn12:50.3": "bất cứ ai còn ham muốn mà đi vào bụi rừng ấy thì phần nhiều lông tóc đều dựng đứng.",
  "mn12:50.4": "Này Sāriputta, vào những đêm lạnh mùa đông, trong những ngày giữa tám ngày, vào lúc tuyết rơi như thế, ban đêm Ta ở ngoài trời, ban ngày ở trong bụi rừng.",
  "mn12:50.5": "Còn vào tháng cuối mùa nóng, ban ngày Ta ở ngoài trời, ban đêm ở trong bụi rừng.",
  "mn12:50.6": "Này Sāriputta, lại có bài kệ lạ này hiện đến với Ta, trước kia chưa từng nghe:",
  "mn12:50.7": "‘Người khô gầy, héo mòn,",
  "mn12:50.8": "một mình trong rừng đáng sợ;",
  "mn12:50.9": "trần truồng, không ngồi bên lửa,",
  "mn12:50.10": "vị lặng lẽ miệt mài tìm kiếm.’",
  "mn12:51.1": "Này Sāriputta, Ta nằm ở bãi tha ma, lấy xương người chết làm gối.",
  "mn12:51.2": "Này Sāriputta, có khi bọn trẻ chăn bò đến gần Ta, nhổ nước bọt lên Ta, tiểu lên Ta, rắc bụi lên Ta, còn nhét que vào lỗ tai Ta nữa.",
  "mn12:51.3": "Nhưng này Sāriputta, Ta không nhớ mình từng khởi lên ý xấu với họ.",
  "mn12:51.4": "Này Sāriputta, đó là cách Ta sống với lòng bình thản.",
  "mn12:52.1": "Này Sāriputta, có một số sa môn, bà la môn nói như vầy, thấy như vầy:",
  "mn12:52.2": "‘Nhờ đồ ăn mà được trong sạch.’",
  "mn12:52.3": "Họ nói như vầy:",
  "mn12:52.4": "‘Chúng tôi sống bằng trái táo rừng.’",
  "mn12:52.5": "Họ ăn trái táo rừng, ăn bột táo rừng, uống nước ngâm táo rừng—",
  "mn12:52.6": "dùng đủ thứ món làm từ táo rừng.",
  "mn12:52.7": "Nhưng này Sāriputta, Ta nhớ có lúc chỉ ăn đúng một trái táo rừng.",
  "mn12:52.8": "Này Sāriputta, có thể họ sẽ nghĩ như vầy:",
  "mn12:52.9": "‘Chắc vào lúc ấy trái táo rừng phải lớn lắm.’",
  "mn12:52.10": "Nhưng này Sāriputta, không nên thấy như vậy.",
  "mn12:52.11": "Khi ấy trái táo rừng cũng chỉ lớn chừng ấy thôi, như bây giờ.",
  "mn12:52.12": "Này Sāriputta, khi Ta chỉ ăn đúng một trái táo rừng, thân Ta gầy đến mức cùng cực.",
  "mn12:52.13": "Ví như những đốt dây leo đen hay những đốt cây khô; các chi phần của Ta cũng thành ra như vậy vì ăn quá ít.",
  "mn12:52.14": "Ví như dấu chân lạc đà; chỗ ngồi của Ta cũng thành ra như vậy vì ăn quá ít.",
  "mn12:52.15": "Ví như một chuỗi hạt tròn; xương sống của Ta lồi lõm như vậy vì ăn quá ít.",
  "mn12:52.16": "Ví như những cây đòn tay trong một mái nhà cũ xiêu vẹo, rời rạc; xương sườn của Ta cũng xiêu vẹo, rời rạc như vậy vì ăn quá ít.",
  "mn12:52.17": "Ví như trong một giếng nước sâu, bóng nước hiện ra sâu hun hút, khó thấy; tròng mắt của Ta trong hốc mắt cũng hiện ra sâu hun hút, khó thấy như vậy vì ăn quá ít.",
  "mn12:52.18": "Ví như trái bầu đắng bị cắt khi còn non, gặp gió nắng thì nhăn nheo, teo lại; cũng vậy, da đầu của ta nứt nẻ, nhăn nhúm vì ăn quá ít như thế.",
  "mn12:52.19": "Này Sāriputta, khi ta nghĩ: ‘Ta sẽ sờ da bụng’, thì ta chỉ chạm vào xương sống; khi ta nghĩ: ‘Ta sẽ sờ xương sống’, thì ta chỉ chạm vào da bụng. Này Sāriputta, da bụng của ta dính sát vào xương sống vì ăn quá ít như thế.",
  "mn12:52.20": "Này Sāriputta, khi ta nghĩ: ‘Ta sẽ đi đại tiện hay tiểu tiện’, thì ta ngã sấp xuống ngay tại chỗ vì ăn quá ít như thế.",
  "mn12:52.21": "Này Sāriputta, khi ta xoa vuốt thân này bằng tay để làm dịu nó, thì lông trên thân ta, gốc đã mục, rụng xuống khỏi thân vì ăn quá ít như thế.",
  "mn12:53-55.1": "Này Sāriputta, có một số sa môn, bà la môn nói như vầy, thấy như vầy:",
  "mn12:53-55.2": "‘Nhờ ăn mà thân sạch.’",
  "mn12:53-55.3": "Họ nói như vầy:",
  "mn12:53-55.4": "‘Chúng tôi sống bằng đậu xanh…",
  "mn12:53-55.5": "chúng tôi sống bằng mè…",
  "mn12:53-55.6": "chúng tôi sống bằng gạo.’",
  "mn12:53-55.7": "Họ ăn cả gạo, ăn cả bột gạo, uống cả nước gạo—",
  "mn12:53-55.8": "họ dùng đủ thứ món làm từ gạo.",
  "mn12:53-55.9": "Nhưng này Sāriputta, ta nhớ rõ đã từng chỉ dùng đúng một hạt gạo làm thức ăn.",
  "mn12:53-55.10": "Này Sāriputta, có thể họ sẽ nghĩ như vầy:",
  "mn12:53-55.11": "‘Chắc vào thời ấy hạt gạo hẳn lớn lắm.’",
  "mn12:53-55.12": "Nhưng này Sāriputta, không nên thấy như vậy.",
  "mn12:53-55.13": "Khi ấy hạt gạo cũng chỉ lớn đến mức ấy thôi, như bây giờ vậy.",
  "mn12:53-55.14": "Này Sāriputta, khi ta chỉ dùng đúng một hạt gạo làm thức ăn, thân ta gầy mòn đến mức cùng cực.",
  "mn12:53-55.15": "Ví như những đốt của dây leo khô hay dây leo đen; cũng vậy, tay chân của ta thành ra từng đốt từng khúc vì ăn quá ít như thế.",
  "mn12:53-55.16": "Ví như dấu chân lạc đà; cũng vậy, chỗ ngồi của ta thành ra như thế vì ăn quá ít như thế.",
  "mn12:53-55.17": "Ví như một chuỗi hạt tròn; cũng vậy, xương sống của ta lồi lên lõm xuống vì ăn quá ít như thế.",
  "mn12:53-55.18": "Ví như những rui mè trong một căn nhà cũ xiêu vẹo, trễ xuống; cũng vậy, xương sườn của ta xiêu vẹo, trễ xuống vì ăn quá ít như thế.",
  "mn12:53-55.19": "Ví như trong một giếng nước sâu, bóng nước hiện ra sâu hun hút; cũng vậy, tròng mắt của ta hiện sâu trong hốc mắt vì ăn quá ít như thế.",
  "mn12:53-55.20": "Ví như trái bầu đắng bị cắt khi còn non, gặp gió nắng thì nhăn nheo, teo lại; cũng vậy, da đầu của ta nứt nẻ, nhăn nhúm vì ăn quá ít như thế.",
  "mn12:53-55.21": "Này Sāriputta, khi ta nghĩ: ‘Ta sẽ sờ da bụng’, thì ta chỉ chạm vào xương sống; khi ta nghĩ: ‘Ta sẽ sờ xương sống’, thì ta chỉ chạm vào da bụng. Này Sāriputta, da bụng của ta dính sát vào xương sống vì ăn quá ít như thế.",
  "mn12:53-55.22": "Này Sāriputta, khi ta nghĩ: ‘Ta sẽ đi đại tiện hay tiểu tiện’, thì ta ngã sấp xuống ngay tại chỗ vì ăn quá ít như thế.",
  "mn12:53-55.23": "Này Sāriputta, khi ta xoa vuốt thân này bằng tay để làm dịu nó, thì lông trên thân ta, gốc đã mục, rụng xuống khỏi thân vì ăn quá ít như thế.",
  "mn12:56.1": "Nhưng này Sāriputta, dù sống theo nếp ấy, theo cách làm ấy, theo lối ép xác khổ hạnh ấy, ta vẫn không đạt được điều gì cao hơn mức người thường, không đạt được sự thấy biết xứng bậc thánh.",
  "mn12:56.2": "Vì sao vậy?",
  "mn12:56.3": "Vì ta chưa đạt được sự hiểu rõ cao quý ấy, sự hiểu rõ cao quý đưa người ta đi ra, đưa người làm đúng theo đó đến chỗ dứt hẳn khổ đau.",
  "mn12:57.1": "Này Sāriputta, có một số sa môn, bà la môn nói như vầy, thấy như vầy:",
  "mn12:57.2": "‘Đi mãi trong vòng sinh tử thì sẽ sạch trong.’",
  "mn12:57.3": "Nhưng này Sāriputta, trong quãng thời gian dài ấy, không dễ tìm ra một kiểu trôi lăn nào mà Ta chưa từng trải qua, trừ chư thiên ở cõi trời trong sạch.",
  "mn12:57.4": "Và này Sāriputta, nếu Ta có sinh vào hàng chư thiên ở cõi trời trong sạch, thì Ta sẽ không trở lại đời này nữa.",
  "mn12:58.1": "Này Sāriputta, có một số sa môn, bà la môn nói như vầy, thấy như vầy:",
  "mn12:58.2": "‘Sinh vào một nơi nào đó thì sẽ sạch trong.’",
  "mn12:58.3": "Nhưng này Sāriputta, trong quãng thời gian dài ấy, không dễ tìm ra một chỗ sinh vào nào mà Ta chưa từng sinh vào, trừ chư thiên ở cõi trời trong sạch.",
  "mn12:58.4": "Và này Sāriputta, nếu Ta có sinh vào hàng chư thiên ở cõi trời trong sạch, thì Ta sẽ không trở lại đời này nữa.",
  "mn12:59.1": "Này Sāriputta, có một số sa môn, bà la môn nói như vầy, thấy như vầy:",
  "mn12:59.2": "‘Ở một nơi nào đó thì sẽ sạch trong.’",
  "mn12:59.3": "Nhưng này Sāriputta, trong quãng thời gian dài ấy, không dễ tìm ra một chỗ ở nào mà Ta chưa từng ở, trừ chư thiên ở cõi trời trong sạch.",
  "mn12:59.4": "Và này Sāriputta, nếu Ta có ở giữa hàng chư thiên ở cõi trời trong sạch, thì Ta sẽ không trở lại đời này nữa.",
  "mn12:60.1": "Này Sāriputta, có một số sa môn, bà la môn nói như vầy, thấy như vầy:",
  "mn12:60.2": "‘Làm lễ cúng thì sẽ sạch trong.’",
  "mn12:60.3": "Nhưng này Sāriputta, không dễ tìm ra một lễ cúng nào mà Ta chưa từng làm trong quãng thời gian dài ấy, nhất là những lễ cúng do vua chúa hay bà la môn giàu lớn làm.",
  "mn12:61.1": "Này Sāriputta, có một số sa môn, bà la môn nói như vầy, thấy như vầy:",
  "mn12:61.2": "‘Thờ lửa thì sẽ sạch trong.’",
  "mn12:61.3": "Nhưng này Sāriputta, không dễ tìm ra một ngọn lửa nào mà Ta chưa từng hầu hạ trong quãng thời gian dài ấy, nhất là ngọn lửa của vua chúa hay bà la môn giàu lớn.",
  "mn12:62.1": "Này Sāriputta, có một số sa môn, bà la môn nói như vầy, thấy như vầy:",
  "mn12:62.2": "‘Chỉ khi người này còn trẻ, đang tuổi thanh xuân, tóc còn đen nhánh, đang ở tuổi đầu đời, thì mới có sự hiểu rõ cao nhất và nói năng sáng suốt nhất.",
  "mn12:62.3": "Nhưng khi người này đã già, lớn tuổi, cao niên, đã đi hết phần lớn đời mình, đến tám mươi, chín mươi hay một trăm tuổi, thì sự hiểu rõ và nói năng sáng suốt ấy sẽ suy giảm.’",
  "mn12:62.4": "Nhưng này Sāriputta, không nên thấy như vậy.",
  "mn12:62.5": "Này Sāriputta, nay Ta đã già, lớn tuổi, cao niên, đã đi hết phần lớn đời mình; nay Ta đang ở tuổi tám mươi.",
  "mn12:62.6": "Này Sāriputta, giả sử Ta có bốn người học trò sống đến một trăm tuổi, sống trọn một trăm năm, có nhớ biết rõ rất mạnh, đi đứng rất nhanh, sức gắng rất bền, và sự hiểu rõ rất cao.",
  "mn12:62.7": "Ví như này Sāriputta, một người bắn cung vững tay, được rèn luyện, khéo tay, tập thuần thục, có thể dùng mũi tên nhẹ mà bắn ngang qua bóng cây cọ một cách rất dễ dàng,",
  "mn12:62.8": "cũng vậy, họ có nhớ biết rõ rất mạnh, đi đứng rất nhanh, sức gắng rất bền, và sự hiểu rõ rất cao.",
  "mn12:62.9": "Nếu họ cứ lần lượt hỏi Ta về bốn nền nhớ biết rõ, thì mỗi câu được hỏi Ta đều trả lời cho họ; và điều Ta trả lời, họ đều ghi nhớ đúng như đã được trả lời; họ cũng không hỏi vặn lại Ta đến câu thứ hai hay hỏi thêm gì hơn nữa.",
  "mn12:62.10": "Trừ lúc ăn, uống, nhai, nếm; trừ lúc đi tiêu, đi tiểu; trừ lúc xua tan sự mệt vì buồn ngủ, thì lời chỉ dạy của Như Lai không hề cạn, lời nói và câu chữ của Như Lai không hề cạn, sự ứng đáp trước câu hỏi của Như Lai không hề cạn.",
  "mn12:62.11": "Rồi này Sāriputta, bốn người học trò ấy, sống đến một trăm tuổi, sống trọn một trăm năm, sau khi hết một trăm năm thì qua đời.",
  "mn12:62.12": "Dù các ông có khiêng Ta bằng giường, này Sāriputta, thì sự hiểu rõ và nói năng sáng suốt của Như Lai cũng không hề đổi khác.",
  "mn12:63.1": "Này Xá Lợi Phất, nếu ai nói đúng thì nên nói rằng:",
  "mn12:63.2": "‘Một người không mê lầm đã xuất hiện ở đời, vì điều lành cho nhiều người, vì niềm vui cho nhiều người, vì thương đời, vì điều lợi ích, điều lành và niềm vui cho chư thiên và loài người’, thì người ấy nói đúng về chính Ta như vậy.",
  "mn12:63.3": "‘Một người không mê lầm đã xuất hiện ở đời, vì điều lành cho nhiều người, vì niềm vui cho nhiều người, vì thương đời, vì điều lợi ích, điều lành và niềm vui cho chư thiên và loài người’.",
  "mn12:64.1": "Lúc bấy giờ, Tỳ Kheo Nāgasamāla đứng phía sau Đức Thế Tôn, đang quạt cho Đức Thế Tôn.",
  "mn12:64.2": "Rồi Tỳ Kheo Nāgasamāla thưa với Đức Thế Tôn:",
  "mn12:64.3": "“Thật lạ thay, bạch Thế Tôn, thật ít có thay, bạch Thế Tôn.",
  "mn12:64.4": "Bạch Thế Tôn, khi nghe cách nói về lẽ thật này, lông con dựng đứng lên.",
  "mn12:64.5": "Bạch Thế Tôn, cách nói về lẽ thật này tên là gì?”",
  "mn12:64.6": "“Vậy thì, này Nāgasamāla, hãy ghi nhớ cách nói về lẽ thật này là Bài Nói Làm Dựng Tóc Gáy.”",
  "mn12:64.7": "Đức Thế Tôn nói như vậy.",
  "mn12:64.8": "Tỳ Kheo Nāgasamāla vui mừng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn12:64.9": "Kinh Tiếng Gầm Sư Tử Lớn chấm dứt, bài thứ hai."
}
window.BILARA["mn12"]["vi"]["mn12:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";