window.BILARA = window.BILARA || {};
window.BILARA["mn131"] = window.BILARA["mn131"] || {};
window.BILARA["mn131"]["vi"] = {
  "mn131:0.1": "Trung Bộ Kinh 131 ",
  "mn131:0.2": "Kinh Một Đêm An Lành ",
  "mn131:1.1": "Tôi nghe như vầy—",
  "mn131:1.2": "Một thời, Thế Tôn trú ở Sāvatthī, tại Jetavana, khu vườn của Anāthapiṇḍika. ",
  "mn131:1.3": "Tại đấy, Thế Tôn gọi các Tỳ-kheo: ",
  "mn131:1.4": "“Này các Tỳ-kheo”. ",
  "mn131:1.5": "“Bạch Thế Tôn”, các Tỳ-kheo ấy vâng đáp Thế Tôn. ",
  "mn131:1.6": "Thế Tôn nói như sau: ",
  "mn131:2.1": "“Này các Tỳ-kheo, Ta sẽ giảng cho các ông bài tóm tắt và phân tích về ‘Một Đêm An Lành’. ",
  "mn131:2.2": "Hãy lắng nghe, hãy khéo tác ý, Ta sẽ nói”. ",
  "mn131:2.3": "“Thưa vâng, bạch Thế Tôn”, các Tỳ-kheo ấy vâng đáp Thế Tôn. ",
  "mn131:2.4": "Thế Tôn nói như sau: ",
  "mn131:3.1": "“Không truy tìm quá khứ, ",
  "mn131:3.2": "Không mong đợi tương lai; ",
  "mn131:3.3": "Quá khứ đã đoạn diệt, ",
  "mn131:3.4": "Tương lai chưa đến. ",
  "mn131:3.5": "Và ai thấy rõ pháp hiện tại, ",
  "mn131:3.6": "Ở đây và ở đây; ",
  "mn131:3.7": "Không lay chuyển, không dao động, ",
  "mn131:3.8": "Người trí nên phát triển điều đó. ",
  "mn131:3.9": "Hôm nay phải tinh tấn, ",
  "mn131:3.10": "Ai biết cái chết đến ngày mai? ",
  "mn131:3.11": "Không có sự thương lượng nào với, ",
  "mn131:3.12": "Đại quân Thần Chết ấy. ",
  "mn131:3.13": "Người sống như vậy, tinh cần, ",
  "mn131:3.14": "Không lười biếng ngày đêm; ",
  "mn131:3.15": "Người ấy thật sự là người ‘Một Đêm An Lành’, ",
  "mn131:3.16": "Bậc hiền trí nói vậy. ",
  "mn131:4.1": "Và này các Tỳ-kheo, thế nào là truy tìm quá khứ? ",
  "mn131:4.2": "‘Ta đã có sắc như vậy trong thời quá khứ’—người ấy tìm thấy sự thích thú ở đó; ‘Ta đã có cảm thọ như vậy trong thời quá khứ’—người ấy tìm thấy sự thích thú ở đó; ‘Ta đã có tưởng như vậy trong thời quá khứ’—người ấy tìm thấy sự thích thú ở đó; ‘Ta đã có hành như vậy trong thời quá khứ’—người ấy tìm thấy sự thích thú ở đó; ‘Ta đã có thức như vậy trong thời quá khứ’—người ấy tìm thấy sự thích thú ở đó—",
  "mn131:4.3": "Này các Tỳ-kheo, như vậy là truy tìm quá khứ. ",
  "mn131:5.1": "Và này các Tỳ-kheo, thế nào là không truy tìm quá khứ? ",
  "mn131:5.2": "‘Ta đã có sắc như vậy trong thời quá khứ’—người ấy không tìm thấy sự thích thú ở đó; ‘Ta đã có cảm thọ như vậy trong thời quá khứ’—người ấy không tìm thấy sự thích thú ở đó; ‘Ta đã có tưởng như vậy trong thời quá khứ’—người ấy không tìm thấy sự thích thú ở đó; ‘Ta đã có hành như vậy trong thời quá khứ’—người ấy không tìm thấy sự thích thú ở đó; ‘Ta đã có thức như vậy trong thời quá khứ’—người ấy không tìm thấy sự thích thú ở đó—",
  "mn131:5.3": "Này các Tỳ-kheo, như vậy là không truy tìm quá khứ. ",
  "mn131:6.1": "Và này các Tỳ-kheo, thế nào là mong đợi tương lai? ",
  "mn131:6.2": "‘Ta sẽ có sắc như vậy trong thời tương lai’—người ấy tìm thấy sự thích thú ở đó; ‘Ta sẽ có cảm thọ như vậy’… ‘Ta sẽ có tưởng như vậy’… ‘Ta sẽ có hành như vậy’… ‘Ta sẽ có thức như vậy trong thời tương lai’—người ấy tìm thấy sự thích thú ở đó—",
  "mn131:6.3": "Này các Tỳ-kheo, như vậy là mong đợi tương lai. ",
  "mn131:7.1": "Và này các Tỳ-kheo, thế nào là không mong đợi tương lai? ",
  "mn131:7.2": "‘Ta sẽ có sắc như vậy trong thời tương lai’—người ấy không tìm thấy sự thích thú ở đó; ‘Ta sẽ có cảm thọ như vậy’… ‘Ta sẽ có tưởng như vậy’… ‘Ta sẽ có hành như vậy’… ‘Ta sẽ có thức như vậy trong thời tương lai’—người ấy không tìm thấy sự thích thú ở đó—",
  "mn131:7.3": "Này các Tỳ-kheo, như vậy là không mong đợi tương lai. ",
  "mn131:8.1": "Và này các Tỳ-kheo, thế nào là bị trói buộc vào các pháp hiện tại? ",
  "mn131:8.2": "Ở đây, này các Tỳ-kheo, phàm phu ít học, không thấy các bậc Thánh, không thông hiểu pháp của các bậc Thánh, không được huấn luyện trong pháp của các bậc Thánh; không thấy các bậc Chân nhân, không thông hiểu pháp của các bậc Chân nhân, không được huấn luyện trong pháp của các bậc Chân nhân, ",
  "mn131:8.3": "người ấy xem sắc là tự ngã, hoặc tự ngã có sắc, hoặc sắc ở trong tự ngã, hoặc tự ngã ở trong sắc; ",
  "mn131:8.4": "cảm thọ… ",
  "mn131:8.5": "tưởng… ",
  "mn131:8.6": "hành… ",
  "mn131:8.7": "thức là tự ngã, hoặc tự ngã có thức, hoặc thức ở trong tự ngã, hoặc tự ngã ở trong thức—",
  "mn131:8.8": "Này các Tỳ-kheo, như vậy là bị trói buộc vào các pháp hiện tại. ",
  "mn131:9.1": "Và này các Tỳ-kheo, thế nào là không bị trói buộc vào các pháp hiện tại? ",
  "mn131:9.2": "Ở đây, này các Tỳ-kheo, đệ tử Thánh đa văn, thấy các bậc Thánh, thông hiểu pháp của các bậc Thánh, được huấn luyện tốt trong pháp của các bậc Thánh; thấy các bậc Chân nhân, thông hiểu pháp của các bậc Chân nhân, được huấn luyện tốt trong pháp của các bậc Chân nhân, ",
  "mn131:9.3": "người ấy không xem sắc là tự ngã, không tự ngã có sắc, không sắc ở trong tự ngã, không tự ngã ở trong sắc; ",
  "mn131:9.4": "không cảm thọ… ",
  "mn131:9.5": "không tưởng… ",
  "mn131:9.6": "không hành… ",
  "mn131:9.7": "không thức là tự ngã, không tự ngã có thức, không thức ở trong tự ngã, không tự ngã ở trong thức—",
  "mn131:9.8": "Này các Tỳ-kheo, như vậy là không bị trói buộc vào các pháp hiện tại. ",
  "mn131:10.1": "Không truy tìm quá khứ, ",
  "mn131:10.2": "Không mong đợi tương lai; ",
  "mn131:10.3": "Quá khứ đã đoạn diệt, ",
  "mn131:10.4": "Tương lai chưa đến. ",
  "mn131:10.5": "Và ai thấy rõ pháp hiện tại, ",
  "mn131:10.6": "Ở đây và ở đây; ",
  "mn131:10.7": "Không lay chuyển, không dao động, ",
  "mn131:10.8": "Người trí nên phát triển điều đó. ",
  "mn131:10.9": "Hôm nay phải tinh tấn, ",
  "mn131:10.10": "Ai biết cái chết đến ngày mai? ",
  "mn131:10.11": "Không có sự thương lượng nào với, ",
  "mn131:10.12": "Đại quân Thần Chết ấy. ",
  "mn131:10.13": "Người sống như vậy, tinh cần, ",
  "mn131:10.14": "Không lười biếng ngày đêm; ",
  "mn131:10.15": "Người ấy thật sự là người ‘Một Đêm An Lành’, ",
  "mn131:10.16": "Bậc hiền trí nói vậy. ",
  "mn131:11.1": "“Này các Tỳ-kheo, Ta sẽ giảng cho các ông bài tóm tắt và phân tích về ‘Một Đêm An Lành’” —",
  "mn131:11.2": "đó là điều đã được nói, và điều này đã được nói dựa trên điều đó”. ",
  "mn131:11.3": "Thế Tôn đã nói như vậy. ",
  "mn131:11.4": "Các Tỳ-kheo ấy hoan hỷ, tán thán lời Thế Tôn dạy. ",
  "mn131:11.5": "Kinh Một Đêm An Lành, bài thứ nhất, chấm dứt. "
}
window.BILARA["mn131"]["vi"]["mn131:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
