window.BILARA = window.BILARA || {};
window.BILARA["mn132"] = window.BILARA["mn132"] || {};
window.BILARA["mn132"]["vi"] = {
  "mn132:0.1": "Trung Bộ Kinh 132 ",
  "mn132:0.2": "Kinh Một Đêm An Lành của Ananda ",
  "mn132:1.1": "Tôi nghe như vầy—",
  "mn132:1.2": "Một thời, Thế Tôn trú ở Sāvatthī, tại khu vườn Jetavana của ông Anāthapiṇḍika. ",
  "mn132:2.1": "Lúc bấy giờ, Tôn giả Ānanda đang ở trong giảng đường, thuyết pháp, khích lệ, làm phấn khởi, làm hoan hỷ các Tỳ-kheo bằng một bài pháp thoại, và giảng về tóm tắt và phân tích về Một Đêm An Lành. ",
  "mn132:2.2": "Rồi Thế Tôn, vào buổi chiều, từ chỗ độc cư thiền định đứng dậy, đi đến giảng đường; sau khi đến, Ngài ngồi xuống trên chỗ đã soạn sẵn. ",
  "mn132:2.3": "Sau khi ngồi, Thế Tôn gọi các Tỳ-kheo: ",
  "mn132:2.4": "“Này các Tỳ-kheo, ai đang ở trong giảng đường, thuyết pháp, khích lệ, làm phấn khởi, làm hoan hỷ các Tỳ-kheo bằng một bài pháp thoại, và giảng về tóm tắt và phân tích về Một Đêm An Lành?” ",
  "mn132:2.5": "“Bạch Thế Tôn, Tôn giả Ānanda đang ở trong giảng đường, thuyết pháp, khích lệ, làm phấn khởi, làm hoan hỷ các Tỳ-kheo bằng một bài pháp thoại, và giảng về tóm tắt và phân tích về Một Đêm An Lành.” ",
  "mn132:2.6": "Rồi Thế Tôn gọi Tôn giả Ānanda: ",
  "mn132:2.7": "“Này Ānanda, ông đã thuyết pháp, khích lệ, làm phấn khởi, làm hoan hỷ các Tỳ-kheo bằng một bài pháp thoại, và giảng về tóm tắt và phân tích về Một Đêm An Lành như thế nào?” ",
  "mn132:3.1": "“Bạch Thế Tôn, con đã thuyết pháp, khích lệ, làm phấn khởi, làm hoan hỷ các Tỳ-kheo bằng một bài pháp thoại, và giảng về tóm tắt và phân tích về Một Đêm An Lành như vầy—",
  "mn132:3.2": "Chớ truy tìm quá khứ, ",
  "mn132:3.3": "Chớ mong đợi tương lai; ",
  "mn132:3.4": "Quá khứ đã qua rồi, ",
  "mn132:3.5": "Tương lai chưa đến. ",
  "mn132:3.6": "Pháp hiện tại, ",
  "mn132:3.7": "Ai thấy rõ từng phần; ",
  "mn132:3.8": "Không lay chuyển, không dao động, ",
  "mn132:3.9": "Người trí nên phát triển. ",
  "mn132:3.10": "Hôm nay phải tinh tấn, ",
  "mn132:3.11": "Ai biết chết ngày mai; ",
  "mn132:3.12": "Không có thỏa hiệp nào, ",
  "mn132:3.13": "Với đại quân tử thần. ",
  "mn132:3.14": "Người sống như vậy, tinh cần, ",
  "mn132:3.15": "Không lười biếng ngày đêm; ",
  "mn132:3.16": "Người ấy thật là Một Đêm An Lành, ",
  "mn132:3.17": "Bậc hiền trí nói vậy. ",
  "mn132:4.1": "‘Này các bạn, thế nào là truy tìm quá khứ? ",
  "mn132:4.2": "Ta đã có hình sắc như vậy trong quá khứ, rồi người ấy tìm thấy sự hoan hỷ ở đó; ta đã có cảm thọ như vậy trong quá khứ, rồi người ấy tìm thấy sự hoan hỷ ở đó; ta đã có tưởng như vậy trong quá khứ, rồi người ấy tìm thấy sự hoan hỷ ở đó; ta đã có hành như vậy trong quá khứ, rồi người ấy tìm thấy sự hoan hỷ ở đó; ta đã có thức như vậy trong quá khứ, rồi người ấy tìm thấy sự hoan hỷ ở đó—",
  "mn132:4.3": "Này các bạn, như vậy là truy tìm quá khứ. ",
  "mn132:5.1": "Này các bạn, thế nào là không truy tìm quá khứ? ",
  "mn132:5.2": "Ta đã có hình sắc như vậy trong quá khứ, rồi người ấy không tìm thấy sự hoan hỷ ở đó; ta đã có cảm thọ như vậy trong quá khứ, rồi người ấy không tìm thấy sự hoan hỷ ở đó; ta đã có tưởng như vậy trong quá khứ, rồi người ấy không tìm thấy sự hoan hỷ ở đó; ta đã có hành như vậy trong quá khứ, rồi người ấy không tìm thấy sự hoan hỷ ở đó; ta đã có thức như vậy trong quá khứ, rồi người ấy không tìm thấy sự hoan hỷ ở đó—",
  "mn132:5.3": "Này các bạn, như vậy là không truy tìm quá khứ. ",
  "mn132:6.1": "Này các bạn, thế nào là mong đợi tương lai? ",
  "mn132:6.2": "Ta sẽ có hình sắc như vậy trong tương lai, rồi người ấy tìm thấy sự hoan hỷ ở đó; ta sẽ có cảm thọ như vậy …v.v… ",
  "mn132:6.3": "ta sẽ có tưởng như vậy … ",
  "mn132:6.4": "ta sẽ có hành như vậy … ",
  "mn132:6.5": "ta sẽ có thức như vậy trong tương lai, rồi người ấy tìm thấy sự hoan hỷ ở đó—",
  "mn132:6.6": "Này các bạn, như vậy là mong đợi tương lai. ",
  "mn132:7.1": "Này các bạn, thế nào là không mong đợi tương lai? ",
  "mn132:7.2": "Ta sẽ có hình sắc như vậy trong tương lai, rồi người ấy không tìm thấy sự hoan hỷ ở đó; ta sẽ có cảm thọ như vậy …v.v… ",
  "mn132:7.3": "ta sẽ có tưởng như vậy … ",
  "mn132:7.4": "ta sẽ có hành như vậy … ",
  "mn132:7.5": "ta sẽ có thức như vậy trong tương lai, rồi người ấy không tìm thấy sự hoan hỷ ở đó—",
  "mn132:7.6": "Này các bạn, như vậy là không mong đợi tương lai. ",
  "mn132:8.1": "Này các bạn, thế nào là bị ràng buộc vào các pháp hiện tại? ",
  "mn132:8.2": "Này các bạn, ở đây, phàm phu ít học, không thấy các bậc Thánh, không thông hiểu pháp của các bậc Thánh, không được huấn luyện trong pháp của các bậc Thánh; không thấy các bậc chân nhân, không thông hiểu pháp của các bậc chân nhân, không được huấn luyện trong pháp của các bậc chân nhân, ",
  "mn132:8.3": "thấy sắc là tự ngã, hoặc tự ngã có sắc, hoặc sắc ở trong tự ngã, hoặc tự ngã ở trong sắc; ",
  "mn132:8.4": "thọ… ",
  "mn132:8.5": "tưởng… ",
  "mn132:8.6": "hành… ",
  "mn132:8.7": "thức là tự ngã, hoặc tự ngã có thức, hoặc thức ở trong tự ngã, hoặc tự ngã ở trong thức—",
  "mn132:8.8": "Này các bạn, như vậy là bị ràng buộc vào các pháp hiện tại. ",
  "mn132:9.1": "Này các bạn, thế nào là không bị ràng buộc vào các pháp hiện tại? ",
  "mn132:9.2": "Này các bạn, ở đây, đệ tử Thánh đa văn, thấy các bậc Thánh, thông hiểu pháp của các bậc Thánh, được huấn luyện tốt trong pháp của các bậc Thánh; thấy các bậc chân nhân, thông hiểu pháp của các bậc chân nhân, được huấn luyện tốt trong pháp của các bậc chân nhân, ",
  "mn132:9.3": "không thấy sắc là tự ngã, không thấy tự ngã có sắc, không thấy sắc ở trong tự ngã, không thấy tự ngã ở trong sắc; ",
  "mn132:9.4": "không thấy thọ… ",
  "mn132:9.5": "không thấy tưởng… ",
  "mn132:9.6": "không thấy hành… ",
  "mn132:9.7": "không thấy thức là tự ngã, không thấy tự ngã có thức, không thấy thức ở trong tự ngã, không thấy tự ngã ở trong thức—",
  "mn132:9.8": "Này các bạn, như vậy là không bị ràng buộc vào các pháp hiện tại. ",
  "mn132:10.1": "Chớ truy tìm quá khứ, ",
  "mn132:10.2": "Chớ mong đợi tương lai; ",
  "mn132:10.3": "Quá khứ đã qua rồi, ",
  "mn132:10.4": "Tương lai chưa đến. ",
  "mn132:10.5": "Pháp hiện tại, ",
  "mn132:10.6": "Ai thấy rõ từng phần; ",
  "mn132:10.7": "Không lay chuyển, không dao động, ",
  "mn132:10.8": "Người trí nên phát triển. ",
  "mn132:10.9": "Hôm nay phải tinh tấn, ",
  "mn132:10.10": "Ai biết chết ngày mai; ",
  "mn132:10.11": "Không có thỏa hiệp nào, ",
  "mn132:10.12": "Với đại quân tử thần. ",
  "mn132:10.13": "Người sống như vậy, tinh cần, ",
  "mn132:10.14": "Không lười biếng ngày đêm; ",
  "mn132:10.15": "Người ấy thật là Một Đêm An Lành, ",
  "mn132:10.16": "Bậc hiền trí nói vậy.’ ",
  "mn132:11.1": "Bạch Thế Tôn, con đã thuyết pháp, khích lệ, làm phấn khởi, làm hoan hỷ các Tỳ-kheo bằng một bài pháp thoại, và giảng về tóm tắt và phân tích về Một Đêm An Lành như vầy.” ",
  "mn132:11.2": "“Lành thay, lành thay, Ānanda. ",
  "mn132:11.3": "Này Ānanda, ông đã thuyết pháp, khích lệ, làm phấn khởi, làm hoan hỷ các Tỳ-kheo bằng một bài pháp thoại, và giảng về tóm tắt và phân tích về Một Đêm An Lành thật là lành thay: ",
  "mn132:12.1": "‘Chớ truy tìm quá khứ, ",
  "mn132:12.2": "…v.v… ",
  "mn132:12.3": "Người ấy thật là Một Đêm An Lành, ",
  "mn132:12.4": "Bậc hiền trí nói vậy.’ ",
  "mn132:13-19.1": "Này Ānanda, thế nào là truy tìm quá khứ …v.v… ",
  "mn132:13-19.2": "Này Ānanda, như vậy là truy tìm quá khứ. ",
  "mn132:13-19.3": "Này Ānanda, thế nào là không truy tìm quá khứ …v.v… ",
  "mn132:13-19.4": "Này Ānanda, như vậy là không truy tìm quá khứ. ",
  "mn132:13-19.5": "Này Ānanda, thế nào là mong đợi tương lai …v.v… ",
  "mn132:13-19.6": "Này Ānanda, như vậy là mong đợi tương lai. ",
  "mn132:13-19.7": "Này Ānanda, thế nào là không mong đợi tương lai …v.v… ",
  "mn132:13-19.8": "Này Ānanda, như vậy là không mong đợi tương lai. ",
  "mn132:13-19.9": "Này Ānanda, thế nào là bị ràng buộc vào các pháp hiện tại …v.v… ",
  "mn132:13-19.10": "Này Ānanda, như vậy là bị ràng buộc vào các pháp hiện tại. ",
  "mn132:13-19.11": "Này Ānanda, thế nào là không bị ràng buộc vào các pháp hiện tại …v.v… ",
  "mn132:13-19.12": "Này Ānanda, như vậy là không bị ràng buộc vào các pháp hiện tại. ",
  "mn132:13-19.13": "‘Chớ truy tìm quá khứ, ",
  "mn132:13-19.14": "…v.v… ",
  "mn132:13-19.15": "Người ấy thật là Một Đêm An Lành, ",
  "mn132:13-19.16": "Bậc hiền trí nói vậy.’” ",
  "mn132:13-19.17": "Thế Tôn đã nói như vậy. ",
  "mn132:13-19.18": "Tôn giả Ānanda hoan hỷ, tán thán lời Thế Tôn dạy. ",
  "mn132:13-19.19": "Kinh Một Đêm An Lành của Ananda, bài thứ hai, chấm dứt. "
}
window.BILARA["mn132"]["vi"]["mn132:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
