window.BILARA = window.BILARA || {};
window.BILARA["mn142"] = window.BILARA["mn142"] || {};
window.BILARA["mn142"]["vi"] = {
  "mn142:0.1": "Trung Bộ Kinh 142 ",
  "mn142:0.2": "Kinh Phân Biệt Bố Thí ",
  "mn142:1.1": "Như vầy tôi nghe—",
  "mn142:1.2": "Một thời Thế Tôn trú ở Kapilavatthu (Ca-tỳ-la-vệ), tại vườn Nigrodha, giữa các bộ tộc Sakka (Thích Ca). ",
  "mn142:2.1": "Rồi Mahāpajāpati Gotamī (Đại Ái Đạo Cồ Đàm Di) mang theo một cặp y phục mới, đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, Mahāpajāpati Gotamī bạch Thế Tôn: ",
  "mn142:2.2": "“Bạch Thế Tôn, đây là cặp y phục mới do con tự tay dệt, tự tay may, dâng cúng Thế Tôn. ",
  "mn142:2.3": "Kính xin Thế Tôn vì lòng thương xót mà thọ nhận cho con.” ",
  "mn142:2.4": "Khi được nói vậy, Thế Tôn nói với Mahāpajāpati Gotamī: ",
  "mn142:2.5": "“Này Gotamī, hãy dâng cúng Tăng chúng. ",
  "mn142:2.6": "Khi con dâng cúng Tăng chúng, thì Ta cũng được cúng dường và Tăng chúng cũng được cúng dường.” ",
  "mn142:2.7": "Lần thứ hai, Mahāpajāpati Gotamī bạch Thế Tôn: ",
  "mn142:2.8": "“Bạch Thế Tôn, đây là cặp y phục mới do con tự tay dệt, tự tay may, dâng cúng Thế Tôn. ",
  "mn142:2.9": "Kính xin Thế Tôn vì lòng thương xót mà thọ nhận cho con.” ",
  "mn142:2.10": "Lần thứ hai, Thế Tôn nói với Mahāpajāpati Gotamī: ",
  "mn142:2.11": "“Này Gotamī, hãy dâng cúng Tăng chúng. ",
  "mn142:2.12": "Khi con dâng cúng Tăng chúng, thì Ta cũng được cúng dường và Tăng chúng cũng được cúng dường.” ",
  "mn142:2.13": "Lần thứ ba, Mahāpajāpati Gotamī bạch Thế Tôn: ",
  "mn142:2.14": "“Bạch Thế Tôn, đây là cặp y phục mới do con tự tay dệt, tự tay may, dâng cúng Thế Tôn. ",
  "mn142:2.15": "Kính xin Thế Tôn vì lòng thương xót mà thọ nhận cho con.” ",
  "mn142:2.16": "Lần thứ ba, Thế Tôn nói với Mahāpajāpati Gotamī: ",
  "mn142:2.17": "“Này Gotamī, hãy dâng cúng Tăng chúng. ",
  "mn142:2.18": "Khi con dâng cúng Tăng chúng, thì Ta cũng được cúng dường và Tăng chúng cũng được cúng dường.” ",
  "mn142:3.1": "Khi được nói vậy, Tôn giả Ānanda (A-nan) bạch Thế Tôn: ",
  "mn142:3.2": "“Bạch Thế Tôn, kính xin Thế Tôn thọ nhận cặp y phục mới của Mahāpajāpati Gotamī. ",
  "mn142:3.3": "Bạch Thế Tôn, Mahāpajāpati Gotamī là người có nhiều ơn đối với Thế Tôn, là dì của Thế Tôn, là người nuôi dưỡng, là người cho bú sữa; ",
  "mn142:3.4": "khi mẹ của Thế Tôn qua đời, bà đã cho Thế Tôn bú sữa. ",
  "mn142:3.5": "Bạch Thế Tôn, Thế Tôn cũng có nhiều ơn đối với Mahāpajāpati Gotamī. ",
  "mn142:3.6": "Bạch Thế Tôn, nhờ Thế Tôn mà Mahāpajāpati Gotamī đã quy y Phật, quy y Pháp, quy y Tăng. ",
  "mn142:3.7": "Bạch Thế Tôn, nhờ Thế Tôn mà Mahāpajāpati Gotamī đã từ bỏ sát sinh, từ bỏ lấy của không cho, từ bỏ tà hạnh trong các dục, từ bỏ nói dối, từ bỏ rượu men, rượu nấu là nguyên nhân của sự buông thả. ",
  "mn142:3.8": "Bạch Thế Tôn, nhờ Thế Tôn mà Mahāpajāpati Gotamī đã thành tựu lòng tin bất động nơi Phật, thành tựu lòng tin bất động nơi Pháp, thành tựu lòng tin bất động nơi Tăng, thành tựu các giới được bậc Thánh yêu thích. ",
  "mn142:3.9": "Bạch Thế Tôn, nhờ Thế Tôn mà Mahāpajāpati Gotamī không còn nghi ngờ về Khổ, không còn nghi ngờ về Khổ tập, không còn nghi ngờ về Khổ diệt, không còn nghi ngờ về con đường đưa đến Khổ diệt. ",
  "mn142:3.10": "Thế Tôn cũng có nhiều ơn đối với Mahāpajāpati Gotamī.” ",
  "mn142:4.1": "“Này Ānanda, đúng là như vậy. ",
  "mn142:4.2": "Này Ānanda, nếu một người nhờ một người mà quy y Phật, quy y Pháp, quy y Tăng, thì Ta nói rằng người này không thể đền đáp đầy đủ cho người kia, đó là—",
  "mn142:4.3": "bằng cách đảnh lễ, đứng dậy đón tiếp, chắp tay, làm các việc cung kính, cúng dường y phục, đồ ăn khất thực, chỗ ở, thuốc men trị bệnh. ",
  "mn142:4.4": "Này Ānanda, nếu một người nhờ một người mà từ bỏ sát sinh, từ bỏ lấy của không cho, từ bỏ tà hạnh trong các dục, từ bỏ nói dối, từ bỏ rượu men, rượu nấu là nguyên nhân của sự buông thả, thì Ta nói rằng người này không thể đền đáp đầy đủ cho người kia, đó là—",
  "mn142:4.5": "bằng cách đảnh lễ, đứng dậy đón tiếp, chắp tay, làm các việc cung kính, cúng dường y phục, đồ ăn khất thực, chỗ ở, thuốc men trị bệnh. ",
  "mn142:4.6": "Này Ānanda, nếu một người nhờ một người mà thành tựu lòng tin bất động nơi Phật, nơi Pháp… nơi Tăng… thành tựu các giới được bậc Thánh yêu thích, thì Ta nói rằng người này không thể đền đáp đầy đủ cho người kia, đó là—",
  "mn142:4.7": "bằng cách đảnh lễ, đứng dậy đón tiếp, chắp tay, làm các việc cung kính, cúng dường y phục, đồ ăn khất thực, chỗ ở, thuốc men trị bệnh. ",
  "mn142:4.8": "Này Ānanda, nếu một người nhờ một người mà không còn nghi ngờ về Khổ, không còn nghi ngờ về Khổ tập, không còn nghi ngờ về Khổ diệt, không còn nghi ngờ về con đường đưa đến Khổ diệt, thì Ta nói rằng người này không thể đền đáp đầy đủ cho người kia, đó là—",
  "mn142:4.9": "bằng cách đảnh lễ, đứng dậy đón tiếp, chắp tay, làm các việc cung kính, cúng dường y phục, đồ ăn khất thực, chỗ ở, thuốc men trị bệnh. ",
  "mn142:5.1": "Này Ānanda, có mười bốn loại bố thí đến từng cá nhân. ",
  "mn142:5.2": "Mười bốn loại nào? ",
  "mn142:5.3": "Bố thí đến bậc Như Lai, A-la-hán, Chánh Đẳng Giác—",
  "mn142:5.4": "đây là loại bố thí đến từng cá nhân thứ nhất. ",
  "mn142:5.5": "Bố thí đến bậc Độc Giác Phật—",
  "mn142:5.6": "đây là loại bố thí đến từng cá nhân thứ hai. ",
  "mn142:5.7": "Bố thí đến các đệ tử A-la-hán của Như Lai—",
  "mn142:5.8": "đây là loại bố thí đến từng cá nhân thứ ba. ",
  "mn142:5.9": "Bố thí đến người đang thực hành để chứng đạt quả A-la-hán—",
  "mn142:5.10": "đây là loại bố thí đến từng cá nhân thứ tư. ",
  "mn142:5.11": "Bố thí đến bậc Bất Lai—",
  "mn142:5.12": "đây là loại bố thí đến từng cá nhân thứ năm. ",
  "mn142:5.13": "Bố thí đến người đang thực hành để chứng đạt quả Bất Lai—",
  "mn142:5.14": "đây là loại bố thí đến từng cá nhân thứ sáu. ",
  "mn142:5.15": "Bố thí đến bậc Nhất Lai—",
  "mn142:5.16": "đây là loại bố thí đến từng cá nhân thứ bảy. ",
  "mn142:5.17": "Bố thí đến người đang thực hành để chứng đạt quả Nhất Lai—",
  "mn142:5.18": "đây là loại bố thí đến từng cá nhân thứ tám. ",
  "mn142:5.19": "Bố thí đến bậc Nhập Lưu—",
  "mn142:5.20": "đây là loại bố thí đến từng cá nhân thứ chín. ",
  "mn142:5.21": "Bố thí đến người đang thực hành để chứng đạt quả Nhập Lưu—",
  "mn142:5.22": "đây là loại bố thí đến từng cá nhân thứ mười. ",
  "mn142:5.23": "Bố thí đến những người ngoại đạo đã ly tham dục—",
  "mn142:5.24": "đây là loại bố thí đến từng cá nhân thứ mười một. ",
  "mn142:5.25": "Bố thí đến phàm phu có giới—",
  "mn142:5.26": "đây là loại bố thí đến từng cá nhân thứ mười hai. ",
  "mn142:5.27": "Bố thí đến phàm phu phá giới—",
  "mn142:5.28": "đây là loại bố thí đến từng cá nhân thứ mười ba. ",
  "mn142:5.29": "Bố thí đến loài súc sinh—",
  "mn142:5.30": "đây là loại bố thí đến từng cá nhân thứ mười bốn. ",
  "mn142:6.1": "Này Ānanda, trong các loại đó, bố thí đến loài súc sinh thì mong đợi phước báu gấp trăm lần; bố thí đến phàm phu phá giới thì mong đợi phước báu gấp ngàn lần; bố thí đến phàm phu có giới thì mong đợi phước báu gấp trăm ngàn lần; bố thí đến những người ngoại đạo đã ly tham dục thì mong đợi phước báu gấp trăm ngàn vạn lần; bố thí đến người đang thực hành để chứng đạt quả Nhập Lưu thì mong đợi phước báu vô số, vô lượng. Huống chi là bố thí đến bậc Nhập Lưu, huống chi là bố thí đến người đang thực hành để chứng đạt quả Nhất Lai, huống chi là bố thí đến bậc Nhất Lai, huống chi là bố thí đến người đang thực hành để chứng đạt quả Bất Lai, huống chi là bố thí đến bậc Bất Lai, huống chi là bố thí đến người đang thực hành để chứng đạt quả A-la-hán, huống chi là bố thí đến các bậc A-la-hán, huống chi là bố thí đến các bậc Độc Giác Phật, huống chi là bố thí đến bậc Như Lai, A-la-hán, Chánh Đẳng Giác. ",
  "mn142:7.1": "Này Ānanda, có bảy loại bố thí đến Tăng chúng. ",
  "mn142:7.2": "Bảy loại nào? ",
  "mn142:7.3": "Bố thí đến Tăng chúng gồm cả hai giới, có Phật đứng đầu—",
  "mn142:7.4": "đây là loại bố thí đến Tăng chúng thứ nhất. ",
  "mn142:7.5": "Khi Như Lai đã nhập Niết Bàn, bố thí đến Tăng chúng gồm cả hai giới—",
  "mn142:7.6": "đây là loại bố thí đến Tăng chúng thứ hai. ",
  "mn142:7.7": "Bố thí đến Tăng chúng Tỳ-kheo—",
  "mn142:7.8": "đây là loại bố thí đến Tăng chúng thứ ba. ",
  "mn142:7.9": "Bố thí đến Tăng chúng Tỳ-kheo-ni—",
  "mn142:7.10": "đây là loại bố thí đến Tăng chúng thứ tư. ",
  "mn142:7.11": "Bố thí với ý định: ‘Hãy chỉ định cho tôi bấy nhiêu Tỳ-kheo và Tỳ-kheo-ni từ Tăng chúng’—",
  "mn142:7.12": "đây là loại bố thí đến Tăng chúng thứ năm. ",
  "mn142:7.13": "Bố thí với ý định: ‘Hãy chỉ định cho tôi bấy nhiêu Tỳ-kheo từ Tăng chúng’—",
  "mn142:7.14": "đây là loại bố thí đến Tăng chúng thứ sáu. ",
  "mn142:7.15": "Bố thí với ý định: ‘Hãy chỉ định cho tôi bấy nhiêu Tỳ-kheo-ni từ Tăng chúng’—",
  "mn142:7.16": "đây là loại bố thí đến Tăng chúng thứ bảy. ",
  "mn142:8.1": "Này Ānanda, trong tương lai sẽ có những người thuộc dòng dõi (Thích Ca), cổ mang y vàng, nhưng phá giới, ác pháp. ",
  "mn142:8.2": "Họ sẽ bố thí đến Tăng chúng, dù những người đó phá giới. ",
  "mn142:8.3": "Khi ấy, này Ānanda, Ta nói rằng bố thí đến Tăng chúng là vô số, vô lượng. ",
  "mn142:8.4": "Tuy nhiên, này Ānanda, Ta không nói rằng bố thí đến từng cá nhân có quả lớn hơn bố thí đến Tăng chúng, bằng bất cứ cách nào. ",
  "mn142:9.1": "Này Ānanda, có bốn sự thanh tịnh của bố thí. ",
  "mn142:9.2": "Bốn loại nào? ",
  "mn142:9.3": "Này Ānanda, có bố thí thanh tịnh từ người cho, không thanh tịnh từ người nhận. ",
  "mn142:9.4": "Này Ānanda, có bố thí thanh tịnh từ người nhận, không thanh tịnh từ người cho. ",
  "mn142:9.5": "Này Ānanda, có bố thí không thanh tịnh từ người cho, cũng không thanh tịnh từ người nhận. ",
  "mn142:9.6": "Này Ānanda, có bố thí thanh tịnh từ người cho và thanh tịnh từ người nhận. ",
  "mn142:10.1": "Này Ānanda, thế nào là bố thí thanh tịnh từ người cho, không thanh tịnh từ người nhận? ",
  "mn142:10.2": "Ở đây, này Ānanda, người cho có giới hạnh, có pháp lành; người nhận thì phá giới, có pháp ác—",
  "mn142:10.3": "như vậy, này Ānanda, bố thí thanh tịnh từ người cho, không thanh tịnh từ người nhận. ",
  "mn142:11.1": "Này Ānanda, thế nào là bố thí thanh tịnh từ người nhận, không thanh tịnh từ người cho? ",
  "mn142:11.2": "Ở đây, này Ānanda, người cho thì phá giới, có pháp ác; người nhận thì có giới hạnh, có pháp lành—",
  "mn142:11.3": "như vậy, này Ānanda, bố thí thanh tịnh từ người nhận, không thanh tịnh từ người cho. ",
  "mn142:12.1": "Này Ānanda, thế nào là bố thí không thanh tịnh từ người cho, cũng không thanh tịnh từ người nhận? ",
  "mn142:12.2": "Ở đây, này Ānanda, người cho thì phá giới, có pháp ác; người nhận cũng phá giới, có pháp ác—",
  "mn142:12.3": "như vậy, này Ānanda, bố thí không thanh tịnh từ người cho, cũng không thanh tịnh từ người nhận. ",
  "mn142:13.1": "Này Ānanda, thế nào là bố thí thanh tịnh từ người cho và thanh tịnh từ người nhận? ",
  "mn142:13.2": "Ở đây, này Ānanda, người cho thì có giới hạnh, có pháp lành; người nhận cũng có giới hạnh, có pháp lành—",
  "mn142:13.3": "như vậy, này Ānanda, bố thí thanh tịnh từ người cho và thanh tịnh từ người nhận. ",
  "mn142:13.4": "Này Ānanda, đây là bốn sự thanh tịnh của bố thí.” ",
  "mn142:14.1": "Thế Tôn đã nói như vậy. ",
  "mn142:14.2": "Sau khi nói điều này, Thiện Thệ, bậc Đạo Sư, lại nói thêm: ",
  "mn142:14.3": "“Người có giới, bố thí cho người phá giới, ",
  "mn142:14.4": "Với tài sản có được đúng Pháp, tâm rất trong sạch; ",
  "mn142:14.5": "Hoàn toàn tin vào quả nghiệp lớn lao, ",
  "mn142:14.6": "Bố thí ấy thanh tịnh từ người cho. ",
  "mn142:14.7": "Người phá giới, bố thí cho người có giới, ",
  "mn142:14.8": "Với tài sản có được không đúng Pháp, tâm không trong sạch; ",
  "mn142:14.9": "Không hoàn toàn tin vào quả nghiệp lớn lao, ",
  "mn142:14.10": "Sự cúng dường ấy được thanh tịnh từ người nhận. ",
  "mn142:14.11": "Ai là người phạm giới, cúng dường cho những người phạm giới,",
  "mn142:14.12": "Với của cải phi pháp, tâm không hoan hỷ;",
  "mn142:14.13": "Không tin tưởng quả báo của nghiệp lớn lao,",
  "mn142:14.14": "Ta nói sự cúng dường ấy không có quả lớn. ",
  "mn142:14.15": "Ai là người giữ giới, cúng dường cho những người giữ giới,",
  "mn142:14.16": "Với của cải hợp pháp, tâm rất hoan hỷ;",
  "mn142:14.17": "Tin tưởng quả báo của nghiệp lớn lao,",
  "mn142:14.18": "Ta nói sự cúng dường ấy chắc chắn có quả lớn. ",
  "mn142:14.19": "Ai là người đã hết tham, cúng dường cho những người đã hết tham,",
  "mn142:14.20": "Với của cải hợp pháp, tâm rất hoan hỷ;",
  "mn142:14.21": "Tin tưởng quả báo của nghiệp lớn lao,",
  "mn142:14.22": "Ta nói sự cúng dường ấy chắc chắn là cao nhất trong các sự cúng dường vật chất.”",
  "mn142:14.23": "Kinh Phân Biệt Cúng Dường, thứ mười hai, đã xong. ",
  "mn142:14.24": "Chương Phân Biệt, thứ tư, đã xong. ",
  "mn142:15.0": "Mục lục của chương ấy: ",
  "mn142:15.1": "Bhaddekaratta, Ananda, Kaccana,",
  "mn142:15.2": "Lomasakaṅgiya, Asubha;",
  "mn142:15.3": "Đại Nghiệp, Phân Biệt Sáu Xứ,",
  "mn142:15.4": "Đề mục, Vô Tranh, Giới, Sự Thật. ",
  "mn142:15.5": "Kinh Phân Biệt Cúng Dường. "
}
window.BILARA["mn142"]["vi"]["mn142:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
