window.BILARA = window.BILARA || {};
window.BILARA["mn146"] = window.BILARA["mn146"] || {};
window.BILARA["mn146"]["vi"] = {
  "mn146:0.1": "Trung Bộ Kinh 146 ",
  "mn146:0.2": "Kinh Nandakovāda ",
  "mn146:1.1": "Tôi nghe như vầy",
  "mn146:1.2": "Một thời Thế Tôn trú ở Sāvatthī, tại Jetavana, khu vườn của ông Anāthapiṇḍika. ",
  "mn146:2.1": "Rồi Mahāpajāpatī Gotamī, cùng với khoảng năm trăm Tỳ Kheo Ni, đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi đứng một bên. Đứng một bên, Mahāpajāpatī Gotamī bạch Tôn Giả rằng: ",
  "mn146:2.2": "“Bạch Thế Tôn, xin Thế Tôn hãy giáo giới các Tỳ Kheo Ni; ",
  "mn146:2.3": "Xin Thế Tôn hãy khuyên dạy các Tỳ Kheo Ni; ",
  "mn146:2.4": "Xin Thế Tôn hãy thuyết pháp cho các Tỳ Kheo Ni.” ",
  "mn146:3.1": "Lúc bấy giờ, các Tỳ Kheo trưởng lão đang giáo giới các Tỳ Kheo Ni theo phiên. ",
  "mn146:3.2": "Tôn giả Nandaka không muốn giáo giới các Tỳ Kheo Ni theo phiên. ",
  "mn146:3.3": "Rồi Thế Tôn gọi Tôn giả Ānanda: ",
  "mn146:3.4": "“Này Ānanda, hôm nay là phiên của ai để giáo giới các Tỳ Kheo Ni?” ",
  "mn146:3.5": "“Bạch Thế Tôn, tất cả đều đã giáo giới các Tỳ Kheo Ni theo phiên rồi. ",
  "mn146:3.6": "Bạch Thế Tôn, Tôn giả Nandaka đây không muốn giáo giới các Tỳ Kheo Ni theo phiên.” ",
  "mn146:4.1": "Rồi Thế Tôn gọi Tôn giả Nandaka: ",
  "mn146:4.2": "“Này Nandaka, hãy giáo giới các Tỳ Kheo Ni; ",
  "mn146:4.3": "hãy khuyên dạy các Tỳ Kheo Ni; ",
  "mn146:4.4": "này Bà-la-môn, hãy thuyết pháp cho các Tỳ Kheo Ni.” ",
  "mn146:4.5": "“Vâng, bạch Thế Tôn,” Tôn giả Nandaka vâng lời Thế Tôn, vào buổi sáng, đắp y, cầm bát và y, đi vào Sāvatthī để khất thực. ",
  "mn146:4.6": "Sau khi khất thực ở Sāvatthī, sau bữa ăn, trở về từ khất thực, một mình với người thứ hai, Tôn giả đi đến khu vườn của vua. ",
  "mn146:4.7": "Các Tỳ Kheo Ni ấy thấy Tôn giả Nandaka đang đến từ xa. ",
  "mn146:4.8": "Thấy vậy, họ sắp đặt chỗ ngồi, và chuẩn bị nước rửa chân. ",
  "mn146:4.9": "Tôn giả Nandaka ngồi xuống chỗ đã sắp đặt. ",
  "mn146:4.10": "Ngồi xuống, Tôn giả rửa chân. ",
  "mn146:4.11": "Các Tỳ Kheo Ni ấy cũng đảnh lễ Tôn giả Nandaka rồi ngồi một bên. ",
  "mn146:4.12": "Ngồi một bên, Tôn giả Nandaka nói với các Tỳ Kheo Ni ấy rằng: ",
  "mn146:5.1": "“này các chị em, sẽ có một cuộc nói chuyện hỏi đáp. ",
  "mn146:5.2": "Ở đó, những ai hiểu thì nên nói: ‘Chúng tôi hiểu’, những ai không hiểu thì nên nói: ‘Chúng tôi không hiểu’. ",
  "mn146:5.3": "Hoặc nếu ai có nghi ngờ hay phân vân, thì chính tôi sẽ là người được hỏi: ",
  "mn146:5.4": "‘Bạch Tôn giả, điều này là thế nào; ý nghĩa của điều này là gì?’” ",
  "mn146:5.5": "“Bạch Tôn giả, chỉ với điều này thôi, chúng con đã hoan hỷ và hài lòng với Tôn giả Nandaka, vì Tôn giả Nandaka đã cho phép chúng con.” ",
  "mn146:6.1": "“này các chị em, các chị nghĩ sao, ",
  "mn146:6.2": "mắt là thường hay vô thường?” ",
  "mn146:6.3": "“Vô thường, bạch Tôn Giả.” ",
  "mn146:6.4": "“Mà cái gì vô thường thì là khổ hay là sướng?” ",
  "mn146:6.5": "“Khổ, bạch Tôn Giả.” ",
  "mn146:6.6": "“Mà cái gì vô thường, khổ, có tính chất biến đổi, có hợp lý không khi xem xét nó là: ",
  "mn146:6.7": "‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’?” ",
  "mn146:6.8": "“Không hợp lý, bạch Tôn Giả.” ",
  "mn146:6.9": "“này các chị em, các chị nghĩ sao, ",
  "mn146:6.10": "tai là thường hay vô thường?” ",
  "mn146:6.11": "“Vô thường, bạch Tôn Giả …pe… ",
  "mn146:6.12": "mũi là thường hay vô thường?” ",
  "mn146:6.13": "“Vô thường, bạch Tôn Giả” … ",
  "mn146:6.14": "“lưỡi là thường hay vô thường?” ",
  "mn146:6.15": "“Vô thường, bạch Tôn Giả” … ",
  "mn146:6.16": "“thân là thường hay vô thường?” ",
  "mn146:6.17": "“Vô thường, bạch Tôn Giả” … ",
  "mn146:6.18": "“ý là thường hay vô thường?” ",
  "mn146:6.19": "“Vô thường, bạch Tôn Giả.” ",
  "mn146:6.20": "“Mà cái gì vô thường thì là khổ hay là sướng?” ",
  "mn146:6.21": "“Khổ, bạch Tôn Giả.” ",
  "mn146:6.22": "“Mà cái gì vô thường, khổ, có tính chất biến đổi, có hợp lý không khi xem xét nó là: ",
  "mn146:6.23": "‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’?” ",
  "mn146:6.24": "“Không hợp lý, bạch Tôn Giả.” ",
  "mn146:6.25": "“Vì lý do gì?” ",
  "mn146:6.26": "“bạch Tôn Giả, trước đây chúng con đã thấy rõ điều này bằng chánh trí như thật rằng: ",
  "mn146:6.27": "‘Sáu nội xứ này là vô thường’.” ",
  "mn146:6.28": "“Lành thay, lành thay, này các chị em. ",
  "mn146:6.29": "này các chị em, một đệ tử của bậc Thánh khi thấy bằng chánh trí như thật thì là như vậy. ",
  "mn146:7.1": "này các chị em, các chị nghĩ sao, ",
  "mn146:7.2": "sắc là thường hay vô thường?” ",
  "mn146:7.3": "“Vô thường, bạch Tôn Giả.” ",
  "mn146:7.4": "“Mà cái gì vô thường thì là khổ hay là sướng?” ",
  "mn146:7.5": "“Khổ, bạch Tôn Giả.” ",
  "mn146:7.6": "“Mà cái gì vô thường, khổ, có tính chất biến đổi, có hợp lý không khi xem xét nó là: ",
  "mn146:7.7": "‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’?” ",
  "mn146:7.8": "“Không hợp lý, bạch Tôn Giả.” ",
  "mn146:7.9": "“này các chị em, các chị nghĩ sao, ",
  "mn146:7.10": "tiếng là thường hay vô thường?” ",
  "mn146:7.11": "“Vô thường, bạch Tôn Giả …pe… ",
  "mn146:7.12": "mùi là thường hay vô thường?” ",
  "mn146:7.13": "“Vô thường, bạch Tôn Giả” … ",
  "mn146:7.14": "“vị là thường hay vô thường?” ",
  "mn146:7.15": "“Vô thường, bạch Tôn Giả” … ",
  "mn146:7.16": "“xúc là thường hay vô thường?” ",
  "mn146:7.17": "“Vô thường, bạch Tôn Giả” … ",
  "mn146:7.18": "“pháp là thường hay vô thường?” ",
  "mn146:7.19": "“Vô thường, bạch Tôn Giả.” ",
  "mn146:7.20": "“Mà cái gì vô thường thì là khổ hay là sướng?” ",
  "mn146:7.21": "“Khổ, bạch Tôn Giả.” ",
  "mn146:7.22": "“Mà cái gì vô thường, khổ, có tính chất biến đổi, có hợp lý không khi xem xét nó là: ",
  "mn146:7.23": "‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’?” ",
  "mn146:7.24": "“Không hợp lý, bạch Tôn Giả.” ",
  "mn146:7.25": "“Vì lý do gì?” ",
  "mn146:7.26": "“bạch Tôn Giả, trước đây chúng con đã thấy rõ điều này bằng chánh trí như thật rằng: ",
  "mn146:7.27": "‘Sáu ngoại xứ này là vô thường’.” ",
  "mn146:7.28": "“Lành thay, lành thay, này các chị em. ",
  "mn146:7.29": "này các chị em, một đệ tử của bậc Thánh khi thấy bằng chánh trí như thật thì là như vậy. ",
  "mn146:8.1": "này các chị em, các chị nghĩ sao, ",
  "mn146:8.2": "nhãn thức là thường hay vô thường?” ",
  "mn146:8.3": "“Vô thường, bạch Tôn Giả.” ",
  "mn146:8.4": "“Mà cái gì vô thường thì là khổ hay là sướng?” ",
  "mn146:8.5": "“Khổ, bạch Tôn Giả.” ",
  "mn146:8.6": "“Mà cái gì vô thường, khổ, có tính chất biến đổi, có hợp lý không khi xem xét nó là: ",
  "mn146:8.7": "‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’?” ",
  "mn146:8.8": "“Không hợp lý, bạch Tôn Giả.” ",
  "mn146:8.9": "“này các chị em, các chị nghĩ sao, nhĩ thức là thường hay vô thường?” ",
  "mn146:8.10": "“Vô thường, bạch Tôn Giả …pe… ",
  "mn146:8.11": "tỷ thức là thường hay vô thường?” ",
  "mn146:8.12": "“Vô thường, bạch Tôn Giả” … ",
  "mn146:8.13": "“thiệt thức là thường hay vô thường?” ",
  "mn146:8.14": "“Vô thường, bạch Tôn Giả” … ",
  "mn146:8.15": "“thân thức là thường hay vô thường?” ",
  "mn146:8.16": "“Vô thường, bạch Tôn Giả” … ",
  "mn146:8.17": "“ý thức là thường hay vô thường?” ",
  "mn146:8.18": "“Vô thường, bạch Tôn Giả.” ",
  "mn146:8.19": "“Mà cái gì vô thường thì là khổ hay là sướng?” ",
  "mn146:8.20": "“Khổ, bạch Tôn Giả.” ",
  "mn146:8.21": "“Mà cái gì vô thường, khổ, có tính chất biến đổi, có hợp lý không khi xem xét nó là: ",
  "mn146:8.22": "‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’?” ",
  "mn146:8.23": "“Không hợp lý, bạch Tôn Giả.” ",
  "mn146:8.24": "“Vì lý do gì?” ",
  "mn146:8.25": "“bạch Tôn Giả, trước đây chúng con đã thấy rõ điều này bằng chánh trí như thật rằng: ",
  "mn146:8.26": "‘Sáu thân thức này là vô thường’.” ",
  "mn146:8.27": "“Lành thay, lành thay, này các chị em. ",
  "mn146:8.28": "này các chị em, một đệ tử của bậc Thánh khi thấy bằng chánh trí như thật thì là như vậy. ",
  "mn146:9.1": "này các chị em, ví như một ngọn đèn dầu đang cháy, dầu cũng vô thường, có tính chất biến đổi, bấc cũng vô thường, có tính chất biến đổi, lửa cũng vô thường, có tính chất biến đổi, ánh sáng cũng vô thường, có tính chất biến đổi. ",
  "mn146:9.2": "này các chị em, nếu ai nói rằng: ",
  "mn146:9.3": "‘Dầu của ngọn đèn dầu đang cháy ấy cũng vô thường, có tính chất biến đổi, bấc cũng vô thường, có tính chất biến đổi, lửa cũng vô thường, có tính chất biến đổi; ",
  "mn146:9.4": "và ánh sáng của nó là thường còn, bền vững, vĩnh cửu, không biến đổi’; ",
  "mn146:9.5": "này các chị em, người ấy nói như vậy có đúng không?” ",
  "mn146:9.6": "“Không đúng vậy, bạch Tôn Giả”. ",
  "mn146:9.7": "“Vì sao vậy”? ",
  "mn146:9.8": "“bạch Tôn Giả, khi ngọn đèn dầu ấy cháy, dầu cũng là vô thường, có tính biến đổi; bấc cũng là vô thường, có tính biến đổi; ngọn lửa cũng là vô thường, có tính biến đổi; ",
  "mn146:9.9": "huống chi ánh sáng của nó là vô thường, có tính biến đổi”. ",
  "mn146:9.10": "“Cũng vậy, này các chị em, nếu ai nói rằng: ",
  "mn146:9.11": "‘Sáu nội xứ này là vô thường; ",
  "mn146:9.12": "và cái gì do duyên sáu nội xứ mà cảm thọ lạc, khổ, hay không khổ không lạc, cái đó là thường còn, bền vững, vĩnh cửu, không biến đổi’; ",
  "mn146:9.13": "này các chị em, người ấy nói như vậy có đúng không?” ",
  "mn146:9.14": "“Không đúng vậy, bạch Tôn Giả”. ",
  "mn146:9.15": "“Vì sao vậy”? ",
  "mn146:9.16": "“bạch Tôn Giả, do duyên từng cái duyên mà từng cái cảm thọ sinh khởi. ",
  "mn146:9.17": "Do duyên từng cái duyên ấy diệt mà từng cái cảm thọ ấy diệt”. ",
  "mn146:9.18": "“Lành thay, lành thay, này các chị em. ",
  "mn146:9.19": "này các chị em, đối với vị Thánh đệ tử thấy đúng như thật bằng tuệ quán chân chính thì sự việc là như vậy. ",
  "mn146:10.1": "Ví như, này các chị em, một cây lớn có lõi đang đứng, rễ cũng là vô thường, có tính biến đổi; thân cũng là vô thường, có tính biến đổi; cành lá cũng là vô thường, có tính biến đổi; bóng cây cũng là vô thường, có tính biến đổi. ",
  "mn146:10.2": "này các chị em, nếu ai nói rằng: ",
  "mn146:10.3": "‘Rễ của cây lớn có lõi đang đứng ấy là vô thường, có tính biến đổi; thân cũng là vô thường, có tính biến đổi; cành lá cũng là vô thường, có tính biến đổi; và bóng cây của nó là thường còn, bền vững, vĩnh cửu, không biến đổi’; ",
  "mn146:10.4": "này các chị em, người ấy nói như vậy có đúng không?” ",
  "mn146:10.5": "“Không đúng vậy, bạch Tôn Giả”. ",
  "mn146:10.6": "“Vì sao vậy”? ",
  "mn146:10.7": "“bạch Tôn Giả, rễ của cây lớn có lõi đang đứng ấy là vô thường, có tính biến đổi; thân cũng là vô thường, có tính biến đổi; cành lá cũng là vô thường, có tính biến đổi; ",
  "mn146:10.8": "huống chi bóng cây của nó là vô thường, có tính biến đổi”. ",
  "mn146:10.9": "“Cũng vậy, này các chị em, nếu ai nói rằng: ",
  "mn146:10.10": "‘Sáu ngoại xứ này là vô thường. ",
  "mn146:10.11": "Và cái gì do duyên sáu ngoại xứ mà cảm thọ lạc, khổ, hay không khổ không lạc, cái đó là thường còn, bền vững, vĩnh cửu, không biến đổi’; ",
  "mn146:10.12": "này các chị em, người ấy nói như vậy có đúng không?” ",
  "mn146:10.13": "“Không đúng vậy, bạch Tôn Giả”. ",
  "mn146:10.14": "“Vì sao vậy”? ",
  "mn146:10.15": "“bạch Tôn Giả, do duyên từng cái duyên mà từng cái cảm thọ sinh khởi. ",
  "mn146:10.16": "Do duyên từng cái duyên ấy diệt mà từng cái cảm thọ ấy diệt”. ",
  "mn146:10.17": "“Lành thay, lành thay, này các chị em. ",
  "mn146:10.18": "này các chị em, đối với vị Thánh đệ tử thấy đúng như thật bằng tuệ quán chân chính thì sự việc là như vậy. ",
  "mn146:11.1": "Ví như, này các chị em, một người đồ tể khéo léo hay đệ tử của người đồ tể, sau khi giết một con bò, dùng dao mổ bò sắc bén để xẻ thịt con bò, không làm tổn hại phần thịt bên trong, không làm tổn hại phần da bên ngoài. ",
  "mn146:11.2": "Chỗ nào có thịt dính, chỗ nào có gân, chỗ nào có dây chằng, người ấy dùng dao mổ bò sắc bén cắt đứt, xẻ ra, tách rời, phân chia. ",
  "mn146:11.3": "Sau khi cắt đứt, xẻ ra, tách rời, phân chia, và rũ bỏ phần da bên ngoài, người ấy dùng chính tấm da đó để che phủ con bò và nói rằng: ",
  "mn146:11.4": "‘Con bò này vẫn còn dính liền với tấm da này’; ",
  "mn146:11.5": "này các chị em, người ấy nói như vậy có đúng không?” ",
  "mn146:11.6": "“Không đúng vậy, bạch Tôn Giả”. ",
  "mn146:11.7": "“Vì sao vậy”? ",
  "mn146:11.8": "“bạch Tôn Giả, người đồ tể khéo léo hay đệ tử của người đồ tể ấy, sau khi giết một con bò, dùng dao mổ bò sắc bén để xẻ thịt con bò, không làm tổn hại phần thịt bên trong, không làm tổn hại phần da bên ngoài. ",
  "mn146:11.9": "Chỗ nào có thịt dính, chỗ nào có gân, chỗ nào có dây chằng, người ấy dùng dao mổ bò sắc bén cắt đứt, xẻ ra, tách rời, phân chia. ",
  "mn146:11.10": "Sau khi cắt đứt, xẻ ra, tách rời, phân chia, và rũ bỏ phần da bên ngoài, người ấy dùng chính tấm da đó để che phủ con bò, dù người ấy có nói rằng: ",
  "mn146:11.11": "‘Con bò này vẫn còn dính liền với tấm da này’; ",
  "mn146:11.12": "nhưng con bò ấy đã không còn dính liền với tấm da đó nữa”. ",
  "mn146:12.1": "“này các chị em, ví dụ này được Ta đưa ra để làm rõ ý nghĩa. ",
  "mn146:12.2": "Đây là ý nghĩa của nó; ",
  "mn146:12.3": "‘phần thịt bên trong’ này, này các chị em, là tên gọi của sáu nội xứ; ",
  "mn146:12.4": "‘phần da bên ngoài’ này, này các chị em, là tên gọi của sáu ngoại xứ; ",
  "mn146:12.5": "‘thịt dính, gân, dây chằng’ này, này các chị em, là tên gọi của hỷ ái; ",
  "mn146:12.6": "‘dao mổ bò sắc bén’ này, này các chị em, là tên gọi của tuệ Thánh; ",
  "mn146:12.7": "tuệ Thánh ấy cắt đứt, xẻ ra, tách rời, phân chia phiền não, kiết sử, trói buộc. ",
  "mn146:13.1": "này các chị em, có bảy chi phần giác ngộ này, khi được tu tập và làm cho sung mãn, vị Tỳ-kheo do diệt trừ các lậu hoặc mà chứng đạt và an trú vô lậu tâm giải thoát, tuệ giải thoát ngay trong hiện tại, tự mình chứng ngộ. ",
  "mn146:13.2": "Bảy chi phần nào? ",
  "mn146:13.3": "Ở đây, này các chị em, vị Tỳ-kheo tu tập biết rõ mình đang làm gì, nghĩ gì, cảm gì, nương tựa viễn ly, nương tựa ly tham, nương tựa đoạn diệt, đưa đến xả bỏ. ",
  "mn146:13.4": "Tu tập quan sát và hiểu bản chất của sự việc … ",
  "mn146:13.5": "tu tập siêng năng, không lười biếng … ",
  "mn146:13.6": "tu tập niềm vui nhẹ nhàng trong tâm khi tu tập đúng … ",
  "mn146:13.7": "tu tập thân và tâm trở nên nhẹ nhàng, thư giãn … ",
  "mn146:13.8": "tu tập tâm tập trung vững vàng, không bị phân tán … ",
  "mn146:13.9": "tu tập tâm quân bình, không thiên về thích hay ghét, nương tựa viễn ly, nương tựa ly tham, nương tựa đoạn diệt, đưa đến xả bỏ. ",
  "mn146:13.10": "này các chị em, đây là bảy chi phần giác ngộ, khi được tu tập và làm cho sung mãn, vị Tỳ-kheo do diệt trừ các lậu hoặc mà chứng đạt và an trú vô lậu tâm giải thoát, tuệ giải thoát ngay trong hiện tại, tự mình chứng ngộ”. ",
  "mn146:14.1": "Rồi Tôn giả Nandaka, sau khi khuyên dạy các Tỳ-kheo-ni ấy bằng lời khuyên này, liền bảo họ ra về: ",
  "mn146:14.2": "“này các chị em, hãy đi đi; đã đến lúc rồi”. ",
  "mn146:14.3": "Rồi các Tỳ-kheo-ni ấy, hoan hỷ và tùy hỷ lời Tôn giả Nandaka đã nói, đứng dậy khỏi chỗ ngồi, đảnh lễ Tôn giả Nandaka, đi nhiễu bên phải, rồi đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn, rồi đứng sang một bên. Khi các Tỳ-kheo-ni ấy đứng sang một bên, Thế Tôn nói với họ: ",
  "mn146:14.4": "“Này các Tỳ-kheo-ni, hãy đi đi; đã đến lúc rồi”. ",
  "mn146:14.5": "Rồi các Tỳ-kheo-ni ấy đảnh lễ Thế Tôn, đi nhiễu bên phải, rồi ra đi. ",
  "mn146:15.1": "Rồi Thế Tôn, khi các Tỳ-kheo-ni ấy vừa đi khỏi không lâu, liền gọi các Tỳ-kheo: ",
  "mn146:15.2": "“Ví như, này các Tỳ-kheo, vào ngày Bố-tát mười bốn, không có nhiều người nghi ngờ hay phân vân rằng: ",
  "mn146:15.3": "‘Trăng có khuyết không, trăng có tròn không’, mà trăng chỉ khuyết thôi. ",
  "mn146:15.4": "Cũng vậy, này các Tỳ-kheo, các Tỳ-kheo-ni ấy hoan hỷ với bài pháp của Nandaka, nhưng chưa hoàn toàn viên mãn ý nguyện”. ",
  "mn146:16.1": "Rồi Thế Tôn gọi Tôn giả Nandaka: ",
  "mn146:16.2": "“Vậy thì, này Nandaka, ngày mai con hãy khuyên dạy các Tỳ-kheo-ni ấy bằng lời khuyên đó”. ",
  "mn146:16.3": "“Vâng, bạch Thế Tôn”, Tôn giả Nandaka vâng lời Thế Tôn. ",
  "mn146:16.4": "Rồi Tôn giả Nandaka, sau khi đêm ấy trôi qua, vào buổi sáng đắp y, cầm bát và y, đi vào Xá-vệ để khất thực. ",
  "mn146:16.5": "Sau khi khất thực ở Xá-vệ, và sau bữa ăn, trở về từ việc khất thực, Tôn giả cùng với một người bạn đi đến khu vườn của vua. ",
  "mn146:16.6": "Các Tỳ-kheo-ni ấy thấy Tôn giả Nandaka đang đến từ xa. ",
  "mn146:16.7": "Sau khi thấy, họ sắp đặt chỗ ngồi, và chuẩn bị nước rửa chân. ",
  "mn146:16.8": "Tôn giả Nandaka ngồi xuống chỗ ngồi đã sắp đặt. ",
  "mn146:16.9": "Sau khi ngồi, Tôn giả rửa chân. ",
  "mn146:16.10": "Các Tỳ-kheo-ni ấy cũng đảnh lễ Tôn giả Nandaka, rồi ngồi sang một bên. ",
  "mn146:16.11": "Khi các Tỳ-kheo-ni ấy đã ngồi sang một bên, Tôn giả Nandaka nói với họ: ",
  "mn146:16.12": "“này các chị em, sẽ có một cuộc đàm thoại hỏi đáp. ",
  "mn146:16.13": "Ở đó, những ai hiểu thì nên nói ‘chúng tôi hiểu’, những ai không hiểu thì nên nói ‘chúng tôi không hiểu’. ",
  "mn146:16.14": "Hoặc nếu ai có nghi ngờ hay phân vân, thì chính tôi sẽ được hỏi: ",
  "mn146:16.15": "‘bạch Tôn Giả, điều này là gì; ý nghĩa của điều này là gì’”. ",
  "mn146:16.16": "“bạch Tôn Giả, chỉ với điều này thôi, chúng con đã hoan hỷ và hài lòng với Tôn giả Nandaka, vì Tôn giả Nandaka đã cho phép chúng con”. ",
  "mn146:17-18.1": "“này các chị em, các chị nghĩ sao, mắt là thường hay vô thường”? ",
  "mn146:17-18.2": "“Vô thường, bạch Tôn Giả”. ",
  "mn146:17-18.3": "“Cái gì vô thường, cái đó là khổ hay lạc”? ",
  "mn146:17-18.4": "“Khổ, bạch Tôn Giả”. ",
  "mn146:17-18.5": "“Cái gì vô thường, khổ, có tính biến đổi, có hợp lý không khi xem xét nó là: ",
  "mn146:17-18.6": "‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’”? ",
  "mn146:17-18.7": "“Không đúng vậy, bạch Tôn Giả”. ",
  "mn146:17-18.8": "“này các chị em, các chị nghĩ sao, tai là thường hay vô thường”? ",
  "mn146:17-18.9": "“Vô thường, bạch Tôn Giả … ",
  "mn146:17-18.10": "mũi là thường hay vô thường”? ",
  "mn146:17-18.11": "“Vô thường, bạch Tôn Giả … ",
  "mn146:17-18.12": "lưỡi … ",
  "mn146:17-18.13": "thân … ",
  "mn146:17-18.14": "ý là thường hay vô thường”? ",
  "mn146:17-18.15": "“Vô thường, bạch Tôn Giả”. ",
  "mn146:17-18.16": "“Cái gì vô thường, cái đó là khổ hay lạc”? ",
  "mn146:17-18.17": "“Khổ, bạch Tôn Giả”. ",
  "mn146:17-18.18": "“Cái gì vô thường, khổ, có tính biến đổi, có hợp lý không khi xem xét nó là: ",
  "mn146:17-18.19": "‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’”? ",
  "mn146:17-18.20": "“Không đúng vậy, bạch Tôn Giả”. ",
  "mn146:17-18.21": "“Vì sao vậy”? ",
  "mn146:17-18.22": "“bạch Tôn Giả, trước đây chúng con đã thấy rõ điều này đúng như thật bằng tuệ quán chân chính: ",
  "mn146:17-18.23": "‘Sáu nội xứ này là vô thường’”. ",
  "mn146:17-18.24": "“Lành thay, lành thay, này các chị em. ",
  "mn146:17-18.25": "này các chị em, đối với vị Thánh đệ tử thấy đúng như thật bằng tuệ quán chân chính thì sự việc là như vậy. ",
  "mn146:19-20.1": "“này các chị em, các chị nghĩ sao, sắc là thường hay vô thường”? ",
  "mn146:19-20.2": "“Vô thường, bạch Tôn Giả”. ",
  "mn146:19-20.3": "“Cái gì vô thường, cái đó là khổ hay lạc”? ",
  "mn146:19-20.4": "“Khổ, bạch Tôn Giả”. ",
  "mn146:19-20.5": "“Cái gì vô thường, khổ, có tính biến đổi, có hợp lý không khi xem xét nó là: ",
  "mn146:19-20.6": "‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’”? ",
  "mn146:19-20.7": "“Không đúng vậy, bạch Tôn Giả”. ",
  "mn146:19-20.8": "“này các chị em, các chị nghĩ sao, âm thanh là thường hay vô thường?”",
  "mn146:19-20.9": "“bạch Tôn Giả, vô thường…pe…”",
  "mn146:19-20.10": "mùi là thường hay vô thường?”",
  "mn146:19-20.11": "“bạch Tôn Giả, vô thường…”",
  "mn146:19-20.12": "vị là thường hay vô thường?”",
  "mn146:19-20.13": "“bạch Tôn Giả, vô thường…”",
  "mn146:19-20.14": "xúc chạm là thường hay vô thường?”",
  "mn146:19-20.15": "“bạch Tôn Giả, vô thường…”",
  "mn146:19-20.16": "pháp là thường hay vô thường?”",
  "mn146:19-20.17": "“bạch Tôn Giả, vô thường”.",
  "mn146:19-20.18": "“Cái gì vô thường, cái đó là khổ hay vui?”",
  "mn146:19-20.19": "“bạch Tôn Giả, là khổ”.",
  "mn146:19-20.20": "“Cái gì vô thường, khổ, có tính đổi thay, có hợp lý không khi xem xét nó là: ",
  "mn146:19-20.21": "‘cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’?”",
  "mn146:19-20.22": "“bạch Tôn Giả, không hợp lý”.",
  "mn146:19-20.23": "“Vì sao vậy?”",
  "mn146:19-20.24": "“bạch Tôn Giả, trước đây chúng con đã thấy rõ điều này bằng tuệ quán đúng đắn như thật: ",
  "mn146:19-20.25": "‘sáu xứ bên ngoài này là vô thường’.”",
  "mn146:19-20.26": "“Lành thay, lành thay, này các chị em. ",
  "mn146:19-20.27": "này các chị em, một đệ tử thánh khi thấy bằng tuệ quán đúng đắn như thật thì là như vậy. ",
  "mn146:21.1": "này các chị em, các chị nghĩ sao, nhãn thức là thường hay vô thường?”",
  "mn146:21.2": "“bạch Tôn Giả, vô thường…pe…”",
  "mn146:21.3": "nhĩ thức là thường hay vô thường?”",
  "mn146:21.4": "“bạch Tôn Giả, vô thường…”",
  "mn146:21.5": "tỷ thức là thường hay vô thường?”",
  "mn146:21.6": "“bạch Tôn Giả, vô thường…”",
  "mn146:21.7": "thiệt thức là thường hay vô thường?”",
  "mn146:21.8": "“bạch Tôn Giả, vô thường…”",
  "mn146:21.9": "thân thức là thường hay vô thường?”",
  "mn146:21.10": "“bạch Tôn Giả, vô thường…”",
  "mn146:21.11": "ý thức là thường hay vô thường?”",
  "mn146:21.12": "“bạch Tôn Giả, vô thường”.",
  "mn146:21.13": "“Cái gì vô thường, cái đó là khổ hay vui?”",
  "mn146:21.14": "“bạch Tôn Giả, là khổ”.",
  "mn146:21.15": "“Cái gì vô thường, khổ, có tính đổi thay, có hợp lý không khi xem xét nó là: ",
  "mn146:21.16": "‘cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’?”",
  "mn146:21.17": "“bạch Tôn Giả, không hợp lý”.",
  "mn146:21.18": "“Vì sao vậy?”",
  "mn146:21.19": "“bạch Tôn Giả, trước đây chúng con đã thấy rõ điều này bằng tuệ quán đúng đắn như thật: ",
  "mn146:21.20": "‘sáu loại thức này là vô thường’.”",
  "mn146:21.21": "“Lành thay, lành thay, này các chị em. ",
  "mn146:21.22": "này các chị em, một đệ tử thánh khi thấy bằng tuệ quán đúng đắn như thật thì là như vậy. ",
  "mn146:22.1": "này các chị em, ví như khi một ngọn đèn dầu đang cháy, dầu cũng vô thường, có tính đổi thay; bấc cũng vô thường, có tính đổi thay; lửa cũng vô thường, có tính đổi thay; ánh sáng cũng vô thường, có tính đổi thay. ",
  "mn146:22.2": "này các chị em, nếu có ai nói rằng: ",
  "mn146:22.3": "‘khi ngọn đèn dầu kia đang cháy, dầu cũng vô thường, có tính đổi thay; bấc cũng vô thường, có tính đổi thay; lửa cũng vô thường, có tính đổi thay; ",
  "mn146:22.4": "còn ánh sáng của nó thì thường, bền vững, vĩnh cửu, không có tính đổi thay’; ",
  "mn146:22.5": "này các chị em, người ấy nói có đúng không?”",
  "mn146:22.6": "“bạch Tôn Giả, không đúng”.",
  "mn146:22.7": "“Vì sao vậy?”",
  "mn146:22.8": "“bạch Tôn Giả, vì khi ngọn đèn dầu kia đang cháy, dầu cũng vô thường, có tính đổi thay; bấc cũng vô thường, có tính đổi thay; lửa cũng vô thường, có tính đổi thay; ",
  "mn146:22.9": "huống chi ánh sáng của nó lại vô thường, có tính đổi thay”.",
  "mn146:22.10": "“Cũng vậy, này các chị em, nếu có ai nói rằng: ",
  "mn146:22.11": "‘sáu xứ bên trong này là vô thường. ",
  "mn146:22.12": "Nhưng cái gì mà do duyên sáu xứ bên trong mà cảm nhận được, hoặc lạc, hoặc khổ, hoặc không khổ không lạc, cái đó là thường, bền vững, vĩnh cửu, không có tính đổi thay’; ",
  "mn146:22.13": "này các chị em, người ấy nói có đúng không?”",
  "mn146:22.14": "“bạch Tôn Giả, không đúng”.",
  "mn146:22.15": "“Vì sao vậy?”",
  "mn146:22.16": "“bạch Tôn Giả, do duyên từng cái tương ứng mà từng cảm thọ tương ứng sinh khởi. ",
  "mn146:22.17": "Do sự diệt của từng cái duyên tương ứng mà từng cảm thọ tương ứng diệt đi”.",
  "mn146:22.18": "“Lành thay, lành thay, này các chị em. ",
  "mn146:22.19": "này các chị em, một đệ tử thánh khi thấy bằng tuệ quán đúng đắn như thật thì là như vậy. ",
  "mn146:23.1": "này các chị em, ví như khi một cây lớn có lõi đang đứng, rễ cũng vô thường, có tính đổi thay; thân cây cũng vô thường, có tính đổi thay; cành lá cũng vô thường, có tính đổi thay; bóng cây cũng vô thường, có tính đổi thay. ",
  "mn146:23.2": "này các chị em, nếu có ai nói rằng: ",
  "mn146:23.3": "‘khi cây lớn có lõi kia đang đứng, rễ cũng vô thường, có tính đổi thay; thân cây cũng vô thường, có tính đổi thay; cành lá cũng vô thường, có tính đổi thay; ",
  "mn146:23.4": "còn bóng cây của nó thì thường, bền vững, vĩnh cửu, không có tính đổi thay’; ",
  "mn146:23.5": "này các chị em, người ấy nói có đúng không?”",
  "mn146:23.6": "“bạch Tôn Giả, không đúng”.",
  "mn146:23.7": "“Vì sao vậy?”",
  "mn146:23.8": "“bạch Tôn Giả, vì khi cây lớn có lõi kia đang đứng, rễ cũng vô thường, có tính đổi thay; thân cây cũng vô thường, có tính đổi thay; cành lá cũng vô thường, có tính đổi thay; ",
  "mn146:23.9": "huống chi bóng cây của nó lại vô thường, có tính đổi thay”.",
  "mn146:23.10": "“Cũng vậy, này các chị em, nếu có ai nói rằng: ",
  "mn146:23.11": "‘sáu xứ bên ngoài này là vô thường. ",
  "mn146:23.12": "Nhưng cái gì mà do duyên sáu xứ bên ngoài mà cảm nhận được, hoặc lạc, hoặc khổ, hoặc không khổ không lạc, cái đó là thường, bền vững, vĩnh cửu, không có tính đổi thay’; ",
  "mn146:23.13": "này các chị em, người ấy nói có đúng không?”",
  "mn146:23.14": "“bạch Tôn Giả, không đúng”.",
  "mn146:23.15": "“Vì sao vậy?”",
  "mn146:23.16": "“bạch Tôn Giả, do duyên từng cái tương ứng mà từng cảm thọ tương ứng sinh khởi. ",
  "mn146:23.17": "Do sự diệt của từng cái duyên tương ứng mà từng cảm thọ tương ứng diệt đi”.",
  "mn146:23.18": "“Lành thay, lành thay, này các chị em. ",
  "mn146:23.19": "này các chị em, một đệ tử thánh khi thấy bằng tuệ quán đúng đắn như thật thì là như vậy. ",
  "mn146:24.1": "này các chị em, ví như một người mổ bò khéo léo hoặc đệ tử của người mổ bò, sau khi giết một con bò, dùng dao mổ bò sắc bén để cắt rời con bò mà không làm tổn hại phần thịt bên trong, không làm tổn hại phần da bên ngoài. ",
  "mn146:24.2": "Bất cứ chỗ nào có thịt dính, có gân, có dây chằng ở giữa, người ấy dùng dao mổ bò sắc bén để cắt rời, tách rời, xẻ rời, phân rời chúng. ",
  "mn146:24.3": "Sau khi cắt rời, tách rời, xẻ rời, phân rời, và rũ bỏ phần da bên ngoài, người ấy dùng chính tấm da đó để che phủ con bò và nói rằng: ",
  "mn146:24.4": "‘con bò này vẫn còn dính liền với tấm da này’;",
  "mn146:24.5": "này các chị em, người ấy nói có đúng không?”",
  "mn146:24.6": "“bạch Tôn Giả, không đúng”.",
  "mn146:24.7": "“Vì sao vậy?”",
  "mn146:24.8": "“bạch Tôn Giả, vì người mổ bò khéo léo hoặc đệ tử của người mổ bò kia, sau khi giết một con bò, dùng dao mổ bò sắc bén để cắt rời con bò mà không làm tổn hại phần thịt bên trong, không làm tổn hại phần da bên ngoài. ",
  "mn146:24.9": "Bất cứ chỗ nào có thịt dính, có gân, có dây chằng ở giữa, người ấy dùng dao mổ bò sắc bén để cắt rời, tách rời, xẻ rời, phân rời chúng. ",
  "mn146:24.10": "Sau khi cắt rời, tách rời, xẻ rời, phân rời, và rũ bỏ phần da bên ngoài, người ấy dùng chính tấm da đó để che phủ con bò, dù người ấy có nói rằng: ",
  "mn146:24.11": "‘con bò này vẫn còn dính liền với tấm da này’;",
  "mn146:24.12": "thì con bò đó đã được tách rời khỏi tấm da đó rồi”.",
  "mn146:25.1": "“này các chị em, ví dụ này được tôi đưa ra để làm rõ ý nghĩa, và đây là ý nghĩa của nó. ",
  "mn146:25.2": "này các chị em, ‘phần thịt bên trong’ là tên gọi của sáu xứ bên trong; ",
  "mn146:25.3": "‘phần da bên ngoài’ là tên gọi của sáu xứ bên ngoài; ",
  "mn146:25.4": "‘thịt dính, gân, dây chằng ở giữa’ là tên gọi của hỷ ái; ",
  "mn146:25.5": "‘dao mổ bò sắc bén’ là tên gọi của tuệ thánh; ",
  "mn146:25.6": "tuệ thánh này cắt rời, tách rời, xẻ rời, phân rời phiền não, kiết sử, trói buộc ở giữa. ",
  "mn146:26.1": "này các chị em, có bảy chi phần giác ngộ này, khi được tu tập và làm cho sung mãn, một Tỳ Kheo do sự diệt trừ các lậu hoặc mà chứng đạt và an trú trong giải thoát tâm, giải thoát tuệ không lậu hoặc, ngay trong hiện tại, tự mình chứng ngộ. ",
  "mn146:26.2": "Bảy chi phần nào?",
  "mn146:26.3": "Ở đây, này các chị em, một Tỳ Kheo tu tập biết rõ mình đang làm gì, nghĩ gì, cảm gì, nương tựa viễn ly, nương tựa ly tham, nương tựa đoạn diệt, hướng đến xả bỏ. ",
  "mn146:26.4": "Tu tập quan sát và hiểu bản chất của sự việc…pe…",
  "mn146:26.5": "tu tập siêng năng, không lười biếng…",
  "mn146:26.6": "tu tập niềm vui nhẹ nhàng trong tâm khi tu tập đúng…",
  "mn146:26.7": "tu tập thân và tâm trở nên nhẹ nhàng, thư giãn…",
  "mn146:26.8": "tu tập tâm tập trung vững vàng, không bị phân tán…",
  "mn146:26.9": "tu tập tâm quân bình, không thiên về thích hay ghét, nương tựa viễn ly, nương tựa ly tham, nương tựa đoạn diệt, hướng đến xả bỏ. ",
  "mn146:26.10": "này các chị em, đây là bảy chi phần giác ngộ, khi được tu tập và làm cho sung mãn, một Tỳ Kheo do sự diệt trừ các lậu hoặc mà chứng đạt và an trú trong giải thoát tâm, giải thoát tuệ không lậu hoặc, ngay trong hiện tại, tự mình chứng ngộ”.",
  "mn146:26.11": "Rồi Tôn giả Nandaka sau khi khuyên dạy các Tỳ Kheo Ni ấy bằng lời khuyên này, đã tiễn họ đi: ",
  "mn146:26.12": "“này các chị em, hãy đi; đã đến lúc rồi”.",
  "mn146:26.13": "Rồi các Tỳ Kheo Ni ấy, hoan hỷ và tùy hỷ với lời Tôn giả Nandaka đã nói, đứng dậy khỏi chỗ ngồi, đảnh lễ Tôn giả Nandaka, đi nhiễu bên phải, rồi đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi đứng sang một bên. Khi các Tỳ Kheo Ni ấy đứng sang một bên, Thế Tôn nói với họ: ",
  "mn146:26.14": "“Này các Tỳ Kheo Ni, hãy đi; đã đến lúc rồi”.",
  "mn146:26.15": "Rồi các Tỳ Kheo Ni ấy đảnh lễ Thế Tôn, đi nhiễu bên phải rồi rời đi. ",
  "mn146:27.1": "Rồi Thế Tôn, khi các Tỳ Kheo Ni ấy vừa rời đi không lâu, gọi các Tỳ Kheo: ",
  "mn146:27.2": "“Này các Tỳ Kheo, ví như vào ngày rằm Bố-tát, không có nhiều người nghi ngờ hay phân vân: ",
  "mn146:27.3": "‘mặt trăng có khuyết không, mặt trăng có tròn không’, mà mặt trăng chỉ là tròn; ",
  "mn146:27.4": "cũng vậy, này các Tỳ Kheo, các Tỳ Kheo Ni ấy đã hoan hỷ và hoàn toàn mãn nguyện với bài pháp của Nandaka. ",
  "mn146:27.5": "Này các Tỳ Kheo, trong số năm trăm Tỳ Kheo Ni ấy, vị Tỳ Kheo Ni cuối cùng đã là bậc nhập lưu, không còn rơi vào khổ cảnh, chắc chắn hướng đến giác ngộ”.",
  "mn146:27.6": "Thế Tôn đã nói điều này. ",
  "mn146:27.7": "Các Tỳ Kheo ấy hoan hỷ và tùy hỷ với lời Thế Tôn đã nói.",
  "mn146:27.8": "Kinh Nandakovāda chấm dứt, thứ tư."
}
window.BILARA["mn146"]["vi"]["mn146:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com Chỉnh sửa: 04/01/2026";
