window.BILARA = window.BILARA || {};
window.BILARA["mn140"] = window.BILARA["mn140"] || {};
window.BILARA["mn140"]["vi"] = {
  "mn140:0.1": "Trung Bộ Kinh 140",
  "mn140:0.2": "Kinh Chẻ Ra Từng Thể",
  "mn140:1.1": "Tôi nghe như vầy",
  "mn140:1.2": "Một thời, Đức Thế Tôn đi du hành trong xứ Magadha, rồi đến thành Rājagaha.",
  "mn140:1.3": "Ngài đi đến chỗ người thợ gốm tên Bhaggava. Đến nơi, Đức Thế Tôn nói với người thợ gốm Bhaggava rằng:",
  "mn140:2.1": "“Này Bhaggava, nếu không phiền, ta xin ở nhờ trong chỗ này một đêm.”",
  "mn140:2.2": "“Bạch Ngài, con không thấy phiền.",
  "mn140:2.3": "Nhưng ở đây có một người đã xuất gia bỏ nhà đi sống không nhà, đến ở trước rồi.",
  "mn140:2.4": "Nếu vị ấy bằng lòng, thì xin Ngài cứ ở cho thoải mái.”",
  "mn140:3.1": "Lúc ấy có một người con nhà tốt tên là Pukkusāti. Vì lòng tin hướng về Đức Thế Tôn, ông đã rời nhà, sống đời không nhà.",
  "mn140:3.2": "Ông là người đến ở trong lò gốm ấy trước.",
  "mn140:3.3": "Rồi Đức Thế Tôn đi đến chỗ Tỳ Kheo Pukkusāti. Đến nơi, Ngài nói với Tỳ Kheo Pukkusāti rằng:",
  "mn140:3.4": "“Này Tỳ Kheo, nếu không phiền, ta xin ở nhờ trong chỗ này một đêm.”",
  "mn140:3.5": "“Này hiền giả, lò gốm này rộng rãi.",
  "mn140:3.6": "Xin hiền giả cứ ở cho thoải mái.”",
  "mn140:4.1": "Rồi Đức Thế Tôn bước vào lò gốm, dọn một chỗ ngồi bằng cỏ ở một bên, ngồi xuống, xếp chân, giữ thân ngay thẳng, đặt sự nhớ biết rõ ở trước mặt.",
  "mn140:4.2": "Rồi Đức Thế Tôn ngồi suốt phần lớn đêm.",
  "mn140:4.3": "Tỳ Kheo Pukkusāti cũng ngồi suốt phần lớn đêm.",
  "mn140:4.4": "Rồi Đức Thế Tôn nghĩ rằng:",
  "mn140:4.5": "“Người con nhà tốt này đi đứng thật dễ mến.",
  "mn140:4.6": "Hay là ta hỏi thử.”",
  "mn140:4.7": "Rồi Đức Thế Tôn nói với Tỳ Kheo Pukkusāti rằng:",
  "mn140:5.1": "“Này Tỳ Kheo, ông vì ai mà rời nhà đi sống đời không nhà? Ai là thầy của ông? Ông ưa thích lời dạy của ai?”",
  "mn140:5.2": "“Này hiền giả, có vị sa môn Gotama, người con của dòng Sakya, đã rời dòng họ Sakya mà đi sống đời không nhà.",
  "mn140:5.3": "Về Đức Thế Tôn Gotama ấy, tiếng tốt đẹp này đã lan rộng rằng:",
  "mn140:5.4": "‘Đó là Đức Thế Tôn, bậc đáng được cúng dường, tự mình hiểu trọn vẹn, đủ đầy hiểu biết và nết sống, khéo đi đến, biết rõ đời, người dẫn dắt bậc nhất cho những ai cần được rèn luyện, thầy của chư thiên và loài người, bậc Giác Ngộ, Đức Thế Tôn.’",
  "mn140:5.5": "Vì Đức Thế Tôn ấy mà tôi đã rời nhà đi sống đời không nhà.",
  "mn140:5.6": "Ngài ấy là thầy của tôi.",
  "mn140:5.7": "Tôi ưa thích lời dạy của Đức Thế Tôn ấy.”",
  "mn140:5.8": "“Nhưng này Tỳ Kheo, hiện nay Đức Thế Tôn, bậc đáng được cúng dường, bậc tự mình hiểu trọn vẹn, đang ở đâu?”",
  "mn140:5.9": "“Này hiền giả, ở các xứ phía bắc có một thành tên là Sāvatthi.",
  "mn140:5.10": "Ở đó, hiện nay Đức Thế Tôn đang ở, bậc đáng kính, tự mình giác ngộ trọn vẹn.”",
  "mn140:5.11": "“Nhưng này Tỳ Kheo, thầy đã từng thấy Đức Thế Tôn ấy chưa?",
  "mn140:5.12": "Và nếu thấy, thầy có nhận ra Ngài không?”",
  "mn140:5.13": "“Thưa hiền giả, tôi chưa từng thấy Đức Thế Tôn ấy.",
  "mn140:5.14": "Và dù có thấy, tôi cũng không nhận ra Ngài.”",
  "mn140:6.1": "Bấy giờ, Đức Thế Tôn nghĩ rằng:",
  "mn140:6.2": "“Người con trai nhà lành này đã đi xuất gia vì Ta.",
  "mn140:6.3": "Hay là Ta giảng lời dạy cho thầy ấy.”",
  "mn140:6.4": "Rồi Đức Thế Tôn gọi Ngài Pukkusāti:",
  "mn140:6.5": "“Này Tỳ Kheo, Ta sẽ giảng lời dạy cho thầy.",
  "mn140:6.6": "Hãy nghe đây, khéo để tâm vào, Ta sẽ nói.”",
  "mn140:6.7": "“Vâng, hiền giả,” Ngài Pukkusāti đáp lời Đức Thế Tôn.",
  "mn140:6.8": "Đức Thế Tôn nói như sau:",
  "mn140:7.1": "“Này Tỳ Kheo, con người này gồm sáu phần, có sáu chỗ tiếp xúc, có mười tám cách tâm tìm tới, có bốn chỗ nương đứng.",
  "mn140:7.2": "Khi đứng vững ở đó thì các nghĩ tưởng ‘ta là’ không còn chạy ra nữa; khi các nghĩ tưởng ‘ta là’ không còn chạy ra, thì người lặng yên được gọi là bậc an ổn.",
  "mn140:7.3": "Người ấy chớ lơ là sự hiểu rõ, hãy giữ gìn điều thật, hãy làm lớn thêm lòng buông xả, và chỉ nên học sự yên lặng.”",
  "mn140:7.4": "Đó là phần nêu gọn về cách chia rõ các phần.”",
  "mn140:8.1": "“Này Tỳ Kheo, con người này gồm sáu phần” —",
  "mn140:8.2": "điều ấy đã được nói ra. Dựa vào đâu mà nói như vậy?",
  "mn140:8.3": "Này Tỳ Kheo, có sáu phần này —",
  "mn140:8.4": "phần đất, phần nước, phần lửa, phần gió, phần trống rỗng, phần nhận biết.",
  "mn140:8.5": "“Này Tỳ Kheo, con người này gồm sáu phần” —",
  "mn140:8.6": "điều đã nói ấy là dựa vào điều này mà nói.",
  "mn140:9.1": "“Này Tỳ Kheo, con người này có sáu chỗ tiếp xúc” —",
  "mn140:9.2": "điều ấy đã được nói ra. Dựa vào đâu mà nói như vậy?",
  "mn140:9.3": "Chỗ tiếp xúc do mắt, chỗ tiếp xúc do tai, chỗ tiếp xúc do mũi, chỗ tiếp xúc do lưỡi, chỗ tiếp xúc do thân, chỗ tiếp xúc do ý.",
  "mn140:9.4": "“Này Tỳ Kheo, con người này có sáu chỗ tiếp xúc” —",
  "mn140:9.5": "điều đã nói ấy là dựa vào điều này mà nói.",
  "mn140:10.1": "“Này Tỳ Kheo, con người này có mười tám cách tâm tìm tới” —",
  "mn140:10.2": "Đó là điều đã được nói. Nói dựa vào đâu?",
  "mn140:10.3": "Do mắt thấy hình sắc, người ấy để tâm chạy theo hình sắc làm chỗ cho niềm vui, để tâm chạy theo hình sắc làm chỗ cho nỗi buồn, để tâm chạy theo hình sắc làm chỗ cho sự bình thản;",
  "mn140:10.4": "do tai nghe tiếng …",
  "mn140:10.5": "do mũi ngửi mùi …",
  "mn140:10.6": "do lưỡi nếm vị …",
  "mn140:10.7": "do thân chạm xúc chạm …",
  "mn140:10.8": "do ý biết điều được nhận ra, người ấy để tâm chạy theo điều được nhận ra làm chỗ cho niềm vui, để tâm chạy theo điều được nhận ra làm chỗ cho nỗi buồn, để tâm chạy theo điều được nhận ra làm chỗ cho sự bình thản—",
  "mn140:10.9": "như vậy là sáu cách tâm chạy theo niềm vui, sáu cách tâm chạy theo nỗi buồn, sáu cách tâm chạy theo sự bình thản.",
  "mn140:10.10": "‘Này Tỳ Kheo, con người này có mười tám cách tâm chạy theo’—",
  "mn140:10.11": "điều được nói như vậy là nói dựa vào điều này.",
  "mn140:11.1": "‘Này Tỳ Kheo, con người này đứng vững trên bốn nền’—",
  "mn140:11.2": "đó là điều đã được nói. Nói dựa vào đâu?",
  "mn140:11.3": "Đứng vững trên sự hiểu rõ, đứng vững trên sự thật, đứng vững trên lòng buông xả, đứng vững trên sự lắng yên.",
  "mn140:11.4": "‘Này Tỳ Kheo, con người này đứng vững trên bốn nền’—",
  "mn140:11.5": "điều được nói như vậy là nói dựa vào điều này.",
  "mn140:12.1": "‘Người ấy chớ lơ là trong sự hiểu rõ, hãy giữ gìn sự thật, hãy làm cho lòng buông xả lớn lên, và chỉ nên học sự yên lặng’—",
  "mn140:12.2": "đó là điều đã được nói. Nói dựa vào đâu?",
  "mn140:13.1": "Và này Tỳ Kheo, thế nào là không lơ là trong sự hiểu rõ?",
  "mn140:13.2": "Này Tỳ Kheo, có sáu thể tính này—",
  "mn140:13.3": "thể cứng, thể nước, thể nóng, thể động, thể trống rỗng, thể biết.",
  "mn140:14.1": "Và này Tỳ Kheo, thế nào là thể cứng?",
  "mn140:14.2": "Thể cứng có thể là bên trong, có thể là bên ngoài.",
  "mn140:14.3": "Và này Tỳ Kheo, thế nào là thể cứng bên trong?",
  "mn140:14.4": "Những gì ở trong thân mình, thuộc riêng thân mình, cứng, thô, bị nắm giữ, như là—",
  "mn140:14.5": "tóc, lông, móng, răng, da, thịt, gân, xương, tủy xương, thận, tim, gan, màng ngăn, lá lách, phổi, ruột, màng ruột, đồ ăn trong bụng, phân; hay bất cứ thứ gì khác ở trong thân mình, thuộc riêng thân mình, cứng, thô, bị nắm giữ—",
  "mn140:14.6": "đó được gọi là thể cứng bên trong, này Tỳ Kheo.",
  "mn140:14.7": "Thể cứng bên trong và thể cứng bên ngoài, cả hai chỉ là thể cứng mà thôi.",
  "mn140:14.8": "‘Cái ấy không phải của tôi, tôi không phải là cái ấy, cái ấy không phải là mình tôi’—cần thấy đúng như thật như vậy bằng sự hiểu rõ đúng đắn.",
  "mn140:14.9": "Khi thấy đúng như thật như vậy bằng sự hiểu rõ đúng đắn, người ấy chán ngán thể cứng, làm cho lòng mình phai nhạt đối với thể cứng.",
  "mn140:15.1": "Và này Tỳ Kheo, thế nào là thể nước?",
  "mn140:15.2": "Yếu tố nước có thể là bên trong, cũng có thể là bên ngoài.",
  "mn140:15.3": "Này Tỳ Kheo, thế nào là yếu tố nước bên trong?",
  "mn140:15.4": "Cái gì ở bên trong, thuộc riêng nơi mình, là nước, mang tính nước, được nắm giữ, như là—",
  "mn140:15.5": "mật, đờm, mủ, máu, mồ hôi, mỡ, nước mắt, mỡ đặc, nước miếng, nước mũi, nước khớp, nước tiểu, hay bất cứ thứ gì khác ở bên trong, thuộc riêng nơi mình, là nước, mang tính nước, được nắm giữ—",
  "mn140:15.6": "đó được gọi là yếu tố nước bên trong, này Tỳ Kheo.",
  "mn140:15.7": "Nhưng yếu tố nước bên trong và yếu tố nước bên ngoài thì chỉ là yếu tố nước mà thôi.",
  "mn140:15.8": "Cần thấy đúng như thật điều ấy bằng sự hiểu rõ đúng đắn rằng: ‘Cái ấy không phải của tôi, tôi không phải là cái ấy, cái ấy không phải là mình’.",
  "mn140:15.9": "Thấy đúng như thật điều ấy bằng sự hiểu rõ đúng đắn như vậy, vị ấy chán lìa yếu tố nước, làm cho lòng mình phai nhạt đối với yếu tố nước.",
  "mn140:16.1": "Này Tỳ Kheo, thế nào là yếu tố lửa?",
  "mn140:16.2": "Yếu tố lửa có thể là bên trong, cũng có thể là bên ngoài.",
  "mn140:16.3": "Này Tỳ Kheo, thế nào là yếu tố lửa bên trong?",
  "mn140:16.4": "Cái gì ở bên trong, thuộc riêng nơi mình, là lửa, mang tính lửa, được nắm giữ, như là—",
  "mn140:16.5": "cái nhờ đó thân được làm ấm, nhờ đó bị già đi, nhờ đó bị đốt nóng, và nhờ đó đồ đã ăn, đã uống, đã nhai, đã nếm được tiêu hóa đúng cách, hay bất cứ thứ gì khác ở bên trong, thuộc riêng nơi mình, là lửa, mang tính lửa, được nắm giữ—",
  "mn140:16.6": "đó được gọi là yếu tố lửa bên trong, này Tỳ Kheo.",
  "mn140:16.7": "Nhưng yếu tố lửa bên trong và yếu tố lửa bên ngoài thì chỉ là yếu tố lửa mà thôi.",
  "mn140:16.8": "Cần thấy đúng như thật điều ấy bằng sự hiểu rõ đúng đắn rằng: ‘Cái ấy không phải của tôi, tôi không phải là cái ấy, cái ấy không phải là mình’.",
  "mn140:16.9": "Thấy đúng như thật điều ấy bằng sự hiểu rõ đúng đắn như vậy, vị ấy chán lìa yếu tố lửa, làm cho lòng mình phai nhạt đối với yếu tố lửa.",
  "mn140:17.1": "Này Tỳ Kheo, thế nào là yếu tố gió?",
  "mn140:17.2": "Yếu tố gió có thể là bên trong, cũng có thể là bên ngoài.",
  "mn140:17.3": "Này Tỳ Kheo, thế nào là yếu tố gió bên trong?",
  "mn140:17.4": "Cái gì ở bên trong, thuộc riêng nơi mình, là gió, mang tính gió, được nắm giữ, như là—",
  "mn140:17.5": "gió đi lên, gió đi xuống, gió ở trong bụng, gió ở trong ruột, gió chạy theo khắp tay chân, hơi thở vào, hơi thở ra; hay bất cứ thứ gì khác ở bên trong, thuộc riêng nơi mình, là gió, mang tính gió, được nắm giữ—",
  "mn140:17.6": "đó được gọi là yếu tố gió bên trong, này Tỳ Kheo.",
  "mn140:17.7": "Nhưng yếu tố gió bên trong và yếu tố gió bên ngoài thì chỉ là yếu tố gió mà thôi.",
  "mn140:17.8": "Cần thấy đúng như thật điều ấy bằng sự hiểu rõ đúng đắn rằng: ‘Cái ấy không phải của tôi, tôi không phải là cái ấy, cái ấy không phải là mình’.",
  "mn140:17.9": "Thấy đúng như thật điều ấy bằng sự hiểu rõ đúng đắn như vậy, vị ấy chán lìa yếu tố gió, làm cho lòng mình phai nhạt đối với yếu tố gió.",
  "mn140:18.1": "Này Tỳ Kheo, thế nào là yếu tố khoảng trống?",
  "mn140:18.2": "Yếu tố khoảng trống có thể là bên trong, cũng có thể là bên ngoài.",
  "mn140:18.3": "Này Tỳ Kheo, thế nào là yếu tố khoảng trống bên trong?",
  "mn140:18.4": "Cái gì ở bên trong, thuộc riêng nơi mình, là khoảng trống, mang tính khoảng trống, được nắm giữ, như là—",
  "mn140:18.5": "lỗ tai, lỗ mũi, cửa miệng, chỗ mà đồ ăn thức uống, thứ nhai, thứ nếm được nuốt vào, chỗ mà đồ ăn thức uống, thứ nhai, thứ nếm ấy nằm lại, chỗ mà đồ ăn thức uống, thứ nhai, thứ nếm ấy đi ra ở phần dưới, hay bất cứ khoảng trống nào khác ở bên trong thân mình, riêng nơi mình, là khoảng không, chỗ có khoảng không, chỗ rỗng, chỗ có lỗ hở, không bị thịt và máu lấp kín, thuộc về thân này—",
  "mn140:18.6": "này Tỳ Kheo, đó được gọi là phần khoảng không ở bên trong.",
  "mn140:18.7": "Nhưng phần khoảng không ở bên trong và phần khoảng không ở bên ngoài thì đều chỉ là khoảng không mà thôi.",
  "mn140:18.8": "Cần thấy đúng như thật bằng sự hiểu rõ đúng đắn rằng: ‘Cái đó không phải của tôi, tôi không phải là cái đó, cái đó không phải là mình tôi’.",
  "mn140:18.9": "Thấy đúng như thật như vậy bằng sự hiểu rõ đúng đắn, vị ấy chán lìa phần khoảng không, làm cho lòng mình nhạt đi đối với phần khoảng không.",
  "mn140:19.1": "Rồi sau đó chỉ còn lại sự nhận biết, trong sạch, sáng trong.",
  "mn140:19.2": "Và với sự nhận biết ấy, người ấy biết gì?",
  "mn140:19.3": "Người ấy biết: ‘dễ chịu’, cũng biết: ‘đau đớn’, cũng biết: ‘không đau đớn không dễ chịu’.",
  "mn140:19.4": "Này Tỳ Kheo, do nương sự đụng chạm đưa đến dễ chịu mà cảm giác dễ chịu sinh ra.",
  "mn140:19.5": "Khi cảm nhận cảm giác dễ chịu, vị ấy biết: ‘Tôi đang cảm nhận cảm giác dễ chịu’.",
  "mn140:19.6": "Vị ấy biết: ‘Khi sự đụng chạm đưa đến dễ chịu ấy dứt đi, thì cảm giác dễ chịu sinh ra do nương sự đụng chạm đưa đến dễ chịu ấy cũng dứt đi, cũng lắng xuống’.",
  "mn140:19.7": "Này Tỳ Kheo, do nương sự đụng chạm đưa đến đau đớn mà cảm giác đau đớn sinh ra.",
  "mn140:19.8": "Khi cảm nhận cảm giác đau đớn, vị ấy biết: ‘Tôi đang cảm nhận cảm giác đau đớn’.",
  "mn140:19.9": "Vị ấy biết: ‘Khi sự đụng chạm đưa đến đau đớn ấy dứt đi, thì cảm giác đau đớn sinh ra do nương sự đụng chạm đưa đến đau đớn ấy cũng dứt đi, cũng lắng xuống’.",
  "mn140:19.10": "Này Tỳ Kheo, do nương sự đụng chạm không đưa đến đau đớn cũng không đưa đến dễ chịu mà cảm giác không đau đớn không dễ chịu sinh ra.",
  "mn140:19.11": "Khi cảm nhận cảm giác không đau đớn không dễ chịu, vị ấy biết: ‘Tôi đang cảm nhận cảm giác không đau đớn không dễ chịu’.",
  "mn140:19.12": "Vị ấy biết: ‘Khi sự đụng chạm không đưa đến đau đớn cũng không đưa đến dễ chịu ấy dứt đi, thì cảm giác không đau đớn không dễ chịu sinh ra do nương sự đụng chạm ấy cũng dứt đi, cũng lắng xuống’.",
  "mn140:19.13": "Ví như, này Tỳ Kheo, do cọ xát và ghép hai thanh củi lại với nhau mà hơi nóng sinh ra, lửa bùng lên; khi hai thanh củi ấy tách rời, bị bỏ ra, thì hơi nóng sinh ra do đó cũng dứt đi, cũng lắng xuống;",
  "mn140:19.14": "cũng vậy, này Tỳ Kheo, do nương sự đụng chạm đưa đến dễ chịu mà cảm giác dễ chịu sinh ra.",
  "mn140:19.15": "Khi cảm nhận cảm giác dễ chịu, vị ấy biết: ‘Tôi đang cảm nhận cảm giác dễ chịu’.",
  "mn140:19.16": "Vị ấy biết: ‘Khi sự đụng chạm đưa đến dễ chịu ấy dứt đi, thì cảm giác dễ chịu sinh ra do nương sự đụng chạm đưa đến dễ chịu ấy cũng dứt đi, cũng lắng xuống’.",
  "mn140:19.17": "Này Tỳ Kheo, do nương sự đụng chạm đưa đến đau đớn mà cảm giác đau đớn sinh ra.",
  "mn140:19.18": "Khi cảm nhận cảm giác đau đớn, vị ấy biết: ‘Tôi đang cảm nhận cảm giác đau đớn’.",
  "mn140:19.19": "Vị ấy biết: ‘Khi sự đụng chạm đưa đến đau đớn ấy dứt đi, thì cảm giác đau đớn sinh ra do nương sự đụng chạm đưa đến đau đớn ấy cũng dứt đi, cũng lắng xuống’.",
  "mn140:19.20": "Này Tỳ Kheo, do nương sự đụng chạm không đưa đến đau đớn cũng không đưa đến dễ chịu mà cảm giác không đau đớn không dễ chịu sinh ra.",
  "mn140:19.21": "Khi cảm nhận cảm giác không đau đớn không dễ chịu, vị ấy biết: ‘Tôi đang cảm nhận cảm giác không đau đớn không dễ chịu’.",
  "mn140:19.22": "Vị ấy biết: ‘Khi sự đụng chạm không đưa đến đau đớn cũng không đưa đến dễ chịu ấy dứt đi, thì cảm giác không đau đớn không dễ chịu sinh ra do nương sự đụng chạm ấy cũng dứt đi, cũng lắng xuống’.",
  "mn140:20.1": "Rồi sau đó chỉ còn lại sự bình thản, trong sạch, sáng trong, mềm mại, dễ dùng, và sáng rỡ.",
  "mn140:20.2": "Ví như, này Tỳ Kheo, một người thợ vàng khéo tay hay người học việc của thợ vàng nhóm lò, nhóm lò xong thì trét miệng lò, trét miệng lò xong thì dùng kẹp gắp vàng bỏ vào miệng lò, rồi khi thì thổi, khi thì rưới nước, khi thì chỉ nhìn; vàng ấy trở nên được nung khéo, được thổi khéo, được lấy ra chất dơ, mềm mại, dễ dùng, sáng rỡ. Khi muốn làm món đồ đeo nào—dù là miếng dẹp, hay vòng tai, hay đồ đeo cổ, hay chuỗi vàng—thì vàng ấy đều dùng được đúng việc ấy;",
  "mn140:20.3": "cũng vậy, này Tỳ Kheo, rồi sau đó chỉ còn lại sự bình thản, trong sạch, sáng trong, mềm mại, dễ dùng, và sáng rỡ.",
  "mn140:21.1": "Vị ấy hiểu rõ như vầy:",
  "mn140:21.2": "‘Nếu ta hướng sự bình thản này, trong sạch như vậy, sáng trong như vậy, đến cảnh không bờ mé của hư không, và làm cho tâm lớn lên theo đó,",
  "mn140:21.3": "thì sự bình thản này của ta, nương vào đó, bám vào đó, sẽ còn kéo dài rất lâu. ",
  "mn140:21.4": "Nếu ta hướng sự bình thản này, trong sạch như vậy, sáng trong như vậy, đến cảnh không bờ mé của sự nhận biết, và làm cho tâm lớn lên theo đó,",
  "mn140:21.5": "thì sự bình thản này của ta, nương vào đó, bám vào đó, sẽ còn kéo dài rất lâu. ",
  "mn140:21.6": "Nếu ta hướng sự bình thản này, trong sạch như vậy, sáng trong như vậy, đến cảnh không có gì cả, và làm cho tâm lớn lên theo đó,",
  "mn140:21.7": "thì sự bình thản này của ta, nương vào đó, bám vào đó, sẽ còn kéo dài rất lâu. ",
  "mn140:21.8": "Nếu ta hướng sự bình thản này, trong sạch như vậy, sáng trong như vậy, đến cảnh không phải còn tưởng mà cũng không phải không còn tưởng, và làm cho tâm lớn lên theo đó,",
  "mn140:21.9": "thì sự bình thản này của ta, nương vào đó, bám vào đó, sẽ còn kéo dài rất lâu.’",
  "mn140:22.1": "Vị ấy hiểu rõ như vầy:",
  "mn140:22.2": "‘Nếu ta hướng sự bình thản này, trong sạch như vậy, sáng trong như vậy, đến cảnh không bờ mé của hư không, và làm cho tâm lớn lên theo đó,",
  "mn140:22.3": "thì đó là thứ do tạo thành. ",
  "mn140:22.4": "Nếu ta hướng sự bình thản này, trong sạch như vậy, sáng trong như vậy, đến cảnh không bờ mé của sự nhận biết, và làm cho tâm lớn lên theo đó,",
  "mn140:22.5": "thì đó là thứ do tạo thành. ",
  "mn140:22.6": "Nếu ta hướng sự bình thản này, trong sạch như vậy, sáng trong như vậy, đến cảnh không có gì cả, và làm cho tâm lớn lên theo đó,",
  "mn140:22.7": "thì đó là thứ do tạo thành. ",
  "mn140:22.8": "Nếu ta hướng sự bình thản này, trong sạch như vậy, sáng trong như vậy, đến cảnh không phải còn tưởng mà cũng không phải không còn tưởng, và làm cho tâm lớn lên theo đó,",
  "mn140:22.9": "thì đó là thứ do tạo thành.’",
  "mn140:22.10": "Vị ấy không tạo tác thêm, không khởi ý thêm, để đi đến còn hiện hữu hay không còn hiện hữu.",
  "mn140:22.11": "Vì không tạo tác thêm, không khởi ý thêm, để đi đến còn hiện hữu hay không còn hiện hữu, vị ấy không bám lấy gì ở đời,",
  "mn140:22.12": "không bám lấy nên không run sợ; không run sợ nên tự mình lặng tắt hẳn.",
  "mn140:22.13": "Vị ấy hiểu rõ: ‘Sanh đã dứt, đời sống phạm hạnh đã sống xong, việc cần làm đã làm xong, không còn trở lui trạng thái này nữa.’",
  "mn140:23.1": "Khi cảm nhận sự dễ chịu, vị ấy hiểu rõ: ‘Nó là không bền’; hiểu rõ: ‘không dính chặt vào nó’; hiểu rõ: ‘không vui thích trong nó’.",
  "mn140:23.2": "Khi cảm nhận sự đau đớn, vị ấy hiểu rõ: ‘Nó là không bền’; hiểu rõ: ‘không dính chặt vào nó’; hiểu rõ: ‘không vui thích trong nó’.",
  "mn140:23.3": "Khi cảm nhận cảm giác không đau không dễ chịu, vị ấy hiểu rõ: ‘Nó là không bền’; hiểu rõ: ‘không dính chặt vào nó’; hiểu rõ: ‘không vui thích trong nó’.",
  "mn140:24.1": "Khi cảm nhận sự dễ chịu, vị ấy cảm nhận nó trong trạng thái không bị trói buộc;",
  "mn140:24.2": "khi cảm nhận sự đau đớn, vị ấy cảm nhận nó trong trạng thái không bị trói buộc;",
  "mn140:24.3": "khi cảm nhận cảm giác không đau không dễ chịu, vị ấy cảm nhận nó trong trạng thái không bị trói buộc.",
  "mn140:24.4": "Khi cảm nhận cảm giác chỉ còn đến mức thân này, vị ấy hiểu rõ: ‘Ta đang cảm nhận cảm giác chỉ còn đến mức thân này’; khi cảm nhận cảm giác chỉ còn đến mức mạng sống này, vị ấy hiểu rõ: ‘Ta đang cảm nhận cảm giác chỉ còn đến mức mạng sống này’,",
  "mn140:24.5": "và hiểu rõ: ‘Khi thân tan rã, sau khi chết, khi mạng sống chấm dứt, ngay tại đây mọi cảm giác, vì không còn được vui thích, sẽ lắng hẳn xuống.’",
  "mn140:24.6": "Ví như, này Tỳ Kheo, đèn dầu cháy nhờ dầu và nhờ tim đèn;",
  "mn140:24.7": "khi chính dầu ấy và tim đèn ấy cạn hết, lại không được châm thêm, không còn gì nuôi, thì nó tắt.",
  "mn140:24.8": "Cũng vậy, này Tỳ Kheo, khi cảm nhận cảm giác chỉ còn đến mức thân, vị ấy biết rõ: ‘Ta đang cảm nhận cảm giác chỉ còn đến mức thân’; khi cảm nhận cảm giác chỉ còn đến mức mạng sống, vị ấy biết rõ: ‘Ta đang cảm nhận cảm giác chỉ còn đến mức mạng sống’.",
  "mn140:24.9": "Vị ấy biết rõ: ‘Khi thân tan rã, sau khi chết, khi mạng sống dứt hẳn, ngay tại đây mọi cảm giác được cảm nhận, vì không còn ưa thích nữa, sẽ lắng nguội’.",
  "mn140:25.1": "Vì vậy, Tỳ Kheo như vậy là người có chỗ nương tựa cao nhất này của sự hiểu rõ.",
  "mn140:25.2": "Vì, này Tỳ Kheo, đây là sự hiểu rõ cao nhất của bậc thánh, đó là—",
  "mn140:25.3": "sự biết rõ về chỗ chấm dứt mọi khổ đau.",
  "mn140:26.1": "Sự giải thoát ấy của vị ấy đứng vững trên sự thật, không lay chuyển.",
  "mn140:26.2": "Vì, này Tỳ Kheo, cái gì có tính dối trá thì là giả, còn cái gì không có tính dối trá, tức là Niết-bàn, thì là thật.",
  "mn140:26.3": "Vì vậy, Tỳ Kheo như vậy là người có chỗ nương tựa cao nhất này của sự thật.",
  "mn140:26.4": "Vì, này Tỳ Kheo, đây là sự thật cao nhất của bậc thánh, đó là—",
  "mn140:26.5": "Niết-bàn, cái không có tính dối trá.",
  "mn140:27.1": "Hơn nữa, trước kia, khi còn chưa thấy rõ, vị ấy đã gom chứa và nắm giữ các thứ tạo nên đời sống.",
  "mn140:27.2": "Nay chúng đã được dứt bỏ, bị chặt tận gốc, như gốc cây thốt nốt bị chém đứt, không còn thành ra nữa, về sau không thể sinh lên lại.",
  "mn140:27.3": "Vì vậy, Tỳ Kheo như vậy là người có chỗ nương tựa cao nhất này của sự buông ra.",
  "mn140:27.4": "Vì, này Tỳ Kheo, đây là sự buông ra cao nhất của bậc thánh, đó là—",
  "mn140:27.5": "thả hết mọi thứ tạo nên đời sống.",
  "mn140:28.1": "Hơn nữa, trước kia, khi còn chưa thấy rõ, vị ấy có lòng ham muốn, có sự thích muốn, có sự vướng mắc.",
  "mn140:28.2": "Nay nó đã được dứt bỏ, bị chặt tận gốc, như gốc cây thốt nốt bị chém đứt, không còn thành ra nữa, về sau không thể sinh lên lại.",
  "mn140:28.3": "Hơn nữa, trước kia, khi còn chưa thấy rõ, vị ấy có sự bực tức, có lòng ghét, có sự giận dữ trọn vẹn.",
  "mn140:28.4": "Nay nó đã được dứt bỏ, bị chặt tận gốc, như gốc cây thốt nốt bị chém đứt, không còn thành ra nữa, về sau không thể sinh lên lại.",
  "mn140:28.5": "Hơn nữa, trước kia, khi còn chưa thấy rõ, vị ấy có sự không biết, có sự mù mờ.",
  "mn140:28.6": "Nay nó đã được dứt bỏ, bị chặt tận gốc, như gốc cây thốt nốt bị chém đứt, không còn thành ra nữa, về sau không thể sinh lên lại.",
  "mn140:28.7": "Vì vậy, Tỳ Kheo như vậy là người có chỗ nương tựa cao nhất này của sự lắng yên.",
  "mn140:28.8": "Vì, này Tỳ Kheo, đây là sự lắng yên cao nhất của bậc thánh, đó là—",
  "mn140:28.9": "sự lắng yên của tham muốn, ghét giận và mê mờ.",
  "mn140:29.1": "‘Chớ xem nhẹ sự hiểu rõ, hãy giữ gìn sự thật, hãy làm lớn mạnh sự buông ra, và chỉ nên học sự yên lặng’—",
  "mn140:29.2": "điều đã được nói như vậy là nói dựa vào điều này.",
  "mn140:30.1": "‘Ở đâu các dòng “ta nghĩ mình là” không còn chảy nữa, và khi các dòng “ta nghĩ mình là” không còn chảy nữa, thì người lặng sáng được gọi là người yên lặng’—",
  "mn140:30.2": "điều này cũng đã được nói như vậy. Điều ấy được nói dựa vào đâu?",
  "mn140:31.1": "Này Tỳ Kheo, nghĩ rằng ‘ta là’ là một lối nghĩ chấp, nghĩ rằng ‘đây là ta’ là một lối nghĩ chấp, nghĩ rằng ‘ta sẽ còn’ là một lối nghĩ chấp, nghĩ rằng ‘ta sẽ không còn’ là một lối nghĩ chấp, nghĩ rằng ‘ta sẽ còn có thân hình’ là một lối nghĩ chấp, nghĩ rằng ‘ta sẽ còn không có thân hình’ là một lối nghĩ chấp, nghĩ rằng ‘ta sẽ còn có biết’ là một lối nghĩ chấp, nghĩ rằng ‘ta sẽ còn không biết’ là một lối nghĩ chấp, nghĩ rằng ‘ta sẽ còn ở trạng thái không phải có biết mà cũng không phải không biết’ là một lối nghĩ chấp.",
  "mn140:31.2": "Này Tỳ Kheo, lối nghĩ chấp là bệnh, lối nghĩ chấp là mụt nhọt, lối nghĩ chấp là mũi tên đâm.",
  "mn140:31.3": "Này Tỳ Kheo, chỉ khi vượt qua hết mọi lối nghĩ chấp ấy thì mới được gọi là bậc lặng yên.",
  "mn140:31.4": "Nhưng này Tỳ Kheo, bậc lặng yên thì không sinh ra, không già đi, không chết, không lay động, không mong cầu.",
  "mn140:31.5": "Vì vị ấy không còn gì khiến mình phải sinh ra. Không sinh ra thì sao già đi được? Không già đi thì sao chết được? Không chết thì sao lay động được? Không lay động thì còn mong cầu gì nữa?",
  "mn140:32.1": "‘Ở đâu các dòng chảy của lối nghĩ chấp không còn chạy nữa, thì khi các dòng chảy của lối nghĩ chấp không còn chạy nữa, người ấy được gọi là bậc lặng yên’—",
  "mn140:32.2": "điều đã được nói như vậy là nói dựa vào điều này.",
  "mn140:32.3": "Này Tỳ Kheo, hãy ghi nhớ cách chia rõ sáu phần này mà Ta đã nói gọn cho ông.”",
  "mn140:33.1": "Bấy giờ Tôn giả Pukkusāti nghĩ rằng:",
  "mn140:33.2": "“Thầy của tôi đã đến rồi, bậc khéo đi đã đến rồi, bậc tự mình biết trọn vẹn đã đến rồi.” Rồi vị ấy đứng dậy khỏi chỗ ngồi, vắt y qua một vai, cúi đầu sát dưới chân Đức Thế Tôn và thưa rằng:",
  "mn140:33.3": "“Bạch Ngài, lỗi ấy đã vượt qua con, vì con dại, vì con mờ tối, vì con không khéo, nên con đã nghĩ rằng có thể gọi Đức Thế Tôn bằng lời xưng hô ngang hàng.",
  "mn140:33.4": "Bạch Ngài, xin Đức Thế Tôn nhận cho con lỗi ấy đúng là lỗi, để từ nay con biết giữ mình.”",
  "mn140:33.5": "“Đúng vậy, này Tỳ Kheo, lỗi ấy đã vượt qua ông, vì ông dại, vì ông mờ tối, vì ông không khéo, nên ông đã nghĩ rằng có thể gọi Ta bằng lời xưng hô ngang hàng.",
  "mn140:33.6": "Nhưng này Tỳ Kheo, vì ông thấy lỗi là lỗi và sửa lại cho đúng lẽ, nên Ta nhận lỗi ấy của ông.",
  "mn140:33.7": "Này Tỳ Kheo, đó là lớn lên trong nếp sống của bậc cao quý: thấy lỗi là lỗi, sửa lại cho đúng lẽ, rồi từ nay biết giữ mình.”",
  "mn140:34.1": "“Bạch Ngài, mong con được sống đời xuất gia trọn vẹn gần Đức Thế Tôn.”",
  "mn140:34.2": "“Nhưng này Tỳ Kheo, ông đã đủ bát và y chưa?”",
  "mn140:34.3": "“Bạch Ngài, con chưa đủ bát và y.”",
  "mn140:34.4": "“Này Tỳ Kheo, các Đức Như Lai không cho sống đời xuất gia trọn vẹn khi chưa đủ bát và y.”",
  "mn140:35.1": "Rồi Tôn giả Pukkusāti vui mừng đón nhận lời Đức Thế Tôn dạy, đứng dậy khỏi chỗ ngồi, kính lễ Đức Thế Tôn, đi quanh bên phải rồi ra đi tìm bát và y.",
  "mn140:35.2": "Trong khi Tôn giả Pukkusāti đang đi tìm bát và y, một con bò cái đang húc loạn đã làm vị ấy mất mạng.",
  "mn140:36.1": "Bấy giờ nhiều Tỳ Kheo đi đến chỗ Đức Thế Tôn, đến nơi, kính lễ Đức Thế Tôn rồi ngồi xuống một bên. Khi đã ngồi xuống một bên, các Tỳ Kheo ấy thưa với Đức Thế Tôn:",
  "mn140:36.2": "“Bạch Ngài, người con trai trong một nhà tốt tên là Pukkusāti, đã được Đức Thế Tôn dạy vắn tắt, nay đã qua đời.",
  "mn140:36.3": "Vị ấy đi về đâu, sẽ ra sao?”",
  "mn140:36.4": "“Này các Tỳ Kheo, người con trai trong một nhà tốt Pukkusāti là người sáng dạ, đã sống đúng với điều nên sống theo lời dạy, và không làm khó Ta vì chuyện lời dạy.",
  "mn140:36.5": "Này các Tỳ Kheo, người con trai trong một nhà tốt Pukkusāti, do đã dứt sạch năm trói buộc kéo xuống, đã sinh lên ở cõi trên, và tại đó sẽ tắt hẳn, không còn quay lại đời này nữa.”",
  "mn140:36.6": "Đức Thế Tôn nói như vậy.",
  "mn140:36.7": "Các Tỳ Kheo ấy vui lòng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn140:36.8": "Kinh Chia Rõ Sáu Phần chấm dứt."
}
window.BILARA["mn140"]["vi"]["mn140:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
