window.BILARA = window.BILARA || {};
window.BILARA["mn152"] = window.BILARA["mn152"] || {};
window.BILARA["mn152"]["vi"] = {
  "mn152:0.1": "Trung Bộ Kinh 152 ",
  "mn152:0.2": "Kinh Tu Tập Các Căn ",
  "mn152:1.1": "Tôi nghe như vầy—",
  "mn152:1.2": "Một thời, Thế Tôn trú ở Gajaṅgalā, tại rừng Suveḷu. ",
  "mn152:2.1": "Rồi thanh niên Uttara, đệ tử của Pārāsiva, đi đến chỗ Thế Tôn; sau khi đến, nói lên những lời chào hỏi thân mật với Thế Tôn. ",
  "mn152:2.2": "Sau khi nói lên những lời chào hỏi thân mật, xã giao rồi, ngồi xuống một bên. Khi thanh niên Uttara, đệ tử của Pārāsiva, đã ngồi xuống một bên, Thế Tôn nói với vị ấy: ",
  "mn152:2.3": "“Này Uttara, Bà-la-môn Pārāsiva có giảng dạy sự tu tập các căn cho các đệ tử không?” ",
  "mn152:2.4": "“Bạch Thế Tôn Gotama, Bà-la-môn Pārāsiva có giảng dạy sự tu tập các căn cho các đệ tử.” ",
  "mn152:2.5": "“Nhưng này Uttara, Bà-la-môn Pārāsiva giảng dạy sự tu tập các căn cho các đệ tử như thế nào?” ",
  "mn152:2.6": "“Bạch Thế Tôn Gotama, ở đây, với mắt không thấy sắc, với tai không nghe tiếng—”",
  "mn152:2.7": "Bạch Thế Tôn Gotama, Bà-la-môn Pārāsiva giảng dạy sự tu tập các căn cho các đệ tử như vậy đó.” ",
  "mn152:2.8": "“Này Uttara, nếu vậy thì người mù sẽ là người có các căn đã tu tập, người điếc sẽ là người có các căn đã tu tập; ",
  "mn152:2.9": "theo lời của Bà-la-môn Pārāsiva. ",
  "mn152:2.10": "Vì này Uttara, người mù không thấy sắc bằng mắt, người điếc không nghe tiếng bằng tai.” ",
  "mn152:2.11": "Khi được nói vậy, thanh niên Uttara, đệ tử của Pārāsiva, im lặng, bối rối, vai rũ xuống, mặt cúi gằm, trầm tư, không thể đối đáp, ngồi yên. ",
  "mn152:3.1": "Rồi Thế Tôn, biết thanh niên Uttara, đệ tử của Pārāsiva, đang im lặng, bối rối, vai rũ xuống, mặt cúi gằm, trầm tư, không thể đối đáp, liền gọi Tôn giả Ānanda: ",
  "mn152:3.2": "“Này Ānanda, Bà-la-môn Pārāsiva giảng dạy sự tu tập các căn cho các đệ tử theo một cách khác, nhưng này Ānanda, trong giới luật của bậc Thánh, sự tu tập các căn vô thượng lại theo một cách khác.” ",
  "mn152:3.3": "“Bạch Thế Tôn, đã đến lúc; bạch Thiện Thệ, đã đến lúc ",
  "mn152:3.4": "Thế Tôn giảng dạy sự tu tập các căn vô thượng trong giới luật của bậc Thánh. Sau khi nghe Thế Tôn, các Tỳ-kheo sẽ thọ trì.” ",
  "mn152:3.5": "“Vậy thì này Ānanda, hãy lắng nghe, hãy khéo tác ý; Ta sẽ nói.” ",
  "mn152:3.6": "“Thưa vâng, bạch Thế Tôn,” Tôn giả Ānanda vâng lời Thế Tôn. ",
  "mn152:3.7": "Thế Tôn nói như sau: ",
  "mn152:4.1": "“Này Ānanda, trong giới luật của bậc Thánh, sự tu tập các căn vô thượng là như thế nào? ",
  "mn152:4.2": "Này Ānanda, ở đây, một Tỳ-kheo khi thấy sắc bằng mắt, khởi lên cái ưa thích, khởi lên cái không ưa thích, khởi lên cái vừa ưa thích vừa không ưa thích. ",
  "mn152:4.3": "Vị ấy biết như sau: ",
  "mn152:4.4": "‘Cái ưa thích này đã khởi lên nơi ta, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên. ",
  "mn152:4.5": "Và cái đó là hữu vi, thô thiển, do duyên khởi. ",
  "mn152:4.6": "Cái này là an tịnh, cái này là thù thắng, tức là—",
  "mn152:4.7": "xả.’ ",
  "mn152:4.8": "Cái ưa thích đã khởi lên nơi vị ấy, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy diệt đi; ",
  "mn152:4.9": "xả an trú. ",
  "mn152:4.10": "Ví như này Ānanda, một người có mắt, mở mắt ra rồi nhắm lại, hoặc nhắm mắt lại rồi mở ra; ",
  "mn152:4.11": "Cũng vậy, này Ānanda, đối với bất cứ ai, cái ưa thích đã khởi lên, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy diệt đi nhanh chóng như vậy, mau lẹ như vậy, dễ dàng như vậy, xả an trú—",
  "mn152:4.12": "Này Ānanda, đây được gọi là sự tu tập các căn vô thượng trong giới luật của bậc Thánh đối với các sắc do mắt nhận biết. ",
  "mn152:5.1": "Lại nữa, này Ānanda, một Tỳ-kheo khi nghe tiếng bằng tai, khởi lên cái ưa thích, khởi lên cái không ưa thích, khởi lên cái vừa ưa thích vừa không ưa thích. ",
  "mn152:5.2": "Vị ấy biết như sau: ",
  "mn152:5.3": "‘Cái ưa thích này đã khởi lên nơi ta, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên. ",
  "mn152:5.4": "Và cái đó là hữu vi, thô thiển, do duyên khởi. ",
  "mn152:5.5": "Cái này là an tịnh, cái này là thù thắng, tức là—",
  "mn152:5.6": "xả.’ ",
  "mn152:5.7": "Cái ưa thích đã khởi lên nơi vị ấy, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy diệt đi; ",
  "mn152:5.8": "xả an trú. ",
  "mn152:5.9": "Ví như này Ānanda, một người mạnh mẽ búng ngón tay một cách dễ dàng; ",
  "mn152:5.10": "Cũng vậy, này Ānanda, đối với bất cứ ai, cái ưa thích đã khởi lên, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy diệt đi nhanh chóng như vậy, mau lẹ như vậy, dễ dàng như vậy, xả an trú—",
  "mn152:5.11": "Này Ānanda, đây được gọi là sự tu tập các căn vô thượng trong giới luật của bậc Thánh đối với các tiếng do tai nhận biết. ",
  "mn152:6.1": "Lại nữa, này Ānanda, một Tỳ-kheo khi ngửi mùi bằng mũi, khởi lên cái ưa thích, khởi lên cái không ưa thích, khởi lên cái vừa ưa thích vừa không ưa thích. ",
  "mn152:6.2": "Vị ấy biết như sau: ",
  "mn152:6.3": "‘Cái ưa thích này đã khởi lên nơi ta, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên. ",
  "mn152:6.4": "Và cái đó là hữu vi, thô thiển, do duyên khởi. ",
  "mn152:6.5": "Cái này là an tịnh, cái này là thù thắng, tức là—",
  "mn152:6.6": "xả.’ ",
  "mn152:6.7": "Cái ưa thích đã khởi lên nơi vị ấy, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy diệt đi; ",
  "mn152:6.8": "xả an trú. ",
  "mn152:6.9": "Ví như này Ānanda, trên lá sen hơi nghiêng, những giọt nước lăn đi, không đọng lại; ",
  "mn152:6.10": "Cũng vậy, này Ānanda, đối với bất cứ ai, cái ưa thích đã khởi lên, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy diệt đi nhanh chóng như vậy, mau lẹ như vậy, dễ dàng như vậy, xả an trú—",
  "mn152:6.11": "Này Ānanda, đây được gọi là sự tu tập các căn vô thượng trong giới luật của bậc Thánh đối với các mùi do mũi nhận biết. ",
  "mn152:7.1": "Lại nữa, này Ānanda, một Tỳ-kheo khi nếm vị bằng lưỡi, khởi lên cái ưa thích, khởi lên cái không ưa thích, khởi lên cái vừa ưa thích vừa không ưa thích. ",
  "mn152:7.2": "Vị ấy biết như sau: ",
  "mn152:7.3": "‘Cái ưa thích này đã khởi lên nơi ta, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên. ",
  "mn152:7.4": "Và cái đó là hữu vi, thô thiển, do duyên khởi. ",
  "mn152:7.5": "Cái này là an tịnh, cái này là thù thắng, tức là—",
  "mn152:7.6": "xả.’ ",
  "mn152:7.7": "Cái ưa thích đã khởi lên nơi vị ấy, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy diệt đi; ",
  "mn152:7.8": "xả an trú. ",
  "mn152:7.9": "Ví như này Ānanda, một người mạnh mẽ gom một cục đờm trên đầu lưỡi rồi dễ dàng nhổ ra; ",
  "mn152:7.10": "Cũng vậy, này Ānanda, đối với bất cứ ai, cái ưa thích đã khởi lên, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy diệt đi nhanh chóng như vậy, mau lẹ như vậy, dễ dàng như vậy, xả an trú—",
  "mn152:7.11": "Này Ānanda, đây được gọi là sự tu tập các căn vô thượng trong giới luật của bậc Thánh đối với các vị do lưỡi nhận biết. ",
  "mn152:8.1": "Lại nữa, này Ānanda, một Tỳ-kheo khi xúc chạm bằng thân, khởi lên cái ưa thích, khởi lên cái không ưa thích, khởi lên cái vừa ưa thích vừa không ưa thích. ",
  "mn152:8.2": "Vị ấy biết như sau: ",
  "mn152:8.3": "‘Cái ưa thích này đã khởi lên nơi ta, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên. ",
  "mn152:8.4": "Và cái đó là hữu vi, thô thiển, do duyên khởi. ",
  "mn152:8.5": "Cái này là an tịnh, cái này là thù thắng, tức là—",
  "mn152:8.6": "xả.’ ",
  "mn152:8.7": "Cái ưa thích đã khởi lên nơi vị ấy, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy diệt đi; ",
  "mn152:8.8": "xả an trú. ",
  "mn152:8.9": "Ví như này Ānanda, một người mạnh mẽ co cánh tay đã duỗi ra, hoặc duỗi cánh tay đã co lại; ",
  "mn152:8.10": "Cũng vậy, này Ānanda, đối với bất cứ ai, cái ưa thích đã khởi lên, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy diệt đi nhanh chóng như vậy, mau lẹ như vậy, dễ dàng như vậy, xả an trú—",
  "mn152:8.11": "Này Ānanda, đây được gọi là sự tu tập các căn vô thượng trong giới luật của bậc Thánh đối với các xúc chạm do thân nhận biết. ",
  "mn152:9.1": "Lại nữa, này Ānanda, một Tỳ-kheo khi nhận biết pháp bằng ý, khởi lên cái ưa thích, khởi lên cái không ưa thích, khởi lên cái vừa ưa thích vừa không ưa thích. ",
  "mn152:9.2": "Vị ấy biết như sau: ",
  "mn152:9.3": "‘Cái ưa thích này đã khởi lên nơi ta, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên. ",
  "mn152:9.4": "Và cái đó là hữu vi, thô thiển, do duyên khởi. ",
  "mn152:9.5": "Cái này là an tịnh, cái này là thù thắng, tức là—",
  "mn152:9.6": "xả.’ ",
  "mn152:9.7": "Cái ưa thích đã khởi lên nơi vị ấy, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy diệt đi; ",
  "mn152:9.8": "xả an trú. ",
  "mn152:9.9": "Ví như này Ānanda, một người mạnh mẽ nhỏ hai hoặc ba giọt nước vào một chảo sắt đã nung nóng cả ngày. ",
  "mn152:9.10": "Này Ānanda, sự rơi xuống của các giọt nước thì chậm, nhưng chúng sẽ nhanh chóng cạn kiệt, tiêu tan; ",
  "mn152:9.11": "Cũng vậy, này Ānanda, đối với bất cứ ai, cái ưa thích đã khởi lên, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy diệt đi nhanh chóng như vậy, mau lẹ như vậy, dễ dàng như vậy, xả an trú—",
  "mn152:9.12": "Này Ānanda, đây được gọi là sự tu tập các căn vô thượng trong giới luật của bậc Thánh đối với các pháp do ý nhận biết. ",
  "mn152:9.13": "Này Ānanda, trong giới luật của bậc Thánh, sự tu tập các căn vô thượng là như vậy đó. ",
  "mn152:10.1": "Này Ānanda, thế nào là người học đạo đang trên đường tu tập? ",
  "mn152:10.2": "Này Ānanda, ở đây, một Tỳ-kheo khi thấy sắc bằng mắt, khởi lên cái ưa thích, khởi lên cái không ưa thích, khởi lên cái vừa ưa thích vừa không ưa thích. ",
  "mn152:10.3": "Vị ấy ghê tởm, hổ thẹn, chán ghét cái ưa thích đã khởi lên, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy. ",
  "mn152:10.4": "Khi nghe tiếng bằng tai …v.v… ",
  "mn152:10.5": "Khi ngửi mùi bằng mũi … ",
  "mn152:10.6": "Khi nếm vị bằng lưỡi … ",
  "mn152:10.7": "Khi xúc chạm bằng thân … ",
  "mn152:10.8": "Khi nhận biết pháp bằng ý, khởi lên cái ưa thích, khởi lên cái không ưa thích, khởi lên cái vừa ưa thích vừa không ưa thích. ",
  "mn152:10.9": "Vị ấy ghê tởm, hổ thẹn, chán ghét cái ưa thích đã khởi lên, cái không ưa thích đã khởi lên, cái vừa ưa thích vừa không ưa thích đã khởi lên ấy. ",
  "mn152:10.10": "Này Ānanda, người học đạo đang trên đường tu tập là như vậy đó. ",
  "mn152:11-15.1": "Này Ānanda, thế nào là bậc Thánh có các căn đã tu tập? ",
  "mn152:11-15.2": "Này Ānanda, ở đây, một Tỳ-kheo khi thấy sắc bằng mắt, khởi lên cái ưa thích, khởi lên cái không ưa thích, khởi lên cái vừa ưa thích vừa không ưa thích. ",
  "mn152:11-15.3": "Nếu vị ấy muốn: ‘Ta sẽ an trú với tưởng không ghê tởm đối với cái ghê tởm,’ thì vị ấy an trú với tưởng không ghê tởm ở đó. ",
  "mn152:11-15.4": "Nếu vị ấy muốn: ‘Ta sẽ an trú với tưởng ghê tởm đối với cái không ghê tởm,’ thì vị ấy an trú với tưởng ghê tởm ở đó. ",
  "mn152:11-15.5": "Nếu vị ấy muốn: ‘Ta sẽ an trú với tưởng không ghê tởm đối với cả cái ghê tởm và cái không ghê tởm,’ thì vị ấy an trú với tưởng không ghê tởm ở đó. ",
  "mn152:11-15.6": "Nếu vị ấy muốn: ‘Ta sẽ an trú với tưởng ghê tởm đối với cả cái không ghê tởm và cái ghê tởm,’ thì vị ấy an trú với tưởng ghê tởm ở đó. ",
  "mn152:11-15.7": "Nếu vị ấy muốn: ‘Sau khi từ bỏ cả cái ghê tởm và cái không ghê tởm, ta sẽ an trú với xả, chánh niệm, tỉnh giác,’ thì vị ấy an trú với xả, chánh niệm, tỉnh giác ở đó. ",
  "mn152:16.1": "Lại nữa, này Ānanda, một Tỳ-kheo khi nghe tiếng bằng tai …v.v… ",
  "mn152:16.2": "Khi ngửi mùi bằng mũi … ",
  "mn152:16.3": "Khi nếm vị bằng lưỡi … ",
  "mn152:16.4": "Khi xúc chạm bằng thân … ",
  "mn152:16.5": "Khi nhận biết pháp bằng ý, khởi lên cái ưa thích, khởi lên cái không ưa thích, khởi lên cái vừa ưa thích vừa không ưa thích. ",
  "mn152:16.6": "Nếu vị ấy muốn: ‘Ta sẽ an trú với tưởng không ghê tởm đối với cái ghê tởm,’ thì vị ấy an trú với tưởng không ghê tởm ở đó. ",
  "mn152:16.7": "Nếu vị ấy muốn: ‘Ta sẽ an trú với tưởng ghê tởm đối với cái không ghê tởm,’ thì vị ấy an trú với tưởng ghê tởm ở đó. ",
  "mn152:16.8": "Nếu vị ấy muốn: ‘Ta sẽ an trú với tưởng không ghê tởm đối với cả cái ghê tởm và cái không ghê tởm,’ thì vị ấy an trú với tưởng không ghê tởm ở đó. ",
  "mn152:16.9": "Nếu vị ấy muốn: ‘Ta sẽ an trú với tưởng ghê tởm đối với cả cái không ghê tởm và cái ghê tởm,’ thì vị ấy an trú với tưởng ghê tởm ở đó. ",
  "mn152:16.10": "Nếu vị ấy muốn: ‘Sau khi từ bỏ cả cái ghê tởm và cái không ghê tởm, ta sẽ an trú với xả, chánh niệm, tỉnh giác,’ thì vị ấy an trú với xả, chánh niệm, tỉnh giác ở đó. ",
  "mn152:16.11": "Này Ānanda, bậc Thánh có các căn đã tu tập là như vậy đó. ",
  "mn152:17.1": "Như vậy, này Ānanda, Ta đã giảng dạy sự tu tập các căn vô thượng trong giới luật của bậc Thánh, đã giảng dạy người học đạo đang trên đường tu tập, đã giảng dạy bậc Thánh có các căn đã tu tập. ",
  "mn152:18.1": "Này Ananda, điều mà một bậc Đạo Sư cần làm vì lòng từ bi, vì lợi ích của các đệ tử, Ta đã làm cho các con rồi. ",
  "mn152:18.2": "Này Ananda, đây là những gốc cây, đây là những ngôi nhà trống. Này Ananda, hãy thiền định, đừng phóng dật, đừng để sau này phải hối hận. Đây là lời giáo huấn của Ta dành cho các con.”",
  "mn152:18.3": "Thế Tôn đã nói điều này. ",
  "mn152:18.4": "Tôn giả Ananda hoan hỷ với lời Thế Tôn đã nói. ",
  "mn152:18.5": "Kinh Tu Tập Các Căn là bài thứ mười, đã xong. ",
  "mn152:18.6": "Phẩm Sáu Xứ là phẩm thứ năm, đã xong. ",
  "mn152:19.0": "Tóm tắt phẩm đó: ",
  "mn152:19.1": "Anathapindika, Channa, ",
  "mn152:19.2": "Punna, Nandaka, Rahula; ",
  "mn152:19.3": "Sáu Sáu, Sáu Xứ, ",
  "mn152:19.4": "Nagaravindeyya, Suddhikā; ",
  "mn152:19.5": "Và Tu Tập Các Căn, ",
  "mn152:19.6": "Phẩm Giáo Huấn thứ năm. ",
  "mn152:20.0": "Đây là tóm tắt các phẩm: ",
  "mn152:20.1": "Devadaha và Anupada, ",
  "mn152:20.2": "Suññata và Vibhanga; ",
  "mn152:20.3": "Các phẩm Sáu Xứ, ",
  "mn152:20.4": "nằm trong Phần Năm Mươi Trên. ",
  "mn152:20.5": "Phần Năm Mươi Trên đã xong. ",
  "mn152:20.6": "Toàn bộ được trang hoàng bởi ba phần năm mươi, ",
  "mn152:20.7": "Trung Bộ Kinh đã xong. "
}
window.BILARA["mn152"]["vi"]["mn152:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
