window.BILARA = window.BILARA || {};
window.BILARA["mn18"] = window.BILARA["mn18"] || {};
window.BILARA["mn18"]["vi"] = {
  "mn18:0.1": "Trung Bộ Kinh 18",
  "mn18:0.2": "Kinh Bánh Mật Ong",
  "mn18:1.1": "Tôi nghe như vầy—",
  "mn18:1.2": "Một thời, Đức Thế Tôn ở giữa dân Sakka, tại Kapilavatthu, trong vườn cây đa.",
  "mn18:2.1": "Rồi vào buổi sáng, Đức Thế Tôn mặc y, cầm bát và áo choàng, đi vào Kapilavatthu để khất thực.",
  "mn18:2.2": "Sau khi đi khất thực trong Kapilavatthu xong, dùng bữa xong và từ chỗ khất thực trở về, Đức Thế Tôn đi đến rừng lớn để nghỉ trưa.",
  "mn18:2.3": "Đi sâu vào rừng lớn, Đức Thế Tôn ngồi nghỉ trưa dưới gốc một bụi cây beluva.",
  "mn18:3.1": "Lúc ấy, người Sakka tên Daṇḍapāṇi đang đi dạo và đi quanh, liền đi đến rừng lớn.",
  "mn18:3.2": "Đi sâu vào rừng lớn, ông đến chỗ bụi cây beluva, đến gần Đức Thế Tôn; đến gần rồi, ông chào hỏi Đức Thế Tôn.",
  "mn18:3.3": "Sau khi nói với nhau vài lời thân thiện gợi nhớ, ông chống gậy đứng sang một bên. Đứng sang một bên, người Sakka Daṇḍapāṇi thưa với Đức Thế Tôn:",
  "mn18:3.4": "“Sa-môn nói điều gì, dạy điều gì?”",
  "mn18:4.1": "“Này hiền giả, Ta nói theo cách mà trong đời, cùng với chư thiên, Ma vương, Phạm thiên, cùng với hạng sa-môn, bà-la-môn, cùng chư thiên và loài người, không ai có thể tranh cãi với Ta; và với người sống tách khỏi các thú vui giác quan, không còn ngờ vực, đã dứt ăn năn, đã vượt khỏi lòng ham muốn đối với có mặt này hay có mặt khác, thì các ghi nhận trong tâm không còn bám theo người ấy nữa—",
  "mn18:4.2": "Ta là người nói như vậy, dạy như vậy.”",
  "mn18:5.1": "Khi được nói vậy, người Sakka Daṇḍapāṇi lắc đầu, thè lưỡi, nhíu trán thành ba nếp, rồi chống gậy bỏ đi.",
  "mn18:6.1": "Rồi vào buổi chiều, Đức Thế Tôn ra khỏi chỗ ở yên một mình, đi đến vườn cây đa; đến nơi, Ngài ngồi xuống chỗ đã dọn sẵn.",
  "mn18:6.2": "Ngồi xuống rồi, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn18:6.3": "“Này các Tỳ Kheo, sáng nay Ta mặc y, cầm bát và áo choàng, đi vào Kapilavatthu để khất thực.",
  "mn18:6.4": "Sau khi đi khất thực trong Kapilavatthu xong, dùng bữa xong và từ chỗ khất thực trở về, Ta đi đến rừng lớn để nghỉ trưa.",
  "mn18:6.5": "Đi sâu vào rừng lớn, Ta ngồi nghỉ trưa dưới gốc một bụi cây beluva.",
  "mn18:6.6": "Này các Tỳ Kheo, người Sakka Daṇḍapāṇi đang đi dạo và đi quanh, liền đi đến rừng lớn.",
  "mn18:6.7": "Đi sâu vào rừng lớn, ông đến chỗ bụi cây beluva, đến gần chỗ Ta; đến gần rồi, ông chào hỏi Ta.",
  "mn18:6.8": "Sau khi nói với nhau vài lời thân thiện gợi nhớ, ông chống gậy đứng sang một bên. Đứng sang một bên, này các Tỳ Kheo, người Sakka Daṇḍapāṇi nói với Ta:",
  "mn18:6.9": "‘Sa-môn nói điều gì, dạy điều gì?’",
  "mn18:6.10": "Khi được hỏi vậy, này các Tỳ Kheo, Ta nói với người Sakka Daṇḍapāṇi như sau:",
  "mn18:6.11": "‘Này hiền giả, Ta nói theo cách mà trong đời, cùng với chư thiên, Ma vương, Phạm thiên, cùng với hạng sa-môn, bà-la-môn, cùng chư thiên và loài người, không ai có thể tranh cãi với Ta; và với người sống tách khỏi các thú vui giác quan, không còn ngờ vực, đã dứt ăn năn, đã vượt khỏi lòng ham muốn đối với có mặt này hay có mặt khác, thì các ghi nhận trong tâm không còn bám theo người ấy nữa—",
  "mn18:6.12": "Ta là người nói như vậy, dạy như vậy.’",
  "mn18:6.13": "Khi được nói vậy, này các Tỳ Kheo, người Sakka Daṇḍapāṇi lắc đầu, thè lưỡi, nhíu trán thành ba nếp, rồi chống gậy bỏ đi.”",
  "mn18:6.14": "Khi được nói vậy, một vị Tỳ Kheo thưa với Đức Thế Tôn:",
  "mn18:7.1": "“Bạch Đức Thế Tôn, Đức Thế Tôn nói thế nào mà trong đời, cùng với chư thiên, Ma vương, Phạm thiên, cùng với hạng sa-môn, bà-la-môn, cùng chư thiên và loài người, không ai có thể tranh cãi với Ngài?",
  "mn18:7.2": "Và thế nào là các ghi nhận trong tâm không còn bám theo Đức Thế Tôn, khi Ngài sống tách khỏi các thú vui giác quan, không còn ngờ vực, đã dứt ăn năn, đã vượt khỏi lòng ham muốn đối với có mặt này hay có mặt khác?”",
  "mn18:8.1": "“Này Tỳ Kheo, từ đâu mà những nghĩ ngợi lan man do nhận ra rồi đặt tên dấy lên nơi một người,",
  "mn18:8.2": "nếu ở đó không có gì đáng ưa thích, không có gì đáng bám theo, không có gì đáng nắm chặt,",
  "mn18:8.3": "thì đó là chỗ chấm dứt của thói ngầm ưa muốn, đó là chỗ chấm dứt của thói ngầm bực chống, đó là chỗ chấm dứt của thói ngầm chấp thấy, đó là chỗ chấm dứt của thói ngầm ngờ vực, đó là chỗ chấm dứt của thói ngầm hơn thua, đó là chỗ chấm dứt của thói ngầm ham sống mãi, đó là chỗ chấm dứt của thói ngầm không sáng biết, đó là chỗ chấm dứt của đánh đập, cầm gậy, cầm dao, cãi cọ, tranh giành, gây gổ, nói xấu sau lưng, nói dối.",
  "mn18:8.4": "Chính tại đây, những điều xấu ác, không lành ấy lặng dứt không còn sót.”",
  "mn18:9.1": "Đức Thế Tôn nói như vậy.",
  "mn18:9.2": "Nói xong, Đấng Khéo Qua đứng dậy khỏi chỗ ngồi rồi vào chỗ ở.",
  "mn18:10.1": "Rồi khi Đức Thế Tôn vừa đi không bao lâu, các Tỳ Kheo ấy nghĩ rằng:",
  "mn18:10.2": "“Này các hiền hữu, Đức Thế Tôn đã nêu vắn tắt đầu mối, nhưng chưa chia rộng nghĩa rõ ràng, rồi đứng dậy khỏi chỗ ngồi và vào chỗ ở:",
  "mn18:10.3": "‘Này Tỳ Kheo, từ đâu mà những nghĩ ngợi lan man do nhận ra rồi đặt tên dấy lên nơi một người,",
  "mn18:10.4": "nếu ở đó không có gì đáng ưa thích, không có gì đáng bám theo, không có gì đáng nắm chặt,",
  "mn18:10.5": "thì đó là chỗ chấm dứt của thói ngầm ưa muốn …",
  "mn18:10.6": "chính tại đây, những điều xấu ác, không lành ấy lặng dứt không còn sót.’",
  "mn18:10.7": "Vậy ai có thể chia rộng nghĩa của lời nêu vắn tắt mà Đức Thế Tôn đã nói, nhưng chưa giảng rõ đầy đủ ấy?”",
  "mn18:10.8": "Rồi các Tỳ Kheo ấy nghĩ rằng:",
  "mn18:10.9": "“Tôn giả Mahākaccāna này được bậc Thầy khen ngợi, lại được các bạn sống đời trong sạch có hiểu biết quý trọng.",
  "mn18:10.10": "Tôn giả Mahākaccāna có thể chia rộng nghĩa của lời nêu vắn tắt mà Đức Thế Tôn đã nói, nhưng chưa giảng rõ đầy đủ ấy.",
  "mn18:10.11": "Hay là chúng ta đến gặp Tôn giả Mahākaccāna; đến rồi sẽ hỏi Tôn giả Mahākaccāna về ý nghĩa này.”",
  "mn18:11.1": "Rồi các Tỳ Kheo ấy đi đến chỗ Tôn giả Mahākaccāna; đến nơi, họ chào hỏi thân tình với Tôn giả Mahākaccāna.",
  "mn18:11.2": "Sau khi nói với nhau những lời thân tình gợi nhớ, họ ngồi xuống một bên. Khi đã ngồi xuống một bên, các Tỳ Kheo ấy nói với Tôn giả Mahākaccāna rằng:",
  "mn18:11.3": "“Này hiền hữu Kaccāna, Đức Thế Tôn đã nêu vắn tắt đầu mối, nhưng chưa chia rộng nghĩa rõ ràng, rồi đứng dậy khỏi chỗ ngồi và vào chỗ ở:",
  "mn18:11.4": "‘Này Tỳ Kheo, từ đâu mà những nghĩ ngợi lan man do nhận ra rồi đặt tên dấy lên nơi một người,",
  "mn18:11.5": "nếu ở đó không có gì đáng ưa thích, không có gì đáng bám theo, không có gì đáng nắm chặt,",
  "mn18:11.6": "thì đó là chỗ chấm dứt của thói ngầm ưa muốn …",
  "mn18:11.7": "chính tại đây, những điều xấu ác, không lành ấy lặng dứt không còn sót.’",
  "mn18:11.8": "Sau khi Đức Thế Tôn vừa đi không bao lâu, chúng tôi nghĩ rằng:",
  "mn18:11.9": "‘Này các hiền hữu, Đức Thế Tôn đã nêu vắn tắt đầu mối, nhưng chưa chia rộng nghĩa rõ ràng, rồi đứng dậy khỏi chỗ ngồi và vào chỗ ở:",
  "mn18:11.10": "“Này Tỳ Kheo, từ đâu mà những nghĩ ngợi lan man do nhận ra rồi đặt tên dấy lên nơi một người,",
  "mn18:11.11": "nếu ở đó không có gì đáng ưa thích, không có gì đáng bám theo, không có gì đáng nắm chặt,",
  "mn18:11.12": "thì đó là chỗ chấm dứt của thói ngầm ưa muốn …",
  "mn18:11.13": "chính tại đây, những điều xấu ác, không lành ấy lặng dứt không còn sót.”’",
  "mn18:11.14": "Vậy ai có thể giảng rộng nghĩa của lời tóm lược mà Đức Thế Tôn đã nói ngắn gọn, nhưng chưa chia rõ nghĩa ra từng phần?",
  "mn18:11.15": "Khi ấy, này hiền giả Kaccāna, chúng tôi nghĩ như vầy:",
  "mn18:11.16": "‘Hiền giả Mahākaccāna này được bậc Thầy khen ngợi và được các bạn sống đời phạm hạnh có hiểu biết quý trọng. Hiền giả Mahākaccāna có thể giảng rộng nghĩa của lời tóm lược mà Đức Thế Tôn đã nói ngắn gọn, nhưng chưa chia rõ nghĩa ra từng phần.",
  "mn18:11.17": "Hay là chúng ta đến gặp hiền giả Mahākaccāna; đến rồi sẽ hỏi hiền giả Mahākaccāna về nghĩa ấy.’",
  "mn18:11.18": "Xin hiền giả Mahākaccāna giảng cho.”",
  "mn18:12.1": "“Này các hiền giả, ví như một người cần lõi cây, đi tìm lõi cây, đang đi kiếm lõi cây nơi một cây lớn đang đứng vững, có lõi chắc, mà lại bỏ qua rễ, bỏ qua thân, rồi nghĩ rằng phải tìm lõi nơi cành lá,",
  "mn18:12.2": "cũng vậy, các hiền giả đang ở ngay trước mặt bậc Thầy, vậy mà lại bỏ qua Đức Thế Tôn ấy, rồi nghĩ rằng nên hỏi chúng tôi về nghĩa này.",
  "mn18:12.3": "Này các hiền giả, Đức Thế Tôn là người biết thì biết rõ, thấy thì thấy rõ, là người có mắt, là người có sự biết rõ, là người thấy lẽ thật, là bậc cao thượng, là người nói ra, chỉ bày ra, là người làm sáng tỏ ý nghĩa, là người trao cái không chết, là bậc chủ của lẽ thật, là Như Lai.",
  "mn18:12.4": "Và chính lúc ấy là lúc các hiền giả nên hỏi thẳng Đức Thế Tôn về nghĩa này.",
  "mn18:12.5": "Đức Thế Tôn trả lời cho các hiền giả thế nào, thì các hiền giả nên ghi nhớ như thế.”",
  "mn18:13.1": "“Đúng vậy, này hiền giả Kaccāna, Đức Thế Tôn là người biết thì biết rõ, thấy thì thấy rõ, là người có mắt, là người có sự biết rõ, là người thấy lẽ thật, là bậc cao thượng, là người nói ra, chỉ bày ra, là người làm sáng tỏ ý nghĩa, là người trao cái không chết, là bậc chủ của lẽ thật, là Như Lai.",
  "mn18:13.2": "Và chính lúc ấy là lúc chúng tôi nên hỏi thẳng Đức Thế Tôn về nghĩa này.",
  "mn18:13.3": "Đức Thế Tôn trả lời cho chúng tôi thế nào, thì chúng tôi sẽ ghi nhớ như thế.",
  "mn18:13.4": "Nhưng hiền giả Mahākaccāna cũng được bậc Thầy khen ngợi và được các bạn sống đời phạm hạnh có hiểu biết quý trọng,",
  "mn18:13.5": "và hiền giả Mahākaccāna có thể giảng rộng nghĩa của lời tóm lược mà Đức Thế Tôn đã nói ngắn gọn, nhưng chưa chia rõ nghĩa ra từng phần.",
  "mn18:13.6": "Xin hiền giả Mahākaccāna giảng cho, đừng ngại.”",
  "mn18:14.1": "“Vậy thì, này các hiền giả, hãy nghe đây, khéo để tâm vào, tôi sẽ nói.”",
  "mn18:14.2": "“Thưa vâng, hiền giả,” các Tỳ Kheo ấy đáp lời hiền giả Mahākaccāna.",
  "mn18:14.3": "Hiền giả Mahākaccāna nói như vầy:",
  "mn18:15.1": "“Này các hiền giả, điều mà Đức Thế Tôn đã nói ngắn gọn bằng lời tóm lược, chưa giảng rộng nghĩa ra, rồi từ chỗ ngồi đứng dậy đi vào chỗ ở, là thế này:",
  "mn18:15.2": "‘Này Tỳ Kheo, do đâu mà những cách nghĩ lan man, những gán đặt lan man, những gọi tên lan man nổi lên quanh một người,",
  "mn18:15.3": "nếu ở đó không có gì để ưa thích, không có gì để bám theo, không có gì để nắm chặt, thì đó là chỗ chấm dứt của thói ham muốn ngầm ẩn … ở đây các điều xấu ác, không khéo, đều lặng dứt không còn sót lại.’",
  "mn18:15.4": "Này các hiền giả, nghĩa rộng của lời tóm lược mà Đức Thế Tôn đã nói ngắn gọn nhưng chưa chia rõ ra từng phần, tôi hiểu như vầy:",
  "mn18:16.1": "Này các hiền giả, do mắt và hình sắc mà sự thấy bằng mắt sinh ra. Sự gặp nhau của ba thứ ấy là sự đụng chạm. Do sự đụng chạm nên có cảm giác. Cái gì được cảm nhận thì được nhận ra. Cái gì được nhận ra thì được nghĩ tới. Cái gì được nghĩ tới thì bị nghĩ lan man ra. Từ cái bị nghĩ lan man ra ấy, những cách nghĩ lan man, những gán đặt lan man, những gọi tên lan man nổi lên quanh một người đối với các hình sắc do mắt biết được trong quá khứ, tương lai và hiện tại.",
  "mn18:16.2": "Này các hiền giả, do tai và tiếng mà sự nghe bằng tai sinh ra …",
  "mn18:16.3": "này các hiền giả, do mũi và mùi mà sự biết mùi bằng mũi sinh ra …",
  "mn18:16.4": "này các hiền giả, do lưỡi và vị mà sự biết vị bằng lưỡi sinh ra …",
  "mn18:16.5": "này các hiền giả, do thân và vật chạm mà sự biết bằng thân sinh ra …",
  "mn18:16.6": "này các hiền giả, do ý và các điều được ý biết mà sự biết bằng ý sinh ra. Sự gặp nhau của ba thứ ấy là sự đụng chạm. Do sự đụng chạm nên có cảm giác. Cái gì được cảm nhận thì được nhận ra. Cái gì được nhận ra thì được nghĩ tới. Cái gì được nghĩ tới thì bị nghĩ lan man ra. Từ cái bị nghĩ lan man ra ấy, những cách nghĩ lan man, những gán đặt lan man, những gọi tên lan man nổi lên quanh một người đối với các điều do ý biết được trong quá khứ, tương lai và hiện tại.",
  "mn18:17.1": "Này các hiền giả, khi có mắt, có hình sắc, có sự thấy bằng mắt, thì có thể nói đến sự đụng chạm; điều này có thể xảy ra.",
  "mn18:17.2": "Khi có sự đụng chạm thì sẽ đặt ra cảm nhận; việc ấy có thể xảy ra.",
  "mn18:17.3": "Khi có cảm nhận thì sẽ đặt ra sự ghi nhận; việc ấy có thể xảy ra.",
  "mn18:17.4": "Khi có sự ghi nhận thì sẽ đặt ra suy nghĩ; việc ấy có thể xảy ra.",
  "mn18:17.5": "Khi có suy nghĩ thì sẽ đặt ra sự lan man do ghi nhận mà thành, rồi nó nổi lên; việc ấy có thể xảy ra.",
  "mn18:17.6": "Này các hiền giả, khi có tai, có tiếng ...",
  "mn18:17.7": "khi có mũi, có mùi ...",
  "mn18:17.8": "khi có lưỡi, có vị ...",
  "mn18:17.9": "khi có thân, có vật chạm ...",
  "mn18:17.10": "khi có ý, có điều được ý biết, có sự biết của ý, thì sẽ đặt ra sự đụng chạm; việc ấy có thể xảy ra.",
  "mn18:17.11": "Khi có sự đụng chạm thì sẽ đặt ra cảm nhận; việc ấy có thể xảy ra.",
  "mn18:17.12": "Khi có cảm nhận thì sẽ đặt ra sự ghi nhận; việc ấy có thể xảy ra.",
  "mn18:17.13": "Khi có sự ghi nhận thì sẽ đặt ra suy nghĩ; việc ấy có thể xảy ra.",
  "mn18:17.14": "Khi có suy nghĩ thì sẽ đặt ra sự lan man do ghi nhận mà thành, rồi nó nổi lên; việc ấy có thể xảy ra.",
  "mn18:18.1": "Này các hiền giả, khi không có mắt, không có hình sắc, không có sự biết của mắt, thì không thể đặt ra sự đụng chạm.",
  "mn18:18.2": "Khi không có sự đụng chạm thì không thể đặt ra cảm nhận.",
  "mn18:18.3": "Khi không có cảm nhận thì không thể đặt ra sự ghi nhận.",
  "mn18:18.4": "Khi không có sự ghi nhận thì không thể đặt ra suy nghĩ.",
  "mn18:18.5": "Khi không có suy nghĩ thì không thể đặt ra sự lan man do ghi nhận mà thành, rồi nó nổi lên.",
  "mn18:18.6": "Này các hiền giả, khi không có tai, không có tiếng ...",
  "mn18:18.7": "khi không có mũi, không có mùi ...",
  "mn18:18.8": "khi không có lưỡi, không có vị ...",
  "mn18:18.9": "khi không có thân, không có vật chạm ...",
  "mn18:18.10": "khi không có ý, không có điều được ý biết, không có sự biết của ý, thì không thể đặt ra sự đụng chạm.",
  "mn18:18.11": "Khi không có sự đụng chạm thì không thể đặt ra cảm nhận.",
  "mn18:18.12": "Khi không có cảm nhận thì không thể đặt ra sự ghi nhận.",
  "mn18:18.13": "Khi không có sự ghi nhận thì không thể đặt ra suy nghĩ.",
  "mn18:18.14": "Khi không có suy nghĩ thì không thể đặt ra sự lan man do ghi nhận mà thành, rồi nó nổi lên.",
  "mn18:19.1": "Này các hiền giả, điều mà Đức Thế Tôn đã nêu gọn, rồi không chia nghĩa ra rộng thêm, mà đứng dậy khỏi chỗ ngồi và đi vào am thất:",
  "mn18:19.2": "‘Này Tỳ Kheo, từ đâu mà sự lan man do ghi nhận mà thành nổi lên nơi một người, nếu ở đó không có gì đáng vui thích, không có gì đáng bám theo, không có gì đáng nắm giữ, thì đó là chỗ chấm dứt của các thói ngầm mang lòng ham muốn ...",
  "mn18:19.3": "chính tại đây, các điều xấu ác, không lành ấy đều lặng dứt không còn sót lại’; này các hiền giả, đối với lời nêu gọn mà Đức Thế Tôn đã nói như vậy, nhưng chưa chia nghĩa ra rộng thêm, tôi hiểu nghĩa rộng của lời ấy như vầy.",
  "mn18:19.4": "Nhưng này các vị đáng kính, nếu các vị muốn, thì hãy đích thân đến hỏi Đức Thế Tôn về ý nghĩa ấy.",
  "mn18:19.5": "Đức Thế Tôn trả lời cho các vị thế nào, thì các vị hãy ghi nhớ như vậy.”",
  "mn18:20.1": "Rồi các Tỳ Kheo ấy vui mừng, tán thành lời của ngài Đại Ca Chiên Diên, đứng dậy khỏi chỗ ngồi, đi đến chỗ Đức Thế Tôn. Đến nơi, họ đảnh lễ Đức Thế Tôn rồi ngồi xuống một bên. Khi đã ngồi xuống một bên, các Tỳ Kheo ấy thưa với Đức Thế Tôn:",
  "mn18:20.2": "“Bạch Thế Tôn, Đức Thế Tôn đã nêu vắn tắt đầu đề, chưa chia rõ ý nghĩa rộng ra, rồi đứng dậy khỏi chỗ ngồi và đi vào chỗ ở:",
  "mn18:20.3": "‘Này Tỳ Kheo, do đâu mà những nghĩ suy lan man và cách gán đặt do tưởng tượng lại nổi lên nơi một người,",
  "mn18:20.4": "nếu ở đó không có gì đáng vui thích, không có gì đáng bám lấy, không có gì đáng nắm chặt,",
  "mn18:20.5": "thì đó là chỗ chấm dứt của thói ngầm ham muốn …",
  "mn18:20.6": "ở đây các điều xấu ác, không khéo, đều lặng dứt không còn sót lại.’",
  "mn18:20.7": "Bạch Thế Tôn, sau khi Đức Thế Tôn vừa đi không bao lâu, chúng con nghĩ như vầy:",
  "mn18:20.8": "‘Đức Thế Tôn đã nêu vắn tắt đầu đề, chưa chia rõ ý nghĩa rộng ra, rồi đứng dậy khỏi chỗ ngồi và đi vào chỗ ở:",
  "mn18:20.9": "“Này Tỳ Kheo, do đâu mà những nghĩ suy lan man và cách gán đặt do tưởng tượng lại nổi lên nơi một người,",
  "mn18:20.10": "nếu ở đó không có gì đáng vui thích, không có gì đáng bám lấy, không có gì đáng nắm chặt,",
  "mn18:20.11": "thì đó là chỗ chấm dứt của thói ngầm ham muốn, là chỗ chấm dứt của thói ngầm bực chống, là chỗ chấm dứt của thói ngầm chấp thấy, là chỗ chấm dứt của thói ngầm ngờ vực, là chỗ chấm dứt của thói ngầm hơn thua, là chỗ chấm dứt của thói ngầm ham sống mãi, là chỗ chấm dứt của thói ngầm không sáng biết, là chỗ chấm dứt của đánh đập, cầm gậy, cầm dao, cãi cọ, tranh giành, gây gổ, nói đâm thọc, nói dối.",
  "mn18:20.12": "Ở đây các điều xấu ác, không khéo, đều lặng dứt không còn sót lại.”",
  "mn18:20.13": "Ai có thể chia rộng ý nghĩa của lời nêu vắn tắt mà Đức Thế Tôn đã nói ra, nhưng chưa chia rõ rộng ra ấy?’",
  "mn18:20.14": "Bạch Thế Tôn, rồi chúng con nghĩ như vầy:",
  "mn18:20.15": "‘Ngài Đại Ca Chiên Diên này được bậc Thầy khen ngợi, được các bạn đồng sống đời phạm hạnh có hiểu biết quý trọng. Ngài Đại Ca Chiên Diên có thể chia rộng ý nghĩa của lời nêu vắn tắt mà Đức Thế Tôn đã nói ra nhưng chưa chia rõ rộng ra ấy. Hay là chúng ta đến chỗ ngài Đại Ca Chiên Diên, rồi hỏi ngài về ý nghĩa này.’",
  "mn18:20.16": "Rồi, bạch Thế Tôn, chúng con đã đến chỗ ngài Đại Ca Chiên Diên. Đến nơi, chúng con đã hỏi ngài về ý nghĩa này.",
  "mn18:20.17": "Bạch Thế Tôn, ngài Đại Ca Chiên Diên đã chia rõ ý nghĩa cho chúng con bằng những cách này, bằng những lời này, bằng những chữ này.”",
  "mn18:21.1": "“Này các Tỳ Kheo, Đại Ca Chiên Diên là người sáng suốt; này các Tỳ Kheo, Đại Ca Chiên Diên có hiểu biết lớn.",
  "mn18:21.2": "Này các Tỳ Kheo, nếu các ông có hỏi Ta về ý nghĩa ấy, thì Ta cũng sẽ trả lời đúng như cách Đại Ca Chiên Diên đã trả lời.",
  "mn18:21.3": "Đó chính là ý nghĩa của điều ấy. Các ông hãy ghi nhớ như vậy.”",
  "mn18:22.1": "Khi được nói vậy, ngài A Nan thưa với Đức Thế Tôn:",
  "mn18:22.2": "“Bạch Thế Tôn, ví như một người đang bị đói và mệt lả mà gặp được một nắm mật ong; người ấy nếm ở chỗ nào cũng đều thấy vị ngọt ngon, không pha trộn.",
  "mn18:22.3": "Cũng vậy, bạch Thế Tôn, một Tỳ Kheo có tâm trong sáng, dù xem xét ý nghĩa của cách trình bày này ở chỗ nào bằng sự hiểu rõ, cũng đều nhận được niềm vui trong lòng, nhận được sự trong sáng của tâm.",
  "mn18:22.4": "Bạch Thế Tôn, cách trình bày này tên là gì?”",
  "mn18:22.5": "“Vậy thì, này A Nan, ông hãy ghi nhớ cách trình bày này là Bài giảng Nắm Mật Ong.”",
  "mn18:22.6": "Đức Thế Tôn nói như vậy.",
  "mn18:22.7": "Ngài A Nan vui mừng, hoan hỷ với lời Đức Thế Tôn dạy.",
  "mn18:22.8": "Kinh Nắm Mật Ong xong, bài thứ tám."
}
window.BILARA["mn18"]["vi"]["mn18:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";