window.BILARA = window.BILARA || {};
window.BILARA["mn19"] = window.BILARA["mn19"] || {};
window.BILARA["mn19"]["vi"] = {
  "mn19:0.1": "Trung Bộ Kinh 19",
  "mn19:0.2": "Kinh Hai Loại Suy Nghĩ",
  "mn19:1.1": "Tôi nghe như vầy—",
  "mn19:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, tại Kỳ Viên, trong vườn của ông Cấp Cô Độc.",
  "mn19:1.3": "Khi ấy, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn19:1.4": "“Này các Tỳ Kheo.”",
  "mn19:1.5": "Các Tỳ Kheo đáp lời Đức Thế Tôn: “Dạ, bạch Ngài.”",
  "mn19:1.6": "Đức Thế Tôn nói như vầy:",
  "mn19:2.1": "“Này các Tỳ Kheo, thuở trước, khi Ta còn chưa tự mình hiểu trọn vẹn, khi còn là người đang đi tới chỗ giác ngộ, Ta nghĩ như vầy:",
  "mn19:2.2": "‘Hay là ta chia các ý nghĩ ra làm hai phần, rồi sống quán xét chúng theo hai phần ấy.’",
  "mn19:2.3": "Này các Tỳ Kheo, rồi Ta xếp ý nghĩ ham muốn giác quan, ý nghĩ giận dữ, và ý nghĩ làm hại",
  "mn19:2.4": "vào một phần;",
  "mn19:2.5": "còn ý nghĩ lìa bỏ, ý nghĩ không giận dữ, và ý nghĩ không làm hại",
  "mn19:2.6": "vào phần thứ hai.",
  "mn19:3.1": "Này các Tỳ Kheo, khi Ta sống như vậy, luôn tỉnh táo, siêng năng, dốc lòng, thì ý nghĩ ham muốn giác quan khởi lên.",
  "mn19:3.2": "Ta hiểu rõ như vầy:",
  "mn19:3.3": "‘Ý nghĩ ham muốn giác quan này đã khởi lên trong ta.",
  "mn19:3.4": "Nó đưa tới làm hại mình, cũng đưa tới làm hại người, cũng đưa tới làm hại cả hai; nó ngăn che sự hiểu rõ, đứng về phía bực bội, không dẫn tới tắt hẳn khổ đau.’",
  "mn19:3.5": "Này các Tỳ Kheo, khi Ta suy xét: ‘Nó đưa tới làm hại mình’, thì nó lắng xuống;",
  "mn19:3.6": "khi Ta suy xét: ‘Nó đưa tới làm hại người’, thì nó lắng xuống;",
  "mn19:3.7": "khi Ta suy xét: ‘Nó đưa tới làm hại cả hai’, thì nó lắng xuống;",
  "mn19:3.8": "khi Ta suy xét: ‘Nó ngăn che sự hiểu rõ, đứng về phía bực bội, không dẫn tới tắt hẳn khổ đau’, thì nó lắng xuống.",
  "mn19:3.9": "Này các Tỳ Kheo, mỗi khi ý nghĩ ham muốn giác quan khởi lên, Ta đều bỏ nó, xua nó đi, làm cho nó chấm dứt.",
  "mn19:4-5.1": "Này các Tỳ Kheo, khi Ta sống như vậy, luôn tỉnh táo, siêng năng, dốc lòng, thì ý nghĩ giận dữ khởi lên …",
  "mn19:4-5.2": "ý nghĩ làm hại khởi lên.",
  "mn19:4-5.3": "Ta hiểu rõ như vầy:",
  "mn19:4-5.4": "‘Ý nghĩ làm hại này đã khởi lên trong ta.",
  "mn19:4-5.5": "Nó đưa tới làm hại mình, cũng đưa tới làm hại người, cũng đưa tới làm hại cả hai; nó ngăn che sự hiểu rõ, đứng về phía bực bội, không dẫn tới tắt hẳn khổ đau.’",
  "mn19:4-5.6": "Này các Tỳ Kheo, khi Ta suy xét: ‘Nó đưa tới làm hại mình’, thì nó lắng xuống;",
  "mn19:4-5.7": "khi Ta suy xét: ‘Nó đưa tới làm hại người’, thì nó lắng xuống;",
  "mn19:4-5.8": "khi ta suy xét như vậy, này các Tỳ Kheo, ta thấy rõ: ‘điều ấy đưa đến hại mình và hại người’;",
  "mn19:4-5.9": "và ta thấy rõ: ‘điều ấy làm sự hiểu rõ lụi tắt, nghiêng về bức bối, không đưa đến tắt hẳn’.",
  "mn19:4-5.10": "Vì vậy, này các Tỳ Kheo, mỗi khi ý nghĩ muốn làm hại khởi lên, ta đều bỏ nó, xua nó đi, làm cho nó chấm dứt, làm cho nó không còn nữa.",
  "mn19:6.1": "Này các Tỳ Kheo, Tỳ Kheo thường nghĩ nhiều và ngẫm nhiều về điều gì, thì tâm sẽ nghiêng theo điều ấy.",
  "mn19:6.2": "Này các Tỳ Kheo, nếu Tỳ Kheo thường nghĩ nhiều và ngẫm nhiều về dục muốn, bỏ ý nghĩ lìa dục, làm cho ý nghĩ dục muốn thành nhiều, thì tâm vị ấy sẽ nghiêng về dục muốn.",
  "mn19:6.3": "Này các Tỳ Kheo, nếu Tỳ Kheo thường nghĩ nhiều và ngẫm nhiều về ý nghĩ ác ý …",
  "mn19:6.4": "này các Tỳ Kheo, nếu Tỳ Kheo thường nghĩ nhiều và ngẫm nhiều về ý nghĩ làm hại, bỏ ý nghĩ không làm hại, làm cho ý nghĩ làm hại thành nhiều, thì tâm vị ấy sẽ nghiêng về ý nghĩ làm hại.",
  "mn19:7.1": "Ví như, này các Tỳ Kheo, vào tháng cuối mùa mưa, khi trời thu, lúc ruộng lúa chen kín, một người chăn bò giữ đàn bò.",
  "mn19:7.2": "Người ấy phải dùng gậy đánh chúng chỗ này chỗ kia, đuổi lui, chặn lại, ngăn lại.",
  "mn19:7.3": "Vì sao vậy?",
  "mn19:7.4": "Vì, này các Tỳ Kheo, người chăn bò ấy thấy rằng từ đó có thể sinh ra bị đánh, bị trói, bị phạt hay bị chê trách.",
  "mn19:7.5": "Cũng vậy, này các Tỳ Kheo, ta đã thấy rõ mặt hại, chỗ thấp kém, sự nhơ bẩn của những điều xấu; và thấy rõ ích lợi của sự lìa dục, mặt trong sạch của những điều lành.",
  "mn19:8.1": "Khi ta sống như vậy, luôn tỉnh táo, siêng năng, dốc lòng, thì ý nghĩ lìa dục khởi lên.",
  "mn19:8.2": "Ta hiểu rõ như vầy:",
  "mn19:8.3": "‘Ý nghĩ lìa dục này đã khởi lên trong ta.",
  "mn19:8.4": "Nó không đưa đến hại mình, không đưa đến hại người, không đưa đến hại cả hai; nó làm sự hiểu rõ lớn lên, nghiêng về không bức bối, đưa đến tắt hẳn’.",
  "mn19:8.5": "Này các Tỳ Kheo, dù ta có tiếp tục nghĩ và ngẫm về nó suốt đêm, ta cũng không thấy từ đó có điều đáng sợ nào.",
  "mn19:8.6": "Này các Tỳ Kheo, dù ta có tiếp tục nghĩ và ngẫm về nó suốt ngày, ta cũng không thấy từ đó có điều đáng sợ nào.",
  "mn19:8.7": "Này các Tỳ Kheo, dù ta có tiếp tục nghĩ và ngẫm về nó cả đêm lẫn ngày, ta cũng không thấy từ đó có điều đáng sợ nào.",
  "mn19:8.8": "Nhưng nếu ta cứ nghĩ và ngẫm quá lâu, thì thân sẽ mệt.",
  "mn19:8.9": "Khi thân mệt, tâm sẽ chao động.",
  "mn19:8.10": "Khi tâm chao động, tâm khó yên vững.",
  "mn19:8.11": "Vì vậy, này các Tỳ Kheo, ta làm cho tâm đứng yên ở bên trong, lắng xuống, gom lại một mối, làm cho vững yên.",
  "mn19:8.12": "Vì sao vậy?",
  "mn19:8.13": "‘Để tâm ta khỏi chao động’.",
  "mn19:9-10.1": "Khi ta sống như vậy, luôn tỉnh táo, siêng năng, dốc lòng, thì ý nghĩ không ác ý khởi lên …",
  "mn19:9-10.2": "ý nghĩ không làm hại khởi lên.",
  "mn19:9-10.3": "Ta hiểu rõ như vầy:",
  "mn19:9-10.4": "‘Ý nghĩ không làm hại này đã khởi lên trong ta.",
  "mn19:9-10.5": "Nó không đưa đến hại mình, không đưa đến hại người, không đưa đến hại cả hai; nó làm sự hiểu rõ lớn lên, nghiêng về không bức bối, đưa đến tắt hẳn’.",
  "mn19:9-10.6": "Này các Tỳ Kheo, dù ta có suy xét và xem kỹ điều ấy suốt đêm, ta cũng không thấy từ đó có điều gì đáng sợ.",
  "mn19:9-10.7": "Này các Tỳ Kheo, dù ta có suy xét và xem kỹ điều ấy suốt ngày, ta cũng không thấy từ đó có điều gì đáng sợ.",
  "mn19:9-10.8": "Này các Tỳ Kheo, dù ta có suy xét và xem kỹ điều ấy suốt đêm ngày, ta cũng không thấy từ đó có điều gì đáng sợ.",
  "mn19:9-10.9": "Nhưng này các Tỳ Kheo, nếu ta cứ suy xét và xem kỹ quá lâu, thân ta sẽ mệt.",
  "mn19:9-10.10": "Khi thân mệt, tâm sẽ bị căng ra.",
  "mn19:9-10.11": "Khi tâm bị căng ra, tâm sẽ xa khỏi sự yên vững.",
  "mn19:9-10.12": "Vì vậy, này các Tỳ Kheo, ta làm cho tâm mình đứng yên ở bên trong, lắng xuống, gom lại thành một, và giữ cho vững.",
  "mn19:9-10.13": "Vì sao vậy?",
  "mn19:9-10.14": "Để tâm ta không bị căng ra.",
  "mn19:11.1": "Này các Tỳ Kheo, Tỳ Kheo thường suy nghĩ và xem kỹ điều gì nhiều, thì tâm sẽ nghiêng theo điều ấy.",
  "mn19:11.2": "Này các Tỳ Kheo, nếu Tỳ Kheo thường suy nghĩ và xem kỹ nhiều về sự lìa bỏ, đã dứt bỏ suy nghĩ về ham muốn giác quan, và làm cho suy nghĩ về sự lìa bỏ thành nhiều, thì tâm vị ấy sẽ nghiêng về sự lìa bỏ.",
  "mn19:11.3": "Này các Tỳ Kheo, nếu Tỳ Kheo thường suy nghĩ và xem kỹ nhiều về lòng không ác ý …",
  "mn19:11.4": "Này các Tỳ Kheo, nếu Tỳ Kheo thường suy nghĩ và xem kỹ nhiều về lòng không làm hại, đã dứt bỏ suy nghĩ làm hại, và làm cho suy nghĩ không làm hại thành nhiều, thì tâm vị ấy sẽ nghiêng về lòng không làm hại.",
  "mn19:12.1": "Ví như này các Tỳ Kheo, vào tháng cuối mùa nóng, khi mọi ruộng lúa đều đã được gom vào gần làng, một người chăn bò giữ đàn bò; khi người ấy ở dưới gốc cây hay ở chỗ trống, điều cần luôn nhớ rõ chỉ là:",
  "mn19:12.2": "‘Đây là đàn bò’.",
  "mn19:12.3": "Cũng vậy, này các Tỳ Kheo, điều ta cần luôn nhớ rõ chỉ là:",
  "mn19:12.4": "‘Đây là những điều ấy’.",
  "mn19:13.1": "Này các Tỳ Kheo, sức gắng của ta đã được khơi dậy, không chùng xuống; sự nhớ biết rõ được dựng lên, không quên mất; thân lắng dịu, không bồn chồn; tâm yên vững, gom vào một mối.",
  "mn19:14.1": "Này các Tỳ Kheo, rồi ta lìa các ham muốn giác quan, lìa các điều xấu ác, vào và an trú tầng lặng sâu thứ nhất, có suy xét và xem kỹ, có niềm vui và sự dễ chịu sinh từ sự lìa ra.",
  "mn19:15.1": "Khi suy xét và xem kỹ lắng xuống, bên trong trong sáng, tâm gom thành một mối, không còn suy xét, không còn xem kỹ, có niềm vui và sự dễ chịu sinh từ tâm yên vững, ta vào và an trú tầng lặng sâu thứ hai.",
  "mn19:16.1": "Khi niềm vui lắng xuống, ta ở với tâm bình thản, nhớ biết rõ và tỉnh táo, cảm nhận sự dễ chịu nơi thân; ta vào và an trú tầng lặng sâu thứ ba, trạng thái mà những bậc cao quý nói rằng: ‘Người giữ tâm bình thản, nhớ biết rõ, sống dễ chịu’.",
  "mn19:17.1": "Khi bỏ sự dễ chịu và bỏ sự đau đớn, khi niềm mừng và nỗi buồn đã lặng mất từ trước, ta vào và an trú tầng lặng sâu thứ tư, không khổ không vui, trong sạch nhờ tâm bình thản và nhớ biết rõ.",
  "mn19:18.1": "Khi tâm như vậy đã yên vững, trong sạch, sáng trong, không nhơ bợn, sạch mọi cấu bẩn, mềm mại, dễ dùng, đứng vững, đạt tới không lay động, ta hướng tâm đến sự hiểu rõ nhớ lại các đời sống trước.",
  "mn19:18.2": "Ta nhớ lại nhiều đời sống trước với nhiều cách khác nhau. Nghĩa là: một đời sống … nhớ lại nhiều đời sống trước với từng nét và từng việc như vậy.",
  "mn19:19.1": "Này các Tỳ Kheo, đó là sự hiểu rõ thứ nhất mà ta đạt được vào canh đầu của đêm.",
  "mn19:19.2": "Sự không biết bị xua tan, sự hiểu rõ sinh ra; bóng tối bị xua tan, ánh sáng hiện ra; đúng như với người sống không buông lung, hết lòng, một dạ chuyên tâm.",
  "mn19:20.1": "Khi tâm như vậy đã yên vững, trong sạch, sáng trong, không nhơ bợn, sạch mọi cấu bẩn, mềm mại, dễ dùng, đứng vững, đạt tới không lay động, ta hướng tâm đến sự hiểu rõ về chúng sinh chết đi và sinh ra trở lại.",
  "mn19:20.2": "Với mắt trời trong sạch, vượt khỏi mắt người thường, ta thấy chúng sinh chết đi, sinh ra trở lại … những chúng sinh này có việc làm xấu nơi thân … với mắt trời trong sạch, vượt khỏi mắt người thường, ta thấy chúng sinh chết đi, sinh ra trở lại, kẻ thấp người cao, kẻ đẹp người xấu, kẻ đi đến chỗ lành người đi đến chỗ dữ; ta hiểu rõ chúng sinh đi theo việc mình đã làm.",
  "mn19:21.1": "Này các Tỳ Kheo, đó là sự hiểu rõ thứ hai mà ta đạt được vào canh giữa của đêm.",
  "mn19:21.2": "Sự không biết bị xua tan, sự hiểu rõ sinh ra; bóng tối bị xua tan, ánh sáng hiện ra; đúng như với người sống không buông lung, hết lòng, một dạ chuyên tâm.",
  "mn19:22.1": "Khi tâm ta được gom lại như vậy, trong sạch, sáng trong, không còn vết nhơ, sạch mọi bợn dơ, mềm mại, dễ dùng, vững chắc, không lay động, ta hướng tâm đến sự hiểu rõ việc dứt sạch các dòng rỉ chảy.",
  "mn19:22.2": "Ta đã biết đúng như thật: ‘Đây là sự khổ đau’; ta đã biết đúng như thật: ‘Đây là nguồn gốc của sự khổ đau’; ta đã biết đúng như thật: ‘Đây là sự dứt của sự khổ đau’; ta đã biết đúng như thật: ‘Đây là con đường đưa đến sự dứt của sự khổ đau’.",
  "mn19:23.1": "Ta đã biết đúng như thật: ‘Đây là các dòng rỉ chảy’; ta đã biết đúng như thật: ‘Đây là nguồn gốc của các dòng rỉ chảy’; ta đã biết đúng như thật: ‘Đây là sự dứt của các dòng rỉ chảy’; ta đã biết đúng như thật: ‘Đây là con đường đưa đến sự dứt của các dòng rỉ chảy’.",
  "mn19:23.2": "Khi ta biết như vậy, thấy như vậy, tâm ta được buông khỏi dòng rỉ chảy do ham muốn giác quan, cũng được buông khỏi dòng rỉ chảy của sự hiện hữu, cũng được buông khỏi dòng rỉ chảy do không sáng biết. Khi tâm đã được buông ra, sự hiểu biết khởi lên: ‘Tâm đã được buông ra’.",
  "mn19:23.3": "Ta biết rõ: ‘Sự sinh đã dứt, đời sống phạm hạnh đã sống xong, việc cần làm đã làm xong, không còn trở lui trạng thái này nữa’.",
  "mn19:24.1": "Này các Tỳ Kheo, đó là sự biết rõ thứ ba mà ta đạt được vào canh cuối của đêm.",
  "mn19:24.2": "Sự không sáng biết bị xua tan, sự sáng biết khởi lên; bóng tối bị xua tan, ánh sáng khởi lên; đúng như với người sống không buông lung, siêng năng, dốc lòng.",
  "mn19:25.1": "Ví như, này các Tỳ Kheo, trong rừng núi có một vũng nước lớn ở chỗ đất trũng.",
  "mn19:25.2": "Một bầy nai lớn nương vào đó mà sống.",
  "mn19:25.3": "Rồi có một người xuất hiện, mong điều hại, mong điều không tốt, mong chúng không được yên ổn an lành.",
  "mn19:25.4": "Người ấy chặn mất con đường an toàn, tốt lành, đưa đến chỗ vui sống của chúng; lại mở ra đường xấu, đặt bẫy, và cắt người canh bẫy ở đó.",
  "mn19:25.5": "Làm như vậy, này các Tỳ Kheo, sau một thời gian bầy nai lớn ấy sẽ gặp tai hại và suy sụp.",
  "mn19:25.6": "Nhưng rồi, này các Tỳ Kheo, lại có một người khác xuất hiện vì điều tốt, vì điều lành, mong chúng được yên ổn an lành.",
  "mn19:25.7": "Người ấy mở ra con đường an toàn, tốt lành, đưa đến chỗ vui sống của chúng; chặn đường xấu, phá bỏ bẫy, và đuổi kẻ canh bẫy đi.",
  "mn19:25.8": "Làm như vậy, này các Tỳ Kheo, sau một thời gian bầy nai lớn ấy sẽ tăng thêm, lớn mạnh, đông lên.",
  "mn19:26.1": "Này các Tỳ Kheo, ví dụ này ta nêu ra để làm rõ ý nghĩa.",
  "mn19:26.2": "Ý nghĩa ở đây là như sau:",
  "mn19:26.3": "‘Vũng nước lớn ở chỗ đất trũng’, này các Tỳ Kheo, là cách gọi các thú vui giác quan.",
  "mn19:26.4": "‘Bầy nai lớn’, này các Tỳ Kheo, là cách gọi các loài sống.",
  "mn19:26.5": "‘Người mong điều hại, mong điều không tốt, mong không được yên ổn an lành’, này các Tỳ Kheo, là cách gọi Ma vương xấu ác.",
  "mn19:26.6": "‘Đường xấu’, này các Tỳ Kheo, là cách gọi con đường sai lạc gồm tám phần, đó là:",
  "mn19:26.7": "thấy sai, nghĩ sai, nói sai, làm sai, sống sai, gắng sức sai, nhớ biết sai, tâm yên vững sai.",
  "mn19:26.8": "‘Bẫy’, này các Tỳ Kheo, là cách gọi sự thích thú và dính mắc.",
  "mn19:26.9": "‘Kẻ canh bẫy’, này các Tỳ Kheo, là cách gọi sự không sáng biết.",
  "mn19:26.10": "‘Người vì điều tốt, vì điều lành, mong được yên ổn an lành’, này các Tỳ Kheo, là cách gọi Như Lai, bậc đáng kính, bậc tự mình biết trọn vẹn.",
  "mn19:26.11": "‘Con đường an toàn, tốt lành, đưa đến chỗ vui sống’, này các Tỳ Kheo, là cách gọi con đường thánh gồm tám phần, đó là:",
  "mn19:26.12": "thấy đúng, nghĩ đúng, nói đúng, làm đúng, sống đúng, gắng sức đúng, nhớ biết đúng, tâm yên vững đúng.",
  "mn19:26.13": "Vậy nên, này các Tỳ Kheo, con đường an toàn, tốt lành, đưa đến chỗ vui sống đã được ta mở ra; đường xấu đã bị chặn; bẫy đã bị phá; kẻ canh bẫy đã bị đuổi đi.",
  "mn19:27.1": "Này các Tỳ Kheo, điều gì một bậc thầy cần làm cho các học trò vì lòng thương, vì muốn điều lành cho họ, thì ta đã làm cho các ông.",
  "mn19:27.2": "Này các Tỳ Kheo, đây là gốc cây, đây là nhà trống; hãy ngồi yên nhìn sâu, chớ buông lung; chớ để về sau phải hối tiếc. Đó là lời dạy của ta cho các ông.",
  "mn19:27.3": "Đức Thế Tôn nói như vậy.",
  "mn19:27.4": "Các Tỳ Kheo vui mừng, ưa thích lời Đức Thế Tôn đã nói.",
  "mn19:27.5": "Bài kinh Hai loại suy nghĩ đến đây là xong, bài thứ chín."
}
window.BILARA["mn19"]["vi"]["mn19:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";