window.BILARA = window.BILARA || {};
window.BILARA["mn24"] = window.BILARA["mn24"] || {};
window.BILARA["mn24"]["vi"] = {
  "mn24:0.1": "Trung Bộ Kinh 24",
  "mn24:0.2": "Kinh Cỗ Xe Chuyển Tiếp",
  "mn24:1.1": "Tôi nghe như vầy—",
  "mn24:1.2": "Một thời, Đức Thế Tôn ở Vương Xá, trong rừng Trúc, tại chỗ cho sóc ăn.",
  "mn24:2.1": "Bấy giờ, nhiều Tỳ Kheo quê ở Jātibhūmi, sau khi ở yên một chỗ suốt mùa mưa tại Jātibhūmi, đã đến gặp Đức Thế Tôn. Đến rồi, họ kính lễ Đức Thế Tôn và ngồi xuống một bên. Khi họ đã ngồi xuống một bên, Đức Thế Tôn nói với họ:",
  "mn24:2.2": "“Này các Tỳ Kheo, ở Jātibhūmi, trong các Tỳ Kheo là bạn sống đời trong sạch với nhau, ai được xem là người như vầy:",
  "mn24:2.3": "‘Tự mình ít ham muốn, lại nói với các Tỳ Kheo về sự ít ham muốn; tự mình biết đủ, lại nói với các Tỳ Kheo về sự biết đủ; tự mình sống riêng vắng, lại nói với các Tỳ Kheo về sự sống riêng vắng; tự mình không dính mắc, lại nói với các Tỳ Kheo về sự không dính mắc; tự mình siêng năng gắng sức, lại nói với các Tỳ Kheo về việc khởi sức tinh cần; tự mình giữ nết tốt trọn vẹn, lại nói với các Tỳ Kheo về sự trọn vẹn trong nết sống; tự mình có tâm yên vững trọn vẹn, lại nói với các Tỳ Kheo về sự trọn vẹn của tâm yên vững; tự mình hiểu rõ trọn vẹn, lại nói với các Tỳ Kheo về sự trọn vẹn của hiểu rõ; tự mình được buông thoát trọn vẹn, lại nói với các Tỳ Kheo về sự trọn vẹn của buông thoát; tự mình trọn vẹn trong thấy biết rằng mình đã buông thoát, lại nói với các Tỳ Kheo về sự trọn vẹn của thấy biết buông thoát; là người khuyên dạy, chỉ bày, làm cho thấy rõ, dẫn dắt, khích lệ, làm cho vui lòng các bạn sống đời trong sạch’?”",
  "mn24:2.4": "“Bạch Thế Tôn, có vị tên là Tôn giả Puṇṇa, con bà Mantāṇī. Ở Jātibhūmi, trong các Tỳ Kheo là bạn sống đời trong sạch với nhau, vị ấy được xem là người như vầy:",
  "mn24:2.5": "‘Tự mình ít ham muốn, lại nói với các Tỳ Kheo về sự ít ham muốn; tự mình biết đủ … là người khuyên dạy, chỉ bày, làm cho thấy rõ, dẫn dắt, khích lệ, làm cho vui lòng các bạn sống đời trong sạch.’",
  "mn24:3.1": "Lúc ấy, Tôn giả Sāriputta đang ngồi không xa Đức Thế Tôn.",
  "mn24:3.2": "Rồi Tôn giả Sāriputta nghĩ như vầy:",
  "mn24:3.3": "“Thật là điều tốt cho Tôn giả Puṇṇa, con bà Mantāṇī, thật khéo được điều tốt cho Tôn giả Puṇṇa, con bà Mantāṇī,",
  "mn24:3.4": "vì các bạn sống đời trong sạch có hiểu biết, ngay trước mặt bậc Thầy, cứ nhắc đi nhắc lại lời khen về vị ấy, và bậc Thầy cũng tán thành điều đó.",
  "mn24:3.5": "Mong sao một lúc nào đó, ta cũng được gặp Tôn giả Puṇṇa, con bà Mantāṇī; mong sao sẽ có dịp cùng nói chuyện.”",
  "mn24:4.1": "Rồi Đức Thế Tôn, sau khi ở tại Vương Xá lâu chừng nào Ngài thấy vừa ý, đã lên đường đi đến Xá Vệ.",
  "mn24:4.2": "Đi dần từng chặng, Ngài đến Xá Vệ.",
  "mn24:4.3": "Tại đó, Đức Thế Tôn ở Xá Vệ, trong Kỳ Viên, khu vườn của ông Cấp Cô Độc.",
  "mn24:4.4": "Tôn giả Puṇṇa, con bà Mantāṇī, nghe tin: “Nghe nói Đức Thế Tôn đã đến Xá Vệ; hiện đang ở Xá Vệ, trong Kỳ Viên, khu vườn của ông Cấp Cô Độc.”",
  "mn24:5.1": "Rồi Tôn giả Puṇṇa, con bà Mantāṇī, dọn dẹp chỗ ở, mang theo bát và y, lên đường đi đến Xá Vệ.",
  "mn24:5.2": "Đi dần từng chặng, vị ấy đến Xá Vệ, đến Kỳ Viên, khu vườn của ông Cấp Cô Độc, đến gặp Đức Thế Tôn. Đến rồi, vị ấy kính lễ Đức Thế Tôn và ngồi xuống một bên.",
  "mn24:5.3": "Khi Tôn giả Puṇṇa, con bà Mantāṇī, ngồi xuống một bên, Đức Thế Tôn đã dùng lời dạy đúng lẽ mà chỉ rõ, khuyên nhủ, khích lệ, làm cho vui lòng vị ấy.",
  "mn24:5.4": "Rồi Tôn giả Puṇṇa, con bà Mantāṇī, sau khi được Đức Thế Tôn dùng lời dạy đúng lẽ chỉ rõ, khuyên nhủ, khích lệ, làm cho vui lòng, đã hoan hỷ nhận lời Đức Thế Tôn dạy, đứng dậy khỏi chỗ ngồi, kính lễ Đức Thế Tôn, đi quanh Ngài về phía phải rồi đi đến rừng Mù để nghỉ ban ngày.",
  "mn24:6.1": "Bấy giờ, có một Tỳ Kheo đến gặp Tôn giả Sāriputta. Đến rồi, vị ấy nói với Tôn giả Sāriputta:",
  "mn24:6.2": "“Này hiền giả Sāriputta, vị Tỳ Kheo tên Puṇṇa, con bà Mantāṇī, người mà hiền giả thường luôn khen ngợi, đã được Đức Thế Tôn dùng lời dạy đúng lẽ chỉ rõ, khuyên nhủ, khích lệ, làm cho vui lòng. Sau khi hoan hỷ nhận lời Đức Thế Tôn dạy, vị ấy đã đứng dậy khỏi chỗ ngồi, kính lễ Đức Thế Tôn, đi quanh Ngài về phía phải rồi đi đến rừng Mù để nghỉ ban ngày.”",
  "mn24:7.1": "Rồi Tôn giả Sāriputta, như người đang vội, cầm tấm tọa cụ lên, đi theo sau Tôn giả Puṇṇa, con bà Mantāṇī, mắt luôn nhìn theo bóng đầu vị ấy.",
  "mn24:7.2": "Rồi Tôn giả Puṇṇa, con bà Mantāṇī, đi sâu vào rừng Mù và ngồi nghỉ ban ngày dưới một gốc cây nào đó.",
  "mn24:7.3": "Tôn giả Sāriputta cũng đi sâu vào rừng Mù và ngồi nghỉ ban ngày dưới một gốc cây nào đó.",
  "mn24:8.1": "Rồi Tôn giả Sāriputta, vào buổi chiều, sau khi ra khỏi chỗ ngồi yên một mình, đã đến gặp Tôn giả Puṇṇa, con bà Mantāṇī. Đến rồi, ngài cùng Tôn giả Puṇṇa, con bà Mantāṇī, chào hỏi thân tình.",
  "mn24:8.2": "Sau khi nói với nhau những lời thân tình, gợi nhớ điều đáng nhớ, ngài ngồi xuống một bên. Khi đã ngồi xuống một bên, Tôn giả Sāriputta nói với Tôn giả Puṇṇa, con bà Mantāṇī:",
  "mn24:9.1": "“Này hiền giả, có phải chúng ta sống đời trong sạch dưới Đức Thế Tôn không?”",
  "mn24:9.2": "“Vâng, này hiền giả.”",
  "mn24:9.3": "“Này hiền giả, có phải sống đời sống trong sạch dưới Đức Thế Tôn là để làm cho nết ở nên trong sạch không?”",
  "mn24:9.4": "“Không phải vậy, này hiền giả.”",
  "mn24:9.5": "“Này hiền giả, vậy có phải sống đời sống trong sạch dưới Đức Thế Tôn là để làm cho lòng nên trong sạch không?”",
  "mn24:9.6": "“Không phải vậy, này hiền giả.”",
  "mn24:9.7": "“Này hiền giả, có phải sống đời sống trong sạch dưới Đức Thế Tôn là để làm cho cái thấy nên trong sạch không?”",
  "mn24:9.8": "“Không phải vậy, này hiền giả.”",
  "mn24:9.9": "“Này hiền giả, vậy có phải sống đời sống trong sạch dưới Đức Thế Tôn là để vượt qua ngờ vực và được trong sạch không?”",
  "mn24:9.10": "“Không phải vậy, này hiền giả.”",
  "mn24:9.11": "“Này hiền giả, có phải sống đời sống trong sạch dưới Đức Thế Tôn là để biết rõ và thấy rõ đâu là đường, đâu không phải đường, và nhờ đó được trong sạch không?”",
  "mn24:9.12": "“Không phải vậy, này hiền giả.”",
  "mn24:9.13": "“Này hiền giả, vậy có phải sống đời sống trong sạch dưới Đức Thế Tôn là để biết rõ và thấy rõ đường thực hành, và nhờ đó được trong sạch không?”",
  "mn24:9.14": "“Không phải vậy, này hiền giả.”",
  "mn24:9.15": "“Này hiền giả, có phải sống đời sống trong sạch dưới Đức Thế Tôn là để biết rõ và thấy rõ, và nhờ đó được trong sạch không?”",
  "mn24:9.16": "“Không phải vậy, này hiền giả.”",
  "mn24:10.1": "“Khi được hỏi: ‘Này hiền giả, có phải sống đời sống trong sạch dưới Đức Thế Tôn là để làm cho nết ở nên trong sạch không?’, hiền giả đáp: ‘Không phải vậy, này hiền giả.’",
  "mn24:10.2": "Khi được hỏi: ‘Này hiền giả, vậy có phải sống đời sống trong sạch dưới Đức Thế Tôn là để làm cho lòng nên trong sạch không?’, hiền giả đáp: ‘Không phải vậy, này hiền giả.’",
  "mn24:10.3": "Khi được hỏi: ‘Này hiền giả, có phải sống đời sống trong sạch dưới Đức Thế Tôn là để làm cho cái thấy nên trong sạch không?’ …",
  "mn24:10.4": "‘là để vượt qua ngờ vực và được trong sạch không?’ …",
  "mn24:10.5": "‘là để biết rõ và thấy rõ đâu là đường, đâu không phải đường, và nhờ đó được trong sạch không?’ …",
  "mn24:10.6": "‘là để biết rõ và thấy rõ đường thực hành, và nhờ đó được trong sạch không?’ …",
  "mn24:10.7": "khi được hỏi: ‘Này hiền giả, có phải sống đời sống trong sạch dưới Đức Thế Tôn là để biết rõ và thấy rõ, và nhờ đó được trong sạch không?’, hiền giả đáp: ‘Không phải vậy, này hiền giả.’",
  "mn24:10.8": "Vậy thì, này hiền giả, sống đời sống trong sạch dưới Đức Thế Tôn là vì mục đích gì?”",
  "mn24:10.9": "“Này hiền giả, sống đời sống trong sạch dưới Đức Thế Tôn là để tắt hẳn do không còn nắm giữ.”",
  "mn24:11.1": "“Này hiền giả, vậy nết ở trong sạch có phải là sự tắt hẳn do không còn nắm giữ không?”",
  "mn24:11.2": "“Không phải vậy, này hiền giả.”",
  "mn24:11.3": "“Này hiền giả, vậy lòng trong sạch có phải là sự tắt hẳn do không còn nắm giữ không?”",
  "mn24:11.4": "“Không phải vậy, này hiền giả.”",
  "mn24:11.5": "“Này hiền giả, vậy cái thấy trong sạch có phải là sự tắt hẳn do không còn nắm giữ không?”",
  "mn24:11.6": "“Không phải vậy, này hiền giả.”",
  "mn24:11.7": "“Này hiền giả, vậy thì sự trong sạch do vượt qua ngờ vực có phải là tắt hẳn vì không còn nắm giữ không?”",
  "mn24:11.8": "“Không phải vậy, hiền giả.”",
  "mn24:11.9": "“Này hiền giả, vậy thì sự trong sạch do biết rõ và thấy rõ đâu là đường, đâu không phải đường có phải là tắt hẳn vì không còn nắm giữ không?”",
  "mn24:11.10": "“Không phải vậy, hiền giả.”",
  "mn24:11.11": "“Này hiền giả, vậy thì sự trong sạch do biết rõ và thấy rõ về cách thực hành có phải là tắt hẳn vì không còn nắm giữ không?”",
  "mn24:11.12": "“Không phải vậy, hiền giả.”",
  "mn24:11.13": "“Này hiền giả, vậy thì sự trong sạch do biết rõ và thấy rõ có phải là tắt hẳn vì không còn nắm giữ không?”",
  "mn24:11.14": "“Không phải vậy, hiền giả.”",
  "mn24:11.15": "“Này hiền giả, vậy thì tắt hẳn vì không còn nắm giữ có ở ngoài những điều này không?”",
  "mn24:11.16": "“Không phải vậy, hiền giả.”",
  "mn24:12.1": "“Khi được hỏi: ‘Này hiền giả, sự trong sạch về nết ở có phải là tắt hẳn vì không còn nắm giữ không?’, hiền giả đã đáp: ‘Không phải vậy, hiền giả.’",
  "mn24:12.2": "Khi được hỏi: ‘Này hiền giả, sự trong sạch của tâm có phải là tắt hẳn vì không còn nắm giữ không?’, hiền giả đã đáp: ‘Không phải vậy, hiền giả.’",
  "mn24:12.3": "Khi được hỏi: ‘Này hiền giả, sự trong sạch về cái thấy có phải là tắt hẳn vì không còn nắm giữ không?’ …",
  "mn24:12.4": "sự trong sạch do vượt qua ngờ vực …",
  "mn24:12.5": "sự trong sạch do biết rõ và thấy rõ đâu là đường, đâu không phải đường …",
  "mn24:12.6": "sự trong sạch do biết rõ và thấy rõ về cách thực hành …",
  "mn24:12.7": "Khi được hỏi: ‘Này hiền giả, sự trong sạch do biết rõ và thấy rõ có phải là tắt hẳn vì không còn nắm giữ không?’, hiền giả đã đáp: ‘Không phải vậy, hiền giả.’",
  "mn24:12.8": "Khi được hỏi: ‘Này hiền giả, vậy thì tắt hẳn vì không còn nắm giữ có ở ngoài những điều này không?’, hiền giả đã đáp: ‘Không phải vậy, hiền giả.’",
  "mn24:12.9": "Vậy thì, này hiền giả, lời nói ấy nên được hiểu ra sao?”",
  "mn24:13.1": "“Này hiền giả, nếu Đức Thế Tôn nói rằng sự trong sạch về nết ở là tắt hẳn vì không còn nắm giữ, thì như vậy Ngài đã nói rằng tắt hẳn vì không còn nắm giữ vẫn còn nắm giữ.",
  "mn24:13.2": "Này hiền giả, nếu Đức Thế Tôn nói rằng sự trong sạch của tâm là tắt hẳn vì không còn nắm giữ, thì như vậy Ngài đã nói rằng tắt hẳn vì không còn nắm giữ vẫn còn nắm giữ.",
  "mn24:13.3": "Này hiền giả, nếu Đức Thế Tôn nói rằng sự trong sạch về cái thấy là tắt hẳn vì không còn nắm giữ, thì như vậy Ngài đã nói rằng tắt hẳn vì không còn nắm giữ vẫn còn nắm giữ.",
  "mn24:13.4": "Này hiền giả, nếu Đức Thế Tôn nói rằng sự trong sạch do vượt qua ngờ vực là tắt hẳn vì không còn nắm giữ, thì như vậy Ngài đã nói rằng tắt hẳn vì không còn nắm giữ vẫn còn nắm giữ.",
  "mn24:13.5": "Này hiền giả, nếu Đức Thế Tôn nói rằng sự trong sạch do biết rõ và thấy rõ đâu là đường, đâu không phải đường là tắt hẳn vì không còn nắm giữ, thì như vậy Ngài đã nói rằng tắt hẳn vì không còn nắm giữ vẫn còn nắm giữ.",
  "mn24:13.6": "Này hiền giả, nếu Đức Thế Tôn nói rằng sự trong sạch do biết rõ và thấy rõ về cách thực hành là tắt hẳn vì không còn nắm giữ, thì như vậy Ngài đã nói rằng tắt hẳn vì không còn nắm giữ vẫn còn nắm giữ.",
  "mn24:13.7": "Này hiền giả, nếu Đức Thế Tôn nói rằng sự trong sạch do biết rõ và thấy rõ là tắt hẳn vì không còn nắm giữ, thì như vậy Ngài đã nói rằng tắt hẳn vì không còn nắm giữ vẫn còn nắm giữ.",
  "mn24:13.8": "Này hiền giả, nếu tắt hẳn vì không còn nắm giữ có ở ngoài những điều này, thì người thường cũng có thể tắt hẳn.",
  "mn24:13.9": "Vì người thường, này hiền giả, là ở ngoài những điều này.",
  "mn24:14.1": "Vậy nên, này hiền giả, tôi sẽ nêu cho hiền giả một ví dụ;",
  "mn24:14.2": "vì nhờ ví dụ, có những người sáng dạ hiểu được ý nghĩa của lời nói.”",
  "mn24:14.3": "Ví như, này hiền giả, vua Ba-tư-nặc nước Kosala đang ở Xá-vệ, bỗng có việc gấp cần làm ở Sāketa.",
  "mn24:14.4": "Người ta sẽ cho sẵn bảy cỗ xe thay đổi dọc đường giữa Xá-vệ và Sāketa.",
  "mn24:14.5": "Rồi này hiền giả, vua Ba-tư-nặc nước Kosala rời Xá-vệ, từ cổng cung trong bước lên cỗ xe thứ nhất; đi bằng cỗ xe thứ nhất đến cỗ xe thứ hai, bỏ cỗ xe thứ nhất lại rồi bước lên cỗ xe thứ hai.",
  "mn24:14.6": "Đi bằng cỗ xe thứ hai đến cỗ xe thứ ba, bỏ cỗ xe thứ hai lại rồi bước lên cỗ xe thứ ba.",
  "mn24:14.7": "Đi bằng cỗ xe thứ ba đến cỗ xe thứ tư, bỏ cỗ xe thứ ba lại rồi bước lên cỗ xe thứ tư.",
  "mn24:14.8": "Đi bằng cỗ xe thứ tư đến cỗ xe thứ năm, bỏ cỗ xe thứ tư lại rồi bước lên cỗ xe thứ năm.",
  "mn24:14.9": "Đi bằng cỗ xe thứ năm đến cỗ xe thứ sáu, bỏ cỗ xe thứ năm lại rồi bước lên cỗ xe thứ sáu.",
  "mn24:14.10": "Đi bằng cỗ xe thứ sáu đến cỗ xe thứ bảy, bỏ cỗ xe thứ sáu lại rồi bước lên cỗ xe thứ bảy.",
  "mn24:14.11": "Đi bằng cỗ xe thứ bảy, nhà vua sẽ đến Sāketa, tới cổng cung trong.",
  "mn24:14.12": "Khi nhà vua đã tới cổng cung trong, bạn bè, quan lại, bà con ruột thịt sẽ hỏi như vầy:",
  "mn24:14.13": "‘Thưa đại vương, có phải ngài đã đi từ Xá-vệ đến Sāketa, tới cổng cung trong, bằng chính cỗ xe này không?’",
  "mn24:14.14": "Này hiền giả, nếu vua Ba-tư-nặc nước Kosala trả lời đúng, thì sẽ trả lời thế nào?”",
  "mn24:14.15": "“Này hiền giả, nếu vua Ba-tư-nặc nước Kosala trả lời đúng, thì sẽ trả lời như vầy:",
  "mn24:14.16": "‘Khi ta đang ở Xá-vệ, có việc gấp cần làm ở Sāketa.",
  "mn24:14.17": "Vì việc ấy, người ta đã cho sẵn bảy cỗ xe thay đổi dọc đường giữa Xá-vệ và Sāketa.",
  "mn24:14.18": "Rồi ta rời Xá-vệ, từ cổng cung trong bước lên cỗ xe thứ nhất.",
  "mn24:14.19": "Đi bằng cỗ xe thứ nhất đến cỗ xe thứ hai, ta bỏ cỗ xe thứ nhất lại rồi bước lên cỗ xe thứ hai.",
  "mn24:14.20": "Đi bằng cỗ xe thứ hai đến cỗ xe thứ ba, ta bỏ cỗ xe thứ hai lại rồi bước lên cỗ xe thứ ba.",
  "mn24:14.21": "Đi bằng cỗ xe thứ ba đến cỗ xe thứ tư, ta bỏ cỗ xe thứ ba lại rồi bước lên cỗ xe thứ tư.",
  "mn24:14.22": "Đi bằng cỗ xe thứ tư đến cỗ xe thứ năm, ta bỏ cỗ xe thứ tư lại rồi bước lên cỗ xe thứ năm.",
  "mn24:14.23": "Đi bằng cỗ xe thứ năm đến cỗ xe thứ sáu, ta bỏ cỗ xe thứ năm lại rồi bước lên cỗ xe thứ sáu.",
  "mn24:14.24": "Đi bằng cỗ xe thứ sáu đến cỗ xe thứ bảy, ta bỏ cỗ xe thứ sáu lại rồi bước lên cỗ xe thứ bảy.",
  "mn24:14.25": "Đi bằng cỗ xe thứ bảy, ta đã đến Sāketa, tới cổng cung trong.’",
  "mn24:14.26": "Này hiền giả, nếu vua Ba-tư-nặc nước Kosala trả lời như vậy, thì là trả lời đúng.”",
  "mn24:15.1": "“Cũng vậy, này hiền giả, sự trong sạch về nết ở chỉ nhằm đưa đến sự trong sạch của tâm; sự trong sạch của tâm chỉ nhằm đưa đến sự trong sạch của cái thấy; sự trong sạch của cái thấy chỉ nhằm đưa đến sự trong sạch do vượt qua ngờ vực; sự trong sạch do vượt qua ngờ vực chỉ nhằm đưa đến sự trong sạch của thấy biết rõ đâu là đường, đâu không phải đường; sự trong sạch của thấy biết rõ đâu là đường, đâu không phải đường chỉ nhằm đưa đến sự trong sạch của thấy biết rõ về cách đi; sự trong sạch của thấy biết rõ về cách đi chỉ nhằm đưa đến sự trong sạch của thấy biết rõ; sự trong sạch của thấy biết rõ chỉ nhằm đưa đến tắt hẳn hoàn toàn vì không còn nắm giữ gì nữa.",
  "mn24:15.2": "Này hiền giả, đời sống trong sạch được sống dưới Đức Thế Tôn là vì tắt hẳn hoàn toàn do không còn nắm giữ gì nữa.”",
  "mn24:16.1": "Khi được nói vậy, ngài Xá-lợi-phất nói với ngài Puṇṇa, con bà Mantāṇī:",
  "mn24:16.2": "“Hiền giả tên là gì, và các bạn cùng sống đời trong sạch biết hiền giả là ai?”",
  "mn24:16.3": "“Này hiền giả, tên tôi là Puṇṇa;",
  "mn24:16.4": "và các bạn cùng sống đời trong sạch biết tôi là con bà Mantāṇī.”",
  "mn24:16.5": "“Lạ thay, này hiền giả, thật ít có thay, này hiền giả.",
  "mn24:16.6": "Đúng như một người học rộng, là đệ tử, hiểu đúng trọn vẹn lời dạy của bậc thầy, thì Tỳ Kheo Puṇṇa, con bà Mantāṇī, cũng đã lần theo từng ý mà trả lời những câu hỏi sâu kín, khó dò như vậy.",
  "mn24:16.7": "Các bạn sống chung phạm hạnh thật có phước, thật khéo được phước,",
  "mn24:16.8": "vì được gặp Tỳ Kheo Puṇṇa, con bà Mantāṇī, được đến gần để ngồi bên học hỏi.",
  "mn24:16.9": "Dù các bạn sống chung phạm hạnh có phải đội Tỳ Kheo Puṇṇa, con bà Mantāṇī, trên đầu bằng một tấm vải mà mới được gặp, mới được đến gần để ngồi bên học hỏi, thì với họ cũng vẫn là có phước, cũng vẫn là khéo được phước. Còn chúng tôi cũng có phước, cũng khéo được phước, vì chúng tôi được gặp Tỳ Kheo Puṇṇa, con bà Mantāṇī, được đến gần để ngồi bên học hỏi.”",
  "mn24:17.1": "Khi được nói vậy, Tỳ Kheo Puṇṇa, con bà Mantāṇī, nói với Tỳ Kheo Sāriputta rằng:",
  "mn24:17.2": "“Hiền giả tên là gì, và các bạn sống chung phạm hạnh biết hiền giả bằng tên nào?”",
  "mn24:17.3": "“Này hiền giả, tên tôi là Upatissa;",
  "mn24:17.4": "còn các bạn sống chung phạm hạnh biết tôi là Sāriputta.”",
  "mn24:17.5": "“Thì ra chúng tôi lại đang cùng nói chuyện với một vị đệ tử giống như bậc thầy mà không biết rằng:",
  "mn24:17.6": "‘đó là Tỳ Kheo Sāriputta’.",
  "mn24:17.7": "Nếu chúng tôi biết ‘đó là Tỳ Kheo Sāriputta’ thì chúng tôi đã không nói ra được đến chừng ấy.",
  "mn24:17.8": "Lạ thay, này hiền giả, thật ít có thay, này hiền giả.",
  "mn24:17.9": "Đúng như một người học rộng, là đệ tử, hiểu đúng trọn vẹn lời dạy của bậc thầy, thì Tỳ Kheo Sāriputta cũng đã lần theo từng ý mà hỏi những câu hỏi sâu kín, khó dò như vậy.",
  "mn24:17.10": "Các bạn sống chung phạm hạnh thật có phước, thật khéo được phước,",
  "mn24:17.11": "vì được gặp Tỳ Kheo Sāriputta, được đến gần để ngồi bên học hỏi.",
  "mn24:17.12": "Dù các bạn sống chung phạm hạnh có phải đội Tỳ Kheo Sāriputta trên đầu bằng một tấm vải mà mới được gặp, mới được đến gần để ngồi bên học hỏi, thì với họ cũng vẫn là có phước, cũng vẫn là khéo được phước. Còn chúng tôi cũng có phước, cũng khéo được phước, vì chúng tôi được gặp Tỳ Kheo Sāriputta, được đến gần để ngồi bên học hỏi.”",
  "mn24:17.13": "Thế là cả hai bậc lớn ấy đều vui lòng tán thành lời nói hay của nhau.",
  "mn24:17.14": "Kinh Cỗ Xe Chuyển Tiếp chấm dứt, bài thứ tư."
}
window.BILARA["mn24"]["vi"]["mn24:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";