window.BILARA = window.BILARA || {};
window.BILARA["mn26"] = window.BILARA["mn26"] || {};
window.BILARA["mn26"]["vi"] = {
  "mn26:0.1": "Trung Bộ Kinh 26 ",
  "mn26:0.2": "Kinh Đống Bẫy ",
  "mn26:1.1": "Tôi nghe như vầy—",
  "mn26:1.2": "Một thời Thế Tôn trú ở Sāvatthī (Xá-vệ), tại Jetavana (Kỳ-đà Lâm), trong vườn của Anāthapiṇḍika (Cấp Cô Độc). ",
  "mn26:2.1": "Rồi Thế Tôn vào buổi sáng, đắp y, cầm bát, đi vào Sāvatthī để khất thực. ",
  "mn26:2.2": "Rồi nhiều Tỳ-kheo đi đến chỗ Tôn giả Ānanda (A-nan); sau khi đến, các vị ấy nói với Tôn giả Ānanda: ",
  "mn26:2.3": "“Này Hiền giả Ānanda, đã lâu chúng tôi chưa được nghe Thế Tôn thuyết pháp trực tiếp. ",
  "mn26:2.4": "Lành thay, này Hiền giả Ānanda, chúng tôi được nghe Thế Tôn thuyết pháp trực tiếp.” ",
  "mn26:2.5": "“Vậy thì, này các Tôn giả, hãy đi đến tịnh xá của Bà-la-môn Rammaka; ",
  "mn26:2.6": "may ra các vị được nghe Thế Tôn thuyết pháp trực tiếp.” ",
  "mn26:2.7": "“Thưa Hiền giả,” các Tỳ-kheo ấy vâng lời Tôn giả Ānanda. ",
  "mn26:3.1": "Rồi Thế Tôn, sau khi khất thực ở Sāvatthī, sau bữa ăn, trở về từ cuộc khất thực, gọi Tôn giả Ānanda: ",
  "mn26:3.2": "“Này Ānanda, chúng ta hãy đi đến Pūbbārāma (Đông Viên), cung điện của Migāramātā (Mẫu Lộc), để nghỉ trưa.” ",
  "mn26:3.3": "“Thưa vâng, bạch Thế Tôn,” Tôn giả Ānanda vâng lời Thế Tôn. ",
  "mn26:3.4": "Rồi Thế Tôn cùng với Tôn giả Ānanda đi đến Pūbbārāma, cung điện của Migāramātā, để nghỉ trưa. ",
  "mn26:3.5": "Rồi Thế Tôn, vào buổi chiều, sau khi ra khỏi chỗ tĩnh cư, gọi Tôn giả Ānanda: ",
  "mn26:3.6": "“Này Ānanda, chúng ta hãy đi đến Pūbbakoṭṭhaka (Đông Cung) để tắm rửa thân thể.” ",
  "mn26:3.7": "“Thưa vâng, bạch Thế Tôn,” Tôn giả Ānanda vâng lời Thế Tôn. ",
  "mn26:3.8": "Rồi Thế Tôn cùng với Tôn giả Ānanda đi đến Pūbbakoṭṭhaka để tắm rửa thân thể. ",
  "mn26:3.9": "Sau khi tắm rửa thân thể ở Pūbbakoṭṭhaka, Thế Tôn đi lên, chỉ đắp một y, đứng phơi mình. ",
  "mn26:3.10": "Rồi Tôn giả Ānanda nói với Thế Tôn: ",
  "mn26:3.11": "“Bạch Thế Tôn, tịnh xá của Bà-la-môn Rammaka không xa. ",
  "mn26:3.12": "Bạch Thế Tôn, tịnh xá của Bà-la-môn Rammaka thật đẹp; ",
  "mn26:3.13": "bạch Thế Tôn, tịnh xá của Bà-la-môn Rammaka thật dễ chịu. ",
  "mn26:3.14": "Lành thay, bạch Thế Tôn, Thế Tôn hãy đi đến tịnh xá của Bà-la-môn Rammaka, vì lòng thương xót.” ",
  "mn26:3.15": "Thế Tôn im lặng chấp thuận. ",
  "mn26:4.1": "Rồi Thế Tôn đi đến tịnh xá của Bà-la-môn Rammaka. ",
  "mn26:4.2": "Lúc bấy giờ, nhiều Tỳ-kheo đang ngồi tụ họp trong tịnh xá của Bà-la-môn Rammaka để đàm luận về Pháp. ",
  "mn26:4.3": "Rồi Thế Tôn đứng ở ngoài cổng, chờ đợi cuộc đàm luận kết thúc. ",
  "mn26:4.4": "Rồi Thế Tôn, biết cuộc đàm luận đã kết thúc, liền ho khan và gõ cửa. ",
  "mn26:4.5": "Các Tỳ-kheo ấy liền mở cửa cho Thế Tôn. ",
  "mn26:4.6": "Rồi Thế Tôn đi vào tịnh xá của Bà-la-môn Rammaka và ngồi xuống chỗ đã được sắp đặt. ",
  "mn26:4.7": "Sau khi ngồi xuống, Thế Tôn gọi các Tỳ-kheo: ",
  "mn26:4.8": "“Này các Tỳ-kheo, hiện giờ các ông đang ngồi tụ họp để đàm luận về điều gì? Và câu chuyện giữa chừng của các ông là gì?” ",
  "mn26:4.9": "“Bạch Thế Tôn, chúng con đang đàm luận về Pháp liên quan đến Thế Tôn, thì Thế Tôn đến.” ",
  "mn26:4.10": "“Lành thay, này các Tỳ-kheo. ",
  "mn26:4.11": "Này các Tỳ-kheo, thật là thích hợp cho các ông, những thiện gia nam tử đã xuất gia từ bỏ gia đình để sống không gia đình, khi các ông ngồi tụ họp để đàm luận về Pháp. ",
  "mn26:4.12": "Này các Tỳ-kheo, khi các ông tụ họp, có hai điều cần làm—",
  "mn26:4.13": "hoặc là đàm luận về Pháp, hoặc là giữ im lặng cao quý. ",
  "mn26:5.1": "Này các Tỳ-kheo, có hai loại tìm cầu—",
  "mn26:5.2": "tìm cầu cao quý và tìm cầu không cao quý. ",
  "mn26:5.3": "Và này các Tỳ-kheo, thế nào là tìm cầu không cao quý? ",
  "mn26:5.4": "Ở đây, này các Tỳ-kheo, có người tự mình mang tính sinh, lại tìm cầu cái mang tính sinh; tự mình mang tính già, lại tìm cầu cái mang tính già; tự mình mang tính bệnh, lại tìm cầu cái mang tính bệnh; tự mình mang tính chết, lại tìm cầu cái mang tính chết; tự mình mang tính sầu, lại tìm cầu cái mang tính sầu; tự mình mang tính ô nhiễm, lại tìm cầu cái mang tính ô nhiễm. ",
  "mn26:6.1": "Và này các Tỳ-kheo, các ông nói cái gì là mang tính sinh? ",
  "mn26:6.2": "Này các Tỳ-kheo, vợ con là mang tính sinh, nô tỳ là mang tính sinh, dê cừu là mang tính sinh, gà heo là mang tính sinh, voi bò ngựa cái là mang tính sinh, vàng bạc là mang tính sinh. ",
  "mn26:6.3": "Này các Tỳ-kheo, những thứ này là những chấp thủ mang tính sinh. ",
  "mn26:6.4": "Ở đây, người ấy bị trói buộc, mê đắm, chìm đắm, tự mình mang tính sinh, lại tìm cầu cái mang tính sinh. ",
  "mn26:7.1": "Và này các Tỳ-kheo, các ông nói cái gì là mang tính già? ",
  "mn26:7.2": "Này các Tỳ-kheo, vợ con là mang tính già, nô tỳ là mang tính già, dê cừu là mang tính già, gà heo là mang tính già, voi bò ngựa cái là mang tính già, vàng bạc là mang tính già. ",
  "mn26:7.3": "Này các Tỳ-kheo, những thứ này là những chấp thủ mang tính già. ",
  "mn26:7.4": "Ở đây, người ấy bị trói buộc, mê đắm, chìm đắm, tự mình mang tính già, lại tìm cầu cái mang tính già. ",
  "mn26:8.1": "Và này các Tỳ-kheo, các ông nói cái gì là mang tính bệnh? ",
  "mn26:8.2": "Này các Tỳ-kheo, vợ con là mang tính bệnh, nô tỳ là mang tính bệnh, dê cừu là mang tính bệnh, gà heo là mang tính bệnh, voi bò ngựa cái là mang tính bệnh. ",
  "mn26:8.3": "Này các Tỳ-kheo, những thứ này là những chấp thủ mang tính bệnh. ",
  "mn26:8.4": "Ở đây, người ấy bị trói buộc, mê đắm, chìm đắm, tự mình mang tính bệnh, lại tìm cầu cái mang tính bệnh. ",
  "mn26:9.1": "Và này các Tỳ-kheo, các ông nói cái gì là mang tính chết? ",
  "mn26:9.2": "Này các Tỳ-kheo, vợ con là mang tính chết, nô tỳ là mang tính chết, dê cừu là mang tính chết, gà heo là mang tính chết, voi bò ngựa cái là mang tính chết. ",
  "mn26:9.3": "Này các Tỳ-kheo, những thứ này là những chấp thủ mang tính chết. ",
  "mn26:9.4": "Ở đây, người ấy bị trói buộc, mê đắm, chìm đắm, tự mình mang tính chết, lại tìm cầu cái mang tính chết. ",
  "mn26:10.1": "Và này các Tỳ-kheo, các ông nói cái gì là mang tính sầu? ",
  "mn26:10.2": "Này các Tỳ-kheo, vợ con là mang tính sầu, nô tỳ là mang tính sầu, dê cừu là mang tính sầu, gà heo là mang tính sầu, voi bò ngựa cái là mang tính sầu. ",
  "mn26:10.3": "Này các Tỳ-kheo, những thứ này là những chấp thủ mang tính sầu. ",
  "mn26:10.4": "Ở đây, người ấy bị trói buộc, mê đắm, chìm đắm, tự mình mang tính sầu, lại tìm cầu cái mang tính sầu. ",
  "mn26:11.1": "Và này các Tỳ-kheo, các ông nói cái gì là mang tính ô nhiễm? ",
  "mn26:11.2": "Này các Tỳ-kheo, vợ con là mang tính ô nhiễm, nô tỳ là mang tính ô nhiễm, dê cừu là mang tính ô nhiễm, gà heo là mang tính ô nhiễm, voi bò ngựa cái là mang tính ô nhiễm, vàng bạc là mang tính ô nhiễm. ",
  "mn26:11.3": "Này các Tỳ-kheo, những thứ này là những chấp thủ mang tính ô nhiễm. ",
  "mn26:11.4": "Ở đây, người ấy bị trói buộc, mê đắm, chìm đắm, tự mình mang tính ô nhiễm, lại tìm cầu cái mang tính ô nhiễm. ",
  "mn26:11.5": "Này các Tỳ-kheo, đây là tìm cầu không cao quý. ",
  "mn26:12.1": "Và này các Tỳ-kheo, thế nào là tìm cầu cao quý? ",
  "mn26:12.2": "Ở đây, này các Tỳ-kheo, có người tự mình mang tính sinh, sau khi thấy sự nguy hiểm trong cái mang tính sinh, liền tìm cầu Niết-bàn không sinh, vô thượng, an ổn khỏi các ách nạn; tự mình mang tính già, sau khi thấy sự nguy hiểm trong cái mang tính già, liền tìm cầu Niết-bàn không già, vô thượng, an ổn khỏi các ách nạn; tự mình mang tính bệnh, sau khi thấy sự nguy hiểm trong cái mang tính bệnh, liền tìm cầu Niết-bàn không bệnh, vô thượng, an ổn khỏi các ách nạn; tự mình mang tính chết, sau khi thấy sự nguy hiểm trong cái mang tính chết, liền tìm cầu Niết-bàn bất tử, vô thượng, an ổn khỏi các ách nạn; tự mình mang tính sầu, sau khi thấy sự nguy hiểm trong cái mang tính sầu, liền tìm cầu Niết-bàn không sầu, vô thượng, an ổn khỏi các ách nạn; tự mình mang tính ô nhiễm, sau khi thấy sự nguy hiểm trong cái mang tính ô nhiễm, liền tìm cầu Niết-bàn không ô nhiễm, vô thượng, an ổn khỏi các ách nạn. ",
  "mn26:12.3": "Này các Tỳ-kheo, đây là tìm cầu cao quý. ",
  "mn26:13.1": "Này các Tỳ-kheo, trước khi giác ngộ, khi còn là Bồ-tát chưa chứng Chánh Đẳng Giác, ta cũng tự mình mang tính sinh, lại tìm cầu cái mang tính sinh; tự mình mang tính già, lại tìm cầu cái mang tính già; tự mình mang tính bệnh, lại tìm cầu cái mang tính bệnh; tự mình mang tính chết, lại tìm cầu cái mang tính chết; tự mình mang tính sầu, lại tìm cầu cái mang tính sầu; tự mình mang tính ô nhiễm, lại tìm cầu cái mang tính ô nhiễm. ",
  "mn26:13.2": "Này các Tỳ-kheo, rồi ta nghĩ: ",
  "mn26:13.3": "‘Sao ta lại tự mình mang tính sinh, lại tìm cầu cái mang tính sinh; tự mình mang tính già… tự mình mang tính bệnh… tự mình mang tính chết… tự mình mang tính sầu… tự mình mang tính ô nhiễm, lại tìm cầu cái mang tính ô nhiễm? ",
  "mn26:13.4": "Hay là ta tự mình mang tính sinh, sau khi thấy sự nguy hiểm trong cái mang tính sinh, hãy tìm cầu Niết-bàn không sinh, vô thượng, an ổn khỏi các ách nạn; tự mình mang tính già, sau khi thấy sự nguy hiểm trong cái mang tính già, hãy tìm cầu Niết-bàn không già, vô thượng, an ổn khỏi các ách nạn; tự mình mang tính bệnh, sau khi thấy sự nguy hiểm trong cái mang tính bệnh, hãy tìm cầu Niết-bàn không bệnh, vô thượng, an ổn khỏi các ách nạn; tự mình mang tính chết, sau khi thấy sự nguy hiểm trong cái mang tính chết, hãy tìm cầu Niết-bàn bất tử, vô thượng, an ổn khỏi các ách nạn; tự mình mang tính sầu, sau khi thấy sự nguy hiểm trong cái mang tính sầu, hãy tìm cầu Niết-bàn không sầu, vô thượng, an ổn khỏi các ách nạn; tự mình mang tính ô nhiễm, sau khi thấy sự nguy hiểm trong cái mang tính ô nhiễm, hãy tìm cầu Niết-bàn không ô nhiễm, vô thượng, an ổn khỏi các ách nạn.’ ",
  "mn26:14.1": "Này các Tỳ-kheo, rồi một thời gian sau, khi còn trẻ, tóc đen nhánh, đầy đủ tuổi thanh xuân, ở độ tuổi đầu tiên, ta đã cạo bỏ râu tóc, đắp y cà-sa, xuất gia từ bỏ gia đình để sống không gia đình, mặc dù cha mẹ không muốn, nước mắt lưng tròng, khóc lóc. ",
  "mn26:15.1": "Sau khi xuất gia như vậy, ta tìm cầu điều thiện, tìm cầu đạo an tịnh vô thượng, rồi đi đến chỗ Āḷāra Kālāma (A-la-la Ca-la-ma). Sau khi đến, ta nói với Āḷāra Kālāma: ",
  "mn26:15.2": "‘Này Hiền giả Kālāma, tôi muốn sống đời phạm hạnh trong Pháp và Luật này.’ ",
  "mn26:15.3": "Này các Tỳ-kheo, khi ta nói vậy, Āḷāra Kālāma nói với ta: ",
  "mn26:15.4": "‘Này Tôn giả, hãy ở lại; ",
  "mn26:15.5": "Pháp này là như vậy, một người có trí tuệ không bao lâu sẽ tự mình chứng ngộ, thực chứng và an trú trong giáo pháp của thầy mình.’ ",
  "mn26:15.6": "Này các Tỳ-kheo, không bao lâu, ta đã nhanh chóng học thuộc Pháp ấy. ",
  "mn26:15.7": "Này các Tỳ-kheo, chỉ với việc nói ra bằng môi miệng, bằng cách lặp đi lặp lại, ta đã có thể nói về giáo lý và giáo pháp của các bậc trưởng lão, và ta tuyên bố ‘ta biết, ta thấy’, cả ta và những người khác. ",
  "mn26:15.8": "Này các Tỳ-kheo, rồi ta nghĩ: ",
  "mn26:15.9": "‘Āḷāra Kālāma không chỉ tuyên bố rằng ông ấy tự mình chứng ngộ, thực chứng và an trú trong Pháp này chỉ bằng niềm tin; ",
  "mn26:15.10": "chắc chắn Āḷāra Kālāma sống biết và thấy Pháp này.’ ",
  "mn26:15.11": "Rồi này các Tỳ-kheo, ta đi đến chỗ Āḷāra Kālāma; sau khi đến, ta nói với Āḷāra Kālāma: ",
  "mn26:15.12": "‘Này Hiền giả Kālāma, ông tuyên bố rằng ông tự mình chứng ngộ, thực chứng và an trú trong Pháp này đến mức độ nào?’ ",
  "mn26:15.13": "Này các Tỳ-kheo, khi ta nói vậy, Āḷāra Kālāma tuyên bố về Vô Sở Hữu Xứ. ",
  "mn26:15.14": "Này các Tỳ-kheo, rồi ta nghĩ: ",
  "mn26:15.15": "‘Không phải chỉ Āḷāra Kālāma có niềm tin, ta cũng có niềm tin; ",
  "mn26:15.16": "không phải chỉ Āḷāra Kālāma có tinh tấn, ta cũng có tinh tấn; ",
  "mn26:15.17": "không phải chỉ Āḷāra Kālāma có niệm, ta cũng có niệm; ",
  "mn26:15.18": "không phải chỉ Āḷāra Kālāma có định, ta cũng có định; ",
  "mn26:15.19": "không phải chỉ Āḷāra Kālāma có trí tuệ, ta cũng có trí tuệ. ",
  "mn26:15.20": "Hay là ta hãy tinh tấn để thực chứng Pháp mà Āḷāra Kālāma tuyên bố rằng ông ấy tự mình chứng ngộ, thực chứng và an trú.’ ",
  "mn26:15.21": "Này các Tỳ-kheo, không bao lâu, ta đã nhanh chóng tự mình chứng ngộ, thực chứng và an trú trong Pháp ấy. ",
  "mn26:15.22": "Rồi này các Tỳ-kheo, ta đi đến chỗ Āḷāra Kālāma; sau khi đến, ta nói với Āḷāra Kālāma: ",
  "mn26:15.23": "‘Này Hiền giả Kālāma, ông tuyên bố rằng ông tự mình chứng ngộ, thực chứng và an trú trong Pháp này đến mức độ nào?’ ",
  "mn26:15.24": "‘Này Hiền giả, ta tuyên bố rằng ta tự mình chứng ngộ, thực chứng và an trú trong Pháp này đến mức độ này.’ ",
  "mn26:15.25": "‘Này Hiền giả, ta cũng tự mình chứng ngộ, thực chứng và an trú trong Pháp này đến mức độ này.’ ",
  "mn26:15.26": "‘Này Hiền giả, chúng ta thật có lợi, chúng ta thật may mắn, ",
  "mn26:15.27": "khi chúng ta thấy một vị đồng phạm hạnh như Tôn giả. ",
  "mn26:15.28": "Như vậy, Pháp mà ta tự mình chứng ngộ, thực chứng và an trú, thì Tôn giả cũng tự mình chứng ngộ, thực chứng và an trú. ",
  "mn26:15.29": "Pháp mà Tôn giả tự mình chứng ngộ, thực chứng và an trú, thì ta cũng tự mình chứng ngộ, thực chứng và an trú. ",
  "mn26:15.30": "Như vậy, Pháp mà ta biết thì Tôn giả cũng biết, Pháp mà Tôn giả biết thì ta cũng biết. ",
  "mn26:15.31": "Như vậy, ta như thế nào thì Tôn giả cũng như thế ấy, Tôn giả như thế nào thì ta cũng như thế ấy. ",
  "mn26:15.32": "Này Hiền giả, bây giờ chúng ta hãy cùng nhau chăm sóc giáo đoàn này.’ ",
  "mn26:15.33": "Này các Tỳ-kheo, như vậy, Āḷāra Kālāma, là thầy của ta, đã đặt ta, đệ tử của ông, ngang hàng với ông, và đã tôn kính ta bằng sự tôn kính cao quý. ",
  "mn26:15.34": "Này các Tỳ-kheo, rồi ta nghĩ: ",
  "mn26:15.35": "‘Pháp này không đưa đến sự nhàm chán, không đưa đến sự ly tham, không đưa đến sự đoạn diệt, không đưa đến sự an tịnh, không đưa đến thắng trí, không đưa đến giác ngộ, không đưa đến Niết-bàn, mà chỉ đưa đến sự tái sinh vào Vô Sở Hữu Xứ.’ ",
  "mn26:15.36": "Này các Tỳ-kheo, ta không hài lòng với Pháp ấy, ta đã nhàm chán Pháp ấy và rời đi. ",
  "mn26:16.1": "Này các Tỳ-kheo, ta tìm cầu điều thiện, tìm cầu đạo an tịnh vô thượng, rồi đi đến chỗ Udaka Rāmaputta (Uất-đà-la La-ma-tử). Sau khi đến, ta nói với Udaka Rāmaputta: ",
  "mn26:16.2": "‘Này Hiền giả, tôi muốn sống đời phạm hạnh trong Pháp và Luật này.’ ",
  "mn26:16.3": "Này các Tỳ-kheo, khi ta nói vậy, Udaka Rāmaputta nói với ta: ",
  "mn26:16.4": "‘Này Tôn giả, hãy ở lại; ",
  "mn26:16.5": "Pháp này là như vậy, một người có trí tuệ không bao lâu sẽ tự mình chứng ngộ, thực chứng và an trú trong giáo pháp của thầy mình.’ ",
  "mn26:16.6": "Này các Tỳ-kheo, không bao lâu, ta đã nhanh chóng học thuộc Pháp ấy. ",
  "mn26:16.7": "Này các Tỳ-kheo, chỉ với việc nói ra bằng môi miệng, bằng cách lặp đi lặp lại, ta đã có thể nói về giáo lý và giáo pháp của các bậc trưởng lão, và ta tuyên bố ‘ta biết, ta thấy’, cả ta và những người khác. ",
  "mn26:16.8": "Này các Tỳ-kheo, rồi ta nghĩ: ",
  "mn26:16.9": "‘Rāma không phải chỉ bằng niềm tin mà tuyên bố rằng ông đã tự mình chứng ngộ và an trú trong pháp này; ",
  "mn26:16.10": "chắc chắn Rāma đã sống biết và thấy pháp này.’ ",
  "mn26:16.11": "Rồi này các Tỳ-kheo, tôi đi đến chỗ Udaka Rāmaputta; sau khi đến, tôi nói với Udaka Rāmaputta như sau: ",
  "mn26:16.12": "‘Này hiền giả, Rāma đã tuyên bố rằng ông đã tự mình chứng ngộ và an trú trong pháp này đến mức độ nào?’ ",
  "mn26:16.13": "Này các Tỳ-kheo, khi được hỏi như vậy, Udaka Rāmaputta đã tuyên bố về cõi Phi tưởng phi phi tưởng xứ. ",
  "mn26:16.14": "Này các Tỳ-kheo, tôi nghĩ thế này: ",
  "mn26:16.15": "‘Không phải chỉ Rāma có niềm tin, tôi cũng có niềm tin; ",
  "mn26:16.16": "không phải chỉ Rāma có tinh tấn, tôi cũng có tinh tấn; ",
  "mn26:16.17": "không phải chỉ Rāma có chánh niệm, tôi cũng có chánh niệm; ",
  "mn26:16.18": "không phải chỉ Rāma có định, tôi cũng có định, ",
  "mn26:16.19": "không phải chỉ Rāma có trí tuệ, tôi cũng có trí tuệ. ",
  "mn26:16.20": "Vậy thì, tôi hãy nỗ lực để chứng ngộ pháp mà Rāma đã tuyên bố là ông đã tự mình chứng ngộ và an trú.’ ",
  "mn26:16.21": "Này các Tỳ-kheo, không lâu sau đó, tôi đã nhanh chóng tự mình chứng ngộ và an trú trong pháp ấy. ",
  "mn26:16.22": "Rồi này các Tỳ-kheo, tôi đi đến chỗ Udaka Rāmaputta; sau khi đến, tôi nói với Udaka Rāmaputta như sau: ",
  "mn26:16.23": "‘Này hiền giả, Rāma đã tự mình chứng ngộ và an trú trong pháp này đến mức độ nào?’ ",
  "mn26:16.24": "‘Này hiền giả, Rāma đã tự mình chứng ngộ và an trú trong pháp này đến mức độ ấy.’ ",
  "mn26:16.25": "‘Này hiền giả, tôi cũng đã tự mình chứng ngộ và an trú trong pháp này đến mức độ ấy.’ ",
  "mn26:16.26": "‘Này hiền giả, chúng ta thật có lợi, chúng ta thật được lợi lớn, ",
  "mn26:16.27": "khi chúng ta thấy một vị đồng phạm hạnh như Tôn giả. ",
  "mn26:16.28": "Như vậy, pháp mà Rāma đã tự mình chứng ngộ và an trú, thì Tôn giả cũng tự mình chứng ngộ và an trú. ",
  "mn26:16.29": "Pháp mà Tôn giả đã tự mình chứng ngộ và an trú, thì Rāma cũng tự mình chứng ngộ và an trú. ",
  "mn26:16.30": "Như vậy, pháp mà Rāma đã chứng ngộ thì Tôn giả cũng biết, pháp mà Tôn giả biết thì Rāma cũng chứng ngộ. ",
  "mn26:16.31": "Như vậy, Rāma như thế nào thì Tôn giả cũng như thế ấy, Tôn giả như thế nào thì Rāma cũng như thế ấy. ",
  "mn26:16.32": "Này hiền giả, bây giờ Tôn giả hãy đến và lãnh đạo chúng này.’ ",
  "mn26:16.33": "Này các Tỳ-kheo, như vậy, Udaka Rāmaputta, dù là đồng phạm hạnh với tôi, đã đặt tôi vào vị trí của một vị thầy, và đã tôn kính tôi bằng sự tôn kính lớn lao. ",
  "mn26:16.34": "Này các Tỳ-kheo, tôi nghĩ thế này: ",
  "mn26:16.35": "‘Pháp này không đưa đến sự nhàm chán, không đưa đến sự ly tham, không đưa đến sự chấm dứt, không đưa đến sự an tịnh, không đưa đến sự chứng ngộ, không đưa đến sự giác ngộ, không đưa đến Niết-bàn, mà chỉ đưa đến sự tái sinh vào cõi Phi tưởng phi phi tưởng xứ.’ ",
  "mn26:16.36": "Này các Tỳ-kheo, tôi không hài lòng với pháp ấy, tôi nhàm chán pháp ấy và rời đi. ",
  "mn26:17.1": "Này các Tỳ-kheo, tôi, người đang tìm kiếm điều thiện, đang tìm kiếm con đường an tịnh tối thượng, tuần tự du hành qua xứ Magadha, rồi đến làng quân sự Uruvelā. ",
  "mn26:17.2": "Ở đó, tôi thấy một vùng đất đẹp, một khu rừng dễ chịu, một dòng sông chảy xiết với bến nước trong sạch, dễ chịu, và xung quanh là làng mạc để khất thực. ",
  "mn26:17.3": "Này các Tỳ-kheo, tôi nghĩ thế này: ",
  "mn26:17.4": "‘Ôi, vùng đất này thật đẹp, khu rừng thật dễ chịu, dòng sông chảy xiết với bến nước trong sạch, dễ chịu, và xung quanh là làng mạc để khất thực. ",
  "mn26:17.5": "Thật là thích hợp cho một thiện nam tử muốn tinh tấn để tinh tấn.’ ",
  "mn26:17.6": "Này các Tỳ-kheo, tôi liền ngồi xuống ở đó—",
  "mn26:17.7": "‘đây là nơi thích hợp để tinh tấn.’ ",
  "mn26:18.1": "Này các Tỳ-kheo, tôi, tự mình mang tính chất sinh, sau khi thấy sự nguy hiểm trong tính chất sinh, đã tìm kiếm Niết-bàn vô sinh, vô thượng, an ổn khỏi các ách, và đã đạt được Niết-bàn vô sinh, vô thượng, an ổn khỏi các ách. Tự mình mang tính chất già, sau khi thấy sự nguy hiểm trong tính chất già, đã tìm kiếm Niết-bàn vô già, vô thượng, an ổn khỏi các ách, và đã đạt được Niết-bàn vô già, vô thượng, an ổn khỏi các ách. Tự mình mang tính chất bệnh, sau khi thấy sự nguy hiểm trong tính chất bệnh, đã tìm kiếm Niết-bàn vô bệnh, vô thượng, an ổn khỏi các ách, và đã đạt được Niết-bàn vô bệnh, vô thượng, an ổn khỏi các ách. Tự mình mang tính chất chết, sau khi thấy sự nguy hiểm trong tính chất chết, đã tìm kiếm Niết-bàn bất tử, vô thượng, an ổn khỏi các ách, và đã đạt được Niết-bàn bất tử, vô thượng, an ổn khỏi các ách. Tự mình mang tính chất sầu, sau khi thấy sự nguy hiểm trong tính chất sầu, đã tìm kiếm Niết-bàn vô sầu, vô thượng, an ổn khỏi các ách, và đã đạt được Niết-bàn vô sầu, vô thượng, an ổn khỏi các ách. Tự mình mang tính chất ô nhiễm, sau khi thấy sự nguy hiểm trong tính chất ô nhiễm, đã tìm kiếm Niết-bàn vô nhiễm, vô thượng, an ổn khỏi các ách, và đã đạt được Niết-bàn vô nhiễm, vô thượng, an ổn khỏi các ách. ",
  "mn26:18.2": "Và tri kiến đã khởi lên nơi tôi: ",
  "mn26:18.3": "‘Sự giải thoát của tôi là bất động, đây là lần sinh cuối cùng, không còn tái sinh nữa.’ ",
  "mn26:19.1": "Này các Tỳ-kheo, tôi nghĩ thế này: ",
  "mn26:19.2": "‘Pháp này mà tôi đã chứng ngộ thật sâu xa, khó thấy, khó hiểu, an tịnh, cao thượng, không thể suy luận, vi tế, chỉ người trí mới cảm nhận được. ",
  "mn26:19.3": "Nhưng chúng sinh này lại ưa thích sự chấp trước, vui thích sự chấp trước, hoan hỷ với sự chấp trước. ",
  "mn26:19.4": "Đối với chúng sinh ưa thích sự chấp trước, vui thích sự chấp trước, hoan hỷ với sự chấp trước, thì điều này thật khó thấy, đó là—duyên khởi, sự sinh khởi có điều kiện. ",
  "mn26:19.5": "Điều này cũng thật khó thấy, đó là—sự làm lắng dịu tất cả các hành, sự từ bỏ tất cả các chấp thủ, sự diệt tận tham ái, sự ly tham, sự chấm dứt, Niết-bàn. ",
  "mn26:19.6": "Nếu tôi thuyết pháp, mà người khác không hiểu, thì đó sẽ là sự mệt mỏi cho tôi, đó sẽ là sự phiền toái cho tôi.’ ",
  "mn26:19.7": "Này các Tỳ-kheo, rồi những bài kệ chưa từng được nghe trước đây đã hiện ra trong tâm tôi: ",
  "mn26:19.8": "‘Ta đã chứng ngộ pháp này thật khó khăn, ",
  "mn26:19.9": "nay không cần phải tuyên bố nữa; ",
  "mn26:19.10": "những người bị tham ái và sân hận chi phối, ",
  "mn26:19.11": "pháp này thật khó hiểu. ",
  "mn26:19.12": "Dòng chảy ngược, vi tế, ",
  "mn26:19.13": "sâu xa, khó thấy, nhỏ nhiệm; ",
  "mn26:19.14": "những người bị tham ái nhuộm màu sẽ không thấy, ",
  "mn26:19.15": "bị che phủ bởi khối tối tăm.’ ",
  "mn26:19.16": "Này các Tỳ-kheo, khi tôi suy nghĩ như vậy, tâm tôi nghiêng về sự ít bận tâm, không nghiêng về việc thuyết pháp. ",
  "mn26:20.1": "Rồi này các Tỳ-kheo, Phạm thiên Sahampati, biết được suy nghĩ trong tâm tôi bằng tâm của mình, đã nghĩ thế này: ",
  "mn26:20.2": "‘Ôi, thế giới này thật sự đang bị hủy diệt, thế giới này thật sự đang bị tiêu vong, khi mà tâm của một vị Như Lai, A-la-hán, Chánh Đẳng Giác lại nghiêng về sự ít bận tâm, không nghiêng về việc thuyết pháp.’ ",
  "mn26:20.3": "Rồi này các Tỳ-kheo, Phạm thiên Sahampati—như một người lực sĩ co cánh tay đang duỗi ra, hoặc duỗi cánh tay đang co lại—cũng vậy, biến mất khỏi cõi Phạm thiên và hiện ra trước mặt tôi. ",
  "mn26:20.4": "Rồi này các Tỳ-kheo, Phạm thiên Sahampati khoác y vai trái, chắp tay hướng về phía tôi và nói với tôi như sau: ",
  "mn26:20.5": "‘Bạch Thế Tôn, xin Thế Tôn thuyết pháp, xin Thiện Thệ thuyết pháp. ",
  "mn26:20.6": "Có những chúng sinh ít bụi trần, vì không được nghe pháp mà bị tổn thất. ",
  "mn26:20.7": "Sẽ có những người hiểu được pháp.’ ",
  "mn26:20.8": "Này các Tỳ-kheo, Phạm thiên Sahampati đã nói điều này. ",
  "mn26:20.9": "Sau khi nói điều này, ông lại nói thêm: ",
  "mn26:20.10": "‘Trước đây ở xứ Magadha đã xuất hiện, ",
  "mn26:20.11": "một pháp bất tịnh do những kẻ ô uế suy nghĩ; ",
  "mn26:20.12": "xin hãy mở cửa bất tử này, ",
  "mn26:20.13": "hãy để họ nghe pháp được giác ngộ bởi bậc vô nhiễm. ",
  "mn26:20.14": "Như người đứng trên đỉnh núi đá, ",
  "mn26:20.15": "có thể nhìn thấy mọi người xung quanh; ",
  "mn26:20.16": "cũng vậy, bậc trí tuệ, bậc có mắt khắp nơi, ",
  "mn26:20.17": "sau khi lên lầu pháp, ",
  "mn26:20.18": "không còn sầu muộn, hãy nhìn xuống chúng sinh đang chìm đắm trong sầu muộn, ",
  "mn26:20.19": "bị sinh và già chi phối. ",
  "mn26:20.20": "Hãy đứng dậy, bậc anh hùng đã chiến thắng trận chiến, ",
  "mn26:20.21": "bậc dẫn đường không nợ nần, hãy du hành trong thế gian; ",
  "mn26:20.22": "xin Thế Tôn thuyết pháp, ",
  "mn26:20.23": "sẽ có những người hiểu được.’ ",
  "mn26:21.1": "Rồi này các Tỳ-kheo, tôi, sau khi biết được lời thỉnh cầu của Phạm thiên và vì lòng từ bi đối với chúng sinh, đã dùng Phật nhãn quán sát thế gian. ",
  "mn26:21.2": "Này các Tỳ-kheo, khi dùng Phật nhãn quán sát thế gian, tôi thấy có những chúng sinh ít bụi trần và nhiều bụi trần, có căn tánh bén nhạy và căn tánh chậm lụt, có thiện tướng và ác tướng, dễ dạy và khó dạy, có những người sống thấy sự nguy hiểm của lỗi lầm ở đời sau, và có những người sống không thấy sự nguy hiểm của lỗi lầm ở đời sau. ",
  "mn26:21.3": "Ví như trong một hồ sen xanh, hồ sen hồng, hay hồ sen trắng, có những bông sen xanh, sen hồng, hay sen trắng sinh ra trong nước, lớn lên trong nước, chìm sâu trong nước và được nuôi dưỡng dưới nước; có những bông sen xanh, sen hồng, hay sen trắng sinh ra trong nước, lớn lên trong nước, vươn lên khỏi mặt nước và đứng ngang mặt nước; có những bông sen xanh, sen hồng, hay sen trắng sinh ra trong nước, lớn lên trong nước, vươn cao khỏi mặt nước và không bị nước làm ô nhiễm; ",
  "mn26:21.4": "cũng vậy, này các Tỳ-kheo, khi dùng Phật nhãn quán sát thế gian, tôi thấy có những chúng sinh ít bụi trần và nhiều bụi trần, có căn tánh bén nhạy và căn tánh chậm lụt, có thiện tướng và ác tướng, dễ dạy và khó dạy, có những người sống thấy sự nguy hiểm của lỗi lầm ở đời sau, và có những người sống không thấy sự nguy hiểm của lỗi lầm ở đời sau. ",
  "mn26:21.5": "Rồi này các Tỳ-kheo, tôi đáp lại Phạm thiên Sahampati bằng bài kệ: ",
  "mn26:21.6": "‘Cửa bất tử đã mở ra cho những ai, ",
  "mn26:21.7": "có tai để nghe, hãy buông bỏ niềm tin; ",
  "mn26:21.8": "vì nghĩ đến sự làm hại, ta không nói pháp cao thượng, ",
  "mn26:21.9": "pháp cao thượng giữa loài người, này Phạm thiên.’ ",
  "mn26:21.10": "Rồi này các Tỳ-kheo, Phạm thiên Sahampati, nghĩ rằng ‘Thế Tôn đã cho phép tôi thuyết pháp’, đã đảnh lễ tôi, đi nhiễu quanh tôi theo chiều thuận, rồi biến mất ngay tại đó. ",
  "mn26:22.1": "Này các Tỳ-kheo, tôi nghĩ thế này: ",
  "mn26:22.2": "‘Ta nên thuyết pháp cho ai trước tiên; ",
  "mn26:22.3": "ai sẽ nhanh chóng hiểu được pháp này?’ ",
  "mn26:22.4": "Này các Tỳ-kheo, tôi nghĩ thế này: ",
  "mn26:22.5": "‘Này Āḷāra Kālāma là người trí tuệ, khéo léo, thông minh, đã lâu rồi ít bụi trần. ",
  "mn26:22.6": "Vậy thì, ta hãy thuyết pháp cho Āḷāra Kālāma trước tiên. ",
  "mn26:22.7": "Ông ấy sẽ nhanh chóng hiểu được pháp này.’ ",
  "mn26:22.8": "Rồi này các Tỳ-kheo, một vị trời đến gần tôi và nói: ",
  "mn26:22.9": "‘Bạch Thế Tôn, Āḷāra Kālāma đã qua đời bảy ngày rồi.’ ",
  "mn26:22.10": "Và tri kiến đã khởi lên nơi tôi: ",
  "mn26:22.11": "‘Āḷāra Kālāma đã qua đời bảy ngày rồi.’ ",
  "mn26:22.12": "Này các Tỳ-kheo, tôi nghĩ thế này: ",
  "mn26:22.13": "‘Āḷāra Kālāma thật sự đã mất mát lớn. ",
  "mn26:22.14": "Nếu ông ấy nghe pháp này, ông ấy sẽ nhanh chóng hiểu được.’ ",
  "mn26:23.1": "Này các Tỳ-kheo, tôi nghĩ thế này: ",
  "mn26:23.2": "‘Ta nên thuyết pháp cho ai trước tiên; ",
  "mn26:23.3": "ai sẽ nhanh chóng hiểu được pháp này?’ ",
  "mn26:23.4": "Này các Tỳ-kheo, tôi nghĩ thế này: ",
  "mn26:23.5": "‘Này Udaka Rāmaputta là người trí tuệ, khéo léo, thông minh, đã lâu rồi ít bụi trần. ",
  "mn26:23.6": "Vậy thì, ta hãy thuyết pháp cho Udaka Rāmaputta trước tiên. ",
  "mn26:23.7": "Ông ấy sẽ nhanh chóng hiểu được pháp này.’ ",
  "mn26:23.8": "Rồi này các Tỳ-kheo, một vị trời đến gần tôi và nói: ",
  "mn26:23.9": "‘Bạch Thế Tôn, Udaka Rāmaputta đã qua đời đêm qua.’ ",
  "mn26:23.10": "Và tri kiến đã khởi lên nơi tôi: ",
  "mn26:23.11": "‘Udaka Rāmaputta đã qua đời đêm qua.’ ",
  "mn26:23.12": "Này các Tỳ-kheo, tôi nghĩ thế này: ",
  "mn26:23.13": "‘Udaka Rāmaputta thật sự đã mất mát lớn. ",
  "mn26:23.14": "Nếu ông ấy nghe pháp này, ông ấy sẽ nhanh chóng hiểu được.’ ",
  "mn26:24.1": "Này các Tỳ-kheo, tôi nghĩ thế này: ",
  "mn26:24.2": "‘Ta nên thuyết pháp cho ai trước tiên; ",
  "mn26:24.3": "ai sẽ nhanh chóng hiểu được pháp này?’ ",
  "mn26:24.4": "Này các Tỳ-kheo, tôi nghĩ thế này: ",
  "mn26:24.5": "‘Năm vị Tỳ-kheo nhóm Kiều Trần Như đã giúp đỡ tôi rất nhiều khi tôi đang tinh tấn.’ ",
  "mn26:24.6": "Hay là ta nên thuyết pháp đầu tiên cho nhóm năm tỳ kheo này. ",
  "mn26:24.7": "Này các tỳ kheo, ta đã nghĩ thế này: ",
  "mn26:24.8": "‘Hiện giờ nhóm năm tỳ kheo này đang ở đâu?’",
  "mn26:24.9": "Này các tỳ kheo, ta đã thấy nhóm năm tỳ kheo đang ở Isipatana, Lộc Uyển, gần Bārāṇasī, bằng thiên nhãn thanh tịnh, vượt ngoài tầm nhìn của con người. ",
  "mn26:24.10": "Này các tỳ kheo, sau khi ở Uruvelā tùy thích, ta lên đường đi đến Bārāṇasī. ",
  "mn26:25.1": "Này các tỳ kheo, Upaka, một đạo sĩ lõa thể, đã thấy ta đang đi trên đường giữa Gayā và Bồ Đề. ",
  "mn26:25.2": "Thấy ta, ông ta nói: ",
  "mn26:25.3": "‘Này bạn, các căn của bạn thật trong sáng, màu da của bạn thật thanh tịnh và rạng rỡ. ",
  "mn26:25.4": "Này bạn, bạn xuất gia vì ai, ai là thầy của bạn, và bạn thích giáo pháp của ai?’",
  "mn26:25.5": "Này các tỳ kheo, khi được hỏi như vậy, ta đã nói với Upaka, đạo sĩ lõa thể, bằng những câu kệ: ",
  "mn26:25.6": "‘Ta là người chiến thắng tất cả, biết tất cả,",
  "mn26:25.7": "Không bị vấy bẩn bởi bất cứ pháp nào;",
  "mn26:25.8": "Từ bỏ tất cả, giải thoát nhờ diệt trừ tham ái,",
  "mn26:25.9": "Tự mình chứng ngộ, ta sẽ chỉ ai là thầy?",
  "mn26:25.10": "Ta không có thầy,",
  "mn26:25.11": "Không ai giống ta;",
  "mn26:25.12": "Trong thế giới có chư thiên,",
  "mn26:25.13": "Không ai là đối thủ của ta.",
  "mn26:25.14": "Ta là bậc A-la-hán trong thế gian,",
  "mn26:25.15": "Ta là bậc thầy vô thượng;",
  "mn26:25.16": "Ta là bậc Chánh Đẳng Giác duy nhất,",
  "mn26:25.17": "Ta đã tịch tịnh, đã niết bàn.",
  "mn26:25.18": "Để chuyển bánh xe pháp,",
  "mn26:25.19": "Ta đi đến thành Kāsī;",
  "mn26:25.20": "Trong thế giới đang mù mịt,",
  "mn26:25.21": "Ta sẽ đánh trống bất tử.’",
  "mn26:25.22": "‘Này bạn, như bạn đã tuyên bố, bạn xứng đáng là một bậc chiến thắng vô biên.’",
  "mn26:25.23": "‘Những người như ta là bậc chiến thắng,",
  "mn26:25.24": "Những người đã đạt đến sự diệt trừ các lậu hoặc;",
  "mn26:25.25": "Ta đã chiến thắng các pháp ác,",
  "mn26:25.26": "Vì vậy, này Upaka, ta là bậc chiến thắng.’",
  "mn26:25.27": "Này các tỳ kheo, khi được nói như vậy, đạo sĩ lõa thể Upaka nói ‘Có lẽ vậy, bạn ơi’, rồi lắc đầu, đi theo một con đường khác và bỏ đi. ",
  "mn26:26.1": "Này các tỳ kheo, sau đó ta tuần tự đi đến Isipatana, Lộc Uyển, gần Bārāṇasī, nơi nhóm năm tỳ kheo đang ở. ",
  "mn26:26.2": "Này các tỳ kheo, nhóm năm tỳ kheo đã thấy ta từ xa đang đến. ",
  "mn26:26.3": "Thấy ta, họ bàn với nhau: ",
  "mn26:26.4": "‘Này các bạn, sa môn Gotama này đang đến, ông ta đã trở nên phóng túng, đã từ bỏ sự tinh tấn, đã quay lại với sự phóng túng. ",
  "mn26:26.5": "Vì vậy, không nên chào hỏi ông ta, không nên đứng dậy đón ông ta; không nên nhận y bát của ông ta. ",
  "mn26:26.6": "Tuy nhiên, nên đặt một chỗ ngồi, nếu ông ta muốn, ông ta sẽ ngồi.’",
  "mn26:26.7": "Này các tỳ kheo, khi ta đến gần, nhóm năm tỳ kheo không thể giữ vững lời giao ước của họ. ",
  "mn26:26.8": "Một số người đứng dậy đón ta và nhận y bát, một số người sắp đặt chỗ ngồi, một số người chuẩn bị nước rửa chân. ",
  "mn26:26.9": "Tuy nhiên, họ vẫn gọi ta bằng tên và bằng cách xưng hô ‘này bạn’. ",
  "mn26:27.1": "Này các tỳ kheo, khi được nói như vậy, ta đã nói với nhóm năm tỳ kheo: ",
  "mn26:27.2": "‘Này các tỳ kheo, đừng gọi Như Lai bằng tên và bằng cách xưng hô ‘này bạn’. ",
  "mn26:27.3": "Này các tỳ kheo, Như Lai là bậc A-la-hán, Chánh Đẳng Giác. ",
  "mn26:27.4": "Này các tỳ kheo, hãy lắng tai nghe, bất tử đã được chứng đắc, ta sẽ giáo huấn, ta sẽ thuyết pháp. ",
  "mn26:27.5": "Thực hành theo lời giáo huấn, không bao lâu nữa—vì mục đích mà các thiện nam tử đã xuất gia từ bỏ gia đình để sống không gia đình, đó là sự chấm dứt đời sống phạm hạnh vô thượng—các bạn sẽ tự mình chứng ngộ, đạt được và an trú trong đó ngay trong hiện tại.’",
  "mn26:27.6": "Này các tỳ kheo, khi được nói như vậy, nhóm năm tỳ kheo đã nói với ta: ",
  "mn26:27.7": "‘Này bạn Gotama, ngay cả với cách sống đó, với con đường tu tập đó, với sự khổ hạnh đó, bạn cũng không đạt được pháp thượng nhân, sự chứng ngộ và thấy biết đặc biệt của bậc thánh, vậy thì bây giờ, khi bạn đã trở nên phóng túng, đã từ bỏ sự tinh tấn, đã quay lại với sự phóng túng, làm sao bạn có thể đạt được pháp thượng nhân, sự chứng ngộ và thấy biết đặc biệt của bậc thánh?’",
  "mn26:27.8": "Này các tỳ kheo, khi được nói như vậy, ta đã nói với nhóm năm tỳ kheo: ",
  "mn26:27.9": "‘Này các tỳ kheo, Như Lai không phóng túng, không từ bỏ sự tinh tấn, không quay lại với sự phóng túng. ",
  "mn26:27.10": "Này các tỳ kheo, Như Lai là bậc A-la-hán, Chánh Đẳng Giác. ",
  "mn26:27.11": "Này các tỳ kheo, hãy lắng tai nghe, bất tử đã được chứng đắc, ta sẽ giáo huấn, ta sẽ thuyết pháp. ",
  "mn26:27.12": "Thực hành theo lời giáo huấn, không bao lâu nữa—vì mục đích mà các thiện nam tử đã xuất gia từ bỏ gia đình để sống không gia đình, đó là sự chấm dứt đời sống phạm hạnh vô thượng—các bạn sẽ tự mình chứng ngộ, đạt được và an trú trong đó ngay trong hiện tại.’",
  "mn26:27.13": "Này các tỳ kheo, lần thứ hai, nhóm năm tỳ kheo đã nói với ta: ",
  "mn26:27.14": "‘Này bạn Gotama, ngay cả với cách sống đó, với con đường tu tập đó, với sự khổ hạnh đó, bạn cũng không đạt được pháp thượng nhân, sự chứng ngộ và thấy biết đặc biệt của bậc thánh, vậy thì bây giờ, khi bạn đã trở nên phóng túng, đã từ bỏ sự tinh tấn, đã quay lại với sự phóng túng, làm sao bạn có thể đạt được pháp thượng nhân, sự chứng ngộ và thấy biết đặc biệt của bậc thánh?’",
  "mn26:27.15": "Này các tỳ kheo, lần thứ hai, ta đã nói với nhóm năm tỳ kheo: ",
  "mn26:27.16": "‘Này các tỳ kheo, Như Lai không phóng túng …v.v… ",
  "mn26:27.17": "…sẽ đạt được và an trú trong đó.’",
  "mn26:27.18": "Này các tỳ kheo, lần thứ ba, nhóm năm tỳ kheo đã nói với ta: ",
  "mn26:27.19": "‘Này bạn Gotama, ngay cả với cách sống đó, với con đường tu tập đó, với sự khổ hạnh đó, bạn cũng không đạt được pháp thượng nhân, sự chứng ngộ và thấy biết đặc biệt của bậc thánh, vậy thì bây giờ, khi bạn đã trở nên phóng túng, đã từ bỏ sự tinh tấn, đã quay lại với sự phóng túng, làm sao bạn có thể đạt được pháp thượng nhân, sự chứng ngộ và thấy biết đặc biệt của bậc thánh?’",
  "mn26:28.1": "Này các tỳ kheo, khi được nói như vậy, ta đã nói với nhóm năm tỳ kheo: ",
  "mn26:28.2": "‘Này các tỳ kheo, các bạn có nhớ rằng trước đây ta đã từng nói như vậy không?’",
  "mn26:28.3": "‘Không, bạch Thế Tôn.’",
  "mn26:28.4": "‘Này các tỳ kheo, Như Lai là bậc A-la-hán, Chánh Đẳng Giác. ",
  "mn26:28.5": "Này các tỳ kheo, hãy lắng tai nghe, bất tử đã được chứng đắc, ta sẽ giáo huấn, ta sẽ thuyết pháp. ",
  "mn26:28.6": "Thực hành theo lời giáo huấn, không bao lâu nữa—vì mục đích mà các thiện nam tử đã xuất gia từ bỏ gia đình để sống không gia đình, đó là sự chấm dứt đời sống phạm hạnh vô thượng—các bạn sẽ tự mình chứng ngộ, đạt được và an trú trong đó ngay trong hiện tại.’",
  "mn26:29.1": "Này các tỳ kheo, ta đã có thể thuyết phục nhóm năm tỳ kheo. ",
  "mn26:29.2": "Này các tỳ kheo, ta giáo huấn hai tỳ kheo, ba tỳ kheo đi khất thực. ",
  "mn26:29.3": "Với những gì ba tỳ kheo khất thực mang về, sáu người chúng ta sống qua ngày. ",
  "mn26:29.4": "Này các tỳ kheo, ta giáo huấn ba tỳ kheo, hai tỳ kheo đi khất thực. ",
  "mn26:29.5": "Với những gì hai tỳ kheo khất thực mang về, sáu người chúng ta sống qua ngày. ",
  "mn26:30.1": "Này các tỳ kheo, sau đó, nhóm năm tỳ kheo, được ta giáo huấn và chỉ dạy như vậy, tự mình là những người có bản chất sinh, đã thấy sự nguy hiểm trong bản chất sinh, đã tìm kiếm Niết Bàn vô sinh, vô thượng, an ổn khỏi các ách buộc, và đã đạt được Niết Bàn vô sinh, vô thượng, an ổn khỏi các ách buộc; tự mình là những người có bản chất già, đã thấy sự nguy hiểm trong bản chất già, đã tìm kiếm Niết Bàn không già, vô thượng, an ổn khỏi các ách buộc, và đã đạt được Niết Bàn không già, vô thượng, an ổn khỏi các ách buộc; tự mình là những người có bản chất bệnh …v.v… tự mình là những người có bản chất chết … tự mình là những người có bản chất sầu muộn … tự mình là những người có bản chất ô nhiễm, đã thấy sự nguy hiểm trong bản chất ô nhiễm, đã tìm kiếm Niết Bàn không ô nhiễm, vô thượng, an ổn khỏi các ách buộc, và đã đạt được Niết Bàn không ô nhiễm, vô thượng, an ổn khỏi các ách buộc. ",
  "mn26:30.2": "Và sự thấy biết đã khởi lên nơi họ: ",
  "mn26:30.3": "‘Sự giải thoát của chúng ta là bất động, đây là kiếp cuối cùng, không còn tái sinh nữa.’",
  "mn26:31.1": "Này các tỳ kheo, có năm dục lạc này. ",
  "mn26:31.2": "Năm nào? ",
  "mn26:31.3": "Các sắc do mắt nhận biết, đáng ưa, đáng thích, đáng mến, đáng yêu, gắn liền với dục, làm say đắm;",
  "mn26:31.4": "Các tiếng do tai nhận biết …v.v… ",
  "mn26:31.5": "Các mùi do mũi nhận biết … ",
  "mn26:31.6": "Các vị do lưỡi nhận biết … ",
  "mn26:31.7": "Các xúc do thân nhận biết, đáng ưa, đáng thích, đáng mến, đáng yêu, gắn liền với dục, làm say đắm. ",
  "mn26:31.8": "Này các tỳ kheo, đây là năm dục lạc. ",
  "mn26:32.1": "Này các tỳ kheo, bất cứ sa môn hay bà la môn nào bị trói buộc, mê đắm, chìm đắm trong năm dục lạc này, không thấy sự nguy hiểm, không có trí tuệ thoát ly, thì nên biết về họ như sau: ",
  "mn26:32.2": "‘Họ đã rơi vào sự suy đồi, đã rơi vào tai họa, sẽ bị ác ma làm theo ý muốn.’",
  "mn26:32.3": "Này các tỳ kheo, ví như một con nai rừng bị trói nằm trên đống bẫy. ",
  "mn26:32.4": "Nên biết về nó như sau: ",
  "mn26:32.5": "‘Nó đã rơi vào sự suy đồi, đã rơi vào tai họa, sẽ bị thợ săn làm theo ý muốn. ",
  "mn26:32.6": "Và khi thợ săn đến, nó sẽ không thể đi đâu tùy ý.’",
  "mn26:32.7": "Cũng vậy, này các tỳ kheo, bất cứ sa môn hay bà la môn nào bị trói buộc, mê đắm, chìm đắm trong năm dục lạc này, không thấy sự nguy hiểm, không có trí tuệ thoát ly, thì nên biết về họ như sau: ",
  "mn26:32.8": "‘Họ đã rơi vào sự suy đồi, đã rơi vào tai họa, sẽ bị ác ma làm theo ý muốn.’",
  "mn26:33.1": "Này các tỳ kheo, còn bất cứ sa môn hay bà la môn nào không bị trói buộc, không mê đắm, không chìm đắm trong năm dục lạc này, thấy sự nguy hiểm, có trí tuệ thoát ly, thì nên biết về họ như sau: ",
  "mn26:33.2": "‘Họ không rơi vào sự suy đồi, không rơi vào tai họa, sẽ không bị ác ma làm theo ý muốn.’",
  "mn26:33.3": "Này các tỳ kheo, ví như một con nai rừng không bị trói nằm trên đống bẫy. ",
  "mn26:33.4": "Nên biết về nó như sau: ",
  "mn26:33.5": "‘Nó không rơi vào sự suy đồi, không rơi vào tai họa, sẽ không bị thợ săn làm theo ý muốn. ",
  "mn26:33.6": "Và khi thợ săn đến, nó sẽ đi đâu tùy ý.’",
  "mn26:33.7": "Cũng vậy, này các tỳ kheo, bất cứ sa môn hay bà la môn nào không bị trói buộc, không mê đắm, không chìm đắm trong năm dục lạc này, thấy sự nguy hiểm, có trí tuệ thoát ly, thì nên biết về họ như sau: ",
  "mn26:33.8": "‘Họ không rơi vào sự suy đồi, không rơi vào tai họa, sẽ không bị ác ma làm theo ý muốn.’",
  "mn26:34.1": "Này các tỳ kheo, ví như một con nai rừng đi lại trong rừng sâu, tự do đi, tự do đứng, tự do ngồi, tự do nằm. ",
  "mn26:34.2": "Vì sao vậy? ",
  "mn26:34.3": "Này các tỳ kheo, nó đã thoát khỏi tầm với của thợ săn. ",
  "mn26:34.4": "Cũng vậy, này các tỳ kheo, một tỳ kheo ly dục, ly bất thiện pháp, chứng và trú thiền thứ nhất, có tầm, có tứ, có hỷ lạc do ly dục sinh. ",
  "mn26:34.5": "Này các tỳ kheo, tỳ kheo này được gọi là người đã làm cho ác ma mù lòa, không dấu vết, đã đánh tan mắt của ác ma, đã biến mất khỏi tầm nhìn của ác ma. ",
  "mn26:35.1": "Lại nữa, này các tỳ kheo, một tỳ kheo, diệt tầm và tứ, nội tâm thanh tịnh, nhất tâm, không tầm, không tứ, chứng và trú thiền thứ hai, có hỷ lạc do định sinh. ",
  "mn26:35.2": "Này các tỳ kheo, tỳ kheo này được gọi là …v.v… của ác ma. ",
  "mn26:36.1": "Lại nữa, này các tỳ kheo, một tỳ kheo, ly hỷ, trú xả, chánh niệm tỉnh giác, thân cảm thọ lạc mà các bậc thánh gọi là ‘trú xả, chánh niệm, an lạc’, chứng và trú thiền thứ ba. ",
  "mn26:36.2": "Này các tỳ kheo, tỳ kheo này được gọi là …v.v… của ác ma. ",
  "mn26:37.1": "Lại nữa, này các tỳ kheo, một tỳ kheo, xả lạc, xả khổ, diệt hỷ ưu đã cảm thọ trước, chứng và trú thiền thứ tư, không khổ không lạc, xả niệm thanh tịnh. ",
  "mn26:37.2": "Này các tỳ kheo, tỳ kheo này được gọi là …v.v… của ác ma. ",
  "mn26:38.1": "Lại nữa, này các tỳ kheo, một tỳ kheo, vượt hoàn toàn các tưởng về sắc, diệt các tưởng về đối ngại, không tác ý các tưởng về sai biệt, chứng và trú không vô biên xứ, nghĩ rằng ‘không gian là vô biên’. ",
  "mn26:38.2": "Này các tỳ kheo, tỳ kheo này được gọi là …v.v… của ác ma. ",
  "mn26:39.1": "Lại nữa, này các tỳ kheo, một tỳ kheo, vượt hoàn toàn không vô biên xứ, chứng và trú thức vô biên xứ, nghĩ rằng ‘thức là vô biên’. ",
  "mn26:39.2": "Này các tỳ kheo, tỳ kheo này được gọi là …v.v… của ác ma. ",
  "mn26:40.1": "Lại nữa, này các tỳ kheo, một tỳ kheo, vượt hoàn toàn thức vô biên xứ, chứng và trú vô sở hữu xứ, nghĩ rằng ‘không có gì cả’. ",
  "mn26:40.2": "Này các tỳ kheo, tỳ kheo này được gọi là …v.v… của ác ma. ",
  "mn26:41.1": "Lại nữa, này các tỳ kheo, một tỳ kheo, vượt hoàn toàn vô sở hữu xứ, chứng và trú phi tưởng phi phi tưởng xứ. ",
  "mn26:41.2": "Này các tỳ kheo, tỳ kheo này được gọi là …v.v… của ác ma. ",
  "mn26:42.1": "Lại nữa, này các tỳ kheo, một tỳ kheo, vượt hoàn toàn phi tưởng phi phi tưởng xứ, chứng và trú diệt thọ tưởng định, và sau khi thấy bằng trí tuệ, các lậu hoặc của vị ấy được diệt trừ. ",
  "mn26:42.2": "Này các tỳ kheo, tỳ kheo này được gọi là người đã làm cho ác ma mù lòa, không dấu vết, đã đánh tan mắt của ác ma, đã biến mất khỏi tầm nhìn của ác ma. ",
  "mn26:42.3": "Vị ấy đã vượt qua sự dính mắc trong thế gian, tự do đi, tự do đứng, tự do ngồi, tự do nằm. ",
  "mn26:42.4": "Vì sao vậy?",
  "mn26:42.5": "Này các tỳ khưu, nó không nằm trong tầm với của ác ma.",
  "mn26:42.6": "Thế Tôn đã nói điều này.",
  "mn26:42.7": "Các tỳ khưu ấy hoan hỷ, tán thán lời Thế Tôn dạy.",
  "mn26:42.8": "Kinh Đống Bẫy đã xong, thứ sáu."
}
window.BILARA["mn26"]["vi"]["mn26:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";