window.BILARA = window.BILARA || {};
window.BILARA["mn29"] = window.BILARA["mn29"] || {};
window.BILARA["mn29"]["vi"] = {
  "mn29:0.1": "Trung Bộ Kinh 29 ",
  "mn29:0.2": "Kinh Ví Dụ Lõi Cây Lớn ",
  "mn29:1.1": "Tôi nghe như vầy—",
  "mn29:1.2": "Một thời Thế Tôn trú ở Rājagaha (Vương Xá), trên núi Gijjhakūṭa (Kỳ Xà Quật), không bao lâu sau khi Devadatta (Đề Bà Đạt Đa) bỏ đi. ",
  "mn29:1.3": "Tại đấy, Thế Tôn, nhân sự việc Devadatta, gọi các Tỳ kheo và nói: ",
  "mn29:2.1": "“Ở đây, này các Tỳ kheo, có người con nhà lành, vì lòng tin, từ bỏ gia đình, sống không gia đình: ",
  "mn29:2.2": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; ta bị chìm đắm trong khổ, bị khổ chi phối, ",
  "mn29:2.3": "mong sao sự chấm dứt toàn bộ khối khổ này được biết đến’. ",
  "mn29:2.4": "Người ấy, sau khi xuất gia như vậy, tạo ra lợi lộc, danh tiếng, tiếng tăm. ",
  "mn29:2.5": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, tự mãn, ý nghĩ được thỏa mãn. ",
  "mn29:2.6": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, tự khen mình, chê người khác: ",
  "mn29:2.7": "‘Ta có lợi lộc, danh tiếng, tiếng tăm, còn những Tỳ kheo khác thì không được biết đến, ít uy tín’. ",
  "mn29:2.8": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, say đắm, phóng dật, rơi vào phóng dật, sống trong khổ khi phóng dật. ",
  "mn29:2.9": "Ví như, này các Tỳ kheo, một người cần lõi cây, tìm lõi cây, đi tìm lõi cây, thấy một cây lớn có lõi, bỏ qua lõi, bỏ qua giác, bỏ qua vỏ, bỏ qua vỏ cây con, chặt cành lá mang đi, nghĩ rằng đó là lõi cây. ",
  "mn29:2.10": "Người có mắt thấy người ấy sẽ nói: ",
  "mn29:2.11": "‘Chắc chắn người này không biết lõi cây, không biết giác cây, không biết vỏ cây, không biết vỏ cây con, không biết cành lá. ",
  "mn29:2.12": "Cũng vậy, người này cần lõi cây, tìm lõi cây, đi tìm lõi cây, thấy một cây lớn có lõi, bỏ qua lõi, bỏ qua giác, bỏ qua vỏ, bỏ qua vỏ cây con, chặt cành lá mang đi, nghĩ rằng đó là lõi cây. ",
  "mn29:2.13": "Việc gì cần làm với lõi cây, người ấy sẽ không đạt được mục đích đó’. ",
  "mn29:2.14": "Cũng vậy, này các Tỳ kheo, ở đây có người con nhà lành, vì lòng tin, từ bỏ gia đình, sống không gia đình: ",
  "mn29:2.15": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; ta bị chìm đắm trong khổ, bị khổ chi phối, ",
  "mn29:2.16": "mong sao sự chấm dứt toàn bộ khối khổ này được biết đến’. ",
  "mn29:2.17": "Người ấy, sau khi xuất gia như vậy, tạo ra lợi lộc, danh tiếng, tiếng tăm. ",
  "mn29:2.18": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, tự mãn, ý nghĩ được thỏa mãn. ",
  "mn29:2.19": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, tự khen mình, chê người khác: ‘Ta có lợi lộc, danh tiếng, tiếng tăm, còn những Tỳ kheo khác thì không được biết đến, ít uy tín’. ",
  "mn29:2.20": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, say đắm, phóng dật, rơi vào phóng dật, sống trong khổ khi phóng dật. ",
  "mn29:2.21": "Này các Tỳ kheo, Tỳ kheo này được gọi là người đã lấy cành lá của Phạm hạnh; ",
  "mn29:2.22": "và đã đạt đến sự chấm dứt với nó. ",
  "mn29:3.1": "Nhưng ở đây, này các Tỳ kheo, có người con nhà lành, vì lòng tin, từ bỏ gia đình, sống không gia đình: ",
  "mn29:3.2": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; ta bị chìm đắm trong khổ, bị khổ chi phối, ",
  "mn29:3.3": "mong sao sự chấm dứt toàn bộ khối khổ này được biết đến’. ",
  "mn29:3.4": "Người ấy, sau khi xuất gia như vậy, tạo ra lợi lộc, danh tiếng, tiếng tăm. ",
  "mn29:3.5": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không tự mãn, ý nghĩ không được thỏa mãn. ",
  "mn29:3.6": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không tự khen mình, không chê người khác. ",
  "mn29:3.7": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không say đắm, không phóng dật, không rơi vào phóng dật. ",
  "mn29:3.8": "Không phóng dật, người ấy đạt được sự thành tựu về giới. ",
  "mn29:3.9": "Người ấy, với sự thành tựu về giới ấy, tự mãn, ý nghĩ được thỏa mãn. ",
  "mn29:3.10": "Người ấy, với sự thành tựu về giới ấy, tự khen mình, chê người khác: ",
  "mn29:3.11": "‘Ta có giới, có pháp lành, còn những Tỳ kheo khác thì phá giới, có pháp ác’. ",
  "mn29:3.12": "Người ấy, với sự thành tựu về giới ấy, say đắm, phóng dật, rơi vào phóng dật, sống trong khổ khi phóng dật. ",
  "mn29:3.13": "Ví như, này các Tỳ kheo, một người cần lõi cây, tìm lõi cây, đi tìm lõi cây, thấy một cây lớn có lõi, bỏ qua lõi, bỏ qua giác, bỏ qua vỏ, chặt vỏ cây con mang đi, nghĩ rằng đó là lõi cây. ",
  "mn29:3.14": "Người có mắt thấy người ấy sẽ nói: ",
  "mn29:3.15": "‘Chắc chắn người này không biết lõi cây, không biết giác cây, không biết vỏ cây, không biết vỏ cây con, không biết cành lá. ",
  "mn29:3.16": "Cũng vậy, người này cần lõi cây, tìm lõi cây, đi tìm lõi cây, thấy một cây lớn có lõi, bỏ qua lõi, bỏ qua giác, bỏ qua vỏ, chặt vỏ cây con mang đi, nghĩ rằng đó là lõi cây; ",
  "mn29:3.17": "việc gì cần làm với lõi cây, người ấy sẽ không đạt được mục đích đó’. ",
  "mn29:4.1": "Cũng vậy, này các Tỳ kheo, ở đây có người con nhà lành, vì lòng tin, từ bỏ gia đình, sống không gia đình: ",
  "mn29:4.2": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; ta bị chìm đắm trong khổ, bị khổ chi phối, ",
  "mn29:4.3": "mong sao sự chấm dứt toàn bộ khối khổ này được biết đến’. ",
  "mn29:4.4": "Người ấy, sau khi xuất gia như vậy, tạo ra lợi lộc, danh tiếng, tiếng tăm. ",
  "mn29:4.5": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không tự mãn, ý nghĩ không được thỏa mãn. ",
  "mn29:4.6": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không tự khen mình, không chê người khác. ",
  "mn29:4.7": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không say đắm, không phóng dật, không rơi vào phóng dật. ",
  "mn29:4.8": "Không phóng dật, người ấy đạt được sự thành tựu về giới. ",
  "mn29:4.9": "Người ấy, với sự thành tựu về giới ấy, tự mãn, ý nghĩ được thỏa mãn. ",
  "mn29:4.10": "Người ấy, với sự thành tựu về giới ấy, tự khen mình, chê người khác: ",
  "mn29:4.11": "‘Ta có giới, có pháp lành, còn những Tỳ kheo khác thì phá giới, có pháp ác’. ",
  "mn29:4.12": "Người ấy, với sự thành tựu về giới ấy, say đắm, phóng dật, rơi vào phóng dật, sống trong khổ khi phóng dật. ",
  "mn29:4.13": "Này các Tỳ kheo, Tỳ kheo này được gọi là người đã lấy vỏ cây con của Phạm hạnh; ",
  "mn29:4.14": "và đã đạt đến sự chấm dứt với nó. ",
  "mn29:4.15": "Nhưng ở đây, này các Tỳ kheo, có người con nhà lành, vì lòng tin, từ bỏ gia đình, sống không gia đình: ",
  "mn29:4.16": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; ta bị chìm đắm trong khổ, bị khổ chi phối, ",
  "mn29:4.17": "mong sao sự chấm dứt toàn bộ khối khổ này được biết đến’. ",
  "mn29:4.18": "Người ấy, sau khi xuất gia như vậy, tạo ra lợi lộc, danh tiếng, tiếng tăm. ",
  "mn29:4.19": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không tự mãn, ý nghĩ không được thỏa mãn. ",
  "mn29:4.20": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không tự khen mình, không chê người khác. ",
  "mn29:4.21": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không say đắm, không phóng dật, không rơi vào phóng dật, không phóng dật, người ấy đạt được sự thành tựu về giới. ",
  "mn29:4.22": "Người ấy, với sự thành tựu về giới ấy, tự mãn, nhưng ý nghĩ không được thỏa mãn. ",
  "mn29:4.23": "Người ấy, với sự thành tựu về giới ấy, không tự khen mình, không chê người khác. ",
  "mn29:4.24": "Người ấy, với sự thành tựu về giới ấy, không say đắm, không phóng dật, không rơi vào phóng dật. ",
  "mn29:4.25": "Không phóng dật, người ấy đạt được sự thành tựu về định. ",
  "mn29:4.26": "Người ấy, với sự thành tựu về định ấy, tự mãn, ý nghĩ được thỏa mãn. ",
  "mn29:4.27": "Người ấy, với sự thành tựu về định ấy, tự khen mình, chê người khác: ",
  "mn29:4.28": "‘Ta có định, tâm nhất tâm, còn những Tỳ kheo khác thì không có định, tâm tán loạn’. ",
  "mn29:4.29": "Người ấy, với sự thành tựu về định ấy, say đắm, phóng dật, rơi vào phóng dật, sống trong khổ khi phóng dật. ",
  "mn29:4.30": "Ví như, này các Tỳ kheo, một người cần lõi cây, tìm lõi cây, đi tìm lõi cây, thấy một cây lớn có lõi, bỏ qua lõi, bỏ qua giác, chặt vỏ cây mang đi, nghĩ rằng đó là lõi cây. ",
  "mn29:4.31": "Người có mắt thấy người ấy sẽ nói: ‘Chắc chắn người này không biết lõi cây, không biết giác cây, không biết vỏ cây, không biết vỏ cây con, không biết cành lá. ",
  "mn29:4.32": "Cũng vậy, người này cần lõi cây, tìm lõi cây, đi tìm lõi cây, thấy một cây lớn có lõi, bỏ qua lõi, bỏ qua giác, chặt vỏ cây mang đi, nghĩ rằng đó là lõi cây. ",
  "mn29:4.33": "Việc gì cần làm với lõi cây, người ấy sẽ không đạt được mục đích đó’. ",
  "mn29:4.34": "Cũng vậy, này các Tỳ kheo, ở đây có người con nhà lành, vì lòng tin, từ bỏ gia đình, sống không gia đình: ",
  "mn29:4.35": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; ta bị chìm đắm trong khổ, bị khổ chi phối, ",
  "mn29:4.36": "mong sao sự chấm dứt toàn bộ khối khổ này được biết đến’. ",
  "mn29:4.37": "Người ấy, sau khi xuất gia như vậy, tạo ra lợi lộc, danh tiếng, tiếng tăm. ",
  "mn29:4.38": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không tự mãn, ý nghĩ không được thỏa mãn. ",
  "mn29:4.39": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không tự khen mình, không chê người khác. ",
  "mn29:4.40": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không say đắm, không phóng dật, không rơi vào phóng dật, không phóng dật, người ấy đạt được sự thành tựu về giới. ",
  "mn29:4.41": "Người ấy, với sự thành tựu về giới ấy, tự mãn, nhưng ý nghĩ không được thỏa mãn. ",
  "mn29:4.42": "Người ấy, với sự thành tựu về giới ấy, không tự khen mình, không chê người khác. ",
  "mn29:4.43": "Người ấy, với sự thành tựu về giới ấy, không say đắm, không phóng dật, không rơi vào phóng dật, không phóng dật, người ấy đạt được sự thành tựu về định. ",
  "mn29:4.44": "Người ấy, với sự thành tựu về định ấy, tự mãn, ý nghĩ được thỏa mãn. ",
  "mn29:4.45": "Người ấy, với sự thành tựu về định ấy, tự khen mình, chê người khác: ",
  "mn29:4.46": "‘Ta có định, tâm nhất tâm, còn những Tỳ kheo khác thì không có định, tâm tán loạn’. ",
  "mn29:4.47": "Người ấy, với sự thành tựu về định ấy, say đắm, phóng dật, rơi vào phóng dật, sống trong khổ khi phóng dật. ",
  "mn29:4.48": "Này các Tỳ kheo, Tỳ kheo này được gọi là người đã lấy vỏ cây của Phạm hạnh; ",
  "mn29:4.49": "và đã đạt đến sự chấm dứt với nó. ",
  "mn29:5.1": "Nhưng ở đây, này các Tỳ kheo, có người con nhà lành, vì lòng tin, từ bỏ gia đình, sống không gia đình: ",
  "mn29:5.2": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; ta bị chìm đắm trong khổ, bị khổ chi phối, ",
  "mn29:5.3": "mong sao sự chấm dứt toàn bộ khối khổ này được biết đến’. ",
  "mn29:5.4": "Người ấy, sau khi xuất gia như vậy, tạo ra lợi lộc, danh tiếng, tiếng tăm. ",
  "mn29:5.5": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không tự mãn, ý nghĩ không được thỏa mãn. ",
  "mn29:5.6": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không tự khen mình, không chê người khác. ",
  "mn29:5.7": "Người ấy, với lợi lộc, danh tiếng, tiếng tăm ấy, không say đắm, không phóng dật, không rơi vào phóng dật. ",
  "mn29:5.8": "Không phóng dật, người ấy đạt được sự thành tựu về giới. ",
  "mn29:5.9": "Người ấy, với sự thành tựu về giới ấy, tự mãn, nhưng ý nghĩ không được thỏa mãn. ",
  "mn29:5.10": "Người ấy, với sự thành tựu về giới ấy, không tự khen mình, không chê người khác. ",
  "mn29:5.11": "Người ấy, với sự thành tựu về giới ấy, không say đắm, không phóng dật, không rơi vào phóng dật, không phóng dật, người ấy đạt được sự thành tựu về định. ",
  "mn29:5.12": "Người ấy, với sự thành tựu về định ấy, tự mãn, nhưng ý nghĩ không được thỏa mãn. ",
  "mn29:5.13": "Người ấy, với sự thành tựu về định ấy, không tự khen mình, không chê người khác. ",
  "mn29:5.14": "Người ấy, với sự thành tựu về định ấy, không say đắm, không phóng dật, không rơi vào phóng dật, không phóng dật, người ấy đạt được sự thấy biết. ",
  "mn29:5.15": "Người ấy, với sự thấy biết ấy, tự mãn, ý nghĩ được thỏa mãn. ",
  "mn29:5.16": "Người ấy, với sự thấy biết ấy, tự khen mình, chê người khác: ",
  "mn29:5.17": "‘Ta sống biết, thấy. ",
  "mn29:5.18": "Còn những Tỳ kheo khác thì sống không biết, không thấy’. ",
  "mn29:5.19": "Người ấy, với sự thấy biết ấy, say đắm, phóng dật, rơi vào phóng dật, sống trong khổ khi phóng dật. ",
  "mn29:5.20": "Ví như, này các Tỳ kheo, một người cần lõi cây, tìm lõi cây, đi tìm lõi cây, thấy một cây lớn có lõi, bỏ qua lõi, chặt giác cây mang đi, nghĩ rằng đó là lõi cây. ",
  "mn29:5.21": "Người có mắt thấy người ấy sẽ nói: ",
  "mn29:5.22": "‘Chắc chắn người này không biết lõi cây, không biết giác cây, không biết vỏ cây, không biết vỏ cây con, không biết cành lá. ",
  "mn29:5.23": "Cũng vậy, người này cần lõi cây, tìm lõi cây, đi tìm lõi cây, thấy một cây lớn có lõi, bỏ qua lõi, chặt giác cây mang đi, nghĩ rằng đó là lõi cây. ",
  "mn29:5.24": "Việc gì cần làm với lõi cây, người ấy sẽ không đạt được mục đích đó’. ",
  "mn29:5.25": "Cũng vậy, này các Tỳ kheo, ở đây có người con nhà lành, vì lòng tin, từ bỏ gia đình, sống không gia đình: ",
  "mn29:5.26": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; ta bị chìm đắm trong khổ, bị khổ chi phối, ",
  "mn29:5.27": "mong sao sự chấm dứt toàn bộ khối khổ này được biết đến’. ",
  "mn29:5.28": "Vị ấy, sau khi xuất gia như vậy, tạo ra lợi lộc, danh tiếng, được kính trọng.",
  "mn29:5.29": "Vị ấy không tự mãn, không hoàn toàn thỏa mãn ý muốn với lợi lộc, danh tiếng, được kính trọng đó.",
  "mn29:5.30": "Vị ấy không tự khen mình, không chê bai người khác với lợi lộc, danh tiếng, được kính trọng đó.",
  "mn29:5.31": "Vị ấy không say đắm, không phóng dật, không rơi vào sự lơ là với lợi lộc, danh tiếng, được kính trọng đó; không phóng dật, vị ấy đạt được sự đầy đủ về giới.",
  "mn29:5.32": "Vị ấy tự mãn với sự đầy đủ về giới đó, nhưng chưa hoàn toàn thỏa mãn ý muốn.",
  "mn29:5.33": "Vị ấy không tự khen mình, không chê bai người khác với sự đầy đủ về giới đó.",
  "mn29:5.34": "Vị ấy không say đắm, không phóng dật, không rơi vào sự lơ là với sự đầy đủ về giới đó; không phóng dật, vị ấy đạt được sự đầy đủ về định.",
  "mn29:5.35": "Vị ấy tự mãn với sự đầy đủ về định đó, nhưng chưa hoàn toàn thỏa mãn ý muốn.",
  "mn29:5.36": "Vị ấy không tự khen mình, không chê bai người khác với sự đầy đủ về định đó.",
  "mn29:5.37": "Vị ấy không say đắm, không phóng dật, không rơi vào sự lơ là với sự đầy đủ về định đó; không phóng dật, vị ấy đạt được tri kiến.",
  "mn29:5.38": "Vị ấy tự mãn, hoàn toàn thỏa mãn ý muốn với tri kiến đó.",
  "mn29:5.39": "Vị ấy tự khen mình, chê bai người khác với tri kiến đó:",
  "mn29:5.40": "‘Ta sống biết, thấy; còn những vị tỳ khưu khác sống không biết, không thấy’.",
  "mn29:5.41": "Vị ấy say đắm, phóng dật, rơi vào sự lơ là với tri kiến đó; phóng dật, vị ấy sống khổ sở.",
  "mn29:5.42": "Này các tỳ khưu, vị tỳ khưu này được gọi là đã nắm lấy phần vỏ của đời sống phạm hạnh;",
  "mn29:5.43": "và đã đạt đến sự kết thúc với nó.",
  "mn29:6.1": "Ở đây, này các tỳ khưu, có một số thiện nam tử, vì lòng tin, từ bỏ gia đình, sống không gia đình:",
  "mn29:6.2": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; bị chìm đắm trong khổ, bị khổ vây hãm,",
  "mn29:6.3": "mong sao sự chấm dứt của toàn bộ khối khổ này được biết đến’.",
  "mn29:6.4": "Vị ấy, sau khi xuất gia như vậy, tạo ra lợi lộc, danh tiếng, được kính trọng.",
  "mn29:6.5": "Vị ấy không tự mãn, không hoàn toàn thỏa mãn ý muốn với lợi lộc, danh tiếng, được kính trọng đó.",
  "mn29:6.6": "Vị ấy không tự khen mình, không chê bai người khác với lợi lộc, danh tiếng, được kính trọng đó.",
  "mn29:6.7": "Vị ấy không say đắm, không phóng dật, không rơi vào sự lơ là với lợi lộc, danh tiếng, được kính trọng đó; không phóng dật, vị ấy đạt được sự đầy đủ về giới.",
  "mn29:6.8": "Vị ấy tự mãn với sự đầy đủ về giới đó, nhưng chưa hoàn toàn thỏa mãn ý muốn.",
  "mn29:6.9": "Vị ấy không tự khen mình, không chê bai người khác với sự đầy đủ về giới đó.",
  "mn29:6.10": "Vị ấy không say đắm, không phóng dật, không rơi vào sự lơ là với sự đầy đủ về giới đó; không phóng dật, vị ấy đạt được sự đầy đủ về định.",
  "mn29:6.11": "Vị ấy tự mãn với sự đầy đủ về định đó, nhưng chưa hoàn toàn thỏa mãn ý muốn.",
  "mn29:6.12": "Vị ấy không tự khen mình, không chê bai người khác với sự đầy đủ về định đó.",
  "mn29:6.13": "Vị ấy không say đắm, không phóng dật, không rơi vào sự lơ là với sự đầy đủ về định đó; không phóng dật, vị ấy đạt được tri kiến.",
  "mn29:6.14": "Vị ấy tự mãn với tri kiến đó, nhưng chưa hoàn toàn thỏa mãn ý muốn.",
  "mn29:6.15": "Vị ấy không tự khen mình, không chê bai người khác với tri kiến đó.",
  "mn29:6.16": "Vị ấy không say đắm, không phóng dật, không rơi vào sự lơ là với tri kiến đó; không phóng dật, vị ấy đạt được sự giải thoát không lay chuyển.",
  "mn29:6.17": "Này các tỳ khưu, không thể có chuyện, không có cơ hội nào để vị tỳ khưu đó bị thoái thất khỏi sự giải thoát không lay chuyển đó.",
  "mn29:6.18": "Ví như, này các tỳ khưu, một người cần lõi cây, tìm lõi cây, đi tìm lõi cây, chặt lấy lõi cây của một cây lớn đứng vững, có lõi, và mang đi, biết rằng đó là lõi cây.",
  "mn29:6.19": "Một người có mắt thấy vậy sẽ nói rằng:",
  "mn29:6.20": "‘Thật vậy, vị này đã biết lõi cây, đã biết vỏ cây, đã biết vỏ ngoài, đã biết vỏ trong, đã biết cành lá.",
  "mn29:6.21": "Cũng vậy, vị này, cần lõi cây, tìm lõi cây, đi tìm lõi cây, đã chặt lấy chính lõi cây của một cây lớn đứng vững, có lõi, và mang đi, biết rằng đó là lõi cây.",
  "mn29:6.22": "Và điều gì cần làm với lõi cây, điều đó sẽ mang lại lợi ích cho vị ấy’.",
  "mn29:6.23": "Cũng vậy, này các tỳ khưu, ở đây có một số thiện nam tử, vì lòng tin, từ bỏ gia đình, sống không gia đình:",
  "mn29:6.24": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; bị chìm đắm trong khổ, bị khổ vây hãm,",
  "mn29:6.25": "mong sao sự chấm dứt của toàn bộ khối khổ này được biết đến’.",
  "mn29:6.26": "Vị ấy, sau khi xuất gia như vậy, tạo ra lợi lộc, danh tiếng, được kính trọng.",
  "mn29:6.27": "Vị ấy không tự mãn, không hoàn toàn thỏa mãn ý muốn với lợi lộc, danh tiếng, được kính trọng đó.",
  "mn29:6.28": "Vị ấy không tự khen mình, không chê bai người khác với lợi lộc, danh tiếng, được kính trọng đó.",
  "mn29:6.29": "Vị ấy không say đắm, không phóng dật, không rơi vào sự lơ là với lợi lộc, danh tiếng, được kính trọng đó; không phóng dật, vị ấy đạt được sự đầy đủ về giới.",
  "mn29:6.30": "Vị ấy tự mãn với sự đầy đủ về giới đó, nhưng chưa hoàn toàn thỏa mãn ý muốn.",
  "mn29:6.31": "Vị ấy không tự khen mình, không chê bai người khác với sự đầy đủ về giới đó.",
  "mn29:6.32": "Vị ấy không say đắm, không phóng dật, không rơi vào sự lơ là với sự đầy đủ về giới đó; không phóng dật, vị ấy đạt được sự đầy đủ về định.",
  "mn29:6.33": "Vị ấy tự mãn với sự đầy đủ về định đó, nhưng chưa hoàn toàn thỏa mãn ý muốn.",
  "mn29:6.34": "Vị ấy không tự khen mình, không chê bai người khác với sự đầy đủ về định đó.",
  "mn29:6.35": "Vị ấy không say đắm, không phóng dật, không rơi vào sự lơ là với sự đầy đủ về định đó; không phóng dật, vị ấy đạt được tri kiến.",
  "mn29:6.36": "Vị ấy tự mãn với tri kiến đó, nhưng chưa hoàn toàn thỏa mãn ý muốn.",
  "mn29:6.37": "Vị ấy không tự khen mình, không chê bai người khác với tri kiến đó.",
  "mn29:6.38": "Vị ấy không say đắm, không phóng dật, không rơi vào sự lơ là với tri kiến đó; không phóng dật, vị ấy đạt được sự giải thoát không lay chuyển.",
  "mn29:6.39": "Này các tỳ khưu, không thể có chuyện, không có cơ hội nào để vị tỳ khưu đó bị thoái thất khỏi sự giải thoát không lay chuyển đó.",
  "mn29:7.1": "Như vậy, này các tỳ khưu, đời sống phạm hạnh này không phải vì lợi lộc, danh tiếng, được kính trọng; không phải vì sự đầy đủ về giới; không phải vì sự đầy đủ về định; không phải vì tri kiến.",
  "mn29:7.2": "Mà này các tỳ khưu, chính là sự giải thoát tâm không lay chuyển—",
  "mn29:7.3": "đây là mục đích của đời sống phạm hạnh này, đây là lõi cây, đây là sự kết thúc’.",
  "mn29:7.4": "Thế Tôn đã nói điều này.",
  "mn29:7.5": "Các tỳ khưu hoan hỷ, tán thán lời Thế Tôn dạy.",
  "mn29:7.6": "Kinh Ví Dụ Lõi Cây Lớn, thứ chín, đã xong."
}
window.BILARA["mn29"]["vi"]["mn29:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
