window.BILARA = window.BILARA || {};
window.BILARA["mn30"] = window.BILARA["mn30"] || {};
window.BILARA["mn30"]["vi"] = {
  "mn30:0.1": "Trung Bộ Kinh 30 ",
  "mn30:0.2": "Kinh Ví Dụ Lõi Cây Nhỏ ",
  "mn30:1.1": "Tôi nghe như vầy—",
  "mn30:1.2": "Một thời Thế Tôn trú ở Sāvatthī, tại Jetavana, khu vườn của Anāthapiṇḍika. ",
  "mn30:2.1": "Rồi Bà La Môn Piṅgalakoccha đi đến chỗ Thế Tôn; sau khi đến, ông chào hỏi Thế Tôn. ",
  "mn30:2.2": "Sau khi nói lên những lời chào hỏi thân mật xã giao, ông ngồi xuống một bên. Ngồi xuống một bên, Bà La Môn Piṅgalakoccha bạch Thế Tôn: ",
  "mn30:2.3": "“Thưa Tôn giả Gotama, những vị Sa Môn, Bà La Môn có chúng, có đoàn, có đạo sư, được biết đến, có danh tiếng, là những người sáng lập giáo phái, được nhiều người xem là bậc thiện xảo, ",
  "mn30:2.4": "như Pūraṇa Kassapa, Makkhali Gosāla, Ajita Kesakambala, Pakudha Kaccāyana, Sañcaya Belaṭṭhaputta, Nigaṇṭha Nāṭaputta, ",
  "mn30:2.5": "tất cả những vị ấy, theo lời tự xưng của họ, có phải tất cả đều đã chứng ngộ, hay tất cả đều chưa chứng ngộ, hay một số đã chứng ngộ, một số chưa chứng ngộ?” ",
  "mn30:2.6": "“Thôi đi, Bà La Môn, hãy gác lại chuyện đó—",
  "mn30:2.7": "tất cả những vị ấy, theo lời tự xưng của họ, có phải tất cả đều đã chứng ngộ, hay tất cả đều chưa chứng ngộ, hay một số đã chứng ngộ, một số chưa chứng ngộ. ",
  "mn30:2.8": "Này Bà La Môn, Ta sẽ thuyết pháp cho ông, ",
  "mn30:2.9": "hãy lắng nghe và suy nghĩ kỹ, Ta sẽ nói.” ",
  "mn30:2.10": "“Vâng, thưa Tôn giả,” Bà La Môn Piṅgalakoccha vâng lời Thế Tôn. ",
  "mn30:2.11": "Thế Tôn nói như sau: ",
  "mn30:3.1": "“Này Bà La Môn, ví như một người cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy bỏ qua lõi, bỏ qua giác, bỏ qua vỏ, bỏ qua vỏ mỏng, chặt cành lá mang đi, nghĩ rằng đó là lõi cây. ",
  "mn30:3.2": "Một người có mắt thấy vậy sẽ nói: ",
  "mn30:3.3": "‘Chắc chắn người này không biết lõi, không biết giác, không biết vỏ, không biết vỏ mỏng, không biết cành lá. ",
  "mn30:3.4": "Cũng vậy, người này cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy bỏ qua lõi, bỏ qua giác, bỏ qua vỏ, bỏ qua vỏ mỏng, chặt cành lá mang đi, nghĩ rằng đó là lõi cây. ",
  "mn30:3.5": "Việc gì cần làm với lõi cây, người ấy sẽ không đạt được lợi ích đó.’ ",
  "mn30:4.1": "Hoặc nữa, này Bà La Môn, ví như một người cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy bỏ qua lõi, bỏ qua giác, bỏ qua vỏ, chặt vỏ mỏng mang đi, nghĩ rằng đó là lõi cây. ",
  "mn30:4.2": "Một người có mắt thấy vậy sẽ nói: ",
  "mn30:4.3": "‘Chắc chắn người này không biết lõi, không biết giác, không biết vỏ, không biết vỏ mỏng, không biết cành lá. ",
  "mn30:4.4": "Cũng vậy, người này cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy bỏ qua lõi, bỏ qua giác, bỏ qua vỏ, chặt vỏ mỏng mang đi, nghĩ rằng đó là lõi cây. ",
  "mn30:4.5": "Việc gì cần làm với lõi cây, người ấy sẽ không đạt được lợi ích đó.’ ",
  "mn30:5.1": "Hoặc nữa, này Bà La Môn, ví như một người cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy bỏ qua lõi, bỏ qua giác, chặt vỏ mang đi, nghĩ rằng đó là lõi cây. ",
  "mn30:5.2": "Một người có mắt thấy vậy sẽ nói: ",
  "mn30:5.3": "‘Chắc chắn người này không biết lõi, không biết giác, không biết vỏ, không biết vỏ mỏng, không biết cành lá. ",
  "mn30:5.4": "Cũng vậy, người này cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy bỏ qua lõi, bỏ qua giác, chặt vỏ mang đi, nghĩ rằng đó là lõi cây. ",
  "mn30:5.5": "Việc gì cần làm với lõi cây, người ấy sẽ không đạt được lợi ích đó.’ ",
  "mn30:6.1": "Hoặc nữa, này Bà La Môn, ví như một người cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy bỏ qua lõi, chặt giác mang đi, nghĩ rằng đó là lõi cây. ",
  "mn30:6.2": "Một người có mắt thấy vậy sẽ nói: ",
  "mn30:6.3": "‘Chắc chắn người này không biết lõi, không biết giác, không biết vỏ, không biết vỏ mỏng, không biết cành lá. ",
  "mn30:6.4": "Cũng vậy, người này cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy bỏ qua lõi, chặt giác mang đi, nghĩ rằng đó là lõi cây. ",
  "mn30:6.5": "Việc gì cần làm với lõi cây, người ấy sẽ không đạt được lợi ích đó.’ ",
  "mn30:7.1": "Hoặc nữa, này Bà La Môn, ví như một người cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy chặt đúng lõi mang đi, biết rằng đó là lõi cây. ",
  "mn30:7.2": "Một người có mắt thấy vậy sẽ nói: ",
  "mn30:7.3": "‘Chắc chắn người này biết lõi, biết giác, biết vỏ, biết vỏ mỏng, biết cành lá. ",
  "mn30:7.4": "Cũng vậy, người này cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy chặt đúng lõi mang đi, biết rằng đó là lõi cây. ",
  "mn30:7.5": "Việc gì cần làm với lõi cây, người ấy sẽ đạt được lợi ích đó.’ ",
  "mn30:8.1": "Cũng vậy, này Bà La Môn, ở đây có một số người vì lòng tin mà từ bỏ gia đình, sống không gia đình: ",
  "mn30:8.2": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; ta bị chìm đắm trong khổ, bị khổ chi phối, ",
  "mn30:8.3": "mong sao sự chấm dứt toàn bộ khối khổ này được biết đến.’ ",
  "mn30:8.4": "Người ấy, sau khi xuất gia như vậy, đạt được lợi lộc, danh vọng, tiếng tăm. ",
  "mn30:8.5": "Người ấy hoan hỷ với lợi lộc, danh vọng, tiếng tăm đó, tâm ý được thỏa mãn. ",
  "mn30:8.6": "Người ấy dùng lợi lộc, danh vọng, tiếng tăm đó để tự tán thán, chê bai người khác: ",
  "mn30:8.7": "‘Ta có lợi lộc, danh vọng, tiếng tăm, còn những Tỳ Kheo khác thì không được biết đến, ít uy tín.’ ",
  "mn30:8.8": "Và đối với những pháp khác cao hơn, vi diệu hơn lợi lộc, danh vọng, tiếng tăm, người ấy không phát sinh ý muốn chứng đạt, không tinh tấn, mà lại sống buông thả, lười biếng. ",
  "mn30:8.9": "Ví như, này Bà La Môn, người cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy bỏ qua lõi, bỏ qua giác, bỏ qua vỏ, bỏ qua vỏ mỏng, chặt cành lá mang đi, nghĩ rằng đó là lõi cây. ",
  "mn30:8.10": "Việc gì cần làm với lõi cây, người ấy sẽ không đạt được lợi ích đó. ",
  "mn30:8.11": "Này Bà La Môn, Ta nói người này ví như vậy. ",
  "mn30:9.1": "Nhưng ở đây, này Bà La Môn, có một số người vì lòng tin mà từ bỏ gia đình, sống không gia đình: ",
  "mn30:9.2": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; ta bị chìm đắm trong khổ, bị khổ chi phối, ",
  "mn30:9.3": "mong sao sự chấm dứt toàn bộ khối khổ này được biết đến.’ ",
  "mn30:9.4": "Người ấy, sau khi xuất gia như vậy, đạt được lợi lộc, danh vọng, tiếng tăm. ",
  "mn30:9.5": "Người ấy không hoan hỷ với lợi lộc, danh vọng, tiếng tăm đó, tâm ý không được thỏa mãn. ",
  "mn30:9.6": "Người ấy không dùng lợi lộc, danh vọng, tiếng tăm đó để tự tán thán, không chê bai người khác. ",
  "mn30:9.7": "Và đối với những pháp khác cao hơn, vi diệu hơn lợi lộc, danh vọng, tiếng tăm, người ấy phát sinh ý muốn chứng đạt, tinh tấn, không sống buông thả, không lười biếng. ",
  "mn30:9.8": "Người ấy đạt được giới hạnh. ",
  "mn30:9.9": "Người ấy hoan hỷ với giới hạnh đó, tâm ý được thỏa mãn. ",
  "mn30:9.10": "Người ấy dùng giới hạnh đó để tự tán thán, chê bai người khác: ",
  "mn30:9.11": "‘Ta có giới hạnh, có pháp lành, còn những Tỳ Kheo khác thì phá giới, có pháp ác.’ ",
  "mn30:9.12": "Và đối với những pháp khác cao hơn, vi diệu hơn giới hạnh, người ấy không phát sinh ý muốn chứng đạt, không tinh tấn, mà lại sống buông thả, lười biếng. ",
  "mn30:9.13": "Ví như, này Bà La Môn, người cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy bỏ qua lõi, bỏ qua giác, bỏ qua vỏ, chặt vỏ mỏng mang đi, nghĩ rằng đó là lõi cây. ",
  "mn30:9.14": "Việc gì cần làm với lõi cây, người ấy sẽ không đạt được lợi ích đó. ",
  "mn30:9.15": "Này Bà La Môn, Ta nói người này ví như vậy. ",
  "mn30:10.1": "Nhưng ở đây, này Bà La Môn, có một số người vì lòng tin mà từ bỏ gia đình, sống không gia đình: ",
  "mn30:10.2": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; ta bị chìm đắm trong khổ, bị khổ chi phối, ",
  "mn30:10.3": "mong sao sự chấm dứt toàn bộ khối khổ này được biết đến.’ ",
  "mn30:10.4": "Người ấy, sau khi xuất gia như vậy, đạt được lợi lộc, danh vọng, tiếng tăm. ",
  "mn30:10.5": "Người ấy không hoan hỷ với lợi lộc, danh vọng, tiếng tăm đó, tâm ý không được thỏa mãn. ",
  "mn30:10.6": "Người ấy không dùng lợi lộc, danh vọng, tiếng tăm đó để tự tán thán, không chê bai người khác. ",
  "mn30:10.7": "Và đối với những pháp khác cao hơn, vi diệu hơn lợi lộc, danh vọng, tiếng tăm, người ấy phát sinh ý muốn chứng đạt, tinh tấn, không sống buông thả, không lười biếng. ",
  "mn30:10.8": "Người ấy đạt được giới hạnh. ",
  "mn30:10.9": "Người ấy hoan hỷ với giới hạnh đó, nhưng tâm ý không được thỏa mãn. ",
  "mn30:10.10": "Người ấy không dùng giới hạnh đó để tự tán thán, không chê bai người khác. ",
  "mn30:10.11": "Và đối với những pháp khác cao hơn, vi diệu hơn giới hạnh, người ấy phát sinh ý muốn chứng đạt, tinh tấn, không sống buông thả, không lười biếng. ",
  "mn30:10.12": "Người ấy đạt được định hạnh. ",
  "mn30:10.13": "Người ấy hoan hỷ với định hạnh đó, tâm ý được thỏa mãn. ",
  "mn30:10.14": "Người ấy dùng định hạnh đó để tự tán thán, chê bai người khác: ",
  "mn30:10.15": "‘Ta có định, tâm nhất tâm, còn những Tỳ Kheo khác thì không có định, tâm tán loạn.’ ",
  "mn30:10.16": "Và đối với những pháp khác cao hơn, vi diệu hơn định hạnh, người ấy không phát sinh ý muốn chứng đạt, không tinh tấn, mà lại sống buông thả, lười biếng. ",
  "mn30:10.17": "Ví như, này Bà La Môn, người cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy bỏ qua lõi, bỏ qua giác, chặt vỏ mang đi, nghĩ rằng đó là lõi cây. ",
  "mn30:10.18": "Việc gì cần làm với lõi cây, người ấy sẽ không đạt được lợi ích đó. ",
  "mn30:10.19": "Này Bà La Môn, Ta nói người này ví như vậy. ",
  "mn30:11.1": "Nhưng ở đây, này Bà La Môn, có một số người vì lòng tin mà từ bỏ gia đình, sống không gia đình: ",
  "mn30:11.2": "‘Ta bị chìm đắm trong sinh, già, chết… ",
  "mn30:11.3": "mong sao sự chấm dứt được biết đến.’ ",
  "mn30:11.4": "Người ấy, sau khi xuất gia như vậy, đạt được lợi lộc, danh vọng, tiếng tăm. ",
  "mn30:11.5": "Người ấy không hoan hỷ với lợi lộc, danh vọng, tiếng tăm đó, tâm ý không được thỏa mãn. ",
  "mn30:11.6": "Người ấy không dùng lợi lộc, danh vọng, tiếng tăm đó để tự tán thán, không chê bai người khác. ",
  "mn30:11.7": "Và đối với những pháp khác cao hơn, vi diệu hơn lợi lộc, danh vọng, tiếng tăm, người ấy phát sinh ý muốn chứng đạt, tinh tấn, không sống buông thả, không lười biếng. ",
  "mn30:11.8": "Người ấy đạt được giới hạnh. ",
  "mn30:11.9": "Người ấy hoan hỷ với giới hạnh đó, nhưng tâm ý không được thỏa mãn. ",
  "mn30:11.10": "Người ấy không dùng giới hạnh đó để tự tán thán, không chê bai người khác. ",
  "mn30:11.11": "Và đối với những pháp khác cao hơn, vi diệu hơn giới hạnh, người ấy phát sinh ý muốn chứng đạt, tinh tấn, không sống buông thả, không lười biếng. ",
  "mn30:11.12": "Người ấy đạt được định hạnh. ",
  "mn30:11.13": "Người ấy hoan hỷ với định hạnh đó, nhưng tâm ý không được thỏa mãn. ",
  "mn30:11.14": "Người ấy không dùng định hạnh đó để tự tán thán, không chê bai người khác. ",
  "mn30:11.15": "Và đối với những pháp khác cao hơn, vi diệu hơn định hạnh, người ấy phát sinh ý muốn chứng đạt, tinh tấn, không sống buông thả, không lười biếng. ",
  "mn30:11.16": "Người ấy đạt được tri kiến. ",
  "mn30:11.17": "Người ấy hoan hỷ với tri kiến đó, tâm ý được thỏa mãn. ",
  "mn30:11.18": "Người ấy dùng tri kiến đó để tự tán thán, chê bai người khác: ",
  "mn30:11.19": "‘Ta sống với sự biết, sự thấy, còn những Tỳ Kheo khác thì sống không biết, không thấy.’ ",
  "mn30:11.20": "Và đối với những pháp khác cao hơn, vi diệu hơn tri kiến, người ấy không phát sinh ý muốn chứng đạt, không tinh tấn, mà lại sống buông thả, lười biếng. ",
  "mn30:11.21": "Ví như, này Bà La Môn, người cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy bỏ qua lõi, chặt giác mang đi, nghĩ rằng đó là lõi cây. ",
  "mn30:11.22": "Việc gì cần làm với lõi cây, người ấy sẽ không đạt được lợi ích đó. ",
  "mn30:11.23": "Này Bà La Môn, Ta nói người này ví như vậy. ",
  "mn30:12.1": "Nhưng ở đây, này Bà La Môn, có một số người vì lòng tin mà từ bỏ gia đình, sống không gia đình: ",
  "mn30:12.2": "‘Ta bị chìm đắm trong sinh, già, chết, sầu, bi, khổ, ưu, não; ta bị chìm đắm trong khổ, bị khổ chi phối, ",
  "mn30:12.3": "mong sao sự chấm dứt toàn bộ khối khổ này được biết đến.’ ",
  "mn30:12.4": "Người ấy, sau khi xuất gia như vậy, đạt được lợi lộc, danh vọng, tiếng tăm. ",
  "mn30:12.5": "Người ấy không hoan hỷ với lợi lộc, danh vọng, tiếng tăm đó, tâm ý không được thỏa mãn. ",
  "mn30:12.6": "Người ấy không dùng lợi lộc, danh vọng, tiếng tăm đó để tự tán thán, không chê bai người khác. ",
  "mn30:12.7": "Và đối với những pháp khác cao hơn, vi diệu hơn lợi lộc, danh vọng, tiếng tăm, người ấy phát sinh ý muốn chứng đạt, tinh tấn, không sống buông thả, không lười biếng. ",
  "mn30:12.8": "Người ấy đạt được giới hạnh. ",
  "mn30:12.9": "Người ấy hoan hỷ với giới hạnh đó, nhưng tâm ý không được thỏa mãn. ",
  "mn30:12.10": "Người ấy không dùng giới hạnh đó để tự tán thán, không chê bai người khác. ",
  "mn30:12.11": "Và đối với những pháp khác cao hơn, vi diệu hơn giới hạnh, người ấy phát sinh ý muốn chứng đạt, tinh tấn, không sống buông thả, không lười biếng. ",
  "mn30:12.12": "Người ấy đạt được định hạnh. ",
  "mn30:12.13": "Người ấy hoan hỷ với thành tựu định đó, nhưng chưa hoàn thành ý nguyện. ",
  "mn30:12.14": "Người ấy không tự khen mình, không chê người khác với thành tựu định đó. ",
  "mn30:12.15": "Và đối với những pháp khác cao hơn và thù thắng hơn thành tựu định, người ấy phát sinh ý muốn, cố gắng, không chùn bước, không lười biếng để chứng đạt những pháp đó. ",
  "mn30:12.16": "Người ấy đạt được tri kiến. ",
  "mn30:12.17": "Người ấy hoan hỷ với tri kiến đó, nhưng chưa hoàn thành ý nguyện. ",
  "mn30:12.18": "Người ấy không tự khen mình, không chê người khác với tri kiến đó. ",
  "mn30:12.19": "Và đối với những pháp khác cao hơn và thù thắng hơn tri kiến, người ấy phát sinh ý muốn, cố gắng, không chùn bước, không lười biếng để chứng đạt những pháp đó. ",
  "mn30:12.20": "Và này Bà-la-môn, những pháp nào cao hơn và thù thắng hơn tri kiến? ",
  "mn30:13.1": "Ở đây, này Bà-la-môn, Tỳ-kheo ly dục, ly bất thiện pháp, chứng và trú Sơ thiền, một trạng thái hỷ lạc do ly dục sinh, có tầm có tứ. ",
  "mn30:13.2": "Này Bà-la-môn, pháp này cũng cao hơn và thù thắng hơn tri kiến. ",
  "mn30:14.1": "Lại nữa, này Bà-la-môn, Tỳ-kheo diệt tầm và tứ, chứng và trú Nhị thiền, một trạng thái hỷ lạc do định sinh, không tầm không tứ, nội tĩnh nhất tâm. ",
  "mn30:14.2": "Này Bà-la-môn, pháp này cũng cao hơn và thù thắng hơn tri kiến. ",
  "mn30:15.1": "Lại nữa, này Bà-la-môn, Tỳ-kheo ly hỷ trú xả, chánh niệm tỉnh giác, thân cảm sự lạc mà các bậc Thánh gọi là: ‘xả niệm lạc trú’, chứng và trú Tam thiền. ",
  "mn30:15.2": "Này Bà-la-môn, pháp này cũng cao hơn và thù thắng hơn tri kiến. ",
  "mn30:16.1": "Lại nữa, này Bà-la-môn, Tỳ-kheo xả lạc xả khổ, diệt hỷ ưu đã cảm thọ trước, chứng và trú Tứ thiền, không khổ không lạc, xả niệm thanh tịnh. ",
  "mn30:16.2": "Này Bà-la-môn, pháp này cũng cao hơn và thù thắng hơn tri kiến. ",
  "mn30:17.1": "Lại nữa, này Bà-la-môn, Tỳ-kheo vượt lên mọi sắc tưởng, diệt trừ các tưởng chướng ngại, không tác ý các tưởng sai biệt, chứng và trú Không vô biên xứ với ý nghĩ: ‘Không gian là vô biên’. ",
  "mn30:17.2": "Này Bà-la-môn, pháp này cũng cao hơn và thù thắng hơn tri kiến. ",
  "mn30:18.1": "Lại nữa, này Bà-la-môn, Tỳ-kheo vượt lên mọi Không vô biên xứ, chứng và trú Thức vô biên xứ với ý nghĩ: ‘Thức là vô biên’. ",
  "mn30:18.2": "Này Bà-la-môn, pháp này cũng cao hơn và thù thắng hơn tri kiến. ",
  "mn30:19.1": "Lại nữa, này Bà-la-môn, Tỳ-kheo vượt lên mọi Thức vô biên xứ, chứng và trú Vô sở hữu xứ với ý nghĩ: ‘Không có gì cả’. ",
  "mn30:19.2": "Này Bà-la-môn, pháp này cũng cao hơn và thù thắng hơn tri kiến. ",
  "mn30:20.1": "Lại nữa, này Bà-la-môn, Tỳ-kheo vượt lên mọi Vô sở hữu xứ, chứng và trú Phi tưởng phi phi tưởng xứ. ",
  "mn30:20.2": "Này Bà-la-môn, pháp này cũng cao hơn và thù thắng hơn tri kiến. ",
  "mn30:21.1": "Lại nữa, này Bà-la-môn, Tỳ-kheo vượt lên mọi Phi tưởng phi phi tưởng xứ, chứng và trú Diệt thọ tưởng định, và sau khi thấy bằng trí tuệ, các lậu hoặc của vị ấy được diệt tận. ",
  "mn30:21.2": "Này Bà-la-môn, pháp này cũng cao hơn và thù thắng hơn tri kiến. ",
  "mn30:21.3": "Này Bà-la-môn, những pháp này cao hơn và thù thắng hơn tri kiến. ",
  "mn30:22.1": "Ví như, này Bà-la-môn, một người cần lõi cây, tìm lõi cây, đi tìm lõi cây, khi gặp một cây lớn có lõi, người ấy chỉ chặt lấy lõi cây và mang đi, biết rằng đó là lõi cây. ",
  "mn30:22.2": "Và những gì cần làm với lõi cây, người ấy sẽ đạt được mục đích đó. ",
  "mn30:22.3": "Này Bà-la-môn, Ta nói người này cũng giống như vậy. ",
  "mn30:23.1": "Như vậy, này Bà-la-môn, đời sống Phạm hạnh này không phải vì lợi lộc, cung kính, danh tiếng; không phải vì thành tựu giới; không phải vì thành tựu định; không phải vì thành tựu tri kiến. ",
  "mn30:23.2": "Mà này Bà-la-môn, chính sự giải thoát tâm bất động này—",
  "mn30:23.3": "đây là mục đích của đời sống Phạm hạnh này, đây là cốt lõi, đây là cứu cánh.”",
  "mn30:24.1": "Khi được nói vậy, Bà-la-môn Piṅgalakoccha bạch Thế Tôn: ",
  "mn30:24.2": "“Thật tuyệt vời thay, thưa Tôn giả Gotama! Thật tuyệt vời thay, thưa Tôn giả Gotama! …pe… ",
  "mn30:24.3": "Mong Tôn giả Gotama nhận con làm cư sĩ, từ nay cho đến trọn đời, con xin quy y.”",
  "mn30:24.4": "Tiểu Lõi Cây Kinh, thứ mười, chấm dứt. ",
  "mn30:24.5": "Phẩm Ví Dụ, thứ ba, chấm dứt. ",
  "mn30:25.0": "Tóm tắt: ",
  "mn30:25.1": "Moḷiya, Phagguna, Ariṭṭha, Nāma, ",
  "mn30:25.2": "Andhavana, Kathipuṇṇa, Nivāpa; ",
  "mn30:25.3": "Rāsika, Neḷu, Mahāgaja, Nāma, ",
  "mn30:25.4": "Sārūpama, và Piṅgalakoccha. "
}
window.BILARA["mn30"]["vi"]["mn30:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
