window.BILARA = window.BILARA || {};
window.BILARA["mn32"] = window.BILARA["mn32"] || {};
window.BILARA["mn32"]["vi"] = {
  "mn32:0.1": "Trung Bộ Kinh 32 ",
  "mn32:0.2": "Đại Kinh Gosinga ",
  "mn32:1.1": "Tôi nghe như vầy—",
  "mn32:1.2": "Một thời, Thế Tôn trú ở rừng Sāla Gosinga, cùng với nhiều vị đệ tử trưởng lão nổi tiếng, nổi tiếng—",
  "mn32:1.3": "cùng với Tôn giả Sāriputta, Tôn giả Mahāmoggallāna, Tôn giả Mahākassapa, Tôn giả Anuruddha, Tôn giả Revata, Tôn giả Ānanda, và cùng với các vị đệ tử trưởng lão nổi tiếng, nổi tiếng khác. ",
  "mn32:2.1": "Rồi Tôn giả Mahāmoggallāna, vào buổi chiều, từ chỗ thiền tịnh đứng dậy, đi đến chỗ Tôn giả Mahākassapa; sau khi đến, Tôn giả nói với Tôn giả Mahākassapa: ",
  "mn32:2.2": "“Này Hiền giả Kassapa, chúng ta hãy đi đến chỗ Tôn giả Sāriputta để nghe pháp.”",
  "mn32:2.3": "“Thưa vâng, Hiền giả,” Tôn giả Mahākassapa đáp lời Tôn giả Mahāmoggallāna. ",
  "mn32:2.4": "Rồi Tôn giả Mahāmoggallāna, Tôn giả Mahākassapa, và Tôn giả Anuruddha đi đến chỗ Tôn giả Sāriputta để nghe pháp. ",
  "mn32:3.1": "Tôn giả Ānanda thấy Tôn giả Mahāmoggallāna, Tôn giả Mahākassapa, và Tôn giả Anuruddha đang đi đến chỗ Tôn giả Sāriputta để nghe pháp. ",
  "mn32:3.2": "Sau khi thấy, Tôn giả đi đến chỗ Tôn giả Revata; sau khi đến, Tôn giả nói với Tôn giả Revata: ",
  "mn32:3.3": "“Này Hiền giả Revata, các bậc thiện nhân kia đang đi đến chỗ Tôn giả Sāriputta để nghe pháp. ",
  "mn32:3.4": "Này Hiền giả Revata, chúng ta hãy đi đến chỗ Tôn giả Sāriputta để nghe pháp.”",
  "mn32:3.5": "“Thưa vâng, Hiền giả,” Tôn giả Revata đáp lời Tôn giả Ānanda. ",
  "mn32:3.6": "Rồi Tôn giả Revata và Tôn giả Ānanda đi đến chỗ Tôn giả Sāriputta để nghe pháp. ",
  "mn32:4.1": "Tôn giả Sāriputta thấy Tôn giả Revata và Tôn giả Ānanda đang đi đến từ xa. ",
  "mn32:4.2": "Sau khi thấy, Tôn giả nói với Tôn giả Ānanda: ",
  "mn32:4.3": "“Này Tôn giả Ānanda, hãy đến. ",
  "mn32:4.4": "Chào mừng Tôn giả Ānanda, thị giả của Thế Tôn, người thường ở gần Thế Tôn. ",
  "mn32:4.5": "Này Hiền giả Ānanda, rừng Sāla Gosinga thật đẹp, đêm trăng sáng, cây sāla nở hoa khắp nơi, hương thơm như của chư thiên đang tỏa ngát; ",
  "mn32:4.6": "này Hiền giả Ānanda, một Tỳ-kheo như thế nào sẽ làm cho rừng Sāla Gosinga thêm đẹp?”",
  "mn32:4.7": "“Này Hiền giả Sāriputta, ở đây, một Tỳ-kheo là người đa văn, thọ trì những điều đã nghe, tích lũy những điều đã nghe. Những pháp nào sơ thiện, trung thiện, hậu thiện, có nghĩa, có văn, tuyên bố đời sống phạm hạnh hoàn toàn đầy đủ, hoàn toàn thanh tịnh, những pháp như vậy được Tỳ-kheo ấy nghe nhiều, thọ trì, đọc tụng thành thạo bằng lời, quán sát bằng ý, và thâm nhập sâu sắc bằng kiến giải. ",
  "mn32:4.8": "Vị ấy thuyết pháp cho bốn chúng hội với những lời lẽ tròn đầy, văn tự liên tục, để diệt trừ các tùy miên. ",
  "mn32:4.9": "Này Hiền giả Sāriputta, một Tỳ-kheo như vậy sẽ làm cho rừng Sāla Gosinga thêm đẹp.”",
  "mn32:5.1": "Khi được nói như vậy, Tôn giả Sāriputta nói với Tôn giả Revata: ",
  "mn32:5.2": "“Này Hiền giả Revata, Tôn giả Ānanda đã trình bày sự hiểu biết của mình. ",
  "mn32:5.3": "Bây giờ chúng tôi hỏi Tôn giả Revata: ",
  "mn32:5.4": "‘Này Hiền giả Revata, rừng Sāla Gosinga thật đẹp, đêm trăng sáng, cây sāla nở hoa khắp nơi, hương thơm như của chư thiên đang tỏa ngát; ",
  "mn32:5.5": "này Hiền giả Revata, một Tỳ-kheo như thế nào sẽ làm cho rừng Sāla Gosinga thêm đẹp?’”",
  "mn32:5.6": "“Này Hiền giả Sāriputta, ở đây, một Tỳ-kheo ưa thích thiền tịnh, hoan hỷ với thiền tịnh, chuyên tâm vào sự an tịnh nội tâm, không bỏ thiền định, đầy đủ tuệ quán, là người phát triển các trú xứ không. ",
  "mn32:5.7": "Này Hiền giả Sāriputta, một Tỳ-kheo như vậy sẽ làm cho rừng Sāla Gosinga thêm đẹp.”",
  "mn32:6.1": "Khi được nói như vậy, Tôn giả Sāriputta nói với Tôn giả Anuruddha: ",
  "mn32:6.2": "“Này Hiền giả Anuruddha, Tôn giả Revata đã trình bày sự hiểu biết của mình. ",
  "mn32:6.3": "Bây giờ chúng tôi hỏi Tôn giả Anuruddha: ",
  "mn32:6.4": "‘Này Hiền giả Anuruddha, rừng Sāla Gosinga thật đẹp, đêm trăng sáng, cây sāla nở hoa khắp nơi, hương thơm như của chư thiên đang tỏa ngát; ",
  "mn32:6.5": "này Hiền giả Anuruddha, một Tỳ-kheo như thế nào sẽ làm cho rừng Sāla Gosinga thêm đẹp?’”",
  "mn32:6.6": "“Này Hiền giả Sāriputta, ở đây, một Tỳ-kheo với thiên nhãn thanh tịnh, siêu việt loài người, nhìn thấy một ngàn thế giới. ",
  "mn32:6.7": "Ví như, này Hiền giả Sāriputta, một người có mắt, đứng trên lầu cao nhất, có thể nhìn thấy một ngàn vòng bánh xe; ",
  "mn32:6.8": "cũng vậy, này Hiền giả Sāriputta, một Tỳ-kheo với thiên nhãn thanh tịnh, siêu việt loài người, nhìn thấy một ngàn thế giới. ",
  "mn32:6.9": "Này Hiền giả Sāriputta, một Tỳ-kheo như vậy sẽ làm cho rừng Sāla Gosinga thêm đẹp.”",
  "mn32:7.1": "Khi được nói như vậy, Tôn giả Sāriputta nói với Tôn giả Mahākassapa: ",
  "mn32:7.2": "“Này Hiền giả Kassapa, Tôn giả Anuruddha đã trình bày sự hiểu biết của mình. ",
  "mn32:7.3": "Bây giờ chúng tôi hỏi Tôn giả Mahākassapa: ",
  "mn32:7.4": "‘Này Hiền giả Kassapa, rừng Sāla Gosinga thật đẹp, đêm trăng sáng, cây sāla nở hoa khắp nơi, hương thơm như của chư thiên đang tỏa ngát; ",
  "mn32:7.5": "này Hiền giả Kassapa, một Tỳ-kheo như thế nào sẽ làm cho rừng Sāla Gosinga thêm đẹp?’”",
  "mn32:7.6": "“Này Hiền giả Sāriputta, ở đây, một Tỳ-kheo tự mình sống ở rừng và tán thán việc sống ở rừng; tự mình khất thực và tán thán việc khất thực; tự mình mặc y phấn tảo và tán thán việc mặc y phấn tảo; tự mình mặc ba y và tán thán việc mặc ba y; tự mình ít dục và tán thán sự ít dục; tự mình biết đủ và tán thán sự biết đủ; tự mình sống viễn ly và tán thán sự viễn ly; tự mình không giao du và tán thán sự không giao du; tự mình tinh tấn và tán thán sự tinh tấn; tự mình đầy đủ giới và tán thán sự đầy đủ giới; tự mình đầy đủ định và tán thán sự đầy đủ định; tự mình đầy đủ tuệ và tán thán sự đầy đủ tuệ; tự mình đầy đủ giải thoát và tán thán sự đầy đủ giải thoát; tự mình đầy đủ giải thoát tri kiến và tán thán sự đầy đủ giải thoát tri kiến. ",
  "mn32:7.7": "Này Hiền giả Sāriputta, một Tỳ-kheo như vậy sẽ làm cho rừng Sāla Gosinga thêm đẹp.”",
  "mn32:8.1": "Khi được nói như vậy, Tôn giả Sāriputta nói với Tôn giả Mahāmoggallāna: ",
  "mn32:8.2": "“Này Hiền giả Moggallāna, Tôn giả Mahākassapa đã trình bày sự hiểu biết của mình. ",
  "mn32:8.3": "Bây giờ chúng tôi hỏi Tôn giả Mahāmoggallāna: ",
  "mn32:8.4": "‘Này Hiền giả Moggallāna, rừng Sāla Gosinga thật đẹp, đêm trăng sáng, cây sāla nở hoa khắp nơi, hương thơm như của chư thiên đang tỏa ngát; ",
  "mn32:8.5": "này Hiền giả Moggallāna, một Tỳ-kheo như thế nào sẽ làm cho rừng Sāla Gosinga thêm đẹp?’”",
  "mn32:8.6": "“Này Hiền giả Sāriputta, ở đây, hai Tỳ-kheo nói chuyện về Vi Diệu Pháp, họ hỏi nhau những câu hỏi, và khi được hỏi, họ trả lời mà không bị lúng túng, và cuộc nói chuyện của họ là về pháp. ",
  "mn32:8.7": "Này Hiền giả Sāriputta, một Tỳ-kheo như vậy sẽ làm cho rừng Sāla Gosinga thêm đẹp.”",
  "mn32:9.1": "Rồi Tôn giả Mahāmoggallāna nói với Tôn giả Sāriputta: ",
  "mn32:9.2": "“Này Hiền giả Sāriputta, tất cả chúng tôi đã trình bày sự hiểu biết của mình. ",
  "mn32:9.3": "Bây giờ chúng tôi hỏi Tôn giả Sāriputta: ",
  "mn32:9.4": "‘Này Hiền giả Sāriputta, rừng Sāla Gosinga thật đẹp, đêm trăng sáng, cây sāla nở hoa khắp nơi, hương thơm như của chư thiên đang tỏa ngát; ",
  "mn32:9.5": "này Hiền giả Sāriputta, một Tỳ-kheo như thế nào sẽ làm cho rừng Sāla Gosinga thêm đẹp?’”",
  "mn32:9.6": "“Này Hiền giả Moggallāna, ở đây, một Tỳ-kheo làm chủ tâm mình, chứ không phải tâm làm chủ Tỳ-kheo. ",
  "mn32:9.7": "Vị ấy muốn an trú trong thiền định nào vào buổi sáng, vị ấy an trú trong thiền định ấy vào buổi sáng; ",
  "mn32:9.8": "muốn an trú trong thiền định nào vào buổi trưa, vị ấy an trú trong thiền định ấy vào buổi trưa; ",
  "mn32:9.9": "muốn an trú trong thiền định nào vào buổi chiều, vị ấy an trú trong thiền định ấy vào buổi chiều. ",
  "mn32:9.10": "Ví như, này Hiền giả Moggallāna, một vị vua hay một vị đại thần có một hộp đầy những bộ y phục đủ màu sắc. ",
  "mn32:9.11": "Vị ấy muốn mặc bộ y phục nào vào buổi sáng, vị ấy sẽ mặc đúng bộ y phục ấy vào buổi sáng; ",
  "mn32:9.12": "muốn mặc bộ y phục nào vào buổi trưa, vị ấy sẽ mặc đúng bộ y phục ấy vào buổi trưa; ",
  "mn32:9.13": "muốn mặc bộ y phục nào vào buổi chiều, vị ấy sẽ mặc đúng bộ y phục ấy vào buổi chiều. ",
  "mn32:9.14": "Cũng vậy, này Hiền giả Moggallāna, một Tỳ-kheo làm chủ tâm mình, chứ không phải tâm làm chủ Tỳ-kheo. ",
  "mn32:9.15": "Vị ấy muốn an trú trong thiền định nào vào buổi sáng, vị ấy an trú trong thiền định ấy vào buổi sáng; ",
  "mn32:9.16": "muốn an trú trong thiền định nào vào buổi trưa, vị ấy an trú trong thiền định ấy vào buổi trưa; ",
  "mn32:9.17": "muốn an trú trong thiền định nào vào buổi chiều, vị ấy an trú trong thiền định ấy vào buổi chiều. ",
  "mn32:9.18": "Này Hiền giả Moggallāna, một Tỳ-kheo như vậy sẽ làm cho rừng Sāla Gosinga thêm đẹp.”",
  "mn32:10.1": "Rồi Tôn giả Sāriputta nói với các Tôn giả ấy: ",
  "mn32:10.2": "“Này các Hiền giả, tất cả chúng ta đã trình bày sự hiểu biết của mình. ",
  "mn32:10.3": "Này các Hiền giả, chúng ta hãy đi đến chỗ Thế Tôn; sau khi đến, chúng ta sẽ trình bày sự việc này với Thế Tôn. ",
  "mn32:10.4": "Thế Tôn sẽ giải thích cho chúng ta như thế nào, chúng ta sẽ thọ trì như vậy.”",
  "mn32:10.5": "“Thưa vâng, Hiền giả,” các Tôn giả ấy đáp lời Tôn giả Sāriputta. ",
  "mn32:10.6": "Rồi các Tôn giả ấy đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Sāriputta nói với Thế Tôn: ",
  "mn32:11.1": "“Bạch Thế Tôn, ở đây, Tôn giả Revata và Tôn giả Ānanda đã đi đến chỗ con để nghe pháp. ",
  "mn32:11.2": "Bạch Thế Tôn, con đã thấy Tôn giả Revata và Tôn giả Ānanda đang đi đến từ xa. ",
  "mn32:11.3": "Sau khi thấy, con đã nói với Tôn giả Ānanda: ",
  "mn32:11.4": "‘Này Tôn giả Ānanda, hãy đến. ",
  "mn32:11.5": "Chào mừng Tôn giả Ānanda, thị giả của Thế Tôn, người thường ở gần Thế Tôn. ",
  "mn32:11.6": "Này Hiền giả Ānanda, rừng Sāla Gosinga thật đẹp, đêm trăng sáng, cây sāla nở hoa khắp nơi, hương thơm như của chư thiên đang tỏa ngát; ",
  "mn32:11.7": "này Hiền giả Ānanda, một Tỳ-kheo như thế nào sẽ làm cho rừng Sāla Gosinga thêm đẹp?’",
  "mn32:11.8": "Bạch Thế Tôn, khi được nói như vậy, Tôn giả Ānanda đã nói với con: ",
  "mn32:11.9": "‘Này Hiền giả Sāriputta, ở đây, một Tỳ-kheo là người đa văn, thọ trì những điều đã nghe …v.v… ",
  "mn32:11.10": "để diệt trừ các tùy miên. ",
  "mn32:11.11": "Này Hiền giả Sāriputta, một Tỳ-kheo như vậy sẽ làm cho rừng Sāla Gosinga thêm đẹp.’”",
  "mn32:11.12": "“Lành thay, lành thay, Sāriputta. ",
  "mn32:11.13": "Đúng như Ānanda đã giải thích một cách đúng đắn. ",
  "mn32:11.14": "Này Sāriputta, Ānanda là người đa văn, thọ trì những điều đã nghe, tích lũy những điều đã nghe. Những pháp nào sơ thiện, trung thiện, hậu thiện, có nghĩa, có văn, tuyên bố đời sống phạm hạnh hoàn toàn đầy đủ, hoàn toàn thanh tịnh, những pháp như vậy được Ānanda nghe nhiều, thọ trì, đọc tụng thành thạo bằng lời, quán sát bằng ý, và thâm nhập sâu sắc bằng kiến giải. ",
  "mn32:11.15": "Vị ấy thuyết pháp cho bốn chúng hội với những lời lẽ tròn đầy, văn tự liên tục, để diệt trừ các tùy miên.”",
  "mn32:12.1": "“Bạch Thế Tôn, khi được nói như vậy, con đã nói với Tôn giả Revata: ",
  "mn32:12.2": "‘Này Hiền giả Revata, Tôn giả Ānanda đã trình bày sự hiểu biết của mình. ",
  "mn32:12.3": "Bây giờ chúng tôi hỏi Tôn giả Revata—",
  "mn32:12.4": "Này Hiền giả Revata, rừng Sāla Gosinga thật đẹp, đêm trăng sáng, cây sāla nở hoa khắp nơi, hương thơm như của chư thiên đang tỏa ngát. ",
  "mn32:12.5": "Này Hiền giả Revata, một Tỳ-kheo như thế nào sẽ làm cho rừng Sāla Gosinga thêm đẹp?’",
  "mn32:12.6": "Bạch Thế Tôn, khi được nói như vậy, Tôn giả Revata đã nói với con: ",
  "mn32:12.7": "‘Này Hiền giả Sāriputta, ở đây, một Tỳ-kheo ưa thích thiền tịnh, hoan hỷ với thiền tịnh, chuyên tâm vào sự an tịnh nội tâm, không bỏ thiền định, đầy đủ tuệ quán, là người phát triển các trú xứ không. ",
  "mn32:12.8": "Này Hiền giả Sāriputta, một Tỳ-kheo như vậy sẽ làm cho rừng Sāla Gosinga thêm đẹp.’”",
  "mn32:12.9": "“Lành thay, lành thay, Sāriputta. ",
  "mn32:12.10": "Đúng như Revata đã giải thích một cách đúng đắn. ",
  "mn32:12.11": "Này Sāriputta, Revata là người ưa thích thiền tịnh, hoan hỷ với thiền tịnh, chuyên tâm vào sự an tịnh nội tâm, không bỏ thiền định, đầy đủ tuệ quán, là người phát triển các trú xứ không.”",
  "mn32:13.1": "“Bạch Thế Tôn, khi được nói như vậy, con đã nói với Tôn giả Anuruddha: ",
  "mn32:13.2": "‘Này Hiền giả Anuruddha, Tôn giả Revata đã trình bày …v.v… ",
  "mn32:13.3": "này Hiền giả Anuruddha, một Tỳ-kheo như thế nào sẽ làm cho rừng Sāla Gosinga thêm đẹp?’",
  "mn32:13.4": "Bạch Thế Tôn, khi được nói như vậy, Tôn giả Anuruddha đã nói với con: ",
  "mn32:13.5": "‘Này Hiền giả Sāriputta, ở đây, một Tỳ-kheo với thiên nhãn thanh tịnh, siêu việt loài người, nhìn thấy một ngàn thế giới. ",
  "mn32:13.6": "Ví như, này Hiền giả Sāriputta, một người có mắt …v.v… ",
  "mn32:13.7": "Này Hiền giả Sāriputta, một Tỳ-kheo như vậy sẽ làm cho rừng Sāla Gosinga thêm đẹp.’”",
  "mn32:13.8": "“Lành thay, lành thay, Sāriputta, đúng như Anuruddha đã giải thích một cách đúng đắn. ",
  "mn32:13.9": "Này Sāriputta, Anuruddha với thiên nhãn thanh tịnh, siêu việt loài người, nhìn thấy một ngàn thế giới.”",
  "mn32:14.1": "“Bạch Thế Tôn, khi được nói như vậy, con đã nói với Tôn giả Mahākassapa: ",
  "mn32:14.2": "‘Này Hiền giả Kassapa, Tôn giả Anuruddha đã trình bày sự hiểu biết của mình. ",
  "mn32:14.3": "Bây giờ chúng tôi hỏi Tôn giả Mahākassapa …v.v… ",
  "mn32:14.4": "này Hiền giả Kassapa, một Tỳ-kheo như thế nào sẽ làm cho rừng Sāla Gosinga thêm đẹp?’",
  "mn32:14.5": "Bạch Thế Tôn, khi được nói như vậy, Tôn giả Mahākassapa đã nói với con: ",
  "mn32:14.6": "‘Này Hiền giả Sāriputta, ở đây, một Tỳ-kheo tự mình sống ở rừng và tán thán việc sống ở rừng; tự mình khất thực và tán thán việc khất thực …v.v… tự mình mặc y phấn tảo và tán thán việc mặc y phấn tảo …v.v… tự mình mặc ba y và tán thán việc mặc ba y …v.v… tự mình ít dục và tán thán sự ít dục …v.v… tự mình biết đủ và tán thán sự biết đủ …v.v… tự mình sống viễn ly và tán thán sự viễn ly …v.v… tự mình không giao du và tán thán sự không giao du …v.v… tự mình tinh tấn và tán thán sự tinh tấn …v.v… tự mình đầy đủ giới và tán thán sự đầy đủ giới …v.v… tự mình đầy đủ định và tán thán sự đầy đủ định …v.v… tự mình đầy đủ tuệ … tự mình đầy đủ giải thoát … tự mình đầy đủ giải thoát tri kiến và tán thán sự đầy đủ giải thoát tri kiến. ",
  "mn32:14.7": "Này Hiền giả Sāriputta, một Tỳ-kheo như vậy sẽ làm cho rừng Sāla Gosinga thêm đẹp.’”",
  "mn32:14.8": "“Lành thay, lành thay, Xá-lợi-phất. ",
  "mn32:14.9": "Như Tôn giả Kassapa đã giải thích đúng đắn. ",
  "mn32:14.10": "Này Xá-lợi-phất, Tôn giả Kassapa tự mình sống hạnh ở rừng và tán thán hạnh ở rừng; tự mình sống hạnh khất thực và tán thán hạnh khất thực; tự mình sống hạnh mặc y phấn tảo và tán thán hạnh mặc y phấn tảo; tự mình sống hạnh ba y và tán thán hạnh ba y; tự mình sống ít muốn và tán thán sự ít muốn; tự mình sống biết đủ và tán thán sự biết đủ; tự mình sống viễn ly và tán thán sự viễn ly; tự mình sống không giao du và tán thán sự không giao du; tự mình tinh tấn và tán thán sự tinh tấn; tự mình đầy đủ giới và tán thán sự đầy đủ giới; tự mình đầy đủ định và tán thán sự đầy đủ định; tự mình đầy đủ tuệ và tán thán sự đầy đủ tuệ; tự mình đầy đủ giải thoát và tán thán sự đầy đủ giải thoát; tự mình đầy đủ giải thoát tri kiến và tán thán sự đầy đủ giải thoát tri kiến.”",
  "mn32:15.1": "“Khi được nói vậy, bạch Thế Tôn, con đã nói với Tôn giả Đại Mục-kiền-liên rằng: ",
  "mn32:15.2": "‘Này Hiền giả Mục-kiền-liên, Tôn giả Đại Kassapa đã giải thích theo sự hiểu biết của mình. ",
  "mn32:15.3": "Bây giờ chúng ta hãy hỏi Tôn giả Đại Mục-kiền-liên …pe… ",
  "mn32:15.4": "Này Hiền giả Mục-kiền-liên, tỳ-kheo như thế nào làm cho rừng Sa-la Gosinga thêm đẹp?’",
  "mn32:15.5": "Khi được nói vậy, bạch Thế Tôn, Tôn giả Đại Mục-kiền-liên đã nói với con rằng: ",
  "mn32:15.6": "‘Này Hiền giả Xá-lợi-phất, ở đây có hai tỳ-kheo nói chuyện về Vi Diệu Pháp. Họ hỏi nhau những câu hỏi, và khi được hỏi, họ trả lời những câu hỏi của nhau, không làm cho nhau lúng túng, và câu chuyện của họ là câu chuyện về Pháp. ",
  "mn32:15.7": "Này Hiền giả Xá-lợi-phất, tỳ-kheo như thế ấy làm cho rừng Sa-la Gosinga thêm đẹp.’”",
  "mn32:15.8": "“Lành thay, lành thay, Xá-lợi-phất, như Tôn giả Mục-kiền-liên đã giải thích đúng đắn. ",
  "mn32:15.9": "Này Xá-lợi-phất, Tôn giả Mục-kiền-liên là người thuyết pháp.”",
  "mn32:16.1": "Khi được nói vậy, Tôn giả Đại Mục-kiền-liên đã nói với Thế Tôn rằng: ",
  "mn32:16.2": "“Bạch Thế Tôn, sau đó con đã nói với Tôn giả Xá-lợi-phất rằng: ",
  "mn32:16.3": "‘Này Hiền giả Xá-lợi-phất, tất cả chúng ta đã giải thích theo sự hiểu biết của mình. ",
  "mn32:16.4": "Bây giờ chúng ta hãy hỏi Tôn giả Xá-lợi-phất—",
  "mn32:16.5": "Này Hiền giả Xá-lợi-phất, rừng Sa-la Gosinga thật đáng yêu, đêm trăng sáng, cây sa-la nở hoa khắp nơi, hương thơm như của chư thiên đang tỏa ra. ",
  "mn32:16.6": "Này Hiền giả Xá-lợi-phất, tỳ-kheo như thế nào làm cho rừng Sa-la Gosinga thêm đẹp?’",
  "mn32:16.7": "Khi được nói vậy, bạch Thế Tôn, Tôn giả Xá-lợi-phất đã nói với con rằng: ",
  "mn32:16.8": "‘Này Hiền giả Mục-kiền-liên, ở đây tỳ-kheo làm chủ tâm mình, chứ không phải tâm làm chủ tỳ-kheo. ",
  "mn32:16.9": "Vị ấy muốn an trú trong trạng thái an trú nào vào buổi sáng, vị ấy an trú trong trạng thái an trú ấy vào buổi sáng; ",
  "mn32:16.10": "vị ấy muốn an trú trong trạng thái an trú nào vào buổi trưa, vị ấy an trú trong trạng thái an trú ấy vào buổi trưa; ",
  "mn32:16.11": "vị ấy muốn an trú trong trạng thái an trú nào vào buổi chiều, vị ấy an trú trong trạng thái an trú ấy vào buổi chiều. ",
  "mn32:16.12": "Này Hiền giả Mục-kiền-liên, ví như một vị vua hay một vị đại thần có một hộp đầy những bộ y phục đủ màu sắc. ",
  "mn32:16.13": "Vị ấy muốn mặc bộ y phục nào vào buổi sáng, vị ấy sẽ mặc đúng bộ y phục ấy vào buổi sáng; ",
  "mn32:16.14": "vị ấy muốn mặc bộ y phục nào vào buổi trưa, vị ấy sẽ mặc đúng bộ y phục ấy vào buổi trưa; ",
  "mn32:16.15": "vị ấy muốn mặc bộ y phục nào vào buổi chiều, vị ấy sẽ mặc đúng bộ y phục ấy vào buổi chiều. ",
  "mn32:16.16": "Cũng vậy, này Hiền giả Mục-kiền-liên, tỳ-kheo làm chủ tâm mình, chứ không phải tâm làm chủ tỳ-kheo. ",
  "mn32:16.17": "Vị ấy muốn an trú trong trạng thái an trú nào vào buổi sáng, vị ấy an trú trong trạng thái an trú ấy vào buổi sáng; ",
  "mn32:16.18": "vị ấy muốn an trú trong trạng thái an trú nào vào buổi trưa, vị ấy an trú trong trạng thái an trú ấy vào buổi trưa; ",
  "mn32:16.19": "vị ấy muốn an trú trong trạng thái an trú nào vào buổi chiều, vị ấy an trú trong trạng thái an trú ấy vào buổi chiều. ",
  "mn32:16.20": "Này Hiền giả Mục-kiền-liên, tỳ-kheo như thế ấy làm cho rừng Sa-la Gosinga thêm đẹp.’”",
  "mn32:16.21": "“Lành thay, lành thay, Mục-kiền-liên. ",
  "mn32:16.22": "Như Tôn giả Xá-lợi-phất đã giải thích đúng đắn. ",
  "mn32:16.23": "Này Mục-kiền-liên, Tôn giả Xá-lợi-phất làm chủ tâm mình, chứ không phải Tôn giả Xá-lợi-phất bị tâm làm chủ. ",
  "mn32:16.24": "Vị ấy muốn an trú trong trạng thái an trú nào vào buổi sáng, vị ấy an trú trong trạng thái an trú ấy vào buổi sáng; ",
  "mn32:16.25": "vị ấy muốn an trú trong trạng thái an trú nào vào buổi trưa, vị ấy an trú trong trạng thái an trú ấy vào buổi trưa; ",
  "mn32:16.26": "vị ấy muốn an trú trong trạng thái an trú nào vào buổi chiều, vị ấy an trú trong trạng thái an trú ấy vào buổi chiều.”",
  "mn32:17.1": "Khi được nói vậy, Tôn giả Xá-lợi-phất đã nói với Thế Tôn rằng: ",
  "mn32:17.2": "“Bạch Thế Tôn, vậy lời nói của ai là lời nói hay?”",
  "mn32:17.3": "“Này Xá-lợi-phất, lời nói của tất cả các con đều là lời nói hay, tùy theo cách nói. ",
  "mn32:17.4": "Nhưng các con cũng hãy nghe ta nói về tỳ-kheo như thế nào làm cho rừng Sa-la Gosinga thêm đẹp. ",
  "mn32:17.5": "Này Xá-lợi-phất, ở đây, một tỳ-kheo sau khi khất thực trở về, ngồi kiết già, lưng thẳng, đặt niệm trước mặt và nghĩ: ",
  "mn32:17.6": "‘Ta sẽ không rời khỏi tư thế ngồi này cho đến khi tâm ta được giải thoát khỏi các lậu hoặc mà không còn chấp thủ.’",
  "mn32:17.7": "Này Xá-lợi-phất, tỳ-kheo như thế ấy làm cho rừng Sa-la Gosinga thêm đẹp.”",
  "mn32:17.8": "Thế Tôn đã nói điều này. ",
  "mn32:17.9": "Các Tôn giả hoan hỷ và tán thán lời Thế Tôn dạy. ",
  "mn32:17.10": "Kinh Đại Gosinga, phẩm thứ hai, chấm dứt. "
}
window.BILARA["mn32"]["vi"]["mn32:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
