window.BILARA = window.BILARA || {};
window.BILARA["mn33"] = window.BILARA["mn33"] || {};
window.BILARA["mn33"]["vi"] = {
  "mn33:0.1": "Trung Bộ Kinh 33 ",
  "mn33:0.2": "Đại Kinh Người Chăn Bò ",
  "mn33:1.1": "Tôi nghe như vầy—",
  "mn33:1.2": "Một thời, Thế Tôn trú ở Sāvatthī, tại Jetavana, khu vườn của Anāthapiṇḍika. ",
  "mn33:1.3": "Tại đấy, Thế Tôn gọi các Tỳ-kheo: ",
  "mn33:1.4": "“Này các Tỳ-kheo”. ",
  "mn33:1.5": "Các Tỳ-kheo ấy vâng đáp Thế Tôn: “Bạch Thế Tôn”. ",
  "mn33:1.6": "Thế Tôn nói như sau: ",
  "mn33:2.1": "“Này các Tỳ-kheo, người chăn bò có mười một yếu tố thì không thể chăm sóc đàn bò, không thể làm cho chúng phát triển. ",
  "mn33:2.2": "Mười một yếu tố ấy là gì? ",
  "mn33:2.3": "Ở đây, này các Tỳ-kheo, người chăn bò không biết hình dáng, không khéo về tướng, không biết loại bỏ những con bò cái gây hại, không biết băng bó vết thương, không biết hun khói, không biết bến nước, không biết chỗ uống, không biết đường đi, không khéo về bãi cỏ, và vắt sữa không chừa lại. Những con bò đực đầu đàn, cha của đàn bò, dẫn đầu đàn bò, người ấy không biết tôn kính đặc biệt. ",
  "mn33:2.4": "Này các Tỳ-kheo, người chăn bò có mười một yếu tố này thì không thể chăm sóc đàn bò, không thể làm cho chúng phát triển. ",
  "mn33:3.1": "Cũng vậy, này các Tỳ-kheo, Tỳ-kheo có mười một pháp thì không thể tăng trưởng, lớn mạnh, phát triển trong Pháp và Luật này. ",
  "mn33:3.2": "Mười một pháp ấy là gì? ",
  "mn33:3.3": "Ở đây, này các Tỳ-kheo, Tỳ-kheo không biết hình dáng, không khéo về tướng, không biết loại bỏ những con bò cái gây hại, không biết băng bó vết thương, không biết hun khói, không biết bến nước, không biết chỗ uống, không biết đường đi, không khéo về bãi cỏ, và vắt sữa không chừa lại. Những Tỳ-kheo Trưởng lão, có kinh nghiệm lâu năm, xuất gia đã lâu, là cha của Tăng đoàn, dẫn đầu Tăng đoàn, người ấy không biết tôn kính đặc biệt. ",
  "mn33:4.1": "Và này các Tỳ-kheo, Tỳ-kheo không biết hình dáng như thế nào? ",
  "mn33:4.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo không như thật biết bất cứ sắc nào, tất cả sắc là ‘bốn đại chủng, và sắc do bốn đại chủng tạo thành’. ",
  "mn33:4.3": "Này các Tỳ-kheo, Tỳ-kheo không biết hình dáng là như vậy. ",
  "mn33:5.1": "Và này các Tỳ-kheo, Tỳ-kheo không khéo về tướng như thế nào? ",
  "mn33:5.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo không như thật biết ‘kẻ ngu có tướng nghiệp, người trí có tướng nghiệp’. ",
  "mn33:5.3": "Này các Tỳ-kheo, Tỳ-kheo không khéo về tướng là như vậy. ",
  "mn33:6.1": "Và này các Tỳ-kheo, Tỳ-kheo không biết loại bỏ những con bò cái gây hại như thế nào? ",
  "mn33:6.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo chấp nhận ý nghĩ dục đã khởi lên, không từ bỏ, không loại trừ, không chấm dứt, không đưa đến không còn nữa. Ý nghĩ sân hận đã khởi lên …pe… ý nghĩ hại người đã khởi lên …pe… những pháp bất thiện, ác đã khởi lên, người ấy chấp nhận, không từ bỏ, không loại trừ, không chấm dứt, không đưa đến không còn nữa. ",
  "mn33:6.3": "Này các Tỳ-kheo, Tỳ-kheo không biết loại bỏ những con bò cái gây hại là như vậy. ",
  "mn33:7.1": "Và này các Tỳ-kheo, Tỳ-kheo không biết băng bó vết thương như thế nào? ",
  "mn33:7.2": "Ở đây, này các Tỳ-kheo, khi thấy sắc bằng mắt, Tỳ-kheo nắm giữ tướng chung, nắm giữ tướng riêng. ",
  "mn33:7.3": "Vì không chế ngự nhãn căn, các pháp bất thiện, ác như tham ái và ưu phiền có thể xâm nhập, người ấy không thực hành để chế ngự, không bảo vệ nhãn căn, không đạt được sự chế ngự nơi nhãn căn. ",
  "mn33:7.4": "Khi nghe tiếng bằng tai …pe… ",
  "mn33:7.5": "Khi ngửi mùi bằng mũi …pe… ",
  "mn33:7.6": "Khi nếm vị bằng lưỡi …pe… ",
  "mn33:7.7": "Khi xúc chạm bằng thân …pe… ",
  "mn33:7.8": "Khi nhận biết pháp bằng ý, Tỳ-kheo nắm giữ tướng chung, nắm giữ tướng riêng. ",
  "mn33:7.9": "Vì không chế ngự ý căn, các pháp bất thiện, ác như tham ái và ưu phiền có thể xâm nhập, người ấy không thực hành để chế ngự, không bảo vệ ý căn, không đạt được sự chế ngự nơi ý căn. ",
  "mn33:7.10": "Này các Tỳ-kheo, Tỳ-kheo không biết băng bó vết thương là như vậy. ",
  "mn33:8.1": "Và này các Tỳ-kheo, Tỳ-kheo không biết hun khói như thế nào? ",
  "mn33:8.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo không giảng rộng Pháp đã nghe, đã học cho người khác. ",
  "mn33:8.3": "Này các Tỳ-kheo, Tỳ-kheo không biết hun khói là như vậy. ",
  "mn33:9.1": "Và này các Tỳ-kheo, Tỳ-kheo không biết bến nước như thế nào? ",
  "mn33:9.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo không đến hỏi, không chất vấn những Tỳ-kheo đa văn, thông thuộc kinh điển, giữ gìn Pháp, giữ gìn Luật, giữ gìn các điều căn bản, vào lúc thích hợp: ",
  "mn33:9.3": "‘Bạch Tôn giả, điều này là gì? ",
  "mn33:9.4": "Ý nghĩa của điều này là gì?’ ",
  "mn33:9.5": "Do đó, các Tôn giả ấy không mở ra những điều chưa được mở, không làm rõ những điều chưa được làm rõ, không giải tỏa nghi ngờ trong nhiều pháp đáng nghi ngờ. ",
  "mn33:9.6": "Này các Tỳ-kheo, Tỳ-kheo không biết bến nước là như vậy. ",
  "mn33:10.1": "Và này các Tỳ-kheo, Tỳ-kheo không biết chỗ uống như thế nào? ",
  "mn33:10.2": "Ở đây, này các Tỳ-kheo, khi Pháp và Luật do Như Lai thuyết giảng được trình bày, Tỳ-kheo không đạt được sự hiểu biết về ý nghĩa, không đạt được sự hiểu biết về Pháp, không đạt được niềm vui liên quan đến Pháp. ",
  "mn33:10.3": "Này các Tỳ-kheo, Tỳ-kheo không biết chỗ uống là như vậy. ",
  "mn33:11.1": "Và này các Tỳ-kheo, Tỳ-kheo không biết đường đi như thế nào? ",
  "mn33:11.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo không như thật biết Bát Chánh Đạo. ",
  "mn33:11.3": "Này các Tỳ-kheo, Tỳ-kheo không biết đường đi là như vậy. ",
  "mn33:12.1": "Và này các Tỳ-kheo, Tỳ-kheo không khéo về bãi cỏ như thế nào? ",
  "mn33:12.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo không như thật biết Tứ Niệm Xứ. ",
  "mn33:12.3": "Này các Tỳ-kheo, Tỳ-kheo không khéo về bãi cỏ là như vậy. ",
  "mn33:13.1": "Và này các Tỳ-kheo, Tỳ-kheo vắt sữa không chừa lại như thế nào? ",
  "mn33:13.2": "Ở đây, này các Tỳ-kheo, các gia chủ có lòng tin cúng dường Tỳ-kheo y phục, đồ ăn khất thực, chỗ ở, thuốc men trị bệnh, nhưng Tỳ-kheo không biết chừng mực khi thọ nhận. ",
  "mn33:13.3": "Này các Tỳ-kheo, Tỳ-kheo vắt sữa không chừa lại là như vậy. ",
  "mn33:14.1": "Và này các Tỳ-kheo, Tỳ-kheo không biết tôn kính đặc biệt những Tỳ-kheo Trưởng lão, có kinh nghiệm lâu năm, xuất gia đã lâu, là cha của Tăng đoàn, dẫn đầu Tăng đoàn như thế nào? ",
  "mn33:14.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo không thực hành thân nghiệp từ ái đối với những Tỳ-kheo Trưởng lão, có kinh nghiệm lâu năm, xuất gia đã lâu, là cha của Tăng đoàn, dẫn đầu Tăng đoàn, cả công khai lẫn bí mật; ",
  "mn33:14.3": "không thực hành khẩu nghiệp từ ái cả công khai lẫn bí mật; ",
  "mn33:14.4": "không thực hành ý nghiệp từ ái cả công khai lẫn bí mật. ",
  "mn33:14.5": "Này các Tỳ-kheo, Tỳ-kheo không biết tôn kính đặc biệt những Tỳ-kheo Trưởng lão, có kinh nghiệm lâu năm, xuất gia đã lâu, là cha của Tăng đoàn, dẫn đầu Tăng đoàn là như vậy. ",
  "mn33:14.6": "Này các Tỳ-kheo, Tỳ-kheo có mười một pháp này thì không thể tăng trưởng, lớn mạnh, phát triển trong Pháp và Luật này. ",
  "mn33:15.1": "Này các Tỳ-kheo, người chăn bò có mười một yếu tố thì có thể chăm sóc đàn bò, có thể làm cho chúng phát triển. ",
  "mn33:15.2": "Mười một yếu tố ấy là gì? ",
  "mn33:15.3": "Ở đây, này các Tỳ-kheo, người chăn bò biết hình dáng, khéo về tướng, biết loại bỏ những con bò cái gây hại, biết băng bó vết thương, biết hun khói, biết bến nước, biết chỗ uống, biết đường đi, khéo về bãi cỏ, và vắt sữa có chừa lại. Những con bò đực đầu đàn, cha của đàn bò, dẫn đầu đàn bò, người ấy biết tôn kính đặc biệt. ",
  "mn33:15.4": "Này các Tỳ-kheo, người chăn bò có mười một yếu tố này thì có thể chăm sóc đàn bò, có thể làm cho chúng phát triển. ",
  "mn33:16.1": "Cũng vậy, này các Tỳ-kheo, Tỳ-kheo có mười một pháp thì có thể tăng trưởng, lớn mạnh, phát triển trong Pháp và Luật này. ",
  "mn33:16.2": "Mười một pháp ấy là gì? ",
  "mn33:16.3": "Ở đây, này các Tỳ-kheo, Tỳ-kheo biết hình dáng, khéo về tướng, biết loại bỏ những con bò cái gây hại, biết băng bó vết thương, biết hun khói, biết bến nước, biết chỗ uống, biết đường đi, khéo về bãi cỏ, và vắt sữa có chừa lại. Những Tỳ-kheo Trưởng lão, có kinh nghiệm lâu năm, xuất gia đã lâu, là cha của Tăng đoàn, dẫn đầu Tăng đoàn, người ấy biết tôn kính đặc biệt. ",
  "mn33:17.1": "Và này các Tỳ-kheo, Tỳ-kheo biết hình dáng như thế nào? ",
  "mn33:17.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo như thật biết bất cứ sắc nào, tất cả sắc là ‘bốn đại chủng, và sắc do bốn đại chủng tạo thành’. ",
  "mn33:17.3": "Này các Tỳ-kheo, Tỳ-kheo biết hình dáng là như vậy. ",
  "mn33:18.1": "Và này các Tỳ-kheo, Tỳ-kheo khéo về tướng như thế nào? ",
  "mn33:18.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo như thật biết ‘kẻ ngu có tướng nghiệp, người trí có tướng nghiệp’. ",
  "mn33:18.3": "Này các Tỳ-kheo, Tỳ-kheo khéo về tướng là như vậy. ",
  "mn33:19.1": "Và này các Tỳ-kheo, Tỳ-kheo biết loại bỏ những con bò cái gây hại như thế nào? ",
  "mn33:19.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo không chấp nhận ý nghĩ dục đã khởi lên, từ bỏ, loại trừ, chấm dứt, đưa đến không còn nữa. Ý nghĩ sân hận đã khởi lên …pe… ý nghĩ hại người đã khởi lên …pe… những pháp bất thiện, ác đã khởi lên, người ấy không chấp nhận, từ bỏ, loại trừ, chấm dứt, đưa đến không còn nữa. ",
  "mn33:19.3": "Này các Tỳ-kheo, Tỳ-kheo biết loại bỏ những con bò cái gây hại là như vậy. ",
  "mn33:20.1": "Và này các Tỳ-kheo, Tỳ-kheo biết băng bó vết thương như thế nào? ",
  "mn33:20.2": "Ở đây, này các Tỳ-kheo, khi thấy sắc bằng mắt, Tỳ-kheo không nắm giữ tướng chung, không nắm giữ tướng riêng. ",
  "mn33:20.3": "Vì không chế ngự nhãn căn, các pháp bất thiện, ác như tham ái và ưu phiền có thể xâm nhập, người ấy thực hành để chế ngự, bảo vệ nhãn căn, đạt được sự chế ngự nơi nhãn căn. ",
  "mn33:20.4": "Khi nghe tiếng bằng tai …pe… ",
  "mn33:20.5": "Khi ngửi mùi bằng mũi …pe… ",
  "mn33:20.6": "Khi nếm vị bằng lưỡi …pe… ",
  "mn33:20.7": "Khi xúc chạm bằng thân …pe… ",
  "mn33:20.8": "Khi nhận biết pháp bằng ý, Tỳ-kheo không nắm giữ tướng chung, không nắm giữ tướng riêng. ",
  "mn33:20.9": "Vì không chế ngự ý căn, các pháp bất thiện, ác như tham ái và ưu phiền có thể xâm nhập, người ấy thực hành để chế ngự, bảo vệ ý căn, đạt được sự chế ngự nơi ý căn. ",
  "mn33:20.10": "Này các Tỳ-kheo, Tỳ-kheo biết băng bó vết thương là như vậy. ",
  "mn33:21.1": "Và này các Tỳ-kheo, Tỳ-kheo biết hun khói như thế nào? ",
  "mn33:21.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo giảng rộng Pháp đã nghe, đã học cho người khác. ",
  "mn33:21.3": "Này các Tỳ-kheo, Tỳ-kheo biết hun khói là như vậy. ",
  "mn33:22.1": "Và này các Tỳ-kheo, Tỳ-kheo biết bến nước như thế nào? ",
  "mn33:22.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo đến hỏi, chất vấn những Tỳ-kheo đa văn, thông thuộc kinh điển, giữ gìn Pháp, giữ gìn Luật, giữ gìn các điều căn bản, vào lúc thích hợp: ",
  "mn33:22.3": "‘Bạch Tôn giả, điều này là gì? ",
  "mn33:22.4": "Ý nghĩa của điều này là gì?’ ",
  "mn33:22.5": "Do đó, các Tôn giả ấy mở ra những điều chưa được mở, làm rõ những điều chưa được làm rõ, giải tỏa nghi ngờ trong nhiều pháp đáng nghi ngờ. ",
  "mn33:22.6": "Này các Tỳ-kheo, Tỳ-kheo biết bến nước là như vậy. ",
  "mn33:23.1": "Và này các Tỳ-kheo, Tỳ-kheo biết chỗ uống như thế nào? ",
  "mn33:23.2": "Ở đây, này các Tỳ-kheo, khi Pháp và Luật do Như Lai thuyết giảng được trình bày, Tỳ-kheo đạt được sự hiểu biết về ý nghĩa, đạt được sự hiểu biết về Pháp, đạt được niềm vui liên quan đến Pháp. ",
  "mn33:23.3": "Này các Tỳ-kheo, Tỳ-kheo biết chỗ uống là như vậy. ",
  "mn33:24.1": "Và này các Tỳ-kheo, Tỳ-kheo biết đường đi như thế nào? ",
  "mn33:24.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo như thật biết Bát Chánh Đạo. ",
  "mn33:24.3": "Này các Tỳ-kheo, Tỳ-kheo biết đường đi là như vậy. ",
  "mn33:25.1": "Và này các Tỳ-kheo, Tỳ-kheo khéo về bãi cỏ như thế nào? ",
  "mn33:25.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo như thật biết Tứ Niệm Xứ. ",
  "mn33:25.3": "Này các Tỳ-kheo, Tỳ-kheo khéo về bãi cỏ là như vậy. ",
  "mn33:26.1": "Và này các Tỳ-kheo, Tỳ-kheo vắt sữa có chừa lại như thế nào? ",
  "mn33:26.2": "Ở đây, này các Tỳ-kheo, các gia chủ có lòng tin cúng dường Tỳ-kheo y phục, đồ ăn khất thực, chỗ ở, thuốc men trị bệnh. ",
  "mn33:26.3": "Tại đấy, Tỳ-kheo biết chừng mực khi thọ nhận. ",
  "mn33:26.4": "Này các Tỳ-kheo, Tỳ-kheo vắt sữa có chừa lại là như vậy. ",
  "mn33:27.1": "Và này các Tỳ-kheo, Tỳ-kheo biết tôn kính đặc biệt những Tỳ-kheo Trưởng lão, có kinh nghiệm lâu năm, xuất gia đã lâu, là cha của Tăng đoàn, dẫn đầu Tăng đoàn như thế nào? ",
  "mn33:27.2": "Ở đây, này các Tỳ-kheo, Tỳ-kheo thực hành thân nghiệp từ ái đối với những Tỳ-kheo Trưởng lão, có kinh nghiệm lâu năm, xuất gia đã lâu, là cha của Tăng đoàn, dẫn đầu Tăng đoàn, cả công khai lẫn bí mật; ",
  "mn33:27.3": "thực hành khẩu nghiệp từ ái cả công khai lẫn bí mật; ",
  "mn33:27.4": "thực hành ý nghiệp từ ái cả công khai lẫn bí mật. ",
  "mn33:27.5": "Này các Tỳ-kheo, Tỳ-kheo biết tôn kính đặc biệt những Tỳ-kheo Trưởng lão, có kinh nghiệm lâu năm, xuất gia đã lâu, là cha của Tăng đoàn, dẫn đầu Tăng đoàn là như vậy. ",
  "mn33:27.6": "Này các Tỳ-kheo, Tỳ-kheo có mười một pháp này thì có thể tăng trưởng, lớn mạnh, phát triển trong Pháp và Luật này”. ",
  "mn33:27.7": "Thế Tôn đã nói như vậy. ",
  "mn33:27.8": "Các Tỳ-kheo ấy hoan hỷ, tùy hỷ lời Thế Tôn dạy. ",
  "mn33:27.9": "Đại Kinh Người Chăn Bò, bài thứ ba, chấm dứt. "
}
window.BILARA["mn33"]["vi"]["mn33:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
