window.BILARA = window.BILARA || {};
window.BILARA["mn36"] = window.BILARA["mn36"] || {};
window.BILARA["mn36"]["vi"] = {
  "mn36:0.1": "Trung Bộ Kinh 36 ",
  "mn36:0.2": "Kinh Đại Saccaka ",
  "mn36:1.1": "Tôi nghe như vầy—",
  "mn36:1.2": "Một thời Thế Tôn trú ở Vesālī, tại Đại Lâm, Trùng Các. ",
  "mn36:2.1": "Lúc bấy giờ, vào buổi sáng, Thế Tôn đắp y, cầm bát, đi vào Vesālī để khất thực. ",
  "mn36:3.1": "Rồi Saccaka, con của Nigaṇṭha, đang đi dạo, đi đến Đại Lâm, Trùng Các. ",
  "mn36:3.2": "Tôn giả Ānanda thấy Saccaka, con của Nigaṇṭha, từ xa đi đến. ",
  "mn36:3.3": "Thấy vậy, Tôn giả bạch Thế Tôn: ",
  "mn36:3.4": "“Bạch Thế Tôn, Saccaka, con của Nigaṇṭha, đang đi đến. Người này hay tranh luận, tự cho mình là bậc trí, được nhiều người kính trọng. ",
  "mn36:3.5": "Bạch Thế Tôn, người này muốn chê bai Phật, muốn chê bai Pháp, muốn chê bai Tăng. ",
  "mn36:3.6": "Bạch Thế Tôn, xin Thế Tôn hãy ngồi lại một lát, vì lòng thương xót.” ",
  "mn36:3.7": "Thế Tôn ngồi xuống trên chỗ đã trải sẵn. ",
  "mn36:3.8": "Rồi Saccaka, con của Nigaṇṭha, đi đến chỗ Thế Tôn. Sau khi đến, người ấy nói những lời chào hỏi, thăm hỏi thân mật với Thế Tôn, rồi ngồi xuống một bên. Ngồi xuống một bên, Saccaka, con của Nigaṇṭha, bạch Thế Tôn: ",
  "mn36:4.1": "“Thưa Tôn giả Gotama, có một số Sa-môn, Bà-la-môn sống chuyên cần tu tập thân, không tu tập tâm. ",
  "mn36:4.2": "Thưa Tôn giả Gotama, họ cảm nhận khổ thọ về thân. ",
  "mn36:4.3": "Thưa Tôn giả Gotama, trong quá khứ, khi bị khổ thọ về thân chạm đến, có người bị cứng đơ đùi, có người tim vỡ, có người máu nóng trào ra từ miệng, có người phát điên, tâm loạn. ",
  "mn36:4.4": "Thưa Tôn giả Gotama, tâm của người ấy bị thân chi phối, tùy thuộc vào thân. ",
  "mn36:4.5": "Vì sao vậy? ",
  "mn36:4.6": "Vì tâm chưa được tu tập. ",
  "mn36:4.7": "Nhưng thưa Tôn giả Gotama, có một số Sa-môn, Bà-la-môn sống chuyên cần tu tập tâm, không tu tập thân. ",
  "mn36:4.8": "Thưa Tôn giả Gotama, họ cảm nhận khổ thọ về tâm. ",
  "mn36:4.9": "Thưa Tôn giả Gotama, trong quá khứ, khi bị khổ thọ về tâm chạm đến, có người bị cứng đơ đùi, có người tim vỡ, có người máu nóng trào ra từ miệng, có người phát điên, tâm loạn. ",
  "mn36:4.10": "Thưa Tôn giả Gotama, thân của người ấy bị tâm chi phối, tùy thuộc vào tâm. ",
  "mn36:4.11": "Vì sao vậy? ",
  "mn36:4.12": "Vì thân chưa được tu tập. ",
  "mn36:4.13": "Thưa Tôn giả Gotama, tôi nghĩ như vầy: ",
  "mn36:4.14": "‘Chắc chắn các đệ tử của Tôn giả Gotama sống chuyên cần tu tập tâm, không tu tập thân.’” ",
  "mn36:5.1": "“Này Aggivessana, ông đã nghe về sự tu tập thân như thế nào?” ",
  "mn36:5.2": "“Thưa Tôn giả, đó là—",
  "mn36:5.3": "Nanda Vaccha, Kisa Saṅkicca, Makkhali Gosāla—",
  "mn36:5.4": "Thưa Tôn giả Gotama, những người này là những người lõa thể, sống phóng túng, liếm tay, không nhận lời mời ‘hãy đến đây’, không nhận lời mời ‘hãy đứng lại’, không nhận thức ăn mang đến, không nhận thức ăn dành riêng, không nhận thức ăn do mời. ",
  "mn36:5.5": "Họ không nhận thức ăn từ miệng nồi, không nhận thức ăn từ miệng bát, không nhận thức ăn giữa hai con dê, không nhận thức ăn giữa hai cây gậy, không nhận thức ăn giữa hai người đang ăn, không nhận thức ăn từ phụ nữ có thai, không nhận thức ăn từ phụ nữ đang cho con bú, không nhận thức ăn từ phụ nữ có chồng, không nhận thức ăn ở nơi có nhiều người tụ tập, không nhận thức ăn ở nơi có chó đứng, không nhận thức ăn ở nơi có ruồi bay thành đàn. Họ không ăn cá, không ăn thịt, không uống rượu, không uống rượu mạnh, không uống nước gạo. ",
  "mn36:5.6": "Họ chỉ ăn một nhà, một nắm; hoặc hai nhà, hai nắm… cho đến bảy nhà, bảy nắm. ",
  "mn36:5.7": "Họ sống nhờ một bữa ăn, hai bữa ăn… cho đến bảy bữa ăn. ",
  "mn36:5.8": "Họ ăn một ngày một bữa, hai ngày một bữa… cho đến bảy ngày một bữa. Cứ như vậy, họ sống chuyên cần tu tập ăn uống theo chu kỳ nửa tháng một lần.” ",
  "mn36:6.1": "“Này Aggivessana, vậy họ chỉ sống nhờ chừng đó thôi sao?” ",
  "mn36:6.2": "“Không phải vậy, thưa Tôn giả Gotama. ",
  "mn36:6.3": "Thưa Tôn giả Gotama, đôi khi họ ăn những món ăn ngon, ăn những món ăn thượng hạng, nếm những món ăn ngon, uống những thức uống ngon. ",
  "mn36:6.4": "Họ làm cho thân này có sức mạnh, làm cho thân này tăng trưởng, làm cho thân này mập mạp.” ",
  "mn36:6.5": "“Này Aggivessana, cái mà họ bỏ đi trước rồi sau đó lại tích lũy, đó là sự tăng trưởng và suy giảm của thân này. ",
  "mn36:6.6": "Này Aggivessana, vậy ông đã nghe về sự tu tập tâm như thế nào?” ",
  "mn36:6.7": "Khi được Thế Tôn hỏi về sự tu tập tâm, Saccaka, con của Nigaṇṭha, không thể trả lời. ",
  "mn36:7.1": "Rồi Thế Tôn nói với Saccaka, con của Nigaṇṭha: ",
  "mn36:7.2": "“Này Aggivessana, ngay cả sự tu tập thân mà ông đã nói trước đây, đó cũng không phải là sự tu tập thân đúng pháp trong giới luật của bậc Thánh. ",
  "mn36:7.3": "Này Aggivessana, ông còn không biết sự tu tập thân, làm sao ông có thể biết sự tu tập tâm? ",
  "mn36:7.4": "Này Aggivessana, có người thân chưa được tu tập và tâm chưa được tu tập, có người thân đã được tu tập và tâm đã được tu tập. ",
  "mn36:7.5": "Hãy lắng nghe, hãy chú ý kỹ, Ta sẽ nói.” ",
  "mn36:7.6": "“Vâng, thưa Tôn giả,” Saccaka, con của Nigaṇṭha, vâng lời Thế Tôn. ",
  "mn36:7.7": "Thế Tôn nói: ",
  "mn36:8.1": "“Này Aggivessana, thế nào là thân chưa được tu tập và tâm chưa được tu tập? ",
  "mn36:8.2": "Này Aggivessana, ở đây, một phàm phu không được nghe giáo pháp, khởi lên lạc thọ. ",
  "mn36:8.3": "Khi bị lạc thọ chạm đến, người ấy tham đắm lạc thọ và trở nên tham đắm lạc thọ. ",
  "mn36:8.4": "Lạc thọ ấy của người ấy diệt đi. ",
  "mn36:8.5": "Khi lạc thọ diệt đi, khổ thọ khởi lên. ",
  "mn36:8.6": "Khi bị khổ thọ chạm đến, người ấy sầu não, than van, đấm ngực, khóc lóc, rơi vào mê loạn. ",
  "mn36:8.7": "Này Aggivessana, lạc thọ đã khởi lên ấy chi phối tâm người ấy vì thân chưa được tu tập; khổ thọ đã khởi lên ấy chi phối tâm người ấy vì tâm chưa được tu tập. ",
  "mn36:8.8": "Này Aggivessana, đối với bất cứ ai, lạc thọ đã khởi lên chi phối tâm vì thân chưa được tu tập, và khổ thọ đã khởi lên chi phối tâm vì tâm chưa được tu tập, như vậy, người ấy là thân chưa được tu tập và tâm chưa được tu tập. ",
  "mn36:9.1": "Này Aggivessana, thế nào là thân đã được tu tập và tâm đã được tu tập? ",
  "mn36:9.2": "Này Aggivessana, ở đây, một đệ tử Thánh đã được nghe giáo pháp, khởi lên lạc thọ. ",
  "mn36:9.3": "Khi bị lạc thọ chạm đến, người ấy không tham đắm lạc thọ và không trở nên tham đắm lạc thọ. ",
  "mn36:9.4": "Lạc thọ ấy của người ấy diệt đi. ",
  "mn36:9.5": "Khi lạc thọ diệt đi, khổ thọ khởi lên. ",
  "mn36:9.6": "Khi bị khổ thọ chạm đến, người ấy không sầu não, không than van, không đấm ngực, không khóc lóc, không rơi vào mê loạn. ",
  "mn36:9.7": "Này Aggivessana, lạc thọ đã khởi lên ấy không chi phối tâm người ấy vì thân đã được tu tập; khổ thọ đã khởi lên ấy không chi phối tâm người ấy vì tâm đã được tu tập. ",
  "mn36:9.8": "Này Aggivessana, đối với bất cứ ai, lạc thọ đã khởi lên không chi phối tâm vì thân đã được tu tập, và khổ thọ đã khởi lên không chi phối tâm vì tâm đã được tu tập, như vậy, người ấy là thân đã được tu tập và tâm đã được tu tập.” ",
  "mn36:10.1": "“Tôi tin tưởng Tôn giả Gotama như vậy. ",
  "mn36:10.2": "Vì Tôn giả Gotama là người thân đã được tu tập và tâm đã được tu tập.” ",
  "mn36:10.3": "“Này Aggivessana, chắc chắn lời nói này của ông là lời nói xúc phạm, lời nói vu khống, ",
  "mn36:10.4": "nhưng Ta sẽ giải thích cho ông. ",
  "mn36:10.5": "Này Aggivessana, từ khi Ta cạo bỏ râu tóc, đắp y cà sa, từ bỏ gia đình, sống không gia đình, thì không có trường hợp nào lạc thọ đã khởi lên có thể chi phối tâm Ta, hay khổ thọ đã khởi lên có thể chi phối tâm Ta.” ",
  "mn36:11.1": "“Chắc chắn Tôn giả Gotama không khởi lên những lạc thọ như vậy, mà những lạc thọ đã khởi lên có thể chi phối tâm; chắc chắn Tôn giả Gotama không khởi lên những khổ thọ như vậy, mà những khổ thọ đã khởi lên có thể chi phối tâm.” ",
  "mn36:12.1": "“Này Aggivessana, tại sao lại không có? ",
  "mn36:12.2": "Này Aggivessana, ở đây, trước khi giác ngộ, khi Ta còn là Bồ Tát chưa chứng ngộ, Ta đã nghĩ như vầy: ",
  "mn36:12.3": "‘Đời sống gia đình chật chội, con đường đầy bụi bặm; đời sống xuất gia là khoảng không rộng mở. ",
  "mn36:12.4": "Thật không dễ dàng cho người sống tại gia để sống một đời sống phạm hạnh hoàn toàn đầy đủ, hoàn toàn thanh tịnh, trắng trong như vỏ ốc. ",
  "mn36:12.5": "Vậy Ta hãy cạo bỏ râu tóc, đắp y cà sa, từ bỏ gia đình, sống không gia đình.’ ",
  "mn36:13.1": "Này Aggivessana, sau đó, khi Ta còn trẻ, tóc đen nhánh, đầy đủ tuổi thanh xuân, ở độ tuổi đầu tiên, Ta đã cạo bỏ râu tóc, đắp y cà sa, từ bỏ gia đình, sống không gia đình, mặc dù cha mẹ không muốn, nước mắt đầm đìa, khóc lóc. ",
  "mn36:13.2": "Sau khi xuất gia như vậy, Ta đi tìm kiếm điều thiện, tìm kiếm con đường an tịnh tối thượng, Ta đi đến chỗ Āḷāra Kālāma. Sau khi đến, Ta nói với Āḷāra Kālāma: ",
  "mn36:13.3": "‘Thưa Hiền giả Kālāma, tôi muốn sống phạm hạnh trong giáo pháp và giới luật này.’ ",
  "mn36:13.4": "Này Aggivessana, khi Ta nói vậy, Āḷāra Kālāma nói với Ta: ",
  "mn36:13.5": "‘Hiền giả hãy ở lại, ",
  "mn36:13.6": "giáo pháp này là như vậy, một người có trí tuệ không bao lâu sẽ tự mình chứng ngộ, thực chứng và an trú trong giáo pháp của thầy mình.’ ",
  "mn36:13.7": "Này Aggivessana, không bao lâu, Ta nhanh chóng học thuộc giáo pháp ấy. ",
  "mn36:13.8": "Này Aggivessana, chỉ với lời nói trên môi, với sự nói đi nói lại, Ta đã có thể nói về giáo lý trí tuệ và giáo lý của các bậc trưởng lão, và Ta tự nhận rằng ‘Ta biết, Ta thấy’, cả Ta và những người khác. ",
  "mn36:13.9": "Này Aggivessana, Ta đã nghĩ như vầy: ",
  "mn36:13.10": "‘Āḷāra Kālāma không phải chỉ vì niềm tin mà tuyên bố rằng ông ấy tự mình chứng ngộ, thực chứng và an trú trong giáo pháp này, ",
  "mn36:13.11": "chắc chắn Āḷāra Kālāma sống biết và thấy giáo pháp này.’ ",
  "mn36:13.12": "Rồi này Aggivessana, Ta đi đến chỗ Āḷāra Kālāma. Sau khi đến, Ta nói với Āḷāra Kālāma: ",
  "mn36:13.13": "‘Thưa Hiền giả Kālāma, ông tuyên bố rằng ông tự mình chứng ngộ, thực chứng và an trú trong giáo pháp này đến mức độ nào?’ ",
  "mn36:13.14": "Này Aggivessana, khi Ta nói vậy, Āḷāra Kālāma tuyên bố về Vô sở hữu xứ. ",
  "mn36:13.15": "Này Aggivessana, Ta đã nghĩ như vầy: ",
  "mn36:13.16": "‘Không phải chỉ Āḷāra Kālāma có niềm tin, Ta cũng có niềm tin; ",
  "mn36:13.17": "không phải chỉ Āḷāra Kālāma có tinh tấn, Ta cũng có tinh tấn; ",
  "mn36:13.18": "không phải chỉ Āḷāra Kālāma có niệm, Ta cũng có niệm; ",
  "mn36:13.19": "không phải chỉ Āḷāra Kālāma có định, Ta cũng có định; ",
  "mn36:13.20": "không phải chỉ Āḷāra Kālāma có trí tuệ, Ta cũng có trí tuệ; ",
  "mn36:13.21": "vậy Ta hãy tinh tấn để thực chứng giáo pháp mà Āḷāra Kālāma tuyên bố rằng ông ấy tự mình chứng ngộ, thực chứng và an trú.’ ",
  "mn36:13.22": "Này Aggivessana, không bao lâu, Ta nhanh chóng tự mình chứng ngộ, thực chứng và an trú trong giáo pháp ấy. ",
  "mn36:14.1": "Rồi này Aggivessana, Ta đi đến chỗ Āḷāra Kālāma. Sau khi đến, Ta nói với Āḷāra Kālāma: ",
  "mn36:14.2": "‘Thưa Hiền giả Kālāma, ông tuyên bố rằng ông tự mình chứng ngộ, thực chứng và an trú trong giáo pháp này đến mức độ nào?’ ",
  "mn36:14.3": "‘Thưa Hiền giả, tôi tuyên bố rằng tôi tự mình chứng ngộ, thực chứng và an trú trong giáo pháp này đến mức độ này.’ ",
  "mn36:14.4": "‘Thưa Hiền giả, tôi cũng tự mình chứng ngộ, thực chứng và an trú trong giáo pháp này đến mức độ này.’ ",
  "mn36:14.5": "‘Thưa Hiền giả, chúng ta thật có lợi, chúng ta thật may mắn, ",
  "mn36:14.6": "khi chúng ta thấy một vị đồng phạm hạnh như Hiền giả. ",
  "mn36:14.7": "Như vậy, giáo pháp mà tôi tự mình chứng ngộ, thực chứng và an trú, ông cũng tự mình chứng ngộ, thực chứng và an trú; ",
  "mn36:14.8": "giáo pháp mà ông tự mình chứng ngộ, thực chứng và an trú, tôi cũng tự mình chứng ngộ, thực chứng và an trú. ",
  "mn36:14.9": "Như vậy, giáo pháp mà tôi biết, ông cũng biết; giáo pháp mà ông biết, tôi cũng biết. ",
  "mn36:14.10": "Như vậy, tôi như thế nào, ông cũng như thế ấy; ông như thế nào, tôi cũng như thế ấy. ",
  "mn36:14.11": "Nào, Hiền giả, bây giờ chúng ta hãy cùng nhau quản lý hội chúng này.’ ",
  "mn36:14.12": "Này Aggivessana, như vậy, Āḷāra Kālāma, là thầy của Ta, đã đặt Ta, là đệ tử của ông ấy, ngang hàng với ông ấy, và đã cúng dường Ta với sự cúng dường cao quý. ",
  "mn36:14.13": "Này Aggivessana, Ta đã nghĩ như vầy: ",
  "mn36:14.14": "‘Giáo pháp này không đưa đến sự nhàm chán, không đưa đến sự ly tham, không đưa đến sự đoạn diệt, không đưa đến sự an tịnh, không đưa đến thắng trí, không đưa đến giác ngộ, không đưa đến Niết Bàn, mà chỉ đưa đến sự tái sinh vào Vô sở hữu xứ.’ ",
  "mn36:14.15": "Này Aggivessana, Ta không hài lòng với giáo pháp ấy, Ta chán ghét giáo pháp ấy và bỏ đi. ",
  "mn36:15.1": "Này Aggivessana, Ta đi tìm kiếm điều thiện, tìm kiếm con đường an tịnh tối thượng, Ta đi đến chỗ Udaka, con của Rāma. Sau khi đến, Ta nói với Udaka, con của Rāma: ",
  "mn36:15.2": "‘Thưa Hiền giả, tôi muốn sống phạm hạnh trong giáo pháp và giới luật này.’ ",
  "mn36:15.3": "Này Aggivessana, khi Ta nói vậy, Udaka, con của Rāma, nói với Ta: ",
  "mn36:15.4": "‘Hiền giả hãy ở lại, ",
  "mn36:15.5": "giáo pháp này là như vậy, một người có trí tuệ không bao lâu sẽ tự mình chứng ngộ, thực chứng và an trú trong giáo pháp của thầy mình.’ ",
  "mn36:15.6": "Này Aggivessana, không bao lâu, Ta nhanh chóng học thuộc giáo pháp ấy. ",
  "mn36:15.7": "Này Aggivessana, chỉ với lời nói trên môi, với sự nói đi nói lại, Ta đã có thể nói về giáo lý trí tuệ và giáo lý của các bậc trưởng lão, và Ta tự nhận rằng ‘Ta biết, Ta thấy’, cả Ta và những người khác. ",
  "mn36:15.8": "Này Aggivessana, tôi đã nghĩ thế này: ",
  "mn36:15.9": "‘Không phải chỉ bằng niềm tin mà Ramana đã tuyên bố rằng ông ấy tự mình chứng ngộ, đạt được và an trú trong giáo pháp này. ",
  "mn36:15.10": "Chắc chắn Ramana đã sống với giáo pháp này bằng sự hiểu biết và thấy rõ.’",
  "mn36:15.11": "Rồi này Aggivessana, tôi đi đến chỗ Udaka, con trai của Ramana; sau khi đến, tôi nói với Udaka, con trai của Ramana, rằng: ",
  "mn36:15.12": "‘Này hiền giả, Ramana đã tuyên bố rằng ông ấy tự mình chứng ngộ, đạt được và an trú trong giáo pháp này đến mức độ nào?’",
  "mn36:15.13": "Khi được hỏi như vậy, này Aggivessana, Udaka, con trai của Ramana, đã tuyên bố về cõi phi tưởng phi phi tưởng. ",
  "mn36:15.14": "Này Aggivessana, tôi đã nghĩ thế này: ",
  "mn36:15.15": "‘Không phải chỉ Ramana có niềm tin, tôi cũng có niềm tin; ",
  "mn36:15.16": "không phải chỉ Ramana có tinh tấn, tôi cũng có tinh tấn; ",
  "mn36:15.17": "không phải chỉ Ramana có chánh niệm, tôi cũng có chánh niệm; ",
  "mn36:15.18": "không phải chỉ Ramana có định, tôi cũng có định; ",
  "mn36:15.19": "không phải chỉ Ramana có trí tuệ, tôi cũng có trí tuệ; ",
  "mn36:15.20": "vậy thì sao tôi không cố gắng để chứng ngộ giáo pháp mà Ramana đã tuyên bố rằng ông ấy tự mình chứng ngộ, đạt được và an trú trong đó?’",
  "mn36:15.21": "Rồi này Aggivessana, không lâu sau đó, tôi đã nhanh chóng tự mình chứng ngộ, đạt được và an trú trong giáo pháp ấy. ",
  "mn36:15.22": "Rồi này Aggivessana, tôi đi đến chỗ Udaka, con trai của Ramana; sau khi đến, tôi nói với Udaka, con trai của Ramana, rằng: ",
  "mn36:15.23": "‘Này hiền giả, Ramana đã tuyên bố rằng ông ấy tự mình chứng ngộ, đạt được và an trú trong giáo pháp này đến mức độ nào?’",
  "mn36:15.24": "‘Này hiền giả, Ramana đã tuyên bố rằng ông ấy tự mình chứng ngộ, đạt được và an trú trong giáo pháp này đến mức độ ấy.’",
  "mn36:15.25": "‘Này hiền giả, tôi cũng tự mình chứng ngộ, đạt được và an trú trong giáo pháp này đến mức độ ấy.’",
  "mn36:15.26": "‘Này hiền giả, chúng ta thật có lợi, chúng ta thật may mắn, ",
  "mn36:15.27": "khi chúng ta thấy một vị đồng phạm hạnh như Tôn giả. ",
  "mn36:15.28": "Như vậy, giáo pháp mà Ramana đã tự mình chứng ngộ, đạt được và an trú, thì Tôn giả cũng tự mình chứng ngộ, đạt được và an trú; giáo pháp mà Tôn giả tự mình chứng ngộ, đạt được và an trú, thì Ramana cũng tự mình chứng ngộ, đạt được và an trú. ",
  "mn36:15.29": "Như vậy, giáo pháp mà Ramana đã chứng ngộ thì Tôn giả cũng biết; giáo pháp mà Tôn giả biết thì Ramana cũng chứng ngộ. ",
  "mn36:15.30": "Như vậy, Ramana như thế nào thì Tôn giả cũng như thế ấy; Tôn giả như thế nào thì Ramana cũng như thế ấy. ",
  "mn36:15.31": "Này hiền giả, bây giờ Tôn giả hãy đến và chăm sóc nhóm này.’",
  "mn36:15.32": "Như vậy, này Aggivessana, Udaka, con trai của Ramana, tuy là đồng phạm hạnh với tôi, nhưng đã đặt tôi vào vị trí của một vị thầy và đã tôn kính tôi bằng sự tôn kính cao quý. ",
  "mn36:15.33": "Này Aggivessana, tôi đã nghĩ thế này: ",
  "mn36:15.34": "‘Giáo pháp này không đưa đến sự nhàm chán, không đưa đến sự ly tham, không đưa đến sự chấm dứt, không đưa đến sự an tịnh, không đưa đến sự chứng ngộ, không đưa đến sự giác ngộ hoàn toàn, không đưa đến Niết Bàn, mà chỉ đưa đến sự tái sinh vào cõi phi tưởng phi phi tưởng.’",
  "mn36:15.35": "Rồi này Aggivessana, tôi không hài lòng với giáo pháp ấy, tôi đã nhàm chán và rời bỏ giáo pháp ấy. ",
  "mn36:16.1": "Rồi này Aggivessana, tôi đi tìm kiếm điều thiện lành, đi tìm kiếm con đường an tịnh tối thượng, tuần tự du hành qua xứ Magadha, và đến làng quân sự Uruvelā. ",
  "mn36:16.2": "Ở đó, tôi thấy một vùng đất đẹp, một khu rừng dễ chịu, một dòng sông chảy xiết với bến nước trong xanh, dễ chịu, và xung quanh là làng mạc để khất thực. ",
  "mn36:16.3": "Này Aggivessana, tôi đã nghĩ thế này: ",
  "mn36:16.4": "‘Ôi, thật là một vùng đất đẹp, một khu rừng dễ chịu, một dòng sông chảy xiết với bến nước trong xanh, dễ chịu, và xung quanh là làng mạc để khất thực. ",
  "mn36:16.5": "Thật là thích hợp cho một thiện nam tử muốn tinh tấn để thực hành tinh tấn.’",
  "mn36:16.6": "Rồi này Aggivessana, tôi ngồi xuống ở đó, ",
  "mn36:16.7": "‘đây là nơi thích hợp để tinh tấn.’",
  "mn36:17.1": "Này Aggivessana, ba ví dụ chưa từng nghe trước đây, chưa từng có, đã hiện ra trong tôi. ",
  "mn36:17.2": "Ví như, này Aggivessana, một khúc gỗ tươi, còn nhựa, được đặt trong nước. ",
  "mn36:17.3": "Rồi một người đàn ông đến, cầm lấy cây cọ xát trên: ",
  "mn36:17.4": "‘Tôi sẽ tạo ra lửa, tôi sẽ làm cho nhiệt hiện ra.’",
  "mn36:17.5": "Này Aggivessana, ông nghĩ sao, ",
  "mn36:17.6": "người đàn ông ấy, cầm lấy cây cọ xát trên, cọ xát khúc gỗ tươi, còn nhựa, được đặt trong nước, liệu có thể tạo ra lửa, làm cho nhiệt hiện ra không?",
  "mn36:17.7": "“Không thể được, này Tôn giả Gotama.”",
  "mn36:17.8": "“Vì sao vậy?”",
  "mn36:17.9": "“Vì, này Tôn giả Gotama, khúc gỗ ấy tươi, còn nhựa, và lại được đặt trong nước. ",
  "mn36:17.10": "Người đàn ông ấy chỉ chuốc lấy sự mệt mỏi và thất vọng mà thôi.”",
  "mn36:17.11": "“Cũng vậy, này Aggivessana, bất cứ vị Sa-môn hay Bà-la-môn nào sống không tách rời khỏi dục lạc bằng thân và tâm, và dục vọng, sự dính mắc, sự mê đắm, sự khát khao, sự nóng bức đối với dục lạc vẫn chưa được đoạn trừ hoàn toàn, chưa được làm lắng dịu hoàn toàn trong nội tâm, thì dù các vị Sa-môn, Bà-la-môn ấy có cảm nhận những cảm thọ đau đớn, mãnh liệt, gay gắt, khó chịu do sự cố gắng, họ cũng không thể đạt được tri kiến, thấy rõ, giác ngộ tối thượng. ",
  "mn36:17.12": "Dù các vị Sa-môn, Bà-la-môn ấy không cảm nhận những cảm thọ đau đớn, mãnh liệt, gay gắt, khó chịu do sự cố gắng, họ cũng không thể đạt được tri kiến, thấy rõ, giác ngộ tối thượng. ",
  "mn36:17.13": "Này Aggivessana, đây là ví dụ thứ nhất chưa từng nghe trước đây, chưa từng có, đã hiện ra trong tôi. ",
  "mn36:18.1": "Này Aggivessana, một ví dụ thứ hai chưa từng nghe trước đây, chưa từng có, cũng đã hiện ra trong tôi. ",
  "mn36:18.2": "Ví như, này Aggivessana, một khúc gỗ tươi, còn nhựa, được đặt trên đất khô, cách xa nước. ",
  "mn36:18.3": "Rồi một người đàn ông đến, cầm lấy cây cọ xát trên: ",
  "mn36:18.4": "‘Tôi sẽ tạo ra lửa, tôi sẽ làm cho nhiệt hiện ra.’",
  "mn36:18.5": "Này Aggivessana, ông nghĩ sao, ",
  "mn36:18.6": "người đàn ông ấy, cầm lấy cây cọ xát trên, cọ xát khúc gỗ tươi, còn nhựa, được đặt trên đất khô, cách xa nước, liệu có thể tạo ra lửa, làm cho nhiệt hiện ra không?",
  "mn36:18.7": "“Không thể được, này Tôn giả Gotama.”",
  "mn36:18.8": "“Vì sao vậy?”",
  "mn36:18.9": "“Vì, này Tôn giả Gotama, khúc gỗ ấy tươi, còn nhựa, mặc dù được đặt trên đất khô, cách xa nước. ",
  "mn36:18.10": "Người đàn ông ấy chỉ chuốc lấy sự mệt mỏi và thất vọng mà thôi.”",
  "mn36:18.11": "“Cũng vậy, này Aggivessana, bất cứ vị Sa-môn hay Bà-la-môn nào sống tách rời khỏi dục lạc bằng thân và tâm, nhưng dục vọng, sự dính mắc, sự mê đắm, sự khát khao, sự nóng bức đối với dục lạc vẫn chưa được đoạn trừ hoàn toàn, chưa được làm lắng dịu hoàn toàn trong nội tâm, thì dù các vị Sa-môn, Bà-la-môn ấy có cảm nhận những cảm thọ đau đớn, mãnh liệt, gay gắt, khó chịu do sự cố gắng, họ cũng không thể đạt được tri kiến, thấy rõ, giác ngộ tối thượng. Dù các vị Sa-môn, Bà-la-môn ấy không cảm nhận những cảm thọ đau đớn, mãnh liệt, gay gắt, khó chịu do sự cố gắng, họ cũng không thể đạt được tri kiến, thấy rõ, giác ngộ tối thượng. ",
  "mn36:18.12": "Này Aggivessana, đây là ví dụ thứ hai chưa từng nghe trước đây, chưa từng có, đã hiện ra trong tôi. ",
  "mn36:19.1": "Này Aggivessana, một ví dụ thứ ba chưa từng nghe trước đây, chưa từng có, cũng đã hiện ra trong tôi. ",
  "mn36:19.2": "Ví như, này Aggivessana, một khúc gỗ khô, không nhựa, được đặt trên đất khô, cách xa nước. ",
  "mn36:19.3": "Rồi một người đàn ông đến, cầm lấy cây cọ xát trên: ",
  "mn36:19.4": "‘Tôi sẽ tạo ra lửa, tôi sẽ làm cho nhiệt hiện ra.’",
  "mn36:19.5": "Này Aggivessana, ông nghĩ sao, ",
  "mn36:19.6": "người đàn ông ấy, cầm lấy cây cọ xát trên, cọ xát khúc gỗ khô, không nhựa, được đặt trên đất khô, cách xa nước, liệu có thể tạo ra lửa, làm cho nhiệt hiện ra không?",
  "mn36:19.7": "“Có thể được, này Tôn giả Gotama.”",
  "mn36:19.8": "“Vì sao vậy?”",
  "mn36:19.9": "“Vì, này Tôn giả Gotama, khúc gỗ ấy khô, không nhựa, và lại được đặt trên đất khô, cách xa nước.”",
  "mn36:19.10": "“Cũng vậy, này Aggivessana, bất cứ vị Sa-môn hay Bà-la-môn nào sống tách rời khỏi dục lạc bằng thân và tâm, và dục vọng, sự dính mắc, sự mê đắm, sự khát khao, sự nóng bức đối với dục lạc đã được đoạn trừ hoàn toàn, đã được làm lắng dịu hoàn toàn trong nội tâm, thì dù các vị Sa-môn, Bà-la-môn ấy có cảm nhận những cảm thọ đau đớn, mãnh liệt, gay gắt, khó chịu do sự cố gắng, họ cũng có thể đạt được tri kiến, thấy rõ, giác ngộ tối thượng. Dù các vị Sa-môn, Bà-la-môn ấy không cảm nhận những cảm thọ đau đớn, mãnh liệt, gay gắt, khó chịu do sự cố gắng, họ cũng có thể đạt được tri kiến, thấy rõ, giác ngộ tối thượng. ",
  "mn36:19.11": "Này Aggivessana, đây là ví dụ thứ ba chưa từng nghe trước đây, chưa từng có, đã hiện ra trong tôi. ",
  "mn36:19.12": "Này Aggivessana, ba ví dụ chưa từng nghe trước đây, chưa từng có, đã hiện ra trong tôi. ",
  "mn36:20.1": "Này Aggivessana, tôi đã nghĩ thế này: ",
  "mn36:20.2": "‘Vậy thì sao tôi không nghiến răng vào răng, ép lưỡi vào vòm miệng, và dùng tâm để chế ngự, đè nén, thiêu đốt tâm?’",
  "mn36:20.3": "Rồi này Aggivessana, tôi nghiến răng vào răng, ép lưỡi vào vòm miệng, và dùng tâm để chế ngự, đè nén, thiêu đốt tâm. ",
  "mn36:20.4": "Này Aggivessana, khi tôi nghiến răng vào răng, ép lưỡi vào vòm miệng, dùng tâm để chế ngự, đè nén, thiêu đốt tâm, mồ hôi chảy ra từ nách tôi. ",
  "mn36:20.5": "Ví như, này Aggivessana, một người đàn ông mạnh mẽ nắm đầu hoặc nắm vai một người đàn ông yếu hơn, rồi chế ngự, đè nén, thiêu đốt anh ta; ",
  "mn36:20.6": "cũng vậy, này Aggivessana, khi tôi nghiến răng vào răng, ép lưỡi vào vòm miệng, dùng tâm để chế ngự, đè nén, thiêu đốt tâm, mồ hôi chảy ra từ nách tôi. ",
  "mn36:20.7": "Này Aggivessana, tinh tấn của tôi được khởi lên không chùn bước, chánh niệm được thiết lập không lãng quên, và thân tôi trở nên căng thẳng, không được an tịnh, vì sự tinh tấn khổ hạnh ấy đã đè nặng lên tôi. ",
  "mn36:20.8": "Này Aggivessana, dù những cảm thọ đau đớn như vậy khởi lên, tâm tôi vẫn không bị chúng chi phối. ",
  "mn36:21.1": "Này Aggivessana, tôi đã nghĩ thế này: ",
  "mn36:21.2": "‘Vậy thì sao tôi không thiền định mà không thở?’",
  "mn36:21.3": "Rồi này Aggivessana, tôi ngừng hơi thở ra và hơi thở vào qua miệng và mũi. ",
  "mn36:21.4": "Này Aggivessana, khi hơi thở ra và hơi thở vào qua miệng và mũi bị ngừng lại, một tiếng ồn lớn phát ra từ lỗ tai do gió thoát ra. ",
  "mn36:21.5": "Ví như, khi ống thổi của thợ rèn được thổi, một tiếng ồn lớn phát ra; ",
  "mn36:21.6": "cũng vậy, này Aggivessana, khi hơi thở ra và hơi thở vào qua miệng và mũi bị ngừng lại, một tiếng ồn lớn phát ra từ lỗ tai do gió thoát ra. ",
  "mn36:21.7": "Này Aggivessana, tinh tấn của tôi được khởi lên không chùn bước, chánh niệm được thiết lập không lãng quên. Thân tôi trở nên căng thẳng, không được an tịnh, vì sự tinh tấn khổ hạnh ấy đã đè nặng lên tôi. ",
  "mn36:21.8": "Này Aggivessana, dù những cảm thọ đau đớn như vậy khởi lên, tâm tôi vẫn không bị chúng chi phối. ",
  "mn36:22.1": "Này Aggivessana, tôi đã nghĩ thế này: ",
  "mn36:22.2": "‘Vậy thì sao tôi không thiền định mà không thở?’",
  "mn36:22.3": "Rồi này Aggivessana, tôi ngừng hơi thở ra và hơi thở vào qua miệng, mũi và tai. ",
  "mn36:22.4": "Này Aggivessana, khi hơi thở ra và hơi thở vào qua miệng, mũi và tai bị ngừng lại, những luồng gió mạnh mẽ dồn lên đỉnh đầu tôi. ",
  "mn36:22.5": "Ví như, này Aggivessana, một người đàn ông mạnh mẽ dùng một mũi nhọn sắc bén đâm vào đỉnh đầu; ",
  "mn36:22.6": "cũng vậy, này Aggivessana, khi hơi thở ra và hơi thở vào qua miệng, mũi và tai bị ngừng lại, những luồng gió mạnh mẽ dồn lên đỉnh đầu tôi. ",
  "mn36:22.7": "Này Aggivessana, tinh tấn của tôi được khởi lên không chùn bước, chánh niệm được thiết lập không lãng quên. Thân tôi trở nên căng thẳng, không được an tịnh, vì sự tinh tấn khổ hạnh ấy đã đè nặng lên tôi. ",
  "mn36:22.8": "Này Aggivessana, dù những cảm thọ đau đớn như vậy khởi lên, tâm tôi vẫn không bị chúng chi phối. ",
  "mn36:23.1": "Này Aggivessana, tôi đã nghĩ thế này: ",
  "mn36:23.2": "‘Vậy thì sao tôi không thiền định mà không thở?’",
  "mn36:23.3": "Rồi này Aggivessana, tôi ngừng hơi thở ra và hơi thở vào qua miệng, mũi và tai. ",
  "mn36:23.4": "Này Aggivessana, khi hơi thở ra và hơi thở vào qua miệng, mũi và tai bị ngừng lại, những cơn đau đầu dữ dội khởi lên trên đầu tôi. ",
  "mn36:23.5": "Ví như, này Aggivessana, một người đàn ông mạnh mẽ dùng một sợi dây da chắc chắn quấn chặt quanh đầu; ",
  "mn36:23.6": "cũng vậy, này Aggivessana, khi hơi thở ra và hơi thở vào qua miệng, mũi và tai bị ngừng lại, những cơn đau đầu dữ dội khởi lên trên đầu tôi. ",
  "mn36:23.7": "Này Aggivessana, tinh tấn của tôi được khởi lên không chùn bước, chánh niệm được thiết lập không lãng quên. Thân tôi trở nên căng thẳng, không được an tịnh, vì sự tinh tấn khổ hạnh ấy đã đè nặng lên tôi. ",
  "mn36:23.8": "Này Aggivessana, dù những cảm thọ đau đớn như vậy khởi lên, tâm tôi vẫn không bị chúng chi phối. ",
  "mn36:24.1": "Này Aggivessana, tôi đã nghĩ thế này: ",
  "mn36:24.2": "‘Vậy thì sao tôi không thiền định mà không thở?’",
  "mn36:24.3": "Rồi này Aggivessana, tôi ngừng hơi thở ra và hơi thở vào qua miệng, mũi và tai. ",
  "mn36:24.4": "Này Aggivessana, khi hơi thở ra và hơi thở vào qua miệng, mũi và tai bị ngừng lại, những luồng gió mạnh mẽ cắt xé bụng tôi. ",
  "mn36:24.5": "Ví như, này Aggivessana, một người đồ tể bò khéo léo hoặc một người học việc của đồ tể bò dùng một con dao mổ bò sắc bén cắt xé bụng; ",
  "mn36:24.6": "cũng vậy, này Aggivessana, khi hơi thở ra và hơi thở vào qua miệng, mũi và tai bị ngừng lại, những luồng gió mạnh mẽ cắt xé bụng tôi. ",
  "mn36:24.7": "Này Aggivessana, tinh tấn của tôi được khởi lên không chùn bước, chánh niệm được thiết lập không lãng quên. Thân tôi trở nên căng thẳng, không được an tịnh, vì sự tinh tấn khổ hạnh ấy đã đè nặng lên tôi. ",
  "mn36:24.8": "Này Aggivessana, dù những cảm thọ đau đớn như vậy khởi lên, tâm tôi vẫn không bị chúng chi phối. ",
  "mn36:25.1": "Này Aggivessana, tôi đã nghĩ thế này: ",
  "mn36:25.2": "‘Vậy thì sao tôi không thiền định mà không thở?’",
  "mn36:25.3": "Rồi này Aggivessana, tôi ngừng hơi thở ra và hơi thở vào qua miệng, mũi và tai. ",
  "mn36:25.4": "Này Aggivessana, khi hơi thở ra và hơi thở vào qua miệng, mũi và tai bị ngừng lại, một sự nóng rát dữ dội khởi lên trong thân tôi. ",
  "mn36:25.5": "Ví như, này Aggivessana, hai người đàn ông mạnh mẽ nắm hai cánh tay của một người đàn ông yếu hơn, rồi nung nóng, thiêu đốt anh ta trên một hố than hồng; ",
  "mn36:25.6": "cũng vậy, này Aggivessana, khi hơi thở ra và hơi thở vào qua miệng, mũi và tai bị ngừng lại, một sự nóng rát dữ dội khởi lên trong thân tôi. ",
  "mn36:25.7": "Này Aggivessana, tinh tấn của tôi được khởi lên không chùn bước, chánh niệm được thiết lập không lãng quên. Thân tôi trở nên căng thẳng, không được an tịnh, vì sự tinh tấn khổ hạnh ấy đã đè nặng lên tôi. ",
  "mn36:25.8": "Này Aggivessana, dù những cảm thọ đau đớn như vậy khởi lên, tâm tôi vẫn không bị chúng chi phối. ",
  "mn36:26.1": "Này Aggivessana, có những vị trời thấy ta và nói như sau: ",
  "mn36:26.2": "‘Sa-môn Gotama đã chết rồi’.",
  "mn36:26.3": "Một số vị trời khác lại nói: ",
  "mn36:26.4": "‘Sa-môn Gotama chưa chết, nhưng đang hấp hối’.",
  "mn36:26.5": "Một số vị trời khác lại nói: ",
  "mn36:26.6": "‘Sa-môn Gotama chưa chết, cũng không hấp hối, Sa-môn Gotama là bậc A-la-hán, và đây là cách bậc A-la-hán sống’.",
  "mn36:27.1": "Này Aggivessana, khi ấy ta nghĩ: ",
  "mn36:27.2": "‘Hay là ta hoàn toàn đoạn tuyệt với thức ăn’.",
  "mn36:27.3": "Này Aggivessana, khi ấy các vị trời đến gần ta và nói: ",
  "mn36:27.4": "‘Này hiền giả, xin đừng hoàn toàn đoạn tuyệt với thức ăn. ",
  "mn36:27.5": "Nếu hiền giả hoàn toàn đoạn tuyệt với thức ăn, chúng tôi sẽ đưa chất bổ thần thánh vào lỗ chân lông của hiền giả, và hiền giả sẽ sống nhờ chất bổ đó’.",
  "mn36:27.6": "Này Aggivessana, khi ấy ta nghĩ: ",
  "mn36:27.7": "‘Nếu ta tuyên bố hoàn toàn không ăn gì, mà các vị trời này lại đưa chất bổ thần thánh vào lỗ chân lông của ta, và ta sống nhờ chất bổ đó, thì điều đó sẽ là dối trá’.",
  "mn36:27.8": "Này Aggivessana, thế là ta từ chối các vị trời đó, ta nói: ‘Thôi đủ rồi’.",
  "mn36:28.1": "Này Aggivessana, khi ấy ta nghĩ: ",
  "mn36:28.2": "‘Hay là ta ăn từng chút một, từng nắm một, hoặc nước đậu xanh, hoặc nước đậu ván, hoặc nước đậu đen, hoặc nước đậu lăng’.",
  "mn36:28.3": "Này Aggivessana, thế là ta ăn từng chút một, từng nắm một, hoặc nước đậu xanh, hoặc nước đậu ván, hoặc nước đậu đen, hoặc nước đậu lăng.",
  "mn36:28.4": "Này Aggivessana, khi ta ăn từng chút một, từng nắm một, hoặc nước đậu xanh, hoặc nước đậu ván, hoặc nước đậu đen, hoặc nước đậu lăng, thân thể ta trở nên cực kỳ gầy yếu.",
  "mn36:28.5": "Ví như các đốt cây sậy hoặc đốt cây tre; cũng vậy, các chi và bộ phận của ta trở nên như thế vì quá ít thức ăn.",
  "mn36:28.6": "Ví như dấu chân lạc đà; cũng vậy, mông của ta trở nên như thế vì quá ít thức ăn.",
  "mn36:28.7": "Ví như một chuỗi hạt; cũng vậy, xương sống của ta lồi lõm vì quá ít thức ăn.",
  "mn36:28.8": "Ví như các kèo của một ngôi nhà cũ kỹ bị sụp đổ; cũng vậy, các xương sườn của ta bị sụp đổ vì quá ít thức ăn.",
  "mn36:28.9": "Ví như các ngôi sao dưới nước trong một cái giếng sâu trông có vẻ chìm sâu và lặn xuống; cũng vậy, các con ngươi của ta trong hốc mắt trông có vẻ chìm sâu và lặn xuống vì quá ít thức ăn.",
  "mn36:28.10": "Ví như một quả bầu đắng chưa chín bị cắt ra, bị gió và nắng làm cho khô héo và nhăn nheo; cũng vậy, da đầu của ta bị khô héo và nhăn nheo vì quá ít thức ăn.",
  "mn36:28.11": "Này Aggivessana, khi ta muốn sờ da bụng, ta lại nắm lấy xương sống; khi ta muốn sờ xương sống, ta lại nắm lấy da bụng, đến nỗi, này Aggivessana, da bụng của ta dính chặt vào xương sống vì quá ít thức ăn.",
  "mn36:28.12": "Này Aggivessana, khi ta muốn đi đại tiện hoặc tiểu tiện, ta lại ngã sấp xuống ngay tại chỗ vì quá ít thức ăn.",
  "mn36:28.13": "Này Aggivessana, khi ta xoa bóp các chi bằng tay để làm dịu thân thể này. Này Aggivessana, khi ta xoa bóp các chi bằng tay, những sợi lông có gốc rễ thối rữa rụng ra khỏi thân thể vì quá ít thức ăn.",
  "mn36:29.1": "Này Aggivessana, có những người thấy ta và nói: ‘Sa-môn Gotama đen’.",
  "mn36:29.2": "Một số người khác lại nói: ‘Sa-môn Gotama không đen, Sa-môn Gotama xanh xao’.",
  "mn36:29.3": "Một số người khác lại nói: ‘Sa-môn Gotama không đen, cũng không xanh xao, Sa-môn Gotama có da màu vàng sẫm’.",
  "mn36:29.4": "Này Aggivessana, đến nỗi màu da trong sáng, thanh khiết của ta bị hư hoại vì quá ít thức ăn.",
  "mn36:30.1": "Này Aggivessana, khi ấy ta nghĩ: ",
  "mn36:30.2": "‘Bất cứ Sa-môn hay Bà-la-môn nào trong quá khứ đã trải qua những cảm thọ đau đớn, dữ dội, khắc nghiệt, cay đắng do nỗ lực, thì đó là mức tối đa, không hơn nữa. ",
  "mn36:30.3": "Bất cứ Sa-môn hay Bà-la-môn nào trong tương lai sẽ trải qua những cảm thọ đau đớn, dữ dội, khắc nghiệt, cay đắng do nỗ lực, thì đó là mức tối đa, không hơn nữa. ",
  "mn36:30.4": "Bất cứ Sa-môn hay Bà-la-môn nào hiện tại đang trải qua những cảm thọ đau đớn, dữ dội, khắc nghiệt, cay đắng do nỗ lực, thì đó là mức tối đa, không hơn nữa. ",
  "mn36:30.5": "Nhưng ta không đạt được bất kỳ sự đặc biệt nào về tri kiến siêu nhân, xứng đáng với bậc Thánh, bằng sự khổ hạnh khắc nghiệt này. ",
  "mn36:30.6": "Có lẽ nào có con đường khác để giác ngộ chăng?’",
  "mn36:31.1": "Này Aggivessana, khi ấy ta nghĩ: ",
  "mn36:31.2": "‘Ta nhớ lại khi cha ta, vua Sát-đế-lợi, đang làm việc, ta ngồi dưới bóng cây jambu mát mẻ, hoàn toàn tách biệt khỏi dục vọng, tách biệt khỏi các pháp bất thiện, nhập và an trú Sơ thiền, một trạng thái có tầm, có tứ, có hỷ và lạc do ly dục sinh. ",
  "mn36:31.3": "Có lẽ nào đây là con đường để giác ngộ chăng?’",
  "mn36:31.4": "Này Aggivessana, khi ấy ý thức của ta theo dõi ký ức và nghĩ: ",
  "mn36:31.5": "‘Đây chính là con đường để giác ngộ’.",
  "mn36:32.1": "Này Aggivessana, khi ấy ta nghĩ: ",
  "mn36:32.2": "‘Tại sao ta lại sợ cái lạc đó, cái lạc không liên quan đến dục vọng, không liên quan đến các pháp bất thiện?’",
  "mn36:32.3": "Này Aggivessana, khi ấy ta nghĩ: ",
  "mn36:32.4": "‘Ta không sợ cái lạc đó, cái lạc không liên quan đến dục vọng, không liên quan đến các pháp bất thiện’.",
  "mn36:33.1": "Này Aggivessana, khi ấy ta nghĩ: ",
  "mn36:33.2": "‘Thật không dễ dàng để đạt được cái lạc đó với thân thể đã trở nên cực kỳ gầy yếu như thế này, hay là ta nên ăn thức ăn thô, cơm và cháo đặc’.",
  "mn36:33.3": "Này Aggivessana, thế là ta ăn thức ăn thô, cơm và cháo đặc.",
  "mn36:33.4": "Này Aggivessana, vào thời điểm đó, có năm vị Tỳ-kheo đang hầu hạ ta: ",
  "mn36:33.5": "‘Bất cứ pháp nào Sa-môn Gotama đạt được, Ngài sẽ nói cho chúng ta biết’.",
  "mn36:33.6": "Này Aggivessana, khi ta ăn thức ăn thô, cơm và cháo đặc, thì năm vị Tỳ-kheo đó chán nản bỏ đi: ",
  "mn36:33.7": "‘Sa-môn Gotama đã trở nên phóng túng, đã từ bỏ sự tinh tấn, đã quay lại với sự phóng túng’.",
  "mn36:34.1": "Này Aggivessana, thế là ta ăn thức ăn thô, lấy lại sức lực, hoàn toàn tách biệt khỏi dục vọng, tách biệt khỏi các pháp bất thiện, nhập và an trú Sơ thiền, một trạng thái có tầm, có tứ, có hỷ và lạc do ly dục sinh.",
  "mn36:34.2": "Này Aggivessana, ngay cả những cảm thọ lạc như vậy cũng không chiếm đoạt tâm ta.",
  "mn36:35-37.1": "Với sự lắng dịu của tầm và tứ, ta nhập và an trú Nhị thiền, một trạng thái nội tâm thanh tịnh, nhất tâm, không tầm, không tứ, có hỷ và lạc do định sinh.",
  "mn36:35-37.2": "Này Aggivessana, ngay cả những cảm thọ lạc như vậy cũng không chiếm đoạt tâm ta.",
  "mn36:35-37.3": "Với sự ly hỷ, ta an trú xả, chánh niệm và tỉnh giác. Ta cảm nhận lạc bằng thân, điều mà các bậc Thánh gọi là: ‘người an trú xả, chánh niệm, sống an lạc’ – ta nhập và an trú Tam thiền.",
  "mn36:35-37.4": "Này Aggivessana, ngay cả những cảm thọ lạc như vậy cũng không chiếm đoạt tâm ta.",
  "mn36:35-37.5": "Với sự đoạn trừ lạc và đoạn trừ khổ, và sự chấm dứt trước đó của hỷ và ưu, ta nhập và an trú Tứ thiền, một trạng thái không khổ không lạc, với sự thanh tịnh của xả và niệm.",
  "mn36:35-37.6": "Này Aggivessana, ngay cả những cảm thọ lạc như vậy cũng không chiếm đoạt tâm ta.",
  "mn36:38.1": "Với tâm định tĩnh như vậy, thanh tịnh, trong sáng, không cấu uế, không phiền não, mềm mại, dễ uốn nắn, vững chắc, bất động, ta hướng tâm đến tuệ nhớ các đời sống trước.",
  "mn36:38.2": "Ta nhớ lại nhiều đời sống trước, đó là—một đời…v.v… như vậy, ta nhớ lại nhiều đời sống trước với đầy đủ chi tiết và đặc điểm.",
  "mn36:39.1": "Này Aggivessana, đây là minh thứ nhất ta đạt được trong canh đầu của đêm; ",
  "mn36:39.2": "vô minh bị diệt trừ, minh đã sinh; bóng tối bị diệt trừ, ánh sáng đã sinh; như vậy đối với người sống không phóng dật, nhiệt tâm, tinh cần.",
  "mn36:39.3": "Này Aggivessana, ngay cả những cảm thọ lạc như vậy cũng không chiếm đoạt tâm ta.",
  "mn36:40.1": "Với tâm định tĩnh như vậy, thanh tịnh, trong sáng, không cấu uế, không phiền não, mềm mại, dễ uốn nắn, vững chắc, bất động, ta hướng tâm đến tuệ về sự sinh và diệt của chúng sinh.",
  "mn36:40.2": "Với thiên nhãn thanh tịnh, vượt xa mắt người, ta thấy chúng sinh chết và sinh, thấp kém và cao sang, đẹp đẽ và xấu xí, may mắn và bất hạnh, ta biết rõ chúng sinh tùy theo nghiệp của họ…v.v… ",
  "mn36:41.1": "Này Aggivessana, đây là minh thứ hai ta đạt được trong canh giữa của đêm; ",
  "mn36:41.2": "vô minh bị diệt trừ, minh đã sinh; bóng tối bị diệt trừ, ánh sáng đã sinh; như vậy đối với người sống không phóng dật, nhiệt tâm, tinh cần.",
  "mn36:41.3": "Này Aggivessana, ngay cả những cảm thọ lạc như vậy cũng không chiếm đoạt tâm ta.",
  "mn36:42.1": "Với tâm định tĩnh như vậy, thanh tịnh, trong sáng, không cấu uế, không phiền não, mềm mại, dễ uốn nắn, vững chắc, bất động, ta hướng tâm đến tuệ về sự diệt trừ các lậu hoặc.",
  "mn36:42.2": "Ta biết rõ ‘đây là khổ’ như thật, ta biết rõ ‘đây là nguyên nhân của khổ’ như thật, ta biết rõ ‘đây là sự diệt khổ’ như thật, ta biết rõ ‘đây là con đường đưa đến sự diệt khổ’ như thật.",
  "mn36:42.3": "Ta biết rõ ‘đây là các lậu hoặc’ như thật, ta biết rõ ‘đây là nguyên nhân của các lậu hoặc’ như thật, ta biết rõ ‘đây là sự diệt trừ các lậu hoặc’ như thật, ta biết rõ ‘đây là con đường đưa đến sự diệt trừ các lậu hoặc’ như thật.",
  "mn36:43.1": "Khi ta biết như vậy, thấy như vậy, tâm ta giải thoát khỏi lậu hoặc dục, tâm ta giải thoát khỏi lậu hoặc hữu, tâm ta giải thoát khỏi lậu hoặc vô minh.",
  "mn36:43.2": "Khi giải thoát, tuệ về sự giải thoát khởi lên.",
  "mn36:43.3": "Ta biết rõ: ‘Sự sinh đã tận, đời sống phạm hạnh đã hoàn thành, việc cần làm đã làm, không còn trở lại trạng thái này nữa’.",
  "mn36:44.1": "Này Aggivessana, đây là minh thứ ba ta đạt được trong canh cuối của đêm; ",
  "mn36:44.2": "vô minh bị diệt trừ, minh đã sinh; bóng tối bị diệt trừ, ánh sáng đã sinh; như vậy đối với người sống không phóng dật, nhiệt tâm, tinh cần.",
  "mn36:44.3": "Này Aggivessana, ngay cả những cảm thọ lạc như vậy cũng không chiếm đoạt tâm ta.",
  "mn36:45.1": "Này Aggivessana, ta nhớ lại khi ta thuyết pháp cho hàng trăm hội chúng.",
  "mn36:45.2": "Và từng người trong số họ nghĩ: ",
  "mn36:45.3": "‘Sa-môn Gotama đang thuyết pháp cho riêng ta’.",
  "mn36:45.4": "Nhưng, này Aggivessana, không nên nghĩ như vậy; ",
  "mn36:45.5": "Như Lai thuyết pháp cho người khác chỉ để làm cho họ hiểu.",
  "mn36:45.6": "Này Aggivessana, khi kết thúc bài nói chuyện đó, ta lại an trú tâm vào cùng một đề mục định trước đó, làm cho tâm an tịnh, nhất tâm, định tĩnh, nhờ đó ta thường xuyên an trú”.",
  "mn36:45.7": "“Điều đó là hợp lý đối với Tôn giả Gotama, như đối với một bậc A-la-hán, Chánh Đẳng Giác. ",
  "mn36:45.8": "Nhưng Tôn giả Gotama có nhớ đã từng ngủ trưa không?”",
  "mn36:46.1": "“Này Aggivessana, ta nhớ rằng vào tháng cuối cùng của mùa hè, sau bữa ăn và sau khi đi khất thực về, ta trải bốn lớp y tăng-già-lê, nằm nghiêng về bên phải, chánh niệm và tỉnh giác, rồi chìm vào giấc ngủ”.",
  "mn36:46.2": "“Thưa Tôn giả Gotama, một số Sa-môn và Bà-la-môn gọi đó là sự sống trong si mê”.",
  "mn36:46.3": "“Này Aggivessana, không phải vì thế mà một người là si mê hay không si mê. ",
  "mn36:46.4": "Nhưng, này Aggivessana, làm thế nào một người là si mê và không si mê, ",
  "mn36:46.5": "hãy lắng nghe, hãy chú ý kỹ, ta sẽ nói”.",
  "mn36:46.6": "“Vâng, thưa Tôn giả,” Saccaka, con trai của Nigaṇṭha, đáp lời Thế Tôn.",
  "mn36:46.7": "Thế Tôn nói như sau: ",
  "mn36:47.1": "“Này Aggivessana, bất cứ ai mà các lậu hoặc gây ô nhiễm, dẫn đến tái sinh, có đau khổ, có quả báo khổ, dẫn đến sinh, già, chết trong tương lai chưa được đoạn trừ, ta gọi người đó là ‘si mê’.",
  "mn36:47.2": "Này Aggivessana, vì các lậu hoặc chưa được đoạn trừ, nên người đó là si mê.",
  "mn36:47.3": "Này Aggivessana, bất cứ ai mà các lậu hoặc gây ô nhiễm, dẫn đến tái sinh, có đau khổ, có quả báo khổ, dẫn đến sinh, già, chết trong tương lai đã được đoạn trừ, ta gọi người đó là ‘không si mê’.",
  "mn36:47.4": "Này Aggivessana, vì các lậu hoặc đã được đoạn trừ, nên người đó là không si mê.",
  "mn36:47.5": "Này Aggivessana, đối với Như Lai, các lậu hoặc gây ô nhiễm, dẫn đến tái sinh, có đau khổ, có quả báo khổ, dẫn đến sinh, già, chết trong tương lai đã được đoạn trừ, bị cắt đứt tận gốc, làm cho như cây thốt nốt bị chặt đứt ngọn, không còn khả năng tái sinh, không còn khả năng phát sinh trong tương lai.",
  "mn36:47.6": "Ví như, này Aggivessana, một cây thốt nốt bị chặt đứt ngọn thì không thể mọc lại được nữa; ",
  "mn36:47.7": "cũng vậy, này Aggivessana, đối với Như Lai, các lậu hoặc gây ô nhiễm, dẫn đến tái sinh, có đau khổ, có quả báo khổ, dẫn đến sinh, già, chết trong tương lai đã được đoạn trừ, bị cắt đứt tận gốc, làm cho như cây thốt nốt bị chặt đứt ngọn, không còn khả năng tái sinh, không còn khả năng phát sinh trong tương lai”.",
  "mn36:48.1": "Khi được nói như vậy, Saccaka, con trai của Nigaṇṭha, nói với Thế Tôn: ",
  "mn36:48.2": "“Thật kỳ diệu, thưa Tôn giả Gotama! Thật phi thường, thưa Tôn giả Gotama! ",
  "mn36:48.3": "Dù Tôn giả Gotama bị chất vấn liên tục, bị hỏi bằng những lời lẽ gay gắt, màu da của Tôn giả vẫn trong sáng, sắc mặt vẫn tươi tắn, như đối với một bậc A-la-hán, Chánh Đẳng Giác.",
  "mn36:48.4": "Thưa Tôn giả Gotama, tôi nhớ đã từng tranh luận với Pūraṇa Kassapa. ",
  "mn36:48.5": "Khi tôi tranh luận với ông ta, ông ta lại nói sang chuyện khác, lái câu chuyện ra ngoài, và biểu lộ sự tức giận, bực bội, và bất mãn.",
  "mn36:48.6": "Nhưng Tôn giả Gotama, dù bị chất vấn liên tục, bị hỏi bằng những lời lẽ gay gắt, màu da của Tôn giả vẫn trong sáng, sắc mặt vẫn tươi tắn, như đối với một bậc A-la-hán, Chánh Đẳng Giác.",
  "mn36:48.7": "Thưa Tôn giả Gotama, tôi nhớ đã từng tranh luận với Makkhali Gosāla…v.v… ",
  "mn36:48.8": "Ajita Kesakambala… ",
  "mn36:48.9": "Pakudha Kaccāyana… ",
  "mn36:48.10": "Sañjaya Belaṭṭhaputta… ",
  "mn36:48.11": "Nigaṇṭha Nāṭaputta.",
  "mn36:48.12": "Khi tôi tranh luận với ông ta, ông ta lại nói sang chuyện khác, lái câu chuyện ra ngoài, và biểu lộ sự tức giận, bực bội, và bất mãn.",
  "mn36:48.13": "Nhưng Tôn giả Gotama, dù bị chất vấn liên tục, bị hỏi bằng những lời lẽ gay gắt, màu da của Tôn giả vẫn trong sáng, sắc mặt vẫn tươi tắn, như đối với một bậc A-la-hán, Chánh Đẳng Giác.",
  "mn36:48.14": "Thưa Tôn giả Gotama, bây giờ chúng tôi xin đi. ",
  "mn36:48.15": "Chúng tôi có nhiều việc phải làm, nhiều điều cần thực hiện”.",
  "mn36:48.16": "“Này Aggivessana, bây giờ ông thấy lúc nào thích hợp thì cứ làm”.",
  "mn36:48.17": "Khi ấy, Saccaka, con trai của Nigaṇṭha, hoan hỷ và tán thán lời Thế Tôn, rồi đứng dậy rời chỗ ngồi và bỏ đi.",
  "mn36:48.18": "Kinh Đại Saccaka, thứ sáu, đã xong."
}
window.BILARA["mn36"]["vi"]["mn36:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
