window.BILARA = window.BILARA || {};
window.BILARA["mn37"] = window.BILARA["mn37"] || {};
window.BILARA["mn37"]["vi"] = {
  "mn37:0.1": "Trung Bộ Kinh 37 ",
  "mn37:0.2": "Tiểu Kinh Đoạn Tận Ái ",
  "mn37:1.1": "Tôi nghe như vầy—",
  "mn37:1.2": "Một thời, Thế Tôn trú ở Sāvatthī, tại Đông Viên, trong lâu đài của Migāra mẹ. ",
  "mn37:2.1": "Rồi Sakka, vua các cõi trời, đi đến chỗ Thế Tôn ở; sau khi đến, đảnh lễ Thế Tôn rồi đứng một bên. Đứng một bên, Sakka, vua các cõi trời, bạch Thế Tôn rằng: ",
  "mn37:2.2": "“Bạch Thế Tôn, tóm tắt lại, một Tỳ-kheo được giải thoát do đoạn tận ái, đạt đến cứu cánh, đạt đến an ổn tối thượng, đạt đến phạm hạnh tối thượng, đạt đến cứu cánh cuối cùng, là bậc tối thắng giữa chư thiên và loài người, là như thế nào?” ",
  "mn37:3.1": "“Ở đây, vua các cõi trời, Tỳ-kheo nghe rằng: ",
  "mn37:3.2": "‘Tất cả các pháp không đáng để chấp thủ.’ ",
  "mn37:3.3": "Và này vua các cõi trời, Tỳ-kheo nghe rằng: ",
  "mn37:3.4": "‘Tất cả các pháp không đáng để chấp thủ.’ ",
  "mn37:3.5": "Vị ấy biết rõ tất cả các pháp; sau khi biết rõ tất cả các pháp, vị ấy hiểu rõ tất cả các pháp; sau khi hiểu rõ tất cả các pháp, vị ấy cảm thọ bất cứ cảm thọ nào—",
  "mn37:3.6": "dù là lạc thọ, khổ thọ, hay bất khổ bất lạc thọ, vị ấy sống quán vô thường trong các cảm thọ ấy, sống quán ly tham, sống quán đoạn diệt, sống quán xả bỏ. ",
  "mn37:3.7": "Vị ấy sống quán vô thường trong các cảm thọ ấy, sống quán ly tham, sống quán đoạn diệt, sống quán xả bỏ, không chấp thủ bất cứ điều gì trên đời. ",
  "mn37:3.8": "Không chấp thủ, vị ấy không lo sợ; không lo sợ, vị ấy tự mình chứng Niết-bàn: ",
  "mn37:3.9": "‘Sanh đã tận, phạm hạnh đã thành, việc cần làm đã làm, không còn trở lại trạng thái này nữa’—vị ấy biết rõ như vậy. ",
  "mn37:3.10": "Này vua các cõi trời, tóm tắt lại, một Tỳ-kheo được giải thoát do đoạn tận ái, đạt đến cứu cánh, đạt đến an ổn tối thượng, đạt đến phạm hạnh tối thượng, đạt đến cứu cánh cuối cùng, là bậc tối thắng giữa chư thiên và loài người, là như vậy.” ",
  "mn37:4.1": "Rồi Sakka, vua các cõi trời, hoan hỷ, tùy hỷ lời Thế Tôn dạy, đảnh lễ Thế Tôn, đi nhiễu bên phải rồi biến mất tại chỗ. ",
  "mn37:5.1": "Lúc bấy giờ, Tôn giả Mahāmoggallāna đang ngồi không xa Thế Tôn. ",
  "mn37:5.2": "Rồi Tôn giả Mahāmoggallāna suy nghĩ: ",
  "mn37:5.3": "“Không biết vị Dạ-xoa ấy có hiểu và tùy hỷ lời Thế Tôn dạy hay không; ",
  "mn37:5.4": "hay là ta nên biết vị Dạ-xoa ấy—",
  "mn37:5.5": "rằng vị Dạ-xoa ấy có hiểu và tùy hỷ lời Thế Tôn dạy hay không?” ",
  "mn37:6.1": "Rồi Tôn giả Mahāmoggallāna—như một người lực sĩ co duỗi cánh tay, hay duỗi co cánh tay—biến mất khỏi Đông Viên, lâu đài của Migāra mẹ, và hiện ra giữa chư thiên cõi Ba mươi ba. ",
  "mn37:7.1": "Lúc bấy giờ, Sakka, vua các cõi trời, đang vui chơi trong vườn Ekapuṇḍarīka, được năm trăm nhạc khí trời hòa tấu. ",
  "mn37:7.2": "Sakka, vua các cõi trời, thấy Tôn giả Mahāmoggallāna từ xa đi đến. ",
  "mn37:7.3": "Thấy vậy, Ngài cho dừng năm trăm nhạc khí trời ấy lại, rồi đi đến chỗ Tôn giả Mahāmoggallāna; sau khi đến, Ngài nói với Tôn giả Mahāmoggallāna rằng: ",
  "mn37:7.4": "“Kính bạch Tôn giả Moggallāna, xin mời đến, kính mừng Tôn giả Moggallāna. ",
  "mn37:7.5": "Đã lâu lắm rồi, kính bạch Tôn giả Moggallāna, Ngài mới có dịp đến đây. ",
  "mn37:7.6": "Xin mời ngồi, kính bạch Tôn giả Moggallāna, chỗ ngồi này đã được sửa soạn.” ",
  "mn37:7.7": "Tôn giả Mahāmoggallāna ngồi xuống chỗ đã sửa soạn. ",
  "mn37:7.8": "Sakka, vua các cõi trời, cũng lấy một chỗ ngồi thấp hơn rồi ngồi một bên. ",
  "mn37:7.9": "Khi Sakka, vua các cõi trời, đã ngồi một bên, Tôn giả Mahāmoggallāna nói với Ngài rằng: ",
  "mn37:8.1": "“Này Kosiya, Thế Tôn đã nói về sự giải thoát do đoạn tận ái một cách tóm tắt như thế nào? ",
  "mn37:8.2": "Chúng tôi cũng muốn được nghe câu chuyện ấy.” ",
  "mn37:8.3": "“Kính bạch Tôn giả Moggallāna, chúng tôi có nhiều việc phải làm, nhiều điều phải lo—",
  "mn37:8.4": "có thể là việc của riêng mình, hoặc là việc của chư thiên cõi Ba mươi ba. ",
  "mn37:8.5": "Và nữa, kính bạch Tôn giả Moggallāna, điều gì đã được nghe kỹ, nắm giữ kỹ, chú ý kỹ, ghi nhớ kỹ, thì nó cũng nhanh chóng biến mất khỏi chúng tôi. ",
  "mn37:8.6": "Thuở xưa, kính bạch Tôn giả Moggallāna, một trận chiến giữa chư thiên và A-tu-la đã xảy ra. ",
  "mn37:8.7": "Trong trận chiến ấy, kính bạch Tôn giả Moggallāna, chư thiên đã thắng, A-tu-la đã thua. ",
  "mn37:8.8": "Sau khi thắng trận chiến ấy, kính bạch Tôn giả Moggallāna, tôi, người đã thắng trận, trở về và xây dựng lâu đài tên là Vejayanta. ",
  "mn37:8.9": "Lâu đài Vejayanta ấy, kính bạch Tôn giả Moggallāna, có một trăm ngọn tháp. ",
  "mn37:8.10": "Mỗi ngọn tháp có bảy trăm lầu các. ",
  "mn37:8.11": "Mỗi lầu các có bảy nàng tiên. ",
  "mn37:8.12": "Mỗi nàng tiên có bảy thị nữ. ",
  "mn37:8.13": "Kính bạch Tôn giả Moggallāna, Ngài có muốn xem vẻ đẹp của lâu đài Vejayanta không?” ",
  "mn37:8.14": "Tôn giả Mahāmoggallāna im lặng chấp thuận. ",
  "mn37:9.1": "Rồi Sakka, vua các cõi trời, và Đại vương Vessavaṇa, dẫn Tôn giả Mahāmoggallāna đi đến lâu đài Vejayanta. ",
  "mn37:9.2": "Các thị nữ của Sakka, vua các cõi trời, thấy Tôn giả Mahāmoggallāna từ xa đi đến; ",
  "mn37:9.3": "thấy vậy, họ hổ thẹn, e ngại, rồi đi vào phòng riêng của mình. ",
  "mn37:10.1": "Như một nàng dâu thấy cha chồng thì hổ thẹn, e ngại; ",
  "mn37:10.2": "cũng vậy, các thị nữ của Sakka, vua các cõi trời, thấy Tôn giả Mahāmoggallāna thì hổ thẹn, e ngại, rồi đi vào phòng riêng của mình. ",
  "mn37:10.3": "Rồi Sakka, vua các cõi trời, và Đại vương Vessavaṇa, dẫn Tôn giả Mahāmoggallāna đi dạo quanh lâu đài Vejayanta, và nói: ",
  "mn37:10.4": "“Kính bạch Tôn giả Moggallāna, xin hãy xem vẻ đẹp này của lâu đài Vejayanta; ",
  "mn37:10.5": "kính bạch Tôn giả Moggallāna, xin hãy xem vẻ đẹp này của lâu đài Vejayanta.” ",
  "mn37:10.6": "“Này Tôn giả Kosiya, điều này thật đẹp, đúng như người đã tạo phước từ trước. ",
  "mn37:10.7": "Con người khi thấy điều gì đẹp đẽ cũng nói rằng: ",
  "mn37:10.8": "‘Ôi, thật đẹp như của chư thiên cõi Ba mươi ba!’ ",
  "mn37:10.9": "Điều này thật đẹp đối với Tôn giả Kosiya, đúng như người đã tạo phước từ trước.” ",
  "mn37:11.1": "Rồi Tôn giả Mahāmoggallāna suy nghĩ: ",
  "mn37:11.2": "“Vị Dạ-xoa này sống quá phóng dật. ",
  "mn37:11.3": "Hay là ta nên làm cho vị Dạ-xoa này khởi tâm sợ hãi.” ",
  "mn37:11.4": "Rồi Tôn giả Mahāmoggallāna vận dụng thần thông đến mức làm cho lâu đài Vejayanta rung chuyển, chấn động, lay động bằng ngón chân cái. ",
  "mn37:11.5": "Rồi Sakka, vua các cõi trời, Đại vương Vessavaṇa, và chư thiên cõi Ba mươi ba đều khởi tâm kinh ngạc, lạ lùng: ",
  "mn37:11.6": "“Ôi, thật kỳ diệu! Ôi, thật phi thường! ",
  "mn37:11.7": "Sức thần thông và uy lực lớn lao của vị Sa-môn này, đến nỗi làm cho cung điện trời rung chuyển, chấn động, lay động bằng ngón chân cái!” ",
  "mn37:12.1": "Rồi Tôn giả Mahāmoggallāna biết Sakka, vua các cõi trời, đã kinh sợ, lông tóc dựng đứng, liền nói với Sakka, vua các cõi trời, rằng: ",
  "mn37:12.2": "“Này Kosiya, Thế Tôn đã nói về sự giải thoát do đoạn tận ái một cách tóm tắt như thế nào? ",
  "mn37:12.3": "Chúng tôi cũng muốn được nghe câu chuyện ấy.” ",
  "mn37:12.4": "“Kính bạch Tôn giả Moggallāna, ở đây tôi đã đi đến chỗ Thế Tôn ở; sau khi đến, đảnh lễ Thế Tôn rồi đứng một bên. Đứng một bên, kính bạch Tôn giả Moggallāna, tôi đã bạch Thế Tôn rằng: ",
  "mn37:12.5": "‘Bạch Thế Tôn, tóm tắt lại, một Tỳ-kheo được giải thoát do đoạn tận ái, đạt đến cứu cánh, đạt đến an ổn tối thượng, đạt đến phạm hạnh tối thượng, đạt đến cứu cánh cuối cùng, là bậc tối thắng giữa chư thiên và loài người, là như thế nào?’ ",
  "mn37:13.1": "Khi được hỏi như vậy, kính bạch Tôn giả Moggallāna, Thế Tôn đã nói với tôi rằng: ",
  "mn37:13.2": "‘Ở đây, vua các cõi trời, Tỳ-kheo nghe rằng: ",
  "mn37:13.3": "“Tất cả các pháp không đáng để chấp thủ.” ",
  "mn37:13.4": "Và này vua các cõi trời, Tỳ-kheo nghe rằng: ",
  "mn37:13.5": "“Tất cả các pháp không đáng để chấp thủ.” ",
  "mn37:13.6": "Vị ấy biết rõ tất cả các pháp; sau khi biết rõ tất cả các pháp, vị ấy hiểu rõ tất cả các pháp; sau khi hiểu rõ tất cả các pháp, vị ấy cảm thọ bất cứ cảm thọ nào, dù là lạc thọ, khổ thọ, hay bất khổ bất lạc thọ. ",
  "mn37:13.7": "Vị ấy sống quán vô thường trong các cảm thọ ấy, sống quán ly tham, sống quán đoạn diệt, sống quán xả bỏ. ",
  "mn37:13.8": "Vị ấy sống quán vô thường trong các cảm thọ ấy, sống quán ly tham, sống quán đoạn diệt, sống quán xả bỏ, không chấp thủ bất cứ điều gì trên đời, ",
  "mn37:13.9": "không chấp thủ, vị ấy không lo sợ; không lo sợ, vị ấy tự mình chứng Niết-bàn: ",
  "mn37:13.10": "“Sanh đã tận, phạm hạnh đã thành, việc cần làm đã làm, không còn trở lại trạng thái này nữa”—vị ấy biết rõ như vậy. ",
  "mn37:13.11": "Này vua các cõi trời, tóm tắt lại, một Tỳ-kheo được giải thoát do đoạn tận ái, đạt đến cứu cánh, đạt đến an ổn tối thượng, đạt đến phạm hạnh tối thượng, đạt đến cứu cánh cuối cùng, là bậc tối thắng giữa chư thiên và loài người, là như vậy.’ ",
  "mn37:13.12": "Kính bạch Tôn giả Moggallāna, Thế Tôn đã nói về sự giải thoát do đoạn tận ái một cách tóm tắt cho tôi như vậy.” ",
  "mn37:14.1": "Rồi Tôn giả Mahāmoggallāna hoan hỷ, tùy hỷ lời Sakka, vua các cõi trời, dạy—như một người lực sĩ co duỗi cánh tay, hay duỗi co cánh tay—biến mất khỏi chư thiên cõi Ba mươi ba, và hiện ra tại Đông Viên, lâu đài của Migāra mẹ. ",
  "mn37:14.2": "Rồi các thị nữ của Sakka, vua các cõi trời, sau khi Tôn giả Mahāmoggallāna vừa đi khỏi, nói với Sakka, vua các cõi trời, rằng: ",
  "mn37:14.3": "“Kính bạch Tôn giả, đó có phải là Thế Tôn, bậc Đạo Sư của Ngài không?” ",
  "mn37:14.4": "“Kính bạch Tôn giả, đó không phải là Thế Tôn, bậc Đạo Sư của tôi. ",
  "mn37:14.5": "Đó là Tôn giả Mahāmoggallāna, một vị đồng phạm hạnh của tôi.” ",
  "mn37:14.6": "“Kính bạch Tôn giả, Ngài thật có lợi, Ngài thật được tốt lành ",
  "mn37:14.7": "khi có một vị đồng phạm hạnh có thần thông lớn, uy lực lớn như vậy. ",
  "mn37:14.8": "Ôi, chắc chắn đó là Thế Tôn, bậc Đạo Sư của Ngài!” ",
  "mn37:15.1": "Rồi Tôn giả Mahāmoggallāna đi đến chỗ Thế Tôn ở; sau khi đến, đảnh lễ Thế Tôn rồi ngồi một bên. Khi đã ngồi một bên, Tôn giả Mahāmoggallāna bạch Thế Tôn rằng: ",
  "mn37:15.2": "“Bạch Thế Tôn, Thế Tôn có biết rằng một vị Dạ-xoa có uy lực lớn đã được nghe về sự giải thoát do đoạn tận ái một cách tóm tắt không?” ",
  "mn37:15.3": "“Này Moggallāna, Ta biết. Ở đây, Sakka, vua các cõi trời, đã đi đến chỗ Ta ở; sau khi đến, đảnh lễ Ta rồi đứng một bên. Đứng một bên, này Moggallāna, Sakka, vua các cõi trời, đã nói với Ta rằng: ",
  "mn37:15.4": "‘Bạch Thế Tôn, tóm tắt lại, một Tỳ-kheo được giải thoát do đoạn tận ái, đạt đến cứu cánh, đạt đến an ổn tối thượng, đạt đến phạm hạnh tối thượng, đạt đến cứu cánh cuối cùng, là bậc tối thắng giữa chư thiên và loài người, là như thế nào?’ ",
  "mn37:15.5": "Khi được hỏi như vậy, này Moggallāna, Ta đã nói với Sakka, vua các cõi trời, rằng: ",
  "mn37:15.6": "‘Ở đây, vua các cõi trời, Tỳ-kheo nghe rằng: ",
  "mn37:15.7": "“Tất cả các pháp không đáng để chấp thủ.” ",
  "mn37:15.8": "Và này vua các cõi trời, Tỳ-kheo nghe rằng: ",
  "mn37:15.9": "“Tất cả các pháp không đáng để chấp thủ.” ",
  "mn37:15.10": "Vị ấy biết rõ tất cả các pháp; sau khi biết rõ tất cả các pháp, vị ấy hiểu rõ tất cả các pháp; sau khi hiểu rõ tất cả các pháp, vị ấy cảm thọ bất cứ cảm thọ nào, dù là lạc thọ, khổ thọ, hay bất khổ bất lạc thọ. ",
  "mn37:15.11": "Vị ấy sống quán vô thường trong các cảm thọ ấy, sống quán ly tham, sống quán đoạn diệt, sống quán xả bỏ. ",
  "mn37:15.12": "Vị ấy sống quán vô thường trong các cảm thọ ấy, sống quán ly tham, sống quán đoạn diệt, ",
  "mn37:15.13": "sống quán xả bỏ, không chấp thủ bất cứ điều gì trên đời, ",
  "mn37:15.14": "không chấp thủ, vị ấy không lo sợ; không lo sợ, vị ấy tự mình chứng Niết-bàn: ",
  "mn37:15.15": "“Sanh đã tận, phạm hạnh đã thành, việc cần làm đã làm, không còn trở lại trạng thái này nữa”—vị ấy biết rõ như vậy. ",
  "mn37:15.16": "Này vua các cõi trời, tóm tắt lại, một Tỳ-kheo được giải thoát do đoạn tận ái, đạt đến cứu cánh, đạt đến an ổn tối thượng, đạt đến phạm hạnh tối thượng, đạt đến cứu cánh cuối cùng, là bậc tối thắng giữa chư thiên và loài người, là như vậy.’ ",
  "mn37:15.17": "Này Moggallāna, Ta biết rằng Ta đã nói về sự giải thoát do đoạn tận ái một cách tóm tắt cho Sakka, vua các cõi trời, như vậy.” ",
  "mn37:15.18": "Thế Tôn đã nói như vậy. ",
  "mn37:15.19": "Tôn giả Mahāmoggallāna hoan hỷ lời Thế Tôn dạy. ",
  "mn37:15.20": "Tiểu Kinh Đoạn Tận Ái, thứ bảy, chấm dứt. "
}
window.BILARA["mn37"]["vi"]["mn37:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
