window.BILARA = window.BILARA || {};
window.BILARA["mn42"] = window.BILARA["mn42"] || {};
window.BILARA["mn42"]["vi"] = {
  "mn42:0.1": "Trung Bộ Kinh 42 ",
  "mn42:0.2": "Kinh Verañja ",
  "mn42:1.1": "Tôi nghe như vầy—",
  "mn42:1.2": "Một thời, Thế Tôn trú ở Sāvatthī, tại Jetavana, khu vườn của Anāthapiṇḍika. ",
  "mn42:2.1": "Lúc bấy giờ, các gia chủ Bà la môn Verañja đang cư trú tại Sāvatthī vì một công việc nào đó. ",
  "mn42:2.2": "Các gia chủ Bà la môn Verañja nghe rằng: ",
  "mn42:2.3": "“Sa môn Gotama, con của dòng Sakya, xuất gia từ dòng Sakya, đang trú ở Sāvatthī, tại Jetavana, khu vườn của Anāthapiṇḍika. ",
  "mn42:2.4": "Tiếng đồn tốt đẹp về Tôn giả Gotama như sau: ",
  "mn42:2.5": "‘Đức Thế Tôn ấy là bậc A la hán, Chánh Đẳng Giác, đầy đủ Minh Hạnh, Thiện Thệ, hiểu biết thế gian, bậc Vô Thượng điều ngự trượng phu, Bậc Đạo Sư của trời và người, Phật, Thế Tôn’. ",
  "mn42:2.6": "Ngài tự mình chứng ngộ, làm chứng và tuyên bố thế giới này cùng với chư thiên, ma vương, phạm thiên, cùng với các sa môn, bà la môn, quần chúng trời và người. ",
  "mn42:2.7": "Ngài thuyết pháp toàn hảo ở đoạn đầu, toàn hảo ở đoạn giữa, toàn hảo ở đoạn cuối, có nghĩa và có văn; Ngài tuyên bố đời sống phạm hạnh hoàn toàn đầy đủ và thanh tịnh. ",
  "mn42:2.8": "Thật tốt lành khi được thấy những bậc A la hán như vậy.” ",
  "mn42:3.1": "Rồi các gia chủ Bà la môn Verañja đi đến chỗ Thế Tôn; sau khi đến, một số người đảnh lễ Thế Tôn rồi ngồi xuống một bên; một số người chào hỏi Thế Tôn, sau khi trao đổi những lời chào hỏi thân mật rồi ngồi xuống một bên; một số người chắp tay vái Thế Tôn rồi ngồi xuống một bên; một số người xưng tên và dòng họ trước Thế Tôn rồi ngồi xuống một bên; một số người im lặng ngồi xuống một bên. Sau khi ngồi xuống một bên, các gia chủ Bà la môn Verañja bạch Thế Tôn rằng: ",
  "mn42:4.1": "“Thưa Tôn giả Gotama, nguyên nhân nào, duyên nào khiến một số chúng sinh ở đây, sau khi thân hoại mạng chung, sinh vào cõi dữ, ác thú, đọa xứ, địa ngục? ",
  "mn42:4.2": "Và thưa Tôn giả Gotama, nguyên nhân nào, duyên nào khiến một số chúng sinh ở đây, sau khi thân hoại mạng chung, sinh vào thiện thú, cõi trời?” ",
  "mn42:5.1": "“Này các gia chủ, do hành động bất thiện, hành động không đúng đắn, mà một số chúng sinh ở đây, sau khi thân hoại mạng chung, sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn42:5.2": "Này các gia chủ, do hành động thiện, hành động đúng đắn, mà một số chúng sinh ở đây, sau khi thân hoại mạng chung, sinh vào thiện thú, cõi trời.” ",
  "mn42:6.1": "“Chúng tôi không hiểu rõ ý nghĩa của lời nói vắn tắt này của Tôn giả Gotama, khi chưa được giải thích rộng rãi. ",
  "mn42:6.2": "Kính mong Tôn giả Gotama thuyết pháp cho chúng tôi để chúng tôi có thể hiểu rõ ý nghĩa của lời nói vắn tắt này của Tôn giả Gotama, khi được giải thích rộng rãi.” ",
  "mn42:6.3": "“Vậy thì, này các gia chủ, hãy lắng nghe và suy nghĩ kỹ, tôi sẽ nói.” ",
  "mn42:6.4": "“Vâng, thưa Tôn giả,” các gia chủ Bà la môn Verañja đáp lời Thế Tôn. ",
  "mn42:6.5": "Thế Tôn nói như sau: ",
  "mn42:7.1": "“Này các gia chủ, có ba loại hành động bất thiện, không đúng đắn bằng thân; có bốn loại hành động bất thiện, không đúng đắn bằng lời; có ba loại hành động bất thiện, không đúng đắn bằng ý. ",
  "mn42:8.1": "Và này các gia chủ, thế nào là ba loại hành động bất thiện, không đúng đắn bằng thân? ",
  "mn42:8.2": "Ở đây, này các gia chủ, có người sát sinh. Người ấy hung ác, tay đẫm máu, chuyên sát hại, không có lòng từ bi đối với chúng sinh. ",
  "mn42:8.3": "Lại nữa, người ấy lấy của không cho. Cái gì là tài sản, vật dụng của người khác … cái đó không được cho, bị xem là trộm cắp, người ấy lấy. ",
  "mn42:8.4": "Lại nữa, người ấy tà hạnh trong các dục. Những người nữ được mẹ bảo vệ … người ấy có hành vi tà hạnh với những người như vậy. ",
  "mn42:8.5": "Này các gia chủ, như vậy là ba loại hành động bất thiện, không đúng đắn bằng thân. ",
  "mn42:9.1": "Và này các gia chủ, thế nào là bốn loại hành động bất thiện, không đúng đắn bằng lời? ",
  "mn42:9.2": "Ở đây, này các gia chủ, có người nói dối. Hoặc ở hội đồng … người ấy nói dối một cách cố ý. ",
  "mn42:9.3": "Lại nữa, người ấy nói lời chia rẽ. Nghe điều này ở đây, nói lại ở kia … người ấy nói lời gây chia rẽ. ",
  "mn42:9.4": "Lại nữa, người ấy nói lời thô ác. Lời nói nào thô lỗ, cộc cằn … người ấy nói lời như vậy. ",
  "mn42:9.5": "Lại nữa, người ấy nói lời vô ích. Nói không đúng lúc … không có giới hạn, không liên quan đến mục đích. ",
  "mn42:9.6": "Này các gia chủ, như vậy là bốn loại hành động bất thiện, không đúng đắn bằng lời. ",
  "mn42:10.1": "Và này các gia chủ, thế nào là ba loại hành động bất thiện, không đúng đắn bằng ý? ",
  "mn42:10.2": "Ở đây, này các gia chủ, có người tham lam …pe… ‘mong cái đó là của tôi’. ",
  "mn42:10.3": "Lại nữa, người ấy có tâm sân hận, ý nghĩ ác độc: ‘mong cho những chúng sinh này bị giết … hoặc không còn tồn tại’. ",
  "mn42:10.4": "Lại nữa, người ấy có tà kiến, thấy sai lầm: ",
  "mn42:10.5": "‘không có bố thí, không có cúng dường … tự mình chứng ngộ, làm chứng và tuyên bố’. ",
  "mn42:10.6": "Này các gia chủ, như vậy là ba loại hành động bất thiện, không đúng đắn bằng ý. ",
  "mn42:10.7": "Này các gia chủ, do hành động bất thiện, không đúng đắn như vậy, mà một số chúng sinh ở đây, sau khi thân hoại mạng chung, sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn42:11.1": "Này các gia chủ, có ba loại hành động thiện, đúng đắn bằng thân; có bốn loại hành động thiện, đúng đắn bằng lời; có ba loại hành động thiện, đúng đắn bằng ý. ",
  "mn42:12.1": "Và này các gia chủ, thế nào là ba loại hành động thiện, đúng đắn bằng thân? ",
  "mn42:12.2": "Ở đây, này các gia chủ, có người từ bỏ sát sinh, tránh xa sát sinh, đặt gậy xuống, đặt vũ khí xuống, biết hổ thẹn, có lòng từ bi, sống vì lợi ích và thương xót tất cả chúng sinh. ",
  "mn42:12.3": "Từ bỏ lấy của không cho, tránh xa lấy của không cho, cái gì là của người khác … cái đó không được cho, không bị xem là trộm cắp, người ấy không lấy. ",
  "mn42:12.4": "Từ bỏ tà hạnh trong các dục … người ấy không có hành vi tà hạnh với những người như vậy. ",
  "mn42:12.5": "Này các gia chủ, như vậy là ba loại hành động thiện, đúng đắn bằng thân. ",
  "mn42:13.1": "Và này các gia chủ, thế nào là bốn loại hành động thiện, đúng đắn bằng lời? ",
  "mn42:13.2": "Ở đây, này các gia chủ, có người từ bỏ nói dối, tránh xa nói dối. Hoặc ở hội đồng …pe… người ấy không nói dối một cách cố ý. ",
  "mn42:13.3": "Từ bỏ lời chia rẽ … người ấy nói lời hòa hợp. ",
  "mn42:13.4": "Từ bỏ lời thô ác … người ấy nói lời như vậy. ",
  "mn42:13.5": "Từ bỏ lời vô ích … đúng lúc, có lý do, có giới hạn, có liên quan đến mục đích. ",
  "mn42:13.6": "Này các gia chủ, như vậy là bốn loại hành động thiện, đúng đắn bằng lời. ",
  "mn42:14.1": "Và này các gia chủ, thế nào là ba loại hành động thiện, đúng đắn bằng ý? ",
  "mn42:14.2": "Ở đây, này các gia chủ, có người không tham lam. Cái gì là tài sản, vật dụng của người khác, người ấy không tham lam: ‘mong cái gì của người khác là của tôi’. ",
  "mn42:14.3": "Lại nữa, người ấy có tâm không sân hận, ý nghĩ không ác độc: ‘mong cho những chúng sinh này không thù hằn, không bị hại, không khổ não, sống an vui’. ",
  "mn42:14.4": "Lại nữa, người ấy có chánh kiến, thấy không sai lầm: ",
  "mn42:14.5": "‘có bố thí, có cúng dường … tự mình chứng ngộ, làm chứng và tuyên bố’. ",
  "mn42:14.6": "Này các gia chủ, như vậy là ba loại hành động thiện, đúng đắn bằng ý. ",
  "mn42:14.7": "Này các gia chủ, do hành động thiện, đúng đắn như vậy, mà một số chúng sinh ở đây, sau khi thân hoại mạng chung, sinh vào thiện thú, cõi trời. ",
  "mn42:15.1": "Này các gia chủ, nếu người hành thiện, hành đúng đắn mong muốn: ",
  "mn42:15.2": "‘mong sao sau khi thân hoại mạng chung, tôi được đồng hành với các đại gia tộc Sát đế lợi’; ",
  "mn42:15.3": "điều đó có thể xảy ra, người ấy sau khi thân hoại mạng chung, có thể được đồng hành với các đại gia tộc Sát đế lợi. ",
  "mn42:15.4": "Vì sao vậy? ",
  "mn42:15.5": "Vì người ấy hành thiện, hành đúng đắn. ",
  "mn42:16-17.1": "Này các gia chủ, nếu người hành thiện, hành đúng đắn mong muốn: ",
  "mn42:16-17.2": "‘mong sao sau khi thân hoại mạng chung, tôi được đồng hành với các đại gia tộc Bà la môn …pe… ",
  "mn42:16-17.3": "các đại gia tộc gia chủ’; ",
  "mn42:16-17.4": "điều đó có thể xảy ra, người ấy sau khi thân hoại mạng chung, có thể được đồng hành với các đại gia tộc gia chủ. ",
  "mn42:16-17.5": "Vì sao vậy? ",
  "mn42:16-17.6": "Vì người ấy hành thiện, hành đúng đắn. ",
  "mn42:18-42.1": "Này các gia chủ, nếu người hành thiện, hành đúng đắn mong muốn: ",
  "mn42:18-42.2": "‘mong sao sau khi thân hoại mạng chung, tôi được đồng hành với chư thiên Tứ Đại Thiên Vương’; ",
  "mn42:18-42.3": "điều đó có thể xảy ra, người ấy sau khi thân hoại mạng chung, có thể được đồng hành với chư thiên Tứ Đại Thiên Vương. ",
  "mn42:18-42.4": "Vì sao vậy? ",
  "mn42:18-42.5": "Vì người ấy hành thiện, hành đúng đắn. ",
  "mn42:18-42.6": "Này các gia chủ, nếu người hành thiện, hành đúng đắn mong muốn: ",
  "mn42:18-42.7": "‘mong sao sau khi thân hoại mạng chung, tôi được đồng hành với chư thiên Đao Lợi … ",
  "mn42:18-42.8": "chư thiên Dạ Ma … ",
  "mn42:18-42.9": "chư thiên Đâu Suất … ",
  "mn42:18-42.10": "chư thiên Hóa Lạc … ",
  "mn42:18-42.11": "chư thiên Tha Hóa Tự Tại … ",
  "mn42:18-42.12": "chư thiên Phạm Chúng’; ",
  "mn42:18-42.13": "điều đó có thể xảy ra, người ấy sau khi thân hoại mạng chung, có thể được đồng hành với chư thiên Phạm Chúng. ",
  "mn42:18-42.14": "Vì sao vậy? ",
  "mn42:18-42.15": "Vì người ấy hành thiện, hành đúng đắn. ",
  "mn42:18-42.16": "Này các gia chủ, nếu người hành thiện, hành đúng đắn mong muốn: ",
  "mn42:18-42.17": "‘mong sao sau khi thân hoại mạng chung, tôi được đồng hành với chư thiên Quang Âm’; ",
  "mn42:18-42.18": "điều đó có thể xảy ra, người ấy sau khi thân hoại mạng chung, có thể được đồng hành với chư thiên Quang Âm. ",
  "mn42:18-42.19": "Vì sao vậy? ",
  "mn42:18-42.20": "Vì người ấy hành thiện, hành đúng đắn. ",
  "mn42:18-42.21": "Này các gia chủ, nếu người hành thiện, hành đúng đắn mong muốn: ",
  "mn42:18-42.22": "‘mong sao sau khi thân hoại mạng chung, tôi được đồng hành với chư thiên Thiểu Quang …pe… ",
  "mn42:18-42.23": "chư thiên Vô Lượng Quang … ",
  "mn42:18-42.24": "chư thiên Quang Âm … ",
  "mn42:18-42.25": "chư thiên Thiểu Tịnh … ",
  "mn42:18-42.26": "chư thiên Vô Lượng Tịnh … ",
  "mn42:18-42.27": "chư thiên Biến Tịnh … ",
  "mn42:18-42.28": "chư thiên Quảng Quả … ",
  "mn42:18-42.29": "chư thiên Vô Phiền … ",
  "mn42:18-42.30": "chư thiên Vô Nhiệt … ",
  "mn42:18-42.31": "chư thiên Thiện Hiện … ",
  "mn42:18-42.32": "chư thiên Thiện Kiến … ",
  "mn42:18-42.33": "chư thiên Sắc Cứu Cánh … ",
  "mn42:18-42.34": "chư thiên Không Vô Biên Xứ … ",
  "mn42:18-42.35": "chư thiên Thức Vô Biên Xứ … ",
  "mn42:18-42.36": "chư thiên Vô Sở Hữu Xứ … ",
  "mn42:18-42.37": "chư thiên Phi Tưởng Phi Phi Tưởng Xứ’; ",
  "mn42:18-42.38": "điều đó có thể xảy ra, người ấy sau khi thân hoại mạng chung, có thể được đồng hành với chư thiên Phi Tưởng Phi Phi Tưởng Xứ. ",
  "mn42:18-42.39": "Vì sao vậy? ",
  "mn42:18-42.40": "Vì người ấy hành thiện, hành đúng đắn. ",
  "mn42:43.1": "Này các gia chủ, nếu người hành thiện, hành đúng đắn mong muốn: ",
  "mn42:43.2": "‘mong sao tôi, do sự diệt trừ các lậu hoặc, tự mình chứng ngộ, làm chứng và an trú trong giải thoát tâm vô lậu, giải thoát tuệ vô lậu ngay trong hiện tại’; ",
  "mn42:43.3": "điều đó có thể xảy ra, người ấy, do sự diệt trừ các lậu hoặc, tự mình chứng ngộ, làm chứng và an trú trong giải thoát tâm vô lậu, giải thoát tuệ vô lậu ngay trong hiện tại. ",
  "mn42:43.4": "Vì sao vậy? ",
  "mn42:43.5": "Vì người ấy hành thiện, hành đúng đắn.’” ",
  "mn42:44.1": "Khi được nói như vậy, các gia chủ Bà la môn Verañja bạch Thế Tôn rằng: ",
  "mn42:44.2": "“Tuyệt vời thay, thưa Tôn giả Gotama! Tuyệt vời thay, thưa Tôn giả Gotama! ",
  "mn42:44.3": "Ví như, thưa Tôn giả Gotama, người ta dựng đứng cái bị lật úp, mở ra cái bị che kín, chỉ đường cho người lạc lối, hoặc cầm đèn trong bóng tối để những người có mắt có thể thấy sắc; cũng vậy, Tôn giả Gotama đã thuyết pháp bằng nhiều cách khác nhau. ",
  "mn42:44.4": "Chúng tôi xin quy y Tôn giả Gotama, quy y Pháp và quy y Tăng chúng. ",
  "mn42:44.5": "Xin Đức Gotama hãy ghi nhận chúng con là cư sĩ đã quy y trọn đời, từ nay trở đi.",
  "mn42:44.6": "Kinh Verañja chấm dứt, bài thứ hai."
}
window.BILARA["mn42"]["vi"]["mn42:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
