window.BILARA = window.BILARA || {};
window.BILARA["mn45"] = window.BILARA["mn45"] || {};
window.BILARA["mn45"]["vi"] = {
  "mn45:0.1": "Trung Bộ Kinh 45 ",
  "mn45:0.2": "Tiểu Kinh Thực Hành Pháp ",
  "mn45:1.1": "Tôi nghe như vầy—",
  "mn45:1.2": "Một thời, Thế Tôn trú ở Sāvatthī, tại Jetavana, khu vườn của Anāthapiṇḍika. ",
  "mn45:1.3": "Tại đấy, Thế Tôn gọi các Tỳ-kheo: ",
  "mn45:1.4": "“Này các Tỳ-kheo”. ",
  "mn45:1.5": "“Bạch Thế Tôn”, các Tỳ-kheo ấy vâng đáp Thế Tôn. ",
  "mn45:1.6": "Thế Tôn nói như sau: ",
  "mn45:2.1": "“Này các Tỳ-kheo, có bốn sự thực hành pháp này. ",
  "mn45:2.2": "Thế nào là bốn? ",
  "mn45:2.3": "Này các Tỳ-kheo, có sự thực hành pháp hiện tại an lạc, tương lai khổ báo; ",
  "mn45:2.4": "này các Tỳ-kheo, có sự thực hành pháp hiện tại khổ, tương lai khổ báo; ",
  "mn45:2.5": "này các Tỳ-kheo, có sự thực hành pháp hiện tại khổ, tương lai lạc báo; ",
  "mn45:2.6": "này các Tỳ-kheo, có sự thực hành pháp hiện tại an lạc, tương lai lạc báo. ",
  "mn45:3.1": "Và này các Tỳ-kheo, thế nào là sự thực hành pháp hiện tại an lạc, tương lai khổ báo? ",
  "mn45:3.2": "Này các Tỳ-kheo, có một số Sa-môn, Bà-la-môn có lời nói như vầy, có quan điểm như vầy: ",
  "mn45:3.3": "‘Không có lỗi lầm trong các dục’. ",
  "mn45:3.4": "Họ chìm đắm trong các dục. ",
  "mn45:3.5": "Họ được các nữ du sĩ búi tóc phục vụ. ",
  "mn45:3.6": "Họ nói như sau: ",
  "mn45:3.7": "‘Những vị Sa-môn, Bà-la-môn ấy thấy sự nguy hiểm trong tương lai của các dục mà nói đến sự từ bỏ các dục, mà thuyết giảng sự liễu tri các dục là gì? ",
  "mn45:3.8": "Sự xúc chạm của cánh tay mềm mại, non tơ, có lông của nữ du sĩ này thật là an lạc’. Rồi họ chìm đắm trong các dục. ",
  "mn45:3.9": "Họ chìm đắm trong các dục, sau khi thân hoại mạng chung, sanh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn45:3.10": "Tại đấy, họ cảm thọ những cảm giác khổ đau, mãnh liệt, gay gắt, khốc liệt. ",
  "mn45:3.11": "Họ nói như sau: ",
  "mn45:3.12": "‘Chính đây là sự nguy hiểm trong tương lai của các dục mà những vị Sa-môn, Bà-la-môn ấy đã thấy mà nói đến sự từ bỏ các dục, mà thuyết giảng sự liễu tri các dục. Chính vì các dục, vì duyên các dục mà chúng ta cảm thọ những cảm giác khổ đau, mãnh liệt, gay gắt, khốc liệt này’. ",
  "mn45:4.1": "Ví như, này các Tỳ-kheo, vào tháng cuối mùa hè, một hạt dây leo mālūvā nứt ra. ",
  "mn45:4.2": "Rồi này các Tỳ-kheo, hạt dây leo mālūvā ấy rơi xuống gốc cây sāla nào đó. ",
  "mn45:4.3": "Rồi này các Tỳ-kheo, vị thiên thần trú ở cây sāla ấy sợ hãi, kinh hoàng, hoảng sợ. ",
  "mn45:4.4": "Rồi này các Tỳ-kheo, bạn bè, thân quyến, bà con huyết thống của vị thiên thần trú ở cây sāla ấy, các thiên thần trú ở vườn, các thiên thần trú ở rừng, các thiên thần trú ở cây, các thiên thần trú ở cây cỏ, thảo mộc, tụ họp lại, tập trung lại và an ủi như sau: ",
  "mn45:4.5": "‘Xin ngài đừng sợ, xin ngài đừng sợ; ",
  "mn45:4.6": "có lẽ hạt dây leo mālūvā này sẽ bị con công nuốt, hoặc con nai ăn, hoặc bị cháy rừng thiêu rụi, hoặc bị người làm rừng nhổ đi, hoặc bị kiến mối đào lên, hoặc nó không có mầm sống’. ",
  "mn45:4.7": "Rồi này các Tỳ-kheo, hạt dây leo mālūvā ấy không bị con công nuốt, không bị con nai ăn, không bị cháy rừng thiêu rụi, không bị người làm rừng nhổ đi, không bị kiến mối đào lên, và nó có mầm sống, được mưa mùa mưa tưới tẩm, nó mọc lên rất tốt. ",
  "mn45:4.8": "Dây leo mālūvā ấy non tơ, mềm mại, có lông, buông rủ, nó bám vào cây sāla ấy. ",
  "mn45:4.9": "Rồi này các Tỳ-kheo, vị thiên thần trú ở cây sāla ấy nghĩ như sau: ",
  "mn45:4.10": "‘Những vị bạn bè, thân quyến, bà con huyết thống của ta, các thiên thần trú ở vườn, các thiên thần trú ở rừng, các thiên thần trú ở cây, các thiên thần trú ở cây cỏ, thảo mộc, đã thấy sự nguy hiểm trong tương lai của hạt dây leo mālūvā mà tụ họp lại, tập trung lại và an ủi ta như sau là gì: ",
  "mn45:4.11": "“Xin ngài đừng sợ, xin ngài đừng sợ, ",
  "mn45:4.12": "có lẽ hạt dây leo mālūvā này sẽ bị con công nuốt, hoặc con nai ăn, hoặc bị cháy rừng thiêu rụi, hoặc bị người làm rừng nhổ đi, hoặc bị kiến mối đào lên, hoặc nó không có mầm sống” ư? ",
  "mn45:4.13": "Sự xúc chạm của dây leo mālūvā non tơ, mềm mại, có lông, buông rủ này thật là an lạc’. ",
  "mn45:4.14": "Nó quấn quanh cây sāla ấy. ",
  "mn45:4.15": "Nó quấn quanh cây sāla ấy, rồi tạo ra một tán lá phía trên. ",
  "mn45:4.16": "Tạo ra một tán lá phía trên, rồi tạo ra một sự che phủ dày đặc. ",
  "mn45:4.17": "Tạo ra một sự che phủ dày đặc, rồi nó làm nứt những thân cây sāla lớn của cây sāla ấy. ",
  "mn45:4.18": "Rồi này các Tỳ-kheo, vị thiên thần trú ở cây sāla ấy nghĩ như sau: ",
  "mn45:4.19": "‘Chính đây là sự nguy hiểm trong tương lai của hạt dây leo mālūvā mà những vị bạn bè, thân quyến, bà con huyết thống của ta, các thiên thần trú ở vườn, các thiên thần trú ở rừng, các thiên thần trú ở cây, các thiên thần trú ở cây cỏ, thảo mộc, đã thấy mà tụ họp lại, tập trung lại và an ủi ta như sau: ",
  "mn45:4.20": "“Xin ngài đừng sợ, xin ngài đừng sợ, có lẽ hạt dây leo mālūvā này sẽ bị con công nuốt, hoặc con nai ăn, hoặc bị cháy rừng thiêu rụi, hoặc bị người làm rừng nhổ đi, hoặc bị kiến mối đào lên, hoặc nó không có mầm sống” ư? ",
  "mn45:4.21": "Và chính vì hạt dây leo mālūvā mà ta cảm thọ những cảm giác khổ đau, mãnh liệt, gay gắt, khốc liệt này’. ",
  "mn45:4.22": "Cũng vậy, này các Tỳ-kheo, có một số Sa-môn, Bà-la-môn có lời nói như vầy, có quan điểm như vầy: ‘Không có lỗi lầm trong các dục’. ",
  "mn45:4.23": "Họ chìm đắm trong các dục. ",
  "mn45:4.24": "Họ được các nữ du sĩ búi tóc phục vụ. ",
  "mn45:4.25": "Họ nói như sau: ",
  "mn45:4.26": "‘Những vị Sa-môn, Bà-la-môn ấy thấy sự nguy hiểm trong tương lai của các dục mà nói đến sự từ bỏ các dục, mà thuyết giảng sự liễu tri các dục là gì? ",
  "mn45:4.27": "Sự xúc chạm của cánh tay mềm mại, non tơ, có lông của nữ du sĩ này thật là an lạc’. ",
  "mn45:4.28": "Họ chìm đắm trong các dục. ",
  "mn45:4.29": "Họ chìm đắm trong các dục, sau khi thân hoại mạng chung, sanh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn45:4.30": "Tại đấy, họ cảm thọ những cảm giác khổ đau, mãnh liệt, gay gắt, khốc liệt. ",
  "mn45:4.31": "Họ nói như sau: ",
  "mn45:4.32": "‘Chính đây là sự nguy hiểm trong tương lai của các dục mà những vị Sa-môn, Bà-la-môn ấy đã thấy mà nói đến sự từ bỏ các dục, mà thuyết giảng sự liễu tri các dục. ",
  "mn45:4.33": "Chính vì các dục, vì duyên các dục mà chúng ta cảm thọ những cảm giác khổ đau, mãnh liệt, gay gắt, khốc liệt này’. ",
  "mn45:4.34": "Này các Tỳ-kheo, đây được gọi là sự thực hành pháp hiện tại an lạc, tương lai khổ báo. ",
  "mn45:5.1": "Và này các Tỳ-kheo, thế nào là sự thực hành pháp hiện tại khổ, tương lai khổ báo? ",
  "mn45:5.2": "Ở đây, này các Tỳ-kheo, có người khỏa thân, sống phóng túng, liếm tay, không đến khi được mời, không đứng khi được mời, không nhận thức ăn mang đến, không nhận thức ăn dành riêng, không nhận thức ăn được mời, ",
  "mn45:5.3": "người ấy không nhận thức ăn từ miệng nồi, không nhận thức ăn từ miệng bát, không nhận thức ăn giữa hai con dê, không nhận thức ăn giữa hai cây gậy, không nhận thức ăn giữa hai cái chày, không nhận thức ăn từ hai người đang ăn, không nhận thức ăn từ người phụ nữ có thai, không nhận thức ăn từ người phụ nữ đang cho con bú, không nhận thức ăn từ người phụ nữ đang ở giữa hai người đàn ông, không nhận thức ăn từ nơi có chó đang tụ tập, không nhận thức ăn từ nơi có ruồi đang bay vo ve, không ăn cá, không ăn thịt, không uống rượu, không uống rượu mạnh, không uống nước gạo. ",
  "mn45:5.4": "Người ấy chỉ ăn một nhà, chỉ ăn một nắm; hoặc ăn hai nhà, chỉ ăn hai nắm… hoặc ăn bảy nhà, chỉ ăn bảy nắm. ",
  "mn45:5.5": "Người ấy sống với một lần bố thí, sống với hai lần bố thí… sống với bảy lần bố thí. ",
  "mn45:5.6": "Người ấy ăn một ngày một bữa, ăn hai ngày một bữa… ăn bảy ngày một bữa. Cứ như vậy, người ấy sống chuyên cần thực hành ăn uống theo chu kỳ nửa tháng. ",
  "mn45:5.7": "Người ấy ăn rau, hoặc ăn kê, hoặc ăn lúa hoang, hoặc ăn cám, hoặc ăn bã gạo, hoặc ăn bột cám, hoặc ăn nước cháo, hoặc ăn bột đậu, hoặc ăn cỏ, hoặc ăn phân bò, sống bằng rễ cây và trái cây rừng, ăn trái cây rụng. ",
  "mn45:5.8": "Người ấy mặc vải gai, hoặc vải thô, hoặc vải liệm, hoặc y phấn tảo, hoặc vỏ cây, hoặc da cọp, hoặc mảnh da cọp, hoặc y bằng cỏ, hoặc y bằng vỏ cây, hoặc y bằng ván cây, hoặc chăn bằng tóc, hoặc chăn bằng lông thú, hoặc cánh cú. ",
  "mn45:5.9": "Người ấy nhổ tóc và râu, sống chuyên cần nhổ tóc và râu. ",
  "mn45:5.10": "Người ấy đứng thẳng, từ chối chỗ ngồi. ",
  "mn45:5.11": "Người ấy ngồi xổm, sống chuyên cần ngồi xổm. ",
  "mn45:5.12": "Người ấy nằm trên giường gai, nằm trên giường gai. ",
  "mn45:5.13": "Người ấy sống chuyên cần tắm nước ba lần vào buổi chiều. ",
  "mn45:5.14": "Cứ như vậy, người ấy sống chuyên cần thực hành nhiều cách hành hạ thân thể, làm cho thân thể nóng bức và đau đớn. ",
  "mn45:5.15": "Sau khi thân hoại mạng chung, người ấy sanh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn45:5.16": "Này các Tỳ-kheo, đây được gọi là sự thực hành pháp hiện tại khổ, tương lai khổ báo. ",
  "mn45:6.1": "Và này các Tỳ-kheo, thế nào là sự thực hành pháp hiện tại khổ, tương lai lạc báo? ",
  "mn45:6.2": "Ở đây, này các Tỳ-kheo, có người tự nhiên sanh ra với tham dục mãnh liệt, người ấy thường xuyên cảm thọ khổ và ưu do tham dục sanh ra; ",
  "mn45:6.3": "tự nhiên sanh ra với sân hận mãnh liệt, người ấy thường xuyên cảm thọ khổ và ưu do sân hận sanh ra; ",
  "mn45:6.4": "tự nhiên sanh ra với si mê mãnh liệt, người ấy thường xuyên cảm thọ khổ và ưu do si mê sanh ra. ",
  "mn45:6.5": "Người ấy, dù với khổ, dù với ưu, mặt đẫm lệ, khóc lóc, vẫn sống phạm hạnh hoàn toàn thanh tịnh. ",
  "mn45:6.6": "Sau khi thân hoại mạng chung, người ấy sanh vào thiện thú, cõi trời. ",
  "mn45:6.7": "Này các Tỳ-kheo, đây được gọi là sự thực hành pháp hiện tại khổ, tương lai lạc báo. ",
  "mn45:7.1": "Và này các Tỳ-kheo, thế nào là sự thực hành pháp hiện tại an lạc, tương lai lạc báo? ",
  "mn45:7.2": "Ở đây, này các Tỳ-kheo, có người tự nhiên không sanh ra với tham dục mãnh liệt, người ấy không thường xuyên cảm thọ khổ và ưu do tham dục sanh ra; ",
  "mn45:7.3": "tự nhiên không sanh ra với sân hận mãnh liệt, người ấy không thường xuyên cảm thọ khổ và ưu do sân hận sanh ra; ",
  "mn45:7.4": "tự nhiên không sanh ra với si mê mãnh liệt, người ấy không thường xuyên cảm thọ khổ và ưu do si mê sanh ra. ",
  "mn45:7.5": "Người ấy, ly dục, ly bất thiện pháp, chứng và trú Thiền thứ nhất, có tầm, có tứ, có hỷ lạc do ly dục sanh. ",
  "mn45:7.6": "Diệt tầm và tứ, nội tĩnh nhất tâm, chứng và trú Thiền thứ hai, không tầm, không tứ, có hỷ lạc do định sanh… ",
  "mn45:7.7": "Thiền thứ ba… ",
  "mn45:7.8": "chứng và trú Thiền thứ tư. ",
  "mn45:7.9": "Sau khi thân hoại mạng chung, người ấy sanh vào thiện thú, cõi trời. ",
  "mn45:7.10": "Này các Tỳ-kheo, đây được gọi là sự thực hành pháp hiện tại an lạc, tương lai lạc báo. ",
  "mn45:7.11": "Này các Tỳ-kheo, đây là bốn sự thực hành pháp này”. ",
  "mn45:7.12": "Thế Tôn đã nói như vậy. ",
  "mn45:7.13": "Các Tỳ-kheo ấy hoan hỷ, tùy hỷ lời Thế Tôn dạy. ",
  "mn45:7.14": "Tiểu Kinh Thực Hành Pháp, thứ năm, chấm dứt. "
}
window.BILARA["mn45"]["vi"]["mn45:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
