window.BILARA = window.BILARA || {};
window.BILARA["mn46"] = window.BILARA["mn46"] || {};
window.BILARA["mn46"]["vi"] = {
  "mn46:0.1": "Trung Bộ Kinh 46 ",
  "mn46:0.2": "Kinh Đại Pháp Thọ Trì ",
  "mn46:1.1": "Như vầy tôi nghe—",
  "mn46:1.2": "Một thời, Thế Tôn trú ở Sāvatthī, tại Jetavana, khu vườn của Anāthapiṇḍika. ",
  "mn46:1.3": "Rồi Thế Tôn gọi các Tỳ-kheo: ",
  "mn46:1.4": "“Này các Tỳ-kheo!” ",
  "mn46:1.5": "“Bạch Thế Tôn”, các Tỳ-kheo ấy vâng đáp Thế Tôn. ",
  "mn46:1.6": "Thế Tôn nói như sau: ",
  "mn46:2.1": "“Này các Tỳ-kheo, phần lớn chúng sinh có ước muốn như vầy, có ý muốn như vầy, có chủ ý như vầy: ",
  "mn46:2.2": "‘Ôi, ước gì những pháp không mong muốn, không ưa thích, không vừa ý sẽ suy giảm; ước gì những pháp mong muốn, ưa thích, vừa ý sẽ tăng trưởng!’ ",
  "mn46:2.3": "Nhưng này các Tỳ-kheo, đối với những chúng sinh có ước muốn như vầy, có ý muốn như vầy, có chủ ý như vầy, thì những pháp không mong muốn, không ưa thích, không vừa ý lại tăng trưởng; những pháp mong muốn, ưa thích, vừa ý lại suy giảm. ",
  "mn46:2.4": "Này các Tỳ-kheo, các ông nghĩ nguyên nhân nào cho điều đó?” ",
  "mn46:2.5": "“Bạch Thế Tôn, các pháp của chúng con có gốc rễ từ Thế Tôn, có người hướng dẫn là Thế Tôn, có nơi nương tựa là Thế Tôn. Lành thay, bạch Thế Tôn, nếu Thế Tôn tự mình giải thích ý nghĩa của lời nói này; sau khi nghe Thế Tôn, các Tỳ-kheo sẽ ghi nhớ.” ",
  "mn46:2.6": "“Vậy thì này các Tỳ-kheo, hãy lắng nghe, hãy khéo tác ý, Ta sẽ nói.” ",
  "mn46:2.7": "“Vâng, bạch Thế Tôn”, các Tỳ-kheo ấy vâng đáp Thế Tôn. ",
  "mn46:2.8": "Thế Tôn nói như sau: ",
  "mn46:3.1": "“Này các Tỳ-kheo, ở đây, một phàm phu không được nghe giáo pháp, không thấy các bậc Thánh, không thông thạo pháp của các bậc Thánh, không được huấn luyện trong pháp của các bậc Thánh; không thấy các bậc chân nhân, không thông thạo pháp của các bậc chân nhân, không được huấn luyện trong pháp của các bậc chân nhân, ",
  "mn46:3.2": "không biết những pháp nên thực hành, không biết những pháp không nên thực hành; không biết những pháp nên thân cận, không biết những pháp không nên thân cận. ",
  "mn46:3.3": "Người ấy, vì không biết những pháp nên thực hành, không biết những pháp không nên thực hành; không biết những pháp nên thân cận, không biết những pháp không nên thân cận, nên thực hành những pháp không nên thực hành, không thực hành những pháp nên thực hành; thân cận những pháp không nên thân cận, không thân cận những pháp nên thân cận. ",
  "mn46:3.4": "Đối với người ấy, vì thực hành những pháp không nên thực hành, không thực hành những pháp nên thực hành; thân cận những pháp không nên thân cận, không thân cận những pháp nên thân cận, nên những pháp không mong muốn, không ưa thích, không vừa ý tăng trưởng; những pháp mong muốn, ưa thích, vừa ý suy giảm. ",
  "mn46:3.5": "Vì sao vậy? ",
  "mn46:3.6": "Này các Tỳ-kheo, đó là vì người không có trí tuệ. ",
  "mn46:4.1": "Còn này các Tỳ-kheo, một Thánh đệ tử được nghe giáo pháp, thấy các bậc Thánh, thông thạo pháp của các bậc Thánh, được huấn luyện khéo léo trong pháp của các bậc Thánh; thấy các bậc chân nhân, thông thạo pháp của các bậc chân nhân, được huấn luyện khéo léo trong pháp của các bậc chân nhân, ",
  "mn46:4.2": "biết những pháp nên thực hành, biết những pháp không nên thực hành; biết những pháp nên thân cận, biết những pháp không nên thân cận. ",
  "mn46:4.3": "Người ấy, vì biết những pháp nên thực hành, biết những pháp không nên thực hành; biết những pháp nên thân cận, biết những pháp không nên thân cận, nên không thực hành những pháp không nên thực hành, thực hành những pháp nên thực hành; không thân cận những pháp không nên thân cận, thân cận những pháp nên thân cận. ",
  "mn46:4.4": "Đối với người ấy, vì không thực hành những pháp không nên thực hành, thực hành những pháp nên thực hành; không thân cận những pháp không nên thân cận, thân cận những pháp nên thân cận, nên những pháp không mong muốn, không ưa thích, không vừa ý suy giảm; những pháp mong muốn, ưa thích, vừa ý tăng trưởng. ",
  "mn46:4.5": "Vì sao vậy? ",
  "mn46:4.6": "Này các Tỳ-kheo, đó là vì người có trí tuệ. ",
  "mn46:5.1": "Này các Tỳ-kheo, có bốn pháp thọ trì này. ",
  "mn46:5.2": "Thế nào là bốn? ",
  "mn46:5.3": "Này các Tỳ-kheo, có pháp thọ trì hiện tại khổ và tương lai quả khổ; ",
  "mn46:5.4": "có pháp thọ trì hiện tại lạc và tương lai quả khổ; ",
  "mn46:5.5": "có pháp thọ trì hiện tại khổ và tương lai quả lạc; ",
  "mn46:5.6": "có pháp thọ trì hiện tại lạc và tương lai quả lạc. ",
  "mn46:6.1": "Này các Tỳ-kheo, ở đây, pháp thọ trì nào hiện tại khổ và tương lai quả khổ, người không có trí tuệ, bị vô minh che lấp, không như thật biết: ",
  "mn46:6.2": "‘Đây là pháp thọ trì hiện tại khổ và tương lai quả khổ.’ ",
  "mn46:6.3": "Người ấy, vì không có trí tuệ, bị vô minh che lấp, không như thật biết, nên thực hành pháp ấy, không tránh xa pháp ấy. ",
  "mn46:6.4": "Đối với người ấy, vì thực hành pháp ấy, không tránh xa pháp ấy, nên những pháp không mong muốn, không ưa thích, không vừa ý tăng trưởng; những pháp mong muốn, ưa thích, vừa ý suy giảm. ",
  "mn46:6.5": "Vì sao vậy? ",
  "mn46:6.6": "Này các Tỳ-kheo, đó là vì người không có trí tuệ. ",
  "mn46:7.1": "Này các Tỳ-kheo, ở đây, pháp thọ trì nào hiện tại lạc và tương lai quả khổ, người không có trí tuệ, bị vô minh che lấp, không như thật biết: ",
  "mn46:7.2": "‘Đây là pháp thọ trì hiện tại lạc và tương lai quả khổ.’ ",
  "mn46:7.3": "Người ấy, vì không có trí tuệ, bị vô minh che lấp, không như thật biết, nên thực hành pháp ấy, không tránh xa pháp ấy. ",
  "mn46:7.4": "Đối với người ấy, vì thực hành pháp ấy, không tránh xa pháp ấy, nên những pháp không mong muốn, không ưa thích, không vừa ý tăng trưởng; những pháp mong muốn, ưa thích, vừa ý suy giảm. ",
  "mn46:7.5": "Vì sao vậy? ",
  "mn46:7.6": "Này các Tỳ-kheo, đó là vì người không có trí tuệ. ",
  "mn46:8.1": "Này các Tỳ-kheo, ở đây, pháp thọ trì nào hiện tại khổ và tương lai quả lạc, người không có trí tuệ, bị vô minh che lấp, không như thật biết: ",
  "mn46:8.2": "‘Đây là pháp thọ trì hiện tại khổ và tương lai quả lạc.’ ",
  "mn46:8.3": "Người ấy, vì không có trí tuệ, bị vô minh che lấp, không như thật biết, nên không thực hành pháp ấy, tránh xa pháp ấy. ",
  "mn46:8.4": "Đối với người ấy, vì không thực hành pháp ấy, tránh xa pháp ấy, nên những pháp không mong muốn, không ưa thích, không vừa ý tăng trưởng; những pháp mong muốn, ưa thích, vừa ý suy giảm. ",
  "mn46:8.5": "Vì sao vậy? ",
  "mn46:8.6": "Này các Tỳ-kheo, đó là vì người không có trí tuệ. ",
  "mn46:9.1": "Này các Tỳ-kheo, ở đây, pháp thọ trì nào hiện tại lạc và tương lai quả lạc, người không có trí tuệ, bị vô minh che lấp, không như thật biết: ",
  "mn46:9.2": "‘Đây là pháp thọ trì hiện tại lạc và tương lai quả lạc.’ ",
  "mn46:9.3": "Người ấy, vì không có trí tuệ, bị vô minh che lấp, không như thật biết, nên không thực hành pháp ấy, tránh xa pháp ấy. ",
  "mn46:9.4": "Đối với người ấy, vì không thực hành pháp ấy, tránh xa pháp ấy, nên những pháp không mong muốn, không ưa thích, không vừa ý tăng trưởng; những pháp mong muốn, ưa thích, vừa ý suy giảm. ",
  "mn46:9.5": "Vì sao vậy? ",
  "mn46:9.6": "Này các Tỳ-kheo, đó là vì người không có trí tuệ. ",
  "mn46:10.1": "Này các Tỳ-kheo, ở đây, pháp thọ trì nào hiện tại khổ và tương lai quả khổ, người có trí tuệ, có minh, như thật biết: ",
  "mn46:10.2": "‘Đây là pháp thọ trì hiện tại khổ và tương lai quả khổ.’ ",
  "mn46:10.3": "Người ấy, vì có trí tuệ, có minh, như thật biết, nên không thực hành pháp ấy, tránh xa pháp ấy. ",
  "mn46:10.4": "Đối với người ấy, vì không thực hành pháp ấy, tránh xa pháp ấy, nên những pháp không mong muốn, không ưa thích, không vừa ý suy giảm; những pháp mong muốn, ưa thích, vừa ý tăng trưởng. ",
  "mn46:10.5": "Vì sao vậy? ",
  "mn46:10.6": "Này các Tỳ-kheo, đó là vì người có trí tuệ. ",
  "mn46:11.1": "Này các Tỳ-kheo, ở đây, pháp thọ trì nào hiện tại lạc và tương lai quả khổ, người có trí tuệ, có minh, như thật biết: ",
  "mn46:11.2": "‘Đây là pháp thọ trì hiện tại lạc và tương lai quả khổ.’ ",
  "mn46:11.3": "Người ấy, vì có trí tuệ, có minh, như thật biết, nên không thực hành pháp ấy, tránh xa pháp ấy. ",
  "mn46:11.4": "Đối với người ấy, vì không thực hành pháp ấy, tránh xa pháp ấy, nên những pháp không mong muốn, không ưa thích, không vừa ý suy giảm; những pháp mong muốn, ưa thích, vừa ý tăng trưởng. ",
  "mn46:11.5": "Vì sao vậy? ",
  "mn46:11.6": "Này các Tỳ-kheo, đó là vì người có trí tuệ. ",
  "mn46:12.1": "Này các Tỳ-kheo, ở đây, pháp thọ trì nào hiện tại khổ và tương lai quả lạc, người có trí tuệ, có minh, như thật biết: ",
  "mn46:12.2": "‘Đây là pháp thọ trì hiện tại khổ và tương lai quả lạc.’ ",
  "mn46:12.3": "Người ấy, vì có trí tuệ, có minh, như thật biết, nên thực hành pháp ấy, không tránh xa pháp ấy. ",
  "mn46:12.4": "Đối với người ấy, vì thực hành pháp ấy, không tránh xa pháp ấy, nên những pháp không mong muốn, không ưa thích, không vừa ý suy giảm; những pháp mong muốn, ưa thích, vừa ý tăng trưởng. ",
  "mn46:12.5": "Vì sao vậy? ",
  "mn46:12.6": "Này các Tỳ-kheo, đó là vì người có trí tuệ. ",
  "mn46:13.1": "Này các Tỳ-kheo, ở đây, pháp thọ trì nào hiện tại lạc và tương lai quả lạc, người có trí tuệ, có minh, như thật biết: ",
  "mn46:13.2": "‘Đây là pháp thọ trì hiện tại lạc và tương lai quả lạc.’ ",
  "mn46:13.3": "Người ấy, vì có trí tuệ, có minh, như thật biết, nên thực hành pháp ấy, không tránh xa pháp ấy. ",
  "mn46:13.4": "Đối với người ấy, vì thực hành pháp ấy, không tránh xa pháp ấy, nên những pháp không mong muốn, không ưa thích, không vừa ý suy giảm; những pháp mong muốn, ưa thích, vừa ý tăng trưởng. ",
  "mn46:13.5": "Vì sao vậy? ",
  "mn46:13.6": "Này các Tỳ-kheo, đó là vì người có trí tuệ. ",
  "mn46:14.1": "Và này các Tỳ-kheo, thế nào là pháp thọ trì hiện tại khổ và tương lai quả khổ? ",
  "mn46:14.2": "Này các Tỳ-kheo, ở đây, có người, dù với khổ, dù với ưu, vẫn sát sinh; do duyên sát sinh, người ấy cảm thọ khổ và ưu; ",
  "mn46:14.3": "dù với khổ, dù với ưu, vẫn trộm cắp; do duyên trộm cắp, người ấy cảm thọ khổ và ưu; ",
  "mn46:14.4": "dù với khổ, dù với ưu, vẫn tà dâm; do duyên tà dâm, người ấy cảm thọ khổ và ưu; ",
  "mn46:14.5": "dù với khổ, dù với ưu, vẫn nói dối; do duyên nói dối, người ấy cảm thọ khổ và ưu; ",
  "mn46:14.6": "dù với khổ, dù với ưu, vẫn nói lời đâm thọc; do duyên nói lời đâm thọc, người ấy cảm thọ khổ và ưu; ",
  "mn46:14.7": "dù với khổ, dù với ưu, vẫn nói lời thô ác; do duyên nói lời thô ác, người ấy cảm thọ khổ và ưu; ",
  "mn46:14.8": "dù với khổ, dù với ưu, vẫn nói lời vô ích; do duyên nói lời vô ích, người ấy cảm thọ khổ và ưu; ",
  "mn46:14.9": "dù với khổ, dù với ưu, vẫn tham lam; do duyên tham lam, người ấy cảm thọ khổ và ưu; ",
  "mn46:14.10": "dù với khổ, dù với ưu, vẫn có tâm sân hận; do duyên sân hận, người ấy cảm thọ khổ và ưu; ",
  "mn46:14.11": "dù với khổ, dù với ưu, vẫn có tà kiến; do duyên tà kiến, người ấy cảm thọ khổ và ưu. ",
  "mn46:14.12": "Người ấy, sau khi thân hoại mạng chung, sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn46:14.13": "Này các Tỳ-kheo, đây gọi là pháp thọ trì hiện tại khổ và tương lai quả khổ. ",
  "mn46:15.1": "Và này các Tỳ-kheo, thế nào là pháp thọ trì hiện tại lạc và tương lai quả khổ? ",
  "mn46:15.2": "Này các Tỳ-kheo, ở đây, có người, dù với lạc, dù với hỷ, vẫn sát sinh; do duyên sát sinh, người ấy cảm thọ lạc và hỷ; ",
  "mn46:15.3": "dù với lạc, dù với hỷ, vẫn trộm cắp; do duyên trộm cắp, người ấy cảm thọ lạc và hỷ; ",
  "mn46:15.4": "dù với lạc, dù với hỷ, vẫn tà dâm; do duyên tà dâm, người ấy cảm thọ lạc và hỷ; ",
  "mn46:15.5": "dù với lạc, dù với hỷ, vẫn nói dối; do duyên nói dối, người ấy cảm thọ lạc và hỷ; ",
  "mn46:15.6": "dù với lạc, dù với hỷ, vẫn nói lời đâm thọc; do duyên nói lời đâm thọc, người ấy cảm thọ lạc và hỷ; ",
  "mn46:15.7": "dù với lạc, dù với hỷ, vẫn nói lời thô ác; do duyên nói lời thô ác, người ấy cảm thọ lạc và hỷ; ",
  "mn46:15.8": "dù với lạc, dù với hỷ, vẫn nói lời vô ích; do duyên nói lời vô ích, người ấy cảm thọ lạc và hỷ; ",
  "mn46:15.9": "dù với lạc, dù với hỷ, vẫn tham lam; do duyên tham lam, người ấy cảm thọ lạc và hỷ; ",
  "mn46:15.10": "dù với lạc, dù với hỷ, vẫn có tâm sân hận; do duyên sân hận, người ấy cảm thọ lạc và hỷ; ",
  "mn46:15.11": "dù với lạc, dù với hỷ, vẫn có tà kiến; do duyên tà kiến, người ấy cảm thọ lạc và hỷ. ",
  "mn46:15.12": "Người ấy, sau khi thân hoại mạng chung, sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn46:15.13": "Này các Tỳ-kheo, đây gọi là pháp thọ trì hiện tại lạc và tương lai quả khổ. ",
  "mn46:16.1": "Và này các Tỳ-kheo, thế nào là pháp thọ trì hiện tại khổ và tương lai quả lạc? ",
  "mn46:16.2": "Này các Tỳ-kheo, ở đây, có người, dù với khổ, dù với ưu, vẫn từ bỏ sát sinh; do duyên từ bỏ sát sinh, người ấy cảm thọ khổ và ưu; ",
  "mn46:16.3": "dù với khổ, dù với ưu, vẫn từ bỏ trộm cắp; do duyên từ bỏ trộm cắp, người ấy cảm thọ khổ và ưu; ",
  "mn46:16.4": "dù với khổ, dù với ưu, vẫn từ bỏ tà dâm; do duyên từ bỏ tà dâm, người ấy cảm thọ khổ và ưu; ",
  "mn46:16.5": "dù với khổ, dù với ưu, vẫn từ bỏ nói dối; do duyên từ bỏ nói dối, người ấy cảm thọ khổ và ưu; ",
  "mn46:16.6": "dù với khổ, dù với ưu, vẫn từ bỏ lời đâm thọc; do duyên từ bỏ lời đâm thọc, người ấy cảm thọ khổ và ưu; ",
  "mn46:16.7": "dù với khổ, dù với ưu, vẫn từ bỏ lời thô ác; do duyên từ bỏ lời thô ác, người ấy cảm thọ khổ và ưu; ",
  "mn46:16.8": "dù với khổ, dù với ưu, vẫn từ bỏ lời vô ích; do duyên từ bỏ lời vô ích, người ấy cảm thọ khổ và ưu; ",
  "mn46:16.9": "dù với khổ, dù với ưu, vẫn không tham lam; do duyên không tham lam, người ấy cảm thọ khổ và ưu; ",
  "mn46:16.10": "dù với khổ, dù với ưu, vẫn không có tâm sân hận; do duyên không sân hận, người ấy cảm thọ khổ và ưu; ",
  "mn46:16.11": "dù với khổ, dù với ưu, vẫn có chánh kiến; do duyên chánh kiến, người ấy cảm thọ khổ và ưu. ",
  "mn46:16.12": "Người ấy, sau khi thân hoại mạng chung, sinh vào cõi lành, cảnh giới chư thiên. ",
  "mn46:16.13": "Này các Tỳ-kheo, đây gọi là sự chấp nhận giáo pháp hiện tại khổ, tương lai quả lạc. ",
  "mn46:17.1": "Và này các Tỳ-kheo, thế nào là sự chấp nhận giáo pháp hiện tại lạc và tương lai quả lạc? ",
  "mn46:17.2": "Ở đây, này các Tỳ-kheo, có người, dù với lạc, dù với hỷ, từ bỏ sát sinh, và do nhân từ bỏ sát sinh, người ấy cảm nhận lạc và hỷ; ",
  "mn46:17.3": "dù với lạc, dù với hỷ, từ bỏ lấy của không cho, và do nhân từ bỏ lấy của không cho, người ấy cảm nhận lạc và hỷ; ",
  "mn46:17.4": "dù với lạc, dù với hỷ, từ bỏ tà hạnh trong các dục, và do nhân từ bỏ tà hạnh trong các dục, người ấy cảm nhận lạc và hỷ; ",
  "mn46:17.5": "dù với lạc, dù với hỷ, từ bỏ nói dối, và do nhân từ bỏ nói dối, người ấy cảm nhận lạc và hỷ; ",
  "mn46:17.6": "dù với lạc, dù với hỷ, từ bỏ lời nói đâm thọc, và do nhân từ bỏ lời nói đâm thọc, người ấy cảm nhận lạc và hỷ; ",
  "mn46:17.7": "dù với lạc, dù với hỷ, từ bỏ lời nói thô tục, và do nhân từ bỏ lời nói thô tục, người ấy cảm nhận lạc và hỷ; ",
  "mn46:17.8": "dù với lạc, dù với hỷ, từ bỏ lời nói vô ích, và do nhân từ bỏ lời nói vô ích, người ấy cảm nhận lạc và hỷ; ",
  "mn46:17.9": "dù với lạc, dù với hỷ, không tham lam, và do nhân không tham lam, người ấy cảm nhận lạc và hỷ; ",
  "mn46:17.10": "dù với lạc, dù với hỷ, không có tâm sân hận, và do nhân không sân hận, người ấy cảm nhận lạc và hỷ; ",
  "mn46:17.11": "dù với lạc, dù với hỷ, có chánh kiến, và do nhân chánh kiến, người ấy cảm nhận lạc và hỷ. ",
  "mn46:17.12": "Người ấy, sau khi thân hoại mạng chung, sinh vào cõi thiện, cảnh trời. ",
  "mn46:17.13": "Này các Tỳ-kheo, đây gọi là sự chấp nhận giáo pháp hiện tại lạc và tương lai quả lạc. ",
  "mn46:17.14": "Này các Tỳ-kheo, đây là bốn sự chấp nhận giáo pháp. ",
  "mn46:18.1": "Này các Tỳ-kheo, ví như một quả bầu đắng trộn với thuốc độc. ",
  "mn46:18.2": "Rồi có người đến, muốn sống, không muốn chết, muốn lạc, ghét khổ. ",
  "mn46:18.3": "Họ nói với người ấy rằng: ",
  "mn46:18.4": "‘Này người kia, quả bầu đắng này trộn với thuốc độc, ",
  "mn46:18.5": "nếu muốn thì hãy uống. ",
  "mn46:18.6": "Khi uống, nó sẽ không làm ngươi vừa ý về màu sắc, mùi vị, và sau khi uống, ngươi sẽ chết hoặc chịu khổ gần chết.’ ",
  "mn46:18.7": "Người ấy không suy xét mà uống, không từ bỏ. ",
  "mn46:18.8": "Khi người ấy uống, nó không làm vừa ý về màu sắc, mùi vị, và sau khi uống, người ấy sẽ chết hoặc chịu khổ gần chết. ",
  "mn46:18.9": "Này các Tỳ-kheo, Ta nói sự chấp nhận giáo pháp này cũng ví như vậy, tức là sự chấp nhận giáo pháp hiện tại khổ và tương lai quả khổ. ",
  "mn46:19.1": "Này các Tỳ-kheo, ví như một chén nước uống có màu sắc đẹp, mùi thơm, vị ngon. ",
  "mn46:19.2": "Nhưng nó lại trộn với thuốc độc. ",
  "mn46:19.3": "Rồi có người đến, muốn sống, không muốn chết, muốn lạc, ghét khổ. ",
  "mn46:19.4": "Họ nói với người ấy rằng: ",
  "mn46:19.5": "‘Này người kia, chén nước uống này có màu sắc đẹp, mùi thơm, vị ngon. ",
  "mn46:19.6": "Nhưng nó lại trộn với thuốc độc, ",
  "mn46:19.7": "nếu muốn thì hãy uống. ",
  "mn46:19.8": "Khi uống, nó sẽ làm ngươi vừa ý về màu sắc, mùi vị, và sau khi uống, ngươi sẽ chết hoặc chịu khổ gần chết.’ ",
  "mn46:19.9": "Người ấy không suy xét mà uống, không từ bỏ. ",
  "mn46:19.10": "Khi người ấy uống, nó làm vừa ý về màu sắc, mùi vị, và sau khi uống, người ấy sẽ chết hoặc chịu khổ gần chết. ",
  "mn46:19.11": "Này các Tỳ-kheo, Ta nói sự chấp nhận giáo pháp này cũng ví như vậy, tức là sự chấp nhận giáo pháp hiện tại lạc, tương lai quả khổ. ",
  "mn46:20.1": "Này các Tỳ-kheo, ví như nước tiểu thối trộn với nhiều loại thuốc. ",
  "mn46:20.2": "Rồi có người đến, bị bệnh vàng da. ",
  "mn46:20.3": "Họ nói với người ấy rằng: ",
  "mn46:20.4": "‘Này người kia, nước tiểu thối này trộn với nhiều loại thuốc, nếu muốn thì hãy uống. ",
  "mn46:20.5": "Khi uống, nó sẽ không làm ngươi vừa ý về màu sắc, mùi vị, nhưng sau khi uống, ngươi sẽ được khỏe mạnh.’ ",
  "mn46:20.6": "Người ấy suy xét mà uống, không từ bỏ. ",
  "mn46:20.7": "Khi người ấy uống, nó không làm vừa ý về màu sắc, mùi vị, nhưng sau khi uống, người ấy được khỏe mạnh. ",
  "mn46:20.8": "Này các Tỳ-kheo, Ta nói sự chấp nhận giáo pháp này cũng ví như vậy, tức là sự chấp nhận giáo pháp hiện tại khổ, tương lai quả lạc. ",
  "mn46:21.1": "Này các Tỳ-kheo, ví như sữa đông, mật ong, bơ và đường thô trộn lẫn vào nhau. ",
  "mn46:21.2": "Rồi có người đến, bị bệnh kiết lỵ ra máu. ",
  "mn46:21.3": "Họ nói với người ấy rằng: ",
  "mn46:21.4": "‘Này người kia, sữa đông, mật ong, bơ và đường thô này trộn lẫn vào nhau, nếu muốn thì hãy uống. ",
  "mn46:21.5": "Khi uống, nó sẽ làm ngươi vừa ý về màu sắc, mùi vị, và sau khi uống, ngươi sẽ được khỏe mạnh.’ ",
  "mn46:21.6": "Người ấy suy xét mà uống, không từ bỏ. ",
  "mn46:21.7": "Khi người ấy uống, nó làm vừa ý về màu sắc, mùi vị, và sau khi uống, người ấy được khỏe mạnh. ",
  "mn46:21.8": "Này các Tỳ-kheo, Ta nói sự chấp nhận giáo pháp này cũng ví như vậy, tức là sự chấp nhận giáo pháp hiện tại lạc và tương lai quả lạc. ",
  "mn46:22.1": "Này các Tỳ-kheo, ví như vào tháng cuối mùa mưa, mùa thu, khi trời quang mây tạnh, mặt trời mọc lên giữa không trung, xua tan mọi bóng tối trong không gian, chiếu sáng, tỏa nhiệt và rực rỡ; ",
  "mn46:22.2": "cũng vậy, này các Tỳ-kheo, sự chấp nhận giáo pháp hiện tại lạc và tương lai quả lạc này, sau khi xua tan mọi giáo thuyết khác của các Sa-môn, Bà-la-môn khác, chiếu sáng, tỏa nhiệt và rực rỡ.” ",
  "mn46:22.3": "Thế Tôn đã nói như vậy. ",
  "mn46:22.4": "Các Tỳ-kheo hoan hỷ và tán thán lời Thế Tôn dạy. ",
  "mn46:22.5": "Đại Pháp Thọ Trì Kinh, thứ sáu, đã xong. "
}
window.BILARA["mn46"]["vi"]["mn46:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
