window.BILARA = window.BILARA || {};
window.BILARA["mn50"] = window.BILARA["mn50"] || {};
window.BILARA["mn50"]["vi"] = {
  "mn50:0.1": "Trung Bộ Kinh 50 ",
  "mn50:0.2": "Kinh Hăm Dọa Ma Vương ",
  "mn50:1.1": "Tôi nghe như vầy—",
  "mn50:1.2": "Một thời, Tôn giả Mahāmoggallāna (Đại Mục Kiền Liên) trú ở xứ Bhagga, tại Susumāragira, trong rừng Bhesakaḷāva, khu vườn Nai. ",
  "mn50:2.1": "Lúc bấy giờ, Tôn giả Mahāmoggallāna đang đi kinh hành ngoài trời. ",
  "mn50:2.2": "Lúc bấy giờ, Ma vương Ác độc đã nhập vào bụng Tôn giả Mahāmoggallāna, đi vào ruột. ",
  "mn50:2.3": "Rồi Tôn giả Mahāmoggallāna nghĩ: ",
  "mn50:2.4": "“Sao bụng mình nặng nề thế nhỉ? ",
  "mn50:2.5": "Chắc là đầy phân rồi.” ",
  "mn50:2.6": "Rồi Tôn giả Mahāmoggallāna rời chỗ kinh hành, đi vào tịnh xá, ngồi xuống trên chỗ đã trải sẵn. ",
  "mn50:3.1": "Ngồi xuống, Tôn giả Mahāmoggallāna tự mình tác ý một cách khéo léo. ",
  "mn50:3.2": "Tôn giả Mahāmoggallāna thấy Ma vương Ác độc đã nhập vào bụng, đi vào ruột. ",
  "mn50:3.3": "Thấy Ma vương Ác độc, Tôn giả nói: ",
  "mn50:3.4": "“Hãy ra đi, Ác độc; ",
  "mn50:3.5": "hãy ra đi, Ác độc. ",
  "mn50:3.6": "Đừng làm hại Như Lai, đừng làm hại đệ tử Như Lai. ",
  "mn50:3.7": "Đừng để điều đó mang lại bất lợi, đau khổ cho ngươi lâu dài.” ",
  "mn50:4.1": "Rồi Ma vương Ác độc nghĩ: ",
  "mn50:4.2": "“Vị Sa-môn này không biết, không thấy ta mà lại nói: ",
  "mn50:4.3": "‘Hãy ra đi, Ác độc; ",
  "mn50:4.4": "hãy ra đi, Ác độc. ",
  "mn50:4.5": "Đừng làm hại Như Lai, đừng làm hại đệ tử Như Lai. ",
  "mn50:4.6": "Đừng để điều đó mang lại bất lợi, đau khổ cho ngươi lâu dài.’ ",
  "mn50:4.7": "Ngay cả vị Thầy của ông ta cũng không thể nhanh chóng biết được ta, huống chi đệ tử này làm sao biết được ta?” ",
  "mn50:5.1": "Rồi Tôn giả Mahāmoggallāna nói với Ma vương Ác độc: ",
  "mn50:5.2": "“Này Ác độc, ta biết ngươi như vậy, đừng nghĩ: ",
  "mn50:5.3": "‘Ông ta không biết ta.’ ",
  "mn50:5.4": "Ngươi là Ma vương, này Ác độc; ",
  "mn50:5.5": "này Ác độc, ngươi đã nghĩ như vầy: ",
  "mn50:5.6": "‘Vị Sa-môn này không biết, không thấy ta mà lại nói—",
  "mn50:5.7": "hãy ra đi, Ác độc; ",
  "mn50:5.8": "hãy ra đi, Ác độc. ",
  "mn50:5.9": "Đừng làm hại Như Lai, đừng làm hại đệ tử Như Lai. ",
  "mn50:5.10": "Đừng để điều đó mang lại bất lợi, đau khổ cho ngươi lâu dài. ",
  "mn50:5.11": "Ngay cả vị Thầy của ông ta cũng không thể nhanh chóng biết được ta, huống chi đệ tử này làm sao biết được ta?’” ",
  "mn50:6.1": "Rồi Ma vương Ác độc nghĩ: ",
  "mn50:6.2": "“Vị Sa-môn này biết, thấy ta mà lại nói: ",
  "mn50:6.3": "‘Hãy ra đi, Ác độc; ",
  "mn50:6.4": "hãy ra đi, Ác độc. ",
  "mn50:6.5": "Đừng làm hại Như Lai, đừng làm hại đệ tử Như Lai. ",
  "mn50:6.6": "Đừng để điều đó mang lại bất lợi, đau khổ cho ngươi lâu dài.’” ",
  "mn50:6.7": "Rồi Ma vương Ác độc thoát ra khỏi miệng Tôn giả Mahāmoggallāna và đứng ở chốt cửa. ",
  "mn50:7.1": "Tôn giả Mahāmoggallāna thấy Ma vương Ác độc đang đứng ở chốt cửa; ",
  "mn50:7.2": "thấy Ma vương Ác độc, Tôn giả nói: ",
  "mn50:7.3": "“Này Ác độc, ta thấy ngươi ở đây nữa; đừng nghĩ ",
  "mn50:7.4": "‘Ông ta không thấy ta.’ ",
  "mn50:7.5": "Ngươi đó, này Ác độc, đang đứng ở chốt cửa. ",
  "mn50:8.1": "Này Ác độc, thuở xưa ta là Ma vương tên Dūsī, ta có một người em gái tên Kāḷī. ",
  "mn50:8.2": "Ngươi là con của cô ấy. ",
  "mn50:8.3": "Vậy ngươi là cháu của ta. ",
  "mn50:9.1": "Này Ác độc, lúc bấy giờ, Đức Kakusandha, bậc A-la-hán, Chánh Đẳng Giác, đã xuất hiện trên đời. ",
  "mn50:9.2": "Này Ác độc, Đức Kakusandha, bậc A-la-hán, Chánh Đẳng Giác, có một cặp đệ tử tên Vidhura và Sañjīva, là cặp đệ tử tối thắng, cao quý. ",
  "mn50:9.3": "Này Ác độc, trong số các đệ tử của Đức Kakusandha, bậc A-la-hán, Chánh Đẳng Giác, ",
  "mn50:9.4": "không ai sánh bằng Tôn giả Vidhura về việc thuyết pháp. ",
  "mn50:9.5": "Này Ác độc, chính vì lý do này mà Tôn giả Vidhura được gọi là Vidhura. ",
  "mn50:10.1": "Còn Tôn giả Sañjīva, này Ác độc, dù đi vào rừng, đến gốc cây, hay vào nhà trống, ngài dễ dàng nhập vào diệt thọ tưởng. ",
  "mn50:10.2": "Này Ác độc, thuở xưa, Tôn giả Sañjīva đã nhập vào diệt thọ tưởng và ngồi dưới một gốc cây. ",
  "mn50:10.3": "Này Ác độc, những người chăn bò, chăn dê, nông dân, và người đi đường thấy Tôn giả Sañjīva đã nhập vào diệt thọ tưởng và ngồi dưới một gốc cây; ",
  "mn50:10.4": "thấy vậy, họ nghĩ: ",
  "mn50:10.5": "‘Ôi lạ lùng thay, thật kỳ diệu thay. ",
  "mn50:10.6": "Vị Sa-môn này đã chết khi đang ngồi. ",
  "mn50:10.7": "Nào, chúng ta hãy thiêu ông ta.’ ",
  "mn50:10.8": "Rồi, này Ác độc, những người chăn bò, chăn dê, nông dân, và người đi đường gom cỏ, củi, và phân bò lại, chất lên thân Tôn giả Sañjīva, châm lửa rồi bỏ đi. ",
  "mn50:11.1": "Rồi, này Ác độc, Tôn giả Sañjīva, sau khi đêm đó qua đi, xuất khỏi định đó, phủi y phục, vào buổi sáng đắp y, cầm bát và y đi vào làng khất thực. ",
  "mn50:11.2": "Này Ác độc, những người chăn bò, chăn dê, nông dân, và người đi đường thấy Tôn giả Sañjīva đang đi khất thực; ",
  "mn50:11.3": "thấy vậy, họ nghĩ: ",
  "mn50:11.4": "‘Ôi lạ lùng thay, thật kỳ diệu thay. ",
  "mn50:11.5": "Vị Sa-môn này đã chết khi đang ngồi, vậy mà ông ta đã sống lại.’ ",
  "mn50:11.6": "Này Ác độc, chính vì lý do này mà Tôn giả Sañjīva được gọi là Sañjīva. ",
  "mn50:12.1": "Rồi, này Ác độc, Ma vương Dūsī nghĩ: ",
  "mn50:12.2": "‘Ta không biết sự đến hay đi của những vị Tỳ-kheo có giới hạnh, có pháp lành này. ",
  "mn50:12.3": "Hay là ta nhập vào các Bà-la-môn và gia chủ—",
  "mn50:12.4": "hỡi các ngươi, hãy mắng nhiếc, phỉ báng, chọc giận, làm hại các Tỳ-kheo có giới hạnh, có pháp lành. ",
  "mn50:12.5": "Biết đâu khi bị các ngươi mắng nhiếc, phỉ báng, chọc giận, làm hại, tâm của họ sẽ thay đổi, để Ma vương Dūsī có thể tìm được cơ hội.’ ",
  "mn50:12.6": "Rồi, này Ác độc, Ma vương Dūsī nhập vào các Bà-la-môn và gia chủ: ",
  "mn50:12.7": "‘Hỡi các ngươi, hãy mắng nhiếc, phỉ báng, chọc giận, làm hại các Tỳ-kheo có giới hạnh, có pháp lành. ",
  "mn50:12.8": "Biết đâu khi bị các ngươi mắng nhiếc, phỉ báng, chọc giận, làm hại, tâm của họ sẽ thay đổi, để Ma vương Dūsī có thể tìm được cơ hội.’ ",
  "mn50:13.1": "Rồi, này Ác độc, các Bà-la-môn và gia chủ bị Ma vương Dūsī nhập vào, mắng nhiếc, phỉ báng, chọc giận, làm hại các Tỳ-kheo có giới hạnh, có pháp lành: ",
  "mn50:13.2": "‘Những Sa-môn đầu trọc, hạ tiện, đen đúa, xuất thân từ dòng dõi của Bà-la-môn, nói “chúng tôi thiền định, chúng tôi thiền định” mà vai rũ xuống, mặt cúi gằm, như bị bệnh mật, thiền định, thiền định, thiền định, thiền định. ",
  "mn50:13.3": "Như con cú trên cành cây rình chuột mà thiền định, thiền định, thiền định, thiền định; ",
  "mn50:13.4": "cũng vậy, những Sa-môn đầu trọc, hạ tiện, đen đúa, xuất thân từ dòng dõi của Bà-la-môn, nói “chúng tôi thiền định, chúng tôi thiền định” mà vai rũ xuống, mặt cúi gằm, như bị bệnh mật, thiền định, thiền định, thiền định, thiền định. ",
  "mn50:13.5": "Như con chó rừng bên bờ sông rình cá mà thiền định, thiền định, thiền định, thiền định; ",
  "mn50:13.6": "cũng vậy, những Sa-môn đầu trọc, hạ tiện, đen đúa, xuất thân từ dòng dõi của Bà-la-môn, nói “chúng tôi thiền định, chúng tôi thiền định” mà vai rũ xuống, mặt cúi gằm, như bị bệnh mật, thiền định, thiền định, thiền định, thiền định. ",
  "mn50:13.7": "Như con mèo ở đống rác bẩn thỉu rình chuột mà thiền định, thiền định, thiền định, thiền định; ",
  "mn50:13.8": "cũng vậy, những Sa-môn đầu trọc, hạ tiện, đen đúa, xuất thân từ dòng dõi của Bà-la-môn, nói “chúng tôi thiền định, chúng tôi thiền định” mà vai rũ xuống, mặt cúi gằm, như bị bệnh mật, thiền định, thiền định, thiền định, thiền định. ",
  "mn50:13.9": "Như con lừa bị cắt dây cương ở đống rác bẩn thỉu mà thiền định, thiền định, thiền định, thiền định; ",
  "mn50:13.10": "cũng vậy, những Sa-môn đầu trọc, hạ tiện, đen đúa, xuất thân từ dòng dõi của Bà-la-môn, nói “chúng tôi thiền định, chúng tôi thiền định” mà vai rũ xuống, mặt cúi gằm, như bị bệnh mật, thiền định, thiền định, thiền định, thiền định.’ ",
  "mn50:13.11": "Này Ác độc, những người nào vào lúc đó chết đi, phần lớn sau khi thân hoại mạng chung, họ tái sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn50:14.1": "Rồi, này Ác độc, Đức Kakusandha, bậc A-la-hán, Chánh Đẳng Giác, gọi các Tỳ-kheo và nói: ",
  "mn50:14.2": "‘Này các Tỳ-kheo, các Bà-la-môn và gia chủ đã bị Ma vương Dūsī nhập vào—",
  "mn50:14.3": "hỡi các ngươi, hãy mắng nhiếc, phỉ báng, chọc giận, làm hại các Tỳ-kheo có giới hạnh, có pháp lành, biết đâu khi bị các ngươi mắng nhiếc, phỉ báng, chọc giận, làm hại, tâm của họ sẽ thay đổi, để Ma vương Dūsī có thể tìm được cơ hội.’ ",
  "mn50:14.4": "Này các Tỳ-kheo, hãy sống trải tâm từ bi đến một phương, cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư. Như vậy, ở trên, ở dưới, ở ngang, khắp mọi nơi, với tất cả mọi loài, hãy sống trải tâm từ bi rộng lớn, bao la, vô lượng, không oán hận, không ác ý, khắp cả thế gian. ",
  "mn50:14.5": "Với tâm bi… ",
  "mn50:14.6": "Với tâm hỷ… ",
  "mn50:14.7": "Với tâm xả đến một phương, cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư. Như vậy, ở trên, ở dưới, ở ngang, khắp mọi nơi, với tất cả mọi loài, hãy sống trải tâm xả rộng lớn, bao la, vô lượng, không oán hận, không ác ý, khắp cả thế gian.’ ",
  "mn50:15.1": "Rồi, này Ác độc, các Tỳ-kheo đó, được Đức Kakusandha, bậc A-la-hán, Chánh Đẳng Giác, khuyên dạy và giáo huấn như vậy, dù đi vào rừng, đến gốc cây, hay vào nhà trống, họ đã sống trải tâm từ bi đến một phương, cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư. Như vậy, ở trên, ở dưới, ở ngang, khắp mọi nơi, với tất cả mọi loài, họ đã sống trải tâm từ bi rộng lớn, bao la, vô lượng, không oán hận, không ác ý, khắp cả thế gian. ",
  "mn50:15.2": "Với tâm bi… ",
  "mn50:15.3": "Với tâm hỷ… ",
  "mn50:15.4": "Với tâm xả đến một phương, cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư. Như vậy, ở trên, ở dưới, ở ngang, khắp mọi nơi, với tất cả mọi loài, họ đã sống trải tâm xả rộng lớn, bao la, vô lượng, không oán hận, không ác ý, khắp cả thế gian. ",
  "mn50:16.1": "Rồi, này Ác độc, Ma vương Dūsī nghĩ: ",
  "mn50:16.2": "‘Ngay cả khi làm như vậy, ta cũng không biết sự đến hay đi của những vị Tỳ-kheo có giới hạnh, có pháp lành này, hay là ta nhập vào các Bà-la-môn và gia chủ: ",
  "mn50:16.3": "“Hỡi các ngươi, hãy tôn kính, trọng vọng, cung kính, cúng dường các Tỳ-kheo có giới hạnh, có pháp lành, ",
  "mn50:16.4": "biết đâu khi được các ngươi tôn kính, trọng vọng, cung kính, cúng dường, tâm của họ sẽ thay đổi, để Ma vương Dūsī có thể tìm được cơ hội.”’ ",
  "mn50:17.1": "Rồi, này Ác độc, Ma vương Dūsī nhập vào các Bà-la-môn và gia chủ: ",
  "mn50:17.2": "‘Hỡi các ngươi, hãy tôn kính, trọng vọng, cung kính, cúng dường các Tỳ-kheo có giới hạnh, có pháp lành, ",
  "mn50:17.3": "biết đâu khi được các ngươi tôn kính, trọng vọng, cung kính, cúng dường, tâm của họ sẽ thay đổi, để Ma vương Dūsī có thể tìm được cơ hội.’ ",
  "mn50:17.4": "Rồi, này Ác độc, các Bà-la-môn và gia chủ bị Ma vương Dūsī nhập vào, tôn kính, trọng vọng, cung kính, cúng dường các Tỳ-kheo có giới hạnh, có pháp lành. ",
  "mn50:17.5": "Này Ác độc, những người nào vào lúc đó chết đi, phần lớn sau khi thân hoại mạng chung, họ tái sinh vào cõi lành, cõi trời. ",
  "mn50:18.1": "Rồi, này Ác độc, Đức Kakusandha, bậc A-la-hán, Chánh Đẳng Giác, gọi các Tỳ-kheo và nói: ",
  "mn50:18.2": "‘Này các Tỳ-kheo, các Bà-la-môn và gia chủ đã bị Ma vương Dūsī nhập vào: ",
  "mn50:18.3": "“Hỡi các ngươi, hãy tôn kính, trọng vọng, cung kính, cúng dường các Tỳ-kheo có giới hạnh, có pháp lành, ",
  "mn50:18.4": "biết đâu khi được các ngươi tôn kính, trọng vọng, cung kính, cúng dường, tâm của họ sẽ thay đổi, để Ma vương Dūsī có thể tìm được cơ hội.” ",
  "mn50:18.5": "Này các Tỳ-kheo, hãy sống quán bất tịnh trong thân, quán ghê tởm trong thức ăn, quán không hoan hỷ trong tất cả thế gian, quán vô thường trong tất cả các hành.’ ",
  "mn50:19.1": "Rồi, này Ác độc, các Tỳ-kheo đó, được Đức Kakusandha, bậc A-la-hán, Chánh Đẳng Giác, khuyên dạy và giáo huấn như vậy, dù đi vào rừng, đến gốc cây, hay vào nhà trống, họ đã sống quán bất tịnh trong thân, quán ghê tởm trong thức ăn, quán không hoan hỷ trong tất cả thế gian, quán vô thường trong tất cả các hành. ",
  "mn50:20.1": "Rồi, này Ác độc, Đức Kakusandha, bậc A-la-hán, Chánh Đẳng Giác, vào buổi sáng đắp y, cầm bát và y, cùng với Tôn giả Vidhura làm thị giả, đi vào làng khất thực. ",
  "mn50:21.1": "Rồi, này Ác độc, Ma vương Dūsī nhập vào một đứa trẻ, cầm một cục đá đánh vào đầu Tôn giả Vidhura; đầu ngài bị vỡ. ",
  "mn50:21.2": "Rồi, này Ác độc, Tôn giả Vidhura, với cái đầu vỡ và máu chảy, vẫn đi theo sau Đức Kakusandha, bậc A-la-hán, Chánh Đẳng Giác. ",
  "mn50:21.3": "Rồi, này Ác độc, Đức Kakusandha, bậc A-la-hán, Chánh Đẳng Giác, nhìn lại như con voi: ",
  "mn50:21.4": "‘Ma vương Dūsī này đã không biết chừng mực.’ ",
  "mn50:21.5": "Và ngay khi nhìn lại, này Ác độc, Ma vương Dūsī đã biến mất khỏi chỗ đó và tái sinh vào đại địa ngục. ",
  "mn50:22.1": "Này ác ma, đại địa ngục ấy có ba tên gọi—",
  "mn50:22.2": "là Sáu Xúc Xứ, là Bị Đâm Bằng Cọc, là Tự Mình Cảm Thọ. ",
  "mn50:22.3": "Rồi này ác ma, các người giữ ngục đến gần tôi và nói: ",
  "mn50:22.4": "‘Này hiền giả, khi nào cọc này đâm xuyên tim ông. ",
  "mn50:22.5": "Khi ấy ông hãy biết: ",
  "mn50:22.6": "“Tôi đã bị nung nấu trong địa ngục một ngàn năm rồi”’. ",
  "mn50:23.1": "Này ác ma, tôi đã bị nung nấu trong đại địa ngục ấy nhiều năm, nhiều trăm năm, nhiều ngàn năm. ",
  "mn50:23.2": "Mười ngàn năm tôi bị nung nấu trong vùng ngoại vi của đại địa ngục ấy, chịu đựng cảm thọ gọi là sự trồi lên. ",
  "mn50:23.3": "Này ác ma, thân tôi khi ấy như thân người. ",
  "mn50:23.4": "Đầu tôi khi ấy như đầu cá. ",
  "mn50:24.1": "Địa ngục ấy ra sao, ",
  "mn50:24.2": "nơi Dūsī bị nung nấu; ",
  "mn50:24.3": "vì xúc phạm đệ tử Vidhura, ",
  "mn50:24.4": "và Bà la môn Kakusandha. ",
  "mn50:24.5": "Có một trăm cọc sắt, ",
  "mn50:24.6": "tất cả đều tự mình cảm thọ; ",
  "mn50:24.7": "Địa ngục ấy như vậy, ",
  "mn50:24.8": "nơi Dūsī bị nung nấu; ",
  "mn50:24.9": "vì xúc phạm đệ tử Vidhura, ",
  "mn50:24.10": "và Bà la môn Kakusandha. ",
  "mn50:24.11": "Ai biết rõ điều này, ",
  "mn50:24.12": "tỳ khưu đệ tử của Phật; ",
  "mn50:24.13": "xúc phạm tỳ khưu như vậy, ",
  "mn50:24.14": "này Kaṇha, ngươi sẽ gặp khổ. ",
  "mn50:25.1": "Giữa hồ nước đứng sừng sững, ",
  "mn50:25.2": "các cung điện tồn tại suốt kiếp; ",
  "mn50:25.3": "màu ngọc bích, rực rỡ, ",
  "mn50:25.4": "chói sáng, rạng rỡ; ",
  "mn50:25.5": "các tiên nữ nhảy múa ở đó, ",
  "mn50:25.6": "với nhiều màu sắc khác nhau. ",
  "mn50:25.7": "Ai biết rõ điều này, ",
  "mn50:25.8": "tỳ khưu đệ tử của Phật; ",
  "mn50:25.9": "xúc phạm tỳ khưu như vậy, ",
  "mn50:25.10": "này Kaṇha, ngươi sẽ gặp khổ. ",
  "mn50:26.1": "Người được Phật khuyến khích, ",
  "mn50:26.2": "tỳ khưu trước mặt Tăng chúng; ",
  "mn50:26.3": "đã làm rung chuyển cung điện của Migāramātā, ",
  "mn50:26.4": "bằng ngón chân cái. ",
  "mn50:26.5": "Ai biết rõ điều này, ",
  "mn50:26.6": "tỳ khưu đệ tử của Phật; ",
  "mn50:26.7": "xúc phạm tỳ khưu như vậy, ",
  "mn50:26.8": "này Kaṇha, ngươi sẽ gặp khổ. ",
  "mn50:27.1": "Người đã làm rung chuyển cung điện Vejayanta, ",
  "mn50:27.2": "bằng ngón chân cái; ",
  "mn50:27.3": "được thần lực hỗ trợ, ",
  "mn50:27.4": "và làm chấn động các vị trời. ",
  "mn50:27.5": "Ai biết rõ điều này, ",
  "mn50:27.6": "tỳ khưu đệ tử của Phật; ",
  "mn50:27.7": "xúc phạm tỳ khưu như vậy, ",
  "mn50:27.8": "này Kaṇha, ngươi sẽ gặp khổ. ",
  "mn50:28.1": "Người ở cung điện Vejayanta, ",
  "mn50:28.2": "đã hỏi Sakka; ",
  "mn50:28.3": "Này Vāsava, ông có biết, ",
  "mn50:28.4": "sự giải thoát do diệt trừ tham ái không; ",
  "mn50:28.5": "Sakka đã giải đáp cho người ấy, ",
  "mn50:28.6": "câu hỏi được hỏi một cách đúng đắn. ",
  "mn50:28.7": "Ai biết rõ điều này, ",
  "mn50:28.8": "tỳ khưu đệ tử của Phật; ",
  "mn50:28.9": "xúc phạm tỳ khưu như vậy, ",
  "mn50:28.10": "này Kaṇha, ngươi sẽ gặp khổ. ",
  "mn50:29.1": "Người đã hỏi Phạm thiên, ",
  "mn50:29.2": "trong hội trường Sudhammā; ",
  "mn50:29.3": "Này hiền giả, hôm nay quan điểm của ông, ",
  "mn50:29.4": "có phải là quan điểm trước đây của ông không; ",
  "mn50:29.5": "Ông có thấy sự vượt qua, ",
  "mn50:29.6": "sự rạng rỡ trong cõi Phạm thiên không. ",
  "mn50:29.7": "Phạm thiên đã giải đáp cho người ấy, ",
  "mn50:29.8": "từng bước một cách đúng đắn; ",
  "mn50:29.9": "Này hiền giả, đó không phải là quan điểm của tôi, ",
  "mn50:29.10": "quan điểm mà tôi đã có trước đây. ",
  "mn50:29.11": "Tôi thấy sự vượt qua, ",
  "mn50:29.12": "sự rạng rỡ trong cõi Phạm thiên; ",
  "mn50:29.13": "Vậy hôm nay làm sao tôi có thể nói, ",
  "mn50:29.14": "tôi là thường hằng, vĩnh cửu. ",
  "mn50:29.15": "Ai biết rõ điều này, ",
  "mn50:29.16": "tỳ khưu đệ tử của Phật; ",
  "mn50:29.17": "xúc phạm tỳ khưu như vậy, ",
  "mn50:29.18": "này Kaṇha, ngươi sẽ gặp khổ. ",
  "mn50:30.1": "Người đã chạm đến đỉnh núi Mahāmeru, ",
  "mn50:30.2": "bằng sự giải thoát; ",
  "mn50:30.3": "rừng của Pubbavideha, ",
  "mn50:30.4": "và những người sống trên mặt đất. ",
  "mn50:30.5": "Ai biết rõ điều này, ",
  "mn50:30.6": "tỳ khưu đệ tử của Phật; ",
  "mn50:30.7": "xúc phạm tỳ khưu như vậy, ",
  "mn50:30.8": "này Kaṇha, ngươi sẽ gặp khổ. ",
  "mn50:31.1": "Lửa không nghĩ, ",
  "mn50:31.2": "‘ta sẽ đốt kẻ ngu’;",
  "mn50:31.3": "Nhưng kẻ ngu chạm vào lửa đang cháy, ",
  "mn50:31.4": "và bị nó đốt cháy. ",
  "mn50:31.5": "Cũng vậy, này Māra, ",
  "mn50:31.6": "ngươi xúc phạm Như Lai; ",
  "mn50:31.7": "ngươi sẽ tự đốt cháy chính mình, ",
  "mn50:31.8": "như kẻ ngu chạm vào lửa. ",
  "mn50:31.9": "Māra đã tạo ra điều bất thiện, ",
  "mn50:31.10": "khi xúc phạm Như Lai; ",
  "mn50:31.11": "Này ác ma, ngươi nghĩ gì, ",
  "mn50:31.12": "tội lỗi của ta sẽ không chín muồi sao. ",
  "mn50:31.13": "Khi làm, tội lỗi tích lũy, ",
  "mn50:31.14": "trong đêm dài, này kẻ hủy diệt; ",
  "mn50:31.15": "Này Māra, hãy chán ghét Phật, ",
  "mn50:31.16": "đừng hy vọng vào các tỳ khưu. ",
  "mn50:31.17": "Như vậy, vị tỳ khưu đã quở trách Māra, ",
  "mn50:31.18": "trong rừng Bhesakaḷā; ",
  "mn50:31.19": "Rồi vị dạ xoa buồn bã ấy, ",
  "mn50:31.20": "đã biến mất ngay tại đó”. ",
  "mn50:31.21": "Kinh Quở Trách Ma Vương, thứ mười, chấm dứt. ",
  "mn50:31.22": "Tiểu Song Ngữ Phẩm, thứ năm, chấm dứt. ",
  "mn50:32.0": "Tóm tắt của phẩm ấy ",
  "mn50:32.1": "Sāleyya, hai Verañja và Tuṭṭhi, ",
  "mn50:32.2": "Tiểu và Đại Pháp Thọ Trì; ",
  "mn50:32.3": "Vīmaṁsakā, Kosambī và Bà la môn, ",
  "mn50:32.4": "Dūsī và Māra là phẩm thứ mười. ",
  "mn50:33.0": "Đây là tóm tắt các phẩm ",
  "mn50:33.1": "Mūlapariyāya, ",
  "mn50:33.2": "và Sīhanāda tối thượng; ",
  "mn50:33.3": "Kakaca và Gosiṅga, ",
  "mn50:33.4": "Sāleyya, đây là năm. ",
  "mn50:33.5": "Năm Mươi Bài Kinh Đầu tiên, hoàn tất. "
}
window.BILARA["mn50"]["vi"]["mn50:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
