window.BILARA = window.BILARA || {};
window.BILARA["mn54"] = window.BILARA["mn54"] || {};
window.BILARA["mn54"]["vi"] = {
  "mn54:0.1": "Trung Bộ Kinh 54 ",
  "mn54:0.2": "Kinh Potaliya ",
  "mn54:1.1": "Tôi nghe như vầy—",
  "mn54:1.2": "Một thời, Thế Tôn trú ở xứ Anguttarāpa, tại thị trấn tên là Āpaṇa của Anguttarāpa. ",
  "mn54:2.1": "Rồi Thế Tôn, vào buổi sáng, đắp y, cầm bát, đi vào Āpaṇa để khất thực. ",
  "mn54:2.2": "Sau khi khất thực ở Āpaṇa và trở về sau bữa ăn, Thế Tôn đi đến một khu rừng để nghỉ trưa. ",
  "mn54:2.3": "Đi sâu vào khu rừng ấy, Thế Tôn ngồi nghỉ trưa dưới gốc cây. ",
  "mn54:3.1": "Cũng vào lúc ấy, gia chủ Potaliya, mặc áo quần chỉnh tề, mang giày dép, đi dạo chơi, đi đến khu rừng ấy; sau khi đến, đi sâu vào khu rừng ấy, đi đến chỗ Thế Tôn; sau khi đến, nói lời chào hỏi với Thế Tôn. ",
  "mn54:3.2": "Sau khi nói lên những lời chào hỏi thân mật, đáng ghi nhớ, ông đứng sang một bên. Khi gia chủ Potaliya đứng sang một bên, Thế Tôn nói với ông: ",
  "mn54:3.3": "“Này gia chủ, có chỗ ngồi đấy; nếu ông muốn, hãy ngồi.” ",
  "mn54:3.4": "Khi được nói vậy, gia chủ Potaliya tức giận, không vui, im lặng, nghĩ: “Sa-môn Gotama gọi ta là ‘gia chủ’.” ",
  "mn54:3.5": "Lần thứ hai, Thế Tôn … ",
  "mn54:3.6": "Lần thứ ba, Thế Tôn nói với gia chủ Potaliya: ",
  "mn54:3.7": "“Này gia chủ, có chỗ ngồi đấy; nếu ông muốn, hãy ngồi.” ",
  "mn54:3.8": "Khi được nói vậy, gia chủ Potaliya tức giận, không vui, nói với Thế Tôn: “Sa-môn Gotama gọi ta là ‘gia chủ’.” ",
  "mn54:3.9": "“Này ông Gotama, điều này không hợp, điều này không phải lẽ, khi ông gọi tôi là ‘gia chủ’.” ",
  "mn54:3.10": "“Này gia chủ, những cử chỉ ấy, những dấu hiệu ấy, những biểu hiện ấy của ông đúng là của một gia chủ.” ",
  "mn54:3.11": "“Nhưng này ông Gotama, tôi đã từ bỏ mọi công việc, đã đoạn trừ mọi giao dịch.” ",
  "mn54:3.12": "“Này gia chủ, ông đã từ bỏ mọi công việc, đã đoạn trừ mọi giao dịch như thế nào?” ",
  "mn54:3.13": "“Này ông Gotama, ở đây, tất cả tài sản, lúa gạo, bạc, vàng của tôi, tôi đã giao lại cho con cái làm của thừa kế, và tôi sống không can thiệp, không chỉ trích, chỉ lo ăn mặc. ",
  "mn54:3.14": "Này ông Gotama, như vậy là tôi đã từ bỏ mọi công việc, đã đoạn trừ mọi giao dịch.” ",
  "mn54:3.15": "“Này gia chủ, ông nói về sự đoạn trừ giao dịch theo một cách khác, còn trong giới luật của bậc Thánh, sự đoạn trừ giao dịch lại là một cách khác.” ",
  "mn54:3.16": "“Bạch Thế Tôn, vậy trong giới luật của bậc Thánh, sự đoạn trừ giao dịch là như thế nào? ",
  "mn54:3.17": "Bạch Thế Tôn, lành thay nếu Thế Tôn thuyết pháp cho con để con biết sự đoạn trừ giao dịch trong giới luật của bậc Thánh là như thế nào.” ",
  "mn54:3.18": "“Vậy thì, này gia chủ, hãy lắng nghe, hãy chú ý kỹ, tôi sẽ nói.” ",
  "mn54:3.19": "“Vâng, bạch Thế Tôn,” gia chủ Potaliya đáp lời Thế Tôn. ",
  "mn54:4.1": "Thế Tôn nói như sau: ",
  "mn54:4.2": "“Này gia chủ, có tám pháp này dẫn đến sự đoạn trừ giao dịch trong giới luật của bậc Thánh. ",
  "mn54:4.3": "Tám pháp nào? ",
  "mn54:4.4": "Nương vào không sát sinh, sát sinh cần được từ bỏ; ",
  "mn54:4.5": "nương vào cho những gì đã được cho, lấy của không cho cần được từ bỏ; ",
  "mn54:4.6": "nương vào lời nói thật, nói dối cần được từ bỏ; ",
  "mn54:4.7": "nương vào lời nói không chia rẽ, lời nói chia rẽ cần được từ bỏ; ",
  "mn54:4.8": "nương vào không tham lam, tham lam cần được từ bỏ; ",
  "mn54:4.9": "nương vào không oán hận, oán hận cần được từ bỏ; ",
  "mn54:4.10": "nương vào không giận dữ và phiền muộn, giận dữ và phiền muộn cần được từ bỏ; ",
  "mn54:4.11": "nương vào không kiêu mạn, kiêu mạn cần được từ bỏ. ",
  "mn54:4.12": "Này gia chủ, tám pháp này được nói tóm tắt, chưa được phân tích rộng rãi, dẫn đến sự đoạn trừ giao dịch trong giới luật của bậc Thánh.” ",
  "mn54:5.1": "“Bạch Thế Tôn, tám pháp mà Thế Tôn đã nói tóm tắt, chưa được phân tích rộng rãi, dẫn đến sự đoạn trừ giao dịch trong giới luật của bậc Thánh, lành thay nếu Thế Tôn vì lòng thương xót mà phân tích rộng rãi tám pháp này cho con.” ",
  "mn54:5.2": "“Vậy thì, này gia chủ, hãy lắng nghe, hãy chú ý kỹ, tôi sẽ nói.” ",
  "mn54:5.3": "“Vâng, bạch Thế Tôn,” gia chủ Potaliya đáp lời Thế Tôn. ",
  "mn54:5.4": "Thế Tôn nói như sau: ",
  "mn54:6.1": "“‘Nương vào không sát sinh, sát sinh cần được từ bỏ’—điều này đã được nói, vậy điều này được nói dựa trên cái gì? ",
  "mn54:6.2": "Này gia chủ, ở đây, một đệ tử của bậc Thánh suy xét như sau: ",
  "mn54:6.3": "‘Vì những ràng buộc nào mà ta có thể sát sinh, ta đã thực hành để từ bỏ, để đoạn trừ những ràng buộc ấy. ",
  "mn54:6.4": "Nếu ta sát sinh, tự ta sẽ chỉ trích ta vì việc sát sinh; những người có trí sau khi xem xét cũng sẽ chê trách ta vì việc sát sinh; sau khi thân hoại mạng chung, ác thú sẽ được mong đợi vì việc sát sinh. ",
  "mn54:6.5": "Chính đây là ràng buộc, chính đây là chướng ngại, tức là sát sinh. ",
  "mn54:6.6": "Và những lậu hoặc, phiền não, khổ đau nào có thể phát sinh do sát sinh, đối với người đã từ bỏ sát sinh, những lậu hoặc, phiền não, khổ đau ấy sẽ không có.’ ",
  "mn54:6.7": "‘Nương vào không sát sinh, sát sinh cần được từ bỏ’—",
  "mn54:6.8": "điều đã được nói ấy, chính là được nói dựa trên điều này. ",
  "mn54:7.1": "‘Nương vào cho những gì đã được cho, lấy của không cho cần được từ bỏ’—điều này đã được nói, vậy điều này được nói dựa trên cái gì? ",
  "mn54:7.2": "Này gia chủ, ở đây, một đệ tử của bậc Thánh suy xét như sau: ",
  "mn54:7.3": "‘Vì những ràng buộc nào mà ta có thể lấy của không cho, ta đã thực hành để từ bỏ, để đoạn trừ những ràng buộc ấy. ",
  "mn54:7.4": "Nếu ta lấy của không cho, tự ta sẽ chỉ trích ta vì việc lấy của không cho; những người có trí sau khi xem xét cũng sẽ chê trách ta vì việc lấy của không cho; sau khi thân hoại mạng chung, ác thú sẽ được mong đợi vì việc lấy của không cho. ",
  "mn54:7.5": "Chính đây là ràng buộc, chính đây là chướng ngại, tức là lấy của không cho. ",
  "mn54:7.6": "Và những lậu hoặc, phiền não, khổ đau nào có thể phát sinh do lấy của không cho, đối với người đã từ bỏ lấy của không cho, những lậu hoặc, phiền não, khổ đau ấy sẽ không có.’ ",
  "mn54:7.7": "‘Nương vào cho những gì đã được cho, lấy của không cho cần được từ bỏ’—",
  "mn54:7.8": "điều đã được nói ấy, chính là được nói dựa trên điều này. ",
  "mn54:8.1": "‘Nương vào lời nói thật, nói dối cần được từ bỏ’—điều này đã được nói, vậy điều này được nói dựa trên cái gì? ",
  "mn54:8.2": "Này gia chủ, ở đây, một đệ tử của bậc Thánh suy xét như sau: ",
  "mn54:8.3": "‘Vì những ràng buộc nào mà ta có thể nói dối, ta đã thực hành để từ bỏ, để đoạn trừ những ràng buộc ấy. ",
  "mn54:8.4": "Nếu ta nói dối, tự ta sẽ chỉ trích ta vì việc nói dối; những người có trí sau khi xem xét cũng sẽ chê trách ta vì việc nói dối; sau khi thân hoại mạng chung, ác thú sẽ được mong đợi vì việc nói dối. ",
  "mn54:8.5": "Chính đây là ràng buộc, chính đây là chướng ngại, tức là nói dối. ",
  "mn54:8.6": "Và những lậu hoặc, phiền não, khổ đau nào có thể phát sinh do nói dối, đối với người đã từ bỏ nói dối, những lậu hoặc, phiền não, khổ đau ấy sẽ không có.’ ",
  "mn54:8.7": "‘Nương vào lời nói thật, nói dối cần được từ bỏ’—",
  "mn54:8.8": "điều đã được nói ấy, chính là được nói dựa trên điều này. ",
  "mn54:9.1": "‘Nương vào lời nói không chia rẽ, lời nói chia rẽ cần được từ bỏ’—điều này đã được nói, vậy điều này được nói dựa trên cái gì? ",
  "mn54:9.2": "Này gia chủ, ở đây, một đệ tử của bậc Thánh suy xét như sau: ",
  "mn54:9.3": "‘Vì những ràng buộc nào mà ta có thể nói lời chia rẽ, ta đã thực hành để từ bỏ, để đoạn trừ những ràng buộc ấy. ",
  "mn54:9.4": "Nếu ta nói lời chia rẽ, tự ta sẽ chỉ trích ta vì việc nói lời chia rẽ; những người có trí sau khi xem xét cũng sẽ chê trách ta vì việc nói lời chia rẽ; sau khi thân hoại mạng chung, ác thú sẽ được mong đợi vì việc nói lời chia rẽ. ",
  "mn54:9.5": "Chính đây là ràng buộc, chính đây là chướng ngại, tức là lời nói chia rẽ. ",
  "mn54:9.6": "Và những lậu hoặc, phiền não, khổ đau nào có thể phát sinh do lời nói chia rẽ, đối với người đã từ bỏ lời nói chia rẽ, những lậu hoặc, phiền não, khổ đau ấy sẽ không có.’ ",
  "mn54:9.7": "‘Nương vào lời nói không chia rẽ, lời nói chia rẽ cần được từ bỏ’—",
  "mn54:9.8": "điều đã được nói ấy, chính là được nói dựa trên điều này. ",
  "mn54:10.1": "‘Nương vào không tham lam, tham lam cần được từ bỏ’—điều này đã được nói, vậy điều này được nói dựa trên cái gì? ",
  "mn54:10.2": "Này gia chủ, ở đây, một đệ tử của bậc Thánh suy xét như sau: ",
  "mn54:10.3": "‘Vì những ràng buộc nào mà ta có thể tham lam, ta đã thực hành để từ bỏ, để đoạn trừ những ràng buộc ấy. ",
  "mn54:10.4": "Nếu ta tham lam, tự ta sẽ chỉ trích ta vì việc tham lam; những người có trí sau khi xem xét cũng sẽ chê trách ta vì việc tham lam; sau khi thân hoại mạng chung, ác thú sẽ được mong đợi vì việc tham lam. ",
  "mn54:10.5": "Chính đây là ràng buộc, chính đây là chướng ngại, tức là tham lam. ",
  "mn54:10.6": "Và những lậu hoặc, phiền não, khổ đau nào có thể phát sinh do tham lam, đối với người đã từ bỏ tham lam, những lậu hoặc, phiền não, khổ đau ấy sẽ không có.’ ",
  "mn54:10.7": "‘Nương vào không tham lam, tham lam cần được từ bỏ’—",
  "mn54:10.8": "điều đã được nói ấy, chính là được nói dựa trên điều này. ",
  "mn54:11.1": "‘Nương vào không oán hận, oán hận cần được từ bỏ’—điều này đã được nói, vậy điều này được nói dựa trên cái gì? ",
  "mn54:11.2": "Này gia chủ, ở đây, một đệ tử của bậc Thánh suy xét như sau: ",
  "mn54:11.3": "‘Vì những ràng buộc nào mà ta có thể oán hận, ta đã thực hành để từ bỏ, để đoạn trừ những ràng buộc ấy. ",
  "mn54:11.4": "Nếu ta oán hận, tự ta sẽ chỉ trích ta vì việc oán hận; những người có trí sau khi xem xét cũng sẽ chê trách ta vì việc oán hận; sau khi thân hoại mạng chung, ác thú sẽ được mong đợi vì việc oán hận. ",
  "mn54:11.5": "Chính đây là ràng buộc, chính đây là chướng ngại, tức là oán hận. ",
  "mn54:11.6": "Và những lậu hoặc, phiền não, khổ đau nào có thể phát sinh do oán hận, đối với người không oán hận, những lậu hoặc, phiền não, khổ đau ấy sẽ không có.’ ",
  "mn54:11.7": "‘Nương vào không oán hận, oán hận cần được từ bỏ’—",
  "mn54:11.8": "điều đã được nói ấy, chính là được nói dựa trên điều này. ",
  "mn54:12.1": "‘Nương vào không giận dữ và phiền muộn, giận dữ và phiền muộn cần được từ bỏ’—điều này đã được nói, vậy điều này được nói dựa trên cái gì? ",
  "mn54:12.2": "Này gia chủ, ở đây, một đệ tử của bậc Thánh suy xét như sau: ",
  "mn54:12.3": "‘Vì những ràng buộc nào mà ta có thể giận dữ và phiền muộn, ta đã thực hành để từ bỏ, để đoạn trừ những ràng buộc ấy. ",
  "mn54:12.4": "Nếu ta giận dữ và phiền muộn, tự ta sẽ chỉ trích ta vì việc giận dữ và phiền muộn; những người có trí sau khi xem xét cũng sẽ chê trách ta vì việc giận dữ và phiền muộn; sau khi thân hoại mạng chung, ác thú sẽ được mong đợi vì việc giận dữ và phiền muộn. ",
  "mn54:12.5": "Chính đây là ràng buộc, chính đây là chướng ngại, tức là giận dữ và phiền muộn. ",
  "mn54:12.6": "Và những lậu hoặc, phiền não, khổ đau nào có thể phát sinh do giận dữ và phiền muộn, đối với người không giận dữ và phiền muộn, những lậu hoặc, phiền não, khổ đau ấy sẽ không có.’ ",
  "mn54:12.7": "‘Nương vào không giận dữ và phiền muộn, giận dữ và phiền muộn cần được từ bỏ’—",
  "mn54:12.8": "điều đã được nói ấy, chính là được nói dựa trên điều này. ",
  "mn54:13.1": "‘Nương vào không kiêu mạn, kiêu mạn cần được từ bỏ’—điều này đã được nói, vậy điều này được nói dựa trên cái gì? ",
  "mn54:13.2": "Này gia chủ, ở đây, một đệ tử của bậc Thánh suy xét như sau: ",
  "mn54:13.3": "‘Vì những ràng buộc nào mà ta có thể kiêu mạn, ta đã thực hành để từ bỏ, để đoạn trừ những ràng buộc ấy. ",
  "mn54:13.4": "Nếu ta kiêu mạn, tự ta sẽ chỉ trích ta vì việc kiêu mạn; những người có trí sau khi xem xét cũng sẽ chê trách ta vì việc kiêu mạn; sau khi thân hoại mạng chung, ác thú sẽ được mong đợi vì việc kiêu mạn. ",
  "mn54:13.5": "Chính đây là ràng buộc, chính đây là chướng ngại, tức là kiêu mạn. ",
  "mn54:13.6": "Và những lậu hoặc, phiền não, khổ đau nào có thể phát sinh do kiêu mạn, đối với người không kiêu mạn, những lậu hoặc, phiền não, khổ đau ấy sẽ không có.’ ",
  "mn54:13.7": "‘Nương vào không kiêu mạn, kiêu mạn cần được từ bỏ’—",
  "mn54:13.8": "điều đã được nói ấy, chính là được nói dựa trên điều này. ",
  "mn54:14.1": "Này gia chủ, tám pháp này đã được nói tóm tắt, đã được phân tích rộng rãi, dẫn đến sự đoạn trừ giao dịch trong giới luật của bậc Thánh; ",
  "mn54:14.2": "nhưng chưa phải là sự đoạn trừ hoàn toàn, toàn bộ, mọi mặt của giao dịch trong giới luật của bậc Thánh.” ",
  "mn54:14.3": "“Bạch Thế Tôn, vậy trong giới luật của bậc Thánh, sự đoạn trừ hoàn toàn, toàn bộ, mọi mặt của giao dịch là như thế nào? ",
  "mn54:14.4": "Bạch Thế Tôn, lành thay nếu Thế Tôn thuyết pháp cho con để con biết sự đoạn trừ hoàn toàn, toàn bộ, mọi mặt của giao dịch trong giới luật của bậc Thánh là như thế nào.” ",
  "mn54:14.5": "“Vậy thì, này gia chủ, hãy lắng nghe, hãy chú ý kỹ, tôi sẽ nói.” ",
  "mn54:14.6": "“Vâng, bạch Thế Tôn,” gia chủ Potaliya đáp lời Thế Tôn. ",
  "mn54:14.7": "Thế Tôn nói như sau: ",
  "mn54:15.0": "1. Bài nói về sự nguy hiểm của dục ",
  "mn54:15.1": "“Này gia chủ, ví như một con chó bị đói và yếu ớt, đứng trước lò mổ bò. ",
  "mn54:15.2": "Người đồ tể khéo léo hoặc người học việc của đồ tể sẽ ném cho nó một bộ xương khô, đã được rút hết thịt, không còn thịt, dính máu. ",
  "mn54:15.3": "Này gia chủ, ông nghĩ sao, ",
  "mn54:15.4": "liệu con chó ấy, khi liếm bộ xương khô, đã được rút hết thịt, không còn thịt, dính máu ấy, có thể xua tan được cơn đói và sự yếu ớt của nó không?” ",
  "mn54:15.5": "“Không, bạch Thế Tôn.” ",
  "mn54:15.6": "“Vì sao vậy?” ",
  "mn54:15.7": "“Thưa Ngài, đó là một bộ xương khô, đã được gọt sạch, không còn thịt, dính đầy máu. ",
  "mn54:15.8": "Con chó đó chỉ phải chịu sự mệt mỏi và thất vọng mà thôi.”",
  "mn54:15.9": "“Cũng vậy, này gia chủ, vị đệ tử cao quý suy xét như sau: ",
  "mn54:15.10": "‘Các dục được Thế Tôn nói ví như bộ xương khô, nhiều khổ, nhiều não, hiểm họa ở đây còn nhiều hơn.’",
  "mn54:15.11": "Sau khi thấy điều này đúng như thật với trí tuệ đúng đắn, vị ấy từ bỏ sự xả khác biệt, dựa trên sự khác biệt, và phát triển sự xả đồng nhất, dựa trên sự đồng nhất, nơi mà mọi sự chấp thủ vào vật chất thế gian hoàn toàn chấm dứt không còn sót lại.",
  "mn54:16.1": "Này gia chủ, ví như một con kên kên, diều hâu hay chim ưng cắp một miếng thịt bay đi.",
  "mn54:16.2": "Các con kên kên, diều hâu, chim ưng khác sẽ bay theo, rượt đuổi và giằng xé nó.",
  "mn54:16.3": "Ông nghĩ sao, này gia chủ,",
  "mn54:16.4": "nếu con kên kên, diều hâu hay chim ưng đó không nhanh chóng buông miếng thịt ấy ra, thì do đó nó có thể gặp cái chết hoặc nỗi khổ gần kề cái chết không?”",
  "mn54:16.5": "“Thưa Ngài, đúng vậy.”",
  "mn54:16.6": "“Cũng vậy, này gia chủ, vị đệ tử cao quý suy xét như sau: ",
  "mn54:16.7": "‘Các dục được Thế Tôn nói ví như miếng thịt, nhiều khổ, nhiều não, hiểm họa ở đây còn nhiều hơn.’",
  "mn54:16.8": "Sau khi thấy điều này đúng như thật với trí tuệ đúng đắn, vị ấy từ bỏ sự xả khác biệt, dựa trên sự khác biệt, và phát triển sự xả đồng nhất, dựa trên sự đồng nhất, nơi mà mọi sự chấp thủ vào vật chất thế gian hoàn toàn chấm dứt không còn sót lại.",
  "mn54:17.1": "Này gia chủ, ví như một người cầm một bó đuốc đang cháy đi ngược gió.",
  "mn54:17.2": "Ông nghĩ sao, này gia chủ,",
  "mn54:17.3": "nếu người đó không nhanh chóng buông bó đuốc đang cháy ấy ra, thì bó đuốc đang cháy đó có thể đốt cháy tay, đốt cháy cánh tay, hoặc đốt cháy bất kỳ bộ phận nào khác trên cơ thể, và do đó người đó có thể gặp cái chết hoặc nỗi khổ gần kề cái chết không?”",
  "mn54:17.4": "“Thưa Ngài, đúng vậy.”",
  "mn54:17.5": "“Cũng vậy, này gia chủ, vị đệ tử cao quý suy xét như sau: ",
  "mn54:17.6": "‘Các dục được Thế Tôn nói ví như bó đuốc, nhiều khổ, nhiều não, hiểm họa ở đây còn nhiều hơn.’",
  "mn54:17.7": "Sau khi thấy điều này đúng như thật với trí tuệ đúng đắn …pe… vị ấy phát triển sự xả đó.",
  "mn54:18.1": "Này gia chủ, ví như một hố than sâu hơn một tầm người, đầy than hồng không còn ngọn lửa hay khói.",
  "mn54:18.2": "Rồi một người đến, muốn sống, không muốn chết, muốn hạnh phúc, ghét khổ đau.",
  "mn54:18.3": "Hai người mạnh mẽ nắm lấy hai cánh tay của người đó và kéo về phía hố than.",
  "mn54:18.4": "Ông nghĩ sao, này gia chủ,",
  "mn54:18.5": "người đó có co người lại, co người lại không?”",
  "mn54:18.6": "“Thưa Ngài, đúng vậy.”",
  "mn54:18.7": "“Vì sao vậy?”",
  "mn54:18.8": "“Thưa Ngài, vì người đó biết rằng: ‘Nếu ta rơi vào hố than này, do đó ta sẽ gặp cái chết hoặc nỗi khổ gần kề cái chết.’”",
  "mn54:18.9": "“Cũng vậy, này gia chủ, vị đệ tử cao quý suy xét như sau: ",
  "mn54:18.10": "‘Các dục được Thế Tôn nói ví như hố than, nhiều khổ, nhiều não, hiểm họa ở đây còn nhiều hơn.’",
  "mn54:18.11": "Sau khi thấy điều này đúng như thật với trí tuệ đúng đắn …pe… vị ấy phát triển sự xả đó.",
  "mn54:19.1": "Này gia chủ, ví như một người nằm mơ thấy một khu vườn đẹp, một khu rừng đẹp, một vùng đất đẹp, một hồ sen đẹp.",
  "mn54:19.2": "Khi tỉnh dậy, người đó không thấy gì cả.",
  "mn54:19.3": "Cũng vậy, này gia chủ, vị đệ tử cao quý suy xét như sau:",
  "mn54:19.4": "‘Các dục được Thế Tôn nói ví như giấc mơ, nhiều khổ, nhiều não, hiểm họa ở đây còn nhiều hơn.’ …pe…",
  "mn54:19.5": "vị ấy phát triển sự xả đó.",
  "mn54:20.1": "Này gia chủ, ví như một người mượn tài sản, mượn xe cộ, mượn đồ trang sức quý giá.",
  "mn54:20.2": "Người đó được những tài sản mượn đó bao quanh, đi vào chợ.",
  "mn54:20.3": "Mọi người thấy người đó và nói rằng:",
  "mn54:20.4": "‘Ôi, người này thật giàu có! Quả thật, những người giàu có hưởng thụ tài sản như thế này.’",
  "mn54:20.5": "Rồi các chủ nhân, bất cứ khi nào và ở đâu họ thấy người đó, họ sẽ lấy lại tài sản của họ.",
  "mn54:20.6": "Ông nghĩ sao, này gia chủ, người đó có bị thay đổi trạng thái không?”",
  "mn54:20.7": "“Thưa Ngài, đúng vậy.”",
  "mn54:20.8": "“Vì sao vậy?”",
  "mn54:20.9": "“Thưa Ngài, vì các chủ nhân lấy lại tài sản của họ.”",
  "mn54:20.10": "“Cũng vậy, này gia chủ, vị đệ tử cao quý suy xét như sau: ",
  "mn54:20.11": "‘Các dục được Thế Tôn nói ví như đồ mượn, nhiều khổ, nhiều não, hiểm họa ở đây còn nhiều hơn.’ …pe…",
  "mn54:20.12": "vị ấy phát triển sự xả đó.",
  "mn54:21.1": "Này gia chủ, ví như không xa một làng hay một thị trấn có một khu rừng rậm.",
  "mn54:21.2": "Ở đó có một cây đầy quả và đang ra quả, không có quả nào rơi xuống đất.",
  "mn54:21.3": "Rồi một người đến, muốn quả, tìm quả, đi tìm quả.",
  "mn54:21.4": "Người đó đi vào khu rừng và thấy cây đó đầy quả và đang ra quả.",
  "mn54:21.5": "Người đó nghĩ:",
  "mn54:21.6": "‘Cây này đầy quả và đang ra quả, không có quả nào rơi xuống đất.",
  "mn54:21.7": "Ta biết cách trèo cây.",
  "mn54:21.8": "Vậy ta hãy trèo lên cây này, ăn thỏa thích và lấp đầy vạt áo của ta.’",
  "mn54:21.9": "Người đó trèo lên cây, ăn thỏa thích và lấp đầy vạt áo.",
  "mn54:21.10": "Rồi một người thứ hai đến, muốn quả, tìm quả, đi tìm quả, mang theo một cái rìu sắc.",
  "mn54:21.11": "Người đó đi vào khu rừng và thấy cây đó đầy quả và đang ra quả.",
  "mn54:21.12": "Người đó nghĩ:",
  "mn54:21.13": "‘Cây này đầy quả và đang ra quả, không có quả nào rơi xuống đất.",
  "mn54:21.14": "Nhưng ta không biết cách trèo cây.",
  "mn54:21.15": "Vậy ta hãy chặt cây này từ gốc, ăn thỏa thích và lấp đầy vạt áo của ta.’",
  "mn54:21.16": "Người đó chặt cây từ gốc.",
  "mn54:21.17": "Ông nghĩ sao, này gia chủ,",
  "mn54:21.18": "người kia, người đã trèo lên cây trước, nếu người đó không nhanh chóng xuống, thì khi cây đổ xuống có thể làm gãy tay, gãy chân, hoặc gãy bất kỳ bộ phận nào khác trên cơ thể, và do đó người đó có thể gặp cái chết hoặc nỗi khổ gần kề cái chết không?”",
  "mn54:21.19": "“Thưa Ngài, đúng vậy.”",
  "mn54:21.20": "“Cũng vậy, này gia chủ, vị đệ tử cao quý suy xét như sau: ",
  "mn54:21.21": "‘Các dục được Thế Tôn nói ví như quả cây, nhiều khổ, nhiều não, hiểm họa ở đây còn nhiều hơn.’",
  "mn54:21.22": "Sau khi thấy điều này đúng như thật với trí tuệ đúng đắn, vị ấy từ bỏ sự xả khác biệt, dựa trên sự khác biệt, và phát triển sự xả đồng nhất, dựa trên sự đồng nhất, nơi mà mọi sự chấp thủ vào vật chất thế gian hoàn toàn chấm dứt không còn sót lại.",
  "mn54:22.1": "Này gia chủ, vị đệ tử cao quý đó, nhờ vào sự thanh tịnh của niệm xả vô thượng này, nhớ lại nhiều kiếp sống quá khứ khác nhau,",
  "mn54:22.2": "như là—một kiếp, hai kiếp …pe… như vậy, nhớ lại nhiều kiếp sống quá khứ khác nhau với đầy đủ chi tiết và đặc điểm.",
  "mn54:23.1": "Này gia chủ, vị đệ tử cao quý đó, nhờ vào sự thanh tịnh của niệm xả vô thượng này, với thiên nhãn thanh tịnh, vượt xa tầm nhìn của con người, thấy các chúng sinh chết đi và tái sinh, kẻ thấp hèn, người cao quý, kẻ đẹp đẽ, người xấu xí, kẻ may mắn, người bất hạnh …pe… biết rõ các chúng sinh tùy theo nghiệp của họ.",
  "mn54:24.1": "Này gia chủ, vị đệ tử cao quý đó, nhờ vào sự thanh tịnh của niệm xả vô thượng này, với sự diệt trừ các lậu hoặc, tự mình chứng ngộ, đạt được và an trú trong giải thoát tâm, giải thoát tuệ vô lậu ngay trong hiện tại.",
  "mn54:25.1": "Này gia chủ, đến đây, trong giới luật của bậc cao quý, mọi sự, mọi cách, mọi lời nói đều chấm dứt hoàn toàn.",
  "mn54:25.2": "Ông nghĩ sao, này gia chủ,",
  "mn54:25.3": "như trong giới luật của bậc cao quý, mọi sự, mọi cách, mọi lời nói đều chấm dứt hoàn toàn, ông có thấy sự chấm dứt lời nói như vậy trong chính mình không?”",
  "mn54:25.4": "“Thưa Ngài, tôi là ai mà có thể đạt được sự chấm dứt mọi lời nói, mọi sự, mọi cách trong giới luật của bậc cao quý.",
  "mn54:25.5": "Thưa Ngài, tôi còn xa lắm mới đạt được sự chấm dứt mọi lời nói, mọi sự, mọi cách trong giới luật của bậc cao quý.",
  "mn54:25.6": "Thưa Ngài, trước đây chúng tôi đã lầm tưởng những du sĩ ngoại đạo không phải là bậc cao quý lại là bậc cao quý, đã cúng dường thức ăn của bậc cao quý cho những người không phải là bậc cao quý, đã đặt những người không phải là bậc cao quý vào vị trí của bậc cao quý;",
  "mn54:25.7": "còn các vị Tỳ-kheo, thưa Ngài, là bậc cao quý nhưng chúng tôi lại lầm tưởng là không phải bậc cao quý, đã cúng dường thức ăn không phải của bậc cao quý cho những người là bậc cao quý, đã đặt những người là bậc cao quý vào vị trí không phải của bậc cao quý;",
  "mn54:25.8": "nhưng bây giờ, thưa Ngài, chúng tôi sẽ biết những du sĩ ngoại đạo không phải là bậc cao quý thì đúng là không phải bậc cao quý, sẽ cúng dường thức ăn không phải của bậc cao quý cho những người không phải là bậc cao quý, sẽ đặt những người không phải là bậc cao quý vào vị trí không phải của bậc cao quý.",
  "mn54:25.9": "Còn các vị Tỳ-kheo, thưa Ngài, là bậc cao quý thì chúng tôi sẽ biết đúng là bậc cao quý, sẽ cúng dường thức ăn của bậc cao quý cho những người là bậc cao quý, sẽ đặt những người là bậc cao quý vào vị trí của bậc cao quý.",
  "mn54:25.10": "Thưa Ngài, Thế Tôn đã thật sự tạo ra trong tôi tình yêu đối với các vị Sa-môn, niềm tin đối với các vị Sa-môn, sự tôn kính đối với các vị Sa-môn.",
  "mn54:26.1": "Tuyệt vời thay, thưa Ngài! Tuyệt vời thay, thưa Ngài!",
  "mn54:26.2": "Thưa Ngài, ví như lật ngửa cái bị úp xuống, mở ra cái bị che đậy, chỉ đường cho người lạc lối, hoặc cầm đèn dầu trong bóng tối để ‘những người có mắt có thể thấy các hình sắc’; cũng vậy, thưa Ngài, Thế Tôn đã thuyết giảng Pháp bằng nhiều cách khác nhau.",
  "mn54:26.3": "Thưa Ngài, con xin quy y Thế Tôn, quy y Pháp và quy y Tăng đoàn.",
  "mn54:26.4": "Xin Thế Tôn hãy chấp nhận con là một cư sĩ đã quy y trọn đời, kể từ hôm nay.”",
  "mn54:26.5": "Kinh Potaliya, thứ tư, chấm dứt."
}
window.BILARA["mn54"]["vi"]["mn54:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
