window.BILARA = window.BILARA || {};
window.BILARA["mn55"] = window.BILARA["mn55"] || {};
window.BILARA["mn55"]["vi"] = {
  "mn55:0.1": "Trung Bộ Kinh 55 ",
  "mn55:0.2": "Kinh Jīvaka ",
  "mn55:1.1": "Tôi nghe như vầy—",
  "mn55:1.2": "Một thời, Thế Tôn trú ở Rājagaha (Vương Xá), tại vườn xoài của Jīvaka Komārabhacca (Kỳ-bà-ca, người nuôi trẻ). ",
  "mn55:2.1": "Rồi Jīvaka Komārabhacca đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, Jīvaka Komārabhacca bạch Thế Tôn rằng: ",
  "mn55:3.1": "“Bạch Thế Tôn, con nghe như vầy: ",
  "mn55:3.2": "‘Người ta giết hại sinh vật vì Sa-môn Gotama, và Sa-môn Gotama biết rõ thịt ấy được giết hại vì mình, vẫn thọ dụng, do duyên hành động ấy’. ",
  "mn55:3.3": "Bạch Thế Tôn, những ai nói như vậy: ‘Người ta giết hại sinh vật vì Sa-môn Gotama, và Sa-môn Gotama biết rõ thịt ấy được giết hại vì mình, vẫn thọ dụng, do duyên hành động ấy’, những người ấy, bạch Thế Tôn, có phải là người nói đúng lời Thế Tôn, không xuyên tạc Thế Tôn với điều không có thật, tuyên bố pháp đúng với pháp, và không có lời chỉ trích nào đúng pháp có thể đến chỗ đáng trách không?” ",
  "mn55:4.1": "“Này Jīvaka, những ai nói như vậy: ‘Người ta giết hại sinh vật vì Sa-môn Gotama, và Sa-môn Gotama biết rõ thịt ấy được giết hại vì mình, vẫn thọ dụng, do duyên hành động ấy’, những người ấy không phải là người nói đúng lời Ta, họ xuyên tạc Ta với điều không có thật. ",
  "mn55:5.1": "Này Jīvaka, Ta nói thịt không được thọ dụng do ba trường hợp. ",
  "mn55:5.2": "Thấy, nghe, nghi ngờ—",
  "mn55:5.3": "Này Jīvaka, Ta nói thịt không được thọ dụng do ba trường hợp này. ",
  "mn55:5.4": "Này Jīvaka, Ta nói thịt được thọ dụng do ba trường hợp. ",
  "mn55:5.5": "Không thấy, không nghe, không nghi ngờ—",
  "mn55:5.6": "Này Jīvaka, Ta nói thịt được thọ dụng do ba trường hợp này. ",
  "mn55:6.1": "Ở đây, này Jīvaka, một Tỳ-kheo trú gần một làng hay một thị trấn nào đó. ",
  "mn55:6.2": "Vị ấy an trú, biến mãn một phương với tâm câu hữu với từ, cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư. Như vậy, phía trên, phía dưới, ngang qua, khắp mọi nơi, với tất cả mọi loài, vị ấy an trú, biến mãn khắp thế gian với tâm câu hữu với từ, quảng đại, vô lượng, không oán, không hại. ",
  "mn55:6.3": "Rồi một gia chủ hay con của gia chủ đến mời vị ấy dùng bữa vào ngày mai. ",
  "mn55:6.4": "Này Jīvaka, Tỳ-kheo ấy chấp nhận nếu muốn. ",
  "mn55:6.5": "Sau đêm ấy, vào buổi sáng, vị ấy đắp y, cầm bát và y đi đến nhà của gia chủ hay con của gia chủ ấy; sau khi đến, ngồi xuống chỗ đã được sắp đặt. ",
  "mn55:6.6": "Rồi gia chủ hay con của gia chủ ấy dâng cúng thức ăn ngon. ",
  "mn55:6.7": "Vị ấy không có ý nghĩ như vầy: ",
  "mn55:6.8": "‘Thật tốt lành thay, gia chủ hay con của gia chủ này đã dâng cúng thức ăn ngon cho ta. ",
  "mn55:6.9": "Ôi, ước gì gia chủ hay con của gia chủ này sẽ dâng cúng thức ăn ngon như vậy trong tương lai nữa!’—",
  "mn55:6.10": "Vị ấy không có ý nghĩ như vậy. ",
  "mn55:6.11": "Vị ấy thọ dụng thức ăn khất thực ấy mà không tham đắm, không mê luyến, không chấp trước, thấy rõ sự nguy hiểm, có trí tuệ về sự thoát ly. ",
  "mn55:6.12": "Này Jīvaka, ông nghĩ sao, ",
  "mn55:6.13": "có phải Tỳ-kheo ấy vào lúc đó có ý nghĩ làm hại mình, hay làm hại người khác, hay làm hại cả hai không?” ",
  "mn55:6.14": "“Không phải vậy, bạch Thế Tôn”. ",
  "mn55:6.15": "“Này Jīvaka, có phải Tỳ-kheo ấy vào lúc đó chỉ thọ dụng thức ăn không có lỗi không?” ",
  "mn55:7.1": "“Đúng vậy, bạch Thế Tôn. ",
  "mn55:7.2": "Bạch Thế Tôn, con nghe như vầy: ",
  "mn55:7.3": "‘Phạm thiên an trú với từ’. ",
  "mn55:7.4": "Bạch Thế Tôn, điều ấy con đã thấy tận mắt nơi Thế Tôn; ",
  "mn55:7.5": "vì Thế Tôn, bạch Thế Tôn, an trú với từ.” ",
  "mn55:7.6": "“Này Jīvaka, cái tham, cái sân, cái si mà do đó có sự hại, cái tham, cái sân, cái si ấy đã được Như Lai đoạn trừ, nhổ tận gốc, làm cho như cây thốt nốt bị chặt, không còn khả năng tái sinh, không còn khả năng phát sinh trong tương lai. ",
  "mn55:7.7": "Này Jīvaka, nếu ông nói điều này với ý đó, thì Ta chấp nhận điều đó cho ông.” ",
  "mn55:7.8": "“Bạch Thế Tôn, con đã nói điều này với ý đó.” ",
  "mn55:8-10.1": "Ở đây, này Jīvaka, một Tỳ-kheo trú gần một làng hay một thị trấn nào đó. ",
  "mn55:8-10.2": "Vị ấy an trú, biến mãn với tâm câu hữu với bi… ",
  "mn55:8-10.3": "với tâm câu hữu với hỷ… ",
  "mn55:8-10.4": "với tâm câu hữu với xả, biến mãn một phương, cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư. ",
  "mn55:8-10.5": "Như vậy, phía trên, phía dưới, ngang qua, khắp mọi nơi, với tất cả mọi loài, vị ấy an trú, biến mãn khắp thế gian với tâm câu hữu với xả, quảng đại, vô lượng, không oán, không hại. ",
  "mn55:8-10.6": "Rồi một gia chủ hay con của gia chủ đến mời vị ấy dùng bữa vào ngày mai. ",
  "mn55:8-10.7": "Này Jīvaka, Tỳ-kheo ấy chấp nhận nếu muốn. ",
  "mn55:8-10.8": "Sau đêm ấy, vào buổi sáng, vị ấy đắp y, cầm bát và y đi đến nhà của gia chủ hay con của gia chủ ấy; sau khi đến, ngồi xuống chỗ đã được sắp đặt. ",
  "mn55:8-10.9": "Rồi gia chủ hay con của gia chủ ấy dâng cúng thức ăn ngon. ",
  "mn55:8-10.10": "Vị ấy không có ý nghĩ như vầy: ",
  "mn55:8-10.11": "‘Thật tốt lành thay, gia chủ hay con của gia chủ này đã dâng cúng thức ăn ngon cho ta. ",
  "mn55:8-10.12": "Ôi, ước gì gia chủ hay con của gia chủ này sẽ dâng cúng thức ăn ngon như vậy trong tương lai nữa!’—",
  "mn55:8-10.13": "Vị ấy không có ý nghĩ như vậy. ",
  "mn55:8-10.14": "Vị ấy thọ dụng thức ăn khất thực ấy mà không tham đắm, không mê luyến, không chấp trước, thấy rõ sự nguy hiểm, có trí tuệ về sự thoát ly. ",
  "mn55:8-10.15": "Này Jīvaka, ông nghĩ sao, ",
  "mn55:8-10.16": "có phải Tỳ-kheo ấy vào lúc đó có ý nghĩ làm hại mình, hay làm hại người khác, hay làm hại cả hai không?” ",
  "mn55:8-10.17": "“Không phải vậy, bạch Thế Tôn”. ",
  "mn55:8-10.18": "“Này Jīvaka, có phải Tỳ-kheo ấy vào lúc đó chỉ thọ dụng thức ăn không có lỗi không?” ",
  "mn55:11.1": "“Đúng vậy, bạch Thế Tôn. ",
  "mn55:11.2": "Bạch Thế Tôn, con nghe như vầy: ",
  "mn55:11.3": "‘Phạm thiên an trú với xả’. ",
  "mn55:11.4": "Bạch Thế Tôn, điều ấy con đã thấy tận mắt nơi Thế Tôn; ",
  "mn55:11.5": "vì Thế Tôn, bạch Thế Tôn, an trú với xả.” ",
  "mn55:11.6": "“Này Jīvaka, cái tham, cái sân, cái si mà do đó có sự làm hại, có sự bất mãn, có sự chống đối, cái tham, cái sân, cái si ấy đã được Như Lai đoạn trừ, nhổ tận gốc, làm cho như cây thốt nốt bị chặt, không còn khả năng tái sinh, không còn khả năng phát sinh trong tương lai. ",
  "mn55:11.7": "Này Jīvaka, nếu ông nói điều này với ý đó, thì Ta chấp nhận điều đó cho ông.” ",
  "mn55:11.8": "“Bạch Thế Tôn, con đã nói điều này với ý đó.” ",
  "mn55:12.1": "“Này Jīvaka, ai giết hại sinh vật vì Như Lai hay vì đệ tử của Như Lai, người ấy tạo ra nhiều điều bất thiện do năm trường hợp. ",
  "mn55:12.2": "Này gia chủ, điều mà người ấy nói: ",
  "mn55:12.3": "‘Hãy đi, mang con vật tên là… đến đây’, do trường hợp thứ nhất này, người ấy tạo ra nhiều điều bất thiện. ",
  "mn55:12.4": "Điều mà con vật ấy bị kéo cổ đến, cảm thấy đau khổ, buồn rầu, do trường hợp thứ hai này, người ấy tạo ra nhiều điều bất thiện. ",
  "mn55:12.5": "Điều mà người ấy nói: ",
  "mn55:12.6": "‘Hãy đi, giết hại con vật này’, do trường hợp thứ ba này, người ấy tạo ra nhiều điều bất thiện. ",
  "mn55:12.7": "Điều mà con vật ấy bị giết hại, cảm thấy đau khổ, buồn rầu, do trường hợp thứ tư này, người ấy tạo ra nhiều điều bất thiện. ",
  "mn55:12.8": "Điều mà người ấy làm ô uế Như Lai hay đệ tử của Như Lai bằng điều không hợp pháp, do trường hợp thứ năm này, người ấy tạo ra nhiều điều bất thiện. ",
  "mn55:12.9": "Này Jīvaka, ai giết hại sinh vật vì Như Lai hay vì đệ tử của Như Lai, người ấy tạo ra nhiều điều bất thiện do năm trường hợp này.” ",
  "mn55:13.1": "Khi được nói như vậy, Jīvaka Komārabhacca bạch Thế Tôn rằng: ",
  "mn55:13.2": "“Thật kỳ diệu thay, bạch Thế Tôn! Thật hy hữu thay, bạch Thế Tôn! ",
  "mn55:13.3": "Bạch Thế Tôn, các Tỳ-kheo thọ dụng thức ăn hợp pháp; ",
  "mn55:13.4": "bạch Thế Tôn, các Tỳ-kheo thọ dụng thức ăn không có lỗi. ",
  "mn55:13.5": "Tuyệt vời thay, bạch Thế Tôn! Tuyệt vời thay, bạch Thế Tôn! …pe… ",
  "mn55:13.6": "Xin Thế Tôn hãy nhận con làm cư sĩ, từ nay cho đến trọn đời, con xin quy y.” ",
  "mn55:13.7": "Kinh Jīvaka, thứ năm, chấm dứt. "
}
window.BILARA["mn55"]["vi"]["mn55:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
