window.BILARA = window.BILARA || {};
window.BILARA["mn66"] = window.BILARA["mn66"] || {};
window.BILARA["mn66"]["vi"] = {
  "mn66:0.1": "Trung Bộ Kinh 66 ",
  "mn66:0.2": "Kinh Ví Dụ Chim Cút ",
  "mn66:1.1": "Như vầy tôi nghe—",
  "mn66:1.2": "Một thời Thế Tôn trú ở xứ Anguttarāpa, tại thị trấn Āpaṇa của Anguttarāpa. ",
  "mn66:2.1": "Rồi Thế Tôn vào buổi sáng, đắp y, cầm bát, đi vào Āpaṇa để khất thực. ",
  "mn66:2.2": "Sau khi khất thực ở Āpaṇa, dùng bữa xong, Thế Tôn đi đến một khu rừng để nghỉ trưa. ",
  "mn66:2.3": "Đi sâu vào khu rừng ấy, Thế Tôn ngồi nghỉ trưa dưới gốc cây. ",
  "mn66:3.1": "Tôn giả Udāyī cũng vào buổi sáng, đắp y, cầm bát, đi vào Āpaṇa để khất thực. ",
  "mn66:3.2": "Sau khi khất thực ở Āpaṇa, dùng bữa xong, Tôn giả đi đến khu rừng ấy để nghỉ trưa. ",
  "mn66:3.3": "Đi sâu vào khu rừng ấy, Tôn giả ngồi nghỉ trưa dưới gốc cây. ",
  "mn66:3.4": "Rồi Tôn giả Udāyī, khi ở một mình, tĩnh lặng, tâm tư khởi lên ý nghĩ này: ",
  "mn66:4.1": "“Thật vậy, Thế Tôn đã loại bỏ nhiều pháp khổ cho chúng ta, Thế Tôn đã mang lại nhiều pháp an lạc cho chúng ta; ",
  "mn66:4.2": "Thật vậy, Thế Tôn đã loại bỏ nhiều pháp bất thiện cho chúng ta, Thế Tôn đã mang lại nhiều pháp thiện cho chúng ta.” ",
  "mn66:5.1": "Rồi Tôn giả Udāyī, vào buổi chiều, từ chỗ tĩnh lặng đứng dậy, đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Udāyī bạch Thế Tôn: ",
  "mn66:6.1": "“Bạch Thế Tôn, ở đây, khi con ở một mình, tĩnh lặng, tâm tư khởi lên ý nghĩ này: ",
  "mn66:6.2": "‘Thật vậy, Thế Tôn đã loại bỏ nhiều pháp khổ cho chúng ta, Thế Tôn đã mang lại nhiều pháp an lạc cho chúng ta; ",
  "mn66:6.3": "Thật vậy, Thế Tôn đã loại bỏ nhiều pháp bất thiện cho chúng ta, Thế Tôn đã mang lại nhiều pháp thiện cho chúng ta.’ ",
  "mn66:6.4": "Bạch Thế Tôn, trước đây chúng con ăn vào buổi chiều, buổi sáng và cả buổi trưa. ",
  "mn66:6.5": "Bạch Thế Tôn, có một thời Thế Tôn gọi các Tỳ-kheo và nói: ",
  "mn66:6.6": "‘Này các Tỳ-kheo, hãy từ bỏ bữa ăn phi thời vào ban ngày này.’ ",
  "mn66:6.7": "Bạch Thế Tôn, lúc ấy con cảm thấy khác lạ, con cảm thấy buồn rầu: ",
  "mn66:6.8": "‘Ngay cả món ăn ngon, thức uống ngon mà các gia chủ có lòng tin cúng dường cho chúng ta vào ban ngày, Thế Tôn cũng bảo chúng ta từ bỏ, Thiện Thệ cũng bảo chúng ta xả bỏ.’ ",
  "mn66:6.9": "Bạch Thế Tôn, chúng con vì thấy lòng yêu mến, kính trọng, hổ thẹn và sợ hãi đối với Thế Tôn, nên đã từ bỏ bữa ăn phi thời vào ban ngày ấy. ",
  "mn66:6.10": "Bạch Thế Tôn, chúng con ăn vào buổi chiều và buổi sáng. ",
  "mn66:6.11": "Bạch Thế Tôn, có một thời Thế Tôn gọi các Tỳ-kheo và nói: ",
  "mn66:6.12": "‘Này các Tỳ-kheo, hãy từ bỏ bữa ăn phi thời vào ban đêm này.’ ",
  "mn66:6.13": "Bạch Thế Tôn, lúc ấy con cảm thấy khác lạ, con cảm thấy buồn rầu: ",
  "mn66:6.14": "‘Ngay cả bữa ăn ngon hơn trong hai bữa này, Thế Tôn cũng bảo chúng ta từ bỏ, Thiện Thệ cũng bảo chúng ta xả bỏ.’ ",
  "mn66:6.15": "Bạch Thế Tôn, trước đây có một người đàn ông, ban ngày nhận được món canh, liền nói: ",
  "mn66:6.16": "‘Này, hãy cất món này đi, tối nay tất cả chúng ta sẽ cùng nhau ăn.’ ",
  "mn66:6.17": "Bạch Thế Tôn, tất cả những món ăn được chuẩn bị đều vào ban đêm, rất ít vào ban ngày. ",
  "mn66:6.18": "Bạch Thế Tôn, chúng con vì thấy lòng yêu mến, kính trọng, hổ thẹn và sợ hãi đối với Thế Tôn, nên đã từ bỏ bữa ăn phi thời vào ban đêm ấy. ",
  "mn66:6.19": "Bạch Thế Tôn, trước đây các Tỳ-kheo đi khất thực trong đêm tối mịt mùng, có khi bước vào cống rãnh, có khi rơi xuống hố phân, có khi leo lên hàng rào gai, có khi đụng phải bò đang ngủ, có khi gặp những người trẻ tuổi đã làm việc hoặc chưa làm việc, và phụ nữ cũng mời họ một cách không đúng pháp. ",
  "mn66:6.20": "Bạch Thế Tôn, trước đây con đi khất thực trong đêm tối mịt mùng. ",
  "mn66:6.21": "Bạch Thế Tôn, có một phụ nữ đang rửa bát trong khe cửa đã nhìn thấy con. ",
  "mn66:6.22": "Thấy con, cô ta sợ hãi và kêu lên: ",
  "mn66:6.23": "‘Ôi chao, đúng là quỷ sứ!’ ",
  "mn66:6.24": "Khi được nói như vậy, bạch Thế Tôn, con nói với người phụ nữ ấy: ",
  "mn66:6.25": "‘Này chị, tôi không phải quỷ sứ; ",
  "mn66:6.26": "tôi là Tỳ-kheo đang khất thực.’ ",
  "mn66:6.27": "‘Tỳ-kheo chết đi, mẹ của Tỳ-kheo chết đi. ",
  "mn66:6.28": "Thà rằng, này Tỳ-kheo, bụng của ông bị dao mổ bò sắc bén rạch ra, còn hơn là ông đi khất thực trong đêm tối mịt mùng vì cái bụng.’ ",
  "mn66:6.29": "Bạch Thế Tôn, khi con nhớ lại điều đó, con nghĩ: ",
  "mn66:6.30": "‘Thật vậy, Thế Tôn đã loại bỏ nhiều pháp khổ cho chúng ta, Thế Tôn đã mang lại nhiều pháp an lạc cho chúng ta; ",
  "mn66:6.31": "Thật vậy, Thế Tôn đã loại bỏ nhiều pháp bất thiện cho chúng ta, Thế Tôn đã mang lại nhiều pháp thiện cho chúng ta.’” ",
  "mn66:7.1": "“Cũng vậy, này Udāyī, ở đây một số người ngu si, khi được Ta bảo ‘Hãy từ bỏ điều này’, họ nói: ",
  "mn66:7.2": "‘Cái này có gì đáng kể, có gì nhỏ nhặt mà vị Sa-môn này lại quá khắt khe như vậy?’ ",
  "mn66:7.3": "Họ không từ bỏ điều đó, và còn gây ra sự bất tín đối với Ta. ",
  "mn66:7.4": "Và đối với những Tỳ-kheo muốn học hỏi, điều đó, này Udāyī, trở thành một sự ràng buộc mạnh mẽ, một sự ràng buộc chắc chắn, một sự ràng buộc kiên cố, một sự ràng buộc không mục nát, một sự ràng buộc thô thiển, một sự ràng buộc như khúc gỗ—",
  "mn66:8.1": "ví như, này Udāyī, một con chim cút bị trói bằng một sợi dây mục nát, nó sẽ phải chịu sự giết hại, sự giam cầm hoặc cái chết ngay tại đó. ",
  "mn66:8.2": "Này Udāyī, nếu có ai nói: ",
  "mn66:8.3": "‘Cái mà con chim cút bị trói bằng sợi dây mục nát, và nó phải chịu sự giết hại, sự giam cầm hoặc cái chết ngay tại đó, thì đó là một sự ràng buộc yếu ớt, một sự ràng buộc lỏng lẻo, một sự ràng buộc mục nát, một sự ràng buộc không cốt lõi’; ",
  "mn66:8.4": "người ấy, này Udāyī, nói có đúng không?” ",
  "mn66:8.5": "“Không đúng, bạch Thế Tôn. ",
  "mn66:8.6": "Cái mà con chim cút bị trói bằng sợi dây mục nát, và nó phải chịu sự giết hại, sự giam cầm hoặc cái chết ngay tại đó, thì đó là một sự ràng buộc mạnh mẽ, một sự ràng buộc chắc chắn, một sự ràng buộc kiên cố, một sự ràng buộc không mục nát, một sự ràng buộc thô thiển, một sự ràng buộc như khúc gỗ.” ",
  "mn66:8.7": "“Cũng vậy, này Udāyī, ở đây một số người ngu si, khi được Ta bảo ‘Hãy từ bỏ điều này’, họ nói: ",
  "mn66:8.8": "‘Cái này có gì đáng kể, có gì nhỏ nhặt mà vị Sa-môn này lại quá khắt khe như vậy?’ ",
  "mn66:8.9": "Họ không từ bỏ điều đó, và còn gây ra sự bất tín đối với Ta. ",
  "mn66:8.10": "Và đối với những Tỳ-kheo muốn học hỏi, điều đó, này Udāyī, trở thành một sự ràng buộc mạnh mẽ, một sự ràng buộc chắc chắn, một sự ràng buộc kiên cố, một sự ràng buộc không mục nát, một sự ràng buộc thô thiển, một sự ràng buộc như khúc gỗ. ",
  "mn66:9.1": "Nhưng ở đây, này Udāyī, một số thiện gia nam tử, khi được Ta bảo ‘Hãy từ bỏ điều này’, họ nói: ",
  "mn66:9.2": "‘Cái này có gì đáng kể, có gì nhỏ nhặt mà Thế Tôn bảo chúng ta từ bỏ, mà Thiện Thệ bảo chúng ta xả bỏ?’ ",
  "mn66:9.3": "Họ từ bỏ điều đó, và không gây ra sự bất tín đối với Ta. ",
  "mn66:9.4": "Và đối với những Tỳ-kheo muốn học hỏi, họ từ bỏ điều đó, sống không lo lắng, không còn lông dựng đứng, sống nhờ vật cúng dường của người khác, với tâm như loài thú. ",
  "mn66:9.5": "Đối với họ, điều đó, này Udāyī, trở thành một sự ràng buộc yếu ớt, một sự ràng buộc lỏng lẻo, một sự ràng buộc mục nát, một sự ràng buộc không cốt lõi—",
  "mn66:10.1": "ví như, này Udāyī, một con voi chúa của vua, có ngà như trục xe, đã trưởng thành, thuộc dòng dõi cao quý, quen chiến trận, bị trói bằng những sợi dây thừng chắc chắn, nó chỉ cần hơi co mình lại, liền cắt đứt và phá tan những sợi dây trói ấy, rồi đi đến nơi nó muốn. ",
  "mn66:10.2": "Này Udāyī, nếu có ai nói: ",
  "mn66:10.3": "‘Cái mà con voi chúa của vua, có ngà như trục xe, đã trưởng thành, thuộc dòng dõi cao quý, quen chiến trận, bị trói bằng những sợi dây thừng chắc chắn, nó chỉ cần hơi co mình lại, liền cắt đứt và phá tan những sợi dây trói ấy, rồi đi đến nơi nó muốn, thì đó là một sự ràng buộc mạnh mẽ, một sự ràng buộc chắc chắn, một sự ràng buộc kiên cố, một sự ràng buộc không mục nát, một sự ràng buộc thô thiển, một sự ràng buộc như khúc gỗ’; ",
  "mn66:10.4": "người ấy, này Udāyī, nói có đúng không?” ",
  "mn66:10.5": "“Không đúng, bạch Thế Tôn. ",
  "mn66:10.6": "Cái mà con voi chúa của vua, có ngà như trục xe, đã trưởng thành, thuộc dòng dõi cao quý, quen chiến trận, bị trói bằng những sợi dây thừng chắc chắn, nó chỉ cần hơi co mình lại, liền cắt đứt và phá tan những sợi dây trói ấy, rồi đi đến nơi nó muốn, thì đó là một sự ràng buộc yếu ớt… không cốt lõi.” ",
  "mn66:10.7": "“Cũng vậy, này Udāyī, ở đây một số thiện gia nam tử, khi được Ta bảo ‘Hãy từ bỏ điều này’, họ nói: ",
  "mn66:10.8": "‘Cái này có gì đáng kể, có gì nhỏ nhặt mà Thế Tôn bảo chúng ta từ bỏ, mà Thiện Thệ bảo chúng ta xả bỏ?’ ",
  "mn66:10.9": "Họ từ bỏ điều đó, và không gây ra sự bất tín đối với Ta. ",
  "mn66:10.10": "Và đối với những Tỳ-kheo muốn học hỏi, họ từ bỏ điều đó, sống không lo lắng, không còn lông dựng đứng, sống nhờ vật cúng dường của người khác, với tâm như loài thú. ",
  "mn66:10.11": "Đối với họ, điều đó, này Udāyī, trở thành một sự ràng buộc yếu ớt, một sự ràng buộc lỏng lẻo, một sự ràng buộc mục nát, một sự ràng buộc không cốt lõi. ",
  "mn66:11.1": "Ví như, này Udāyī, một người đàn ông nghèo khổ, không có tài sản, không có của cải; ",
  "mn66:11.2": "anh ta có một căn nhà xiêu vẹo, đổ nát, chim quạ bay vào được, không ra gì; một cái giường xiêu vẹo, đổ nát, không ra gì; một cái nồi đựng lúa không ra gì; một người vợ không ra gì. ",
  "mn66:11.3": "Anh ta thấy một Tỳ-kheo đang ở trong vườn, tay chân đã rửa sạch, đã dùng bữa ăn ngon, đang ngồi dưới bóng mát, tâm chuyên chú vào thiền định. ",
  "mn66:11.4": "Anh ta nghĩ: ",
  "mn66:11.5": "‘Ôi, đời sống Sa-môn thật an lạc, đời sống Sa-môn thật khỏe mạnh. ",
  "mn66:11.6": "Ước gì mình cũng cạo bỏ râu tóc, đắp y cà sa, từ bỏ gia đình, sống không gia đình, xuất gia.’ ",
  "mn66:11.7": "Anh ta không thể từ bỏ căn nhà xiêu vẹo, đổ nát, chim quạ bay vào được, không ra gì; không thể từ bỏ cái giường xiêu vẹo, đổ nát, không ra gì; không thể từ bỏ cái nồi đựng lúa không ra gì; không thể từ bỏ người vợ không ra gì, để cạo bỏ râu tóc, đắp y cà sa, từ bỏ gia đình, sống không gia đình, xuất gia. ",
  "mn66:11.8": "Này Udāyī, nếu có ai nói: ",
  "mn66:11.9": "‘Cái mà người đàn ông ấy bị trói buộc bởi những ràng buộc, không thể từ bỏ căn nhà xiêu vẹo, đổ nát, chim quạ bay vào được, không ra gì; không thể từ bỏ cái giường xiêu vẹo, đổ nát, không ra gì; không thể từ bỏ cái nồi đựng lúa không ra gì; không thể từ bỏ người vợ không ra gì, để cạo bỏ râu tóc, đắp y cà sa, từ bỏ gia đình, sống không gia đình, xuất gia; ",
  "mn66:11.10": "thì đó là một sự ràng buộc yếu ớt, một sự ràng buộc lỏng lẻo, một sự ràng buộc mục nát, một sự ràng buộc không cốt lõi’; ",
  "mn66:11.11": "người ấy, này Udāyī, nói có đúng không?” ",
  "mn66:11.12": "“Không đúng, bạch Thế Tôn. ",
  "mn66:11.13": "Cái mà người đàn ông ấy bị trói buộc bởi những ràng buộc, không thể từ bỏ căn nhà xiêu vẹo, đổ nát, chim quạ bay vào được, không ra gì; không thể từ bỏ cái giường xiêu vẹo, đổ nát, không ra gì; không thể từ bỏ cái nồi đựng lúa không ra gì; không thể từ bỏ người vợ không ra gì, để cạo bỏ râu tóc, đắp y cà sa, từ bỏ gia đình, sống không gia đình, xuất gia; ",
  "mn66:11.14": "thì đó là một sự ràng buộc mạnh mẽ, một sự ràng buộc chắc chắn, một sự ràng buộc kiên cố, một sự ràng buộc không mục nát, một sự ràng buộc thô thiển, một sự ràng buộc như khúc gỗ.” ",
  "mn66:11.15": "“Cũng vậy, này Udāyī, ở đây một số người ngu si, khi được Ta bảo ‘Hãy từ bỏ điều này’, họ nói: ",
  "mn66:11.16": "‘Cái này có gì đáng kể, có gì nhỏ nhặt mà vị Sa-môn này lại quá khắt khe như vậy?’ ",
  "mn66:11.17": "Họ không từ bỏ điều đó, và còn gây ra sự bất tín đối với Ta. ",
  "mn66:11.18": "Và đối với những Tỳ-kheo muốn học hỏi, điều đó, này Udāyī, trở thành một sự ràng buộc mạnh mẽ, một sự ràng buộc chắc chắn, một sự ràng buộc kiên cố, một sự ràng buộc không mục nát, một sự ràng buộc thô thiển, một sự ràng buộc như khúc gỗ. ",
  "mn66:12.1": "Ví như, này Udāyī, một gia chủ hoặc con của gia chủ, giàu có, nhiều tài sản, nhiều của cải, có nhiều kho vàng, nhiều kho lúa, nhiều ruộng đất, nhiều nhà cửa, nhiều vợ, nhiều nô lệ nam, nhiều nô lệ nữ; ",
  "mn66:12.2": "anh ta thấy một Tỳ-kheo đang ở trong vườn, tay chân đã rửa sạch, đã dùng bữa ăn ngon, đang ngồi dưới bóng mát, tâm chuyên chú vào thiền định. ",
  "mn66:12.3": "Anh ta nghĩ: ",
  "mn66:12.4": "‘Ôi, đời sống Sa-môn thật an lạc, đời sống Sa-môn thật khỏe mạnh. ",
  "mn66:12.5": "Ước gì mình cũng cạo bỏ râu tóc, đắp y cà sa, từ bỏ gia đình, sống không gia đình, xuất gia.’ ",
  "mn66:12.6": "Anh ta có thể từ bỏ nhiều kho vàng, nhiều kho lúa, nhiều ruộng đất, nhiều nhà cửa, nhiều vợ, nhiều nô lệ nam, nhiều nô lệ nữ, để cạo bỏ râu tóc, đắp y cà sa, từ bỏ gia đình, sống không gia đình, xuất gia. ",
  "mn66:12.7": "Này Udāyī, nếu có ai nói: ",
  "mn66:12.8": "‘Cái mà gia chủ hoặc con của gia chủ ấy bị trói buộc bởi những ràng buộc, có thể từ bỏ nhiều kho vàng, nhiều kho lúa, nhiều ruộng đất, nhiều nhà cửa, nhiều vợ, nhiều nô lệ nam, nhiều nô lệ nữ, để cạo bỏ râu tóc, đắp y cà sa, từ bỏ gia đình, sống không gia đình, xuất gia, thì đó là một sự ràng buộc mạnh mẽ, một sự ràng buộc chắc chắn, một sự ràng buộc kiên cố, một sự ràng buộc không mục nát, một sự ràng buộc thô thiển, một sự ràng buộc như khúc gỗ’; ",
  "mn66:12.9": "người ấy, này Udāyī, nói có đúng không?” ",
  "mn66:12.10": "“Không đúng, bạch Thế Tôn. ",
  "mn66:12.11": "Cái mà gia chủ hoặc con của gia chủ ấy bị trói buộc bởi những ràng buộc, có thể từ bỏ nhiều kho vàng, nhiều kho lúa, nhiều ruộng đất, nhiều nhà cửa, nhiều vợ, nhiều nô lệ nam, nhiều nô lệ nữ, để cạo bỏ râu tóc, đắp y cà sa, từ bỏ gia đình, sống không gia đình, xuất gia; ",
  "mn66:12.12": "thì đó là một sự ràng buộc yếu ớt, một sự ràng buộc lỏng lẻo, một sự ràng buộc mục nát, một sự ràng buộc không cốt lõi.” ",
  "mn66:12.13": "“Cũng vậy, này Udāyī, ở đây một số thiện gia nam tử, khi được Ta bảo ‘Hãy từ bỏ điều này’, họ nói: ",
  "mn66:12.14": "‘Cái này có gì đáng kể, có gì nhỏ nhặt mà Thế Tôn bảo chúng ta từ bỏ, mà Thiện Thệ bảo chúng ta xả bỏ?’ ",
  "mn66:12.15": "Họ từ bỏ điều đó, và không gây ra sự bất tín đối với Ta. ",
  "mn66:12.16": "Và đối với những Tỳ-kheo muốn học hỏi, họ từ bỏ điều đó, sống không lo lắng, không còn lông dựng đứng, sống nhờ vật cúng dường của người khác, với tâm như loài thú. ",
  "mn66:12.17": "Đối với họ, điều đó, này Udāyī, trở thành một sự ràng buộc yếu ớt, một sự ràng buộc lỏng lẻo, một sự ràng buộc mục nát, một sự ràng buộc không cốt lõi. ",
  "mn66:13.1": "Này Udāyī, có bốn hạng người hiện hữu, có mặt trên đời. ",
  "mn66:13.2": "Bốn hạng người nào? ",
  "mn66:14.1": "Ở đây, này Udāyī, có một người đang thực hành để từ bỏ các chấp thủ, để xả bỏ các chấp thủ. ",
  "mn66:14.2": "Khi người ấy đang thực hành để từ bỏ các chấp thủ, để xả bỏ các chấp thủ, những ý nghĩ liên quan đến chấp thủ khởi lên. ",
  "mn66:14.3": "Người ấy chấp nhận chúng, không từ bỏ, không xua đuổi, không làm cho chúng biến mất, không làm cho chúng không còn. ",
  "mn66:14.4": "Này Udāyī, Ta nói người này là ‘bị trói buộc’, chứ không phải ‘không bị trói buộc’. ",
  "mn66:14.5": "Vì sao? ",
  "mn66:14.6": "Vì Ta biết, này Udāyī, sự khác biệt về căn tính ở người này. ",
  "mn66:15.1": "Nhưng ở đây, này Udāyī, có một người đang thực hành để từ bỏ các chấp thủ, để xả bỏ các chấp thủ. ",
  "mn66:15.2": "Khi người ấy đang thực hành để từ bỏ các chấp thủ, để xả bỏ các chấp thủ, những ý nghĩ liên quan đến chấp thủ khởi lên. ",
  "mn66:15.3": "Người ấy không chấp nhận, từ bỏ, xua đuổi, chấm dứt, làm cho biến mất. ",
  "mn66:15.4": "Này Udayi, ta nói người này là ‘bị trói buộc’ chứ không phải ‘không bị trói buộc’. ",
  "mn66:15.5": "Vì sao vậy? ",
  "mn66:15.6": "Này Udayi, ta biết sự khác biệt về căn của người này. ",
  "mn66:16.1": "Ở đây, này Udayi, có người đang thực hành để từ bỏ chấp thủ, để xả bỏ chấp thủ. ",
  "mn66:16.2": "Khi người ấy đang thực hành để từ bỏ chấp thủ, để xả bỏ chấp thủ, đôi khi do sự lãng quên chánh niệm, những ý nghĩ liên quan đến chấp thủ khởi lên; ",
  "mn66:16.3": "này Udayi, sự khởi lên của chánh niệm chậm chạp. ",
  "mn66:16.4": "Nhưng rồi người ấy nhanh chóng từ bỏ, xua đuổi, chấm dứt, làm cho biến mất. ",
  "mn66:16.5": "Ví như, này Udayi, một người nhỏ hai hoặc ba giọt nước vào một chảo sắt đã nung nóng cả ngày; ",
  "mn66:16.6": "này Udayi, sự nhỏ giọt của nước chậm chạp. Nhưng rồi chúng nhanh chóng cạn kiệt, biến mất. ",
  "mn66:16.7": "Cũng vậy, này Udayi, ở đây có người đang thực hành để từ bỏ chấp thủ, để xả bỏ chấp thủ. ",
  "mn66:16.8": "Khi người ấy đang thực hành để từ bỏ chấp thủ, để xả bỏ chấp thủ, đôi khi do sự lãng quên chánh niệm, những ý nghĩ liên quan đến chấp thủ khởi lên; ",
  "mn66:16.9": "này Udayi, sự khởi lên của chánh niệm chậm chạp. ",
  "mn66:16.10": "Nhưng rồi người ấy nhanh chóng từ bỏ, xua đuổi, chấm dứt, làm cho biến mất. ",
  "mn66:16.11": "Này Udayi, ta nói người này là ‘bị trói buộc’ chứ không phải ‘không bị trói buộc’. ",
  "mn66:16.12": "Vì sao vậy? ",
  "mn66:16.13": "Này Udayi, ta biết sự khác biệt về căn của người này. ",
  "mn66:17.1": "Ở đây, này Udayi, có người biết rằng ‘chấp thủ là gốc rễ của khổ’—",
  "mn66:17.2": "như vậy, và trở thành không chấp thủ, giải thoát khi chấp thủ đã diệt. ",
  "mn66:17.3": "Này Udayi, ta nói người này là ‘không bị trói buộc’ chứ không phải ‘bị trói buộc’. ",
  "mn66:17.4": "Vì sao vậy? ",
  "mn66:17.5": "Này Udayi, ta biết sự khác biệt về căn của người này. ",
  "mn66:17.6": "Này Udayi, bốn hạng người này có mặt, hiện hữu trên đời. ",
  "mn66:18.1": "Này Udayi, có năm dục công đức này. ",
  "mn66:18.2": "Thế nào là năm? ",
  "mn66:18.3": "Các sắc do mắt nhận biết, đáng ưa, đáng thích, đáng mến, đáng yêu, liên hệ đến dục, gợi dục; ",
  "mn66:18.4": "các tiếng do tai nhận biết …v.v… ",
  "mn66:18.5": "các mùi do mũi nhận biết … ",
  "mn66:18.6": "các vị do lưỡi nhận biết … ",
  "mn66:18.7": "các xúc chạm do thân nhận biết, đáng ưa, đáng thích, đáng mến, đáng yêu, liên hệ đến dục, gợi dục. ",
  "mn66:18.8": "Này Udayi, đây là năm dục công đức. ",
  "mn66:19.1": "Này Udayi, sự lạc và hỷ phát sinh do duyên năm dục công đức này, được gọi là dục lạc, lạc của sự dơ bẩn, lạc của phàm phu, lạc không thánh thiện, không nên tìm cầu, không nên tu tập, không nên làm cho sung mãn; ta nói rằng ‘nên sợ hãi lạc này’. ",
  "mn66:20.1": "Ở đây, này Udayi, một tỳ khưu ly dục …v.v… chứng và trú thiền thứ nhất ",
  "mn66:20.2": "do sự lắng dịu của tầm và tứ …v.v… chứng và trú thiền thứ hai, ",
  "mn66:20.3": "do sự ly hỷ …v.v… chứng và trú thiền thứ ba, ",
  "mn66:20.4": "do sự từ bỏ lạc …v.v… chứng và trú thiền thứ tư. ",
  "mn66:21.1": "Đây được gọi là lạc xuất ly, lạc viễn ly, lạc tịch tịnh, lạc giác ngộ, nên tìm cầu, nên tu tập, nên làm cho sung mãn; ta nói rằng ‘không nên sợ hãi lạc này’. ",
  "mn66:22.1": "Ở đây, này Udayi, một tỳ khưu ly dục …v.v… chứng và trú thiền thứ nhất; ",
  "mn66:22.2": "này Udayi, ta nói điều này là có sự lay động. ",
  "mn66:22.3": "Và điều gì ở đó là có sự lay động? ",
  "mn66:22.4": "Chính là tầm và tứ ở đó chưa diệt, đây là sự lay động ở đó. ",
  "mn66:23.1": "Ở đây, này Udayi, một tỳ khưu do sự lắng dịu của tầm và tứ …v.v… chứng và trú thiền thứ hai; ",
  "mn66:23.2": "này Udayi, ta cũng nói điều này là có sự lay động. ",
  "mn66:23.3": "Và điều gì ở đó là có sự lay động? ",
  "mn66:23.4": "Chính là hỷ và lạc ở đó chưa diệt, đây là sự lay động ở đó. ",
  "mn66:24.1": "Ở đây, này Udayi, một tỳ khưu do sự ly hỷ …v.v… chứng và trú thiền thứ ba; ",
  "mn66:24.2": "này Udayi, ta cũng nói điều này là có sự lay động. ",
  "mn66:24.3": "Và điều gì ở đó là có sự lay động? ",
  "mn66:24.4": "Chính là xả và lạc ở đó chưa diệt, đây là sự lay động ở đó. ",
  "mn66:25.1": "Ở đây, này Udayi, một tỳ khưu do sự từ bỏ lạc …v.v… chứng và trú thiền thứ tư; ",
  "mn66:25.2": "này Udayi, ta nói điều này là không có sự lay động. ",
  "mn66:26.1": "Ở đây, này Udayi, một tỳ khưu ly dục …v.v… chứng và trú thiền thứ nhất; ",
  "mn66:26.2": "này Udayi, ta nói điều này là ‘chưa đủ’, ta nói ‘hãy từ bỏ’, ta nói ‘hãy vượt qua’. ",
  "mn66:26.3": "Và sự vượt qua của điều đó là gì? ",
  "mn66:27.1": "Ở đây, này Udayi, một tỳ khưu do sự lắng dịu của tầm và tứ …v.v… chứng và trú thiền thứ hai, đây là sự vượt qua của điều đó; ",
  "mn66:27.2": "này Udayi, ta cũng nói điều này là ‘chưa đủ’, ta nói ‘hãy từ bỏ’, ta nói ‘hãy vượt qua’. ",
  "mn66:27.3": "Và sự vượt qua của điều đó là gì? ",
  "mn66:28.1": "Ở đây, này Udayi, một tỳ khưu do sự ly hỷ …v.v… chứng và trú thiền thứ ba, đây là sự vượt qua của điều đó; ",
  "mn66:28.2": "này Udayi, ta cũng nói điều này là ‘chưa đủ’, ta nói ‘hãy từ bỏ’, ta nói ‘hãy vượt qua’. ",
  "mn66:28.3": "Và sự vượt qua của điều đó là gì? ",
  "mn66:29.1": "Ở đây, này Udayi, một tỳ khưu do sự từ bỏ lạc …v.v… chứng và trú thiền thứ tư, đây là sự vượt qua của điều đó; ",
  "mn66:29.2": "này Udayi, ta cũng nói điều này là ‘chưa đủ’, ta nói ‘hãy từ bỏ’, ta nói ‘hãy vượt qua’. ",
  "mn66:29.3": "Và sự vượt qua của điều đó là gì? ",
  "mn66:30.1": "Ở đây, này Udayi, một tỳ khưu do hoàn toàn vượt qua các tưởng về sắc, do sự diệt mất các tưởng về đối ngại, do không tác ý các tưởng về sai biệt, với ý nghĩ ‘không gian là vô biên’, chứng và trú không vô biên xứ, đây là sự vượt qua của điều đó; ",
  "mn66:30.2": "này Udayi, ta cũng nói điều này là ‘chưa đủ’, ta nói ‘hãy từ bỏ’, ta nói ‘hãy vượt qua’. ",
  "mn66:30.3": "Và sự vượt qua của điều đó là gì? ",
  "mn66:31.1": "Ở đây, này Udayi, một tỳ khưu do hoàn toàn vượt qua không vô biên xứ, với ý nghĩ ‘thức là vô biên’, chứng và trú thức vô biên xứ, đây là sự vượt qua của điều đó; ",
  "mn66:31.2": "này Udayi, ta cũng nói điều này là ‘chưa đủ’, ta nói ‘hãy từ bỏ’, ta nói ‘hãy vượt qua’. ",
  "mn66:31.3": "Và sự vượt qua của điều đó là gì? ",
  "mn66:32.1": "Ở đây, này Udayi, một tỳ khưu do hoàn toàn vượt qua thức vô biên xứ, với ý nghĩ ‘không có gì cả’, chứng và trú vô sở hữu xứ, đây là sự vượt qua của điều đó; ",
  "mn66:32.2": "này Udayi, ta cũng nói điều này là ‘chưa đủ’, ta nói ‘hãy từ bỏ’, ta nói ‘hãy vượt qua’. ",
  "mn66:32.3": "Và sự vượt qua của điều đó là gì? ",
  "mn66:33.1": "Ở đây, này Udayi, một tỳ khưu do hoàn toàn vượt qua vô sở hữu xứ, chứng và trú phi tưởng phi phi tưởng xứ, đây là sự vượt qua của điều đó; ",
  "mn66:33.2": "này Udayi, ta cũng nói điều này là ‘chưa đủ’, ta nói ‘hãy từ bỏ’, ta nói ‘hãy vượt qua’. ",
  "mn66:33.3": "Và sự vượt qua của điều đó là gì? ",
  "mn66:34.1": "Ở đây, này Udayi, một tỳ khưu do hoàn toàn vượt qua phi tưởng phi phi tưởng xứ, chứng và trú diệt thọ tưởng định, đây là sự vượt qua của điều đó; ",
  "mn66:34.2": "như vậy, này Udayi, ta nói đến sự từ bỏ ngay cả phi tưởng phi phi tưởng xứ. ",
  "mn66:34.3": "Này Udayi, ông có thấy một kiết sử nào dù nhỏ hay lớn mà ta không nói đến sự từ bỏ không?” ",
  "mn66:34.4": "“Không có, bạch Thế Tôn.” ",
  "mn66:34.5": "Thế Tôn đã nói như vậy. ",
  "mn66:34.6": "Tôn giả Udayi hoan hỷ tán thán lời Thế Tôn đã nói. ",
  "mn66:34.7": "Kinh Ví Dụ Chim Cút, thứ sáu, chấm dứt."
}
window.BILARA["mn66"]["vi"]["mn66:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
