window.BILARA = window.BILARA || {};
window.BILARA["mn70"] = window.BILARA["mn70"] || {};
window.BILARA["mn70"]["vi"] = {
  "mn70:0.1": "Trung Bộ Kinh 70 ",
  "mn70:0.2": "Kinh Kīṭāgiri ",
  "mn70:1.1": "Tôi nghe như vầy—",
  "mn70:1.2": "Một thời, Thế Tôn du hành trong xứ Kāsī với đại chúng Tỳ-kheo. ",
  "mn70:1.3": "Tại đấy, Thế Tôn gọi các Tỳ-kheo: ",
  "mn70:2.1": "“Này các Tỳ-kheo, Ta không ăn sau giờ ngọ. ",
  "mn70:2.2": "Này các Tỳ-kheo, khi không ăn sau giờ ngọ, Ta cảm thấy ít bệnh, ít khổ, nhẹ nhàng, có sức lực và sống an lạc. ",
  "mn70:2.3": "Này các Tỳ-kheo, các con cũng hãy không ăn sau giờ ngọ. ",
  "mn70:2.4": "Này các Tỳ-kheo, khi các con không ăn sau giờ ngọ, các con cũng sẽ cảm thấy ít bệnh, ít khổ, nhẹ nhàng, có sức lực và sống an lạc.” ",
  "mn70:2.5": "“Thưa vâng, bạch Thế Tôn,” các Tỳ-kheo ấy vâng lời Thế Tôn. ",
  "mn70:3.1": "Rồi Thế Tôn, tuần tự du hành trong xứ Kāsī, đến một thị trấn của dân Kāsī tên là Kīṭāgiri. ",
  "mn70:3.2": "Tại đấy, Thế Tôn trú ở Kīṭāgiri, thị trấn của dân Kāsī. ",
  "mn70:4.1": "Lúc bấy giờ, các Tỳ-kheo tên là Assaji và Punabbasu đang trú tại Kīṭāgiri. ",
  "mn70:4.2": "Rồi nhiều Tỳ-kheo đi đến chỗ các Tỳ-kheo Assaji và Punabbasu; sau khi đến, họ nói với các Tỳ-kheo Assaji và Punabbasu rằng: ",
  "mn70:4.3": "“Này các Hiền giả, Thế Tôn không ăn sau giờ ngọ, và Tăng đoàn cũng vậy. ",
  "mn70:4.4": "Này các Hiền giả, khi không ăn sau giờ ngọ, họ cảm thấy ít bệnh, ít khổ, nhẹ nhàng, có sức lực và sống an lạc. ",
  "mn70:4.5": "Này các Hiền giả, các con cũng hãy không ăn sau giờ ngọ. ",
  "mn70:4.6": "Này các Hiền giả, khi các con không ăn sau giờ ngọ, các con cũng sẽ cảm thấy ít bệnh, ít khổ, nhẹ nhàng, có sức lực và sống an lạc.” ",
  "mn70:4.7": "Khi được nói vậy, các Tỳ-kheo Assaji và Punabbasu nói với các Tỳ-kheo ấy rằng: ",
  "mn70:4.8": "“Này các Hiền giả, chúng tôi ăn vào buổi chiều, buổi sáng, ban ngày và vào lúc phi thời. ",
  "mn70:4.9": "Khi chúng tôi ăn vào buổi chiều, buổi sáng, ban ngày và vào lúc phi thời, chúng tôi cảm thấy ít bệnh, ít khổ, nhẹ nhàng, có sức lực và sống an lạc. ",
  "mn70:4.10": "Chúng tôi sẽ từ bỏ điều thấy rõ mà chạy theo điều không thấy rõ sao? ",
  "mn70:4.11": "Chúng tôi sẽ ăn vào buổi chiều, buổi sáng, ban ngày và vào lúc phi thời.” ",
  "mn70:5.1": "Khi các Tỳ-kheo ấy không thể thuyết phục được các Tỳ-kheo Assaji và Punabbasu, họ đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, các Tỳ-kheo ấy nói với Thế Tôn rằng: ",
  "mn70:5.2": "“Bạch Thế Tôn, ở đây chúng con đã đi đến chỗ các Tỳ-kheo Assaji và Punabbasu; sau khi đến, chúng con đã nói với các Tỳ-kheo Assaji và Punabbasu rằng: ",
  "mn70:5.3": "‘Này các Hiền giả, Thế Tôn không ăn sau giờ ngọ, và Tăng đoàn cũng vậy; ",
  "mn70:5.4": "này các Hiền giả, khi không ăn sau giờ ngọ, họ cảm thấy ít bệnh, ít khổ, nhẹ nhàng, có sức lực và sống an lạc. ",
  "mn70:5.5": "Này các Hiền giả, các con cũng hãy không ăn sau giờ ngọ. ",
  "mn70:5.6": "Này các Hiền giả, khi các con không ăn sau giờ ngọ, các con cũng sẽ cảm thấy ít bệnh, ít khổ, nhẹ nhàng, có sức lực và sống an lạc.’ ",
  "mn70:5.7": "Bạch Thế Tôn, khi được nói vậy, các Tỳ-kheo Assaji và Punabbasu đã nói với chúng con rằng: ",
  "mn70:5.8": "‘Này các Hiền giả, chúng tôi ăn vào buổi chiều, buổi sáng, ban ngày và vào lúc phi thời. ",
  "mn70:5.9": "Khi chúng tôi ăn vào buổi chiều, buổi sáng, ban ngày và vào lúc phi thời, chúng tôi cảm thấy ít bệnh, ít khổ, nhẹ nhàng, có sức lực và sống an lạc. ",
  "mn70:5.10": "Chúng tôi sẽ từ bỏ điều thấy rõ mà chạy theo điều không thấy rõ sao? ",
  "mn70:5.11": "Chúng tôi sẽ ăn vào buổi chiều, buổi sáng, ban ngày và vào lúc phi thời.’ ",
  "mn70:5.12": "Bạch Thế Tôn, vì chúng con không thể thuyết phục được các Tỳ-kheo Assaji và Punabbasu, nên chúng con đã trình bày việc này lên Thế Tôn.” ",
  "mn70:6.1": "Rồi Thế Tôn gọi một Tỳ-kheo khác: ",
  "mn70:6.2": "“Này Tỳ-kheo, con hãy đi, nhân danh Ta mà gọi các Tỳ-kheo Assaji và Punabbasu: ",
  "mn70:6.3": "‘Thầy gọi các Hiền giả.’” ",
  "mn70:6.4": "“Thưa vâng, bạch Thế Tôn,” Tỳ-kheo ấy vâng lời Thế Tôn, đi đến chỗ các Tỳ-kheo Assaji và Punabbasu; sau khi đến, nói với các Tỳ-kheo Assaji và Punabbasu rằng: ",
  "mn70:6.5": "“Thầy gọi các Hiền giả.” ",
  "mn70:6.6": "“Thưa vâng, Hiền giả,” các Tỳ-kheo Assaji và Punabbasu vâng lời Tỳ-kheo ấy, đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Khi các Tỳ-kheo Assaji và Punabbasu ngồi xuống một bên, Thế Tôn nói với họ rằng: ",
  "mn70:6.7": "“Này các Tỳ-kheo, có thật là nhiều Tỳ-kheo đã đến chỗ các con và nói rằng: ",
  "mn70:6.8": "‘Này các Hiền giả, Thế Tôn không ăn sau giờ ngọ, và Tăng đoàn cũng vậy. ",
  "mn70:6.9": "Này các Hiền giả, khi không ăn sau giờ ngọ, họ cảm thấy ít bệnh, ít khổ, nhẹ nhàng, có sức lực và sống an lạc. ",
  "mn70:6.10": "Này các Hiền giả, các con cũng hãy không ăn sau giờ ngọ. ",
  "mn70:6.11": "Này các Hiền giả, khi các con không ăn sau giờ ngọ, các con cũng sẽ cảm thấy ít bệnh, ít khổ, nhẹ nhàng, có sức lực và sống an lạc.’ ",
  "mn70:6.12": "Này các Tỳ-kheo, có thật là khi được nói vậy, các con đã nói với các Tỳ-kheo ấy rằng: ",
  "mn70:6.13": "‘Này các Hiền giả, chúng tôi ăn vào buổi chiều, buổi sáng, ban ngày và vào lúc phi thời. ",
  "mn70:6.14": "Khi chúng tôi ăn vào buổi chiều, buổi sáng, ban ngày và vào lúc phi thời, chúng tôi cảm thấy ít bệnh, ít khổ, nhẹ nhàng, có sức lực và sống an lạc. ",
  "mn70:6.15": "Chúng tôi sẽ từ bỏ điều thấy rõ mà chạy theo điều không thấy rõ sao? ",
  "mn70:6.16": "Chúng tôi sẽ ăn vào buổi chiều, buổi sáng, ban ngày và vào lúc phi thời.’ ” ",
  "mn70:6.17": "“Thưa vâng, bạch Thế Tôn.” ",
  "mn70:6.18": "“Này các Tỳ-kheo, các con có hiểu giáo pháp Ta đã dạy như thế này không: ‘Bất cứ điều gì mà người này cảm nhận, dù là lạc, khổ, hay không khổ không lạc, thì các pháp bất thiện của người ấy suy giảm, các pháp thiện của người ấy tăng trưởng’?” ",
  "mn70:6.19": "“Không phải vậy, bạch Thế Tôn.” ",
  "mn70:7.1": "“Này các Tỳ-kheo, các con có hiểu giáo pháp Ta đã dạy như thế này không: ‘Ở đây, đối với một số người, khi cảm nhận một cảm thọ lạc như vậy, các pháp bất thiện tăng trưởng, các pháp thiện suy giảm; nhưng ở đây, đối với một số người khác, khi cảm nhận một cảm thọ lạc như vậy, các pháp bất thiện suy giảm, các pháp thiện tăng trưởng. Ở đây, đối với một số người, khi cảm nhận một cảm thọ khổ như vậy, các pháp bất thiện tăng trưởng, các pháp thiện suy giảm; nhưng ở đây, đối với một số người khác, khi cảm nhận một cảm thọ khổ như vậy, các pháp bất thiện suy giảm, các pháp thiện tăng trưởng. Ở đây, đối với một số người, khi cảm nhận một cảm thọ không khổ không lạc như vậy, các pháp bất thiện tăng trưởng, các pháp thiện suy giảm; nhưng ở đây, đối với một số người khác, khi cảm nhận một cảm thọ không khổ không lạc như vậy, các pháp bất thiện suy giảm, các pháp thiện tăng trưởng’?” ",
  "mn70:7.2": "“Thưa vâng, bạch Thế Tôn.” ",
  "mn70:8.1": "“Lành thay, này các Tỳ-kheo. ",
  "mn70:8.2": "Này các Tỳ-kheo, nếu điều này Ta chưa biết, chưa thấy, chưa hiểu, chưa chứng ngộ, chưa cảm nhận bằng trí tuệ: ",
  "mn70:8.3": "‘Ở đây, đối với một số người, khi cảm nhận một cảm thọ lạc như vậy, các pháp bất thiện tăng trưởng, các pháp thiện suy giảm,’ ",
  "mn70:8.4": "thì Ta, khi chưa biết như vậy, có nên nói: ‘Hãy từ bỏ cảm thọ lạc như vậy’ không? Này các Tỳ-kheo, điều đó có phù hợp với Ta không?” ",
  "mn70:8.5": "“Không phải vậy, bạch Thế Tôn.” ",
  "mn70:8.6": "“Này các Tỳ-kheo, vì điều này Ta đã biết, đã thấy, đã hiểu, đã chứng ngộ, đã cảm nhận bằng trí tuệ: ",
  "mn70:8.7": "‘Ở đây, đối với một số người, khi cảm nhận một cảm thọ lạc như vậy, các pháp bất thiện tăng trưởng, các pháp thiện suy giảm,’ do đó Ta nói: ‘Hãy từ bỏ cảm thọ lạc như vậy.’ ",
  "mn70:8.8": "Này các Tỳ-kheo, nếu điều này Ta chưa biết, chưa thấy, chưa hiểu, chưa chứng ngộ, chưa cảm nhận bằng trí tuệ: ",
  "mn70:8.9": "‘Ở đây, đối với một số người, khi cảm nhận một cảm thọ lạc như vậy, các pháp bất thiện suy giảm, các pháp thiện tăng trưởng,’ thì Ta, khi chưa biết như vậy, có nên nói: ‘Hãy an trú trong cảm thọ lạc như vậy’ không? ",
  "mn70:8.10": "Này các Tỳ-kheo, điều đó có phù hợp với Ta không?” ",
  "mn70:8.11": "“Không phải vậy, bạch Thế Tôn.” ",
  "mn70:8.12": "“Này các Tỳ-kheo, vì điều này Ta đã biết, đã thấy, đã hiểu, đã chứng ngộ, đã cảm nhận bằng trí tuệ: ",
  "mn70:8.13": "‘Ở đây, đối với một số người, khi cảm nhận một cảm thọ lạc như vậy, các pháp bất thiện suy giảm, các pháp thiện tăng trưởng,’ do đó Ta nói: ‘Hãy an trú trong cảm thọ lạc như vậy.’ ",
  "mn70:8.14": "Này các Tỳ-kheo, nếu điều này Ta chưa biết, chưa thấy, chưa hiểu, chưa chứng ngộ, chưa cảm nhận bằng trí tuệ: ",
  "mn70:8.15": "‘Ở đây, đối với một số người, khi cảm nhận một cảm thọ khổ như vậy, các pháp bất thiện tăng trưởng, các pháp thiện suy giảm,’ thì Ta, khi chưa biết như vậy, có nên nói: ‘Hãy từ bỏ cảm thọ khổ như vậy’ không? ",
  "mn70:8.16": "Này các Tỳ-kheo, điều đó có phù hợp với Ta không?” ",
  "mn70:8.17": "“Không phải vậy, bạch Thế Tôn.” ",
  "mn70:9.1": "“Này các Tỳ-kheo, vì điều này Ta đã biết, đã thấy, đã hiểu, đã chứng ngộ, đã cảm nhận bằng trí tuệ: ",
  "mn70:9.2": "‘Ở đây, đối với một số người, khi cảm nhận một cảm thọ khổ như vậy, các pháp bất thiện tăng trưởng, các pháp thiện suy giảm,’ do đó Ta nói: ‘Hãy từ bỏ cảm thọ khổ như vậy.’ ",
  "mn70:9.3": "Này các Tỳ-kheo, nếu điều này Ta chưa biết, chưa thấy, chưa hiểu, chưa chứng ngộ, chưa cảm nhận bằng trí tuệ: ",
  "mn70:9.4": "‘Ở đây, đối với một số người, khi cảm nhận một cảm thọ khổ như vậy, các pháp bất thiện suy giảm, các pháp thiện tăng trưởng,’ thì Ta, khi chưa biết như vậy, có nên nói: ‘Hãy an trú trong cảm thọ khổ như vậy’ không? ",
  "mn70:9.5": "Này các Tỳ-kheo, điều đó có phù hợp với Ta không?” ",
  "mn70:9.6": "“Không phải vậy, bạch Thế Tôn.” ",
  "mn70:9.7": "“Này các Tỳ-kheo, vì điều này Ta đã biết, đã thấy, đã hiểu, đã chứng ngộ, đã cảm nhận bằng trí tuệ: ",
  "mn70:9.8": "‘Ở đây, đối với một số người, khi cảm nhận một cảm thọ khổ như vậy, các pháp bất thiện suy giảm, các pháp thiện tăng trưởng,’ do đó Ta nói: ‘Hãy an trú trong cảm thọ khổ như vậy.’ ",
  "mn70:10.1": "Này các Tỳ-kheo, nếu điều này Ta chưa biết, chưa thấy, chưa hiểu, chưa chứng ngộ, chưa cảm nhận bằng trí tuệ: ",
  "mn70:10.2": "‘Ở đây, đối với một số người, khi cảm nhận một cảm thọ không khổ không lạc như vậy, các pháp bất thiện tăng trưởng, các pháp thiện suy giảm,’ thì Ta, khi chưa biết như vậy, có nên nói: ‘Hãy từ bỏ cảm thọ không khổ không lạc như vậy’ không? ",
  "mn70:10.3": "Này các Tỳ-kheo, điều đó có phù hợp với Ta không?” ",
  "mn70:10.4": "“Không phải vậy, bạch Thế Tôn.” ",
  "mn70:10.5": "“Này các Tỳ-kheo, vì điều này Ta đã biết, đã thấy, đã hiểu, đã chứng ngộ, đã cảm nhận bằng trí tuệ: ",
  "mn70:10.6": "‘Ở đây, đối với một số người, khi cảm nhận một cảm thọ không khổ không lạc như vậy, các pháp bất thiện tăng trưởng, các pháp thiện suy giảm,’ do đó Ta nói: ‘Hãy từ bỏ cảm thọ không khổ không lạc như vậy.’ ",
  "mn70:10.7": "Này các Tỳ-kheo, nếu điều này Ta chưa biết, chưa thấy, chưa hiểu, chưa chứng ngộ, chưa cảm nhận bằng trí tuệ: ",
  "mn70:10.8": "‘Ở đây, đối với một số người, khi cảm nhận một cảm thọ không khổ không lạc như vậy, các pháp bất thiện suy giảm, các pháp thiện tăng trưởng,’ thì Ta, khi chưa biết như vậy, có nên nói: ‘Hãy an trú trong cảm thọ không khổ không lạc như vậy’ không? ",
  "mn70:10.9": "Này các Tỳ-kheo, điều đó có phù hợp với Ta không?” ",
  "mn70:10.10": "“Không phải vậy, bạch Thế Tôn.” ",
  "mn70:11.1": "“Này các Tỳ-kheo, vì điều này Ta đã biết, đã thấy, đã hiểu, đã chứng ngộ, đã cảm nhận bằng trí tuệ: ",
  "mn70:11.2": "‘Ở đây, đối với một số người, khi cảm nhận một cảm thọ không khổ không lạc như vậy, các pháp bất thiện suy giảm, các pháp thiện tăng trưởng,’ do đó Ta nói: ‘Hãy an trú trong cảm thọ không khổ không lạc như vậy.’ ",
  "mn70:12.1": "Này các Tỳ-kheo, Ta không nói rằng ‘tất cả các Tỳ-kheo đều cần phải tinh tấn’; ",
  "mn70:12.2": "nhưng Ta cũng không nói rằng ‘tất cả các Tỳ-kheo đều không cần phải tinh tấn’. ",
  "mn70:12.3": "Này các Tỳ-kheo, những Tỳ-kheo nào là A-la-hán, các lậu hoặc đã tận, đã sống phạm hạnh, đã làm những việc cần làm, đã đặt gánh nặng xuống, đã đạt được mục đích của mình, đã đoạn tận các kiết sử của đời sống, đã giải thoát hoàn toàn nhờ chánh trí, đối với những Tỳ-kheo như vậy, Ta nói rằng ‘không cần phải tinh tấn’. ",
  "mn70:12.4": "Vì sao? ",
  "mn70:12.5": "Họ đã làm xong việc tinh tấn. ",
  "mn70:12.6": "Họ không thể lơ là. ",
  "mn70:13.1": "Này các Tỳ-kheo, những Tỳ-kheo nào là bậc Hữu học, tâm chưa đạt được, đang mong cầu sự an ổn vô thượng khỏi các ách nạn, đối với những Tỳ-kheo như vậy, Ta nói rằng ‘cần phải tinh tấn’. ",
  "mn70:13.2": "Vì sao? ",
  "mn70:13.3": "Mong rằng các Hiền giả này, khi thực hành các chỗ ở thuận lợi, thân cận bạn lành, điều hòa các căn—",
  "mn70:13.4": "vì mục đích mà các thiện nam tử đã xuất gia từ bỏ gia đình để sống không gia đình, tức là sự chấm dứt vô thượng của phạm hạnh—họ sẽ tự mình chứng ngộ, thực chứng và an trú ngay trong hiện tại. ",
  "mn70:13.5": "Này các Tỳ-kheo, khi thấy được quả lợi của sự tinh tấn cho những Tỳ-kheo này, Ta nói rằng ‘cần phải tinh tấn’. ",
  "mn70:14.1": "Này các Tỳ-kheo, có bảy hạng người hiện hữu, có mặt trên đời. ",
  "mn70:14.2": "Bảy hạng nào? ",
  "mn70:14.3": "Giải thoát cả hai phần, Giải thoát bằng trí tuệ, Thân chứng, Đạt được kiến giải, Giải thoát bằng niềm tin, Tùy pháp hành, Tùy tín hành. ",
  "mn70:15.1": "Này các Tỳ-kheo, thế nào là người Giải thoát cả hai phần? ",
  "mn70:15.2": "Ở đây, này các Tỳ-kheo, có người nào đó, sau khi vượt qua các giải thoát an tịnh, các vô sắc, vị ấy an trú bằng cách thân chứng chúng, và các lậu hoặc của vị ấy đã được đoạn tận sau khi thấy bằng trí tuệ. ",
  "mn70:15.3": "Này các Tỳ-kheo, người này được gọi là Giải thoát cả hai phần. ",
  "mn70:15.4": "Này các Tỳ-kheo, đối với Tỳ-kheo này, Ta nói rằng ‘không cần phải tinh tấn’. ",
  "mn70:15.5": "Vì sao? ",
  "mn70:15.6": "Vị ấy đã làm xong việc tinh tấn. ",
  "mn70:15.7": "Vị ấy không thể lơ là. ",
  "mn70:16.1": "Này các Tỳ-kheo, thế nào là người Giải thoát bằng trí tuệ? ",
  "mn70:16.2": "Ở đây, này các Tỳ-kheo, có người nào đó, sau khi vượt qua các giải thoát an tịnh, các vô sắc, vị ấy không an trú bằng cách thân chứng chúng, nhưng các lậu hoặc của vị ấy đã được đoạn tận sau khi thấy bằng trí tuệ. ",
  "mn70:16.3": "Này các Tỳ-kheo, người này được gọi là Giải thoát bằng trí tuệ. ",
  "mn70:16.4": "Này các Tỳ-kheo, đối với Tỳ-kheo này, Ta cũng nói rằng ‘không cần phải tinh tấn’. ",
  "mn70:16.5": "Vì sao? ",
  "mn70:16.6": "Vị ấy đã làm xong việc tinh tấn. ",
  "mn70:16.7": "Người ấy không thể lơ là. ",
  "mn70:17.1": "Và này các Tỳ-kheo, thế nào là người thân chứng? ",
  "mn70:17.2": "Ở đây, này các Tỳ-kheo, có người nào đó, những giải thoát an tịnh, vượt qua sắc, thuộc vô sắc, người ấy thân chứng và an trú, và sau khi thấy với trí tuệ, một số lậu hoặc của người ấy được diệt trừ. ",
  "mn70:17.3": "Người này, này các Tỳ-kheo, được gọi là người thân chứng. ",
  "mn70:17.4": "Này các Tỳ-kheo, ta nói rằng vị Tỳ-kheo này ‘cần phải không phóng dật’. ",
  "mn70:17.5": "Vì cớ gì? ",
  "mn70:17.6": "Mong rằng vị Tôn giả này, khi sống ở các trú xứ thuận lợi, thân cận các bạn lành, điều hòa các căn—",
  "mn70:17.7": "vì mục đích mà các thiện gia nam tử xuất gia từ bỏ gia đình, sống không gia đình, mục đích tối thượng—chấm dứt đời sống Phạm hạnh, tự mình với thắng trí chứng ngộ và an trú ngay trong hiện tại. ",
  "mn70:17.8": "Này các Tỳ-kheo, khi thấy quả của sự không phóng dật này của vị Tỳ-kheo ấy, ta nói rằng ‘cần phải không phóng dật’. ",
  "mn70:18.1": "Và này các Tỳ-kheo, thế nào là người đạt kiến? ",
  "mn70:18.2": "Ở đây, này các Tỳ-kheo, có người nào đó, những giải thoát an tịnh, vượt qua sắc, thuộc vô sắc, người ấy không thân chứng và an trú, nhưng sau khi thấy với trí tuệ, một số lậu hoặc của người ấy được diệt trừ, và các pháp do Như Lai thuyết giảng được người ấy thấy rõ và quán sát với trí tuệ. ",
  "mn70:18.3": "Người này, này các Tỳ-kheo, được gọi là người đạt kiến. ",
  "mn70:18.4": "Này các Tỳ-kheo, ta cũng nói rằng vị Tỳ-kheo này ‘cần phải không phóng dật’. ",
  "mn70:18.5": "Vì cớ gì? ",
  "mn70:18.6": "Mong rằng vị Tôn giả này, khi sống ở các trú xứ thuận lợi, thân cận các bạn lành, điều hòa các căn—",
  "mn70:18.7": "vì mục đích mà các thiện gia nam tử xuất gia từ bỏ gia đình, sống không gia đình, mục đích tối thượng—chấm dứt đời sống Phạm hạnh, tự mình với thắng trí chứng ngộ và an trú ngay trong hiện tại. ",
  "mn70:18.8": "Này các Tỳ-kheo, khi thấy quả của sự không phóng dật này của vị Tỳ-kheo ấy, ta nói rằng ‘cần phải không phóng dật’. ",
  "mn70:19.1": "Và này các Tỳ-kheo, thế nào là người giải thoát nhờ tín? ",
  "mn70:19.2": "Ở đây, này các Tỳ-kheo, có người nào đó, những giải thoát an tịnh, vượt qua sắc, thuộc vô sắc, người ấy không thân chứng và an trú, nhưng sau khi thấy với trí tuệ, một số lậu hoặc của người ấy được diệt trừ, và niềm tin của người ấy đối với Như Lai đã ăn sâu, bén rễ, vững chắc. ",
  "mn70:19.3": "Người này, này các Tỳ-kheo, được gọi là người giải thoát nhờ tín. ",
  "mn70:19.4": "Này các Tỳ-kheo, ta cũng nói rằng vị Tỳ-kheo này ‘cần phải không phóng dật’. ",
  "mn70:19.5": "Vì cớ gì? ",
  "mn70:19.6": "Mong rằng vị Tôn giả này, khi sống ở các trú xứ thuận lợi, thân cận các bạn lành, điều hòa các căn—",
  "mn70:19.7": "vì mục đích mà các thiện gia nam tử xuất gia từ bỏ gia đình, sống không gia đình, mục đích tối thượng—chấm dứt đời sống Phạm hạnh, tự mình với thắng trí chứng ngộ và an trú ngay trong hiện tại. ",
  "mn70:19.8": "Này các Tỳ-kheo, khi thấy quả của sự không phóng dật này của vị Tỳ-kheo ấy, ta nói rằng ‘cần phải không phóng dật’. ",
  "mn70:20.1": "Và này các Tỳ-kheo, thế nào là người tùy pháp hành? ",
  "mn70:20.2": "Ở đây, này các Tỳ-kheo, có người nào đó, những giải thoát an tịnh, vượt qua sắc, thuộc vô sắc, người ấy không thân chứng và an trú, nhưng sau khi thấy với trí tuệ, một số lậu hoặc của người ấy được diệt trừ, và các pháp do Như Lai thuyết giảng được người ấy chấp nhận một cách vừa phải qua sự quán sát bằng trí tuệ, và người ấy có những pháp này, tức là—",
  "mn70:20.3": "tín căn, tấn căn, niệm căn, định căn, tuệ căn. ",
  "mn70:20.4": "Người này, này các Tỳ-kheo, được gọi là người tùy pháp hành. ",
  "mn70:20.5": "Này các Tỳ-kheo, ta cũng nói rằng vị Tỳ-kheo này ‘cần phải không phóng dật’. ",
  "mn70:20.6": "Vì cớ gì? ",
  "mn70:20.7": "Mong rằng vị Tôn giả này, khi sống ở các trú xứ thuận lợi, thân cận các bạn lành, điều hòa các căn—",
  "mn70:20.8": "vì mục đích mà các thiện gia nam tử xuất gia từ bỏ gia đình, sống không gia đình, mục đích tối thượng—chấm dứt đời sống Phạm hạnh, tự mình với thắng trí chứng ngộ và an trú ngay trong hiện tại. ",
  "mn70:20.9": "Này các Tỳ-kheo, khi thấy quả của sự không phóng dật này của vị Tỳ-kheo ấy, ta nói rằng ‘cần phải không phóng dật’. ",
  "mn70:21.1": "Và này các Tỳ-kheo, thế nào là người tùy tín hành? ",
  "mn70:21.2": "Ở đây, này các Tỳ-kheo, có người nào đó, những giải thoát an tịnh, vượt qua sắc, thuộc vô sắc, người ấy không thân chứng và an trú, nhưng sau khi thấy với trí tuệ, một số lậu hoặc của người ấy được diệt trừ, và người ấy có một chút niềm tin, một chút tình yêu đối với Như Lai, và người ấy có những pháp này, tức là—",
  "mn70:21.3": "tín căn, tấn căn, niệm căn, định căn, tuệ căn. ",
  "mn70:21.4": "Người này, này các Tỳ-kheo, được gọi là người tùy tín hành. ",
  "mn70:21.5": "Này các Tỳ-kheo, ta cũng nói rằng vị Tỳ-kheo này ‘cần phải không phóng dật’. ",
  "mn70:21.6": "Vì cớ gì? ",
  "mn70:21.7": "Mong rằng vị Tôn giả này, khi sống ở các trú xứ thuận lợi, thân cận các bạn lành, điều hòa các căn—",
  "mn70:21.8": "vì mục đích mà các thiện gia nam tử xuất gia từ bỏ gia đình, sống không gia đình, mục đích tối thượng—chấm dứt đời sống Phạm hạnh, tự mình với thắng trí chứng ngộ và an trú ngay trong hiện tại. ",
  "mn70:21.9": "Này các Tỳ-kheo, khi thấy quả của sự không phóng dật này của vị Tỳ-kheo ấy, ta nói rằng ‘cần phải không phóng dật’. ",
  "mn70:22.1": "Này các Tỳ-kheo, ta không nói rằng sự chứng ngộ có thể đạt được ngay từ đầu; ",
  "mn70:22.2": "mà này các Tỳ-kheo, chính là nhờ sự học tập tuần tự, hành động tuần tự, con đường tuần tự mà sự chứng ngộ được đạt đến. ",
  "mn70:23.1": "Và này các Tỳ-kheo, thế nào là sự học tập tuần tự, hành động tuần tự, con đường tuần tự mà sự chứng ngộ được đạt đến? ",
  "mn70:23.2": "Ở đây, này các Tỳ-kheo, người có niềm tin đến gần, khi đến gần thì thân cận, khi thân cận thì lắng tai nghe, người lắng tai nghe thì nghe pháp, sau khi nghe pháp thì ghi nhớ pháp, ghi nhớ pháp rồi thì quán sát ý nghĩa của các pháp ấy, khi quán sát ý nghĩa thì các pháp ấy được chấp nhận qua sự quán sát, khi có sự chấp nhận qua sự quán sát pháp thì ý muốn phát sinh, người có ý muốn thì nỗ lực, sau khi nỗ lực thì cân nhắc, sau khi cân nhắc thì tinh tấn, người đã tinh tấn thì tự mình chứng ngộ chân lý tối thượng bằng thân, và thấy rõ nó bằng trí tuệ. ",
  "mn70:24.1": "Này các Tỳ-kheo, nếu niềm tin ấy không có; ",
  "mn70:24.2": "này các Tỳ-kheo, nếu sự đến gần ấy không có; ",
  "mn70:24.3": "này các Tỳ-kheo, nếu sự thân cận ấy không có; ",
  "mn70:24.4": "này các Tỳ-kheo, nếu sự lắng tai nghe ấy không có; ",
  "mn70:24.5": "này các Tỳ-kheo, nếu sự nghe pháp ấy không có; ",
  "mn70:24.6": "này các Tỳ-kheo, nếu sự ghi nhớ pháp ấy không có; ",
  "mn70:24.7": "này các Tỳ-kheo, nếu sự quán sát ý nghĩa ấy không có; ",
  "mn70:24.8": "này các Tỳ-kheo, nếu sự chấp nhận qua sự quán sát pháp ấy không có; ",
  "mn70:24.9": "này các Tỳ-kheo, nếu ý muốn ấy không có; ",
  "mn70:24.10": "này các Tỳ-kheo, nếu sự nỗ lực ấy không có; ",
  "mn70:24.11": "này các Tỳ-kheo, nếu sự cân nhắc ấy không có; ",
  "mn70:24.12": "này các Tỳ-kheo, nếu sự tinh tấn ấy không có. ",
  "mn70:24.13": "Này các Tỳ-kheo, các ông đã đi sai đường, các ông đã đi sai đường. ",
  "mn70:24.14": "Này các Tỳ-kheo, những kẻ ngu si này đã rời xa Pháp và Luật này biết bao! ",
  "mn70:25.1": "Này các Tỳ-kheo, có một lời giải thích bốn phần mà khi được trình bày, người trí không lâu sau sẽ hiểu được ý nghĩa bằng trí tuệ. ",
  "mn70:25.2": "Này các Tỳ-kheo, ta sẽ trình bày cho các ông, các ông sẽ hiểu được điều đó chăng?” ",
  "mn70:25.3": "“Bạch Thế Tôn, chúng con là ai, và ai là người hiểu biết Pháp?” ",
  "mn70:26.1": "“Này các Tỳ-kheo, ngay cả vị Đạo sư nào mà nặng về vật chất, thừa hưởng vật chất, sống dính mắc với vật chất, thì đối với vị ấy, những lời bàn luận như thế này thường không xuất hiện: ",
  "mn70:26.2": "‘Nếu chúng ta có điều này thì chúng ta sẽ làm điều đó, nếu chúng ta không có điều này thì chúng ta sẽ không làm điều đó’, huống chi, này các Tỳ-kheo, Như Lai hoàn toàn không dính mắc với vật chất. ",
  "mn70:27.1": "Này các Tỳ-kheo, đối với đệ tử có niềm tin, khi sống theo lời dạy của Đạo sư, đây là một pháp phù hợp: ",
  "mn70:27.2": "‘Đạo sư là Thế Tôn, tôi là đệ tử; ",
  "mn70:27.3": "Thế Tôn biết, tôi không biết’. ",
  "mn70:27.4": "Này các Tỳ-kheo, đối với đệ tử có niềm tin, khi sống theo lời dạy của Đạo sư, lời dạy của Đạo sư trở nên vững chắc và có sức mạnh. ",
  "mn70:27.5": "Này các Tỳ-kheo, đối với đệ tử có niềm tin, khi sống theo lời dạy của Đạo sư, đây là một pháp phù hợp: ",
  "mn70:27.6": "‘Dù da, gân, xương còn lại, thịt và máu trong thân khô cạn, điều gì có thể đạt được bằng sức mạnh của người nam, bằng sự tinh tấn của người nam, bằng sự nỗ lực của người nam, tôi sẽ không dừng sự tinh tấn cho đến khi đạt được điều đó’. ",
  "mn70:27.7": "Này các Tỳ-kheo, đối với đệ tử có niềm tin, khi sống theo lời dạy của Đạo sư, một trong hai quả sau đây có thể được mong đợi—",
  "mn70:27.8": "sự chứng ngộ ngay trong hiện tại, hoặc nếu còn dư y, thì là quả Bất Hoàn”. ",
  "mn70:27.9": "Thế Tôn đã nói điều này. ",
  "mn70:27.10": "Các Tỳ-kheo ấy hoan hỷ và tán thán lời Thế Tôn dạy. ",
  "mn70:27.11": "Kinh Kīṭāgiri, thứ mười, chấm dứt. ",
  "mn70:27.12": "Phẩm Tỳ-kheo, thứ hai, chấm dứt. ",
  "mn70:28.0": "Tóm tắt phẩm ấy: ",
  "mn70:28.1": "Kuñjara, Rāhula, thế giới thường còn, ",
  "mn70:28.2": "Mālukyaputta và tên Bhaddāli; ",
  "mn70:28.3": "Chim nhỏ, rồi Sahampati thỉnh cầu, ",
  "mn70:28.4": "Nāḷaka, Raññi, tên Kīṭāgiri. "
}
window.BILARA["mn70"]["vi"]["mn70:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
