window.BILARA = window.BILARA || {};
window.BILARA["mn71"] = window.BILARA["mn71"] || {};
window.BILARA["mn71"]["vi"] = {
  "mn71:0.1": "Trung Bộ Kinh 71 ",
  "mn71:0.2": "Kinh Vacchagotta Ba Minh ",
  "mn71:1.1": "Như vầy tôi nghe—",
  "mn71:1.2": "Một thời, Thế Tôn trú ở Vesālī, tại Đại Lâm, Trùng Các. ",
  "mn71:2.1": "Lúc bấy giờ, du sĩ Vacchagotta trú ở tu viện du sĩ Một Hoa Sen. ",
  "mn71:3.1": "Rồi Thế Tôn vào buổi sáng, đắp y, cầm bát, đi vào Vesālī để khất thực. ",
  "mn71:3.2": "Rồi Thế Tôn nghĩ: ",
  "mn71:3.3": "“Còn quá sớm để đi khất thực ở Vesālī; ",
  "mn71:3.4": "ta hãy đi đến tu viện du sĩ Một Hoa Sen, đến chỗ du sĩ Vacchagotta thì hơn.” ",
  "mn71:3.5": "Rồi Thế Tôn đi đến tu viện du sĩ Một Hoa Sen, đến chỗ du sĩ Vacchagotta. ",
  "mn71:4.1": "Du sĩ Vacchagotta thấy Thế Tôn từ xa đi đến. ",
  "mn71:4.2": "Thấy vậy, liền nói với Thế Tôn: ",
  "mn71:4.3": "“Xin mời Thế Tôn đến đây, bạch Ngài. ",
  "mn71:4.4": "Kính mừng Thế Tôn đã đến, bạch Ngài. ",
  "mn71:4.5": "Đã lâu lắm rồi, bạch Ngài, Thế Tôn mới làm cuộc hành trình này, tức là đến đây. ",
  "mn71:4.6": "Xin Thế Tôn hãy ngồi xuống, bạch Ngài, chỗ ngồi này đã được sửa soạn.” ",
  "mn71:4.7": "Thế Tôn ngồi xuống chỗ đã được sửa soạn. ",
  "mn71:4.8": "Du sĩ Vacchagotta cũng lấy một chỗ ngồi thấp hơn, rồi ngồi xuống một bên. ",
  "mn71:4.9": "Ngồi xuống một bên, du sĩ Vacchagotta nói với Thế Tôn: ",
  "mn71:5.1": "“Bạch Ngài, tôi nghe nói rằng: ",
  "mn71:5.2": "‘Sa-môn Gotama là bậc Nhất thiết trí, bậc Nhất thiết kiến, tuyên bố trí kiến không còn sót lại, ",
  "mn71:5.3": "trí kiến thường xuyên hiện hữu nơi ta, khi đi, khi đứng, khi ngủ, khi thức.’ ",
  "mn71:5.4": "Bạch Ngài, những ai nói như vậy: ‘Sa-môn Gotama là bậc Nhất thiết trí, bậc Nhất thiết kiến, tuyên bố trí kiến không còn sót lại, trí kiến thường xuyên hiện hữu nơi ta, khi đi, khi đứng, khi ngủ, khi thức,’ những người ấy có nói đúng lời Thế Tôn không, và không vu khống Thế Tôn với điều không thật, và có giảng giải pháp đúng với pháp không, và không có lời chỉ trích nào đúng pháp đưa đến chỗ đáng trách không?” ",
  "mn71:5.5": "“Này Vaccha, những ai nói như vậy: ‘Sa-môn Gotama là bậc Nhất thiết trí, bậc Nhất thiết kiến, tuyên bố trí kiến không còn sót lại, trí kiến thường xuyên hiện hữu nơi ta, khi đi, khi đứng, khi ngủ, khi thức,’ những người ấy không nói đúng lời ta, mà họ vu khống ta với điều không thật, không đúng sự thật.” ",
  "mn71:6.1": "“Bạch Ngài, nếu chúng tôi giảng giải như thế nào thì chúng tôi mới nói đúng lời Thế Tôn, và không vu khống Thế Tôn với điều không thật, và giảng giải pháp đúng với pháp, và không có lời chỉ trích nào đúng pháp đưa đến chỗ đáng trách?” ",
  "mn71:6.2": "“Này Vaccha, nếu giảng giải rằng: ‘Sa-môn Gotama là bậc Ba Minh,’ thì người ấy nói đúng lời ta, và không vu khống ta với điều không thật, và giảng giải pháp đúng với pháp, và không có lời chỉ trích nào đúng pháp đưa đến chỗ đáng trách. ",
  "mn71:7.1": "Này Vaccha, khi nào ta muốn, ta nhớ lại nhiều đời sống quá khứ khác nhau, ",
  "mn71:7.2": "như một đời, hai đời… cho đến ta nhớ lại nhiều đời sống quá khứ khác nhau với các chi tiết và đặc điểm. ",
  "mn71:8.1": "Này Vaccha, khi nào ta muốn, với thiên nhãn thanh tịnh, siêu việt loài người, ta thấy các chúng sinh chết đi, sinh lại, hạ liệt, cao sang, đẹp đẽ, xấu xí, may mắn, bất hạnh… cho đến ta biết rõ các chúng sinh tùy theo nghiệp của họ. ",
  "mn71:9.1": "Này Vaccha, do sự diệt trừ các lậu hoặc, ta tự mình chứng ngộ, thực chứng và an trú trong giải thoát tâm, giải thoát tuệ không lậu hoặc ngay trong hiện tại. ",
  "mn71:10.1": "Này Vaccha, nếu giảng giải rằng: ‘Sa-môn Gotama là bậc Ba Minh,’ thì người ấy nói đúng lời ta, và không vu khống ta với điều không thật, và giảng giải pháp đúng với pháp, và không có lời chỉ trích nào đúng pháp đưa đến chỗ đáng trách.” ",
  "mn71:11.1": "Khi được nói vậy, du sĩ Vacchagotta nói với Thế Tôn: ",
  "mn71:11.2": "“Bạch Gotama, có người cư sĩ nào, chưa đoạn trừ các kiết sử của cư sĩ, sau khi thân hoại mạng chung, chấm dứt khổ đau không?” ",
  "mn71:11.3": "“Này Vaccha, không có người cư sĩ nào, chưa đoạn trừ các kiết sử của cư sĩ, sau khi thân hoại mạng chung, chấm dứt khổ đau.” ",
  "mn71:12.1": "“Bạch Gotama, có người cư sĩ nào, chưa đoạn trừ các kiết sử của cư sĩ, sau khi thân hoại mạng chung, được sinh lên cõi trời không?” ",
  "mn71:12.2": "“Này Vaccha, không phải một trăm, không phải hai trăm, không phải ba trăm, không phải bốn trăm, không phải năm trăm, mà còn nhiều hơn nữa những người cư sĩ, chưa đoạn trừ các kiết sử của cư sĩ, sau khi thân hoại mạng chung, được sinh lên cõi trời.” ",
  "mn71:13.1": "“Bạch Gotama, có người Ājīvaka nào, sau khi thân hoại mạng chung, chấm dứt khổ đau không?” ",
  "mn71:13.2": "“Này Vaccha, không có người Ājīvaka nào, sau khi thân hoại mạng chung, chấm dứt khổ đau.” ",
  "mn71:14.1": "“Bạch Gotama, có người Ājīvaka nào, sau khi thân hoại mạng chung, được sinh lên cõi trời không?” ",
  "mn71:14.2": "“Này Vaccha, từ đây trở về trước chín mươi mốt kiếp mà ta nhớ lại, ta không biết một Ājīvaka nào được sinh lên cõi trời, ngoại trừ một người; ",
  "mn71:14.3": "người ấy là người chủ trương nghiệp, chủ trương hành động.” ",
  "mn71:15.1": "“Bạch Gotama, nếu vậy, giáo phái ấy trống rỗng, ngay cả với người được sinh lên cõi trời?” ",
  "mn71:15.2": "“Này Vaccha, đúng vậy, giáo phái ấy trống rỗng, ngay cả với người được sinh lên cõi trời.” ",
  "mn71:15.3": "Thế Tôn đã nói như vậy. ",
  "mn71:15.4": "Du sĩ Vacchagotta hoan hỷ, tùy hỷ lời Thế Tôn dạy. ",
  "mn71:15.5": "Kinh Vacchagotta Ba Minh, thứ nhất, chấm dứt. "
}
window.BILARA["mn71"]["vi"]["mn71:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
