window.BILARA = window.BILARA || {};
window.BILARA["mn72"] = window.BILARA["mn72"] || {};
window.BILARA["mn72"]["vi"] = {
  "mn72:0.1": "Trung Bộ Kinh 72 ",
  "mn72:0.2": "Kinh Với Vacchagotta Về Lửa ",
  "mn72:1.1": "Tôi nghe như vầy—",
  "mn72:1.2": "Một thời, Thế Tôn trú ở Sāvatthī, tại Jetavana, khu vườn của Anāthapiṇḍika. ",
  "mn72:2.1": "Rồi du sĩ Vacchagotta đi đến chỗ Thế Tôn; sau khi đến, nói lên những lời chào hỏi thân mật với Thế Tôn. ",
  "mn72:2.2": "Sau khi trao đổi những lời chào hỏi thân mật, đáng ghi nhớ, Vacchagotta ngồi xuống một bên. Ngồi xuống một bên, du sĩ Vacchagotta bạch Thế Tôn: ",
  "mn72:3.1": "“Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: ‘Thế giới là thường còn, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:3.2": "có quan điểm như vậy chăng?” ",
  "mn72:3.3": "“Này Vaccha, Ta không có quan điểm như vậy: ",
  "mn72:3.4": "‘Thế giới là thường còn, đây là sự thật, còn những cái khác là hư dối’.” ",
  "mn72:4.1": "“Nhưng bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: ‘Thế giới là vô thường, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:4.2": "có quan điểm như vậy chăng?” ",
  "mn72:4.3": "“Này Vaccha, Ta không có quan điểm như vậy: ",
  "mn72:4.4": "‘Thế giới là vô thường, đây là sự thật, còn những cái khác là hư dối’.” ",
  "mn72:5.1": "“Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: ‘Thế giới là hữu hạn, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:5.2": "có quan điểm như vậy chăng?” ",
  "mn72:5.3": "“Này Vaccha, Ta không có quan điểm như vậy: ",
  "mn72:5.4": "‘Thế giới là hữu hạn, đây là sự thật, còn những cái khác là hư dối’.” ",
  "mn72:6.1": "“Nhưng bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: ‘Thế giới là vô hạn, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:6.2": "có quan điểm như vậy chăng?” ",
  "mn72:6.3": "“Này Vaccha, Ta không có quan điểm như vậy: ",
  "mn72:6.4": "‘Thế giới là vô hạn, đây là sự thật, còn những cái khác là hư dối’.” ",
  "mn72:7.1": "“Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: ‘Sinh mạng và thân thể là một, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:7.2": "có quan điểm như vậy chăng?” ",
  "mn72:7.3": "“Này Vaccha, Ta không có quan điểm như vậy: ",
  "mn72:7.4": "‘Sinh mạng và thân thể là một, đây là sự thật, còn những cái khác là hư dối’.” ",
  "mn72:8.1": "“Nhưng bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: ‘Sinh mạng khác, thân thể khác, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:8.2": "có quan điểm như vậy chăng?” ",
  "mn72:8.3": "“Này Vaccha, Ta không có quan điểm như vậy: ",
  "mn72:8.4": "‘Sinh mạng khác, thân thể khác, đây là sự thật, còn những cái khác là hư dối’.” ",
  "mn72:9.1": "“Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: ‘Như Lai có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:9.2": "có quan điểm như vậy chăng?” ",
  "mn72:9.3": "“Này Vaccha, Ta không có quan điểm như vậy: ",
  "mn72:9.4": "‘Như Lai có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’.” ",
  "mn72:10.1": "“Nhưng bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: ‘Như Lai không có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:10.2": "có quan điểm như vậy chăng?” ",
  "mn72:10.3": "“Này Vaccha, Ta không có quan điểm như vậy: ",
  "mn72:10.4": "‘Như Lai không có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’.” ",
  "mn72:11.1": "“Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: ‘Như Lai có mặt và không có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:11.2": "có quan điểm như vậy chăng?” ",
  "mn72:11.3": "“Này Vaccha, Ta không có quan điểm như vậy: ",
  "mn72:11.4": "‘Như Lai có mặt và không có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’.” ",
  "mn72:12.1": "“Nhưng bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: ‘Như Lai không có mặt cũng không không có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:12.2": "có quan điểm như vậy chăng?” ",
  "mn72:12.3": "“Này Vaccha, Ta không có quan điểm như vậy: ",
  "mn72:12.4": "‘Như Lai không có mặt cũng không không có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’.” ",
  "mn72:13.1": "“‘Khi được hỏi: ‘Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: Thế giới là thường còn, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:13.2": "có quan điểm như vậy chăng?’, Tôn giả trả lời: ‘Này Vaccha, Ta không có quan điểm như vậy—",
  "mn72:13.3": "Thế giới là thường còn, đây là sự thật, còn những cái khác là hư dối’. ",
  "mn72:13.4": "Khi được hỏi: ‘Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: Thế giới là vô thường, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:13.5": "có quan điểm như vậy chăng?’, Tôn giả trả lời: ‘Này Vaccha, Ta không có quan điểm như vậy—",
  "mn72:13.6": "Thế giới là vô thường, đây là sự thật, còn những cái khác là hư dối’. ",
  "mn72:13.7": "Khi được hỏi: ‘Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: Thế giới là hữu hạn, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:13.8": "có quan điểm như vậy chăng?’, Tôn giả trả lời: ‘Này Vaccha, Ta không có quan điểm như vậy—",
  "mn72:13.9": "Thế giới là hữu hạn, đây là sự thật, còn những cái khác là hư dối’. ",
  "mn72:13.10": "Khi được hỏi: ‘Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: Thế giới là vô hạn, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:13.11": "có quan điểm như vậy chăng?’, Tôn giả trả lời: ‘Này Vaccha, Ta không có quan điểm như vậy—",
  "mn72:13.12": "Thế giới là vô hạn, đây là sự thật, còn những cái khác là hư dối’. ",
  "mn72:13.13": "Khi được hỏi: ‘Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: Sinh mạng và thân thể là một, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:13.14": "có quan điểm như vậy chăng?’, Tôn giả trả lời: ‘Này Vaccha, Ta không có quan điểm như vậy—",
  "mn72:13.15": "Sinh mạng và thân thể là một, đây là sự thật, còn những cái khác là hư dối’. ",
  "mn72:13.16": "Khi được hỏi: ‘Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: Sinh mạng khác, thân thể khác, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:13.17": "có quan điểm như vậy chăng?’, Tôn giả trả lời: ‘Này Vaccha, Ta không có quan điểm như vậy—",
  "mn72:13.18": "Sinh mạng khác, thân thể khác, đây là sự thật, còn những cái khác là hư dối’. ",
  "mn72:13.19": "Khi được hỏi: ‘Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: Như Lai có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:13.20": "có quan điểm như vậy chăng?’, Tôn giả trả lời: ‘Này Vaccha, Ta không có quan điểm như vậy—",
  "mn72:13.21": "Như Lai có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’. ",
  "mn72:13.22": "Khi được hỏi: ‘Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: Như Lai không có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:13.23": "có quan điểm như vậy chăng?’, Tôn giả trả lời: ‘Này Vaccha, Ta không có quan điểm như vậy—",
  "mn72:13.24": "Như Lai không có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’. ",
  "mn72:13.25": "Khi được hỏi: ‘Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: Như Lai có mặt và không có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:13.26": "có quan điểm như vậy chăng?’, Tôn giả trả lời: ‘Này Vaccha, Ta không có quan điểm như vậy—",
  "mn72:13.27": "Như Lai có mặt và không có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’. ",
  "mn72:13.28": "Khi được hỏi: ‘Bạch Tôn giả Gotama, phải chăng Tôn giả Gotama có quan điểm: Như Lai không có mặt cũng không không có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’—",
  "mn72:13.29": "có quan điểm như vậy chăng?’, Tôn giả trả lời: ‘Này Vaccha, Ta không có quan điểm như vậy—",
  "mn72:13.30": "Như Lai không có mặt cũng không không có mặt sau khi chết, đây là sự thật, còn những cái khác là hư dối’. ",
  "mn72:13.31": "Bạch Tôn giả Gotama, Tôn giả thấy rõ sự nguy hiểm nào mà không chấp nhận hoàn toàn tất cả các quan điểm này?” ",
  "mn72:14.1": "“Này Vaccha, quan điểm ‘Thế giới là thường còn’ là một quan điểm, một rừng quan điểm, một hoang địa quan điểm, một sự vặn vẹo của quan điểm, một sự dao động của quan điểm, một sự trói buộc của quan điểm, cùng với khổ đau, cùng với phiền não, cùng với ưu phiền, cùng với nóng bức, không đưa đến chán ghét, không đưa đến ly tham, không đưa đến chấm dứt, không đưa đến an tịnh, không đưa đến hiểu biết cao siêu, không đưa đến giác ngộ, không đưa đến Niết Bàn. ",
  "mn72:14.2": "Này Vaccha, quan điểm ‘Thế giới là vô thường’ … ",
  "mn72:14.3": "Này Vaccha, quan điểm ‘Thế giới là hữu hạn’ … ",
  "mn72:14.4": "Này Vaccha, quan điểm ‘Thế giới là vô hạn’ … ",
  "mn72:14.5": "Này Vaccha, quan điểm ‘Sinh mạng và thân thể là một’ … ",
  "mn72:14.6": "Này Vaccha, quan điểm ‘Sinh mạng khác, thân thể khác’ … ",
  "mn72:14.7": "Này Vaccha, quan điểm ‘Như Lai có mặt sau khi chết’ … ",
  "mn72:14.8": "Này Vaccha, quan điểm ‘Như Lai không có mặt sau khi chết’ … ",
  "mn72:14.9": "Này Vaccha, quan điểm ‘Như Lai có mặt và không có mặt sau khi chết’ … ",
  "mn72:14.10": "Này Vaccha, quan điểm ‘Như Lai không có mặt cũng không không có mặt sau khi chết’ là một quan điểm, một rừng quan điểm, một hoang địa quan điểm, một sự vặn vẹo của quan điểm, một sự dao động của quan điểm, một sự trói buộc của quan điểm, cùng với khổ đau, cùng với phiền não, cùng với ưu phiền, cùng với nóng bức, không đưa đến chán ghét, không đưa đến ly tham, không đưa đến chấm dứt, không đưa đến an tịnh, không đưa đến hiểu biết cao siêu, không đưa đến giác ngộ, không đưa đến Niết Bàn. ",
  "mn72:14.11": "Này Vaccha, thấy rõ sự nguy hiểm này, Ta không chấp nhận hoàn toàn tất cả các quan điểm này.” ",
  "mn72:15.1": "“Nhưng bạch Tôn giả Gotama, Tôn giả có quan điểm nào không?” ",
  "mn72:15.2": "“Này Vaccha, quan điểm là cái đã được Như Lai loại bỏ. ",
  "mn72:15.3": "Này Vaccha, Như Lai đã thấy rõ: ",
  "mn72:15.4": "‘Đây là sắc, đây là sự sanh khởi của sắc, đây là sự diệt tận của sắc; ",
  "mn72:15.5": "đây là thọ, đây là sự sanh khởi của thọ, đây là sự diệt tận của thọ; ",
  "mn72:15.6": "đây là tưởng, đây là sự sanh khởi của tưởng, đây là sự diệt tận của tưởng; ",
  "mn72:15.7": "đây là hành, đây là sự sanh khởi của hành, đây là sự diệt tận của hành; ",
  "mn72:15.8": "đây là thức, đây là sự sanh khởi của thức, đây là sự diệt tận của thức’. ",
  "mn72:15.9": "Do đó, Ta nói rằng Như Lai đã được giải thoát, không còn chấp thủ, do sự diệt tận, ly tham, chấm dứt, từ bỏ, buông xả tất cả những gì được cho là ‘Ta’, tất cả những gì được cho là ‘của Ta’, tất cả những gì là ngã mạn và tùy miên ngã mạn.” ",
  "mn72:16.1": "“Bạch Tôn giả Gotama, vậy một vị Tỳ-kheo có tâm giải thoát như vậy sẽ tái sanh ở đâu?” ",
  "mn72:16.2": "“Này Vaccha, nói ‘tái sanh’ thì không đúng”. ",
  "mn72:16.3": "“Vậy thì bạch Tôn giả Gotama, không tái sanh chăng?” ",
  "mn72:16.4": "“Này Vaccha, nói ‘không tái sanh’ thì không đúng”. ",
  "mn72:16.5": "“Vậy thì bạch Tôn giả Gotama, tái sanh và không tái sanh chăng?” ",
  "mn72:16.6": "“Này Vaccha, nói ‘tái sanh và không tái sanh’ thì không đúng”. ",
  "mn72:16.7": "“Vậy thì bạch Tôn giả Gotama, không tái sanh cũng không không tái sanh chăng?” ",
  "mn72:16.8": "“Này Vaccha, nói ‘không tái sanh cũng không không tái sanh’ thì không đúng”. ",
  "mn72:17.1": "“Khi được hỏi: ‘Bạch Tôn giả Gotama, vậy một vị Tỳ-kheo có tâm giải thoát như vậy sẽ tái sanh ở đâu?’, Tôn giả trả lời: ‘Này Vaccha, nói “tái sanh” thì không đúng’. ",
  "mn72:17.2": "Khi được hỏi: ‘Vậy thì bạch Tôn giả Gotama, không tái sanh chăng?’, Tôn giả trả lời: ‘Này Vaccha, nói “không tái sanh” thì không đúng’. ",
  "mn72:17.3": "Khi được hỏi: ‘Vậy thì bạch Tôn giả Gotama, tái sanh và không tái sanh chăng?’, Tôn giả trả lời: ‘Này Vaccha, nói “tái sanh và không tái sanh” thì không đúng’. ",
  "mn72:17.4": "Khi được hỏi: ‘Vậy thì bạch Tôn giả Gotama, không tái sanh cũng không không tái sanh chăng?’, Tôn giả trả lời: ‘Này Vaccha, nói “không tái sanh cũng không không tái sanh” thì không đúng’. ",
  "mn72:17.5": "Bạch Tôn giả Gotama, ở đây con trở nên không hiểu biết, ở đây con trở nên mê mờ. ",
  "mn72:17.6": "Ngay cả chút niềm tin mà con đã có từ cuộc nói chuyện trước với Tôn giả Gotama, nay cũng đã biến mất.” ",
  "mn72:18.1": "“Này Vaccha, đủ để ông không hiểu biết, đủ để ông mê mờ. ",
  "mn72:18.2": "Này Vaccha, giáo pháp này sâu xa, khó thấy, khó hiểu, an tịnh, cao thượng, không thể đạt được bằng lý luận, vi tế, chỉ người trí mới cảm nhận được. ",
  "mn72:18.3": "Ông, với quan điểm khác, sự chấp nhận khác, sở thích khác, sự thực hành khác, và vị thầy khác, thì khó mà hiểu được. ",
  "mn72:18.4": "Vậy thì này Vaccha, Ta sẽ hỏi lại ông về điều này; ông hãy trả lời theo cách ông thấy phù hợp. ",
  "mn72:19.1": "Này Vaccha, ông nghĩ sao, ",
  "mn72:19.2": "nếu có một ngọn lửa cháy trước mặt ông, ông có biết: ",
  "mn72:19.3": "‘Ngọn lửa này đang cháy trước mặt ta’ không?” ",
  "mn72:19.4": "“Bạch Tôn giả Gotama, nếu có một ngọn lửa cháy trước mặt con, con sẽ biết: ",
  "mn72:19.5": "‘Ngọn lửa này đang cháy trước mặt ta’.” "
}
window.BILARA["mn72"]["vi"]["mn72:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
