window.BILARA = window.BILARA || {};
window.BILARA["mn74"] = window.BILARA["mn74"] || {};
window.BILARA["mn74"]["vi"] = {
  "mn74:0.1": "Trung Bộ Kinh 74 ",
  "mn74:0.2": "Kinh Dīghanakha (Móng Dài) ",
  "mn74:1.1": "Tôi nghe như vầy—",
  "mn74:1.2": "Một thời, Thế Tôn trú ở Rājagaha (Vương Xá), trên núi Gijjhakūṭa (Linh Thứu), tại hang Sūkarakhata (Heo Rừng). ",
  "mn74:2.1": "Rồi du sĩ Dīghanakha (Móng Dài) đi đến chỗ Thế Tôn; sau khi đến, chào hỏi thân mật với Thế Tôn. ",
  "mn74:2.2": "Sau khi nói lên những lời chào hỏi thân mật, đáng ghi nhớ, du sĩ Dīghanakha đứng sang một bên. Đứng sang một bên, du sĩ Dīghanakha bạch Thế Tôn: ",
  "mn74:2.3": "“Thưa Tôn giả Gotama, tôi có chủ trương, có quan điểm như sau: ",
  "mn74:2.4": "‘Tất cả đối với tôi đều không vừa ý’.”",
  "mn74:2.5": "“Này Aggivessana, chính cái quan điểm này của ông: ",
  "mn74:2.6": "‘Tất cả đối với tôi đều không vừa ý’, chính quan điểm này của ông cũng không vừa ý ông sao?”",
  "mn74:2.7": "“Thưa Tôn giả Gotama, nếu quan điểm này của tôi mà vừa ý tôi, thì nó cũng sẽ là như vậy, nó cũng sẽ là như vậy.”",
  "mn74:3.1": "“Này Aggivessana, trên đời này có rất nhiều người nói như sau: ",
  "mn74:3.2": "‘Nó cũng sẽ là như vậy, nó cũng sẽ là như vậy’. ",
  "mn74:3.3": "Họ không từ bỏ quan điểm ấy, và chấp thủ một quan điểm khác. ",
  "mn74:3.4": "Này Aggivessana, trên đời này có rất ít người nói như sau: ",
  "mn74:3.5": "‘Nó cũng sẽ là như vậy, nó cũng sẽ là như vậy’. ",
  "mn74:3.6": "Họ từ bỏ quan điểm ấy, và không chấp thủ một quan điểm khác. ",
  "mn74:4.1": "Này Aggivessana, có một số Sa-môn, Bà-la-môn có chủ trương, có quan điểm như sau: ",
  "mn74:4.2": "‘Tất cả đối với tôi đều vừa ý’; ",
  "mn74:4.3": "Này Aggivessana, có một số Sa-môn, Bà-la-môn có chủ trương, có quan điểm như sau: ",
  "mn74:4.4": "‘Tất cả đối với tôi đều không vừa ý’; ",
  "mn74:4.5": "Này Aggivessana, có một số Sa-môn, Bà-la-môn có chủ trương, có quan điểm như sau: ",
  "mn74:4.6": "‘Một phần đối với tôi vừa ý, một phần đối với tôi không vừa ý’. ",
  "mn74:4.7": "Này Aggivessana, trong số những Sa-môn, Bà-la-môn có chủ trương, có quan điểm như sau: ‘Tất cả đối với tôi đều vừa ý’, ",
  "mn74:4.8": "quan điểm ấy của họ gần với tham ái, gần với ràng buộc, gần với hoan hỷ, gần với chấp trước, gần với chấp thủ; ",
  "mn74:4.9": "Này Aggivessana, trong số những Sa-môn, Bà-la-môn có chủ trương, có quan điểm như sau: ‘Tất cả đối với tôi đều không vừa ý’, ",
  "mn74:4.10": "quan điểm ấy của họ gần với không tham ái, gần với không ràng buộc, gần với không hoan hỷ, gần với không chấp trước, gần với không chấp thủ.”",
  "mn74:5.1": "Khi được nói vậy, du sĩ Dīghanakha bạch Thế Tôn: ",
  "mn74:5.2": "“Tôn giả Gotama tán dương quan điểm của tôi, Tôn giả Gotama tán dương quan điểm của tôi.”",
  "mn74:5.3": "“Này Aggivessana, trong số những Sa-môn, Bà-la-môn có chủ trương, có quan điểm như sau: ",
  "mn74:5.4": "‘Một phần đối với tôi vừa ý, một phần đối với tôi không vừa ý’. ",
  "mn74:5.5": "Phần quan điểm nào của họ vừa ý, quan điểm ấy gần với tham ái, gần với ràng buộc, gần với hoan hỷ, gần với chấp trước, gần với chấp thủ; ",
  "mn74:5.6": "phần quan điểm nào của họ không vừa ý, quan điểm ấy gần với không tham ái, gần với không ràng buộc, gần với không hoan hỷ, gần với không chấp trước, gần với không chấp thủ. ",
  "mn74:6.1": "Này Aggivessana, trong số những Sa-môn, Bà-la-môn có chủ trương, có quan điểm như sau: ",
  "mn74:6.2": "‘Tất cả đối với tôi đều vừa ý’, ",
  "mn74:6.3": "ở đây, một người có trí suy xét như sau: ",
  "mn74:6.4": "‘Quan điểm này của tôi—",
  "mn74:6.5": "tất cả đối với tôi đều vừa ý, ",
  "mn74:6.6": "nếu tôi kiên trì, bám víu, chấp chặt vào quan điểm này—",
  "mn74:6.7": "chỉ đây là sự thật, còn cái khác là sai lầm; ",
  "mn74:6.8": "thì tôi sẽ có tranh chấp với hai loại người—",
  "mn74:6.9": "những Sa-môn hay Bà-la-môn có chủ trương, có quan điểm như sau: tất cả đối với tôi đều không vừa ý, ",
  "mn74:6.10": "và những Sa-môn hay Bà-la-môn có chủ trương, có quan điểm như sau: một phần đối với tôi vừa ý, một phần đối với tôi không vừa ý—",
  "mn74:6.11": "tôi sẽ có tranh chấp với hai loại người này. ",
  "mn74:6.12": "Khi có tranh chấp thì có cãi vã, khi có cãi vã thì có phiền não, khi có phiền não thì có khổ đau’. ",
  "mn74:6.13": "Như vậy, khi thấy tranh chấp, cãi vã, phiền não và khổ đau trong tự thân, người ấy từ bỏ quan điểm ấy và không chấp thủ một quan điểm khác. ",
  "mn74:6.14": "Như vậy là sự từ bỏ những quan điểm ấy, như vậy là sự xả ly những quan điểm ấy. ",
  "mn74:7.1": "Này Aggivessana, trong số những Sa-môn, Bà-la-môn có chủ trương, có quan điểm như sau: ",
  "mn74:7.2": "‘Tất cả đối với tôi đều không vừa ý’, ",
  "mn74:7.3": "ở đây, một người có trí suy xét như sau: ",
  "mn74:7.4": "‘Quan điểm này của tôi—",
  "mn74:7.5": "tất cả đối với tôi đều không vừa ý, ",
  "mn74:7.6": "nếu tôi kiên trì, bám víu, chấp chặt vào quan điểm này—",
  "mn74:7.7": "chỉ đây là sự thật, còn cái khác là sai lầm; ",
  "mn74:7.8": "thì tôi sẽ có tranh chấp với hai loại người—",
  "mn74:7.9": "những Sa-môn hay Bà-la-môn có chủ trương, có quan điểm như sau: tất cả đối với tôi đều vừa ý, ",
  "mn74:7.10": "và những Sa-môn hay Bà-la-môn có chủ trương, có quan điểm như sau: một phần đối với tôi vừa ý, một phần đối với tôi không vừa ý—",
  "mn74:7.11": "tôi sẽ có tranh chấp với hai loại người này. ",
  "mn74:7.12": "Khi có tranh chấp thì có cãi vã, khi có cãi vã thì có phiền não, khi có phiền não thì có khổ đau’. ",
  "mn74:7.13": "Như vậy, khi thấy tranh chấp, cãi vã, phiền não và khổ đau trong tự thân, người ấy từ bỏ quan điểm ấy và không chấp thủ một quan điểm khác. ",
  "mn74:7.14": "Như vậy là sự từ bỏ những quan điểm ấy, như vậy là sự xả ly những quan điểm ấy. ",
  "mn74:8.1": "Này Aggivessana, trong số những Sa-môn, Bà-la-môn có chủ trương, có quan điểm như sau: ",
  "mn74:8.2": "‘Một phần đối với tôi vừa ý, một phần đối với tôi không vừa ý’, ",
  "mn74:8.3": "ở đây, một người có trí suy xét như sau: ",
  "mn74:8.4": "‘Quan điểm này của tôi—",
  "mn74:8.5": "một phần đối với tôi vừa ý, một phần đối với tôi không vừa ý, ",
  "mn74:8.6": "nếu tôi kiên trì, bám víu, chấp chặt vào quan điểm này—",
  "mn74:8.7": "chỉ đây là sự thật, còn cái khác là sai lầm; ",
  "mn74:8.8": "thì tôi sẽ có tranh chấp với hai loại người—",
  "mn74:8.9": "những Sa-môn hay Bà-la-môn có chủ trương, có quan điểm như sau: tất cả đối với tôi đều vừa ý, ",
  "mn74:8.10": "và những Sa-môn hay Bà-la-môn có chủ trương, có quan điểm như sau: tất cả đối với tôi đều không vừa ý—",
  "mn74:8.11": "tôi sẽ có tranh chấp với hai loại người này. ",
  "mn74:8.12": "Khi có tranh chấp thì có cãi vã, khi có cãi vã thì có phiền não, khi có phiền não thì có khổ đau’. ",
  "mn74:8.13": "Như vậy, khi thấy tranh chấp, cãi vã, phiền não và khổ đau trong tự thân, người ấy từ bỏ quan điểm ấy và không chấp thủ một quan điểm khác. ",
  "mn74:8.14": "Như vậy là sự từ bỏ những quan điểm ấy, như vậy là sự xả ly những quan điểm ấy. ",
  "mn74:9.1": "Này Aggivessana, thân này là sắc, do bốn đại hợp thành, do cha mẹ sinh ra, được nuôi dưỡng bằng cơm cháo, là vật thường bị chà xát, xoa bóp, phá hoại, tan rã, phải được quán chiếu là vô thường, khổ, bệnh, nhọt, mũi tên, tai họa, bệnh hoạn, khác, hoại diệt, trống rỗng, vô ngã. ",
  "mn74:9.2": "Khi quán chiếu thân này là vô thường, khổ, bệnh, nhọt, mũi tên, tai họa, bệnh hoạn, khác, hoại diệt, trống rỗng, vô ngã, thì dục vọng đối với thân, sự quyến luyến đối với thân, sự ràng buộc đối với thân được từ bỏ. ",
  "mn74:10.1": "Này Aggivessana, có ba loại cảm thọ này—",
  "mn74:10.2": "cảm thọ lạc, cảm thọ khổ, cảm thọ không khổ không lạc. ",
  "mn74:10.3": "Này Aggivessana, vào lúc nào cảm thọ lạc được cảm nhận, thì vào lúc ấy không cảm thọ khổ được cảm nhận, không cảm thọ không khổ không lạc được cảm nhận; ",
  "mn74:10.4": "chỉ cảm thọ lạc được cảm nhận vào lúc ấy. ",
  "mn74:10.5": "Này Aggivessana, vào lúc nào cảm thọ khổ được cảm nhận, thì vào lúc ấy không cảm thọ lạc được cảm nhận, không cảm thọ không khổ không lạc được cảm nhận; ",
  "mn74:10.6": "chỉ cảm thọ khổ được cảm nhận vào lúc ấy. ",
  "mn74:10.7": "Này Aggivessana, vào lúc nào cảm thọ không khổ không lạc được cảm nhận, thì vào lúc ấy không cảm thọ lạc được cảm nhận, không cảm thọ khổ được cảm nhận; ",
  "mn74:10.8": "chỉ cảm thọ không khổ không lạc được cảm nhận vào lúc ấy. ",
  "mn74:11.1": "Này Aggivessana, cảm thọ lạc cũng là vô thường, do duyên hợp, do duyên sinh, có tính chất hoại diệt, có tính chất biến mất, có tính chất ly tham, có tính chất chấm dứt; ",
  "mn74:11.2": "cảm thọ khổ cũng là vô thường, do duyên hợp, do duyên sinh, có tính chất hoại diệt, có tính chất biến mất, có tính chất ly tham, có tính chất chấm dứt; ",
  "mn74:11.3": "cảm thọ không khổ không lạc cũng là vô thường, do duyên hợp, do duyên sinh, có tính chất hoại diệt, có tính chất biến mất, có tính chất ly tham, có tính chất chấm dứt. ",
  "mn74:12.1": "Này Aggivessana, khi thấy như vậy, vị Thánh đệ tử có học nhàm chán cảm thọ lạc, nhàm chán cảm thọ khổ, nhàm chán cảm thọ không khổ không lạc; ",
  "mn74:12.2": "nhàm chán thì ly tham, do ly tham mà giải thoát. Khi giải thoát, trí biết rằng đã giải thoát. ",
  "mn74:12.3": "Vị ấy biết: ‘Sanh đã tận, phạm hạnh đã thành, việc cần làm đã làm, không còn trở lại trạng thái này nữa’. ",
  "mn74:13.1": "Này Aggivessana, một Tỳ-kheo có tâm giải thoát như vậy không tranh luận với ai, không cãi vã với ai, và những gì được nói trong đời, vị ấy dùng chúng mà không chấp thủ.”",
  "mn74:14.1": "Lúc bấy giờ, Tôn giả Sāriputta đang đứng phía sau Thế Tôn, quạt cho Thế Tôn. ",
  "mn74:14.2": "Rồi Tôn giả Sāriputta suy nghĩ: ",
  "mn74:14.3": "“Thật vậy, Thế Tôn đã nói về sự từ bỏ các pháp ấy bằng thắng trí, Thiện Thệ đã nói về sự xả ly các pháp ấy bằng thắng trí.”",
  "mn74:14.4": "Khi Tôn giả Sāriputta suy xét như vậy, tâm của Ngài được giải thoát khỏi các lậu hoặc mà không chấp thủ. ",
  "mn74:15.1": "Còn du sĩ Dīghanakha, pháp nhãn không bụi trần, không cấu uế khởi lên: ",
  "mn74:15.2": "“Phàm cái gì có tính chất sinh khởi, tất cả cái đó có tính chất chấm dứt.”",
  "mn74:15.3": "Rồi du sĩ Dīghanakha, đã thấy pháp, đã đạt pháp, đã hiểu pháp, đã thâm nhập pháp, đã vượt qua nghi ngờ, đã dứt bỏ do dự, đã đạt được sự tự tin, không còn tùy thuộc vào người khác trong giáo pháp của Bậc Đạo Sư, bạch Thế Tôn: ",
  "mn74:16.1": "“Tuyệt vời thay, thưa Tôn giả Gotama! Tuyệt vời thay, thưa Tôn giả Gotama! ",
  "mn74:16.2": "Thưa Tôn giả Gotama, như người dựng đứng cái bị lật úp, phơi bày cái bị che kín, chỉ đường cho người lạc lối, hay cầm đèn trong bóng tối để những người có mắt có thể thấy sắc; cũng vậy, Tôn giả Gotama đã thuyết giảng Chánh pháp bằng nhiều cách khác nhau. ",
  "mn74:16.3": "Con xin quy y Tôn giả Gotama, quy y Chánh pháp và quy y Tăng đoàn. ",
  "mn74:16.4": "Kính xin Tôn giả Gotama nhận con làm cư sĩ, từ nay cho đến trọn đời, con xin quy y.”",
  "mn74:16.5": "Kinh Dīghanakha (Móng Dài) chấm dứt, thứ tư. "
}
window.BILARA["mn74"]["vi"]["mn74:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
