window.BILARA = window.BILARA || {};
window.BILARA["mn78"] = window.BILARA["mn78"] || {};
window.BILARA["mn78"]["vi"] = {
  "mn78:0.1": "Trung Bộ Kinh 78 ",
  "mn78:0.2": "Kinh Samaṇamuṇḍika ",
  "mn78:1.1": "Tôi nghe như vầy—",
  "mn78:1.2": "Một thời, Thế Tôn trú ở Sāvatthī, tại Jetavana, khu vườn của Anāthapiṇḍika. ",
  "mn78:1.3": "Lúc bấy giờ, du sĩ Uggāhamāna, con của Samaṇamuṇḍikā, đang trú tại khu vườn Mallikā, ở Tindukācīra, một hội trường tranh luận, cùng với đại chúng du sĩ khoảng năm trăm người. ",
  "mn78:2.1": "Rồi, gia chủ Pañcakaṅga rời Sāvatthī vào ban ngày để đến yết kiến Thế Tôn. ",
  "mn78:2.2": "Rồi, gia chủ Pañcakaṅga suy nghĩ: ",
  "mn78:2.3": "“Bây giờ không phải lúc để yết kiến Thế Tôn; ",
  "mn78:2.4": "Thế Tôn đang nhập thất. ",
  "mn78:2.5": "Cũng không phải lúc để yết kiến các Tỳ-kheo đang tu tập tâm; ",
  "mn78:2.6": "các Tỳ-kheo đang tu tập tâm cũng đang nhập thất. ",
  "mn78:2.7": "Vậy ta hãy đi đến khu vườn Mallikā, ở Tindukācīra, hội trường tranh luận, nơi du sĩ Uggāhamāna, con của Samaṇamuṇḍikā đang ở.” ",
  "mn78:2.8": "Rồi, gia chủ Pañcakaṅga đi đến khu vườn Mallikā, ở Tindukācīra, hội trường tranh luận, nơi du sĩ Uggāhamāna, con của Samaṇamuṇḍikā đang ở. ",
  "mn78:3.1": "Lúc bấy giờ, du sĩ Uggāhamāna, con của Samaṇamuṇḍikā, đang ngồi cùng với đại chúng du sĩ ồn ào, nói lớn tiếng, bàn tán đủ thứ chuyện tầm phào, như là—",
  "mn78:3.2": "chuyện vua chúa, chuyện trộm cướp, chuyện đại thần, chuyện quân đội, chuyện sợ hãi, chuyện chiến tranh, chuyện ăn uống, chuyện đồ uống, chuyện y phục, chuyện giường nằm, chuyện vòng hoa, chuyện hương liệu, chuyện bà con, chuyện xe cộ, chuyện làng mạc, chuyện thị trấn, chuyện thành phố, chuyện quốc gia, chuyện phụ nữ, chuyện anh hùng, chuyện đường phố, chuyện bến nước, chuyện người đã chết, chuyện tạp nhạp, chuyện thế giới, chuyện biển cả, chuyện có hay không có đời này đời khác, v.v. ",
  "mn78:3.3": "Du sĩ Uggāhamāna, con của Samaṇamuṇḍikā, thấy gia chủ Pañcakaṅga từ xa đi đến. ",
  "mn78:3.4": "Thấy vậy, ông bảo hội chúng của mình: ",
  "mn78:3.5": "“Xin quý vị hãy giữ yên lặng, đừng làm ồn; ",
  "mn78:3.6": "gia chủ Pañcakaṅga, một đệ tử của Sa-môn Gotama đang đến. ",
  "mn78:3.7": "Trong số các đệ tử cư sĩ mặc áo trắng của Sa-môn Gotama đang trú ở Sāvatthī, gia chủ Pañcakaṅga là một trong số đó. ",
  "mn78:3.8": "Các vị ấy thích yên lặng, được rèn luyện trong sự yên lặng, và tán thán sự yên lặng; ",
  "mn78:3.9": "có lẽ khi thấy hội chúng yên lặng, ông ấy sẽ nghĩ là nên đến.” ",
  "mn78:3.10": "Rồi, các du sĩ ấy giữ yên lặng. ",
  "mn78:4.1": "Rồi, gia chủ Pañcakaṅga đi đến chỗ du sĩ Uggāhamāna, con của Samaṇamuṇḍikā; sau khi đến, ông chào hỏi du sĩ Uggāhamāna, con của Samaṇamuṇḍikā. ",
  "mn78:4.2": "Sau khi trao đổi những lời chào hỏi thân mật, ông ngồi xuống một bên. Khi gia chủ Pañcakaṅga đã ngồi xuống một bên, du sĩ Uggāhamāna, con của Samaṇamuṇḍikā, nói với ông: ",
  "mn78:5.1": "“Này gia chủ, tôi tuyên bố một người có đủ bốn pháp là người thiện xảo hoàn toàn, thiện xảo tối thượng, đạt được thành tựu tối cao, là một Sa-môn không thể bị đánh bại. ",
  "mn78:5.2": "Bốn pháp đó là gì? ",
  "mn78:5.3": "Ở đây, này gia chủ, người ấy không làm ác nghiệp bằng thân, không nói lời ác, không suy nghĩ ác, không sống bằng tà mạng—",
  "mn78:5.4": "Này gia chủ, tôi tuyên bố một người có đủ bốn pháp này là người thiện xảo hoàn toàn, thiện xảo tối thượng, đạt được thành tựu tối cao, là một Sa-môn không thể bị đánh bại.” ",
  "mn78:6.1": "Rồi, gia chủ Pañcakaṅga không hoan hỷ cũng không phản đối lời nói của du sĩ Uggāhamāna, con của Samaṇamuṇḍikā. ",
  "mn78:6.2": "Không hoan hỷ, không phản đối, ông đứng dậy khỏi chỗ ngồi và bỏ đi: ",
  "mn78:6.3": "“Ta sẽ tìm hiểu ý nghĩa của lời nói này từ Thế Tôn.” ",
  "mn78:7.1": "Rồi, gia chủ Pañcakaṅga đi đến chỗ Thế Tôn; sau khi đến, ông đảnh lễ Thế Tôn rồi ngồi xuống một bên. ",
  "mn78:7.2": "Khi gia chủ Pañcakaṅga đã ngồi xuống một bên, ông kể lại tất cả cuộc trò chuyện của mình với du sĩ Uggāhamāna, con của Samaṇamuṇdika, cho Thế Tôn nghe. ",
  "mn78:8.1": "Khi được nói như vậy, Thế Tôn nói với gia chủ Pañcakaṅga: ",
  "mn78:8.2": "“Này gia chủ, nếu đúng như vậy, thì một đứa trẻ sơ sinh, còn non nớt, nằm ngửa, sẽ là người thiện xảo hoàn toàn, thiện xảo tối thượng, đạt được thành tựu tối cao, là một Sa-môn không thể bị đánh bại, theo lời của du sĩ Uggāhamāna, con của Samaṇamuṇḍikā. ",
  "mn78:8.3": "Này gia chủ, một đứa trẻ sơ sinh, còn non nớt, nằm ngửa, còn chưa có ý niệm về thân, làm sao nó có thể làm ác nghiệp bằng thân, ngoài sự cử động đơn thuần. ",
  "mn78:8.4": "Này gia chủ, một đứa trẻ sơ sinh, còn non nớt, nằm ngửa, còn chưa có ý niệm về lời nói, làm sao nó có thể nói lời ác, ngoài tiếng khóc đơn thuần. ",
  "mn78:8.5": "Này gia chủ, một đứa trẻ sơ sinh, còn non nớt, nằm ngửa, còn chưa có ý niệm về ý nghĩ, làm sao nó có thể suy nghĩ ác, ngoài tiếng kêu đơn thuần. ",
  "mn78:8.6": "Này gia chủ, một đứa trẻ sơ sinh, còn non nớt, nằm ngửa, còn chưa có ý niệm về sinh kế, làm sao nó có thể sống bằng tà mạng, ngoài việc bú sữa mẹ. ",
  "mn78:8.7": "Này gia chủ, nếu đúng như vậy, thì một đứa trẻ sơ sinh, còn non nớt, nằm ngửa, sẽ là người thiện xảo hoàn toàn, thiện xảo tối thượng, đạt được thành tựu tối cao, là một Sa-môn không thể bị đánh bại, theo lời của du sĩ Uggāhamāna, con của Samaṇamuṇḍikā. ",
  "mn78:8.8": "Này gia chủ, tôi tuyên bố một người có đủ bốn pháp không phải là người thiện xảo hoàn toàn, không phải thiện xảo tối thượng, không đạt được thành tựu tối cao, không phải là một Sa-môn không thể bị đánh bại, mà còn thua kém cả đứa trẻ sơ sinh, non nớt, nằm ngửa này. ",
  "mn78:8.9": "Bốn pháp đó là gì? ",
  "mn78:8.10": "Ở đây, này gia chủ, người ấy không làm ác nghiệp bằng thân, không nói lời ác, không suy nghĩ ác, không sống bằng tà mạng—",
  "mn78:8.11": "Này gia chủ, tôi tuyên bố một người có đủ bốn pháp này không phải là người thiện xảo hoàn toàn, không phải thiện xảo tối thượng, không đạt được thành tựu tối cao, không phải là một Sa-môn không thể bị đánh bại, mà còn thua kém cả đứa trẻ sơ sinh, non nớt, nằm ngửa này. ",
  "mn78:9.1": "Này gia chủ, tôi tuyên bố một người có đủ mười pháp là người thiện xảo hoàn toàn, thiện xảo tối thượng, đạt được thành tựu tối cao, là một Sa-môn không thể bị đánh bại. ",
  "mn78:9.2": "Đây là các giới bất thiện; ",
  "mn78:9.3": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.4": "Các giới bất thiện này khởi lên từ đó; ",
  "mn78:9.5": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.6": "Ở đây, các giới bất thiện này diệt tận không còn sót lại; ",
  "mn78:9.7": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.8": "Người thực hành như vậy là đang thực hành để diệt trừ các giới bất thiện; ",
  "mn78:9.9": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.10": "Đây là các giới thiện; ",
  "mn78:9.11": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.12": "Các giới thiện này khởi lên từ đó; ",
  "mn78:9.13": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.14": "Ở đây, các giới thiện này diệt tận không còn sót lại; ",
  "mn78:9.15": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.16": "Người thực hành như vậy là đang thực hành để diệt trừ các giới thiện; ",
  "mn78:9.17": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.18": "Đây là các ý nghĩ bất thiện; ",
  "mn78:9.19": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.20": "Các ý nghĩ bất thiện này khởi lên từ đó; ",
  "mn78:9.21": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.22": "Ở đây, các ý nghĩ bất thiện này diệt tận không còn sót lại; ",
  "mn78:9.23": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.24": "Người thực hành như vậy là đang thực hành để diệt trừ các ý nghĩ bất thiện; ",
  "mn78:9.25": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.26": "Đây là các ý nghĩ thiện; ",
  "mn78:9.27": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.28": "Các ý nghĩ thiện này khởi lên từ đó; ",
  "mn78:9.29": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.30": "Ở đây, các ý nghĩ thiện này diệt tận không còn sót lại; ",
  "mn78:9.31": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:9.32": "Người thực hành như vậy là đang thực hành để diệt trừ các ý nghĩ thiện; ",
  "mn78:9.33": "này gia chủ, tôi nói rằng điều đó cần phải được biết. ",
  "mn78:10.1": "Này gia chủ, thế nào là các giới bất thiện? ",
  "mn78:10.2": "Ác nghiệp thân, ác nghiệp khẩu, tà mạng—",
  "mn78:10.3": "này gia chủ, đây được gọi là các giới bất thiện. ",
  "mn78:10.4": "Này gia chủ, các giới bất thiện này khởi lên từ đâu? ",
  "mn78:10.5": "Nguồn gốc của chúng cũng đã được nói. ",
  "mn78:10.6": "Cần phải nói rằng: ‘Khởi lên từ tâm’. ",
  "mn78:10.7": "Tâm nào? ",
  "mn78:10.8": "Tâm thì có nhiều loại, đủ thứ, khác nhau. ",
  "mn78:10.9": "Tâm nào có tham, có sân, có si, thì các giới bất thiện này khởi lên từ đó. ",
  "mn78:10.10": "Này gia chủ, các giới bất thiện này diệt tận không còn sót lại ở đâu? ",
  "mn78:10.11": "Sự diệt trừ của chúng cũng đã được nói. ",
  "mn78:10.12": "Ở đây, này gia chủ, Tỳ-kheo từ bỏ ác hạnh thân, tu tập thiện hạnh thân; từ bỏ ác hạnh khẩu, tu tập thiện hạnh khẩu; từ bỏ ác hạnh ý, tu tập thiện hạnh ý; từ bỏ tà mạng, sống bằng chánh mạng—",
  "mn78:10.13": "chính ở đây, các giới bất thiện này diệt tận không còn sót lại. ",
  "mn78:10.14": "Này gia chủ, người thực hành như thế nào là đang thực hành để diệt trừ các giới bất thiện? ",
  "mn78:10.15": "Ở đây, này gia chủ, Tỳ-kheo phát sinh ý muốn, nỗ lực, tinh tấn, giữ tâm, và cố gắng để các pháp bất thiện, ác chưa sinh không sinh khởi; ",
  "mn78:10.16": "phát sinh ý muốn, nỗ lực, tinh tấn, giữ tâm, và cố gắng để các pháp bất thiện, ác đã sinh được đoạn trừ; ",
  "mn78:10.17": "phát sinh ý muốn, nỗ lực, tinh tấn, giữ tâm, và cố gắng để các pháp thiện chưa sinh được sinh khởi; ",
  "mn78:10.18": "phát sinh ý muốn, nỗ lực, tinh tấn, giữ tâm, và cố gắng để các pháp thiện đã sinh được duy trì, không bị quên lãng, được tăng trưởng, được phát triển, được tu tập, được viên mãn. ",
  "mn78:10.19": "Này gia chủ, người thực hành như vậy là đang thực hành để diệt trừ các giới bất thiện. ",
  "mn78:11.1": "Này gia chủ, thế nào là các giới thiện? ",
  "mn78:11.2": "Thiện nghiệp thân, thiện nghiệp khẩu, và này gia chủ, tôi nói rằng sự thanh tịnh về sinh kế cũng thuộc về giới. ",
  "mn78:11.3": "Này gia chủ, đây được gọi là các giới thiện. ",
  "mn78:11.4": "Này gia chủ, các giới thiện này khởi lên từ đâu? ",
  "mn78:11.5": "Nguồn gốc của chúng cũng đã được nói. ",
  "mn78:11.6": "Cần phải nói rằng: ‘Khởi lên từ tâm’. ",
  "mn78:11.7": "Tâm nào? ",
  "mn78:11.8": "Tâm thì có nhiều loại, đủ thứ, khác nhau. ",
  "mn78:11.9": "Tâm nào không tham, không sân, không si, thì các giới thiện này khởi lên từ đó. ",
  "mn78:11.10": "Này gia chủ, các giới thiện này diệt tận không còn sót lại ở đâu? ",
  "mn78:11.11": "Sự diệt trừ của chúng cũng đã được nói. ",
  "mn78:11.12": "Ở đây, này gia chủ, Tỳ-kheo có giới nhưng không bị giới trói buộc, ",
  "mn78:11.13": "và vị ấy như thật biết sự giải thoát tâm, sự giải thoát tuệ; chính ở đó, các giới thiện của vị ấy diệt tận không còn sót lại. ",
  "mn78:11.14": "Này gia chủ, người thực hành như thế nào là đang thực hành để diệt trừ các giới thiện? ",
  "mn78:11.15": "Ở đây, này gia chủ, Tỳ-kheo phát sinh ý muốn, nỗ lực, tinh tấn, giữ tâm, và cố gắng để các pháp bất thiện, ác chưa sinh không sinh khởi; ",
  "mn78:11.16": "để các pháp bất thiện, ác đã sinh được đoạn trừ …v.v… ",
  "mn78:11.17": "để các pháp thiện chưa sinh được sinh khởi …v.v… ",
  "mn78:11.18": "để các pháp thiện đã sinh được duy trì, không bị quên lãng, được tăng trưởng, được phát triển, được tu tập, được viên mãn. ",
  "mn78:11.19": "Này gia chủ, người thực hành như vậy là đang thực hành để diệt trừ các giới thiện. ",
  "mn78:12.1": "Này gia chủ, thế nào là các ý nghĩ bất thiện? ",
  "mn78:12.2": "Ý nghĩ dục, ý nghĩ sân, ý nghĩ hại—",
  "mn78:12.3": "này gia chủ, đây được gọi là các ý nghĩ bất thiện. ",
  "mn78:12.4": "Này gia chủ, các ý nghĩ bất thiện này khởi lên từ đâu? ",
  "mn78:12.5": "Cội nguồn của chúng cũng đã được nói đến.",
  "mn78:12.6": "Phải nói rằng: ‘Cội nguồn của chúng là tưởng’.",
  "mn78:12.7": "Tưởng là gì?",
  "mn78:12.8": "Tưởng cũng có nhiều loại, nhiều cách, nhiều hình thức khác nhau.",
  "mn78:12.9": "Tưởng dục, tưởng sân, tưởng hại—",
  "mn78:12.10": "Từ đó mà các tư duy bất thiện khởi lên.",
  "mn78:12.11": "Này gia chủ, các tư duy bất thiện này diệt tận không còn sót lại ở đâu?",
  "mn78:12.12": "Sự diệt trừ của chúng cũng đã được nói đến.",
  "mn78:12.13": "Này gia chủ, ở đây, tỳ kheo ly dục …pe… chứng và trú thiền thứ nhất;",
  "mn78:12.14": "ở đó, các tư duy bất thiện này diệt tận không còn sót lại.",
  "mn78:12.15": "Này gia chủ, hành trì như thế nào thì hành trì để diệt trừ các tư duy bất thiện?",
  "mn78:12.16": "Này gia chủ, ở đây, tỳ kheo phát ý muốn, cố gắng, tinh tấn, giữ tâm, nỗ lực để các pháp bất thiện, ác chưa sinh không sinh khởi;",
  "mn78:12.17": "để các pháp bất thiện, ác đã sinh được đoạn trừ …pe…",
  "mn78:12.18": "để các pháp thiện chưa sinh được sinh khởi …pe…",
  "mn78:12.19": "để các pháp thiện đã sinh được tồn tại, không bị quên lãng, được tăng trưởng, được phát triển, được tu tập, được viên mãn, tỳ kheo phát ý muốn, cố gắng, tinh tấn, giữ tâm, nỗ lực.",
  "mn78:12.20": "Này gia chủ, hành trì như vậy là hành trì để diệt trừ các tư duy bất thiện.",
  "mn78:13.1": "Này gia chủ, các tư duy thiện là gì?",
  "mn78:13.2": "Tư duy xuất ly, tư duy không sân, tư duy không hại—",
  "mn78:13.3": "Này gia chủ, đây được gọi là các tư duy thiện.",
  "mn78:13.4": "Này gia chủ, các tư duy thiện này có cội nguồn từ đâu?",
  "mn78:13.5": "Cội nguồn của chúng cũng đã được nói đến.",
  "mn78:13.6": "Phải nói rằng: ‘Cội nguồn của chúng là tưởng’.",
  "mn78:13.7": "Tưởng là gì?",
  "mn78:13.8": "Tưởng cũng có nhiều loại, nhiều cách, nhiều hình thức khác nhau.",
  "mn78:13.9": "Tưởng xuất ly, tưởng không sân, tưởng không hại—",
  "mn78:13.10": "Từ đó mà các tư duy thiện khởi lên.",
  "mn78:13.11": "Này gia chủ, các tư duy thiện này diệt tận không còn sót lại ở đâu?",
  "mn78:13.12": "Sự diệt trừ của chúng cũng đã được nói đến.",
  "mn78:13.13": "Này gia chủ, ở đây, tỳ kheo làm lắng dịu tầm và tứ …pe… chứng và trú thiền thứ hai;",
  "mn78:13.14": "ở đó, các tư duy thiện này diệt tận không còn sót lại.",
  "mn78:13.15": "Này gia chủ, hành trì như thế nào thì hành trì để diệt trừ các tư duy thiện?",
  "mn78:13.16": "Này gia chủ, ở đây, tỳ kheo phát ý muốn, cố gắng, tinh tấn, giữ tâm, nỗ lực để các pháp bất thiện, ác chưa sinh không sinh khởi;",
  "mn78:13.17": "để các pháp bất thiện, ác đã sinh được đoạn trừ …pe…",
  "mn78:13.18": "để các pháp thiện chưa sinh được sinh khởi …pe…",
  "mn78:13.19": "để các pháp thiện đã sinh được tồn tại, không bị quên lãng, được tăng trưởng, được phát triển, được tu tập, được viên mãn, tỳ kheo phát ý muốn, cố gắng, tinh tấn, giữ tâm, nỗ lực.",
  "mn78:13.20": "Này gia chủ, hành trì như vậy là hành trì để diệt trừ các tư duy thiện.",
  "mn78:14.1": "Này gia chủ, với mười pháp nào, ta tuyên bố một người là thiện đầy đủ, thiện tối thượng, đạt được thành tựu cao nhất, là sa môn không thể bị đánh bại?",
  "mn78:14.2": "Này gia chủ, ở đây, tỳ kheo có chánh kiến vô học, có chánh tư duy vô học, có chánh ngữ vô học, có chánh nghiệp vô học, có chánh mạng vô học, có chánh tinh tấn vô học, có chánh niệm vô học, có chánh định vô học, có chánh trí vô học, có chánh giải thoát vô học—",
  "mn78:14.3": "Này gia chủ, với mười pháp này, ta tuyên bố một người là thiện đầy đủ, thiện tối thượng, đạt được thành tựu cao nhất, là sa môn không thể bị đánh bại.",
  "mn78:14.4": "Thế Tôn đã nói điều này.",
  "mn78:14.5": "Gia chủ Pañcakaṅga hoan hỷ, tán thán lời Thế Tôn dạy.",
  "mn78:14.6": "Kinh Sa Môn Muṇḍika, thứ tám, chấm dứt."
}
window.BILARA["mn78"]["vi"]["mn78:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
