window.BILARA = window.BILARA || {};
window.BILARA["mn84"] = window.BILARA["mn84"] || {};
window.BILARA["mn84"]["vi"] = {
  "mn84:0.1": "Trung Bộ Kinh 84",
  "mn84:0.2": "Kinh ở Madhurā",
  "mn84:1.1": "Tôi nghe như vầy—",
  "mn84:1.2": "Có một thời, ngài Đại Ca Chiên Diên ở tại Madhurā, trong rừng Gundā.",
  "mn84:2.1": "Vua Madhurā, con của xứ Avanti, nghe tin:",
  "mn84:2.2": "“Này các ông, sa môn Ca Chiên Diên đang ở tại Madhurā, trong rừng Gundā.",
  "mn84:2.3": "Về ngài Ca Chiên Diên ấy, tiếng tốt được đồn lên như sau:",
  "mn84:2.4": "‘là người sáng dạ, khéo léo, hiểu sâu, nghe học nhiều, nói năng rõ ràng, đối đáp hay, lại đã lớn tuổi và là bậc đã làm xong’.",
  "mn84:2.5": "Thật tốt khi được gặp những bậc đã làm xong như vậy.”",
  "mn84:3.1": "Rồi vua Madhurā, con của xứ Avanti, cho thắng những cỗ xe tốt nhất, lên một cỗ xe tốt, cùng với nhiều cỗ xe tốt khác đi ra khỏi Madhurā, với uy thế lớn của bậc vua chúa, để gặp ngài Đại Ca Chiên Diên.",
  "mn84:3.2": "Đi xe đến chỗ xe còn đi được, rồi xuống xe và đi bộ đến chỗ ngài Đại Ca Chiên Diên. Đến nơi, vua chào hỏi thân tình với ngài Đại Ca Chiên Diên. Sau khi nói với nhau những lời thân tình gợi nhớ, vua ngồi xuống một bên. Ngồi xuống một bên rồi, vua Madhurā, con của xứ Avanti, nói với ngài Đại Ca Chiên Diên như vầy:",
  "mn84:4.1": "“Này ngài Ca Chiên Diên, các bà la môn nói như vầy:",
  "mn84:4.2": "‘Chỉ bà la môn mới là hạng cao nhất, các hạng khác đều thấp hơn;",
  "mn84:4.3": "chỉ bà la môn mới là hạng trắng, các hạng khác là đen;",
  "mn84:4.4": "chỉ bà la môn mới sạch, không phải người không phải bà la môn;",
  "mn84:4.5": "chỉ bà la môn mới là con của Phạm thiên, sinh ra từ chính miệng Phạm thiên, do Phạm thiên sinh ra, do Phạm thiên tạo ra, là người thừa hưởng của Phạm thiên.’",
  "mn84:4.6": "Ngài Ca Chiên Diên nói sao về việc này?”",
  "mn84:5.1": "“Thưa đại vương, đó chỉ là tiếng nói ở đời:",
  "mn84:5.2": "‘Chỉ bà la môn mới là hạng cao nhất, các hạng khác đều thấp hơn;",
  "mn84:5.3": "chỉ bà la môn mới là hạng trắng, các hạng khác là đen;",
  "mn84:5.4": "chỉ bà la môn mới sạch, không phải người không phải bà la môn;",
  "mn84:5.5": "chỉ bà la môn mới là con của Phạm thiên, sinh ra từ chính miệng Phạm thiên, do Phạm thiên sinh ra, do Phạm thiên tạo ra, là người thừa hưởng của Phạm thiên.’",
  "mn84:5.6": "Điều ấy, thưa đại vương, có thể hiểu theo cách này, rằng đó chỉ là tiếng nói ở đời:",
  "mn84:5.7": "‘Chỉ bà la môn mới là hạng cao nhất, các hạng khác đều thấp hơn …",
  "mn84:5.8": "là người thừa hưởng của Phạm thiên.’",
  "mn84:5.9": "Đại vương nghĩ sao,",
  "mn84:5.10": "nếu một người thuộc dòng sát đế lỵ được thành công về của cải, lúa thóc, bạc hay vàng, thì một người sát đế lỵ khác cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử vừa ý, nói lời dễ nghe …",
  "mn84:5.11": "một bà la môn cũng sẽ như vậy …",
  "mn84:5.12": "một người buôn bán cũng sẽ như vậy …",
  "mn84:5.13": "một người làm thuê cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử vừa ý, nói lời dễ nghe chăng?”",
  "mn84:5.14": "“Này ông Kaccāna, nếu một người Sát Đế Lỵ thành công, có của cải, lúa thóc, bạc hay vàng, thì một người Sát Đế Lỵ cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe …",
  "mn84:5.15": "một người Bà La Môn cũng sẽ như vậy với người ấy …",
  "mn84:5.16": "một người Vệ Xá cũng sẽ như vậy với người ấy …",
  "mn84:5.17": "một người Thủ Đà cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe.”",
  "mn84:5.18": "“Đại vương nghĩ sao,",
  "mn84:5.19": "nếu một người Bà La Môn thành công, có của cải, lúa thóc, bạc hay vàng, thì một người Bà La Môn cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe …",
  "mn84:5.20": "một người Vệ Xá cũng sẽ như vậy với người ấy …",
  "mn84:5.21": "một người Thủ Đà cũng sẽ như vậy với người ấy …",
  "mn84:5.22": "một người Sát Đế Lỵ cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe chăng?”",
  "mn84:5.23": "“Này ông Kaccāna, nếu một người Bà La Môn thành công, có của cải, lúa thóc, bạc hay vàng, thì một người Bà La Môn cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe …",
  "mn84:5.24": "một người Vệ Xá cũng sẽ như vậy với người ấy …",
  "mn84:5.25": "một người Thủ Đà cũng sẽ như vậy với người ấy …",
  "mn84:5.26": "một người Sát Đế Lỵ cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe.”",
  "mn84:5.27": "“Đại vương nghĩ sao, nếu một người Vệ Xá thành công, có của cải, lúa thóc, bạc hay vàng, thì một người Vệ Xá cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe …",
  "mn84:5.28": "một người Thủ Đà cũng sẽ như vậy với người ấy …",
  "mn84:5.29": "một người Sát Đế Lỵ cũng sẽ như vậy với người ấy …",
  "mn84:5.30": "một người Bà La Môn cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe chăng?”",
  "mn84:5.31": "“Này ông Kaccāna, nếu một người Vệ Xá thành công, có của cải, lúa thóc, bạc hay vàng, thì một người Vệ Xá cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe …",
  "mn84:5.32": "một người Thủ Đà cũng sẽ như vậy với người ấy …",
  "mn84:5.33": "một người Sát Đế Lỵ cũng sẽ như vậy với người ấy …",
  "mn84:5.34": "một người Bà La Môn cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe.”",
  "mn84:5.35": "“Đại vương nghĩ sao, nếu một người Thủ Đà thành công, có của cải, lúa thóc, bạc hay vàng, thì một người Thủ Đà cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe …",
  "mn84:5.36": "một người Sát Đế Lỵ cũng sẽ như vậy với người ấy …",
  "mn84:5.37": "một người Bà La Môn cũng sẽ như vậy với người ấy …",
  "mn84:5.38": "một người Vệ Xá cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe chăng?”",
  "mn84:5.39": "“Này ông Kaccāna, nếu một người Thủ Đà thành công, có của cải, lúa thóc, bạc hay vàng, thì một người Thủ Đà cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe …",
  "mn84:5.40": "một người Sát Đế Lỵ cũng sẽ như vậy với người ấy …",
  "mn84:5.41": "một người Bà La Môn cũng sẽ như vậy với người ấy …",
  "mn84:5.42": "một người Vệ Xá cũng sẽ dậy trước người ấy, ngồi sau người ấy, làm theo lời sai bảo, cư xử cho vừa lòng, nói lời dễ nghe.”",
  "mn84:5.43": "“Đại vương nghĩ sao,",
  "mn84:5.44": "Nếu là vậy, bốn giai cấp này có ngang nhau hay không?",
  "mn84:5.45": "Đại vương nghĩ sao về việc này?",
  "mn84:5.46": "Thưa ngài Kaccāna, đúng là nếu vậy thì bốn giai cấp này ngang nhau.",
  "mn84:5.47": "Tôi không thấy ở đây có chút gì khác nhau giữa họ.",
  "mn84:5.48": "Thưa Đại vương, cũng từ cách này có thể biết rằng tiếng đồn trong đời là như vậy:",
  "mn84:5.49": "‘Chỉ giai cấp bà-la-môn là cao quý nhất, các giai cấp khác là thấp kém …",
  "mn84:5.50": "là con cháu của Phạm thiên’.",
  "mn84:6.1": "Đại vương nghĩ sao,",
  "mn84:6.2": "ở đây, nếu một người thuộc dòng vua chúa giết hại sinh mạng, lấy của không cho, ăn nằm sai trái, nói dối, nói hai lưỡi, nói lời thô ác, nói chuyện rỗng không, tham lam, ôm lòng hại người, thấy sai, thì khi thân tan rã, sau khi chết, có sinh vào cảnh xấu, nơi khốn khổ, chỗ sa đọa, địa ngục hay không?",
  "mn84:6.3": "Đại vương nghĩ sao về việc này?",
  "mn84:6.4": "Thưa ngài Kaccāna, người thuộc dòng vua chúa cũng vậy, nếu giết hại sinh mạng, lấy của không cho, ăn nằm sai trái, nói dối, nói hai lưỡi, nói lời thô ác, nói chuyện rỗng không, tham lam, ôm lòng hại người, thấy sai, thì khi thân tan rã, sau khi chết, sẽ sinh vào cảnh xấu, nơi khốn khổ, chỗ sa đọa, địa ngục.",
  "mn84:6.5": "Tôi nghĩ như vậy, và tôi cũng đã nghe điều này từ những vị đáng kính.",
  "mn84:6.6": "Lành thay, lành thay, Đại vương.",
  "mn84:6.7": "Đại vương nghĩ như vậy là phải, và Đại vương cũng đã nghe điều này từ những vị đáng kính là phải.",
  "mn84:6.8": "Đại vương nghĩ sao,",
  "mn84:6.9": "ở đây, nếu một người bà-la-môn …",
  "mn84:6.10": "ở đây, nếu một người làm ăn buôn bán …",
  "mn84:6.11": "ở đây, nếu một người thuộc hạng tôi tớ giết hại sinh mạng, lấy của không cho … thấy sai, thì khi thân tan rã, sau khi chết, có sinh vào cảnh xấu, nơi khốn khổ, chỗ sa đọa, địa ngục hay không?",
  "mn84:6.12": "Đại vương nghĩ sao về việc này?",
  "mn84:6.13": "Thưa ngài Kaccāna, người thuộc hạng tôi tớ cũng vậy, nếu giết hại sinh mạng, lấy của không cho … thấy sai, thì khi thân tan rã, sau khi chết, sẽ sinh vào cảnh xấu, nơi khốn khổ, chỗ sa đọa, địa ngục.",
  "mn84:6.14": "Tôi nghĩ như vậy, và tôi cũng đã nghe điều này từ những vị đáng kính.",
  "mn84:6.15": "Lành thay, lành thay, Đại vương.",
  "mn84:6.16": "Đại vương nghĩ như vậy là phải, và Đại vương cũng đã nghe điều này từ những vị đáng kính là phải.",
  "mn84:6.17": "Đại vương nghĩ sao,",
  "mn84:6.18": "nếu là vậy, bốn giai cấp này có ngang nhau hay không?",
  "mn84:6.19": "Đại vương nghĩ sao về việc này?",
  "mn84:6.20": "Thưa ngài Kaccāna, đúng là nếu vậy thì bốn giai cấp này ngang nhau.",
  "mn84:6.21": "Tôi không thấy ở đây có chút gì khác nhau giữa họ.",
  "mn84:6.22": "Thưa Đại vương, cũng từ cách này có thể biết rằng tiếng đồn trong đời là như vậy:",
  "mn84:6.23": "‘Chỉ giai cấp bà-la-môn là cao quý nhất, các giai cấp khác là thấp kém … là con cháu của Phạm thiên’.",
  "mn84:7.1": "“Đại vương nghĩ sao,",
  "mn84:7.2": "ở đây, nếu một người dòng vua tránh giết hại sinh mạng, tránh lấy của không cho, tránh ăn nằm sai trái, tránh nói dối, tránh nói lời chia rẽ, tránh nói lời thô ác, tránh nói chuyện nhảm, không tham muốn, lòng không ác ý, thấy đúng, thì khi thân tan rã, sau khi chết, có sinh vào cõi lành, cõi trời hay không?",
  "mn84:7.3": "Đại vương nghĩ việc này thế nào?”",
  "mn84:7.4": "“Thưa ngài Kaccāna, người dòng vua cũng vậy, nếu tránh giết hại sinh mạng, tránh lấy của không cho, tránh ăn nằm sai trái, tránh nói dối, tránh nói lời chia rẽ, tránh nói lời thô ác, tránh nói chuyện nhảm, không tham muốn, lòng không ác ý, thấy đúng, thì khi thân tan rã, sau khi chết, sẽ sinh vào cõi lành, cõi trời.",
  "mn84:7.5": "Tôi nghĩ như vậy, và tôi cũng đã nghe điều này từ các bậc đáng kính.”",
  "mn84:7.6": "“Lành thay, lành thay, Đại vương.",
  "mn84:7.7": "Đại vương nghĩ như vậy là phải, và Đại vương cũng đã nghe điều này từ các bậc đáng kính là phải.",
  "mn84:7.8": "Đại vương nghĩ sao,",
  "mn84:7.9": "ở đây, nếu một người dòng Bà-la-môn, một người dòng buôn bán, một người dòng làm thuê tránh giết hại sinh mạng, tránh lấy của không cho … thấy đúng, thì khi thân tan rã, sau khi chết, có sinh vào cõi lành, cõi trời hay không?",
  "mn84:7.10": "Đại vương nghĩ việc này thế nào?”",
  "mn84:7.11": "“Thưa ngài Kaccāna, người dòng làm thuê cũng vậy, nếu tránh giết hại sinh mạng, tránh lấy của không cho … thấy đúng, thì khi thân tan rã, sau khi chết, sẽ sinh vào cõi lành, cõi trời.",
  "mn84:7.12": "Tôi nghĩ như vậy, và tôi cũng đã nghe điều này từ các bậc đáng kính.”",
  "mn84:7.13": "“Lành thay, lành thay, Đại vương.",
  "mn84:7.14": "Đại vương nghĩ như vậy là phải, và Đại vương cũng đã nghe điều này từ các bậc đáng kính là phải.",
  "mn84:7.15": "Đại vương nghĩ sao,",
  "mn84:7.16": "nếu là vậy, bốn hạng người này có ngang nhau hay không?",
  "mn84:7.17": "Đại vương nghĩ việc này thế nào?”",
  "mn84:7.18": "“Quả thật, thưa ngài Kaccāna, nếu là vậy, bốn hạng người này là ngang nhau.",
  "mn84:7.19": "Tôi không thấy ở đây có gì khác nhau cả.”",
  "mn84:7.20": "“Ngay bằng cách này nữa, Đại vương cũng nên biết rằng lời đồn trong đời này rằng:",
  "mn84:7.21": "‘chỉ có Bà-la-môn là hạng cao nhất, các hạng khác là thấp hơn … là con cháu của Phạm thiên’.”",
  "mn84:8.1": "“Đại vương nghĩ sao,",
  "mn84:8.2": "ở đây, nếu một người dòng vua phá khoét, cướp bóc, cướp cả một nhà, đứng chặn đường cướp, hay đi với vợ người khác, rồi người ta bắt được và dẫn đến cho Đại vương:",
  "mn84:8.3": "‘Tâu Đại vương, đây là kẻ trộm, kẻ làm điều xấu.",
  "mn84:8.4": "Xin Đại vương phạt nó theo điều Đại vương muốn.’",
  "mn84:8.5": "Đại vương sẽ làm gì với người ấy?”",
  "mn84:8.6": "“Thưa ngài Kaccāna, chúng tôi có thể giết, phạt vạ, đuổi đi, hay xử theo điều thích hợp.",
  "mn84:8.7": "Vì sao vậy?",
  "mn84:8.8": "Vì, thưa ngài Kaccāna, cái tên gọi trước kia là ‘người dòng vua’ của nó không còn nữa; nó chỉ bị kể là kẻ trộm thôi.”",
  "mn84:8.9": "“Đại vương nghĩ sao,”",
  "mn84:8.10": "Ở đây, một người Bà-la-môn, một người Vệ-xá, hay một người Thủ-đà, nếu phá vách vào nhà, hay cướp bóc, hay vét sạch một nhà, hay đứng chặn đường, hay đi với vợ người khác, rồi người ta bắt được và dẫn đến cho ngài rằng:",
  "mn84:8.11": "‘Tâu đại vương, đây là kẻ trộm, làm điều sai quấy.",
  "mn84:8.12": "Xin ngài đặt hình phạt nào tùy ý cho kẻ này.’",
  "mn84:8.13": "Thì ngài sẽ làm gì với người ấy?”",
  "mn84:8.14": "“Này ngài Kaccāna, chúng tôi có thể giết, hay phạt vạ, hay đuổi đi, hay làm theo điều thích hợp.",
  "mn84:8.15": "Vì sao vậy?",
  "mn84:8.16": "Vì tên gọi trước kia của người ấy là ‘Thủ-đà’ đã mất rồi; người ấy chỉ còn bị kể là kẻ trộm thôi.”",
  "mn84:8.17": "“Đại vương nghĩ sao,",
  "mn84:8.18": "nếu là vậy thì bốn hạng này có ngang nhau hay không?",
  "mn84:8.19": "Ngài thấy việc này thế nào?”",
  "mn84:8.20": "“Quả thật, này ngài Kaccāna, nếu là vậy thì bốn hạng này ngang nhau.",
  "mn84:8.21": "Tôi không thấy ở đây có gì khác nhau.”",
  "mn84:8.22": "“Cũng bằng cách này, thưa đại vương, có thể biết rằng lời đồn trong đời này rằng:",
  "mn84:8.23": "‘Chỉ Bà-la-môn mới là hạng cao nhất, các hạng khác đều thấp hơn … con cháu của Phạm thiên’ chỉ là tiếng nói suông thôi.”",
  "mn84:9.1": "“Đại vương nghĩ sao,",
  "mn84:9.2": "ở đây, nếu một người Sát-đế-lỵ cạo bỏ tóc râu, khoác áo màu đất, từ bỏ nhà cửa sống không nhà, đã tránh xa giết hại, tránh xa lấy của không cho, tránh xa nói dối, không ăn ban đêm, ăn một bữa, sống đời trong sạch, giữ nết tốt, có các điều lành.",
  "mn84:9.3": "Thì ngài sẽ làm gì với người ấy?”",
  "mn84:9.4": "“Này ngài Kaccāna, chúng tôi sẽ chào người ấy, sẽ đứng dậy đón, sẽ mời ngồi, sẽ kính mời, và sẽ sắp đặt cho người ấy y áo, đồ ăn khất thực, chỗ nằm chỗ ngồi, thuốc men và vật dùng khi đau ốm; hoặc sẽ lo cho người ấy sự che chở, bảo bọc và giữ gìn đúng lẽ phải.",
  "mn84:9.5": "Vì sao vậy?",
  "mn84:9.6": "Vì tên gọi trước kia của người ấy là ‘Sát-đế-lỵ’ đã mất rồi; người ấy chỉ còn được kể là một vị sa-môn thôi.”",
  "mn84:9.7": "“Đại vương nghĩ sao,",
  "mn84:9.8": "ở đây, một người Bà-la-môn, một người Vệ-xá, hay một người Thủ-đà cạo bỏ tóc râu, khoác áo màu đất, từ bỏ nhà cửa sống không nhà, đã tránh xa giết hại, tránh xa lấy của không cho, tránh xa nói dối, không ăn ban đêm, ăn một bữa, sống đời trong sạch, giữ nết tốt, có các điều lành.",
  "mn84:9.9": "Thì ngài sẽ làm gì với người ấy?”",
  "mn84:9.10": "“Này ngài Kaccāna, chúng tôi sẽ chào người ấy, sẽ đứng dậy đón, sẽ mời ngồi, sẽ kính mời, và sẽ sắp đặt cho người ấy y áo, đồ ăn khất thực, chỗ nằm chỗ ngồi, thuốc men và vật dùng khi đau ốm; hoặc sẽ lo cho người ấy sự che chở, bảo bọc và giữ gìn đúng lẽ phải.",
  "mn84:9.11": "Vì sao vậy?",
  "mn84:9.12": "Vì tên gọi trước kia của người ấy là ‘Thủ-đà’ đã mất rồi; người ấy chỉ còn được kể là một vị sa-môn thôi.”",
  "mn84:9.13": "“Đại vương nghĩ sao,",
  "mn84:9.14": "nếu là vậy thì bốn hạng này có ngang nhau hay không?",
  "mn84:9.15": "Ngài thấy việc này thế nào?”",
  "mn84:9.16": "“Quả thật, này ngài Kaccāna, nếu là vậy thì bốn hạng này ngang nhau.”",
  "mn84:9.17": "Tôi không thấy ở đây có chút gì khác nhau giữa họ.",
  "mn84:9.18": "Thưa đại vương, cũng từ cách này có thể biết rằng trong đời chỉ có tiếng đồn như sau:",
  "mn84:9.19": "‘Chỉ giai cấp bà-la-môn là cao quý, giai cấp khác là thấp kém;",
  "mn84:9.20": "chỉ giai cấp bà-la-môn là trắng, giai cấp khác là đen;",
  "mn84:9.21": "chỉ bà-la-môn mới được trong sạch, không phải người không phải bà-la-môn;",
  "mn84:9.22": "chỉ bà-la-môn là con của Phạm thiên, là con ruột sinh ra từ miệng Phạm thiên, do Phạm thiên sinh ra, do Phạm thiên tạo ra, là người thừa hưởng của Phạm thiên.’",
  "mn84:10.1": "Khi được nói vậy, vua Madhurā, con của xứ Avanti, nói với ngài Mahākaccāna rằng:",
  "mn84:10.2": "“Hay lắm, thưa ngài Kaccāna, hay lắm, thưa ngài Kaccāna.",
  "mn84:10.3": "Ví như, thưa ngài Kaccāna, dựng vật bị úp xuống cho ngửa lên, mở ra vật bị che kín, chỉ đường cho người lạc lối, đem đèn dầu vào chỗ tối để người có mắt thấy được hình sắc; cũng vậy, ngài Kaccāna đã dùng nhiều cách làm sáng tỏ lời dạy.",
  "mn84:10.4": "Con xin nương tựa ngài Kaccāna, nương tựa lời dạy và nương tựa chúng Tỳ Kheo.",
  "mn84:10.5": "Xin ngài Kaccāna ghi nhận con là người tại gia nương tựa từ nay cho đến trọn đời.”",
  "mn84:10.6": "“Thưa đại vương, xin đừng nương tựa tôi.",
  "mn84:10.7": "Đại vương hãy nương tựa chính Đức Thế Tôn, bậc mà tôi đã nương tựa.”",
  "mn84:10.8": "“Thưa ngài Kaccāna, hiện nay Đức Thế Tôn, bậc Ứng Cúng, bậc tự mình giác ngộ trọn vẹn, đang ở đâu?”",
  "mn84:10.9": "“Thưa đại vương, hiện nay Đức Thế Tôn, bậc Ứng Cúng, bậc tự mình giác ngộ trọn vẹn, đã tắt hẳn rồi.”",
  "mn84:11.1": "“Thưa ngài Kaccāna, nếu chúng con nghe rằng Đức Thế Tôn ấy ở cách mười do-tuần, thì chúng con cũng sẽ đi mười do-tuần để được gặp Đức Thế Tôn, bậc Ứng Cúng, bậc tự mình giác ngộ trọn vẹn.",
  "mn84:11.2": "Thưa ngài Kaccāna, nếu chúng con nghe rằng Đức Thế Tôn ấy ở cách hai mươi do-tuần, ba mươi do-tuần, bốn mươi do-tuần, năm mươi do-tuần, thì chúng con cũng sẽ đi năm mươi do-tuần để được gặp Đức Thế Tôn, bậc Ứng Cúng, bậc tự mình giác ngộ trọn vẹn.",
  "mn84:11.3": "Thưa ngài Kaccāna, nếu chúng con nghe rằng Đức Thế Tôn ấy ở cách một trăm do-tuần, thì chúng con cũng sẽ đi một trăm do-tuần để được gặp Đức Thế Tôn, bậc Ứng Cúng, bậc tự mình giác ngộ trọn vẹn.",
  "mn84:11.4": "Nhưng vì Đức Thế Tôn ấy đã tắt hẳn rồi, nên chúng con xin nương tựa Đức Thế Tôn đã tắt hẳn, nương tựa lời dạy và nương tựa chúng Tỳ Kheo.",
  "mn84:11.5": "Xin ngài Kaccāna ghi nhận con là người tại gia nương tựa từ nay cho đến trọn đời.”",
  "mn84:11.6": "Kinh Madhura chấm dứt, bài thứ tư."
}
window.BILARA["mn84"]["vi"]["mn84:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
