window.BILARA = window.BILARA || {};
window.BILARA["mn85"] = window.BILARA["mn85"] || {};
window.BILARA["mn85"]["vi"] = {
  "mn85:0.1": "Trung Bộ Kinh 85",
  "mn85:0.2": "Kinh Hoàng tử Bodhi",
  "mn85:1.1": "Tôi nghe như vầy—",
  "mn85:1.2": "Một thời, Đức Thế Tôn ở xứ Bhagga, tại núi Susumāra, trong rừng Bhesakaḷā, nơi nai ở.",
  "mn85:2.1": "Lúc ấy, Hoàng tử Bodhi vừa cho xây xong một lầu đài tên là Kokanada, chưa từng có sa môn, bà la môn, hay bất cứ người nào ở trong đó.",
  "mn85:3.1": "Rồi Hoàng tử Bodhi gọi chàng thanh niên Sañjikāputta:",
  "mn85:3.2": "“Này anh Sañjikāputta, hãy đi đến chỗ Đức Thế Tôn; đến rồi, nhân danh ta, cúi đầu đảnh lễ dưới chân Đức Thế Tôn, và hỏi thăm Ngài có ít bệnh, ít đau, đi đứng nhẹ nhàng, có sức, sống yên ổn không.",
  "mn85:3.3": "Hãy nói rằng: ‘Bạch Ngài, Hoàng tử Bodhi cúi đầu đảnh lễ dưới chân Đức Thế Tôn, và hỏi thăm Ngài có ít bệnh, ít đau, đi đứng nhẹ nhàng, có sức, sống yên ổn không.’",
  "mn85:3.4": "Và hãy nói thêm:",
  "mn85:3.5": "‘Bạch Ngài, xin Đức Thế Tôn nhận lời dùng bữa ăn ngày mai tại nhà Hoàng tử Bodhi, cùng với chúng Tỳ Kheo.’”",
  "mn85:4.1": "“Vâng, thưa ngài,” chàng thanh niên Sañjikāputta đáp lời Hoàng tử Bodhi rồi đi đến chỗ Đức Thế Tôn; đến rồi, chàng chào hỏi thân tình với Đức Thế Tôn.",
  "mn85:4.2": "Sau khi nói chuyện thân tình, gợi nhớ, chàng ngồi xuống một bên. Ngồi xuống một bên rồi, chàng thanh niên Sañjikāputta thưa với Đức Thế Tôn:",
  "mn85:4.3": "“Hoàng tử Bodhi cúi đầu đảnh lễ dưới chân ngài Gotama, và hỏi thăm ngài có ít bệnh, ít đau, đi đứng nhẹ nhàng, có sức, sống yên ổn không.",
  "mn85:4.4": "Và còn nói rằng:",
  "mn85:4.5": "‘Xin ngài Gotama nhận lời dùng bữa ăn ngày mai tại nhà Hoàng tử Bodhi, cùng với chúng Tỳ Kheo.’”",
  "mn85:4.6": "Đức Thế Tôn im lặng nhận lời.",
  "mn85:4.7": "Rồi chàng thanh niên Sañjikāputta, biết Đức Thế Tôn đã nhận lời, liền đứng dậy khỏi chỗ ngồi, đi đến chỗ Hoàng tử Bodhi; đến rồi, chàng nói với Hoàng tử Bodhi:",
  "mn85:4.8": "“Tôi đã nói với ngài Gotama theo lời của ngài:",
  "mn85:4.9": "‘Hoàng tử Bodhi cúi đầu đảnh lễ dưới chân ngài Gotama, và hỏi thăm ngài có ít bệnh, ít đau, đi đứng nhẹ nhàng, có sức, sống yên ổn không.",
  "mn85:4.10": "Và còn nói rằng—",
  "mn85:4.11": "xin ngài Gotama nhận lời dùng bữa ăn ngày mai tại nhà Hoàng tử Bodhi, cùng với chúng Tỳ Kheo.’",
  "mn85:4.12": "Và sa môn Gotama đã nhận lời.”",
  "mn85:5.1": "Rồi khi đêm ấy qua đi, Hoàng tử Bodhi cho dọn sẵn tại nhà mình các món ăn ngon, thức ăn ngon, và cho trải những tấm vải trắng trong lầu Kokanada cho đến bậc thềm cuối cùng, rồi gọi chàng thanh niên Sañjikāputta:",
  "mn85:5.2": "“Này anh Sañjikāputta, hãy đi đến chỗ Đức Thế Tôn; đến rồi, báo giờ với Đức Thế Tôn rằng:",
  "mn85:5.3": "‘Bạch Ngài, đã đến giờ, bữa ăn đã dọn xong.’”",
  "mn85:5.4": "“Vâng, thưa ngài,” chàng thanh niên Sañjikāputta đáp lời Hoàng tử Bodhi rồi đi đến chỗ Đức Thế Tôn; đến rồi, chàng báo giờ với Đức Thế Tôn:",
  "mn85:5.5": "“Thưa ngài Gotama, đã đến giờ, bữa ăn đã dọn xong.”",
  "mn85:6.1": "Rồi Đức Thế Tôn vào buổi sáng, mặc y, cầm bát và y ngoài, đi đến nhà của Hoàng tử Bodhi.",
  "mn85:7.1": "Lúc ấy, Hoàng tử Bodhi đang đứng ở cổng ngoài, chờ Đức Thế Tôn đến.",
  "mn85:7.2": "Hoàng tử Bodhi thấy Đức Thế Tôn từ xa đang đi đến.",
  "mn85:7.3": "Thấy Đức Thế Tôn, vị ấy đi ra đón, cúi đầu chào Đức Thế Tôn, rồi đi trước dẫn đường đến lầu Kokanada.",
  "mn85:7.4": "Bấy giờ Đức Thế Tôn đứng dựa vào bậc thang cuối cùng.",
  "mn85:7.5": "Bấy giờ vương tử Bodhi thưa với Đức Thế Tôn:",
  "mn85:7.6": "“Xin Đức Thế Tôn bước lên các tấm vải, bạch ngài, xin bậc Thiện Thệ bước lên các tấm vải;",
  "mn85:7.7": "để việc ấy đem lại điều lành và sự yên vui lâu dài cho con.”",
  "mn85:7.8": "Được nói vậy, Đức Thế Tôn im lặng.",
  "mn85:7.9": "Lần thứ hai cũng vậy.",
  "mn85:7.10": "Đến lần thứ ba, vương tử Bodhi lại thưa với Đức Thế Tôn:",
  "mn85:7.11": "“Xin Đức Thế Tôn bước lên các tấm vải, bạch ngài, xin bậc Thiện Thệ bước lên các tấm vải;",
  "mn85:7.12": "để việc ấy đem lại điều lành và sự yên vui lâu dài cho con.”",
  "mn85:7.13": "Bấy giờ Đức Thế Tôn nhìn Tôn giả Ānanda.",
  "mn85:7.14": "Bấy giờ Tôn giả Ānanda nói với vương tử Bodhi:",
  "mn85:7.15": "“Xin vương tử cất các tấm vải đi;",
  "mn85:7.16": "Đức Thế Tôn sẽ không giẫm lên tấm trải bằng vải đâu.",
  "mn85:7.17": "Như Lai thương xót người đời sau.”",
  "mn85:8.1": "Bấy giờ vương tử Bodhi cho cất các tấm vải đi, rồi sắp đặt chỗ ngồi ở tầng trên của lầu Kokanada.",
  "mn85:8.2": "Bấy giờ Đức Thế Tôn bước lên lầu Kokanada và ngồi vào chỗ đã dọn sẵn cùng với chúng Tỳ Kheo.",
  "mn85:9.1": "Bấy giờ vương tử Bodhi tự tay dâng cúng và mời chúng Tỳ Kheo có Đức Phật đứng đầu dùng các món ăn ngon, cả món cứng lẫn món mềm, cho đến khi vừa đủ.",
  "mn85:9.2": "Bấy giờ vương tử Bodhi, khi Đức Thế Tôn đã dùng bữa xong, đã rời tay khỏi bát, liền lấy một chỗ ngồi thấp khác và ngồi xuống một bên.",
  "mn85:9.3": "Khi đã ngồi xuống một bên, vương tử Bodhi thưa với Đức Thế Tôn:",
  "mn85:9.4": "“Bạch ngài, con nghĩ như vầy:",
  "mn85:9.5": "‘Không thể nhờ sự dễ chịu mà đạt được sự dễ chịu; chỉ nhờ sự nhọc nhằn mới đạt được sự dễ chịu.’”",
  "mn85:10.1": "“Này vương tử, trước khi tự mình hiểu ra trọn vẹn, khi ta còn là người đang đi tìm sự tỉnh sáng trọn vẹn, ta cũng đã nghĩ như vầy:",
  "mn85:10.2": "‘Không thể nhờ sự dễ chịu mà đạt được sự dễ chịu; chỉ nhờ sự nhọc nhằn mới đạt được sự dễ chịu.’",
  "mn85:11.1": "Này vương tử, rồi một thời sau, khi ta còn trẻ, tóc đen nhánh, đang ở tuổi xuân đẹp đẽ, trong thời đầu của đời người, dù cha mẹ không muốn, mặt đầy nước mắt, đang khóc, ta đã cạo bỏ tóc và râu, khoác y màu nâu sẫm, rời nhà sống đời không nhà.",
  "mn85:11.2": "Sau khi ra đi như vậy, trong khi tìm điều lành, tìm kiếm trạng thái yên lặng tốt đẹp không gì hơn, ta đi đến gặp Āḷāra Kālāma. Đến nơi, ta nói với Āḷāra Kālāma rằng:",
  "mn85:11.3": "‘Này hiền giả Kālāma, tôi muốn sống đời trong sạch theo nếp sống này và đường lối này.’",
  "mn85:11.4": "Này vương tử, khi được nói vậy, Āḷāra Kālāma nói với ta:",
  "mn85:11.5": "‘Xin Tôn giả cứ ở lại.",
  "mn85:11.6": "Nếp sống này là như vậy: người sáng dạ chẳng bao lâu sẽ tự mình biết rõ, tự mình thấy ra, đạt đến phần việc của bậc thầy mình và sống an trú trong đó.’",
  "mn85:11.7": "Này hoàng tử, chẳng bao lâu sau, rất nhanh, ta đã học thuộc lời dạy ấy.",
  "mn85:11.8": "Này hoàng tử, rồi chỉ với mức dùng môi lưỡi mà nói lại, chỉ với mức nói năng bàn luận, ta cũng nói lời hiểu biết, biết lời của bậc già, và nhận rằng: ‘Tôi biết, tôi thấy’, cùng với những người khác.",
  "mn85:11.9": "Này hoàng tử, rồi ta nghĩ như vầy:",
  "mn85:11.10": "‘Không phải thầy Āḷāra Kālāma chỉ do lòng tin mà nói rằng mình tự biết rõ, tự mình thấy ra, đạt tới và an trú trong cách tu này.",
  "mn85:11.11": "Chắc hẳn thầy Āḷāra Kālāma sống khi đã biết và đã thấy cách tu này.’",
  "mn85:12.1": "Này hoàng tử, rồi ta đi đến gặp Āḷāra Kālāma. Đến rồi, ta nói với Āḷāra Kālāma như vầy:",
  "mn85:12.2": "‘Này hiền giả Kālāma, thầy nói rằng mình tự biết rõ, tự mình thấy ra, đạt tới và an trú trong cách tu này đến mức nào?’",
  "mn85:12.3": "Khi được hỏi như vậy, này hoàng tử, Āḷāra Kālāma nói về cảnh không có gì cả.",
  "mn85:12.4": "Này hoàng tử, rồi ta nghĩ như vầy:",
  "mn85:12.5": "‘Không phải chỉ riêng Āḷāra Kālāma mới có lòng tin, ta cũng có lòng tin.",
  "mn85:12.6": "Không phải chỉ riêng Āḷāra Kālāma mới có sức gắng bền...",
  "mn85:12.7": "sự nhớ biết rõ...",
  "mn85:12.8": "tâm yên vững...",
  "mn85:12.9": "sự hiểu rõ, ta cũng có sự hiểu rõ.",
  "mn85:12.10": "Hay là ta hãy ra sức để tự mình thấy ra điều mà Āḷāra Kālāma nói là mình đã tự biết rõ, tự mình thấy ra, đạt tới và an trú trong cách tu ấy.’",
  "mn85:12.11": "Này hoàng tử, rồi chẳng bao lâu sau, rất nhanh, ta đã tự biết rõ, tự mình thấy ra, đạt tới và an trú trong cách tu ấy.",
  "mn85:12.12": "Này hoàng tử, rồi ta đi đến gặp Āḷāra Kālāma. Đến rồi, ta nói với Āḷāra Kālāma như vầy:",
  "mn85:12.13": "‘Này hiền giả Kālāma, thầy nói rằng mình tự biết rõ, tự mình thấy ra, đạt tới điều này đến mức nào?’",
  "mn85:12.14": "‘Này hiền giả, tôi nói rằng mình tự biết rõ, tự mình thấy ra, đạt tới điều này đến mức ấy.’",
  "mn85:12.15": "‘Này hiền giả, tôi cũng tự biết rõ, tự mình thấy ra, và an trú trong điều này đến mức ấy.’",
  "mn85:12.16": "‘Thật là điều tốt cho chúng ta, này hiền giả, thật khéo được cho chúng ta, này hiền giả,",
  "mn85:12.17": "vì chúng ta được gặp một người cùng sống đời trong sạch như ngài.’",
  "mn85:12.18": "‘Điều mà tôi tự biết rõ, tự mình thấy ra, đạt tới và nói ra, thì ngài cũng tự biết rõ, tự mình thấy ra, đạt tới và an trú trong điều ấy.",
  "mn85:12.19": "Điều mà ngài tự biết rõ, tự mình thấy ra, đạt tới và an trú trong điều ấy, thì tôi cũng tự biết rõ, tự mình thấy ra, đạt tới và nói ra điều ấy.",
  "mn85:12.20": "Như vậy, điều tôi biết thì ngài biết; điều ngài biết thì tôi biết.",
  "mn85:12.21": "Như tôi thế nào thì ngài thế ấy; như ngài thế nào thì tôi thế ấy.",
  "mn85:12.22": "Vậy này hiền giả, hãy đến, cả hai ta cùng chăm nom nhóm này.’",
  "mn85:12.23": "Này hoàng tử, như vậy đó, Āḷāra Kālāma là thầy của ta, nhưng đã đặt ta, là học trò của mình, ngang bằng với chính mình, và còn tôn trọng ta bằng sự quý trọng lớn lao.",
  "mn85:12.24": "Này hoàng tử, rồi ta nghĩ như vầy:",
  "mn85:12.25": "‘Cách tu này không đưa đến chán lìa, không đưa đến phai nhạt ham muốn, không đưa đến dứt hẳn, không đưa đến lắng yên, không đưa đến tự biết rõ, không đưa đến tỉnh sáng trọn vẹn, không đưa đến tắt hẳn; nó chỉ đưa đến chỗ sinh vào cảnh không có gì cả mà thôi.’",
  "mn85:12.26": "Này hoàng tử, ta đã không thấy điều ấy đáng để gắn bó, nên chán nó rồi bỏ đi.",
  "mn85:12.27": "Này hoàng tử, khi tìm điều lành, tìm chỗ yên ổn tốt đẹp hơn hết, ta đi đến chỗ Udaka Rāmaputta. Đến nơi, ta nói với Udaka Rāmaputta:",
  "mn85:12.28": "‘Này bạn, tôi muốn sống đời sống trong sạch trong nếp sống và đường lối này.’",
  "mn85:12.29": "Khi ta nói vậy, này hoàng tử, Udaka Rāmaputta nói với ta:",
  "mn85:12.30": "‘Xin tôn giả cứ ở lại,",
  "mn85:12.31": "vì nếp sống này là như vậy: người sáng dạ chẳng bao lâu sẽ tự mình biết rõ điều thầy mình đã biết rõ, rồi sống an trú trong đó.’",
  "mn85:12.32": "Này hoàng tử, chẳng bao lâu, rất nhanh, ta đã học thuộc nếp sống ấy.",
  "mn85:12.33": "Này hoàng tử, chỉ với mức ấy thôi, chỉ bằng lời nói ngoài môi miệng, bằng chuyện bàn nói suông, ta đã nói lời hiểu biết, biết lời của bậc già, và nhận rằng: ‘Tôi biết, tôi thấy’, cũng như những người khác.",
  "mn85:12.34": "Này hoàng tử, rồi ta nghĩ như vầy:",
  "mn85:12.35": "‘Không phải chỉ do lòng tin suông mà Rāma nói rằng mình tự biết rõ, tự mình thấy rõ, rồi sống an trú trong nếp sống này.",
  "mn85:12.36": "Chắc hẳn Rāma đã sống khi thật sự biết và thấy điều này.’",
  "mn85:13.1": "Rồi, này hoàng tử, ta đi đến chỗ Udaka Rāmaputta. Đến nơi, ta nói với Udaka Rāmaputta:",
  "mn85:13.2": "‘Này bạn, Rāma đã nói mình tự biết rõ, tự mình thấy rõ, rồi sống an trú trong nếp sống này đến mức nào?’",
  "mn85:13.3": "Khi ta nói vậy, này hoàng tử, Udaka Rāmaputta nói đến cảnh giới không còn rõ là có nhận ra hay không nhận ra.",
  "mn85:13.4": "Này hoàng tử, rồi ta nghĩ như vầy:",
  "mn85:13.5": "‘Không phải chỉ riêng Rāma mới có lòng tin, ta cũng có lòng tin.",
  "mn85:13.6": "Không phải chỉ riêng Rāma mới có sức gắng bền, ta cũng có sức gắng bền.",
  "mn85:13.7": "Không phải chỉ riêng Rāma mới có nhớ biết rõ, ta cũng có nhớ biết rõ.",
  "mn85:13.8": "Không phải chỉ riêng Rāma mới có tâm yên vững, ta cũng có tâm yên vững.",
  "mn85:13.9": "Không phải chỉ riêng Rāma mới có sự hiểu rõ, ta cũng có sự hiểu rõ.",
  "mn85:13.10": "Vậy thì, sao ta không dốc sức để tự mình thấy rõ điều mà Rāma nói là mình đã tự biết rõ, tự mình thấy rõ, rồi sống an trú trong đó?’",
  "mn85:13.11": "Này hoàng tử, chẳng bao lâu, rất nhanh, ta đã tự mình biết rõ, tự mình thấy rõ điều ấy, rồi sống an trú trong đó.",
  "mn85:13.12": "Rồi, này hoàng tử, ta đi đến chỗ Udaka Rāmaputta. Đến nơi, ta nói với Udaka Rāmaputta:",
  "mn85:13.13": "‘Này bạn, có phải Rāma đã nói mình tự biết rõ, tự mình thấy rõ, rồi sống an trú trong nếp sống này đến mức ấy không?’",
  "mn85:13.14": "‘Đúng vậy, này bạn, Rāma đã nói mình tự biết rõ, tự mình thấy rõ, rồi sống an trú trong nếp sống này đến mức ấy.’",
  "mn85:13.15": "‘Này bạn, tôi cũng đã tự mình biết rõ, tự mình thấy rõ, rồi sống an trú trong nếp sống này đến mức ấy.’",
  "mn85:13.16": "‘Thật là điều may cho chúng tôi, này bạn, thật khéo được cho chúng tôi, này bạn,",
  "mn85:13.17": "khi chúng tôi được gặp một bạn đồng tu như tôn giả.",
  "mn85:13.18": "Như vậy, điều mà Rāma tự mình biết rõ, tự mình thấy rõ, rồi sống an trú trong đó, thì nay ông cũng tự mình biết rõ, tự mình thấy rõ, rồi sống an trú trong đó.",
  "mn85:13.19": "Và điều mà ông tự mình biết rõ, tự mình thấy rõ, rồi sống an trú trong đó, thì chính là điều mà Rāma đã tự mình biết rõ, tự mình thấy rõ, rồi sống an trú trong đó.’",
  "mn85:13.20": "Như vậy, điều thầy Rāma tự mình biết rõ, thì ông cũng biết rõ điều ấy; điều ông biết rõ, thì thầy Rāma cũng biết rõ điều ấy.",
  "mn85:13.21": "Như vậy, thầy Rāma thế nào thì ông cũng thế ấy; ông thế nào thì thầy Rāma cũng thế ấy.",
  "mn85:13.22": "Nào, này hiền giả, từ nay ông hãy chăm nom nhóm này.",
  "mn85:13.23": "Này hoàng tử, như vậy đó, Udaka, con của Rāma, là bạn sống chung một nếp sống tu với ta, đã đặt ta vào chỗ thầy dạy, và còn tôn kính ta với sự kính trọng lớn lao.",
  "mn85:13.24": "Này hoàng tử, rồi ta nghĩ như vầy:",
  "mn85:13.25": "Phép này không đưa đến chán lìa, không đưa đến nhạt bớt ham muốn, không đưa đến dứt hẳn, không đưa đến lắng yên, không đưa đến tự mình biết rõ, không đưa đến tỉnh thức trọn vẹn, không đưa đến tắt hẳn, mà chỉ đưa đến cõi không phải còn tưởng mà cũng không phải không còn tưởng.",
  "mn85:13.26": "Này hoàng tử, rồi ta không xem trọng phép ấy, chán ngán phép ấy và bỏ đi.",
  "mn85:14.1": "Này hoàng tử, rồi ta, trong khi tìm điều lành, tìm chỗ yên ổn tốt đẹp hơn hết, đi dần qua xứ Magadha, lang thang từng chặng, đã đến làng Senānigama ở Uruvelā.",
  "mn85:14.2": "Ở đó, ta thấy một vùng đất thật đẹp, một bụi rừng thật vừa mắt, một con sông nước trong đang chảy, có bến xuống nước tốt, và quanh đó có làng mạc thuận tiện để đi khất thực.",
  "mn85:14.3": "Này hoàng tử, rồi ta nghĩ như vầy:",
  "mn85:14.4": "Vùng đất này thật đẹp, bụi rừng này thật vừa mắt, con sông nước trong đang chảy, có bến xuống nước tốt, và quanh đó có làng mạc thuận tiện để đi khất thực.",
  "mn85:14.5": "Nơi này thật đủ cho người con nhà lành muốn gắng sức.",
  "mn85:14.6": "Này hoàng tử, rồi ta ngồi xuống ngay tại đó:",
  "mn85:14.7": "Nơi này đủ để gắng sức.",
  "mn85:15.1": "Này hoàng tử, rồi có ba ví dụ hiện ra trong ta, chưa từng lạ lùng như vậy, trước đây ta chưa từng nghe.",
  "mn85:16.1": "Ví như, này hoàng tử, một khúc gỗ còn ướt, còn nhựa, bị quăng xuống nước.",
  "mn85:16.2": "Rồi có người cầm thanh gỗ làm lửa trên mà đến và nghĩ:",
  "mn85:16.3": "Ta sẽ làm cho lửa bật ra, ta sẽ làm cho sức nóng hiện ra.",
  "mn85:16.4": "Này hoàng tử, ông nghĩ sao,",
  "mn85:16.5": "người ấy có thể lấy thanh gỗ làm lửa trên cọ xát vào khúc gỗ ướt còn nhựa bị quăng xuống nước ấy mà làm cho lửa bật ra, làm cho sức nóng hiện ra được không?",
  "mn85:16.6": "Thưa không, bạch Đức Thế Tôn.",
  "mn85:16.7": "Vì sao vậy?",
  "mn85:16.8": "Vì, bạch Đức Thế Tôn, đó là khúc gỗ còn ướt, còn nhựa, lại còn bị quăng xuống nước,",
  "mn85:16.9": "nên người ấy chỉ chuốc lấy mệt nhọc và bực bội mà thôi.",
  "mn85:17.1": "Cũng vậy, này hoàng tử, bất cứ những người sống đời tu hay những người học rộng nào còn sống chưa lìa các thú vui giác quan, cả nơi thân lẫn nơi tâm, và trong họ sự ham muốn thú vui giác quan, sự dính mắc vào thú vui giác quan, sự say đắm thú vui giác quan, sự khát khao thú vui giác quan, sự nung nấu vì thú vui giác quan vẫn chưa được bỏ sạch bên trong, chưa được lắng hẳn,",
  "mn85:17.2": "thì dù những người ấy có cảm nhận những cảm giác đau đớn dữ dội, gay gắt, nhói buốt do cố sức mà ra, họ vẫn không thể đạt đến sự biết rõ, sự thấy rõ, sự tỉnh thức trọn vẹn hơn hết.",
  "mn85:17.3": "Mà dù những người ấy không cảm nhận những cảm giác đau đớn dữ dội, gay gắt, nhói buốt do cố sức mà ra, họ vẫn không thể đạt đến sự biết rõ, sự thấy rõ, sự tỉnh thức trọn vẹn hơn hết.",
  "mn85:17.4": "Này hoàng tử, đó là ví dụ thứ nhất hiện ra trong ta, lạ lùng, trước đây chưa từng nghe.",
  "mn85:18.1": "Này hoàng tử, rồi ví dụ thứ hai cũng hiện ra trong ta, lạ lùng, trước đây chưa từng nghe.",
  "mn85:18.2": "Ví như, này hoàng tử, một khúc gỗ còn ướt, còn nhựa, được để trên đất khô, xa nước.",
  "mn85:18.3": "Rồi có một người đến, cầm thanh gỗ trên, nghĩ rằng:",
  "mn85:18.4": "‘Ta sẽ làm ra lửa, sẽ làm cho sức nóng hiện ra.’",
  "mn85:18.5": "Này hoàng tử, con nghĩ sao,",
  "mn85:18.6": "người ấy lấy thanh gỗ trên, cọ xát vào khúc gỗ ướt còn nhựa, dù đã để trên đất xa nước, thì có làm ra lửa, có làm cho sức nóng hiện ra được không?”",
  "mn85:18.7": "“Thưa không, bạch Thế Tôn.",
  "mn85:18.8": "Vì sao vậy?",
  "mn85:18.9": "Vì, bạch Thế Tôn, khúc gỗ ấy còn ướt, còn nhựa, dù đã để trên đất xa nước,",
  "mn85:18.10": "người ấy chỉ chuốc lấy mệt nhọc và bực bội mà thôi.”",
  "mn85:18.11": "“Cũng vậy, này hoàng tử, bất cứ người tu hay thầy cúng nào sống tách xa các dục bằng thân và cả tâm, nhưng sự ham muốn dục, sự dính mắc dục, sự say đắm dục, sự khát khao dục, sự nung nấu vì dục ở trong họ vẫn chưa dứt sạch, chưa lắng hẳn.",
  "mn85:18.12": "Dù những vị người tu hay thầy cúng ấy có cảm nhận những cảm giác đau đớn dữ dội, gắt gao, nhói buốt do cố sức mà ra, họ vẫn không thể đạt tới sự biết rõ, sự thấy rõ, sự tỉnh ngộ không gì hơn.",
  "mn85:18.13": "Dù những vị người tu hay thầy cúng ấy không cảm nhận những cảm giác đau đớn dữ dội, gắt gao, nhói buốt do cố sức mà ra, họ vẫn không thể đạt tới sự biết rõ, sự thấy rõ, sự tỉnh ngộ không gì hơn.",
  "mn85:18.14": "Này hoàng tử, đó là ví dụ thứ hai hiện ra với Ta, lạ lùng, trước đây chưa từng nghe.”",
  "mn85:19.1": "Này hoàng tử, rồi một ví dụ thứ ba nữa hiện ra với Ta, lạ lùng, trước đây chưa từng nghe.",
  "mn85:19.2": "Ví như, này hoàng tử, có một khúc gỗ khô, không còn nhựa, được để trên đất xa nước.",
  "mn85:19.3": "Rồi có một người đến, cầm thanh gỗ trên, nghĩ rằng:",
  "mn85:19.4": "‘Ta sẽ làm ra lửa, sẽ làm cho sức nóng hiện ra.’",
  "mn85:19.5": "Này hoàng tử, con nghĩ sao,",
  "mn85:19.6": "người ấy lấy thanh gỗ trên, cọ xát vào khúc gỗ khô không còn nhựa ấy, đã để trên đất xa nước, thì có làm ra lửa, có làm cho sức nóng hiện ra được không?”",
  "mn85:19.7": "“Thưa được, bạch Thế Tôn.",
  "mn85:19.8": "Vì sao vậy?",
  "mn85:19.9": "Vì, bạch Thế Tôn, khúc gỗ ấy khô, không còn nhựa, lại được để trên đất xa nước.”",
  "mn85:19.10": "“Cũng vậy, này hoàng tử, bất cứ người tu hay thầy cúng nào sống tách xa các dục bằng thân và cả tâm, và sự ham muốn dục, sự dính mắc dục, sự say đắm dục, sự khát khao dục, sự nung nấu vì dục ở trong họ đã dứt sạch, đã lắng hẳn.",
  "mn85:19.11": "Dù những vị người tu hay thầy cúng ấy có cảm nhận những cảm giác đau đớn dữ dội, gắt gao, nhói buốt do cố sức mà ra, họ vẫn có thể đạt tới sự biết rõ, sự thấy rõ, sự tỉnh ngộ không gì hơn.",
  "mn85:19.12": "Dù những vị người tu hay thầy cúng ấy không cảm nhận những cảm giác đau đớn dữ dội, gắt gao, nhói buốt do cố sức mà ra, họ vẫn có thể đạt tới sự biết rõ, sự thấy rõ, sự tỉnh ngộ không gì hơn.",
  "mn85:19.13": "Này hoàng tử, đó là ví dụ thứ ba hiện ra với Ta, lạ lùng, trước đây chưa từng nghe.",
  "mn85:19.14": "Này hoàng tử, đó là ba ví dụ hiện ra với Ta, lạ lùng, trước đây chưa từng nghe.",
  "mn85:20.1": "Khi ấy, này hoàng tử, Ta nghĩ rằng:",
  "mn85:20.2": "‘Hay là ta nghiến răng, ép lưỡi lên nóc họng, rồi dùng tâm ghì chặt tâm, đè nén tâm, nung ép tâm.’",
  "mn85:20.3": "Rồi, này hoàng tử, Ta nghiến răng, ép lưỡi lên nóc họng, dùng tâm ghì chặt tâm, đè nén tâm, nung ép tâm.",
  "mn85:20.4": "Khi Ta nghiến răng, ép lưỡi lên nóc họng, dùng tâm ghì chặt tâm, đè nén tâm, nung ép tâm như vậy, mồ hôi chảy ra từ dưới nách.",
  "mn85:20.5": "Ví như, này hoàng tử, một người khỏe nắm đầu hay nắm vai một người yếu hơn rồi ghì chặt, ép mạnh, làm cho nóng bức khổ sở;",
  "mn85:20.6": "cũng vậy, này hoàng tử, khi Ta nghiến răng, ép lưỡi lên nóc miệng, rồi dùng tâm ghì giữ tâm, ép chặt tâm, nung bức tâm, thì mồ hôi chảy ra từ nách.",
  "mn85:20.7": "Nhưng này hoàng tử, sức gắng của Ta được khơi dậy, không chùng xuống; sự nhớ biết rõ được giữ vững, không lẫn mất; thân Ta thì căng cứng, không lắng dịu, vì Ta đang dốc sức theo đuổi sự gắng sức đầy đau đớn ấy.",
  "mn85:21.1": "Rồi này hoàng tử, Ta nghĩ rằng:",
  "mn85:21.2": "‘Hay là Ta thử ngồi yên không thở.’",
  "mn85:21.3": "Rồi này hoàng tử, Ta chặn hơi thở ra vào nơi miệng và mũi.",
  "mn85:21.4": "Khi ấy, này hoàng tử, do hơi thở ra vào nơi miệng và mũi bị chặn lại, có tiếng gió thoát ra từ lỗ tai rất lớn.",
  "mn85:21.5": "Ví như tiếng ống bễ của người thợ rèn đang thổi phát ra âm thanh rất lớn;",
  "mn85:21.6": "cũng vậy, này hoàng tử, khi hơi thở ra vào nơi miệng và mũi bị chặn lại, có tiếng gió thoát ra từ lỗ tai rất lớn.",
  "mn85:21.7": "Nhưng này hoàng tử, sức gắng của Ta được khơi dậy, không chùng xuống; sự nhớ biết rõ được giữ vững, không lẫn mất; thân Ta thì căng cứng, không lắng dịu, vì Ta đang dốc sức theo đuổi sự gắng sức đầy đau đớn ấy.",
  "mn85:22.1": "Rồi này hoàng tử, Ta nghĩ rằng:",
  "mn85:22.2": "‘Hay là Ta thử ngồi yên không thở.’",
  "mn85:22.3": "Rồi này hoàng tử, Ta chặn hơi thở ra vào nơi miệng, mũi và tai.",
  "mn85:22.4": "Khi ấy, này hoàng tử, do hơi thở ra vào nơi miệng, mũi và tai bị chặn lại, những luồng gió mạnh dội lên đỉnh đầu.",
  "mn85:22.5": "Ví như, này hoàng tử, một người khỏe lấy mũi nhọn sắc đâm mạnh vào đỉnh đầu;",
  "mn85:22.6": "cũng vậy, này hoàng tử, khi hơi thở ra vào nơi miệng, mũi và tai bị chặn lại, những luồng gió mạnh dội lên đỉnh đầu.",
  "mn85:22.7": "Nhưng này hoàng tử, sức gắng của Ta được khơi dậy, không chùng xuống; sự nhớ biết rõ được giữ vững, không lẫn mất; thân Ta thì căng cứng, không lắng dịu, vì Ta đang dốc sức theo đuổi sự gắng sức đầy đau đớn ấy.",
  "mn85:23.1": "Rồi này hoàng tử, Ta nghĩ rằng:",
  "mn85:23.2": "‘Hay là Ta thử ngồi yên không thở.’",
  "mn85:23.3": "Rồi này hoàng tử, Ta chặn hơi thở ra vào nơi miệng, mũi và tai.",
  "mn85:23.4": "Khi ấy, này hoàng tử, do hơi thở ra vào nơi miệng, mũi và tai bị chặn lại, những cơn đau dữ dội nổi lên ở đầu.",
  "mn85:23.5": "Ví như, này hoàng tử, một người khỏe lấy dây da chắc quấn siết đầu thật chặt;",
  "mn85:23.6": "cũng vậy, này hoàng tử, khi hơi thở ra vào nơi miệng, mũi và tai bị chặn lại, những cơn đau dữ dội nổi lên ở đầu.",
  "mn85:23.7": "Nhưng này hoàng tử, sức gắng của Ta được khơi dậy, không chùng xuống; sự nhớ biết rõ được giữ vững, không lẫn mất; thân Ta thì căng cứng, không lắng dịu, vì Ta đang dốc sức theo đuổi sự gắng sức đầy đau đớn ấy.",
  "mn85:24.1": "Rồi này hoàng tử, Ta nghĩ rằng:",
  "mn85:24.2": "‘Hay là Ta thử ngồi yên không thở.’",
  "mn85:24.3": "Rồi này hoàng tử, Ta chặn hơi thở ra vào nơi miệng, mũi và tai.",
  "mn85:24.4": "Khi ấy, này hoàng tử, do hơi thở ra vào nơi miệng, mũi và tai bị chặn lại, những luồng gió mạnh cắt xé bụng Ta.",
  "mn85:24.5": "Ví như một người mổ bò khéo tay, hay học trò của người mổ bò, lấy dao bén rạch bụng;",
  "mn85:24.6": "cũng vậy, này hoàng tử, khi hơi thở ra vào nơi miệng, mũi và tai bị chặn lại, những luồng gió mạnh cắt xé bụng Ta.",
  "mn85:24.7": "Nhưng này hoàng tử, sức gắng của ta vẫn được khơi dậy, không chùng xuống; sự nhớ biết rõ vẫn có mặt, không lẫn mất; thân ta thì căng cứng, không lắng dịu, vì ta đang dốc sức chịu đựng sự khổ đau ấy.",
  "mn85:25.1": "Rồi này hoàng tử, ta nghĩ như vầy:",
  "mn85:25.2": "‘Hay là ta chỉ ngồi yên, không thở nữa.’",
  "mn85:25.3": "Rồi này hoàng tử, ta chặn hơi thở ra vào nơi miệng, nơi mũi, và nơi tai.",
  "mn85:25.4": "Khi hơi thở ra vào nơi miệng, nơi mũi, và nơi tai bị chặn lại như vậy, thì trong thân ta có sức nóng dữ dội.",
  "mn85:25.5": "Ví như này hoàng tử, hai người khỏe nắm lấy tay chân một người yếu hơn rồi hơ nóng, nung nóng người ấy trên hố than đỏ;",
  "mn85:25.6": "cũng vậy, này hoàng tử, khi hơi thở ra vào nơi miệng, nơi mũi, và nơi tai bị chặn lại, thì trong thân ta có sức nóng dữ dội.",
  "mn85:25.7": "Nhưng này hoàng tử, sức gắng của ta vẫn được khơi dậy, không chùng xuống; sự nhớ biết rõ vẫn có mặt, không lẫn mất; thân ta thì căng cứng, không lắng dịu, vì ta đang dốc sức chịu đựng sự khổ đau ấy.",
  "mn85:26.1": "Lại nữa, này hoàng tử, có các vị trời thấy ta rồi nói như vầy:",
  "mn85:26.2": "‘Sa môn Gotama đã chết rồi.’",
  "mn85:26.3": "Một số vị trời nói như vầy:",
  "mn85:26.4": "‘Sa môn Gotama chưa chết, nhưng đang hấp hối.’",
  "mn85:26.5": "Một số vị trời khác nói như vầy:",
  "mn85:26.6": "‘Sa môn Gotama chưa chết, cũng không phải đang hấp hối. Sa môn Gotama là bậc đáng kính. Cách sống của một bậc đáng kính là như vậy.’",
  "mn85:27.1": "Rồi này hoàng tử, ta nghĩ như vầy:",
  "mn85:27.2": "‘Hay là ta đi đến chỗ dứt hẳn mọi thức ăn.’",
  "mn85:27.3": "Khi ấy, này hoàng tử, các vị trời đến gần ta và nói như vầy:",
  "mn85:27.4": "‘Này ngài, xin đừng đi đến chỗ dứt hẳn mọi thức ăn.",
  "mn85:27.5": "Nếu ngài đi đến chỗ dứt hẳn mọi thức ăn, thì chúng tôi sẽ đưa chất nuôi sống cõi trời vào qua lỗ chân lông cho ngài; nhờ đó ngài sẽ sống được.’",
  "mn85:27.6": "Rồi này hoàng tử, ta nghĩ như vầy:",
  "mn85:27.7": "‘Nếu ta nói là mình dứt hẳn không ăn gì, mà các vị trời này lại đưa chất nuôi sống cõi trời vào qua lỗ chân lông cho ta, rồi ta nhờ đó mà sống, thì như vậy nơi ta sẽ thành lời nói dối.’",
  "mn85:27.8": "Rồi này hoàng tử, ta từ chối các vị trời ấy. Ta nói: ‘Thôi đủ rồi.’",
  "mn85:28.1": "Rồi này hoàng tử, ta nghĩ như vầy:",
  "mn85:28.2": "‘Hay là ta ăn từng chút một, từng nắm nhỏ, hoặc nước đậu xanh, hoặc nước đậu ngựa, hoặc nước đậu Hà Lan, hoặc nước đậu nhỏ.’",
  "mn85:28.3": "Rồi này hoàng tử, ta ăn từng chút một, từng nắm nhỏ, hoặc nước đậu xanh, hoặc nước đậu ngựa, hoặc nước đậu Hà Lan, hoặc nước đậu nhỏ.",
  "mn85:28.4": "Khi ta ăn từng chút một, từng nắm nhỏ như vậy, hoặc nước đậu xanh, hoặc nước đậu ngựa, hoặc nước đậu Hà Lan, hoặc nước đậu nhỏ, thì thân ta gầy mòn đến mức cùng cực.",
  "mn85:28.5": "Ví như những đốt dây leo đen hay những đốt cây khô; cũng vậy, tay chân ta trở nên như thế vì ăn quá ít.",
  "mn85:28.6": "Ví như dấu chân lạc đà; cũng vậy, chỗ ngồi của ta trở nên như thế vì ăn quá ít.",
  "mn85:28.7": "Ví như một chuỗi hạt tròn; cũng vậy, xương sống của ta lồi lên lõm xuống vì ăn quá ít.",
  "mn85:28.8": "Ví như những xà ngang trong một mái nhà cũ bị võng xuống, xiêu vẹo; cũng vậy, các xương sườn của ta bị võng xuống, xiêu vẹo vì ăn quá ít.",
  "mn85:28.9": "Ví như trong một giếng nước sâu, bóng nước nằm sâu bên dưới, thấp hẳn xuống, có thể thấy được; cũng vậy, con ngươi trong hốc mắt ta nằm sâu vào bên trong, tụt hẳn xuống, có thể thấy được, vì ta ăn quá ít như thế.",
  "mn85:28.10": "Ví như trái bầu đắng bị cắt khi còn non, bị gió nắng làm cho nhăn nheo, teo quắt; cũng vậy, da đầu ta bị nhăn nheo, teo quắt, vì ta ăn quá ít như thế.",
  "mn85:28.11": "Này vương tử, khi ta nghĩ: ‘Ta sẽ sờ da bụng’, thì ta nắm ngay xương sống; khi ta nghĩ: ‘Ta sẽ sờ xương sống’, thì ta nắm ngay da bụng. Này vương tử, da bụng ta dính sát vào xương sống, vì ta ăn quá ít như thế.",
  "mn85:28.12": "Này vương tử, khi ta nghĩ: ‘Ta sẽ đi đại tiện hay tiểu tiện’, thì ta ngã úp xuống ngay tại chỗ, vì ta ăn quá ít như thế.",
  "mn85:28.13": "Này vương tử, khi ta xoa bóp tay chân bằng bàn tay để làm dịu thân này, thì lông trên thân ta, gốc đã mục, rụng xuống khỏi thân, vì ta ăn quá ít như thế.",
  "mn85:29.1": "Này vương tử, có người thấy ta rồi nói: ‘Sa-môn Gotama đen quá’,",
  "mn85:29.2": "một số người khác nói: ‘Sa-môn Gotama không đen, Sa-môn Gotama sạm màu’,",
  "mn85:29.3": "một số người khác nữa nói: ‘Sa-môn Gotama không đen, cũng không sạm, da Sa-môn Gotama màu cá mang’.",
  "mn85:29.4": "Này vương tử, nước da vốn rất trong sáng, sạch đẹp của ta đã hư hao đến mức ấy, vì ta ăn quá ít như thế.",
  "mn85:30.1": "Này vương tử, rồi ta nghĩ:",
  "mn85:30.2": "‘Bất cứ sa-môn hay bà-la-môn nào trong thời đã qua đã chịu những cảm giác đau đớn dữ dội, gay gắt, khốc liệt do tự ép xác gây ra, thì cũng chỉ đến mức này, không hơn được nữa.",
  "mn85:30.3": "Bất cứ sa-môn hay bà-la-môn nào trong thời sắp tới sẽ chịu những cảm giác đau đớn dữ dội, gay gắt, khốc liệt do tự ép xác gây ra, thì cũng chỉ đến mức này, không hơn được nữa.",
  "mn85:30.4": "Bất cứ sa-môn hay bà-la-môn nào trong lúc này đang chịu những cảm giác đau đớn dữ dội, gay gắt, khốc liệt do tự ép xác gây ra, thì cũng chỉ đến mức này, không hơn được nữa.",
  "mn85:30.5": "Nhưng ta không đạt được điều gì vượt hơn mức người thường, không đạt được chỗ thấy biết riêng của bậc cao quý, nhờ lối hành xác cay nghiệt, khó làm này.",
  "mn85:30.6": "Hay là có một con đường khác để tỉnh sáng chăng?’",
  "mn85:31.1": "Này vương tử, rồi ta nghĩ:",
  "mn85:31.2": "‘Ta nhớ rõ, khi cha ta là người dòng Thích đang làm việc, ta ngồi dưới bóng mát cây diêm-phù lúc trời mát, tách khỏi các thú vui giác quan, tách khỏi những điều xấu ác, đi vào tầng lắng tâm thứ nhất, có hướng tâm, có xem xét, có niềm vui và sự dễ chịu do lìa ra mà sinh, và an trú như vậy.",
  "mn85:31.3": "Có phải đó là con đường đưa đến tỉnh sáng chăng?’",
  "mn85:31.4": "Này vương tử, rồi sự nhận biết đi theo ký ức ấy khởi lên nơi ta:",
  "mn85:31.5": "‘Đó chính là con đường đưa đến tỉnh sáng.’",
  "mn85:32.1": "Này vương tử, rồi ta nghĩ:",
  "mn85:32.2": "‘Vì sao ta lại sợ niềm vui ấy, thứ niềm vui không dính đến thú vui giác quan, không dính đến những điều xấu ác?’",
  "mn85:32.3": "Này vương tử, rồi ta nghĩ:",
  "mn85:32.4": "‘Ta không sợ niềm vui ấy, thứ niềm vui không dính đến thú vui giác quan, không dính đến những điều xấu ác.’",
  "mn85:33.1": "Này vương tử, rồi ta nghĩ:",
  "mn85:33.2": "‘Với thân thể đã gầy mòn đến mức cùng cực như thế này, không dễ gì đạt được niềm vui ấy. Hay là ta nên ăn thức ăn thô, như cơm và cháo đặc.’",
  "mn85:33.3": "Này vương tử, rồi ta ăn thức ăn thô, như cơm và cháo đặc.",
  "mn85:33.4": "Lúc ấy, này vương tử, có năm vị Tỳ Kheo ở gần bên ta:",
  "mn85:33.5": "‘Sa-môn Gotama đạt được điều gì, sẽ nói lại cho chúng ta biết.’",
  "mn85:33.6": "Nhưng khi ta ăn thức ăn thô, như cơm và cháo đặc, thì năm vị Tỳ Kheo ấy chán nản rồi bỏ đi.",
  "mn85:33.7": "‘Sa môn Gotama sống quá dễ dãi, đã rời bỏ sự gắng sức, quay lại nếp sống dễ dãi.’",
  "mn85:34-37.1": "Này hoàng tử, rồi ta ăn thức ăn thô chắc, lấy lại sức, rồi tách khỏi các ham muốn giác quan … sống an trú trong tầng lắng tâm thứ nhất.",
  "mn85:34-37.2": "Khi sự nghĩ lời và xét kỹ lắng xuống … tầng lắng tâm thứ hai …",
  "mn85:34-37.3": "tầng lắng tâm thứ ba …",
  "mn85:34-37.4": "ta sống an trú trong tầng lắng tâm thứ tư.",
  "mn85:34-37.5": "Khi tâm ta yên vững như vậy, trong sạch, sáng sạch, không nhơ bợn, sạch mọi vết dơ, mềm mại, dễ dùng, đứng vững, không lay động, ta hướng tâm đến sự biết nhớ lại các đời sống trước.",
  "mn85:34-37.6": "Ta nhớ lại nhiều đời sống trước khác nhau, như là: một đời, hai đời … như vậy, với nét riêng và chi tiết, ta nhớ lại nhiều đời sống trước khác nhau.",
  "mn85:34-37.7": "Này hoàng tử, đó là sự biết thứ nhất mà ta đạt được vào canh đầu của đêm.",
  "mn85:34-37.8": "Sự không biết bị xua tan, sự hiểu biết sinh ra; bóng tối tan đi, ánh sáng hiện ra — đúng như với người sống không buông lung, bền chí, dốc lòng.",
  "mn85:38.1": "Khi tâm ta yên vững như vậy, trong sạch, sáng sạch, không nhơ bợn, sạch mọi vết dơ, mềm mại, dễ dùng, đứng vững, không lay động, ta hướng tâm đến sự biết về chúng sinh chết đi rồi sinh ra.",
  "mn85:38.2": "Với mắt trời trong sạch, vượt khỏi mắt người thường, ta thấy chúng sinh chết đi, sinh ra, kẻ thấp kẻ cao, người đẹp người xấu, đi về chỗ lành hay chỗ dữ; ta hiểu rõ chúng sinh đi theo việc mình đã làm …",
  "mn85:39.1": "Này hoàng tử, đó là sự biết thứ hai mà ta đạt được vào canh giữa của đêm. Sự không biết bị xua tan, sự hiểu biết sinh ra; bóng tối tan đi, ánh sáng hiện ra — đúng như với người sống không buông lung, bền chí, dốc lòng.",
  "mn85:40.1": "Khi tâm ta yên vững như vậy, trong sạch, sáng sạch, không nhơ bợn, sạch mọi vết dơ, mềm mại, dễ dùng, đứng vững, không lay động, ta hướng tâm đến sự biết về sự dứt sạch các dòng chảy ngầm.",
  "mn85:40.2": "Ta hiểu đúng như thật: ‘Đây là sự khổ đau’ … ‘Đây là con đường đưa đến chấm dứt sự khổ đau’;",
  "mn85:40.3": "‘Đây là các dòng chảy ngầm’ … ‘Đây là con đường đưa đến chấm dứt các dòng chảy ngầm’, ta hiểu đúng như thật.",
  "mn85:41.1": "Khi biết như vậy, thấy như vậy, tâm ta thoát khỏi dòng chảy ngầm của ham muốn giác quan, cũng thoát khỏi dòng chảy ngầm của sự tiếp nối đời sống, cũng thoát khỏi dòng chảy ngầm của sự không biết.",
  "mn85:41.2": "Khi tâm đã thoát, sự biết hiện ra: ‘Tâm đã thoát.’",
  "mn85:41.3": "Ta hiểu rõ: ‘Sinh đã dứt, đời sống phạm hạnh đã sống xong, việc cần làm đã làm xong, không còn trở lại trạng thái này nữa.’",
  "mn85:42.1": "Này hoàng tử, đó là sự biết thứ ba mà ta đạt được vào canh cuối của đêm.",
  "mn85:42.2": "Sự không biết bị xua tan, sự hiểu biết sinh ra; bóng tối tan đi, ánh sáng hiện ra — đúng như với người sống không buông lung, bền chí, dốc lòng.",
  "mn85:43.1": "Này hoàng tử, rồi ta nghĩ như vầy:",
  "mn85:43.2": "‘Điều ta đạt được này thật sâu xa, khó thấy, khó hiểu, yên lặng, cao đẹp, không thuộc chỗ suy tính suông, rất tinh tế, chỉ người sáng dạ mới nhận ra.",
  "mn85:43.3": "Nhưng người đời này thích chỗ bám víu, vui với chỗ bám víu, mừng với chỗ bám víu.",
  "mn85:43.4": "Với người đời thích chỗ bám víu, vui với chỗ bám víu, mừng với chỗ bám víu, điều này thật khó thấy, đó là: cái này có nên cái kia có, từ đó mọi thứ nương nhau mà sinh khởi.",
  "mn85:43.5": "Điều này cũng thật khó thấy, đó là: làm lắng yên mọi tạo tác, buông hết mọi chỗ vin bám, dứt sạch thèm muốn, phai nhạt dính mắc, chấm dứt, tắt hẳn.",
  "mn85:43.6": "Nếu ta giảng dạy điều này mà người khác không hiểu ta, thì đó sẽ là mệt nhọc cho ta, là khó nhọc cho ta.’",
  "mn85:43.7": "Này hoàng tử, rồi những câu kệ này hiện đến với ta, chưa từng được nghe trước đây:",
  "mn85:43.8": "‘Ta khó nhọc lắm mới đạt được,",
  "mn85:43.9": "thôi nay chưa nên bày ra;",
  "mn85:43.10": "Với những người bị tham muốn và giận dữ chi phối,’",
  "mn85:43.11": "Lẽ thật này không dễ hiểu thấu.",
  "mn85:43.12": "Nó đi ngược dòng, rất tinh tế,",
  "mn85:43.13": "sâu kín, khó thấy, rất nhỏ nhiệm;",
  "mn85:43.14": "những ai say đắm ham muốn thì không thấy được,",
  "mn85:43.15": "vì bị một khối tối tăm che phủ.",
  "mn85:43.16": "Này hoàng tử, khi Ta suy nghĩ như vậy, lòng Ta nghiêng về yên lặng, không nghiêng về việc giảng dạy lẽ thật.",
  "mn85:44.1": "Rồi này hoàng tử, Phạm thiên Sahampati biết được ý nghĩ trong lòng Ta bằng tâm mình, liền nghĩ rằng:",
  "mn85:44.2": "‘Than ôi, đời này thật sẽ mất; than ôi, đời này thật sẽ tiêu tan. Vì nay tâm của một bậc Như Lai, bậc đã sạch hết lậu hoặc, bậc tự mình hiểu trọn vẹn, lại nghiêng về yên lặng, không nghiêng về việc giảng dạy lẽ thật.’",
  "mn85:44.3": "Rồi này hoàng tử, Phạm thiên Sahampati—như một người khỏe co cánh tay đang duỗi lại, hay duỗi cánh tay đang co ra—cũng nhanh như vậy, biến mất khỏi cõi Phạm thiên và hiện ra trước mặt Ta.",
  "mn85:44.4": "Rồi này hoàng tử, Phạm thiên Sahampati vắt y qua một bên vai, chắp tay hướng về Ta và nói với Ta rằng:",
  "mn85:44.5": "‘Xin Đức Thế Tôn giảng lẽ thật, xin bậc Khéo Đi giảng lẽ thật.",
  "mn85:44.6": "Có những chúng sinh ít bụi trong mắt, vì không được nghe lẽ thật mà bị thiệt mất;",
  "mn85:44.7": "sẽ có những người hiểu được lẽ thật.’",
  "mn85:44.8": "Này hoàng tử, đó là lời Phạm thiên Sahampati nói.",
  "mn85:44.9": "Nói xong, vị ấy lại nói thêm rằng:",
  "mn85:44.10": "‘Trước đây ở xứ Magadha đã hiện ra",
  "mn85:44.11": "những lời dạy không trong sạch, do những kẻ còn nhơ bẩn nghĩ ra.",
  "mn85:44.12": "Xin mở toang cánh cửa của cái không chết,",
  "mn85:44.13": "để người ta được nghe lẽ thật do bậc trong sạch tự mình hiểu ra.",
  "mn85:44.14": "Như người đứng trên đỉnh núi đá",
  "mn85:44.15": "có thể nhìn thấy dân chúng khắp bốn phía;",
  "mn85:44.16": "cũng vậy, này bậc rất sáng suốt, đầy ắp lẽ thật,",
  "mn85:44.17": "xin lên lầu cao và nhìn khắp mọi phía.",
  "mn85:44.18": "Xin nhìn xuống đám người đang chìm trong buồn đau, còn Ngài đã lìa buồn đau,",
  "mn85:44.19": "đang bị sinh ra và già yếu đè nặng.",
  "mn85:44.20": "Xin đứng dậy, hỡi bậc anh hùng, người đã thắng trận chiến,",
  "mn85:44.21": "hỡi người dẫn đường, không còn mắc nợ, hãy đi khắp đời;",
  "mn85:44.22": "xin Đức Thế Tôn giảng lẽ thật,",
  "mn85:44.23": "sẽ có những người hiểu được.’",
  "mn85:45.1": "Rồi này hoàng tử, biết được lời thỉnh cầu của Phạm thiên và vì lòng thương đối với chúng sinh, Ta dùng mắt giác ngộ nhìn khắp đời.",
  "mn85:45.2": "Này hoàng tử, khi Ta dùng mắt giác ngộ nhìn khắp đời, Ta thấy chúng sinh có kẻ ít bụi trong mắt, có kẻ nhiều bụi trong mắt; có kẻ căn bén, có kẻ căn chậm; có kẻ dễ dạy, có kẻ khó dạy; có kẻ dễ hiểu, có kẻ khó hiểu; có kẻ sống thấy rõ nỗi sợ do việc xấu và do đời sau, có kẻ không sống thấy rõ nỗi sợ do việc xấu và do đời sau.",
  "mn85:45.3": "Cũng như trong ao sen xanh, ao sen hồng, hay ao sen trắng, có những bông sen sinh trong nước, lớn lên trong nước, chưa vươn khỏi mặt nước, còn chìm trong nước; có những bông sen sinh trong nước, lớn lên trong nước, vươn tới mặt nước và đứng ngang mặt nước; có những bông sen sinh trong nước, lớn lên trong nước, vươn lên khỏi nước và đứng đó, không bị nước dính bám.",
  "mn85:45.4": "Cũng vậy, này hoàng tử, khi Ta dùng mắt giác ngộ nhìn khắp đời, Ta thấy chúng sinh có kẻ ít bụi trong mắt, có kẻ nhiều bụi trong mắt; có kẻ căn bén, có kẻ căn chậm; có kẻ dễ dạy, có kẻ khó dạy; có kẻ dễ hiểu, có kẻ khó hiểu; có kẻ sống thấy rõ nỗi sợ do việc xấu và do đời sau, có kẻ không sống thấy rõ nỗi sợ do việc xấu và do đời sau.",
  "mn85:45.5": "Rồi, này hoàng tử, Ta đáp lại Phạm thiên Sahampati bằng kệ rằng:",
  "mn85:45.6": "‘Cửa vào cái không chết đã mở ra cho họ,",
  "mn85:45.7": "Ai có tai để nghe, hãy buông lòng tin ra;",
  "mn85:45.8": "Vì nghĩ đến sự hại, Ta đã không nói ra",
  "mn85:45.9": "lời dạy cao đẹp, tinh tế giữa loài người, này Phạm thiên.’",
  "mn85:45.10": "Rồi, này hoàng tử, Phạm thiên Sahampati nghĩ: ‘Đức Thế Tôn đã cho ta cơ hội để thỉnh Ngài nói lời dạy,’ rồi đảnh lễ Ta, đi quanh bên phải, và biến mất ngay tại đó.",
  "mn85:46.1": "Khi ấy, này hoàng tử, Ta nghĩ rằng:",
  "mn85:46.2": "‘Ta nên nói lời dạy này trước hết cho ai?",
  "mn85:46.3": "Ai sẽ mau chóng hiểu lời dạy này?’",
  "mn85:46.4": "Rồi, này hoàng tử, Ta nghĩ rằng:",
  "mn85:46.5": "‘Āḷāra Kālāma này là người sáng dạ, khéo léo, có trí, từ lâu là người ít bụi trong mắt.",
  "mn85:46.6": "Hay là Ta nên nói lời dạy này trước hết cho Āḷāra Kālāma;",
  "mn85:46.7": "ông ấy sẽ mau chóng hiểu lời dạy này.’",
  "mn85:46.8": "Rồi, này hoàng tử, có một vị trời đến gần Ta và nói rằng:",
  "mn85:46.9": "‘Bạch Ngài, Āḷāra Kālāma đã mất được bảy ngày rồi.’",
  "mn85:46.10": "Và nơi Ta khởi lên sự biết và sự thấy rằng:",
  "mn85:46.11": "‘Āḷāra Kālāma đã mất được bảy ngày rồi.’",
  "mn85:46.12": "Rồi, này hoàng tử, Ta nghĩ rằng:",
  "mn85:46.13": "‘Āḷāra Kālāma thật là một mất mát lớn.",
  "mn85:46.14": "Nếu ông ấy được nghe lời dạy này, ông ấy sẽ mau chóng hiểu ra.’",
  "mn85:47.1": "Rồi, này hoàng tử, Ta nghĩ rằng:",
  "mn85:47.2": "‘Ta nên nói lời dạy này trước hết cho ai?",
  "mn85:47.3": "Ai sẽ mau chóng hiểu lời dạy này?’",
  "mn85:47.4": "Rồi, này hoàng tử, Ta nghĩ rằng:",
  "mn85:47.5": "‘Udaka Rāmaputta này là người sáng dạ, khéo léo, có trí, từ lâu là người ít bụi trong mắt.",
  "mn85:47.6": "Hay là Ta nên nói lời dạy này trước hết cho Udaka Rāmaputta;",
  "mn85:47.7": "ông ấy sẽ mau chóng hiểu lời dạy này.’",
  "mn85:47.8": "Rồi, này hoàng tử, có một vị trời đến gặp ta và nói như vầy:",
  "mn85:47.9": "‘Thưa ngài, Udaka Rāmaputta đã mất vào đầu đêm qua.’",
  "mn85:47.10": "Rồi nơi ta khởi lên sự biết và thấy rõ:",
  "mn85:47.11": "‘Udaka Rāmaputta đã mất vào đầu đêm qua.’",
  "mn85:47.12": "Khi ấy, này hoàng tử, ta nghĩ như vầy:",
  "mn85:47.13": "‘Udaka Rāmaputta thật là người rất sáng dạ.",
  "mn85:47.14": "Nếu ông ấy được nghe lời dạy này, hẳn sẽ mau hiểu ngay.’",
  "mn85:48.1": "Khi ấy, này hoàng tử, ta nghĩ như vầy:",
  "mn85:48.2": "‘Ta nên giảng lời dạy này trước tiên cho ai đây?",
  "mn85:48.3": "Ai sẽ mau hiểu lời dạy này ngay?’",
  "mn85:48.4": "Khi ấy, này hoàng tử, ta nghĩ như vầy:",
  "mn85:48.5": "‘Năm vị Tỳ Kheo cùng nhóm đã giúp đỡ ta nhiều, những vị đã chăm lo cho ta khi ta dốc lòng gắng sức.",
  "mn85:48.6": "Hay là ta sẽ giảng lời dạy này trước tiên cho năm vị Tỳ Kheo ấy.’",
  "mn85:48.7": "Khi ấy, này hoàng tử, ta nghĩ như vầy:",
  "mn85:48.8": "‘Bây giờ năm vị Tỳ Kheo ấy đang ở đâu?’",
  "mn85:48.9": "Rồi ta, này hoàng tử, với mắt trời trong sạch, vượt khỏi cái thấy của người thường, đã thấy năm vị Tỳ Kheo ấy đang ở gần Bārāṇasī, tại chỗ các vị tiên xưa từng ở, trong vườn nai.",
  "mn85:49.1": "Rồi ta, này hoàng tử, sau khi ở lại Uruvelā lâu chừng nào ta thấy vừa ý, đã lên đường đi về phía Bārāṇasī.",
  "mn85:49.2": "Này hoàng tử, khi ta đang đi trên đường giữa Gayā và cội bồ đề, du sĩ khổ hạnh Upaka đã thấy ta.",
  "mn85:49.3": "Thấy ta, ông ấy nói như vầy:",
  "mn85:49.4": "‘Này bạn, các giác quan của bạn thật trong sáng, da mặt thật sạch và rạng rỡ.",
  "mn85:49.5": "Vì ai mà bạn đã bỏ nhà ra đi? Ai là thầy của bạn? Bạn ưa thích lời dạy của ai?’",
  "mn85:49.6": "Khi được nói vậy, này hoàng tử, ta đã đáp lại du sĩ khổ hạnh Upaka bằng kệ rằng:",
  "mn85:49.7": "‘Ta đã vượt hơn tất cả, ta biết tất cả,",
  "mn85:49.8": "giữa mọi điều, ta không dính mắc;",
  "mn85:49.9": "ta đã buông hết mọi thứ, nhờ dứt sạch lòng ham muốn mà được giải thoát,",
  "mn85:49.10": "tự mình biết rõ rồi, ta còn phải nương theo ai?",
  "mn85:49.11": "Ta không có thầy,",
  "mn85:49.12": "không ai giống như ta;",
  "mn85:49.13": "trong đời này cùng với chư thiên,",
  "mn85:49.14": "không có ai ngang bằng ta.",
  "mn85:49.15": "Ta là bậc đã sạch hết ô nhiễm ở đời,",
  "mn85:49.16": "ta là bậc chỉ dạy không ai hơn;",
  "mn85:49.17": "chỉ một mình ta là bậc tự mình giác ngộ trọn vẹn,",
  "mn85:49.18": "ta đã nguội yên, đã tắt hẳn.",
  "mn85:49.19": "Để làm cho bánh xe lẽ thật lăn đi,",
  "mn85:49.20": "ta đi đến thành Kāsi;",
  "mn85:49.21": "trong cõi đời mù tối này,",
  "mn85:49.22": "ta sẽ đánh lên trống không chết.”",
  "mn85:49.23": "“Này hiền giả, nếu đúng như ông tự nhận, thì ông là bậc đã sạch hết ô nhiễm, bậc thắng không bờ mé.”",
  "mn85:49.24": "“Những người như ta mới thật là người thắng,",
  "mn85:49.25": "là những người đã tới chỗ dứt sạch các dòng rỉ chảy;",
  "mn85:49.26": "những điều xấu ác trong ta đã bị thắng rồi,",
  "mn85:49.27": "nên này Upaka, ta là người thắng.”",
  "mn85:49.28": "Khi được nói vậy, thưa hoàng tử, Upaka, người tu khổ hạnh ấy, nói: “Mong là vậy, hiền giả”, rồi lắc đầu và đi theo ngả khác.",
  "mn85:50.1": "Rồi ta, thưa hoàng tử, đi dần từng chặng, và đã đến Bārāṇasī, tại chỗ các vị tiên xưa từng ở, vườn nai, nơi có năm vị Tỳ Kheo nhóm năm người.",
  "mn85:50.2": "Thưa hoàng tử, năm vị Tỳ Kheo ấy thấy ta từ xa đang đi đến.",
  "mn85:50.3": "Thấy vậy, họ bảo nhau:",
  "mn85:50.4": "“Này các hiền giả, sa môn Gotama kia đang đến, người đã sống dễ dãi, đã rời bỏ gắng sức, đã quay lại nếp sống dễ dãi.",
  "mn85:50.5": "Không nên chào đón ông ấy, không nên đứng dậy tiếp, cũng không nên nhận bát và áo của ông ấy;",
  "mn85:50.6": "nhưng cứ đặt sẵn một chỗ ngồi, nếu ông ấy muốn thì sẽ ngồi.”",
  "mn85:50.7": "Nhưng thưa hoàng tử, khi ta càng đến gần năm vị Tỳ Kheo nhóm năm người, thì họ càng không giữ nổi điều đã hẹn với nhau.",
  "mn85:50.8": "Có người đi ra đón ta và nhận bát cùng áo. Có người dọn chỗ ngồi. Có người mang nước rửa chân đến.",
  "mn85:50.9": "Nhưng họ vẫn gọi ta bằng tên và xưng hô như với người ngang hàng.",
  "mn85:51.1": "Khi ấy, thưa hoàng tử, ta nói với năm vị Tỳ Kheo nhóm năm người như sau:",
  "mn85:51.2": "“Này các Tỳ Kheo, đừng gọi Như Lai bằng tên hay xưng hô như với người ngang hàng.",
  "mn85:51.3": "Này các Tỳ Kheo, Như Lai là bậc đã sạch hết ô nhiễm, là bậc tự mình giác ngộ trọn vẹn.",
  "mn85:51.4": "Hãy lắng tai nghe, này các Tỳ Kheo. Ta đã đạt được cái không chết. Ta chỉ dạy, ta giảng bày lẽ thật.",
  "mn85:51.5": "Nếu các ông làm theo đúng như lời chỉ dạy, thì chẳng bao lâu nữa, ngay trong đời này, tự mình biết rõ, tự mình chạm tới và an trú trong mục đích tối thượng mà con em nhà lành chân chánh rời nhà, sống không nhà để đi tu vì mục đích ấy, tức là chỗ trọn vẹn của đời sống trong sạch.”",
  "mn85:51.6": "Khi được nói vậy, thưa hoàng tử, năm vị Tỳ Kheo nhóm năm người nói với ta rằng:",
  "mn85:51.7": "“Này hiền giả Gotama, ngay cả với cách sống ấy, với đường lối ấy, với sự gắng sức khó làm ấy, ông còn chưa đạt được điều gì vượt hơn mức người thường, chưa đạt được chỗ thấy biết xứng bậc cao quý; huống nữa bây giờ ông sống dễ dãi, đã rời bỏ gắng sức, đã quay lại nếp sống dễ dãi, làm sao ông có thể đạt được điều gì vượt hơn mức người thường, đạt được chỗ thấy biết xứng bậc cao quý?”",
  "mn85:51.8": "Khi được nói vậy, này hoàng tử, ta nói với năm vị Tỳ Kheo ấy rằng:",
  "mn85:51.9": "‘Không đâu, này các Tỳ Kheo, Như Lai không sống buông lung, không rời bỏ gắng sức, không quay lại nếp sống buông lung.",
  "mn85:51.10": "Này các Tỳ Kheo, Như Lai là bậc đáng được cúng dường, tự mình hiểu trọn vẹn, không nhờ ai chỉ dạy.",
  "mn85:51.11": "Hãy lắng tai nghe, này các Tỳ Kheo. Ta đã đạt đến cái không chết, ta chỉ dạy, ta giảng bày lẽ thật.",
  "mn85:51.12": "Nếu các ông làm theo đúng như lời dạy, thì chẳng bao lâu nữa, ngay trong đời này, tự mình biết rõ, tự mình chạm tới và an trú trong chỗ cùng tột của đời sống trong sạch, là điều mà con em nhà lành chân chánh rời nhà, sống không nhà để đi tu vì điều ấy.’",
  "mn85:51.13": "Lần thứ hai, này hoàng tử, năm vị Tỳ Kheo ấy nói với ta rằng:",
  "mn85:51.14": "‘Này hiền giả Gotama, ngay với cách sống ấy, đường lối ấy, sự gắng sức khổ nhọc ấy, ông còn chưa đạt được điều gì vượt hơn mức người thường, chưa đạt được sự thấy biết đặc biệt xứng bậc cao quý; thì nay, khi sống buông lung, rời bỏ gắng sức, quay lại nếp sống buông lung, làm sao ông có thể đạt được điều ấy?’",
  "mn85:51.15": "Lần thứ hai, này hoàng tử, ta nói với năm vị Tỳ Kheo ấy rằng:",
  "mn85:51.16": "‘Không đâu, này các Tỳ Kheo, Như Lai không sống buông lung, không rời bỏ gắng sức, không quay lại nếp sống buông lung.",
  "mn85:51.17": "Này các Tỳ Kheo, Như Lai là bậc đáng được cúng dường, tự mình hiểu trọn vẹn, không nhờ ai chỉ dạy.",
  "mn85:51.18": "Hãy lắng tai nghe, này các Tỳ Kheo. Ta đã đạt đến cái không chết, ta chỉ dạy, ta giảng bày lẽ thật.",
  "mn85:51.19": "Nếu các ông làm theo đúng như lời dạy, thì chẳng bao lâu nữa, ngay trong đời này, tự mình biết rõ, tự mình chạm tới và an trú trong chỗ cùng tột của đời sống trong sạch, là điều mà con em nhà lành chân chánh rời nhà, sống không nhà để đi tu vì điều ấy.’",
  "mn85:51.20": "Lần thứ ba, này hoàng tử, năm vị Tỳ Kheo ấy nói với ta rằng:",
  "mn85:51.21": "‘Này hiền giả Gotama, ngay với cách sống ấy, đường lối ấy, sự gắng sức khổ nhọc ấy, ông còn chưa đạt được điều gì vượt hơn mức người thường, chưa đạt được sự thấy biết đặc biệt xứng bậc cao quý; thì nay, khi sống buông lung, rời bỏ gắng sức, quay lại nếp sống buông lung, làm sao ông có thể đạt được điều ấy?’",
  "mn85:52.1": "Khi được nói vậy, này hoàng tử, ta nói với năm vị Tỳ Kheo ấy rằng:",
  "mn85:52.2": "‘Này các Tỳ Kheo, trước đây các ông có từng biết ta nói ra lời như vậy chăng?’",
  "mn85:52.3": "‘Thưa không, bạch Đức Thế Tôn.’",
  "mn85:52.4": "‘Này các Tỳ Kheo, Như Lai là bậc đáng được cúng dường, tự mình hiểu trọn vẹn, không nhờ ai chỉ dạy.",
  "mn85:52.5": "Hãy lắng tai nghe, này các Tỳ Kheo. Ta đã đạt đến cái không chết, ta chỉ dạy, ta giảng bày lẽ thật.",
  "mn85:52.6": "Nếu các ông làm theo đúng như lời dạy, thì chẳng bao lâu nữa, ngay trong đời này, tự mình biết rõ, tự mình chạm tới và an trú trong chỗ cùng tột của đời sống trong sạch, là điều mà con em nhà lành chân chánh rời nhà, sống không nhà để đi tu vì điều ấy.’",
  "mn85:53.1": "Này hoàng tử, ta đã làm cho năm vị Tỳ Kheo ấy hiểu ra.",
  "mn85:53.2": "Này hoàng tử, có khi ta dạy hai vị Tỳ Kheo, còn ba vị đi khất thực.",
  "mn85:53.3": "Ba vị ấy đi khất thực mang về được gì, thì sáu người chúng ta sống nhờ vào đó.",
  "mn85:53.4": "Này hoàng tử, có khi ta dạy ba vị Tỳ Kheo, còn hai vị đi khất thực.",
  "mn85:53.5": "Hai vị ấy đi khất thực mang về được gì, thì sáu người chúng ta sống nhờ vào đó.",
  "mn85:54.1": "Rồi này hoàng tử, năm vị Tỳ Kheo ấy, khi được ta dạy như vậy, được ta chỉ bảo như vậy, thì chẳng bao lâu nữa, ngay trong đời này, tự mình biết rõ, tự mình chạm tới và an trú trong chỗ cùng tột của đời sống trong sạch, là điều mà con em nhà lành chân chánh rời nhà, sống không nhà để đi tu vì điều ấy.”",
  "mn85:55.1": "Khi được nói vậy, hoàng tử Bodhi thưa với Đức Thế Tôn rằng:",
  "mn85:55.2": "“Bạch Đức Thế Tôn, một vị Tỳ Kheo được gặp Như Lai là người dẫn đường, thì trong bao lâu có thể, ngay trong đời này, tự mình biết rõ, tự mình chạm tới và an trú trong chỗ cùng tột của đời sống trong sạch, là điều mà con em nhà lành chân chánh rời nhà, sống không nhà để đi tu vì điều ấy?”",
  "mn85:55.3": "“Vậy thì, này hoàng tử, ở đây ta sẽ hỏi lại ông chính điều ấy. Ông thấy thế nào thích hợp thì hãy trả lời như vậy.",
  "mn85:55.4": "Này hoàng tử, ông nghĩ sao,",
  "mn85:55.5": "Ngươi có giỏi nghề cưỡi voi và điều khiển voi bằng móc sắt không?",
  "mn85:55.6": "Thưa ngài, vâng, tôi giỏi nghề cưỡi voi và điều khiển voi bằng móc sắt.",
  "mn85:56.1": "Này hoàng tử, ngươi nghĩ sao,",
  "mn85:56.2": "ở đây có một người đến và nói:",
  "mn85:56.3": "‘Hoàng tử Bodhi biết nghề cưỡi voi và điều khiển voi bằng móc sắt;",
  "mn85:56.4": "ta sẽ học nghề cưỡi voi và điều khiển voi bằng móc sắt nơi vị ấy.’",
  "mn85:56.5": "Nếu người ấy không có lòng tin,",
  "mn85:56.6": "thì điều gì chỉ người có lòng tin mới đạt tới được, người ấy sẽ không đạt tới.",
  "mn85:56.7": "Nếu người ấy nhiều bệnh,",
  "mn85:56.8": "thì điều gì chỉ người ít bệnh mới đạt tới được, người ấy sẽ không đạt tới.",
  "mn85:56.9": "Nếu người ấy gian dối, lừa lọc,",
  "mn85:56.10": "thì điều gì chỉ người ngay thật, không lừa lọc mới đạt tới được, người ấy sẽ không đạt tới.",
  "mn85:56.11": "Nếu người ấy lười nhác,",
  "mn85:56.12": "thì điều gì chỉ người siêng năng gắng sức mới đạt tới được, người ấy sẽ không đạt tới.",
  "mn85:56.13": "Nếu người ấy kém hiểu biết,",
  "mn85:56.14": "thì điều gì chỉ người hiểu biết mới đạt tới được, người ấy sẽ không đạt tới.",
  "mn85:56.15": "Này hoàng tử, ngươi nghĩ sao,",
  "mn85:56.16": "người ấy có thể học nghề cưỡi voi và điều khiển voi bằng móc sắt nơi ngươi không?",
  "mn85:56.17": "Thưa ngài, chỉ cần có một trong các mặt ấy thôi, người đó cũng không thể học nghề cưỡi voi và điều khiển voi bằng móc sắt nơi tôi, huống chi là có đủ cả năm mặt ấy.",
  "mn85:57.1": "Này hoàng tử, ngươi nghĩ sao,",
  "mn85:57.2": "ở đây có một người đến và nói:",
  "mn85:57.3": "‘Hoàng tử Bodhi biết nghề cưỡi voi và điều khiển voi bằng móc sắt;",
  "mn85:57.4": "ta sẽ học nghề cưỡi voi và điều khiển voi bằng móc sắt nơi vị ấy.’",
  "mn85:57.5": "Nếu người ấy có lòng tin,",
  "mn85:57.6": "thì điều gì người có lòng tin có thể đạt tới, người ấy sẽ đạt tới.",
  "mn85:57.7": "Nếu người ấy ít bệnh,",
  "mn85:57.8": "thì điều gì người ít bệnh có thể đạt tới, người ấy sẽ đạt tới.",
  "mn85:57.9": "Nếu người ấy ngay thật, không lừa lọc,",
  "mn85:57.10": "thì điều gì người ngay thật, không lừa lọc có thể đạt tới, người ấy sẽ đạt tới.",
  "mn85:57.11": "Nếu người ấy siêng năng gắng sức,",
  "mn85:57.12": "người ấy sẽ đạt được điều có thể đạt được nhờ siêng năng gắng sức.",
  "mn85:57.13": "Người ấy cũng là người hiểu rõ;",
  "mn85:57.14": "người ấy sẽ đạt được điều có thể đạt được nhờ sự hiểu rõ.",
  "mn85:57.15": "Này hoàng tử, ông nghĩ sao,",
  "mn85:57.16": "người ấy có thể học nơi ông nghề cưỡi voi, cầm móc điều khiển voi chăng?",
  "mn85:57.17": "“Bạch ngài, chỉ cần có được một trong các phần ấy thôi, người ấy cũng có thể học nơi con nghề cưỡi voi, cầm móc điều khiển voi, huống chi là đủ cả năm phần.”",
  "mn85:58.1": "“Cũng vậy, này hoàng tử, có năm phần cần có để gắng sức.",
  "mn85:58.2": "Năm phần ấy là gì?",
  "mn85:58.3": "Ở đây, này hoàng tử, một Tỳ Kheo có lòng tin; tin vào sự giác ngộ của Như Lai rằng:",
  "mn85:58.4": "‘Đức Thế Tôn là bậc đáng được cúng dường, tự mình hiểu ra đúng trọn vẹn, đủ hiểu biết và nết sống, đã đi đến nơi tốt đẹp, hiểu rõ đời, là người dẫn dắt không ai hơn được đối với những người cần được rèn luyện, là bậc thầy của chư thiên và loài người, là bậc giác ngộ, là Đức Thế Tôn.’",
  "mn85:58.5": "vị ấy ít bệnh, ít đau, có sức tiêu hóa điều hòa, không quá lạnh, không quá nóng, vừa phải, chịu đựng được việc gắng sức;",
  "mn85:58.6": "vị ấy không dối trá, không quanh co, bày tỏ đúng như thật về mình với bậc thầy hoặc với những người hiểu biết sống cùng đời sống phạm hạnh;",
  "mn85:58.7": "vị ấy sống siêng năng gắng sức để dứt bỏ những điều xấu, làm cho những điều lành sinh khởi, có sức mạnh, bền chí, cố gắng vững vàng, không bỏ dở việc gánh vác đối với những điều lành;",
  "mn85:58.8": "vị ấy là người hiểu rõ, có sự hiểu rõ đưa đến thấy sự sinh lên và tan đi, cao quý, thấu suốt, đưa đến chấm dứt hẳn sự khổ đau một cách đúng đắn.",
  "mn85:58.9": "Này hoàng tử, đó là năm phần cần có để gắng sức.",
  "mn85:59.1": "Này hoàng tử, một Tỳ Kheo có đủ năm phần cần có để gắng sức này, lại gặp được Như Lai là người dẫn dắt—",
  "mn85:59.2": "vì mục đích mà những người con trai trong gia đình, sau khi suy xét đúng đắn, rời nhà sống không nhà, xuất gia, thì vị ấy có thể ngay trong đời này tự mình biết rõ, tự mình chứng nghiệm, đạt đến và an trú trong đích cao nhất, là chỗ trọn vẹn của đời sống phạm hạnh, trong bảy năm.",
  "mn85:59.3": "Thôi, này hoàng tử, đừng nói bảy năm.",
  "mn85:59.4": "Một Tỳ Kheo có đủ năm phần cần có để gắng sức này, lại gặp được Như Lai là người dẫn dắt—",
  "mn85:59.5": "vì mục đích mà những người con trai trong gia đình, sau khi suy xét đúng đắn, rời nhà sống không nhà, xuất gia, thì vị ấy có thể ngay trong đời này tự mình biết rõ, tự mình chứng nghiệm, đạt đến và an trú trong đích cao nhất, là chỗ trọn vẹn của đời sống phạm hạnh, trong sáu năm…",
  "mn85:59.6": "năm năm…",
  "mn85:59.7": "bốn năm…",
  "mn85:59.8": "ba năm…",
  "mn85:59.9": "hai năm…",
  "mn85:59.10": "một năm.",
  "mn85:59.11": "Thôi, này hoàng tử, đừng nói một năm.",
  "mn85:59.12": "Một Tỳ Kheo có đủ năm phần cần có để gắng sức này, lại gặp được Như Lai là người dẫn dắt—",
  "mn85:59.13": "vì mục đích mà những người con trai trong gia đình, sau khi suy xét đúng đắn, rời nhà sống không nhà, xuất gia, thì vị ấy có thể ngay trong đời này tự mình biết rõ, tự mình chứng nghiệm, đạt đến và an trú trong đích cao nhất, là chỗ trọn vẹn của đời sống phạm hạnh, trong bảy tháng.",
  "mn85:59.14": "Thôi, này hoàng tử, đừng nói bảy tháng.",
  "mn85:59.15": "Một Tỳ Kheo có đủ năm phần cần có để gắng sức này, lại gặp được Như Lai là người dẫn dắt—",
  "mn85:59.16": "điều tối thượng mà những người con trai trong gia đình chân chánh rời nhà, sống không nhà để đi tu là đây—",
  "mn85:59.17": "sống trọn đời sống trong sạch, ngay trong đời này tự mình biết rõ, tự mình thấy rõ, đạt tới rồi an trú trong đó trong sáu tháng…",
  "mn85:59.18": "năm tháng…",
  "mn85:59.19": "bốn tháng…",
  "mn85:59.20": "ba tháng…",
  "mn85:59.21": "hai tháng…",
  "mn85:59.22": "một tháng…",
  "mn85:59.23": "nửa tháng.",
  "mn85:59.24": "Thôi, thưa vương tử, nửa tháng cũng được.",
  "mn85:59.25": "Một Tỳ Kheo có đủ năm phần siêng năng này, lại gặp được Đức Như Lai là người dẫn dắt—",
  "mn85:59.26": "điều tối thượng mà những người con trai trong gia đình chân chánh rời nhà, sống không nhà để đi tu là đây—",
  "mn85:59.27": "sống trọn đời sống trong sạch, ngay trong đời này tự mình biết rõ, tự mình thấy rõ, đạt tới rồi an trú trong đó trong bảy ngày đêm.",
  "mn85:59.28": "Thôi, thưa vương tử, bảy ngày đêm cũng được.",
  "mn85:59.29": "Một Tỳ Kheo có đủ năm phần siêng năng này, lại gặp được Đức Như Lai là người dẫn dắt—",
  "mn85:59.30": "điều tối thượng mà những người con trai trong gia đình chân chánh rời nhà, sống không nhà để đi tu là đây—",
  "mn85:59.31": "sống trọn đời sống trong sạch, ngay trong đời này tự mình biết rõ, tự mình thấy rõ, đạt tới rồi an trú trong đó trong sáu ngày đêm…",
  "mn85:59.32": "năm ngày đêm…",
  "mn85:59.33": "bốn ngày đêm…",
  "mn85:59.34": "ba ngày đêm…",
  "mn85:59.35": "hai ngày đêm…",
  "mn85:59.36": "một ngày đêm.",
  "mn85:59.37": "Thôi, thưa vương tử, một ngày đêm cũng được.",
  "mn85:59.38": "Một Tỳ Kheo có đủ năm phần siêng năng này, lại gặp được Đức Như Lai là người dẫn dắt, nếu được chỉ dạy vào buổi chiều thì sáng hôm sau sẽ đạt phần hơn; nếu được chỉ dạy vào buổi sáng thì chiều hôm ấy sẽ đạt phần hơn.”",
  "mn85:60.1": "Khi được nói vậy, vương tử Bodhi thưa với Đức Thế Tôn như sau:",
  "mn85:60.2": "“Thật kỳ diệu, bậc Giác Ngộ! Thật kỳ diệu, lời dạy! Thật khéo nói biết bao, lời dạy ấy.",
  "mn85:60.3": "Vì ở đây, người được chỉ dạy vào buổi chiều thì sáng hôm sau sẽ đạt phần hơn; người được chỉ dạy vào buổi sáng thì chiều hôm ấy sẽ đạt phần hơn.”",
  "mn85:61.1": "Khi được nói vậy, chàng Bà-la-môn, con của Sañjikā, nói với vương tử Bodhi như sau:",
  "mn85:61.2": "“Đúng là ngài Bodhi này",
  "mn85:61.3": "vừa nói: ‘Thật kỳ diệu, bậc Giác Ngộ! Thật kỳ diệu, lời dạy! Thật khéo nói biết bao, lời dạy ấy’;",
  "mn85:61.4": "thế mà lại không nương tựa nơi ngài Gotama, nơi lời dạy, và nơi chúng Tỳ Kheo.”",
  "mn85:61.5": "“Này bạn Sañjikāputta, đừng nói như vậy, đừng nói như vậy.",
  "mn85:61.6": "Này bạn Sañjikāputta, chính tôi đã nghe điều ấy trực tiếp từ vị đáng kính ấy, đã nhận điều ấy trực tiếp.”",
  "mn85:61.7": "“Có một thời, Đức Thế Tôn ở Kosambī, tại vườn Ghosita.",
  "mn85:61.8": "Lúc ấy, mẹ tôi khi đang mang thai tôi đã đi đến chỗ Đức Thế Tôn; đến nơi, bà đảnh lễ Đức Thế Tôn rồi ngồi xuống một bên. Khi đã ngồi xuống một bên, mẹ tôi thưa với Đức Thế Tôn rằng:",
  "mn85:61.9": "‘Bạch Thế Tôn, đứa bé trai hay bé gái đang ở trong bụng tôi này xin nương tựa Đức Thế Tôn, lời dạy, và hội chúng Tỳ Kheo.",
  "mn85:61.10": "Xin Đức Thế Tôn ghi nhận nó là người tại gia từ hôm nay cho đến trọn đời đã đi nương tựa.’",
  "mn85:61.11": "Có một thời, Đức Thế Tôn ở ngay tại xứ Bhagga, trên núi Susumāra, trong rừng Bhesakaḷā, tại vườn nai.",
  "mn85:61.12": "Lúc ấy, người nuôi tôi bồng tôi trên tay đi đến chỗ Đức Thế Tôn; đến nơi, bà đảnh lễ Đức Thế Tôn rồi đứng sang một bên. Khi đã đứng sang một bên, người nuôi tôi thưa với Đức Thế Tôn rằng:",
  "mn85:61.13": "‘Bạch Thế Tôn, đây là hoàng tử Bodhi xin nương tựa Đức Thế Tôn, lời dạy, và hội chúng Tỳ Kheo.",
  "mn85:61.14": "Xin Đức Thế Tôn ghi nhận nó là người tại gia từ hôm nay cho đến trọn đời đã đi nương tựa.’",
  "mn85:61.15": "Này bạn Sañjikāputta, nay tôi lần thứ ba xin nương tựa Đức Thế Tôn, lời dạy, và hội chúng Tỳ Kheo.",
  "mn85:61.16": "Xin Đức Thế Tôn ghi nhận tôi là người tại gia từ hôm nay cho đến trọn đời đã đi nương tựa.”",
  "mn85:61.17": "Kinh Hoàng tử Bodhi chấm dứt, bài thứ năm."
}
window.BILARA["mn85"]["vi"]["mn85:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
