window.BILARA = window.BILARA || {};
window.BILARA["mn89"] = window.BILARA["mn89"] || {};
window.BILARA["mn89"]["vi"] = {
  "mn89:0.1": "Trung Bộ Kinh 89",
  "mn89:0.2": "Kinh Đài Tưởng Nhớ Điều Lành",
  "mn89:1.1": "Tôi nghe như vầy—",
  "mn89:1.2": "Một thời, Đức Thế Tôn ở giữa dân Thích Ca, tại một thị trấn của người Thích Ca tên là Medāḷupa.",
  "mn89:2.1": "Lúc ấy, vua Pasenadi nước Kosala đã đến thành phố vì một việc gì đó.",
  "mn89:2.2": "Rồi vua Pasenadi nước Kosala gọi Dīgha Kārāyana:",
  "mn89:2.3": "“Này Kārāyana, hãy cho thắng những cỗ xe tốt tốt vào, ta sẽ đi đến khu vườn để ngắm cảnh đẹp.”",
  "mn89:2.4": "“Vâng, thưa ngài,” Dīgha Kārāyana đáp lời vua Pasenadi nước Kosala, cho thắng những cỗ xe tốt tốt vào rồi thưa với vua Pasenadi nước Kosala:",
  "mn89:2.5": "“Thưa ngài, những cỗ xe tốt tốt đã sẵn sàng.",
  "mn89:2.6": "Xin ngài xem lúc nào là phải.”",
  "mn89:3.1": "Rồi vua Pasenadi nước Kosala lên cỗ xe tốt, cùng những cỗ xe tốt tốt đi ra khỏi thành phố với uy thế lớn của bậc vua chúa.",
  "mn89:3.2": "Nhà vua đi về phía khu vườn.",
  "mn89:3.3": "Đi xe đến chỗ xe còn đi được, rồi xuống xe và đi bộ vào khu vườn.",
  "mn89:4.1": "Vua Pasenadi nước Kosala thấy trong khu vườn có những gốc cây thật đẹp, gợi lòng tin, yên ắng, ít tiếng động, vắng vẻ, tránh xa chỗ người qua lại, hợp cho ngồi riêng một mình, trong khi nhà vua đang đi dạo và đi tới đi lui.",
  "mn89:4.2": "Khi thấy vậy, nhà vua chợt nhớ đến Đức Thế Tôn:",
  "mn89:4.3": "“Đúng là những gốc cây đẹp, gợi lòng tin, yên ắng, ít tiếng động, vắng vẻ, tránh xa chỗ người qua lại, hợp cho ngồi riêng một mình như thế này là nơi mà trước kia ta thường đến gần Đức Thế Tôn, bậc đáng kính, bậc tự mình hiểu trọn vẹn.”",
  "mn89:4.4": "Rồi vua Pasenadi nước Kosala gọi Dīgha Kārāyana:",
  "mn89:4.5": "“Này Kārāyana, đúng là những gốc cây đẹp, gợi lòng tin, yên ắng, ít tiếng động, vắng vẻ, tránh xa chỗ người qua lại, hợp cho ngồi riêng một mình như thế này là nơi mà trước kia ta thường đến gần Đức Thế Tôn, bậc đáng kính, bậc tự mình hiểu trọn vẹn.",
  "mn89:4.6": "Này Kārāyana, giờ đây Đức Thế Tôn, bậc đáng kính, bậc tự mình hiểu trọn vẹn đang ở đâu?”",
  "mn89:5.1": "“Thưa đại vương, có một thị trấn của người Thích Ca tên là Medāḷupa.",
  "mn89:5.2": "Hiện nay Đức Thế Tôn, bậc đáng kính, bậc tự mình hiểu trọn vẹn đang ở đó.”",
  "mn89:5.3": "“Này Kārāyana, từ thành phố đến thị trấn của người Thích Ca tên là Medāḷupa ấy xa chừng nào?”",
  "mn89:5.4": "“Không xa đâu, thưa đại vương;",
  "mn89:5.5": "ba do-tuần;",
  "mn89:5.6": "có thể đến nơi trước khi hết ngày.”",
  "mn89:5.7": "“Vậy thì, này Kārāyana, hãy cho thắng những cỗ xe tốt tốt vào, ta sẽ đi gặp Đức Thế Tôn, bậc đáng kính, bậc tự mình hiểu trọn vẹn.”",
  "mn89:5.8": "“Vâng, thưa ngài,” Dīgha Kārāyana đáp lời vua Pasenadi nước Kosala, cho thắng những cỗ xe tốt tốt vào rồi thưa với vua Pasenadi nước Kosala:",
  "mn89:5.9": "“Thưa ngài, những cỗ xe tốt tốt đã sẵn sàng.",
  "mn89:5.10": "Xin ngài xem lúc nào là phải.”",
  "mn89:6.1": "Rồi vua Pasenadi nước Kosala lên cỗ xe tốt, cùng những cỗ xe tốt tốt đi ra khỏi thành phố, hướng đến thị trấn của người Thích Ca tên là Medāḷupa.",
  "mn89:6.2": "Ngay trong phần còn lại của ngày hôm ấy, vua đến một thị trấn của dòng Sakya tên là Medāḷupa.",
  "mn89:6.3": "Vua đi đến khu vườn.",
  "mn89:6.4": "Đi xe đến chỗ xe còn đi được, rồi xuống xe và đi bộ vào khu vườn.",
  "mn89:7.1": "Lúc ấy có nhiều Tỳ Kheo đang đi qua đi lại ngoài trời.",
  "mn89:7.2": "Rồi vua Pasenadi nước Kosala đi đến chỗ các Tỳ Kheo ấy, đến nơi rồi hỏi:",
  "mn89:7.3": "“Bạch các ngài, lúc này Đức Thế Tôn, bậc đáng kính, bậc tự mình hiểu ra trọn vẹn, đang ở đâu?",
  "mn89:7.4": "Vì chúng tôi muốn gặp Đức Thế Tôn, bậc đáng kính, bậc tự mình hiểu ra trọn vẹn.”",
  "mn89:8.1": "“Tâu đại vương, đó là am có cửa đóng. Xin đại vương đi đến thật khẽ, đừng vội, bước vào hiên, hắng giọng rồi gõ then cửa. Đức Thế Tôn sẽ mở cửa cho đại vương.”",
  "mn89:8.2": "Rồi ngay tại đó, vua Pasenadi nước Kosala trao gươm và khăn đội đầu cho Dīgha Kārāyana.",
  "mn89:8.3": "Bấy giờ Dīgha Kārāyana nghĩ rằng:",
  "mn89:8.4": "“Giờ vua đi vào chỗ kín, vậy ta nên đứng lại ngay đây.”",
  "mn89:8.5": "Rồi vua Pasenadi nước Kosala đi thật khẽ đến am có cửa đóng ấy, không vội, bước vào hiên, hắng giọng rồi gõ then cửa. Đức Thế Tôn mở cửa.",
  "mn89:9.1": "Rồi vua Pasenadi nước Kosala bước vào am, cúi đầu sát dưới chân Đức Thế Tôn, hôn chân Ngài và lấy tay xoa chân Ngài, rồi xưng tên mình:",
  "mn89:9.2": "“Bạch ngài, con là vua Pasenadi nước Kosala;",
  "mn89:9.3": "bạch ngài, con là vua Pasenadi nước Kosala.”",
  "mn89:9.4": "“Nhưng này đại vương, thấy điều lợi ích gì mà đại vương lại làm sự kính trọng rất mực như vậy đối với thân này, và bày tỏ lòng thân mến như thế?”",
  "mn89:10.1": "“Bạch ngài, con có lòng tin theo điều này đối với Đức Thế Tôn:",
  "mn89:10.2": "‘Đức Thế Tôn là bậc tự mình hiểu ra trọn vẹn, lời dạy do Đức Thế Tôn chỉ bày thật khéo, đoàn người học theo Đức Thế Tôn sống đúng đường.’",
  "mn89:10.3": "Ở đây, bạch ngài, con thấy có những sa môn và bà la môn sống đời trong sạch có giới hạn trong mười năm, hai mươi năm, ba mươi năm, bốn mươi năm.",
  "mn89:10.4": "Rồi về sau, họ tắm rửa sạch sẽ, xức thơm, sửa tóc sửa râu, hưởng đủ năm món vui của giác quan.",
  "mn89:10.5": "Còn ở đây, bạch ngài, con thấy các Tỳ Kheo sống đời trong sạch trọn vẹn, tinh sạch, cho đến hết đời.",
  "mn89:10.6": "Bạch ngài, ngoài giáo pháp này ra, con không thấy ở đâu có đời sống trong sạch nào trọn vẹn và tinh sạch như vậy.",
  "mn89:10.7": "Đây cũng là một điều khiến con có lòng tin theo đối với Đức Thế Tôn:",
  "mn89:10.8": "‘Đức Thế Tôn là bậc tự mình hiểu ra trọn vẹn, lời dạy do Đức Thế Tôn chỉ bày thật khéo, đoàn người học theo Đức Thế Tôn sống đúng đường.’",
  "mn89:11.1": "Lại nữa, bạch ngài, các vua còn cãi nhau với các vua, người dòng chiến sĩ còn cãi nhau với người dòng chiến sĩ, bà la môn còn cãi nhau với bà la môn, người chủ nhà còn cãi nhau với người chủ nhà; mẹ cũng cãi với con, con cũng cãi với mẹ; cha cũng cãi với con, con cũng cãi với cha; anh em trai cũng cãi với chị em gái, chị em gái cũng cãi với anh em trai; bạn bè cũng cãi với bạn bè.",
  "mn89:11.2": "Còn ở đây, bạch ngài, con thấy các Tỳ Kheo sống hòa hợp, vui vẻ với nhau, không cãi nhau, chan hòa như nước với sữa, nhìn nhau bằng ánh mắt thương mến.",
  "mn89:11.3": "Bạch ngài, ngoài giáo pháp này ra, con không thấy một nhóm nào hòa hợp như vậy.",
  "mn89:11.4": "Đây cũng là một điều khiến con có lòng tin theo đối với Đức Thế Tôn:",
  "mn89:11.5": "‘Đức Thế Tôn là bậc tự mình hiểu ra trọn vẹn, lời dạy do Đức Thế Tôn chỉ bày thật khéo, đoàn người học theo Đức Thế Tôn sống đúng đường.’",
  "mn89:12.1": "Lại nữa, bạch ngài, con đi dạo từ vườn này sang vườn khác, từ công viên này sang công viên khác.",
  "mn89:12.2": "Khi ở đó, con thấy có những sa môn, bà la môn gầy guộc, thô ráp, da dẻ xấu xí, tái nhợt, gân nổi khắp thân, nhìn như chẳng làm ai ưa mắt khi trông thấy.",
  "mn89:12.3": "Khi ấy, bạch Đức Thế Tôn, con nghĩ thế này:",
  "mn89:12.4": "‘Chắc hẳn các vị đáng kính này sống đời trong sạch mà không vui, hoặc họ có làm điều xấu nào đó rồi giấu kín;",
  "mn89:12.5": "vì các vị đáng kính này gầy guộc, thô ráp, da dẻ xấu xí, tái nhợt, gân nổi khắp thân, nhìn như chẳng làm ai ưa mắt khi trông thấy.’",
  "mn89:12.6": "Rồi con đến gần và nói như vầy:",
  "mn89:12.7": "‘Vì sao các vị đáng kính lại gầy guộc, thô ráp, da dẻ xấu xí, tái nhợt, gân nổi khắp thân, nhìn như chẳng làm ai ưa mắt khi trông thấy vậy?’",
  "mn89:12.8": "Họ đáp con như vầy:",
  "mn89:12.9": "‘Thưa đại vương, chúng tôi bị bệnh vàng da.’",
  "mn89:12.10": "Còn ở đây, bạch Đức Thế Tôn, con thấy các Tỳ Kheo vui vẻ, hớn hở, sống an vui, thân thể khỏe mạnh, không lo toan, da dẻ tươi sáng, sống nhờ đồ người khác cúng dường, với lòng như nai rừng.",
  "mn89:12.11": "Khi ấy, bạch Đức Thế Tôn, con nghĩ thế này:",
  "mn89:12.12": "‘Chắc hẳn các vị đáng kính này biết được điều cao quý hơn hẳn, trước và sau, trong lời dạy của Đức Thế Tôn;",
  "mn89:12.13": "vì các vị đáng kính này vui vẻ, hớn hở, sống an vui, thân thể khỏe mạnh, không lo toan, da dẻ tươi sáng, sống nhờ đồ người khác cúng dường, với lòng như nai rừng.’",
  "mn89:12.14": "Điều này nữa, bạch Đức Thế Tôn, khiến con thuận theo lòng tin nơi Đức Thế Tôn:",
  "mn89:12.15": "‘Đức Thế Tôn là bậc tự mình hiểu trọn vẹn đúng đắn, lời dạy do Đức Thế Tôn nói ra đã được chỉ bày khéo léo, đoàn đệ tử nghe theo Đức Thế Tôn đã sống đúng đường.’",
  "mn89:13.1": "Lại nữa, bạch Đức Thế Tôn, con là vua, người thuộc dòng chiến sĩ, đã làm lễ quán đảnh trên đầu;",
  "mn89:13.2": "con có thể giết người đáng bị giết, phạt người đáng bị phạt, đuổi đi người đáng bị đuổi đi.",
  "mn89:13.3": "Thế mà, bạch Đức Thế Tôn, khi con đang ngồi xử việc kiện tụng, người ta cứ chen lời vào giữa chừng.",
  "mn89:13.4": "Con không thể nói được rằng:",
  "mn89:13.5": "‘Các ông chớ chen lời vào giữa khi ta đang ngồi xử việc kiện tụng; hãy đợi ta nói xong đã.’",
  "mn89:13.6": "Vậy mà họ vẫn chen lời vào giữa chừng với con.",
  "mn89:13.7": "Còn ở đây, bạch Đức Thế Tôn, con thấy các Tỳ Kheo;",
  "mn89:13.8": "khi Đức Thế Tôn đang nói lời dạy cho hội chúng đông đến nhiều trăm người, thì trong lúc ấy, nơi các đệ tử của Đức Thế Tôn, không có cả tiếng động mạnh hay tiếng ho.",
  "mn89:13.9": "Có lần, bạch Đức Thế Tôn, Đức Thế Tôn đang nói lời dạy cho hội chúng đông đến nhiều trăm người.",
  "mn89:13.10": "Khi ấy, một đệ tử của Đức Thế Tôn ho lên.",
  "mn89:13.11": "Một vị cùng sống đời trong sạch liền lấy đầu gối khẽ chạm người ấy và nhắc:",
  "mn89:13.12": "‘Xin ngài giữ yên lặng, chớ gây tiếng động; bậc Thầy của chúng ta, Đức Thế Tôn, đang nói lời dạy.’",
  "mn89:13.13": "Khi ấy, bạch Đức Thế Tôn, con nghĩ thế này:",
  "mn89:13.14": "‘Thật lạ thay, thưa ngài, thật chưa từng có thay, thưa ngài.",
  "mn89:13.15": "Không dùng gậy, không dùng dao, mà hội chúng này lại được dạy dỗ khéo đến như vậy.’",
  "mn89:13.16": "Bạch Đức Thế Tôn, ngoài nơi này ra, con không thấy một hội chúng nào khác được dạy dỗ khéo đến như vậy.",
  "mn89:13.17": "Bạch ngài, đây cũng là điều khiến con tin chắc nơi Đức Thế Tôn:",
  "mn89:13.18": "‘Đức Thế Tôn là bậc tự mình hiểu trọn vẹn đúng đắn, lời dạy được Đức Thế Tôn nói ra khéo léo rõ ràng, đoàn đệ tử của Đức Thế Tôn sống theo nẻo lành.’",
  "mn89:14.1": "Lại nữa, bạch ngài, con thấy ở đời này có một số người thuộc dòng vua chúa, khôn ngoan, lanh lợi, giỏi bác bỏ lời người khác, sắc bén như bắn trúng sợi tóc. Họ đi đây đi đó, tưởng như có thể chẻ nát mọi cách nhìn bằng trí khôn của mình.",
  "mn89:14.2": "Họ nghe rằng:",
  "mn89:14.3": "‘Này các ông, sa môn Gotama sắp đến một làng hay một thị trấn tên như thế.’",
  "mn89:14.4": "Họ sắp sẵn câu hỏi:",
  "mn89:14.5": "‘Chúng ta sẽ đến gặp sa môn Gotama và hỏi câu này.",
  "mn89:14.6": "Nếu được hỏi mà ông ấy đáp như vầy, thì chúng ta sẽ bắt bẻ ông ấy theo cách này;",
  "mn89:14.7": "còn nếu được hỏi mà ông ấy đáp như kia, thì chúng ta sẽ bắt bẻ ông ấy theo cách kia.’",
  "mn89:14.8": "Rồi họ nghe rằng:",
  "mn89:14.9": "‘Này các ông, sa môn Gotama đã đến làng hay thị trấn tên như thế.’",
  "mn89:14.10": "Họ đi đến chỗ Đức Thế Tôn.",
  "mn89:14.11": "Đức Thế Tôn chỉ bày cho họ bằng lời nói hợp lẽ, khuyến khích họ, làm cho họ hăng hái, làm cho họ vui lên.",
  "mn89:14.12": "Khi được Đức Thế Tôn chỉ bày, khuyến khích, làm cho hăng hái, làm cho vui lên bằng lời nói hợp lẽ, họ chẳng những không hỏi Đức Thế Tôn câu nào, thì còn bắt bẻ gì được nữa?",
  "mn89:14.13": "Trái lại, họ còn trở thành đệ tử của Đức Thế Tôn.",
  "mn89:14.14": "Bạch ngài, đây cũng là điều khiến con tin chắc nơi Đức Thế Tôn:",
  "mn89:14.15": "‘Đức Thế Tôn là bậc tự mình hiểu trọn vẹn đúng đắn, lời dạy được Đức Thế Tôn nói ra khéo léo rõ ràng, đoàn đệ tử của Đức Thế Tôn sống theo nẻo lành.’",
  "mn89:15.1": "Lại nữa, bạch ngài, con thấy ở đời này có một số bà la môn khôn ngoan …",
  "mn89:16.1": "một số người chủ nhà khôn ngoan …",
  "mn89:17.1": "một số sa môn khôn ngoan, lanh lợi, giỏi bác bỏ lời người khác, sắc bén như bắn trúng sợi tóc. Họ đi đây đi đó, tưởng như có thể chẻ nát mọi cách nhìn bằng trí khôn của mình.",
  "mn89:17.2": "Họ nghe rằng:",
  "mn89:17.3": "‘Này các ông, sa môn Gotama sắp đến một làng hay một thị trấn tên như thế.’",
  "mn89:17.4": "Họ sắp sẵn câu hỏi:",
  "mn89:17.5": "‘Chúng ta sẽ đến gặp sa môn Gotama và hỏi câu này.",
  "mn89:17.6": "Nếu được hỏi mà ông ấy đáp như vầy, thì chúng ta sẽ bắt bẻ ông ấy theo cách này;",
  "mn89:17.7": "còn nếu được hỏi mà ông ấy đáp như kia, thì chúng ta sẽ bắt bẻ ông ấy theo cách kia.’",
  "mn89:17.8": "Rồi họ nghe rằng:",
  "mn89:17.9": "‘Này các ông, sa môn Gotama đã đến làng hay thị trấn tên như thế.’",
  "mn89:17.10": "Họ đi đến chỗ Đức Thế Tôn.",
  "mn89:17.11": "Đức Thế Tôn chỉ bày cho họ bằng lời nói hợp lẽ, khuyến khích họ, làm cho họ hăng hái, làm cho họ vui lên.",
  "mn89:17.12": "Họ được Đức Thế Tôn nói chuyện hợp lẽ, chỉ cho thấy rõ, khuyên cho vững lòng, khích lệ, làm cho vui mừng, nên họ không còn hỏi vặn Đức Thế Tôn nữa, huống gì là cãi lại.",
  "mn89:17.13": "Trái lại, họ chỉ xin chính Đức Thế Tôn cho phép rời nhà, sống đời không nhà.",
  "mn89:17.14": "Đức Thế Tôn cho họ xuất gia.",
  "mn89:17.15": "Sau khi đã xuất gia như vậy, họ sống riêng vắng, không buông lung, siêng năng, dốc lòng; chẳng bao lâu, ngay trong đời này, tự mình biết rõ, tự mình thấy rõ, đạt tới và an trú trọn vẹn mục đích cao nhất mà những người con trai nhà lành chân chánh rời nhà, sống đời không nhà là để hướng tới: đời sống trong sạch đã đi đến chỗ cùng tận.",
  "mn89:17.16": "Họ nói như vầy:",
  "mn89:17.17": "‘Thưa ngài, thật là chúng tôi đã mất mát. Thưa ngài, thật là chúng tôi đã mất mát quá nhiều.’",
  "mn89:17.18": "Vì trước kia, khi chưa phải là người sống đời tu, chúng tôi lại tự nhận mình là người sống đời tu; chưa phải là người sống đời sạch trong lòng, chúng tôi lại tự nhận mình là người sống đời sạch trong lòng; chưa phải là người đã dứt sạch ô nhiễm, chúng tôi lại tự nhận mình là người đã dứt sạch ô nhiễm.",
  "mn89:17.19": "Còn nay, chúng tôi mới thật là người sống đời tu, nay chúng tôi mới thật là người sống đời sạch trong lòng, nay chúng tôi mới thật là người đã dứt sạch ô nhiễm.’",
  "mn89:17.20": "Thưa ngài, đây cũng là một lẽ khiến tôi tin theo Đức Thế Tôn:",
  "mn89:17.21": "‘Đức Thế Tôn là bậc tự mình hiểu trọn vẹn và chỉ dạy cho người khác, lời dạy do Đức Thế Tôn nói ra đã khéo giảng bày, đoàn người học theo Đức Thế Tôn đã sống đúng đường.’",
  "mn89:18.1": "Lại nữa, thưa ngài, những vị chủ nhà Isidatta và Purāṇa này là người ăn cơm của tôi, đi theo tôi; tôi là người lo miếng sống cho họ, là nguồn gốc danh tiếng của họ.",
  "mn89:18.2": "Thế mà họ lại không kính nể tôi bằng kính nể Đức Thế Tôn.",
  "mn89:18.3": "Có lần, thưa ngài, khi tôi đang đi cùng quân lính, muốn dò xét những vị chủ nhà Isidatta và Purāṇa này, tôi đã đến ở trong một chỗ nghỉ chật hẹp nào đó.",
  "mn89:18.4": "Rồi, thưa ngài, những vị chủ nhà Isidatta và Purāṇa này đã dành gần trọn đêm để nói chuyện hợp lẽ; đến khi đi nằm, họ quay đầu về phía Đức Thế Tôn, còn chân hướng về phía tôi.",
  "mn89:18.5": "Lúc ấy tôi nghĩ thế này:",
  "mn89:18.6": "‘Lạ thật, thưa ngài, hiếm có thật, thưa ngài.",
  "mn89:18.7": "Những vị chủ nhà Isidatta và Purāṇa này là người ăn cơm của tôi, đi theo tôi; tôi là người lo miếng sống cho họ, là nguồn gốc danh tiếng của họ.",
  "mn89:18.8": "Thế mà họ lại không kính nể tôi bằng kính nể Đức Thế Tôn.",
  "mn89:18.9": "Chắc hẳn những vị đáng kính này biết rõ trong lời dạy của Đức Thế Tôn có sự khác biệt lớn lao, càng về sau càng cao quý hơn.’",
  "mn89:18.10": "Thưa ngài, đây cũng là một lẽ khiến tôi tin theo Đức Thế Tôn:",
  "mn89:18.11": "‘Đức Thế Tôn là bậc tự mình hiểu trọn vẹn và chỉ dạy cho người khác, lời dạy do Đức Thế Tôn nói ra đã khéo giảng bày, đoàn người học theo Đức Thế Tôn đã sống đúng đường.’",
  "mn89:19.1": "Lại nữa, thưa ngài, Đức Thế Tôn là người dòng vua, tôi cũng là người dòng vua.",
  "mn89:19.2": "Đức Thế Tôn là người xứ Kosala, tôi cũng là người xứ Kosala.",
  "mn89:19.3": "Đức Thế Tôn tám mươi tuổi, tôi cũng tám mươi tuổi.",
  "mn89:19.4": "Thưa ngài, vì Đức Thế Tôn là người dòng vua, tôi cũng là người dòng vua; Đức Thế Tôn là người xứ Kosala, tôi cũng là người xứ Kosala; Đức Thế Tôn tám mươi tuổi, tôi cũng tám mươi tuổi,",
  "mn89:19.5": "nên chỉ riêng chừng ấy thôi cũng đủ để tôi hết lòng kính trọng Đức Thế Tôn và bày tỏ tình thân.",
  "mn89:20.1": "Thôi, thưa ngài, giờ chúng tôi xin đi,",
  "mn89:20.2": "vì chúng tôi còn nhiều việc, nhiều điều phải làm.’",
  "mn89:20.3": "‘Này Đại vương, nay ngài thấy hợp lúc nào thì cứ làm theo lúc ấy.’",
  "mn89:20.4": "Rồi vua Pasenadi nước Kosala đứng dậy khỏi chỗ ngồi, cúi đầu kính lễ Đức Thế Tôn, đi nhiễu quanh bên phải rồi ra về.",
  "mn89:21.1": "Bấy giờ, sau khi vua Pasenadi nước Kosala vừa mới đi khỏi, Đức Thế Tôn gọi các Tỳ Kheo lại và nói:",
  "mn89:21.2": "Này các Tỳ Kheo, vua Pasenadi nước Kosala ấy, sau khi nói lên những lời tưởng nhớ về lẽ thật, đã đứng dậy khỏi chỗ ngồi rồi đi.",
  "mn89:21.3": "Này các Tỳ Kheo, hãy học lấy những lời tưởng nhớ về lẽ thật ấy;",
  "mn89:21.4": "này các Tỳ Kheo, hãy học cho thuộc những lời tưởng nhớ về lẽ thật ấy;",
  "mn89:21.5": "này các Tỳ Kheo, hãy ghi nhớ gìn giữ những lời tưởng nhớ về lẽ thật ấy.",
  "mn89:21.6": "Này các Tỳ Kheo, những lời tưởng nhớ về lẽ thật ấy gắn với điều lợi ích, và thuộc về nếp sống trong sạch từ buổi đầu.",
  "mn89:21.7": "Đức Thế Tôn nói như vậy.",
  "mn89:21.8": "Các Tỳ Kheo ấy vui mừng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn89:21.9": "Kinh Những Lời Tưởng Nhớ Về Lẽ Thật chấm dứt, bài thứ chín."
}
window.BILARA["mn89"]["vi"]["mn89:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
