window.BILARA = window.BILARA || {};
window.BILARA["mn93"] = window.BILARA["mn93"] || {};
window.BILARA["mn93"]["vi"] = {
  "mn93:0.1": "Trung Bộ Kinh 93",
  "mn93:0.2": "Kinh Assalāyana",
  "mn93:1.1": "Tôi nghe như vầy—",
  "mn93:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, trong rừng Kỳ Đà, tại khu vườn của ông Cấp Cô Độc.",
  "mn93:2.1": "Lúc ấy, có khoảng năm trăm Bà La Môn từ nhiều xứ khác nhau đang ở tại Xá Vệ vì một việc nào đó.",
  "mn93:2.2": "Bấy giờ, các Bà La Môn ấy nghĩ rằng:",
  "mn93:2.3": "“Sa môn Gotama này nói rằng cả bốn hạng người đều có thể trong sạch.",
  "mn93:2.4": "Vậy ai có thể cùng sa môn Gotama bàn luận về lời nói này?”",
  "mn93:3.1": "Lúc ấy, có một thanh niên tên là Assalāyana đang ở tại Xá Vệ. Cậu còn trẻ, đầu đã cạo, chừng mười sáu tuổi, đã học thông suốt ba bộ Vệ Đà cùng với từ ngữ, nghi lễ, âm chữ, chuyện xưa là phần thứ năm, giỏi về từ ngữ, giỏi về giải nghĩa, thông thạo lối lý luận thế gian và các dấu hiệu của bậc lớn.",
  "mn93:3.2": "Bấy giờ, các Bà La Môn ấy nghĩ rằng:",
  "mn93:3.3": "“Thanh niên Assalāyana này đang ở tại Xá Vệ, còn trẻ, đầu đã cạo, chừng mười sáu tuổi, đã học thông suốt ba bộ Vệ Đà … giỏi về các dấu hiệu của bậc lớn.",
  "mn93:3.4": "Cậu ấy có thể cùng sa môn Gotama bàn luận về lời nói này.”",
  "mn93:4.1": "Rồi các Bà La Môn ấy đi đến chỗ thanh niên Assalāyana. Đến nơi, họ nói với thanh niên Assalāyana rằng:",
  "mn93:4.2": "“Này Assalāyana, sa môn Gotama này nói rằng cả bốn hạng người đều có thể trong sạch.",
  "mn93:4.3": "Xin ngài Assalāyana hãy đến cùng sa môn Gotama bàn luận về lời nói này.”",
  "mn93:4.4": "Nghe nói vậy, thanh niên Assalāyana nói với các Bà La Môn ấy rằng:",
  "mn93:4.5": "“Thưa các vị, sa môn Gotama là người nói điều đúng.",
  "mn93:4.6": "Mà người nói điều đúng thì khó bàn cãi.",
  "mn93:4.7": "Tôi không thể cùng sa môn Gotama bàn luận về lời nói này.”",
  "mn93:4.8": "Lần thứ hai, các Bà La Môn ấy nói với thanh niên Assalāyana rằng:",
  "mn93:4.9": "“Này Assalāyana, sa môn Gotama này nói rằng cả bốn hạng người đều có thể trong sạch.",
  "mn93:4.10": "Xin ngài Assalāyana hãy đến cùng sa môn Gotama bàn luận về lời nói này.",
  "mn93:4.11": "Vả lại, ngài Assalāyana đã từng đi theo các du sĩ.”",
  "mn93:4.12": "Lần thứ hai, thanh niên Assalāyana nói với các Bà La Môn ấy rằng:",
  "mn93:4.13": "“Thưa các vị, sa môn Gotama là người nói điều đúng.",
  "mn93:4.14": "Mà người nói điều đúng thì khó bàn cãi.",
  "mn93:4.15": "Tôi không thể cùng sa môn Gotama bàn luận về lời nói này.”",
  "mn93:4.16": "Lần thứ ba, các Bà La Môn ấy nói với thanh niên Assalāyana rằng:",
  "mn93:4.17": "“Này Assalāyana, sa môn Gotama này nói rằng cả bốn hạng người đều có thể trong sạch.",
  "mn93:4.18": "Xin ngài Assalāyana hãy đến cùng sa môn Gotama bàn luận về lời nói này.”",
  "mn93:4.19": "Ngài Assalāyana đã từng theo học với vị du sĩ ấy.",
  "mn93:4.20": "Xin ngài Assalāyana đừng để người thua trong cuộc tranh luận với người không thua lại thành kẻ làm cho người không thua bị thua.”",
  "mn93:4.21": "Khi được nói vậy, chàng Bà-la-môn Assalāyana nói với các Bà-la-môn ấy:",
  "mn93:4.22": "“Thật ra, thưa các vị, tôi không thể làm được.",
  "mn93:4.23": "Sa-môn Gotama là người nói điều đúng.",
  "mn93:4.24": "Mà người nói điều đúng thì khó bị bác lại.",
  "mn93:4.25": "Tôi không thể tranh luận với sa-môn Gotama về lời này.",
  "mn93:4.26": "Nhưng vì lời các vị, tôi sẽ đi.”",
  "mn93:5.1": "Bấy giờ chàng Bà-la-môn Assalāyana cùng với đông đảo nhóm Bà-la-môn đi đến chỗ Đức Thế Tôn; đến nơi, ông chào hỏi thân tình với Đức Thế Tôn.",
  "mn93:5.2": "Sau khi nói chuyện thân tình gợi nhớ xong, ông ngồi xuống một bên. Khi đã ngồi xuống một bên, chàng Bà-la-môn Assalāyana thưa với Đức Thế Tôn:",
  "mn93:5.3": "“Thưa ngài Gotama, các Bà-la-môn nói như vầy:",
  "mn93:5.4": "‘Chỉ Bà-la-môn là dòng tốt nhất, dòng khác đều thấp hơn;",
  "mn93:5.5": "chỉ Bà-la-môn là dòng trắng, dòng khác là đen;",
  "mn93:5.6": "chỉ Bà-la-môn mới sạch, không phải người không phải Bà-la-môn;",
  "mn93:5.7": "chỉ Bà-la-môn là con của Phạm thiên, là con ruột sinh ra từ miệng, do Phạm thiên sinh ra, do Phạm thiên tạo ra, là kẻ thừa hưởng của Phạm thiên.’",
  "mn93:5.8": "Ở đây, ngài Gotama nói sao?”",
  "mn93:5.9": "“Nhưng này Assalāyana, người nữ Bà-la-môn vẫn thấy có kỳ kinh, vẫn mang thai, vẫn sinh con, vẫn cho con bú.",
  "mn93:5.10": "Thế mà họ, tuy thật sự được sinh ra từ bụng người nữ Bà-la-môn, lại nói như vầy:",
  "mn93:5.11": "‘Chỉ Bà-la-môn là dòng tốt nhất, dòng khác đều thấp hơn;",
  "mn93:5.12": "chỉ Bà-la-môn là dòng trắng, dòng khác là đen;",
  "mn93:5.13": "chỉ Bà-la-môn mới sạch, không phải người không phải Bà-la-môn;",
  "mn93:5.14": "chỉ Bà-la-môn là con của Phạm thiên, là con ruột sinh ra từ miệng, do Phạm thiên sinh ra, do Phạm thiên tạo ra, là kẻ thừa hưởng của Phạm thiên.’”",
  "mn93:6.1": "“Dù ngài Gotama nói như vậy, nhưng ở đây các Bà-la-môn vẫn nghĩ như vầy:",
  "mn93:6.2": "‘Chỉ Bà-la-môn là dòng tốt nhất, dòng khác đều thấp hơn …",
  "mn93:6.3": "là kẻ thừa hưởng của Phạm thiên.’”",
  "mn93:6.4": "“Assalāyana, ông nghĩ sao,",
  "mn93:6.5": "ông có nghe rằng ở xứ Yona, Kamboja và các vùng biên khác chỉ có hai hạng người: người chủ và người tôi tớ; từ người chủ có thể thành tôi tớ, từ tôi tớ có thể thành người chủ không?”",
  "mn93:6.6": "“Vâng, thưa ngài, tôi có nghe như vậy: ở xứ Yona, Kamboja và các vùng biên khác chỉ có hai hạng người: người chủ và người tôi tớ; từ người chủ có thể thành tôi tớ, từ tôi tớ có thể thành người chủ.”",
  "mn93:6.7": "“Vậy thì, Assalāyana, các Bà-la-môn có sức mạnh gì, có chỗ dựa gì, mà ở đây họ lại nói như vầy:",
  "mn93:6.8": "‘Chỉ Bà-la-môn là dòng tốt nhất, dòng khác đều thấp hơn …’",
  "mn93:6.9": "‘là con cháu của Phạm thiên’ sao?",
  "mn93:7.1": "“Dù ngài Gotama nói như vậy, nhưng ở đây các Bà-la-môn vẫn nghĩ thế này:",
  "mn93:7.2": "‘chỉ giai cấp Bà-la-môn là cao nhất, các giai cấp khác đều thấp hơn …",
  "mn93:7.3": "là con cháu của Phạm thiên’.”",
  "mn93:7.4": "“Ông nghĩ sao, Assalāyana,",
  "mn93:7.5": "có phải chỉ người Sát-đế-lỵ giết hại, lấy của không cho, ăn nằm sai trái, nói dối, nói hai lưỡi, nói lời thô ác, nói nhảm nhí, tham lam, ôm lòng hại người, thấy sai, khi thân tan rã, sau khi chết, mới rơi vào cõi dữ, đường xấu, chỗ sa đọa, địa ngục, còn Bà-la-môn thì không?",
  "mn93:7.6": "Hay chỉ người Vệ-xá …",
  "mn93:7.7": "hay chỉ người Thủ-đà giết hại, lấy của không cho, ăn nằm sai trái, nói dối, nói hai lưỡi, nói lời thô ác, nói nhảm nhí, tham lam, ôm lòng hại người, thấy sai, khi thân tan rã, sau khi chết, mới rơi vào cõi dữ, đường xấu, chỗ sa đọa, địa ngục, còn Bà-la-môn thì không?”",
  "mn93:7.8": "“Không phải vậy đâu, thưa ngài Gotama.",
  "mn93:7.9": "Vì người Sát-đế-lỵ cũng vậy, thưa ngài Gotama, nếu giết hại, lấy của không cho, ăn nằm sai trái, nói dối, nói hai lưỡi, nói lời thô ác, nói nhảm nhí, tham lam, ôm lòng hại người, thấy sai, thì khi thân tan rã, sau khi chết, cũng rơi vào cõi dữ, đường xấu, chỗ sa đọa, địa ngục.",
  "mn93:7.10": "Người Bà-la-môn cũng vậy, thưa ngài Gotama …",
  "mn93:7.11": "người Vệ-xá cũng vậy, thưa ngài Gotama …",
  "mn93:7.12": "người Thủ-đà cũng vậy, thưa ngài Gotama …",
  "mn93:7.13": "vì cả bốn giai cấp, thưa ngài Gotama, nếu giết hại, lấy của không cho, ăn nằm sai trái, nói dối, nói hai lưỡi, nói lời thô ác, nói nhảm nhí, tham lam, ôm lòng hại người, thấy sai, thì khi thân tan rã, sau khi chết, đều rơi vào cõi dữ, đường xấu, chỗ sa đọa, địa ngục.”",
  "mn93:7.14": "“Vậy thì, Assalāyana, ở đây Bà-la-môn có sức mạnh gì, có chỗ dựa gì, mà lại nói rằng:",
  "mn93:7.15": "‘chỉ giai cấp Bà-la-môn là cao nhất, các giai cấp khác đều thấp hơn …",
  "mn93:7.16": "là con cháu của Phạm thiên’?”",
  "mn93:8.1": "“Dù ngài Gotama nói như vậy, nhưng ở đây các Bà-la-môn vẫn nghĩ thế này:",
  "mn93:8.2": "‘chỉ giai cấp Bà-la-môn là cao nhất, các giai cấp khác đều thấp hơn …",
  "mn93:8.3": "là con cháu của Phạm thiên’.”",
  "mn93:8.4": "“Ông nghĩ sao, Assalāyana,",
  "mn93:8.5": "có phải chỉ Bà-la-môn là người tránh xa giết hại, tránh xa lấy của không cho, tránh xa ăn nằm sai trái, tránh xa nói dối, tránh xa nói hai lưỡi, tránh xa lời thô ác, tránh xa nói nhảm nhí, không tham lam, không ôm lòng hại người, thấy đúng, khi thân tan rã, sau khi chết, mới sinh vào cõi lành, cõi trời, còn Sát-đế-lỵ, Vệ-xá, Thủ-đà thì không?”",
  "mn93:8.6": "“Không phải vậy đâu, thưa ngài Gotama.",
  "mn93:8.7": "Vì người Sát-đế-lỵ cũng vậy, thưa ngài Gotama, nếu tránh xa giết hại, tránh xa lấy của không cho, tránh xa ăn nằm sai trái, tránh xa nói dối, tránh xa nói hai lưỡi, tránh xa lời thô ác, tránh xa nói nhảm nhí, không tham lam, không ôm lòng hại người, thấy đúng, thì khi thân tan rã, sau khi chết, cũng sinh vào cõi lành, cõi trời.",
  "mn93:8.8": "Người Bà-la-môn cũng vậy, thưa ngài Gotama …",
  "mn93:8.9": "người Vệ-xá cũng vậy, thưa ngài Gotama …",
  "mn93:8.10": "người Thủ-đà cũng vậy, thưa ngài Gotama …",
  "mn93:8.11": "vì cả bốn giai cấp, thưa ngài Gotama, nếu tránh xa giết hại, tránh xa lấy của không cho, tránh xa ăn nằm sai trái, tránh xa nói dối, tránh xa nói hai lưỡi, tránh xa lời thô ác, tránh xa nói nhảm nhí, không tham lam, không ôm lòng hại người, thấy đúng, thì khi thân tan rã, sau khi chết, đều sinh vào cõi lành, cõi trời.”",
  "mn93:8.12": "“Vậy thì, Assalāyana, ở đây Bà-la-môn có sức mạnh gì, có chỗ dựa gì, mà lại nói rằng:",
  "mn93:8.13": "‘chỉ giai cấp Bà-la-môn là cao nhất, các giai cấp khác đều thấp hơn …",
  "mn93:8.14": "‘là con cháu của Phạm thiên’ sao?",
  "mn93:9.1": "“Dù ngài Gotama nói như vậy, nhưng ở đây các Bà-la-môn vẫn nghĩ thế này:",
  "mn93:9.2": "‘chỉ giai tầng Bà-la-môn là cao quý nhất, các giai tầng khác đều thấp kém …",
  "mn93:9.3": "là con cháu của Phạm thiên’.”",
  "mn93:9.4": "“Ông nghĩ sao, Assalāyana,",
  "mn93:9.5": "có phải chỉ Bà-la-môn mới có thể ở nơi này nuôi lớn lòng thương không oán ghét, không hại ai, còn Sát-đế-lỵ, Phệ-xá, Thủ-đà-la thì không thể chăng?”",
  "mn93:9.6": "“Không phải vậy, thưa ngài Gotama.",
  "mn93:9.7": "Sát-đế-lỵ cũng có thể ở nơi này nuôi lớn lòng thương không oán ghét, không hại ai;",
  "mn93:9.8": "Bà-la-môn cũng vậy, thưa ngài Gotama …",
  "mn93:9.9": "Phệ-xá cũng vậy, thưa ngài Gotama …",
  "mn93:9.10": "Thủ-đà-la cũng vậy, thưa ngài Gotama …",
  "mn93:9.11": "cả bốn giai tầng, thưa ngài Gotama, đều có thể ở nơi này nuôi lớn lòng thương không oán ghét, không hại ai.”",
  "mn93:9.12": "“Vậy thì ở đây, Assalāyana, các Bà-la-môn có sức mạnh gì, có chỗ dựa gì, mà lại nói rằng:",
  "mn93:9.13": "‘chỉ giai tầng Bà-la-môn là cao quý nhất, các giai tầng khác đều thấp kém …",
  "mn93:9.14": "là con cháu của Phạm thiên’?”",
  "mn93:10.1": "“Dù ngài Gotama nói như vậy, nhưng ở đây các Bà-la-môn vẫn nghĩ thế này:",
  "mn93:10.2": "‘chỉ giai tầng Bà-la-môn là cao quý nhất, các giai tầng khác đều thấp kém …",
  "mn93:10.3": "là con cháu của Phạm thiên’.”",
  "mn93:10.4": "“Ông nghĩ sao, Assalāyana,",
  "mn93:10.5": "có phải chỉ Bà-la-môn mới có thể cầm đồ tắm đi ra sông để rửa sạch bụi bẩn, còn Sát-đế-lỵ, Phệ-xá, Thủ-đà-la thì không thể chăng?”",
  "mn93:10.6": "“Không phải vậy, thưa ngài Gotama.",
  "mn93:10.7": "Sát-đế-lỵ cũng có thể cầm đồ tắm đi ra sông để rửa sạch bụi bẩn; Bà-la-môn cũng vậy, thưa ngài Gotama …",
  "mn93:10.8": "Phệ-xá cũng vậy, thưa ngài Gotama …",
  "mn93:10.9": "Thủ-đà-la cũng vậy, thưa ngài Gotama …",
  "mn93:10.10": "cả bốn giai tầng, thưa ngài Gotama, đều có thể cầm đồ tắm đi ra sông để rửa sạch bụi bẩn.”",
  "mn93:10.11": "“Vậy thì ở đây, Assalāyana, các Bà-la-môn có sức mạnh gì, có chỗ dựa gì, mà lại nói rằng:",
  "mn93:10.12": "‘chỉ giai tầng Bà-la-môn là cao quý nhất, các giai tầng khác đều thấp kém …",
  "mn93:10.13": "là con cháu của Phạm thiên’?”",
  "mn93:11.1": "“Dù ngài Gotama nói như vậy, nhưng ở đây các Bà-la-môn vẫn nghĩ thế này:",
  "mn93:11.2": "‘chỉ giai tầng Bà-la-môn là cao quý nhất, các giai tầng khác đều thấp kém …",
  "mn93:11.3": "là kẻ thừa hưởng của Phạm thiên’.”",
  "mn93:11.4": "“Ông nghĩ sao, Assalāyana,",
  "mn93:11.5": "ví như một vua thuộc dòng chiến sĩ, đã làm lễ quán đảnh lên ngôi, cho gọi đến một trăm người thuộc nhiều dòng họ khác nhau:",
  "mn93:11.6": "‘Mời các vị nào sinh trong dòng chiến sĩ, dòng bà-la-môn, hay dòng vua chúa, hãy lấy thanh gỗ gây lửa trên làm bằng gỗ saka, gỗ sāl, gỗ salaḷa, gỗ chiên đàn, hay gỗ sen rừng, rồi nhóm lửa lên, làm cho lửa hiện ra.",
  "mn93:11.7": "Còn những vị nào sinh trong dòng Chiên-đà-la, dòng thợ săn, dòng đan tre, dòng làm xe, hay dòng hốt rác, thì hãy lấy thanh gỗ gây lửa trên từ máng nước cho chó, máng ăn cho heo, máng giặt đồ, hay từ gỗ thầu dầu, rồi nhóm lửa lên, làm cho lửa hiện ra.’",
  "mn93:11.8": "Ông nghĩ sao, Assalāyana,",
  "mn93:11.9": "ngọn lửa được nhóm lên, được làm cho hiện ra, bởi những người sinh trong dòng chiến sĩ, dòng bà-la-môn, hay dòng vua chúa, dùng thanh gỗ gây lửa trên bằng gỗ saka, gỗ sāl, gỗ salaḷa, gỗ chiên đàn, hay gỗ sen rừng, có phải chỉ ngọn lửa ấy mới có ngọn, có sắc đẹp, có sáng rực, và có thể dùng ngọn lửa ấy để làm việc cần lửa;",
  "mn93:11.10": "còn ngọn lửa được nhóm lên, được làm cho hiện ra, bởi những người sinh trong dòng Chiên-đà-la, dòng thợ săn, dòng đan tre, dòng làm xe, hay dòng hốt rác, dùng thanh gỗ gây lửa trên từ máng nước cho chó, máng ăn cho heo, máng giặt đồ, hay từ gỗ thầu dầu, thì ngọn lửa ấy không có ngọn, không đẹp, không sáng rực, và không thể dùng ngọn lửa ấy để làm việc cần lửa sao?”",
  "mn93:11.11": "“Không phải vậy, thưa ngài Gotama.",
  "mn93:11.12": "Dù là ngọn lửa được nhóm lên, được làm cho hiện ra, bởi những người sinh trong dòng chiến sĩ, dòng bà-la-môn, hay dòng vua chúa, dùng thanh gỗ gây lửa trên bằng gỗ saka, gỗ sāl, gỗ salaḷa, gỗ chiên đàn, hay gỗ sen rừng, thì ngọn lửa ấy có ngọn, đẹp, sáng rực, và có thể dùng ngọn lửa ấy để làm việc cần lửa;",
  "mn93:11.13": "và dù là ngọn lửa được nhóm lên, được làm cho hiện ra, bởi những người sinh trong dòng Chiên-đà-la, dòng thợ săn, dòng đan tre, dòng làm xe, hay dòng hốt rác, dùng thanh gỗ gây lửa trên từ máng nước cho chó, máng ăn cho heo, máng giặt đồ, hay từ gỗ thầu dầu, thì ngọn lửa ấy cũng có ngọn, đẹp, sáng rực, và có thể dùng ngọn lửa ấy để làm việc cần lửa.",
  "mn93:11.14": "Vì mọi ngọn lửa đều có ngọn, đẹp, sáng rực, và ngọn nào cũng có thể dùng để làm việc cần lửa.”",
  "mn93:11.15": "“Vậy thì ở đây, Assalāyana, bà-la-môn có sức mạnh gì, có chỗ dựa gì, mà lại nói rằng:",
  "mn93:11.16": "‘Chỉ bà-la-môn là dòng cao quý nhất, các dòng khác đều thấp kém;",
  "mn93:11.17": "chỉ bà-la-môn là dòng trắng sạch, các dòng khác đều đen;",
  "mn93:11.18": "chỉ bà-la-môn mới sạch, không phải người không phải bà-la-môn;",
  "mn93:11.19": "chỉ bà-la-môn mới là con của Phạm thiên, là con ruột sinh từ miệng Phạm thiên, do Phạm thiên sinh ra, do Phạm thiên tạo ra, là kẻ thừa hưởng của Phạm thiên’?”",
  "mn93:12.1": "“Dù ngài Gotama nói như vậy, nhưng ở đây các bà-la-môn vẫn nghĩ như vầy:",
  "mn93:12.2": "‘Chỉ bà-la-môn là dòng cao quý nhất, các dòng khác đều thấp kém …",
  "mn93:12.3": "là kẻ thừa hưởng của Phạm thiên’.”",
  "mn93:12.4": "“Ông nghĩ sao, Assalāyana,",
  "mn93:12.5": "ví như một chàng trai dòng chiến sĩ sống chung với một cô gái bà-la-môn, rồi từ sự sống chung ấy sinh ra một đứa con;",
  "mn93:12.6": "đứa con sinh ra từ chàng trai dòng chiến sĩ và cô gái bà-la-môn ấy, có thể giống mẹ và cũng có thể giống cha, có thể gọi là ‘chiến sĩ’, cũng có thể gọi là ‘bà-la-môn’, phải không?”",
  "mn93:12.7": "“Đứa con sinh ra từ chàng trai dòng chiến sĩ và cô gái bà-la-môn ấy, thưa ngài Gotama, có thể giống mẹ và cũng có thể giống cha, có thể gọi là ‘chiến sĩ’, cũng có thể gọi là ‘bà-la-môn’.”",
  "mn93:13.1": "“Ông nghĩ sao, Assalāyana,",
  "mn93:13.2": "ví như một chàng trai bà-la-môn sống chung với một cô gái dòng chiến sĩ, rồi từ sự sống chung ấy sinh ra một đứa con;",
  "mn93:13.3": "đứa con sinh ra từ chàng trai bà-la-môn và cô gái dòng chiến sĩ ấy, có thể giống mẹ và cũng có thể giống cha, có thể gọi là ‘chiến sĩ’, cũng có thể gọi là ‘bà-la-môn’, phải không?”",
  "mn93:13.4": "“Đứa con sinh ra từ chàng trai bà-la-môn và cô gái dòng chiến sĩ ấy, thưa ngài Gotama, có thể giống mẹ và cũng có thể giống cha, có thể gọi là ‘chiến sĩ’, cũng có thể gọi là ‘bà-la-môn’.”",
  "mn93:14.1": "“Ông nghĩ sao, Assalāyana,",
  "mn93:14.2": "ví như cho ngựa cái giao phối với lừa đực, rồi từ sự giao phối ấy sinh ra con la non;",
  "mn93:14.3": "Nếu con la đực sinh ra từ ngựa cái và lừa đực, thì nó có thể giống mẹ hay giống cha; vậy có nên gọi nó là ‘ngựa’ hay cũng nên gọi là ‘lừa’ không?",
  "mn93:14.4": "“Không đâu, thưa ngài Gotama, nó là con la.",
  "mn93:14.5": "Vì ở đây, thưa ngài Gotama, tôi thấy có chỗ khác nhau;",
  "mn93:14.6": "còn ở kia tôi không thấy có gì khác nhau cả.”",
  "mn93:15.1": "“Ông nghĩ sao, Assalāyana,",
  "mn93:15.2": "giả sử ở đây có hai cậu bà-la-môn là anh em cùng cha cùng mẹ, một người học thuộc kinh chú và đã làm lễ trao truyền, một người không học thuộc kinh chú và chưa làm lễ trao truyền.",
  "mn93:15.3": "Trong hai người ấy, các bà-la-môn sẽ mời ai ăn trước trong lễ cúng, hay bữa cơm nấu trong nồi, hay lễ lửa, hay khi có khách?”",
  "mn93:15.4": "“Thưa ngài Gotama, người thanh niên bà-la-môn nào học thuộc kinh chú và đã làm lễ trao truyền, thì các bà-la-môn sẽ mời người ấy ăn trước trong lễ cúng, hay bữa cơm nấu trong nồi, hay lễ lửa, hay khi có khách.",
  "mn93:15.5": "Vì cho người không học thuộc kinh chú và chưa làm lễ trao truyền thì đâu có mang lại kết quả lớn.”",
  "mn93:16.1": "“Ông nghĩ sao, Assalāyana,",
  "mn93:16.2": "giả sử ở đây có hai cậu bà-la-môn là anh em cùng cha cùng mẹ, một người học thuộc kinh chú và đã làm lễ trao truyền nhưng nết xấu, làm điều ác; một người không học thuộc kinh chú và chưa làm lễ trao truyền nhưng giữ nết tốt, sống tốt lành.",
  "mn93:16.3": "Trong hai người ấy, các bà-la-môn sẽ mời ai ăn trước trong lễ cúng, hay bữa cơm nấu trong nồi, hay lễ lửa, hay khi có khách?”",
  "mn93:16.4": "“Thưa ngài Gotama, người thanh niên bà-la-môn nào không học thuộc kinh chú, chưa làm lễ trao truyền, nhưng giữ nết tốt, sống tốt lành, thì các bà-la-môn sẽ mời người ấy ăn trước trong lễ cúng, hay bữa cơm nấu trong nồi, hay lễ lửa, hay khi có khách.",
  "mn93:16.5": "Vì cho người nết xấu, làm điều ác thì đâu có mang lại kết quả lớn.”",
  "mn93:17.1": "“Trước đó, này Assalāyana, ông vin vào dòng sinh ra;",
  "mn93:17.2": "khi không đứng vững ở dòng sinh ra, ông vin vào kinh chú;",
  "mn93:17.3": "khi không đứng vững ở kinh chú, ông vin vào lối ép xác;",
  "mn93:17.4": "khi không đứng vững ở lối ép xác, ông quay lại bám vào sự trong sạch của bốn hạng người, điều mà ta đã chỉ ra.”",
  "mn93:17.5": "Khi được nói vậy, chàng bà-la-môn Assalāyana ngồi im, bối rối, vai sụp xuống, cúi mặt, ngồi thừ ra, không đáp được.",
  "mn93:18.1": "Rồi Đức Thế Tôn, biết chàng bà-la-môn Assalāyana đang im lặng, bối rối, vai sụp xuống, cúi mặt, ngồi thừ ra, không đáp được, liền nói với chàng bà-la-môn Assalāyana như sau:",
  "mn93:18.2": "“Này Assalāyana, thuở xưa, khi bảy vị tiên bà-la-môn đang ở trong những túp lều lá nơi rừng vắng, đã khởi lên một cái thấy xấu ác như vầy:",
  "mn93:18.3": "‘Chỉ bà-la-môn mới là hạng cao nhất, các hạng khác đều thấp kém…",
  "mn93:18.4": "…",
  "mn93:18.5": "là con cháu của Phạm thiên.’",
  "mn93:18.6": "Này Assalāyana, vị tiên Asita Devala đã nghe rằng:",
  "mn93:18.7": "‘Nghe nói bảy vị tiên bà-la-môn đang ở trong những túp lều lá nơi rừng vắng đã khởi lên một cái thấy xấu ác như vầy:",
  "mn93:18.8": "chỉ bà-la-môn mới là hạng cao nhất …",
  "mn93:18.9": "là con cháu của Phạm thiên.’",
  "mn93:18.10": "Rồi này Assalāyana, vị tiên Asita Devala cắt tóc cạo râu, mặc y vải màu đỏ sẫm, mang dép lá cọ, cầm cây gậy bằng vàng ròng, hiện ra ở sân đất nện của bảy vị tiên bà-la-môn.",
  "mn93:18.11": "Rồi này Assalāyana, vị tiên Asita Devala đi qua đi lại ở sân đất nện của bảy vị tiên bà-la-môn và nói như vầy:",
  "mn93:18.12": "‘Nào, các vị bà-la-môn ẩn tu này đã đi đâu rồi?",
  "mn93:18.13": "Nào, các vị bà-la-môn ẩn tu này đã đi đâu rồi?’",
  "mn93:18.14": "Rồi, này Assalāyana, bảy vị bà-la-môn ẩn tu nghĩ rằng:",
  "mn93:18.15": "‘Ai là kẻ giống như cục bùn làng này, đi qua đi lại trên lối đi của bảy vị bà-la-môn ẩn tu mà nói rằng:",
  "mn93:18.16": "“Nào, các vị bà-la-môn ẩn tu này đã đi đâu rồi;",
  "mn93:18.17": "nào, các vị bà-la-môn ẩn tu này đã đi đâu rồi?”",
  "mn93:18.18": "Thôi, ta hãy rủa hắn.”",
  "mn93:18.19": "Rồi, này Assalāyana, bảy vị bà-la-môn ẩn tu rủa vị ẩn sĩ Asita Devala rằng:",
  "mn93:18.20": "‘Hãy thành tro đi, đồ hèn;",
  "mn93:18.21": "hãy thành tro đi, đồ hèn.’",
  "mn93:18.22": "Nhưng này Assalāyana, bảy vị bà-la-môn ẩn tu càng rủa vị ẩn sĩ Asita Devala bao nhiêu thì vị ẩn sĩ Asita Devala lại càng đẹp hơn, càng dễ nhìn hơn, càng sáng sủa hơn bấy nhiêu.",
  "mn93:18.23": "Rồi, này Assalāyana, bảy vị bà-la-môn ẩn tu nghĩ rằng:",
  "mn93:18.24": "‘Khổ công ép xác của chúng ta thật uổng rồi, đời sống giữ mình trong sạch thật không có kết quả.",
  "mn93:18.25": "Vì trước đây, người nào chúng ta rủa rằng—",
  "mn93:18.26": "“Hãy thành tro đi, đồ hèn;",
  "mn93:18.27": "hãy thành tro đi, đồ hèn” thì có kẻ đã thành tro thật.",
  "mn93:18.28": "Còn người này, chúng ta càng rủa bao nhiêu thì lại càng đẹp hơn, càng dễ nhìn hơn, càng sáng sủa hơn bấy nhiêu.’",
  "mn93:18.29": "‘Công ép xác của các vị không phải là uổng, đời sống giữ mình trong sạch không phải là không có kết quả.",
  "mn93:18.30": "Nào các vị, xin hãy bỏ đi điều bực tức trong lòng đối với tôi.’",
  "mn93:18.31": "‘Chúng tôi sẽ bỏ điều bực tức trong lòng ấy.",
  "mn93:18.32": "Nhưng ngài là ai?’",
  "mn93:18.33": "‘Các vị có từng nghe rằng—",
  "mn93:18.34": "Asita Devala là một vị ẩn sĩ chăng?’",
  "mn93:18.35": "‘Có, thưa ngài.’",
  "mn93:18.36": "‘Thưa các vị, chính tôi là người ấy.’",
  "mn93:18.37": "Rồi, này Assalāyana, bảy vị bà-la-môn ẩn tu tiến đến để chào vị ẩn sĩ Asita Devala.",
  "mn93:18.38": "Rồi, này Assalāyana, vị ẩn sĩ Asita Devala nói với bảy vị bà-la-môn ẩn tu rằng:",
  "mn93:18.39": "‘Thưa các vị, tôi có nghe rằng khi bảy vị bà-la-môn ẩn tu đang bàn bạc trong những chòi lá ở chốn rừng vắng, một cách thấy xấu ác như sau đã khởi lên:",
  "mn93:18.40": "“Chỉ bà-la-môn mới là hạng cao quý, hạng khác là thấp kém;",
  "mn93:18.41": "chỉ bà-la-môn mới là hạng trắng sạch, hạng khác là đen đúa;”",
  "mn93:18.42": "chỉ có bà-la-môn mới trong sạch, không phải người không phải bà-la-môn;",
  "mn93:18.43": "chỉ có bà-la-môn mới là con của Phạm thiên, là con ruột sinh ra từ miệng Phạm thiên, do Phạm thiên sinh ra, do Phạm thiên tạo ra, là người thừa hưởng từ Phạm thiên.’",
  "mn93:18.44": "‘Vâng, thưa ngài.’",
  "mn93:18.45": "‘Nhưng này các vị, các vị có biết rằng—",
  "mn93:18.46": "người mẹ đã sinh ra mình chỉ từng gần gũi một bà-la-môn thôi, không gần gũi người không phải bà-la-môn chăng?’",
  "mn93:18.47": "‘Thưa ngài, không biết điều ấy.’",
  "mn93:18.48": "‘Nhưng này các vị, các vị có biết rằng—",
  "mn93:18.49": "mẹ của người mẹ đã sinh ra mình, cho đến đời thứ bảy bên dòng mẹ, chỉ từng gần gũi một bà-la-môn thôi, không gần gũi người không phải bà-la-môn chăng?’",
  "mn93:18.50": "‘Thưa ngài, không biết điều ấy.’",
  "mn93:18.51": "‘Nhưng này các vị, các vị có biết rằng—",
  "mn93:18.52": "người cha đã sinh ra mình chỉ từng gần gũi một người đàn bà bà-la-môn thôi, không gần gũi người đàn bà không phải bà-la-môn chăng?’",
  "mn93:18.53": "‘Thưa ngài, không biết điều ấy.’",
  "mn93:18.54": "‘Nhưng này các vị, các vị có biết rằng—",
  "mn93:18.55": "cha của người cha đã sinh ra mình, cho đến đời thứ bảy bên dòng cha, chỉ từng gần gũi một người đàn bà bà-la-môn thôi, không gần gũi người đàn bà không phải bà-la-môn chăng?’",
  "mn93:18.56": "‘Thưa ngài, không biết điều ấy.’",
  "mn93:18.57": "‘Nhưng này các vị, các vị có biết rằng—",
  "mn93:18.58": "một bào thai vào trong bụng mẹ như thế nào chăng?’",
  "mn93:18.59": "‘Thưa ngài, chúng tôi biết—",
  "mn93:18.60": "một bào thai vào trong bụng mẹ như thế nào.",
  "mn93:18.61": "Ở đây, cha mẹ gần gũi nhau, người mẹ đúng kỳ có thể mang thai, và một hương linh có mặt; khi ba điều ấy cùng có mặt thì bào thai vào trong bụng mẹ.’",
  "mn93:18.62": "‘Nhưng này các vị, các vị có biết rằng—",
  "mn93:18.63": "vậy thì hương linh ấy là người dòng vua chúa, hay bà-la-môn, hay người buôn bán, hay người làm thuê chăng?’",
  "mn93:18.64": "‘Thưa ngài, chúng tôi không biết—",
  "mn93:18.65": "hương linh ấy là người dòng vua chúa, hay bà-la-môn, hay người buôn bán, hay người làm thuê.’",
  "mn93:18.66": "‘Nếu vậy, này các vị, các vị có biết—",
  "mn93:18.67": "các vị là ai chăng?’",
  "mn93:18.68": "‘Nếu vậy, thưa ngài, chúng tôi không biết—",
  "mn93:18.69": "chúng tôi là ai.’",
  "mn93:18.70": "Này Assalāyana, bảy vị tiên bà-la-môn xưa kia, khi bị vị tiên Asita Devala hỏi gạn, dồn sát, và vạch rõ về lời nói của chính mình về dòng giống, còn không đứng vững nổi;",
  "mn93:18.71": "huống gì nay chính ông, khi bị ta hỏi gạn, dồn sát, và vạch rõ về lời nói của chính mình về dòng giống, lại có thể đứng vững nổi, trong khi điều học từ thầy của ông còn chưa đầy đủ, ông chỉ mới nắm được như cái muôi múc canh.’",
  "mn93:19.1": "Khi được nói vậy, thanh niên Bà-la-môn Assalāyana thưa với Đức Thế Tôn như vầy:",
  "mn93:19.2": "“Thật hay, thưa ngài Gotama…",
  "mn93:19.3": "xin ngài Gotama ghi nhận con từ nay trọn đời là người tại gia nương tựa.”",
  "mn93:19.4": "Kinh Assalāyana chấm dứt. Bài thứ ba."
}
window.BILARA["mn93"]["vi"]["mn93:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
