window.BILARA = window.BILARA || {};
window.BILARA["mn95"] = window.BILARA["mn95"] || {};
window.BILARA["mn95"]["vi"] = {
  "mn95:0.1": "Trung Bộ Kinh 95",
  "mn95:0.2": "Kinh Caṅkī",
  "mn95:1.1": "Tôi nghe như vầy—",
  "mn95:1.2": "Một thời, Đức Thế Tôn đi du hành trong xứ Kosala cùng với đông đảo Tỳ Kheo, và đã đến một làng bà-la-môn của dân Kosala tên là Opāsāda.",
  "mn95:1.3": "Tại đó, Đức Thế Tôn ở phía bắc làng Opāsāda, trong khu rừng của chư thiên, rừng cây sala.",
  "mn95:2.1": "Lúc bấy giờ, bà-la-môn Caṅkī sống ở Opāsāda, một nơi sung túc, có cỏ, củi, nước và lúa thóc, là phần hưởng của vua, do vua Pasenadi nước Kosala ban cho, làm đất ban tặng cho bà-la-môn.",
  "mn95:3.1": "Các bà-la-môn và người chủ nhà ở Opāsāda nghe tin:",
  "mn95:3.2": "“Sa-môn Gotama, con của dòng Sakya, đã rời nhà sống đời không nhà từ dòng Sakya, đang đi du hành trong xứ Kosala cùng với đông đảo Tỳ Kheo, nay đã đến Opāsāda, và đang ở phía bắc làng Opāsāda, trong khu rừng của chư thiên, rừng cây sala.",
  "mn95:3.3": "Về ngài Gotama ấy, tiếng tốt đẹp này đã lan truyền lên rằng:",
  "mn95:3.4": "‘Đó là Đức Thế Tôn, bậc đáng được cúng dường, tự mình hiểu trọn vẹn, đủ đầy hiểu biết và nết sống, khéo đi đến, biết rõ đời, bậc không ai hơn trong việc dìu dắt người cần được rèn luyện, bậc thầy của chư thiên và loài người, bậc giác ngộ, Đức Thế Tôn.’",
  "mn95:3.5": "Ngài tự mình biết rõ, tự mình thấy rõ rồi nói ra cho người khác biết về thế gian này cùng với chư thiên, Ma vương, Phạm thiên, cùng với hạng sa-môn, bà-la-môn, cùng dân chúng gồm chư thiên và loài người.",
  "mn95:3.6": "Ngài chỉ bày lời dạy hay ở đầu, hay ở giữa, hay ở cuối, đủ nghĩa, đủ lời, và bày rõ nếp sống trong sạch trọn vẹn, tinh sạch.",
  "mn95:3.7": "Thật lành thay khi được gặp những bậc đáng được cúng dường như vậy.”",
  "mn95:4.1": "Rồi các bà-la-môn và người chủ nhà ở Opāsāda đi ra khỏi Opāsāda, tụ họp thành từng nhóm, cùng nhau đi về phía bắc đến khu rừng của chư thiên, rừng cây sala.",
  "mn95:5.1": "Lúc ấy, bà-la-môn Caṅkī đang ở trên lầu cao để nghỉ trưa.",
  "mn95:5.2": "Bà-la-môn Caṅkī thấy các bà-la-môn và người chủ nhà ở Opāsāda đi ra khỏi Opāsāda, tụ họp thành từng nhóm, cùng nhau đi về phía bắc đến khu rừng của chư thiên, rừng cây sala.",
  "mn95:5.3": "Thấy vậy, ông gọi người giữ việc trong nhà và hỏi:",
  "mn95:5.4": "“Này ông, vì sao các bà-la-môn và người chủ nhà ở Opāsāda đi ra khỏi Opāsāda, tụ họp thành từng nhóm, cùng nhau đi về phía bắc đến khu rừng của chư thiên, rừng cây sala?”",
  "mn95:6.1": "“Thưa ngài Caṅkī, có sa-môn Gotama, con của dòng Sakya, đã rời nhà sống đời không nhà từ dòng Sakya, đang đi du hành trong xứ Kosala cùng với đông đảo Tỳ Kheo, nay đã đến Opāsāda, và đang ở phía bắc làng Opāsāda, trong khu rừng của chư thiên, rừng cây sala.",
  "mn95:6.2": "Về ngài Gotama ấy, tiếng tốt đẹp này đã lan truyền lên rằng:",
  "mn95:6.3": "‘Đó là Đức Thế Tôn, bậc đáng được cúng dường, tự mình hiểu trọn vẹn, đủ đầy hiểu biết và nết sống, khéo đi đến, biết rõ đời, bậc không ai hơn trong việc dìu dắt người cần được rèn luyện, bậc thầy của chư thiên và loài người, bậc giác ngộ, Đức Thế Tôn.’",
  "mn95:6.4": "Họ đang đi để gặp ngài Gotama ấy.”",
  "mn95:6.5": "“Vậy thì, này ông, hãy đến chỗ các bà-la-môn và người chủ nhà ở Opāsāda; đến rồi hãy nói với họ như vầy:",
  "mn95:6.6": "‘Bà-la-môn Caṅkī nói thế này—",
  "mn95:6.7": "xin các vị hãy đợi, vì bà-la-môn Caṅkī cũng sẽ đến gặp sa-môn Gotama.’”",
  "mn95:6.8": "“Vâng, thưa ngài,” người ấy đáp lời bà-la-môn Caṅkī, rồi đi đến chỗ các bà-la-môn và người chủ nhà ở Opāsāda; đến rồi nói với họ rằng:",
  "mn95:6.9": "“Bà-la-môn Caṅkī nói thế này:",
  "mn95:6.10": "‘xin các vị hãy đợi, vì bà-la-môn Caṅkī cũng sẽ đến gặp sa-môn Gotama.’”",
  "mn95:7.1": "Lúc bấy giờ, có khoảng năm trăm bà-la-môn từ nhiều xứ khác nhau đang ở tại Opāsāda vì một việc nào đó.",
  "mn95:7.2": "Các bà-la-môn ấy nghe tin:",
  "mn95:7.3": "“Nghe nói bà-la-môn Caṅkī sẽ đi gặp sa-môn Gotama.”",
  "mn95:7.4": "Rồi các bà-la-môn ấy đi đến chỗ bà-la-môn Caṅkī; đến nơi, họ nói với bà-la-môn Caṅkī rằng:",
  "mn95:7.5": "“Có thật ngài Caṅkī sẽ đi gặp sa-môn Gotama chăng?”",
  "mn95:7.6": "“Đúng vậy, này các vị, tôi nghĩ thế này:",
  "mn95:7.7": "‘Tôi sẽ đi gặp sa-môn Gotama.’”",
  "mn95:8.1": "“Xin ngài Caṅkī đừng đi gặp sa-môn Gotama.",
  "mn95:8.2": "Ngài Caṅkī không nên đi gặp sa-môn Gotama;",
  "mn95:8.3": "chính sa-môn Gotama mới nên đến gặp ngài Caṅkī.",
  "mn95:8.4": "Vì ngài Caṅkī có dòng giống tốt cả bên mẹ lẫn bên cha, trong sạch về gốc gác đến bảy đời ông tổ, không ai chê trách hay chỉ trích về chuyện dòng giống.",
  "mn95:8.5": "Chỉ riêng điều này thôi, ngài Caṅkī cũng không nên đi gặp sa-môn Gotama;",
  "mn95:8.6": "chính sa-môn Gotama mới nên đến gặp ngài Caṅkī.",
  "mn95:8.7": "Vì ngài Caṅkī giàu có, nhiều của, hưởng nhiều thứ tốt đẹp …",
  "mn95:8.8": "vì ngài Caṅkī đã học thông ba bộ Vệ-đà, cùng với từ ngữ, nghi lễ, âm chữ và cách chia tách chữ, thêm truyện xưa là phần thứ năm; giỏi về từ ngữ, giỏi về văn phạm, thông suốt học thuyết thế gian và các dấu hiệu của bậc lớn …",
  "mn95:8.9": "vì ngài Caṅkī đẹp người, dễ nhìn, sáng sủa, có nước da rất đẹp, dung sắc như Phạm thiên, dáng vẻ cao quý, ai thấy cũng không chán …",
  "mn95:8.10": "vì ngài Caṅkī sống nết tốt, tuổi cao, đầy đủ nết tốt của người lớn tuổi …",
  "mn95:8.11": "vì ngài Caṅkī nói lời hay, nói khéo, lời nói rõ ràng, trôi chảy, dễ hiểu, bày tỏ được điều mình muốn nói …",
  "mn95:8.12": "vì ngài Caṅkī là thầy của nhiều thầy, dạy ba trăm thanh niên học thuộc các câu chú …",
  "mn95:8.13": "vì ngài Caṅkī được vua Pasenadi nước Kosala kính trọng, quý mến, xem trọng, tôn kính, lễ đãi …",
  "mn95:8.14": "vì ngài Caṅkī được bà-la-môn Pokkharasāti kính trọng, quý mến, xem trọng, tôn kính, lễ đãi …",
  "mn95:8.15": "vì ngài Caṅkī ở tại Opāsāda, một nơi đông đúc, có cỏ, củi, nước và lúa thóc, là phần hưởng của vua, do vua Pasenadi nước Kosala ban cho, là đất vua cấp cho bà-la-môn.",
  "mn95:8.16": "Chỉ riêng điều này thôi, ngài Caṅkī cũng không nên đi gặp sa-môn Gotama;",
  "mn95:8.17": "chính sa-môn Gotama mới nên đến gặp ngài Caṅkī.”",
  "mn95:9.1": "Khi được nói vậy, bà-la-môn Caṅkī nói với các bà-la-môn ấy rằng:",
  "mn95:9.2": "“Vậy thì, này các vị, hãy nghe tôi nữa, vì sao chính chúng ta mới nên đi gặp sa-môn Gotama ấy;",
  "mn95:9.3": "còn ngài Gotama ấy không nên đến gặp chúng ta.",
  "mn95:9.4": "Vì sa-môn Gotama có dòng giống tốt cả bên mẹ lẫn bên cha, trong sạch về gốc gác đến bảy đời ông tổ, không ai chê trách hay chỉ trích về chuyện dòng giống.",
  "mn95:9.5": "Chỉ riêng điều này thôi, ngài Gotama ấy cũng không nên đến gặp chúng ta;",
  "mn95:9.6": "chính chúng ta mới nên đi gặp ngài Gotama ấy.",
  "mn95:9.7": "Vì sa-môn Gotama đã bỏ lại nhiều vàng bạc mà đi ra sống không nhà, bỏ cả của cải dưới đất lẫn của cải cất giữ trên cao …",
  "mn95:9.8": "Vì sa-môn Gotama khi còn rất trẻ, đang ở tuổi thanh xuân, tóc đen mượt, đầy đủ vẻ đẹp của tuổi trẻ, ngay trong tuổi đầu xanh đã rời nhà, đi ra sống không nhà …",
  "mn95:9.9": "Này ngài, sa môn Gotama đã cạo bỏ tóc râu, khoác áo nhuộm màu đất, rời đời sống tại gia để sống không nhà, dù cha mẹ không bằng lòng, mặt đẫm nước mắt, đang khóc than …",
  "mn95:9.10": "Này ngài, sa môn Gotama đẹp người, dễ nhìn, khiến người ta sinh lòng mến, có nước da rất đẹp, dung sắc cao quý, thân tướng sáng ngời, nhìn không biết chán …",
  "mn95:9.11": "Này ngài, sa môn Gotama giữ nết tốt, có nết tốt của bậc cao quý, có nết tốt khéo lành, đầy đủ nết tốt khéo lành …",
  "mn95:9.12": "Này ngài, sa môn Gotama nói lời tốt đẹp, nói năng khéo léo, lời nói nhã nhặn, rõ ràng, trôi chảy, dễ hiểu, làm sáng tỏ điều có ích …",
  "mn95:9.13": "Này ngài, sa môn Gotama là thầy của nhiều thầy …",
  "mn95:9.14": "Này ngài, sa môn Gotama đã dứt lòng ham muốn dục lạc, không còn bồng bột …",
  "mn95:9.15": "Này ngài, sa môn Gotama nói về việc làm, nói về sự tạo tác, đặt việc không làm điều ác lên trước cho loài người sống theo nếp sống trong sạch …",
  "mn95:9.16": "Này ngài, sa môn Gotama xuất gia từ dòng họ cao, từ một dòng Sát Đế Lỵ không pha tạp …",
  "mn95:9.17": "Này ngài, sa môn Gotama xuất gia từ một gia đình giàu có, nhiều của cải, nhiều tài sản …",
  "mn95:9.18": "Này ngài, người ta từ xứ khác, từ miền khác đến để hỏi sa môn Gotama …",
  "mn95:9.19": "Này ngài, nhiều ngàn vị trời đã tìm đến nương tựa nơi sa môn Gotama bằng cả mạng sống …",
  "mn95:9.20": "Này ngài, tiếng tốt đẹp này đã vang lên về sa môn Gotama như sau:",
  "mn95:9.21": "‘Đức Thế Tôn là bậc đáng được cúng dường, tự mình hiểu trọn vẹn không nhờ ai chỉ dạy, đầy đủ hiểu biết và nết sống, đã đi đến chỗ tốt lành, hiểu rõ đời, là người dẫn dắt không ai hơn được đối với những người cần được rèn luyện, là bậc thầy của chư thiên và loài người, là bậc giác ngộ, là Đức Thế Tôn’ …",
  "mn95:9.22": "Này ngài, sa môn Gotama có đủ ba mươi hai tướng lớn của bậc vĩ nhân …",
  "mn95:9.23": "Này ngài, vua nước Magadha là Seniya Bimbisāra cùng con và vợ đã đem cả mạng sống nương tựa nơi sa môn Gotama …",
  "mn95:9.24": "Này ngài, vua Pasenadi xứ Kosala cùng con và vợ đã đem cả mạng sống nương tựa nơi sa môn Gotama …",
  "mn95:9.25": "Này ngài, bà la môn Pokkharasāti cùng con và vợ đã đem cả mạng sống nương tựa nơi sa môn Gotama …",
  "mn95:9.26": "Này ngài, sa môn Gotama đã đến Opāsāda và đang ở tại Opāsāda, phía bắc Opāsāda, trong rừng của chư thiên, rừng cây sala.",
  "mn95:9.27": "Những sa môn hay bà la môn nào đến vùng làng xóm của chúng ta thì họ là khách của chúng ta.",
  "mn95:9.28": "Mà khách thì chúng ta phải tiếp đãi, phải kính trọng, phải quý mến, phải tôn kính.",
  "mn95:9.29": "Sa môn Gotama đã đến Opāsāda và đang ở tại Opāsāda, phía bắc Opāsāda, trong rừng của chư thiên, rừng cây sala; sa môn Gotama là khách của chúng ta.",
  "mn95:9.30": "Mà khách thì chúng ta phải tiếp đãi, phải kính trọng, phải quý mến, phải tôn kính.",
  "mn95:9.31": "Chỉ riêng điểm này thôi cũng đủ để ngài Gotama không nên đến gặp chúng ta;",
  "mn95:9.32": "trái lại, chính chúng ta mới nên đến gặp ngài Gotama.",
  "mn95:9.33": "Này ngài, tôi chỉ học thuộc được chừng ấy lời khen về ngài Gotama, nhưng ngài Gotama không chỉ có chừng ấy điều đáng khen;",
  "mn95:9.34": "vì ngài Gotama có những điều đáng khen không sao kể xiết.",
  "mn95:9.35": "Chỉ cần có đủ một trong từng điểm ấy thôi, ngài Gotama cũng không nên đến gặp chúng ta;",
  "mn95:9.36": "trái lại, chính chúng ta mới nên đến gặp ngài Gotama.”",
  "mn95:9.37": "“Vậy thì, này các ngài, tất cả chúng ta hãy cùng đi gặp sa môn Gotama.”",
  "mn95:10.1": "Bấy giờ bà la môn Caṅkī cùng với một nhóm đông bà la môn đi đến chỗ Đức Thế Tôn; đến nơi, ông chào hỏi thân tình với Đức Thế Tôn.",
  "mn95:10.2": "Sau khi nói chuyện chào hỏi thân tình và nhắc lại những điều đáng nhớ, ông ngồi xuống một bên.",
  "mn95:11.1": "Lúc ấy, Đức Thế Tôn đang ngồi, sau khi nói qua lại đôi chút với các bà-la-môn lớn tuổi lớn tuổi về những điều đáng nhớ.",
  "mn95:11.2": "Khi ấy có một thanh niên tên là Kāpaṭika, đầu mới cạo, chừng mười sáu tuổi, thuộc dòng bà-la-môn, đã học thông ba bộ Vệ-đà cùng với từ ngữ, nghi lễ, âm vần, chuyện xưa là phần thứ năm, giỏi về từ ngữ, giỏi về ngữ nghĩa, thông suốt học thuyết thế gian và các dấu hiệu của bậc lớn. Cậu đang ngồi trong hội chúng ấy.",
  "mn95:11.3": "Trong khi các bà-la-môn lớn tuổi đang bàn luận với Đức Thế Tôn, cậu cứ chen lời vào giữa chừng.",
  "mn95:11.4": "Bấy giờ, Đức Thế Tôn ngăn thanh niên Kāpaṭika lại:",
  "mn95:11.5": "“Này ngài Bhāradvāja, chớ chen lời vào giữa khi các bà-la-môn lớn tuổi đang bàn luận.",
  "mn95:11.6": "Hãy đợi đến khi câu chuyện kết thúc.”",
  "mn95:11.7": "Khi được nói vậy, bà-la-môn Caṅkī thưa với Đức Thế Tôn:",
  "mn95:11.8": "“Xin ngài Gotama đừng ngăn thanh niên Kāpaṭika.",
  "mn95:11.9": "Thanh niên Kāpaṭika là con nhà tốt, học nhiều, khôn ngoan, nói năng khéo, và có thể đối đáp với ngài Gotama về việc này.”",
  "mn95:12.1": "Bấy giờ, Đức Thế Tôn nghĩ rằng:",
  "mn95:12.2": "“Chắc hẳn thanh niên Kāpaṭika sẽ nói về lời dạy của người thông ba bộ Vệ-đà.",
  "mn95:12.3": "Vì các bà-la-môn đang đưa cậu ấy ra trước.”",
  "mn95:12.4": "Rồi thanh niên Kāpaṭika nghĩ rằng:",
  "mn95:12.5": "“Khi nào sa-môn Gotama hướng mắt về phía ta, khi ấy ta sẽ hỏi sa-môn Gotama một điều.”",
  "mn95:12.6": "Đức Thế Tôn biết được ý nghĩ trong lòng của thanh niên Kāpaṭika, nên hướng mắt về phía cậu.",
  "mn95:12.7": "Rồi thanh niên Kāpaṭika nghĩ rằng:",
  "mn95:12.8": "“Sa-môn Gotama đang để ý đến ta.",
  "mn95:12.9": "Vậy ta nên hỏi sa-môn Gotama một điều.”",
  "mn95:12.10": "Rồi thanh niên Kāpaṭika thưa với Đức Thế Tôn:",
  "mn95:12.11": "“Thưa ngài Gotama, về những lời tụng xưa của các bà-la-môn, được truyền nối từ người này sang người kia, được giữ gìn trong các tập sách, ở đó các bà-la-môn đi đến kết luận chắc chắn rằng:",
  "mn95:12.12": "‘Chỉ điều này là thật, còn điều khác đều rỗng không.’",
  "mn95:12.13": "Về việc ấy, ngài Gotama nói sao?”",
  "mn95:13.1": "“Này Bhāradvāja, có chăng dù chỉ một bà-la-môn nào nói rằng:",
  "mn95:13.2": "‘Tôi biết điều ấy, tôi thấy điều ấy.",
  "mn95:13.3": "Chỉ điều này là thật, còn điều khác đều rỗng không’?”",
  "mn95:13.4": "“Thưa ngài Gotama, không có.”",
  "mn95:13.5": "“Này Bhāradvāja, có chăng dù chỉ một thầy của các bà-la-môn, hay thầy của thầy, cho đến hàng thầy tổ đời thứ bảy, nói rằng:",
  "mn95:13.6": "‘Tôi biết điều ấy, tôi thấy điều ấy.",
  "mn95:13.7": "Chỉ điều này là thật, còn điều khác đều rỗng không’?”",
  "mn95:13.8": "“Không phải vậy đâu, thưa ngài Gotama.”",
  "mn95:13.9": "“Nhưng này Bhāradvāja, còn những vị ẩn sĩ xưa của các bà-la-môn, là người làm ra các bài tụng, truyền lại các bài tụng, mà nay các bà-la-môn vẫn hát theo, đọc theo, lặp lại lời đã nói, đọc lại lời đã đọc, như là Aṭṭhaka, Vāmaka, Vāmadeva, Vessāmitta, Yamataggi, Aṅgīrasa, Bhāradvāja, Vāseṭṭha, Kassapa, Bhagu,",
  "mn95:13.10": "các vị ấy có từng nói rằng:",
  "mn95:13.11": "‘Chúng tôi biết điều này, chúng tôi thấy điều này.",
  "mn95:13.12": "Chỉ đây mới là sự thật, ngoài ra đều rỗng không’ không?”",
  "mn95:13.13": "“Không phải vậy đâu, thưa ngài Gotama.”",
  "mn95:13.14": "“Vậy thì này Bhāradvāja, không có một bà-la-môn nào nói rằng:",
  "mn95:13.15": "‘Tôi biết điều này, tôi thấy điều này.",
  "mn95:13.16": "Chỉ đây mới là sự thật, ngoài ra đều rỗng không’;",
  "mn95:13.17": "không có một thầy nào của các bà-la-môn, cũng không có thầy của thầy, cho đến bảy đời thầy nối nhau, mà nói rằng:",
  "mn95:13.18": "‘Tôi biết điều này, tôi thấy điều này.",
  "mn95:13.19": "Chỉ đây mới là sự thật, ngoài ra đều rỗng không’;",
  "mn95:13.20": "ngay cả những vị ẩn sĩ xưa của các bà-la-môn, là người làm ra các bài tụng, truyền lại các bài tụng, mà nay các bà-la-môn vẫn hát theo, đọc theo, lặp lại lời đã nói, đọc lại lời đã đọc, như là Aṭṭhaka, Vāmaka, Vāmadeva, Vessāmitta, Yamataggi, Aṅgīrasa, Bhāradvāja, Vāseṭṭha, Kassapa, Bhagu, các vị ấy cũng không nói rằng:",
  "mn95:13.21": "‘Chúng tôi biết điều này, chúng tôi thấy điều này.",
  "mn95:13.22": "Chỉ đây mới là sự thật, ngoài ra đều rỗng không.’",
  "mn95:13.23": "Ví như này Bhāradvāja, một hàng người mù nắm áo nhau mà đi, người đầu không thấy, người giữa không thấy, người cuối cũng không thấy;",
  "mn95:13.24": "cũng vậy, này Bhāradvāja, ta cho rằng lời nói của các bà-la-môn giống như một hàng người mù: người đầu không thấy, người giữa không thấy, người cuối cũng không thấy.",
  "mn95:13.25": "Ông nghĩ sao, này Bhāradvāja,",
  "mn95:13.26": "nếu là như vậy, chẳng phải lòng tin của các bà-la-môn là không có gốc rễ sao?”",
  "mn95:14.1": "“Không phải ở đây các bà-la-môn chỉ nương vào lòng tin đâu, thưa ngài Gotama; ở đây các bà-la-môn còn nương vào điều được truyền lại nữa.”",
  "mn95:14.2": "“Trước đó chính ông đã nói đến lòng tin, này Bhāradvāja; còn bây giờ ông lại nói đến điều được truyền lại.",
  "mn95:14.3": "Này Bhāradvāja, có năm điều này, ngay trong đời này, có thể đưa đến hai ngả.",
  "mn95:14.4": "Năm điều ấy là gì?",
  "mn95:14.5": "Lòng tin, sự ưa thích, điều được truyền lại, suy xét theo dáng vẻ bên ngoài, và chấp nhận sau khi ngẫm theo cái thấy của mình—",
  "mn95:14.6": "này Bhāradvāja, đó là năm điều, ngay trong đời này, có thể đưa đến hai ngả.",
  "mn95:14.7": "Có khi một điều được tin rất chắc, nhưng lại rỗng không, trống không, sai sự thật;",
  "mn95:14.8": "cũng có khi một điều không được tin chắc, nhưng lại là thật, đúng, không khác đi.",
  "mn95:14.9": "Cũng có khi một điều được ưa thích lắm …",
  "mn95:14.10": "một điều được nghe truyền lại kỹ lắm …",
  "mn95:14.11": "một điều được suy xét rất kỹ lắm …",
  "mn95:14.12": "Dù có suy xét kỹ, điều ấy vẫn có thể rỗng không, trống không, sai dối;",
  "mn95:14.13": "và dù không suy xét kỹ, điều ấy vẫn có thể là thật, đúng, không khác đi.",
  "mn95:14.14": "Này Bhāradvāja, một người sáng suốt giữ gìn sự thật thì không nên vì việc này mà đi đến kết luận chắc nịch rằng:",
  "mn95:14.15": "‘Chỉ đây mới là thật, còn điều khác là sai.’",
  "mn95:15.1": "“Nhưng, thưa ngài Gotama, đến mức nào thì gọi là giữ gìn sự thật, đến mức nào thì gọi là giữ gìn sự thật?",
  "mn95:15.2": "Chúng tôi hỏi ngài Gotama về việc giữ gìn sự thật.”",
  "mn95:15.3": "“Này Bhāradvāja, nếu một người có lòng tin,",
  "mn95:15.4": "thì người ấy nói:",
  "mn95:15.5": "‘Tôi tin như vậy’; nói như thế là giữ gìn sự thật, nhưng chưa vì thế mà đi đến kết luận chắc nịch rằng:",
  "mn95:15.6": "‘Chỉ đây mới là thật, còn điều khác là sai.’",
  "mn95:15.7": "Này Bhāradvāja, nếu một người có sự ưa thích …",
  "mn95:15.8": "Này Bhāradvāja, nếu một người nghe truyền lại …",
  "mn95:15.9": "Này Bhāradvāja, nếu một người suy nghĩ theo dấu hiệu bề ngoài …",
  "mn95:15.10": "Này Bhāradvāja, nếu một người chấp nhận một cái nhìn sau khi suy xét,",
  "mn95:15.11": "thì người ấy nói:",
  "mn95:15.12": "‘Tôi chấp nhận cái nhìn này sau khi suy xét’; nói như thế là giữ gìn sự thật, nhưng chưa vì thế mà đi đến kết luận chắc nịch rằng:",
  "mn95:15.13": "‘Chỉ đây mới là thật, còn điều khác là sai.’",
  "mn95:15.14": "Này Bhāradvāja, đến mức ấy thì gọi là giữ gìn sự thật, đến mức ấy thì người ta giữ gìn sự thật, và đến mức ấy Ta nói là giữ gìn sự thật;",
  "mn95:15.15": "nhưng chưa phải là tự mình hiểu ra sự thật.”",
  "mn95:16.1": "“Thưa ngài Gotama, đến mức ấy thì gọi là giữ gìn sự thật, đến mức ấy thì người ta giữ gìn sự thật, và đến mức ấy chúng tôi thấy là giữ gìn sự thật.",
  "mn95:16.2": "Nhưng, thưa ngài Gotama, đến mức nào thì là tự mình hiểu ra sự thật, đến mức nào thì người ta hiểu ra sự thật?",
  "mn95:16.3": "Chúng tôi hỏi ngài Gotama về việc tự mình hiểu ra sự thật.”",
  "mn95:17.1": "“Này Bhāradvāja, ở đây một Tỳ Kheo sống nương gần một làng hay một thị trấn nào đó.",
  "mn95:17.2": "Rồi một người chủ nhà hay con của người chủ nhà đến gặp vị ấy và xem xét vị ấy ở ba mặt —",
  "mn95:17.3": "những điều dễ làm nảy lòng tham, những điều dễ làm nảy lòng ghét, những điều dễ làm nảy lòng mê mờ.",
  "mn95:17.4": "Vị đáng kính này có những điều dễ làm nảy lòng tham đến mức, khi tâm bị chúng chiếm lấy, vị ấy sẽ nói điều mình không biết là biết,",
  "mn95:17.5": "hay nói điều mình không thấy là thấy,",
  "mn95:17.6": "hay thúc đẩy người khác làm theo điều đó, khiến họ lâu dài bị hại và khổ đau chăng?",
  "mn95:17.7": "Khi xem xét như vậy, người ấy biết rằng:",
  "mn95:17.8": "‘Vị đáng kính này không có những điều dễ làm nảy lòng tham đến mức, khi tâm bị chúng chiếm lấy, vị ấy sẽ nói điều mình không biết là biết,’",
  "mn95:17.9": "‘biết’, hay không thấy mà nói:",
  "mn95:17.10": "‘tôi thấy’, hoặc khuyên người khác làm theo điều ấy, khiến họ lâu dài bị hại và khổ đau chăng?",
  "mn95:17.11": "Nhưng cách vị Tôn giả này làm bằng thân, cách vị ấy nói bằng lời, là như vậy đó, vì vị ấy không tham.",
  "mn95:17.12": "Còn điều vị Tôn giả này chỉ dạy thì sâu xa, khó thấy, khó hiểu, lặng yên, tốt đẹp, không thuộc chỗ suy lường suông, tinh tế, người sáng dạ mới cảm nhận được.",
  "mn95:17.13": "Điều được chỉ dạy như thế không thể được giảng khéo bởi người tham.’",
  "mn95:18.1": "Khi xem xét vị ấy và thấy vị ấy trong sạch đối với những điều đáng chê vì giận dữ, thì người ấy xét thêm nữa về những điều đáng chê vì si mê.",
  "mn95:18.2": "Có chăng nơi vị Tôn giả này những điều đáng chê như vậy, khiến khi tâm bị giận dữ chiếm lấy thì vị ấy có thể không biết mà nói:",
  "mn95:18.3": "‘biết’, hay không thấy mà nói:",
  "mn95:18.4": "‘tôi thấy’, hoặc khuyên người khác làm theo điều ấy, khiến họ lâu dài bị hại và khổ đau chăng?",
  "mn95:18.5": "Khi xem xét vị ấy, người ấy biết như sau:",
  "mn95:18.6": "‘Không có nơi vị Tôn giả này những điều đáng chê như vậy, khiến khi tâm bị giận dữ chiếm lấy thì vị ấy có thể không biết mà nói:",
  "mn95:18.7": "‘biết’, hay không thấy mà nói:",
  "mn95:18.8": "‘tôi thấy’, hoặc khuyên người khác làm theo điều ấy, khiến họ lâu dài bị hại và khổ đau.",
  "mn95:18.9": "Nhưng cách vị Tôn giả này làm bằng thân, cách vị ấy nói bằng lời, là như vậy đó, vì vị ấy không giận dữ.",
  "mn95:18.10": "Còn điều vị Tôn giả này chỉ dạy thì sâu xa, khó thấy, khó hiểu, lặng yên, tốt đẹp, không thuộc chỗ suy lường suông, tinh tế, người sáng dạ mới cảm nhận được.",
  "mn95:18.11": "Điều được chỉ dạy như thế không thể được giảng khéo bởi người giận dữ.’",
  "mn95:19.1": "Khi xem xét vị ấy và thấy vị ấy trong sạch đối với những điều đáng chê vì si mê, thì người ấy",
  "mn95:19.2": "xét xem nơi vị Tôn giả này có những điều đáng chê như vậy không, khiến khi tâm bị si mê chiếm lấy thì vị ấy có thể không biết mà nói:",
  "mn95:19.3": "‘biết’, hay không thấy mà nói:",
  "mn95:19.4": "‘tôi thấy’, hoặc khuyên người khác làm theo điều ấy, khiến họ lâu dài bị hại và khổ đau chăng?",
  "mn95:19.5": "Khi xem xét vị ấy, người ấy biết như sau:",
  "mn95:19.6": "‘Không có nơi vị Tôn giả này những điều đáng chê như vậy, khiến khi tâm bị si mê chiếm lấy thì vị ấy có thể không biết mà nói:",
  "mn95:19.7": "‘biết’, hay không thấy mà nói:",
  "mn95:19.8": "‘tôi thấy’, hoặc khuyên người khác làm theo điều ấy, khiến họ lâu dài bị hại và khổ đau.",
  "mn95:19.9": "Nhưng cách vị Tôn giả này làm bằng thân, cách vị ấy nói bằng lời, là như vậy đó, vì vị ấy không mê lầm.",
  "mn95:19.10": "Còn điều vị Tôn giả này chỉ dạy thì sâu xa, khó thấy, khó hiểu, lặng yên, tốt đẹp, không thuộc chỗ suy lường suông, tinh tế, người sáng dạ mới cảm nhận được.",
  "mn95:19.11": "Điều được chỉ dạy như thế không thể được giảng khéo bởi người mê lầm.’",
  "mn95:20.1": "Khi xem xét vị ấy và thấy vị ấy trong sạch đối với những điều đáng chê vì si mê,",
  "mn95:20.2": "thì người ấy đặt lòng tin nơi vị ấy. Có lòng tin rồi thì đến gần. Đến gần rồi thì ở bên học hỏi. Ở bên học hỏi rồi thì lắng tai nghe. Lắng tai nghe rồi thì nghe điều được chỉ dạy. Nghe rồi thì ghi nhớ. Ghi nhớ những điều đã nghe rồi thì xem xét ý nghĩa. Khi xem xét ý nghĩa, những điều ấy được chấp nhận sau khi suy ngẫm. Khi đã chấp nhận sau khi suy ngẫm, lòng muốn làm phát sinh. Có lòng muốn làm rồi thì gắng sức. Gắng sức rồi thì cân nhắc. Cân nhắc rồi thì dốc sức. Khi đã dốc sức, người ấy tự mình làm cho sự thật cao nhất hiện rõ, và bằng sự hiểu rõ, người ấy thấy thấu điều ấy.",
  "mn95:20.3": "Đến mức ấy, này Bhāradvāja, là có sự hiểu ra sự thật; đến mức ấy là hiểu được sự thật; và đến mức ấy chúng tôi nói là sự hiểu ra sự thật.",
  "mn95:20.4": "nhưng đến mức ấy vẫn chưa đạt tới sự thật.”",
  "mn95:21.1": "“Đến mức ấy, thưa ngài Gotama, là có hiểu ra sự thật, đến mức ấy là hiểu thấu sự thật, và đến mức ấy chúng tôi thấy là có sự hiểu ra sự thật.",
  "mn95:21.2": "Nhưng, thưa ngài Gotama, đến mức nào thì đạt tới sự thật, đến mức nào thì chạm tới sự thật?",
  "mn95:21.3": "Chúng tôi hỏi ngài Gotama về việc đạt tới sự thật.”",
  "mn95:21.4": "“Này Bhāradvāja, chính do thường làm, nuôi lớn, và làm cho nhiều lên những điều ấy mà đạt tới sự thật.",
  "mn95:21.5": "Này Bhāradvāja, đến mức ấy là đạt tới sự thật, đến mức ấy là chạm tới sự thật, và đến mức ấy ta nói rõ về việc đạt tới sự thật.”",
  "mn95:22.1": "“Đến mức ấy, thưa ngài Gotama, là đạt tới sự thật, đến mức ấy là chạm tới sự thật, và đến mức ấy chúng tôi thấy là có việc đạt tới sự thật.",
  "mn95:22.2": "Nhưng, thưa ngài Gotama, đối với việc đạt tới sự thật, điều nào giúp ích nhiều nhất?",
  "mn95:22.3": "Chúng tôi hỏi ngài Gotama về điều giúp ích nhiều nhất cho việc đạt tới sự thật.”",
  "mn95:22.4": "“Này Bhāradvāja, đối với việc đạt tới sự thật, sự gắng sức giúp ích nhiều nhất.",
  "mn95:22.5": "Nếu không gắng sức thì không thể chạm tới sự thật này.",
  "mn95:22.6": "Chính vì gắng sức nên mới chạm tới sự thật.",
  "mn95:22.7": "Vì vậy, đối với việc đạt tới sự thật, sự gắng sức giúp ích nhiều nhất.”",
  "mn95:23.1": "“Nhưng, thưa ngài Gotama, đối với sự gắng sức, điều nào giúp ích nhiều nhất?",
  "mn95:23.2": "Chúng tôi hỏi ngài Gotama về điều giúp ích nhiều nhất cho sự gắng sức.”",
  "mn95:23.3": "“Này Bhāradvāja, đối với sự gắng sức, sự cân nhắc giúp ích nhiều nhất.",
  "mn95:23.4": "Nếu không cân nhắc thì không thể gắng sức.",
  "mn95:23.5": "Chính vì cân nhắc nên mới gắng sức.",
  "mn95:23.6": "Vì vậy, đối với sự gắng sức, sự cân nhắc giúp ích nhiều nhất.”",
  "mn95:24.1": "“Nhưng, thưa ngài Gotama, đối với sự cân nhắc, điều nào giúp ích nhiều nhất?",
  "mn95:24.2": "Chúng tôi hỏi ngài Gotama về điều giúp ích nhiều nhất cho sự cân nhắc.”",
  "mn95:24.3": "“Này Bhāradvāja, đối với sự cân nhắc, sự cố gắng giúp ích nhiều nhất.",
  "mn95:24.4": "Nếu không cố gắng thì không thể cân nhắc.",
  "mn95:24.5": "Chính vì cố gắng nên mới cân nhắc.",
  "mn95:24.6": "Vì vậy, đối với sự cân nhắc, sự cố gắng giúp ích nhiều nhất.”",
  "mn95:25.1": "“Nhưng, thưa ngài Gotama, đối với sự cố gắng, điều nào giúp ích nhiều nhất?",
  "mn95:25.2": "Chúng tôi hỏi ngài Gotama về điều giúp ích nhiều nhất cho sự cố gắng.”",
  "mn95:25.3": "“Này Bhāradvāja, đối với sự cố gắng, lòng muốn làm giúp ích nhiều nhất.",
  "mn95:25.4": "Nếu lòng muốn làm không khởi lên thì không thể cố gắng.",
  "mn95:25.5": "Chính vì lòng muốn làm khởi lên nên mới cố gắng.”",
  "mn95:25.6": "Vì vậy, lòng gắng sức rất giúp cho ý muốn ấy.”",
  "mn95:26.1": "“Nhưng, thưa ngài Gotama, điều gì rất giúp cho ý muốn?",
  "mn95:26.2": "Chúng tôi hỏi ngài Gotama về điều rất giúp cho ý muốn ấy.”",
  "mn95:26.3": "“Này Bhāradvāja, điều rất giúp cho ý muốn là sự chấp nhận sau khi suy xét lời dạy.",
  "mn95:26.4": "Nếu những lời dạy này không đáng để chấp nhận sau khi suy xét, thì ý muốn ấy sẽ không sinh ra.",
  "mn95:26.5": "Chính vì những lời dạy này đáng để chấp nhận sau khi suy xét, nên ý muốn sinh ra.",
  "mn95:26.6": "Vì vậy, sự chấp nhận sau khi suy xét lời dạy rất giúp cho ý muốn ấy.”",
  "mn95:27.1": "“Nhưng, thưa ngài Gotama, điều gì rất giúp cho sự chấp nhận sau khi suy xét lời dạy?",
  "mn95:27.2": "Chúng tôi hỏi ngài Gotama về điều rất giúp cho sự chấp nhận sau khi suy xét lời dạy ấy.”",
  "mn95:27.3": "“Này Bhāradvāja, điều rất giúp cho sự chấp nhận sau khi suy xét lời dạy là xem xét ý nghĩa.",
  "mn95:27.4": "Nếu người ta không xem xét ý nghĩa ấy, thì những lời dạy này sẽ không đáng để chấp nhận sau khi suy xét.",
  "mn95:27.5": "Chính vì người ta xem xét ý nghĩa ấy, nên những lời dạy này đáng để chấp nhận sau khi suy xét.",
  "mn95:27.6": "Vì vậy, xem xét ý nghĩa rất giúp cho sự chấp nhận sau khi suy xét lời dạy ấy.”",
  "mn95:28.1": "“Nhưng, thưa ngài Gotama, điều gì rất giúp cho việc xem xét ý nghĩa?",
  "mn95:28.2": "Chúng tôi hỏi ngài Gotama về điều rất giúp cho việc xem xét ý nghĩa ấy.”",
  "mn95:28.3": "“Này Bhāradvāja, điều rất giúp cho việc xem xét ý nghĩa là ghi nhớ lời dạy.",
  "mn95:28.4": "Nếu người ta không ghi nhớ lời dạy ấy, thì sẽ không xem xét ý nghĩa ấy.",
  "mn95:28.5": "Chính vì người ta ghi nhớ lời dạy ấy, nên người ta xem xét ý nghĩa ấy.",
  "mn95:28.6": "Vì vậy, ghi nhớ lời dạy rất giúp cho việc xem xét ý nghĩa ấy.”",
  "mn95:29.1": "“Nhưng, thưa ngài Gotama, điều gì rất giúp cho việc ghi nhớ lời dạy?",
  "mn95:29.2": "Chúng tôi hỏi ngài Gotama về điều rất giúp cho việc ghi nhớ lời dạy ấy.”",
  "mn95:29.3": "“Này Bhāradvāja, điều rất giúp cho việc ghi nhớ lời dạy là nghe lời dạy.",
  "mn95:29.4": "Nếu người ta không nghe lời dạy ấy, thì sẽ không ghi nhớ lời dạy ấy.",
  "mn95:29.5": "Chính vì người ta nghe lời dạy ấy, nên người ta ghi nhớ lời dạy ấy.",
  "mn95:29.6": "Vì vậy, nghe lời dạy rất giúp cho việc ghi nhớ lời dạy ấy.”",
  "mn95:30.1": "“Nhưng, thưa ngài Gotama, điều gì rất giúp cho việc nghe lời dạy?",
  "mn95:30.2": "Chúng tôi hỏi ngài Gotama về điều rất giúp cho việc nghe lời dạy ấy.”",
  "mn95:30.3": "“Này Bhāradvāja, điều rất giúp cho việc nghe lời dạy là chăm chú lắng tai.",
  "mn95:30.4": "Nếu người ta không lắng tai nghe, thì sẽ không nghe được lời dạy ấy.",
  "mn95:30.5": "Chính vì người ta lắng tai nghe, nên người ta nghe được lời dạy ấy.”",
  "mn95:30.6": "Vì vậy, để chăm chú lắng nghe, thì nghe lời dạy là điều giúp ích nhiều.",
  "mn95:31.1": "“Nhưng thưa ngài Gotama, điều gì giúp ích nhiều cho việc chăm chú lắng nghe?",
  "mn95:31.2": "Chúng tôi hỏi ngài Gotama về điều giúp ích nhiều cho việc chăm chú lắng nghe.”",
  "mn95:31.3": "“Này Bhāradvāja, đối với việc chăm chú lắng nghe, gần gũi học hỏi là điều giúp ích nhiều.",
  "mn95:31.4": "Nếu không gần gũi học hỏi, thì người ấy sẽ không lắng tai nghe.",
  "mn95:31.5": "Vì khi gần gũi học hỏi, thì người ấy lắng tai nghe.",
  "mn95:31.6": "Vì vậy, đối với việc chăm chú lắng nghe, gần gũi học hỏi là điều giúp ích nhiều.”",
  "mn95:32.1": "“Nhưng thưa ngài Gotama, điều gì giúp ích nhiều cho việc gần gũi học hỏi?",
  "mn95:32.2": "Chúng tôi hỏi ngài Gotama về điều giúp ích nhiều cho việc gần gũi học hỏi.”",
  "mn95:32.3": "“Này Bhāradvāja, đối với việc gần gũi học hỏi, đi đến gần là điều giúp ích nhiều.",
  "mn95:32.4": "Nếu không đi đến gần, thì người ấy sẽ không gần gũi học hỏi.",
  "mn95:32.5": "Vì khi đi đến gần, thì người ấy gần gũi học hỏi.",
  "mn95:32.6": "Vì vậy, đối với việc gần gũi học hỏi, đi đến gần là điều giúp ích nhiều.”",
  "mn95:33.1": "“Nhưng thưa ngài Gotama, điều gì giúp ích nhiều cho việc đi đến gần?",
  "mn95:33.2": "Chúng tôi hỏi ngài Gotama về điều giúp ích nhiều cho việc đi đến gần.”",
  "mn95:33.3": "“Này Bhāradvāja, đối với việc đi đến gần, lòng tin là điều giúp ích nhiều.",
  "mn95:33.4": "Nếu lòng tin không khởi lên, thì người ấy sẽ không đi đến gần.",
  "mn95:33.5": "Vì khi lòng tin khởi lên, thì người ấy đi đến gần.",
  "mn95:33.6": "Vì vậy, đối với việc đi đến gần, lòng tin là điều giúp ích nhiều.”",
  "mn95:34.1": "“Chúng tôi đã hỏi ngài Gotama về việc giữ gìn điều thật, và ngài Gotama đã trả lời về việc giữ gìn điều thật;",
  "mn95:34.2": "điều ấy làm chúng tôi ưa thích, vừa ý, nên chúng tôi vui lòng.",
  "mn95:34.3": "Chúng tôi đã hỏi ngài Gotama về việc hiểu ra điều thật, và ngài Gotama đã trả lời về việc hiểu ra điều thật;",
  "mn95:34.4": "điều ấy làm chúng tôi ưa thích, vừa ý, nên chúng tôi vui lòng.",
  "mn95:34.5": "Chúng tôi đã hỏi ngài Gotama về việc đạt tới điều thật, và ngài Gotama đã trả lời về việc đạt tới điều thật;",
  "mn95:34.6": "điều ấy làm chúng tôi ưa thích, vừa ý, nên chúng tôi vui lòng.",
  "mn95:34.7": "Chúng tôi đã hỏi ngài Gotama về điều gì giúp ích nhiều cho việc đạt tới điều thật, và ngài Gotama đã trả lời về điều gì giúp ích nhiều cho việc đạt tới điều thật;",
  "mn95:34.8": "điều ấy làm chúng tôi ưa thích, vừa ý, nên chúng tôi vui lòng.",
  "mn95:34.9": "Điều gì chúng tôi hỏi ngài Gotama, thì đúng điều ấy ngài Gotama đã trả lời;",
  "mn95:34.10": "điều ấy làm chúng tôi ưa thích, vừa ý, nên chúng tôi vui lòng.",
  "mn95:34.11": "Vì trước đây, thưa ngài Gotama, chúng tôi biết như vầy:",
  "mn95:34.12": "‘Mấy kẻ cạo đầu, sống đời bỏ nhà, hạng tôi đòi thấp kém, da đen, sinh từ chân của họ hàng, thì biết gì về lời dạy?’",
  "mn95:34.13": "Thật ra, ngài Gotama đã làm cho tôi khởi lên lòng mến người sống đời bỏ nhà, lòng tin người sống đời bỏ nhà, và lòng kính trọng người sống đời bỏ nhà.",
  "mn95:35.1": "Thật hay, thưa ngài Gotama…",
  "mn95:35.2": "Xin ngài Gotama ghi nhận tôi từ nay cho đến trọn đời là người tại gia nương tựa.",
  "mn95:35.3": "Kinh Caṅkī chấm dứt, bài thứ năm."
}
window.BILARA["mn95"]["vi"]["mn95:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
