window.BILARA = window.BILARA || {};
window.BILARA["mn96"] = window.BILARA["mn96"] || {};
window.BILARA["mn96"]["vi"] = {
  "mn96:0.1": "Trung Bộ Kinh 96",
  "mn96:0.2": "Kinh Esukārī",
  "mn96:1.1": "Tôi nghe như vầy—",
  "mn96:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, tại Kỳ Viên, khu vườn của ông Cấp Cô Độc.",
  "mn96:2.1": "Bấy giờ, bà la môn Esukārī đi đến chỗ Đức Thế Tôn; đến rồi, ông chào hỏi thân tình với Đức Thế Tôn.",
  "mn96:2.2": "Sau khi nói chuyện thân tình gợi nhớ đáng mến xong, ông ngồi xuống một bên. Ngồi xuống một bên rồi, bà la môn Esukārī thưa với Đức Thế Tôn như vầy:",
  "mn96:3.1": "“Thưa ngài Gotama, các bà la môn đặt ra bốn hạng người phải hầu hạ—",
  "mn96:3.2": "họ đặt ra việc hầu hạ bà la môn, việc hầu hạ người cai trị, việc hầu hạ người buôn bán, việc hầu hạ người làm thuê.",
  "mn96:3.3": "Trong đó, thưa ngài Gotama, các bà la môn đặt ra việc hầu hạ bà la môn như sau:",
  "mn96:3.4": "‘Bà la môn thì có thể hầu hạ bà la môn, người cai trị thì có thể hầu hạ bà la môn, người buôn bán thì có thể hầu hạ bà la môn, người làm thuê thì có thể hầu hạ bà la môn.’",
  "mn96:3.5": "Đó là điều các bà la môn đặt ra về việc hầu hạ bà la môn.",
  "mn96:3.6": "Trong đó, thưa ngài Gotama, các bà la môn đặt ra việc hầu hạ người cai trị như sau:",
  "mn96:3.7": "‘Người cai trị thì có thể hầu hạ người cai trị, người buôn bán thì có thể hầu hạ người cai trị, người làm thuê thì có thể hầu hạ người cai trị.’",
  "mn96:3.8": "Đó là điều các bà la môn đặt ra về việc hầu hạ người cai trị.",
  "mn96:3.9": "Trong đó, thưa ngài Gotama, các bà la môn đặt ra việc hầu hạ người buôn bán như sau:",
  "mn96:3.10": "‘Người buôn bán thì có thể hầu hạ người buôn bán, người làm thuê thì có thể hầu hạ người buôn bán.’",
  "mn96:3.11": "Đó là điều các bà la môn đặt ra về việc hầu hạ người buôn bán.",
  "mn96:3.12": "Trong đó, thưa ngài Gotama, các bà la môn đặt ra việc hầu hạ người làm thuê như sau:",
  "mn96:3.13": "‘Chỉ người làm thuê mới có thể hầu hạ người làm thuê.",
  "mn96:3.14": "Ngoài ra, ai còn hầu hạ người làm thuê nữa?’",
  "mn96:3.15": "Đó là điều các bà la môn đặt ra về việc hầu hạ người làm thuê.",
  "mn96:3.16": "Thưa ngài Gotama, các bà la môn đặt ra bốn hạng hầu hạ ấy.",
  "mn96:3.17": "Ở đây, ngài Gotama nói sao?”",
  "mn96:4.1": "“Này bà la môn, có phải cả đời đều cho phép các bà la môn đặt ra như vầy: ‘Hãy đặt ra bốn hạng hầu hạ này’ không?”",
  "mn96:4.2": "“Thưa không, ngài Gotama.”",
  "mn96:4.3": "“Này bà la môn, cũng như có một người nghèo, không có gì, không giàu. Dù người ấy không muốn, người ta vẫn treo vào cổ người ấy một miếng thịt và nói: ‘Này anh kia, đây là thịt cho anh ăn, và anh phải trả tiền nữa.’",
  "mn96:4.4": "Cũng vậy, này bà la môn, các bà la môn không được những sa môn và bà la môn kia chấp thuận, vậy mà vẫn đặt ra bốn hạng hầu hạ này.",
  "mn96:5.1": "Này bà la môn, ta không nói: ‘Phải hầu hạ tất cả’; ta cũng không nói: ‘Không nên hầu hạ ai cả.’",
  "mn96:5.2": "Vì này bà la môn, nếu khi hầu hạ ai mà do việc hầu hạ đó người ấy trở nên xấu hơn, không tốt hơn, thì ta không nói người ấy nên được hầu hạ.",
  "mn96:5.3": "Còn này bà la môn, nếu khi hầu hạ ai mà do việc hầu hạ đó người ấy trở nên tốt hơn, không xấu hơn, thì ta nói người ấy nên được hầu hạ.”",
  "mn96:6.1": "Này Bà-la-môn, nếu người ta hỏi cả một người Sát-đế-lỵ như vầy:",
  "mn96:6.2": "‘Nếu ông gần gũi, hầu hạ ai mà vì vậy ông thành ra xấu hơn, không tốt hơn; hay nếu ông gần gũi, hầu hạ ai mà vì vậy ông thành ra tốt hơn, không xấu hơn;",
  "mn96:6.3": "thì ở đây ông sẽ gần gũi ai?’ Này Bà-la-môn, người Sát-đế-lỵ ấy, nếu đáp đúng, sẽ đáp như vầy:",
  "mn96:6.4": "‘Nếu tôi gần gũi, hầu hạ ai mà vì vậy tôi thành ra xấu hơn, không tốt hơn, thì tôi sẽ không gần gũi người ấy. Còn nếu tôi gần gũi, hầu hạ ai mà vì vậy tôi thành ra tốt hơn, không xấu hơn, thì tôi sẽ gần gũi người ấy.’",
  "mn96:7.1": "Này Bà-la-môn, nếu người ta hỏi cả một người Bà-la-môn như vậy...",
  "mn96:7.2": "nếu người ta hỏi cả một người Vệ-xá như vậy...",
  "mn96:7.3": "nếu người ta hỏi cả một người Thủ-đà như vầy:",
  "mn96:7.4": "‘Nếu ông gần gũi, hầu hạ ai mà vì vậy ông thành ra xấu hơn, không tốt hơn; hay nếu ông gần gũi, hầu hạ ai mà vì vậy ông thành ra tốt hơn, không xấu hơn;",
  "mn96:7.5": "thì ở đây ông sẽ gần gũi ai?’ Này Bà-la-môn, người Thủ-đà ấy, nếu đáp đúng, sẽ đáp như vầy:",
  "mn96:7.6": "‘Nếu tôi gần gũi, hầu hạ ai mà vì vậy tôi thành ra xấu hơn, không tốt hơn, thì tôi sẽ không gần gũi người ấy. Còn nếu tôi gần gũi, hầu hạ ai mà vì vậy tôi thành ra tốt hơn, không xấu hơn, thì tôi sẽ gần gũi người ấy.’",
  "mn96:7.7": "Này Bà-la-môn, ta không nói rằng sinh trong dòng họ cao quý là hơn hẳn, cũng không nói rằng sinh trong dòng họ cao quý là xấu hơn.",
  "mn96:7.8": "Này Bà-la-môn, ta không nói rằng dáng vẻ đẹp đẽ là hơn hẳn, cũng không nói rằng dáng vẻ đẹp đẽ là xấu hơn.",
  "mn96:7.9": "Này Bà-la-môn, ta không nói rằng của cải nhiều là hơn hẳn, cũng không nói rằng của cải nhiều là xấu hơn.",
  "mn96:8.1": "Này Bà-la-môn, có người tuy sinh trong dòng họ cao quý, nhưng lại giết hại, lấy của không cho, ăn nằm sai trái, nói dối, nói hai lưỡi, nói lời thô ác, nói nhảm nhí, tham muốn, ôm lòng hại người, thấy sai.",
  "mn96:8.2": "Vì vậy, ta không nói rằng sinh trong dòng họ cao quý là hơn hẳn.",
  "mn96:8.3": "Này Bà-la-môn, cũng có người tuy sinh trong dòng họ cao quý, nhưng tránh xa giết hại, tránh xa lấy của không cho, tránh xa ăn nằm sai trái, tránh xa nói dối, tránh xa nói hai lưỡi, tránh xa lời thô ác, tránh xa nói nhảm nhí, không tham muốn, không ôm lòng hại người, thấy đúng.",
  "mn96:8.4": "Vì vậy, ta không nói rằng sinh trong dòng họ cao quý là xấu hơn.",
  "mn96:8.5": "Này Bà-la-môn, cũng có người tuy dáng vẻ đẹp đẽ...",
  "mn96:8.6": "...",
  "mn96:8.7": "Này Bà-la-môn, cũng có người tuy của cải nhiều, nhưng lại giết hại...",
  "mn96:8.8": "...",
  "mn96:8.9": "thấy sai.",
  "mn96:8.10": "Vì vậy, ta không nói rằng của cải nhiều là hơn hẳn.",
  "mn96:8.11": "Này Bà-la-môn, cũng có người tuy của cải nhiều, nhưng tránh xa giết hại ... thấy đúng.",
  "mn96:8.12": "Vì vậy, ta không nói rằng của cải nhiều là xấu hơn.",
  "mn96:9.1": "Này Bà-la-môn, ta không nói rằng phải gần gũi tất cả, cũng không nói rằng không nên gần gũi tất cả.",
  "mn96:9.2": "Này Bà-la-môn, nếu khi gần gũi ai mà vì vậy lòng tin lớn lên, nết tốt lớn lên, điều đã nghe học lớn lên, lòng rộng rãi lớn lên, sự hiểu rõ lớn lên, thì ta nói người ấy đáng để gần gũi.",
  "mn96:9.3": "Này Bà-la-môn, nếu khi gần gũi ai mà vì vậy lòng tin không lớn lên, nết tốt không lớn lên, điều đã nghe học không lớn lên, lòng rộng rãi không lớn lên, sự hiểu rõ không lớn lên, thì ta không nói người ấy đáng để gần gũi.”",
  "mn96:10.1": "Khi được nói vậy, Bà-la-môn Esukārī thưa với Đức Thế Tôn:",
  "mn96:10.2": "“Thưa ngài Gotama, các Bà-la-môn nêu ra bốn thứ của cải—",
  "mn96:10.3": "Họ nói ra việc sống hợp với mình cho bà-la-môn, họ nói ra việc sống hợp với mình cho người dòng vua chúa, họ nói ra việc sống hợp với mình cho người làm ăn buôn bán, họ nói ra việc sống hợp với mình cho người làm thuê hầu hạ.",
  "mn96:10.4": "Này ông Gotama, trong đó, bà-la-môn nói rằng việc sống hợp với bà-la-môn là đi xin ăn.",
  "mn96:10.5": "Nhưng nếu một bà-la-môn coi thường việc sống ấy thì người ấy làm điều không nên làm, như người chăn bò lấy thứ không được cho.",
  "mn96:10.6": "Này ông Gotama, đó là điều bà-la-môn nói ra là việc sống hợp với bà-la-môn.",
  "mn96:10.7": "Này ông Gotama, trong đó, bà-la-môn nói rằng việc sống hợp với người dòng vua chúa là cung tên.",
  "mn96:10.8": "Nhưng nếu một người dòng vua chúa coi thường việc sống ấy thì người ấy làm điều không nên làm, như người chăn bò lấy thứ không được cho.",
  "mn96:10.9": "Này ông Gotama, đó là điều bà-la-môn nói ra là việc sống hợp với người dòng vua chúa.",
  "mn96:10.10": "Này ông Gotama, trong đó, bà-la-môn nói rằng việc sống hợp với người làm ăn buôn bán là cày cấy và nuôi bò.",
  "mn96:10.11": "Nhưng nếu một người làm ăn buôn bán coi thường việc sống ấy thì người ấy làm điều không nên làm, như người chăn bò lấy thứ không được cho.",
  "mn96:10.12": "Này ông Gotama, đó là điều bà-la-môn nói ra là việc sống hợp với người làm ăn buôn bán.",
  "mn96:10.13": "Này ông Gotama, trong đó, bà-la-môn nói rằng việc sống hợp với người làm thuê hầu hạ là mang liềm và đòn gánh để kiếm ăn.",
  "mn96:10.14": "Nhưng nếu một người làm thuê hầu hạ coi thường việc sống ấy thì người ấy làm điều không nên làm, như người chăn bò lấy thứ không được cho.",
  "mn96:10.15": "Này ông Gotama, đó là điều bà-la-môn nói ra là việc sống hợp với người làm thuê hầu hạ.",
  "mn96:10.16": "Này ông Gotama, bà-la-môn nói ra bốn của cải này.",
  "mn96:10.17": "Còn ngài Gotama nói sao về việc này?",
  "mn96:11.1": "Này bà-la-môn, có phải cả đời đều cho phép bà-la-môn nói ra rằng: ‘Hãy nói ra bốn của cải này’ không?",
  "mn96:11.2": "Thưa không, ông Gotama.",
  "mn96:11.3": "Này bà-la-môn, cũng như một người nghèo, không có gì, không giàu có. Người ta lại treo trước mặt người ấy một miếng thịt, dù người ấy không muốn, rồi nói: ‘Này anh kia, anh phải ăn miếng thịt này và còn phải trả tiền nữa.’",
  "mn96:11.4": "Cũng vậy, này bà-la-môn, bà-la-môn không được các sa-môn và bà-la-môn kia bằng lòng, vậy mà vẫn nói ra bốn của cải này.",
  "mn96:12.1": "Này bà-la-môn, ta nói ra việc sống hợp với một người là nếp sống cao quý, vượt khỏi đời thường.",
  "mn96:12.2": "Còn khi nhớ lại dòng họ xưa truyền từ mẹ cha, thì ở đâu thân này sinh ra, người ta được gọi theo chỗ ấy.",
  "mn96:12.3": "Nếu thân này sinh ra trong dòng vua chúa thì được gọi là người dòng vua chúa.",
  "mn96:12.4": "Nếu thân này sinh ra trong dòng bà-la-môn thì được gọi là bà-la-môn.",
  "mn96:12.5": "Nếu thân này sinh ra trong dòng người làm ăn buôn bán thì được gọi là người làm ăn buôn bán.",
  "mn96:12.6": "Nếu thân này sinh ra trong dòng người làm thuê hầu hạ thì được gọi là người làm thuê hầu hạ.",
  "mn96:12.7": "Này bà-la-môn, cũng như lửa cháy nương vào thứ gì thì được gọi theo thứ ấy.",
  "mn96:12.8": "Nếu lửa cháy nương vào củi thì được gọi là lửa củi.",
  "mn96:12.9": "Nếu lửa cháy nương vào dăm gỗ thì được gọi là lửa dăm gỗ.",
  "mn96:12.10": "Nếu lửa cháy nương vào cỏ thì được gọi là lửa cỏ.",
  "mn96:12.11": "Nếu lửa cháy nương vào phân bò khô thì được gọi là lửa phân bò khô.",
  "mn96:12.12": "Cũng vậy, này Bà-la-môn, ta chỉ bày con đường vượt khỏi đời thường, bậc cao quý, để rèn luyện con người.",
  "mn96:12.13": "Nhưng khi người ấy nhớ lại dòng họ xưa do mẹ cha truyền lại, thì thân này sinh ra ở đâu, người ấy được gọi theo nơi ấy.",
  "mn96:12.14": "Nếu thân này sinh ra trong dòng vua chúa thì được gọi là người vua chúa;",
  "mn96:12.15": "nếu thân này sinh ra trong dòng Bà-la-môn thì được gọi là Bà-la-môn;",
  "mn96:12.16": "nếu thân này sinh ra trong dòng thương gia thì được gọi là người buôn bán;",
  "mn96:12.17": "nếu thân này sinh ra trong dòng người làm thuê thì được gọi là người làm thuê.",
  "mn96:13.1": "Này Bà-la-môn, dù là người từ dòng vua chúa, rời nhà sống không nhà, thì khi nương theo lời dạy và nếp sống do Như Lai chỉ bày, vị ấy tránh xa việc giết hại loài sống, tránh xa lấy của không cho, tránh xa sống không trong sạch, tránh xa nói dối, tránh xa nói hai lưỡi, tránh xa lời nói thô ác, tránh xa nói nhảm nhí, không tham muốn của người khác, lòng không ôm hại, thấy đúng, và khéo thành tựu nếp sống tốt lành đúng đắn này.",
  "mn96:13.2": "Này Bà-la-môn, dù là người từ dòng Bà-la-môn, rời nhà sống không nhà, thì khi nương theo lời dạy và nếp sống do Như Lai chỉ bày, vị ấy tránh xa việc giết hại loài sống … thấy đúng, và khéo thành tựu nếp sống tốt lành đúng đắn này.",
  "mn96:13.3": "Này Bà-la-môn, dù là người từ dòng thương gia, rời nhà sống không nhà, thì khi nương theo lời dạy và nếp sống do Như Lai chỉ bày, vị ấy tránh xa việc giết hại loài sống … thấy đúng, và khéo thành tựu nếp sống tốt lành đúng đắn này.",
  "mn96:13.4": "Này Bà-la-môn, dù là người từ dòng người làm thuê, rời nhà sống không nhà, thì khi nương theo lời dạy và nếp sống do Như Lai chỉ bày, vị ấy tránh xa việc giết hại loài sống … thấy đúng, và khéo thành tựu nếp sống tốt lành đúng đắn này.",
  "mn96:14.1": "Này Bà-la-môn, ông nghĩ sao,",
  "mn96:14.2": "chỉ riêng Bà-la-môn mới có thể ở trong trường hợp này nuôi lớn lòng thương yêu với tâm không thù hằn, không hại ai, còn người vua chúa, người buôn bán, hay người làm thuê thì không thể sao?",
  "mn96:14.3": "Thưa không phải vậy, ngài Gotama.",
  "mn96:14.4": "Vì người vua chúa cũng có thể ở trong trường hợp này nuôi lớn lòng thương yêu với tâm không thù hằn, không hại ai;",
  "mn96:14.5": "người Bà-la-môn cũng vậy, thưa ngài Gotama …",
  "mn96:14.6": "người buôn bán cũng vậy, thưa ngài Gotama …",
  "mn96:14.7": "người làm thuê cũng vậy, thưa ngài Gotama …",
  "mn96:14.8": "thưa ngài Gotama, cả bốn hạng người đều có thể ở trong trường hợp này nuôi lớn lòng thương yêu với tâm không thù hằn, không hại ai.",
  "mn96:14.9": "Cũng vậy, này Bà-la-môn, dù là người từ dòng vua chúa, rời nhà sống không nhà, thì khi nương theo lời dạy và nếp sống do Như Lai chỉ bày, vị ấy tránh xa việc giết hại loài sống … thấy đúng, và khéo thành tựu nếp sống tốt lành đúng đắn này.",
  "mn96:14.10": "Này Bà-la-môn, dù là người từ dòng Bà-la-môn …",
  "mn96:14.11": "này Bà-la-môn, dù là người từ dòng thương gia …",
  "mn96:14.12": "này Bà-la-môn, dù là người từ dòng người làm thuê, rời nhà sống không nhà, thì khi nương theo lời dạy và nếp sống do Như Lai chỉ bày, vị ấy tránh xa việc giết hại loài sống … thấy đúng, và khéo thành tựu nếp sống tốt lành đúng đắn này.",
  "mn96:15.1": "Này Bà-la-môn, ông nghĩ sao,",
  "mn96:15.2": "chỉ riêng Bà-la-môn mới có thể cầm đồ tắm đi ra sông để rửa sạch bụi bẩn, còn người vua chúa, người buôn bán, hay người làm thuê thì không thể sao?",
  "mn96:15.3": "Thưa không phải vậy, ngài Gotama.",
  "mn96:15.4": "Vì người vua chúa cũng có thể cầm đồ tắm đi ra sông để rửa sạch bụi bẩn;",
  "mn96:15.5": "người Bà-la-môn cũng vậy, thưa ngài Gotama …",
  "mn96:15.6": "người buôn bán cũng vậy, thưa ngài Gotama …",
  "mn96:15.7": "người làm thuê cũng vậy, thưa ngài Gotama …",
  "mn96:15.8": "thưa ngài Gotama, cả bốn hạng người đều có thể cầm đồ tắm đi ra sông để rửa sạch bụi bẩn.",
  "mn96:15.9": "Cũng vậy, này Bà-la-môn, nếu một người từ dòng Sát-đế-lỵ rời nhà, sống không nhà, và nương theo lời dạy và nếp sống do Như Lai chỉ bày, thì người ấy tránh xa việc giết hại loài sống … có cái thấy đúng, khéo đạt được con đường tốt lành này.",
  "mn96:15.10": "Nếu từ dòng Bà-la-môn cũng vậy, này Bà-la-môn …",
  "mn96:15.11": "Nếu từ dòng Vệ-xá cũng vậy, này Bà-la-môn …",
  "mn96:15.12": "Nếu từ dòng Thủ-đà cũng vậy, này Bà-la-môn, rời nhà, sống không nhà, và nương theo lời dạy và nếp sống do Như Lai chỉ bày, thì người ấy tránh xa việc giết hại loài sống … có cái thấy đúng, khéo đạt được con đường tốt lành này.",
  "mn96:16.1": "Này Bà-la-môn, ông nghĩ sao,",
  "mn96:16.2": "ví như một vua Sát-đế-lỵ đã làm lễ quán đảnh, cho gọi đến một trăm người thuộc nhiều dòng khác nhau,",
  "mn96:16.3": "và bảo: ‘Mời những vị nào ở đây sinh trong dòng Sát-đế-lỵ, dòng Bà-la-môn, dòng vua chúa, hãy lấy thanh gỗ trên bằng gỗ saka, gỗ sāl, gỗ salaḷa, gỗ chiên-đàn hay gỗ padumaka mà nhóm lửa lên, làm cho lửa hiện ra;",
  "mn96:16.4": "còn những vị nào ở đây sinh trong dòng Chiên-đà-la, dòng thợ săn, dòng đan tre, dòng làm xe, dòng Pukkusa, hãy lấy thanh gỗ trên bằng máng cho chó ăn, máng cho heo ăn, máng của thợ giặt, hay bằng gỗ thầu dầu mà nhóm lửa lên, làm cho lửa hiện ra.’",
  "mn96:16.5": "Này Bà-la-môn, ông nghĩ sao,",
  "mn96:16.6": "ngọn lửa được nhóm lên và hiện ra từ thanh gỗ trên bằng gỗ saka, gỗ sāl, gỗ salaḷa, gỗ chiên-đàn hay gỗ padumaka, do những người sinh trong dòng Sát-đế-lỵ, dòng Bà-la-môn, dòng vua chúa làm ra, có phải chỉ ngọn lửa ấy mới có ngọn, có sắc đẹp, có sáng rực, và chỉ với ngọn lửa ấy mới làm được việc cần làm với lửa;",
  "mn96:16.7": "còn ngọn lửa được nhóm lên và hiện ra từ thanh gỗ trên bằng máng cho chó ăn, máng cho heo ăn, máng của thợ giặt, hay bằng gỗ thầu dầu, do những người sinh trong dòng Chiên-đà-la, dòng thợ săn, dòng đan tre, dòng làm xe, dòng Pukkusa làm ra, thì ngọn lửa ấy không có ngọn, không đẹp sắc, không sáng rực, và không thể dùng ngọn lửa ấy để làm việc cần làm với lửa sao?’",
  "mn96:16.8": "‘Không phải vậy đâu, thưa ngài Gotama.",
  "mn96:16.9": "Dù là ngọn lửa được nhóm lên và hiện ra từ thanh gỗ trên bằng gỗ saka, gỗ sāl, gỗ salaḷa, gỗ chiên-đàn hay gỗ padumaka, do những người sinh trong dòng Sát-đế-lỵ, dòng Bà-la-môn, dòng vua chúa làm ra, thì ngọn lửa ấy có ngọn, có sắc đẹp, có sáng rực, và có thể dùng ngọn lửa ấy để làm việc cần làm với lửa;",
  "mn96:16.10": "hay là ngọn lửa được nhóm lên và hiện ra từ thanh gỗ trên bằng máng cho chó ăn, máng cho heo ăn, máng của thợ giặt, hay bằng gỗ thầu dầu, do những người sinh trong dòng Chiên-đà-la, dòng thợ săn, dòng đan tre, dòng làm xe, dòng Pukkusa làm ra, thì ngọn lửa ấy cũng có ngọn, có sắc đẹp, có sáng rực, và cũng có thể dùng ngọn lửa ấy để làm việc cần làm với lửa.",
  "mn96:16.11": "Vì mọi ngọn lửa đều có ngọn, có sắc đẹp, có sáng rực, và đều có thể dùng để làm việc cần làm với lửa.’",
  "mn96:16.12": "Cũng vậy, này Bà-la-môn, nếu một người từ dòng Sát-đế-lỵ rời nhà, sống không nhà, và nương theo lời dạy và nếp sống do Như Lai chỉ bày, thì người ấy tránh xa việc giết hại loài sống … có cái thấy đúng, khéo đạt được con đường tốt lành này.",
  "mn96:16.13": "Nếu từ dòng Bà-la-môn cũng vậy, này Bà-la-môn …",
  "mn96:16.14": "Nếu từ dòng Vệ-xá cũng vậy, này Bà-la-môn …",
  "mn96:16.15": "Nếu từ dòng Thủ-đà cũng vậy, này Bà-la-môn, rời nhà, sống không nhà, và nương theo lời dạy và nếp sống do Như Lai chỉ bày, thì người ấy tránh xa việc giết hại loài sống, tránh xa lấy của không cho, tránh xa sống không trong sạch, tránh xa nói dối, tránh xa nói hai lưỡi, tránh xa lời nói thô ác, tránh xa nói nhảm, không tham muốn, lòng không ác ý, có cái thấy đúng, khéo đạt được con đường tốt lành này.’",
  "mn96:17.1": "Khi được nói vậy, Bà-la-môn Esukārī thưa với Đức Thế Tôn:",
  "mn96:17.2": "‘Thật hay, thưa ngài Gotama, thật hay, thưa ngài Gotama …",
  "mn96:17.3": "xin ngài Gotama nhận con là người tại gia theo nương, từ nay cho đến trọn đời đã tìm đến nương tựa.’",
  "mn96:17.4": "Kinh Esukārī chấm dứt, bài thứ sáu."
}
window.BILARA["mn96"]["vi"]["mn96:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
