window.BILARA = window.BILARA || {};
window.BILARA["mn97"] = window.BILARA["mn97"] || {};
window.BILARA["mn97"]["vi"] = {
  "mn97:0.1": "Trung Bộ Kinh 97",
  "mn97:0.2": "Kinh Dhanañjāni",
  "mn97:1.1": "Tôi nghe như vầy—",
  "mn97:1.2": "Một thời, Đức Thế Tôn ở Rājagaha, trong rừng tre, tại chỗ cho sóc ăn.",
  "mn97:2.1": "Lúc ấy, ngài Sāriputta đang đi từ nơi này sang nơi khác ở miền núi phía nam, cùng với đông đảo Tỳ Kheo.",
  "mn97:2.2": "Bấy giờ, có một Tỳ Kheo an cư mùa mưa xong ở Rājagaha, đi đến miền núi phía nam, đến gặp ngài Sāriputta. Đến nơi, vị ấy chào hỏi thân tình với ngài Sāriputta.",
  "mn97:2.3": "Sau khi nói chuyện thân mật gợi nhớ nhau xong, vị ấy ngồi xuống một bên. Khi vị ấy ngồi xuống một bên, ngài Sāriputta nói với vị ấy:",
  "mn97:2.4": "“Này hiền giả, Đức Thế Tôn có mạnh khỏe, có sức không?”",
  "mn97:2.5": "“Này hiền giả, Đức Thế Tôn mạnh khỏe, có sức.”",
  "mn97:2.6": "“Này hiền giả, chúng Tỳ Kheo có mạnh khỏe, có sức không?”",
  "mn97:2.7": "“Này hiền giả, chúng Tỳ Kheo cũng mạnh khỏe, có sức.”",
  "mn97:2.8": "“Này hiền giả, ở đây, tại cổng Taṇḍulapāli, có một bà la môn tên là Dhanañjāni.",
  "mn97:2.9": "Này hiền giả, bà la môn Dhanañjāni có mạnh khỏe, có sức không?”",
  "mn97:2.10": "“Này hiền giả, bà la môn Dhanañjāni cũng mạnh khỏe, có sức.”",
  "mn97:2.11": "“Nhưng này hiền giả, bà la môn Dhanañjāni có sống cẩn thận không?”",
  "mn97:2.12": "“Này hiền giả, làm sao bà la môn Dhanañjāni có thể sống cẩn thận được?",
  "mn97:2.13": "Này hiền giả, bà la môn Dhanañjāni dựa vào vua mà bóc lột các bà la môn và người chủ nhà; lại dựa vào các bà la môn và người chủ nhà mà bóc lột vua.",
  "mn97:2.14": "Người vợ có lòng tin của ông ấy, được cưới từ một gia đình có lòng tin, nay đã qua đời;",
  "mn97:2.15": "ông ấy lại cưới một người vợ khác không có lòng tin, từ một gia đình không có lòng tin.”",
  "mn97:2.16": "“Thật là điều chúng ta nghe không hay, này hiền giả, thật là điều chúng ta nghe không hay, này hiền giả;",
  "mn97:2.17": "rằng bà la môn Dhanañjāni sống buông lung.",
  "mn97:2.18": "Biết đâu có lúc nào đó chúng ta sẽ gặp bà la môn Dhanañjāni, biết đâu sẽ có một cuộc nói chuyện nào đó.”",
  "mn97:3.1": "Rồi ngài Sāriputta ở miền núi phía nam cho đến khi thấy vừa ý, sau đó lên đường đi đến Rājagaha.",
  "mn97:3.2": "Đi dần từng chặng, ngài đến Rājagaha.",
  "mn97:3.3": "Tại đó, ngài Sāriputta ở Rājagaha, trong rừng tre, tại chỗ cho sóc ăn.",
  "mn97:4.1": "Rồi ngài Sāriputta vào buổi sáng, mặc y, cầm bát và áo choàng, đi vào Rājagaha để khất thực.",
  "mn97:4.2": "Lúc ấy, bà la môn Dhanañjāni đang ở ngoài thành, cho vắt sữa bò trong chuồng.",
  "mn97:4.3": "Rồi ngài Sāriputta đi khất thực trong Rājagaha xong, sau bữa ăn, khi đã đi khất thực trở về, liền đi đến chỗ bà la môn Dhanañjāni.",
  "mn97:4.4": "Bà la môn Dhanañjāni thấy ngài Sāriputta từ xa đang đi đến.",
  "mn97:4.5": "Thấy vậy, ông đi đến gặp ngài Sāriputta. Đến nơi, ông nói với ngài Sāriputta:",
  "mn97:4.6": "“Này ngài Xá Lợi Phất, đây có sữa, xin ngài uống đi, rồi sẽ tới giờ ăn.”",
  "mn97:4.7": "“Thôi, này Bà-la-môn.",
  "mn97:4.8": "Hôm nay ta đã xong việc ăn rồi.",
  "mn97:4.9": "Ta sẽ nghỉ ban ngày dưới một gốc cây kia.",
  "mn97:4.10": "Ông hãy đến đó.”",
  "mn97:4.11": "Bà-la-môn Dhanañjāni đáp lời Tôn giả Xá Lợi Phất: “Vâng, thưa ngài.”",
  "mn97:5.1": "Rồi sau bữa ăn, sau khi dùng xong bữa sáng, Bà-la-môn Dhanañjāni đi đến chỗ Tôn giả Xá Lợi Phất; đến nơi, ông nói chuyện thân tình với Tôn giả Xá Lợi Phất.",
  "mn97:5.2": "Sau khi nói với nhau những lời thân tình, gợi nhớ, rồi ông ngồi xuống một bên. Khi Bà-la-môn Dhanañjāni ngồi xuống một bên, Tôn giả Xá Lợi Phất nói với ông:",
  "mn97:5.3": "“Này Dhanañjāni, ông có sống không buông lung chứ?”",
  "mn97:5.4": "“Thưa ngài Xá Lợi Phất, làm sao chúng tôi có thể không buông lung được, khi chúng tôi phải nuôi cha mẹ, phải nuôi vợ con, phải nuôi người hầu và người làm, phải làm điều cần làm cho bạn bè và người giúp việc, phải làm điều cần làm cho bà con ruột thịt, phải làm điều cần làm cho khách đến nhà, phải làm điều cần làm cho người thân đã mất, phải làm điều cần làm cho các vị trời, phải làm điều cần làm cho vua, lại còn phải nuôi nấng, bồi bổ thân này nữa?”",
  "mn97:6.1": "“Ông nghĩ sao, này Dhanañjāni,",
  "mn97:6.2": "ở đây có người vì cha mẹ mà sống trái lẽ phải, làm điều lệch lạc; vì sống trái lẽ phải, làm điều lệch lạc ấy mà bị lính ngục kéo vào địa ngục.",
  "mn97:6.3": "Người ấy có thể nói: ‘Chính vì cha mẹ mà tôi đã sống trái lẽ phải, làm điều lệch lạc; xin lính ngục đừng kéo tôi đi vào địa ngục’, hay cha mẹ người ấy có thể nói: ‘Chính vì chúng tôi mà người này đã sống trái lẽ phải, làm điều lệch lạc; xin lính ngục đừng kéo người này đi vào địa ngục’ được chăng?”",
  "mn97:6.4": "“Không thể vậy đâu, thưa ngài Xá Lợi Phất.",
  "mn97:6.5": "Trái lại, dù người ấy có gào khóc, lính ngục vẫn quăng người ấy vào địa ngục.”",
  "mn97:7.1": "“Ông nghĩ sao, này Dhanañjāni,",
  "mn97:7.2": "ở đây có người vì vợ con mà sống trái lẽ phải, làm điều lệch lạc; vì sống trái lẽ phải, làm điều lệch lạc ấy mà bị lính ngục kéo vào địa ngục.",
  "mn97:7.3": "Người ấy có thể nói: ‘Chính vì vợ con mà tôi đã sống trái lẽ phải, làm điều lệch lạc; xin lính ngục đừng kéo tôi đi vào địa ngục’, hay vợ con người ấy có thể nói: ‘Chính vì chúng tôi mà người này đã sống trái lẽ phải, làm điều lệch lạc; xin lính ngục đừng kéo người này đi vào địa ngục’ được chăng?”",
  "mn97:7.4": "“Không thể vậy đâu, thưa ngài Xá Lợi Phất.",
  "mn97:7.5": "Trái lại, dù người ấy có gào khóc, lính ngục vẫn quăng người ấy vào địa ngục.”",
  "mn97:8.1": "“Ông nghĩ sao, này Dhanañjāni, ở đây có người vì người hầu, người làm và kẻ giúp việc mà sống trái lẽ phải, làm điều lệch lạc; vì sống trái lẽ phải, làm điều lệch lạc ấy mà bị lính ngục kéo vào địa ngục.",
  "mn97:8.2": "Người ấy có thể nói: ‘Chính vì người hầu, người làm và kẻ giúp việc mà tôi đã sống trái lẽ phải, làm điều lệch lạc; xin lính ngục đừng kéo tôi đi vào địa ngục’, hay những người hầu, người làm và kẻ giúp việc ấy có thể nói: ‘Chính vì chúng tôi mà người này đã sống trái lẽ phải, làm điều lệch lạc; xin lính ngục đừng kéo người này đi vào địa ngục’ được chăng?”",
  "mn97:8.3": "“Không thể vậy đâu, thưa ngài Xá Lợi Phất.",
  "mn97:8.4": "Trái lại, dù người ấy có gào khóc, lính ngục vẫn quăng người ấy vào địa ngục.”",
  "mn97:9.1": "“Ông nghĩ sao, này Dhanañjāni, ở đây có người vì bạn bè và người giúp việc mà sống trái lẽ phải, làm điều lệch lạc; vì sống trái lẽ phải, làm điều lệch lạc ấy mà bị lính ngục kéo vào địa ngục.",
  "mn97:9.2": "Người ấy có thể nói: ‘Chính vì bạn bè và người giúp việc mà tôi đã sống trái lẽ phải, làm điều lệch lạc; xin lính ngục đừng kéo tôi đi vào địa ngục’, hay bạn bè và người giúp việc ấy có thể nói: ‘Chính vì chúng tôi mà người này đã sống trái lẽ phải, làm điều lệch lạc; xin lính ngục đừng kéo người này đi vào địa ngục’ được chăng?”",
  "mn97:9.3": "“Không thể vậy đâu, thưa ngài Xá Lợi Phất.",
  "mn97:9.4": "Trái lại, dù người ấy có gào khóc, lính ngục vẫn quăng người ấy vào địa ngục.”",
  "mn97:10.1": "“Ông nghĩ sao, này Dhanañjāni, ở đây có người vì bà con ruột thịt mà sống trái lẽ phải, làm điều lệch lạc; vì sống trái lẽ phải, làm điều lệch lạc ấy mà bị lính ngục kéo vào địa ngục.",
  "mn97:10.2": "Người ấy có thể nói: ‘Chính vì bà con ruột thịt mà tôi đã sống trái lẽ phải, làm điều lệch lạc; xin lính ngục đừng kéo tôi đi vào địa ngục’, hay bà con ruột thịt ấy có thể nói: ‘Chính vì chúng tôi mà người này đã sống trái lẽ phải, làm điều lệch lạc; xin lính ngục đừng kéo người này đi vào địa ngục’ được chăng?”",
  "mn97:10.3": "“Không đâu, thưa ngài Xá Lợi Phất.",
  "mn97:10.4": "Rồi khi người ấy còn đang gào khóc, lính ngục sẽ quăng người ấy vào địa ngục.”",
  "mn97:11.1": "“Ông nghĩ sao, này Dhanañjāni, ở đây có người vì khách đến nhà mà sống trái lẽ phải, cư xử lệch lạc; vì sống trái lẽ phải, cư xử lệch lạc ấy, lính ngục lôi người ấy đến địa ngục.",
  "mn97:11.2": "Người ấy có thể nói được chăng: ‘Chính vì khách đến nhà mà tôi đã sống trái lẽ phải, cư xử lệch lạc; xin đừng lôi tôi vào địa ngục’? Hay những người khách ấy có thể nói được chăng: ‘Chính vì chúng tôi mà người này đã sống trái lẽ phải, cư xử lệch lạc; xin đừng lôi người này vào địa ngục’?”",
  "mn97:11.3": "“Không đâu, thưa ngài Xá Lợi Phất.",
  "mn97:11.4": "Rồi khi người ấy còn đang gào khóc, lính ngục sẽ quăng người ấy vào địa ngục.”",
  "mn97:12.1": "“Ông nghĩ sao, này Dhanañjāni, ở đây có người vì người thân đã mất mà sống trái lẽ phải, cư xử lệch lạc; vì sống trái lẽ phải, cư xử lệch lạc ấy, lính ngục lôi người ấy đến địa ngục.",
  "mn97:12.2": "Người ấy có thể nói được chăng: ‘Chính vì người thân đã mất mà tôi đã sống trái lẽ phải, cư xử lệch lạc; xin đừng lôi tôi vào địa ngục’? Hay những người thân đã mất ấy có thể nói được chăng: ‘Chính vì chúng tôi mà người này đã sống trái lẽ phải, cư xử lệch lạc; xin đừng lôi người này vào địa ngục’?”",
  "mn97:12.3": "“Không đâu, thưa ngài Xá Lợi Phất.",
  "mn97:12.4": "Rồi khi người ấy còn đang gào khóc, lính ngục sẽ quăng người ấy vào địa ngục.”",
  "mn97:13.1": "“Ông nghĩ sao, này Dhanañjāni, ở đây có người vì các vị trời mà sống trái lẽ phải, cư xử lệch lạc; vì sống trái lẽ phải, cư xử lệch lạc ấy, lính ngục lôi người ấy đến địa ngục.",
  "mn97:13.2": "Người ấy có thể nói được chăng: ‘Chính vì các vị trời mà tôi đã sống trái lẽ phải, cư xử lệch lạc; xin đừng lôi tôi vào địa ngục’? Hay các vị trời ấy có thể nói được chăng: ‘Chính vì chúng tôi mà người này đã sống trái lẽ phải, cư xử lệch lạc; xin đừng lôi người này vào địa ngục’?”",
  "mn97:13.3": "“Không đâu, thưa ngài Xá Lợi Phất.",
  "mn97:13.4": "Rồi khi người ấy còn đang gào khóc, lính ngục sẽ quăng người ấy vào địa ngục.”",
  "mn97:14.1": "“Ông nghĩ sao, này Dhanañjāni, ở đây có người vì vua mà sống trái lẽ phải, cư xử lệch lạc; vì sống trái lẽ phải, cư xử lệch lạc ấy, lính ngục lôi người ấy đến địa ngục.",
  "mn97:14.2": "Người ấy có thể nói được chăng: ‘Chính vì vua mà tôi đã sống trái lẽ phải, cư xử lệch lạc; xin đừng lôi tôi vào địa ngục’? Hay vua có thể nói được chăng: ‘Chính vì chúng tôi mà người này đã sống trái lẽ phải, cư xử lệch lạc; xin đừng lôi người này vào địa ngục’?”",
  "mn97:14.3": "“Không đâu, thưa ngài Xá Lợi Phất.",
  "mn97:14.4": "Rồi khi người ấy còn đang gào khóc, lính ngục sẽ quăng người ấy vào địa ngục.”",
  "mn97:15.1": "“Ông nghĩ sao, này Dhanañjāni, ở đây có người vì nuôi thân cho mập mạnh, cho lớn lên mà sống trái lẽ phải, cư xử lệch lạc; vì sống trái lẽ phải, cư xử lệch lạc ấy, lính ngục lôi người ấy đến địa ngục.",
  "mn97:15.2": "Người ấy có thể nói được chăng: ‘Chính vì nuôi thân cho mập mạnh, cho lớn lên mà tôi đã sống trái lẽ phải, cư xử lệch lạc; xin đừng lôi tôi vào địa ngục’? Hay người khác có thể nói được chăng: ‘Chính vì nuôi thân cho mập mạnh, cho lớn lên mà người này đã sống trái lẽ phải, cư xử lệch lạc; xin đừng lôi người này vào địa ngục’?”",
  "mn97:15.3": "“Không đâu, thưa ngài Xá Lợi Phất.",
  "mn97:15.4": "Rồi khi người ấy còn đang gào khóc, lính ngục sẽ quăng người ấy vào địa ngục.”",
  "mn97:16.1": "“Ông nghĩ sao, này Dhanañjāni, người vì cha mẹ mà sống trái lẽ phải, cư xử lệch lạc, và người vì cha mẹ mà sống đúng lẽ phải, cư xử ngay thẳng;",
  "mn97:16.2": "ai tốt hơn?”",
  "mn97:16.3": "“Thưa ngài Xá Lợi Phất, người vì cha mẹ mà sống trái lẽ phải, cư xử lệch lạc, thì không tốt hơn.",
  "mn97:16.4": "Còn người vì cha mẹ mà sống đúng lẽ phải, cư xử ngay thẳng, thì trong trường hợp này người ấy tốt hơn.",
  "mn97:16.5": "Thưa ngài Xá Lợi Phất, sống đúng lẽ phải, cư xử ngay thẳng tốt hơn sống trái lẽ phải, cư xử lệch lạc.”",
  "mn97:16.6": "“Này Dhanañjāni, có những việc làm đúng lẽ phải khác vì người khác mà làm, nhờ đó có thể nuôi cha mẹ, lại không làm việc xấu, và còn đi theo con đường lành.",
  "mn97:17.1": "Ông nghĩ sao, này Dhanañjāni, người vì vợ con mà sống trái lẽ phải, cư xử lệch lạc, và người vì vợ con mà sống đúng lẽ phải, cư xử ngay thẳng;",
  "mn97:17.2": "ai tốt hơn?”",
  "mn97:17.3": "“Này ông Sāriputta, nếu vì vợ con mà một người sống trái lẽ phải, sống lệch lạc, thì điều đó không tốt hơn;",
  "mn97:17.4": "còn nếu vì vợ con mà một người sống đúng lẽ phải, sống ngay thẳng, thì điều đó mới là tốt hơn ở đây.",
  "mn97:17.5": "Này ông Sāriputta, sống đúng lẽ phải, sống ngay thẳng, tốt hơn sống trái lẽ phải, sống lệch lạc.”",
  "mn97:17.6": "“Này Dhanañjāni, có những nghề làm ăn đúng lẽ phải vì những người khác, nhờ đó có thể nuôi vợ con, lại không làm việc xấu, và còn đi theo nẻo lành.",
  "mn97:18.1": "Ông nghĩ sao, này Dhanañjāni, người nào vì tôi tớ, người làm công và người giúp việc mà sống trái lẽ phải, sống lệch lạc, hay người nào vì tôi tớ, người làm công và người giúp việc mà sống đúng lẽ phải, sống ngay thẳng;",
  "mn97:18.2": "ai tốt hơn?”",
  "mn97:18.3": "“Này ông Sāriputta, nếu vì tôi tớ, người làm công và người giúp việc mà một người sống trái lẽ phải, sống lệch lạc, thì điều đó không tốt hơn;",
  "mn97:18.4": "còn nếu vì tôi tớ, người làm công và người giúp việc mà một người sống đúng lẽ phải, sống ngay thẳng, thì điều đó mới là tốt hơn ở đây.",
  "mn97:18.5": "Này ông Sāriputta, sống đúng lẽ phải, sống ngay thẳng, tốt hơn sống trái lẽ phải, sống lệch lạc.”",
  "mn97:18.6": "“Này Dhanañjāni, có những nghề làm ăn đúng lẽ phải vì những người khác, nhờ đó có thể nuôi tôi tớ, người làm công và người giúp việc, lại không làm việc xấu, và còn đi theo nẻo lành.",
  "mn97:19.1": "Ông nghĩ sao, này Dhanañjāni, người nào vì bạn bè và người giúp việc thân cận mà sống trái lẽ phải, sống lệch lạc, hay người nào vì bạn bè và người giúp việc thân cận mà sống đúng lẽ phải, sống ngay thẳng;",
  "mn97:19.2": "ai tốt hơn?”",
  "mn97:19.3": "“Này ông Sāriputta, nếu vì bạn bè và người giúp việc thân cận mà một người sống trái lẽ phải, sống lệch lạc, thì điều đó không tốt hơn;",
  "mn97:19.4": "còn nếu vì bạn bè và người giúp việc thân cận mà một người sống đúng lẽ phải, sống ngay thẳng, thì điều đó mới là tốt hơn ở đây.",
  "mn97:19.5": "Này ông Sāriputta, sống đúng lẽ phải, sống ngay thẳng, tốt hơn sống trái lẽ phải, sống lệch lạc.”",
  "mn97:19.6": "“Này Dhanañjāni, có những nghề làm ăn đúng lẽ phải vì những người khác, nhờ đó có thể lo cho bạn bè và người giúp việc thân cận, làm những việc cần làm cho họ, lại không làm việc xấu, và còn đi theo nẻo lành.",
  "mn97:20.1": "Ông nghĩ sao, này Dhanañjāni, người nào vì bà con ruột thịt mà sống trái lẽ phải, sống lệch lạc, hay người nào vì bà con ruột thịt mà sống đúng lẽ phải, sống ngay thẳng;",
  "mn97:20.2": "ai tốt hơn?”",
  "mn97:20.3": "“Này ông Sāriputta, nếu vì bà con ruột thịt mà một người sống trái lẽ phải, sống lệch lạc, thì điều đó không tốt hơn;",
  "mn97:20.4": "còn nếu vì bà con ruột thịt mà một người sống đúng lẽ phải, sống ngay thẳng, thì điều đó mới là tốt hơn ở đây.",
  "mn97:20.5": "Này ông Sāriputta, sống đúng lẽ phải, sống ngay thẳng, tốt hơn sống trái lẽ phải, sống lệch lạc.”",
  "mn97:20.6": "“Này Dhanañjāni, có những nghề làm ăn đúng lẽ phải vì những người khác, nhờ đó có thể lo cho bà con ruột thịt, làm những việc cần làm cho họ, lại không làm việc xấu, và còn đi theo nẻo lành.",
  "mn97:21.1": "Ông nghĩ sao, này Dhanañjāni, người nào vì khách đến nhà mà sống trái lẽ phải, sống lệch lạc, hay người nào vì khách đến nhà mà sống đúng lẽ phải, sống ngay thẳng;",
  "mn97:21.2": "ai tốt hơn?”",
  "mn97:21.3": "“Này ông Sāriputta, nếu vì khách đến nhà mà một người sống trái lẽ phải, sống lệch lạc, thì điều đó không tốt hơn;",
  "mn97:21.4": "còn nếu vì khách đến nhà mà một người sống đúng lẽ phải, sống ngay thẳng, thì điều đó mới là tốt hơn ở đây.",
  "mn97:21.5": "Này ông Sāriputta, sống đúng lẽ phải, sống ngay thẳng, tốt hơn sống trái lẽ phải, sống lệch lạc.”",
  "mn97:21.6": "“Này Dhanañjāni, có những nghề làm ăn đúng lẽ phải vì những người khác, nhờ đó có thể lo cho khách đến nhà, làm những việc cần làm cho họ, lại không làm việc xấu, và còn đi theo nẻo lành.",
  "mn97:22.1": "Ông nghĩ sao, này Dhanañjāni, người nào vì người thân đã mất mà sống trái lẽ phải, sống lệch lạc, hay người nào vì người thân đã mất mà sống đúng lẽ phải, sống ngay thẳng;",
  "mn97:22.2": "ai tốt hơn?”",
  "mn97:22.3": "“Này ngài Xá Lợi Phất, nếu vì những người thân đã mất mà sống sai lẽ phải, cư xử lệch lạc, thì điều đó không tốt;",
  "mn97:22.4": "còn nếu, này ngài Xá Lợi Phất, vì những người thân đã mất mà sống đúng lẽ phải, cư xử ngay thẳng, thì điều đó mới là tốt hơn ở đây.",
  "mn97:22.5": "Này ngài Xá Lợi Phất, sống đúng lẽ phải và cư xử ngay thẳng tốt hơn sống sai lẽ phải và cư xử lệch lạc.”",
  "mn97:22.6": "“Này Dhanañjāni, có những việc làm đúng lẽ phải vì người khác, nhờ đó có thể làm điều cần làm cho những người thân đã mất, mà không làm việc xấu, lại còn đi theo con đường lành.",
  "mn97:23.1": "Ông nghĩ sao, này Dhanañjāni, người nào vì chư thiên mà sống sai lẽ phải, cư xử lệch lạc, hay người nào vì chư thiên mà sống đúng lẽ phải, cư xử ngay thẳng;",
  "mn97:23.2": "người nào tốt hơn?”",
  "mn97:23.3": "“Này ngài Xá Lợi Phất, nếu vì chư thiên mà sống sai lẽ phải, cư xử lệch lạc, thì điều đó không tốt;",
  "mn97:23.4": "còn nếu, này ngài Xá Lợi Phất, vì chư thiên mà sống đúng lẽ phải, cư xử ngay thẳng, thì điều đó mới là tốt hơn ở đây.",
  "mn97:23.5": "Này ngài Xá Lợi Phất, sống đúng lẽ phải và cư xử ngay thẳng tốt hơn sống sai lẽ phải và cư xử lệch lạc.”",
  "mn97:23.6": "“Này Dhanañjāni, có những việc làm đúng lẽ phải vì người khác, nhờ đó có thể làm điều cần làm cho chư thiên, mà không làm việc xấu, lại còn đi theo con đường lành.",
  "mn97:24.1": "Ông nghĩ sao, này Dhanañjāni, người nào vì vua mà sống sai lẽ phải, cư xử lệch lạc, hay người nào vì vua mà sống đúng lẽ phải, cư xử ngay thẳng;",
  "mn97:24.2": "người nào tốt hơn?”",
  "mn97:24.3": "“Này ngài Xá Lợi Phất, nếu vì vua mà sống sai lẽ phải, cư xử lệch lạc, thì điều đó không tốt;",
  "mn97:24.4": "còn nếu, này ngài Xá Lợi Phất, vì vua mà sống đúng lẽ phải, cư xử ngay thẳng, thì điều đó mới là tốt hơn ở đây.",
  "mn97:24.5": "Này ngài Xá Lợi Phất, sống đúng lẽ phải và cư xử ngay thẳng tốt hơn sống sai lẽ phải và cư xử lệch lạc.”",
  "mn97:24.6": "“Này Dhanañjāni, có những việc làm đúng lẽ phải vì người khác, nhờ đó có thể làm điều cần làm cho vua, mà không làm việc xấu, lại còn đi theo con đường lành.",
  "mn97:25.1": "Ông nghĩ sao, này Dhanañjāni, người nào vì nuôi thân cho mập mạnh, cho lớn lên mà sống sai lẽ phải, cư xử lệch lạc, hay người nào vì nuôi thân cho mập mạnh, cho lớn lên mà sống đúng lẽ phải, cư xử ngay thẳng;",
  "mn97:25.2": "người nào tốt hơn?”",
  "mn97:25.3": "“Này ngài Xá Lợi Phất, nếu vì nuôi thân cho mập mạnh, cho lớn lên mà sống sai lẽ phải, cư xử lệch lạc, thì điều đó không tốt;",
  "mn97:25.4": "còn nếu, này ngài Xá Lợi Phất, vì nuôi thân cho mập mạnh, cho lớn lên mà sống đúng lẽ phải, cư xử ngay thẳng, thì điều đó mới là tốt hơn ở đây.",
  "mn97:25.5": "Này ngài Xá Lợi Phất, sống đúng lẽ phải và cư xử ngay thẳng tốt hơn sống sai lẽ phải và cư xử lệch lạc.”",
  "mn97:25.6": "“Này Dhanañjāni, có những việc làm đúng lẽ phải vì người khác, nhờ đó có thể nuôi thân cho mập mạnh, cho lớn lên, mà không làm việc xấu, lại còn đi theo con đường lành.”",
  "mn97:26.1": "Rồi bà-la-môn Dhanañjāni vui mừng, bằng lòng với lời của ngài Xá Lợi Phất, đứng dậy khỏi chỗ ngồi và ra về.",
  "mn97:27.1": "Rồi sau một thời gian, bà-la-môn Dhanañjāni bị bệnh, đau đớn, bệnh rất nặng.",
  "mn97:27.2": "Khi ấy bà-la-môn Dhanañjāni gọi một người đến:",
  "mn97:27.3": "“Này anh, hãy đi đến chỗ Đức Thế Tôn; đến rồi, thay mặt tôi cúi đầu đảnh lễ dưới chân Đức Thế Tôn và thưa rằng:",
  "mn97:27.4": "‘Bạch ngài, bà-la-môn Dhanañjāni đang bị bệnh, đau đớn, bệnh rất nặng.",
  "mn97:27.5": "Ông ấy cúi đầu đảnh lễ dưới chân Đức Thế Tôn.’",
  "mn97:27.6": "Rồi hãy đi đến chỗ ngài Xá Lợi Phất; đến rồi, thay mặt tôi cúi đầu đảnh lễ dưới chân ngài Xá Lợi Phất và thưa rằng:",
  "mn97:27.7": "‘Bạch ngài, bà-la-môn Dhanañjāni đang bị bệnh, đau đớn, bệnh rất nặng.’",
  "mn97:27.8": "Vị ấy cúi đầu đảnh lễ dưới chân ngài Xá Lợi Phất.",
  "mn97:27.9": "Và hãy nói như vầy:",
  "mn97:27.10": "‘Lành thay, bạch ngài, mong ngài Xá Lợi Phất vì thương xót mà đến nhà bà la môn Dhanañjāni.’",
  "mn97:27.11": "“Dạ vâng, bạch ngài,” người ấy nhận lời với bà la môn Dhanañjāni rồi đi đến chỗ Đức Thế Tôn; đến nơi, đảnh lễ Đức Thế Tôn rồi ngồi xuống một bên. Khi đã ngồi xuống một bên, người ấy thưa với Đức Thế Tôn:",
  "mn97:27.12": "“Bạch ngài, bà la môn Dhanañjāni đang đau yếu, khổ sở, bệnh rất nặng.",
  "mn97:27.13": "Ông ấy cúi đầu đảnh lễ dưới chân Đức Thế Tôn.”",
  "mn97:27.14": "Rồi người ấy đi đến chỗ ngài Xá Lợi Phất; đến nơi, đảnh lễ ngài Xá Lợi Phất rồi ngồi xuống một bên. Khi đã ngồi xuống một bên, người ấy thưa với ngài Xá Lợi Phất:",
  "mn97:27.15": "“Bạch ngài, bà la môn Dhanañjāni đang đau yếu, khổ sở, bệnh rất nặng.",
  "mn97:27.16": "Ông ấy cúi đầu đảnh lễ dưới chân ngài Xá Lợi Phất, và nói như vầy:",
  "mn97:27.17": "‘Lành thay, bạch ngài, mong ngài Xá Lợi Phất vì thương xót mà đến nhà bà la môn Dhanañjāni.’”",
  "mn97:27.18": "Ngài Xá Lợi Phất im lặng nhận lời.",
  "mn97:28.1": "Rồi ngài Xá Lợi Phất mặc y, mang bát và áo choàng, đi đến nhà bà la môn Dhanañjāni; đến nơi, ngồi xuống chỗ đã dọn sẵn. Khi đã ngồi xuống, ngài Xá Lợi Phất nói với bà la môn Dhanañjāni:",
  "mn97:28.2": "“Này Dhanañjāni, ông có chịu đựng nổi không, có cầm cự được không? Những cảm giác đau đớn có dịu bớt đi chăng, chứ không tăng thêm chăng? Có thấy chúng lùi bớt, chứ không thấy tăng lên chăng?”",
  "mn97:29.1": "“Thưa ngài Xá Lợi Phất, tôi không chịu đựng nổi, không cầm cự được. Những cảm giác đau đớn dữ dội cứ tăng lên, không dịu bớt. Chỉ thấy chúng tăng lên, không thấy lùi bớt.",
  "mn97:29.2": "Ví như một người khỏe mạnh lấy mũi nhọn sắc đâm thẳng vào đỉnh đầu, thì cũng vậy, thưa ngài Xá Lợi Phất, những luồng gió dữ dội đang xoáy trong đầu tôi.",
  "mn97:29.3": "Thưa ngài Xá Lợi Phất, tôi không chịu đựng nổi, không cầm cự được. Những cảm giác đau đớn dữ dội cứ tăng lên, không dịu bớt. Chỉ thấy chúng tăng lên, không thấy lùi bớt.",
  "mn97:29.4": "Ví như một người khỏe mạnh lấy dây da chắc quấn siết đầu thật chặt, thì cũng vậy, thưa ngài Xá Lợi Phất, đầu tôi đau dữ dội như bị siết chặt.",
  "mn97:29.5": "Thưa ngài Xá Lợi Phất, tôi không chịu đựng nổi, không cầm cự được. Những cảm giác đau đớn dữ dội cứ tăng lên, không dịu bớt. Chỉ thấy chúng tăng lên, không thấy lùi bớt.",
  "mn97:29.6": "Ví như một người mổ bò khéo tay, hay học trò của người ấy, lấy dao bén mổ bụng một con bò, thì cũng vậy, thưa ngài Xá Lợi Phất, những luồng gió dữ dội đang cắt xé bụng tôi.",
  "mn97:29.7": "Thưa ngài Xá Lợi Phất, tôi không chịu đựng nổi, không cầm cự được. Những cảm giác đau đớn dữ dội cứ tăng lên, không dịu bớt. Chỉ thấy chúng tăng lên, không thấy lùi bớt.",
  "mn97:29.8": "Ví như hai người khỏe mạnh nắm hai cánh tay một người yếu hơn rồi hơ nóng, thiêu đốt người ấy trên hố than, thì cũng vậy, thưa ngài Xá Lợi Phất, thân tôi nóng rát dữ dội.",
  "mn97:29.9": "Thưa ngài Xá Lợi Phất, tôi không chịu đựng nổi, không cầm cự được. Những cảm giác đau đớn dữ dội cứ tăng lên, không dịu bớt. Chỉ thấy chúng tăng lên, không thấy lùi bớt.”",
  "mn97:30.1": "“Này Dhanañjāni, ông nghĩ sao, cái nào tốt hơn:",
  "mn97:30.2": "địa ngục hay loài vật?”",
  "mn97:30.3": "“Thưa ngài Xá Lợi Phất, so với địa ngục thì loài vật tốt hơn.”",
  "mn97:30.4": "“Này Dhanañjāni, ông nghĩ sao, cái nào tốt hơn:",
  "mn97:30.5": "loài vật hay cõi ngạ quỷ?”",
  "mn97:30.6": "“Thưa ngài Xá Lợi Phất, so với loài vật thì cõi ngạ quỷ tốt hơn.”",
  "mn97:30.7": "“Này Dhanañjāni, ông nghĩ sao, cái nào tốt hơn:",
  "mn97:30.8": "cõi ngạ quỷ hay loài người?”",
  "mn97:30.9": "“Thưa ngài Xá Lợi Phất, cõi ngạ quỷ kém hơn loài người.”",
  "mn97:30.10": "“Này Dhanañjāni, ông nghĩ sao, bên nào hơn—",
  "mn97:30.11": "loài người hay chư thiên Bốn Vua Trời?”",
  "mn97:30.12": "“Thưa ngài Xá Lợi Phất, chư thiên Bốn Vua Trời hơn loài người.”",
  "mn97:30.13": "“Này Dhanañjāni, ông nghĩ sao, bên nào hơn—",
  "mn97:30.14": "chư thiên Bốn Vua Trời hay chư thiên cõi Ba Mươi Ba?”",
  "mn97:30.15": "“Thưa ngài Xá Lợi Phất, chư thiên cõi Ba Mươi Ba hơn chư thiên Bốn Vua Trời.”",
  "mn97:30.16": "“Này Dhanañjāni, ông nghĩ sao, bên nào hơn—",
  "mn97:30.17": "chư thiên cõi Ba Mươi Ba hay chư thiên Dạ Ma?”",
  "mn97:30.18": "“Thưa ngài Xá Lợi Phất, chư thiên Dạ Ma hơn chư thiên cõi Ba Mươi Ba.”",
  "mn97:30.19": "“Này Dhanañjāni, ông nghĩ sao, bên nào hơn—",
  "mn97:30.20": "chư thiên Dạ Ma hay chư thiên Đâu Suất?”",
  "mn97:30.21": "“Thưa ngài Xá Lợi Phất, chư thiên Đâu Suất hơn chư thiên Dạ Ma.”",
  "mn97:30.22": "“Này Dhanañjāni, ông nghĩ sao, bên nào hơn—",
  "mn97:30.23": "chư thiên Đâu Suất hay chư thiên Hóa Lạc?”",
  "mn97:30.24": "“Thưa ngài Xá Lợi Phất, chư thiên Hóa Lạc hơn chư thiên Đâu Suất.”",
  "mn97:30.25": "“Này Dhanañjāni, ông nghĩ sao, bên nào hơn—",
  "mn97:30.26": "chư thiên Hóa Lạc hay chư thiên Tha Hóa Tự Tại?”",
  "mn97:30.27": "“Thưa ngài Xá Lợi Phất, chư thiên Tha Hóa Tự Tại hơn chư thiên Hóa Lạc.”",
  "mn97:31.1": "“Này Dhanañjāni, ông nghĩ sao, bên nào hơn—",
  "mn97:31.2": "chư thiên Tha Hóa Tự Tại hay cõi Phạm thiên?”",
  "mn97:31.3": "“Ngài Xá Lợi Phất nói: ‘cõi Phạm thiên’;",
  "mn97:31.4": "ngài Xá Lợi Phất nói: ‘cõi Phạm thiên’.”",
  "mn97:31.5": "Bấy giờ, ngài Xá Lợi Phất nghĩ như sau:",
  "mn97:31.6": "“Những vị Bà-la-môn này hướng lòng về cõi Phạm thiên.",
  "mn97:31.7": "Hay là ta chỉ cho Bà-la-môn Dhanañjāni con đường để cùng ở với Phạm thiên.”",
  "mn97:31.8": "“Này Dhanañjāni, ta sẽ chỉ cho ông con đường để cùng ở với Phạm thiên;",
  "mn97:31.9": "ông hãy nghe, khéo để tâm, ta sẽ nói.”",
  "mn97:31.10": "“Vâng, thưa ngài,” Bà-la-môn Dhanañjāni đáp lời ngài Xá Lợi Phất.",
  "mn97:31.11": "Ngài Xá Lợi Phất nói như sau:",
  "mn97:32.1": "“Này Dhanañjāni, con đường nào đưa đến chỗ sống chung với Phạm thiên?",
  "mn97:32.2": "Ở đây, này Dhanañjāni, một Tỳ Kheo sống với lòng thương trải khắp một phương, cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư; như vậy, trên, dưới, ngang khắp, mọi nơi, khắp tất cả, vị ấy sống bao trùm cả thế gian với lòng thương, rộng lớn, cao rộng, không lường, không oán, không hại.",
  "mn97:32.3": "Này Dhanañjāni, đó là con đường đưa đến chỗ sống chung với Phạm thiên.",
  "mn97:33-35.1": "Lại nữa, này Dhanañjāni, một Tỳ Kheo sống với lòng thương xót …",
  "mn97:33-35.2": "với lòng vui theo …",
  "mn97:33-35.3": "với lòng bình thản trải khắp một phương, cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư; như vậy, trên, dưới, ngang khắp, mọi nơi, khắp tất cả, vị ấy sống bao trùm cả thế gian với lòng bình thản, rộng lớn, cao rộng, không lường, không oán, không hại.",
  "mn97:33-35.4": "Này Dhanañjāni, đó là con đường đưa đến chỗ sống chung với Phạm thiên.”",
  "mn97:36.1": "“Vậy thì, thưa ngài Sāriputta, xin ngài thay lời tôi cúi đầu đảnh lễ dưới chân Đức Thế Tôn:",
  "mn97:36.2": "‘Bạch ngài, bà-la-môn Dhanañjāni đang đau yếu, khổ sở, bệnh rất nặng.",
  "mn97:36.3": "Ông ấy cúi đầu đảnh lễ dưới chân Đức Thế Tôn.’”",
  "mn97:36.4": "Rồi Tôn giả Sāriputta, sau khi đặt bà-la-môn Dhanañjāni vào cõi Phạm thiên, trong khi vẫn còn có chỗ cao hơn cần làm, liền đứng dậy khỏi chỗ ngồi và ra đi.",
  "mn97:36.5": "Rồi bà-la-môn Dhanañjāni, không bao lâu sau khi Tôn giả Sāriputta ra đi, đã qua đời và sinh lên cõi Phạm thiên.",
  "mn97:37.1": "Rồi Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn97:37.2": "“Này các Tỳ Kheo, Sāriputta đã đặt bà-la-môn Dhanañjāni vào cõi Phạm thiên, trong khi vẫn còn có chỗ cao hơn cần làm, rồi đứng dậy khỏi chỗ ngồi và ra đi.”",
  "mn97:38.1": "Rồi Tôn giả Sāriputta đi đến chỗ Đức Thế Tôn, đến nơi, đảnh lễ Đức Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên rồi, Tôn giả Sāriputta thưa với Đức Thế Tôn:",
  "mn97:38.2": "“Bạch ngài, bà-la-môn Dhanañjāni đang đau yếu, khổ sở, bệnh rất nặng,",
  "mn97:38.3": "ông ấy cúi đầu đảnh lễ dưới chân Đức Thế Tôn.”",
  "mn97:38.4": "“Nhưng này Sāriputta, vì sao ông đã đặt bà-la-môn Dhanañjāni vào cõi Phạm thiên, trong khi vẫn còn có chỗ cao hơn cần làm, rồi đứng dậy khỏi chỗ ngồi và ra đi?”",
  "mn97:38.5": "“Bạch ngài, con đã nghĩ như vầy:",
  "mn97:38.6": "‘Những bà-la-môn này hướng lòng đến cõi Phạm thiên, vậy ta nên chỉ cho bà-la-môn Dhanañjāni con đường đưa đến chỗ sống chung với Phạm thiên.’”",
  "mn97:38.7": "“Này Sāriputta, bà-la-môn Dhanañjāni đã qua đời và đã sinh lên cõi Phạm thiên.”",
  "mn97:38.8": "Kinh Dhanañjāni chấm dứt, bài thứ bảy."
}
window.BILARA["mn97"]["vi"]["mn97:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
