window.BILARA = window.BILARA || {};
window.BILARA["mn99"] = window.BILARA["mn99"] || {};
window.BILARA["mn99"]["vi"] = {
  "mn99:0.1": "Trung Bộ Kinh 99",
  "mn99:0.2": "Kinh Subha",
  "mn99:1.1": "Tôi nghe như vầy—",
  "mn99:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, trong rừng Kỳ Đà, tại vườn của ông Cấp Cô Độc.",
  "mn99:2.1": "Lúc ấy, thanh niên Bà-la-môn Subha, con ông Todeyya, đang ở Xá Vệ, trong nhà của một người chủ nhà, vì có chút việc.",
  "mn99:2.2": "Rồi thanh niên Bà-la-môn Subha, con ông Todeyya, nói với người chủ nhà nơi mình đang ở rằng:",
  "mn99:2.3": "“Tôi có nghe thế này, này chủ nhà:",
  "mn99:2.4": "‘Xá Vệ không vắng những người đã làm xong việc cần làm.’",
  "mn99:2.5": "Hôm nay, ta nên đến gần vị sa-môn hay Bà-la-môn nào đây?”",
  "mn99:2.6": "“Thưa ngài, Đức Thế Tôn đang ở Xá Vệ, trong rừng Kỳ Đà, tại vườn của ông Cấp Cô Độc.",
  "mn99:2.7": "Thưa ngài, xin ngài đến gặp Đức Thế Tôn ấy.”",
  "mn99:3.1": "Rồi thanh niên Bà-la-môn Subha, con ông Todeyya, nhận lời người chủ nhà ấy, đi đến chỗ Đức Thế Tôn; đến nơi, ông chào hỏi thân tình với Đức Thế Tôn.",
  "mn99:3.2": "Sau khi nói chuyện thân tình gợi nhớ đủ rồi, ông ngồi xuống một bên. Khi đã ngồi xuống một bên, thanh niên Bà-la-môn Subha, con ông Todeyya, thưa với Đức Thế Tôn rằng:",
  "mn99:4.1": "“Thưa ông Gotama, các Bà-la-môn nói như vầy:",
  "mn99:4.2": "‘Người sống đời ở nhà thì làm trọn được nếp sống đúng đắn, khéo lành; người đã rời nhà đi sống không nhà thì không làm trọn được nếp sống đúng đắn, khéo lành.’",
  "mn99:4.3": "Ở đây, ông Gotama nói sao?”",
  "mn99:4.4": "“Này thanh niên, ở đây ta nói bằng cách chia rõ từng phần;",
  "mn99:4.5": "ta không nói một chiều.",
  "mn99:4.6": "Này thanh niên, ta không khen người sống ở nhà hay người đã rời nhà đi sống không nhà mà đi sai đường.",
  "mn99:4.7": "Vì này thanh niên, dù là người sống ở nhà hay người đã rời nhà đi sống không nhà, nếu đi sai đường thì do đi sai đường, người ấy không làm trọn được nếp sống đúng đắn, khéo lành.",
  "mn99:4.8": "Này thanh niên, ta khen người sống ở nhà hay người đã rời nhà đi sống không nhà mà đi đúng đường.",
  "mn99:4.9": "Vì này thanh niên, dù là người sống ở nhà hay người đã rời nhà đi sống không nhà, nếu đi đúng đường thì do đi đúng đường, người ấy làm trọn được nếp sống đúng đắn, khéo lành.”",
  "mn99:5.1": "“Thưa ông Gotama, các Bà-la-môn nói như vầy:",
  "mn99:5.2": "‘Việc sống đời ở nhà có nền tảng lớn, nhiều việc lớn, nhiều ràng buộc lớn, nhiều lo toan lớn, và đem lại quả lớn;",
  "mn99:5.3": "còn việc rời nhà đi sống không nhà có nền tảng nhỏ, ít việc, ít ràng buộc, ít lo toan, và đem lại quả nhỏ.’",
  "mn99:5.4": "Ở đây, ông Gotama nói sao?”",
  "mn99:5.5": "“Này thanh niên, ở đây ta cũng nói bằng cách chia rõ từng phần;",
  "mn99:5.6": "ta không nói một chiều.",
  "mn99:5.7": "Này thanh niên, có việc làm có nền tảng lớn, nhiều việc lớn, nhiều ràng buộc lớn, nhiều lo toan lớn, nhưng khi hỏng thì cho quả nhỏ;",
  "mn99:5.8": "này thanh niên, có việc làm có nền tảng lớn, nhiều việc lớn, nhiều ràng buộc lớn, nhiều lo toan lớn, nhưng khi thành thì cho quả lớn;",
  "mn99:5.9": "Này thanh niên, có việc làm ít lợi, ít việc phải lo, ít ràng buộc, ít phải gắng sức; nếu hỏng thì cho ra ít kết quả.",
  "mn99:5.10": "Này thanh niên, có việc làm ít lợi, ít việc phải lo, ít ràng buộc, ít phải gắng sức; nếu thành thì cho ra kết quả lớn.",
  "mn99:6.1": "Và này thanh niên, việc làm nào có lợi lớn, nhiều việc phải lo, nhiều ràng buộc, phải gắng sức nhiều, mà nếu hỏng thì cho ra ít kết quả?",
  "mn99:6.2": "Này thanh niên, làm ruộng là việc làm có lợi lớn, nhiều việc phải lo, nhiều ràng buộc, phải gắng sức nhiều, mà nếu hỏng thì cho ra ít kết quả.",
  "mn99:6.3": "Và này thanh niên, việc làm nào có lợi lớn, nhiều việc phải lo, nhiều ràng buộc, phải gắng sức nhiều, mà nếu thành thì cho ra kết quả lớn?",
  "mn99:6.4": "Này thanh niên, chính làm ruộng là việc làm có lợi lớn, nhiều việc phải lo, nhiều ràng buộc, phải gắng sức nhiều, mà nếu thành thì cho ra kết quả lớn.",
  "mn99:6.5": "Và này thanh niên, việc làm nào ít lợi, ít việc phải lo, ít ràng buộc, ít phải gắng sức, mà nếu hỏng thì cho ra ít kết quả?",
  "mn99:6.6": "Này thanh niên, buôn bán là việc làm ít lợi, ít việc phải lo, ít ràng buộc, ít phải gắng sức, mà nếu hỏng thì cho ra ít kết quả.",
  "mn99:6.7": "Và này thanh niên, việc làm nào ít lợi, ít việc phải lo, ít ràng buộc, ít phải gắng sức, mà nếu thành thì cho ra kết quả lớn?",
  "mn99:6.8": "Này thanh niên, chính buôn bán là việc làm ít lợi, ít việc phải lo, ít ràng buộc, ít phải gắng sức, mà nếu thành thì cho ra kết quả lớn.",
  "mn99:7.1": "Cũng như này thanh niên, làm ruộng là việc làm có lợi lớn, nhiều việc phải lo, nhiều ràng buộc, phải gắng sức nhiều, mà nếu hỏng thì cho ra ít kết quả;",
  "mn99:7.2": "cũng vậy, này thanh niên, đời sống tại nhà là việc làm có lợi lớn, nhiều việc phải lo, nhiều ràng buộc, phải gắng sức nhiều, mà nếu hỏng thì cho ra ít kết quả.",
  "mn99:7.3": "Cũng như này thanh niên, chính làm ruộng là việc làm có lợi lớn, nhiều việc phải lo, nhiều ràng buộc, phải gắng sức nhiều, mà nếu thành thì cho ra kết quả lớn;",
  "mn99:7.4": "cũng vậy, này thanh niên, đời sống tại nhà là việc làm có lợi lớn, nhiều việc phải lo, nhiều ràng buộc, phải gắng sức nhiều, mà nếu thành thì cho ra kết quả lớn.",
  "mn99:7.5": "Cũng như này thanh niên, buôn bán là việc làm ít lợi, ít việc phải lo, ít ràng buộc, ít phải gắng sức, mà nếu hỏng thì cho ra ít kết quả;",
  "mn99:7.6": "cũng vậy, này thanh niên, đời sống lìa nhà là việc làm ít lợi, ít việc phải lo, ít ràng buộc, ít phải gắng sức, mà nếu hỏng thì cho ra ít kết quả.",
  "mn99:7.7": "Cũng như này thanh niên, chính buôn bán là việc làm ít lợi, ít việc phải lo, ít ràng buộc, ít phải gắng sức, mà nếu thành thì cho ra kết quả lớn;",
  "mn99:7.8": "cũng vậy, này thanh niên, đời sống lìa nhà là việc làm ít lợi, ít việc phải lo, ít ràng buộc, ít phải gắng sức, mà nếu thành thì cho ra kết quả lớn.”",
  "mn99:8.1": "“Thưa ngài Gotama, các Bà-la-môn nêu ra năm điều để làm việc lành, để đạt điều khéo.”",
  "mn99:8.2": "“Này thanh niên, các Bà-la-môn ấy nêu ra năm điều để làm việc lành, để đạt điều khéo —",
  "mn99:8.3": "nếu điều ấy không làm ngươi ngại —",
  "mn99:8.4": "thì lành thay, hãy nói năm điều ấy giữa hội chúng này.”",
  "mn99:8.5": "“Thưa ngài Gotama, tôi không ngại khi có các vị ngồi đây, hay một người như ngài ngồi đây.”",
  "mn99:8.6": "“Vậy thì, này thanh niên, hãy nói đi.”",
  "mn99:9.1": "“Thưa ngài Gotama, các Bà-la-môn nêu ra điều thứ nhất là nói thật, để làm việc lành, để đạt điều khéo.",
  "mn99:9.2": "Thưa ngài Gotama, các Bà-la-môn nêu ra điều thứ hai là sống kham khổ, để làm việc lành, để đạt điều khéo.",
  "mn99:9.3": "Thưa ngài Gotama, các Bà-la-môn nêu ra điều thứ ba là sống trong sạch, để làm việc lành, để đạt điều khéo.",
  "mn99:9.4": "Thưa ngài Gotama, các Bà-la-môn nêu ra điều thứ tư là học đọc tụng, để làm việc lành, để đạt điều khéo.",
  "mn99:9.5": "Thưa ngài Gotama, các Bà-la-môn nêu ra điều thứ năm là rộng lòng cho đi, để làm việc lành, để đạt điều khéo.",
  "mn99:9.6": "Thưa ngài Gotama, các Bà-la-môn nêu ra năm điều này để làm việc lành, để đạt điều khéo.”",
  "mn99:9.7": "Ở đây, Đức Gotama nói thế nào?",
  "mn99:9.8": "Này thanh niên, trong hàng bà-la-môn có lấy một người nào nói như vầy không:",
  "mn99:9.9": "‘Tôi tự mình biết rõ, tự mình thấy rõ kết quả của năm điều này, rồi nói ra’?”",
  "mn99:9.10": "“Thưa ngài Gotama, không có.”",
  "mn99:9.11": "“Này thanh niên, trong hàng bà-la-môn có lấy một thầy nào, hay thầy của thầy, cho đến bảy đời thầy truyền nối, nói như vầy không:",
  "mn99:9.12": "‘Tôi tự mình biết rõ, tự mình thấy rõ kết quả của năm điều này, rồi nói ra’?”",
  "mn99:9.13": "“Thưa ngài Gotama, không có.”",
  "mn99:9.14": "“Này thanh niên, còn những vị ẩn sĩ xưa của hàng bà-la-môn, là người làm ra các bài chú, truyền lại các bài chú, mà nay các bà-la-môn vẫn hát theo, nói theo, lặp lại lời đã nói, đọc lại lời đã đọc, như là Aṭṭhaka, Vāmaka, Vāmadeva, Vessāmitta, Yamataggi, Aṅgīrasa, Bhāradvāja, Vāseṭṭha, Kassapa, Bhagu,",
  "mn99:9.15": "các vị ấy có nói như vầy không:",
  "mn99:9.16": "‘Chúng tôi tự mình biết rõ, tự mình thấy rõ kết quả của năm điều này, rồi nói ra’?”",
  "mn99:9.17": "“Thưa ngài Gotama, không có.”",
  "mn99:9.18": "“Vậy thì, này thanh niên, trong hàng bà-la-môn không có lấy một người nào nói như vầy:",
  "mn99:9.19": "‘Tôi tự mình biết rõ, tự mình thấy rõ kết quả của năm điều này, rồi nói ra’;",
  "mn99:9.20": "không có lấy một thầy nào, hay thầy của thầy, cho đến bảy đời thầy truyền nối, nói như vầy:",
  "mn99:9.21": "‘Tôi tự mình biết rõ, tự mình thấy rõ kết quả của năm điều này, rồi nói ra’;",
  "mn99:9.22": "còn những vị ẩn sĩ xưa của hàng bà-la-môn, là người làm ra các bài chú, truyền lại các bài chú, mà nay các bà-la-môn vẫn hát theo, nói theo, lặp lại lời đã nói, đọc lại lời đã đọc, như là Aṭṭhaka, Vāmaka, Vāmadeva, Vessāmitta, Yamataggi, Aṅgīrasa, Bhāradvāja, Vāseṭṭha, Kassapa, Bhagu,",
  "mn99:9.23": "các vị ấy cũng không nói như vầy:",
  "mn99:9.24": "‘Chúng tôi tự mình biết rõ, tự mình thấy rõ kết quả của năm điều này, rồi nói ra’.",
  "mn99:9.25": "Ví như, này thanh niên, một hàng người mù bám nối nhau, người đầu không thấy, người giữa không thấy, người cuối cũng không thấy;",
  "mn99:9.26": "cũng vậy, này thanh niên, lời nói của các bà-la-môn, theo Ta nghĩ, giống như một hàng người mù: người đầu không thấy, người giữa không thấy, người cuối cũng không thấy.”",
  "mn99:10.1": "Khi được nói như vậy, thanh niên Subha, con ông Todeyya, bị Đức Thế Tôn ví như hàng người mù, liền nổi giận, không vui, chê trách chính Đức Thế Tôn, công kích chính Đức Thế Tôn, nói ngược lại chính Đức Thế Tôn:",
  "mn99:10.2": "“Sa-môn Gotama hẳn là kẻ làm điều xấu,” rồi nói với Đức Thế Tôn như vầy:",
  "mn99:10.3": "“Thưa ngài Gotama, bà-la-môn Pokkharasāti, người dòng Opamañña, người ở Subhagavana, nói như vầy:",
  "mn99:10.4": "‘Cũng vậy, ở đây có một số sa-môn và bà-la-môn tự nhận mình có biết và thấy vượt hơn mức người thường, xứng bậc cao quý. ",
  "mn99:10.5": "Lời nói của họ chỉ thành ra chuyện đáng cười, chỉ là tên gọi suông, chỉ là rỗng không, chỉ là trống trơn. ",
  "mn99:10.6": "Làm sao một người là người thường lại có thể biết, có thể thấy, hay tự mình làm cho thật rõ điều vượt hơn mức người thường, xứng bậc cao quý được—",
  "mn99:10.7": "điều ấy không thể có.’”",
  "mn99:11.1": "“Này thanh niên, bà-la-môn Pokkharasāti, người dòng Opamañña, người ở Subhagavana, có dò biết hết lòng dạ của tất cả sa-môn và bà-la-môn, lấy lòng mình mà biết lòng người khác chăng?”",
  "mn99:11.2": "“Thưa ngài Gotama, ngay cả lòng dạ của cô đầy tớ Puṇṇikā trong nhà mình, bà-la-môn Pokkharasāti, người dòng Opamañña, người ở Subhagavana, còn không dò biết được, huống nữa là dò biết hết lòng dạ của tất cả sa-môn và bà-la-môn.”",
  "mn99:12.1": "“Ví như, này thanh niên, một người mù từ khi mới sinh không thấy các màu đen trắng, không thấy màu xanh, không thấy màu vàng, không thấy màu đỏ, không thấy màu đỏ sẫm, không thấy chỗ bằng chỗ gồ ghề, không thấy các vì sao, không thấy mặt trăng và mặt trời.",
  "mn99:12.2": "Người ấy có thể nói như vầy:",
  "mn99:12.3": "‘Không có các màu đen trắng, không có người thấy các màu đen trắng;",
  "mn99:12.4": "không có các màu xanh, không có người thấy các màu xanh;",
  "mn99:12.5": "không có các màu vàng, không có người thấy các màu vàng;",
  "mn99:12.6": "không có các màu đỏ, không có người thấy các màu đỏ;",
  "mn99:12.7": "không có các màu đỏ sẫm, không có người thấy các màu đỏ sẫm;",
  "mn99:12.8": "không có cái đều và không đều, không có người thấy cái đều và không đều;",
  "mn99:12.9": "không có các hình ngôi sao, không có người thấy các hình ngôi sao;",
  "mn99:12.10": "không có mặt trăng mặt trời, không có người thấy mặt trăng mặt trời.",
  "mn99:12.11": "Tôi không biết điều ấy, tôi không thấy điều ấy;",
  "mn99:12.12": "nên vì vậy, cái ấy là không có.’",
  "mn99:12.13": "Này thanh niên, người ấy nói như vậy có đúng không?”",
  "mn99:12.14": "“Thưa ngài Gotama, không đúng.",
  "mn99:12.15": "Có các màu đen trắng, có người thấy các màu đen trắng;",
  "mn99:12.16": "có các màu xanh, có người thấy các màu xanh;",
  "mn99:12.17": "có các màu vàng, có người thấy các màu vàng;",
  "mn99:12.18": "có các màu đỏ, có người thấy các màu đỏ;",
  "mn99:12.19": "có các màu đỏ sẫm, có người thấy các màu đỏ sẫm;",
  "mn99:12.20": "có cái đều và không đều, có người thấy cái đều và không đều;",
  "mn99:12.21": "có các hình ngôi sao, có người thấy các hình ngôi sao;",
  "mn99:12.22": "có mặt trăng mặt trời, có người thấy mặt trăng mặt trời.",
  "mn99:12.23": "‘Tôi không biết điều ấy, tôi không thấy điều ấy;",
  "mn99:12.24": "nên vì vậy, cái ấy là không có’;",
  "mn99:12.25": "thưa ngài Gotama, người ấy nói như vậy là không đúng.”",
  "mn99:13.1": "“Cũng vậy, này thanh niên, bà-la-môn Pokkharasāti, người học trò của Opamañña thuộc dòng Subhagavanika, là người mù, không có mắt.",
  "mn99:13.2": "Người ấy mà có thể biết, có thể thấy, hay tự mình chạm tới điều vượt hơn mức người thường, là sự thấy biết riêng của bậc cao quý, thì chuyện ấy không thể có.",
  "mn99:13.3": "Này thanh niên, ông nghĩ sao,",
  "mn99:13.4": "những bà-la-môn giàu lớn ở xứ Kosala kia, như là—",
  "mn99:13.5": "bà-la-môn Caṅkī, bà-la-môn Tārukkha, bà-la-môn Pokkharasāti, bà-la-môn Jāṇussoṇi, và cha ông là Todeyya bà-la-môn, trong số họ ai là người hơn, về việc họ nói lời đã gom đủ hay lời chưa gom đủ?”",
  "mn99:13.6": "“Thưa ngài Gotama, là lời đã gom đủ.”",
  "mn99:13.7": "“Theo ông nghĩ sao, trong hai cách ấy, cách nào tốt hơn: nói lời có suy nghĩ hay nói lời không suy nghĩ?”",
  "mn99:13.8": "“Thưa ngài Gotama, nói lời có suy nghĩ là tốt hơn.”",
  "mn99:13.9": "“Trong hai cách ấy, cách nào tốt hơn: nói lời sau khi cân nhắc hay nói lời không cân nhắc?”",
  "mn99:13.10": "“Thưa ngài Gotama, nói lời sau khi cân nhắc là tốt hơn.”",
  "mn99:13.11": "“Trong hai cách ấy, cách nào tốt hơn: nói lời có ích hay nói lời không có ích?”",
  "mn99:13.12": "“Thưa ngài Gotama, nói lời có ích là tốt hơn.”",
  "mn99:14.1": "“Ông nghĩ sao, này thanh niên,",
  "mn99:14.2": "nếu là vậy, thì lời mà bà-la-môn Pokkharasāti, dòng Opamañña, người Subhagavanika, đã nói là lời đúng sự thật hay không đúng sự thật?”",
  "mn99:14.3": "“Thưa ngài Gotama, là không đúng sự thật.”",
  "mn99:14.4": "“Là lời có suy nghĩ hay không suy nghĩ?”",
  "mn99:14.5": "“Thưa ngài Gotama, là không suy nghĩ.”",
  "mn99:14.6": "“Là lời sau khi cân nhắc hay không cân nhắc?”",
  "mn99:14.7": "“Thưa ngài Gotama, là không cân nhắc.”",
  "mn99:14.8": "“Là lời có ích hay không có ích?”",
  "mn99:14.9": "“Thưa ngài Gotama, là không có ích.”",
  "mn99:15.1": "“Này thanh niên, có năm thứ che lấp này.",
  "mn99:15.2": "Năm thứ là gì?",
  "mn99:15.3": "Sự ham muốn dục lạc che lấp, sự ghét giận che lấp, sự dã dượi buồn ngủ che lấp, sự xao động hối hận che lấp, sự ngờ vực che lấp—",
  "mn99:15.4": "này thanh niên, đó là năm thứ che lấp.",
  "mn99:15.5": "Này thanh niên, bà-la-môn Pokkharasāti, dòng Opamañña, người Subhagavanika, bị năm thứ che lấp này bao phủ, che kín, trùm lấp, quấn chặt.",
  "mn99:15.6": "Người ấy mà có thể biết, thấy, hay tự mình chạm tới điều vượt hơn mức người thường, là sự thấy biết đặc biệt cao quý, thì chuyện ấy không thể có.",
  "mn99:16.1": "“Này thanh niên, có năm thứ vui sướng giác quan này.",
  "mn99:16.2": "Năm thứ là gì?",
  "mn99:16.3": "Những hình sắc mắt nhận ra, đáng ưa, dễ mến, vừa lòng, hấp dẫn, gắn với dục lạc, khơi lòng say đắm;",
  "mn99:16.4": "những tiếng tai nhận ra …",
  "mn99:16.5": "những mùi mũi nhận ra …",
  "mn99:16.6": "những vị lưỡi nhận ra …",
  "mn99:16.7": "những sự chạm đụng thân nhận ra, đáng ưa, dễ mến, vừa lòng, hấp dẫn, gắn với dục lạc, khơi lòng say đắm—",
  "mn99:16.8": "này thanh niên, đó là năm thứ vui sướng giác quan.",
  "mn99:16.9": "Này thanh niên, bà-la-môn Pokkharasāti, dòng Opamañña, người Subhagavanika, bị trói buộc, mê mẩn, chìm đắm trong năm thứ vui sướng giác quan này, không thấy mặt hại, không biết lối ra, và hưởng thụ chúng.",
  "mn99:16.10": "Vậy thì chuyện người ấy sẽ biết, sẽ thấy, hay sẽ tự mình chạm tới một trạng thái vượt hơn mức người thường, là sự thấy biết riêng của bậc cao quý — chuyện ấy không thể có.",
  "mn99:17.1": "Này thanh niên, anh nghĩ sao,",
  "mn99:17.2": "nếu một người nhóm lửa nhờ cỏ và củi, còn một người nhóm lửa từ cỏ và củi đã bị quăng bỏ, thì lửa nào có ngọn hơn, đẹp hơn, sáng hơn?",
  "mn99:17.3": "Thưa ngài Gotama, nếu có thể nhóm lửa từ cỏ và củi đã bị quăng bỏ, thì lửa ấy sẽ có ngọn hơn, đẹp hơn, sáng hơn.",
  "mn99:17.4": "Nhưng này thanh niên, chuyện nhóm lửa từ cỏ và củi đã bị quăng bỏ là điều không thể có, không có chỗ xảy ra, trừ người có sức mầu nhiệm.",
  "mn99:17.5": "Này thanh niên, cũng như lửa cháy nhờ cỏ và củi, Ta cũng nói niềm vui này là như vậy: niềm vui nương vào năm thứ thích thú của giác quan.",
  "mn99:17.6": "Này thanh niên, cũng như lửa cháy từ cỏ và củi đã bị quăng bỏ, Ta cũng nói niềm vui này là như vậy: niềm vui tách hẳn khỏi các thích thú giác quan, tách khỏi các điều xấu ác.",
  "mn99:17.7": "Và này thanh niên, niềm vui nào là niềm vui tách hẳn khỏi các thích thú giác quan, tách khỏi các điều xấu ác?",
  "mn99:17.8": "Ở đây, này thanh niên, một Tỳ Kheo lìa các thích thú giác quan… đạt tới tầng lặng sâu thứ nhất và sống an trú trong đó.",
  "mn99:17.9": "Đây cũng là niềm vui tách hẳn khỏi các thích thú giác quan, tách khỏi các điều xấu ác.",
  "mn99:17.10": "Lại nữa, này thanh niên, Tỳ Kheo làm cho lắng yên sự nghĩ lời và xét lời… đạt tới tầng lặng sâu thứ hai và sống an trú trong đó.",
  "mn99:17.11": "Đây cũng là niềm vui tách hẳn khỏi các thích thú giác quan, tách khỏi các điều xấu ác.",
  "mn99:18.1": "Này thanh niên, các bà-la-môn nêu ra năm điều để làm việc lành, để vun bồi điều tốt. Trong những điều ấy, các bà-la-môn cho điều nào là cho quả lớn hơn trong việc làm lành, vun bồi điều tốt?",
  "mn99:18.2": "Thưa ngài Gotama, trong năm điều mà các bà-la-môn nêu ra để làm việc lành, để vun bồi điều tốt, thì các bà-la-môn cho rằng sự cho ra là điều cho quả lớn hơn.",
  "mn99:19.1": "Này thanh niên, anh nghĩ sao,",
  "mn99:19.2": "ở đây có một bà-la-môn nào đó đang làm một lễ cúng lớn.",
  "mn99:19.3": "Rồi có hai bà-la-môn đến:",
  "mn99:19.4": "‘Chúng ta sẽ dự lễ cúng lớn của vị bà-la-môn tên như thế ấy.’",
  "mn99:19.5": "Trong đó, một bà-la-môn nghĩ rằng:",
  "mn99:19.6": "‘Ước gì chỉ riêng ta được chỗ ngồi đầu trong bữa ăn, được nước tốt nhất, được phần ăn ngon nhất; đừng để bà-la-môn nào khác được chỗ ngồi đầu trong bữa ăn, được nước tốt nhất, được phần ăn ngon nhất.’",
  "mn99:19.7": "Nhưng này thanh niên, có thể xảy ra chuyện một bà-la-môn khác lại được chỗ ngồi đầu trong bữa ăn, được nước tốt nhất, được phần ăn ngon nhất, còn vị bà-la-môn ấy thì không được.",
  "mn99:19.8": "‘Bà-la-môn khác được chỗ ngồi đầu trong bữa ăn, được nước tốt nhất, được phần ăn ngon nhất, còn ta thì không được’—",
  "mn99:19.9": "nghĩ vậy, người ấy nổi giận, không vui lòng.",
  "mn99:19.10": "Này thanh niên, trong trường hợp này các bà-la-môn nói kết quả của việc ấy là gì?",
  "mn99:19.11": "Thưa ngài Gotama, ở đây các bà-la-môn không cho ra như vầy:",
  "mn99:19.12": "‘Mong cho người kia vì việc này mà nổi giận, không vui lòng.’",
  "mn99:19.13": "Trái lại, ở đây các bà-la-môn chỉ cho ra với lòng thương xót thôi.",
  "mn99:19.14": "Nếu vậy, này thanh niên, đây là nền thứ sáu của việc làm lành nơi các bà-la-môn—",
  "mn99:19.15": "đó là cho ra với lòng thương xót.",
  "mn99:19.16": "Vâng, thưa ngài Gotama, nếu vậy thì đây là nền thứ sáu của việc làm lành nơi các bà-la-môn—",
  "mn99:19.17": "nghĩa là lòng thương xót.”",
  "mn99:20.1": "“Này thanh niên, các bà-la-môn nêu ra năm điều để làm việc lành và vun bồi điều tốt.",
  "mn99:20.2": "Theo anh thấy, năm điều ấy có nhiều hơn ở người sống tại nhà hay ở người đã rời nhà?”",
  "mn99:20.3": "“Thưa ngài Gotama, năm điều mà các bà-la-môn nêu ra để làm việc lành và vun bồi điều tốt, con thấy năm điều ấy có nhiều ở người đã rời nhà, ít ở người sống tại nhà.",
  "mn99:20.4": "Vì người sống tại nhà thì nhiều việc, nhiều bổn phận, nhiều ràng buộc, nhiều lo toan, nên không luôn luôn nói thật.",
  "mn99:20.5": "Còn người đã rời nhà thì ít việc, ít bổn phận, ít ràng buộc, ít lo toan, nên luôn luôn nói thật.",
  "mn99:20.6": "Vì người sống tại nhà thì nhiều việc, nhiều bổn phận, nhiều ràng buộc, nhiều lo toan, nên không luôn luôn sống khổ hạnh…",
  "mn99:20.7": "không luôn luôn sống đời trong sạch…",
  "mn99:20.8": "không luôn luôn siêng đọc tụng…",
  "mn99:20.9": "không luôn luôn rộng lòng cho đi.",
  "mn99:20.10": "Còn người đã rời nhà thì ít việc, ít bổn phận, ít ràng buộc, ít lo toan, nên luôn luôn sống khổ hạnh…",
  "mn99:20.11": "luôn luôn sống đời trong sạch…",
  "mn99:20.12": "luôn luôn siêng đọc tụng…",
  "mn99:20.13": "luôn luôn rộng lòng cho đi.",
  "mn99:20.14": "Thưa ngài Gotama, năm điều mà các bà-la-môn nêu ra để làm việc lành và vun bồi điều tốt, con thấy năm điều ấy có nhiều ở người đã rời nhà, ít ở người sống tại nhà.”",
  "mn99:21.1": "“Này thanh niên, năm điều mà các bà-la-môn nêu ra để làm việc lành và vun bồi điều tốt, ta nói rằng đó là những thứ giúp cho tâm—",
  "mn99:21.2": "nghĩa là để làm cho tâm không oán ghét, không hại ai, được lớn lên.",
  "mn99:21.3": "Ở đây, này thanh niên, một Tỳ Kheo là người nói thật.",
  "mn99:21.4": "Vị ấy, khi nghĩ rằng ‘ta là người nói thật’, thì được biết điều lợi ích, được biết lẽ thật, được niềm vui gắn với lẽ thật.",
  "mn99:21.5": "Niềm vui gắn với điều tốt ấy, ta nói, là thứ giúp cho tâm—",
  "mn99:21.6": "nghĩa là để làm cho tâm không oán ghét, không hại ai, được lớn lên.",
  "mn99:21.7": "Ở đây, này thanh niên, một Tỳ Kheo sống khổ hạnh…",
  "mn99:21.8": "sống đời trong sạch…",
  "mn99:21.9": "siêng đọc tụng…",
  "mn99:21.10": "rộng lòng cho đi.",
  "mn99:21.11": "Vị ấy, khi nghĩ rằng ‘ta là người rộng lòng cho đi’, thì được biết điều lợi ích, được biết lẽ thật, được niềm vui gắn với lẽ thật.",
  "mn99:21.12": "Niềm vui gắn với điều tốt ấy, ta nói, là thứ giúp cho tâm—",
  "mn99:21.13": "nghĩa là để làm cho tâm không oán ghét, không hại ai, được lớn lên.",
  "mn99:21.14": "Này thanh niên, năm điều mà các bà-la-môn nêu ra để làm việc lành và vun bồi điều tốt, ta nói rằng đó là những thứ giúp cho tâm—",
  "mn99:21.15": "nghĩa là để làm cho tâm không oán ghét, không hại ai, được lớn lên.”",
  "mn99:22.1": "Khi được nói vậy, thanh niên Bà-la-môn Subha, con ông Todeyya, thưa với Đức Thế Tôn như vầy:",
  "mn99:22.2": "“Thưa ngài Gotama, tôi có nghe rằng:",
  "mn99:22.3": "‘Sa-môn Gotama biết con đường để sống chung với Phạm thiên.’”",
  "mn99:22.4": "“Này thanh niên, ông nghĩ sao,",
  "mn99:22.5": "làng Naḷakāra ở gần đây chứ không xa phải không?”",
  "mn99:22.6": "“Vâng, thưa ngài, làng Naḷakāra ở gần đây, không xa.”",
  "mn99:22.7": "“Này thanh niên, ông nghĩ sao, ở đây có một người sinh ra và lớn lên tại làng Naḷakāra;",
  "mn99:22.8": "nếu người ấy vừa mới rời làng Naḷakāra, rồi có người hỏi đường đến làng Naḷakāra;",
  "mn99:22.9": "này thanh niên, người sinh ra và lớn lên ở làng Naḷakāra ấy, khi được hỏi đường đến làng Naḷakāra, có thể nào lại ngập ngừng hay nói quanh co không?”",
  "mn99:22.10": "“Không đâu, thưa ngài Gotama.”",
  "mn99:22.11": "“Vì sao vậy?”",
  "mn99:22.12": "“Thưa ngài Gotama, vì người ấy sinh ra và lớn lên ở làng Naḷakāra. Mọi con đường đến làng Naḷakāra, người ấy đều biết rõ.”",
  "mn99:22.13": "“Này thanh niên, người sinh ra và lớn lên ở làng Naḷakāra ấy, khi được hỏi đường đến làng Naḷakāra, có thể còn ngập ngừng hay nói quanh co; nhưng Như Lai thì không như vậy khi được hỏi về cõi Phạm thiên hay con đường đưa đến cõi Phạm thiên.",
  "mn99:22.14": "Này thanh niên, Ta biết Phạm thiên, biết cõi Phạm thiên, biết con đường đưa đến cõi Phạm thiên; và Ta cũng biết người đi theo con đường ấy rồi sinh về cõi Phạm thiên.”",
  "mn99:23.1": "“Thưa ngài Gotama, tôi có nghe rằng:",
  "mn99:23.2": "‘Sa-môn Gotama chỉ dạy con đường để sống chung với Phạm thiên.’",
  "mn99:23.3": "Xin ngài Gotama hãy chỉ dạy cho tôi con đường để sống chung với Phạm thiên.”",
  "mn99:23.4": "“Vậy thì, này thanh niên, hãy nghe đây, khéo để tâm vào, Ta sẽ nói.”",
  "mn99:23.5": "“Vâng, thưa ngài,” thanh niên Bà-la-môn Subha, con ông Todeyya, đáp lời Đức Thế Tôn.",
  "mn99:23.6": "Đức Thế Tôn nói như vầy:",
  "mn99:24.1": "“Này thanh niên, thế nào là con đường để sống chung với Phạm thiên?",
  "mn99:24.2": "Ở đây, này thanh niên, một Tỳ Kheo sống với lòng thương trải khắp một phương, cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư; như vậy, trên, dưới, ngang khắp, mọi nơi, đối với tất cả, vị ấy sống với lòng thương trải khắp cả thế gian, rộng lớn, cao rộng, không lường, không oán ghét, không hại ai.",
  "mn99:24.3": "Này thanh niên, khi sự mở lòng ấy được làm cho lớn mạnh như vậy, thì mọi việc làm còn trong mức nhỏ hẹp không còn sót lại ở đó, không còn đứng vững ở đó.",
  "mn99:24.4": "Ví như, này thanh niên, một người thổi tù và khỏe, có thể dễ dàng làm cho bốn phương đều nghe;",
  "mn99:24.5": "cũng vậy, này thanh niên … như trên … khi sự mở lòng ấy được làm cho lớn mạnh như vậy, thì mọi việc làm còn trong mức nhỏ hẹp không còn sót lại ở đó, không còn đứng vững ở đó.",
  "mn99:24.6": "Đây cũng là con đường để sống chung với Phạm thiên.",
  "mn99:25-27.1": "“Lại nữa, này thanh niên, một Tỳ Kheo sống với lòng thương xót … như trên …",
  "mn99:25-27.2": "sống với lòng vui theo niềm vui của người khác … như trên …",
  "mn99:25-27.3": "sống với tâm bình thản trải khắp một phương, cũng vậy phương thứ hai, cũng vậy phương thứ ba, cũng vậy phương thứ tư; như vậy, trên, dưới, ngang khắp, mọi nơi, đối với tất cả, vị ấy sống với tâm bình thản trải khắp cả thế gian, rộng lớn, cao rộng, không lường, không oán ghét, không hại ai.",
  "mn99:25-27.4": "Này thanh niên, khi sự buông giữ tâm bình thản ấy được làm cho lớn mạnh như vậy, thì mọi việc làm còn trong mức nhỏ hẹp không còn sót lại ở đó, không còn đứng vững ở đó.”",
  "mn99:25-27.5": "Này thanh niên, ví như một người thổi ốc mạnh, chỉ khó nhọc chút ít cũng làm cho bốn phương đều nghe tiếng,",
  "mn99:25-27.6": "cũng vậy, này thanh niên… khi sự buông bỏ với tâm được mở thoát được làm cho lớn mạnh như vậy, thì việc làm nào còn bị đo lường cũng không còn sót lại ở đó, không đứng lại ở đó.",
  "mn99:25-27.7": "Đây cũng là con đường đưa đến sống chung với cõi Phạm thiên.”",
  "mn99:28.1": "Khi được nói vậy, thanh niên Subha, con ông Todeyya, thưa với Đức Thế Tôn:",
  "mn99:28.2": "“Thật hay quá, thưa ngài Gotama, thật hay quá, thưa ngài Gotama.",
  "mn99:28.3": "Ví như có người lật vật đang úp xuống cho ngửa lên, mở ra điều bị che kín, chỉ đường cho người lạc lối, hay cầm đèn dầu vào chỗ tối để người có mắt thấy được hình sắc; cũng vậy, ngài Gotama đã dùng nhiều cách làm sáng tỏ lời dạy.",
  "mn99:28.4": "Con xin nương tựa ngài Gotama, nương tựa lời dạy, và nương tựa hội chúng Tỳ Kheo.",
  "mn99:28.5": "Xin ngài Gotama nhận con là người tại gia nương tựa từ nay cho đến trọn đời.",
  "mn99:28.6": "Giờ thì, thưa ngài Gotama, chúng con xin đi,",
  "mn99:28.7": "vì chúng con có nhiều việc, nhiều điều phải làm.”",
  "mn99:29.1": "“Này thanh niên, ông thấy nay là lúc nào thích hợp thì cứ làm.”",
  "mn99:29.2": "Rồi thanh niên Subha, con ông Todeyya, vui mừng đón nhận lời Đức Thế Tôn dạy, từ chỗ ngồi đứng dậy, cúi đầu chào Đức Thế Tôn, đi quanh bên phải rồi ra về.",
  "mn99:30.1": "Lúc ấy, bà la môn Jāṇussoṇi đi ra khỏi Sāvatthī giữa ban ngày trên cỗ xe do những ngựa cái trắng kéo.",
  "mn99:30.2": "Bà la môn Jāṇussoṇi thấy từ xa thanh niên Subha, con ông Todeyya, đang đi đến.",
  "mn99:30.3": "Thấy thanh niên Subha, con ông Todeyya, ông nói:",
  "mn99:30.4": "“Nào, ngài Bhāradvāja từ đâu về giữa ban ngày vậy?”",
  "mn99:30.5": "“Thưa ngài, tôi từ chỗ sa môn Gotama mà về.”",
  "mn99:30.6": "“Ngài nghĩ sao, ngài Bhāradvāja có cho rằng sa môn Gotama là người khôn sáng không?”",
  "mn99:30.7": "“Tôi là ai mà biết được sự khôn sáng của sa môn Gotama?",
  "mn99:30.8": "Chắc hẳn chỉ người nào ngang tầm như vậy mới biết được sự khôn sáng của sa môn Gotama.”",
  "mn99:30.9": "“Ngài Bhāradvāja thật đang khen sa môn Gotama bằng lời khen rất cao.”",
  "mn99:30.10": "“Tôi là ai mà khen sa môn Gotama?",
  "mn99:30.11": "Ngài Gotama được những người đáng khen khen ngợi, là bậc hơn hết giữa chư thiên và loài người.",
  "mn99:30.12": "Thưa ngài, năm điều mà các bà la môn này nêu ra để làm việc lành, để vun bồi điều tốt,",
  "mn99:30.13": "sa môn Gotama nói rằng đó chỉ là đồ dùng cho tâm—",
  "mn99:30.14": "nghĩa là để làm cho tâm không oán ghét, không hại ai, được lớn lên.”",
  "mn99:31.1": "Khi được nói vậy, bà la môn Jāṇussoṇi bước xuống khỏi cỗ xe do những ngựa cái trắng kéo, vắt y qua một bên vai, chắp tay hướng về Đức Thế Tôn và thốt lên lời cảm hứng:",
  "mn99:31.2": "“Vua Pasenadi nước Kosala thật có phước, vua Pasenadi nước Kosala thật khéo được phước,",
  "mn99:31.3": "vì trong xứ của vua có Như Lai đang sống, bậc đáng kính, bậc tự mình hiểu trọn vẹn.”",
  "mn99:31.4": "Kinh Subha chấm dứt, bài thứ chín."
}
window.BILARA["mn99"]["vi"]["mn99:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
