window.BILARA = window.BILARA || {};
window.BILARA["sn1_v2"] = window.BILARA["sn1_v2"] || {};
window.BILARA["sn1_v2"]["vi"] = {
  "sn1.11:0.1": "Tương Ưng Bộ 1.11",
  "sn1.11:0.2": "2. Phẩm Vườn Hoan Hỷ",
  "sn1.11:0.3": "Kinh Vườn Hoan Hỷ",
  "sn1.11:1.1": "Tôi đã nghe như vầy",
  "sn1.11:1.2": "Một thời, Thế Tôn đang trú tại Sāvatthī (Xá-vệ), trong khu vườn của ông Anāthapiṇḍika (Cấp Cô Độc), rừng Jeta (Kỳ-đà).",
  "sn1.11:1.3": "Ở đó, Thế Tôn gọi các Tỳ-kheo:",
  "sn1.11:1.4": "'Này các Tỳ-kheo!'",
  "sn1.11:1.5": "Bạch Thế Tôn!'  các Tỳ-kheo vâng đáp.",
  "sn1.11:1.6": "Thế Tôn nói:",
  "sn1.11:2.1": "Này các Tỳ-kheo, thuở xưa có một vị thiên nhân thuộc cõi trời Ba mươi ba (Tāvatiṁsa), đang vui chơi trong rừng Hoan Hỷ (Nandana), được vây quanh bởi các thiên nữ, đang thọ hưởng năm thứ dục lạc cõi trời. Vào lúc đó, vị thiên nhân ấy đọc bài kệ này:",
  "sn1.11:3.1": "'Những ai chưa thấy vườn Hoan Hỷ,'",
  "sn1.11:3.2": "thì họ không biết hạnh phúc là gì;",
  "sn1.11:3.3": "Đây là chốn ở của các thiên nhân (naradevas)",
  "sn1.11:3.4": "'thuộc cõi trời Ba mươi ba vinh quang.'",
  "sn1.11:4.1": "Khi nghe vậy, này các Tỳ-kheo, một vị thiên nhân khác đáp lại bằng bài kệ:",
  "sn1.11:5.1": "'Này kẻ ngu, ngươi không hiểu'",
  "sn1.11:5.2": "lời dạy của bậc A-la-hán là thế nào;",
  "sn1.11:5.3": "Tất cả các hành đều vô thường,",
  "sn1.11:5.4": "có bản chất sinh khởi và hoại diệt;",
  "sn1.11:5.5": "Sinh khởi rồi lại diệt",
  "sn1.11:5.6": "sự lắng dịu của chúng mới là hạnh phúc thực sự.''",
  "sn1.12:0.1": "Tương Ưng Bộ 1.12",
  "sn1.12:0.2": "2. Phẩm Vườn Hoan Hỷ",
  "sn1.12:0.3": "Kinh Hoan Hỷ",
  "sn1.12:1.1": "Kinh này xảy ra tại Sāvatthī (Xá-vệ).",
  "sn1.12:1.2": "Đứng một bên, vị thiên nhân đọc bài kệ này trước mặt Thế Tôn:",
  "sn1.12:2.1": "Người có con thì vui mừng vì con,",
  "sn1.12:2.2": "người có trâu bò thì cũng vui mừng vì trâu bò;",
  "sn1.12:2.3": "Niềm vui của người đời đến từ những thứ họ bám víu",
  "sn1.12:2.4": "'người không còn bám víu vào đâu thì không có niềm vui ấy.'",
  "sn1.12:3.1": "Người có con thì lo âu vì con,",
  "sn1.12:3.2": "người có trâu bò thì cũng lo âu vì trâu bò;",
  "sn1.12:3.3": "Nỗi lo của người đời đến từ những thứ họ bám víu",
  "sn1.12:3.4": "'người không còn bám víu vào đâu thì không có nỗi lo ấy.'",
  "sn1.13:0.1": "Tương Ưng Bộ 1.13",
  "sn1.13:0.2": "2. Phẩm Vườn Hoan Hỷ",
  "sn1.13:0.3": "Kinh Không Gì Bằng Con",
  "sn1.13:1.1": "Kinh này xảy ra tại Sāvatthī (Xá-vệ).",
  "sn1.13:1.2": "Đứng một bên, vị thiên nhân đọc bài kệ này trước mặt Thế Tôn:",
  "sn1.13:2.1": "Không có tình yêu nào bằng tình yêu con,",
  "sn1.13:2.2": "không có tài sản nào bằng trâu bò;",
  "sn1.13:2.3": "Không có ánh sáng nào bằng ánh mặt trời,",
  "sn1.13:2.4": "'không có hồ nước nào bằng biển cả.'",
  "sn1.13:3.1": "Không có tình yêu nào bằng tình yêu chính mình (tự thân),",
  "sn1.13:3.2": "không có tài sản nào bằng lúa gạo (của cải thực sự);",
  "sn1.13:3.3": "Không có ánh sáng nào bằng trí tuệ (paññā),",
  "sn1.13:3.4": "'không có hồ nước nào bằng cơn mưa.'",
  "sn1.14:0.1": "Tương Ưng Bộ 1.14",
  "sn1.14:0.2": "2. Phẩm Vườn Hoan Hỷ",
  "sn1.14:0.3": "Kinh Người Sát-đế-lỵ",
  "sn1.14:1.1": "Người Sát-đế-lỵ (Khattiya) là bậc nhất trong hai chân (loài người),",
  "sn1.14:1.2": "trâu kéo cày là bậc nhất trong bốn chân (súc vật);",
  "sn1.14:1.3": "người vợ trinh khiết là bậc nhất trong các loại vợ,",
  "sn1.14:1.4": "'và con trưởng là bậc nhất trong các người con.'",
  "sn1.14:2.1": "Đức Phật Chánh Đẳng Giác (Sambuddha) là bậc nhất trong hai chân (loài người),",
  "sn1.14:2.2": "ngựa thuần chủng là bậc nhất trong bốn chân (súc vật);",
  "sn1.14:2.3": "người vợ khéo lắng nghe là bậc nhất trong các loại vợ,",
  "sn1.14:2.4": "'và người con vâng lời là bậc nhất trong các người con.'",
  "sn1.15:0.1": "Tương Ưng Bộ 1.15",
  "sn1.15:0.2": "2. Phẩm Vườn Hoan Hỷ",
  "sn1.15:0.3": "Kinh Rừng Vang Tiếng",
  "sn1.15:1.1": "Vào giữa trưa đứng bóng,",
  "sn1.15:1.2": "khi chim chóc im lặng tụ về;",
  "sn1.15:1.3": "Khu đại rừng vang rền âm thanh",
  "sn1.15:1.4": "'điều đó gợi lên trong ta **nỗi sợ hãi**.'",
  "sn1.15:2.1": "Vào giữa trưa đứng bóng,",
  "sn1.15:2.2": "khi chim chóc im lặng tụ về;",
  "sn1.15:2.3": "Khu đại rừng vang rền âm thanh",
  "sn1.15:2.4": "'điều đó gợi lên trong ta **niềm vui thích**.'",
  "sn1.16:0.1": "Tương Ưng Bộ 1.16",
  "sn1.16:0.2": "2. Phẩm Vườn Hoan Hỷ",
  "sn1.16:0.3": "Kinh Buồn Ngủ Và Uể Oải",
  "sn1.16:1.1": "Buồn ngủ, uể oải, ngáp vặt,",
  "sn1.16:1.2": "bất mãn, no nê sau bữa ăn",
  "sn1.16:1.3": "với những thứ này, con đường cao quý (Thánh Đạo)",
  "sn1.16:1.4": "'không thể tỏa sáng cho chúng sinh ở đây.'",
  "sn1.16:2.1": "Buồn ngủ, uể oải, ngáp vặt,",
  "sn1.16:2.2": "bất mãn, no nê sau bữa ăn",
  "sn1.16:2.3": "dùng tinh tấn (viriya) để xua đuổi chúng đi,",
  "sn1.16:2.4": "'thì con đường cao quý (Thánh Đạo) được thanh tịnh.'",
  "sn1.17:0.1": "Tương Ưng Bộ 1.17",
  "sn1.17:0.2": "2. Phẩm Vườn Hoan Hỷ",
  "sn1.17:0.3": "Kinh Khó Làm",
  "sn1.17:1.1": "Đời tu hành thật khó làm, khó chịu đựng,",
  "sn1.17:1.2": "đời sống xuất gia đối với kẻ chưa khéo léo thật gian nan;",
  "sn1.17:1.3": "Có rất nhiều chướng ngại trên con đường ấy",
  "sn1.17:1.4": "'đó là chỗ kẻ ngu bị chìm đắm.'",
  "sn1.17:2.1": "Bao nhiêu ngày có thể sống đời xuất gia,",
  "sn1.17:2.2": "nếu không kiểm soát được tâm?",
  "sn1.17:2.3": "Từng bước sẽ bị chìm đắm,",
  "sn1.17:2.4": "bị kéo theo bởi các tư duy (saṅkappa  suy nghĩ, ý muốn).",
  "sn1.17:3.1": "Như con rùa thu các chi vào trong mai của mình,",
  "sn1.17:3.2": "Tỳ-kheo hãy thu tâm và các tư duy vào bên trong;",
  "sn1.17:3.3": "Không nương tựa, không làm hại ai",
  "sn1.17:3.4": "'đã viên tịch (Niết-bàn), vị ấy không trách cứ ai cả.'",
  "sn1.18:0.1": "Tương Ưng Bộ 1.18",
  "sn1.18:0.2": "2. Phẩm Vườn Hoan Hỷ",
  "sn1.18:0.3": "Kinh Hổ Thẹn",
  "sn1.18:1.1": "Ở đời có người nào đó",
  "sn1.18:1.2": "được thu thúc bởi lòng hổ thẹn (hirī);",
  "sn1.18:1.3": "người ấy tránh xa điều bị chê trách",
  "sn1.18:1.4": "'như ngựa hiền lành tránh roi da.'",
  "sn1.18:2.1": "Những ai được thu thúc bởi lòng hổ thẹn, dù mỏng manh,",
  "sn1.18:2.2": "mà luôn luôn sống với chánh niệm (sati);",
  "sn1.18:2.3": "đạt đến chỗ chấm dứt khổ đau,",
  "sn1.18:2.4": "'đi trên con đường gập ghềnh mà vẫn bằng phẳng.'",
  "sn1.19:0.1": "Tương Ưng Bộ 1.19",
  "sn1.19:0.2": "2. Phẩm Vườn Hoan Hỷ",
  "sn1.19:0.3": "Kinh Túp Lều",
  "sn1.19:1.1": "Ngươi có túp lều không?",
  "sn1.19:1.2": "Ngươi có tổ chim không?",
  "sn1.19:1.3": "Ngươi có dây leo không?",
  "sn1.19:1.4": "'Ngươi đã thoát khỏi trói buộc chưa?'",
  "sn1.19:2.1": "Quả thật Ta không có túp lều,",
  "sn1.19:2.2": "quả thật Ta không có tổ chim;",
  "sn1.19:2.3": "quả thật Ta không có dây leo,",
  "sn1.19:2.4": "'quả thật Ta đã thoát khỏi trói buộc.'",
  "sn1.19:3.1": "Vậy ý ngươi nói 'túp lều' là gì?",
  "sn1.19:3.2": "Ý ngươi nói 'tổ chim' là gì?",
  "sn1.19:3.3": "Ý ngươi nói 'dây leo' là gì?",
  "sn1.19:3.4": "'Ý ngươi nói 'trói buộc' là gì?'",
  "sn1.19:4.1": "Ngươi gọi 'túp lều' là mẹ,",
  "sn1.19:4.2": "ngươi gọi 'tổ chim' là vợ;",
  "sn1.19:4.3": "ngươi gọi 'dây leo' là các con,",
  "sn1.19:4.4": "'ngươi gọi 'trói buộc' là tham ái (taṇhā).'",
  "sn1.19:5.1": "Lành thay! Ngươi không có túp lều,",
  "sn1.19:5.2": "lành thay! Ngươi không có tổ chim;",
  "sn1.19:5.3": "lành thay! Ngươi không có dây leo,",
  "sn1.19:5.4": "'lành thay! Ngươi đã thoát khỏi trói buộc.'",
  "sn1.20:0.1": "Tương Ưng Bộ 1.20",
  "sn1.20:0.2": "2. Phẩm Vườn Hoan Hỷ",
  "sn1.20:0.3": "Kinh Samiddhi",
  "sn1.20:1.1": "Tôi đã nghe như vầy",
  "sn1.20:1.2": "Một thời, Thế Tôn đang trú tại Rājagaha (Vương Xá), trong vườn suối nước nóng (Tapodārāma).",
  "sn1.20:1.3": "Khi ấy, Tôn giả Samiddhi dậy sớm lúc trời còn tối, đến suối nước nóng để tắm rửa.",
  "sn1.20:1.4": "Sau khi tắm xong, bước lên bờ, đứng mặc một tấm áo choàng, phơi khô thân mình.",
  "sn1.20:1.5": "Lúc ấy, một vị thiên nhân với hào quang rực rỡ chiếu sáng toàn bộ suối nóng, đến gặp Tôn giả Samiddhi, đứng trên không và đọc bài kệ:",
  "sn1.20:2.1": "Này Tỳ-kheo, ngươi đi khất thực khi chưa hưởng thụ gì cả,",
  "sn1.20:2.2": "chứ không phải sau khi đã hưởng thụ rồi mới đi khất thực;",
  "sn1.20:2.3": "Hãy hưởng thụ đi rồi hãy đi khất thực,",
  "sn1.20:2.4": "'đừng để thời cơ trôi qua mất.'",
  "sn1.20:3.1": "Ta không biết thời cơ ấy khi nào đến,",
  "sn1.20:3.2": "thời cơ ấy bị che giấu, không thấy được;",
  "sn1.20:3.3": "Vì vậy ta đi khất thực khi chưa hưởng thụ gì",
  "sn1.20:3.4": "'đừng để thời cơ (cái chết) trôi qua ta mất.'",
  "sn1.20:4.1": "Khi ấy, vị thiên nhân đáp xuống đất và nói với Tôn giả Samiddhi:",
  "sn1.20:4.2": "Này Tỳ-kheo, ngươi còn trẻ, xuất gia khi còn là trai trẻ tóc đen, tràn đầy sức xuân, ở độ tuổi tươi đẹp nhất  chưa từng thưởng thức các dục lạc.",
  "sn1.20:4.3": "Hãy hưởng thụ các dục lạc của con người đi, này Tỳ-kheo;",
  "sn1.20:4.4": "'đừng bỏ thứ hiện tiền để chạy theo thứ mãi về sau.'",
  "sn1.20:5.1": "Này hiền giả, chính ta không bỏ thứ hiện tiền để chạy theo thứ mãi về sau.",
  "sn1.20:5.2": "Chính ta bỏ thứ mãi về sau để chạy theo thứ hiện tiền.",
  "sn1.20:5.3": "Vì này hiền giả, Thế Tôn đã dạy rằng các dục lạc là 'mãi về sau' (kālikā)  đầy đau khổ, đầy não hại; sự nguy hiểm ở đó còn nhiều hơn nữa.",
  "sn1.20:5.4": "'Còn Pháp này là 'hiện tiền' (sandiṭṭhiko)  thấy ngay trong hiện tại, không bị thời gian giới hạn, đến để thấy, hướng vào bên trong, người trí tự mình chứng nghiệm.'",
  "sn1.20:6.1": "Nhưng này Tỳ-kheo, thế nào là dục lạc 'mãi về sau' như Thế Tôn đã dạy  đầy đau khổ, đầy não hại, sự nguy hiểm còn nhiều hơn?",
  "sn1.20:6.2": "'Và thế nào là Pháp 'hiện tiền'  thấy ngay, không bị thời gian giới hạn, đến để thấy, hướng vào trong, người trí tự chứng nghiệm?'",
  "sn1.20:7.1": "Này hiền giả, ta mới xuất gia, vừa mới đến với Pháp và Luật này.",
  "sn1.20:7.2": "Ta chưa có thể giải thích rộng rãi được.",
  "sn1.20:7.3": "Có Thế Tôn kia  bậc A-la-hán, Chánh Đẳng Giác  đang trú tại Rājagaha, trong vườn suối nước nóng.",
  "sn1.20:7.4": "Hãy đến gặp Thế Tôn và hỏi điều này.",
  "sn1.20:7.5": "'Thế Tôn giải thích thế nào thì hãy ghi nhớ như vậy.'",
  "sn1.20:8.1": "Này Tỳ-kheo, Thế Tôn đó không dễ đến gặp  vì được vây quanh bởi các thiên nhân quyền năng khác.",
  "sn1.20:8.2": "'Nhưng nếu ngươi đến gặp Thế Tôn và hỏi điều này, chúng ta cũng sẽ đến để nghe Pháp.'",
  "sn1.20:8.3": "Tôn giả Samiddhi vâng lời vị thiên nhân, đến gặp Thế Tôn, đảnh lễ rồi ngồi xuống một bên. Ngồi xong, Tôn giả Samiddhi thưa lại toàn bộ câu chuyện với Thế Tôn:",
  "sn1.20:9.1": "Bạch Thế Tôn, con dậy sớm lúc còn tối, đến suối nước nóng để tắm.",
  "sn1.20:9.2": "Sau khi tắm xong, bước lên đứng mặc một áo choàng, phơi khô thân mình.",
  "sn1.20:9.3": "Lúc đó, một vị thiên nhân hào quang rực rỡ chiếu sáng toàn bộ suối nóng, đến gặp con, đứng trên không và đọc bài kệ:",
  "sn1.20:10.1": "'Này Tỳ-kheo, ngươi đi khất thực khi chưa hưởng thụ gì cả,'",
  "sn1.20:10.2": "chứ không phải sau khi đã hưởng thụ rồi;",
  "sn1.20:10.3": "Hãy hưởng thụ đi rồi hãy đi khất thực,",
  "sn1.20:10.4": "'đừng để thời cơ trôi qua mất.'",
  "sn1.20:11.1": "Khi nghe vậy, bạch Thế Tôn, con đã đáp lại vị thiên nhân bằng bài kệ:",
  "sn1.20:12.1": "'Ta không biết thời cơ ấy khi nào đến,'",
  "sn1.20:12.2": "thời cơ bị che giấu, không thấy được;",
  "sn1.20:12.3": "Vì vậy ta đi khất thực khi chưa hưởng thụ gì",
  "sn1.20:12.4": "'đừng để thời cơ (cái chết) trôi qua ta mất.'",
  "sn1.20:13.1": "Khi ấy, bạch Thế Tôn, vị thiên nhân đáp xuống đất nói với con:",
  "sn1.20:13.2": "'Này Tỳ-kheo, ngươi còn trẻ, xuất gia khi còn trai trẻ tóc đen, tràn đầy sức xuân, ở độ tuổi tươi đẹp nhất  chưa từng thưởng thức dục lạc.'",
  "sn1.20:13.3": "Hãy hưởng thụ các dục lạc của con người đi,",
  "sn1.20:13.4": "'đừng bỏ thứ hiện tiền để chạy theo thứ mãi về sau.'",
  "sn1.20:14.1": "Khi nghe vậy, bạch Thế Tôn, con đã đáp:",
  "sn1.20:14.2": "'Này hiền giả, chính ta không bỏ thứ hiện tiền để chạy theo thứ mãi về sau;'",
  "sn1.20:14.3": "chính ta bỏ thứ mãi về sau để chạy theo thứ hiện tiền.",
  "sn1.20:14.4": "Vì Thế Tôn đã dạy dục lạc là mãi về sau  đầy đau khổ, đầy não hại; sự nguy hiểm ở đó còn nhiều.",
  "sn1.20:14.5": "'Còn Pháp này là hiện tiền  thấy ngay, không bị thời gian giới hạn, đến để thấy, hướng vào trong, người trí tự chứng nghiệm.'",
  "sn1.20:15.1": "Khi ấy, bạch Thế Tôn, vị thiên nhân hỏi con:",
  "sn1.20:15.2": "'Thế nào là dục lạc là mãi về sau  đầy đau khổ, đầy não hại?'",
  "sn1.20:15.3": "'Thế nào là Pháp hiện tiền  thấy ngay, không bị thời gian giới hạn, đến để thấy, hướng vào trong, người trí tự chứng nghiệm?'",
  "sn1.20:16.1": "Khi ấy, bạch Thế Tôn, con đã thưa:",
  "sn1.20:16.2": "'Này hiền giả, ta mới xuất gia, vừa đến với Pháp và Luật, chưa có thể giải thích rộng rãi.'",
  "sn1.20:16.3": "Có Thế Tôn  bậc A-la-hán, Chánh Đẳng Giác  đang trú tại Rājagaha.",
  "sn1.20:16.4": "Hãy đến hỏi Ngài.",
  "sn1.20:16.5": "'Ngài giải thích thế nào thì hãy ghi nhớ như vậy.'",
  "sn1.20:17.1": "Khi ấy, bạch Thế Tôn, vị thiên nhân nói:",
  "sn1.20:17.2": "'Thế Tôn không dễ đến gặp  được vây quanh bởi các thiên nhân quyền năng.'",
  "sn1.20:17.3": "'Nhưng nếu ngươi đến hỏi Thế Tôn, chúng ta cũng sẽ đến nghe Pháp.'",
  "sn1.20:17.4": "'Bạch Thế Tôn, nếu lời vị thiên nhân ấy là thật, thì vị ấy đang ở đâu đó gần đây.'",
  "sn1.20:18.1": "Khi ấy, vị thiên nhân nói với Tôn giả Samiddhi:",
  "sn1.20:18.2": "'Hỏi đi, Tỳ-kheo! Hỏi đi! Ta đã đến đây rồi.'",
  "sn1.20:19.1": "Lúc ấy, Thế Tôn đọc bài kệ cho vị thiên nhân nghe:",
  "sn1.20:20.1": "Chúng sinh có tưởng về những thứ có thể đặt tên (danh xưng),",
  "sn1.20:20.2": "họ đứng vững trên những thứ có thể đặt tên;",
  "sn1.20:20.3": "Do không thấu hiểu những thứ có thể đặt tên,",
  "sn1.20:20.4": "họ rơi vào ràng buộc của cái chết.",
  "sn1.20:21.1": "Người đã thấu hiểu hoàn toàn những thứ có thể đặt tên,",
  "sn1.20:21.2": "không nghĩ đến 'người đặt tên' (không có khái niệm về ngã);",
  "sn1.20:21.3": "Vì với họ, điều đó không tồn tại",
  "sn1.20:21.4": "không có gì để ai có thể gán vào họ;",
  "sn1.20:21.5": "'Nếu ngươi hiểu được, hãy nói đi, này thiên nhân (Yakkha)!'",
  "sn1.20:22.1": "Bạch Thế Tôn, con không hiểu được ý nghĩa đầy đủ từ lời Thế Tôn đã nói vắn tắt.",
  "sn1.20:22.2": "'Xin Thế Tôn hãy dạy theo cách con có thể hiểu được ý nghĩa đầy đủ.'",
  "sn1.20:23.1": "Ai nghĩ 'ta bằng, ta hơn, hay ta kém'",
  "sn1.20:23.2": "kẻ ấy sẽ tranh luận về điều đó;",
  "sn1.20:23.3": "Người không bị lay chuyển bởi ba loại so sánh này,",
  "sn1.20:23.4": "thì không có khái niệm 'bằng' hay 'hơn';",
  "sn1.20:23.5": "'Nếu ngươi hiểu được, hãy nói đi, này thiên nhân!'",
  "sn1.20:24.1": "Bạch Thế Tôn, con vẫn chưa hiểu được ý nghĩa đầy đủ từ lời này.",
  "sn1.20:24.2": "'Xin Thế Tôn hãy dạy theo cách con có thể hiểu được.'",
  "sn1.20:25.1": "Người đã từ bỏ mọi phân biệt, không đi vào ngã mạn (vimāna);",
  "sn1.20:25.2": "đã cắt đứt tham ái đối với danh-sắc (nāmarūpa) ở đây;",
  "sn1.20:25.3": "Người ấy  mọi trói buộc đã đứt, không còn khổ não, không còn khát vọng",
  "sn1.20:25.4": "dù chư thiên hay con người tìm kiếm cũng không gặp được;",
  "sn1.20:25.5": "Dù ở đây hay ở cõi kia,",
  "sn1.20:25.6": "hay ở các cõi trời, ở mọi chốn nương náu.",
  "sn1.20:26.1": "'Nếu ngươi hiểu được, hãy nói đi, này thiên nhân!'",
  "sn1.20:27.1": "Bạch Thế Tôn, từ lời Thế Tôn nói vắn tắt này, con hiểu ý nghĩa đầy đủ như sau",
  "sn1.20:28.1": "Đừng làm bất cứ điều ác nào bằng lời nói, tâm ý,",
  "sn1.20:28.2": "hay thân thể  dù ở bất cứ đâu trên đời;",
  "sn1.20:28.3": "Từ bỏ các dục lạc, sống chánh niệm và tỉnh giác,",
  "sn1.20:28.4": "'đừng đeo đuổi khổ đau  thứ không đem lại lợi ích.'",
  "sn1.20:28.5": "Kết thúc Phẩm Vườn Hoan Hỷ thứ hai.",
  "sn1.20:29.0": "Tóm tắt các kinh trong phẩm:",
  "sn1.20:29.1": "Vườn Hoan Hỷ, Hoan Hỷ,",
  "sn1.20:29.2": "Không Gì Bằng Con;",
  "sn1.20:29.3": "Sát-đế-lỵ, Rừng Vang Tiếng,",
  "sn1.20:29.4": "Buồn Ngủ Uể Oải, Khó Làm;",
  "sn1.20:29.5": "Hổ Thẹn, Túp Lều là thứ chín,",
  "sn1.20:29.6": "'Samiddhi được nói là thứ mười.'"
}
window.BILARA["sn1_v2"]["vi"]["sn1_v2:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com;"
