window.BILARA = window.BILARA || {};
window.BILARA["sn2_v3"] = window.BILARA["sn2_v3"] || {};
window.BILARA["sn2_v3"]["vi"] = {
  "sn2.21:0.1": "Tương Ưng Bộ Kinh 2.21",
  "sn2.21:0.2": "3. Phẩm Các Ngoại Đạo",
  "sn2.21:0.3": "Kinh Siva",
  "sn2.21:1.1": "Tôi nghe như vầy",
  "sn2.21:1.2": "Một thời, Đức Thế Tôn đang trú tại thành Sāvatthī, trong khu vườn Jetavana của ông Anāthapiṇḍika.",
  "sn2.21:1.3": "Khi ấy, thiên tử Siva, vào lúc đêm đã về khuya, với ánh hào quang rực rỡ chiếu sáng toàn khu vườn Jetavana, đến chỗ Đức Thế Tôn, đảnh lễ Ngài rồi đứng sang một bên.",
  "sn2.21:1.4": "Đứng sang một bên, thiên tử Siva đọc những bài kệ này trước mặt Đức Thế Tôn:",
  "sn2.21:2.1": "Hãy luôn gần gũi thân cận người thiện lành,",
  "sn2.21:2.2": "hãy kết bạn và giao du với người thiện lành;",
  "sn2.21:2.3": "Khi đã hiểu được Chánh pháp của bậc Hiền,",
  "sn2.21:2.4": "thì ngày càng tốt hơn chứ không xấu đi.",
  "sn2.21:3.1": "Hãy luôn gần gũi thân cận người thiện lành,",
  "sn2.21:3.2": "hãy kết bạn và giao du với người thiện lành;",
  "sn2.21:3.3": "Khi đã hiểu được Chánh pháp của bậc Hiền,",
  "sn2.21:3.4": "trí tuệ sẽ được thành tựu chứ không từ chỗ nào khác.",
  "sn2.21:4.1": "Hãy luôn gần gũi thân cận người thiện lành,",
  "sn2.21:4.2": "hãy kết bạn và giao du với người thiện lành;",
  "sn2.21:4.3": "Khi đã hiểu được Chánh pháp của bậc Hiền,",
  "sn2.21:4.4": "dù ở giữa muôn vàn khổ đau cũng không còn sầu khổ.",
  "sn2.21:5.1": "Hãy luôn gần gũi thân cận người thiện lành,",
  "sn2.21:5.2": "hãy kết bạn và giao du với người thiện lành;",
  "sn2.21:5.3": "Khi đã hiểu được Chánh pháp của bậc Hiền,",
  "sn2.21:5.4": "sẽ tỏa sáng rực rỡ giữa đám thân bằng quyến thuộc.",
  "sn2.21:6.1": "Hãy luôn gần gũi thân cận người thiện lành,",
  "sn2.21:6.2": "hãy kết bạn và giao du với người thiện lành;",
  "sn2.21:6.3": "Khi đã hiểu được Chánh pháp của bậc Hiền,",
  "sn2.21:6.4": "chúng sinh sẽ đi đến cõi lành an vui.",
  "sn2.21:7.1": "Hãy luôn gần gũi thân cận người thiện lành,",
  "sn2.21:7.2": "hãy kết bạn và giao du với người thiện lành;",
  "sn2.21:7.3": "Khi đã hiểu được Chánh pháp của bậc Hiền,",
  "sn2.21:7.4": "'chúng sinh sẽ được an trú lâu dài bền vững.'",
  "sn2.21:8.1": "Khi ấy, Đức Thế Tôn đáp lại thiên tử Siva bằng bài kệ:",
  "sn2.21:9.1": "Hãy luôn gần gũi thân cận người thiện lành,",
  "sn2.21:9.2": "hãy kết bạn và giao du với người thiện lành;",
  "sn2.21:9.3": "Khi đã hiểu được Chánh pháp của bậc Hiền,",
  "sn2.21:9.4": "'sẽ được giải thoát hoàn toàn khỏi mọi khổ đau.'",
  "sn2.22:0.1": "Tương Ưng Bộ 2.22",
  "sn2.22:0.2": "3. Phẩm Các Ngoại Đạo Khác Nhau",
  "sn2.22:0.3": "Kinh Khema",
  "sn2.22:1.1": "Thiên tử Khema đứng một bên, rồi đọc những bài kệ này trước Thế Tôn:",
  "sn2.22:2.1": "Kẻ ngu si, thiếu trí tuệ,",
  "sn2.22:2.2": "như kẻ thù của chính mình;",
  "sn2.22:2.3": "Cứ làm những việc ác,",
  "sn2.22:2.4": "gặt lấy quả đắng cay.",
  "sn2.22:3.1": "Làm việc mà sau hối hận,",
  "sn2.22:3.2": "đó không phải việc làm tốt;",
  "sn2.22:3.3": "Khi nhận quả báo, mặt đẫm lệ,",
  "sn2.22:3.4": "chỉ biết ngồi khóc than.",
  "sn2.22:4.1": "Làm việc mà sau không hối hận,",
  "sn2.22:4.2": "đó mới là việc làm tốt;",
  "sn2.22:4.3": "Khi nhận quả báo, lòng vui mừng,",
  "sn2.22:4.4": "hoan hỷ thọ nhận kết quả.",
  "sn2.22:5.1": "Hãy làm ngay từ đầu",
  "sn2.22:5.2": "điều gì biết là lợi ích cho mình;",
  "sn2.22:5.3": "Người trí không nên suy nghĩ lông bông,",
  "sn2.22:5.4": "như kẻ đánh xe bò thiếu khôn ngoan.",
  "sn2.22:6.1": "Như người đánh xe bò bỏ con đường lớn bằng phẳng,",
  "sn2.22:6.2": "rời xa đường cái rộng thênh thang;",
  "sn2.22:6.3": "Lại đi vào con đường gồ ghề khó đi,",
  "sn2.22:6.4": "trục bánh gãy, đành ngồi than thở.",
  "sn2.22:7.1": "Cũng vậy, kẻ nào bỏ chánh pháp,",
  "sn2.22:7.2": "chạy theo con đường tà pháp;",
  "sn2.22:7.3": "Kẻ ngu ấy đối mặt với thần chết,",
  "sn2.22:7.4": "'than thở như trục xe bị gãy.'",
  "sn2.23:0.1": "Tương Ưng Bộ 2.23",
  "sn2.23:0.2": "3. Phẩm Các Ngoại Đạo Khác Nhau",
  "sn2.23:0.3": "Kinh Serī",
  "sn2.23:1.1": "Thiên tử Serī đứng một bên, rồi đọc bài kệ này trước Thế Tôn:",
  "sn2.23:2.1": "Cả hai loài trời và người",
  "sn2.23:2.2": "đều vui thích với thức ăn;",
  "sn2.23:2.3": "Vậy thì có loài dạ xoa nào",
  "sn2.23:2.4": "'lại không thích thức ăn chăng?'",
  "sn2.23:3.1": "Những ai bố thí với lòng tin,",
  "sn2.23:3.2": "với tâm trong sáng, thanh tịnh;",
  "sn2.23:3.3": "Chính thức ăn ấy sẽ theo họ,",
  "sn2.23:3.4": "cả ở đời này lẫn đời sau.",
  "sn2.23:4.1": "Vì vậy hãy dẹp bỏ lòng keo kiệt,",
  "sn2.23:4.2": "hãy bố thí, vượt qua cấu uế;",
  "sn2.23:4.3": "Công đức ở cõi đời sau",
  "sn2.23:4.4": "'chính là chỗ nương tựa của chúng sinh.'",
  "sn2.23:5.1": "Thật kỳ diệu thay, bạch Thế Tôn! Thật vi diệu thay, bạch Thế Tôn!",
  "sn2.23:5.2": "Thế Tôn đã dạy thật khéo léo, bạch Thế Tôn:",
  "sn2.23:6.1": "'Những ai bố thí với lòng tin,'",
  "sn2.23:6.2": "với tâm trong sáng, thanh tịnh;",
  "sn2.23:6.3": "Chính thức ăn ấy sẽ theo họ,",
  "sn2.23:6.4": "cả ở đời này lẫn đời sau.",
  "sn2.23:7.1": "Vì vậy hãy dẹp bỏ lòng keo kiệt,",
  "sn2.23:7.2": "hãy bố thí, vượt qua cấu uế;",
  "sn2.23:7.3": "Công đức ở cõi đời sau",
  "sn2.23:7.4": "'chính là chỗ nương tựa của chúng sinh.'",
  "sn2.23:8.1": "Bạch Thế Tôn, thuở xưa con từng là vua Sirī, người hay bố thí, chủ của sự bố thí, người ca ngợi sự bố thí.",
  "sn2.23:8.2": "Bạch Thế Tôn, con đã cho bố thí ở bốn cổng thành cho các sa-môn, bà-la-môn, người nghèo, kẻ lang thang, người hành khất.",
  "sn2.23:8.3": "Bấy giờ, bạch Thế Tôn, hậu cung của con đến gặp con và thưa:",
  "sn2.23:8.4": "'Của bố thí được dâng cho bệ hạ; nhưng chúng tôi không được bố thí.'",
  "sn2.23:8.5": "'Lành thay, xin cho chúng tôi cũng được nương nhờ bệ hạ mà bố thí, làm phước.'",
  "sn2.23:8.6": "Bạch Thế Tôn, con đã suy nghĩ:",
  "sn2.23:8.7": "'Ta là người hay bố thí, chủ của sự bố thí, người ca ngợi bố thí.'",
  "sn2.23:8.8": "'Khi họ nói muốn bố thí, ta nên nói gì?'",
  "sn2.23:8.9": "Vì vậy, bạch Thế Tôn, con đã nhường cổng thứ nhất cho hậu cung.",
  "sn2.23:8.10": "Từ đó hậu cung bố thí ở đó; phần bố thí của con giảm đi.",
  "sn2.23:9.1": "Bạch Thế Tôn, rồi các vị quan tùy tùng hoàng gia đến gặp con và thưa:",
  "sn2.23:9.2": "'Của bố thí được dâng cho bệ hạ; được dâng cho hậu cung; nhưng chúng tôi không được bố thí.'",
  "sn2.23:9.3": "'Lành thay, xin cho chúng tôi cũng được nương nhờ bệ hạ mà bố thí, làm phước.'",
  "sn2.23:9.4": "Bạch Thế Tôn, con đã suy nghĩ:",
  "sn2.23:9.5": "'Ta là người hay bố thí, chủ của sự bố thí, người ca ngợi bố thí.'",
  "sn2.23:9.6": "'Khi họ nói muốn bố thí, ta nên nói gì?'",
  "sn2.23:9.7": "Vì vậy, bạch Thế Tôn, con đã nhường cổng thứ hai cho các quan tùy tùng hoàng gia.",
  "sn2.23:9.8": "Từ đó các quan tùy tùng bố thí ở đó; phần bố thí của con giảm đi.",
  "sn2.23:10.1": "Bạch Thế Tôn, rồi quân đội đến gặp con và thưa:",
  "sn2.23:10.2": "'Của bố thí được dâng cho bệ hạ; cho hậu cung; cho các quan tùy tùng; nhưng chúng tôi không được bố thí.'",
  "sn2.23:10.3": "'Lành thay, xin cho chúng tôi cũng được nương nhờ bệ hạ mà bố thí, làm phước.'",
  "sn2.23:10.4": "Bạch Thế Tôn, con đã suy nghĩ:",
  "sn2.23:10.5": "'Ta là người hay bố thí, chủ của sự bố thí, người ca ngợi bố thí.'",
  "sn2.23:10.6": "'Khi họ nói muốn bố thí, ta nên nói gì?'",
  "sn2.23:10.7": "Vì vậy, bạch Thế Tôn, con đã nhường cổng thứ ba cho quân đội.",
  "sn2.23:10.8": "Từ đó quân đội bố thí ở đó; phần bố thí của con giảm đi.",
  "sn2.23:11.1": "Bạch Thế Tôn, rồi các bà-la-môn và gia chủ đến gặp con và thưa:",
  "sn2.23:11.2": "'Của bố thí được dâng cho bệ hạ; cho hậu cung; cho các quan tùy tùng; cho quân đội; nhưng chúng tôi không được bố thí.'",
  "sn2.23:11.3": "'Lành thay, xin cho chúng tôi cũng được nương nhờ bệ hạ mà bố thí, làm phước.'",
  "sn2.23:11.4": "Bạch Thế Tôn, con đã suy nghĩ:",
  "sn2.23:11.5": "'Ta là người hay bố thí, chủ của sự bố thí, người ca ngợi bố thí.'",
  "sn2.23:11.6": "'Khi họ nói muốn bố thí, ta nên nói gì?'",
  "sn2.23:11.7": "Vì vậy, bạch Thế Tôn, con đã nhường cổng thứ tư cho các bà-la-môn và gia chủ.",
  "sn2.23:11.8": "Từ đó họ bố thí ở đó; phần bố thí của con giảm đi.",
  "sn2.23:12.1": "Bạch Thế Tôn, rồi các thị thần đến gặp con và thưa:",
  "sn2.23:12.2": "'Bây giờ không còn ai dâng của bố thí cho bệ hạ nữa.'",
  "sn2.23:12.3": "Bạch Thế Tôn, nghe vậy con đã bảo họ:",
  "sn2.23:12.4": "'Vậy thì, này các khanh, toàn bộ thuế thu từ các địa phương bên ngoài, hãy đưa một nửa vào cung, còn một nửa hãy bố thí tại chỗ đó cho các sa-môn, bà-la-môn, người nghèo, kẻ lang thang, người hành khất.'",
  "sn2.23:12.5": "Bạch Thế Tôn, với những công đức và thiện pháp đã làm trong thời gian dài như vậy, con không thể tìm thấy giới hạn của chúng",
  "sn2.23:12.6": "không biết phước đức là bao nhiêu, quả phước là bao nhiêu, sẽ ở cõi trời bao lâu.",
  "sn2.23:12.7": "Thật kỳ diệu thay, bạch Thế Tôn! Thật vi diệu thay, bạch Thế Tôn!",
  "sn2.23:12.8": "Thế Tôn đã dạy thật khéo léo, bạch Thế Tôn:",
  "sn2.23:13.1": "'Những ai bố thí với lòng tin,'",
  "sn2.23:13.2": "với tâm trong sáng, thanh tịnh;",
  "sn2.23:13.3": "Chính thức ăn ấy sẽ theo họ,",
  "sn2.23:13.4": "cả ở đời này lẫn đời sau.",
  "sn2.23:14.1": "Vì vậy hãy dẹp bỏ lòng keo kiệt,",
  "sn2.23:14.2": "hãy bố thí, vượt qua cấu uế;",
  "sn2.23:14.3": "Công đức ở cõi đời sau",
  "sn2.23:14.4": "chính là chỗ nương tựa của chúng sinh.''",
  "sn2.24:0.1": "Tương Ưng Bộ 2.24",
  "sn2.24:0.2": "3. Phẩm Các Ngoại Đạo Khác Nhau",
  "sn2.24:0.3": "Kinh Ghaṭīkāra",
  "sn2.24:1.1": "Thiên tử Ghaṭīkāra đứng một bên, rồi đọc bài kệ này trước Thế Tôn:",
  "sn2.24:2.1": "Bảy vị tỳ-kheo đã sinh lên cõi Aviha,",
  "sn2.24:2.2": "đã được giải thoát;",
  "sn2.24:2.3": "Đã đoạn trừ tham và sân,",
  "sn2.24:2.4": "'đã vượt qua sự chấp thủ ở đời.'",
  "sn2.24:3.1": "Những ai đã vượt qua bùn lầy,",
  "sn2.24:3.2": "vượt qua cõi chết rất khó vượt;",
  "sn2.24:3.3": "Những ai đã bỏ lại thân người,",
  "sn2.24:3.4": "'vượt lên đạt được sự gắn bó với cõi trời?'",
  "sn2.24:4.1": "Upaka, Palagaṇḍa,",
  "sn2.24:4.2": "và Pukkusāti  đó là ba vị;",
  "sn2.24:4.3": "Bhaddiyo, Khaṇḍadeva,",
  "sn2.24:4.4": "Bāhuragi và Saṅgiya;",
  "sn2.24:4.5": "Họ đã bỏ lại thân người,",
  "sn2.24:4.6": "'vượt lên đạt được sự gắn bó với cõi trời.'",
  "sn2.24:5.1": "Ngài nói tốt về những vị đó,",
  "sn2.24:5.2": "những người đã từ bỏ bẫy của Ma;",
  "sn2.24:5.3": "Nhờ hiểu Pháp của ai",
  "sn2.24:5.4": "'mà họ đã cắt đứt xiềng xích luân hồi?'",
  "sn2.24:6.1": "Không phải từ ai khác ngoài Thế Tôn,",
  "sn2.24:6.2": "không phải từ giáo pháp nào khác ngoài giáo pháp của Ngài;",
  "sn2.24:6.3": "Nhờ hiểu Pháp của Ngài",
  "sn2.24:6.4": "mà họ đã cắt đứt xiềng xích luân hồi.",
  "sn2.24:7.1": "Nơi mà danh và sắc",
  "sn2.24:7.2": "đều hoàn toàn chấm dứt;",
  "sn2.24:7.3": "Nhờ hiểu Pháp đó ở đây,",
  "sn2.24:7.4": "'họ đã cắt đứt xiềng xích luân hồi.'",
  "sn2.24:8.1": "Ngài nói những lời thâm sâu,",
  "sn2.24:8.2": "khó hiểu, rất khó nhận ra;",
  "sn2.24:8.3": "Nhờ hiểu Pháp của ai",
  "sn2.24:8.4": "'mà ngài nói những lời như vậy?'",
  "sn2.24:9.1": "Xưa kia ta từng là người thợ gốm,",
  "sn2.24:9.2": "tên là Ghaṭīkāra ở Vekaḷiṅga;",
  "sn2.24:9.3": "Ta phụng dưỡng cha mẹ,",
  "sn2.24:9.4": "và là cư sĩ của Đức Phật Kassapa.",
  "sn2.24:10.1": "Ta đã từ bỏ tà hạnh trong tình dục,",
  "sn2.24:10.2": "sống phạm hạnh, không tham đắm;",
  "sn2.24:10.3": "Ta từng là người đồng làng với Ngài,",
  "sn2.24:10.4": "ta từng là bạn cũ của Ngài.",
  "sn2.24:11.1": "Chính ta biết rõ những vị đó,",
  "sn2.24:11.2": "bảy vị tỳ-kheo đã được giải thoát;",
  "sn2.24:11.3": "Đã đoạn trừ tham và sân,",
  "sn2.24:11.4": "'đã vượt qua sự chấp thủ ở đời.'",
  "sn2.24:12.1": "Đúng vậy, đúng như vậy lúc bấy giờ,",
  "sn2.24:12.2": "như ngài đã nói, này Bhaggava;",
  "sn2.24:12.3": "Xưa kia đã từng là người thợ gốm,",
  "sn2.24:12.4": "tên là Ghaṭīkāra ở Vekaḷiṅga.",
  "sn2.24:13.1": "Đã phụng dưỡng cha mẹ,",
  "sn2.24:13.2": "là cư sĩ của Đức Phật Kassapa;",
  "sn2.24:13.3": "Đã từ bỏ tà hạnh trong tình dục,",
  "sn2.24:13.4": "sống phạm hạnh, không tham đắm;",
  "sn2.24:13.5": "Đã từng là người đồng làng với ta,",
  "sn2.24:13.6": "'đã từng là bạn cũ của ta.'",
  "sn2.24:14.1": "Đây là cuộc gặp gỡ của những người bạn cũ,",
  "sn2.24:14.2": "những bạn đồng hành từ thuở trước;",
  "sn2.24:14.3": "Cả hai đều đã tu tập viên mãn,",
  "sn2.24:14.4": "'đang mang thân xác cuối cùng.'",
  "sn2.25:0.1": "Tương Ưng Bộ 2.25",
  "sn2.25:0.2": "3. Phẩm Các Ngoại Đạo Khác Nhau",
  "sn2.25:0.3": "Kinh Jantu",
  "sn2.25:1.1": "Tôi đã nghe như vầy",
  "sn2.25:1.2": "Một thời, nhiều vị tỳ-kheo đang trú ở xứ Kosala, trong một am thất giữa rừng gần dãy Himalaya, nhưng các vị ấy sống buông lung, kiêu mạn, phóng túng, miệng nói không ngừng, lời lẽ tán loạn, thiếu chánh niệm, không tỉnh giác, tâm không định tĩnh, tâm ý tán loạn, các căn không thu thúc.",
  "sn2.25:2.1": "Bấy giờ, vào ngày rằm bố-tát, thiên tử Jantu đến gặp các vị tỳ-kheo đó; sau khi đến, liền đọc những bài kệ này trước các vị tỳ-kheo:",
  "sn2.25:3.1": "Xưa kia các tỳ-kheo đệ tử của Đức Phật Gotama",
  "sn2.25:3.2": "sống thật an lạc;",
  "sn2.25:3.3": "Đi khất thực không ham muốn nhiều,",
  "sn2.25:3.4": "chỗ nằm ngồi cũng không đòi hỏi;",
  "sn2.25:3.5": "Biết rõ sự vô thường của đời,",
  "sn2.25:3.6": "các vị đã chấm dứt khổ đau.",
  "sn2.25:4.1": "Nay các vị tự làm khó nuôi dưỡng cho mình,",
  "sn2.25:4.2": "như những kẻ trưởng làng ham hưởng thụ;",
  "sn2.25:4.3": "Ăn xong rồi lại ăn, rồi nằm ngủ,",
  "sn2.25:4.4": "mê mẩn, quyến luyến nhà người.",
  "sn2.25:5.1": "Chắp tay kính lễ Tăng đoàn,",
  "sn2.25:5.2": "ta nói với một số vị ở đây:",
  "sn2.25:5.3": "Những vị đó đã bị bỏ rơi, không ai nương tựa,",
  "sn2.25:5.4": "chẳng khác gì những vong hồn đói khát.",
  "sn2.25:6.1": "Những ai đang sống buông lung, phóng dật,",
  "sn2.25:6.2": "ta nói lời này là nhắm vào họ;",
  "sn2.25:6.3": "Còn những ai đang sống không buông lung, tinh tấn,",
  "sn2.25:6.4": "'ta xin kính lễ các vị đó.'",
  "sn2.26:0.1": "Tương Ưng Bộ 2.26",
  "sn2.26:0.2": "3. Phẩm Các Ngoại Đạo Khác Nhau",
  "sn2.26:0.3": "Kinh Rohitassa",
  "sn2.26:1.1": "Duyên khởi tại Sāvatthī.",
  "sn2.26:1.2": "Thiên tử Rohitassa đứng một bên, rồi thưa với Thế Tôn:",
  "sn2.26:1.3": "'Bạch Thế Tôn, có một nơi mà ở đó không có sinh, không có già, không có chết, không có mất đi, không có tái sinh  liệu có thể bằng cách đi đến đó mà biết, thấy, hay chạm tới tận cùng của thế giới không?'",
  "sn2.26:1.4": "'Này hiền giả, nơi mà ở đó không có sinh, không có già, không có chết, không có mất đi, không có tái sinh  Ta nói rằng không thể bằng cách đi đến đó mà biết, thấy, hay chạm tới tận cùng của thế giới.'",
  "sn2.26:2.1": "Thật kỳ diệu thay, bạch Thế Tôn! Thật vi diệu thay, bạch Thế Tôn!",
  "sn2.26:2.2": "Thế Tôn đã dạy thật khéo léo, bạch Thế Tôn:",
  "sn2.26:2.3": "'Này hiền giả, nơi mà ở đó không có sinh, không có già, không có chết, không có mất đi, không có tái sinh  Ta nói rằng không thể bằng cách đi đến đó mà biết, thấy, hay chạm tới tận cùng của thế giới.'",
  "sn2.26:3.1": "Bạch Thế Tôn, thuở xưa con là một vị tiên nhân tên Rohitassa, con của Bhoja, có thần thông, đi lại được trên hư không.",
  "sn2.26:3.2": "Bạch Thế Tôn, tốc độ của con lúc đó nhanh đến mức: như một cung thủ thithiện xảo, được huấn luyện tốt, tay đã quen cung, giỏi bắn  có thể dễ dàng bắn một mũi tên nhẹ bay ngang qua bóng cây thốt nốt.",
  "sn2.26:3.3": "Bạch Thế Tôn, mỗi bước chân của con lúc đó dài như từ biển Đông sang biển Tây.",
  "sn2.26:3.4": "Bạch Thế Tôn, con đã khởi lên ý muốn:",
  "sn2.26:3.5": "'Ta sẽ đi đến tận cùng của thế giới.'",
  "sn2.26:3.6": "Bạch Thế Tôn, với tốc độ như vậy và bước chân như vậy, ngoại trừ thời gian ăn uống, đại tiểu tiện, ngủ nghỉ và xua đuổi mệt mỏi  con đã sống một trăm năm, đi suốt một trăm năm, nhưng vẫn chưa chạm tới tận cùng của thế giới thì đã mạng chung giữa chừng.",
  "sn2.26:4.1": "Thật kỳ diệu thay, bạch Thế Tôn! Thật vi diệu thay, bạch Thế Tôn!",
  "sn2.26:4.2": "Thế Tôn đã dạy thật khéo léo, bạch Thế Tôn:",
  "sn2.26:4.3": "'Này hiền giả, nơi mà ở đó không có sinh, không có già, không có chết, không có mất đi, không có tái sinh  Ta nói rằng không thể bằng cách đi đến đó mà biết, thấy, hay chạm tới tận cùng của thế giới.''",
  "sn2.26:5.1": "Này hiền giả, Ta không nói rằng phải đi đến tận cùng của thế giới thì mới chấm dứt được khổ đau.",
  "sn2.26:5.2": "Nhưng Ta nói rằng, chính trong thân này  dài chừng một sải tay, có tri giác, có ý thức  Ta tuyên bố về thế giới, về sự sinh khởi của thế giới, về sự chấm dứt của thế giới, và con đường dẫn đến sự chấm dứt của thế giới.",
  "sn2.26:6.1": "Không thể bằng cách đi mà đến được,",
  "sn2.26:6.2": "tận cùng của thế giới bất kỳ lúc nào;",
  "sn2.26:6.3": "Mà không đến được tận cùng thế giới,",
  "sn2.26:6.4": "thì không thể thoát khỏi khổ đau.",
  "sn2.26:7.1": "Vì vậy, bậc trí tuệ hiểu rõ thế giới,",
  "sn2.26:7.2": "đã đến tận cùng thế giới, sống phạm hạnh viên mãn;",
  "sn2.26:7.3": "Biết rõ tận cùng của thế giới, an tịnh,",
  "sn2.26:7.4": "'không còn mong cầu đời này hay đời sau.'",
  "sn2.27:0.1": "Tương Ưng Bộ 2.27",
  "sn2.27:0.2": "3. Phẩm Các Ngoại Đạo Khác Nhau",
  "sn2.27:0.3": "Kinh Nanda",
  "sn2.27:1.1": "Thiên tử Nanda đứng một bên, rồi đọc bài kệ này trước Thế Tôn:",
  "sn2.27:2.1": "Thời gian trôi qua, đêm tháng lướt nhanh,",
  "sn2.27:2.2": "Tuổi xuân dần dần bị bỏ lại phía sau;",
  "sn2.27:2.3": "Nhìn thấy hiểm nguy của cái chết đang đến,",
  "sn2.27:2.4": "'Hãy làm các việc phước đức để mang lại an lạc.'",
  "sn2.27:3.1": "Thời gian trôi qua, đêm tháng lướt nhanh,",
  "sn2.27:3.2": "Tuổi xuân dần dần bị bỏ lại phía sau;",
  "sn2.27:3.3": "Nhìn thấy hiểm nguy của cái chết đang đến,",
  "sn2.27:3.4": "'Người cầu an tịnh hãy buông bỏ mọi cám dỗ ở đời.'",
  "sn2.28:0.1": "Tương Ưng Bộ 2.28",
  "sn2.28:0.2": "3. Phẩm Các Ngoại Đạo Khác Nhau",
  "sn2.28:0.3": "Kinh Nandivisāla",
  "sn2.28:1.1": "Thiên tử Nandivisāla đứng một bên, rồi đọc bài kệ này trước Thế Tôn:",
  "sn2.28:2.1": "Thân này có bốn bánh xe, chín cửa,",
  "sn2.28:2.2": "đầy ắp, bị tham lam trói buộc;",
  "sn2.28:2.3": "Sinh ra từ vũng bùn, hỡi bậc Đại Hùng,",
  "sn2.28:2.4": "'làm thế nào để thoát ra được?'",
  "sn2.28:3.1": "Hãy chặt đứt dây trói và dây da,",
  "sn2.28:3.2": "và cả lòng ham muốn, tham lam xấu ác;",
  "sn2.28:3.3": "Nhổ tận gốc rễ khát ái,",
  "sn2.28:3.4": "'làm được như vậy thì sẽ thoát ra được.'",
  "sn2.29:0.1": "Tương Ưng Bộ 2.29",
  "sn2.29:0.2": "3. Phẩm Các Ngoại Đạo Khác Nhau",
  "sn2.29:0.3": "Kinh Susima",
  "sn2.29:1.1": "Duyên khởi tại Sāvatthī.",
  "sn2.29:1.2": "Bấy giờ, Tôn giả Ānanda đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Khi Tôn giả Ānanda đang ngồi một bên, Thế Tôn hỏi:",
  "sn2.29:1.3": "'Này Ānanda, ông có ưa thích Sāriputta không?'",
  "sn2.29:2.1": "Bạch Thế Tôn, người nào không ngu si, không sân hận, không si mê, không tâm ý điên đảo mà lại không ưa thích Tôn giả Sāriputta?",
  "sn2.29:2.2": "Bạch Thế Tôn, Tôn giả Sāriputta là người có trí tuệ.",
  "sn2.29:2.3": "Bạch Thế Tôn, Tôn giả Sāriputta có trí tuệ rộng lớn.",
  "sn2.29:2.4": "Bạch Thế Tôn, Tôn giả Sāriputta có trí tuệ bao la.",
  "sn2.29:2.5": "Bạch Thế Tôn, Tôn giả Sāriputta có trí tuệ nhanh nhẹn, hoan hỷ.",
  "sn2.29:2.6": "Bạch Thế Tôn, Tôn giả Sāriputta có trí tuệ mau lẹ.",
  "sn2.29:2.7": "Bạch Thế Tôn, Tôn giả Sāriputta có trí tuệ sắc bén.",
  "sn2.29:2.8": "Bạch Thế Tôn, Tôn giả Sāriputta có trí tuệ thấu suốt.",
  "sn2.29:2.9": "Bạch Thế Tôn, Tôn giả Sāriputta ít ham muốn.",
  "sn2.29:2.10": "Bạch Thế Tôn, Tôn giả Sāriputta biết đủ, luôn hài lòng.",
  "sn2.29:2.11": "Bạch Thế Tôn, Tôn giả Sāriputta ưa sống một mình, ẩn dật.",
  "sn2.29:2.12": "Bạch Thế Tôn, Tôn giả Sāriputta không thích giao du ồn ào.",
  "sn2.29:2.13": "Bạch Thế Tôn, Tôn giả Sāriputta tinh tấn, nỗ lực.",
  "sn2.29:2.14": "Bạch Thế Tôn, Tôn giả Sāriputta hay chỉ dạy người khác.",
  "sn2.29:2.15": "Bạch Thế Tôn, Tôn giả Sāriputta nhẫn nhục, chịu đựng lời nói.",
  "sn2.29:2.16": "Bạch Thế Tôn, Tôn giả Sāriputta hay khuyến khích, nhắc nhở người khác.",
  "sn2.29:2.17": "Bạch Thế Tôn, Tôn giả Sāriputta hay quở trách điều ác.",
  "sn2.29:2.18": "'Bạch Thế Tôn, người nào không ngu si, không sân hận, không si mê, không tâm ý điên đảo mà lại không ưa thích Tôn giả Sāriputta?'",
  "sn2.29:3.1": "Đúng vậy, Ānanda! Đúng vậy, Ānanda!",
  "sn2.29:3.2": "Này Ānanda, người nào không ngu si, không sân hận, không si mê, không tâm ý điên đảo mà lại không ưa thích Sāriputta?",
  "sn2.29:3.3": "Này Ānanda, Sāriputta là người có trí tuệ.",
  "sn2.29:3.4": "Này Ānanda, Sāriputta có trí tuệ rộng lớn.",
  "sn2.29:3.5": "Này Ānanda, Sāriputta có trí tuệ bao la.",
  "sn2.29:3.6": "Này Ānanda, Sāriputta có trí tuệ nhanh nhẹn, hoan hỷ.",
  "sn2.29:3.7": "Này Ānanda, Sāriputta có trí tuệ mau lẹ.",
  "sn2.29:3.8": "Này Ānanda, Sāriputta có trí tuệ sắc bén.",
  "sn2.29:3.9": "Này Ānanda, Sāriputta có trí tuệ thấu suốt.",
  "sn2.29:3.10": "Này Ānanda, Sāriputta ít ham muốn.",
  "sn2.29:3.11": "Này Ānanda, Sāriputta biết đủ, luôn hài lòng.",
  "sn2.29:3.12": "Này Ānanda, Sāriputta ưa sống một mình, ẩn dật.",
  "sn2.29:3.13": "Này Ānanda, Sāriputta không thích giao du ồn ào.",
  "sn2.29:3.14": "Này Ānanda, Sāriputta tinh tấn, nỗ lực.",
  "sn2.29:3.15": "Này Ānanda, Sāriputta hay chỉ dạy người khác.",
  "sn2.29:3.16": "Này Ānanda, Sāriputta nhẫn nhục, chịu đựng lời nói.",
  "sn2.29:3.17": "Này Ānanda, Sāriputta hay khuyến khích, nhắc nhở người khác.",
  "sn2.29:3.18": "Này Ānanda, Sāriputta hay quở trách điều ác.",
  "sn2.29:3.19": "'Này Ānanda, người nào không ngu si, không sân hận, không si mê, không tâm ý điên đảo mà lại không ưa thích Sāriputta?'",
  "sn2.29:4.1": "Bấy giờ, đang khi nghe những lời tán thán Tôn giả Sāriputta, thiên tử Susima cùng với đại chúng thiên tử đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi đứng sang một bên. Thiên tử Susima đứng một bên, thưa với Thế Tôn:",
  "sn2.29:5.1": "Đúng vậy, bạch Thế Tôn! Đúng vậy, bạch Thiện Thệ!",
  "sn2.29:5.2": "Bạch Thế Tôn, người nào không ngu si, không sân hận, không si mê, không tâm ý điên đảo mà lại không ưa thích Tôn giả Sāriputta?",
  "sn2.29:5.3": "Bạch Thế Tôn, Tôn giả Sāriputta là người có trí tuệ.",
  "sn2.29:5.4": "Bạch Thế Tôn, Tôn giả Sāriputta có trí tuệ rộng lớn, bao la, nhanh nhẹn hoan hỷ, mau lẹ, sắc bén, thấu suốt; ít ham muốn, biết đủ, ưa sống ẩn dật, không thích ồn ào, tinh tấn, hay chỉ dạy, nhẫn nhục, hay nhắc nhở và quở trách điều ác.",
  "sn2.29:5.5": "Bạch Thế Tôn, người nào không ngu si, không sân hận, không si mê, không tâm ý điên đảo mà lại không ưa thích Tôn giả Sāriputta?",
  "sn2.29:6.1": "Bạch Thế Tôn, dù con đến hội chúng thiên tử nào, con cũng thường nghe tiếng khen rằng:",
  "sn2.29:6.2": "'Tôn giả Sāriputta là người có trí tuệ;'",
  "sn2.29:6.3": "'Tôn giả có trí tuệ rộng lớn, bao la, nhanh nhẹn hoan hỷ, mau lẹ, sắc bén, thấu suốt; ít ham muốn, biết đủ, ưa sống ẩn dật, không thích ồn ào, tinh tấn, hay chỉ dạy, nhẫn nhục, hay nhắc nhở và quở trách điều ác.'",
  "sn2.29:6.4": "'Bạch Thế Tôn, người nào không ngu si, không sân hận, không si mê, không tâm ý điên đảo mà lại không ưa thích Tôn giả Sāriputta?'",
  "sn2.29:7.1": "Bấy giờ, đang khi nghe những lời tán thán Tôn giả Sāriputta, đại chúng thiên tử của thiên tử Susima đều hoan hỷ, vui mừng, phấn khởi, tỏa ra nhiều màu sắc ánh sáng rực rỡ khác nhau.",
  "sn2.29:8.1": "Ví như viên ngọc lưu ly quý giá, trong sáng, có tám mặt, được mài giũa khéo léo, đặt trên tấm vải vàng, tỏa sáng, chiếu sáng và rực rỡ;",
  "sn2.29:8.2": "cũng vậy, đại chúng thiên tử của thiên tử Susima, khi nghe lời tán thán Tôn giả Sāriputta, đều hoan hỷ, vui mừng, phấn khởi, tỏa ra nhiều màu sắc ánh sáng rực rỡ khác nhau.",
  "sn2.29:9.1": "Ví như vàng ròng Jambonada được người thợ kim hoàn khéo tay dùng lò lửa nung nấu, đặt trên tấm vải vàng, tỏa sáng, chiếu sáng và rực rỡ;",
  "sn2.29:9.2": "cũng vậy, đại chúng thiên tử của thiên tử Susima, khi nghe lời tán thán Tôn giả Sāriputta, đều hoan hỷ, vui mừng, phấn khởi, tỏa ra nhiều màu sắc ánh sáng rực rỡ khác nhau.",
  "sn2.29:10.1": "Ví như vào mùa thu, bầu trời quang đãng không mây, vào lúc gần sáng, ngôi sao Osadhī tỏa sáng, chiếu sáng và rực rỡ;",
  "sn2.29:10.2": "cũng vậy, đại chúng thiên tử của thiên tử Susima, khi nghe lời tán thán Tôn giả Sāriputta, đều hoan hỷ, vui mừng, phấn khởi, tỏa ra nhiều màu sắc ánh sáng rực rỡ khác nhau.",
  "sn2.29:11.1": "Ví như vào mùa thu, bầu trời quang đãng không mây, mặt trời mọc lên xua tan mọi bóng tối trên bầu trời, tỏa sáng, chiếu sáng và rực rỡ;",
  "sn2.29:11.2": "cũng vậy, đại chúng thiên tử của thiên tử Susima, khi nghe lời tán thán Tôn giả Sāriputta, đều hoan hỷ, vui mừng, phấn khởi, tỏa ra nhiều màu sắc ánh sáng rực rỡ khác nhau.",
  "sn2.29:12.1": "Bấy giờ thiên tử Susima đọc bài kệ này trước Thế Tôn về Tôn giả Sāriputta:",
  "sn2.29:13.1": "Được mọi người biết đến là bậc có trí tuệ,",
  "sn2.29:13.2": "Sāriputta không có sân hận;",
  "sn2.29:13.3": "Ít ham muốn, hiền hòa, đã điều phục,",
  "sn2.29:13.4": "'vị ẩn sĩ được Bậc Đạo Sư khen ngợi.'",
  "sn2.29:14.1": "Bấy giờ Thế Tôn đáp lại thiên tử Susima bằng bài kệ về Tôn giả Sāriputta:",
  "sn2.29:15.1": "Được mọi người biết đến là bậc có trí tuệ,",
  "sn2.29:15.2": "Sāriputta không có sân hận;",
  "sn2.29:15.3": "Ít ham muốn, hiền hòa, đã điều phục,",
  "sn2.29:15.4": "'đã khéo điều phục, chờ đợi giờ phút ra đi.'",
  "sn2.30:0.1": "Tương Ưng Bộ 2.30",
  "sn2.30:0.2": "3. Phẩm Các Ngoại Đạo Khác Nhau",
  "sn2.30:0.3": "Kinh Các Đệ Tử Ngoại Đạo",
  "sn2.30:1.1": "Tôi đã nghe như vầy",
  "sn2.30:1.2": "Một thời, Thế Tôn đang trú tại Rājagaha, trong rừng Trúc Lâm, vườn nuôi sóc.",
  "sn2.30:1.3": "Bấy giờ, nhiều thiên tử vốn là đệ tử của các ngoại đạo  gồm Asama, Sahali, Nīka, Ākoṭaka, Vegabbhari và Māṇavagāmiya  vào lúc đêm khuya, với ánh sáng rực rỡ chiếu sáng khắp rừng Trúc Lâm, đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi đứng sang một bên.",
  "sn2.30:1.4": "Thiên tử Asama đứng một bên, liền đọc bài kệ này trước Thế Tôn về Pūraṇa Kassapa:",
  "sn2.30:2.1": "Ở đây, dù có giết chóc hay chặt đứt,",
  "sn2.30:2.2": "dù có hủy diệt sinh linh  Kassapa",
  "sn2.30:2.3": "không thấy đó là tội ác,",
  "sn2.30:2.4": "cũng không thấy đó là công đức của mình;",
  "sn2.30:2.5": "Vị ấy thực sự đã tuyên bố điều đáng tin cậy,",
  "sn2.30:2.6": "'bậc Đạo Sư như vậy xứng đáng được tôn kính.'",
  "sn2.30:3.1": "Rồi thiên tử Sahali đọc bài kệ này trước Thế Tôn về Makkali Gosāla:",
  "sn2.30:4.1": "Tự thu thúc bằng khổ hạnh và biết ghê tởm tội lỗi,",
  "sn2.30:4.2": "từ bỏ lời nói tranh cãi với mọi người;",
  "sn2.30:4.3": "Tránh xa lời nói hai chiều, luôn nói thật,",
  "sn2.30:4.4": "'người như vậy chắc chắn không làm điều ác.'",
  "sn2.30:5.1": "Rồi thiên tử Nīka đọc bài kệ này trước Thế Tôn về Nigaṇṭha Nāṭaputta:",
  "sn2.30:6.1": "Vị tỳ-kheo biết ghê tởm tội lỗi, có trí tuệ,",
  "sn2.30:6.2": "thu thúc tốt bằng bốn điều kiêng giữ;",
  "sn2.30:6.3": "Giảng dạy những gì đã thấy và đã nghe,",
  "sn2.30:6.4": "'người như vậy chắc chắn không có tội lỗi.'",
  "sn2.30:7.1": "Rồi thiên tử Ākoṭaka đọc bài kệ này trước Thế Tôn về các ngoại đạo:",
  "sn2.30:8.1": "Pakudha Kaccāyana, Nigaṇṭha,",
  "sn2.30:8.2": "và cả Makkali, Pūraṇa nữa;",
  "sn2.30:8.3": "Những vị lãnh đạo giáo đoàn, đạt được quả sa-môn,",
  "sn2.30:8.4": "'chắc chắn không phải là xa cách bậc chân nhân.'",
  "sn2.30:9.1": "Bấy giờ thiên tử Vegabbhari đáp lại thiên tử Ākoṭaka bằng bài kệ:",
  "sn2.30:10.1": "Con chó rừng hèn mọn dù sống cùng bầy sư tử,",
  "sn2.30:10.2": "cũng không bao giờ sánh bằng sư tử;",
  "sn2.30:10.3": "Kẻ lõa thể, nói dối, lãnh đạo giáo đoàn,",
  "sn2.30:10.4": "'hành xử đáng ngờ vực  không thể so với bậc chân nhân.'",
  "sn2.30:11.1": "Bấy giờ Ác ma nhập vào thiên tử Vegabbhari rồi đọc bài kệ này trước Thế Tôn:",
  "sn2.30:12.1": "Những ai chuyên tâm khổ hạnh và ghê tởm tội lỗi,",
  "sn2.30:12.2": "gìn giữ sự sống độc cư;",
  "sn2.30:12.3": "Những ai đắm chìm trong sắc pháp,",
  "sn2.30:12.4": "vui thích với cõi trời;",
  "sn2.30:12.5": "Họ thực sự chỉ dạy đúng đắn,",
  "sn2.30:12.6": "'theo tiêu chuẩn của đời sau.'",
  "sn2.30:13.1": "Bấy giờ Thế Tôn nhận ra 'Đây là Ác ma' liền đáp lại Ác ma bằng bài kệ:",
  "sn2.30:14.1": "Bất kỳ các sắc pháp nào ở đây hay ở kia,",
  "sn2.30:14.2": "hay những gì sáng rực trong hư không;",
  "sn2.30:14.3": "Tất cả đều là những thứ được Namucī  Ác ma  ca ngợi,",
  "sn2.30:14.4": "'như mồi câu được ném xuống để giết cá.'",
  "sn2.30:15.1": "Rồi thiên tử Māṇavagāmiya đọc những bài kệ này trước Thế Tôn về Thế Tôn:",
  "sn2.30:16.1": "Vipula được gọi là ngọn núi tốt nhất",
  "sn2.30:16.2": "của người dân Rājagaha;",
  "sn2.30:16.3": "Seta là ngọn núi tốt nhất trong dãy Himalaya,",
  "sn2.30:16.4": "Mặt trời là tốt nhất trong các thiên thể chiếu sáng.",
  "sn2.30:17.1": "Biển cả là tốt nhất trong các vùng nước,",
  "sn2.30:17.2": "Mặt trăng là tốt nhất trong các vì sao;",
  "sn2.30:17.3": "Còn trong toàn thế giới cùng với cõi trời,",
  "sn2.30:17.4": "'Đức Phật được gọi là tối thượng.'",
  "sn2.30:17.5": "Phẩm Các Ngoại Đạo Khác Nhau, phẩm thứ ba.",
  "sn2.30:18.0": "Tóm lược phẩm này:",
  "sn2.30:18.1": "Siva, Khema, Serī,",
  "sn2.30:18.2": "Ghaṭī, Jantu và Rohita;",
  "sn2.30:18.3": "Nanda, Nandivisāla,",
  "sn2.30:18.4": "Susima và bài kinh Ngoại Đạo  mười bài kệ này.",
  "sn2.30:18.5": "Tương Ưng Thiên Tử đã hoàn tất."
}
window.BILARA["sn2_v3"]["vi"]["sn2_v3:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com";
