window.BILARA = window.BILARA || {};
window.BILARA["sn3_v1"] = window.BILARA["sn3_v1"] || {};
window.BILARA["sn3_v1"]["vi"] = {
  "sn3.21:0.1": "Tương Ưng Bộ Kinh 3.21",
  "sn3.21:0.2": "Chương 3. Phẩm Thứ Ba",
  "sn3.21:0.3": "Kinh Bốn Hạng Người (Puggalasutta)",
  "sn3.21:1.1": "Nhân duyên tại thành Xá-vệ.",
  "sn3.21:1.2": "Một hôm, vua Ba-tư-nặc xứ Kosala đến chỗ Thế Tôn, đảnh lễ rồi ngồi sang một bên. Thế Tôn nói với vua rằng:",
  "sn3.21:1.3": "Này Đại vương, có bốn hạng người này đang hiện diện trong thế gian.",
  "sn3.21:1.4": "Bốn hạng đó là gì?",
  "sn3.21:1.5": "Người từ tối đi vào tối,",
  "sn3.21:1.6": "người từ tối đi đến sáng,",
  "sn3.21:1.7": "người từ sáng đi vào tối,",
  "sn3.21:1.8": "người từ sáng đi đến sáng.",
  "sn3.21:2.1": "Thế nào là người từ tối đi vào tối, Đại vương?",
  "sn3.21:2.2": "Ở đây, Đại vương, có người sinh ra trong gia đình thấp kém  gia đình người hốt rác, người đan rổ, người săn bắt, người thợ xe, hay người làm thuê nghèo hèn  thiếu ăn thiếu uống, sống vô cùng cực khổ, kiếm miếng cơm manh áo còn khó.",
  "sn3.21:2.3": "Lại còn xấu xí, khó coi, còm cõi, hay bệnh tật  mù, tàn tật, què quặt, hay liệt nửa người  không có được cơm ăn, nước uống, áo mặc, xe cộ, hoa thơm, dầu thoa, chỗ ngủ, nhà ở, đèn đuốc.",
  "sn3.21:2.4": "Người ấy lại còn làm điều xấu bằng thân, nói điều xấu bằng lời, nghĩ điều xấu bằng tâm.",
  "sn3.21:2.5": "Do làm ác bằng thân, lời và tâm như vậy, sau khi chết, người ấy đọa vào cõi dữ, địa ngục.",
  "sn3.21:3.1": "Ví như, Đại vương, người từ chỗ tối bước vào chỗ tối hơn, từ bóng tối này lao vào bóng tối khác, từ vũng bùn này lún xuống vũng bùn khác.",
  "sn3.21:3.2": "Thế Tôn ví người ấy như vậy.",
  "sn3.21:3.3": "Đó là hạng người từ tối đi vào tối.",
  "sn3.21:4.1": "Thế nào là người từ tối đi đến sáng, Đại vương?",
  "sn3.21:4.2": "Ở đây, Đại vương, có người sinh ra trong gia đình thấp kém  gia đình người hốt rác, người đan rổ, người săn bắt, người thợ xe, hay người làm thuê nghèo hèn  thiếu ăn thiếu uống, sống vô cùng cực khổ, kiếm miếng cơm manh áo còn khó.",
  "sn3.21:4.3": "Lại còn xấu xí, khó coi, còm cõi, hay bệnh tật  mù, tàn tật, què quặt, hay liệt nửa người  không có được cơm ăn, nước uống, áo mặc, xe cộ, hoa thơm, dầu thoa, chỗ ngủ, nhà ở, đèn đuốc.",
  "sn3.21:4.4": "Nhưng người ấy lại làm điều tốt bằng thân, nói điều tốt bằng lời, nghĩ điều tốt bằng tâm.",
  "sn3.21:4.5": "Do làm lành bằng thân, lời và tâm như vậy, sau khi chết, người ấy được sanh lên cõi lành, cõi trời.",
  "sn3.21:5.1": "Ví như, Đại vương, người từ mặt đất bước lên giường, từ giường leo lên lưng ngựa, từ lưng ngựa leo lên lưng voi, từ lưng voi leo lên đài cao.",
  "sn3.21:5.2": "Thế Tôn ví người ấy như vậy.",
  "sn3.21:5.3": "Đó là hạng người từ tối đi đến sáng.",
  "sn3.21:6.1": "Thế nào là người từ sáng đi vào tối, Đại vương?",
  "sn3.21:6.2": "Ở đây, Đại vương, có người sinh ra trong gia đình cao quý  dòng dõi vua chúa, Bà-la-môn danh giá, hay gia đình trưởng giả giàu có  nhiều tiền của, vàng bạc, tài sản, lúa gạo dồi dào.",
  "sn3.21:6.3": "Lại còn đẹp đẽ, dễ nhìn, duyên dáng, nhan sắc rực rỡ; có đầy đủ cơm ăn, nước uống, áo mặc, xe cộ, hoa thơm, dầu thoa, chỗ ngủ, nhà ở, đèn đuốc.",
  "sn3.21:6.4": "Thế nhưng người ấy lại làm điều xấu bằng thân, nói điều xấu bằng lời, nghĩ điều xấu bằng tâm.",
  "sn3.21:6.5": "Do làm ác bằng thân, lời và tâm như vậy, sau khi chết, người ấy đọa vào cõi dữ, địa ngục.",
  "sn3.21:7.1": "Ví như, Đại vương, người từ đài cao bước xuống lưng voi, từ lưng voi xuống lưng ngựa, từ lưng ngựa xuống giường, từ giường xuống đất, từ đất bước vào bóng tối.",
  "sn3.21:7.2": "Thế Tôn ví người ấy như vậy.",
  "sn3.21:7.3": "Đó là hạng người từ sáng đi vào tối.",
  "sn3.21:8.1": "Thế nào là người từ sáng đi đến sáng, Đại vương?",
  "sn3.21:8.2": "Ở đây, Đại vương, có người sinh ra trong gia đình cao quý  dòng dõi vua chúa, Bà-la-môn danh giá, hay gia đình trưởng giả giàu có  nhiều tiền của, vàng bạc, tài sản, lúa gạo dồi dào.",
  "sn3.21:8.3": "Lại còn đẹp đẽ, dễ nhìn, duyên dáng, nhan sắc rực rỡ; có đầy đủ cơm ăn, nước uống, áo mặc, xe cộ, hoa thơm, dầu thoa, chỗ ngủ, nhà ở, đèn đuốc.",
  "sn3.21:8.4": "Và người ấy cũng làm điều tốt bằng thân, nói điều tốt bằng lời, nghĩ điều tốt bằng tâm.",
  "sn3.21:8.5": "Do làm lành bằng thân, lời và tâm như vậy, sau khi chết, người ấy được sanh lên cõi lành, cõi trời.",
  "sn3.21:9.1": "Ví như, Đại vương, người từ đài cao này bước sang đài cao khác, từ lưng voi này sang lưng voi khác, từ lưng ngựa này sang lưng ngựa khác, từ giường này sang giường khác.",
  "sn3.21:9.2": "Thế Tôn ví người ấy như vậy.",
  "sn3.21:9.3": "Đó là hạng người từ sáng đi đến sáng.",
  "sn3.21:9.4": "'Này Đại vương, đó là bốn hạng người đang hiện diện trong thế gian.'",
  "sn3.21:9.5": "Đó là điều Thế Tôn nói...",
  "sn3.21:10.1": "Người nghèo, thưa Đại vương,",
  "sn3.21:10.2": "không có lòng tin, lại keo kiệt bủn xỉn;",
  "sn3.21:10.3": "Tâm địa xấu xa, toan tính điều ác,",
  "sn3.21:10.4": "tà kiến, không biết kính trọng ai.",
  "sn3.21:11.1": "Gặp Sa-môn hay Bà-la-môn,",
  "sn3.21:11.2": "hay người ăn xin khác,",
  "sn3.21:11.3": "Thì chửi mắng, xỉ nhục họ,",
  "sn3.21:11.4": "phủ nhận mọi thứ, đầy sân hận.",
  "sn3.21:12.1": "Ngăn cản người khác bố thí,",
  "sn3.21:12.2": "không cho kẻ đói được ăn;",
  "sn3.21:12.3": "Người như vậy, thưa Đại vương,",
  "sn3.21:12.4": "khi mạng chung, hỡi bậc trị vì;",
  "sn3.21:12.5": "Đi thẳng vào địa ngục khủng khiếp",
  "sn3.21:12.6": "từ tối đi vào tối.",
  "sn3.21:13.1": "Người nghèo, thưa Đại vương,",
  "sn3.21:13.2": "có lòng tin, không keo kiệt;",
  "sn3.21:13.3": "Sẵn lòng bố thí, tâm thiện lành,",
  "sn3.21:13.4": "tâm trí thản nhiên, không tán loạn.",
  "sn3.21:14.1": "Gặp Sa-môn hay Bà-la-môn,",
  "sn3.21:14.2": "hay người ăn xin khác,",
  "sn3.21:14.3": "Đứng dậy cung kính chào hỏi,",
  "sn3.21:14.4": "tu tập theo hạnh bình đẳng.",
  "sn3.21:15.1": "Không ngăn cản người khác bố thí,",
  "sn3.21:15.2": "sẵn lòng cho kẻ đói được ăn;",
  "sn3.21:15.3": "Người như vậy, thưa Đại vương,",
  "sn3.21:15.4": "khi mạng chung, hỡi bậc trị vì;",
  "sn3.21:15.5": "Được sanh lên cõi trời an lành",
  "sn3.21:15.6": "từ tối đi đến sáng.",
  "sn3.21:16.1": "Người giàu có, thưa Đại vương,",
  "sn3.21:16.2": "không có lòng tin, lại keo kiệt bủn xỉn;",
  "sn3.21:16.3": "Tâm địa xấu xa, toan tính điều ác,",
  "sn3.21:16.4": "tà kiến, không biết kính trọng ai.",
  "sn3.21:17.1": "Gặp Sa-môn hay Bà-la-môn,",
  "sn3.21:17.2": "hay người ăn xin khác,",
  "sn3.21:17.3": "Thì chửi mắng, xỉ nhục họ,",
  "sn3.21:17.4": "phủ nhận mọi thứ, đầy sân hận.",
  "sn3.21:18.1": "Ngăn cản người khác bố thí,",
  "sn3.21:18.2": "không cho kẻ đói được ăn;",
  "sn3.21:18.3": "Người như vậy, thưa Đại vương,",
  "sn3.21:18.4": "khi mạng chung, hỡi bậc trị vì;",
  "sn3.21:18.5": "Đi thẳng vào địa ngục khủng khiếp",
  "sn3.21:18.6": "từ sáng đi vào tối.",
  "sn3.21:19.1": "Người giàu có, thưa Đại vương,",
  "sn3.21:19.2": "có lòng tin, không keo kiệt;",
  "sn3.21:19.3": "Sẵn lòng bố thí, tâm thiện lành,",
  "sn3.21:19.4": "tâm trí thản nhiên, không tán loạn.",
  "sn3.21:20.1": "Gặp Sa-môn hay Bà-la-môn,",
  "sn3.21:20.2": "hay người ăn xin khác,",
  "sn3.21:20.3": "Đứng dậy cung kính chào hỏi,",
  "sn3.21:20.4": "tu tập theo hạnh bình đẳng.",
  "sn3.21:21.1": "Không ngăn cản người khác bố thí,",
  "sn3.21:21.2": "sẵn lòng cho kẻ đói được ăn;",
  "sn3.21:21.3": "Người như vậy, thưa Đại vương,",
  "sn3.21:21.4": "khi mạng chung, hỡi bậc trị vì;",
  "sn3.21:21.5": "Được sanh lên cõi trời an lành",
  "sn3.21:21.6": "'từ sáng đi đến sáng.'",
  "sn3.22:0.1": "Tương Ưng Bộ Kinh 3.22",
  "sn3.22:0.2": "Chương 3. Phẩm Thứ Ba",
  "sn3.22:0.3": "Kinh Bà Nội (Ayyikāsutta)",
  "sn3.22:1.1": "Nhân duyên tại thành Xá-vệ.",
  "sn3.22:1.2": "Vua Ba-tư-nặc xứ Kosala ngồi sang một bên, Thế Tôn hỏi rằng:",
  "sn3.22:1.3": "'Này Đại vương, giữa ban ngày như vầy mà Ngài từ đâu đến vậy?'",
  "sn3.22:2.1": "Bạch Thế Tôn, bà nội của trẫm vừa mới qua đời. Bà đã già lão, cao tuổi, sống lâu, đã đi hết đoạn đường đời, thọ đến một trăm hai mươi tuổi.",
  "sn3.22:2.2": "Bạch Thế Tôn, bà nội là người trẫm hết mực thương yêu, trân quý.",
  "sn3.22:2.3": "Nếu có ai nói rằng: 'Hãy dâng báu vật voi chúa, thì bà nội Ngài sẽ không chết'  thì trẫm cũng sẵn sàng dâng báu vật voi chúa ấy,",
  "sn3.22:2.4": "chỉ để bà nội không phải qua đời.",
  "sn3.22:2.5": "Nếu có ai nói rằng: 'Hãy dâng báu vật ngựa chúa, thì bà nội Ngài sẽ không chết'  thì trẫm cũng sẵn sàng dâng báu vật ngựa chúa ấy,",
  "sn3.22:2.6": "chỉ để bà nội không phải qua đời.",
  "sn3.22:2.7": "Nếu có ai nói rằng: 'Hãy dâng một ngôi làng tốt đẹp, thì bà nội Ngài sẽ không chết'  thì trẫm cũng sẵn sàng dâng ngôi làng ấy,",
  "sn3.22:2.8": "chỉ để bà nội không phải qua đời.",
  "sn3.22:2.9": "Nếu có ai nói rằng: 'Hãy dâng cả một vùng đất, thì bà nội Ngài sẽ không chết'  thì trẫm cũng sẵn sàng dâng vùng đất ấy,",
  "sn3.22:2.10": "'chỉ để bà nội không phải qua đời.'",
  "sn3.22:2.11": "'Này Đại vương, tất cả chúng sinh đều phải chết, đều kết thúc bằng cái chết, không ai thoát khỏi cái chết.'",
  "sn3.22:2.12": "Thật kỳ diệu thay, bạch Thế Tôn! Thật hy hữu thay, bạch Thế Tôn!",
  "sn3.22:2.13": "Thế Tôn đã nói thật khéo léo thay",
  "sn3.22:2.14": "'tất cả chúng sinh đều phải chết, đều kết thúc bằng cái chết, không ai thoát khỏi cái chết.'",
  "sn3.22:3.1": "Đúng vậy, Đại vương! Đúng vậy, Đại vương!",
  "sn3.22:3.2": "Tất cả chúng sinh đều phải chết, đều kết thúc bằng cái chết, không ai thoát khỏi cái chết.",
  "sn3.22:3.3": "Ví như, Đại vương, tất cả đồ gốm của người thợ gốm  dù còn sống hay đã nung chín  tất cả đều có tính chất vỡ bể, đều kết thúc bằng sự vỡ bể, không cái nào thoát khỏi sự vỡ bể;",
  "sn3.22:3.4": "'cũng vậy, Đại vương, tất cả chúng sinh đều phải chết, đều kết thúc bằng cái chết, không ai thoát khỏi cái chết.'",
  "sn3.22:3.5": "Đó là điều Thế Tôn nói...",
  "sn3.22:4.1": "Tất cả chúng sinh rồi đều sẽ chết,",
  "sn3.22:4.2": "vì sự sống vốn kết thúc bằng cái chết;",
  "sn3.22:4.3": "Mỗi người sẽ đi theo nghiệp của mình,",
  "sn3.22:4.4": "gặt hái quả của thiện hay ác đã gieo;",
  "sn3.22:4.5": "Kẻ làm ác sẽ đọa vào địa ngục,",
  "sn3.22:4.6": "người làm lành sẽ sanh lên cõi tốt lành.",
  "sn3.22:5.1": "Vậy hãy siêng làm điều thiện lành,",
  "sn3.22:5.2": "tích lũy phước đức cho đời sau;",
  "sn3.22:5.3": "Vì phước lành ở cõi kia,",
  "sn3.22:5.4": "'mới là chỗ nương tựa vững chắc cho chúng sinh.'",
  "sn3.23:0.1": "Tương Ưng Bộ Kinh 3.23",
  "sn3.23:0.2": "Chương 3. Phẩm Thứ Ba",
  "sn3.23:0.3": "Kinh Thế Gian (Lokasutta)",
  "sn3.23:1.1": "Nhân duyên tại thành Xá-vệ.",
  "sn3.23:1.2": "Vua Ba-tư-nặc xứ Kosala ngồi sang một bên, hỏi Thế Tôn rằng:",
  "sn3.23:1.3": "'Bạch Thế Tôn, có bao nhiêu pháp sinh khởi trong thế gian mang lại bất hạnh, đau khổ và sự khó chịu?'",
  "sn3.23:1.4": "Này Đại vương, có ba pháp sinh khởi trong thế gian mang lại bất hạnh, đau khổ và sự khó chịu.",
  "sn3.23:1.5": "Ba pháp đó là gì?",
  "sn3.23:1.6": "Tham lam, Đại vương, là pháp của thế gian  khi sinh khởi, nó mang lại bất hạnh, đau khổ và sự khó chịu.",
  "sn3.23:1.7": "Sân hận, Đại vương, là pháp của thế gian  khi sinh khởi, nó mang lại bất hạnh, đau khổ và sự khó chịu.",
  "sn3.23:1.8": "Si mê, Đại vương, là pháp của thế gian  khi sinh khởi, nó mang lại bất hạnh, đau khổ và sự khó chịu.",
  "sn3.23:1.9": "'Đó là ba pháp sinh khởi trong thế gian mang lại bất hạnh, đau khổ và sự khó chịu.'",
  "sn3.23:1.10": "Đó là điều Thế Tôn nói...",
  "sn3.23:2.1": "Tham, sân và si",
  "sn3.23:2.2": "ba độc này hại người tâm địa xấu;",
  "sn3.23:2.3": "Chúng sinh ra từ chính bên trong ta,",
  "sn3.23:2.4": "'như loài sâu đục khoét từ bên trong, phá nát cây từ lõi ra vỏ.'",
  "sn3.24:0.1": "Tương Ưng Bộ Kinh 3.24",
  "sn3.24:0.2": "Chương 3. Phẩm Thứ Ba",
  "sn3.24:0.3": "Kinh Bố Thí (Issattasutta)",
  "sn3.24:1.1": "Nhân duyên tại thành Xá-vệ.",
  "sn3.24:1.2": "Vua Ba-tư-nặc xứ Kosala ngồi sang một bên, hỏi Thế Tôn rằng:",
  "sn3.24:1.3": "'Bạch Thế Tôn, nên bố thí ở đâu?'",
  "sn3.24:1.4": "'Này Đại vương, hãy bố thí nơi nào mà tâm Ngài cảm thấy tịnh tín, hoan hỷ.'",
  "sn3.24:1.5": "'Bạch Thế Tôn, vậy bố thí ở đâu thì được quả báo lớn?'",
  "sn3.24:1.6": "Này Đại vương, đây là hai câu hỏi khác nhau  một câu hỏi về nơi nên bố thí, một câu hỏi về nơi bố thí được quả lớn.",
  "sn3.24:1.7": "Bố thí cho người có giới hạnh thì được quả báo lớn, bố thí cho kẻ phá giới thì không được như vậy.",
  "sn3.24:1.8": "Thôi, để Thế Tôn hỏi lại Ngài, Ngài trả lời theo ý mình.",
  "sn3.24:1.9": "Đại vương nghĩ sao,",
  "sn3.24:1.10": "giả sử Ngài đang có chiến trận sắp xảy ra, quân địch đang dàn thế trận.",
  "sn3.24:1.11": "Lúc ấy có người thuộc dòng dõi vua chúa đến  nhưng chưa được huấn luyện, tay nghề kém, chưa luyện tập, chưa thực chiến, lại nhút nhát, run sợ, hoảng loạn, hay bỏ chạy.",
  "sn3.24:1.12": "'Ngài có nuôi dưỡng người ấy không? Người như vậy có ích gì cho Ngài?'",
  "sn3.24:1.13": "'Bạch Thế Tôn, trẫm không nuôi người như vậy, và người như vậy cũng chẳng có ích gì cho trẫm.'",
  "sn3.24:1.14": "Nếu đến là người Bà-la-môn chưa được huấn luyện...",
  "sn3.24:1.15": "nếu đến là người thương gia chưa được huấn luyện...",
  "sn3.24:1.16": "nếu đến là người thợ thuyền chưa được huấn luyện... nhút nhát, run sợ, hoảng loạn, hay bỏ chạy...",
  "sn3.24:1.17": "'thì cũng chẳng có ích gì cho trẫm.'",
  "sn3.24:2.1": "Đại vương nghĩ sao,",
  "sn3.24:2.2": "giả sử Ngài đang có chiến trận sắp xảy ra, quân địch đang dàn thế trận.",
  "sn3.24:2.3": "Lúc ấy có người thuộc dòng dõi vua chúa đến  đã được huấn luyện tinh nhuệ, tay nghề giỏi, đã luyện tập kỹ càng, đã thực chiến, dũng cảm, không sợ hãi, không hoảng loạn, không bỏ chạy.",
  "sn3.24:2.4": "'Ngài có nuôi dưỡng người ấy không? Người như vậy có ích gì cho Ngài?'",
  "sn3.24:2.5": "'Bạch Thế Tôn, trẫm sẽ nuôi người như vậy, và người như vậy rất có ích cho trẫm.'",
  "sn3.24:2.6": "Nếu đến là người Bà-la-môn đã được huấn luyện...",
  "sn3.24:2.7": "nếu đến là người thương gia đã được huấn luyện...",
  "sn3.24:2.8": "nếu đến là người thợ thuyền đã được huấn luyện tinh nhuệ, tay nghề giỏi, đã luyện tập kỹ càng, đã thực chiến, dũng cảm, không sợ hãi, không hoảng loạn, không bỏ chạy",
  "sn3.24:2.9": "'Ngài có nuôi dưỡng người ấy không? Người như vậy có ích gì cho Ngài?'",
  "sn3.24:2.10": "'Bạch Thế Tôn, trẫm sẽ nuôi người như vậy, và người như vậy rất có ích cho trẫm.'",
  "sn3.24:3.1": "Cũng vậy, Đại vương, dù người xuất gia từ dòng dõi nào đi nữa  nếu người ấy đã đoạn trừ năm chi phần và đầy đủ năm chi phần kia, thì bố thí cho người ấy được quả báo rất lớn.",
  "sn3.24:3.2": "Năm chi phần đã đoạn trừ là gì?",
  "sn3.24:3.3": "Đã đoạn trừ tham dục, đã đoạn trừ sân hận, đã đoạn trừ hôn trầm thụy miên (buồn ngủ, lười biếng), đã đoạn trừ trạo cử hối hận (tâm bất an, lo lắng), đã đoạn trừ nghi ngờ.",
  "sn3.24:3.4": "Đó là năm chi phần đã được đoạn trừ.",
  "sn3.24:3.5": "Năm chi phần đầy đủ là gì?",
  "sn3.24:3.6": "Đầy đủ giới hạnh của bậc vô học, đầy đủ định của bậc vô học, đầy đủ trí tuệ của bậc vô học, đầy đủ giải thoát của bậc vô học, đầy đủ tri kiến về giải thoát của bậc vô học.",
  "sn3.24:3.7": "Đó là năm chi phần đầy đủ.",
  "sn3.24:3.8": "'Bố thí cho người đã đoạn trừ năm chi phần và đầy đủ năm chi phần ấy thì được quả báo rất lớn.'",
  "sn3.24:3.9": "Đó là điều Thế Tôn nói...",
  "sn3.24:3.10": "Bậc Đạo Sư tiếp tục:",
  "sn3.24:4.1": "Người thanh niên nào có tài bắn cung, dũng mãnh,",
  "sn3.24:4.2": "thì vua cần chiến trận sẽ dùng người ấy;",
  "sn3.24:4.3": "Vua nuôi dưỡng người dũng sĩ ấy,",
  "sn3.24:4.4": "chứ không chọn người chỉ vì dòng dõi cao sang.",
  "sn3.24:5.1": "Cũng vậy, người có đức nhẫn nhục và hiền lành,",
  "sn3.24:5.2": "đứng vững trên nền tảng Chánh Pháp;",
  "sn3.24:5.3": "Người sống đời cao quý, có trí tuệ",
  "sn3.24:5.4": "dù sinh ra trong dòng dõi thấp hèn cũng đáng được tôn kính và cúng dường.",
  "sn3.24:6.1": "Hãy xây dựng những am thất thanh tịnh,",
  "sn3.24:6.2": "mời các bậc uyên thâm về an trú;",
  "sn3.24:6.3": "Hãy làm giếng nước giữa rừng hoang,",
  "sn3.24:6.4": "và bắc cầu qua những nơi hiểm trở.",
  "sn3.24:7.1": "Hãy dâng cúng cơm ăn, nước uống, thức nhấm nháp,",
  "sn3.24:7.2": "áo mặc và chỗ ở;",
  "sn3.24:7.3": "Hãy bố thí cho những người ngay thẳng,",
  "sn3.24:7.4": "với tâm trong sáng, hoan hỷ.",
  "sn3.24:8.1": "Như đám mây sấm chớp rền vang,",
  "sn3.24:8.2": "vòng sét chớp lóe sáng trăm tia;",
  "sn3.24:8.3": "Mưa đổ xuống tràn đầy cả chỗ cao lẫn chỗ thấp,",
  "sn3.24:8.4": "tưới khắp mặt đất.",
  "sn3.24:9.1": "Cũng vậy, người có lòng tin, đa văn,",
  "sn3.24:9.2": "lo toan sắm sửa thức ăn;",
  "sn3.24:9.3": "Người trí ấy dâng cơm nước",
  "sn3.24:9.4": "làm no lòng những kẻ nghèo đói.",
  "sn3.24:10.1": "Hoan hỷ rải tặng khắp nơi,",
  "sn3.24:10.2": "miệng nói: 'Hãy cho, hãy cho!';",
  "sn3.24:10.3": "Tiếng kêu gọi bố thí ấy của người ấy,",
  "sn3.24:10.4": "vang lên như tiếng sấm của trời mưa;",
  "sn3.24:10.5": "Và dòng phước đức dồi dào ấy",
  "sn3.24:10.6": "'sẽ tuôn trào tưới xuống chính người bố thí.'",
  "sn3.25:0.1": "Tương Ưng Bộ Kinh 3.25",
  "sn3.25:0.2": "Chương 3. Phẩm Thứ Ba",
  "sn3.25:0.3": "Kinh Ví Dụ Ngọn Núi (Pabbatūpamasutta)",
  "sn3.25:1.1": "Nhân duyên tại thành Xá-vệ.",
  "sn3.25:1.2": "Vua Ba-tư-nặc xứ Kosala ngồi sang một bên, Thế Tôn hỏi rằng:",
  "sn3.25:1.3": "'Này Đại vương, giữa ban ngày như vầy mà Ngài từ đâu đến vậy?'",
  "sn3.25:1.4": "'Bạch Thế Tôn, trẫm đang bận bịu với những công việc triều chính của các vua chúa  những người say mê quyền lực, đắm chìm trong dục lạc, đã chinh phục và cai trị những vùng đất rộng lớn.'",
  "sn3.25:2.1": "Đại vương nghĩ sao,",
  "sn3.25:2.2": "giả sử có một người đáng tin cậy từ phương Đông đến gặp Ngài,",
  "sn3.25:2.3": "người ấy đến thưa với Ngài rằng:",
  "sn3.25:2.4": "'Tâu Đại vương, xin Ngài hãy biết  thần từ phương Đông đến.'",
  "sn3.25:2.5": "Thần thấy ở đó một ngọn núi khổng lồ cao tận mây xanh đang lăn đến, nghiền nát tất cả chúng sinh trên đường đi.",
  "sn3.25:2.6": "'Tâu Đại vương, xin Ngài hãy làm những gì cần làm.'",
  "sn3.25:2.7": "Rồi một người thứ hai từ phương Tây đến...",
  "sn3.25:2.8": "rồi người thứ ba từ phương Bắc đến...",
  "sn3.25:2.9": "rồi người thứ tư đáng tin cậy từ phương Nam đến gặp Ngài,",
  "sn3.25:2.10": "người ấy thưa với Ngài rằng:",
  "sn3.25:2.11": "'Tâu Đại vương, xin Ngài hãy biết  thần từ phương Nam đến.'",
  "sn3.25:2.12": "Thần thấy ở đó một ngọn núi khổng lồ cao tận mây xanh đang lăn đến, nghiền nát tất cả chúng sinh trên đường đi.",
  "sn3.25:2.13": "'Tâu Đại vương, xin Ngài hãy làm những gì cần làm.'",
  "sn3.25:2.14": "'Thưa Đại vương, khi tai họa khủng khiếp như vậy ập đến  bốn ngọn núi từ bốn phương đồng loạt nghiền nát muôn loài, kiếp người thật ngắn ngủi và hiếm có  Ngài sẽ làm gì?'",
  "sn3.25:3.1": "'Bạch Thế Tôn, khi tai họa khủng khiếp như vậy ập đến  bốn ngọn núi từ bốn phương nghiền nát muôn loài, kiếp người ngắn ngủi và hiếm có  thì trẫm biết làm gì khác hơn là sống đúng Chánh Pháp, sống ngay thẳng, làm điều thiện và tích lũy phước đức?'",
  "sn3.25:4.1": "Này Đại vương, Thế Tôn xin thông báo cho Ngài biết, xin tâu trình lên Ngài rằng  già và chết đang tiến đến Ngài đó.",
  "sn3.25:4.2": "'Khi già và chết đang tiến đến Ngài như vậy, Ngài sẽ làm gì?'",
  "sn3.25:4.3": "Bạch Thế Tôn, khi già và chết đang tiến đến như vậy, thì trẫm biết làm gì khác hơn là sống đúng Chánh Pháp, sống ngay thẳng, làm điều thiện và tích lũy phước đức?",
  "sn3.25:4.4": "Bạch Thế Tôn, các vua chúa đã chinh phục vùng đất rộng lớn còn có đội quân voi hùng mạnh",
  "sn3.25:4.5": "nhưng đội quân voi ấy cũng vô dụng, không có chỗ dứng, không cản nổi khi già và chết tiến đến.",
  "sn3.25:4.6": "Các vua ấy cũng có đội quân ngựa hùng mạnh...",
  "sn3.25:4.7": "đội quân ngựa ấy cũng vô dụng trước già và chết...",
  "sn3.25:4.8": "đội xe chiến hùng mạnh cũng vô dụng...",
  "sn3.25:4.9": "đội bộ binh hùng mạnh",
  "sn3.25:4.10": "đội bộ binh ấy cũng vô dụng, không cản nổi khi già và chết tiến đến.",
  "sn3.25:4.11": "Bạch Thế Tôn, trong triều đình của trẫm còn có những vị mưu thần tài giỏi, có thể dùng mưu kế chia rẽ hàng ngũ kẻ thù.",
  "sn3.25:4.12": "Nhưng những mưu kế ấy cũng vô dụng, không cản nổi khi già và chết tiến đến.",
  "sn3.25:4.13": "Bạch Thế Tôn, trong kho hoàng cung của trẫm còn có vàng bạc châu báu  cả dưới đất lẫn trên kho  đủ để mua chuộc kẻ thù.",
  "sn3.25:4.14": "Nhưng của cải ấy cũng vô dụng, không cản nổi khi già và chết tiến đến.",
  "sn3.25:4.15": "'Bạch Thế Tôn, khi già và chết đang tiến đến như vậy, thì trẫm biết làm gì khác hơn là sống đúng Chánh Pháp, sống ngay thẳng, làm điều thiện và tích lũy phước đức?'",
  "sn3.25:5.1": "Đúng vậy, Đại vương! Đúng vậy, Đại vương!",
  "sn3.25:5.2": "'Khi già và chết đang tiến đến, thì biết làm gì khác hơn là sống đúng Chánh Pháp, sống ngay thẳng, làm điều thiện và tích lũy phước đức?'",
  "sn3.25:5.3": "Đó là điều Thế Tôn nói...",
  "sn3.25:5.4": "Bậc Đạo Sư tiếp tục:",
  "sn3.25:6.1": "Như những ngọn núi đồ sộ,",
  "sn3.25:6.2": "cao chạm đến tận bầu trời;",
  "sn3.25:6.3": "Lăn đến từ khắp bốn phương,",
  "sn3.25:6.4": "nghiền nát tất cả trên đường đi.",
  "sn3.25:7.1": "Cũng vậy, già và chết",
  "sn3.25:7.2": "đang tiến đến cuốn trôi chúng sinh;",
  "sn3.25:7.3": "Vua chúa, Bà-la-môn, thương nhân,",
  "sn3.25:7.4": "thợ thuyền, người hốt rác  tất cả;",
  "sn3.25:7.5": "Không ai được tha, không ai thoát",
  "sn3.25:7.6": "tất cả đều bị nghiền nát như nhau.",
  "sn3.25:8.1": "Trước già và chết, voi trận vô dụng,",
  "sn3.25:8.2": "xe chiến vô dụng, bộ binh vô dụng;",
  "sn3.25:8.3": "Mưu kế cũng chẳng làm gì được,",
  "sn3.25:8.4": "dùng của cải mua chuộc cũng không xong.",
  "sn3.25:9.1": "Vậy người trí, lo cho lợi ích của mình,",
  "sn3.25:9.2": "hãy nhìn thấy rõ điều này;",
  "sn3.25:9.3": "Hãy đặt lòng tin vững chắc vào Phật, Pháp, Tăng",
  "sn3.25:9.4": "đó mới là điều người có trí tuệ nên làm.",
  "sn3.25:10.1": "Ai sống đúng Chánh Pháp  bằng thân,",
  "sn3.25:10.2": "bằng lời nói và bằng tâm ý;",
  "sn3.25:10.3": "Ngay trong đời này được người đời ca ngợi,",
  "sn3.25:10.4": "'sau khi mất được hưởng phúc lạc cõi trời.'",
  "sn3.25:10.5": "Hết Phẩm Thứ Ba.",
  "sn3.25:11.0": "Tóm tắt các bài kinh trong phẩm:",
  "sn3.25:11.1": "Bốn hạng người, bà nội, thế gian,",
  "sn3.25:11.2": "bố thí, và ví dụ ngọn núi;",
  "sn3.25:11.3": "Được Đức Phật tối thượng giảng dạy",
  "sn3.25:11.4": "đây là năm bài kinh thuộc phẩm Kosala thứ ba.",
  "sn3.25:11.5": "Hết Tương Ưng Kosala."
}
window.BILARA["sn3_v1"]["vi"]["sn3_v1:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com";
