window.BILARA = window.BILARA || {};
window.BILARA["sn1_v1"] = window.BILARA["sn1_v1"] || {};
window.BILARA["sn1_v1"]["en"] = {
  "sn1.1:0.1": "Linked Discourses 1.1",
  "sn1.1:0.2": "1. A Reed",
  "sn1.1:0.3": "Crossing the Flood",
  "sn1.1:1.1": "So I have heard.",
  "sn1.1:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s Monastery.",
  "sn1.1:1.3": "Then, late at night, a glorious deity, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, stood to one side, and said to him,",
  "sn1.1:1.4": "“Good fellow, how did you cross the flood?”",
  "sn1.1:1.5": "“Neither standing nor swimming, respectable sir, I crossed the flood.”",
  "sn1.1:1.6": "“But in what way did you cross the flood neither standing nor swimming?”",
  "sn1.1:1.7": "“When I stood, I sank under.",
  "sn1.1:1.8": "When I swam, I was swept away.",
  "sn1.1:1.9": "That’s how I crossed the flood neither standing nor swimming.”",
  "sn1.1:2.1": "“After a long time I see",
  "sn1.1:2.2": "a brahmin fully quenched.",
  "sn1.1:2.3": "Neither standing nor swimming,",
  "sn1.1:2.4": "he’s crossed over clinging to the world.”",
  "sn1.1:3.1": "This is what that deity said,",
  "sn1.1:3.2": "and the teacher approved.",
  "sn1.1:3.3": "",
  "sn1.1:3.4": "Then that deity, knowing that the teacher approved, bowed and respectfully circled the Buddha, keeping him on his right, before vanishing right there.",
  "sn1.2:0.1": "Linked Discourses 1.2",
  "sn1.2:0.2": "1. A Reed",
  "sn1.2:0.3": "Liberation",
  "sn1.2:1.1": "At Sāvatthī.",
  "sn1.2:1.2": "Then, late at night, a glorious deity, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, stood to one side, and said to him,",
  "sn1.2:2.1": "“Good fellow, do you know the liberation, emancipation, and seclusion of sentient beings?”",
  "sn1.2:3.1": "“I do, good sir.”",
  "sn1.2:4.1": "“But how is it that you know the liberation, emancipation, and seclusion of sentient beings?”",
  "sn1.2:5.1": "“Due to the ending of relish for rebirth;",
  "sn1.2:5.2": "due to the finishing of perception and consciousness;",
  "sn1.2:5.3": "due to the cessation and stilling of feelings",
  "sn1.2:5.4": "that, respectable sir, is how I know the liberation,",
  "sn1.2:5.5": "emancipation, and seclusion of sentient beings.”",
  "sn1.3:0.1": "Linked Discourses 1.3",
  "sn1.3:0.2": "1. A Reed",
  "sn1.3:0.3": "Led On",
  "sn1.3:1.1": "At Sāvatthī.",
  "sn1.3:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence:",
  "sn1.3:2.1": "“This life, so very short, is led onward.",
  "sn1.3:2.2": "One led on to old age has no shelter.",
  "sn1.3:2.3": "Seeing this peril in death,",
  "sn1.3:2.4": "do good deeds that bring you joy.”",
  "sn1.3:3.1": "“This life, so very short, is led onward;",
  "sn1.3:3.2": "one led on to old age has no shelter.",
  "sn1.3:3.3": "Seeing this peril in death,",
  "sn1.3:3.4": "a seeker of peace would drop the world’s bait.”",
  "sn1.4:0.1": "Linked Discourses 1.4",
  "sn1.4:0.2": "1. A Reed",
  "sn1.4:0.3": "Time Flies",
  "sn1.4:1.1": "At Sāvatthī.",
  "sn1.4:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence:",
  "sn1.4:2.1": "“Time flies, nights pass by,",
  "sn1.4:2.2": "the stages of life leave us one by one.",
  "sn1.4:2.3": "Seeing this peril in death,",
  "sn1.4:2.4": "do good deeds that bring you joy.”",
  "sn1.4:3.1": "“Time flies, nights pass by,",
  "sn1.4:3.2": "the stages of life leave us one by one.",
  "sn1.4:3.3": "Seeing this peril in death,",
  "sn1.4:3.4": "a seeker of peace would drop the world’s bait.”",
  "sn1.5:0.1": "Linked Discourses 1.5",
  "sn1.5:0.2": "1. A Reed",
  "sn1.5:0.3": "Cut How Many?",
  "sn1.5:1.1": "At Sāvatthī.",
  "sn1.5:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence:",
  "sn1.5:2.1": "“Cut how many? Drop how many?",
  "sn1.5:2.2": "Develop how many more?",
  "sn1.5:2.3": "When a mendicant slips how many chains",
  "sn1.5:2.4": "are they said to have crossed the flood?”",
  "sn1.5:3.1": "“Five to cut, five to drop,",
  "sn1.5:3.2": "and five more to develop.",
  "sn1.5:3.3": "When a mendicant slips five chains",
  "sn1.5:3.4": "they’re said to have crossed the flood.”",
  "sn1.6:0.1": "Linked Discourses 1.6",
  "sn1.6:0.2": "1. A Reed",
  "sn1.6:0.3": "Awake",
  "sn1.6:1.1": "At Sāvatthī.",
  "sn1.6:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence:",
  "sn1.6:2.1": "“How many sleep among the waking?",
  "sn1.6:2.2": "How many wake among the sleeping?",
  "sn1.6:2.3": "By how many do you gather dust?",
  "sn1.6:2.4": "By how many are you cleansed?”",
  "sn1.6:3.1": "“Five sleep among the waking.",
  "sn1.6:3.2": "Five wake among the sleeping.",
  "sn1.6:3.3": "By five you gather dust.",
  "sn1.6:3.4": "By five you’re cleansed.”",
  "sn1.7:0.1": "Linked Discourses 1.7",
  "sn1.7:0.2": "1. A Reed",
  "sn1.7:0.3": "Not Comprehending",
  "sn1.7:1.1": "At Sāvatthī.",
  "sn1.7:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence:",
  "sn1.7:2.1": "“Those have not deciphered the teachings",
  "sn1.7:2.2": "may be led astray by the doctrines of others.",
  "sn1.7:2.3": "Asleep, they have not woken up:",
  "sn1.7:2.4": "it is time for them to wake!”",
  "sn1.7:3.1": "“Those who have well deciphered the teachings",
  "sn1.7:3.2": "won’t be led astray by the doctrines of others.",
  "sn1.7:3.3": "They have woken up, they rightly know,",
  "sn1.7:3.4": "smoothly they walk in the rough.”",
  "sn1.8:0.1": "Linked Discourses 1.8",
  "sn1.8:0.2": "1. A Reed",
  "sn1.8:0.3": "Very Confused",
  "sn1.8:1.1": "At Sāvatthī.",
  "sn1.8:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence:",
  "sn1.8:2.1": "“Those who are very confused about the teachings",
  "sn1.8:2.2": "may be led astray by the doctrines of others.",
  "sn1.8:2.3": "Asleep, they have not woken up:",
  "sn1.8:2.4": "it is time for them to wake!”",
  "sn1.8:3.1": "“Those who are unconfused about the teachings,",
  "sn1.8:3.2": "won’t be led astray by the doctrines of others.",
  "sn1.8:3.3": "They have woken up, they rightly know,",
  "sn1.8:3.4": "smoothly they walk in the rough.”",
  "sn1.9:0.1": "Linked Discourses 1.9",
  "sn1.9:0.2": "1. A Reed",
  "sn1.9:0.3": "Fond of Conceit",
  "sn1.9:1.1": "At Sāvatthī.",
  "sn1.9:1.2": "Standing to one side, that deity spoke this verse in the Buddha’s presence:",
  "sn1.9:2.1": "“One fond of conceit can’t be tamed,",
  "sn1.9:2.2": "no sage is lacking immersion.",
  "sn1.9:2.3": "Living negligent alone in the wilderness,",
  "sn1.9:2.4": "they can’t cross beyond Death’s dominion.”",
  "sn1.9:3.1": "“Having given up conceit, serene within oneself,",
  "sn1.9:3.2": "with a good heart, everywhere free;",
  "sn1.9:3.3": "living diligent alone in the wilderness,",
  "sn1.9:3.4": "they cross beyond Death’s dominion.”",
  "sn1.10:0.1": "Linked Discourses 1.10",
  "sn1.10:0.2": "1. A Reed",
  "sn1.10:0.3": "Wilderness",
  "sn1.10:1.1": "At Sāvatthī.",
  "sn1.10:1.2": "Standing to one side, that deity addressed the Buddha in verse:",
  "sn1.10:2.1": "“Living in the wilderness,",
  "sn1.10:2.2": "peaceful spiritual practitioners",
  "sn1.10:2.3": "eat just one meal a day:",
  "sn1.10:2.4": "so why is their complexion so clear?”",
  "sn1.10:3.1": "“They don’t grieve for the past,",
  "sn1.10:3.2": "nor do they pray for the future;",
  "sn1.10:3.3": "they feed on whatever comes that day,",
  "sn1.10:3.4": "that’s why their complexion’s so clear.",
  "sn1.10:4.1": "Because they long for the future,",
  "sn1.10:4.2": "and grieve for the past,",
  "sn1.10:4.3": "fools wither away,",
  "sn1.10:4.4": "like a green reed mowed down.”",
  "sn1.10:4.5": "",
  "sn1.10:5.1": "",
  "sn1.10:5.2": "",
  "sn1.10:5.3": "",
  "sn1.10:5.4": "",
  "sn1.10:5.5": ""
}
window.BILARA["sn1_v1"]["en"]["sn1_v1:source"] =
 "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
