window.BILARA = window.BILARA || {};
window.BILARA["sn1_v4"] = window.BILARA["sn1_v4"] || {};
window.BILARA["sn1_v4"]["en"] = {
  "sn1.31:0.1": "Linked Discourses 1.31",
  "sn1.31:0.2": "4. The Host of a Hundred Felicities",
  "sn1.31:0.3": "Virtuous",
  "sn1.31:1.1": "So I have heard.",
  "sn1.31:1.2": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s Monastery.",
  "sn1.31:1.3": "Then, late at night, several glorious deities of the host of a hundred felicities, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, and stood to one side.",
  "sn1.31:1.4": "Standing to one side, one deity spoke this verse in the Buddha’s presence:",
  "sn1.31:2.1": "“Associate only with the virtuous!",
  "sn1.31:2.2": "Try to get close to the virtuous!",
  "sn1.31:2.3": "Understanding the true teaching of the good,",
  "sn1.31:2.4": "things get better, not worse.”",
  "sn1.31:3.1": "Then another deity spoke this verse in the Buddha’s presence:",
  "sn1.31:4.1": "“Associate only with the virtuous!",
  "sn1.31:4.2": "Try to get close to the virtuous!",
  "sn1.31:4.3": "Understanding the true teaching of the good,",
  "sn1.31:4.4": "wisdom is gainedbut not from anyone else.”",
  "sn1.31:5.1": "Then another deity spoke this verse in the Buddha’s presence:",
  "sn1.31:6.1": "“Associate only with the virtuous!",
  "sn1.31:6.2": "Try to get close to the virtuous!",
  "sn1.31:6.3": "Understanding the true teaching of the good,",
  "sn1.31:6.4": "you grieve not among the grieving.”",
  "sn1.31:7.1": "Then another deity spoke this verse in the Buddha’s presence:",
  "sn1.31:8.1": "“Associate only with the virtuous!",
  "sn1.31:8.2": "Try to get close to the virtuous!",
  "sn1.31:8.3": "Understanding the true teaching of the good,",
  "sn1.31:8.4": "you shine among your relatives.”",
  "sn1.31:9.1": "Then another deity spoke this verse in the Buddha’s presence:",
  "sn1.31:10.1": "“Associate only with the virtuous!",
  "sn1.31:10.2": "Try to get close to the virtuous!",
  "sn1.31:10.3": "Understanding the true teaching of the good,",
  "sn1.31:10.4": "sentient beings go to a good place.”",
  "sn1.31:11.1": "Then another deity spoke this verse in the Buddha’s presence:",
  "sn1.31:12.1": "“Associate only with the virtuous!",
  "sn1.31:12.2": "Try to get close to the virtuous!",
  "sn1.31:12.3": "Understanding the true teaching of the good,",
  "sn1.31:12.4": "sentient beings live happily.”",
  "sn1.31:13.1": "Then another deity said to the Buddha,",
  "sn1.31:13.2": "“Sir, who has spoken well?”",
  "sn1.31:14.1": "“You’ve all spoken well in your own way. However, listen to me also:",
  "sn1.31:15.1": "Associate only with the virtuous!",
  "sn1.31:15.2": "Try to get close to the virtuous!",
  "sn1.31:15.3": "Understanding the true teaching of the good,",
  "sn1.31:15.4": "you’re released from all suffering.”",
  "sn1.31:16.1": "That is what the Buddha said.",
  "sn1.31:16.2": "Then those deities, knowing that the teacher approved, bowed and respectfully circled the Buddha, keeping him on their right, before vanishing right there.",
  "sn1.32:0.1": "Linked Discourses 1.32",
  "sn1.32:0.2": "4. The Host of a Hundred Felicities",
  "sn1.32:0.3": "Stinginess",
  "sn1.32:1.1": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery.",
  "sn1.32:1.2": "Then, late at night, several glorious deities of the host of a hundred felicities, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, and stood to one side.",
  "sn1.32:1.3": "Standing to one side, one deity spoke this verse in the Buddha’s presence:",
  "sn1.32:2.1": "“Because of stinginess and negligence",
  "sn1.32:2.2": "a gift is not given.",
  "sn1.32:2.3": "Wanting merit,",
  "sn1.32:2.4": "a smart person would give.”",
  "sn1.32:3.1": "Then another deity recited these verses in the Buddha’s presence:",
  "sn1.32:4.1": "“When a miser fails to give because of fear,",
  "sn1.32:4.2": "the very thing they’re afraid of comes to pass.",
  "sn1.32:4.3": "The hunger and thirst",
  "sn1.32:4.4": "that a miser fears",
  "sn1.32:4.5": "hurt the fool",
  "sn1.32:4.6": "in this world and the next.",
  "sn1.32:5.1": "So you should dispel stinginess,",
  "sn1.32:5.2": "overcoming that stain, and give a gift.",
  "sn1.32:5.3": "The good deeds of sentient beings",
  "sn1.32:5.4": "support them in the next world.”",
  "sn1.32:6.1": "Then another deity recited these verses in the Buddha’s presence:",
  "sn1.32:7.1": "“Among the dead they do not die,",
  "sn1.32:7.2": "those who, like fellow travelers on the road,",
  "sn1.32:7.3": "are happy to provide, though they have but little.",
  "sn1.32:7.4": "This is an ancient teaching.",
  "sn1.32:8.1": "Some who have little are happy to provide,",
  "sn1.32:8.2": "while some who have much don’t wish to give.",
  "sn1.32:8.3": "An offering given from little",
  "sn1.32:8.4": "is multiplied a thousand times.”",
  "sn1.32:9.1": "Then another deity recited these verses in the Buddha’s presence:",
  "sn1.32:10.1": "“Giving what’s hard to give,",
  "sn1.32:10.2": "doing what’s hard to do;",
  "sn1.32:10.3": "the wicked don’t act like this,",
  "sn1.32:10.4": "for the teaching of the good is hard to follow.",
  "sn1.32:11.1": "That’s why the virtuous and the wicked",
  "sn1.32:11.2": "have different destinations after here.",
  "sn1.32:11.3": "The wicked go to hell,",
  "sn1.32:11.4": "while the virtuous are bound for heaven.”",
  "sn1.32:12.1": "Then another deity said to the Buddha,",
  "sn1.32:12.2": "“Sir, who has spoken well?”",
  "sn1.32:13.1": "“You’ve all spoken well in your own way. However, listen to me also:",
  "sn1.32:14.1": "A hundred thousand people <j>making a thousand sacrifices",
  "sn1.32:14.2": "isn’t worth a fraction of that sort,",
  "sn1.32:14.3": "who lives rightly, wandering for gleanings,",
  "sn1.32:14.4": "or one who supports their partner <j>with what little they have.”",
  "sn1.32:15.1": "Then another deity addressed the Buddha in verse:",
  "sn1.32:16.1": "“Why doesn’t that sacrifice of theirs, so abundant and magnificent,",
  "sn1.32:16.2": "equal the value of a moral person’s gift?",
  "sn1.32:16.3": "How is it that a hundred thousand people  <j>making a thousand sacrifices",
  "sn1.32:16.4": "isn’t worth a fraction of what’s offered by that sort?”",
  "sn1.32:17.1": "“Some give based on immorality",
  "sn1.32:17.2": "after slaying, killing, and tormenting.",
  "sn1.32:17.3": "Such an offeringtearful, violent",
  "sn1.32:17.4": "in no way equals the value of a moral person’s gift.",
  "sn1.32:18.1": "That’s how it is that a hundred thousand people  <j>making a thousand sacrifices",
  "sn1.32:18.2": "isn’t worth a fraction of what’s offered by that sort.”",
  "sn1.33:0.1": "Linked Discourses 1.33",
  "sn1.33:0.2": "4. The Host of a Hundred Felicities",
  "sn1.33:0.3": "Good",
  "sn1.33:1.1": "At Sāvatthī.",
  "sn1.33:1.2": "Then, late at night, several glorious deities of the host of a hundred felicities, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, and stood to one side.",
  "sn1.33:1.3": "Standing to one side, one deity expressed this heartfelt sentiment in the Buddha’s presence:",
  "sn1.33:2.1": "“Good, good fellow, is giving!",
  "sn1.33:2.2": "Because of stinginess and negligence",
  "sn1.33:2.3": "a gift is not given.",
  "sn1.33:2.4": "Wanting merit,",
  "sn1.33:2.5": "a smart person would give.”",
  "sn1.33:3.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence:",
  "sn1.33:4.1": "“Good, good fellow, is giving!",
  "sn1.33:4.2": "Even when one has little, giving is good.",
  "sn1.33:5.1": "Some who have little are happy to provide,",
  "sn1.33:5.2": "while some who have much don’t wish to give.",
  "sn1.33:5.3": "An offering given from little",
  "sn1.33:5.4": "is multiplied a thousand times.”",
  "sn1.33:6.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence:",
  "sn1.33:7.1": "“Good, good fellow, is giving!",
  "sn1.33:7.2": "Even when one has little, giving is good.",
  "sn1.33:7.3": "And it’s also good to give out of faith.",
  "sn1.33:7.4": "Giving and warfare are similar, they say,",
  "sn1.33:7.5": "for even a few of the good may conquer the many.",
  "sn1.33:7.6": "If a faithful person gives even a little,",
  "sn1.33:7.7": "it still brings them happiness in the hereafter.”",
  "sn1.33:8.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence:",
  "sn1.33:9.1": "“Good, good fellow, is giving!",
  "sn1.33:9.2": "Even when one has little, giving is good.",
  "sn1.33:9.3": "And it’s also good to give out of faith.",
  "sn1.33:9.4": "And it’s also good to give legitimate wealth.",
  "sn1.33:10.1": "A personage who gives legitimate wealth,",
  "sn1.33:10.2": "earned by his efforts and initiative,",
  "sn1.33:10.3": "has passed over Yama’s Vetaraṇī River;",
  "sn1.33:10.4": "that mortal arrives at celestial fields.”",
  "sn1.33:11.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence:",
  "sn1.33:12.1": "“Good, good fellow, is giving!",
  "sn1.33:12.2": "Even when one has little, giving is good.",
  "sn1.33:12.3": "And it’s also good to give out of faith.",
  "sn1.33:12.4": "And it’s also good to give legitimate wealth.",
  "sn1.33:12.5": "And it’s also good to give intelligently.",
  "sn1.33:13.1": "The Holy One praises giving intelligently",
  "sn1.33:13.2": "to those worthy of offerings here  <j>in the world of the living.",
  "sn1.33:13.3": "What’s given to these is very fruitful,",
  "sn1.33:13.4": "like seeds sown in a fertile field.”",
  "sn1.33:14.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence:",
  "sn1.33:15.1": "“Good, good fellow, is giving!",
  "sn1.33:15.2": "Even when one has little, giving is good.",
  "sn1.33:15.3": "And it’s also good to give out of faith.",
  "sn1.33:15.4": "And it’s also good to give legitimate wealth.",
  "sn1.33:15.5": "And it’s also good to give intelligently.",
  "sn1.33:15.6": "And it’s also good to be restrained  <j>when it comes to living creatures.",
  "sn1.33:16.1": "One who lives without harming any living being",
  "sn1.33:16.2": "does no bad because of others’ blame.",
  "sn1.33:16.3": "Were that the case they praise the coward, not the brave;",
  "sn1.33:16.4": "for the virtuous do no bad out of fear.”",
  "sn1.33:17.1": "Then another deity said to the Buddha,",
  "sn1.33:17.2": "“Sir, who has spoken well?”",
  "sn1.33:18.1": "“You’ve all spoken well in your own way. However, listen to me also:",
  "sn1.33:19.1": "A gift of faith is praised in many ways,",
  "sn1.33:19.2": "but a passage of teaching is better than giving,",
  "sn1.33:19.3": "for the virtuous, in days old and older still,",
  "sn1.33:19.4": "even attained extinction with wisdom.”",
  "sn1.34:0.1": "Linked Discourses 1.34",
  "sn1.34:0.2": "4. The Host of a Hundred Felicities",
  "sn1.34:0.3": "There Are None",
  "sn1.34:1.1": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s Monastery.",
  "sn1.34:1.2": "Then, late at night, several glorious deities of the host of a hundred felicities, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, and stood to one side.",
  "sn1.34:1.3": "Standing to one side, one deity spoke this verse in the Buddha’s presence:",
  "sn1.34:2.1": "“Among mankind there are no sensual pleasures that are permanent.",
  "sn1.34:2.2": "Here there are sensuous things, bound to which,",
  "sn1.34:2.3": "drunk on which, there’s no coming back.",
  "sn1.34:2.4": "That person doesn’t return from Death’s dominion.”",
  "sn1.34:3.1": "“Gloom is born of desire; suffering is born of desire;",
  "sn1.34:3.2": "when desire is removed, gloom is removed;",
  "sn1.34:3.3": "when gloom is removed, suffering is removed.”",
  "sn1.34:4.1": "“The world’s pretty things aren’t sensual pleasures.",
  "sn1.34:4.2": "Greedy intention is a person’s sensual pleasure.",
  "sn1.34:4.3": "The world’s pretty things stay just as they are,",
  "sn1.34:4.4": "but the attentive remove desire for them.",
  "sn1.34:5.1": "Give up anger, get rid of conceit,",
  "sn1.34:5.2": "and get past all the fetters.",
  "sn1.34:5.3": "Sufferings don’t torment the one who has nothing,",
  "sn1.34:5.4": "not clinging to name and form.",
  "sn1.34:6.1": "They gave up judgement without falling into conceit;",
  "sn1.34:6.2": "craving for name and form was cut off right here.",
  "sn1.34:6.3": "They cut the ties, untroubled, <j>with no need for hope.",
  "sn1.34:6.4": "Though gods and humans search for them",
  "sn1.34:6.5": "in this life or the next, they never find them,",
  "sn1.34:6.6": "not in heaven nor in any abode.”",
  "sn1.34:7.1": "“If neither gods nor humans see one freed in this way,”",
  "sn1.34:7.2": "said Venerable Mogharāja,",
  "sn1.34:7.3": "“in this life or the next,",
  "sn1.34:7.4": "are those who revere that supreme man,",
  "sn1.34:7.5": "who lives for the good of mankind, <j>also worthy of praise?”",
  "sn1.34:8.1": "“The mendicants who revere one freed in this way,”",
  "sn1.34:8.2": "said the Buddha,",
  "sn1.34:8.3": "“are also worthy of praise, Mogharāja.",
  "sn1.34:8.4": "Having understood the teaching <j>and given up doubt,",
  "sn1.34:8.5": "those mendicants slip their chains.”",
  "sn1.35:0.1": "Linked Discourses 1.35",
  "sn1.35:0.2": "4. The Host of a Hundred Felicities",
  "sn1.35:0.3": "Fault-Finding Deities",
  "sn1.35:1.1": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s Monastery.",
  "sn1.35:1.2": "Then, late at night, several glorious deities of the host of the fault-finders, lighting up the entire Jeta’s Grove, went up to the Buddha, and stood in the air.",
  "sn1.35:1.3": "Standing in the air, one deity spoke this verse in the Buddha’s presence:",
  "sn1.35:2.1": "“Someone who pretends",
  "sn1.35:2.2": "to be other than they really are,",
  "sn1.35:2.3": "is like a cheating gambler",
  "sn1.35:2.4": "who enjoys what was gained by theft.",
  "sn1.35:3.1": "You should only say what you would do;",
  "sn1.35:3.2": "you shouldn’t say what you wouldn’t do.",
  "sn1.35:3.3": "The wise will recognize",
  "sn1.35:3.4": "one who talks without doing.”",
  "sn1.35:4.1": "“Not just by speaking,",
  "sn1.35:4.2": "nor solely by listening,",
  "sn1.35:4.3": "are you able to progress",
  "sn1.35:4.4": "on this hard path,",
  "sn1.35:4.5": "by which the attentive practicing absorption",
  "sn1.35:4.6": "are released from Māra’s bonds.",
  "sn1.35:5.1": "The attentive certainly don’t act like that,",
  "sn1.35:5.2": "for they understand the way of the world.",
  "sn1.35:5.3": "The attentive are quenched by understanding,",
  "sn1.35:5.4": "they’ve crossed over clinging to the world.”",
  "sn1.35:6.1": "Then those deities landed on the ground, bowed with their heads at the Buddha’s feet and said,",
  "sn1.35:6.2": "“We made a mistake, sir. It was foolish, stupid, and unskillful of us to presume to attack the Buddha!",
  "sn1.35:6.3": "Please, sir, accept our mistake for what it is, so we will restrain ourselves in future.”",
  "sn1.35:6.4": "At that, the Buddha smiled.",
  "sn1.35:6.5": "Then those deities, becoming even more fault-finding, flew up in the air.",
  "sn1.35:6.6": "One deity spoke this verse in the Buddha’s presence:",
  "sn1.35:7.1": "“If you don’t give your pardon",
  "sn1.35:7.2": "when a mistake is confessed,",
  "sn1.35:7.3": "with hidden anger and heavy hate,",
  "sn1.35:7.4": "you’re stuck in your enmity.”",
  "sn1.35:8.1": "“Suppose no mistake were found,",
  "sn1.35:8.2": "and no-one here had gone astray:",
  "sn1.35:8.3": "if enmities were not settled,",
  "sn1.35:8.4": "how could that be skilful?”",
  "sn1.35:9.1": "“Who makes no mistakes?",
  "sn1.35:9.2": "Who doesn’t go astray?",
  "sn1.35:9.3": "Who doesn’t fall into confusion?",
  "sn1.35:9.4": "Who is attentive, ever mindful?”",
  "sn1.35:10.1": "“The Realized One, the Buddha,",
  "sn1.35:10.2": "sympathetic for all beings:",
  "sn1.35:10.3": "that’s who makes no mistakes,",
  "sn1.35:10.4": "and that’s who doesn’t go astray.",
  "sn1.35:10.5": "He doesn’t fall into confusion,",
  "sn1.35:10.6": "for he’s attentive, ever mindful.",
  "sn1.35:11.1": "If you don’t give your pardon",
  "sn1.35:11.2": "when a mistake is confessed,",
  "sn1.35:11.3": "with hidden anger and heavy hate,",
  "sn1.35:11.4": "you’re stuck in your enmity.",
  "sn1.35:11.5": "I don’t approve of such enmity,",
  "sn1.35:11.6": "and so I pardon your mistake.”",
  "sn1.36:0.1": "Linked Discourses 1.36",
  "sn1.36:0.2": "4. The Host of a Hundred Felicities",
  "sn1.36:0.3": "Faith",
  "sn1.36:1.1": "At one time the Buddha was staying near Sāvatthī in Jeta’s Grove, Anāthapiṇḍika’s monastery.",
  "sn1.36:1.2": "Then, late at night, several glorious deities of the host of a hundred felicities, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, and stood to one side.",
  "sn1.36:1.3": "Standing to one side, one deity spoke this verse in the Buddha’s presence:",
  "sn1.36:2.1": "“Faith is a person’s partner.",
  "sn1.36:2.2": "If faithlessness doesn’t linger,",
  "sn1.36:2.3": "fame and renown are theirs,",
  "sn1.36:2.4": "and when they discard this corpse they go to heaven.”",
  "sn1.36:3.1": "Then another deity recited these verses in the Buddha’s presence:",
  "sn1.36:4.1": "“Give up anger, get rid of conceit,",
  "sn1.36:4.2": "and get past all the fetters.",
  "sn1.36:4.3": "Chains don’t torment one who has nothing,",
  "sn1.36:4.4": "not clinging to name and form.”",
  "sn1.36:5.1": "“Fools and simpletons",
  "sn1.36:5.2": "devote themselves to negligence.",
  "sn1.36:5.3": "But the wise protect diligence",
  "sn1.36:5.4": "as their best treasure.",
  "sn1.36:6.1": "Don’t devote yourself to negligence,",
  "sn1.36:6.2": "or delight in erotic intimacy.",
  "sn1.36:6.3": "For if you’re diligent and practice absorption,",
  "sn1.36:6.4": "you’ll attain ultimate happiness.”",
  "sn1.37:0.1": "Linked Discourses 1.37",
  "sn1.37:0.2": "4. The Host of a Hundred Felicities",
  "sn1.37:0.3": "The Congregation",
  "sn1.37:1.1": "So I have heard.",
  "sn1.37:1.2": "At one time the Buddha was staying in the land of the Sakyans, in the Great Wood near Kapilavatthu, together with a large Saṅgha of five hundred mendicants, all of whom were perfected ones.",
  "sn1.37:1.3": "And most of the deities from ten solar systems had gathered to see the Buddha and the Saṅgha of mendicants.",
  "sn1.37:1.4": "Then four deities of the Pure Abodes, aware of what was happening, thought:",
  "sn1.37:1.5": "",
  "sn1.37:1.6": "",
  "sn1.37:1.7": "“Why don’t we go to the Buddha and each recite a verse in his presence?”",
  "sn1.37:2.1": "Then, as easily as a strong person would extend or contract their arm, they vanished from the Pure Abodes and reappeared in front of the Buddha.",
  "sn1.37:2.2": "They bowed to the Buddha and stood to one side.",
  "sn1.37:2.3": "Standing to one side, one deity spoke this verse in the Buddha’s presence:",
  "sn1.37:3.1": "“There’s a great congregation in the woods,",
  "sn1.37:3.2": "where hosts of gods have assembled.",
  "sn1.37:3.3": "We’ve come to this righteous congregation",
  "sn1.37:3.4": "to see the invincible Saṅgha!”",
  "sn1.37:4.1": "Then another deity spoke this verse in the Buddha’s presence:",
  "sn1.37:5.1": "“The mendicants there have immersion,",
  "sn1.37:5.2": "they’ve straightened their own minds.",
  "sn1.37:5.3": "Like a charioteer holding the reins,",
  "sn1.37:5.4": "the astute ones protect their senses.”",
  "sn1.37:6.1": "Then another deity spoke this verse in the Buddha’s presence:",
  "sn1.37:7.1": "“They snapped the post and snapped the cross-bar,",
  "sn1.37:7.2": "unstirred, they tore out Indra’s pillar.",
  "sn1.37:7.3": "They live pure and immaculate,",
  "sn1.37:7.4": "the young giants tamed by the Clear-eyed One.”",
  "sn1.37:8.1": "Then another deity spoke this verse in the Buddha’s presence:",
  "sn1.37:9.1": "“Anyone who has gone to the Buddha for refuge",
  "sn1.37:9.2": "won’t go to a plane of loss.",
  "sn1.37:9.3": "After giving up this human body,",
  "sn1.37:9.4": "they swell the hosts of gods.”",
  "sn1.38:0.1": "Linked Discourses 1.38",
  "sn1.38:0.2": "4. The Host of a Hundred Felicities",
  "sn1.38:0.3": "A Splinter",
  "sn1.38:1.1": "So I have heard.",
  "sn1.38:1.2": "At one time the Buddha was staying near Rājagaha in the Maddakucchi deer park.",
  "sn1.38:1.3": "Now at that time the Buddha’s foot had been cut by a wooden splinter.",
  "sn1.38:1.4": "The Buddha was stricken by harrowing pains; physical feelings that were painful, sharp, severe, acute, unpleasant, and disagreeable.",
  "sn1.38:1.5": "But he endured unbothered, with mindfulness and situational awareness.",
  "sn1.38:1.6": "And then he spread out his outer robe folded in four and laid down in the lion’s postureon the right side, placing one foot on top of the othermindful and aware.",
  "sn1.38:2.1": "Then, late at night, seven hundred glorious deities of the host of a hundred felicities, lighting up the entire Maddakucchi, went up to the Buddha, bowed, and stood to one side.",
  "sn1.38:2.2": "Standing to one side, one deity expressed this heartfelt sentiment in the Buddha’s presence:",
  "sn1.38:2.3": "“The ascetic Gotama is such an elephant, sir!",
  "sn1.38:2.4": "And as an elephant, he endures painful physical feelings that have come upsharp, severe, acute, unpleasant, and disagreeableunbothered, with mindfulness and situational awareness.”",
  "sn1.38:3.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence:",
  "sn1.38:3.2": "“The ascetic Gotama is such a lion, sir!",
  "sn1.38:3.3": "And as a lion, he endures painful physical feelings … unbothered.”",
  "sn1.38:4.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence:",
  "sn1.38:4.2": "“The ascetic Gotama is such a thoroughbred, sir!",
  "sn1.38:4.3": "And as a thoroughbred, he endures painful physical feelings … unbothered.”",
  "sn1.38:5.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence:",
  "sn1.38:5.2": "“The ascetic Gotama is such a boss bull, sir!",
  "sn1.38:5.3": "And as a boss bull, he endures painful physical feelings … unbothered.”",
  "sn1.38:6.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence:",
  "sn1.38:6.2": "“The ascetic Gotama is such a behemoth, sir!",
  "sn1.38:6.3": "And as a behemoth, he endures painful physical feelings … unbothered.”",
  "sn1.38:7.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence:",
  "sn1.38:7.2": "“The ascetic Gotama is truly tamed, sir!",
  "sn1.38:7.3": "And as someone tamed, he endures painful physical feelings … unbothered.”",
  "sn1.38:8.1": "Then another deity expressed this heartfelt sentiment in the Buddha’s presence:",
  "sn1.38:8.2": "“See, his immersion is so well developed, and his mind is so well freednot leaning forward or pulling back, and not held in place by forceful suppression.",
  "sn1.38:8.3": "If anyone imagines that they can overcome such an elephant of a man, a lion of a man, a thoroughbred of a man, a boss bull of a man, a behemoth of a man, a tamed manwhat is that but a failure to see?”",
  "sn1.38:9.1": "“Learned in the five branches of Vedic lore,",
  "sn1.38:9.2": "brahmins practice fervent mortification for a full century.",
  "sn1.38:9.3": "But their minds are not properly freed,",
  "sn1.38:9.4": "for those of base character don’t cross to the far shore.",
  "sn1.38:10.1": "Seized by craving,  <j>attached to precept and observance,",
  "sn1.38:10.2": "they practice rough and fervent mortification for a hundred years.",
  "sn1.38:10.3": "But their minds are not properly freed,",
  "sn1.38:10.4": "for those of base character don’t cross to the far shore.",
  "sn1.38:11.1": "Someone who’s fond of conceit can’t be tamed,",
  "sn1.38:11.2": "and someone without immersion can’t be a sage.",
  "sn1.38:11.3": "Living negligent alone in the wilderness,",
  "sn1.38:11.4": "they can’t cross beyond Death’s dominion.”",
  "sn1.38:12.1": "“Having given up conceit, serene within oneself,",
  "sn1.38:12.2": "with a good heart, everywhere free;",
  "sn1.38:12.3": "living diligent alone in the wilderness,",
  "sn1.38:12.4": "they cross beyond Death’s dominion.”",
  "sn1.39:0.1": "Linked Discourses 1.39",
  "sn1.39:0.2": "4. The Host of a Hundred Felicities",
  "sn1.39:0.3": "With Pajjunna’s Daughter (1st)",
  "sn1.39:1.1": "So I have heard.",
  "sn1.39:1.2": "At one time the Buddha was staying near Vesālī, at the Great Wood, in the hall with the peaked roof.",
  "sn1.39:1.3": "Then, late at night, the glorious Kokanadā, Pajjunna’s daughter, lighting up the entire Great Wood, went up to the Buddha, bowed, stood to one side,",
  "sn1.39:1.4": "and recited these verses in the Buddha’s presence:",
  "sn1.39:2.1": "“Staying in the woods of Vesālī",
  "sn1.39:2.2": "is the Buddha, best of creation.",
  "sn1.39:2.3": "Kokanadā am I who worships him,",
  "sn1.39:2.4": "Kokanadā, Pajjuna’s daughter.",
  "sn1.39:3.1": "Previously I had only heard",
  "sn1.39:3.2": "the teaching realized by the Clear-eyed One.",
  "sn1.39:3.3": "But now I know it as a witness",
  "sn1.39:3.4": "while the sage, the Holy One teaches.",
  "sn1.39:4.1": "There are simpletons who go about",
  "sn1.39:4.2": "denouncing the teaching of the noble ones.",
  "sn1.39:4.3": "They fall into the terrible Hell of Screams",
  "sn1.39:4.4": "where they suffer long.",
  "sn1.39:5.1": "There are those who have found  <j>acceptance and peace",
  "sn1.39:5.2": "in the teaching of the noble ones.",
  "sn1.39:5.3": "After giving up this human body,",
  "sn1.39:5.4": "they swell the hosts of gods.”",
  "sn1.40:0.1": "Linked Discourses 1.40",
  "sn1.40:0.2": "4. The Host of a Hundred Felicities",
  "sn1.40:0.3": "With Pajjunna’s Daughter (2nd)",
  "sn1.40:1.1": "So I have heard.",
  "sn1.40:1.2": "At one time the Buddha was staying near Vesālī, at the Great Wood, in the hall with the peaked roof.",
  "sn1.40:1.3": "Then, late at night, the glorious Kokanadā the Younger, Pajjunna’s daughter, lighting up the entire Great Wood, went up to the Buddha, bowed, stood to one side,",
  "sn1.40:1.4": "and recited these verses in the Buddha’s presence:",
  "sn1.40:2.1": "“She came here, beautiful as a flash of lightning,",
  "sn1.40:2.2": "Kokanadā, Pajjunna’s daughter.",
  "sn1.40:2.3": "Revering the Buddha and the teaching,",
  "sn1.40:2.4": "she spoke these verses full of meaning.",
  "sn1.40:3.1": "The teaching is such that",
  "sn1.40:3.2": "I could analyze it in many different ways.",
  "sn1.40:3.3": "However, I will state the meaning in brief",
  "sn1.40:3.4": "as far as I have learned it by heart.",
  "sn1.40:4.1": "You should never do anything bad",
  "sn1.40:4.2": "by speech or mind or body in all the world.",
  "sn1.40:4.3": "Having given up sensual pleasures,  <j>mindful and aware,",
  "sn1.40:4.4": "you shouldn’t keep doing  <j>what’s painful and pointless.”",
  "sn1.40:4.5": "",
  "sn1.40:5.1": "",
  "sn1.40:5.2": "",
  "sn1.40:5.3": ""
}
window.BILARA["sn1_v4"]["en"]["sn1_v4:source"] =
 "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
