window.BILARA = window.BILARA || {};
window.BILARA["sn2_v2"] = window.BILARA["sn2_v2"] || {};
window.BILARA["sn2_v2"]["en"] = {
  "sn2.11:0.1": "Linked Discourses 2.11",
  "sn2.11:0.2": "2. With Anāthapiṇḍika",
  "sn2.11:0.3": "With Candimasa",
  "sn2.11:1.1": "At Sāvatthī.",
  "sn2.11:1.2": "Then, late at night, the glorious godling Candimasa, lighting up the entire Jeta’s Grove, went up to the Buddha, bowed, stood to one side,",
  "sn2.11:1.3": "and spoke this verse in the Buddha’s presence:",
  "sn2.11:2.1": "“Like deer in a mosquito-free marsh,",
  "sn2.11:2.2": "they will reach a safe place",
  "sn2.11:2.3": "having entered the absorptions,",
  "sn2.11:2.4": "unified, alert, and mindful.”",
  "sn2.11:3.1": "“Like fish when the net is cut,",
  "sn2.11:3.2": "they will reach the far shore",
  "sn2.11:3.3": "having entered the absorptions,",
  "sn2.11:3.4": "diligent, with strife discarded.”",
  "sn2.12:0.1": "Linked Discourses 2.12",
  "sn2.12:0.2": "2. With Anāthapiṇḍika",
  "sn2.12:0.3": "With Vishnu",
  "sn2.12:1.1": "Standing to one side, the godling Vishnu spoke this verse in the Buddha’s presence:",
  "sn2.12:2.1": "“Happy are the men",
  "sn2.12:2.2": "who pay homage to the Holy One!",
  "sn2.12:2.3": "They apply themselves to Gotama’s instructions,",
  "sn2.12:2.4": "diligently training.”",
  "sn2.12:3.1": "“Those who practice absorption <j>in accord with the training”,",
  "sn2.12:3.2": "said the Buddha to Vishnu,",
  "sn2.12:3.3": "“in the way of teaching I’ve proclaimed,",
  "sn2.12:3.4": "diligent while there is still time;",
  "sn2.12:3.5": "they won’t fall under the sway of Death.”",
  "sn2.13:0.1": "Linked Discourses 2.13",
  "sn2.13:0.2": "2. With Anāthapiṇḍika",
  "sn2.13:0.3": "With Dīghalaṭṭhi",
  "sn2.13:1.1": "So I have heard.",
  "sn2.13:1.2": "At one time the Buddha was staying near Rājagaha, in the Bamboo Grove, the squirrels’ feeding ground.",
  "sn2.13:1.3": "Then, late at night, the glorious godling Dīghalaṭṭhi, lighting up the entire Bamboo Grove, went up to the Buddha, bowed, stood to one side,",
  "sn2.13:1.4": "and spoke this verse in the Buddha’s presence:",
  "sn2.13:2.1": "“If a mendicant is a meditator, freed in mind,",
  "sn2.13:2.2": "and if they desire the heart’s fulfillment",
  "sn2.13:2.3": "having known the arising and passing of the world,",
  "sn2.13:2.4": "good-hearted, independent, that is their reward.”",
  "sn2.14:0.1": "Linked Discourses 2.14",
  "sn2.14:0.2": "2. With Anāthapiṇḍika",
  "sn2.14:0.3": "With Nandana",
  "sn2.14:1.1": "Standing to one side, the godling Nandana addressed the Buddha in verse:",
  "sn2.14:2.1": "“I ask you, Gotama, whose wisdom is vast,",
  "sn2.14:2.2": "the Blessed One <j>of unhindered knowledge and vision.",
  "sn2.14:2.3": "What sort do they call ethical?",
  "sn2.14:2.4": "What sort do they call wise?",
  "sn2.14:2.5": "What sort lives on after transcending suffering?",
  "sn2.14:2.6": "What sort is worshipped by the deities?”",
  "sn2.14:3.1": "“Someone who is ethical, wise, evolved,",
  "sn2.14:3.2": "becomes serene, loving absorption, mindful,",
  "sn2.14:3.3": "who’s gotten rid of and given up all sorrows,",
  "sn2.14:3.4": "with defilements ended, they bear their final body.",
  "sn2.14:4.1": "That sort they call ethical.",
  "sn2.14:4.2": "That sort they call wise.",
  "sn2.14:4.3": "That sort lives on after transcending suffering.",
  "sn2.14:4.4": "That sort is worshipped by the deities.”",
  "sn2.15:0.1": "Linked Discourses 2.15",
  "sn2.15:0.2": "2. With Anāthapiṇḍika",
  "sn2.15:0.3": "With Candana",
  "sn2.15:1.1": "Standing to one side, the godling Candana addressed the Buddha in verse:",
  "sn2.15:2.1": "“Who here crosses the flood,",
  "sn2.15:2.2": "tireless all day and night?",
  "sn2.15:2.3": "Who, not standing and unsupported,",
  "sn2.15:2.4": "does not sink in the deep?”",
  "sn2.15:3.1": "“Someone who is always endowed with ethics,",
  "sn2.15:3.2": "wise and serene,",
  "sn2.15:3.3": "energetic and resolute,",
  "sn2.15:3.4": "crosses the flood so hard to cross.",
  "sn2.15:4.1": "Someone who desists from sensual perception,",
  "sn2.15:4.2": "has moved past the fetter of form,",
  "sn2.15:4.3": "and has finished with relishing and greed",
  "sn2.15:4.4": "does not sink in the deep.”",
  "sn2.16:0.1": "Linked Discourses 2.16",
  "sn2.16:0.2": "2. With Anāthapiṇḍika",
  "sn2.16:0.3": "With Vāsudatta",
  "sn2.16:1.1": "Standing to one side, the godling Vāsudatta spoke this verse in the Buddha’s presence:",
  "sn2.16:2.1": "“Like they’re struck by a sword,",
  "sn2.16:2.2": "like their head was on fire,",
  "sn2.16:2.3": "a mendicant should wander mindful,",
  "sn2.16:2.4": "to give up sensual desire.”",
  "sn2.16:3.1": "“Like they’re struck by a sword,",
  "sn2.16:3.2": "like their head was on fire,",
  "sn2.16:3.3": "a mendicant should wander mindful,",
  "sn2.16:3.4": "to give up substantialist view.”",
  "sn2.17:0.1": "Linked Discourses 2.17",
  "sn2.17:0.2": "2. With Anāthapiṇḍika",
  "sn2.17:0.3": "With Subrahmā",
  "sn2.17:1.1": "Standing to one side, the godling Subrahmā addressed the Buddha in verse:",
  "sn2.17:2.1": "“This mind is always anxious,",
  "sn2.17:2.2": "this mind is always stressed",
  "sn2.17:2.3": "about stresses that haven’t arisen",
  "sn2.17:2.4": "and those that have.",
  "sn2.17:2.5": "If there is a state free of anxiety,",
  "sn2.17:2.6": "please answer my question.”",
  "sn2.17:3.1": "“Not without understanding and fervor,",
  "sn2.17:3.2": "not without restraining the sense faculties,",
  "sn2.17:3.3": "not without letting go of everything,",
  "sn2.17:3.4": "do I see safety for living creatures.”",
  "sn2.17:4.1": "That is what the Buddha said. …",
  "sn2.17:4.2": "The god vanished right there.",
  "sn2.18:0.1": "Linked Discourses 2.18",
  "sn2.18:0.2": "2. With Anāthapiṇḍika",
  "sn2.18:0.3": "With Kakudha",
  "sn2.18:1.1": "So I have heard.",
  "sn2.18:1.2": "At one time the Buddha was staying near Sāketa in the deer park at the Añjana Wood.",
  "sn2.18:1.3": "Then, late at night, the glorious godling Kakudha, lighting up the entire Añjana Wood, went up to the Buddha, bowed, stood to one side, and said to him,",
  "sn2.18:1.4": "“Do you delight, ascetic?”",
  "sn2.18:1.5": "“What have I gained, sir?”",
  "sn2.18:1.6": "“Well then, ascetic, do you sorrow?”",
  "sn2.18:1.7": "“What have I lost, sir?”",
  "sn2.18:1.8": "“Well then, ascetic, do you neither delight nor sorrow?”",
  "sn2.18:1.9": "“Yes, sir.”",
  "sn2.18:2.1": "“I hope you’re not gloomy, mendicant,",
  "sn2.18:2.2": "I hope that delight isn’t found in you.",
  "sn2.18:2.3": "I hope that discontent doesn’t",
  "sn2.18:2.4": "overwhelm you as you sit alone.”",
  "sn2.18:3.1": "“I’m genuinely not gloomy, spirit,",
  "sn2.18:3.2": "and no delight is found in me.",
  "sn2.18:3.3": "And also discontent doesn’t",
  "sn2.18:3.4": "overwhelm me as I sit alone.”",
  "sn2.18:4.1": "“How are you not gloomy, mendicant?",
  "sn2.18:4.2": "How is delight not found in you?",
  "sn2.18:4.3": "How does discontent not",
  "sn2.18:4.4": "overwhelm you as you sit alone?”",
  "sn2.18:5.1": "“Delight is born from gloom,",
  "sn2.18:5.2": "gloom is born from delight;",
  "sn2.18:5.3": "sir, you should know me as",
  "sn2.18:5.4": "a mendicant free of delight and gloom.”",
  "sn2.18:6.1": "“After a long time I see",
  "sn2.18:6.2": "a brahmin fully quenched.",
  "sn2.18:6.3": "A mendicant free of delight and gloom,",
  "sn2.18:6.4": "he has crossed over clinging to the world.”",
  "sn2.19:0.1": "Linked Discourses 2.19",
  "sn2.19:0.2": "2. With Anāthapiṇḍika",
  "sn2.19:0.3": "With Uttara",
  "sn2.19:1.1": "At Rājagaha.",
  "sn2.19:1.2": "Standing to one side, the godling Uttara spoke this verse in the Buddha’s presence:",
  "sn2.19:2.1": "“This life, so very short, is led onward.",
  "sn2.19:2.2": "One led on to old age has no shelter.",
  "sn2.19:2.3": "Seeing this peril in death,",
  "sn2.19:2.4": "do good deeds that bring you joy.”",
  "sn2.19:3.1": "“This life, so very short, is led onward.",
  "sn2.19:3.2": "One led on to old age has no shelter.",
  "sn2.19:3.3": "Seeing this peril in death,",
  "sn2.19:3.4": "a seeker of peace would drop the world’s bait.”",
  "sn2.20:0.1": "Linked Discourses 2.20",
  "sn2.20:0.2": "2. With Anāthapiṇḍika",
  "sn2.20:0.3": "With Anāthapiṇḍika",
  "sn2.20:1.1": "Standing to one side, the godling Anāthapiṇḍika recited these verses in the Buddha’s presence:",
  "sn2.20:2.1": "“This is indeed that Jeta’s Grove,",
  "sn2.20:2.2": "frequented by the Saṅgha of seers,",
  "sn2.20:2.3": "where the King of Dhamma stayed:",
  "sn2.20:2.4": "it brings me joy!",
  "sn2.20:3.1": "Deeds, knowledge, and principle;",
  "sn2.20:3.2": "ethical conduct, an excellent livelihood;",
  "sn2.20:3.3": "by these are mortals purified,",
  "sn2.20:3.4": "not by clan or wealth.",
  "sn2.20:4.1": "That’s why an astute person,",
  "sn2.20:4.2": "seeing what’s good for themselves,",
  "sn2.20:4.3": "would examine the teaching rationally,",
  "sn2.20:4.4": "and thus be purified in it.",
  "sn2.20:5.1": "Sāriputta is full of wisdom,",
  "sn2.20:5.2": "ethics, and peace.",
  "sn2.20:5.3": "Even a mendicant who has crossed over",
  "sn2.20:5.4": "might at best equal him.”",
  "sn2.20:6.1": "This is what the godling Anāthapiṇḍika said.",
  "sn2.20:6.2": "Then he bowed and respectfully circled the Buddha, keeping him on his right side, before vanishing right there.",
  "sn2.20:7.1": "Then, when the night had passed, the Buddha addressed the mendicants:",
  "sn2.20:7.2": "“Mendicants, tonight, a certain glorious godling, lighting up the entire Jeta’s Grove, came to me, bowed, stood to one side,",
  "sn2.20:7.3": "and recited these verses in my presence.” The Buddha then repeated the verses in full.",
  "sn2.20:8.1": "",
  "sn2.20:8.2": "",
  "sn2.20:8.3": "",
  "sn2.20:8.4": "",
  "sn2.20:9.1": "",
  "sn2.20:9.2": "",
  "sn2.20:9.3": "",
  "sn2.20:9.4": "",
  "sn2.20:10.1": "",
  "sn2.20:10.2": "",
  "sn2.20:10.3": "",
  "sn2.20:10.4": "",
  "sn2.20:11.1": "",
  "sn2.20:11.2": "",
  "sn2.20:11.3": "",
  "sn2.20:11.4": "",
  "sn2.20:12.1": "",
  "sn2.20:12.2": "",
  "sn2.20:13.1": "When he said this, Venerable Ānanda said to the Buddha,",
  "sn2.20:13.2": "“Sir, that godling must surely have been Anāthapiṇḍika.",
  "sn2.20:13.3": "For the householder Anāthapiṇḍika was devoted to Venerable Sāriputta.”",
  "sn2.20:13.4": "“Good, good, Ānanda. You’ve reached the logical conclusion, as far as logic goes.",
  "sn2.20:13.5": "For that was indeed the godling Anāthapiṇḍika.”",
  "sn2.20:13.6": "",
  "sn2.20:14.1": "",
  "sn2.20:14.2": "",
  "sn2.20:14.3": "",
  "sn2.20:14.4": "",
  "sn2.20:14.5": ""
}
window.BILARA["sn2_v2"]["en"]["sn2_v2:source"] =
 "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
