window.BILARA = window.BILARA || {};
window.BILARA["sn3_v3"] = window.BILARA["sn3_v3"] || {};
window.BILARA["sn3_v3"]["en"] = {
  "sn3.21:0.1": "Linked Discourses 3.21",
  "sn3.21:0.2": "3. Kosala",
  "sn3.21:0.3": "Individuals",
  "sn3.21:1.1": "At Sāvatthī.",
  "sn3.21:1.2": "Then King Pasenadi of Kosala went up to the Buddha, bowed, and sat down to one side. The Buddha said to him:",
  "sn3.21:1.3": "“Great king, these four individuals are found in the world.",
  "sn3.21:1.4": "What four?",
  "sn3.21:1.5": "The dark bound for darkness,",
  "sn3.21:1.6": "the dark bound for light,",
  "sn3.21:1.7": "the light bound for darkness,",
  "sn3.21:1.8": "and the light bound for light.",
  "sn3.21:2.1": "And how is an individual dark and bound for darkness?",
  "sn3.21:2.2": "It’s when an individual is reborn in a low familya family of corpse-workers, bamboo-workers, hunters, chariot-makers, or scavengerspoor, with little to eat or drink, where life is tough, and food and shelter are hard to find.",
  "sn3.21:2.3": "And they’re ugly, unsightly, deformed, sicklyone-eyed, crippled, lame, or half-paralyzed. They don’t get to have food, drink, clothes, and vehicles; garlands, fragrance, and makeup; or bed, house, and lighting.",
  "sn3.21:2.4": "And they do bad things by way of body, speech, and mind.",
  "sn3.21:2.5": "When their body breaks up, after death, they’re reborn in a place of loss, a bad place, the underworld, hell.",
  "sn3.21:3.1": "This individual is like someone who goes from darkness to darkness, from blackness to blackness, from bloodstain to bloodstain.",
  "sn3.21:3.2": "",
  "sn3.21:3.3": "That’s how an individual is dark and bound for darkness.",
  "sn3.21:4.1": "And how is an individual dark and bound for light?",
  "sn3.21:4.2": "It’s when an individual is reborn in a low familya family of corpse-workers, bamboo-workers, hunters, chariot-makers, or scavengerspoor, with little to eat or drink, where life is tough, and food and shelter are hard to find.",
  "sn3.21:4.3": "And they’re ugly, unsightly, deformed, sicklyone-eyed, crippled, lame, or half-paralyzed. They don’t get to have food, drink, clothes, and vehicles; garlands, fragrance, and makeup; or bed, house, and lighting.",
  "sn3.21:4.4": "But they do good things by way of body, speech, and mind.",
  "sn3.21:4.5": "When their body breaks up, after death, they’re reborn in a good place, a heavenly realm.",
  "sn3.21:5.1": "This individual is like someone who ascends from the ground to a couch; from a couch to horseback; from horseback to an elephant; and from an elephant to a stilt longhouse.",
  "sn3.21:5.2": "",
  "sn3.21:5.3": "That’s how an individual is dark and bound for light.",
  "sn3.21:6.1": "And how is an individual light and bound for darkness?",
  "sn3.21:6.2": "It’s when an individual is reborn in an eminent familya well-to-do family of aristocrats, brahmins, or householdersrich, affluent, and wealthy, with lots of gold and silver, lots of property and assets, and lots of money and grain.",
  "sn3.21:6.3": "And they’re attractive, good-looking, lovely, of surpassing beauty. They get to have food, drink, clothes, and vehicles; garlands, fragrance, and makeup; and bed, house, and lighting.",
  "sn3.21:6.4": "But they do bad things by way of body, speech, and mind.",
  "sn3.21:6.5": "When their body breaks up, after death, they’re reborn in a place of loss, a bad place, the underworld, hell.",
  "sn3.21:7.1": "This individual is like someone who descends from a stilt longhouse to an elephant; from an elephant to horseback; from horseback to a couch; and from a couch to the ground; and from the ground they enter darkness.",
  "sn3.21:7.2": "",
  "sn3.21:7.3": "That’s how an individual is light and bound for darkness.",
  "sn3.21:8.1": "And how is an individual light and bound for light?",
  "sn3.21:8.2": "It’s when an individual is reborn in an eminent familya well-to-do family of aristocrats, brahmins, or householdersrich, affluent, and wealthy, with lots of gold and silver, lots of property and assets, and lots of money and grain.",
  "sn3.21:8.3": "And they’re attractive, good-looking, lovely, of surpassing beauty. They get to have food, drink, clothes, and vehicles; garlands, fragrance, and makeup; and bed, house, and lighting.",
  "sn3.21:8.4": "And they do good things by way of body, speech, and mind.",
  "sn3.21:8.5": "When their body breaks up, after death, they’re reborn in a good place, a heavenly realm.",
  "sn3.21:9.1": "This individual is like someone who shifts from one couch to another; from the back of one horse to another; from one elephant to another; or from one stilt longhouse to another.",
  "sn3.21:9.2": "",
  "sn3.21:9.3": "That’s how an individual is light and bound for light.",
  "sn3.21:9.4": "These are the four individuals found in the world.”",
  "sn3.21:9.5": "That is what the Buddha said. …",
  "sn3.21:10.1": "“O king, some people are poor,",
  "sn3.21:10.2": "faithless and stingy.",
  "sn3.21:10.3": "Miserly, with bad intentions,",
  "sn3.21:10.4": "they lack regard, they have wrong view.",
  "sn3.21:11.1": "They abuse and insult",
  "sn3.21:11.2": "ascetics and brahmins",
  "sn3.21:11.3": "and other supplicants.",
  "sn3.21:11.4": "They’re nihilists and bullies,",
  "sn3.21:12.1": "who prevent others from giving",
  "sn3.21:12.2": "food to beggars.",
  "sn3.21:12.3": "O king, ruler of the people:",
  "sn3.21:12.4": "when such people die",
  "sn3.21:12.5": "they fall into the terrible hell",
  "sn3.21:12.6": "from darkness they’re bound for darkness.",
  "sn3.21:13.1": "O king, some people are poor,",
  "sn3.21:13.2": "but faithful and not stingy.",
  "sn3.21:13.3": "They give with best of intentions,",
  "sn3.21:13.4": "that peaceful-hearted person.",
  "sn3.21:14.1": "They rise for and bow to",
  "sn3.21:14.2": "ascetics and brahmins",
  "sn3.21:14.3": "and other supplicants.",
  "sn3.21:14.4": "Training in moral conduct,",
  "sn3.21:15.1": "they don’t prevent others from giving",
  "sn3.21:15.2": "food to beggars.",
  "sn3.21:15.3": "O king, ruler of the people:",
  "sn3.21:15.4": "when such people die",
  "sn3.21:15.5": "they go to the Third Heaven",
  "sn3.21:15.6": "from darkness they’re bound for light.",
  "sn3.21:16.1": "O king, some people are rich,",
  "sn3.21:16.2": "but faithless and stingy.",
  "sn3.21:16.3": "Miserly, with bad intentions,",
  "sn3.21:16.4": "they lack regard, they have wrong view.",
  "sn3.21:17.1": "They abuse and insult",
  "sn3.21:17.2": "ascetics and brahmins",
  "sn3.21:17.3": "and other supplicants",
  "sn3.21:17.4": "They’re nihilists and bullies,",
  "sn3.21:18.1": "who prevent others from giving",
  "sn3.21:18.2": "food to beggars.",
  "sn3.21:18.3": "O king, ruler of the people:",
  "sn3.21:18.4": "when such people die",
  "sn3.21:18.5": "they fall into the terrible hell",
  "sn3.21:18.6": "from light they’re bound for darkness.",
  "sn3.21:19.1": "O king, some people are rich,",
  "sn3.21:19.2": "faithful and not stingy.",
  "sn3.21:19.3": "They give with best of intentions,",
  "sn3.21:19.4": "that peaceful-hearted person.",
  "sn3.21:20.1": "They rise for and bow to",
  "sn3.21:20.2": "ascetics and brahmins",
  "sn3.21:20.3": "and other supplicants.",
  "sn3.21:20.4": "Training in moral conduct,",
  "sn3.21:21.1": "they don’t prevent others from giving",
  "sn3.21:21.2": "food to beggars.",
  "sn3.21:21.3": "O king, ruler of the people:",
  "sn3.21:21.4": "when such people die",
  "sn3.21:21.5": "they go to the Third Heaven",
  "sn3.21:21.6": "from light they’re bound for light.”",
  "sn3.22:0.1": "Linked Discourses 3.22",
  "sn3.22:0.2": "3. Kosala",
  "sn3.22:0.3": "Grandmother",
  "sn3.22:1.1": "At Sāvatthī.",
  "sn3.22:1.2": "King Pasenadi of Kosala sat to one side, and the Buddha said to him,",
  "sn3.22:1.3": "“So, great king, where are you coming from in the middle of the day?”",
  "sn3.22:2.1": "“Sir, my grandmother has passed away. She was old, elderly and senior. She was advanced in years and had reached the final stage of life; she was a hundred and twenty years old.",
  "sn3.22:2.2": "But I loved my grandmother; she was dear to me.",
  "sn3.22:2.3": "If by giving away the elephant-treasure I could get my grandmother back, I’d do it.",
  "sn3.22:2.4": "",
  "sn3.22:2.5": "If by giving away the horse-treasure I could get my grandmother back, I’d do it.",
  "sn3.22:2.6": "",
  "sn3.22:2.7": "If by giving away a prize village I could get my grandmother back, I’d do it.",
  "sn3.22:2.8": "",
  "sn3.22:2.9": "If by giving away the whole country I could get my grandmother back, I’d do it.”",
  "sn3.22:2.10": "",
  "sn3.22:2.11": "“Great king, all sentient beings are liable to die. Death is their end; they’re not exempt from death.”",
  "sn3.22:2.12": "“It’s incredible, sir, it’s amazing,",
  "sn3.22:2.13": "how well said this was by the Buddha:",
  "sn3.22:2.14": "‘All sentient beings are liable to die. Death is their end; they’re not exempt from death.’”",
  "sn3.22:3.1": "“That’s so true, great king! That’s so true!",
  "sn3.22:3.2": "All sentient beings are liable to die. Death is their end; they’re not exempt from death.",
  "sn3.22:3.3": "It’s like the vessels made by potters. Whatever kind they are, whether baked or unbaked, all of them are liable to break apart. Breaking is their end; they’re not exempt from breakage.",
  "sn3.22:3.4": "In the same way, all sentient beings are liable to die. Death is their end; they’re not exempt from death.”",
  "sn3.22:3.5": "That is what the Buddha said. …",
  "sn3.22:4.1": "“All beings will die,",
  "sn3.22:4.2": "for life ends in death.",
  "sn3.22:4.3": "They pass on according to their deeds,",
  "sn3.22:4.4": "reaping the fruits of good and bad.",
  "sn3.22:4.5": "Those who do bad go to hell,",
  "sn3.22:4.6": "and if you do good you go to heaven.",
  "sn3.22:5.1": "That’s why you should do good,",
  "sn3.22:5.2": "investing in the future life.",
  "sn3.22:5.3": "The good deeds of sentient beings",
  "sn3.22:5.4": "support them in the next world.”",
  "sn3.23:0.1": "Linked Discourses 3.23",
  "sn3.23:0.2": "3. Kosala",
  "sn3.23:0.3": "The World",
  "sn3.23:1.1": "At Sāvatthī.",
  "sn3.23:1.2": "Seated to one side, King Pasenadi said to the Buddha,",
  "sn3.23:1.3": "“Sir, how many things arise in the world for its harm, suffering, and discomfort?”",
  "sn3.23:1.4": "“Great king, three things arise in the world for its harm, suffering, and discomfort.",
  "sn3.23:1.5": "What three?",
  "sn3.23:1.6": "Greed,",
  "sn3.23:1.7": "hate,",
  "sn3.23:1.8": "and delusion.",
  "sn3.23:1.9": "These three things arise in the world for its harm, suffering, and discomfort.”",
  "sn3.23:1.10": "That is what the Buddha said. …",
  "sn3.23:2.1": "“When greed, hate, and delusion,",
  "sn3.23:2.2": "originate inside oneself,",
  "sn3.23:2.3": "they harm a person of wicked heart,",
  "sn3.23:2.4": "as a bamboo is destroyed by its own fruit.”",
  "sn3.24:0.1": "Linked Discourses 3.24",
  "sn3.24:0.2": "3. Kosala",
  "sn3.24:0.3": "Archery",
  "sn3.24:1.1": "At Sāvatthī.",
  "sn3.24:1.2": "Seated to one side, King Pasenadi said to the Buddha,",
  "sn3.24:1.3": "“Sir, where should a gift be given?”",
  "sn3.24:1.4": "“Wherever your heart feels inspired, great king.”",
  "sn3.24:1.5": "“But sir, where is a gift very fruitful?”",
  "sn3.24:1.6": "“Where a gift should be given is one thing, great king, but where a gift is very fruitful is another.",
  "sn3.24:1.7": "A gift is very fruitful when it’s given to an ethical person, not so much to an unethical person.",
  "sn3.24:1.8": "Well then, great king, I’ll ask you about this in return, and you can answer as you like.",
  "sn3.24:1.9": "What do you think, great king?",
  "sn3.24:1.10": "Suppose you were at war, ready to fight a battle.",
  "sn3.24:1.11": "Then along comes an aristocrat youth who is untrained, inexpert, unfit, inexperienced. And he’s fearful, scared, nervous, quick to flee.",
  "sn3.24:1.12": "Would you employ such a man? Would he be of any use to you?”",
  "sn3.24:1.13": "“No, sir, I would have no use for such a man.”",
  "sn3.24:1.14": "“What about a brahmin youth,",
  "sn3.24:1.15": "a peasant youth,",
  "sn3.24:1.16": "or a menial youth who was similar?”",
  "sn3.24:1.17": "“No, sir, I would have no use for such a man.”",
  "sn3.24:2.1": "“What do you think, great king?",
  "sn3.24:2.2": "Suppose you were at war, ready to fight a battle.",
  "sn3.24:2.3": "Then along comes an aristocrat youth who is trained, expert, fit, experienced. And he’s fearless, brave, bold, standing his ground.",
  "sn3.24:2.4": "Would you employ such a man? Would he be of any use to you?”",
  "sn3.24:2.5": "“Yes, sir, I would have a use for such a man.”",
  "sn3.24:2.6": "“What about a brahmin youth,",
  "sn3.24:2.7": "a peasant youth,",
  "sn3.24:2.8": "or a menial youth who was similar?",
  "sn3.24:2.9": "Would you employ such a man? Would he be of any use to you?”",
  "sn3.24:2.10": "“Yes, sir, I would have a use for such a man.”",
  "sn3.24:3.1": "“In the same way, a gift to anyone who has given up five factors and possesses five factors is very fruitful, no matter what family they’ve gone forth from.",
  "sn3.24:3.2": "What are the five factors they’ve given up?",
  "sn3.24:3.3": "Sensual desire, ill will, dullness and drowsiness, restlessness and remorse, and doubt.",
  "sn3.24:3.4": "These are the five factors they’ve given up.",
  "sn3.24:3.5": "What are the five factors they possess?",
  "sn3.24:3.6": "The entire spectrum of an adept’s ethics, immersion, wisdom, freedom, and knowledge and vision of freedom.",
  "sn3.24:3.7": "These are the five factors they possess.",
  "sn3.24:3.8": "I say that a gift to anyone who has given up these five factors and possesses these five factors is very fruitful.”",
  "sn3.24:3.9": "That is what the Buddha said.",
  "sn3.24:3.10": "Then the Holy One, the Teacher, went on to say:",
  "sn3.24:4.1": "“Any youth skilled at archery,",
  "sn3.24:4.2": "powerful and vigorous,",
  "sn3.24:4.3": "would be employed by a king going to war",
  "sn3.24:4.4": "one is not a coward by reason of birth.",
  "sn3.24:5.1": "Just so, whoever is settled",
  "sn3.24:5.2": "in the qualities of patience and gentleness,",
  "sn3.24:5.3": "a clever person with noble conduct,",
  "sn3.24:5.4": "should be venerated even if they’re low born.",
  "sn3.24:6.1": "You should build lovely hermitages",
  "sn3.24:6.2": "and settle learned people in them.",
  "sn3.24:6.3": "You should set up water supplies in barren regions",
  "sn3.24:6.4": "and passages in places hard to travel.",
  "sn3.24:7.1": "Food, drink, edibles,",
  "sn3.24:7.2": "clothes, and lodgings",
  "sn3.24:7.3": "should be given to the upright ones,",
  "sn3.24:7.4": "with a clear and confident heart.",
  "sn3.24:8.1": "The thundering rain cloud,",
  "sn3.24:8.2": "its hundred peaks wreathed in lightning,",
  "sn3.24:8.3": "pours down over the rich earth,",
  "sn3.24:8.4": "soaking the uplands and valleys.",
  "sn3.24:9.1": "So too an astute person,",
  "sn3.24:9.2": "faithful and learned,",
  "sn3.24:9.3": "should prepare a meal to satisfy",
  "sn3.24:9.4": "supplicants with food and drink.",
  "sn3.24:10.1": "Rejoicing, they strew gifts about,",
  "sn3.24:10.2": "crying ‘Give! give!’",
  "sn3.24:10.3": "For that is their thunder,",
  "sn3.24:10.4": "like rain sent from the heavens.",
  "sn3.24:10.5": "That stream of merit so abundant",
  "sn3.24:10.6": "showers down on the giver.”",
  "sn3.25:0.1": "Linked Discourses 3.25",
  "sn3.25:0.2": "3. Kosala",
  "sn3.25:0.3": "The Simile of the Mountain",
  "sn3.25:1.1": "At Sāvatthī.",
  "sn3.25:1.2": "King Pasenadi of Kosala sat to one side, and the Buddha said to him,",
  "sn3.25:1.3": "“So, great king, where are you coming from in the middle of the day?”",
  "sn3.25:1.4": "“Sir, there are anointed aristocratic kings who are infatuated with authority, and obsessed with greed for sensual pleasures. They have attained stability in the country, occupying a vast conquered territory. Today I have been busy fulfilling the duties of such kings.”",
  "sn3.25:2.1": "“What do you think, great king?",
  "sn3.25:2.2": "Suppose a trustworthy and dependable man were to come from the east.",
  "sn3.25:2.3": "He’d approach you and say:",
  "sn3.25:2.4": "‘Please great king, you should know this. I come from the east.",
  "sn3.25:2.5": "There I saw a huge mountain that reached the clouds. And it was coming this way, crushing all creatures.",
  "sn3.25:2.6": "So then, great king, do what you must!’",
  "sn3.25:2.7": "Then a second trustworthy and dependable man were to come from the west …",
  "sn3.25:2.8": "a third from the north …",
  "sn3.25:2.9": "and a fourth from the south.",
  "sn3.25:2.10": "He’d approach you and say:",
  "sn3.25:2.11": "‘Please great king, you should know this. I come from the south.",
  "sn3.25:2.12": "There I saw a huge mountain that reached the clouds. And it was coming this way, crushing all creatures.",
  "sn3.25:2.13": "So then, great king, do what you must!’",
  "sn3.25:2.14": "Should such a dire threat arisea grim loss of human life, when human birth is so rarewhat would you do?”",
  "sn3.25:3.1": "“Sir, what could I do but practice the teachings, practice morality, doing skillful and good actions?”",
  "sn3.25:4.1": "“I tell you, great king, I announce to you: old age and death are advancing upon you.",
  "sn3.25:4.2": "Since old age and death are advancing upon you, what would you do?”",
  "sn3.25:4.3": "“Sir, what can I do but practice the teachings, practice morality, doing skillful and good actions?",
  "sn3.25:4.4": "Sir, there are anointed aristocratic kings who are infatuated with authority, and obsessed with greed for sensual pleasures. They have attained stability in the country, occupying a vast conquered territory. Such kings engage in battles of elephants,",
  "sn3.25:4.5": "",
  "sn3.25:4.6": "",
  "sn3.25:4.7": "cavalry,",
  "sn3.25:4.8": "chariots,",
  "sn3.25:4.9": "or infantry.",
  "sn3.25:4.10": "But there is no place, no domain for such battles when old age and death are advancing.",
  "sn3.25:4.11": "In this royal court there are ministers of wise counsel who are capable of dividing an approaching enemy by wise counsel.",
  "sn3.25:4.12": "But there is no place, no domain for such diplomatic battles when old age and death are advancing.",
  "sn3.25:4.13": "In this royal court there is abundant gold, both coined and uncoined, stored above and below ground. Using this wealth we can bribe an approaching enemy.",
  "sn3.25:4.14": "But there is no place, no domain for such monetary battles when old age and death are advancing.",
  "sn3.25:4.15": "When old age and death are advancing, what can I do but practice the teachings, practice morality, doing skillful and good actions?”",
  "sn3.25:5.1": "“That’s so true, great king! That’s so true!",
  "sn3.25:5.2": "When old age and death are advancing, what can you do but practice the teachings, practice morality, doing skillful and good actions?”",
  "sn3.25:5.3": "That is what the Buddha said.",
  "sn3.25:5.4": "Then the Holy One, the Teacher, went on to say:",
  "sn3.25:6.1": "“Suppose there were vast mountains",
  "sn3.25:6.2": "of solid rock pressing against the sky",
  "sn3.25:6.3": "drawing in from all sides",
  "sn3.25:6.4": "and crushing the four quarters.",
  "sn3.25:7.1": "So too old age and death",
  "sn3.25:7.2": "advance upon all living creatures",
  "sn3.25:7.3": "aristocrats, brahmins, peasants,",
  "sn3.25:7.4": "menials, corpse-workers, and scavengers.",
  "sn3.25:7.5": "They spare nothing.",
  "sn3.25:7.6": "They crush all beneath them.",
  "sn3.25:8.1": "There’s nowhere for elephants to take a stand,",
  "sn3.25:8.2": "nor chariots nor infantry.",
  "sn3.25:8.3": "They can’t be defeated",
  "sn3.25:8.4": "by diplomatic battles or by wealth.",
  "sn3.25:9.1": "That’s why an astute person,",
  "sn3.25:9.2": "seeing what’s good for themselves,",
  "sn3.25:9.3": "being wise, would place faith",
  "sn3.25:9.4": "in the Buddha, the teaching, and the Saṅgha.",
  "sn3.25:10.1": "Whoever lives by the teaching",
  "sn3.25:10.2": "in body, speech, and mind,",
  "sn3.25:10.3": "is praised in this life",
  "sn3.25:10.4": "and departs to rejoice in heaven.”",
  "sn3.25:10.5": "",
  "sn3.25:11.1": "",
  "sn3.25:11.2": "",
  "sn3.25:11.3": "",
  "sn3.25:11.4": "",
  "sn3.25:11.5": "The Linked Discourses with the Kosalan are completed."
}
window.BILARA["sn3_v3"]["en"]["sn3_v3:source"] =
 "SOURCE: https://suttacentral.net/  TRANSLATE BY SUJATO";
