window.BILARA = window.BILARA || {};
window.BILARA["sn1_v4"] = window.BILARA["sn1_v4"] || {};
window.BILARA["sn1_v4"]["pli"] = {
  "sn1.31:0.1": "Saṁyutta Nikāya 1.31",
  "sn1.31:0.2": "4. Satullapakāyikavagga",
  "sn1.31:0.3": "Sabbhisutta",
  "sn1.31:1.1": "Evaṁ me sutaṁ",
  "sn1.31:1.2": "ekaṁ samayaṁ bhagavā sāvatthiyaṁ viharati jetavane anāthapiṇḍikassa ārāme.",
  "sn1.31:1.3": "Atha kho sambahulā satullapakāyikā devatāyo abhikkantāya rattiyā abhikkantavaṇṇā kevalakappaṁ jetavanaṁ obhāsetvā yena bhagavā tenupasaṅkamiṁsu; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ aṭṭhaṁsu.",
  "sn1.31:1.4": "Ekamantaṁ ṭhitā kho ekā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.31:2.1": "“Sabbhireva samāsetha,",
  "sn1.31:2.2": "sabbhi kubbetha santhavaṁ;",
  "sn1.31:2.3": "Sataṁ saddhammamaññāya,",
  "sn1.31:2.4": "seyyo hoti na pāpiyo”ti.",
  "sn1.31:3.1": "Atha kho aparā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.31:4.1": "“Sabbhireva samāsetha,",
  "sn1.31:4.2": "sabbhi kubbetha santhavaṁ;",
  "sn1.31:4.3": "Sataṁ saddhammamaññāya,",
  "sn1.31:4.4": "paññā labbhati nāññato”ti.",
  "sn1.31:5.1": "Atha kho aparā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.31:6.1": "“Sabbhireva samāsetha,",
  "sn1.31:6.2": "sabbhi kubbetha santhavaṁ;",
  "sn1.31:6.3": "Sataṁ saddhammamaññāya,",
  "sn1.31:6.4": "sokamajjhe na socatī”ti.",
  "sn1.31:7.1": "Atha kho aparā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.31:8.1": "“Sabbhireva samāsetha,",
  "sn1.31:8.2": "sabbhi kubbetha santhavaṁ;",
  "sn1.31:8.3": "Sataṁ saddhammamaññāya,",
  "sn1.31:8.4": "ñātimajjhe virocatī”ti.",
  "sn1.31:9.1": "Atha kho aparā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.31:10.1": "“Sabbhireva samāsetha,",
  "sn1.31:10.2": "sabbhi kubbetha santhavaṁ;",
  "sn1.31:10.3": "Sataṁ saddhammamaññāya,",
  "sn1.31:10.4": "sattā gacchanti suggatin”ti.",
  "sn1.31:11.1": "Atha kho aparā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.31:12.1": "“Sabbhireva samāsetha,",
  "sn1.31:12.2": "sabbhi kubbetha santhavaṁ;",
  "sn1.31:12.3": "Sataṁ saddhammamaññāya,",
  "sn1.31:12.4": "sattā tiṭṭhanti sātatan”ti.",
  "sn1.31:13.1": "Atha kho aparā devatā bhagavantaṁ etadavoca:",
  "sn1.31:13.2": "“kassa nu kho, bhagavā, subhāsitan”ti?",
  "sn1.31:14.1": "“Sabbāsaṁ vo subhāsitaṁ pariyāyena, api ca mamapi suṇātha",
  "sn1.31:15.1": "Sabbhireva samāsetha,",
  "sn1.31:15.2": "sabbhi kubbetha santhavaṁ;",
  "sn1.31:15.3": "Sataṁ saddhammamaññāya,",
  "sn1.31:15.4": "sabbadukkhā pamuccatī”ti.",
  "sn1.31:16.1": "Idamavoca bhagavā.",
  "sn1.31:16.2": "Attamanā tā devatāyo bhagavantaṁ abhivādetvā padakkhiṇaṁ katvā tatthevantaradhāyiṁsūti.",
  "sn1.32:0.1": "Saṁyutta Nikāya 1.32",
  "sn1.32:0.2": "4. Satullapakāyikavagga",
  "sn1.32:0.3": "Maccharisutta",
  "sn1.32:1.1": "Ekaṁ samayaṁ bhagavā sāvatthiyaṁ viharati jetavane anāthapiṇḍikassa ārāme.",
  "sn1.32:1.2": "Atha kho sambahulā satullapakāyikā devatāyo abhikkantāya rattiyā abhikkantavaṇṇā kevalakappaṁ jetavanaṁ obhāsetvā yena bhagavā tenupasaṅkamiṁsu; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ aṭṭhaṁsu.",
  "sn1.32:1.3": "Ekamantaṁ ṭhitā kho ekā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.32:2.1": "“Maccherā ca pamādā ca,",
  "sn1.32:2.2": "evaṁ dānaṁ na dīyati;",
  "sn1.32:2.3": "Puññaṁ ākaṅkhamānena,",
  "sn1.32:2.4": "deyyaṁ hoti vijānatā”ti.",
  "sn1.32:3.1": "Atha kho aparā devatā bhagavato santike imā gāthāyo abhāsi:",
  "sn1.32:4.1": "“Yasseva bhīto na dadāti maccharī,",
  "sn1.32:4.2": "Tadevādadato bhayaṁ;",
  "sn1.32:4.3": "Jighacchā ca pipāsā ca,",
  "sn1.32:4.4": "Yassa bhāyati maccharī;",
  "sn1.32:4.5": "Tameva bālaṁ phusati,",
  "sn1.32:4.6": "Asmiṁ loke paramhi ca.",
  "sn1.32:5.1": "Tasmā vineyya maccheraṁ,",
  "sn1.32:5.2": "dajjā dānaṁ malābhibhū;",
  "sn1.32:5.3": "Puññāni paralokasmiṁ,",
  "sn1.32:5.4": "patiṭṭhā honti pāṇinan”ti.",
  "sn1.32:6.1": "Atha kho aparā devatā bhagavato santike imā gāthāyo abhāsi:",
  "sn1.32:7.1": "“Te matesu na mīyanti,",
  "sn1.32:7.2": "panthānaṁva sahabbajaṁ;",
  "sn1.32:7.3": "Appasmiṁ ye pavecchanti,",
  "sn1.32:7.4": "esa dhammo sanantano.",
  "sn1.32:8.1": "Appasmeke pavecchanti,",
  "sn1.32:8.2": "bahuneke na dicchare;",
  "sn1.32:8.3": "Appasmā dakkhiṇā dinnā,",
  "sn1.32:8.4": "sahassena samaṁ mitā”ti.",
  "sn1.32:9.1": "Atha kho aparā devatā bhagavato santike imā gāthāyo abhāsi:",
  "sn1.32:10.1": "“Duddadaṁ dadamānānaṁ,",
  "sn1.32:10.2": "dukkaraṁ kamma kubbataṁ;",
  "sn1.32:10.3": "Asanto nānukubbanti,",
  "sn1.32:10.4": "sataṁ dhammo duranvayo.",
  "sn1.32:11.1": "Tasmā satañca asataṁ,",
  "sn1.32:11.2": "nānā hoti ito gati;",
  "sn1.32:11.3": "Asanto nirayaṁ yanti,",
  "sn1.32:11.4": "santo saggaparāyanā”ti.",
  "sn1.32:12.1": "Atha kho aparā devatā bhagavato santike etadavoca:",
  "sn1.32:12.2": "“kassa nu kho, bhagavā, subhāsitan”ti?",
  "sn1.32:13.1": "“Sabbāsaṁ vo subhāsitaṁ pariyāyena; api ca mamapi suṇātha",
  "sn1.32:14.1": "Dhammaṁ care yopi samuñjakaṁ care,",
  "sn1.32:14.2": "Dārañca posaṁ dadamappakasmiṁ;",
  "sn1.32:14.3": "Sataṁ sahassānaṁ sahassayāginaṁ,",
  "sn1.32:14.4": "Kalampi nāgghanti tathāvidhassa te”ti.",
  "sn1.32:15.1": "Atha kho aparā devatā bhagavantaṁ gāthāya ajjhabhāsi:",
  "sn1.32:16.1": "“Kenesa yañño vipulo mahaggato,",
  "sn1.32:16.2": "Samena dinnassa na agghameti;",
  "sn1.32:16.3": "Kathaṁ sataṁ sahassānaṁ sahassayāginaṁ,",
  "sn1.32:16.4": "Kalampi nāgghanti tathāvidhassa te”ti.",
  "sn1.32:17.1": "“Dadanti heke visame niviṭṭhā,",
  "sn1.32:17.2": "Chetvā vadhitvā atha socayitvā;",
  "sn1.32:17.3": "Sā dakkhiṇā assumukhā sadaṇḍā,",
  "sn1.32:17.4": "Samena dinnassa na agghameti.",
  "sn1.32:18.1": "Evaṁ sataṁ sahassānaṁ sahassayāginaṁ,",
  "sn1.32:18.2": "Kalampi nāgghanti tathāvidhassa te”ti.",
  "sn1.33:0.1": "Saṁyutta Nikāya 1.33",
  "sn1.33:0.2": "4. Satullapakāyikavagga",
  "sn1.33:0.3": "Sādhusutta",
  "sn1.33:1.1": "Sāvatthinidānaṁ.",
  "sn1.33:1.2": "Atha kho sambahulā satullapakāyikā devatāyo abhikkantāya rattiyā abhikkantavaṇṇā kevalakappaṁ jetavanaṁ obhāsetvā yena bhagavā tenupasaṅkamiṁsu; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ aṭṭhaṁsu.",
  "sn1.33:1.3": "Ekamantaṁ ṭhitā kho ekā devatā bhagavato santike imaṁ udānaṁ udānesi:",
  "sn1.33:2.1": "“Sādhu kho mārisa dānaṁ,",
  "sn1.33:2.2": "maccherā ca pamādā ca;",
  "sn1.33:2.3": "Evaṁ dānaṁ na dīyati,",
  "sn1.33:2.4": "puññaṁ ākaṅkhamānena;",
  "sn1.33:2.5": "Deyyaṁ hoti vijānatā”ti.",
  "sn1.33:3.1": "Atha kho aparā devatā bhagavato santike imaṁ udānaṁ udānesi:",
  "sn1.33:4.1": "“Sādhu kho mārisa dānaṁ,",
  "sn1.33:4.2": "Api ca appakasmimpi sāhu dānaṁ.",
  "sn1.33:5.1": "Appasmeke pavecchanti,",
  "sn1.33:5.2": "bahuneke na dicchare;",
  "sn1.33:5.3": "Appasmā dakkhiṇā dinnā,",
  "sn1.33:5.4": "sahassena samaṁ mitā”ti.",
  "sn1.33:6.1": "Atha kho aparā devatā bhagavato santike imaṁ udānaṁ udānesi:",
  "sn1.33:7.1": "“Sādhu kho mārisa dānaṁ,",
  "sn1.33:7.2": "Appakasmimpi sāhu dānaṁ;",
  "sn1.33:7.3": "Api ca saddhāyapi sāhu dānaṁ,",
  "sn1.33:7.4": "Dānañca yuddhañca samānamāhu;",
  "sn1.33:7.5": "Appāpi santā bahuke jinanti,",
  "sn1.33:7.6": "Appampi ce saddahāno dadāti;",
  "sn1.33:7.7": "Teneva so hoti sukhī paratthā”ti.",
  "sn1.33:8.1": "Atha kho aparā devatā bhagavato santike imaṁ udānaṁ udānesi:",
  "sn1.33:9.1": "“Sādhu kho mārisa dānaṁ,",
  "sn1.33:9.2": "Appakasmimpi sāhu dānaṁ;",
  "sn1.33:9.3": "Saddhāyapi sāhu dānaṁ,",
  "sn1.33:9.4": "Api ca dhammaladdhassāpi sāhu dānaṁ.",
  "sn1.33:10.1": "Yo dhammaladdhassa dadāti dānaṁ,",
  "sn1.33:10.2": "Uṭṭhānavīriyādhigatassa jantu;",
  "sn1.33:10.3": "Atikkamma so vetaraṇiṁ yamassa,",
  "sn1.33:10.4": "Dibbāni ṭhānāni upeti macco”ti.",
  "sn1.33:11.1": "Atha kho aparā devatā bhagavato santike imaṁ udānaṁ udānesi:",
  "sn1.33:12.1": "“Sādhu kho mārisa dānaṁ,",
  "sn1.33:12.2": "Appakasmimpi sāhu dānaṁ;",
  "sn1.33:12.3": "Saddhāyapi sāhu dānaṁ,",
  "sn1.33:12.4": "Dhammaladdhassāpi sāhu dānaṁ;",
  "sn1.33:12.5": "Api ca viceyya dānampi sāhu dānaṁ.",
  "sn1.33:13.1": "Viceyya dānaṁ sugatappasatthaṁ,",
  "sn1.33:13.2": "Ye dakkhiṇeyyā idha jīvaloke;",
  "sn1.33:13.3": "Etesu dinnāni mahapphalāni,",
  "sn1.33:13.4": "Bījāni vuttāni yathā sukhette”ti.",
  "sn1.33:14.1": "Atha kho aparā devatā bhagavato santike imaṁ udānaṁ udānesi:",
  "sn1.33:15.1": "“Sādhu kho mārisa dānaṁ,",
  "sn1.33:15.2": "Appakasmimpi sāhu dānaṁ;",
  "sn1.33:15.3": "Saddhāyapi sāhu dānaṁ,",
  "sn1.33:15.4": "Dhammaladdhassāpi sāhu dānaṁ;",
  "sn1.33:15.5": "Viceyya dānampi sāhu dānaṁ,",
  "sn1.33:15.6": "Api ca pāṇesupi sādhu saṁyamo.",
  "sn1.33:16.1": "Yo pāṇabhūtāni aheṭhayaṁ caraṁ,",
  "sn1.33:16.2": "Parūpavādā na karonti pāpaṁ;",
  "sn1.33:16.3": "Bhīruṁ pasaṁsanti na hi tattha sūraṁ,",
  "sn1.33:16.4": "Bhayā hi santo na karonti pāpan”ti.",
  "sn1.33:17.1": "Atha kho aparā devatā bhagavantaṁ etadavoca:",
  "sn1.33:17.2": "“kassa nu kho, bhagavā, subhāsitan”ti?",
  "sn1.33:18.1": "“Sabbāsaṁ vo subhāsitaṁ pariyāyena, api ca mamapi suṇātha",
  "sn1.33:19.1": "Saddhā hi dānaṁ bahudhā pasatthaṁ,",
  "sn1.33:19.2": "Dānā ca kho dhammapadaṁva seyyo;",
  "sn1.33:19.3": "Pubbe ca hi pubbatare ca santo,",
  "sn1.33:19.4": "Nibbānamevajjhagamuṁ sapaññā”ti.",
  "sn1.34:0.1": "Saṁyutta Nikāya 1.34",
  "sn1.34:0.2": "4. Satullapakāyikavagga",
  "sn1.34:0.3": "Nasantisutta",
  "sn1.34:1.1": "Ekaṁ samayaṁ bhagavā sāvatthiyaṁ viharati jetavane anāthapiṇḍikassa ārāme.",
  "sn1.34:1.2": "Atha kho sambahulā satullapakāyikā devatāyo abhikkantāya rattiyā abhikkantavaṇṇā kevalakappaṁ jetavanaṁ obhāsetvā yena bhagavā tenupasaṅkamiṁsu; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ aṭṭhaṁsu.",
  "sn1.34:1.3": "Ekamantaṁ ṭhitā kho ekā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.34:2.1": "“Na santi kāmā manujesu niccā,",
  "sn1.34:2.2": "Santīdha kamanīyāni yesu baddho;",
  "sn1.34:2.3": "Yesu pamatto apunāgamanaṁ,",
  "sn1.34:2.4": "Anāgantā puriso maccudheyyā”ti.",
  "sn1.34:3.1": "“Chandajaṁ aghaṁ chandajaṁ dukkhaṁ,",
  "sn1.34:3.2": "Chandavinayā aghavinayo;",
  "sn1.34:3.3": "Aghavinayā dukkhavinayo”ti.",
  "sn1.34:4.1": "“Na te kāmā yāni citrāni loke,",
  "sn1.34:4.2": "Saṅkapparāgo purisassa kāmo;",
  "sn1.34:4.3": "Tiṭṭhanti citrāni tatheva loke,",
  "sn1.34:4.4": "Athettha dhīrā vinayanti chandaṁ.",
  "sn1.34:5.1": "Kodhaṁ jahe vippajaheyya mānaṁ,",
  "sn1.34:5.2": "Saṁyojanaṁ sabbamatikkameyya;",
  "sn1.34:5.3": "Taṁ nāmarūpasmimasajjamānaṁ,",
  "sn1.34:5.4": "Akiñcanaṁ nānupatanti dukkhā.",
  "sn1.34:6.1": "Pahāsi saṅkhaṁ na vimānamajjhagā,",
  "sn1.34:6.2": "Acchecchi taṇhaṁ idha nāmarūpe;",
  "sn1.34:6.3": "Taṁ chinnaganthaṁ anighaṁ nirāsaṁ,",
  "sn1.34:6.4": "Pariyesamānā nājjhagamuṁ;",
  "sn1.34:6.5": "Devā manussā idha vā huraṁ vā,",
  "sn1.34:6.6": "Saggesu vā sabbanivesanesū”ti.",
  "sn1.34:7.1": "“Tañce hi nāddakkhuṁ tathāvimuttaṁ,",
  "sn1.34:7.2": "(iccāyasmā mogharājā)",
  "sn1.34:7.3": "Devā manussā idha vā huraṁ vā;",
  "sn1.34:7.4": "Naruttamaṁ atthacaraṁ narānaṁ,",
  "sn1.34:7.5": "Ye taṁ namassanti pasaṁsiyā te”ti.",
  "sn1.34:8.1": "“Pasaṁsiyā tepi bhavanti bhikkhū,",
  "sn1.34:8.2": "(mogharājāti bhagavā)",
  "sn1.34:8.3": "Ye taṁ namassanti tathāvimuttaṁ;",
  "sn1.34:8.4": "Aññāya dhammaṁ vicikicchaṁ pahāya,",
  "sn1.34:8.5": "Saṅgātigā tepi bhavanti bhikkhū”ti.",
  "sn1.35:0.1": "Saṁyutta Nikāya 1.35",
  "sn1.35:0.2": "4. Satullapakāyikavagga",
  "sn1.35:0.3": "Ujjhānasaññisutta",
  "sn1.35:1.1": "Ekaṁ samayaṁ bhagavā sāvatthiyaṁ viharati jetavane anāthapiṇḍikassa ārāme.",
  "sn1.35:1.2": "Atha kho sambahulā ujjhānasaññikā devatāyo abhikkantāya rattiyā abhikkantavaṇṇā kevalakappaṁ jetavanaṁ obhāsetvā yena bhagavā tenupasaṅkamiṁsu; upasaṅkamitvā vehāsaṁ aṭṭhaṁsu.",
  "sn1.35:1.3": "Vehāsaṁ ṭhitā kho ekā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.35:2.1": "“Aññathā santamattānaṁ,",
  "sn1.35:2.2": "aññathā yo pavedaye;",
  "sn1.35:2.3": "Nikacca kitavasseva,",
  "sn1.35:2.4": "bhuttaṁ theyyena tassa taṁ.",
  "sn1.35:3.1": "Yañhi kayirā tañhi vade,",
  "sn1.35:3.2": "yaṁ na kayirā na taṁ vade;",
  "sn1.35:3.3": "Akarontaṁ bhāsamānaṁ,",
  "sn1.35:3.4": "parijānanti paṇḍitā”ti.",
  "sn1.35:4.1": "“Na yidaṁ bhāsitamattena,",
  "sn1.35:4.2": "ekantasavanena vā;",
  "sn1.35:4.3": "Anukkamitave sakkā,",
  "sn1.35:4.4": "yāyaṁ paṭipadā daḷhā;",
  "sn1.35:4.5": "Yāya dhīrā pamuccanti,",
  "sn1.35:4.6": "jhāyino mārabandhanā.",
  "sn1.35:5.1": "Na ve dhīrā pakubbanti,",
  "sn1.35:5.2": "viditvā lokapariyāyaṁ;",
  "sn1.35:5.3": "Aññāya nibbutā dhīrā,",
  "sn1.35:5.4": "tiṇṇā loke visattikan”ti.",
  "sn1.35:6.1": "Atha kho tā devatāyo pathaviyaṁ patiṭṭhahitvā bhagavato pādesu sirasā nipatitvā bhagavantaṁ etadavocuṁ:",
  "sn1.35:6.2": "“accayo no, bhante, accagamā yathābālaṁ yathāmūḷhaṁ yathāakusalaṁ, yā mayaṁ bhagavantaṁ āsādetabbaṁ amaññimhā.",
  "sn1.35:6.3": "Tāsaṁ no, bhante, bhagavā accayaṁ accayato paṭiggaṇhātu āyatiṁ saṁvarāyā”ti.",
  "sn1.35:6.4": "Atha kho bhagavā sitaṁ pātvākāsi.",
  "sn1.35:6.5": "Atha kho tā devatāyo bhiyyoso mattāya ujjhāyantiyo vehāsaṁ abbhuggañchuṁ.",
  "sn1.35:6.6": "Ekā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.35:7.1": "“Accayaṁ desayantīnaṁ,",
  "sn1.35:7.2": "yo ce na paṭigaṇhati;",
  "sn1.35:7.3": "Kopantaro dosagaru,",
  "sn1.35:7.4": "sa veraṁ paṭimuñcatī”ti.",
  "sn1.35:8.1": "“Accayo ce na vijjetha,",
  "sn1.35:8.2": "nocidhāpagataṁ siyā;",
  "sn1.35:8.3": "Verāni na ca sammeyyuṁ,",
  "sn1.35:8.4": "kenīdha kusalo siyā”ti.",
  "sn1.35:9.1": "“Kassaccayā na vijjanti,",
  "sn1.35:9.2": "kassa natthi apāgataṁ;",
  "sn1.35:9.3": "Ko na sammohamāpādi,",
  "sn1.35:9.4": "ko ca dhīro sadā sato”ti.",
  "sn1.35:10.1": "“Tathāgatassa buddhassa,",
  "sn1.35:10.2": "sabbabhūtānukampino;",
  "sn1.35:10.3": "Tassaccayā na vijjanti,",
  "sn1.35:10.4": "tassa natthi apāgataṁ;",
  "sn1.35:10.5": "So na sammohamāpādi,",
  "sn1.35:10.6": "sova dhīro sadā satoti.",
  "sn1.35:11.1": "Accayaṁ desayantīnaṁ,",
  "sn1.35:11.2": "yo ce na paṭigaṇhati;",
  "sn1.35:11.3": "Kopantaro dosagaru,",
  "sn1.35:11.4": "sa veraṁ paṭimuñcati;",
  "sn1.35:11.5": "Taṁ veraṁ nābhinandāmi,",
  "sn1.35:11.6": "paṭiggaṇhāmi voccayan”ti.",
  "sn1.36:0.1": "Saṁyutta Nikāya 1.36",
  "sn1.36:0.2": "4. Satullapakāyikavagga",
  "sn1.36:0.3": "Saddhāsutta",
  "sn1.36:1.1": "Ekaṁ samayaṁ bhagavā sāvatthiyaṁ viharati jetavane anāthapiṇḍikassa ārāme.",
  "sn1.36:1.2": "Atha kho sambahulā satullapakāyikā devatāyo abhikkantāya rattiyā abhikkantavaṇṇā kevalakappaṁ jetavanaṁ obhāsetvā yena bhagavā tenupasaṅkamiṁsu; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ aṭṭhaṁsu.",
  "sn1.36:1.3": "Ekamantaṁ ṭhitā kho ekā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.36:2.1": "“Saddhā dutiyā purisassa hoti,",
  "sn1.36:2.2": "No ce assaddhiyaṁ avatiṭṭhati;",
  "sn1.36:2.3": "Yaso ca kittī ca tatvassa hoti,",
  "sn1.36:2.4": "Saggañca so gacchati sarīraṁ vihāyā”ti.",
  "sn1.36:3.1": "Atha kho aparā devatā bhagavato santike imā gāthāyo abhāsi:",
  "sn1.36:4.1": "“Kodhaṁ jahe vippajaheyya mānaṁ,",
  "sn1.36:4.2": "Saṁyojanaṁ sabbamatikkameyya;",
  "sn1.36:4.3": "Taṁ nāmarūpasmimasajjamānaṁ,",
  "sn1.36:4.4": "Akiñcanaṁ nānupatanti saṅgā”ti.",
  "sn1.36:5.1": "“Pamādamanuyuñjanti,",
  "sn1.36:5.2": "bālā dummedhino janā;",
  "sn1.36:5.3": "Appamādañca medhāvī,",
  "sn1.36:5.4": "dhanaṁ seṭṭhaṁva rakkhati.",
  "sn1.36:6.1": "Mā pamādamanuyuñjetha,",
  "sn1.36:6.2": "mā kāmarati santhavaṁ;",
  "sn1.36:6.3": "Appamatto hi jhāyanto,",
  "sn1.36:6.4": "pappoti paramaṁ sukhan”ti.",
  "sn1.37:0.1": "Saṁyutta Nikāya 1.37",
  "sn1.37:0.2": "4. Satullapakāyikavagga",
  "sn1.37:0.3": "Samayasutta",
  "sn1.37:1.1": "Evaṁ me sutaṁ",
  "sn1.37:1.2": "ekaṁ samayaṁ bhagavā sakkesu viharati kapilavatthusmiṁ mahāvane mahatā bhikkhusaṅghena saddhiṁ pañcamattehi bhikkhusatehi sabbeheva arahantehi;",
  "sn1.37:1.3": "dasahi ca lokadhātūhi devatā yebhuyyena sannipatitā honti bhagavantaṁ dassanāya bhikkhusaṅghañca.",
  "sn1.37:1.4": "Atha kho catunnaṁ suddhāvāsakāyikānaṁ devatānaṁ etadahosi:",
  "sn1.37:1.5": "“ayaṁ kho bhagavā sakkesu viharati kapilavatthusmiṁ mahāvane mahatā bhikkhusaṅghena saddhiṁ pañcamattehi bhikkhusatehi sabbeheva arahantehi;",
  "sn1.37:1.6": "dasahi ca lokadhātūhi devatā yebhuyyena sannipatitā honti bhagavantaṁ dassanāya bhikkhusaṅghañca.",
  "sn1.37:1.7": "Yannūna mayampi yena bhagavā tenupasaṅkameyyāma; upasaṅkamitvā bhagavato santike paccekaṁ gāthaṁ bhāseyyāmā”ti.",
  "sn1.37:2.1": "Atha kho tā devatāseyyathāpi nāma balavā puriso samiñjitaṁ vā bāhaṁ pasāreyya pasāritaṁ vā bāhaṁ samiñjeyya; evamevasuddhāvāsesu devesu antarahitā bhagavato purato pāturahesuṁ.",
  "sn1.37:2.2": "Atha kho tā devatā bhagavantaṁ abhivādetvā ekamantaṁ aṭṭhaṁsu.",
  "sn1.37:2.3": "Ekamantaṁ ṭhitā kho ekā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.37:3.1": "“Mahāsamayo pavanasmiṁ,",
  "sn1.37:3.2": "Devakāyā samāgatā;",
  "sn1.37:3.3": "Āgatamha imaṁ dhammasamayaṁ,",
  "sn1.37:3.4": "Dakkhitāye aparājitasaṅghan”ti.",
  "sn1.37:4.1": "Atha kho aparā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.37:5.1": "“Tatra bhikkhavo samādahaṁsu,",
  "sn1.37:5.2": "Cittamattano ujukaṁ akaṁsu;",
  "sn1.37:5.3": "Sārathīva nettāni gahetvā,",
  "sn1.37:5.4": "Indriyāni rakkhanti paṇḍitā”ti.",
  "sn1.37:6.1": "Atha kho aparā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.37:7.1": "“Chetvā khīlaṁ chetvā palighaṁ,",
  "sn1.37:7.2": "Indakhīlaṁ ūhacca manejā;",
  "sn1.37:7.3": "Te caranti suddhā vimalā,",
  "sn1.37:7.4": "Cakkhumatā sudantā susunāgā”ti.",
  "sn1.37:8.1": "Atha kho aparā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.37:9.1": "“Ye keci buddhaṁ saraṇaṁ gatāse,",
  "sn1.37:9.2": "Na te gamissanti apāyabhūmiṁ;",
  "sn1.37:9.3": "Pahāya mānusaṁ dehaṁ,",
  "sn1.37:9.4": "Devakāyaṁ paripūressantī”ti.",
  "sn1.38:0.1": "Saṁyutta Nikāya 1.38",
  "sn1.38:0.2": "4. Satullapakāyikavagga",
  "sn1.38:0.3": "Sakalikasutta",
  "sn1.38:1.1": "Evaṁ me sutaṁ",
  "sn1.38:1.2": "ekaṁ samayaṁ bhagavā rājagahe viharati maddakucchismiṁ migadāye.",
  "sn1.38:1.3": "Tena kho pana samayena bhagavato pādo sakalikāya khato hoti.",
  "sn1.38:1.4": "Bhusā sudaṁ bhagavato vedanā vattanti sārīrikā vedanā dukkhā tibbā kharā kaṭukā asātā amanāpā;",
  "sn1.38:1.5": "tā sudaṁ bhagavā sato sampajāno adhivāseti avihaññamāno.",
  "sn1.38:1.6": "Atha kho bhagavā catugguṇaṁ saṅghāṭiṁ paññāpetvā dakkhiṇena passena sīhaseyyaṁ kappeti pāde pādaṁ accādhāya sato sampajāno.",
  "sn1.38:2.1": "Atha kho sattasatā satullapakāyikā devatāyo abhikkantāya rattiyā abhikkantavaṇṇā kevalakappaṁ maddakucchiṁ obhāsetvā yena bhagavā tenupasaṅkamiṁsu; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ aṭṭhaṁsu.",
  "sn1.38:2.2": "Ekamantaṁ ṭhitā kho ekā devatā bhagavato santike imaṁ udānaṁ udānesi:",
  "sn1.38:2.3": "“nāgo vata, bho, samaṇo gotamo;",
  "sn1.38:2.4": "nāgavatā ca samuppannā sārīrikā vedanā dukkhā tibbā kharā kaṭukā asātā amanāpā sato sampajāno adhivāseti avihaññamāno”ti.",
  "sn1.38:3.1": "Atha kho aparā devatā bhagavato santike imaṁ udānaṁ udānesi:",
  "sn1.38:3.2": "“sīho vata, bho, samaṇo gotamo;",
  "sn1.38:3.3": "sīhavatā ca samuppannā sārīrikā vedanā dukkhā tibbā kharā kaṭukā asātā amanāpā sato sampajāno adhivāseti avihaññamāno”ti.",
  "sn1.38:4.1": "Atha kho aparā devatā bhagavato santike imaṁ udānaṁ udānesi:",
  "sn1.38:4.2": "“ājānīyo vata, bho, samaṇo gotamo;",
  "sn1.38:4.3": "ājānīyavatā ca samuppannā sārīrikā vedanā dukkhā tibbā kharā kaṭukā asātā amanāpā sato sampajāno adhivāseti avihaññamāno”ti.",
  "sn1.38:5.1": "Atha kho aparā devatā bhagavato santike imaṁ udānaṁ udānesi:",
  "sn1.38:5.2": "“nisabho vata, bho, samaṇo gotamo;",
  "sn1.38:5.3": "nisabhavatā ca samuppannā sārīrikā vedanā dukkhā tibbā kharā kaṭukā asātā amanāpā sato sampajāno adhivāseti avihaññamāno”ti.",
  "sn1.38:6.1": "Atha kho aparā devatā bhagavato santike imaṁ udānaṁ udānesi:",
  "sn1.38:6.2": "“dhorayho vata, bho, samaṇo gotamo;",
  "sn1.38:6.3": "dhorayhavatā ca samuppannā sārīrikā vedanā dukkhā tibbā kharā kaṭukā asātā amanāpā sato sampajāno adhivāseti avihaññamāno”ti.",
  "sn1.38:7.1": "Atha kho aparā devatā bhagavato santike imaṁ udānaṁ udānesi:",
  "sn1.38:7.2": "“danto vata, bho, samaṇo gotamo;",
  "sn1.38:7.3": "dantavatā ca samuppannā sārīrikā vedanā dukkhā tibbā kharā kaṭukā asātā amanāpā sato sampajāno adhivāseti avihaññamāno”ti.",
  "sn1.38:8.1": "Atha kho aparā devatā bhagavato santike imaṁ udānaṁ udānesi:",
  "sn1.38:8.2": "“passa samādhiṁ subhāvitaṁ cittañca suvimuttaṁ, na cābhinataṁ na cāpanataṁ na ca sasaṅkhāraniggayhavāritagataṁ.",
  "sn1.38:8.3": "Yo evarūpaṁ purisanāgaṁ purisasīhaṁ purisaājānīyaṁ purisanisabhaṁ purisadhorayhaṁ purisadantaṁ atikkamitabbaṁ maññeyya kimaññatra adassanā”ti.",
  "sn1.38:9.1": "“Pañcavedā sataṁ samaṁ,",
  "sn1.38:9.2": "Tapassī brāhmaṇā caraṁ;",
  "sn1.38:9.3": "Cittañca nesaṁ na sammā vimuttaṁ,",
  "sn1.38:9.4": "Hīnattharūpā na pāraṅgamā te.",
  "sn1.38:10.1": "Taṇhādhipannā vatasīlabaddhā,",
  "sn1.38:10.2": "Lūkhaṁ tapaṁ vassasataṁ carantā;",
  "sn1.38:10.3": "Cittañca nesaṁ na sammā vimuttaṁ,",
  "sn1.38:10.4": "Hīnattharūpā na pāraṅgamā te.",
  "sn1.38:11.1": "Na mānakāmassa damo idhatthi,",
  "sn1.38:11.2": "Na monamatthi asamāhitassa;",
  "sn1.38:11.3": "Eko araññe viharaṁ pamatto,",
  "sn1.38:11.4": "Na maccudheyyassa tareyya pāran”ti.",
  "sn1.38:12.1": "“Mānaṁ pahāya susamāhitatto,",
  "sn1.38:12.2": "Sucetaso sabbadhi vippamutto;",
  "sn1.38:12.3": "Eko araññe viharamappamatto,",
  "sn1.38:12.4": "Sa maccudheyyassa tareyya pāran”ti.",
  "sn1.39:0.1": "Saṁyutta Nikāya 1.39",
  "sn1.39:0.2": "4. Satullapakāyikavagga",
  "sn1.39:0.3": "Paṭhamapajjunnadhītusutta",
  "sn1.39:1.1": "Evaṁ me sutaṁ",
  "sn1.39:1.2": "ekaṁ samayaṁ bhagavā vesāliyaṁ viharati mahāvane kūṭāgārasālāyaṁ.",
  "sn1.39:1.3": "Atha kho kokanadā pajjunnassa dhītā abhikkantāya rattiyā abhikkantavaṇṇā kevalakappaṁ mahāvanaṁ obhāsetvā yena bhagavā tenupasaṅkami; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ aṭṭhāsi.",
  "sn1.39:1.4": "Ekamantaṁ ṭhitā kho sā devatā kokanadā pajjunnassa dhītā bhagavato santike imā gāthāyo abhāsi:",
  "sn1.39:2.1": "“Vesāliyaṁ vane viharantaṁ,",
  "sn1.39:2.2": "Aggaṁ sattassa sambuddhaṁ;",
  "sn1.39:2.3": "Kokanadāhamasmi abhivande,",
  "sn1.39:2.4": "Kokanadā pajjunnassa dhītā.",
  "sn1.39:3.1": "Sutameva pure āsi,",
  "sn1.39:3.2": "Dhammo cakkhumatānubuddho;",
  "sn1.39:3.3": "Sāhaṁ dāni sakkhi jānāmi,",
  "sn1.39:3.4": "Munino desayato sugatassa.",
  "sn1.39:4.1": "Ye keci ariyaṁ dhammaṁ,",
  "sn1.39:4.2": "Vigarahantā caranti dummedhā;",
  "sn1.39:4.3": "Upenti roruvaṁ ghoraṁ,",
  "sn1.39:4.4": "Cirarattaṁ dukkhaṁ anubhavanti.",
  "sn1.39:5.1": "Ye ca kho ariye dhamme,",
  "sn1.39:5.2": "Khantiyā upasamena upetā;",
  "sn1.39:5.3": "Pahāya mānusaṁ dehaṁ,",
  "sn1.39:5.4": "Devakāyaṁ paripūressantī”ti.",
  "sn1.40:0.1": "Saṁyutta Nikāya 1.40",
  "sn1.40:0.2": "4. Satullapakāyikavagga",
  "sn1.40:0.3": "Dutiyapajjunnadhītusuttaṁ",
  "sn1.40:1.1": "Evaṁ me sutaṁ",
  "sn1.40:1.2": "ekaṁ samayaṁ bhagavā vesāliyaṁ viharati mahāvane kūṭāgārasālāyaṁ.",
  "sn1.40:1.3": "Atha kho cūḷakokanadā pajjunnassa dhītā abhikkantāya rattiyā abhikkantavaṇṇā kevalakappaṁ mahāvanaṁ obhāsetvā yena bhagavā tenupasaṅkami; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ aṭṭhāsi.",
  "sn1.40:1.4": "Ekamantaṁ ṭhitā kho sā devatā cūḷakokanadā pajjunnassa dhītā bhagavato santike imā gāthāyo abhāsi:",
  "sn1.40:2.1": "“Idhāgamā vijjupabhāsavaṇṇā,",
  "sn1.40:2.2": "Kokanadā pajjunnassa dhītā;",
  "sn1.40:2.3": "Buddhañca dhammañca namassamānā,",
  "sn1.40:2.4": "Gāthācimā atthavatī abhāsi.",
  "sn1.40:3.1": "Bahunāpi kho taṁ vibhajeyyaṁ,",
  "sn1.40:3.2": "Pariyāyena tādiso dhammo;",
  "sn1.40:3.3": "Saṅkhittamatthaṁ lapayissāmi,",
  "sn1.40:3.4": "Yāvatā me manasā pariyattaṁ.",
  "sn1.40:4.1": "Pāpaṁ na kayirā vacasā manasā,",
  "sn1.40:4.2": "Kāyena vā kiñcana sabbaloke;",
  "sn1.40:4.3": "Kāme pahāya satimā sampajāno,",
  "sn1.40:4.4": "Dukkhaṁ na sevetha anatthasaṁhitan”ti.",
  "sn1.40:4.5": "Satullapakāyikavaggo catuttho.",
  "sn1.40:5.0": "Tassuddānaṁ",
  "sn1.40:5.1": "Sabbhimaccharinā sādhu,",
  "sn1.40:5.2": "na santujjhānasaññino;",
  "sn1.40:5.3": "Saddhā samayo sakalikaṁ,",
  "sn1.40:5.4": "ubho pajjunnadhītaroti."
}
window.BILARA["sn1_v4"]["pli"]["sn1_v4:source"] =
  "SOURCE: https://suttacentral.net/ ";