window.BILARA = window.BILARA || {};
window.BILARA["sn1_v2"] = window.BILARA["sn1_v2"] || {};
window.BILARA["sn1_v2"]["pli"] = {
  "sn1.11:0.1": "Saṁyutta Nikāya 1.11",
  "sn1.11:0.2": "2. Nandanavagga",
  "sn1.11:0.3": "Nandanasutta",
  "sn1.11:1.1": "Evaṁ me sutaṁ",
  "sn1.11:1.2": "ekaṁ samayaṁ bhagavā sāvatthiyaṁ viharati jetavane anāthapiṇḍikassa ārāme.",
  "sn1.11:1.3": "Tatra kho bhagavā bhikkhū āmantesi:",
  "sn1.11:1.4": "“bhikkhavo”ti.",
  "sn1.11:1.5": "“Bhadante”ti te bhikkhū bhagavato paccassosuṁ.",
  "sn1.11:1.6": "Bhagavā etadavoca:",
  "sn1.11:2.1": "“Bhūtapubbaṁ, bhikkhave, aññatarā tāvatiṁsakāyikā devatā nandane vane accharāsaṅghaparivutā dibbehi pañcahi kāmaguṇehi samappitā samaṅgībhūtā paricārayamānā tāyaṁ velāyaṁ imaṁ gāthaṁ abhāsi:",
  "sn1.11:3.1": "‘Na te sukhaṁ pajānanti,",
  "sn1.11:3.2": "ye na passanti nandanaṁ;",
  "sn1.11:3.3": "Āvāsaṁ naradevānaṁ,",
  "sn1.11:3.4": "tidasānaṁ yasassinan’ti.",
  "sn1.11:4.1": "Evaṁ vutte, bhikkhave, aññatarā devatā taṁ devataṁ gāthāya paccabhāsi:",
  "sn1.11:5.1": "‘Na tvaṁ bāle pajānāsi,",
  "sn1.11:5.2": "yathā arahataṁ vaco;",
  "sn1.11:5.3": "Aniccā sabbasaṅkhārā,",
  "sn1.11:5.4": "uppādavayadhammino;",
  "sn1.11:5.5": "Uppajjitvā nirujjhanti,",
  "sn1.11:5.6": "tesaṁ vūpasamo sukho’”ti.",
  "sn1.12:0.1": "Saṁyutta Nikāya 1.12",
  "sn1.12:0.2": "2. Nandanavagga",
  "sn1.12:0.3": "Nandatisutta",
  "sn1.12:1.1": "Sāvatthinidānaṁ.",
  "sn1.12:1.2": "Ekamantaṁ ṭhitā kho sā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.12:2.1": "“Nandati puttehi puttimā,",
  "sn1.12:2.2": "Gomā gohi tatheva nandati;",
  "sn1.12:2.3": "Upadhīhi narassa nandanā,",
  "sn1.12:2.4": "Na hi so nandati yo nirūpadhī”ti.",
  "sn1.12:3.1": "“Socati puttehi puttimā,",
  "sn1.12:3.2": "Gomā gohi tatheva socati;",
  "sn1.12:3.3": "Upadhīhi narassa socanā,",
  "sn1.12:3.4": "Na hi so socati yo nirūpadhī”ti.",
  "sn1.13:0.1": "Saṁyutta Nikāya 1.13",
  "sn1.13:0.2": "2. Nandanavagga",
  "sn1.13:0.3": "Natthiputtasamasutta",
  "sn1.13:1.1": "Sāvatthinidānaṁ.",
  "sn1.13:1.2": "Ekamantaṁ ṭhitā kho sā devatā bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn1.13:2.1": "“Natthi puttasamaṁ pemaṁ,",
  "sn1.13:2.2": "natthi gosamitaṁ dhanaṁ;",
  "sn1.13:2.3": "Natthi sūriyasamā ābhā,",
  "sn1.13:2.4": "samuddaparamā sarā”ti.",
  "sn1.13:3.1": "“Natthi attasamaṁ pemaṁ,",
  "sn1.13:3.2": "natthi dhaññasamaṁ dhanaṁ;",
  "sn1.13:3.3": "Natthi paññāsamā ābhā,",
  "sn1.13:3.4": "vuṭṭhi ve paramā sarā”ti.",
  "sn1.14:0.1": "Saṁyutta Nikāya 1.14",
  "sn1.14:0.2": "2. Nandanavagga",
  "sn1.14:0.3": "Khattiyasutta",
  "sn1.14:1.1": "“Khattiyo dvipadaṁ seṭṭho,",
  "sn1.14:1.2": "balībaddo catuppadaṁ;",
  "sn1.14:1.3": "Komārī seṭṭhā bhariyānaṁ,",
  "sn1.14:1.4": "yo ca puttāna pubbajo”ti.",
  "sn1.14:2.1": "“Sambuddho dvipadaṁ seṭṭho,",
  "sn1.14:2.2": "ājānīyo catuppadaṁ;",
  "sn1.14:2.3": "Sussūsā seṭṭhā bhariyānaṁ,",
  "sn1.14:2.4": "yo ca puttānamassavo”ti.",
  "sn1.15:0.1": "Saṁyutta Nikāya 1.15",
  "sn1.15:0.2": "2. Nandanavagga",
  "sn1.15:0.3": "Saṇamānasutta",
  "sn1.15:1.1": "“Ṭhite majjhanhike kāle,",
  "sn1.15:1.2": "sannisīvesu pakkhisu;",
  "sn1.15:1.3": "Saṇateva brahāraññaṁ,",
  "sn1.15:1.4": "taṁ bhayaṁ paṭibhāti man”ti.",
  "sn1.15:2.1": "“Ṭhite majjhanhike kāle,",
  "sn1.15:2.2": "sannisīvesu pakkhisu;",
  "sn1.15:2.3": "Saṇateva brahāraññaṁ,",
  "sn1.15:2.4": "sā rati paṭibhāti man”ti.",
  "sn1.16:0.1": "Saṁyutta Nikāya 1.16",
  "sn1.16:0.2": "2. Nandanavagga",
  "sn1.16:0.3": "Niddātandīsutta",
  "sn1.16:1.1": "“Niddā tandī vijambhitā,",
  "sn1.16:1.2": "Aratī bhattasammado;",
  "sn1.16:1.3": "Etena nappakāsati,",
  "sn1.16:1.4": "Ariyamaggo idha pāṇinan”ti.",
  "sn1.16:2.1": "“Niddaṁ tandiṁ vijambhitaṁ,",
  "sn1.16:2.2": "Aratiṁ bhattasammadaṁ;",
  "sn1.16:2.3": "Vīriyena naṁ paṇāmetvā,",
  "sn1.16:2.4": "Ariyamaggo visujjhatī”ti.",
  "sn1.17:0.1": "Saṁyutta Nikāya 1.17",
  "sn1.17:0.2": "2. Nandanavagga",
  "sn1.17:0.3": "Dukkarasutta",
  "sn1.17:1.1": "“Dukkaraṁ duttitikkhañca,",
  "sn1.17:1.2": "abyattena ca sāmaññaṁ;",
  "sn1.17:1.3": "Bahūhi tattha sambādhā,",
  "sn1.17:1.4": "yattha bālo visīdatī”ti.",
  "sn1.17:2.1": "“Katihaṁ careyya sāmaññaṁ,",
  "sn1.17:2.2": "cittañce na nivāraye;",
  "sn1.17:2.3": "Pade pade visīdeyya,",
  "sn1.17:2.4": "saṅkappānaṁ vasānugoti.",
  "sn1.17:3.1": "Kummova aṅgāni sake kapāle,",
  "sn1.17:3.2": "Samodahaṁ bhikkhu manovitakke;",
  "sn1.17:3.3": "Anissito aññamaheṭhayāno,",
  "sn1.17:3.4": "Parinibbuto nūpavadeyya kañcī”ti.",
  "sn1.18:0.1": "Saṁyutta Nikāya 1.18",
  "sn1.18:0.2": "2. Nandanavagga",
  "sn1.18:0.3": "Hirīsutta",
  "sn1.18:1.1": "“Hirīnisedho puriso,",
  "sn1.18:1.2": "koci lokasmiṁ vijjati;",
  "sn1.18:1.3": "Yo nindaṁ apabodhati,",
  "sn1.18:1.4": "asso bhadro kasāmivā”ti.",
  "sn1.18:2.1": "“Hirīnisedhā tanuyā,",
  "sn1.18:2.2": "ye caranti sadā satā;",
  "sn1.18:2.3": "Antaṁ dukkhassa pappuyya,",
  "sn1.18:2.4": "caranti visame saman”ti.",
  "sn1.19:0.1": "Saṁyutta Nikāya 1.19",
  "sn1.19:0.2": "2. Nandanavagga",
  "sn1.19:0.3": "Kuṭikāsutta",
  "sn1.19:1.1": "“Kacci te kuṭikā natthi,",
  "sn1.19:1.2": "kacci natthi kulāvakā;",
  "sn1.19:1.3": "Kacci santānakā natthi,",
  "sn1.19:1.4": "kacci muttosi bandhanā”ti.",
  "sn1.19:2.1": "“Taggha me kuṭikā natthi,",
  "sn1.19:2.2": "taggha natthi kulāvakā;",
  "sn1.19:2.3": "Taggha santānakā natthi,",
  "sn1.19:2.4": "taggha muttomhi bandhanā”ti.",
  "sn1.19:3.1": "“Kintāhaṁ kuṭikaṁ brūmi,",
  "sn1.19:3.2": "kiṁ te brūmi kulāvakaṁ;",
  "sn1.19:3.3": "Kiṁ te santānakaṁ brūmi,",
  "sn1.19:3.4": "kintāhaṁ brūmi bandhanan”ti.",
  "sn1.19:4.1": "“Mātaraṁ kuṭikaṁ brūsi,",
  "sn1.19:4.2": "bhariyaṁ brūsi kulāvakaṁ;",
  "sn1.19:4.3": "Putte santānake brūsi,",
  "sn1.19:4.4": "taṇhaṁ me brūsi bandhanan”ti.",
  "sn1.19:5.1": "“Sāhu te kuṭikā natthi,",
  "sn1.19:5.2": "sāhu natthi kulāvakā;",
  "sn1.19:5.3": "Sāhu santānakā natthi,",
  "sn1.19:5.4": "sāhu muttosi bandhanā”ti.",
  "sn1.20:0.1": "Saṁyutta Nikāya 1.20",
  "sn1.20:0.2": "2. Nandanavagga",
  "sn1.20:0.3": "Samiddhisutta",
  "sn1.20:1.1": "Evaṁ me sutaṁ",
  "sn1.20:1.2": "ekaṁ samayaṁ bhagavā rājagahe viharati tapodārāme.",
  "sn1.20:1.3": "Atha kho āyasmā samiddhi rattiyā paccūsasamayaṁ paccuṭṭhāya yena tapodā tenupasaṅkami gattāni parisiñcituṁ.",
  "sn1.20:1.4": "Tapode gattāni parisiñcitvā paccuttaritvā ekacīvaro aṭṭhāsi gattāni pubbāpayamāno.",
  "sn1.20:1.5": "Atha kho aññatarā devatā abhikkantāya rattiyā abhikkantavaṇṇā kevalakappaṁ tapodaṁ obhāsetvā yena āyasmā samiddhi tenupasaṅkami; upasaṅkamitvā vehāsaṁ ṭhitā āyasmantaṁ samiddhiṁ gāthāya ajjhabhāsi:",
  "sn1.20:2.1": "“Abhutvā bhikkhasi bhikkhu,",
  "sn1.20:2.2": "na hi bhutvāna bhikkhasi;",
  "sn1.20:2.3": "Bhutvāna bhikkhu bhikkhassu,",
  "sn1.20:2.4": "mā taṁ kālo upaccagā”ti.",
  "sn1.20:3.1": "“Kālaṁ vohaṁ na jānāmi,",
  "sn1.20:3.2": "channo kālo na dissati;",
  "sn1.20:3.3": "Tasmā abhutvā bhikkhāmi,",
  "sn1.20:3.4": "mā maṁ kālo upaccagā”ti.",
  "sn1.20:4.1": "Atha kho sā devatā pathaviyaṁ patiṭṭhahitvā āyasmantaṁ samiddhiṁ etadavoca:",
  "sn1.20:4.2": "“daharo tvaṁ, bhikkhu, pabbajito susu kāḷakeso, bhadrena yobbanena samannāgato, paṭhamena vayasā, anikkīḷitāvī kāmesu.",
  "sn1.20:4.3": "Bhuñja, bhikkhu, mānusake kāme;",
  "sn1.20:4.4": "mā sandiṭṭhikaṁ hitvā kālikaṁ anudhāvī”ti.",
  "sn1.20:5.1": "“Na khvāhaṁ, āvuso, sandiṭṭhikaṁ hitvā kālikaṁ anudhāvāmi.",
  "sn1.20:5.2": "Kālikañca khvāhaṁ, āvuso, hitvā sandiṭṭhikaṁ anudhāvāmi.",
  "sn1.20:5.3": "Kālikā hi, āvuso, kāmā vuttā bhagavatā bahudukkhā bahupāyāsā; ādīnavo ettha bhiyyo.",
  "sn1.20:5.4": "Sandiṭṭhiko ayaṁ dhammo akāliko ehipassiko opaneyyiko paccattaṁ veditabbo viññūhī”ti.",
  "sn1.20:6.1": "“Kathañca, bhikkhu, kālikā kāmā vuttā bhagavatā bahudukkhā bahupāyāsā, ādīnavo ettha bhiyyo?",
  "sn1.20:6.2": "Kathaṁ sandiṭṭhiko ayaṁ dhammo akāliko ehipassiko opaneyyiko paccattaṁ veditabbo viññūhī”ti?",
  "sn1.20:7.1": "“Ahaṁ kho, āvuso, navo acirapabbajito adhunāgato imaṁ dhammavinayaṁ.",
  "sn1.20:7.2": "Na tāhaṁ sakkomi vitthārena ācikkhituṁ.",
  "sn1.20:7.3": "Ayaṁ so bhagavā arahaṁ sammāsambuddho rājagahe viharati tapodārāme.",
  "sn1.20:7.4": "Taṁ bhagavantaṁ upasaṅkamitvā etamatthaṁ puccha.",
  "sn1.20:7.5": "Yathā te bhagavā byākaroti tathā naṁ dhāreyyāsī”ti.",
  "sn1.20:8.1": "“Na kho, bhikkhu, sukaro so bhagavā amhehi upasaṅkamituṁ, aññāhi mahesakkhāhi devatāhi parivuto.",
  "sn1.20:8.2": "Sace kho tvaṁ, bhikkhu, taṁ bhagavantaṁ upasaṅkamitvā etamatthaṁ puccheyyāsi, mayampi āgaccheyyāma dhammassavanāyā”ti.",
  "sn1.20:8.3": "“Evamāvuso”ti kho āyasmā samiddhi tassā devatāya paṭissutvā yena bhagavā tenupasaṅkami; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ nisīdi. Ekamantaṁ nisinno kho āyasmā samiddhi bhagavantaṁ etadavoca:",
  "sn1.20:9.1": "“Idhāhaṁ, bhante, rattiyā paccūsasamayaṁ paccuṭṭhāya yena tapodā tenupasaṅkamiṁ gattāni parisiñcituṁ.",
  "sn1.20:9.2": "Tapode gattāni parisiñcitvā paccuttaritvā ekacīvaro aṭṭhāsiṁ gattāni pubbāpayamāno.",
  "sn1.20:9.3": "Atha kho, bhante, aññatarā devatā abhikkantāya rattiyā abhikkantavaṇṇā kevalakappaṁ tapodaṁ obhāsetvā yenāhaṁ tenupasaṅkami; upasaṅkamitvā vehāsaṁ ṭhitā imāya gāthāya ajjhabhāsi:",
  "sn1.20:10.1": "‘Abhutvā bhikkhasi bhikkhu,",
  "sn1.20:10.2": "na hi bhutvāna bhikkhasi;",
  "sn1.20:10.3": "Bhutvāna bhikkhu bhikkhassu,",
  "sn1.20:10.4": "mā taṁ kālo upaccagā’ti.",
  "sn1.20:11.1": "Evaṁ vutte, ahaṁ, bhante, taṁ devataṁ gāthāya paccabhāsiṁ:",
  "sn1.20:12.1": "‘Kālaṁ vohaṁ na jānāmi,",
  "sn1.20:12.2": "channo kālo na dissati;",
  "sn1.20:12.3": "Tasmā abhutvā bhikkhāmi,",
  "sn1.20:12.4": "mā maṁ kālo upaccagā’ti.",
  "sn1.20:13.1": "Atha kho, bhante, sā devatā pathaviyaṁ patiṭṭhahitvā maṁ etadavoca:",
  "sn1.20:13.2": "‘daharo tvaṁ, bhikkhu, pabbajito susu kāḷakeso, bhadrena yobbanena samannāgato, paṭhamena vayasā, anikkīḷitāvī kāmesu.",
  "sn1.20:13.3": "Bhuñja, bhikkhu, mānusake kāme;",
  "sn1.20:13.4": "mā sandiṭṭhikaṁ hitvā kālikaṁ anudhāvī’ti.",
  "sn1.20:14.1": "Evaṁ vuttāhaṁ, bhante, taṁ devataṁ etadavocaṁ:",
  "sn1.20:14.2": "‘na khvāhaṁ, āvuso, sandiṭṭhikaṁ hitvā kālikaṁ anudhāvāmi;",
  "sn1.20:14.3": "kālikañca khvāhaṁ, āvuso, hitvā sandiṭṭhikaṁ anudhāvāmi.",
  "sn1.20:14.4": "Kālikā hi, āvuso, kāmā vuttā bhagavatā bahudukkhā bahupāyāsā; ādīnavo ettha bhiyyo.",
  "sn1.20:14.5": "Sandiṭṭhiko ayaṁ dhammo akāliko ehipassiko opaneyyiko paccattaṁ veditabbo viññūhī’ti.",
  "sn1.20:15.1": "Evaṁ vutte, bhante, sā devatā maṁ etadavoca:",
  "sn1.20:15.2": "‘kathañca, bhikkhu, kālikā kāmā vuttā bhagavatā bahudukkhā bahupāyāsā; ādīnavo ettha bhiyyo?",
  "sn1.20:15.3": "Kathaṁ sandiṭṭhiko ayaṁ dhammo akāliko ehipassiko opaneyyiko paccattaṁ veditabbo viññūhī’ti?",
  "sn1.20:16.1": "Evaṁ vuttāhaṁ, bhante, taṁ devataṁ etadavocaṁ:",
  "sn1.20:16.2": "‘ahaṁ kho, āvuso, navo acirapabbajito adhunāgato imaṁ dhammavinayaṁ, na tāhaṁ sakkomi vitthārena ācikkhituṁ.",
  "sn1.20:16.3": "Ayaṁ so bhagavā arahaṁ sammāsambuddho rājagahe viharati tapodārāme.",
  "sn1.20:16.4": "Taṁ bhagavantaṁ upasaṅkamitvā etamatthaṁ puccha.",
  "sn1.20:16.5": "Yathā te bhagavā byākaroti tathā naṁ dhāreyyāsī’ti.",
  "sn1.20:17.1": "Evaṁ vutte, bhante, sā devatā maṁ etadavoca:",
  "sn1.20:17.2": "‘na kho, bhikkhu, sukaro so bhagavā amhehi upasaṅkamituṁ, aññāhi mahesakkhāhi devatāhi parivuto.",
  "sn1.20:17.3": "Sace kho tvaṁ, bhikkhu, taṁ bhagavantaṁ upasaṅkamitvā etamatthaṁ puccheyyāsi, mayampi āgaccheyyāma dhammassavanāyā’ti.",
  "sn1.20:17.4": "Sace, bhante, tassā devatāya saccaṁ vacanaṁ, idheva sā devatā avidūre”ti.",
  "sn1.20:18.1": "Evaṁ vutte, sā devatā āyasmantaṁ samiddhiṁ etadavoca:",
  "sn1.20:18.2": "“puccha, bhikkhu, puccha, bhikkhu, yamahaṁ anuppattā”ti.",
  "sn1.20:19.1": "Atha kho bhagavā taṁ devataṁ gāthāhi ajjhabhāsi:",
  "sn1.20:20.1": "“Akkheyyasaññino sattā,",
  "sn1.20:20.2": "akkheyyasmiṁ patiṭṭhitā;",
  "sn1.20:20.3": "Akkheyyaṁ apariññāya,",
  "sn1.20:20.4": "yogamāyanti maccuno.",
  "sn1.20:21.1": "Akkheyyañca pariññāya,",
  "sn1.20:21.2": "Akkhātāraṁ na maññati;",
  "sn1.20:21.3": "Tañhi tassa na hotīti,",
  "sn1.20:21.4": "Yena naṁ vajjā na tassa atthi;",
  "sn1.20:21.5": "Sace vijānāsi vadehi yakkhā”ti.",
  "sn1.20:22.1": "“Na khvāhaṁ, bhante, imassa bhagavatā saṅkhittena bhāsitassa vitthārena atthaṁ ājānāmi.",
  "sn1.20:22.2": "Sādhu me, bhante, bhagavā tathā bhāsatu yathāhaṁ imassa bhagavatā saṅkhittena bhāsitassa vitthārena atthaṁ jāneyyan”ti.",
  "sn1.20:23.1": "“Samo visesī uda vā nihīno,",
  "sn1.20:23.2": "Yo maññatī so vivadetha tena;",
  "sn1.20:23.3": "Tīsu vidhāsu avikampamāno,",
  "sn1.20:23.4": "Samo visesīti na tassa hoti;",
  "sn1.20:23.5": "Sace vijānāsi vadehi yakkhā”ti.",
  "sn1.20:24.1": "“Imassapi khvāhaṁ, bhante, bhagavatā saṅkhittena bhāsitassa na vitthārena atthaṁ ājānāmi.",
  "sn1.20:24.2": "Sādhu me, bhante, bhagavā tathā bhāsatu yathāhaṁ imassa bhagavatā saṅkhittena bhāsitassa vitthārena atthaṁ jāneyyan”ti.",
  "sn1.20:25.1": "“Pahāsi saṅkhaṁ na vimānamajjhagā,",
  "sn1.20:25.2": "Acchecchi taṇhaṁ idha nāmarūpe;",
  "sn1.20:25.3": "Taṁ chinnaganthaṁ anighaṁ nirāsaṁ,",
  "sn1.20:25.4": "Pariyesamānā nājjhagamuṁ;",
  "sn1.20:25.5": "Devā manussā idha vā huraṁ vā,",
  "sn1.20:25.6": "Saggesu vā sabbanivesanesu.",
  "sn1.20:26.1": "Sace vijānāsi vadehi yakkhā”ti.",
  "sn1.20:27.1": "“Imassa khvāhaṁ, bhante, bhagavatā saṅkhittena bhāsitassa evaṁ vitthārena atthaṁ ājānāmi",
  "sn1.20:28.1": "Pāpaṁ na kayirā vacasā manasā,",
  "sn1.20:28.2": "Kāyena vā kiñcana sabbaloke;",
  "sn1.20:28.3": "Kāme pahāya satimā sampajāno,",
  "sn1.20:28.4": "Dukkhaṁ na sevetha anatthasaṁhitan”ti.",
  "sn1.20:28.5": "Nandanavaggo dutiyo.",
  "sn1.20:29.0": "Tassuddānaṁ",
  "sn1.20:29.1": "Nandanā nandati ceva,",
  "sn1.20:29.2": "Natthiputtasamena ca;",
  "sn1.20:29.3": "Khattiyo saṇamāno ca,",
  "sn1.20:29.4": "Niddātandī ca dukkaraṁ;",
  "sn1.20:29.5": "Hirī kuṭikā navamo,",
  "sn1.20:29.6": "Dasamo vutto samiddhināti."
}
window.BILARA["sn1_v2"]["pli"]["sn1_v2:source"] =
  "SOURCE: https://suttacentral.net/ ";