window.BILARA = window.BILARA || {};
window.BILARA["sn2_v1"] = window.BILARA["sn2_v1"] || {};
window.BILARA["sn2_v1"]["pli"] = {
  "sn2.1:0.1": "Saṁyutta Nikāya 2.1",
  "sn2.1:0.2": "1. Paṭhamavagga",
  "sn2.1:0.3": "Paṭhamakassapasutta",
  "sn2.1:1.1": "Evaṁ me sutaṁ",
  "sn2.1:1.2": "ekaṁ samayaṁ bhagavā sāvatthiyaṁ viharati jetavane anāthapiṇḍikassa ārāme.",
  "sn2.1:1.3": "Atha kho kassapo devaputto abhikkantāya rattiyā abhikkantavaṇṇo kevalakappaṁ jetavanaṁ obhāsetvā yena bhagavā tenupasaṅkami; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ aṭṭhāsi. Ekamantaṁ ṭhito kho kassapo devaputto bhagavantaṁ etadavoca:",
  "sn2.1:1.4": "“bhikkhuṁ bhagavā pakāsesi, no ca bhikkhuno anusāsan”ti.",
  "sn2.1:1.5": "“Tena hi, kassapa, taññevettha paṭibhātū”ti.",
  "sn2.1:2.1": "“Subhāsitassa sikkhetha,",
  "sn2.1:2.2": "samaṇūpāsanassa ca;",
  "sn2.1:2.3": "Ekāsanassa ca raho,",
  "sn2.1:2.4": "cittavūpasamassa cā”ti.",
  "sn2.1:3.1": "Idamavoca kassapo devaputto;",
  "sn2.1:3.2": "samanuñño satthā ahosi.",
  "sn2.1:3.3": "Atha kho kassapo devaputto “samanuñño me satthā”ti bhagavantaṁ abhivādetvā padakkhiṇaṁ katvā tatthevantaradhāyīti.",
  "sn2.2:0.1": "Saṁyutta Nikāya 2.2",
  "sn2.2:0.2": "1. Paṭhamavagga",
  "sn2.2:0.3": "Dutiyakassapasutta",
  "sn2.2:1.1": "Sāvatthinidānaṁ.",
  "sn2.2:1.2": "Ekamantaṁ ṭhito kho kassapo devaputto bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn2.2:2.1": "“Bhikkhu siyā jhāyī vimuttacitto,",
  "sn2.2:2.2": "Ākaṅkhe ce hadayassānupattiṁ;",
  "sn2.2:2.3": "Lokassa ñatvā udayabbayañca,",
  "sn2.2:2.4": "Sucetaso anissito tadānisaṁso”ti.",
  "sn2.3:0.1": "Saṁyutta Nikāya 2.3",
  "sn2.3:0.2": "1. Paṭhamavagga",
  "sn2.3:0.3": "Māghasutta",
  "sn2.3:1.1": "Sāvatthinidānaṁ.",
  "sn2.3:1.2": "Atha kho māgho devaputto abhikkantāya rattiyā abhikkantavaṇṇo kevalakappaṁ jetavanaṁ obhāsetvā yena bhagavā tenupasaṅkami; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ aṭṭhāsi.",
  "sn2.3:1.3": "Ekamantaṁ ṭhito kho māgho devaputto bhagavantaṁ gāthāya ajjhabhāsi:",
  "sn2.3:2.1": "“Kiṁsu chetvā sukhaṁ seti,",
  "sn2.3:2.2": "kiṁsu chetvā na socati;",
  "sn2.3:2.3": "Kissassu ekadhammassa,",
  "sn2.3:2.4": "vadhaṁ rocesi gotamā”ti.",
  "sn2.3:3.1": "“Kodhaṁ chetvā sukhaṁ seti,",
  "sn2.3:3.2": "kodhaṁ chetvā na socati;",
  "sn2.3:3.3": "Kodhassa visamūlassa,",
  "sn2.3:3.4": "madhuraggassa vatrabhū;",
  "sn2.3:3.5": "Vadhaṁ ariyā pasaṁsanti,",
  "sn2.3:3.6": "tañhi chetvā na socatī”ti.",
  "sn2.4:0.1": "Saṁyutta Nikāya 2.4",
  "sn2.4:0.2": "1. Paṭhamavagga",
  "sn2.4:0.3": "Māgadhasutta",
  "sn2.4:1.1": "Sāvatthinidānaṁ.",
  "sn2.4:1.2": "Ekamantaṁ ṭhito kho māgadho devaputto bhagavantaṁ gāthāya ajjhabhāsi:",
  "sn2.4:2.1": "“Kati lokasmiṁ pajjotā,",
  "sn2.4:2.2": "yehi loko pakāsati;",
  "sn2.4:2.3": "Bhavantaṁ puṭṭhumāgamma,",
  "sn2.4:2.4": "kathaṁ jānemu taṁ mayan”ti.",
  "sn2.4:3.1": "“Cattāro loke pajjotā,",
  "sn2.4:3.2": "pañcamettha na vijjati;",
  "sn2.4:3.3": "Divā tapati ādicco,",
  "sn2.4:3.4": "rattimābhāti candimā.",
  "sn2.4:4.1": "Atha aggi divārattiṁ,",
  "sn2.4:4.2": "tattha tattha pakāsati;",
  "sn2.4:4.3": "Sambuddho tapataṁ seṭṭho,",
  "sn2.4:4.4": "esā ābhā anuttarā”ti.",
  "sn2.5:0.1": "Saṁyutta Nikāya 2.5",
  "sn2.5:0.2": "1. Paṭhamavagga",
  "sn2.5:0.3": "Dāmalisutta",
  "sn2.5:1.1": "Sāvatthinidānaṁ.",
  "sn2.5:1.2": "Atha kho dāmali devaputto abhikkantāya rattiyā abhikkantavaṇṇo kevalakappaṁ jetavanaṁ obhāsetvā yena bhagavā tenupasaṅkami; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ aṭṭhāsi.",
  "sn2.5:1.3": "Ekamantaṁ ṭhito kho dāmali devaputto bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn2.5:2.1": "“Karaṇīyametaṁ brāhmaṇena,",
  "sn2.5:2.2": "Padhānaṁ akilāsunā;",
  "sn2.5:2.3": "Kāmānaṁ vippahānena,",
  "sn2.5:2.4": "Na tenāsīsate bhavan”ti.",
  "sn2.5:3.1": "“Natthi kiccaṁ brāhmaṇassa,",
  "sn2.5:3.2": "(dāmalīti bhagavā)",
  "sn2.5:3.3": "Katakicco hi brāhmaṇo;",
  "sn2.5:3.4": "Yāva na gādhaṁ labhati nadīsu,",
  "sn2.5:3.5": "Āyūhati sabbagattebhi jantu;",
  "sn2.5:3.6": "Gādhañca laddhāna thale ṭhito yo,",
  "sn2.5:3.7": "Nāyūhatī pāragato hi sova.",
  "sn2.5:4.1": "Esūpamā dāmali brāhmaṇassa,",
  "sn2.5:4.2": "Khīṇāsavassa nipakassa jhāyino;",
  "sn2.5:4.3": "Pappuyya jātimaraṇassa antaṁ,",
  "sn2.5:4.4": "Nāyūhatī pāragato hi so”ti.",
  "sn2.6:0.1": "Saṁyutta Nikāya 2.6",
  "sn2.6:0.2": "1. Paṭhamavagga",
  "sn2.6:0.3": "Kāmadasutta",
  "sn2.6:1.1": "Sāvatthinidānaṁ.",
  "sn2.6:1.2": "Ekamantaṁ ṭhito kho kāmado devaputto bhagavantaṁ etadavoca:",
  "sn2.6:1.3": "“dukkaraṁ, bhagavā, sudukkaraṁ, bhagavā”ti.",
  "sn2.6:2.1": "“Dukkaraṁ vāpi karonti,",
  "sn2.6:2.2": "(kāmadāti bhagavā)",
  "sn2.6:2.3": "Sekhā sīlasamāhitā;",
  "sn2.6:2.4": "Ṭhitattā anagāriyupetassa,",
  "sn2.6:2.5": "Tuṭṭhi hoti sukhāvahā”ti.",
  "sn2.6:3.1": "“Dullabhā, bhagavā, yadidaṁ tuṭṭhī”ti.",
  "sn2.6:4.1": "“Dullabhaṁ vāpi labhanti,",
  "sn2.6:4.2": "(kāmadāti bhagavā)",
  "sn2.6:4.3": "Cittavūpasame ratā;",
  "sn2.6:4.4": "Yesaṁ divā ca ratto ca,",
  "sn2.6:4.5": "Bhāvanāya rato mano”ti.",
  "sn2.6:5.1": "“Dussamādahaṁ, bhagavā, yadidaṁ cittan”ti.",
  "sn2.6:6.1": "“Dussamādahaṁ vāpi samādahanti,",
  "sn2.6:6.2": "(kāmadāti bhagavā)",
  "sn2.6:6.3": "Indriyūpasame ratā;",
  "sn2.6:6.4": "Te chetvā maccuno jālaṁ,",
  "sn2.6:6.5": "Ariyā gacchanti kāmadā”ti.",
  "sn2.6:7.1": "“Duggamo, bhagavā, visamo maggo”ti.",
  "sn2.6:8.1": "“Duggame visame vāpi,",
  "sn2.6:8.2": "Ariyā gacchanti kāmada;",
  "sn2.6:8.3": "Anariyā visame magge,",
  "sn2.6:8.4": "Papatanti avaṁsirā;",
  "sn2.6:8.5": "Ariyānaṁ samo maggo,",
  "sn2.6:8.6": "Ariyā hi visame samā”ti.",
  "sn2.7:0.1": "Saṁyutta Nikāya 2.7",
  "sn2.7:0.2": "1. Paṭhamavagga",
  "sn2.7:0.3": "Pañcālacaṇḍasutta",
  "sn2.7:1.1": "Sāvatthinidānaṁ.",
  "sn2.7:1.2": "Ekamantaṁ ṭhito kho pañcālacaṇḍo devaputto bhagavato santike imaṁ gāthaṁ abhāsi:",
  "sn2.7:2.1": "“Sambādhe vata okāsaṁ,",
  "sn2.7:2.2": "Avindi bhūrimedhaso;",
  "sn2.7:2.3": "Yo jhānamabujjhi buddho,",
  "sn2.7:2.4": "Paṭilīnanisabho munī”ti.",
  "sn2.7:3.1": "“Sambādhe vāpi vindanti,",
  "sn2.7:3.2": "(pañcālacaṇḍāti bhagavā)",
  "sn2.7:3.3": "Dhammaṁ nibbānapattiyā;",
  "sn2.7:3.4": "Ye satiṁ paccalatthaṁsu,",
  "sn2.7:3.5": "Sammā te susamāhitā”ti.",
  "sn2.8:0.1": "Saṁyutta Nikāya 2.8",
  "sn2.8:0.2": "1. Paṭhamavagga",
  "sn2.8:0.3": "Tāyanasutta",
  "sn2.8:1.1": "Sāvatthinidānaṁ.",
  "sn2.8:1.2": "Atha kho tāyano devaputto purāṇatitthakaro abhikkantāya rattiyā abhikkantavaṇṇo kevalakappaṁ jetavanaṁ obhāsetvā yena bhagavā tenupasaṅkami; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ aṭṭhāsi.",
  "sn2.8:1.3": "Ekamantaṁ ṭhito kho tāyano devaputto bhagavato santike imā gāthāyo abhāsi:",
  "sn2.8:2.1": "“Chinda sotaṁ parakkamma,",
  "sn2.8:2.2": "kāme panuda brāhmaṇa;",
  "sn2.8:2.3": "Nappahāya munī kāme,",
  "sn2.8:2.4": "nekattamupapajjati.",
  "sn2.8:3.1": "Kayirā ce kayirāthenaṁ,",
  "sn2.8:3.2": "daḷhamenaṁ parakkame;",
  "sn2.8:3.3": "Sithilo hi paribbājo,",
  "sn2.8:3.4": "bhiyyo ākirate rajaṁ.",
  "sn2.8:4.1": "Akataṁ dukkaṭaṁ seyyo,",
  "sn2.8:4.2": "pacchā tapati dukkaṭaṁ;",
  "sn2.8:4.3": "Katañca sukataṁ seyyo,",
  "sn2.8:4.4": "yaṁ katvā nānutappati.",
  "sn2.8:5.1": "Kuso yathā duggahito,",
  "sn2.8:5.2": "hatthamevānukantati;",
  "sn2.8:5.3": "Sāmaññaṁ dupparāmaṭṭhaṁ,",
  "sn2.8:5.4": "nirayāyūpakaḍḍhati.",
  "sn2.8:6.1": "Yaṁ kiñci sithilaṁ kammaṁ,",
  "sn2.8:6.2": "saṅkiliṭṭhañca yaṁ vataṁ;",
  "sn2.8:6.3": "Saṅkassaraṁ brahmacariyaṁ,",
  "sn2.8:6.4": "na taṁ hoti mahapphalan”ti.",
  "sn2.8:7.1": "Idamavoca tāyano devaputto;",
  "sn2.8:7.2": "idaṁ vatvā bhagavantaṁ abhivādetvā padakkhiṇaṁ katvā tatthevantaradhāyīti.",
  "sn2.8:8.1": "Atha kho bhagavā tassā rattiyā accayena bhikkhū āmantesi:",
  "sn2.8:8.2": "“imaṁ, bhikkhave, rattiṁ tāyano nāma devaputto purāṇatitthakaro abhikkantāya rattiyā abhikkantavaṇṇo kevalakappaṁ jetavanaṁ obhāsetvā yenāhaṁ tenupasaṅkami; upasaṅkamitvā maṁ abhivādetvā ekamantaṁ aṭṭhāsi.",
  "sn2.8:8.3": "Ekamantaṁ ṭhito kho, bhikkhave, tāyano devaputto mama santike imā gāthāyo abhāsi:",
  "sn2.8:9.1": "‘Chinda sotaṁ parakkamma,",
  "sn2.8:9.2": "kāme panuda brāhmaṇa;",
  "sn2.8:9.3": "Nappahāya munī kāme,",
  "sn2.8:9.4": "nekattamupapajjati.",
  "sn2.8:10.1": "Kayirā ce kayirāthenaṁ,",
  "sn2.8:10.2": "daḷhamenaṁ parakkame;",
  "sn2.8:10.3": "Sithilo hi paribbājo,",
  "sn2.8:10.4": "bhiyyo ākirate rajaṁ.",
  "sn2.8:11.1": "Akataṁ dukkaṭaṁ seyyo,",
  "sn2.8:11.2": "pacchā tapati dukkaṭaṁ;",
  "sn2.8:11.3": "Katañca sukataṁ seyyo,",
  "sn2.8:11.4": "yaṁ katvā nānutappati.",
  "sn2.8:12.1": "Kuso yathā duggahito,",
  "sn2.8:12.2": "hatthamevānukantati;",
  "sn2.8:12.3": "Sāmaññaṁ dupparāmaṭṭhaṁ,",
  "sn2.8:12.4": "nirayāyūpakaḍḍhati.",
  "sn2.8:13.1": "Yaṁ kiñci sithilaṁ kammaṁ,",
  "sn2.8:13.2": "saṅkiliṭṭhañca yaṁ vataṁ;",
  "sn2.8:13.3": "Saṅkassaraṁ brahmacariyaṁ,",
  "sn2.8:13.4": "na taṁ hoti mahapphalan’ti.",
  "sn2.8:14.1": "Idamavoca, bhikkhave, tāyano devaputto, idaṁ vatvā maṁ abhivādetvā padakkhiṇaṁ katvā tatthevantaradhāyi.",
  "sn2.8:14.2": "Uggaṇhātha, bhikkhave, tāyanagāthā;",
  "sn2.8:14.3": "pariyāpuṇātha, bhikkhave, tāyanagāthā;",
  "sn2.8:14.4": "dhāretha, bhikkhave, tāyanagāthā.",
  "sn2.8:14.5": "Atthasaṁhitā, bhikkhave, tāyanagāthā ādibrahmacariyikā”ti.",
  "sn2.9:0.1": "Saṁyutta Nikāya 2.9",
  "sn2.9:0.2": "1. Paṭhamavagga",
  "sn2.9:0.3": "Candimasutta",
  "sn2.9:1.1": "Sāvatthinidānaṁ.",
  "sn2.9:1.2": "Tena kho pana samayena candimā devaputto rāhunā asurindena gahito hoti.",
  "sn2.9:1.3": "Atha kho candimā devaputto bhagavantaṁ anussaramāno tāyaṁ velāyaṁ imaṁ gāthaṁ abhāsi:",
  "sn2.9:2.1": "“Namo te buddha vīratthu,",
  "sn2.9:2.2": "vippamuttosi sabbadhi;",
  "sn2.9:2.3": "Sambādhapaṭipannosmi,",
  "sn2.9:2.4": "tassa me saraṇaṁ bhavā”ti.",
  "sn2.9:3.1": "Atha kho bhagavā candimaṁ devaputtaṁ ārabbha rāhuṁ asurindaṁ gāthāya ajjhabhāsi:",
  "sn2.9:4.1": "“Tathāgataṁ arahantaṁ,",
  "sn2.9:4.2": "candimā saraṇaṁ gato;",
  "sn2.9:4.3": "Rāhu candaṁ pamuñcassu,",
  "sn2.9:4.4": "buddhā lokānukampakā”ti.",
  "sn2.9:5.1": "Atha kho rāhu asurindo candimaṁ devaputtaṁ muñcitvā taramānarūpo yena vepacitti asurindo tenupasaṅkami; upasaṅkamitvā saṁviggo lomahaṭṭhajāto ekamantaṁ aṭṭhāsi.",
  "sn2.9:5.2": "Ekamantaṁ ṭhitaṁ kho rāhuṁ asurindaṁ vepacitti asurindo gāthāya ajjhabhāsi:",
  "sn2.9:6.1": "“Kiṁ nu santaramānova,",
  "sn2.9:6.2": "rāhu candaṁ pamuñcasi;",
  "sn2.9:6.3": "Saṁviggarūpo āgamma,",
  "sn2.9:6.4": "kiṁ nu bhītova tiṭṭhasī”ti.",
  "sn2.9:7.1": "“Sattadhā me phale muddhā,",
  "sn2.9:7.2": "jīvanto na sukhaṁ labhe;",
  "sn2.9:7.3": "Buddhagāthābhigītomhi,",
  "sn2.9:7.4": "no ce muñceyya candiman”ti.",
  "sn2.10:0.1": "Saṁyutta Nikāya 2.10",
  "sn2.10:0.2": "1. Paṭhamavagga",
  "sn2.10:0.3": "Sūriyasutta",
  "sn2.10:1.1": "Sāvatthinidānaṁ.",
  "sn2.10:1.2": "Tena kho pana samayena sūriyo devaputto rāhunā asurindena gahito hoti.",
  "sn2.10:1.3": "Atha kho sūriyo devaputto bhagavantaṁ anussaramāno tāyaṁ velāyaṁ imaṁ gāthaṁ abhāsi:",
  "sn2.10:2.1": "“Namo te buddha vīratthu,",
  "sn2.10:2.2": "vippamuttosi sabbadhi;",
  "sn2.10:2.3": "Sambādhapaṭipannosmi,",
  "sn2.10:2.4": "tassa me saraṇaṁ bhavā”ti.",
  "sn2.10:3.1": "Atha kho bhagavā sūriyaṁ devaputtaṁ ārabbha rāhuṁ asurindaṁ gāthāhi ajjhabhāsi:",
  "sn2.10:4.1": "“Tathāgataṁ arahantaṁ,",
  "sn2.10:4.2": "sūriyo saraṇaṁ gato;",
  "sn2.10:4.3": "Rāhu sūriyaṁ pamuñcassu,",
  "sn2.10:4.4": "buddhā lokānukampakā.",
  "sn2.10:5.1": "Yo andhakāre tamasi pabhaṅkaro,",
  "sn2.10:5.2": "Verocano maṇḍalī uggatejo;",
  "sn2.10:5.3": "Mā rāhu gilī caramantalikkhe,",
  "sn2.10:5.4": "Pajaṁ mamaṁ rāhu pamuñca sūriyan”ti.",
  "sn2.10:6.1": "Atha kho rāhu asurindo sūriyaṁ devaputtaṁ muñcitvā taramānarūpo yena vepacitti asurindo tenupasaṅkami; upasaṅkamitvā saṁviggo lomahaṭṭhajāto ekamantaṁ aṭṭhāsi.",
  "sn2.10:6.2": "Ekamantaṁ ṭhitaṁ kho rāhuṁ asurindaṁ vepacitti asurindo gāthāya ajjhabhāsi:",
  "sn2.10:7.1": "“Kiṁ nu santaramānova,",
  "sn2.10:7.2": "rāhu sūriyaṁ pamuñcasi;",
  "sn2.10:7.3": "Saṁviggarūpo āgamma,",
  "sn2.10:7.4": "kiṁ nu bhītova tiṭṭhasī”ti.",
  "sn2.10:8.1": "“Sattadhā me phale muddhā,",
  "sn2.10:8.2": "jīvanto na sukhaṁ labhe;",
  "sn2.10:8.3": "Buddhagāthābhigītomhi,",
  "sn2.10:8.4": "no ce muñceyya sūriyan”ti.",
  "sn2.10:8.5": "Paṭhamo vaggo.",
  "sn2.10:9.0": "Tassuddānaṁ",
  "sn2.10:9.1": "Dve kassapā ca māgho ca,",
  "sn2.10:9.2": "Māgadho dāmali kāmado;",
  "sn2.10:9.3": "Pañcālacaṇḍo tāyano,",
  "sn2.10:9.4": "Candimasūriyena te dasāti."
}
window.BILARA["sn2_v1"]["pli"]["sn2_v1:source"] =
  "SOURCE: https://suttacentral.net/ ";