window.BILARA = window.BILARA || {};
window.BILARA["sn3_v2"] = window.BILARA["sn3_v2"] || {};
window.BILARA["sn3_v2"]["pli"] = {
  "sn3.11:0.1": "Saṁyutta Nikāya 3.11",
  "sn3.11:0.2": "2. Dutiyavagga",
  "sn3.11:0.3": "Sattajaṭilasutta",
  "sn3.11:1.1": "Ekaṁ samayaṁ bhagavā sāvatthiyaṁ viharati pubbārāme migāramātupāsāde.",
  "sn3.11:1.2": "Tena kho pana samayena bhagavā sāyanhasamayaṁ paṭisallānā vuṭṭhito bahidvārakoṭṭhake nisinno hoti.",
  "sn3.11:1.3": "Atha kho rājā pasenadi kosalo yena bhagavā tenupasaṅkami; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ nisīdi.",
  "sn3.11:2.1": "Tena kho pana samayena satta ca jaṭilā satta ca nigaṇṭhā satta ca acelakā satta ca ekasāṭakā satta ca paribbājakā parūḷhakacchanakhalomā khārivividhamādāya bhagavato avidūre atikkamanti.",
  "sn3.11:2.2": "Atha kho rājā pasenadi kosalo uṭṭhāyāsanā ekaṁsaṁ uttarāsaṅgaṁ karitvā dakkhiṇajāṇumaṇḍalaṁ pathaviyaṁ nihantvā yena te satta ca jaṭilā satta ca nigaṇṭhā satta ca acelakā satta ca ekasāṭakā satta ca paribbājakā tenañjaliṁ paṇāmetvā tikkhattuṁ nāmaṁ sāvesi:",
  "sn3.11:2.3": "“rājāhaṁ, bhante, pasenadi kosalo …pe…",
  "sn3.11:2.4": "rājāhaṁ, bhante, pasenadi kosalo”ti.",
  "sn3.11:3.1": "Atha kho rājā pasenadi kosalo acirapakkantesu tesu sattasu ca jaṭilesu sattasu ca nigaṇṭhesu sattasu ca acelakesu sattasu ca ekasāṭakesu sattasu ca paribbājakesu yena bhagavā tenupasaṅkami; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ nisīdi. Ekamantaṁ nisinno kho rājā pasenadi kosalo bhagavantaṁ etadavoca:",
  "sn3.11:3.2": "“ye te, bhante, loke arahanto vā arahattamaggaṁ vā samāpannā ete tesaṁ aññatarā”ti.",
  "sn3.11:4.1": "“Dujjānaṁ kho etaṁ, mahārāja, tayā gihinā kāmabhoginā puttasambādhasayanaṁ ajjhāvasantena kāsikacandanaṁ paccanubhontena mālāgandhavilepanaṁ dhārayantena jātarūparajataṁ sādiyantena: ‘ime vā arahanto, ime vā arahattamaggaṁ samāpannā’ti.",
  "sn3.11:5.1": "Saṁvāsena kho, mahārāja, sīlaṁ veditabbaṁ. Tañca kho dīghena addhunā, na ittaraṁ; manasikarotā, no amanasikarotā; paññavatā, no duppaññena.",
  "sn3.11:5.2": "Saṁvohārena kho, mahārāja, soceyyaṁ veditabbaṁ. Tañca kho dīghena addhunā, na ittaraṁ; manasikarotā, no amanasikarotā; paññavatā, no duppaññena.",
  "sn3.11:5.3": "Āpadāsu kho, mahārāja, thāmo veditabbo. So ca kho dīghena addhunā, na ittaraṁ; manasikarotā, no amanasikarotā; paññavatā, no duppaññena.",
  "sn3.11:5.4": "Sākacchāya, kho, mahārāja, paññā veditabbā. Sā ca kho dīghena addhunā, na ittaraṁ; manasikarotā, no amanasikarotā; paññavatā, no duppaññenā”ti.",
  "sn3.11:6.1": "“Acchariyaṁ, bhante, abbhutaṁ, bhante.",
  "sn3.11:6.2": "Yāva subhāsitamidaṁ, bhante, bhagavatā:",
  "sn3.11:6.3": "‘dujjānaṁ kho etaṁ, mahārāja, tayā gihinā kāmabhoginā puttasambādhasayanaṁ ajjhāvasantena kāsikacandanaṁ paccanubhontena mālāgandhavilepanaṁ dhārayantena jātarūparajataṁ sādiyantena:",
  "sn3.11:6.4": "“ime vā arahanto, ime vā arahattamaggaṁ samāpannā”ti.",
  "sn3.11:6.5": "Saṁvāsena kho, mahārāja, sīlaṁ veditabbaṁ. Tañca kho dīghena addhunā, na ittaraṁ; manasikarotā, no amanasikarotā; paññavatā, no duppaññena.",
  "sn3.11:6.6": "Saṁvohārena kho, mahārāja, soceyyaṁ veditabbaṁ. Tañca kho dīghena addhunā, na ittaraṁ; manasikarotā, no amanasikarotā; paññavatā, no duppaññena.",
  "sn3.11:6.7": "Āpadāsu kho, mahārāja, thāmo veditabbo. So ca kho dīghena addhunā, na ittaraṁ; manasikarotā, no amanasikarotā; paññavatā, no duppaññena.",
  "sn3.11:6.8": "Sākacchāya kho, mahārāja, paññā veditabbā. Sā ca kho dīghena addhunā, na ittaraṁ; manasikarotā, no amanasikarotā; paññavatā, no duppaññenā’ti.",
  "sn3.11:7.1": "Ete, bhante, mama purisā carā ocarakā janapadaṁ ocaritvā āgacchanti.",
  "sn3.11:7.2": "Tehi paṭhamaṁ ociṇṇaṁ ahaṁ pacchā osāpayissāmi.",
  "sn3.11:7.3": "Idāni te, bhante, taṁ rajojallaṁ pavāhetvā sunhātā suvilittā kappitakesamassū odātavatthā pañcahi kāmaguṇehi samappitā samaṅgībhūtā paricāressantī”ti.",
  "sn3.11:8.1": "Atha kho bhagavā etamatthaṁ viditvā tāyaṁ velāyaṁ imā gāthāyo abhāsi:",
  "sn3.11:9.1": "“Na vaṇṇarūpena naro sujāno,",
  "sn3.11:9.2": "Na vissase ittaradassanena;",
  "sn3.11:9.3": "Susaññatānañhi viyañjanena,",
  "sn3.11:9.4": "Asaññatā lokamimaṁ caranti.",
  "sn3.11:10.1": "Patirūpako mattikākuṇḍalova,",
  "sn3.11:10.2": "Lohaḍḍhamāsova suvaṇṇachanno;",
  "sn3.11:10.3": "Caranti loke parivārachannā,",
  "sn3.11:10.4": "Anto asuddhā bahi sobhamānā”ti.",
  "sn3.12:0.1": "Saṁyutta Nikāya 3.12",
  "sn3.12:0.2": "2. Dutiyavagga",
  "sn3.12:0.3": "Pañcarājasutta",
  "sn3.12:1.1": "Sāvatthinidānaṁ.",
  "sn3.12:1.2": "Tena kho pana samayena pañcannaṁ rājūnaṁ pasenadipamukhānaṁ pañcahi kāmaguṇehi samappitānaṁ samaṅgībhūtānaṁ paricārayamānānaṁ ayamantarākathā udapādi:",
  "sn3.12:1.3": "“kiṁ nu kho kāmānaṁ aggan”ti?",
  "sn3.12:1.4": "Tatrekacce evamāhaṁsu:",
  "sn3.12:1.5": "“rūpā kāmānaṁ aggan”ti.",
  "sn3.12:1.6": "Ekacce evamāhaṁsu:",
  "sn3.12:1.7": "“saddā kāmānaṁ aggan”ti.",
  "sn3.12:1.8": "Ekacce evamāhaṁsu:",
  "sn3.12:1.9": "“gandhā kāmānaṁ aggan”ti.",
  "sn3.12:1.10": "Ekacce evamāhaṁsu:",
  "sn3.12:1.11": "“rasā kāmānaṁ aggan”ti.",
  "sn3.12:1.12": "Ekacce evamāhaṁsu:",
  "sn3.12:1.13": "“phoṭṭhabbā kāmānaṁ aggan”ti.",
  "sn3.12:1.14": "Yato kho te rājāno nāsakkhiṁsu aññamaññaṁ saññāpetuṁ.",
  "sn3.12:2.1": "Atha kho rājā pasenadi kosalo te rājāno etadavoca:",
  "sn3.12:2.2": "“āyāma, mārisā, yena bhagavā tenupasaṅkamissāma; upasaṅkamitvā bhagavantaṁ etamatthaṁ paṭipucchissāma.",
  "sn3.12:2.3": "Yathā no bhagavā byākarissati tathā naṁ dhāressāmā”ti.",
  "sn3.12:2.4": "“Evaṁ, mārisā”ti kho te rājāno rañño pasenadissa kosalassa paccassosuṁ.",
  "sn3.12:3.1": "Atha kho te pañca rājāno pasenadipamukhā yena bhagavā tenupasaṅkamiṁsu; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ nisīdiṁsu. Ekamantaṁ nisinno kho rājā pasenadi kosalo bhagavantaṁ etadavoca:",
  "sn3.12:3.2": "“idha, bhante, amhākaṁ pañcannaṁ rājūnaṁ pañcahi kāmaguṇehi samappitānaṁ samaṅgībhūtānaṁ paricārayamānānaṁ ayamantarākathā udapādi:",
  "sn3.12:3.3": "‘kiṁ nu kho kāmānaṁ aggan’ti?",
  "sn3.12:3.4": "Ekacce evamāhaṁsu:",
  "sn3.12:3.5": "‘rūpā kāmānaṁ aggan’ti.",
  "sn3.12:3.6": "Ekacce evamāhaṁsu:",
  "sn3.12:3.7": "‘saddā kāmānaṁ aggan’ti.",
  "sn3.12:3.8": "Ekacce evamāhaṁsu:",
  "sn3.12:3.9": "‘gandhā kāmānaṁ aggan’ti.",
  "sn3.12:3.10": "Ekacce evamāhaṁsu:",
  "sn3.12:3.11": "‘rasā kāmānaṁ aggan’ti.",
  "sn3.12:3.12": "Ekacce evamāhaṁsu:",
  "sn3.12:3.13": "‘phoṭṭhabbā kāmānaṁ aggan’ti.",
  "sn3.12:3.14": "Kiṁ nu kho, bhante, kāmānaṁ aggan”ti?",
  "sn3.12:4.1": "“Manāpapariyantaṁ khvāhaṁ, mahārāja, pañcasu kāmaguṇesu agganti vadāmi.",
  "sn3.12:4.2": "Teva, mahārāja, rūpā ekaccassa manāpā honti, teva rūpā ekaccassa amanāpā honti.",
  "sn3.12:4.3": "Yehi ca yo rūpehi attamano hoti paripuṇṇasaṅkappo, so tehi rūpehi aññaṁ rūpaṁ uttaritaraṁ vā paṇītataraṁ vā na pattheti.",
  "sn3.12:4.4": "Te tassa rūpā paramā honti.",
  "sn3.12:4.5": "Te tassa rūpā anuttarā honti.",
  "sn3.12:5.1": "Teva, mahārāja, saddā ekaccassa manāpā honti, teva saddā ekaccassa amanāpā honti.",
  "sn3.12:5.2": "Yehi ca yo saddehi attamano hoti paripuṇṇasaṅkappo, so tehi saddehi aññaṁ saddaṁ uttaritaraṁ vā paṇītataraṁ vā na pattheti.",
  "sn3.12:5.3": "Te tassa saddā paramā honti.",
  "sn3.12:5.4": "Te tassa saddā anuttarā honti.",
  "sn3.12:6.1": "Teva, mahārāja, gandhā ekaccassa manāpā honti, teva gandhā ekaccassa amanāpā honti.",
  "sn3.12:6.2": "Yehi ca yo gandhehi attamano hoti paripuṇṇasaṅkappo, so tehi gandhehi aññaṁ gandhaṁ uttaritaraṁ vā paṇītataraṁ vā na pattheti.",
  "sn3.12:6.3": "Te tassa gandhā paramā honti.",
  "sn3.12:6.4": "Te tassa gandhā anuttarā honti.",
  "sn3.12:7.1": "Teva, mahārāja, rasā ekaccassa manāpā honti, teva rasā ekaccassa amanāpā honti.",
  "sn3.12:7.2": "Yehi ca yo rasehi attamano hoti paripuṇṇasaṅkappo, so tehi rasehi aññaṁ rasaṁ uttaritaraṁ vā paṇītataraṁ vā na pattheti.",
  "sn3.12:7.3": "Te tassa rasā paramā honti.",
  "sn3.12:7.4": "Te tassa rasā anuttarā honti.",
  "sn3.12:8.1": "Teva, mahārāja, phoṭṭhabbā ekaccassa manāpā honti, teva phoṭṭhabbā ekaccassa amanāpā honti.",
  "sn3.12:8.2": "Yehi ca yo phoṭṭhabbehi attamano hoti paripuṇṇasaṅkappo, so tehi phoṭṭhabbehi aññaṁ phoṭṭhabbaṁ uttaritaraṁ vā paṇītataraṁ vā na pattheti.",
  "sn3.12:8.3": "Te tassa phoṭṭhabbā paramā honti.",
  "sn3.12:8.4": "Te tassa phoṭṭhabbā anuttarā hontī”ti.",
  "sn3.12:9.1": "Tena kho pana samayena candanaṅgaliko upāsako tassaṁ parisāyaṁ nisinno hoti.",
  "sn3.12:9.2": "Atha kho candanaṅgaliko upāsako uṭṭhāyāsanā ekaṁsaṁ uttarāsaṅgaṁ karitvā yena bhagavā tenañjaliṁ paṇāmetvā bhagavantaṁ etadavoca:",
  "sn3.12:9.3": "“paṭibhāti maṁ, bhagavā, paṭibhāti maṁ, sugatā”ti.",
  "sn3.12:9.4": "“Paṭibhātu taṁ, candanaṅgalikā”ti bhagavā avoca.",
  "sn3.12:10.1": "Atha kho candanaṅgaliko upāsako bhagavato sammukhā tadanurūpāya gāthāya abhitthavi:",
  "sn3.12:11.1": "“Padumaṁ yathā kokanadaṁ sugandhaṁ,",
  "sn3.12:11.2": "Pāto siyā phullamavītagandhaṁ;",
  "sn3.12:11.3": "Aṅgīrasaṁ passa virocamānaṁ,",
  "sn3.12:11.4": "Tapantamādiccamivantalikkhe”ti.",
  "sn3.12:12.1": "Atha kho te pañca rājāno candanaṅgalikaṁ upāsakaṁ pañcahi uttarāsaṅgehi acchādesuṁ.",
  "sn3.12:12.2": "Atha kho candanaṅgaliko upāsako tehi pañcahi uttarāsaṅgehi bhagavantaṁ acchādesīti.",
  "sn3.13:0.1": "Saṁyutta Nikāya 3.13",
  "sn3.13:0.2": "2. Dutiyavagga",
  "sn3.13:0.3": "Doṇapākasutta",
  "sn3.13:1.1": "Sāvatthinidānaṁ.",
  "sn3.13:1.2": "Tena kho pana samayena rājā pasenadi kosalo doṇapākakuraṁ bhuñjati.",
  "sn3.13:1.3": "Atha kho rājā pasenadi kosalo bhuttāvī mahassāsī yena bhagavā tenupasaṅkami; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ nisīdi.",
  "sn3.13:2.1": "Atha kho bhagavā rājānaṁ pasenadiṁ kosalaṁ bhuttāviṁ mahassāsiṁ viditvā tāyaṁ velāyaṁ imaṁ gāthaṁ abhāsi:",
  "sn3.13:3.1": "“Manujassa sadā satīmato,",
  "sn3.13:3.2": "Mattaṁ jānato laddhabhojane;",
  "sn3.13:3.3": "Tanukassa bhavanti vedanā,",
  "sn3.13:3.4": "Saṇikaṁ jīrati āyupālayan”ti.",
  "sn3.13:4.1": "Tena kho pana samayena sudassano māṇavo rañño pasenadissa kosalassa piṭṭhito ṭhito hoti.",
  "sn3.13:4.2": "Atha kho rājā pasenadi kosalo sudassanaṁ māṇavaṁ āmantesi:",
  "sn3.13:4.3": "“ehi tvaṁ, tāta sudassana, bhagavato santike imaṁ gāthaṁ pariyāpuṇitvā mama bhattābhihāre bhattābhihāre bhāsa.",
  "sn3.13:4.4": "Ahañca te devasikaṁ kahāpaṇasataṁ kahāpaṇasataṁ niccaṁ bhikkhaṁ pavattayissāmī”ti.",
  "sn3.13:4.5": "“Evaṁ, devā”ti kho sudassano māṇavo rañño pasenadissa kosalassa paṭissutvā bhagavato santike imaṁ gāthaṁ pariyāpuṇitvā rañño pasenadissa kosalassa bhattābhihāre sudaṁ bhāsati:",
  "sn3.13:5.1": "“Manujassa sadā satīmato,",
  "sn3.13:5.2": "Mattaṁ jānato laddhabhojane;",
  "sn3.13:5.3": "Tanukassa bhavanti vedanā,",
  "sn3.13:5.4": "Saṇikaṁ jīrati āyupālayan”ti.",
  "sn3.13:6.1": "Atha kho rājā pasenadi kosalo anupubbena nāḷikodanaparamatāya saṇṭhāsi.",
  "sn3.13:6.2": "Atha kho rājā pasenadi kosalo aparena samayena susallikhitagatto pāṇinā gattāni anumajjanto tāyaṁ velāyaṁ imaṁ udānaṁ udānesi:",
  "sn3.13:6.3": "“ubhayena vata maṁ so bhagavā atthena anukampi",
  "sn3.13:6.4": "diṭṭhadhammikena ceva atthena samparāyikena cā”ti.",
  "sn3.14:0.1": "Saṁyutta Nikāya 3.14",
  "sn3.14:0.2": "2. Dutiyavagga",
  "sn3.14:0.3": "Paṭhamasaṅgāmasutta",
  "sn3.14:1.1": "Sāvatthinidānaṁ.",
  "sn3.14:1.2": "Atha kho rājā māgadho ajātasattu vedehiputto caturaṅginiṁ senaṁ sannayhitvā rājānaṁ pasenadiṁ kosalaṁ abbhuyyāsi yena kāsi.",
  "sn3.14:1.3": "Assosi kho rājā pasenadi kosalo:",
  "sn3.14:1.4": "“rājā kira māgadho ajātasattu vedehiputto caturaṅginiṁ senaṁ sannayhitvā mamaṁ abbhuyyāto yena kāsī”ti.",
  "sn3.14:1.5": "Atha kho rājā pasenadi kosalo caturaṅginiṁ senaṁ sannayhitvā rājānaṁ māgadhaṁ ajātasattuṁ vedehiputtaṁ paccuyyāsi yena kāsi.",
  "sn3.14:1.6": "Atha kho rājā ca māgadho ajātasattu vedehiputto rājā ca pasenadi kosalo saṅgāmesuṁ.",
  "sn3.14:1.7": "Tasmiṁ kho pana saṅgāme rājā māgadho ajātasattu vedehiputto rājānaṁ pasenadiṁ kosalaṁ parājesi.",
  "sn3.14:1.8": "Parājito ca rājā pasenadi kosalo sakameva rājadhāniṁ sāvatthiṁ paccuyyāsi.",
  "sn3.14:2.1": "Atha kho sambahulā bhikkhū pubbaṇhasamayaṁ nivāsetvā pattacīvaramādāya sāvatthiṁ piṇḍāya pavisiṁsu.",
  "sn3.14:2.2": "Sāvatthiyaṁ piṇḍāya caritvā pacchābhattaṁ piṇḍapātapaṭikkantā yena bhagavā tenupasaṅkamiṁsu; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ nisīdiṁsu. Ekamantaṁ nisinnā kho te bhikkhū bhagavantaṁ etadavocuṁ:",
  "sn3.14:3.1": "“Idha, bhante, rājā māgadho ajātasattu vedehiputto caturaṅginiṁ senaṁ sannayhitvā rājānaṁ pasenadiṁ kosalaṁ abbhuyyāsi yena kāsi.",
  "sn3.14:3.2": "Assosi kho, bhante, rājā pasenadi kosalo:",
  "sn3.14:3.3": "‘rājā kira māgadho ajātasattu vedehiputto caturaṅginiṁ senaṁ sannayhitvā mamaṁ abbhuyyāto yena kāsī’ti.",
  "sn3.14:3.4": "Atha kho, bhante, rājā pasenadi kosalo caturaṅginiṁ senaṁ sannayhitvā rājānaṁ māgadhaṁ ajātasattuṁ vedehiputtaṁ paccuyyāsi yena kāsi.",
  "sn3.14:3.5": "Atha kho, bhante, rājā ca māgadho ajātasattu vedehiputto rājā ca pasenadi kosalo saṅgāmesuṁ.",
  "sn3.14:3.6": "Tasmiṁ kho pana, bhante, saṅgāme rājā māgadho ajātasattu vedehiputto rājānaṁ pasenadiṁ kosalaṁ parājesi.",
  "sn3.14:3.7": "Parājito ca, bhante, rājā pasenadi kosalo sakameva rājadhāniṁ sāvatthiṁ paccuyyāsī”ti.",
  "sn3.14:4.1": "“Rājā, bhikkhave, māgadho ajātasattu vedehiputto pāpamitto pāpasahāyo pāpasampavaṅko;",
  "sn3.14:4.2": "rājā ca kho, bhikkhave, pasenadi kosalo kalyāṇamitto kalyāṇasahāyo kalyāṇasampavaṅko.",
  "sn3.14:4.3": "Ajjeva, bhikkhave, rājā pasenadi kosalo imaṁ rattiṁ dukkhaṁ seti parājito”ti.",
  "sn3.14:4.4": "Idamavoca …pe…",
  "sn3.14:5.1": "“Jayaṁ veraṁ pasavati,",
  "sn3.14:5.2": "dukkhaṁ seti parājito;",
  "sn3.14:5.3": "Upasanto sukhaṁ seti,",
  "sn3.14:5.4": "hitvā jayaparājayan”ti.",
  "sn3.15:0.1": "Saṁyutta Nikāya 3.15",
  "sn3.15:0.2": "2. Dutiyavagga",
  "sn3.15:0.3": "Dutiyasaṅgāmasutta",
  "sn3.15:1.1": "Atha kho rājā māgadho ajātasattu vedehiputto caturaṅginiṁ senaṁ sannayhitvā rājānaṁ pasenadiṁ kosalaṁ abbhuyyāsi yena kāsi.",
  "sn3.15:1.2": "Assosi kho rājā pasenadi kosalo:",
  "sn3.15:1.3": "“rājā kira māgadho ajātasattu vedehiputto caturaṅginiṁ senaṁ sannayhitvā mamaṁ abbhuyyāto yena kāsī”ti.",
  "sn3.15:1.4": "Atha kho rājā pasenadi kosalo caturaṅginiṁ senaṁ sannayhitvā rājānaṁ māgadhaṁ ajātasattuṁ vedehiputtaṁ paccuyyāsi yena kāsi.",
  "sn3.15:1.5": "Atha kho rājā ca māgadho ajātasattu vedehiputto rājā ca pasenadi kosalo saṅgāmesuṁ.",
  "sn3.15:1.6": "Tasmiṁ kho pana saṅgāme rājā pasenadi kosalo rājānaṁ māgadhaṁ ajātasattuṁ vedehiputtaṁ parājesi, jīvaggāhañca naṁ aggahesi.",
  "sn3.15:1.7": "Atha kho rañño pasenadissa kosalassa etadahosi:",
  "sn3.15:1.8": "“kiñcāpi kho myāyaṁ rājā māgadho ajātasattu vedehiputto adubbhantassa dubbhati, atha ca pana me bhāgineyyo hoti.",
  "sn3.15:1.9": "Yannūnāhaṁ rañño māgadhassa ajātasattuno vedehiputtassa sabbaṁ hatthikāyaṁ pariyādiyitvā sabbaṁ assakāyaṁ pariyādiyitvā sabbaṁ rathakāyaṁ pariyādiyitvā sabbaṁ pattikāyaṁ pariyādiyitvā jīvantameva naṁ osajjeyyan”ti.",
  "sn3.15:2.1": "Atha kho rājā pasenadi kosalo rañño māgadhassa ajātasattuno vedehiputtassa sabbaṁ hatthikāyaṁ pariyādiyitvā sabbaṁ assakāyaṁ pariyādiyitvā sabbaṁ rathakāyaṁ pariyādiyitvā sabbaṁ pattikāyaṁ pariyādiyitvā jīvantameva naṁ osajji.",
  "sn3.15:3.1": "Atha kho sambahulā bhikkhū pubbaṇhasamayaṁ nivāsetvā pattacīvaramādāya sāvatthiṁ piṇḍāya pavisiṁsu.",
  "sn3.15:3.2": "Sāvatthiyaṁ piṇḍāya caritvā pacchābhattaṁ piṇḍapātapaṭikkantā yena bhagavā tenupasaṅkamiṁsu; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ nisīdiṁsu. Ekamantaṁ nisinnā kho te bhikkhū bhagavantaṁ etadavocuṁ:",
  "sn3.15:4.1": "“Idha, bhante, rājā māgadho ajātasattu vedehiputto caturaṅginiṁ senaṁ sannayhitvā rājānaṁ pasenadiṁ kosalaṁ abbhuyyāsi yena kāsi.",
  "sn3.15:4.2": "Assosi kho, bhante, rājā pasenadi kosalo:",
  "sn3.15:4.3": "‘rājā kira māgadho ajātasattu vedehiputto caturaṅginiṁ senaṁ sannayhitvā mamaṁ abbhuyyāto yena kāsī’ti.",
  "sn3.15:4.4": "Atha kho, bhante, rājā pasenadi kosalo caturaṅginiṁ senaṁ sannayhitvā rājānaṁ māgadhaṁ ajātasattuṁ vedehiputtaṁ paccuyyāsi yena kāsi.",
  "sn3.15:4.5": "Atha kho, bhante, rājā ca māgadho ajātasattu vedehiputto rājā ca pasenadi kosalo saṅgāmesuṁ.",
  "sn3.15:4.6": "Tasmiṁ kho pana, bhante, saṅgāme rājā pasenadi kosalo rājānaṁ māgadhaṁ ajātasattuṁ vedehiputtaṁ parājesi, jīvaggāhañca naṁ aggahesi.",
  "sn3.15:4.7": "Atha kho, bhante, rañño pasenadissa kosalassa etadahosi:",
  "sn3.15:4.8": "‘kiñcāpi kho myāyaṁ rājā māgadho ajātasattu vedehiputto adubbhantassa dubbhati, atha ca pana me bhāgineyyo hoti.",
  "sn3.15:4.9": "Yannūnāhaṁ rañño māgadhassa ajātasattuno vedehiputtassa sabbaṁ hatthikāyaṁ pariyādiyitvā sabbaṁ assakāyaṁ sabbaṁ rathakāyaṁ sabbaṁ pattikāyaṁ pariyādiyitvā jīvantameva naṁ osajjeyyan’”ti.",
  "sn3.15:5.1": "“Atha kho, bhante, rājā pasenadi kosalo rañño māgadhassa ajātasattuno vedehiputtassa sabbaṁ hatthikāyaṁ pariyādiyitvā sabbaṁ assakāyaṁ pariyādiyitvā sabbaṁ rathakāyaṁ pariyādiyitvā sabbaṁ pattikāyaṁ pariyādiyitvā jīvantameva naṁ osajjī”ti.",
  "sn3.15:6.1": "Atha kho bhagavā etamatthaṁ viditvā tāyaṁ velāyaṁ imā gāthāyo abhāsi:",
  "sn3.15:7.1": "“Vilumpateva puriso,",
  "sn3.15:7.2": "yāvassa upakappati;",
  "sn3.15:7.3": "Yadā caññe vilumpanti,",
  "sn3.15:7.4": "so vilutto viluppati.",
  "sn3.15:8.1": "Ṭhānañhi maññati bālo,",
  "sn3.15:8.2": "yāva pāpaṁ na paccati;",
  "sn3.15:8.3": "Yadā ca paccati pāpaṁ,",
  "sn3.15:8.4": "atha dukkhaṁ nigacchati.",
  "sn3.15:9.1": "Hantā labhati hantāraṁ,",
  "sn3.15:9.2": "jetāraṁ labhate jayaṁ;",
  "sn3.15:9.3": "Akkosako ca akkosaṁ,",
  "sn3.15:9.4": "rosetārañca rosako;",
  "sn3.15:9.5": "Atha kammavivaṭṭena,",
  "sn3.15:9.6": "so vilutto viluppatī”ti.",
  "sn3.16:0.1": "Saṁyutta Nikāya 3.16",
  "sn3.16:0.2": "2. Dutiyavagga",
  "sn3.16:0.3": "Mallikāsutta",
  "sn3.16:1.1": "Sāvatthinidānaṁ.",
  "sn3.16:1.2": "Atha kho rājā pasenadi kosalo yena bhagavā tenupasaṅkami; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ nisīdi.",
  "sn3.16:1.3": "Atha kho aññataro puriso yena rājā pasenadi kosalo tenupasaṅkami; upasaṅkamitvā rañño pasenadissa kosalassa upakaṇṇake ārocesi:",
  "sn3.16:1.4": "“mallikā, deva, devī dhītaraṁ vijātā”ti.",
  "sn3.16:1.5": "Evaṁ vutte, rājā pasenadi kosalo anattamano ahosi.",
  "sn3.16:2.1": "Atha kho bhagavā rājānaṁ pasenadiṁ kosalaṁ anattamanataṁ viditvā tāyaṁ velāyaṁ imā gāthāyo abhāsi:",
  "sn3.16:3.1": "“Itthīpi hi ekacciyā,",
  "sn3.16:3.2": "seyyā posa janādhipa;",
  "sn3.16:3.3": "Medhāvinī sīlavatī,",
  "sn3.16:3.4": "sassudevā patibbatā.",
  "sn3.16:4.1": "Tassā yo jāyati poso,",
  "sn3.16:4.2": "sūro hoti disampati;",
  "sn3.16:4.3": "Tādisā subhagiyā putto,",
  "sn3.16:4.4": "rajjampi anusāsatī”ti.",
  "sn3.17:0.1": "Saṁyutta Nikāya 3.17",
  "sn3.17:0.2": "2. Dutiyavagga",
  "sn3.17:0.3": "Appamādasutta",
  "sn3.17:1.1": "Sāvatthinidānaṁ.",
  "sn3.17:1.2": "Ekamantaṁ nisīdi.",
  "sn3.17:1.3": "Ekamantaṁ nisinno kho rājā pasenadi kosalo bhagavantaṁ etadavoca:",
  "sn3.17:1.4": "“atthi nu kho, bhante, eko dhammo yo ubho atthe samadhiggayha tiṭṭhati",
  "sn3.17:1.5": "diṭṭhadhammikañceva atthaṁ samparāyikañcā”ti?",
  "sn3.17:2.1": "“Atthi kho, mahārāja, eko dhammo yo ubho atthe samadhiggayha tiṭṭhati",
  "sn3.17:2.2": "diṭṭhadhammikañceva atthaṁ samparāyikañcā”ti.",
  "sn3.17:3.1": "“Katamo pana, bhante, eko dhammo, yo ubho atthe samadhiggayha tiṭṭhati",
  "sn3.17:3.2": "diṭṭhadhammikañceva atthaṁ samparāyikañcā”ti?",
  "sn3.17:4.1": "“Appamādo kho, mahārāja, eko dhammo, yo ubho atthe samadhiggayha tiṭṭhati",
  "sn3.17:4.2": "diṭṭhadhammikañceva atthaṁ samparāyikañcāti.",
  "sn3.17:4.3": "Seyyathāpi, mahārāja, yāni kānici jaṅgalānaṁ pāṇānaṁ padajātāni, sabbāni tāni hatthipade samodhānaṁ gacchanti, hatthipadaṁ tesaṁ aggamakkhāyatiyadidaṁ mahantattena;",
  "sn3.17:4.4": "evameva kho, mahārāja, appamādo eko dhammo, yo ubho atthe samadhiggayha tiṭṭhati",
  "sn3.17:4.5": "diṭṭhadhammikañceva atthaṁ samparāyikañcā”ti.",
  "sn3.17:4.6": "Idamavoca …pe…",
  "sn3.17:5.1": "“Āyuṁ arogiyaṁ vaṇṇaṁ,",
  "sn3.17:5.2": "saggaṁ uccākulīnataṁ;",
  "sn3.17:5.3": "Ratiyo patthayantena,",
  "sn3.17:5.4": "uḷārā aparāparā.",
  "sn3.17:6.1": "Appamādaṁ pasaṁsanti,",
  "sn3.17:6.2": "puññakiriyāsu paṇḍitā;",
  "sn3.17:6.3": "Appamatto ubho atthe,",
  "sn3.17:6.4": "adhiggaṇhāti paṇḍito.",
  "sn3.17:7.1": "Diṭṭhe dhamme ca yo attho,",
  "sn3.17:7.2": "yo cattho samparāyiko;",
  "sn3.17:7.3": "Atthābhisamayā dhīro,",
  "sn3.17:7.4": "paṇḍitoti pavuccatī”ti.",
  "sn3.18:0.1": "Saṁyutta Nikāya 3.18",
  "sn3.18:0.2": "2. Dutiyavagga",
  "sn3.18:0.3": "Kalyāṇamittasutta",
  "sn3.18:1.1": "Sāvatthinidānaṁ.",
  "sn3.18:1.2": "Ekamantaṁ nisinno kho rājā pasenadi kosalo bhagavantaṁ etadavoca:",
  "sn3.18:1.3": "“idha mayhaṁ, bhante, rahogatassa paṭisallīnassa evaṁ cetaso parivitakko udapādi:",
  "sn3.18:1.4": "‘svākkhāto bhagavatā dhammo, so ca kho kalyāṇamittassa kalyāṇasahāyassa kalyāṇasampavaṅkassa, no pāpamittassa no pāpasahāyassa no pāpasampavaṅkassā’”ti.",
  "sn3.18:2.1": "“Evametaṁ, mahārāja, evametaṁ, mahārāja.",
  "sn3.18:2.2": "Svākkhāto, mahārāja, mayā dhammo. So ca kho kalyāṇamittassa kalyāṇasahāyassa kalyāṇasampavaṅkassa, no pāpamittassa no pāpasahāyassa no pāpasampavaṅkassāti.",
  "sn3.18:3.1": "Ekamidāhaṁ, mahārāja, samayaṁ sakkesu viharāmi nagarakaṁ nāma sakyānaṁ nigamo.",
  "sn3.18:3.2": "Atha kho, mahārāja, ānando bhikkhu yenāhaṁ tenupasaṅkami; upasaṅkamitvā maṁ abhivādetvā ekamantaṁ nisīdi. Ekamantaṁ nisinno kho, mahārāja, ānando bhikkhu maṁ etadavoca:",
  "sn3.18:3.3": "‘upaḍḍhamidaṁ, bhante, brahmacariyassayadidaṁ kalyāṇamittatā kalyāṇasahāyatā kalyāṇasampavaṅkatā’ti.",
  "sn3.18:4.1": "Evaṁ vuttāhaṁ, mahārāja, ānandaṁ bhikkhuṁ etadavocaṁ:",
  "sn3.18:4.2": "‘mā hevaṁ, ānanda, mā hevaṁ, ānanda.",
  "sn3.18:4.3": "Sakalameva hidaṁ, ānanda, brahmacariyaṁyadidaṁ kalyāṇamittatā kalyāṇasahāyatā kalyāṇasampavaṅkatā.",
  "sn3.18:4.4": "Kalyāṇamittassetaṁ, ānanda, bhikkhuno pāṭikaṅkhaṁ kalyāṇasahāyassa kalyāṇasampavaṅkassa ariyaṁ aṭṭhaṅgikaṁ maggaṁ bhāvessati ariyaṁ aṭṭhaṅgikaṁ maggaṁ bahulīkarissati.",
  "sn3.18:5.1": "Kathañca, ānanda, bhikkhu kalyāṇamitto kalyāṇasahāyo kalyāṇasampavaṅko ariyaṁ aṭṭhaṅgikaṁ maggaṁ bhāveti, ariyaṁ aṭṭhaṅgikaṁ maggaṁ bahulīkaroti?",
  "sn3.18:5.2": "Idhānanda, bhikkhu sammādiṭṭhiṁ bhāveti vivekanissitaṁ virāganissitaṁ nirodhanissitaṁ vossaggapariṇāmiṁ, sammāsaṅkappaṁ bhāveti … sammāvācaṁ bhāveti … sammākammantaṁ bhāveti … sammāājīvaṁ bhāveti … sammāvāyāmaṁ bhāveti … sammāsatiṁ bhāveti … sammāsamādhiṁ bhāveti vivekanissitaṁ virāganissitaṁ nirodhanissitaṁ vossaggapariṇāmiṁ.",
  "sn3.18:5.3": "Evaṁ kho, ānanda, bhikkhu kalyāṇamitto kalyāṇasahāyo kalyāṇasampavaṅko ariyaṁ aṭṭhaṅgikaṁ maggaṁ bhāveti, ariyaṁ aṭṭhaṅgikaṁ maggaṁ bahulīkaroti.",
  "sn3.18:5.4": "Tadamināpetaṁ, ānanda, pariyāyena veditabbaṁ yathā sakalamevidaṁ brahmacariyaṁyadidaṁ kalyāṇamittatā kalyāṇasahāyatā kalyāṇasampavaṅkatāti.",
  "sn3.18:6.1": "Mamañhi, ānanda, kalyāṇamittaṁ āgamma jātidhammā sattā jātiyā parimuccanti, jarādhammā sattā jarāya parimuccanti, byādhidhammā sattā byādhito parimuccanti, maraṇadhammā sattā maraṇena parimuccanti, sokaparidevadukkhadomanassupāyāsadhammā sattā sokaparidevadukkhadomanassupāyāsehi parimuccanti.",
  "sn3.18:6.2": "Iminā kho etaṁ, ānanda, pariyāyena veditabbaṁ yathā sakalamevidaṁ brahmacariyaṁyadidaṁ kalyāṇamittatā kalyāṇasahāyatā kalyāṇasampavaṅkatā’ti.",
  "sn3.18:7.1": "Tasmātiha te, mahārāja, evaṁ sikkhitabbaṁ:",
  "sn3.18:7.2": "‘kalyāṇamitto bhavissāmi kalyāṇasahāyo kalyāṇasampavaṅko’ti.",
  "sn3.18:7.3": "Evañhi te, mahārāja, sikkhitabbaṁ.",
  "sn3.18:8.1": "Kalyāṇamittassa te, mahārāja, kalyāṇasahāyassa kalyāṇasampavaṅkassa ayaṁ eko dhammo upanissāya vihātabbo",
  "sn3.18:8.2": "appamādo kusalesu dhammesu.",
  "sn3.18:9.1": "Appamattassa te, mahārāja, viharato appamādaṁ upanissāya, itthāgārassa anuyantassa evaṁ bhavissati:",
  "sn3.18:9.2": "‘rājā kho appamatto viharati, appamādaṁ upanissāya.",
  "sn3.18:9.3": "Handa mayampi appamattā viharāma, appamādaṁ upanissāyā’ti.",
  "sn3.18:10.1": "Appamattassa te, mahārāja, viharato appamādaṁ upanissāya, khattiyānampi anuyantānaṁ evaṁ bhavissati:",
  "sn3.18:10.2": "‘rājā kho appamatto viharati appamādaṁ upanissāya.",
  "sn3.18:10.3": "Handa mayampi appamattā viharāma, appamādaṁ upanissāyā’ti.",
  "sn3.18:11.1": "Appamattassa te, mahārāja, viharato appamādaṁ upanissāya, balakāyassapi evaṁ bhavissati:",
  "sn3.18:11.2": "‘rājā kho appamatto viharati appamādaṁ upanissāya.",
  "sn3.18:11.3": "Handa mayampi appamattā viharāma, appamādaṁ upanissāyā’ti.",
  "sn3.18:12.1": "Appamattassa te, mahārāja, viharato appamādaṁ upanissāya, negamajānapadassapi evaṁ bhavissati:",
  "sn3.18:12.2": "‘rājā kho appamatto viharati, appamādaṁ upanissāya.",
  "sn3.18:12.3": "Handa mayampi appamattā viharāma, appamādaṁ upanissāyā’ti?",
  "sn3.18:13.1": "Appamattassa te, mahārāja, viharato appamādaṁ upanissāya, attāpi gutto rakkhito bhavissati",
  "sn3.18:13.2": "itthāgārampi guttaṁ rakkhitaṁ bhavissati, kosakoṭṭhāgārampi guttaṁ rakkhitaṁ bhavissatī”ti.",
  "sn3.18:13.3": "Idamavoca …pe…",
  "sn3.18:14.1": "“Bhoge patthayamānena,",
  "sn3.18:14.2": "uḷāre aparāpare;",
  "sn3.18:14.3": "Appamādaṁ pasaṁsanti,",
  "sn3.18:14.4": "puññakiriyāsu paṇḍitā;",
  "sn3.18:14.5": "Appamatto ubho atthe,",
  "sn3.18:14.6": "adhiggaṇhāti paṇḍito.",
  "sn3.18:15.1": "Diṭṭhe dhamme ca yo attho,",
  "sn3.18:15.2": "yo cattho samparāyiko;",
  "sn3.18:15.3": "Atthābhisamayā dhīro,",
  "sn3.18:15.4": "paṇḍitoti pavuccatī”ti.",
  "sn3.19:0.1": "Saṁyutta Nikāya 3.19",
  "sn3.19:0.2": "2. Dutiyavagga",
  "sn3.19:0.3": "Paṭhamaaputtakasutta",
  "sn3.19:1.1": "Sāvatthinidānaṁ.",
  "sn3.19:1.2": "Atha kho rājā pasenadi kosalo divā divassa yena bhagavā tenupasaṅkami; upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ nisīdi. Ekamantaṁ nisinnaṁ kho rājānaṁ pasenadiṁ kosalaṁ bhagavā etadavoca:",
  "sn3.19:1.3": "“handa kuto nu tvaṁ, mahārāja, āgacchasi divā divassā”ti?",
  "sn3.19:2.1": "“Idha, bhante, sāvatthiyaṁ seṭṭhi gahapati kālaṅkato.",
  "sn3.19:2.2": "Tamahaṁ aputtakaṁ sāpateyyaṁ rājantepuraṁ atiharitvā āgacchāmi.",
  "sn3.19:2.3": "Asīti, bhante, satasahassāni hiraññasseva, ko pana vādo rūpiyassa.",
  "sn3.19:2.4": "Tassa kho pana, bhante, seṭṭhissa gahapatissa evarūpo bhattabhogo ahosi",
  "sn3.19:2.5": "kaṇājakaṁ bhuñjati bilaṅgadutiyaṁ.",
  "sn3.19:2.6": "Evarūpo vatthabhogo ahosi",
  "sn3.19:2.7": "sāṇaṁ dhāreti tipakkhavasanaṁ.",
  "sn3.19:2.8": "Evarūpo yānabhogo ahosi",
  "sn3.19:2.9": "jajjararathakena yāti paṇṇachattakena dhāriyamānenā”ti.",
  "sn3.19:3.1": "“Evametaṁ, mahārāja, evametaṁ, mahārāja.",
  "sn3.19:3.2": "Asappuriso kho, mahārāja, uḷāre bhoge labhitvā nevattānaṁ sukheti pīṇeti, na mātāpitaro sukheti pīṇeti, na puttadāraṁ sukheti pīṇeti, na dāsakammakaraporise sukheti pīṇeti, na mittāmacce sukheti pīṇeti, na samaṇabrāhmaṇesu uddhaggikaṁ dakkhiṇaṁ patiṭṭhāpeti sovaggikaṁ sukhavipākaṁ saggasaṁvattanikaṁ.",
  "sn3.19:3.3": "Tassa te bhoge evaṁ sammā aparibhuñjiyamāne rājāno vā haranti corā vā haranti aggi vā ḍahati udakaṁ vā vahati appiyā vā dāyādā haranti.",
  "sn3.19:3.4": "Evaṁsa te, mahārāja, bhogā sammā aparibhuñjiyamānā parikkhayaṁ gacchanti, no paribhogaṁ.",
  "sn3.19:4.1": "Seyyathāpi, mahārāja, amanussaṭṭhāne pokkharaṇī acchodakā sītodakā sātodakā setodakā supatitthā ramaṇīyā.",
  "sn3.19:4.2": "Taṁ jano neva hareyya na piveyya na nahāyeyya na yathāpaccayaṁ vā kareyya.",
  "sn3.19:4.3": "Evañhi taṁ, mahārāja, udakaṁ sammā aparibhuñjiyamānaṁ parikkhayaṁ gaccheyya, no paribhogaṁ.",
  "sn3.19:4.4": "Evameva kho, mahārāja, asappuriso uḷāre bhoge labhitvā nevattānaṁ sukheti pīṇeti, na mātāpitaro sukheti pīṇeti, na puttadāraṁ sukheti pīṇeti, na dāsakammakaraporise sukheti pīṇeti, na mittāmacce sukheti pīṇeti, na samaṇabrāhmaṇesu uddhaggikaṁ dakkhiṇaṁ patiṭṭhāpeti sovaggikaṁ sukhavipākaṁ saggasaṁvattanikaṁ.",
  "sn3.19:4.5": "Tassa te bhoge evaṁ sammā aparibhuñjiyamāne rājāno vā haranti, corā vā haranti, aggi vā ḍahati, udakaṁ vā vahati, appiyā vā dāyādā haranti.",
  "sn3.19:4.6": "Evaṁsa te, mahārāja, bhogā sammā aparibhuñjiyamānā parikkhayaṁ gacchanti, no paribhogaṁ.",
  "sn3.19:5.1": "Sappuriso ca kho, mahārāja, uḷāre bhoge labhitvā attānaṁ sukheti pīṇeti, mātāpitaro sukheti pīṇeti, puttadāraṁ sukheti pīṇeti, dāsakammakaraporise sukheti pīṇeti, mittāmacce sukheti pīṇeti, samaṇabrāhmaṇesu uddhaggikaṁ dakkhiṇaṁ patiṭṭhāpeti sovaggikaṁ sukhavipākaṁ saggasaṁvattanikaṁ.",
  "sn3.19:5.2": "Tassa te bhoge evaṁ sammā paribhuñjiyamāne neva rājāno haranti, na corā haranti, na aggi ḍahati, na udakaṁ vahati, na appiyā dāyādā haranti.",
  "sn3.19:5.3": "Evaṁsa te, mahārāja, bhogā sammā paribhuñjiyamānā paribhogaṁ gacchanti, no parikkhayaṁ.",
  "sn3.19:6.1": "Seyyathāpi, mahārāja, gāmassa vā nigamassa vā avidūre pokkharaṇī acchodakā sītodakā sātodakā setodakā supatitthā ramaṇīyā.",
  "sn3.19:6.2": "Tañca udakaṁ jano hareyyapi piveyyapi nahāyeyyapi yathāpaccayampi kareyya.",
  "sn3.19:6.3": "Evañhi taṁ, mahārāja, udakaṁ sammā paribhuñjiyamānaṁ paribhogaṁ gaccheyya, no parikkhayaṁ.",
  "sn3.19:6.4": "Evameva kho, mahārāja, sappuriso uḷāre bhoge labhitvā attānaṁ sukheti pīṇeti, mātāpitaro sukheti pīṇeti, puttadāraṁ sukheti pīṇeti, dāsakammakaraporise sukheti pīṇeti, mittāmacce sukheti pīṇeti, samaṇabrāhmaṇesu uddhaggikaṁ dakkhiṇaṁ patiṭṭhāpeti sovaggikaṁ sukhavipākaṁ saggasaṁvattanikaṁ.",
  "sn3.19:6.5": "Tassa te bhoge evaṁ sammā paribhuñjiyamāne neva rājāno haranti, na corā haranti, na aggi ḍahati, na udakaṁ vahati, na appiyā dāyādā haranti.",
  "sn3.19:6.6": "Evaṁsa te, mahārāja, bhogā sammā paribhuñjiyamānā paribhogaṁ gacchanti, no parikkhayan”ti.",
  "sn3.19:7.1": "“Amanussaṭṭhāne udakaṁva sītaṁ,",
  "sn3.19:7.2": "Tadapeyyamānaṁ parisosameti;",
  "sn3.19:7.3": "Evaṁ dhanaṁ kāpuriso labhitvā,",
  "sn3.19:7.4": "Nevattanā bhuñjati no dadāti.",
  "sn3.19:8.1": "Dhīro ca viññū adhigamma bhoge,",
  "sn3.19:8.2": "So bhuñjati kiccakaro ca hoti;",
  "sn3.19:8.3": "So ñātisaṅghaṁ nisabho bharitvā,",
  "sn3.19:8.4": "Anindito saggamupeti ṭhānan”ti.",
  "sn3.20:0.1": "Saṁyutta Nikāya 3.20",
  "sn3.20:0.2": "2. Dutiyavagga",
  "sn3.20:0.3": "Dutiyaaputtakasutta",
  "sn3.20:1.1": "Atha kho rājā pasenadi kosalo divā divassa yena bhagavā tenupasaṅkami; upasaṅkamitvā ekamantaṁ nisinnaṁ kho rājānaṁ pasenadiṁ kosalaṁ bhagavā etadavoca:",
  "sn3.20:1.2": "“handa kuto nu tvaṁ, mahārāja, āgacchasi divā divassā”ti?",
  "sn3.20:2.1": "“Idha, bhante, sāvatthiyaṁ seṭṭhi gahapati kālaṅkato.",
  "sn3.20:2.2": "Tamahaṁ aputtakaṁ sāpateyyaṁ rājantepuraṁ atiharitvā āgacchāmi.",
  "sn3.20:2.3": "Sataṁ, bhante, satasahassāni hiraññasseva, ko pana vādo rūpiyassa.",
  "sn3.20:2.4": "Tassa kho pana, bhante, seṭṭhissa gahapatissa evarūpo bhattabhogo ahosi",
  "sn3.20:2.5": "kaṇājakaṁ bhuñjati bilaṅgadutiyaṁ.",
  "sn3.20:2.6": "Evarūpo vatthabhogo ahosi",
  "sn3.20:2.7": "sāṇaṁ dhāreti tipakkhavasanaṁ.",
  "sn3.20:2.8": "Evarūpo yānabhogo ahosi",
  "sn3.20:2.9": "jajjararathakena yāti paṇṇachattakena dhāriyamānenā”ti.",
  "sn3.20:3.1": "“Evametaṁ, mahārāja, evametaṁ, mahārāja.",
  "sn3.20:3.2": "Bhūtapubbaṁ so, mahārāja, seṭṭhi gahapati taggarasikhiṁ nāma paccekasambuddhaṁ piṇḍapātena paṭipādesi.",
  "sn3.20:3.3": "‘Detha samaṇassa piṇḍan’ti vatvā uṭṭhāyāsanā pakkāmi.",
  "sn3.20:3.4": "Datvā ca pana pacchā vippaṭisārī ahosi:",
  "sn3.20:3.5": "‘varametaṁ piṇḍapātaṁ dāsā vā kammakarā vā bhuñjeyyun’ti.",
  "sn3.20:3.6": "Bhātu ca pana ekaputtakaṁ sāpateyyassa kāraṇā jīvitā voropesi.",
  "sn3.20:4.1": "Yaṁ kho so, mahārāja, seṭṭhi gahapati taggarasikhiṁ paccekasambuddhaṁ piṇḍapātena paṭipādesi, tassa kammassa vipākena sattakkhattuṁ sugatiṁ saggaṁ lokaṁ upapajji.",
  "sn3.20:4.2": "Tasseva kammassa vipākāvasesena imissāyeva sāvatthiyā sattakkhattuṁ seṭṭhittaṁ kāresi.",
  "sn3.20:4.3": "Yaṁ kho so, mahārāja, seṭṭhi gahapati datvā pacchā vippaṭisārī ahosi:",
  "sn3.20:4.4": "‘varametaṁ piṇḍapātaṁ dāsā vā kammakarā vā bhuñjeyyun’ti, tassa kammassa vipākena nāssuḷārāya bhattabhogāya cittaṁ namati, nāssuḷārāya vatthabhogāya cittaṁ namati, nāssuḷārāya yānabhogāya cittaṁ namati, nāssuḷārānaṁ pañcannaṁ kāmaguṇānaṁ bhogāya cittaṁ namati.",
  "sn3.20:4.5": "Yaṁ kho so, mahārāja, seṭṭhi gahapati bhātu ca pana ekaputtakaṁ sāpateyyassa kāraṇā jīvitā voropesi, tassa kammassa vipākena bahūni vassāni bahūni vassasatāni bahūni vassasahassāni bahūni vassasatasahassāni niraye paccittha.",
  "sn3.20:4.6": "Tasseva kammassa vipākāvasesena idaṁ sattamaṁ aputtakaṁ sāpateyyaṁ rājakosaṁ paveseti.",
  "sn3.20:4.7": "Tassa kho, mahārāja, seṭṭhissa gahapatissa purāṇañca puññaṁ parikkhīṇaṁ, navañca puññaṁ anupacitaṁ.",
  "sn3.20:4.8": "Ajja pana, mahārāja, seṭṭhi gahapati mahāroruve niraye paccatī”ti.",
  "sn3.20:4.9": "“Evaṁ, bhante, seṭṭhi gahapati mahāroruvaṁ nirayaṁ upapanno”ti.",
  "sn3.20:4.10": "“Evaṁ, mahārāja, seṭṭhi gahapati mahāroruvaṁ nirayaṁ upapanno”ti.",
  "sn3.20:4.11": "Idamavoca …pe….",
  "sn3.20:5.1": "“Dhaññaṁ dhanaṁ rajataṁ jātarūpaṁ,",
  "sn3.20:5.2": "Pariggahaṁ vāpi yadatthi kiñci;",
  "sn3.20:5.3": "Dāsā kammakarā pessā,",
  "sn3.20:5.4": "Ye cassa anujīvino.",
  "sn3.20:6.1": "Sabbaṁ nādāya gantabbaṁ,",
  "sn3.20:6.2": "sabbaṁ nikkhippagāminaṁ;",
  "sn3.20:6.3": "Yañca karoti kāyena,",
  "sn3.20:6.4": "vācāya uda cetasā.",
  "sn3.20:7.1": "Tañhi tassa sakaṁ hoti,",
  "sn3.20:7.2": "taṁva ādāya gacchati;",
  "sn3.20:7.3": "Taṁvassa anugaṁ hoti,",
  "sn3.20:7.4": "chāyāva anapāyinī.",
  "sn3.20:8.1": "Tasmā kareyya kalyāṇaṁ,",
  "sn3.20:8.2": "nicayaṁ samparāyikaṁ;",
  "sn3.20:8.3": "Puññāni paralokasmiṁ,",
  "sn3.20:8.4": "patiṭṭhā honti pāṇinan”ti.",
  "sn3.20:8.5": "Dutiyo vaggo.",
  "sn3.20:9.0": "Tassuddānaṁ",
  "sn3.20:9.1": "Jaṭilā pañca rājāno,",
  "sn3.20:9.2": "Doṇapākakurena ca;",
  "sn3.20:9.3": "Saṅgāmena dve vuttāni,",
  "sn3.20:9.4": "Mallikā dve appamādena ca;",
  "sn3.20:9.5": "Aputtakena dve vuttā,",
  "sn3.20:9.6": "Vaggo tena pavuccatīti."
}
window.BILARA["sn3_v2"]["pli"]["sn3_v2:source"] =
  "SOURCE: https://suttacentral.net/ ";