window.BILARA = window.BILARA || {};
window.BILARA["dn06"] = window.BILARA["dn06"] || {};
window.BILARA["dn06"]["vi"] = {
  "dn6:0.1": "Trường Bộ Kinh 6 ",
  "dn6:0.2": "Kinh Mahāli ",
  "dn6:1.0": "1. Câu chuyện các sứ giả Bà-la-môn ",
  "dn6:1.1": "Tôi nghe như vầy—",
  "dn6:1.2": "Một thời Thế Tôn trú tại Vesāli, trong Đại Lâm, tại giảng đường có nóc nhọn. ",
  "dn6:1.3": "Lúc bấy giờ, nhiều sứ giả Bà-la-môn của xứ Kosala và nhiều sứ giả Bà-la-môn của xứ Magadha đang cư trú tại Vesāli vì một công việc nào đó. ",
  "dn6:1.4": "Họ nghe rằng: ",
  "dn6:1.5": "“Này chư vị, sa-môn Gotama, con trai dòng Sakya, xuất gia từ dòng họ Sakya, đang trú tại Vesāli, trong Đại Lâm, tại giảng đường có nóc nhọn. ",
  "dn6:1.6": "Và tiếng tốt đẹp này đã được truyền tụng về Tôn giả Gotama ấy: ",
  "dn6:1.7": "‘Vị ấy là Thế Tôn, bậc A-la-hán, Chánh Đẳng Giác, đầy đủ minh và hạnh, Thiện Thệ, bậc hiểu biết thế gian, bậc vô thượng điều ngự những người đáng được điều ngự, bậc Đạo Sư của chư thiên và loài người, Phật, Thế Tôn.’ ",
  "dn6:1.8": "Ngài tự mình chứng ngộ với thắng trí rồi tuyên thuyết thế giới này cùng với chư thiên, Ma vương, Phạm thiên, cùng quần chúng gồm sa-môn, Bà-la-môn, chư thiên và loài người. ",
  "dn6:1.9": "Ngài thuyết pháp thiện ở đoạn đầu, thiện ở đoạn giữa, thiện ở đoạn cuối, có nghĩa, có văn, trình bày đời sống phạm hạnh hoàn toàn đầy đủ và thanh tịnh. ",
  "dn6:1.10": "Thật lành thay được thấy những bậc A-la-hán như vậy.” ",
  "dn6:2.1": "Bấy giờ, các sứ giả Bà-la-môn của xứ Kosala và các sứ giả Bà-la-môn của xứ Magadha đi đến Đại Lâm, giảng đường có nóc nhọn. ",
  "dn6:2.2": "Lúc ấy, Tôn giả Nāgita là thị giả của Thế Tôn. ",
  "dn6:2.3": "Rồi các sứ giả Bà-la-môn của xứ Kosala và các sứ giả Bà-la-môn của xứ Magadha đi đến Tôn giả Nāgita. Sau khi đến, họ nói với Tôn giả Nāgita như sau: ",
  "dn6:2.4": "“Này Tôn giả Nāgita, hiện nay Tôn giả Gotama đang trú ở đâu? ",
  "dn6:2.5": "Vì chúng tôi muốn được yết kiến Tôn giả Gotama ấy.” ",
  "dn6:2.6": "“Này các hiền hữu, nay chưa phải lúc để yết kiến Thế Tôn, vì Thế Tôn đang độc cư.” ",
  "dn6:2.7": "Bấy giờ, các sứ giả Bà-la-môn của xứ Kosala và các sứ giả Bà-la-môn của xứ Magadha ngồi xuống một bên ngay tại đó: ",
  "dn6:2.8": "“Chúng ta sẽ chỉ đi sau khi đã được thấy Tôn giả Gotama ấy.” ",
  "dn6:3.0": "2. Câu chuyện Oṭṭhaddha người Licchavi ",
  "dn6:3.1": "Oṭṭhaddha người Licchavi cũng cùng với một hội chúng Licchavi đông đảo đi đến Đại Lâm, giảng đường có nóc nhọn, đến chỗ Tôn giả Nāgita; sau khi đến, ông đảnh lễ Tôn giả Nāgita rồi đứng sang một bên. Đứng sang một bên, Oṭṭhaddha người Licchavi nói với Tôn giả Nāgita như sau: ",
  "dn6:3.2": "“Bạch Tôn giả Nāgita, hiện nay Thế Tôn, bậc A-la-hán, Chánh Đẳng Giác, đang trú ở đâu, ",
  "dn6:3.3": "vì chúng tôi muốn được yết kiến Thế Tôn, bậc A-la-hán, Chánh Đẳng Giác ấy.” ",
  "dn6:3.4": "“Này Mahāli, nay chưa phải lúc để yết kiến Thế Tôn, vì Thế Tôn đang độc cư.” ",
  "dn6:3.5": "Oṭṭhaddha người Licchavi ngồi xuống một bên ngay tại đó: ",
  "dn6:3.6": "“Chỉ sau khi được thấy Thế Tôn, bậc A-la-hán, Chánh Đẳng Giác ấy, tôi mới đi.” ",
  "dn6:4.1": "Bấy giờ, sa-di Sīha đi đến chỗ Tôn giả Nāgita; sau khi đến, đảnh lễ Tôn giả Nāgita rồi đứng sang một bên. Đứng sang một bên, sa-di Sīha nói với Tôn giả Nāgita như sau: ",
  "dn6:4.2": "“Bạch Tôn giả Kassapa, ở đây có nhiều sứ giả Bà-la-môn của xứ Kosala và nhiều sứ giả Bà-la-môn của xứ Magadha đến để yết kiến Thế Tôn; Oṭṭhaddha người Licchavi cũng cùng với một hội chúng Licchavi đông đảo đến đây để yết kiến Thế Tôn. Lành thay, bạch Tôn giả Kassapa, xin cho dân chúng này được yết kiến Thế Tôn.” ",
  "dn6:4.3": "“Vậy thì, này Sīha, chính ngươi hãy bạch lên Thế Tôn.” ",
  "dn6:4.4": "“Vâng, bạch Tôn giả.” Sa-di Sīha vâng lời Tôn giả Nāgita rồi đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi đứng sang một bên. Đứng sang một bên, sa-di Sīha bạch Thế Tôn như sau: ",
  "dn6:4.5": "“Bạch Thế Tôn, ở đây có nhiều sứ giả Bà-la-môn của xứ Kosala và nhiều sứ giả Bà-la-môn của xứ Magadha đến để yết kiến Thế Tôn; Oṭṭhaddha người Licchavi cũng cùng với một hội chúng Licchavi đông đảo đến để yết kiến Thế Tôn. ",
  "dn6:4.6": "Lành thay, bạch Thế Tôn, xin cho dân chúng này được yết kiến Thế Tôn.” ",
  "dn6:4.7": "“Vậy thì, này Sīha, hãy dọn chỗ ngồi ở bóng mát phía sau tịnh xá.” ",
  "dn6:4.8": "“Vâng, bạch Thế Tôn.” Sa-di Sīha vâng lời Thế Tôn rồi dọn chỗ ngồi ở bóng mát phía sau tịnh xá. ",
  "dn6:4.9": "Bấy giờ, Thế Tôn từ tịnh xá đi ra và ngồi xuống chỗ ngồi đã được dọn ở bóng mát phía sau tịnh xá. ",
  "dn6:5.1": "Bấy giờ, các sứ giả Bà-la-môn của xứ Kosala và các sứ giả Bà-la-môn của xứ Magadha đi đến chỗ Thế Tôn; sau khi đến, họ chào hỏi thân thiện với Thế Tôn. ",
  "dn6:5.2": "Sau khi nói lên những lời chào hỏi thân tình và đáng ghi nhớ, họ ngồi xuống một bên. ",
  "dn6:5.3": "Oṭṭhaddha người Licchavi cũng cùng với một hội chúng Licchavi đông đảo đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, Oṭṭhaddha người Licchavi bạch Thế Tôn như sau: “Bạch Thế Tôn, những ngày trước đây, Sunakkhatta, con trai người Licchavi, đã đi đến chỗ con; sau khi đến, ông ấy nói với con như sau: ",
  "dn6:5.4": "‘Này Mahāli, từ khi tôi sống nương tựa Thế Tôn, chưa bao lâu, mới ba năm, tôi thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm, nhưng tôi không nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm.’ ",
  "dn6:5.5": "Bạch Thế Tôn, có phải Sunakkhatta, con trai người Licchavi, thật sự không nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, hay là không có những âm thanh ấy?” ",
  "dn6:5.6.0": "2.1. Định được tu tập một phần ",
  "dn6:5.7": "“Này Mahāli, Sunakkhatta, con trai người Licchavi, thật sự không nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, chứ không phải là không có.” ",
  "dn6:6.1": "“Bạch Thế Tôn, do nhân gì, do duyên gì mà Sunakkhatta, con trai người Licchavi, thật sự không nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, chứ không phải là không có?” ",
  "dn6:6.2": "“Này Mahāli, ở đây một vị tỳ-kheo có định được tu tập một phần theo phương đông để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm, nhưng không phải để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:6.3": "Vị ấy, trong định được tu tập một phần theo phương đông để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm, nhưng không phải để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, ",
  "dn6:6.4": "thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm ở phương đông, nhưng không nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:6.5": "Vì sao vậy? ",
  "dn6:6.6": "Này Mahāli, là như vậy đó đối với vị tỳ-kheo có định được tu tập một phần theo phương đông để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm, nhưng không phải để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:7.1": "Lại nữa, này Mahāli, vị tỳ-kheo có định được tu tập một phần theo phương nam … ",
  "dn6:7.2": "theo phương tây … ",
  "dn6:7.3": "theo phương bắc … ",
  "dn6:7.4": "theo trên, dưới và ngang, có định được tu tập một phần để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm, nhưng không phải để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:7.5": "Vị ấy, trong định được tu tập một phần theo trên, dưới và ngang để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm, nhưng không phải để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, ",
  "dn6:7.6": "thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm theo trên, dưới và ngang, nhưng không nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:7.7": "Vì sao vậy? ",
  "dn6:7.8": "Này Mahāli, là như vậy đó đối với vị tỳ-kheo có định được tu tập một phần theo trên, dưới và ngang để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm, nhưng không phải để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:8.1": "Này Mahāli, ở đây một vị tỳ-kheo có định được tu tập một phần theo phương đông để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, nhưng không phải để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:8.2": "Vị ấy, trong định được tu tập một phần theo phương đông để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, nhưng không phải để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm, ",
  "dn6:8.3": "nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm ở phương đông, nhưng không thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:8.4": "Vì sao vậy? ",
  "dn6:8.5": "Này Mahāli, là như vậy đó đối với vị tỳ-kheo có định được tu tập một phần theo phương đông để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, nhưng không phải để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:9.1": "Lại nữa, này Mahāli, vị tỳ-kheo có định được tu tập một phần theo phương nam … ",
  "dn6:9.2": "theo phương tây … ",
  "dn6:9.3": "theo phương bắc … ",
  "dn6:9.4": "theo trên, dưới và ngang, có định được tu tập một phần để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, nhưng không phải để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:9.5": "Vị ấy, trong định được tu tập một phần theo trên, dưới và ngang để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, nhưng không phải để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm, ",
  "dn6:9.6": "nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm theo trên, dưới và ngang, nhưng không thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:9.7": "Vì sao vậy? ",
  "dn6:9.8": "Này Mahāli, là như vậy đó đối với vị tỳ-kheo có định được tu tập một phần theo trên, dưới và ngang để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, nhưng không phải để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:10.1": "Này Mahāli, ở đây một vị tỳ-kheo có định được tu tập cả hai phần theo phương đông để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm và để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:10.2": "Vị ấy, trong định được tu tập cả hai phần theo phương đông để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm và để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, ",
  "dn6:10.3": "thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm và nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm ở phương đông. ",
  "dn6:10.4": "Vì sao vậy? ",
  "dn6:10.5": "Này Mahāli, là như vậy đó đối với vị tỳ-kheo có định được tu tập cả hai phần theo phương đông để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm và để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:11.1": "Lại nữa, này Mahāli, vị tỳ-kheo có định được tu tập cả hai phần theo phương nam … ",
  "dn6:11.2": "theo phương tây … ",
  "dn6:11.3": "theo phương bắc … ",
  "dn6:11.4": "theo trên, dưới và ngang, có định được tu tập cả hai phần để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm và để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:11.5": "Vị ấy, trong định được tu tập cả hai phần theo trên, dưới và ngang để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm và để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, ",
  "dn6:11.6": "thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm và nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm theo trên, dưới và ngang. ",
  "dn6:11.7": "Vì sao vậy? ",
  "dn6:11.8": "Này Mahāli, là như vậy đó đối với vị tỳ-kheo có định được tu tập cả hai phần theo trên, dưới và ngang để thấy các sắc trời khả ái, liên hệ đến dục, đáng say đắm và để nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm. ",
  "dn6:11.9": "Này Mahāli, đây là nhân, đây là duyên khiến Sunakkhatta, con trai người Licchavi, thật sự không nghe các âm thanh trời khả ái, liên hệ đến dục, đáng say đắm, chứ không phải là không có.” ",
  "dn6:12.1": "“Bạch Thế Tôn, chắc hẳn các vị tỳ-kheo sống phạm hạnh với Thế Tôn là vì mục đích chứng đạt những sự tu tập định này?” ",
  "dn6:12.2": "“Không phải vậy, này Mahāli, các vị tỳ-kheo sống phạm hạnh với Ta không phải vì mục đích chứng đạt những sự tu tập định này. ",
  "dn6:12.3": "Này Mahāli, còn có những pháp khác cao thượng hơn và vi diệu hơn, vì mục đích chứng đạt những pháp ấy mà các vị tỳ-kheo sống phạm hạnh với Ta.” ",
  "dn6:13.0": "2.2. Bốn quả Thánh ",
  "dn6:13.1": "“Bạch Thế Tôn, những pháp nào là cao thượng hơn và vi diệu hơn, vì mục đích chứng đạt những pháp ấy mà các vị tỳ-kheo sống phạm hạnh với Thế Tôn?” ",
  "dn6:13.2": "“Này Mahāli, ở đây vị tỳ-kheo do đoạn tận ba kiết sử mà trở thành bậc nhập lưu, không còn bị đọa lạc, chắc chắn hướng đến giác ngộ. ",
  "dn6:13.3": "Này Mahāli, đây cũng là một pháp cao thượng hơn và vi diệu hơn, vì mục đích chứng đạt pháp này mà các vị tỳ-kheo sống phạm hạnh với Ta. ",
  "dn6:13.4": "Lại nữa, này Mahāli, vị tỳ-kheo do đoạn tận ba kiết sử, và do tham, sân, si được làm cho mỏng nhẹ, trở thành bậc nhất lai, chỉ còn trở lại thế gian này một lần nữa rồi chấm dứt khổ đau. ",
  "dn6:13.5": "Này Mahāli, đây cũng là một pháp cao thượng hơn và vi diệu hơn, vì mục đích chứng đạt pháp này mà các vị tỳ-kheo sống phạm hạnh với Ta. ",
  "dn6:13.6": "Lại nữa, này Mahāli, vị tỳ-kheo do đoạn tận năm hạ phần kiết sử mà hóa sinh, tại đó nhập Niết-bàn, không còn trở lui thế giới này nữa. ",
  "dn6:13.7": "Này Mahāli, đây cũng là một pháp cao thượng hơn và vi diệu hơn, vì mục đích chứng đạt pháp này mà các vị tỳ-kheo sống phạm hạnh với Ta. ",
  "dn6:13.8": "Lại nữa, này Mahāli, vị tỳ-kheo do đoạn tận các lậu hoặc mà ngay trong hiện tại tự mình với thắng trí chứng ngộ, chứng đạt và an trú trong tâm giải thoát không lậu, tuệ giải thoát. ",
  "dn6:13.9": "Này Mahāli, đây cũng là một pháp cao thượng hơn và vi diệu hơn, vì mục đích chứng đạt pháp này mà các vị tỳ-kheo sống phạm hạnh với Ta. ",
  "dn6:13.10": "Này Mahāli, đó là những pháp cao thượng hơn và vi diệu hơn, vì mục đích chứng đạt những pháp ấy mà các vị tỳ-kheo sống phạm hạnh với Ta.” ",
  "dn6:14.0": "2.3. Thánh đạo tám ngành ",
  "dn6:14.1": "“Bạch Thế Tôn, có con đường, có pháp hành nào để chứng ngộ các pháp ấy chăng?” ",
  "dn6:14.2": "“Này Mahāli, có con đường, có pháp hành để chứng ngộ các pháp ấy.” ",
  "dn6:14.3": "“Bạch Thế Tôn, con đường nào, pháp hành nào để chứng ngộ các pháp ấy?” ",
  "dn6:14.4": "“Chính là Thánh đạo tám ngành này. ",
  "dn6:14.5": "Tức là: chánh kiến, chánh tư duy, chánh ngữ, chánh nghiệp, chánh mạng, chánh tinh tấn, chánh niệm, chánh định. ",
  "dn6:14.6": "Này Mahāli, đây là con đường, đây là pháp hành để chứng ngộ các pháp ấy. ",
  "dn6:15.0": "2.4. Câu chuyện về hai vị xuất gia ",
  "dn6:15.1": "Này Mahāli, một thời ta trú tại Kosambī, ở Ghositārāma. ",
  "dn6:15.2": "Rồi có hai vị xuất gia—",
  "dn6:15.3": "du sĩ Muṇḍiya và Jāli, đệ tử của Dārupattika, đi đến chỗ ta. Đến rồi, họ chào hỏi thân thiện với ta. ",
  "dn6:15.4": "Sau khi nói lên những lời chào hỏi thân tình đáng ghi nhớ, họ đứng sang một bên. Đứng sang một bên, hai vị xuất gia ấy nói với ta như sau: ",
  "dn6:15.5": "‘Này hiền giả Gotama, mạng sống và thân thể là một, hay mạng sống là một thứ còn thân thể là một thứ khác?’ ",
  "dn6:16.1": "‘Vậy này các hiền giả, hãy lắng nghe kỹ và khéo tác ý, ta sẽ nói.’ ",
  "dn6:16.2": "‘Thưa vâng, hiền giả,’ hai vị xuất gia ấy đáp lời ta. ",
  "dn6:16.3": "Ta nói như sau: ",
  "dn6:16.4": "‘Này các hiền giả, ở đây Như Lai xuất hiện ở đời, là bậc A-la-hán, Chánh Đẳng Giác… ",
  "dn6:16.5": "Như vậy, này các hiền giả, vị tỳ-kheo thành tựu giới. ",
  "dn6:16.6": "… ",
  "dn6:16.7": "Vị ấy chứng và an trú sơ thiền. ",
  "dn6:16.8": "Này các hiền giả, vị tỳ-kheo nào biết như vậy, thấy như vậy, có thích hợp chăng nếu nói rằng: ",
  "dn6:16.9": "‘Mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’?” ",
  "dn6:16.10": "Này các hiền giả, vị tỳ-kheo ấy biết như vậy, thấy như vậy, thì thích hợp nếu nói rằng: ",
  "dn6:16.11": "‘Mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’. ",
  "dn6:16.12": "Còn ta, này các hiền giả, ta biết như vậy, thấy như vậy. ",
  "dn6:16.13": "Nhưng ta không nói rằng: ",
  "dn6:16.14": "‘Mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’… ",
  "dn6:17.1": "nhị thiền… ",
  "dn6:17.2": "tam thiền… ",
  "dn6:17.3": "vị ấy chứng và an trú tứ thiền. ",
  "dn6:17.4": "Này các hiền giả, vị tỳ-kheo nào biết như vậy, thấy như vậy, có thích hợp chăng nếu nói rằng: ",
  "dn6:17.5": "‘Mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’?” ",
  "dn6:17.6": "Này các hiền giả, vị tỳ-kheo ấy biết như vậy, thấy như vậy, thì thích hợp nếu nói rằng: ",
  "dn6:17.7": "‘Mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’. ",
  "dn6:17.8": "Còn ta, này các hiền giả, ta biết như vậy, thấy như vậy. ",
  "dn6:17.9": "Nhưng ta không nói rằng: ",
  "dn6:17.10": "‘Mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’… ",
  "dn6:18.1": "vị ấy hướng tâm, nghiêng tâm đến trí và kiến… ",
  "dn6:18.2": "Này các hiền giả, vị tỳ-kheo nào biết như vậy, thấy như vậy, có thích hợp chăng nếu nói rằng: ",
  "dn6:18.3": "‘Mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’?” ",
  "dn6:18.4": "… ",
  "dn6:18.5": "Này các hiền giả, vị tỳ-kheo ấy biết như vậy, thấy như vậy, thì thích hợp nếu nói rằng: ",
  "dn6:18.6": "‘Mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’. ",
  "dn6:18.7": "Còn ta, này các hiền giả, ta biết như vậy, thấy như vậy. ",
  "dn6:18.8": "Nhưng ta không nói rằng: ",
  "dn6:18.9": "‘Mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’. … ",
  "dn6:19.1": "Vị ấy biết rằng: ‘Không còn trở lui trạng thái này nữa.’ ",
  "dn6:19.2": "Này các hiền giả, vị tỳ-kheo nào biết như vậy, thấy như vậy, có thích hợp chăng nếu nói rằng: ",
  "dn6:19.3": "‘Mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’?” ",
  "dn6:19.4": "Này các hiền giả, vị tỳ-kheo ấy biết như vậy, thấy như vậy, thì không thích hợp nếu nói rằng: ",
  "dn6:19.5": "‘Mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’. ",
  "dn6:19.6": "Còn ta, này các hiền giả, ta biết như vậy, thấy như vậy. ",
  "dn6:19.7": "Nhưng ta không nói rằng: ",
  "dn6:19.8": "‘Mạng sống và thân thể là một’, hay ‘mạng sống là một thứ, thân thể là một thứ khác’.” ",
  "dn6:19.9": "Thế Tôn đã nói như vậy. ",
  "dn6:19.10": "Licchavī Oṭṭhaddha hoan hỷ, tán thán lời dạy của Thế Tôn. ",
  "dn6:19.11": "Kinh Mahāli thứ sáu chấm dứt. "
}
window.BILARA["dn06"]["vi"]["dn06:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
