window.BILARA = window.BILARA || {};
window.BILARA["dn12"] = window.BILARA["dn12"] || {};
window.BILARA["dn12"]["vi"] = {
  "dn12:0.1": "Trường Bộ Kinh 12 ",
  "dn12:0.2": "Kinh Lohicca ",
  "dn12:1.1": "Tôi nghe như vầy—",
  "dn12:1.2": "Một thời, Thế Tôn du hành trong xứ Kosala cùng với đại chúng Tỳ-kheo gồm khoảng năm trăm vị, và đã đến Sālavatikā. ",
  "dn12:1.3": "Lúc bấy giờ, bà-la-môn Lohicca cư trú tại Sālavatikā, một nơi phồn thịnh, cỏ cây, củi và nước đầy đủ, lúa thóc sung túc, là đất vua ban, tài sản của hoàng gia, được vua Pasenadi nước Kosala ban cho làm lãnh địa bà-la-môn. ",
  "dn12:2.1": "Lúc ấy, nơi bà-la-môn Lohicca khởi lên ác kiến như sau: ",
  "dn12:2.2": "“Ở đời, nếu một sa-môn hay bà-la-môn chứng đạt thiện pháp, sau khi chứng đạt thiện pháp ấy, không nên nói cho người khác biết; người này có thể làm gì cho người kia chứ? ",
  "dn12:2.3": "Ví như chặt đứt một xiềng xích cũ rồi lại làm một xiềng xích mới; ",
  "dn12:2.4": "cũng vậy, tôi nói sự thành tựu ấy là một pháp tham ác; người này có thể làm gì cho người kia chứ?” ",
  "dn12:3.1": "Bà-la-môn Lohicca nghe rằng: ",
  "dn12:3.2": "“Sa-môn Gotama, con trai dòng họ Sakya, xuất gia từ dòng họ Sakya, đang du hành trong xứ Kosala cùng với đại chúng Tỳ-kheo gồm khoảng năm trăm vị, đã đến Sālavatikā. ",
  "dn12:3.3": "Tiếng tốt đẹp này được truyền tụng về Tôn giả Gotama như sau: ",
  "dn12:3.4": "‘Thế Tôn ấy là bậc A-la-hán, Chánh Đẳng Giác, đầy đủ minh và hạnh, Thiện Thệ, bậc hiểu biết thế gian, bậc vô thượng điều ngự trượng phu, thầy của chư thiên và loài người, là Phật, là Thế Tôn’. ",
  "dn12:3.5": "Ngài tự mình chứng ngộ với thắng trí rồi tuyên thuyết thế giới này cùng với chư thiên, Ma, Phạm thiên, cùng quần chúng sa-môn, bà-la-môn, chư thiên và loài người. ",
  "dn12:3.6": "Ngài thuyết pháp sơ thiện, trung thiện, hậu thiện, có nghĩa, có văn, trình bày đời sống phạm hạnh hoàn toàn đầy đủ, thanh tịnh. ",
  "dn12:3.7": "Thật là tốt lành khi được gặp những bậc A-la-hán như vậy.” ",
  "dn12:4.1": "Rồi bà-la-môn Lohicca gọi người thợ cạo Rosika: ",
  "dn12:4.2": "“Này Rosika, hãy đi đến chỗ sa-môn Gotama; đến rồi, nhân danh ta mà thăm hỏi sa-môn Gotama có ít bệnh, ít não, khinh an, có sức khỏe, sống an lạc chăng: ",
  "dn12:4.3": "‘Bà-la-môn Lohicca kính hỏi Tôn giả Gotama có ít bệnh, ít não, khinh an, có sức khỏe, sống an lạc chăng’; ",
  "dn12:4.4": "và hãy nói như vầy—",
  "dn12:4.5": "xin Tôn giả Gotama nhận lời thọ thực ngày mai tại nhà bà-la-môn Lohicca cùng với chúng Tỳ-kheo.” ",
  "dn12:5.1": "“Vâng, thưa ngài,” người thợ cạo Rosika đáp lời bà-la-môn Lohicca, rồi đi đến chỗ Thế Tôn; đến nơi, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Khi đã ngồi xuống một bên, người thợ cạo Rosika bạch Thế Tôn: ",
  "dn12:5.2": "“Bạch Thế Tôn, bà-la-môn Lohicca kính hỏi Thế Tôn có ít bệnh, ít não, khinh an, có sức khỏe, sống an lạc chăng; ",
  "dn12:5.3": "và còn nói rằng—",
  "dn12:5.4": "xin Thế Tôn nhận lời thọ thực ngày mai tại nhà bà-la-môn Lohicca cùng với chúng Tỳ-kheo.” ",
  "dn12:5.5": "Thế Tôn im lặng nhận lời. ",
  "dn12:6.1": "Rồi người thợ cạo Rosika, biết Thế Tôn đã nhận lời, liền từ chỗ ngồi đứng dậy, đảnh lễ Thế Tôn, đi nhiễu bên phải rồi đến chỗ bà-la-môn Lohicca; đến nơi, nói với bà-la-môn Lohicca rằng: ",
  "dn12:6.2": "“Tôi đã thưa với Thế Tôn ấy theo lời của ngài: ",
  "dn12:6.3": "‘Bạch Thế Tôn, bà-la-môn Lohicca kính hỏi Thế Tôn có ít bệnh, ít não, khinh an, có sức khỏe, sống an lạc chăng; ",
  "dn12:6.4": "và còn nói rằng—",
  "dn12:6.5": "xin Thế Tôn nhận lời thọ thực ngày mai tại nhà bà-la-môn Lohicca cùng với chúng Tỳ-kheo’. ",
  "dn12:6.6": "Và Thế Tôn ấy đã nhận lời.” ",
  "dn12:7.1": "Rồi bà-la-môn Lohicca, sau khi đêm ấy đã qua, cho chuẩn bị tại tư gia các món ăn cứng và mềm thượng vị, rồi gọi người thợ cạo Rosika: ",
  "dn12:7.2": "“Này Rosika, hãy đi đến chỗ sa-môn Gotama; đến rồi báo giờ cho sa-môn Gotama rằng—",
  "dn12:7.3": "‘Đã đến giờ, thưa Tôn giả Gotama, bữa ăn đã chuẩn bị xong.’” ",
  "dn12:7.4": "“Vâng, thưa ngài,” người thợ cạo Rosika đáp lời bà-la-môn Lohicca, rồi đi đến chỗ Thế Tôn; đến nơi, đảnh lễ Thế Tôn rồi đứng sang một bên. ",
  "dn12:7.5": "Đứng sang một bên, người thợ cạo Rosika báo giờ với Thế Tôn: ",
  "dn12:7.6": "“Bạch Thế Tôn, đã đến giờ, bữa ăn đã chuẩn bị xong.” ",
  "dn12:7.7": "Rồi Thế Tôn vào buổi sáng đắp y, mang bát và y, cùng với chúng Tỳ-kheo đi đến Sālavatikā. ",
  "dn12:8.1": "Lúc ấy, người thợ cạo Rosika đi theo sau lưng Thế Tôn. ",
  "dn12:8.2": "Rồi người thợ cạo Rosika bạch Thế Tôn: ",
  "dn12:8.3": "“Bạch Thế Tôn, bà-la-môn Lohicca có khởi lên ác kiến như sau: ",
  "dn12:8.4": "‘Ở đời, nếu một sa-môn hay bà-la-môn chứng đạt thiện pháp, sau khi chứng đạt thiện pháp ấy, không nên nói cho người khác biết—",
  "dn12:8.5": "người này có thể làm gì cho người kia chứ? ",
  "dn12:8.6": "Ví như chặt đứt một xiềng xích cũ rồi lại làm một xiềng xích mới; ",
  "dn12:8.7": "cũng vậy, tôi nói sự thành tựu ấy là một pháp tham ác—",
  "dn12:8.8": "người này có thể làm gì cho người kia chứ?’ ",
  "dn12:8.9": "Lành thay, bạch Thế Tôn, xin Thế Tôn khiến bà-la-môn Lohicca từ bỏ ác kiến ấy.” ",
  "dn12:8.10": "“Có thể lắm, này Rosika, có thể lắm, này Rosika.” ",
  "dn12:9.1": "Rồi Thế Tôn đi đến nhà của bà-la-môn Lohicca; đến nơi, ngồi xuống trên chỗ ngồi đã soạn sẵn. ",
  "dn12:9.2": "Bấy giờ, bà-la-môn Lohicca tự tay dâng cúng và làm cho chúng Tỳ-kheo có Đức Phật đứng đầu được thỏa mãn với các món ăn cứng và mềm thượng vị. ",
  "dn12:9.3.0": "1. Chất vấn bà-la-môn Lohicca ",
  "dn12:9.4": "Rồi bà-la-môn Lohicca, sau khi Thế Tôn dùng bữa xong, tay đã rời bát, lấy một ghế thấp khác rồi ngồi xuống một bên. ",
  "dn12:9.5": "Khi bà-la-môn Lohicca ngồi xuống một bên, Thế Tôn nói với ông: ",
  "dn12:9.6": "“Có thật chăng, này Lohicca, nơi ông đã khởi lên ác kiến như sau: ",
  "dn12:9.7": "‘Ở đời, nếu một sa-môn hay bà-la-môn chứng đạt thiện pháp, sau khi chứng đạt thiện pháp ấy, không nên nói cho người khác biết; người này có thể làm gì cho người kia chứ? ",
  "dn12:9.8": "Ví như chặt đứt một xiềng xích cũ rồi lại làm một xiềng xích mới; ",
  "dn12:9.9": "cũng vậy, tôi nói sự thành tựu ấy là một pháp tham ác; người này có thể làm gì cho người kia chứ?’” ",
  "dn12:9.10": "“Đúng vậy, thưa Tôn giả Gotama.” ",
  "dn12:10.1": "“Này Lohicca, ông nghĩ sao, ",
  "dn12:10.2": "chẳng phải ông đang cư trú tại Sālavatikā sao?” ",
  "dn12:10.3": "“Đúng vậy, thưa Tôn giả Gotama.” ",
  "dn12:10.4": "“Này Lohicca, nếu có người nói như vầy: ",
  "dn12:10.5": "‘Bà-la-môn Lohicca cư trú tại Sālavatikā. ",
  "dn12:10.6": "Mọi lợi tức và sản vật phát sinh ở Sālavatikā ấy, chỉ một mình bà-la-môn Lohicca hưởng dùng, không cho người khác’— ",
  "dn12:10.7": "người nói như vậy có gây chướng ngại cho những người sống nương vào ông ấy hay không?” ",
  "dn12:10.8": "“Có gây chướng ngại, thưa Tôn giả Gotama.” ",
  "dn12:10.9": "“Khi gây chướng ngại như vậy, người ấy là người thương tưởng lợi ích cho họ hay thương tưởng điều bất lợi cho họ?” ",
  "dn12:10.10": "“Thương tưởng điều bất lợi, thưa Tôn giả Gotama.” ",
  "dn12:10.11": "“Đối với người thương tưởng điều bất lợi, tâm từ đối với họ được an trú hay tâm như kẻ thù được an trú?” ",
  "dn12:10.12": "“Tâm như kẻ thù, thưa Tôn giả Gotama.” ",
  "dn12:10.13": "“Khi tâm như kẻ thù được an trú, đó là tà kiến hay chánh kiến?” ",
  "dn12:10.14": "“Là tà kiến, thưa Tôn giả Gotama.” ",
  "dn12:10.15": "“Này Lohicca, đối với người có tà kiến, ta nói một trong hai thú: ",
  "dn12:10.16": "địa ngục hoặc loài bàng sinh. ",
  "dn12:11.1": "Này Lohicca, ông nghĩ sao, ",
  "dn12:11.2": "chẳng phải vua Pasenadi nước Kosala đang cai trị xứ Kāsi-Kosala sao?” ",
  "dn12:11.3": "“Đúng vậy, thưa Tôn giả Gotama.” ",
  "dn12:11.4": "“Này Lohicca, nếu có người nói như vầy: ",
  "dn12:11.5": "‘Vua Pasenadi nước Kosala đang cai trị xứ Kāsi-Kosala; ",
  "dn12:11.6": "mọi lợi tức và sản vật phát sinh ở Kāsi-Kosala ấy, chỉ một mình vua Pasenadi nước Kosala hưởng dùng, không cho người khác’— ",
  "dn12:11.7": "người nói như vậy có gây chướng ngại cho những người sống nương vào vua Pasenadi nước Kosala, gồm cả ông và những người khác, hay không?” ",
  "dn12:11.8": "“Có gây chướng ngại, thưa Tôn giả Gotama.” ",
  "dn12:11.9": "“Khi gây chướng ngại như vậy, người ấy là người thương tưởng lợi ích cho họ hay thương tưởng điều bất lợi cho họ?” ",
  "dn12:11.10": "“Thương tưởng điều bất lợi, thưa Tôn giả Gotama.” ",
  "dn12:11.11": "“Đối với người thương tưởng điều bất lợi, tâm từ đối với họ được an trú hay tâm như kẻ thù được an trú?” ",
  "dn12:11.12": "“Tâm như kẻ thù, thưa Tôn giả Gotama.” ",
  "dn12:11.13": "“Khi tâm như kẻ thù được an trú, đó là tà kiến hay chánh kiến?” ",
  "dn12:11.14": "“Là tà kiến, thưa Tôn giả Gotama.” ",
  "dn12:11.15": "“Này Lohicca, đối với người có tà kiến, ta nói một trong hai thú: ",
  "dn12:11.16": "địa ngục hoặc loài bàng sinh. ",
  "dn12:12.1": "Vậy nên, này Lohicca, nếu có người nói như vầy: ",
  "dn12:12.2": "‘Bà-la-môn Lohicca cư trú tại Sālavatikā; ",
  "dn12:12.3": "mọi lợi tức và sản vật phát sinh ở Sālavatikā ấy, chỉ một mình bà-la-môn Lohicca hưởng dùng, không cho người khác’— ",
  "dn12:13.1": "người nói như vậy gây chướng ngại cho những người sống nương vào ông ấy. ",
  "dn12:13.2": "Khi gây chướng ngại, người ấy là người thương tưởng điều bất lợi; đối với người thương tưởng điều bất lợi, tâm như kẻ thù được an trú; khi tâm như kẻ thù được an trú thì là tà kiến. ",
  "dn12:13.3": "Cũng vậy, này Lohicca, nếu có người nói như vầy: ",
  "dn12:13.4": "‘Ở đời, nếu một sa-môn hay bà-la-môn chứng đạt thiện pháp, sau khi chứng đạt thiện pháp ấy, không nên nói cho người khác biết; người này có thể làm gì cho người kia chứ? ",
  "dn12:13.5": "Ví như chặt đứt một xiềng xích cũ rồi lại làm một xiềng xích mới … ",
  "dn12:13.6": "người này có thể làm gì cho người kia chứ?’ ",
  "dn12:13.7": "Nói như vậy, người ấy trở thành kẻ gây chướng ngại cho những thiện nam tử nương theo pháp và luật do Như Lai thuyết giảng mà chứng đạt sự thù thắng cao quý như vậy, chứng ngộ cả quả Dự lưu, chứng ngộ cả quả Nhất lai, chứng ngộ cả quả Bất lai, chứng ngộ cả quả A-la-hán; và cả những vị đang làm chín muồi thai tạng chư thiên để tái sinh vào các cõi trời. Là kẻ gây chướng ngại, người ấy là kẻ thương tưởng điều bất lợi; kẻ thương tưởng điều bất lợi thì tâm như đối với kẻ thù hiện khởi; khi tâm như đối với kẻ thù hiện khởi thì có tà kiến. ",
  "dn12:13.8": "Này Lohicca, đối với người có tà kiến, ta nói đến một trong hai thú—",
  "dn12:13.9": "địa ngục hoặc loài bàng sinh. ",
  "dn12:14.1": "Ví như, này Lohicca, có người nói rằng: ",
  "dn12:14.2": "‘Vua Pasenadi nước Kosala cai trị xứ Kāsi-Kosala; ",
  "dn12:14.3": "mọi sản vật phát sinh trong xứ Kāsi-Kosala ấy chỉ một mình vua Pasenadi nước Kosala được hưởng dùng, không nên cho người khác.’ ",
  "dn12:15.1": "Nói như vậy, người ấy trở thành kẻ gây chướng ngại cho những người sống nương vào vua Pasenadi nước Kosala, gồm cả ông và những người khác. ",
  "dn12:15.2": "Là kẻ gây chướng ngại, người ấy là kẻ thương tưởng điều bất lợi; kẻ thương tưởng điều bất lợi thì tâm như đối với kẻ thù hiện khởi; khi tâm như đối với kẻ thù hiện khởi thì có tà kiến. ",
  "dn12:15.3": "Cũng vậy, này Lohicca, nếu có người nói rằng: ",
  "dn12:15.4": "‘Ở đây, một sa-môn hay bà-la-môn chứng được thiện pháp; sau khi chứng được thiện pháp, vị ấy không nên nói cho người khác biết; người này có thể làm gì cho người kia chứ? ",
  "dn12:15.5": "Ví như... ",
  "dn12:15.6": "người này có thể làm gì cho người kia chứ?’ ",
  "dn12:15.7": "Nói như vậy, người ấy trở thành kẻ gây chướng ngại cho những thiện nam tử nương theo pháp và luật do Như Lai thuyết giảng mà chứng đạt sự thù thắng cao quý như vậy, chứng ngộ cả quả Dự lưu, chứng ngộ cả quả Nhất lai, chứng ngộ cả quả Bất lai, chứng ngộ cả quả A-la-hán. ",
  "dn12:15.8": "Và cả những vị đang làm chín muồi thai tạng chư thiên để tái sinh vào các cõi trời, người ấy trở thành kẻ gây chướng ngại cho họ, ",
  "dn12:15.9": "là kẻ gây chướng ngại, người ấy là kẻ thương tưởng điều bất lợi; kẻ thương tưởng điều bất lợi thì tâm như đối với kẻ thù hiện khởi; khi tâm như đối với kẻ thù hiện khởi thì có tà kiến. ",
  "dn12:15.10": "Này Lohicca, đối với người có tà kiến, ta nói đến một trong hai thú—",
  "dn12:15.11": "địa ngục hoặc loài bàng sinh. ",
  "dn12:16.0": "2. Ba hạng đạo sư đáng bị quở trách ",
  "dn12:16.1": "Này Lohicca, có ba hạng đạo sư ở đời đáng bị quở trách; ",
  "dn12:16.2": "và ai quở trách những hạng đạo sư như vậy thì sự quở trách ấy là đúng sự thật, chân thực, hợp pháp, không có lỗi. ",
  "dn12:16.3": "Ba hạng ấy là những hạng nào? ",
  "dn12:16.4": "Này Lohicca, ở đây có một vị đạo sư xuất gia từ gia đình sống không gia đình vì mục đích nào đó, nhưng mục đích sa-môn ấy của vị ấy chưa đạt được. ",
  "dn12:16.5": "Không đạt được mục đích sa-môn ấy, vị ấy lại thuyết pháp cho các đệ tử rằng: ",
  "dn12:16.6": "‘Điều này là vì lợi ích cho các ông, điều này là vì hạnh phúc cho các ông.’ ",
  "dn12:16.7": "Nhưng các đệ tử của vị ấy không lắng nghe, không chú tâm, không đặt tâm để hiểu biết, và còn làm trái lời dạy của bậc đạo sư. ",
  "dn12:16.8": "Vị ấy đáng bị quở trách như sau: ",
  "dn12:16.9": "‘Tôn giả xuất gia từ gia đình sống không gia đình vì mục đích nào đó, nhưng mục đích sa-môn ấy của ngài chưa đạt được; ngài chưa đạt được mục đích sa-môn ấy mà lại thuyết pháp cho các đệ tử rằng: ",
  "dn12:16.10": "“Điều này là vì lợi ích cho các ông, điều này là vì hạnh phúc cho các ông.” ",
  "dn12:16.11": "Thế mà các đệ tử của ngài không lắng nghe, không chú tâm, không đặt tâm để hiểu biết, và còn làm trái lời dạy của bậc đạo sư. ",
  "dn12:16.12": "Ví như người ta lại cố đẩy xuống một vật đang trượt xuống, hay ôm lấy một người đang quay mặt đi chỗ khác; ",
  "dn12:16.13": "cũng vậy, ta nói đây là một pháp tham ác xấu xa như thế—",
  "dn12:16.14": "người này có thể làm gì cho người kia chứ?’ ",
  "dn12:16.15": "Này Lohicca, đây là hạng đạo sư thứ nhất ở đời đáng bị quở trách; ",
  "dn12:16.16": "và ai quở trách hạng đạo sư như vậy thì sự quở trách ấy là đúng sự thật, chân thực, hợp pháp, không có lỗi. ",
  "dn12:17.1": "Lại nữa, này Lohicca, ở đây có một vị đạo sư xuất gia từ gia đình sống không gia đình vì mục đích nào đó, nhưng mục đích sa-môn ấy của vị ấy chưa đạt được. ",
  "dn12:17.2": "Không đạt được mục đích sa-môn ấy, vị ấy lại thuyết pháp cho các đệ tử rằng: ",
  "dn12:17.3": "‘Điều này là vì lợi ích cho các ông, điều này là vì hạnh phúc cho các ông.’ ",
  "dn12:17.4": "Các đệ tử của vị ấy lắng nghe, chú tâm, đặt tâm để hiểu biết, và không làm trái lời dạy của bậc đạo sư. ",
  "dn12:17.5": "Vị ấy đáng bị quở trách như sau: ",
  "dn12:17.6": "‘Tôn giả xuất gia từ gia đình sống không gia đình vì mục đích nào đó, nhưng mục đích sa-môn ấy của ngài chưa đạt được. Ngài chưa đạt được mục đích sa-môn ấy mà lại thuyết pháp cho các đệ tử rằng: ",
  "dn12:17.7": "“Điều này là vì lợi ích cho các ông, điều này là vì hạnh phúc cho các ông.” ",
  "dn12:17.8": "Các đệ tử của ngài lắng nghe, chú tâm, đặt tâm để hiểu biết, và không làm trái lời dạy của bậc đạo sư. ",
  "dn12:17.9": "Ví như người ta bỏ ruộng của mình mà lại cho rằng nên làm cỏ ruộng người khác; cũng vậy, ta nói đây là một pháp tham ác xấu xa như thế—người này có thể làm gì cho người kia chứ?’ ",
  "dn12:17.10": "Này Lohicca, đây là hạng đạo sư thứ hai ở đời đáng bị quở trách; ",
  "dn12:17.11": "và ai quở trách hạng đạo sư như vậy thì sự quở trách ấy là đúng sự thật, chân thực, hợp pháp, không có lỗi. ",
  "dn12:18.1": "Lại nữa, này Lohicca, ở đây có một vị đạo sư xuất gia từ gia đình sống không gia đình vì mục đích nào đó, và mục đích sa-môn ấy của vị ấy đã đạt được. ",
  "dn12:18.2": "Sau khi đạt được mục đích sa-môn ấy, vị ấy thuyết pháp cho các đệ tử rằng: ",
  "dn12:18.3": "‘Điều này là vì lợi ích cho các ông, điều này là vì hạnh phúc cho các ông.’ ",
  "dn12:18.4": "Nhưng các đệ tử của vị ấy không lắng nghe, không chú tâm, không đặt tâm để hiểu biết, và còn làm trái lời dạy của bậc đạo sư. ",
  "dn12:18.5": "Vị ấy đáng bị quở trách như sau: ",
  "dn12:18.6": "‘Tôn giả xuất gia từ gia đình sống không gia đình vì mục đích nào đó, và mục đích sa-môn ấy của ngài đã đạt được. ",
  "dn12:18.7": "Ngài đã đạt được mục đích sa-môn ấy mà lại thuyết pháp cho các đệ tử rằng: ",
  "dn12:18.8": "“Điều này là vì lợi ích cho các ông, điều này là vì hạnh phúc cho các ông.” ",
  "dn12:18.9": "Thế mà các đệ tử của ngài không lắng nghe, không chú tâm, không đặt tâm để hiểu biết, và còn làm trái lời dạy của bậc đạo sư. ",
  "dn12:18.10": "Ví như người ta chặt đứt xiềng xích cũ rồi lại làm một xiềng xích mới khác; ",
  "dn12:18.11": "cũng vậy, ta nói đây là một pháp tham ác xấu xa như thế: người này có thể làm gì cho người kia chứ?’ ",
  "dn12:18.12": "Này Lohicca, đây là hạng đạo sư thứ ba ở đời đáng bị quở trách; ",
  "dn12:18.13": "và ai quở trách hạng đạo sư như vậy thì sự quở trách ấy là đúng sự thật, chân thực, hợp pháp, không có lỗi. ",
  "dn12:18.14": "Này Lohicca, đó là ba hạng đạo sư ở đời đáng bị quở trách, ",
  "dn12:18.15": "và ai quở trách những hạng đạo sư như vậy thì sự quở trách ấy là đúng sự thật, chân thực, hợp pháp, không có lỗi.”",
  "dn12:19.0": "3. Hạng đạo sư không đáng bị quở trách ",
  "dn12:19.1": "Khi được nói vậy, bà-la-môn Lohicca bạch Thế Tôn rằng: ",
  "dn12:19.2": "“Thưa Tôn giả Gotama, có chăng một vị đạo sư nào ở đời không đáng bị quở trách?” ",
  "dn12:19.3": "“Này Lohicca, có một vị đạo sư ở đời không đáng bị quở trách.” ",
  "dn12:19.4": "“Thưa Tôn giả Gotama, vị đạo sư nào ở đời không đáng bị quở trách ấy là ai?” ",
  "dn12:20-55.1": "“Này Lohicca, ở đây Như Lai xuất hiện ở đời, là bậc A-la-hán, Chánh Đẳng Giác... ",
  "dn12:20-55.2": "Này Lohicca, như vậy vị tỳ-kheo thành tựu giới... ",
  "dn12:20-55.3": "chứng và an trú sơ thiền... ",
  "dn12:20-55.4": "Này Lohicca, nơi vị đạo sư nào mà đệ tử chứng đạt được sự thù thắng cao quý như vậy, thì vị đạo sư ấy là vị ở đời không đáng bị quở trách. ",
  "dn12:20-55.5": "Và ai quở trách một vị đạo sư như vậy thì sự quở trách ấy là không đúng sự thật, không chân thực, phi pháp, có lỗi. ",
  "dn12:56-62.1": "... ",
  "dn12:56-62.2": "nhị thiền... ",
  "dn12:56-62.3": "tam thiền... ",
  "dn12:56-62.4": "chứng và an trú tứ thiền. ",
  "dn12:56-62.5": "Này Lohicca, nơi vị đạo sư nào mà đệ tử chứng đạt được sự thù thắng cao quý như vậy, thì vị đạo sư ấy là vị ở đời không đáng bị quở trách; và ai quở trách một vị đạo sư như vậy thì sự quở trách ấy là không đúng sự thật, không chân thực, phi pháp, có lỗi. ",
  "dn12:63-77.1": "... ",
  "dn12:63-77.2": "vị ấy hướng tâm, dẫn tâm đến trí và kiến... ",
  "dn12:63-77.3": "Này Lohicca, nơi vị đạo sư nào mà đệ tử chứng đạt được sự thù thắng cao quý như vậy, thì vị đạo sư ấy là vị ở đời không đáng bị quở trách; và ai quở trách một vị đạo sư như vậy thì sự quở trách ấy là không đúng sự thật, không chân thực, phi pháp, có lỗi. ",
  "dn12:63-77.4": "... ",
  "dn12:63-77.5": "vị ấy biết rằng: ‘Không còn trở lui trạng thái này nữa.’ ",
  "dn12:63-77.6": "Này Lohicca, nơi vị đạo sư nào mà đệ tử chứng đạt được sự thù thắng cao quý như vậy, thì vị đạo sư ấy là vị ở đời không đáng bị quở trách; và ai quở trách một vị đạo sư như vậy thì sự quở trách ấy là không đúng sự thật, không chân thực, phi pháp, có lỗi.”",
  "dn12:78.1": "Khi được nói vậy, bà-la-môn Lohicca bạch Thế Tôn rằng: ",
  "dn12:78.2": "“Ví như, thưa Tôn giả Gotama, một người thấy người khác đang rơi xuống vực địa ngục, nắm tóc kéo lên và đặt đứng trên đất liền; ",
  "dn12:78.3": "cũng vậy, con đang rơi xuống vực địa ngục đã được Tôn giả Gotama kéo lên và đặt đứng trên đất liền. ",
  "dn12:78.4": "Thật vi diệu, thưa Tôn giả Gotama, thật vi diệu, thưa Tôn giả Gotama. ",
  "dn12:78.5": "Ví như dựng đứng lại vật bị úp xuống, mở ra vật bị che kín, chỉ đường cho người lạc lối, đem đèn vào trong bóng tối để những ai có mắt có thể thấy các sắc; cũng vậy, Chánh pháp đã được Tôn giả Gotama dùng nhiều phương cách trình bày sáng tỏ. ",
  "dn12:78.6": "Con xin quy y Tôn giả Gotama, quy y Pháp và quy y Tỳ-kheo Tăng. ",
  "dn12:78.7": "Xin Tôn giả Gotama nhận con làm cư sĩ tại gia từ nay cho đến mạng chung đã quy y.”",
  "dn12:78.8": "Kinh Lohicca thứ mười hai chấm dứt. "
}
window.BILARA["dn12"]["vi"]["dn12:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
