window.BILARA = window.BILARA || {};
window.BILARA["dn15"] = window.BILARA["dn15"] || {};
window.BILARA["dn15"]["vi"] ={
  "dn15:0.1": "Trường Bộ Kinh 15 ",
  "dn15:0.2": "Kinh Đại Duyên ",
  "dn15:1.0": "1. Duyên khởi ",
  "dn15:1.1": "Tôi nghe như vầy—",
  "dn15:1.2": "Một thời, Thế Tôn trú ở xứ Kuru, tại một thị trấn của người Kuru tên là Kammāsadhamma. ",
  "dn15:1.3": "Bấy giờ, Tôn giả Ānanda đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. Ngồi xuống một bên, Tôn giả Ānanda bạch Thế Tôn rằng: ",
  "dn15:1.4": "“Thật vi diệu, bạch Thế Tôn, thật hy hữu, bạch Thế Tôn. ",
  "dn15:1.5": "Duyên khởi này, bạch Thế Tôn, thật sâu xa và hiện ra là sâu xa, thế mà đối với con nó lại có vẻ như rõ ràng, dễ hiểu.”",
  "dn15:1.6": "“Chớ nói như vậy, này Ānanda, chớ nói như vậy, này Ānanda. ",
  "dn15:1.7": "Duyên khởi này, này Ānanda, thật sâu xa và hiện ra là sâu xa. ",
  "dn15:1.8": "Chính vì không thấu hiểu, không thể nhập pháp này mà chúng sinh này trở nên rối ren như cuộn chỉ, như búi dây thắt nút, như cỏ muñja và cỏ babbaja quấn chằng chịt, không vượt khỏi ác thú, khổ cảnh, đọa xứ, luân hồi. ",
  "dn15:2.1": "Này Ānanda, khi được hỏi: ‘Có già chết do duyên này chăng?’, thì phải đáp: ‘Có’. ",
  "dn15:2.2": "Nếu hỏi: ‘Già chết do duyên gì?’, thì phải đáp: ‘Già chết do duyên sinh’. ",
  "dn15:2.3": "Này Ānanda, khi được hỏi: ‘Có sinh do duyên này chăng?’, thì phải đáp: ‘Có’. ",
  "dn15:2.4": "Nếu hỏi: ‘Sinh do duyên gì?’, thì phải đáp: ‘Sinh do duyên hữu’. ",
  "dn15:2.5": "Này Ānanda, khi được hỏi: ‘Có hữu do duyên này chăng?’, thì phải đáp: ‘Có’. ",
  "dn15:2.6": "Nếu hỏi: ‘Hữu do duyên gì?’, thì phải đáp: ‘Hữu do duyên thủ’. ",
  "dn15:2.7": "Này Ānanda, khi được hỏi: ‘Có thủ do duyên này chăng?’, thì phải đáp: ‘Có’. ",
  "dn15:2.8": "Nếu hỏi: ‘Thủ do duyên gì?’, thì phải đáp: ‘Thủ do duyên ái’. ",
  "dn15:2.9": "Này Ānanda, khi được hỏi: ‘Có ái do duyên này chăng?’, thì phải đáp: ‘Có’. ",
  "dn15:2.10": "Nếu hỏi: ‘Ái do duyên gì?’, thì phải đáp: ‘Ái do duyên thọ’. ",
  "dn15:2.11": "Này Ānanda, khi được hỏi: ‘Có thọ do duyên này chăng?’, thì phải đáp: ‘Có’. ",
  "dn15:2.12": "Nếu hỏi: ‘Thọ do duyên gì?’, thì phải đáp: ‘Thọ do duyên xúc’. ",
  "dn15:2.13": "Này Ānanda, khi được hỏi: ‘Có xúc do duyên này chăng?’, thì phải đáp: ‘Có’. ",
  "dn15:2.14": "Nếu hỏi: ‘Xúc do duyên gì?’, thì phải đáp: ‘Xúc do duyên danh sắc’. ",
  "dn15:2.15": "Này Ānanda, khi được hỏi: ‘Có danh sắc do duyên này chăng?’, thì phải đáp: ‘Có’. ",
  "dn15:2.16": "Nếu hỏi: ‘Danh sắc do duyên gì?’, thì phải đáp: ‘Danh sắc do duyên thức’. ",
  "dn15:2.17": "Này Ānanda, khi được hỏi: ‘Có thức do duyên này chăng?’, thì phải đáp: ‘Có’. ",
  "dn15:2.18": "Nếu hỏi: ‘Thức do duyên gì?’, thì phải đáp: ‘Thức do duyên danh sắc’. ",
  "dn15:3.1": "Như vậy, này Ānanda, do danh sắc làm duyên nên có thức, do thức làm duyên nên có danh sắc, do danh sắc làm duyên nên có xúc, do xúc làm duyên nên có thọ, do thọ làm duyên nên có ái, do ái làm duyên nên có thủ, do thủ làm duyên nên có hữu, do hữu làm duyên nên có sinh, do sinh làm duyên nên có già chết, sầu, bi, khổ, ưu, não sinh khởi. ",
  "dn15:3.2": "Như vậy là sự tập khởi của toàn bộ khối khổ này. ",
  "dn15:4.1": "Câu nói: ‘Do sinh làm duyên nên có già chết’, này Ānanda, cần phải được hiểu theo cách này, tức là già chết do duyên sinh. ",
  "dn15:4.2": "Này Ānanda, nếu hoàn toàn không có sinh, không có sự sinh ra dưới bất cứ hình thức nào của bất cứ ai trong bất cứ cảnh giới nào, như là—",
  "dn15:4.3": "sự sinh ra của chư thiên trong cõi chư thiên, của các gandhabba trong loài gandhabba, của các dạ-xoa trong loài dạ-xoa, của các loài hữu tình trong loài hữu tình, của loài người trong loài người, của loài bốn chân trong loài bốn chân, của loài chim trong loài chim, của loài bò sát trong loài bò sát; này Ānanda, nếu không có sự sinh ra như vậy của các loài hữu tình ấy, thì khi sinh hoàn toàn không có, do sinh diệt, già chết có được nhận thấy chăng?”",
  "dn15:4.4": "“Thưa không, bạch Thế Tôn.”",
  "dn15:4.5": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện của già chết, tức là sinh. ",
  "dn15:5.1": "Câu nói: ‘Do hữu làm duyên nên có sinh’, này Ānanda, cần phải được hiểu theo cách này, tức là sinh do duyên hữu. ",
  "dn15:5.2": "Này Ānanda, nếu hoàn toàn không có hữu, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ cảnh giới nào, như là—",
  "dn15:5.3": "dục hữu, sắc hữu hay vô sắc hữu; nếu hoàn toàn không có hữu, do hữu diệt, sinh có được nhận thấy chăng?”",
  "dn15:5.4": "“Thưa không, bạch Thế Tôn.”",
  "dn15:5.5": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện của sinh, tức là hữu. ",
  "dn15:6.1": "Câu nói: ‘Do thủ làm duyên nên có hữu’, này Ānanda, cần phải được hiểu theo cách này, tức là hữu do duyên thủ. ",
  "dn15:6.2": "Này Ānanda, nếu hoàn toàn không có thủ, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ trường hợp nào, như là—",
  "dn15:6.3": "dục thủ, kiến thủ, giới cấm thủ hay ngã luận thủ; nếu hoàn toàn không có thủ, do thủ diệt, hữu có được nhận thấy chăng?”",
  "dn15:6.4": "“Thưa không, bạch Thế Tôn.”",
  "dn15:6.5": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện của hữu, tức là thủ. ",
  "dn15:7.1": "Câu nói: ‘Do ái làm duyên nên có thủ’, này Ānanda, cần phải được hiểu theo cách này, tức là thủ do duyên ái. ",
  "dn15:7.2": "Này Ānanda, nếu hoàn toàn không có ái, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ trường hợp nào, như là—",
  "dn15:7.3": "ái đối với sắc, ái đối với tiếng, ái đối với mùi, ái đối với vị, ái đối với xúc chạm, ái đối với các pháp; nếu hoàn toàn không có ái, do ái diệt, thủ có được nhận thấy chăng?”",
  "dn15:7.4": "“Thưa không, bạch Thế Tôn.”",
  "dn15:7.5": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện của thủ, tức là ái. ",
  "dn15:8.1": "Câu nói: ‘Do thọ làm duyên nên có ái’, này Ānanda, cần phải được hiểu theo cách này, tức là ái do duyên thọ. ",
  "dn15:8.2": "Này Ānanda, nếu hoàn toàn không có thọ, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ trường hợp nào, như là—",
  "dn15:8.3": "thọ do nhãn xúc sinh, thọ do nhĩ xúc sinh, thọ do tỷ xúc sinh, thọ do thiệt xúc sinh, thọ do thân xúc sinh, thọ do ý xúc sinh; nếu hoàn toàn không có thọ, do thọ diệt, ái có được nhận thấy chăng?”",
  "dn15:8.4": "“Thưa không, bạch Thế Tôn.”",
  "dn15:8.5": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện của ái, tức là thọ. ",
  "dn15:9.1": "Như vậy, này Ānanda, duyên thọ có ái, duyên ái có tìm cầu, duyên tìm cầu có đạt được, duyên đạt được có phân định, duyên phân định có dục tham, duyên dục tham có chấp trước, duyên chấp trước có sở hữu, duyên sở hữu có xan tham, duyên xan tham có phòng hộ. ",
  "dn15:9.2": "Do phòng hộ làm nguyên nhân mà phát sinh cầm gậy, cầm khí giới, tranh cãi, xung đột, tranh chấp, cãi vã, nói xấu, nói dối, và nhiều pháp ác bất thiện khác. ",
  "dn15:10.1": "Câu nói: ‘Do phòng hộ làm nguyên nhân mà phát sinh cầm gậy, cầm khí giới, tranh cãi, xung đột, tranh chấp, cãi vã, nói xấu, nói dối, và nhiều pháp ác bất thiện khác’, này Ānanda, cần phải được hiểu theo cách này, tức là do phòng hộ làm nguyên nhân mà những pháp ấy phát sinh. ",
  "dn15:10.2": "Này Ānanda, nếu hoàn toàn không có phòng hộ, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ trường hợp nào, thì khi hoàn toàn không có phòng hộ, do phòng hộ diệt, cầm gậy, cầm khí giới, tranh cãi, xung đột, tranh chấp, cãi vã, nói xấu, nói dối, và nhiều pháp ác bất thiện khác có phát sinh chăng?”",
  "dn15:10.3": "“Thưa không, bạch Thế Tôn.”",
  "dn15:10.4": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện cho sự phát sinh của cầm gậy, cầm khí giới, tranh cãi, xung đột, tranh chấp, cãi vã, nói xấu, nói dối, và nhiều pháp ác bất thiện khác, tức là phòng hộ. ",
  "dn15:11.1": "Câu nói: ‘Duyên xan tham có phòng hộ’, này Ānanda, cần phải được hiểu theo cách này, tức là duyên xan tham có phòng hộ. ",
  "dn15:11.2": "Này Ānanda, nếu hoàn toàn không có xan tham, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ trường hợp nào, thì khi hoàn toàn không có xan tham, do xan tham diệt, phòng hộ có được nhận thấy chăng?”",
  "dn15:11.3": "“Thưa không, bạch Thế Tôn.”",
  "dn15:11.4": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện của phòng hộ, tức là xan tham. ",
  "dn15:12.1": "Câu nói: ‘Duyên sở hữu có xan tham’, này Ānanda, cần phải được hiểu theo cách này, tức là duyên sở hữu có xan tham. ",
  "dn15:12.2": "Này Ānanda, nếu hoàn toàn không có sở hữu, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ trường hợp nào, thì khi hoàn toàn không có sở hữu, do sở hữu diệt, xan tham có được nhận thấy chăng?”",
  "dn15:12.3": "“Thưa không, bạch Thế Tôn.”",
  "dn15:12.4": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện của xan tham, tức là sở hữu. ",
  "dn15:13.1": "Câu nói: ‘Duyên chấp trước có sở hữu’, này Ānanda, cần phải được hiểu theo cách này, tức là duyên chấp trước có sở hữu. ",
  "dn15:13.2": "Này Ānanda, nếu hoàn toàn không có chấp trước, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ trường hợp nào, thì khi hoàn toàn không có chấp trước, do chấp trước diệt, sở hữu có được nhận thấy chăng?”",
  "dn15:13.3": "“Thưa không, bạch Thế Tôn.”",
  "dn15:13.4": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện của sở hữu — tức là chấp trước. ",
  "dn15:14.1": "Câu nói: ‘Duyên dục tham có chấp trước’, này Ānanda, cần phải được hiểu theo cách này, tức là duyên dục tham có chấp trước. ",
  "dn15:14.2": "Này Ānanda, nếu hoàn toàn không có dục tham, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ trường hợp nào, thì khi hoàn toàn không có dục tham, do dục tham diệt, chấp trước có được nhận thấy chăng?”",
  "dn15:14.3": "“Thưa không, bạch Thế Tôn.”",
  "dn15:14.4": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện của chấp trước, tức là dục tham. ",
  "dn15:15.1": "Câu nói: ‘Duyên phân định có dục tham’, này Ānanda, cần phải được hiểu theo cách này, tức là duyên phân định có dục tham. ",
  "dn15:15.2": "Này Ānanda, nếu hoàn toàn không có phân định, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ trường hợp nào, thì khi hoàn toàn không có phân định, do phân định diệt, dục tham có được nhận thấy chăng?”",
  "dn15:15.3": "“Thưa không, bạch Thế Tôn.”",
  "dn15:15.4": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện của dục tham, tức là phân định. ",
  "dn15:16.1": "Câu nói: ‘Duyên đạt được có phân định’, này Ānanda, cần phải được hiểu theo cách này, tức là duyên đạt được có phân định. ",
  "dn15:16.2": "Này Ānanda, nếu hoàn toàn không có đạt được, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ trường hợp nào, thì khi hoàn toàn không có đạt được, do đạt được diệt, phân định có được nhận thấy chăng?”",
  "dn15:16.3": "“Thưa không, bạch Thế Tôn.”",
  "dn15:16.4": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện của phân định, tức là đạt được. ",
  "dn15:17.1": "Câu nói: ‘Duyên tìm cầu có đạt được’, này Ānanda, cần phải được hiểu theo cách này, tức là duyên tìm cầu có đạt được. ",
  "dn15:17.2": "Này Ānanda, nếu hoàn toàn không có tìm cầu, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ trường hợp nào, thì khi hoàn toàn không có tìm cầu, do tìm cầu diệt, đạt được có được nhận thấy chăng?”",
  "dn15:17.3": "“Thưa không, bạch Thế Tôn.”",
  "dn15:17.4": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện của đạt được, tức là tìm cầu. ",
  "dn15:18.1": "Câu nói: ‘Duyên ái có tìm cầu’, này Ānanda, cần phải được hiểu theo cách này, tức là duyên ái có tìm cầu. ",
  "dn15:18.2": "Này Ānanda, nếu hoàn toàn không có ái, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ trường hợp nào, như là—",
  "dn15:18.3": "dục ái, hữu ái, phi hữu ái; nếu hoàn toàn không có ái, do ái diệt, tìm cầu có được nhận thấy chăng?”",
  "dn15:18.4": "“Thưa không, bạch Thế Tôn.”",
  "dn15:18.5": "“Vậy nên, này Ānanda, chính đây là nhân, là duyên, là sự tập khởi, là điều kiện của tìm cầu, tức là ái. ",
  "dn15:18.6": "Như vậy, này Ānanda, hai pháp này cùng hội tụ trong thọ theo từng cặp. ",
  "dn15:19.1": "Câu nói: ‘Do xúc làm duyên nên có thọ’, này Ānanda, cần phải được hiểu theo cách này, tức là thọ do duyên xúc. ",
  "dn15:19.2": "Này Ānanda, nếu hoàn toàn không có xúc, không có dưới bất cứ hình thức nào của bất cứ ai trong bất cứ trường hợp nào, như là—",
  "dn15:19.3": "nhãn xúc, nhĩ xúc, tỷ xúc, thiệt xúc, thân xúc, ý xúc; nếu hoàn toàn không có xúc, do xúc diệt, thọ có được nhận thấy chăng?”",
  "dn15:19.4": "“Thưa không, bạch Thế Tôn.”",
  "dn15:19.5": "“Vì vậy, này A-nan, đây chính là nhân, đây là duyên khởi, đây là sự sinh khởi, đây là điều kiện của thọ, tức là xúc.",
  "dn15:20.1": "‘Do danh sắc làm duyên nên có xúc’, này A-nan, điều này đã được nói như vậy, và điều ấy cũng cần được hiểu theo cách này, rằng do danh sắc làm duyên nên có xúc.",
  "dn15:20.2": "Này A-nan, bởi những phương diện nào, những dấu hiệu nào, những đặc tướng nào, những cách chỉ định nào mà danh thân được thiết lập; nếu những phương diện ấy, những dấu hiệu ấy, những đặc tướng ấy, những cách chỉ định ấy không có, thì nơi sắc thân có thể nhận ra xúc do ngôn thuyết chăng?”",
  "dn15:20.3": "“Thưa không, bạch Thế Tôn.”",
  "dn15:20.4": "“Này A-nan, bởi những phương diện nào, những dấu hiệu nào, những đặc tướng nào, những cách chỉ định nào mà sắc thân được thiết lập; nếu những phương diện ấy … những cách chỉ định ấy không có, thì nơi danh thân có thể nhận ra xúc do đối chạm chăng?”",
  "dn15:20.5": "“Thưa không, bạch Thế Tôn.”",
  "dn15:20.6": "“Này A-nan, bởi những phương diện nào … những cách chỉ định nào mà cả danh thân và sắc thân được thiết lập; nếu những phương diện ấy … những cách chỉ định ấy không có, thì có thể nhận ra xúc do ngôn thuyết hay xúc do đối chạm chăng?”",
  "dn15:20.7": "“Thưa không, bạch Thế Tôn.”",
  "dn15:20.8": "“Này A-nan, bởi những phương diện nào … những cách chỉ định nào mà danh sắc được thiết lập; nếu những phương diện ấy … những cách chỉ định ấy không có, thì có thể nhận ra xúc chăng?”",
  "dn15:20.9": "“Thưa không, bạch Thế Tôn.”",
  "dn15:20.10": "“Vì vậy, này A-nan, đây chính là nhân, đây là duyên khởi, đây là sự sinh khởi, đây là điều kiện của xúc, tức là danh sắc.",
  "dn15:21.1": "‘Do thức làm duyên nên có danh sắc’, này A-nan, điều này đã được nói như vậy, và điều ấy cũng cần được hiểu theo cách này, rằng do thức làm duyên nên có danh sắc.",
  "dn15:21.2": "Này A-nan, nếu thức không đi vào trong thai mẹ, thì danh sắc có được hình thành trong thai mẹ chăng?”",
  "dn15:21.3": "“Thưa không, bạch Thế Tôn.”",
  "dn15:21.4": "“Này A-nan, nếu thức đã đi vào thai mẹ rồi lại rời đi, thì danh sắc có được sinh khởi thành trạng thái hiện hữu này chăng?”",
  "dn15:21.5": "“Thưa không, bạch Thế Tôn.”",
  "dn15:21.6": "“Này A-nan, nếu thức của một bé trai hay bé gái còn nhỏ bị đoạn diệt, thì danh sắc có đạt đến tăng trưởng, phát triển, lớn mạnh chăng?”",
  "dn15:21.7": "“Thưa không, bạch Thế Tôn.”",
  "dn15:21.8": "“Vì vậy, này A-nan, đây chính là nhân, đây là duyên khởi, đây là sự sinh khởi, đây là điều kiện của danh sắc — tức là thức.",
  "dn15:22.1": "‘Do danh sắc làm duyên nên có thức’, này A-nan, điều này đã được nói như vậy, và điều ấy cũng cần được hiểu theo cách này, rằng do danh sắc làm duyên nên có thức.",
  "dn15:22.2": "Này A-nan, nếu thức không có chỗ đứng trong danh sắc, thì trong tương lai có thể nhận ra sự phát sinh của khổ là sinh, già, chết chăng?”",
  "dn15:22.3": "“Thưa không, bạch Thế Tôn.”",
  "dn15:22.4": "“Vì vậy, này A-nan, đây chính là nhân, đây là duyên khởi, đây là sự sinh khởi, đây là điều kiện của thức, tức là danh sắc.",
  "dn15:22.5": "Đến mức này, này A-nan, là có thể sinh ra, già đi, chết đi, qua đời, hay tái sinh.",
  "dn15:22.6": "Đến mức này là phạm vi của ngôn ngữ, đến mức này là phạm vi của diễn đạt, đến mức này là phạm vi của khái niệm, đến mức này là phạm vi của trí tuệ, đến mức này vòng luân chuyển vận hành để chỉ bày trạng thái hiện hữu, tức là danh sắc cùng với thức vận hành trong sự làm duyên lẫn nhau.",
  "dn15:23.0": "2. Thiết lập tự ngã",
  "dn15:23.1": "Và đến mức nào, này A-nan, khi thiết lập tự ngã thì người ta thiết lập tự ngã?",
  "dn15:23.2": "Này A-nan, có người khi thiết lập tự ngã thì thiết lập tự ngã là có sắc, hữu hạn:",
  "dn15:23.3": "‘Tự ngã của tôi là có sắc, hữu hạn.’",
  "dn15:23.4": "Này A-nan, có người khi thiết lập tự ngã thì thiết lập tự ngã là có sắc, vô hạn:",
  "dn15:23.5": "‘Tự ngã của tôi là có sắc, vô hạn.’",
  "dn15:23.6": "Này A-nan, có người khi thiết lập tự ngã thì thiết lập tự ngã là vô sắc, hữu hạn:",
  "dn15:23.7": "‘Tự ngã của tôi là vô sắc, hữu hạn.’",
  "dn15:23.8": "Này A-nan, có người khi thiết lập tự ngã thì thiết lập tự ngã là vô sắc, vô hạn:",
  "dn15:23.9": "‘Tự ngã của tôi là vô sắc, vô hạn.’",
  "dn15:24.1": "Ở đây, này A-nan, có người thiết lập tự ngã là có sắc, hữu hạn.",
  "dn15:24.2": "Người ấy hoặc hiện nay thiết lập tự ngã là có sắc, hữu hạn, hoặc thiết lập tự ngã là có sắc, hữu hạn trong tương lai, hoặc lại nghĩ: ‘Dù hiện không như vậy, ta sẽ làm cho nó trở thành như vậy.’",
  "dn15:24.3": "Trong trường hợp như vậy, này A-nan, có thể nói rằng tùy miên kiến chấp về tự ngã có sắc, hữu hạn vẫn còn tiềm ẩn.",
  "dn15:24.4": "Ở đây, này A-nan, có người thiết lập tự ngã là có sắc, vô hạn.",
  "dn15:24.5": "Người ấy hoặc hiện nay thiết lập tự ngã là có sắc, vô hạn, hoặc thiết lập tự ngã là có sắc, vô hạn trong tương lai, hoặc lại nghĩ: ‘Dù hiện không như vậy, ta sẽ làm cho nó trở thành như vậy.’",
  "dn15:24.6": "Trong trường hợp như vậy, này A-nan, có thể nói rằng tùy miên kiến chấp về tự ngã có sắc, vô hạn vẫn còn tiềm ẩn.",
  "dn15:24.7": "Ở đây, này A-nan, có người thiết lập tự ngã là vô sắc, hữu hạn.",
  "dn15:24.8": "Người ấy hoặc hiện nay thiết lập tự ngã là vô sắc, hữu hạn, hoặc thiết lập tự ngã là vô sắc, hữu hạn trong tương lai, hoặc lại nghĩ: ‘Dù hiện không như vậy, ta sẽ làm cho nó trở thành như vậy.’",
  "dn15:24.9": "Trong trường hợp như vậy, này A-nan, có thể nói rằng tùy miên kiến chấp về tự ngã vô sắc, hữu hạn vẫn còn tiềm ẩn.",
  "dn15:24.10": "Ở đây, này A-nan, có người thiết lập tự ngã là vô sắc, vô hạn.",
  "dn15:24.11": "Người ấy hoặc hiện nay thiết lập tự ngã là vô sắc, vô hạn, hoặc thiết lập tự ngã là vô sắc, vô hạn trong tương lai, hoặc lại nghĩ: ‘Dù hiện không như vậy, ta sẽ làm cho nó trở thành như vậy.’",
  "dn15:24.12": "Trong trường hợp như vậy, này A-nan, có thể nói rằng tùy miên kiến chấp về tự ngã vô sắc, vô hạn vẫn còn tiềm ẩn.",
  "dn15:24.13": "Đến mức ấy, này A-nan, là khi thiết lập tự ngã thì người ta thiết lập tự ngã.",
  "dn15:25.0": "3. Không thiết lập tự ngã",
  "dn15:25.1": "Và đến mức nào, này A-nan, khi không thiết lập tự ngã thì người ta không thiết lập tự ngã?",
  "dn15:25.2": "Này A-nan, có người khi không thiết lập tự ngã thì không thiết lập tự ngã là có sắc, hữu hạn:",
  "dn15:25.3": "‘Tự ngã của tôi là có sắc, hữu hạn.’",
  "dn15:25.4": "Này A-nan, có người khi không thiết lập tự ngã thì không thiết lập tự ngã là có sắc, vô hạn:",
  "dn15:25.5": "‘Tự ngã của tôi là có sắc, vô hạn.’",
  "dn15:25.6": "Này A-nan, có người khi không thiết lập tự ngã thì không thiết lập tự ngã là vô sắc, hữu hạn:",
  "dn15:25.7": "‘Tự ngã của tôi là vô sắc, hữu hạn.’",
  "dn15:25.8": "Này A-nan, có người khi không thiết lập tự ngã thì không thiết lập tự ngã là vô sắc, vô hạn:",
  "dn15:25.9": "‘Tự ngã của tôi là vô sắc, vô hạn.’",
  "dn15:26.1": "Ở đây, này A-nan, có người không thiết lập tự ngã là có sắc, hữu hạn.",
  "dn15:26.2": "Người ấy hoặc hiện nay không thiết lập tự ngã là có sắc, hữu hạn, hoặc không thiết lập tự ngã là có sắc, hữu hạn trong tương lai, hoặc cũng không nghĩ: ‘Dù hiện không như vậy, ta sẽ làm cho nó trở thành như vậy.’",
  "dn15:26.3": "Trong trường hợp như vậy, này A-nan, có thể nói rằng tùy miên kiến chấp về tự ngã có sắc, hữu hạn không còn tiềm ẩn.",
  "dn15:26.4": "Ở đây, này A-nan, có người không thiết lập tự ngã là có sắc, vô hạn.",
  "dn15:26.5": "Người ấy hoặc hiện nay không thiết lập tự ngã là có sắc, vô hạn, hoặc không thiết lập tự ngã là có sắc, vô hạn trong tương lai, hoặc cũng không nghĩ: ‘Dù hiện không như vậy, ta sẽ làm cho nó trở thành như vậy.’",
  "dn15:26.6": "Trong trường hợp như vậy, này A-nan, có thể nói rằng tùy miên kiến chấp về tự ngã có sắc, vô hạn không còn tiềm ẩn.",
  "dn15:26.7": "Ở đây, này A-nan, có người không thiết lập tự ngã là vô sắc, hữu hạn.",
  "dn15:26.8": "Người ấy hoặc hiện nay không thiết lập tự ngã là vô sắc, hữu hạn, hoặc không thiết lập tự ngã là vô sắc, hữu hạn trong tương lai, hoặc cũng không nghĩ: ‘Dù hiện không như vậy, ta sẽ làm cho nó trở thành như vậy.’",
  "dn15:26.9": "Trong trường hợp như vậy, này A-nan, có thể nói rằng tùy miên kiến chấp về tự ngã vô sắc, hữu hạn không còn tiềm ẩn.",
  "dn15:26.10": "Ở đây, này A-nan, có người không thiết lập tự ngã là vô sắc, vô hạn.",
  "dn15:26.11": "Người ấy hoặc hiện nay không thiết lập tự ngã là vô sắc, vô hạn, hoặc không thiết lập tự ngã là vô sắc, vô hạn trong tương lai, hoặc cũng không nghĩ: ‘Dù hiện không như vậy, ta sẽ làm cho nó trở thành như vậy.’",
  "dn15:26.12": "Trong trường hợp như vậy, này A-nan, có thể nói rằng tùy miên kiến chấp về tự ngã vô sắc, vô hạn không còn tiềm ẩn.",
  "dn15:26.13": "Đến mức ấy, này A-nan, là khi không thiết lập tự ngã thì người ta không thiết lập tự ngã.",
  "dn15:27.0": "4. Quán sát tự ngã",
  "dn15:27.1": "Và đến mức nào, này A-nan, khi quán sát tự ngã thì người ta quán sát tự ngã?",
  "dn15:27.2": "Này A-nan, có người khi quán sát tự ngã thì quán sát tự ngã là thọ:",
  "dn15:27.3": "‘Thọ là tự ngã của tôi.’",
  "dn15:27.4": "Hoặc, này A-nan, có người khi quán sát tự ngã thì quán sát như sau: ‘Thọ không phải là tự ngã của tôi, tự ngã của tôi là không cảm thọ.’",
  "dn15:27.5": "Hoặc, này A-nan, có người khi quán sát tự ngã thì quán sát như sau: ‘Thọ không phải là tự ngã của tôi, nhưng tự ngã của tôi cũng không phải là không cảm thọ; tự ngã của tôi là cái cảm nhận, vì tự ngã của tôi có bản chất là cảm thọ.’",
  "dn15:28.1": "Ở đây, này A-nan, có người nói như sau:",
  "dn15:28.2": "‘Thọ là tự ngã của tôi’,",
  "dn15:28.3": "người ấy cần được nói như sau:",
  "dn15:28.4": "‘Này hiền giả, có ba loại thọ này —",
  "dn15:28.5": "lạc thọ, khổ thọ, và bất khổ bất lạc thọ.",
  "dn15:28.6": "Trong ba loại thọ ấy, ông quán loại nào là tự ngã?’",
  "dn15:28.7": "Này A-nan, vào lúc cảm thọ lạc, thì lúc ấy người ta không cảm thọ khổ, cũng không cảm thọ bất khổ bất lạc;",
  "dn15:28.8": "lúc ấy chỉ cảm thọ lạc mà thôi.",
  "dn15:28.9": "Này A-nan, vào lúc cảm thọ khổ, thì lúc ấy người ta không cảm thọ lạc, cũng không cảm thọ bất khổ bất lạc;",
  "dn15:28.10": "lúc ấy chỉ cảm thọ khổ mà thôi.",
  "dn15:28.11": "Này A-nan, vào lúc cảm thọ bất khổ bất lạc, thì lúc ấy người ta không cảm thọ lạc, cũng không cảm thọ khổ;",
  "dn15:28.12": "lúc ấy chỉ cảm thọ bất khổ bất lạc mà thôi.",
  "dn15:29.1": "Này A-nan, lạc thọ là vô thường, hữu vi, do duyên sinh, có bản chất hoại diệt, có bản chất tan rã, có bản chất ly tham, có bản chất đoạn diệt.",
  "dn15:29.2": "Này A-nan, khổ thọ là vô thường, hữu vi, do duyên sinh, có bản chất hoại diệt, có bản chất tan rã, có bản chất ly tham, có bản chất đoạn diệt.",
  "dn15:29.3": "Này A-nan, bất khổ bất lạc thọ là vô thường, hữu vi, do duyên sinh, có bản chất hoại diệt, có bản chất tan rã, có bản chất ly tham, có bản chất đoạn diệt.",
  "dn15:29.4": "Khi đang cảm thọ lạc, người ấy nghĩ: ‘Đây là tự ngã của tôi.’",
  "dn15:29.5": "Chính khi lạc thọ ấy diệt đi, người ấy nghĩ: ‘Tự ngã của tôi đã mất rồi.’",
  "dn15:29.6": "Khi đang cảm thọ khổ, người ấy nghĩ: ‘Đây là tự ngã của tôi.’",
  "dn15:29.7": "Chính khi khổ thọ ấy diệt đi, người ấy nghĩ: ‘Tự ngã của tôi đã mất rồi.’",
  "dn15:29.8": "Khi đang cảm thọ bất khổ bất lạc, người ấy nghĩ: ‘Đây là tự ngã của tôi.’",
  "dn15:29.9": "Chính khi bất khổ bất lạc thọ ấy diệt đi, người ấy nghĩ: ‘Tự ngã của tôi đã mất rồi.’",
  "dn15:29.10": "Như vậy, ngay trong hiện tại, người nói rằng: ‘Thọ là tự ngã của tôi’ là đang quán sát tự ngã như một cái gì vô thường, xen lẫn lạc khổ, có bản chất sinh và diệt.",
  "dn15:29.11": "Vì vậy, này A-nan, với điều này cũng không thích hợp để quán sát rằng: ‘Thọ là tự ngã của tôi.’",
  "dn15:30.1": "Ở đây, này A-nan, có người nói như vầy: ",
  "dn15:30.2": "‘Cảm thọ không phải là tự ngã của tôi, tự ngã của tôi là không cảm nhận’ thì nên nói với người ấy như sau: ",
  "dn15:30.3": "‘Nhưng này hiền hữu, ở nơi hoàn toàn không có bất cứ cảm thọ nào, liệu ở đó có thể có ý nghĩ “ta là cái này” chăng?’”",
  "dn15:30.4": "“Thưa không, bạch Thế Tôn.”",
  "dn15:30.5": "“Vậy nên, này A-nan, như thế cũng không thích hợp để quán xét rằng: ‘Cảm thọ không phải là tự ngã của tôi, tự ngã của tôi là không cảm nhận.’",
  "dn15:31.1": "Ở đây, này A-nan, có người nói như vầy: ",
  "dn15:31.2": "‘Cảm thọ không phải là tự ngã của tôi, nhưng tự ngã của tôi cũng không phải là không cảm nhận; tự ngã của tôi có cảm nhận, vì tự ngã của tôi có bản chất là cảm thọ.’",
  "dn15:31.3": "Nên nói với người ấy như sau—",
  "dn15:31.4": "‘Này hiền hữu, nếu các cảm thọ ấy hoàn toàn, toàn bộ, mọi mặt, không còn dư sót mà diệt tận,",
  "dn15:31.5": "khi hoàn toàn không có cảm thọ, do cảm thọ đã diệt, liệu ở đó có thể có ý nghĩ “ta là cái này” chăng?’”",
  "dn15:31.6": "“Thưa không, bạch Thế Tôn.”",
  "dn15:31.7": "“Vậy nên, này A-nan, như thế cũng không thích hợp để quán xét rằng: ‘Cảm thọ không phải là tự ngã của tôi, nhưng tự ngã của tôi cũng không phải là không cảm nhận; tự ngã của tôi có cảm nhận, vì tự ngã của tôi có bản chất là cảm thọ.’",
  "dn15:32.1": "Khi nào, này A-nan, vị tỳ-kheo không quán cảm thọ là tự ngã, cũng không quán cái không cảm nhận là tự ngã, cũng không quán rằng: ‘Tự ngã của tôi có cảm nhận, vì tự ngã của tôi có bản chất là cảm thọ’,",
  "dn15:32.2": "vị ấy do không quán như vậy nên không chấp thủ bất cứ gì ở đời,",
  "dn15:32.3": "không chấp thủ nên không dao động; không dao động nên tự mình hoàn toàn tịch diệt,",
  "dn15:32.4": "và biết rằng: ‘Sanh đã tận, phạm hạnh đã thành, việc cần làm đã làm xong, không còn trở lui trạng thái này nữa.’",
  "dn15:32.5": "Này A-nan, đối với vị tỳ-kheo tâm đã giải thoát như vậy, nếu có ai nói như vầy: ",
  "dn15:32.6": "‘Như Lai còn tồn tại sau khi chết’ là kiến chấp không thích đáng.",
  "dn15:32.7": "‘Như Lai không còn tồn tại sau khi chết’ là kiến chấp không thích đáng.",
  "dn15:32.8": "‘Như Lai vừa còn tồn tại vừa không còn tồn tại sau khi chết’ là kiến chấp không thích đáng.",
  "dn15:32.9": "‘Như Lai không còn tồn tại cũng không phải không còn tồn tại sau khi chết’ là kiến chấp không thích đáng.",
  "dn15:32.10": "Vì sao vậy?",
  "dn15:32.11": "Này A-nan, trong phạm vi nào có ngôn thuyết, trong phạm vi nào có con đường của ngôn thuyết; trong phạm vi nào có diễn đạt, trong phạm vi nào có con đường của diễn đạt; trong phạm vi nào có khái niệm, trong phạm vi nào có con đường của khái niệm; trong phạm vi nào có trí, trong phạm vi nào là cảnh giới của trí; trong phạm vi nào có luân chuyển, trong phạm vi nào còn xoay vần; vị tỳ-kheo đã giải thoát nhờ thắng tri đối với tất cả điều ấy. Nói rằng vị tỳ-kheo đã giải thoát như vậy là ‘không biết, không thấy’ là kiến chấp không thích đáng.”",
  "dn15:33.0": "5. Bảy trú xứ của thức",
  "dn15:33.1": "Này A-nan, có bảy trú xứ của thức và hai cảnh giới.",
  "dn15:33.2": "Bảy là những gì?",
  "dn15:33.3": "Này A-nan, có những chúng sanh thân sai khác, tưởng sai khác, như loài người, một số chư thiên, và một số chúng sanh ở đọa xứ.",
  "dn15:33.4": "Đây là trú xứ thứ nhất của thức.",
  "dn15:33.5": "Này A-nan, có những chúng sanh thân sai khác nhưng tưởng đồng nhất, như chư thiên Phạm chúng mới sanh lần đầu.",
  "dn15:33.6": "Đây là trú xứ thứ hai của thức.",
  "dn15:33.7": "Này A-nan, có những chúng sanh thân đồng nhất nhưng tưởng sai khác, như chư thiên Quang Âm.",
  "dn15:33.8": "Đây là trú xứ thứ ba của thức.",
  "dn15:33.9": "Này A-nan, có những chúng sanh thân đồng nhất và tưởng đồng nhất, như chư thiên Biến Tịnh.",
  "dn15:33.10": "Đây là trú xứ thứ tư của thức.",
  "dn15:33.11": "Này A-nan, có những chúng sanh do vượt qua hoàn toàn các tưởng về sắc, do sự biến mất của các tưởng về chướng ngại, do không tác ý đến các tưởng sai khác, nghĩ rằng: ‘Hư không là vô biên’, nên đạt đến Không vô biên xứ.",
  "dn15:33.12": "Đây là trú xứ thứ năm của thức.",
  "dn15:33.13": "Này A-nan, có những chúng sanh do vượt qua hoàn toàn Không vô biên xứ, nghĩ rằng: ‘Thức là vô biên’, nên đạt đến Thức vô biên xứ.",
  "dn15:33.14": "Đây là trú xứ thứ sáu của thức.",
  "dn15:33.15": "Này A-nan, có những chúng sanh do vượt qua hoàn toàn Thức vô biên xứ, nghĩ rằng: ‘Không có gì cả’, nên đạt đến Vô sở hữu xứ.",
  "dn15:33.16": "Đây là trú xứ thứ bảy của thức.",
  "dn15:33.17": "Cõi chúng sanh vô tưởng và Phi tưởng phi phi tưởng xứ là hai cảnh giới.",
  "dn15:34.1": "Ở đây, này A-nan, trú xứ thứ nhất của thức là những chúng sanh thân sai khác, tưởng sai khác, như loài người, một số chư thiên, và một số chúng sanh ở đọa xứ.",
  "dn15:34.2": "Này A-nan, ai biết rõ trú xứ ấy, biết rõ sự sanh khởi của nó, biết rõ sự đoạn diệt của nó, biết rõ vị ngọt của nó, biết rõ sự nguy hại của nó, biết rõ sự xuất ly khỏi nó, thì người ấy có thích thú nó chăng?”",
  "dn15:34.3": "“Thưa không, bạch Thế Tôn.” …",
  "dn15:34.4": "“Ở đây, này A-nan, đó là cõi chúng sanh vô tưởng.",
  "dn15:34.5": "Này A-nan, ai biết rõ cõi ấy, biết rõ sự sanh khởi của nó, biết rõ sự đoạn diệt của nó, biết rõ vị ngọt của nó, biết rõ sự nguy hại của nó, biết rõ sự xuất ly khỏi nó, thì người ấy có thích thú nó chăng?”",
  "dn15:34.6": "“Thưa không, bạch Thế Tôn.”",
  "dn15:34.7": "“Ở đây, này A-nan, đó là Phi tưởng phi phi tưởng xứ.",
  "dn15:34.8": "Này A-nan, ai biết rõ cõi ấy, biết rõ sự sanh khởi của nó, biết rõ sự đoạn diệt của nó, biết rõ vị ngọt của nó, biết rõ sự nguy hại của nó, biết rõ sự xuất ly khỏi nó, thì người ấy có thích thú nó chăng?”",
  "dn15:34.9": "“Thưa không, bạch Thế Tôn.”",
  "dn15:34.10": "“Khi nào, này A-nan, vị tỳ-kheo biết như thật sự sanh khởi, sự đoạn diệt, vị ngọt, sự nguy hại và sự xuất ly của bảy trú xứ của thức này và hai cảnh giới này, rồi nhờ không chấp thủ mà được giải thoát, thì vị ấy được gọi là tỳ-kheo giải thoát nhờ tuệ, này A-nan.",
  "dn15:35.0": "6. Tám giải thoát",
  "dn15:35.1": "Này A-nan, có tám giải thoát này.",
  "dn15:35.2": "Tám là những gì?",
  "dn15:35.3": "Có sắc, thấy các sắc,",
  "dn15:35.4": "đây là giải thoát thứ nhất.",
  "dn15:35.5": "Trong tự thân không có tưởng về sắc, thấy các sắc ở bên ngoài,",
  "dn15:35.6": "đây là giải thoát thứ hai.",
  "dn15:35.7": "Chỉ chuyên chú vào tịnh đẹp,",
  "dn15:35.8": "đây là giải thoát thứ ba.",
  "dn15:35.9": "Do vượt qua hoàn toàn các tưởng về sắc, do sự biến mất của các tưởng về chướng ngại, do không tác ý đến các tưởng sai khác, nghĩ rằng: ‘Hư không là vô biên’, vị ấy chứng và an trú Không vô biên xứ,",
  "dn15:35.10": "đây là giải thoát thứ tư.",
  "dn15:35.11": "Do vượt qua hoàn toàn Không vô biên xứ, nghĩ rằng: ‘Thức là vô biên’, vị ấy chứng và an trú Thức vô biên xứ,",
  "dn15:35.12": "đây là giải thoát thứ năm.",
  "dn15:35.13": "Do vượt qua hoàn toàn Thức vô biên xứ, nghĩ rằng: ‘Không có gì cả’, vị ấy chứng và an trú Vô sở hữu xứ,",
  "dn15:35.14": "đây là giải thoát thứ sáu.",
  "dn15:35.15": "Do vượt qua hoàn toàn Vô sở hữu xứ, vị ấy chứng và an trú Phi tưởng phi phi tưởng xứ,",
  "dn15:35.16": "đây là giải thoát thứ bảy.",
  "dn15:35.17": "Do vượt qua hoàn toàn Phi tưởng phi phi tưởng xứ, vị ấy chứng và an trú Diệt thọ tưởng,",
  "dn15:35.18": "đây là giải thoát thứ tám.",
  "dn15:35.19": "Này A-nan, đó là tám giải thoát.",
  "dn15:36.1": "Khi nào, này A-nan, vị tỳ-kheo nhập tám giải thoát này theo thuận, cũng nhập theo nghịch, cũng nhập theo cả thuận lẫn nghịch; tùy ý muốn ở đâu, muốn thế nào, muốn bao lâu thì nhập, cũng xuất khỏi,",
  "dn15:36.2": "và do đoạn tận các lậu hoặc, ngay trong hiện tại tự mình với thắng trí chứng ngộ và an trú vô lậu tâm giải thoát, tuệ giải thoát, thì vị ấy được gọi là tỳ-kheo giải thoát cả hai phần, này A-nan.",
  "dn15:36.3": "Và này A-nan, ngoài sự giải thoát cả hai phần này, không có sự giải thoát cả hai phần nào cao hơn hay thù thắng hơn.”",
  "dn15:36.4": "Thế Tôn đã nói như vậy.",
  "dn15:36.5": "Tôn giả A-nan hoan hỷ tín thọ lời Thế Tôn dạy.",
  "dn15:36.6": "Kinh Đại Duyên, phần thứ hai, chấm dứt."
}
window.BILARA["dn15"]["vi"]["dn15:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
