window.BILARA = window.BILARA || {};
window.BILARA["dn31"] = window.BILARA["dn31"] || {};
window.BILARA["dn31"]["vi"] = {
  "dn31:0.1": "Trường Bộ Kinh 31 ",
  "dn31:0.2": "Kinh Siṅgāla ",
  "dn31:1.1": "Tôi nghe như vầy—",
  "dn31:1.2": "Một thời, Thế Tôn ở Rājagaha, tại Trúc Lâm, chỗ nuôi sóc Kalandaka. ",
  "dn31:1.3": "Lúc bấy giờ, chàng Siṅgālaka, con một gia chủ, dậy thật sớm, ra khỏi Rājagaha, áo quần còn ướt, tóc còn ướt, chắp tay lễ bái các phương—",
  "dn31:1.4": "phương đông, phương nam, phương tây, phương bắc, phương dưới, phương trên. ",
  "dn31:2.1": "Rồi Thế Tôn vào buổi sáng, đắp y, mang bát và y, đi vào Rājagaha khất thực. ",
  "dn31:2.2": "Thế Tôn thấy chàng Siṅgālaka, con một gia chủ, dậy thật sớm, ra khỏi Rājagaha, áo quần còn ướt, tóc còn ướt, chắp tay lễ bái các phương—",
  "dn31:2.3": "phương đông, phương nam, phương tây, phương bắc, phương dưới, phương trên. ",
  "dn31:2.4": "Thấy vậy, Thế Tôn nói với chàng Siṅgālaka, con một gia chủ: ",
  "dn31:2.5": "“Này con gia chủ, vì sao con dậy thật sớm, ra khỏi Rājagaha, áo quần còn ướt, tóc còn ướt, chắp tay lễ bái các phương—",
  "dn31:2.6": "phương đông, phương nam, phương tây, phương bắc, phương dưới, phương trên?” ",
  "dn31:2.7": "“Bạch Thế Tôn, khi cha con sắp mất đã dặn con như vầy: ",
  "dn31:2.8": "‘Này con, hãy lễ bái các phương.’ ",
  "dn31:2.9": "Vì vậy, bạch Thế Tôn, kính trọng, tôn kính, quý mến và tưởng nhớ lời cha dặn, con dậy thật sớm, ra khỏi Rājagaha, áo quần còn ướt, tóc còn ướt, chắp tay lễ bái các phương—",
  "dn31:2.10": "phương đông, phương nam, phương tây, phương bắc, phương dưới, phương trên.” ",
  "dn31:2.11.0": "1. Sáu phương ",
  "dn31:2.12": "“Này con gia chủ, trong pháp luật của bậc thánh, không phải lễ bái sáu phương như vậy.” ",
  "dn31:2.13": "“Nhưng bạch Thế Tôn, trong pháp luật của bậc thánh thì phải lễ bái sáu phương như thế nào? ",
  "dn31:2.14": "Lành thay, bạch Thế Tôn, xin Thế Tôn giảng pháp cho con như vậy, để trong pháp luật của bậc thánh, người ta biết cách lễ bái sáu phương.” ",
  "dn31:2.15": "“Vậy thì, này con gia chủ, hãy nghe kỹ, khéo để tâm, ta sẽ nói.” ",
  "dn31:2.16": "“Dạ vâng, bạch Thế Tôn,” chàng Siṅgālaka, con một gia chủ, đáp lời Thế Tôn. ",
  "dn31:2.17": "Thế Tôn nói như sau: ",
  "dn31:3.1": "“Này con gia chủ, khi người đệ tử thánh đã từ bỏ bốn điều nhơ bẩn của hành động, không làm việc xấu do bốn nguyên do, và không theo sáu cửa làm tiêu tan tài sản, thì người ấy đã tránh xa mười bốn điều xấu, che chở sáu phương, ",
  "dn31:3.2": "và đang đi trên con đường thắng lợi ở cả hai đời. Đời này của người ấy được vững chắc, và đời sau cũng vậy. ",
  "dn31:3.3": "Sau khi thân hoại mạng chung, người ấy sinh vào cõi lành, cõi trời. ",
  "dn31:3.4.0": "2. Bốn điều nhơ bẩn của hành động ",
  "dn31:3.5": "Thế nào là bốn điều nhơ bẩn của hành động đã được từ bỏ? ",
  "dn31:3.6": "Này con gia chủ, sát sinh là điều nhơ bẩn của hành động, lấy của không cho là điều nhơ bẩn của hành động, tà dâm là điều nhơ bẩn của hành động, nói dối là điều nhơ bẩn của hành động. ",
  "dn31:3.7": "Đó là bốn điều nhơ bẩn của hành động đã được từ bỏ.” ",
  "dn31:3.8": "Thế Tôn nói như vậy. ",
  "dn31:3.9": "Nói xong, bậc Thiện Thệ lại nói thêm rằng: ",
  "dn31:4.1": "“Sát sinh, lấy của không cho, ",
  "dn31:4.2": "và nói dối, ",
  "dn31:4.3": "cùng với đi đến vợ người khác, ",
  "dn31:4.4": "đều không được người trí khen ngợi.” ",
  "dn31:5.0": "3. Bốn nguyên do ",
  "dn31:5.1": "“Do bốn nguyên do nào mà người ta không làm việc xấu? ",
  "dn31:5.2": "Khi bị dục vọng lôi kéo thì làm việc xấu, khi bị sân hận lôi kéo thì làm việc xấu, khi bị si mê lôi kéo thì làm việc xấu, khi bị sợ hãi lôi kéo thì làm việc xấu. ",
  "dn31:5.3": "Này con gia chủ, khi người đệ tử thánh không bị dục vọng lôi kéo, không bị sân hận lôi kéo, không bị si mê lôi kéo, không bị sợ hãi lôi kéo, ",
  "dn31:5.4": "thì người ấy không làm việc xấu do bốn nguyên do ấy.” ",
  "dn31:5.5": "Thế Tôn nói như vậy. ",
  "dn31:5.6": "Nói xong, bậc Thiện Thệ lại nói thêm rằng: ",
  "dn31:6.1": "“Dục vọng, sân hận, sợ hãi, si mê, ",
  "dn31:6.2": "ai vì chúng mà vượt khỏi điều đúng, ",
  "dn31:6.3": "danh tiếng người ấy sẽ suy giảm, ",
  "dn31:6.4": "như mặt trăng vào nửa tháng tối. ",
  "dn31:6.5": "Dục vọng, sân hận, sợ hãi, si mê, ",
  "dn31:6.6": "ai không vì chúng mà vượt khỏi điều đúng, ",
  "dn31:6.7": "danh tiếng người ấy sẽ đầy lên, ",
  "dn31:6.8": "như mặt trăng vào nửa tháng sáng.”",
  "dn31:7.0": "4. Sáu cửa ngõ làm tiêu tán tài sản",
  "dn31:7.1": "“Này con nhà cư sĩ, sáu cửa ngõ làm tiêu tán tài sản mà người ấy không theo là gì?",
  "dn31:7.2": "Này con nhà cư sĩ, đam mê rượu men, rượu nấu và các thứ say sưa là một cửa ngõ làm tiêu tán tài sản; lang thang ngoài đường vào giờ không thích hợp là một cửa ngõ làm tiêu tán tài sản; la cà hội hè đình đám là một cửa ngõ làm tiêu tán tài sản; mê cờ bạc là một cửa ngõ làm tiêu tán tài sản; giao du bạn xấu là một cửa ngõ làm tiêu tán tài sản; sống lười biếng là một cửa ngõ làm tiêu tán tài sản.",
  "dn31:8.0": "5. Sáu tai hại của rượu chè",
  "dn31:8.1": "Này con nhà cư sĩ, có sáu tai hại của việc đam mê rượu men, rượu nấu và các thứ say sưa.",
  "dn31:8.2": "Mất tiền của ngay trước mắt, làm tăng thêm cãi vã, là chỗ phát sinh bệnh tật, gây tiếng xấu, để lộ thân thể không kín đáo, và làm suy yếu trí khôn là điều thứ sáu.",
  "dn31:8.3": "Này con nhà cư sĩ, đó là sáu tai hại của việc đam mê rượu men, rượu nấu và các thứ say sưa.",
  "dn31:9.0": "6. Sáu tai hại của việc đi đường không đúng lúc",
  "dn31:9.1": "Này con nhà cư sĩ, có sáu tai hại của việc lang thang ngoài đường vào giờ không thích hợp.",
  "dn31:9.2": "Bản thân không được giữ gìn, không được bảo vệ; vợ con cũng không được giữ gìn, không được bảo vệ; tài sản cũng không được giữ gìn, không được bảo vệ; lại còn bị nghi ngờ ở những nơi xấu ác; những lời vu khống cũng bám vào mình; và còn phải đối mặt với nhiều khổ não.",
  "dn31:9.3": "Này con nhà cư sĩ, đó là sáu tai hại của việc lang thang ngoài đường vào giờ không thích hợp.",
  "dn31:10.0": "7. Sáu tai hại của việc la cà hội hè đình đám",
  "dn31:10.1": "Này con nhà cư sĩ, có sáu tai hại của việc la cà hội hè đình đám.",
  "dn31:10.2": "Ở đâu có múa, ở đâu có hát, ở đâu có nhạc, ở đâu có kể chuyện, ở đâu có tiếng trống tay, ở đâu có đánh trống, người ấy đều tìm đến.",
  "dn31:10.3": "Này con nhà cư sĩ, đó là sáu tai hại của việc la cà hội hè đình đám.",
  "dn31:11.0": "8. Sáu tai hại của cờ bạc",
  "dn31:11.1": "Này con nhà cư sĩ, có sáu tai hại của việc mê cờ bạc.",
  "dn31:11.2": "Thắng thì sinh oán thù, thua thì tiếc của, mất tiền của ngay trước mắt, lời nói không có trọng lượng trong hội chúng, bị bạn bè và người thân xem thường, và không được ai muốn gả cưới, vì người ta nói:",
  "dn31:11.3": "‘Người này mê cờ bạc, không đủ sức nuôi vợ con.’",
  "dn31:11.4": "Này con nhà cư sĩ, đó là sáu tai hại của việc mê cờ bạc.",
  "dn31:12.0": "9. Sáu tai hại của việc giao du bạn xấu",
  "dn31:12.1": "Này con nhà cư sĩ, có sáu tai hại của việc giao du bạn xấu.",
  "dn31:12.2": "Những kẻ cờ bạc, những kẻ nghiện ngập, những kẻ ham nhậu nhẹt, những kẻ lừa lọc, những kẻ gian trá, những kẻ hung hăng liều lĩnh — chúng là bạn, là bè của người ấy.",
  "dn31:12.3": "Này con nhà cư sĩ, đó là sáu tai hại của việc giao du bạn xấu.",
  "dn31:13.0": "10. Sáu tai hại của lười biếng",
  "dn31:13.1": "Này con nhà cư sĩ, có sáu tai hại của việc sống lười biếng.",
  "dn31:13.2": "Quá lạnh nên không làm việc, quá nóng nên không làm việc, quá trễ nên không làm việc, quá sớm nên không làm việc, quá đói nên không làm việc, quá no nên không làm việc.",
  "dn31:13.3": "Người sống với quá nhiều cớ thoái thác công việc như vậy thì của cải chưa có sẽ không có được, còn của cải đã có thì đi đến hao mòn.",
  "dn31:13.4": "Này con nhà cư sĩ, đó là sáu tai hại của việc sống lười biếng.”",
  "dn31:13.5": "Thế Tôn nói như vậy.",
  "dn31:13.6": "Nói xong, bậc Thiện Thệ lại nói thêm như sau:",
  "dn31:14.1": "“Có kẻ được gọi là bạn nhậu,",
  "dn31:14.2": "có kẻ chỉ là bạn ngoài miệng;",
  "dn31:14.3": "nhưng ai khi việc cần phát sinh,",
  "dn31:14.4": "người ấy mới thật là bạn.",
  "dn31:14.5": "Ngủ nướng, dan díu vợ người,",
  "dn31:14.6": "gây oán thù và sống không lợi ích;",
  "dn31:14.7": "bạn xấu và tính keo kiệt,",
  "dn31:14.8": "sáu điều ấy làm người suy sụp.",
  "dn31:14.9": "Bạn xấu, bạn đồng hành xấu,",
  "dn31:14.10": "sống và lui tới trong nếp xấu;",
  "dn31:14.11": "ở đời này và đời sau,",
  "dn31:14.12": "người ấy đều suy sụp cả hai.",
  "dn31:14.13": "Cờ bạc, đàn bà, rượu chè, múa hát,",
  "dn31:14.14": "ngủ ngày, lang thang không đúng lúc;",
  "dn31:14.15": "bạn xấu và tính keo kiệt,",
  "dn31:14.16": "sáu điều ấy làm người suy sụp.",
  "dn31:14.17": "Chúng vui với cờ bạc, uống rượu say,",
  "dn31:14.18": "đi đến với đàn bà là người yêu của kẻ khác;",
  "dn31:14.19": "Gần gũi kẻ thấp kém, không gần người trưởng thành,",
  "dn31:14.20": "thì sa sút như trăng vào nửa tháng tối.",
  "dn31:14.21": "Ai nghiện rượu, nghèo túng, không có gì,",
  "dn31:14.22": "khát nước mà cứ uống khi đến quán rượu;",
  "dn31:14.23": "như lao xuống nước vì nợ nần,",
  "dn31:14.24": "chẳng bao lâu sẽ làm tan nát gia đình mình.",
  "dn31:14.25": "Không phải do thói quen ngủ ngày,",
  "dn31:14.26": "hay thức dậy trễ ban đêm;",
  "dn31:14.27": "nếu luôn say sưa, nghiện ngập,",
  "dn31:14.28": "thì không thể giữ yên cửa nhà.",
  "dn31:14.29": "Quá lạnh, quá nóng,",
  "dn31:14.30": "quá trễ rồi;",
  "dn31:14.31": "cứ vin vào đó mà bỏ bê công việc,",
  "dn31:14.32": "thì lợi ích sẽ trôi qua mất nơi người ấy.",
  "dn31:14.33": "Nhưng ai xem lạnh và nóng,",
  "dn31:14.34": "không đáng kể hơn cọng cỏ,",
  "dn31:14.35": "và làm những việc người nam cần làm,",
  "dn31:14.36": "thì không đánh mất an vui.”",
  "dn31:15.0": "11. Bạn giả dạng bạn thân",
  "dn31:15.1": "“Này con nhà cư sĩ, có bốn hạng không phải bạn mà giống như bạn, cần phải biết.",
  "dn31:15.2": "Kẻ chỉ lấy phần cho mình là hạng không phải bạn mà giống như bạn, kẻ chỉ giỏi nói là hạng không phải bạn mà giống như bạn, kẻ chỉ nói lời chiều ý là hạng không phải bạn mà giống như bạn, kẻ cùng mình đi vào đường xấu là hạng không phải bạn mà giống như bạn.",
  "dn31:16.1": "Này con nhà cư sĩ, có bốn điểm để biết kẻ chỉ lấy phần cho mình là hạng không phải bạn mà giống như bạn.",
  "dn31:16.2": "Người ấy chỉ nhắm lợi riêng,",
  "dn31:16.3": "cho ít mà muốn lấy nhiều;",
  "dn31:16.4": "chỉ giúp khi có chuyện sợ hãi,",
  "dn31:16.5": "và qua lại chỉ vì lợi lộc.",
  "dn31:16.6": "Này con nhà cư sĩ, đó là bốn điểm để biết kẻ chỉ lấy phần cho mình là hạng không phải bạn mà giống như bạn.",
  "dn31:17.1": "Này con nhà cư sĩ, có bốn điểm để biết kẻ chỉ giỏi nói là hạng không phải bạn mà giống như bạn.",
  "dn31:17.2": "Người ấy lấy chuyện đã qua để đãi bôi, lấy chuyện chưa tới để đãi bôi, dùng lời vô ích để lôi kéo, và khi có việc hiện tại cần làm thì lại chỉ ra sự bất lợi.",
  "dn31:17.3": "Này con nhà cư sĩ, đó là bốn điểm để biết kẻ chỉ giỏi nói là hạng không phải bạn mà giống như bạn.",
  "dn31:18.1": "Này con nhà cư sĩ, có bốn điểm để biết kẻ chỉ nói lời chiều ý là hạng không phải bạn mà giống như bạn.",
  "dn31:18.2": "Làm điều xấu cũng tán thành, làm điều tốt cũng tán thành, trước mặt thì khen, sau lưng thì chê.",
  "dn31:18.3": "Này con nhà cư sĩ, đó là bốn điểm để biết kẻ chỉ nói lời chiều ý là hạng không phải bạn mà giống như bạn.",
  "dn31:19.1": "Này con nhà cư sĩ, có bốn điểm để biết kẻ cùng mình đi vào đường xấu là hạng không phải bạn mà giống như bạn.",
  "dn31:19.2": "Người ấy là bạn trong việc đắm theo rượu men và chất say đưa đến buông lung, là bạn trong việc đi rong ngoài đường không đúng lúc, là bạn trong việc la cà hội hè, là bạn trong việc đắm theo cờ bạc đưa đến buông lung.",
  "dn31:19.3": "Này con nhà cư sĩ, đó là bốn điểm để biết kẻ cùng mình đi vào đường xấu là hạng không phải bạn mà giống như bạn.”",
  "dn31:19.4": "Đức Thế Tôn nói như vậy.",
  "dn31:19.5": "Nói xong, bậc Thiện Thệ lại dạy thêm rằng:",
  "dn31:20.1": "“Kẻ chỉ lấy phần cho mình mà làm bạn,",
  "dn31:20.2": "và kẻ làm bạn chỉ bằng lời nói;",
  "dn31:20.3": "kẻ chỉ nói lời chiều ý,",
  "dn31:20.4": "và kẻ làm bạn trong các đường xấu.",
  "dn31:20.5": "Biết rõ bốn hạng ấy",
  "dn31:20.6": "đều là bạn giả, người có trí",
  "dn31:20.7": "nên tránh xa,",
  "dn31:20.8": "như tránh con đường đầy hiểm nguy.”",
  "dn31:21.0": "12. Bạn tốt thật sự",
  "dn31:21.1": "“Này con nhà cư sĩ, có bốn hạng bạn tốt thật sự cần phải biết.",
  "dn31:21.2": "Bạn hay giúp đỡ là bạn tốt thật sự cần phải biết, bạn cùng vui cùng khổ là bạn tốt thật sự cần phải biết, bạn chỉ điều lợi ích là bạn tốt thật sự cần phải biết, bạn có lòng thương là bạn tốt thật sự cần phải biết.",
  "dn31:22.1": "Này con nhà cư sĩ, có bốn điểm để biết bạn hay giúp đỡ là bạn tốt thật sự.",
  "dn31:22.2": "Giữ gìn người bạn khi người ấy lơ là, giữ gìn tài sản của người bạn khi người ấy lơ là, là chỗ nương cho người sợ hãi, khi có việc cần làm thì giúp thêm gấp đôi của cải.",
  "dn31:22.3": "Này con nhà cư sĩ, nhờ bốn điều này mà biết được người bạn tốt là bạn giúp đỡ.",
  "dn31:23.1": "Này con nhà cư sĩ, nhờ bốn điều này mà biết được người bạn tốt cùng vui cùng khổ.",
  "dn31:23.2": "Nói cho biết điều kín của mình, giữ kín điều kín của bạn, không bỏ bạn khi gặp nạn, thậm chí dám hy sinh mạng sống vì bạn.",
  "dn31:23.3": "Này con nhà cư sĩ, nhờ bốn điều này mà biết được người bạn tốt cùng vui cùng khổ.",
  "dn31:24.1": "Này con nhà cư sĩ, nhờ bốn điều này mà biết được người bạn tốt chỉ điều lợi ích.",
  "dn31:24.2": "Ngăn khỏi điều xấu, hướng vào điều lành, cho nghe điều chưa nghe, chỉ đường lên cõi lành.",
  "dn31:24.3": "Này con nhà cư sĩ, nhờ bốn điều này mà biết được người bạn tốt chỉ điều lợi ích.",
  "dn31:25.1": "Này con nhà cư sĩ, nhờ bốn điều này mà biết được người bạn tốt có lòng thương.",
  "dn31:25.2": "Không vui khi bạn sa sút, vui khi bạn khá lên, ngăn người nói xấu bạn, khen người nói tốt về bạn.",
  "dn31:25.3": "Này con nhà cư sĩ, nhờ bốn điều này mà biết được người bạn tốt có lòng thương.”",
  "dn31:25.4": "Thế Tôn nói như vậy.",
  "dn31:25.5": "Nói xong, bậc Thiện Thệ lại nói thêm rằng:",
  "dn31:26.1": "“Người bạn giúp đỡ,",
  "dn31:26.2": "người bạn đồng hành trong vui khổ;",
  "dn31:26.3": "người bạn chỉ điều lợi ích,",
  "dn31:26.4": "và người bạn có lòng thương bạn.",
  "dn31:26.5": "Bốn hạng bạn ấy,",
  "dn31:26.6": "người có trí biết rõ như vậy;",
  "dn31:26.7": "nên hết lòng gần gũi,",
  "dn31:26.8": "như mẹ với con ruột;",
  "dn31:26.9": "Người có trí, đủ đức hạnh,",
  "dn31:26.10": "sáng rực như lửa cháy.",
  "dn31:26.11": "Người đang gom góp của cải,",
  "dn31:26.12": "sống như ong hút nhụy;",
  "dn31:26.13": "của cải dần dần tích tụ,",
  "dn31:26.14": "như ụ mối lớn dần lên.",
  "dn31:26.15": "Gom góp của cải như vậy,",
  "dn31:26.16": "người tại gia đủ nuôi gia đình;",
  "dn31:26.17": "nên chia của cải làm bốn phần,",
  "dn31:26.18": "như vậy mới kết được bạn bè.",
  "dn31:26.19": "Một phần để tiêu dùng,",
  "dn31:26.20": "hai phần dùng làm ăn;",
  "dn31:26.21": "phần thứ tư nên để dành,",
  "dn31:26.22": "để dùng khi gặp hoạn nạn.”",
  "dn31:27.0": "13. Phần che chở sáu phương",
  "dn31:27.1": "“Và này con nhà cư sĩ, người đệ tử thánh che chở sáu phương như thế nào?",
  "dn31:27.2": "Này con nhà cư sĩ, có sáu phương này cần được hiểu:",
  "dn31:27.3": "phương đông là cha mẹ, phương nam là thầy cô, phương tây là vợ con, phương bắc là bạn bè và người cộng sự, phương dưới là người làm công, phương trên là những vị tu hành và bà-la-môn.",
  "dn31:28.1": "Này con nhà cư sĩ, người con phải phụng dưỡng cha mẹ là phương đông bằng năm cách:",
  "dn31:28.2": "‘Cha mẹ đã nuôi ta, ta sẽ nuôi lại cha mẹ; ta sẽ làm việc bổn phận của cha mẹ; ta sẽ giữ gìn nếp nhà; ta sẽ nhận phần gia tài; và khi cha mẹ qua đời, ta sẽ làm việc tưởng nhớ cúng dường.’",
  "dn31:28.3": "Này con nhà cư sĩ, khi người con phụng dưỡng cha mẹ là phương đông bằng năm cách ấy, thì cha mẹ thương tưởng con bằng năm cách.",
  "dn31:28.4": "Ngăn con khỏi điều xấu, hướng con vào điều lành, dạy cho nghề nghiệp, cưới gả cho người xứng hợp, đến lúc thì trao gia tài.",
  "dn31:28.5": "Này con nhà cư sĩ, khi người con phụng dưỡng cha mẹ là phương đông bằng năm cách ấy, thì cha mẹ thương tưởng con bằng năm cách này.",
  "dn31:28.6": "Như vậy phương đông ấy được che chở, được yên ổn, không lo sợ.",
  "dn31:29.1": "Này con nhà cư sĩ, học trò phải phụng sự thầy cô là phương nam bằng năm cách:",
  "dn31:29.2": "bằng cách siêng năng, hầu cận, chăm chú lắng nghe, phục vụ, và kính cẩn tiếp nhận nghề học.",
  "dn31:29.3": "Này con nhà cư sĩ, khi học trò phụng sự thầy cô là phương nam bằng năm cách ấy, thì thầy cô thương tưởng học trò bằng năm cách:",
  "dn31:29.4": "dạy dỗ cho nên người, giúp nắm vững điều đã học, truyền dạy đầy đủ mọi nghề học, giới thiệu với bạn bè và người cộng sự, bảo vệ ở mọi phương.",
  "dn31:29.5": "Này con nhà cư sĩ, khi học trò phụng sự thầy cô là phương nam bằng năm cách ấy, thì thầy cô thương tưởng học trò bằng năm cách này.",
  "dn31:29.6": "Như vậy, phương nam ấy được che chở, an ổn, không hiểm nguy.",
  "dn31:30.1": "Này con nhà cư sĩ, có năm cách người chồng nên đối xử với vợ như phương tây—",
  "dn31:30.2": "kính trọng, không xem thường, không ngoại tình, giao quyền quán xuyến, và sắm đồ trang sức cho vợ.",
  "dn31:30.3": "Này con nhà cư sĩ, khi người chồng đối xử với vợ như phương tây bằng năm cách ấy, thì người vợ thương tưởng chồng bằng năm cách—",
  "dn31:30.4": "khéo sắp xếp công việc, chăm lo người trong nhà, không ngoại tình, giữ gìn tài sản đã làm ra, và khéo léo, siêng năng trong mọi việc.",
  "dn31:30.5": "Này con nhà cư sĩ, khi người chồng đối xử với vợ như phương tây bằng năm cách ấy, thì người vợ thương tưởng chồng bằng năm cách này.",
  "dn31:30.6": "Như vậy, phương tây ấy được che chở, an ổn, không hiểm nguy.",
  "dn31:31.1": "Này con nhà cư sĩ, có năm cách người con trai trong gia đình nên đối xử với bạn bè, người thân cận như phương bắc—",
  "dn31:31.2": "bằng sự cho đi, lời nói dễ mến, giúp ích, đối xử ngang nhau, và không dối gạt.",
  "dn31:31.3": "Này con nhà cư sĩ, khi người con trai trong gia đình đối xử với bạn bè, người thân cận như phương bắc bằng năm cách ấy, thì họ thương tưởng người ấy bằng năm cách—",
  "dn31:31.4": "bảo vệ khi người ấy sơ suất, giữ gìn tài sản khi người ấy sơ suất, làm chỗ nương tựa khi người ấy sợ hãi, không bỏ rơi trong lúc hoạn nạn, và kính trọng cả con cháu của người ấy.",
  "dn31:31.5": "Này con nhà cư sĩ, khi người con trai trong gia đình đối xử với bạn bè, người thân cận như phương bắc bằng năm cách ấy, thì họ thương tưởng người ấy bằng năm cách này.",
  "dn31:31.6": "Như vậy, phương bắc ấy được che chở, an ổn, không hiểm nguy.",
  "dn31:32.1": "Này con nhà cư sĩ, có năm cách người chủ nên đối xử với người làm công, kẻ giúp việc như phương dưới—",
  "dn31:32.2": "giao việc theo sức, cấp cơm lương, chăm sóc khi đau ốm, chia phần món ngon vật lạ, và cho nghỉ đúng lúc.",
  "dn31:32.3": "Này con nhà cư sĩ, khi người chủ đối xử với người làm công, kẻ giúp việc như phương dưới bằng năm cách ấy, thì họ thương tưởng người chủ bằng năm cách—",
  "dn31:32.4": "dậy trước, ngủ sau, chỉ lấy những gì được cho, làm việc khéo léo, và giữ gìn tiếng tốt cho chủ.",
  "dn31:32.5": "Này con nhà cư sĩ, khi người chủ đối xử với người làm công, kẻ giúp việc như phương dưới bằng năm cách ấy, thì họ thương tưởng người chủ bằng năm cách này.",
  "dn31:32.6": "Như vậy, phương dưới ấy được che chở, an ổn, không hiểm nguy.",
  "dn31:33.1": "Này con nhà cư sĩ, có năm cách người con trai trong gia đình nên đối xử với các vị sa môn, bà la môn như phương trên—",
  "dn31:33.2": "bằng hành động thân thiện, lời nói thân thiện, ý nghĩ thân thiện, mở rộng cửa đón tiếp, và cúng dường vật dụng.",
  "dn31:33.3": "Này con nhà cư sĩ, khi người con trai trong gia đình đối xử với các vị sa môn, bà la môn như phương trên bằng năm cách ấy, thì các vị ấy thương tưởng người ấy bằng sáu cách—",
  "dn31:33.4": "ngăn điều xấu, hướng vào điều lành, thương tưởng với tâm tốt, dạy điều chưa nghe, làm sáng tỏ điều đã nghe, và chỉ đường lên cõi lành.",
  "dn31:33.5": "Này con nhà cư sĩ, khi người con trai trong gia đình đối xử với các vị sa môn, bà la môn như phương trên bằng năm cách ấy, thì các vị ấy thương tưởng người ấy bằng sáu cách này.",
  "dn31:33.6": "Như vậy, phương trên ấy được che chở, an ổn, không hiểm nguy.”",
  "dn31:33.7": "Đức Thế Tôn nói như vậy.",
  "dn31:33.8": "Nói xong, bậc Thiện Thệ lại nói thêm như sau:",
  "dn31:34.1": "“Cha mẹ là phương đông,",
  "dn31:34.2": "thầy dạy là phương nam;",
  "dn31:34.3": "vợ con là phương tây,",
  "dn31:34.4": "bạn bè, người thân cận là phương bắc.",
  "dn31:34.5": "Người làm công, kẻ giúp việc là phương dưới,",
  "dn31:34.6": "sa môn, bà la môn là phương trên;",
  "dn31:34.7": "người tại gia trong gia đình",
  "dn31:34.8": "đủ trưởng thành nên kính lễ các phương ấy.",
  "dn31:34.9": "Người có trí, đủ giới hạnh,",
  "dn31:34.10": "nhẹ nhàng và có tài nói năng;",
  "dn31:34.11": "sống khiêm nhường, không cứng cỏi,",
  "dn31:34.12": "người như vậy được tiếng tốt.",
  "dn31:34.13": "Siêng năng, không lười biếng,",
  "dn31:34.14": "không run sợ trong hoạn nạn;",
  "dn31:34.15": "sống vững vàng, có trí,",
  "dn31:34.16": "người như vậy được tiếng tốt.",
  "dn31:34.17": "Biết nâng đỡ, tạo bạn bè,",
  "dn31:34.18": "rộng rãi, không keo kiệt;",
  "dn31:34.19": "biết dẫn dắt, biết dạy bảo, biết khuyên nhủ,",
  "dn31:34.20": "người như vậy được tiếng tốt.",
  "dn31:34.21": "Bố thí và lời nói dễ mến,",
  "dn31:34.22": "cùng với việc làm lợi ích ở đời này;",
  "dn31:34.23": "và đối xử ngang nhau trong mọi việc,",
  "dn31:34.24": "ở mỗi nơi, tùy theo điều thích hợp;",
  "dn31:34.25": "Đó là những cách gắn kết ở đời,",
  "dn31:34.26": "như chốt trục của cỗ xe đang chạy.",
  "dn31:34.27": "Nếu không có những cách gắn kết ấy,",
  "dn31:34.28": "thì mẹ vì con",
  "dn31:34.29": "không được kính trọng hay tôn vinh,",
  "dn31:34.30": "cha vì con cũng vậy.",
  "dn31:34.31": "Vì những cách gắn kết này,",
  "dn31:34.32": "được người có trí nhìn nhận đúng đắn,",
  "dn31:34.33": "nên họ đạt được sự lớn mạnh,",
  "dn31:34.34": "và được người đời khen ngợi.”",
  "dn31:35.1": "Khi được nói vậy, Siṅgālaka, con trai người gia chủ, bạch Thế Tôn:",
  "dn31:35.2": "“Thật tuyệt vời, bạch Thế Tôn, thật tuyệt vời, bạch Thế Tôn.",
  "dn31:35.3": "Ví như, bạch Thế Tôn, người ta dựng vật bị úp xuống lên, mở ra điều bị che kín, chỉ đường cho người lạc lối, đem đèn dầu vào chỗ tối để người có mắt thấy được các hình sắc; cũng vậy, Chánh pháp đã được Thế Tôn trình bày bằng nhiều cách.",
  "dn31:35.4": "Con xin nương tựa Thế Tôn, nương tựa Pháp và nương tựa Tăng chúng tỳ-kheo.",
  "dn31:35.5": "Xin Thế Tôn ghi nhận con là người cư sĩ tại gia từ nay cho đến trọn đời đã quy y.”",
  "dn31:35.6": "Kinh Siṅgāla chấm dứt, bài thứ tám."
}
window.BILARA["dn31"]["vi"]["dn31:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";
