window.BILARA = window.BILARA || {};
window.BILARA["mn09"] = window.BILARA["mn09"] || {};
window.BILARA["mn09"]["vi"] = {
  "mn9:0.1": "Trung Bộ Kinh 9 ",
  "mn9:0.2": "Kinh Chánh Tri Kiến ",
  "mn9:1.1": "Tôi nghe như vầy—",
  "mn9:1.2": "Một thời Thế Tôn trú ở Sāvatthī, tại Jetavana, khu vườn của Anāthapiṇḍika. ",
  "mn9:1.3": "Lúc bấy giờ, Tôn giả Sāriputta gọi các Tỳ kheo: ",
  "mn9:1.4": "“Này các Hiền giả Tỳ kheo!” ",
  "mn9:1.5": "Các Tỳ kheo ấy vâng đáp Tôn giả Sāriputta: “Thưa Hiền giả!” ",
  "mn9:1.6": "Tôn giả Sāriputta nói như sau: ",
  "mn9:2.1": "“Này các Hiền giả, người ta nói ‘Chánh tri kiến, chánh tri kiến’. ",
  "mn9:2.2": "Này các Hiền giả, cho đến mức độ nào thì một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này?” ",
  "mn9:2.3": "“Thưa Hiền giả, chúng tôi từ xa đến để hiểu ý nghĩa lời nói này từ Tôn giả Sāriputta. ",
  "mn9:2.4": "Lành thay, Tôn giả Sāriputta hãy giải thích ý nghĩa lời nói này. ",
  "mn9:2.5": "Nghe Tôn giả Sāriputta nói, các Tỳ kheo sẽ ghi nhớ.” ",
  "mn9:2.6": "“Vậy thì, này các Hiền giả, hãy lắng nghe, hãy khéo tác ý, tôi sẽ nói.” ",
  "mn9:2.7": "Các Tỳ kheo ấy vâng đáp Tôn giả Sāriputta: “Thưa vâng, Hiền giả!” ",
  "mn9:2.8": "Tôn giả Sāriputta nói như sau: ",
  "mn9:3.1": "“Này các Hiền giả, khi một Thánh đệ tử biết bất thiện, biết gốc rễ của bất thiện, biết thiện, biết gốc rễ của thiện—",
  "mn9:3.2": "cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này.” ",
  "mn9:4.1": "“Này các Hiền giả, thế nào là bất thiện, thế nào là gốc rễ của bất thiện, thế nào là thiện, thế nào là gốc rễ của thiện? ",
  "mn9:4.2": "Này các Hiền giả, sát sinh là bất thiện, trộm cắp là bất thiện, tà dâm là bất thiện, nói dối là bất thiện, nói hai lưỡi là bất thiện, nói lời thô ác là bất thiện, nói lời vô ích là bất thiện, tham lam là bất thiện, sân hận là bất thiện, tà kiến là bất thiện—",
  "mn9:4.3": "đây gọi là bất thiện, này các Hiền giả. ",
  "mn9:5.1": "Và này các Hiền giả, thế nào là gốc rễ của bất thiện? ",
  "mn9:5.2": "Tham là gốc rễ của bất thiện, sân là gốc rễ của bất thiện, si là gốc rễ của bất thiện—",
  "mn9:5.3": "đây gọi là gốc rễ của bất thiện, này các Hiền giả. ",
  "mn9:6.1": "Và này các Hiền giả, thế nào là thiện? ",
  "mn9:6.2": "Không sát sinh là thiện, không trộm cắp là thiện, không tà dâm là thiện, không nói dối là thiện, không nói hai lưỡi là thiện, không nói lời thô ác là thiện, không nói lời vô ích là thiện, không tham lam là thiện, không sân hận là thiện, chánh tri kiến là thiện—",
  "mn9:6.3": "đây gọi là thiện, này các Hiền giả. ",
  "mn9:7.1": "Và này các Hiền giả, thế nào là gốc rễ của thiện? ",
  "mn9:7.2": "Không tham là gốc rễ của thiện, không sân là gốc rễ của thiện, không si là gốc rễ của thiện—",
  "mn9:7.3": "đây gọi là gốc rễ của thiện, này các Hiền giả. ",
  "mn9:8.1": "Này các Hiền giả, khi một Thánh đệ tử biết bất thiện như vậy, biết gốc rễ của bất thiện như vậy, biết thiện như vậy, biết gốc rễ của thiện như vậy, vị ấy hoàn toàn từ bỏ tùy miên tham, loại trừ tùy miên sân, nhổ tận gốc tùy miên kiêu mạn ‘ta là’, từ bỏ vô minh, phát sinh minh, và ngay trong đời này chấm dứt khổ đau—",
  "mn9:8.2": "cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này.” ",
  "mn9:9.1": "“Lành thay, Hiền giả!” Các Tỳ kheo ấy hoan hỷ, tùy hỷ lời Tôn giả Sāriputta nói, rồi hỏi thêm Tôn giả Sāriputta: ",
  "mn9:9.2": "“Này Hiền giả, có thể có một cách khác nữa để một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này không?” ",
  "mn9:10.1": "“Có, này các Hiền giả. ",
  "mn9:10.2": "Này các Hiền giả, khi một Thánh đệ tử biết thức ăn, biết nguyên nhân của thức ăn, biết sự chấm dứt của thức ăn, biết con đường đưa đến sự chấm dứt của thức ăn—",
  "mn9:10.3": "cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này. ",
  "mn9:11.1": "Này các Hiền giả, thế nào là thức ăn, thế nào là nguyên nhân của thức ăn, thế nào là sự chấm dứt của thức ăn, thế nào là con đường đưa đến sự chấm dứt của thức ăn? ",
  "mn9:11.2": "Này các Hiền giả, có bốn loại thức ăn này để duy trì các loài đã sinh hoặc để hỗ trợ các loài đang tìm cầu sự sinh. ",
  "mn9:11.3": "Bốn loại nào? ",
  "mn9:11.4": "Thức ăn vật chất, thô hay tế; xúc là thứ hai; tư niệm là thứ ba; thức là thứ tư. ",
  "mn9:11.5": "Do khát ái sinh, thức ăn sinh; do khát ái diệt, thức ăn diệt; chính Bát Chánh Đạo này là con đường đưa đến sự chấm dứt của thức ăn, đó là—",
  "mn9:11.6": "chánh tri kiến, chánh tư duy, chánh ngữ, chánh nghiệp, chánh mạng, chánh tinh tấn, chánh niệm, chánh định. ",
  "mn9:12.1": "Này các Hiền giả, khi một Thánh đệ tử biết thức ăn như vậy, biết nguyên nhân của thức ăn như vậy, biết sự chấm dứt của thức ăn như vậy, biết con đường đưa đến sự chấm dứt của thức ăn như vậy, vị ấy hoàn toàn từ bỏ tùy miên tham, loại trừ tùy miên sân, nhổ tận gốc tùy miên kiêu mạn ‘ta là’, từ bỏ vô minh, phát sinh minh, và ngay trong đời này chấm dứt khổ đau—",
  "mn9:12.2": "cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này.” ",
  "mn9:13.1": "“Lành thay, Hiền giả!” Các Tỳ kheo ấy hoan hỷ, tùy hỷ lời Tôn giả Sāriputta nói, rồi hỏi thêm Tôn giả Sāriputta: ",
  "mn9:13.2": "“Này Hiền giả, có thể có một cách khác nữa để một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này không?” ",
  "mn9:14.1": "“Có, này các Hiền giả. ",
  "mn9:14.2": "Này các Hiền giả, khi một Thánh đệ tử biết khổ, biết nguyên nhân của khổ, biết sự chấm dứt của khổ, biết con đường đưa đến sự chấm dứt của khổ—",
  "mn9:14.3": "cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này. ",
  "mn9:15.1": "Này các Hiền giả, thế nào là khổ, thế nào là nguyên nhân của khổ, thế nào là sự chấm dứt của khổ, thế nào là con đường đưa đến sự chấm dứt của khổ? ",
  "mn9:15.2": "Sinh là khổ, già là khổ, chết là khổ, sầu bi khổ ưu não là khổ, gặp gỡ người không ưa thích là khổ, xa lìa người ưa thích là khổ, mong cầu mà không được là khổ, tóm lại năm thủ uẩn là khổ—",
  "mn9:15.3": "đây gọi là khổ, này các Hiền giả. ",
  "mn9:16.1": "Và này các Hiền giả, thế nào là nguyên nhân của khổ? ",
  "mn9:16.2": "Chính là khát ái đưa đến tái sinh, cùng với hỷ và tham, tìm cầu khoái lạc chỗ này chỗ kia, đó là—",
  "mn9:16.3": "dục ái, hữu ái, vô hữu ái—",
  "mn9:16.4": "đây gọi là nguyên nhân của khổ, này các Hiền giả. ",
  "mn9:17.1": "Và này các Hiền giả, thế nào là sự chấm dứt của khổ? ",
  "mn9:17.2": "Chính là sự diệt tận hoàn toàn, sự từ bỏ, sự xả ly, sự giải thoát, sự không chấp trước khát ái ấy—",
  "mn9:17.3": "đây gọi là sự chấm dứt của khổ, này các Hiền giả. ",
  "mn9:18.1": "Và này các Hiền giả, thế nào là con đường đưa đến sự chấm dứt của khổ? ",
  "mn9:18.2": "Chính là Bát Chánh Đạo này, đó là—",
  "mn9:18.3": "chánh tri kiến… cho đến… chánh định—",
  "mn9:18.4": "đây gọi là con đường đưa đến sự chấm dứt của khổ, này các Hiền giả. ",
  "mn9:19.1": "Này các Hiền giả, khi một Thánh đệ tử biết khổ như vậy, biết nguyên nhân của khổ như vậy, biết sự chấm dứt của khổ như vậy, biết con đường đưa đến sự chấm dứt của khổ như vậy, vị ấy hoàn toàn từ bỏ tùy miên tham, loại trừ tùy miên sân, nhổ tận gốc tùy miên kiêu mạn ‘ta là’, từ bỏ vô minh, phát sinh minh, và ngay trong đời này chấm dứt khổ đau—",
  "mn9:19.2": "cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này.” ",
  "mn9:20.1": "“Lành thay, Hiền giả!” Các Tỳ kheo ấy hoan hỷ, tùy hỷ lời Tôn giả Sāriputta nói, rồi hỏi thêm Tôn giả Sāriputta: ",
  "mn9:20.2": "“Này Hiền giả, có thể có một cách khác nữa để một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này không?” ",
  "mn9:21.1": "“Có, này các Hiền giả. ",
  "mn9:21.2": "Này các Hiền giả, khi một Thánh đệ tử biết già chết, biết nguyên nhân của già chết, biết sự chấm dứt của già chết, biết con đường đưa đến sự chấm dứt của già chết—",
  "mn9:21.3": "cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này. ",
  "mn9:22.1": "Này các Hiền giả, thế nào là già chết, thế nào là nguyên nhân của già chết, thế nào là sự chấm dứt của già chết, thế nào là con đường đưa đến sự chấm dứt của già chết? ",
  "mn9:22.2": "Sự già yếu, sự suy tàn, sự răng rụng, tóc bạc, da nhăn, sự suy giảm tuổi thọ, sự suy yếu các căn của các loài hữu tình trong các loài hữu tình ấy—",
  "mn9:22.3": "đây gọi là già, này các Hiền giả. ",
  "mn9:22.4": "Và này các Hiền giả, thế nào là chết? ",
  "mn9:22.5": "Sự từ bỏ, sự biến mất, sự tan rã, sự biến mất, sự chết, sự qua đời, sự tan rã của các uẩn, sự vứt bỏ thân thể, sự cắt đứt sinh mạng của các loài hữu tình từ các loài hữu tình ấy—",
  "mn9:22.6": "đây gọi là chết, này các Hiền giả. ",
  "mn9:22.7": "Như vậy, sự già này và sự chết này—",
  "mn9:22.8": "đây gọi là già chết, này các Hiền giả. ",
  "mn9:22.9": "Do sinh sinh, già chết sinh; do sinh diệt, già chết diệt; chính Bát Chánh Đạo này là con đường đưa đến sự chấm dứt của già chết, đó là—",
  "mn9:22.10": "chánh tri kiến… cho đến… chánh định. ",
  "mn9:23.1": "Này các Hiền giả, khi một Thánh đệ tử biết già chết như vậy, biết nguyên nhân của già chết như vậy, biết sự chấm dứt của già chết như vậy, biết con đường đưa đến sự chấm dứt của già chết như vậy, vị ấy hoàn toàn từ bỏ tùy miên tham… cho đến… chấm dứt khổ đau—",
  "mn9:23.2": "cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này.” ",
  "mn9:24.1": "“Lành thay, Hiền giả!” Các Tỳ kheo ấy… cho đến… hỏi thêm—",
  "mn9:24.2": "“Này Hiền giả, có thể có một cách khác nữa… cho đến…” ",
  "mn9:25.1": "“Có, này các Hiền giả. ",
  "mn9:25.2": "Này các Hiền giả, khi một Thánh đệ tử biết sinh, biết nguyên nhân của sinh, biết sự chấm dứt của sinh, biết con đường đưa đến sự chấm dứt của sinh—",
  "mn9:25.3": "cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này. ",
  "mn9:26.1": "Này các Hiền giả, thế nào là sinh, thế nào là nguyên nhân của sinh, thế nào là sự chấm dứt của sinh, thế nào là con đường đưa đến sự chấm dứt của sinh? ",
  "mn9:26.2": "Sự sinh, sự tái sinh, sự nhập thai, sự xuất hiện, sự hiển lộ của các uẩn, sự thọ nhận các xứ của các loài hữu tình trong các loài hữu tình ấy—",
  "mn9:26.3": "đây gọi là sinh, này các Hiền giả. ",
  "mn9:26.4": "Do hữu sinh, sinh sinh; do hữu diệt, sinh diệt; chính Bát Chánh Đạo này là con đường đưa đến sự chấm dứt của sinh, đó là—",
  "mn9:26.5": "chánh tri kiến… cho đến… chánh định. ",
  "mn9:27.1": "Này các Hiền giả, khi một Thánh đệ tử biết sinh như vậy, biết nguyên nhân của sinh như vậy, biết sự chấm dứt của sinh như vậy, biết con đường đưa đến sự chấm dứt của sinh như vậy, vị ấy hoàn toàn từ bỏ tùy miên tham… cho đến… chấm dứt khổ đau—",
  "mn9:27.2": "cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này.” ",
  "mn9:28.1": "“Lành thay, Hiền giả!” Các Tỳ kheo ấy… cho đến… hỏi thêm—",
  "mn9:28.2": "“Này Hiền giả, có thể có một cách khác nữa… cho đến…” ",
  "mn9:29.1": "“Có, này các Hiền giả. ",
  "mn9:29.2": "Này các Hiền giả, khi một Thánh đệ tử biết hữu, biết nguyên nhân của hữu, biết sự chấm dứt của hữu, biết con đường đưa đến sự chấm dứt của hữu—",
  "mn9:29.3": "cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này. ",
  "mn9:30.1": "Này các Hiền giả, thế nào là hữu, thế nào là nguyên nhân của hữu, thế nào là sự chấm dứt của hữu, thế nào là con đường đưa đến sự chấm dứt của hữu? ",
  "mn9:30.2": "Này các Hiền giả, có ba loại hữu này—",
  "mn9:30.3": "dục hữu, sắc hữu, vô sắc hữu. ",
  "mn9:30.4": "Do chấp thủ sinh, hữu sinh; do chấp thủ diệt, hữu diệt; chính Bát Chánh Đạo này là con đường đưa đến sự chấm dứt của hữu, đó là—",
  "mn9:30.5": "chánh tri kiến… cho đến… chánh định. ",
  "mn9:31.1": "Này các Hiền giả, khi một Thánh đệ tử biết hữu như vậy, biết nguyên nhân của hữu như vậy, biết sự chấm dứt của hữu như vậy, biết con đường đưa đến sự chấm dứt của hữu như vậy, vị ấy hoàn toàn từ bỏ tùy miên tham… cho đến… chấm dứt khổ đau. ",
  "mn9:31.2": "Cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này.” ",
  "mn9:32.1": "“Lành thay, Hiền giả!” Các Tỳ kheo ấy… cho đến… hỏi thêm—",
  "mn9:32.2": "“Này Hiền giả, có thể có một cách khác nữa… cho đến…” ",
  "mn9:33.1": "“Có, này các Hiền giả. ",
  "mn9:33.2": "Này các Hiền giả, khi một Thánh đệ tử biết chấp thủ, biết nguyên nhân của chấp thủ, biết sự chấm dứt của chấp thủ, biết con đường đưa đến sự chấm dứt của chấp thủ—",
  "mn9:33.3": "cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này. ",
  "mn9:34.1": "Này các Hiền giả, thế nào là chấp thủ, thế nào là nguyên nhân của chấp thủ, thế nào là sự chấm dứt của chấp thủ, thế nào là con đường đưa đến sự chấm dứt của chấp thủ? ",
  "mn9:34.2": "Này các Hiền giả, có bốn loại chấp thủ này—",
  "mn9:34.3": "dục chấp thủ, kiến chấp thủ, giới cấm chấp thủ, ngã luận chấp thủ. ",
  "mn9:34.4": "Do khát ái sinh, chấp thủ sinh; do khát ái diệt, chấp thủ diệt; chính Bát Chánh Đạo này là con đường đưa đến sự chấm dứt của chấp thủ, đó là—",
  "mn9:34.5": "chánh tri kiến… cho đến… chánh định. ",
  "mn9:35.1": "Này các Hiền giả, khi một Thánh đệ tử biết chấp thủ như vậy, biết nguyên nhân của chấp thủ như vậy, biết sự chấm dứt của chấp thủ như vậy, biết con đường đưa đến sự chấm dứt của chấp thủ như vậy, vị ấy hoàn toàn từ bỏ tùy miên tham… cho đến… chấm dứt khổ đau—",
  "mn9:35.2": "cho đến mức độ ấy, này các Hiền giả, một Thánh đệ tử có chánh tri kiến, có tri kiến ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với Chánh pháp này.” ",
  "mn9:36.1": "“Lành thay, Hiền giả!” Các Tỳ kheo ấy… cho đến… hỏi thêm—",
  "mn9:36.2": "Thưa các bạn, có thể có …pe… ",
  "mn9:37.1": "“Thưa các bạn, có thể có. ",
  "mn9:37.2": "Này các bạn, khi một đệ tử thánh biết rõ về tham ái, biết rõ về nguyên nhân của tham ái, biết rõ về sự chấm dứt tham ái, biết rõ về con đường đưa đến sự chấm dứt tham ái—",
  "mn9:37.3": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này. ",
  "mn9:38.1": "Này các bạn, tham ái là gì, nguyên nhân của tham ái là gì, sự chấm dứt tham ái là gì, con đường đưa đến sự chấm dứt tham ái là gì? ",
  "mn9:38.2": "Này các bạn, có sáu loại tham ái này—",
  "mn9:38.3": "tham ái đối với sắc, tham ái đối với tiếng, tham ái đối với mùi, tham ái đối với vị, tham ái đối với xúc, tham ái đối với pháp. ",
  "mn9:38.4": "Do cảm thọ sinh khởi mà tham ái sinh khởi; do cảm thọ chấm dứt mà tham ái chấm dứt; chính con đường thánh tám ngành này là con đường đưa đến sự chấm dứt tham ái, đó là—",
  "mn9:38.5": "chánh kiến …pe… chánh định. ",
  "mn9:39.1": "Này các bạn, khi một đệ tử thánh biết rõ tham ái như vậy, biết rõ nguyên nhân của tham ái như vậy, biết rõ sự chấm dứt tham ái như vậy, biết rõ con đường đưa đến sự chấm dứt tham ái như vậy, thì người ấy hoàn toàn từ bỏ tùy miên tham ái …pe… trở thành người chấm dứt khổ đau—",
  "mn9:39.2": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này.”",
  "mn9:40.1": "“Lành thay, thưa các bạn,” …pe… họ hỏi—",
  "mn9:40.2": "Thưa các bạn, có thể có …pe… ",
  "mn9:41.1": "“Thưa các bạn, có thể có. ",
  "mn9:41.2": "Này các bạn, khi một đệ tử thánh biết rõ về cảm thọ, biết rõ về nguyên nhân của cảm thọ, biết rõ về sự chấm dứt cảm thọ, biết rõ về con đường đưa đến sự chấm dứt cảm thọ—",
  "mn9:41.3": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này. ",
  "mn9:42.1": "Này các bạn, cảm thọ là gì, nguyên nhân của cảm thọ là gì, sự chấm dứt cảm thọ là gì, con đường đưa đến sự chấm dứt cảm thọ là gì? ",
  "mn9:42.2": "Này các bạn, có sáu loại cảm thọ này—",
  "mn9:42.3": "cảm thọ do xúc chạm mắt sinh, cảm thọ do xúc chạm tai sinh, cảm thọ do xúc chạm mũi sinh, cảm thọ do xúc chạm lưỡi sinh, cảm thọ do xúc chạm thân sinh, cảm thọ do xúc chạm ý sinh. ",
  "mn9:42.4": "Do xúc chạm sinh khởi mà cảm thọ sinh khởi; do xúc chạm chấm dứt mà cảm thọ chấm dứt; chính con đường thánh tám ngành này là con đường đưa đến sự chấm dứt cảm thọ, đó là—",
  "mn9:42.5": "chánh kiến …pe… chánh định. ",
  "mn9:43.1": "Này các bạn, khi một đệ tử thánh biết rõ cảm thọ như vậy, biết rõ nguyên nhân của cảm thọ như vậy, biết rõ sự chấm dứt cảm thọ như vậy, biết rõ con đường đưa đến sự chấm dứt cảm thọ như vậy, thì người ấy hoàn toàn từ bỏ tùy miên tham ái …pe… trở thành người chấm dứt khổ đau—",
  "mn9:43.2": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này.”",
  "mn9:44.1": "“Lành thay, thưa các bạn,” …pe… họ hỏi—",
  "mn9:44.2": "Thưa các bạn, có thể có …pe… ",
  "mn9:45.1": "“Thưa các bạn, có thể có. ",
  "mn9:45.2": "Này các bạn, khi một đệ tử thánh biết rõ về xúc chạm, biết rõ về nguyên nhân của xúc chạm, biết rõ về sự chấm dứt xúc chạm, biết rõ về con đường đưa đến sự chấm dứt xúc chạm—",
  "mn9:45.3": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này. ",
  "mn9:46.1": "Này các bạn, xúc chạm là gì, nguyên nhân của xúc chạm là gì, sự chấm dứt xúc chạm là gì, con đường đưa đến sự chấm dứt xúc chạm là gì? ",
  "mn9:46.2": "Này các bạn, có sáu loại xúc chạm này—",
  "mn9:46.3": "xúc chạm mắt, xúc chạm tai, xúc chạm mũi, xúc chạm lưỡi, xúc chạm thân, xúc chạm ý. ",
  "mn9:46.4": "Do sáu xứ sinh khởi mà xúc chạm sinh khởi; do sáu xứ chấm dứt mà xúc chạm chấm dứt; chính con đường thánh tám ngành này là con đường đưa đến sự chấm dứt xúc chạm, đó là—",
  "mn9:46.5": "chánh kiến …pe… chánh định. ",
  "mn9:47.1": "Này các bạn, khi một đệ tử thánh biết rõ xúc chạm như vậy, biết rõ nguyên nhân của xúc chạm như vậy, biết rõ sự chấm dứt xúc chạm như vậy, biết rõ con đường đưa đến sự chấm dứt xúc chạm như vậy, thì người ấy hoàn toàn từ bỏ tùy miên tham ái …pe… trở thành người chấm dứt khổ đau—",
  "mn9:47.2": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này.”",
  "mn9:48.1": "“Lành thay, thưa các bạn,” …pe… họ hỏi—",
  "mn9:48.2": "Thưa các bạn, có thể có …pe… ",
  "mn9:49.1": "“Thưa các bạn, có thể có. ",
  "mn9:49.2": "Này các bạn, khi một đệ tử thánh biết rõ về sáu xứ, biết rõ về nguyên nhân của sáu xứ, biết rõ về sự chấm dứt sáu xứ, biết rõ về con đường đưa đến sự chấm dứt sáu xứ—",
  "mn9:49.3": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này. ",
  "mn9:50.1": "Này các bạn, sáu xứ là gì, nguyên nhân của sáu xứ là gì, sự chấm dứt sáu xứ là gì, con đường đưa đến sự chấm dứt sáu xứ là gì? ",
  "mn9:50.2": "Này các bạn, có sáu xứ này—",
  "mn9:50.3": "xứ mắt, xứ tai, xứ mũi, xứ lưỡi, xứ thân, xứ ý. ",
  "mn9:50.4": "Do danh sắc sinh khởi mà sáu xứ sinh khởi; do danh sắc chấm dứt mà sáu xứ chấm dứt; chính con đường thánh tám ngành này là con đường đưa đến sự chấm dứt sáu xứ, đó là—",
  "mn9:50.5": "chánh kiến …pe… chánh định. ",
  "mn9:51.1": "Này các bạn, khi một đệ tử thánh biết rõ sáu xứ như vậy, biết rõ nguyên nhân của sáu xứ như vậy, biết rõ sự chấm dứt sáu xứ như vậy, biết rõ con đường đưa đến sự chấm dứt sáu xứ như vậy, thì người ấy hoàn toàn từ bỏ tùy miên tham ái …pe… trở thành người chấm dứt khổ đau—",
  "mn9:51.2": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này.”",
  "mn9:52.1": "“Lành thay, thưa các bạn,” …pe… họ hỏi—",
  "mn9:52.2": "Thưa các bạn, có thể có …pe… ",
  "mn9:53.1": "“Thưa các bạn, có thể có. ",
  "mn9:53.2": "Này các bạn, khi một đệ tử thánh biết rõ về danh sắc, biết rõ về nguyên nhân của danh sắc, biết rõ về sự chấm dứt danh sắc, biết rõ về con đường đưa đến sự chấm dứt danh sắc—",
  "mn9:53.3": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này. ",
  "mn9:54.1": "Này các bạn, danh sắc là gì, nguyên nhân của danh sắc là gì, sự chấm dứt danh sắc là gì, con đường đưa đến sự chấm dứt danh sắc là gì? ",
  "mn9:54.2": "Cảm thọ, tưởng, tư, xúc, tác ý—",
  "mn9:54.3": "này các bạn, đây gọi là danh; ",
  "mn9:54.4": "bốn đại và sắc do bốn đại tạo thành—",
  "mn9:54.5": "này các bạn, đây gọi là sắc. ",
  "mn9:54.6": "Như vậy, danh này và sắc này—",
  "mn9:54.7": "này các bạn, đây gọi là danh sắc. ",
  "mn9:54.8": "Do thức sinh khởi mà danh sắc sinh khởi; do thức chấm dứt mà danh sắc chấm dứt; chính con đường thánh tám ngành này là con đường đưa đến sự chấm dứt danh sắc, đó là—",
  "mn9:54.9": "chánh kiến …pe… chánh định. ",
  "mn9:55.1": "Này các bạn, khi một đệ tử thánh biết rõ danh sắc như vậy, biết rõ nguyên nhân của danh sắc như vậy, biết rõ sự chấm dứt danh sắc như vậy, biết rõ con đường đưa đến sự chấm dứt danh sắc như vậy, thì người ấy hoàn toàn từ bỏ tùy miên tham ái …pe… trở thành người chấm dứt khổ đau—",
  "mn9:55.2": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này.”",
  "mn9:56.1": "“Lành thay, thưa các bạn,” …pe… họ hỏi—",
  "mn9:56.2": "Thưa các bạn, có thể có …pe… ",
  "mn9:57.1": "“Thưa các bạn, có thể có. ",
  "mn9:57.2": "Này các bạn, khi một đệ tử thánh biết rõ về thức, biết rõ về nguyên nhân của thức, biết rõ về sự chấm dứt thức, biết rõ về con đường đưa đến sự chấm dứt thức—",
  "mn9:57.3": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này. ",
  "mn9:58.1": "Này các bạn, thức là gì, nguyên nhân của thức là gì, sự chấm dứt thức là gì, con đường đưa đến sự chấm dứt thức là gì? ",
  "mn9:58.2": "Này các bạn, có sáu loại thức này—",
  "mn9:58.3": "nhãn thức, nhĩ thức, tỷ thức, thiệt thức, thân thức, ý thức. ",
  "mn9:58.4": "Do các hành sinh khởi mà thức sinh khởi; do các hành chấm dứt mà thức chấm dứt; chính con đường thánh tám ngành này là con đường đưa đến sự chấm dứt thức, đó là—",
  "mn9:58.5": "chánh kiến …pe… chánh định. ",
  "mn9:59.1": "Này các bạn, khi một đệ tử thánh biết rõ thức như vậy, biết rõ nguyên nhân của thức như vậy, biết rõ sự chấm dứt thức như vậy, biết rõ con đường đưa đến sự chấm dứt thức như vậy, thì người ấy hoàn toàn từ bỏ tùy miên tham ái …pe… trở thành người chấm dứt khổ đau—",
  "mn9:59.2": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này.”",
  "mn9:60.1": "“Lành thay, thưa các bạn,” …pe… họ hỏi—",
  "mn9:60.2": "Thưa các bạn, có thể có …pe… ",
  "mn9:61.1": "“Thưa các bạn, có thể có. ",
  "mn9:61.2": "Này các bạn, khi một đệ tử thánh biết rõ về các hành, biết rõ về nguyên nhân của các hành, biết rõ về sự chấm dứt các hành, biết rõ về con đường đưa đến sự chấm dứt các hành—",
  "mn9:61.3": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này. ",
  "mn9:62.1": "Này các bạn, các hành là gì, nguyên nhân của các hành là gì, sự chấm dứt các hành là gì, con đường đưa đến sự chấm dứt các hành là gì? ",
  "mn9:62.2": "Này các bạn, có ba loại hành này—",
  "mn9:62.3": "thân hành, khẩu hành, ý hành. ",
  "mn9:62.4": "Do vô minh sinh khởi mà các hành sinh khởi; do vô minh chấm dứt mà các hành chấm dứt; chính con đường thánh tám ngành này là con đường đưa đến sự chấm dứt các hành, đó là—",
  "mn9:62.5": "chánh kiến …pe… chánh định. ",
  "mn9:63.1": "Này các bạn, khi một đệ tử thánh biết rõ các hành như vậy, biết rõ nguyên nhân của các hành như vậy, biết rõ sự chấm dứt các hành như vậy, biết rõ con đường đưa đến sự chấm dứt các hành như vậy, thì người ấy hoàn toàn từ bỏ tùy miên tham ái, loại bỏ tùy miên sân hận, nhổ tận gốc tùy miên kiến chấp ‘ta là’, từ bỏ vô minh, làm phát sinh minh, trở thành người chấm dứt khổ đau ngay trong hiện tại—",
  "mn9:63.2": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này.”",
  "mn9:64.1": "“Lành thay, thưa các bạn,” …pe… họ hỏi—",
  "mn9:64.2": "Thưa các bạn, có thể có …pe… ",
  "mn9:64.3": "“Thưa các bạn, có thể có. ",
  "mn9:65.1": "Này các bạn, khi một đệ tử thánh biết rõ về vô minh, biết rõ về nguyên nhân của vô minh, biết rõ về sự chấm dứt vô minh, biết rõ về con đường đưa đến sự chấm dứt vô minh—",
  "mn9:65.2": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này. ",
  "mn9:65.3": "Này các bạn, vô minh là gì, nguyên nhân của vô minh là gì, sự chấm dứt vô minh là gì, con đường đưa đến sự chấm dứt vô minh là gì? ",
  "mn9:65.4": "Này các bạn, sự không biết về khổ, sự không biết về nguyên nhân của khổ, sự không biết về sự chấm dứt khổ, sự không biết về con đường đưa đến sự chấm dứt khổ—",
  "mn9:65.5": "này các bạn, đây gọi là vô minh. ",
  "mn9:66.1": "Do các lậu hoặc sinh khởi mà vô minh sinh khởi; do các lậu hoặc chấm dứt mà vô minh chấm dứt; chính con đường thánh tám ngành này là con đường đưa đến sự chấm dứt vô minh, đó là—",
  "mn9:66.2": "chánh kiến …pe… chánh định. ",
  "mn9:67.1": "Này các bạn, khi một đệ tử thánh biết rõ vô minh như vậy, biết rõ nguyên nhân của vô minh như vậy, biết rõ sự chấm dứt vô minh như vậy, biết rõ con đường đưa đến sự chấm dứt vô minh như vậy, thì người ấy hoàn toàn từ bỏ tùy miên tham ái, loại bỏ tùy miên sân hận, nhổ tận gốc tùy miên kiến chấp ‘ta là’, từ bỏ vô minh, làm phát sinh minh, trở thành người chấm dứt khổ đau ngay trong hiện tại—",
  "mn9:67.2": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này.”",
  "mn9:68.1": "“Lành thay, thưa các bạn,” các vị tỳ khưu ấy hoan hỷ và tán thán lời dạy của Tôn giả Xá Lợi Phất, rồi hỏi Tôn giả Xá Lợi Phất thêm một câu hỏi: ",
  "mn9:68.2": "“Thưa các bạn, có thể có một cách khác nữa để một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này chăng?”",
  "mn9:69.1": "“Thưa các bạn, có thể có. ",
  "mn9:69.2": "Này các bạn, khi một đệ tử thánh biết rõ về các lậu hoặc, biết rõ về nguyên nhân của các lậu hoặc, biết rõ về sự chấm dứt các lậu hoặc, biết rõ về con đường đưa đến sự chấm dứt các lậu hoặc—",
  "mn9:69.3": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này. ",
  "mn9:70.1": "Này các bạn, lậu hoặc là gì, nguyên nhân của lậu hoặc là gì, sự chấm dứt lậu hoặc là gì, con đường đưa đến sự chấm dứt lậu hoặc là gì? ",
  "mn9:70.2": "Này các bạn, có ba loại lậu hoặc này—",
  "mn9:70.3": "lậu hoặc dục, lậu hoặc hữu, lậu hoặc vô minh. ",
  "mn9:70.4": "Do vô minh sinh khởi mà các lậu hoặc sinh khởi; do vô minh chấm dứt mà các lậu hoặc chấm dứt; chính con đường thánh tám ngành này là con đường đưa đến sự chấm dứt các lậu hoặc, đó là—",
  "mn9:70.5": "chánh kiến …pe… chánh định. ",
  "mn9:71.1": "Này các bạn, khi một đệ tử thánh biết rõ các lậu hoặc như vậy, biết rõ nguyên nhân của các lậu hoặc như vậy, biết rõ sự chấm dứt các lậu hoặc như vậy, biết rõ con đường đưa đến sự chấm dứt các lậu hoặc như vậy, thì người ấy hoàn toàn từ bỏ tùy miên tham ái, loại bỏ tùy miên sân hận, nhổ tận gốc tùy miên kiến chấp ‘ta là’, từ bỏ vô minh, làm phát sinh minh, trở thành người chấm dứt khổ đau ngay trong hiện tại—",
  "mn9:71.2": "Này các bạn, cho đến chừng ấy, một đệ tử thánh có chánh kiến, có cái thấy ngay thẳng, có niềm tin bất động vào giáo pháp, đã đến với chánh pháp này.”",
  "mn9:71.3": "Tôn giả Xá Lợi Phất đã nói như vậy. ",
  "mn9:71.4": "Các vị tỳ khưu ấy hoan hỷ với lời dạy của Tôn giả Xá Lợi Phất. ",
  "mn9:71.5": "Kinh Chánh Kiến, thứ chín, chấm dứt."
}
window.BILARA["mn09"]["vi"]["mn09:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
