window.BILARA = window.BILARA || {};
window.BILARA["mn100"] = window.BILARA["mn100"] || {};
window.BILARA["mn100"]["vi"] = {
  "mn100:0.1": "Trung Bộ Kinh 100",
  "mn100:0.2": "Kinh Saṅgārava",
  "mn100:1.1": "Tôi nghe như vầy—",
  "mn100:1.2": "Một thời, Đức Thế Tôn đi du hành trong xứ Kosala cùng với đông đảo Tỳ Kheo.",
  "mn100:2.1": "Lúc bấy giờ, có một bà Bà-la-môn tên là Dhanañjānī sống ở Cañcalikappa, hết lòng tin kính Đức Phật, lời dạy và đoàn thể tu học.",
  "mn100:2.2": "Rồi bà Bà-la-môn Dhanañjānī vấp chân, liền thốt lên ba lần:",
  "mn100:2.3": "“Kính lễ Đức Thế Tôn, bậc đáng kính, bậc tự mình giác ngộ trọn vẹn.",
  "mn100:2.4": "Kính lễ Đức Thế Tôn, bậc đáng kính, bậc tự mình giác ngộ trọn vẹn.",
  "mn100:2.5": "Kính lễ Đức Thế Tôn, bậc đáng kính, bậc tự mình giác ngộ trọn vẹn.”",
  "mn100:3.1": "Lúc bấy giờ, có một thanh niên Bà-la-môn tên là Saṅgārava sống ở Cañcalikappa, đã học thông suốt ba bộ Vệ-đà, cùng với từ ngữ, nghi lễ, âm vần, cách chia tách chữ, và truyện xưa là phần thứ năm; giỏi về từ ngữ, giỏi về văn phạm, thông thạo lối bàn luận về đời và các dấu hiệu của bậc lớn.",
  "mn100:3.2": "Saṅgārava nghe bà Bà-la-môn Dhanañjānī nói như vậy.",
  "mn100:3.3": "Nghe xong, anh ta nói với bà Bà-la-môn Dhanañjānī:",
  "mn100:3.4": "“Bà Bà-la-môn Dhanañjānī này thật là hèn kém, thật là lép vế. Trong khi có các Bà-la-môn thông suốt ba bộ Vệ-đà, vậy mà bà lại đi khen ngợi ông sa-môn trọc đầu ấy.”",
  "mn100:3.5": "“Này con, gương mặt dễ mến, con đâu có biết nếp sống và sự hiểu rõ của Đức Thế Tôn ấy.",
  "mn100:3.6": "Này con, gương mặt dễ mến, nếu con biết nếp sống và sự hiểu rõ của Đức Thế Tôn ấy, thì con đã không nghĩ là nên mắng chửi hay khinh chê Ngài.”",
  "mn100:3.7": "“Vậy thì, thưa bà, khi nào sa-môn Gotama đến Cañcalikappa, xin báo cho tôi biết.”",
  "mn100:3.8": "“Vâng, này cậu gương mặt dễ mến,” bà Bà-la-môn Dhanañjānī đáp lại Saṅgārava.",
  "mn100:4.1": "Rồi Đức Thế Tôn đi du hành dần dần trong xứ Kosala và đến Cañcalikappa.",
  "mn100:4.2": "Tại đó, Đức Thế Tôn ở trong vườn xoài của các Bà-la-môn dòng Todeyya tại Cañcalikappa.",
  "mn100:5.1": "Bà Bà-la-môn Dhanañjānī nghe tin: “Đức Thế Tôn đã đến Cañcalikappa, đang ở trong vườn xoài của các Bà-la-môn dòng Todeyya tại Cañcalikappa.”",
  "mn100:5.2": "Rồi bà Bà-la-môn Dhanañjānī đi đến chỗ thanh niên Bà-la-môn Saṅgārava; đến nơi, bà nói với anh ta:",
  "mn100:5.3": "“Này con, gương mặt dễ mến, Đức Thế Tôn ấy nay đã đến Cañcalikappa, đang ở trong vườn xoài của các Bà-la-môn dòng Todeyya tại Cañcalikappa.",
  "mn100:5.4": "Bây giờ con thấy lúc nào thuận tiện thì cứ đi.”",
  "mn100:5.5": "“Vâng, thưa bà,” thanh niên Bà-la-môn Saṅgārava đáp lời bà Bà-la-môn Dhanañjānī, rồi đi đến chỗ Đức Thế Tôn; đến nơi, anh ta chào hỏi thân tình với Đức Thế Tôn.",
  "mn100:5.6": "Sau khi nói chuyện thân tình gợi nhớ tốt đẹp xong, anh ta ngồi xuống một bên. Khi đã ngồi xuống một bên, thanh niên Bà-la-môn Saṅgārava thưa với Đức Thế Tôn:",
  "mn100:6.1": "“Thưa ông Gotama, có một số sa-môn và Bà-la-môn tự nhận rằng họ đã đạt tới chỗ cùng tận, tới bờ bên kia, nhờ sự biết rõ ngay trong đời này, và họ nói rằng mình sống đời trong sạch từ buổi đầu.",
  "mn100:6.2": "Thưa ông Gotama, trong số những sa-môn và Bà-la-môn tự nhận như vậy, ông Gotama thuộc hạng nào?”",
  "mn100:7.1": "“Này Bhāradvāja, ngay cả trong số những người tự nhận rằng họ đã đạt tới chỗ cùng tận, tới bờ bên kia, nhờ sự biết rõ ngay trong đời này, và sống đời trong sạch từ buổi đầu, ta nói rằng vẫn có khác nhau.",
  "mn100:7.2": "Này Bhāradvāja, có một số sa-môn và Bà-la-môn chỉ dựa vào điều được truyền lại.",
  "mn100:7.3": "Họ dựa vào điều được truyền lại mà tự nhận rằng mình đã đạt tới chỗ cùng tận, tới bờ bên kia, nhờ sự biết rõ ngay trong đời này, và sống đời trong sạch từ buổi đầu;",
  "mn100:7.4": "Ví như các Bà-la-môn thông suốt ba bộ Vệ-đà.",
  "mn100:7.5": "Nhưng này Bhāradvāja, có một số người sống đời tu và Bà-la-môn chỉ nhờ lòng tin suông mà nói rằng mình đã đi đến chỗ cùng tận của sự biết rõ ngay trong đời này, và nhận mình sống đời trong sạch từ buổi đầu;",
  "mn100:7.6": "ví như người chỉ dựa vào suy luận và dò xét.",
  "mn100:7.7": "Này Bhāradvāja, có một số người sống đời tu và Bà-la-môn, đối với những điều trước kia chưa từng được nghe, tự mình biết rõ điều ấy, đã đi đến chỗ cùng tận của sự biết rõ ngay trong đời này, và nhận mình sống đời trong sạch từ buổi đầu.",
  "mn100:7.8": "Này Bhāradvāja, trong số những người sống đời tu và Bà-la-môn ấy, những người đối với những điều trước kia chưa từng được nghe, tự mình biết rõ điều ấy, đã đi đến chỗ cùng tận của sự biết rõ ngay trong đời này, và nhận mình sống đời trong sạch từ buổi đầu, Ta là một người như vậy.",
  "mn100:8.1": "Này Bhāradvāja, điều ấy còn có thể được hiểu theo cách khác nữa, để biết rằng trong số những người sống đời tu và Bà-la-môn, những người đối với những điều trước kia chưa từng được nghe, tự mình biết rõ điều ấy, đã đi đến chỗ cùng tận của sự biết rõ ngay trong đời này, và nhận mình sống đời trong sạch từ buổi đầu, Ta là một người như vậy.",
  "mn100:9.1": "Này Bhāradvāja, trước khi tự mình giác ngộ trọn vẹn, khi còn là vị đang đi tìm sự tỉnh sáng, Ta đã nghĩ như vầy:",
  "mn100:9.2": "‘Đời sống trong nhà thì chật hẹp, là con đường đầy bụi; đời sống không nhà thì rộng thoáng.",
  "mn100:9.3": "Sống ở nhà không dễ gì sống trọn vẹn, thật trong sạch, đời sống trong sạch được gọt giũa kỹ lưỡng.",
  "mn100:9.4": "Hay là ta cạo bỏ tóc râu, khoác áo nhuộm màu đất, rời nhà, sống đời không nhà.’",
  "mn100:9.5": "Rồi này Bhāradvāja, một thời gian sau, khi Ta còn trẻ, tóc còn đen nhánh, đang ở tuổi thanh xuân tốt đẹp, vào độ tuổi đầu đời, dù cha mẹ không muốn, mặt đầy nước mắt, đang khóc, Ta vẫn cạo bỏ tóc râu, khoác áo nhuộm màu đất, rời nhà, sống đời không nhà.",
  "mn100:9.6": "Sau khi ra đi như vậy, trong khi tìm điều lành, tìm kiếm trạng thái yên ổn tốt đẹp cao hơn hết, Ta đến gặp Āḷāra Kālāma. Đến nơi, Ta nói với Āḷāra Kālāma rằng:",
  "mn100:9.7": "‘Này hiền giả Kālāma, tôi muốn sống đời trong sạch theo nếp sống và phép dạy này.’",
  "mn100:9.8": "Khi được nói vậy, này Bhāradvāja, Āḷāra Kālāma nói với Ta:",
  "mn100:9.9": "‘Xin vị đáng kính cứ ở lại.",
  "mn100:9.10": "Nếp sống này là như vậy: người có hiểu biết chẳng bao lâu sẽ tự mình biết rõ, tự mình thấy ra điều bậc thầy mình đã biết, rồi an trú trong đó.’",
  "mn100:9.11": "Này Bhāradvāja, chẳng bao lâu sau, rất nhanh, Ta đã học thuộc nếp sống ấy.",
  "mn100:9.12": "Này Bhāradvāja, rồi chỉ bằng lời nói nơi đầu môi chót lưỡi, chỉ bằng chuyện bàn qua nói lại, Ta đã có thể nói: ‘Tôi nói lời của sự biết, tôi biết lời của bậc già dặn, tôi thấy,’ và không chỉ riêng Ta mà người khác cũng vậy.",
  "mn100:9.13": "Này Bhāradvāja, rồi Ta nghĩ như vầy:",
  "mn100:9.14": "‘Không phải Āḷāra Kālāma chỉ nhờ lòng tin suông mà nói rằng mình tự biết rõ, tự thấy rõ, rồi an trú trong nếp sống này;",
  "mn100:9.15": "chắc chắn Āḷāra Kālāma sống khi đang biết và đang thấy nếp sống này.’",
  "mn100:10.1": "Rồi này Bhāradvāja, Ta đến gặp Āḷāra Kālāma. Đến nơi, Ta nói với Āḷāra Kālāma rằng:",
  "mn100:10.2": "‘Này hiền giả Kālāma, đến mức nào thì thầy nói rằng mình tự biết rõ, tự thấy rõ, rồi an trú trong nếp sống này?’",
  "mn100:10.3": "Khi được nói vậy, này Bhāradvāja, Āḷāra Kālāma nói về cảnh giới không có gì cả.",
  "mn100:10.4": "Này Bhāradvāja, rồi Ta nghĩ như vầy:",
  "mn100:10.5": "‘Không phải chỉ riêng Āḷāra Kālāma mới có lòng tin, Ta cũng có lòng tin;",
  "mn100:10.6": "không phải chỉ riêng Āḷāra Kālāma mới có sức gắng bền, Ta cũng có sức gắng bền;",
  "mn100:10.7": "không phải chỉ riêng Āḷāra Kālāma mới có nhớ biết rõ, Ta cũng có nhớ biết rõ;",
  "mn100:10.8": "không phải chỉ riêng Āḷāra Kālāma mới có tâm yên vững, Ta cũng có tâm yên vững;",
  "mn100:10.9": "không phải chỉ riêng Āḷāra Kālāma mới có sự hiểu rõ, Ta cũng có sự hiểu rõ.’",
  "mn100:10.10": "Rồi ta nghĩ: ‘Hay là ta gắng sức để tự mình biết rõ, tự mình thấy thật điều mà Āḷāra Kālāma nói là ông ấy đã tự mình biết rõ, tự mình thấy thật rồi an trú trong đó.’",
  "mn100:10.11": "Này Bhāradvāja, chẳng bao lâu sau, rất nhanh, ta đã tự mình biết rõ, tự mình thấy thật điều ấy rồi an trú trong đó.",
  "mn100:10.12": "Rồi này Bhāradvāja, ta đi đến chỗ Āḷāra Kālāma. Đến nơi, ta nói với Āḷāra Kālāma:",
  "mn100:10.13": "‘Này hiền giả Kālāma, có phải đến mức này là ông nói rằng mình đã tự mình biết rõ, tự mình thấy thật điều này rồi an trú trong đó chăng?’",
  "mn100:10.14": "‘Này hiền giả, đúng vậy, đến mức này là tôi nói rằng mình đã tự mình biết rõ, tự mình thấy thật điều này rồi an trú trong đó.’",
  "mn100:10.15": "‘Này hiền giả, tôi cũng đến mức này đã tự mình biết rõ, tự mình thấy thật điều này rồi an trú trong đó.’",
  "mn100:10.16": "‘Thật là điều tốt cho chúng ta, này hiền giả, thật là khéo được cho chúng ta, này hiền giả,",
  "mn100:10.17": "vì chúng ta được gặp một người cùng sống đời trong sạch như ngài.’",
  "mn100:10.18": "Như vậy, điều mà tôi tự mình biết rõ, tự mình thấy thật rồi an trú trong đó và chỉ dạy, thì ông cũng tự mình biết rõ, tự mình thấy thật rồi an trú trong đó;",
  "mn100:10.19": "còn điều mà ông tự mình biết rõ, tự mình thấy thật rồi an trú trong đó, thì tôi cũng tự mình biết rõ, tự mình thấy thật rồi an trú trong đó và chỉ dạy.",
  "mn100:10.20": "Như vậy, điều tôi biết thì ông biết; điều ông biết thì tôi biết.",
  "mn100:10.21": "Như tôi thế nào thì ông thế ấy; như ông thế nào thì tôi thế ấy.",
  "mn100:10.22": "Vậy bây giờ, này hiền giả, chúng ta cùng nhau chăm nom nhóm này.’",
  "mn100:10.23": "Này Bhāradvāja, như vậy đó, Āḷāra Kālāma là thầy của ta, nhưng đã đặt ta, là học trò của mình, ngang hàng với chính mình, và còn tỏ lòng quý trọng ta rất mực.",
  "mn100:10.24": "Này Bhāradvāja, rồi ta nghĩ như vầy:",
  "mn100:10.25": "‘Điều này không đưa đến chán lìa, không đưa đến phai nhạt ham muốn, không đưa đến dứt hẳn, không đưa đến lắng yên, không đưa đến biết rõ, không đưa đến tỉnh ngộ trọn vẹn, không đưa đến tắt hẳn khổ đau, mà chỉ đưa đến cõi không có gì.’",
  "mn100:10.26": "Này Bhāradvāja, rồi ta không xem trọng điều ấy, chán nó và bỏ đi.",
  "mn100:11.1": "Này Bhāradvāja, rồi ta, trong khi tìm điều lành, tìm chỗ yên ổn tốt đẹp hơn hết, đã đi đến chỗ Udaka Rāmaputta. Đến nơi, ta nói với Udaka Rāmaputta:",
  "mn100:11.2": "‘Này hiền giả, tôi muốn sống đời trong sạch theo nếp sống và đường lối này.’",
  "mn100:11.3": "Này Bhāradvāja, khi được nói vậy, Udaka Rāmaputta nói với ta:",
  "mn100:11.4": "‘Xin ngài cứ ở lại.",
  "mn100:11.5": "Nếp sống và đường lối này là như vậy: một người sáng dạ chẳng bao lâu sẽ tự mình biết rõ, tự mình thấy thật điều thầy mình đã đạt đến, rồi an trú trong đó.’",
  "mn100:11.6": "Này Bhāradvāja, chẳng bao lâu sau, rất nhanh, ta đã học thuộc điều ấy.",
  "mn100:11.7": "Này Bhāradvāja, chỉ với mức ấy thôi, chỉ bằng việc mấp máy môi và nói năng bàn luận, ta đã có thể nhận rằng: ‘Tôi nói lời của người có hiểu biết, tôi biết lời của bậc già dặn, tôi thấy,’ và không chỉ riêng ta mà người khác cũng vậy.",
  "mn100:11.8": "Này Bhāradvāja, rồi ta nghĩ như vầy:",
  "mn100:11.9": "‘Hẳn không phải Rāma chỉ do lòng tin suông mà nói rằng mình đã tự mình biết rõ, tự mình thấy thật điều này rồi an trú trong đó.",
  "mn100:11.10": "Chắc chắn Rāma đã sống khi biết và thấy điều này.’",
  "mn100:11.11": "Rồi này Bhāradvāja, ta đi đến chỗ Udaka Rāmaputta. Đến nơi, ta nói với Udaka Rāmaputta:",
  "mn100:11.12": "‘Này hiền giả, Rāma đã nói rằng mình tự mình biết rõ, tự mình thấy thật điều này rồi an trú trong đó đến mức nào?’",
  "mn100:11.13": "Khi được hỏi vậy, này Bhāradvāja, Udaka Rāmaputta nói đến cảnh giới không phải còn nhận ra mà cũng không phải không còn nhận ra.",
  "mn100:11.14": "Này Bhāradvāja, khi ấy ta nghĩ rằng:",
  "mn100:11.15": "‘Không phải chỉ riêng Rāma mới có lòng tin, ta cũng có lòng tin;",
  "mn100:11.16": "không phải chỉ riêng Rāma mới có sức gắng sức ...",
  "mn100:11.17": "sự nhớ biết rõ ...",
  "mn100:11.18": "tâm yên vững ...",
  "mn100:11.19": "sự hiểu rõ, ta cũng có sự hiểu rõ.",
  "mn100:11.20": "Hay là ta gắng sức để tự mình biết rõ, tự mình thấy rõ, rồi sống an trú trong điều mà Rāma đã tự mình biết rõ, tự mình thấy rõ, rồi tuyên nói.’",
  "mn100:11.21": "Này Bhāradvāja, rồi chẳng bao lâu, rất nhanh, ta đã tự mình biết rõ, tự mình thấy rõ điều ấy, rồi sống an trú trong đó.",
  "mn100:12.1": "Rồi này Bhāradvāja, ta đi đến chỗ Udaka Rāmaputta. Đến nơi, ta nói với Udaka Rāmaputta rằng:",
  "mn100:12.2": "‘Này hiền giả, có phải Rāma đã tự mình biết rõ, tự mình thấy rõ, rồi tuyên nói điều này đến mức ấy không?’",
  "mn100:12.3": "‘Này hiền giả, đúng vậy, Rāma đã tự mình biết rõ, tự mình thấy rõ, rồi tuyên nói điều này đến mức ấy.’",
  "mn100:12.4": "‘Này hiền giả, ta cũng đã tự mình biết rõ, tự mình thấy rõ, rồi sống an trú trong điều này đến mức ấy.’",
  "mn100:12.5": "‘Thật là điều tốt cho chúng tôi, này hiền giả, thật là khéo được cho chúng tôi, này hiền giả,",
  "mn100:12.6": "khi chúng tôi được gặp một người cùng sống đời sạch trong sạch như ngài.",
  "mn100:12.7": "Điều mà Rāma đã tự mình biết rõ, tự mình thấy rõ, rồi tuyên nói, thì nay ngài cũng đã tự mình biết rõ, tự mình thấy rõ, rồi sống an trú trong điều ấy;",
  "mn100:12.8": "điều mà ngài đã tự mình biết rõ, tự mình thấy rõ, rồi sống an trú trong đó, thì Rāma cũng đã tự mình biết rõ, tự mình thấy rõ, rồi tuyên nói điều ấy.",
  "mn100:12.9": "Vậy điều mà Rāma đã biết rõ thì ngài biết, điều mà ngài biết thì Rāma đã biết rõ.",
  "mn100:12.10": "Vậy Rāma thế nào thì ngài cũng thế ấy, ngài thế nào thì Rāma cũng thế ấy.",
  "mn100:12.11": "Vậy bây giờ, này hiền giả, hãy chăm nom nhóm này.’",
  "mn100:12.12": "Này Bhāradvāja, như vậy, Udaka Rāmaputta, tuy là người cùng sống đời sạch trong sạch với ta, đã đặt ta vào chỗ của thầy, và còn tỏ lòng kính trọng lớn lao đối với ta.",
  "mn100:12.13": "Này Bhāradvāja, khi ấy ta nghĩ rằng:",
  "mn100:12.14": "‘Cách này không đưa đến chán lìa, không đưa đến nhạt bớt ham muốn, không đưa đến dứt hẳn, không đưa đến lắng yên, không đưa đến biết rõ, không đưa đến tỉnh sáng trọn vẹn, không đưa đến tắt hẳn; nó chỉ đưa đến cõi không phải còn tưởng mà cũng không phải không còn tưởng.’",
  "mn100:12.15": "Này Bhāradvāja, rồi ta không xem trọng cách ấy, chán nó và bỏ đi.",
  "mn100:13.1": "Này Bhāradvāja, rồi ta đi tìm điều lành, tìm kiếm chỗ yên ổn tốt đẹp hơn hết, đi dần qua xứ Magadha, lần lượt du hành và đến làng Senānigama ở Uruvelā.",
  "mn100:13.2": "Ở đó, ta thấy một vùng đất thật đẹp, một cụm rừng thật vừa mắt, một con sông chảy trong sáng, có bến xuống nước tốt và đẹp, lại có làng để đi khất thực ở quanh đó.",
  "mn100:13.3": "Này Bhāradvāja, khi ấy ta nghĩ rằng:",
  "mn100:13.4": "‘Thật là một vùng đất đẹp, một cụm rừng vừa mắt, con sông chảy trong sáng, có bến xuống nước tốt và đẹp, lại có làng để đi khất thực ở quanh đây.",
  "mn100:13.5": "Nơi này thật đủ cho một người con nhà lành muốn gắng sức hết mình.’",
  "mn100:13.6": "Này Bhāradvāja, rồi ta ngồi xuống ngay tại đó:",
  "mn100:13.7": "‘Nơi này đủ để gắng sức hết mình.’",
  "mn100:14.1": "Rồi này Bhāradvāja, ta lại nghĩ ra ba ví dụ, lạ lùng, trước đây chưa từng nghe.",
  "mn100:14.2": "Ví như này Bhāradvāja, có khúc gỗ ướt, còn nhựa, bị quăng xuống nước.",
  "mn100:14.3": "Rồi có người đến, cầm thanh gỗ làm lửa trên tay:",
  "mn100:14.4": "‘Ta sẽ làm ra lửa, sẽ làm cho sức nóng hiện ra.’",
  "mn100:14.5": "Này Bhāradvāja, ông nghĩ sao,",
  "mn100:14.6": "người ấy lấy thanh gỗ làm lửa, cọ xát vào khúc gỗ ướt còn nhựa đang nằm dưới nước ấy, có làm ra lửa, có làm cho sức nóng hiện ra được không?”",
  "mn100:14.7": "“Thưa không, thưa ngài Gotama.",
  "mn100:14.8": "Vì sao vậy?",
  "mn100:14.9": "Vì, thưa ngài Gotama, khúc gỗ ấy ướt, còn nhựa, lại còn bị quăng xuống nước;",
  "mn100:14.10": "người ấy chỉ chuốc lấy mệt nhọc và bực bội mà thôi.”",
  "mn100:14.11": "“Cũng vậy, này Bhāradvāja, bất cứ sa môn hay bà la môn nào còn sống chưa lìa các ham muốn bằng cả thân lẫn lòng, và sự thèm muốn, sự dính mắc, sự say đắm, sự khát khao, sự nung nấu đối với các ham muốn ấy vẫn chưa được dứt sạch, chưa được lắng yên ở bên trong, thì dù các vị sa môn hay bà la môn ấy có cảm nhận những cảm giác đau đớn, dữ dội, gắt gao, cay nghiệt do cố sức mà ra, họ vẫn không thể đạt tới sự biết rõ, sự thấy rõ, sự tỉnh ngộ không gì hơn. Dù các vị sa môn hay bà la môn ấy không cảm nhận những cảm giác đau đớn, dữ dội, gắt gao, cay nghiệt do cố sức mà ra, họ vẫn không thể đạt tới sự biết rõ, sự thấy rõ, sự tỉnh ngộ không gì hơn.",
  "mn100:14.12": "Này Bhāradvāja, đó là ví dụ thứ nhất ta nghĩ ra, lạ lùng, trước đây chưa từng nghe.",
  "mn100:15.1": "Rồi này Bhāradvāja, ta lại nghĩ ra ví dụ thứ hai, lạ lùng, trước đây chưa từng nghe.",
  "mn100:15.2": "Ví như này Bhāradvāja, có khúc gỗ ướt, còn nhựa, được để trên đất, xa nước.",
  "mn100:15.3": "Rồi có người đến, cầm thanh gỗ làm lửa trên tay:",
  "mn100:15.4": "‘Ta sẽ làm ra lửa, sẽ làm cho sức nóng hiện ra.’",
  "mn100:15.5": "Này Bhāradvāja, ông nghĩ sao,",
  "mn100:15.6": "người ấy lấy thanh gỗ làm lửa, cọ xát vào khúc gỗ ướt còn nhựa được để trên đất, xa nước ấy, có làm ra lửa, có làm cho sức nóng hiện ra được không?”",
  "mn100:15.7": "“Thưa không, thưa ngài Gotama.",
  "mn100:15.8": "Vì sao vậy?",
  "mn100:15.9": "Vì, thưa ngài Gotama, khúc gỗ ấy ướt, còn nhựa, dù được để trên đất, xa nước;",
  "mn100:15.10": "người ấy chỉ chuốc lấy mệt nhọc và bực bội mà thôi.” “Cũng vậy, này Bhāradvāja, bất cứ sa môn hay bà la môn nào tuy sống tách khỏi các ham muốn bằng cả thân lẫn lòng, nhưng sự thèm muốn, sự dính mắc, sự say đắm, sự khát khao, sự nung nấu đối với các ham muốn ấy vẫn chưa được dứt sạch, chưa được lắng yên ở bên trong, thì dù các vị sa môn hay bà la môn ấy có cảm nhận những cảm giác đau đớn, dữ dội, gắt gao, cay nghiệt do cố sức mà ra, họ vẫn không thể đạt tới sự biết rõ, sự thấy rõ, sự tỉnh ngộ không gì hơn. Dù các vị sa môn hay bà la môn ấy không cảm nhận những cảm giác đau đớn, dữ dội, gắt gao, cay nghiệt do cố sức mà ra, họ vẫn không thể đạt tới sự biết rõ, sự thấy rõ, sự tỉnh ngộ không gì hơn.",
  "mn100:15.11": "Này Bhāradvāja, đó là ví dụ thứ hai ta nghĩ ra, lạ lùng, trước đây chưa từng nghe.",
  "mn100:16.1": "Rồi này Bhāradvāja, ta lại nghĩ ra ví dụ thứ ba, lạ lùng, trước đây chưa từng nghe.",
  "mn100:16.2": "Ví như này Bhāradvāja, có bó củi khô, để trên đất, xa nước.",
  "mn100:16.3": "Rồi có người đến, cầm thanh gỗ làm lửa trên tay:",
  "mn100:16.4": "‘Ta sẽ làm ra lửa, sẽ làm cho sức nóng hiện ra.’",
  "mn100:16.5": "Này Bhāradvāja, ông nghĩ sao,",
  "mn100:16.6": "người ấy lấy thanh gỗ làm lửa, cọ xát vào bó củi khô được để trên đất, xa nước ấy, có làm ra lửa, có làm cho sức nóng hiện ra được không?”",
  "mn100:16.7": "“Thưa được, thưa ngài Gotama.”",
  "mn100:16.8": "Vì sao vậy?",
  "mn100:16.9": "Này ngài Gotama, vì khúc gỗ khô ấy là bó củi khô, lại còn được để trên đất khô, xa nước.",
  "mn100:16.10": "Cũng vậy, này Bhāradvāja, bất cứ vị sa môn hay bà la môn nào sống tách xa các dục cả nơi thân lẫn nơi tâm, và sự ham muốn dục, sự dính mắc dục, sự say đắm dục, sự khát khao dục, sự nung nấu vì dục ở họ đã được dứt sạch bên trong, đã lắng yên hẳn, thì dù các vị sa môn hay bà la môn ấy có cảm nhận những cảm giác đau đớn dữ dội, gắt gao, nhói buốt do cố sức mà ra, họ vẫn có thể đạt tới sự biết rõ, sự thấy rõ, sự tỉnh ngộ không gì hơn. Và dù các vị sa môn hay bà la môn ấy không cảm nhận những cảm giác đau đớn dữ dội, gắt gao, nhói buốt do cố sức mà ra, họ vẫn có thể đạt tới sự biết rõ, sự thấy rõ, sự tỉnh ngộ không gì hơn.",
  "mn100:16.11": "Này Bhāradvāja, đó là ví dụ thứ ba hiện ra với Ta, chưa từng lạ lùng như vậy, trước đây chưa từng nghe đến.",
  "mn100:16.12": "Này Bhāradvāja, ba ví dụ này đã hiện ra với Ta, lạ lùng, trước đây chưa từng nghe đến.",
  "mn100:17.1": "Rồi này Bhāradvāja, Ta nghĩ như vầy:",
  "mn100:17.2": "‘Hay là Ta nghiến răng chặt răng, ép lưỡi lên nóc họng, rồi dùng tâm ghìm tâm lại, đè ép nó, nung nó lên.’",
  "mn100:17.3": "Rồi này Bhāradvāja, Ta nghiến răng chặt răng, ép lưỡi lên nóc họng, dùng tâm ghìm tâm lại, đè ép nó, nung nó lên.",
  "mn100:17.4": "Khi Ta nghiến răng chặt răng, ép lưỡi lên nóc họng, dùng tâm ghìm tâm lại, đè ép nó, nung nó lên như vậy, thì mồ hôi chảy ra từ nách.",
  "mn100:17.5": "Ví như một người khỏe nắm đầu hay nắm vai một người yếu hơn rồi ghìm xuống, đè ép, nung bức người ấy;",
  "mn100:17.6": "cũng vậy, khi Ta nghiến răng chặt răng, ép lưỡi lên nóc họng, dùng tâm ghìm tâm lại, đè ép nó, nung nó lên, thì mồ hôi chảy ra từ nách.",
  "mn100:17.7": "Nhưng sức gắng của Ta vẫn được khơi dậy, không chùng xuống; sự nhớ biết rõ vẫn đứng vững, không lẫn mất; còn thân Ta thì căng cứng, không lắng dịu, vì bị đè nặng bởi sự gắng sức đau đớn ấy.",
  "mn100:18.1": "Rồi này Bhāradvāja, Ta nghĩ như vầy:",
  "mn100:18.2": "‘Hay là Ta ngồi yên không thở.’",
  "mn100:18.3": "Rồi này Bhāradvāja, Ta chặn hơi thở ra hơi thở vào nơi miệng và nơi mũi.",
  "mn100:18.4": "Khi hơi thở ra hơi thở vào nơi miệng và nơi mũi bị chặn lại, thì có tiếng gió thoát ra từ lỗ tai rất mạnh.",
  "mn100:18.5": "Ví như ống bễ của người thợ rèn khi được thổi thì phát ra tiếng rất mạnh;",
  "mn100:18.6": "cũng vậy, khi hơi thở ra hơi thở vào nơi miệng và nơi mũi bị chặn lại, thì có tiếng gió thoát ra từ lỗ tai rất mạnh.",
  "mn100:18.7": "Nhưng sức gắng của Ta vẫn được khơi dậy, không chùng xuống; sự nhớ biết rõ vẫn đứng vững, không lẫn mất; còn thân Ta thì căng cứng, không lắng dịu, vì bị đè nặng bởi sự gắng sức đau đớn ấy.",
  "mn100:19.1": "Rồi này Bhāradvāja, Ta nghĩ như vầy:",
  "mn100:19.2": "‘Hay là Ta ngồi yên không thở.’",
  "mn100:19.3": "Rồi này Bhāradvāja, Ta chặn hơi thở ra hơi thở vào nơi miệng, nơi mũi và nơi tai.",
  "mn100:19.4": "Khi hơi thở ra hơi thở vào nơi miệng, nơi mũi và nơi tai bị chặn lại, thì những luồng gió mạnh dội lên đỉnh đầu Ta.",
  "mn100:19.5": "Ví như một người khỏe lấy mũi nhọn sắc đâm vào đỉnh đầu;",
  "mn100:19.6": "cũng vậy, khi hơi thở ra hơi thở vào nơi miệng, nơi mũi và nơi tai bị chặn lại, thì những luồng gió mạnh dội lên đỉnh đầu Ta.",
  "mn100:19.7": "Nhưng sức gắng của Ta vẫn được khơi dậy, không chùng xuống; sự nhớ biết rõ vẫn đứng vững, không lẫn mất; còn thân Ta thì căng cứng, không lắng dịu, vì bị đè nặng bởi sự gắng sức đau đớn ấy.",
  "mn100:20.1": "Rồi này Bhāradvāja, Ta nghĩ như vầy:",
  "mn100:20.2": "‘Hay là Ta ngồi yên không thở.’",
  "mn100:20.3": "Rồi này Bhāradvāja, Ta chặn hơi thở ra hơi thở vào nơi miệng, nơi mũi và nơi tai.",
  "mn100:20.4": "Khi hơi thở ra hơi thở vào nơi miệng, nơi mũi và nơi tai bị chặn lại, thì trong đầu Ta phát sinh những cơn đau dữ dội ở đầu.",
  "mn100:20.5": "Ví như, này Bhāradvāja, một người khỏe lấy một sợi dây chắc quấn chặt quanh đầu,",
  "mn100:20.6": "cũng vậy, này Bhāradvāja, khi hơi thở ra vào bị chặn ở miệng, mũi và tai, thì trong đầu ta có cảm giác đau dữ dội như bị siết chặt.",
  "mn100:20.7": "Nhưng, này Bhāradvāja, sức gắng của ta vẫn được khơi dậy, không chùng xuống; sự nhớ biết rõ vẫn đứng vững, không lẫn mất. Thân ta căng cứng, không lắng dịu, vì ta đang dốc sức chịu đựng sự đau đớn ấy.",
  "mn100:21.1": "Rồi, này Bhāradvāja, ta nghĩ rằng:",
  "mn100:21.2": "‘Hay là ta hãy dồn tâm vào cách ngồi yên không thở hẳn.’",
  "mn100:21.3": "Rồi, này Bhāradvāja, ta chặn hơi thở ra vào ở miệng, mũi và tai.",
  "mn100:21.4": "Khi hơi thở ra vào bị chặn ở miệng, mũi và tai, thì những luồng gió dữ dội cắt xé bụng ta.",
  "mn100:21.5": "Ví như một người mổ bò khéo tay, hay học trò của người mổ bò, dùng dao bén rạch bụng một con bò,",
  "mn100:21.6": "cũng vậy, này Bhāradvāja, khi hơi thở ra vào bị chặn ở miệng, mũi và tai, thì những luồng gió dữ dội cắt xé bụng ta.",
  "mn100:21.7": "Nhưng, này Bhāradvāja, sức gắng của ta vẫn được khơi dậy, không chùng xuống; sự nhớ biết rõ vẫn đứng vững, không lẫn mất. Thân ta căng cứng, không lắng dịu, vì ta đang dốc sức chịu đựng sự đau đớn ấy.",
  "mn100:22.1": "Rồi, này Bhāradvāja, ta nghĩ rằng:",
  "mn100:22.2": "‘Hay là ta hãy dồn tâm vào cách ngồi yên không thở hẳn.’",
  "mn100:22.3": "Rồi, này Bhāradvāja, ta chặn hơi thở ra vào ở miệng, mũi và tai.",
  "mn100:22.4": "Khi hơi thở ra vào bị chặn ở miệng, mũi và tai, thì toàn thân ta nóng rát dữ dội.",
  "mn100:22.5": "Ví như hai người khỏe nắm hai cánh tay của một người yếu hơn rồi đè người ấy xuống hố than đang cháy cho nóng rát, cho bỏng rát khắp nơi,",
  "mn100:22.6": "cũng vậy, này Bhāradvāja, khi hơi thở ra vào bị chặn ở miệng, mũi và tai, thì toàn thân ta nóng rát dữ dội.",
  "mn100:22.7": "Nhưng, này Bhāradvāja, sức gắng của ta vẫn được khơi dậy, không chùng xuống; sự nhớ biết rõ vẫn đứng vững, không lẫn mất. Thân ta căng cứng, không lắng dịu, vì ta đang dốc sức chịu đựng sự đau đớn ấy.",
  "mn100:23.1": "Lại nữa, này Bhāradvāja, có các vị trời thấy ta thì nói rằng:",
  "mn100:23.2": "‘Sa-môn Gotama đã chết rồi.’",
  "mn100:23.3": "Một số vị trời nói rằng:",
  "mn100:23.4": "‘Sa-môn Gotama chưa chết, nhưng sắp chết.’",
  "mn100:23.5": "Một số vị trời khác nói rằng:",
  "mn100:23.6": "‘Sa-môn Gotama chưa chết, cũng không phải sắp chết;",
  "mn100:23.7": "Sa-môn Gotama là bậc đáng kính, và chỗ ở của bậc đáng kính là như vậy.’",
  "mn100:24.1": "Rồi, này Bhāradvāja, ta nghĩ rằng:",
  "mn100:24.2": "‘Hay là ta dứt hẳn mọi thức ăn.’",
  "mn100:24.3": "Bấy giờ, này Bhāradvāja, các vị trời đến gần ta và nói rằng:",
  "mn100:24.4": "‘Này bạn, xin đừng dứt hẳn mọi thức ăn.",
  "mn100:24.5": "Nếu bạn dứt hẳn mọi thức ăn, thì chúng tôi sẽ rót chất nuôi sống cõi trời vào thân bạn qua các lỗ chân lông.",
  "mn100:24.6": "Nhờ đó bạn sẽ sống được.’",
  "mn100:24.7": "Này Bhāradvāja, khi ấy ta nghĩ như vầy:",
  "mn100:24.8": "‘Nếu ta nói rằng ta hoàn toàn không ăn gì, trong khi các vị trời lại cho chất nuôi thân từ lỗ chân lông đi vào thân ta, và nhờ đó ta sống được,",
  "mn100:24.9": "thì lời ấy của ta sẽ là nói dối.’",
  "mn100:24.10": "Này Bhāradvāja, rồi ta nói rõ với các vị trời ấy, bảo rằng: ‘Thôi.’",
  "mn100:25.1": "Này Bhāradvāja, khi ấy ta nghĩ như vầy:",
  "mn100:25.2": "‘Hay là ta ăn từng chút một, từng nắm nhỏ, hoặc nước đậu xanh, hoặc nước đậu ngựa, hoặc nước đậu Hà Lan, hoặc nước đậu nhỏ.’",
  "mn100:25.3": "Này Bhāradvāja, rồi ta ăn từng chút một, từng nắm nhỏ, hoặc nước đậu xanh, hoặc nước đậu ngựa, hoặc nước đậu Hà Lan, hoặc nước đậu nhỏ.",
  "mn100:25.4": "Này Bhāradvāja, khi ta ăn từng chút một, từng nắm nhỏ, hoặc nước đậu xanh, hoặc nước đậu ngựa, hoặc nước đậu Hà Lan, hoặc nước đậu nhỏ, thân ta gầy mòn đến mức cùng cực.",
  "mn100:25.5": "Ví như những đốt của dây leo khô hay những đốt tre đen; cũng vậy, tay chân ta trở nên như thế vì ăn quá ít.",
  "mn100:25.6": "Ví như dấu chân lạc đà; cũng vậy, chỗ ngồi của ta trở nên như thế vì ăn quá ít.",
  "mn100:25.7": "Ví như một chuỗi hạt tròn; cũng vậy, xương sống của ta lồi lên lõm xuống vì ăn quá ít.",
  "mn100:25.8": "Ví như những cây kèo trong một căn nhà cũ xiêu vẹo, lệch lạc; cũng vậy, xương sườn ta xiêu vẹo, lệch lạc vì ăn quá ít.",
  "mn100:25.9": "Ví như trong một giếng sâu, bóng nước hiện ra nằm sâu hun hút; cũng vậy, tròng mắt ta hiện ra nằm sâu trong hốc mắt vì ăn quá ít.",
  "mn100:25.10": "Ví như trái bầu đắng bị cắt khi còn non, gặp gió nắng thì nhăn nheo, héo quắt; cũng vậy, da đầu ta nhăn nheo, héo quắt vì ăn quá ít.",
  "mn100:25.11": "Này Bhāradvāja, khi ta nghĩ: ‘Ta sẽ sờ da bụng,’ thì ta lại nắm phải xương sống; khi ta nghĩ: ‘Ta sẽ sờ xương sống,’ thì ta lại nắm phải da bụng; da bụng ta dính sát vào xương sống vì ăn quá ít.",
  "mn100:25.12": "Này Bhāradvāja, khi ta muốn đi đại tiện hay tiểu tiện, thì ta ngã úp ngay tại chỗ vì ăn quá ít.",
  "mn100:25.13": "Này Bhāradvāja, khi ta xoa bóp tay chân để làm dịu thân này, thì lông trên thân, gốc đã mục, rụng xuống vì ăn quá ít.",
  "mn100:26.1": "Này Bhāradvāja, có người thấy ta rồi nói: ‘Sa-môn Gotama đen quá.’",
  "mn100:26.2": "Có người khác nói: ‘Sa-môn Gotama không đen, mà xanh xám.’",
  "mn100:26.3": "Có người khác nữa nói: ‘Sa-môn Gotama không đen, cũng không xanh xám, mà da như cá maṅgura.’",
  "mn100:26.4": "Này Bhāradvāja, màu da vốn trong sáng, sạch sẽ của ta đã hư hoại đến mức ấy vì ăn quá ít.",
  "mn100:27.1": "Này Bhāradvāja, khi ấy ta nghĩ như vầy:",
  "mn100:27.2": "‘Bất cứ sa-môn hay bà-la-môn nào trong thời đã qua từng chịu những cảm giác đau đớn dữ dội, gay gắt, khốc liệt do tự ép xác, thì cũng chỉ đến mức này, không hơn được nữa;",
  "mn100:27.3": "bất cứ sa-môn hay bà-la-môn nào trong thời sắp tới sẽ chịu những cảm giác đau đớn dữ dội, gay gắt, khốc liệt do tự ép xác, thì cũng chỉ đến mức này, không hơn được nữa;",
  "mn100:27.4": "bất cứ sa-môn hay bà-la-môn nào ngay bây giờ đang chịu những cảm giác đau đớn dữ dội, gay gắt, khốc liệt do tự ép xác, thì cũng chỉ đến mức này, không hơn được nữa.",
  "mn100:27.5": "Nhưng với lối hành xác cay nghiệt, khó làm này, ta không đạt được điều gì vượt hơn mức người thường, không đạt được sự thấy biết đặc biệt xứng bậc cao quý.",
  "mn100:27.6": "Hay là có một con đường khác đưa đến giác ngộ chăng?’",
  "mn100:28.1": "Này Bhāradvāja, khi ấy ta nghĩ như vầy:",
  "mn100:28.2": "‘Ta nhớ rõ rằng, khi cha ta, người dòng Sakka, đang làm việc ngoài đồng, ta ngồi dưới bóng mát cây jambu, tách khỏi các ham muốn, tách khỏi các điều xấu, ta vào và ở trong tầng lặng tâm thứ nhất, có hướng tâm, có xem xét, có niềm vui và sự dễ chịu sinh ra từ sự lìa xa.",
  "mn100:28.3": "Phải chăng đó là con đường đưa đến giác ngộ?’",
  "mn100:28.4": "Này Bhāradvāja, khi ấy nơi ta khởi lên sự nhận biết đi theo điều ấy:",
  "mn100:28.5": "‘Đây chính là con đường đưa đến sự tỉnh sáng.’",
  "mn100:29.1": "Này Bhāradvāja, khi ấy ta nghĩ rằng:",
  "mn100:29.2": "‘Vì sao ta lại sợ niềm vui ấy, niềm vui không dính đến dục lạc, không dính đến những điều xấu ác?’",
  "mn100:29.3": "Này Bhāradvāja, khi ấy ta nghĩ rằng:",
  "mn100:29.4": "‘Ta không sợ niềm vui ấy, niềm vui không dính đến dục lạc, không dính đến những điều xấu ác.’",
  "mn100:30.1": "Này Bhāradvāja, khi ấy ta nghĩ rằng:",
  "mn100:30.2": "‘Với thân thể đã kiệt quệ đến mức này, thật không dễ gì đạt được niềm vui ấy.",
  "mn100:30.3": "Hay là ta nên ăn thức ăn thô, như cơm và cháo đậu.’",
  "mn100:30.4": "Này Bhāradvāja, rồi ta đã ăn thức ăn thô, như cơm và cháo đậu.",
  "mn100:30.5": "Này Bhāradvāja, lúc ấy có năm vị Tỳ Kheo ở gần bên ta:",
  "mn100:30.6": "‘Sa-môn Gotama đạt được điều gì thì sẽ nói lại cho chúng ta biết.’",
  "mn100:30.7": "Nhưng khi ta ăn thức ăn thô, như cơm và cháo đậu, thì năm vị Tỳ Kheo ấy chán nản bỏ đi:",
  "mn100:30.8": "‘Sa-môn Gotama đã sống dễ dãi, đã rời bỏ sự gắng sức, quay lại nếp sống đầy đủ.’",
  "mn100:31-33.1": "Này Bhāradvāja, rồi ta ăn thức ăn thô, lấy lại sức, lìa hẳn dục lạc … sống an trú trong tầng thiền thứ nhất.",
  "mn100:31-33.2": "Khi những ý nghĩ khởi lên và xét đi xét lại đã lắng xuống, bên trong lắng trong, lòng gom lại thành một, không còn ý nghĩ khởi lên, không còn xét đi xét lại, có niềm vui và sự dễ chịu do tâm yên vững sinh ra, ta sống an trú trong tầng thiền thứ hai …",
  "mn100:31-33.3": "tầng thiền thứ ba …",
  "mn100:31-33.4": "ta sống an trú trong tầng thiền thứ tư.",
  "mn100:34.1": "Khi tâm ta yên vững như vậy, trong sạch, sáng sạch, không nhơ bợn, sạch mọi cấu uế, mềm mại, dễ dùng, vững chắc, không lay động, ta hướng tâm đến sự biết nhớ lại những đời sống trước.",
  "mn100:34.2": "Ta nhớ lại nhiều đời sống trước với nhiều cách khác nhau, như là một đời, hai đời … nhớ lại nhiều đời sống trước cùng với hình dạng và chi tiết như vậy.",
  "mn100:35.1": "Này Bhāradvāja, đó là sự biết rõ thứ nhất mà ta đạt được trong canh đầu của đêm,",
  "mn100:35.2": "sự mù mờ tan đi, sự biết rõ sinh ra; bóng tối tan đi, ánh sáng hiện ra; như với người sống không buông lung, hết lòng gắng sức, chuyên tâm như vậy.",
  "mn100:36-38.1": "Khi tâm ta yên vững như vậy, trong sạch, sáng sạch, không nhơ bợn, sạch mọi cấu uế, mềm mại, dễ dùng, vững chắc, không lay động, ta hướng tâm đến sự biết rõ về sự chết đi và sinh ra của chúng sinh.",
  "mn100:36-38.2": "Với mắt trời trong sạch, vượt hơn mắt người thường, ta thấy chúng sinh chết đi rồi sinh ra, kẻ thấp kẻ cao, người đẹp người xấu, đi đến chỗ lành hay chỗ dữ; ta biết rõ chúng sinh đi theo việc mình đã làm …",
  "mn100:36-38.3": "Này Bhāradvāja, đó là sự biết rõ thứ hai mà ta đạt được trong canh giữa của đêm,",
  "mn100:36-38.4": "sự mù mờ tan đi, sự biết rõ sinh ra; bóng tối tan đi, ánh sáng hiện ra; như với người sống không buông lung, hết lòng gắng sức, chuyên tâm như vậy.",
  "mn100:39.1": "Khi tâm ta yên vững như vậy, trong sạch, sáng sạch, không nhơ bợn, sạch mọi cấu uế, mềm mại, dễ dùng, vững chắc, không lay động, ta hướng tâm đến sự biết rõ về sự dứt sạch các dòng rỉ chảy.",
  "mn100:39.2": "Ta biết đúng như thật: ‘Đây là sự khổ đau’; ta biết đúng như thật: ‘Đây là nguồn gốc của sự khổ đau’; ta biết đúng như thật: ‘Đây là sự chấm dứt của sự khổ đau’; ta biết đúng như thật: ‘Đây là con đường đưa đến sự chấm dứt của sự khổ đau’;",
  "mn100:39.3": "ta biết đúng như thật: ‘Đây là các dòng rỉ chảy’; ta biết đúng như thật: ‘Đây là nguồn gốc của các dòng rỉ chảy’; ta biết đúng như thật: ‘Đây là sự chấm dứt của các dòng rỉ chảy’; ta biết đúng như thật: ‘Đây là con đường đưa đến sự chấm dứt của các dòng rỉ chảy’.",
  "mn100:40.1": "Khi ta biết như vậy, thấy như vậy, tâm ta được buông thoát khỏi dòng rỉ chảy của dục lạc, cũng được buông thoát khỏi dòng rỉ chảy của sự hiện hữu, cũng được buông thoát khỏi dòng rỉ chảy của sự mù mờ.",
  "mn100:40.2": "Khi tâm đã được giải thoát, tôi biết rõ: tâm đã được giải thoát.",
  "mn100:40.3": "Tôi hiểu rõ: sự sinh ra đã dứt, đời sống phạm hạnh đã sống xong, việc cần làm đã làm xong, không còn trở lui trạng thái này nữa.",
  "mn100:41.1": "Này Bhāradvāja, đó là điều biết rõ thứ ba mà ta đạt được vào canh cuối của đêm,",
  "mn100:41.2": "sự không biết đã tan, sự biết rõ đã sinh ra; bóng tối đã tan, ánh sáng đã hiện lên; đúng như vậy với người sống không buông lung, siêng năng, dốc lòng.",
  "mn100:42.1": "Khi được nói vậy, thanh niên Bà-la-môn Saṅgārava thưa với Đức Thế Tôn:",
  "mn100:42.2": "“Sự gắng sức của ngài Gotama thật là bền chắc, sự gắng sức của ngài Gotama thật là của bậc người tốt;",
  "mn100:42.3": "đúng như nơi một vị đã sạch hết lậu hoặc, tự mình biết trọn vẹn.",
  "mn100:42.4": "Thưa ngài Gotama, có các vị trời chăng?”",
  "mn100:42.5": "“Này Bhāradvāja, điều ấy ta biết rõ ngay tại chỗ, đó là—",
  "mn100:42.6": "các vị trời cao hơn.”",
  "mn100:42.7": "“Thưa ngài Gotama, khi được hỏi ‘có các vị trời chăng?’, ngài lại nói ‘này Bhāradvāja, điều ấy ta biết rõ ngay tại chỗ, đó là các vị trời cao hơn’.",
  "mn100:42.8": "Thưa ngài Gotama, nếu vậy chẳng phải là lời rỗng, lời sai sao?”",
  "mn100:42.9": "“Này Bhāradvāja, khi được hỏi ‘có các vị trời chăng?’, ai nói ‘có các vị trời’, ai nói ‘ta biết rõ điều ấy ngay tại chỗ’,",
  "mn100:42.10": "thì ở đây người có hiểu biết phải đi đến kết luận dứt khoát này:",
  "mn100:42.11": "‘có các vị trời’.“",
  "mn100:42.12": "“Nhưng vì sao ngay từ đầu ngài Gotama không trả lời cho tôi như vậy?”",
  "mn100:42.13": "“Này Bhāradvāja, trong đời điều này được mọi người công nhận là cao quý, đó là:",
  "mn100:42.14": "‘có các vị trời’.“",
  "mn100:43.1": "Khi được nói vậy, thanh niên Bà-la-môn Saṅgārava thưa với Đức Thế Tôn:",
  "mn100:43.2": "“Thật hay quá, thưa ngài Gotama, thật hay quá, thưa ngài Gotama.",
  "mn100:43.3": "Ví như dựng vật bị úp xuống lên, mở ra điều bị che kín, chỉ đường cho người lạc lối, đem đèn dầu vào chỗ tối để người có mắt thấy được hình sắc; cũng vậy, ngài Gotama đã dùng nhiều cách làm sáng tỏ lời dạy.",
  "mn100:43.4": "Con xin nương tựa ngài Gotama, nương tựa lời dạy, và nương tựa chúng Tỳ Kheo.",
  "mn100:43.5": "Xin ngài Gotama ghi nhận con là người tại gia nương tựa từ nay cho đến trọn đời.”",
  "mn100:43.6": "Kinh Saṅgārava chấm dứt, bài thứ mười.",
  "mn100:43.7": "Phẩm Bà-la-môn thứ năm chấm dứt.",
  "mn100:44.0": "Bài tóm tắt:",
  "mn100:44.1": "Brahmāyu, Sela, Assalāyana,",
  "mn100:44.2": "Ghoṭamukha và Bà-la-môn;",
  "mn100:44.3": "Caṅkī, rồi Dhanañjāni,",
  "mn100:44.4": "Vāseṭṭha, Subha, Saṅgārava.",
  "mn100:45.0": "Đây là bài kệ tóm tắt các phần:",
  "mn100:45.1": "phần người chủ nhà, phần Tỳ Kheo,",
  "mn100:45.2": "phần mang tên người đi lang thang;",
  "mn100:45.3": "phần vua chúa và phần người đọc lời thiêng,",
  "mn100:45.4": "năm phần trong Bộ Kinh Giữa.",
  "mn100:45.5": "Năm mươi bài kinh ở phần giữa đã xong."
}
window.BILARA["mn100"]["vi"]["mn100:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
