window.BILARA = window.BILARA || {};
window.BILARA["mn101"] = window.BILARA["mn101"] || {};
window.BILARA["mn101"]["vi"] = {
  "mn101:0.1": "Trung Bộ Kinh 101",
  "mn101:0.2": "Kinh ở Devadaha",
  "mn101:1.1": "Tôi nghe như vầy—",
  "mn101:1.2": "Một thời, Đức Thế Tôn ở giữa dân Sakka, tại Devadaha, một thị trấn của người Sakya.",
  "mn101:1.3": "Tại đó, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn101:2.1": "“Này các Tỳ Kheo.”",
  "mn101:2.2": "Các Tỳ Kheo ấy đáp lời Đức Thế Tôn: “Dạ, bạch Thế Tôn.”",
  "mn101:2.3": "Đức Thế Tôn nói như vầy:",
  "mn101:2.4": "“Này các Tỳ Kheo, có một số người sống đời tu và các bà-la-môn nói như vầy, thấy như vầy:",
  "mn101:2.5": "‘Bất cứ điều gì con người này cảm nhận, dù dễ chịu, khổ đau, hay không khổ đau cũng không dễ chịu, tất cả đều do việc đã làm trước đây. ",
  "mn101:2.6": "Vì thế, do làm khổ mình mà việc đã làm cũ đi đến chấm dứt, không làm việc mới, nên về sau không còn chảy ra nữa; ",
  "mn101:2.7": "về sau không còn chảy ra nữa thì việc làm dứt sạch; việc làm dứt sạch thì khổ đau dứt sạch; khổ đau dứt sạch thì cảm giác dứt sạch; cảm giác dứt sạch thì mọi khổ đau sẽ mòn hết.’",
  "mn101:2.8": "Này các Tỳ Kheo, những người Nigaṇṭha nói như vậy.",
  "mn101:3.1": "Này các Tỳ Kheo, khi đến gặp những người Nigaṇṭha và nói chuyện với họ, Ta nói như vầy:",
  "mn101:3.2": "‘Có thật chăng, này các bạn Nigaṇṭha, các vị nói như vầy, thấy như vầy—",
  "mn101:3.3": "bất cứ điều gì con người này cảm nhận, dù dễ chịu, khổ đau, hay không khổ đau cũng không dễ chịu, tất cả đều do việc đã làm trước đây. ",
  "mn101:3.4": "Vì thế, do làm khổ mình mà việc đã làm cũ đi đến chấm dứt, không làm việc mới, nên về sau không còn chảy ra nữa; ",
  "mn101:3.5": "về sau không còn chảy ra nữa thì việc làm dứt sạch; việc làm dứt sạch thì khổ đau dứt sạch; khổ đau dứt sạch thì cảm giác dứt sạch; cảm giác dứt sạch thì mọi khổ đau sẽ mòn hết?’",
  "mn101:3.6": "Này các Tỳ Kheo, khi được hỏi như vậy, những người Nigaṇṭha ấy nhận là: ‘Đúng vậy.’",
  "mn101:4.1": "Rồi Ta nói với họ như vầy:",
  "mn101:4.2": "‘Nhưng này các bạn Nigaṇṭha, các vị có biết rằng—",
  "mn101:4.3": "“Chúng ta thật sự đã có mặt trong thời trước, chứ không phải là đã không có mặt” không?’",
  "mn101:4.4": "‘Không, này bạn.’",
  "mn101:4.5": "‘Nhưng này các bạn Nigaṇṭha, các vị có biết rằng—",
  "mn101:4.6": "“Chúng ta thật sự đã làm điều xấu trong thời trước, chứ không phải là đã không làm” không?’",
  "mn101:4.7": "‘Không, này bạn.’",
  "mn101:4.8": "‘Nhưng này các bạn Nigaṇṭha, các vị có biết rằng—",
  "mn101:4.9": "“Chúng ta đã làm những điều xấu như thế này hay như thế kia” không?’",
  "mn101:4.10": "‘Không, này bạn.’",
  "mn101:4.11": "‘Nhưng này các bạn Nigaṇṭha, các vị có biết rằng—",
  "mn101:4.12": "‘Có phải các ông biết: chừng này sự khổ đau đã mòn hết, chừng này sự khổ đau còn phải làm cho mòn hết, và khi chừng này sự khổ đau đã mòn hết thì mọi sự khổ đau sẽ mòn hết chăng?’",
  "mn101:4.13": "‘Thưa hiền giả, không.’",
  "mn101:4.14": "‘Vậy này các hiền giả Ni Kiền Tử, các ông có biết—",
  "mn101:4.15": "ngay trong đời này, bỏ được các điều xấu của tâm, làm cho các điều lành có mặt chăng?’",
  "mn101:4.16": "‘Thưa hiền giả, không.’",
  "mn101:5.1": "‘Vậy ra này các hiền giả Ni Kiền Tử, các ông không biết—",
  "mn101:5.2": "trước kia chúng tôi có thật đã từng có mặt, hay đã không từng có mặt, các ông không biết—",
  "mn101:5.3": "trước kia chúng tôi có thật đã làm việc xấu, hay đã không làm việc xấu, các ông không biết—",
  "mn101:5.4": "chúng tôi đã làm những việc xấu như thế này hay như thế kia, các ông không biết—",
  "mn101:5.5": "chừng này sự khổ đau đã mòn hết, chừng này sự khổ đau còn phải làm cho mòn hết, và khi chừng này sự khổ đau đã mòn hết thì mọi sự khổ đau sẽ mòn hết, các ông không biết—",
  "mn101:5.6": "ngay trong đời này, bỏ được các điều xấu của tâm, làm cho các điều lành có mặt;",
  "mn101:5.7": "đã vậy thì các vị Ni Kiền Tử không nên nói chắc rằng:",
  "mn101:5.8": "“Bất cứ người này cảm nhận điều gì, vui, khổ đau, hay không khổ đau không vui, tất cả đều do việc đã làm trước đây.",
  "mn101:5.9": "Như vậy, do sự khổ hạnh mà các việc làm cũ đi đến chỗ hết sạch, không làm các việc làm mới, nên về sau không còn chảy tràn nữa;",
  "mn101:5.10": "về sau không còn chảy tràn nên việc làm dứt hết; do việc làm dứt hết nên sự khổ đau dứt hết; do sự khổ đau dứt hết nên cảm giác dứt hết; do cảm giác dứt hết nên mọi sự khổ đau sẽ mòn hết.”",
  "mn101:6.1": "‘Nhưng này các hiền giả Ni Kiền Tử, nếu các ông biết—",
  "mn101:6.2": "trước kia chúng tôi có thật đã từng có mặt, hay đã không từng có mặt, các ông biết—",
  "mn101:6.3": "trước kia chúng tôi có thật đã làm việc xấu, hay đã không làm việc xấu, các ông biết—",
  "mn101:6.4": "chúng tôi đã làm những việc xấu như thế này hay như thế kia, các ông biết—",
  "mn101:6.5": "chừng này sự khổ đau đã mòn hết, chừng này sự khổ đau còn phải làm cho mòn hết, và khi chừng này sự khổ đau đã mòn hết thì mọi sự khổ đau sẽ mòn hết, các ông biết—",
  "mn101:6.6": "ngay trong đời này, bỏ được các điều xấu của tâm, làm cho các điều lành có mặt;",
  "mn101:6.7": "đã vậy thì các vị Ni Kiền Tử có thể nói chắc rằng:",
  "mn101:6.8": "“Bất cứ người này cảm nhận điều gì, vui, khổ đau, hay không khổ đau không vui, tất cả đều do việc đã làm trước đây.",
  "mn101:6.9": "Như vậy, do sự khổ hạnh mà các việc làm cũ đi đến chỗ hết sạch, không làm các việc làm mới, nên về sau không còn chảy tràn nữa;",
  "mn101:6.10": "về sau không còn chảy tràn nên việc làm dứt hết; do việc làm dứt hết nên sự khổ đau dứt hết; do sự khổ đau dứt hết nên cảm giác dứt hết; do cảm giác dứt hết nên mọi sự khổ đau sẽ mòn hết.”",
  "mn101:7.1": "‘Ví như này các hiền giả Ni Kiền Tử, có một người bị mũi tên có thuốc độc bắn trúng, thuốc độc bám chặt vào đó.",
  "mn101:7.2": "Người ấy vì mũi tên đâm nên cảm thấy những cảm giác khổ đau dữ dội, gắt buốt.",
  "mn101:7.3": "Bạn bè, người thân, bà con ruột thịt của người ấy mời một thầy thuốc giỏi về rút mũi tên.",
  "mn101:7.4": "Thầy thuốc ấy dùng dao rạch rộng miệng vết thương.",
  "mn101:7.5": "Người ấy vì bị dao rạch miệng vết thương nên cũng cảm thấy những cảm giác khổ đau dữ dội, gắt buốt.”",
  "mn101:7.6": "Rồi người thầy thuốc mổ xẻ ấy dùng que dò để tìm mũi tên.",
  "mn101:7.7": "Vì việc dùng que dò tìm mũi tên ấy, người đó cảm thấy đau đớn dữ dội, nhói buốt.",
  "mn101:7.8": "Rồi người thầy thuốc mổ xẻ ấy rút mũi tên ra.",
  "mn101:7.9": "Vì việc rút mũi tên ấy, người đó cảm thấy đau đớn dữ dội, nhói buốt.",
  "mn101:7.10": "Rồi người thầy thuốc mổ xẻ ấy đặt thuốc nóng lên miệng vết thương.",
  "mn101:7.11": "Vì việc đặt thuốc nóng lên miệng vết thương ấy, người đó cảm thấy đau đớn dữ dội, nhói buốt.",
  "mn101:7.12": "Một thời gian sau, khi vết thương đã lành, da đã kéo lại, người đó hết bệnh, dễ chịu, nhẹ nhàng, tự chủ, muốn đi đâu thì đi.",
  "mn101:7.13": "Người đó nghĩ như vầy:",
  "mn101:7.14": "“Trước đây ta đã bị mũi tên đâm trúng, có thuốc độc, lại dính chặt vào thịt.",
  "mn101:7.15": "Vì bị mũi tên đâm, ta đã cảm thấy đau đớn dữ dội, nhói buốt.",
  "mn101:7.16": "Rồi bạn bè, người thân và bà con ruột thịt của ta đã mời một người thầy thuốc mổ xẻ đến chữa.",
  "mn101:7.17": "Người thầy thuốc mổ xẻ ấy đã dùng dao rạch miệng vết thương cho ta.",
  "mn101:7.18": "Vì việc dùng dao rạch miệng vết thương ấy, ta đã cảm thấy đau đớn dữ dội, nhói buốt.",
  "mn101:7.19": "Rồi người thầy thuốc mổ xẻ ấy đã dùng que dò để tìm mũi tên cho ta.",
  "mn101:7.20": "Vì việc dùng que dò tìm mũi tên ấy, ta đã cảm thấy đau đớn dữ dội, nhói buốt.",
  "mn101:7.21": "Rồi người thầy thuốc mổ xẻ ấy đã rút mũi tên ra cho ta.",
  "mn101:7.22": "Vì việc rút mũi tên ấy, ta đã cảm thấy đau đớn dữ dội, nhói buốt.",
  "mn101:7.23": "Rồi người thầy thuốc mổ xẻ ấy đã đặt thuốc nóng lên miệng vết thương cho ta.",
  "mn101:7.24": "Vì việc đặt thuốc nóng lên miệng vết thương ấy, ta đã cảm thấy đau đớn dữ dội, nhói buốt.",
  "mn101:7.25": "Còn nay, vết thương của ta đã lành, da đã kéo lại, ta hết bệnh, dễ chịu, nhẹ nhàng, tự chủ, muốn đi đâu thì đi.”",
  "mn101:8.1": "Cũng vậy, này các bạn Nigaṇṭha, nếu các ông biết rằng—",
  "mn101:8.2": "‘trước đây quả thật chúng ta đã từng có mặt, không phải là đã không có mặt’, các ông biết như vậy—",
  "mn101:8.3": "‘trước đây quả thật chúng ta đã làm việc xấu, không phải là đã không làm’, các ông biết như vậy—",
  "mn101:8.4": "‘chúng ta đã làm việc xấu như thế này hay như thế kia’, các ông biết như vậy—",
  "mn101:8.5": "‘chừng này sự khổ đau đã được làm cho mòn đi, chừng này sự khổ đau còn phải được làm cho mòn đi nữa, khi chừng này sự khổ đau được làm cho mòn đi thì mọi sự khổ đau sẽ được làm cho mòn đi hết’, các ông biết như vậy—",
  "mn101:8.6": "ngay trong đời này, bỏ được các điều xấu, làm cho các điều lành có mặt;",
  "mn101:8.7": "nếu thật là vậy thì lời đáp của các vị Nigaṇṭha đáng được xem là đúng:",
  "mn101:8.8": "‘Bất cứ người nào cảm nhận điều gì, dù dễ chịu, đau đớn, hay không đau không dễ chịu, tất cả đều do việc đã làm trước đây.",
  "mn101:8.9": "Như vậy, do làm khổ thân mà việc đã làm cũ đi đến chỗ hết sạch, và do không làm việc mới nên về sau không còn chảy ra nữa.",
  "mn101:8.10": "Về sau không còn chảy ra nữa thì việc làm dứt hết; việc làm dứt hết thì sự khổ đau dứt hết; sự khổ đau dứt hết thì cảm giác dứt hết; cảm giác dứt hết thì mọi sự khổ đau sẽ được làm cho mòn đi hết.’",
  "mn101:9.1": "Này các bạn Ni Kiền Tử, vì các ông không biết rằng—",
  "mn101:9.2": "trước kia chúng ta có thật sự đã từng có mặt hay không, các ông không biết—",
  "mn101:9.3": "trước kia chúng ta có thật sự đã làm việc xấu hay không, các ông không biết—",
  "mn101:9.4": "đã làm những việc xấu như thế này hay như thế kia, các ông không biết—",
  "mn101:9.5": "đã mòn hết bao nhiêu khổ đau, còn phải làm cho mòn hết bao nhiêu khổ đau nữa, và khi chừng ấy khổ đau đã mòn hết thì mọi khổ đau sẽ mòn hết, các ông không biết—",
  "mn101:9.6": "ngay trong đời này, việc buông bỏ những điều xấu và làm cho lớn lên những điều lành;",
  "mn101:9.7": "vì vậy, các vị Ni Kiền Tử không nên quả quyết rằng:",
  "mn101:9.8": "‘Bất cứ người nào cảm nhận điều dễ chịu, khổ đau, hay không khổ không dễ chịu, tất cả đều do việc đã làm trước đây.",
  "mn101:9.9": "Nhờ tự hành xác mà những việc cũ chấm dứt, không làm việc mới, nên về sau không còn chảy tràn nữa;",
  "mn101:9.10": "về sau không còn chảy tràn nên việc làm dứt; việc làm dứt nên khổ đau dứt; khổ đau dứt nên cảm giác dứt; cảm giác dứt nên mọi khổ đau sẽ mòn hết.’",
  "mn101:10.1": "Này các Tỳ Kheo, khi được nói vậy, những người Ni Kiền Tử ấy nói với ta rằng:",
  "mn101:10.2": "‘Này bạn, Ni Kiền Tử Nāṭaputta là người biết hết, thấy hết, tự nhận là có thấy biết trọn vẹn không sót gì.",
  "mn101:10.3": "Vị ấy nói: “Khi ta đi, đứng, ngủ, thức, sự thấy biết luôn luôn có mặt liên tục nơi ta.”",
  "mn101:10.4": "Vị ấy nói như vầy:",
  "mn101:10.5": "“Này các bạn Ni Kiền Tử, các ông có những việc xấu đã làm từ trước, hãy làm cho chúng mòn hết bằng lối khổ hạnh cay nghiệt, khó làm này.",
  "mn101:10.6": "Còn hiện nay, nếu các ông giữ thân, giữ lời nói, giữ ý, thì đó là không làm việc xấu cho về sau.",
  "mn101:10.7": "Như vậy, nhờ tự hành xác mà những việc cũ chấm dứt, không làm việc mới, nên về sau không còn chảy tràn nữa;",
  "mn101:10.8": "về sau không còn chảy tràn nên việc làm dứt; việc làm dứt nên khổ đau dứt; khổ đau dứt nên cảm giác dứt; cảm giác dứt nên mọi khổ đau sẽ mòn hết.”",
  "mn101:10.9": "Điều ấy làm chúng tôi ưng ý và chấp nhận, nên chúng tôi vui lòng.’",
  "mn101:11.1": "Này các Tỳ Kheo, khi được nói vậy, ta nói với những người Ni Kiền Tử ấy rằng:",
  "mn101:11.2": "‘Này các bạn Ni Kiền Tử, có năm điều này, ngay trong đời này, cho ra hai kết quả khác nhau.",
  "mn101:11.3": "Năm điều ấy là gì?",
  "mn101:11.4": "Lòng tin, sự ưa thích, điều được nghe truyền lại, sự suy xét theo dáng vẻ bên ngoài, và sự chấp nhận sau khi ngẫm theo cái thấy của mình—",
  "mn101:11.5": "này các bạn Ni Kiền Tử, đó là năm điều, ngay trong đời này, cho ra hai kết quả khác nhau.",
  "mn101:11.6": "Vậy thì đối với các vị Ni Kiền Tử, về phần quá khứ nơi bậc thầy của mình, lòng tin là gì, sự ưa thích là gì, điều được nghe truyền lại là gì, sự suy xét theo dáng vẻ bên ngoài là gì, sự chấp nhận sau khi ngẫm theo cái thấy của mình là gì?’",
  "mn101:11.7": "Này các Tỳ Kheo, khi ta nói như vậy với những người Ni Kiền Tử, ta không thấy họ có lời đáp trả nào đúng với lẽ phải.",
  "mn101:12.1": "Rồi nữa, này các Tỳ Kheo, ta lại nói với những người Ni Kiền Tử ấy như vầy:",
  "mn101:12.2": "‘Các bạn Ni Kiền Tử nghĩ sao?",
  "mn101:12.3": "Khi nào các ông gắng sức dữ dội, ráng hết mức, thì lúc ấy các ông cảm nhận những cảm giác khổ đau dữ dội, gay gắt, do sự gắng sức ấy gây ra;",
  "mn101:12.4": "còn khi nào các ông không gắng sức dữ dội, không ráng hết mức, thì lúc ấy các ông không cảm nhận những cảm giác khổ đau dữ dội, gay gắt, do sự gắng sức ấy gây ra, có phải vậy không?’",
  "mn101:12.5": "‘Này hiền giả Gotama, khi nào chúng tôi ra sức dữ dội, gắng sức dữ dội, thì khi ấy chúng tôi cảm nhận những cảm giác đau đớn dữ dội, gay gắt, do sự cố sức ấy gây ra;",
  "mn101:12.6": "còn khi nào chúng tôi không ra sức dữ dội, không gắng sức dữ dội, thì khi ấy chúng tôi không cảm nhận những cảm giác đau đớn dữ dội, gay gắt, do sự cố sức ấy gây ra.’",
  "mn101:13.1": "‘Vậy ra, này các hiền giả Nigaṇṭha, khi nào các vị ra sức dữ dội, gắng sức dữ dội, thì khi ấy các vị cảm nhận những cảm giác đau đớn dữ dội, gay gắt, do sự cố sức ấy gây ra;",
  "mn101:13.2": "còn khi nào các vị không ra sức dữ dội, không gắng sức dữ dội, thì khi ấy các vị không cảm nhận những cảm giác đau đớn dữ dội, gay gắt, do sự cố sức ấy gây ra.",
  "mn101:13.3": "Nếu vậy, các vị Nigaṇṭha đáng kính không nên trả lời rằng:",
  "mn101:13.4": "“Bất cứ người nào cảm nhận điều dễ chịu, đau đớn, hay không đau không dễ chịu, thì tất cả đều do việc đã làm trước đây.",
  "mn101:13.5": "Như vậy, do lối khổ hạnh mà việc đã làm cũ được làm cho chấm dứt, không tạo ra việc làm mới, nên về sau không còn chảy ra nữa;",
  "mn101:13.6": "về sau không còn chảy ra nữa thì việc làm dứt sạch; việc làm dứt sạch thì khổ đau dứt sạch; khổ đau dứt sạch thì cảm giác dứt sạch; cảm giác dứt sạch thì mọi khổ đau sẽ bị mài mòn hết.”",
  "mn101:14.1": "Này các hiền giả Nigaṇṭha, nếu khi nào các vị ra sức dữ dội, gắng sức dữ dội, mà khi ấy các vị không cảm nhận những cảm giác đau đớn dữ dội, gay gắt, do sự cố sức ấy gây ra;",
  "mn101:14.2": "còn khi nào các vị không ra sức dữ dội, không gắng sức dữ dội, mà khi ấy các vị lại cảm nhận những cảm giác đau đớn dữ dội, gay gắt, do sự cố sức ấy gây ra;",
  "mn101:14.3": "thì khi ấy các vị Nigaṇṭha đáng kính có thể trả lời rằng:",
  "mn101:14.4": "“Bất cứ người nào cảm nhận điều dễ chịu, đau đớn, hay không đau không dễ chịu, thì tất cả đều do việc đã làm trước đây.",
  "mn101:14.5": "Như vậy, do lối khổ hạnh mà việc đã làm cũ được làm cho chấm dứt, không tạo ra việc làm mới, nên về sau không còn chảy ra nữa;",
  "mn101:14.6": "về sau không còn chảy ra nữa thì việc làm dứt sạch; việc làm dứt sạch thì khổ đau dứt sạch; khổ đau dứt sạch thì cảm giác dứt sạch; cảm giác dứt sạch thì mọi khổ đau sẽ bị mài mòn hết.”",
  "mn101:15.1": "Nhưng này các hiền giả Nigaṇṭha, vì khi nào các vị ra sức dữ dội, gắng sức dữ dội, thì khi ấy các vị cảm nhận những cảm giác đau đớn dữ dội, gay gắt, do sự cố sức ấy gây ra;",
  "mn101:15.2": "còn khi nào các vị không ra sức dữ dội, không gắng sức dữ dội, thì khi ấy các vị không cảm nhận những cảm giác đau đớn dữ dội, gay gắt, do sự cố sức ấy gây ra;",
  "mn101:15.3": "nên chính khi đang cảm nhận những cảm giác đau đớn dữ dội, gay gắt, do sự cố sức ấy gây ra, các vị chín muồi trong không biết rõ, không hay biết, và mê mờ rằng:",
  "mn101:15.4": "“Bất cứ người nào cảm nhận điều dễ chịu, đau đớn, hay không đau không dễ chịu, thì tất cả đều do việc đã làm trước đây.",
  "mn101:15.5": "Như vậy, do lối khổ hạnh mà việc đã làm cũ được làm cho chấm dứt, không tạo ra việc làm mới, nên về sau không còn chảy ra nữa;",
  "mn101:15.6": "về sau không còn chảy ra nữa thì việc làm dứt sạch; việc làm dứt sạch thì khổ đau dứt sạch; khổ đau dứt sạch thì cảm giác dứt sạch; cảm giác dứt sạch thì mọi khổ đau sẽ bị mài mòn hết.”’",
  "mn101:15.7": "Dù nói như vậy, này các Tỳ Kheo, Ta không thấy nơi các Nigaṇṭha có được một lời đáp trả nào hợp lẽ.",
  "mn101:16.1": "Lại nữa, này các Tỳ Kheo, Ta nói với các Nigaṇṭha ấy như sau:",
  "mn101:16.2": "‘Các hiền giả Nigaṇṭha nghĩ sao, việc đã làm nào cho quả phải cảm nhận ngay trong đời này, có thể nhờ ra sức hay gắng sức mà thành ra cho quả phải cảm nhận ở đời sau được chăng?’",
  "mn101:16.3": "‘Không thể vậy, này hiền giả.’",
  "mn101:16.4": "‘Còn việc đã làm nào cho quả phải cảm nhận ở đời sau, có thể nhờ ra sức hay gắng sức mà thành ra cho quả phải cảm nhận ngay trong đời này được chăng?’",
  "mn101:16.5": "‘Không thể vậy, này hiền giả.’",
  "mn101:17.1": "‘Các hiền giả Nigaṇṭha nghĩ sao, việc đã làm nào cho quả là điều dễ chịu, có thể nhờ ra sức hay gắng sức mà thành ra điều đau đớn được chăng?’",
  "mn101:17.2": "‘Không thể vậy, này hiền giả.’",
  "mn101:17.3": "‘Còn việc đã làm nào cho quả là điều đau đớn, có thể nhờ ra sức hay gắng sức mà thành ra điều dễ chịu được chăng?’",
  "mn101:17.4": "‘Không thể vậy, này hiền giả.’",
  "mn101:18.1": "“Này các bạn Nigaṇṭha, các bạn nghĩ sao: việc làm nào đưa đến cảm nhận khi đã chín muồi, có thể do ra sức hay do gắng sức mà thành ra cảm nhận khi chưa chín muồi được chăng?”",
  "mn101:18.2": "“Không được đâu, này bạn.”",
  "mn101:18.3": "“Còn việc làm nào đưa đến cảm nhận khi chưa chín muồi, có thể do ra sức hay do gắng sức mà thành ra cảm nhận khi đã chín muồi được chăng?”",
  "mn101:18.4": "“Không được đâu, này bạn.”",
  "mn101:19.1": "“Này các bạn Nigaṇṭha, các bạn nghĩ sao: việc làm nào đưa đến cảm nhận nhiều, có thể do ra sức hay do gắng sức mà thành ra cảm nhận ít được chăng?”",
  "mn101:19.2": "“Không được đâu, này bạn.”",
  "mn101:19.3": "“Còn việc làm nào đưa đến cảm nhận ít, có thể do ra sức hay do gắng sức mà thành ra cảm nhận nhiều được chăng?”",
  "mn101:19.4": "“Không được đâu, này bạn.”",
  "mn101:20.1": "“Này các bạn Nigaṇṭha, các bạn nghĩ sao: việc làm nào đưa đến cảm nhận, có thể do ra sức hay do gắng sức mà thành ra không cảm nhận được chăng?”",
  "mn101:20.2": "“Không được đâu, này bạn.”",
  "mn101:20.3": "“Còn việc làm nào không đưa đến cảm nhận, có thể do ra sức hay do gắng sức mà thành ra có cảm nhận được chăng?”",
  "mn101:20.4": "“Không được đâu, này bạn.”",
  "mn101:21.1": "“Vậy thì, này các bạn Nigaṇṭha, việc làm nào đưa đến cảm nhận ngay trong đời này thì không thể do ra sức hay do gắng sức mà thành ra cảm nhận ở đời sau; việc làm nào đưa đến cảm nhận ở đời sau thì không thể do ra sức hay do gắng sức mà thành ra cảm nhận ngay trong đời này; việc làm nào đưa đến cảm nhận dễ chịu thì không thể do ra sức hay do gắng sức mà thành ra cảm nhận khổ đau; việc làm nào đưa đến cảm nhận khổ đau thì không thể do ra sức hay do gắng sức mà thành ra cảm nhận dễ chịu; việc làm nào đưa đến cảm nhận khi đã chín muồi thì không thể do ra sức hay do gắng sức mà thành ra cảm nhận khi chưa chín muồi; việc làm nào đưa đến cảm nhận khi chưa chín muồi thì không thể do ra sức hay do gắng sức mà thành ra cảm nhận khi đã chín muồi; việc làm nào đưa đến cảm nhận nhiều thì không thể do ra sức hay do gắng sức mà thành ra cảm nhận ít; việc làm nào đưa đến cảm nhận ít thì không thể do ra sức hay do gắng sức mà thành ra cảm nhận nhiều; việc làm nào đưa đến cảm nhận thì không thể do ra sức hay do gắng sức mà thành ra không cảm nhận; việc làm nào không đưa đến cảm nhận thì không thể do ra sức hay do gắng sức mà thành ra có cảm nhận.”",
  "mn101:21.2": "“Nếu vậy thì sự ra sức của các vị Nigaṇṭha là không có kết quả, sự gắng sức cũng không có kết quả.”",
  "mn101:22.1": "Này các Tỳ Kheo, Nigaṇṭha nói như vậy.",
  "mn101:22.2": "Này các Tỳ Kheo, với những người Nigaṇṭha nói như vậy, có mười cách bắt bẻ hợp lẽ đưa họ đến chỗ đáng chê.",
  "mn101:22.3": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận khổ đau và dễ chịu do việc đã làm trước đây,",
  "mn101:22.4": "thì chắc hẳn các Nigaṇṭha trước đây đã làm việc xấu, nên nay mới cảm nhận những nỗi đau đớn dữ dội, gắt gao như vậy.",
  "mn101:22.5": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận khổ đau và dễ chịu do đấng tạo hóa tạo ra,",
  "mn101:22.6": "thì chắc hẳn các Nigaṇṭha đã bị một đấng tạo hóa xấu ác tạo ra, nên nay mới cảm nhận những nỗi đau đớn dữ dội, gắt gao như vậy.",
  "mn101:22.7": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận khổ đau và dễ chịu do sự kết hợp của các duyên,",
  "mn101:22.8": "thì chắc hẳn các Nigaṇṭha có sự kết hợp xấu ác, nên nay mới cảm nhận những nỗi đau đớn dữ dội, gắt gao như vậy.",
  "mn101:22.9": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận khổ đau và dễ chịu do sinh loại,",
  "mn101:22.10": "thì chắc hẳn các Nigaṇṭha thuộc sinh loại xấu ác, nên nay mới cảm nhận những nỗi đau đớn dữ dội, gắt gao như vậy.",
  "mn101:22.11": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận khổ đau và dễ chịu do sự ra sức trong đời này,",
  "mn101:22.12": "thì chắc hẳn các Nigaṇṭha đang có sự ra sức như vậy, nên nay mới cảm nhận những nỗi đau đớn dữ dội, gắt gao như vậy.",
  "mn101:22.13": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận khổ đau và dễ chịu do việc đã làm trước đây, thì các Nigaṇṭha đáng chê;",
  "mn101:22.14": "còn nếu chúng sinh không cảm nhận khổ đau và dễ chịu do việc đã làm trước đây, thì các Nigaṇṭha cũng đáng chê.",
  "mn101:22.15": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận khổ đau và dễ chịu do đấng tạo hóa tạo ra, thì các Nigaṇṭha đáng chê;",
  "mn101:22.16": "còn nếu chúng sinh không cảm nhận khổ đau và dễ chịu do đấng tạo hóa tạo ra, thì các Nigaṇṭha cũng đáng chê.",
  "mn101:22.17": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận vui buồn do ở chung với nhau, thì các Ni Kiền Tử đáng bị chê trách;",
  "mn101:22.18": "nếu chúng sinh không cảm nhận vui buồn do ở chung với nhau, thì các Ni Kiền Tử cũng đáng bị chê trách.",
  "mn101:22.19": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận vui buồn do sinh ra trong một hạng nào đó, thì các Ni Kiền Tử đáng bị chê trách;",
  "mn101:22.20": "nếu chúng sinh không cảm nhận vui buồn do sinh ra trong một hạng nào đó, thì các Ni Kiền Tử cũng đáng bị chê trách.",
  "mn101:22.21": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận vui buồn do việc mình làm trong đời này, thì các Ni Kiền Tử đáng bị chê trách;",
  "mn101:22.22": "nếu chúng sinh không cảm nhận vui buồn do việc mình làm trong đời này, thì các Ni Kiền Tử cũng đáng bị chê trách.",
  "mn101:22.23": "Này các Tỳ Kheo, các Ni Kiền Tử nói như vậy.",
  "mn101:22.24": "Này các Tỳ Kheo, với những người nói như vậy là các Ni Kiền Tử, có mười cách bắt bẻ hợp lẽ khiến họ rơi vào chỗ đáng bị chê trách.",
  "mn101:22.25": "Này các Tỳ Kheo, như vậy là sự gắng sức không có kết quả, sự ra sức cũng không có kết quả.",
  "mn101:23.1": "Và này các Tỳ Kheo, thế nào là sự gắng sức có kết quả, sự ra sức có kết quả?",
  "mn101:23.2": "Ở đây, này các Tỳ Kheo, một Tỳ Kheo không tự làm khổ mình bằng khổ đau khi điều ấy chưa xảy ra, cũng không từ bỏ niềm vui đúng lẽ, và không dính mắc vào niềm vui ấy.",
  "mn101:23.3": "Vị ấy hiểu rõ như vầy:",
  "mn101:23.4": "‘Khi ta ra sức dẹp bỏ cái tạo tác làm duyên cho gốc của khổ đau này, thì sự nguội tắt sinh khởi do ra sức dẹp bỏ cái tạo tác ấy; còn khi ta nhìn nó với tâm bình thản, nuôi lớn sự bình thản, thì sự nguội tắt cũng sinh khởi.’",
  "mn101:23.5": "Vậy, đối với gốc nào của khổ đau mà khi ra sức dẹp bỏ cái tạo tác thì sự nguội tắt sinh khởi do ra sức dẹp bỏ cái tạo tác ấy, vị ấy ra sức dẹp bỏ cái tạo tác ở đó.",
  "mn101:23.6": "Còn đối với gốc nào của khổ đau mà khi nhìn với tâm bình thản, nuôi lớn sự bình thản, thì sự nguội tắt sinh khởi, vị ấy nuôi lớn sự bình thản ở đó.",
  "mn101:23.7": "Đối với từng gốc của khổ đau, khi vị ấy ra sức dẹp bỏ cái tạo tác, thì sự nguội tắt sinh khởi do ra sức dẹp bỏ cái tạo tác ấy—",
  "mn101:23.8": "như vậy, khổ đau ấy nơi vị ấy được làm cho mòn dần.",
  "mn101:23.9": "Đối với từng gốc của khổ đau, khi vị ấy nhìn với tâm bình thản, nuôi lớn sự bình thản, thì sự nguội tắt sinh khởi—",
  "mn101:23.10": "như vậy, khổ đau ấy nơi vị ấy được làm cho mòn dần.",
  "mn101:24.1": "Ví như, này các Tỳ Kheo, có một người đàn ông say đắm một người đàn bà, lòng bị buộc chặt, ham muốn mãnh liệt, mong mỏi mãnh liệt.",
  "mn101:24.2": "Người ấy thấy người đàn bà đó đang đứng với một người đàn ông khác, đang nói chuyện, đang cười đùa, đang vui vẻ với nhau.",
  "mn101:24.3": "Này các Tỳ Kheo, các ông nghĩ sao,",
  "mn101:24.4": "khi người đàn ông ấy thấy người đàn bà đó đang đứng với một người đàn ông khác, đang nói chuyện, đang cười đùa, đang vui vẻ với nhau, có phải buồn rầu, than khóc, khổ đau, bứt rứt trong lòng và não nề sẽ sinh khởi nơi ông ta không?”",
  "mn101:24.5": "“Thưa vâng, bạch Thế Tôn.”",
  "mn101:24.6": "“Vì sao vậy?”",
  "mn101:24.7": "“Bạch Thế Tôn, vì người đàn ông ấy say đắm người đàn bà đó, lòng bị buộc chặt, ham muốn mãnh liệt, mong mỏi mãnh liệt.",
  "mn101:24.8": "Cho nên khi thấy người đàn bà đó đang đứng với một người đàn ông khác, đang nói chuyện, đang cười đùa, đang vui vẻ với nhau, thì buồn rầu, than khóc, khổ đau, bứt rứt trong lòng và não nề sẽ sinh khởi nơi ông ta.”",
  "mn101:25.1": "“Rồi này các Tỳ Kheo, người đàn ông ấy nghĩ như vầy:",
  "mn101:25.2": "‘Ta say đắm người đàn bà đó, lòng bị buộc chặt, ham muốn mãnh liệt, mong mỏi mãnh liệt.",
  "mn101:25.3": "Vì vậy, khi ta thấy người đàn bà đó đang đứng với một người đàn ông khác, đang nói chuyện, đang cười đùa, đang vui vẻ với nhau, thì buồn rầu, than khóc, khổ đau, bứt rứt trong lòng và não nề sinh khởi nơi ta.",
  "mn101:25.4": "Người ấy nghĩ: ‘Hay là ta bỏ lòng ham muốn say đắm đối với người đàn bà ấy.’",
  "mn101:25.5": "Rồi người ấy bỏ lòng ham muốn say đắm đối với người đàn bà ấy.",
  "mn101:25.6": "Đến một lúc khác, người ấy thấy người đàn bà ấy đang đứng cùng một người đàn ông khác, đang nói chuyện, đang cười đùa, đang vui vẻ với nhau.",
  "mn101:25.7": "Các Tỳ Kheo nghĩ sao,",
  "mn101:25.8": "khi người đàn ông ấy thấy người đàn bà ấy đang đứng cùng một người đàn ông khác, đang nói chuyện, đang cười đùa, đang vui vẻ với nhau, liệu nơi người ấy có sinh ra buồn rầu, than khóc, khổ đau, bứt rứt trong lòng và não nề không?”",
  "mn101:25.9": "“Thưa không, bạch Đức Thế Tôn.”",
  "mn101:25.10": "“Vì sao vậy?”",
  "mn101:25.11": "“Thưa Đức Thế Tôn, vì người đàn ông ấy đã hết say đắm đối với người đàn bà ấy.",
  "mn101:25.12": "Cho nên khi thấy người đàn bà ấy đang đứng cùng một người đàn ông khác, đang nói chuyện, đang cười đùa, đang vui vẻ với nhau, nơi người ấy không sinh ra buồn rầu, than khóc, khổ đau, bứt rứt trong lòng và não nề.”",
  "mn101:26.1": "“Cũng vậy, này các Tỳ Kheo, một Tỳ Kheo không làm khổ mình bằng sự khổ đau khi điều ấy không đưa tới mục đích, không từ bỏ niềm vui đúng đắn, và không dính mắc vào niềm vui ấy.",
  "mn101:26.2": "Vị ấy hiểu rõ như vầy:",
  "mn101:26.3": "‘Khi ta ra sức dứt bỏ các hoạt động tạo nên gốc của sự khổ đau này, thì sự nguội lạnh đối với gốc khổ đau này sinh ra do ra sức ấy; còn khi ta nhìn gốc của sự khổ đau này với tâm bình thản, nuôi lớn sự bình thản ấy, thì sự nguội lạnh đối với gốc khổ đau này sinh ra.’",
  "mn101:26.4": "Đối với gốc nào của sự khổ đau mà khi vị ấy ra sức dứt bỏ các hoạt động tạo nên nó thì sự nguội lạnh sinh ra do sự ra sức ấy, thì ở đó vị ấy ra sức dứt bỏ các hoạt động ấy;",
  "mn101:26.5": "còn đối với gốc nào của sự khổ đau mà khi vị ấy nhìn với tâm bình thản, nuôi lớn sự bình thản, thì sự nguội lạnh sinh ra, thì ở đó vị ấy nuôi lớn sự bình thản.",
  "mn101:26.6": "Đối với từng gốc của sự khổ đau, khi vị ấy ra sức dứt bỏ các hoạt động tạo nên nó, thì sự nguội lạnh sinh ra do sự ra sức ấy—",
  "mn101:26.7": "như vậy sự khổ đau ấy của vị ấy được mòn dần và chấm dứt.",
  "mn101:26.8": "Đối với từng gốc của sự khổ đau, khi vị ấy nhìn với tâm bình thản, nuôi lớn sự bình thản, thì sự nguội lạnh sinh ra—",
  "mn101:26.9": "như vậy sự khổ đau ấy của vị ấy được mòn dần và chấm dứt.",
  "mn101:26.10": "Như vậy, này các Tỳ Kheo, sự gắng sức có kết quả, sự ra sức có kết quả.",
  "mn101:27.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo suy xét như vầy:",
  "mn101:27.2": "‘Khi ta sống theo sự dễ chịu, thì các điều xấu tăng lên, các điều lành giảm xuống;",
  "mn101:27.3": "còn khi ta ra sức chịu khổ, thì các điều xấu giảm xuống, các điều lành tăng lên.",
  "mn101:27.4": "Hay là ta ra sức chịu khổ.’",
  "mn101:27.5": "Rồi vị ấy ra sức chịu khổ.",
  "mn101:27.6": "Khi vị ấy ra sức chịu khổ, thì các điều xấu giảm xuống, các điều lành tăng lên.",
  "mn101:27.7": "Về sau, vị ấy không còn ra sức chịu khổ nữa.",
  "mn101:27.8": "Vì sao vậy?",
  "mn101:27.9": "Vì, này các Tỳ Kheo, mục đích mà vị Tỳ Kheo ấy ra sức chịu khổ để đạt tới, nay đã làm xong.",
  "mn101:27.10": "Cho nên về sau vị ấy không còn ra sức chịu khổ nữa.",
  "mn101:28.1": "Ví như, này các Tỳ Kheo, một người làm tên hơ nóng mũi tên giữa hai cục than cháy, làm cho nó nóng lên, rồi nắn cho thẳng và dễ dùng.",
  "mn101:29.1": "Này các Tỳ Kheo, khi người làm tên đã hơ nóng cán tên giữa hai cục than, làm cho nó nóng kỹ, nắn cho thẳng, làm cho dùng được, thì về sau người ấy không còn hơ nóng cán tên giữa hai cục than, không còn làm nóng kỹ, nắn cho thẳng, làm cho dùng được nữa.",
  "mn101:29.2": "Vì sao vậy?",
  "mn101:29.3": "Này các Tỳ Kheo, vì mục đích mà người làm tên hơ nóng cán tên giữa hai cục than, làm nóng kỹ, nắn cho thẳng, làm cho dùng được, thì mục đích ấy đã làm xong.",
  "mn101:29.4": "Cho nên về sau người làm tên không còn hơ nóng cán tên giữa hai cục than, không còn làm nóng kỹ, nắn cho thẳng, làm cho dùng được nữa.",
  "mn101:29.5": "Cũng vậy, này các Tỳ Kheo, một Tỳ Kheo suy xét như sau:",
  "mn101:29.6": "‘Khi ta sống dễ dãi thoải mái, những điều xấu tăng lên, những điều lành giảm xuống;",
  "mn101:29.7": "còn khi ta gắng sức chịu khó, những điều xấu giảm xuống, những điều lành tăng lên.",
  "mn101:29.8": "Vậy ta nên gắng sức chịu khó.’",
  "mn101:29.9": "Vị ấy gắng sức chịu khó.",
  "mn101:29.10": "Khi vị ấy gắng sức chịu khó, những điều xấu giảm xuống, những điều lành tăng lên.",
  "mn101:29.11": "Rồi về sau vị ấy không còn gắng sức chịu khó như vậy nữa.",
  "mn101:29.12": "Vì sao vậy?",
  "mn101:29.13": "Này các Tỳ Kheo, vì mục đích mà vị Tỳ Kheo ấy gắng sức chịu khó, thì mục đích ấy đã làm xong.",
  "mn101:29.14": "Cho nên về sau vị ấy không còn gắng sức chịu khó như vậy nữa.",
  "mn101:29.15": "Như vậy, này các Tỳ Kheo, sự bắt tay làm là có kết quả, sự gắng sức là có kết quả.",
  "mn101:30.1": "Lại nữa, này các Tỳ Kheo, ở đời có Như Lai ra đời, là bậc đáng kính, tự mình hiểu trọn vẹn, đủ hiểu biết và nết sống, khéo vượt qua, rõ đời, là người dẫn dắt không ai hơn được đối với những người cần được rèn luyện, là bậc thầy của chư thiên và loài người, là bậc Giác Ngộ, Đức Thế Tôn.",
  "mn101:30.2": "Ngài tự mình biết rõ, tự mình thấy rõ rồi chỉ bày thế gian này cùng với chư thiên, Ma vương, Phạm thiên, cùng hạng tu sĩ, bà-la-môn, cùng loài người và chư thiên.",
  "mn101:30.3": "Ngài giảng dạy lời dạy hay ở đầu, hay ở giữa, hay ở cuối, đủ nghĩa, đủ lời, bày ra nếp sống trong sạch trọn vẹn, tinh sạch hoàn toàn.",
  "mn101:31.1": "Một người chủ nhà, hay con của người chủ nhà, hay một người sinh trong dòng họ nào khác, được nghe lời dạy ấy.",
  "mn101:31.2": "Sau khi nghe lời dạy ấy, người ấy khởi lòng tin nơi Như Lai.",
  "mn101:31.3": "Có được lòng tin ấy, người ấy suy xét như sau:",
  "mn101:31.4": "‘Đời sống ở nhà thì chật hẹp, đầy bụi bặm; đời sống không nhà thì rộng thoáng.",
  "mn101:31.5": "Sống ở nhà không dễ gì sống trọn vẹn, sống thật trong sạch, sống đời phạm hạnh được tinh sạch hoàn toàn như vỏ ốc được mài nhẵn.",
  "mn101:31.6": "Hay là ta cạo bỏ tóc và râu, khoác y màu đất, rời nhà sống không nhà.’",
  "mn101:31.7": "Rồi về sau, người ấy bỏ ít của cải hay nhiều của cải, bỏ ít bà con hay nhiều bà con, cạo bỏ tóc và râu, khoác y màu đất, rời nhà sống không nhà.",
  "mn101:32.1": "Sau khi xuất gia như vậy, vị ấy sống giữ theo sự học và nếp sống của các Tỳ Kheo, từ bỏ giết hại, tránh xa giết hại, bỏ gậy, bỏ dao, biết hổ thẹn, có lòng thương, sống thương xót, mong điều tốt cho mọi loài có sự sống.",
  "mn101:32.2": "Từ bỏ lấy của không cho, tránh xa lấy của không cho, chỉ nhận cái được cho, chờ cái được cho, tự sống trong sạch, không trộm cắp.",
  "mn101:32.3": "Từ bỏ đời sống dâm dục, sống đời trong sạch, sống riêng hẳn, tránh xa việc trai gái.",
  "mn101:32.4": "Từ bỏ nói dối, tránh xa nói dối, nói thật, gắn với sự thật, đáng tin, vững chắc, không lừa dối đời.",
  "mn101:32.5": "Từ bỏ lời nói chia rẽ, tránh xa lời nói chia rẽ; nghe chuyện ở đây không đem nói ở kia để làm họ chia rẽ, nghe chuyện ở kia không đem nói ở đây để làm những người này chia rẽ. Như vậy, vị ấy nối lại những người đã rạn nứt, làm tăng thêm sự gắn bó nơi những người đang thuận hòa, ưa sự hòa hợp, vui với sự hòa hợp, thích sự hòa hợp, nói lời đưa đến hòa hợp.",
  "mn101:32.6": "Vị ấy từ bỏ lời nói thô ác, tránh xa lời nói thô ác; vị ấy nói những lời êm dịu, lọt tai, dễ mến, chạm đến lòng người, nhã nhặn, được nhiều người ưa thích, làm nhiều người vừa lòng.",
  "mn101:32.7": "Vị ấy từ bỏ nói chuyện rỗng không, tránh xa nói chuyện rỗng không; nói đúng lúc, nói đúng sự thật, nói điều có ích, nói điều đúng với lẽ phải, nói điều đúng với nề nếp; lời nói có nền nếp, đúng lúc, rõ ràng, có chừng mực, gắn với điều có ích.",
  "mn101:32.8": "Vị ấy tránh làm hại hạt giống và cây cỏ.",
  "mn101:32.9": "Vị ấy chỉ ăn một bữa, không ăn ban đêm, tránh ăn không đúng giờ.",
  "mn101:32.10": "Vị ấy tránh xem múa, hát, nhạc và các trò vui diễn trò.",
  "mn101:32.11": "Vị ấy tránh dùng vòng hoa, hương thơm, dầu thoa, đồ đeo, đồ làm đẹp và đồ trang sức.",
  "mn101:32.12": "Vị ấy tránh dùng giường cao và giường lớn sang trọng.",
  "mn101:32.13": "Vị ấy tránh nhận vàng bạc.",
  "mn101:32.14": "Vị ấy tránh nhận lúa thóc còn sống.",
  "mn101:32.15": "Vị ấy tránh nhận thịt sống.",
  "mn101:32.16": "Vị ấy tránh nhận đàn bà và thiếu nữ.",
  "mn101:32.17": "Vị ấy tránh nhận tôi trai tớ gái.",
  "mn101:32.18": "Vị ấy tránh nhận dê và cừu.",
  "mn101:32.19": "Vị ấy tránh nhận gà và heo.",
  "mn101:32.20": "Vị ấy tránh nhận voi, bò, ngựa và ngựa cái.",
  "mn101:32.21": "Vị ấy tránh nhận ruộng vườn và đất đai.",
  "mn101:32.22": "Vị ấy tránh làm việc đưa tin, sai phái và chạy việc.",
  "mn101:32.23": "Vị ấy tránh mua bán đổi chác.",
  "mn101:32.24": "Vị ấy tránh gian dối bằng cân, bằng đồ đo và bằng đồ đong.",
  "mn101:32.25": "Vị ấy tránh hối lộ, lừa gạt, bịp bợm và quanh co gian trá.",
  "mn101:32.26": "Vị ấy tránh chặt chém, giết hại, trói buộc, cướp đoạt, trấn lột và dùng sức mạnh ép lấy.",
  "mn101:33.1": "Vị ấy biết đủ với tấm y để che thân, với đồ ăn xin được để nuôi bụng. Vị ấy đi đâu cũng chỉ mang theo những thứ ấy.",
  "mn101:33.2": "Như chim có cánh, bay đến đâu cũng chỉ mang theo đôi cánh của mình,",
  "mn101:33.3": "cũng vậy, Tỳ Kheo biết đủ với tấm y để che thân, với đồ ăn xin được để nuôi bụng; đi đâu cũng chỉ mang theo những thứ ấy.",
  "mn101:33.4": "Vị ấy nhờ nếp sống tốt đẹp cao quý này mà cảm nhận niềm dễ chịu không có gì phải áy náy ở trong lòng.",
  "mn101:34.1": "Vị ấy khi mắt thấy hình sắc thì không nắm giữ tướng chung, không nắm giữ tướng riêng.",
  "mn101:34.2": "Vì nếu sống không giữ gìn cửa mắt thì lòng ham muốn và buồn bực, những điều xấu ác, không khéo lành có thể tràn vào; nên vị ấy thực hành để giữ gìn, bảo vệ cửa mắt, giữ gìn mắt.",
  "mn101:34.3": "Khi tai nghe tiếng …",
  "mn101:34.4": "khi mũi ngửi mùi …",
  "mn101:34.5": "khi lưỡi nếm vị …",
  "mn101:34.6": "thân chạm vật chạm … ",
  "mn101:34.7": "ý nhận biết điều được biết, không nắm lấy tướng chung, không nắm lấy tướng riêng.",
  "mn101:34.8": "Vì nếu sống không giữ gìn cửa ý như vậy, thì lòng ham muốn và buồn bực, những điều xấu ác không lành, sẽ tràn vào. Nên vị ấy thực hành để giữ gìn nó, bảo vệ cửa ý, giữ gìn cửa ý.",
  "mn101:34.9": "Vị ấy, nhờ có sự giữ gìn các cửa giác quan cao quý này, cảm nhận niềm vui trong lòng không vẩn đục.",
  "mn101:35.1": "Vị ấy khi đi tới đi lui đều biết rõ, khi nhìn thẳng nhìn quanh đều biết rõ, khi co tay duỗi tay đều biết rõ, khi mang y bát áo đều biết rõ, khi ăn uống nhai nếm đều biết rõ, khi đi tiêu đi tiểu đều biết rõ, khi đi đứng ngồi nằm, khi thức, khi nói, khi im lặng đều biết rõ.",
  "mn101:36.1": "Vị ấy có đủ nếp sống tốt đẹp cao quý này, có đủ sự bằng lòng cao quý này, có đủ sự giữ gìn các cửa giác quan cao quý này, có đủ sự nhớ biết rõ và tỉnh táo cao quý này,",
  "mn101:36.2": "thì tìm đến chỗ ở vắng: rừng, gốc cây, núi, hang núi, động đá, bãi tha ma, chỗ rừng sâu, khoảng trống ngoài trời, đống rơm.",
  "mn101:36.3": "Sau bữa ăn, đi khất thực trở về, vị ấy ngồi xuống, xếp chân lại, giữ thân ngay thẳng, đặt sự nhớ biết rõ trước mặt.",
  "mn101:37.1": "Vị ấy bỏ lòng ham muốn đối với đời, sống với tâm không còn ham muốn, gột sạch tâm khỏi lòng ham muốn.",
  "mn101:37.2": "Vị ấy bỏ lòng dữ và sự bực bội, sống với tâm không dữ, thương xót vì lợi ích của mọi loài có mạng sống, gột sạch tâm khỏi lòng dữ và sự bực bội.",
  "mn101:37.3": "Vị ấy bỏ sự lười nhác và buồn ngủ, sống không còn lười nhác buồn ngủ, hướng tâm về sáng, nhớ biết rõ và tỉnh táo, gột sạch tâm khỏi sự lười nhác và buồn ngủ.",
  "mn101:37.4": "Vị ấy bỏ sự xao động và ăn năn, sống không xao động, tâm bên trong lắng yên, gột sạch tâm khỏi sự xao động và ăn năn.",
  "mn101:37.5": "Vị ấy bỏ sự ngờ vực, sống vượt qua ngờ vực, không còn phân vân đối với những điều lành, gột sạch tâm khỏi sự ngờ vực.",
  "mn101:38.1": "Vị ấy bỏ năm thứ che lấp này, là những thứ làm bẩn tâm, làm yếu sự hiểu rõ,",
  "mn101:38.2": "tách khỏi các ham muốn, tách khỏi những điều xấu ác không lành, vị ấy vào và an trú tầng thiền thứ nhất, có hướng tâm, có xem xét, có niềm vui và sự dễ chịu do lìa xa mà sinh ra.",
  "mn101:38.3": "Này các Tỳ Kheo, như vậy là sự gắng sức có kết quả, sự tinh cần có kết quả.",
  "mn101:39.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo làm lắng xuống hướng tâm và xem xét, bên trong lặng trong, tâm gom lại một mối, không còn hướng tâm, không còn xem xét, vị ấy vào và an trú tầng thiền thứ hai, có niềm vui và sự dễ chịu do tâm yên vững mà sinh ra.",
  "mn101:39.2": "Này các Tỳ Kheo, như vậy là sự gắng sức có kết quả, sự tinh cần có kết quả.",
  "mn101:40.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo phai nhạt niềm vui rộn ràng, sống buông bỏ, nhớ biết rõ và tỉnh táo, tự thân cảm nhận sự dễ chịu. Vị ấy vào và an trú tầng thiền thứ ba, mà những bậc cao quý nói rằng: ‘Người buông giữ tâm bình thản, nhớ biết rõ, sống dễ chịu’.",
  "mn101:40.2": "Này các Tỳ Kheo, như vậy là sự gắng sức có kết quả, sự tinh cần có kết quả.",
  "mn101:41.1": "Lại nữa, này các Tỳ Kheo, Tỳ Kheo bỏ sự dễ chịu, bỏ sự khổ đau, và trước đó niềm mừng cùng nỗi buồn cũng đã lặng mất, vị ấy vào và an trú tầng thiền thứ tư, không khổ không dễ chịu, trong sạch nhờ buông và nhớ biết rõ.",
  "mn101:41.2": "Này các Tỳ Kheo, như vậy là sự gắng sức có kết quả, sự tinh cần có kết quả.",
  "mn101:42.1": "Khi tâm đã yên vững như vậy, trong sạch, sáng sạch, không nhơ bẩn, hết cấu uế, mềm mại, dễ dùng, vững chắc, không lay động, vị ấy hướng tâm đến sự biết nhớ lại các đời sống trước.",
  "mn101:42.2": "Vị ấy nhớ lại nhiều đời sống trước với nhiều cách khác nhau, như là: một đời, hai đời, ba đời, bốn đời, năm đời, mười đời, hai mươi đời, ba mươi đời, bốn mươi đời, năm mươi đời, một trăm đời, một ngàn đời, một trăm ngàn đời, nhiều thời thế gian co lại, nhiều thời thế gian mở ra, nhiều thời thế gian co lại rồi mở ra: ‘Ở chỗ kia ta có tên như thế này, thuộc dòng họ như thế này, dáng vẻ như thế này, ăn uống như thế này, nếm trải vui buồn như thế này, sống lâu đến mức ấy. Rồi từ đó mất đi, ta sinh ra ở chỗ nọ. Ở chỗ nọ ta cũng có tên như thế này, thuộc dòng họ như thế này, dáng vẻ như thế này, ăn uống như thế này, nếm trải vui buồn như thế này, sống lâu đến mức ấy. Rồi từ đó mất đi, ta sinh ra ở đây.’ Như vậy vị ấy nhớ lại nhiều đời sống trước với hình dạng và chi tiết rõ ràng.",
  "mn101:42.3": "Này các Tỳ Kheo, như vậy là sự gắng sức có kết quả, sự tinh cần có kết quả.",
  "mn101:43.1": "Khi tâm đã yên vững như vậy, trong sạch, sáng sạch, không nhơ bẩn, hết cấu uế, mềm mại, dễ dùng, vững chắc, không lay động, vị ấy hướng tâm đến sự biết về việc chúng sinh chết đi rồi sinh lại.",
  "mn101:43.2": "Với mắt trời trong sạch, vượt hơn mắt người, vị ấy thấy chúng sinh chết đi, sinh lại, kẻ thấp kẻ cao, người đẹp kẻ xấu, đi về chỗ lành hay chỗ dữ; vị ấy hiểu rõ chúng sinh đi theo việc mình đã làm: ‘Quả thật, những chúng sinh này sống với việc làm xấu của thân, việc làm xấu của lời nói, việc làm xấu của ý; chê bai những bậc cao quý, thấy sai, làm theo cái thấy sai. Sau khi thân tan rã, khi chết, họ sinh vào cõi dữ, đường xấu, chỗ sa đọa, địa ngục. Còn những chúng sinh kia sống với việc làm tốt của thân, việc làm tốt của lời nói, việc làm tốt của ý; không chê bai những bậc cao quý, thấy đúng, làm theo cái thấy đúng. Sau khi thân tan rã, khi chết, họ sinh vào chỗ lành, cõi trời.’ Như vậy, với mắt trời trong sạch, vượt hơn mắt người, vị ấy thấy chúng sinh chết đi, sinh lại, kẻ thấp kẻ cao, người đẹp kẻ xấu, đi về chỗ lành hay chỗ dữ; vị ấy hiểu rõ chúng sinh đi theo việc mình đã làm.",
  "mn101:43.3": "Này các Tỳ Kheo, như vậy là sự gắng sức có kết quả, sự tinh cần có kết quả.",
  "mn101:44.1": "Khi tâm đã yên vững như vậy, trong sạch, sáng sạch, không nhơ bẩn, hết cấu uế, mềm mại, dễ dùng, vững chắc, không lay động, vị ấy hướng tâm đến sự biết về sự dứt sạch các dòng chảy ngầm.",
  "mn101:44.2": "Vị ấy hiểu đúng như thật: ‘Đây là sự khổ đau’, hiểu đúng như thật: ‘Đây là nguồn gốc của sự khổ đau’, hiểu đúng như thật: ‘Đây là sự dứt của sự khổ đau’, hiểu đúng như thật: ‘Đây là con đường đưa đến sự dứt của sự khổ đau’;",
  "mn101:44.3": "Vị ấy biết đúng như thật: ‘đây là những dòng chảy ngầm làm tâm rỉ chảy’; biết đúng như thật: ‘đây là nguồn gốc sinh ra những dòng chảy ngầm làm tâm rỉ chảy’; biết đúng như thật: ‘đây là sự dứt hẳn của những dòng chảy ngầm làm tâm rỉ chảy’; biết đúng như thật: ‘đây là con đường đưa đến sự dứt hẳn những dòng chảy ngầm làm tâm rỉ chảy’.",
  "mn101:45.1": "Người ấy biết như vậy, thấy như vậy, nên tâm được buông khỏi dòng chảy ngầm của ham muốn giác quan, tâm được buông khỏi dòng chảy ngầm của muốn tiếp tục hiện hữu, tâm được buông khỏi dòng chảy ngầm của không sáng biết.",
  "mn101:45.2": "Khi tâm đã được buông ra, thì có sự biết rằng: ‘tâm đã được buông ra’.",
  "mn101:45.3": "Người ấy biết rõ: ‘sự sinh ra đã dứt, đời sống trong sạch đã sống xong, việc cần làm đã làm xong, không còn trở lui trạng thái này nữa’.",
  "mn101:45.4": "Này các Tỳ Kheo, gắng sức như vậy là có kết quả, ra sức như vậy là có kết quả.",
  "mn101:46.1": "Này các Tỳ Kheo, Như Lai nói như vậy.",
  "mn101:46.2": "Này các Tỳ Kheo, với những Như Lai nói như vậy, có mười chỗ đáng được khen hợp với lẽ thật đi đến.",
  "mn101:46.3": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận vui buồn do việc đã làm trước đây,",
  "mn101:46.4": "thì chắc chắn Như Lai trước đây đã làm việc lành, nên nay cảm nhận sự dễ chịu vui sướng không còn dòng chảy ngầm như vậy.",
  "mn101:46.5": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận vui buồn do đấng chủ tể tạo ra,",
  "mn101:46.6": "thì chắc chắn Như Lai đã được một đấng chủ tể tốt lành tạo ra, nên nay cảm nhận sự dễ chịu vui sướng không còn dòng chảy ngầm như vậy.",
  "mn101:46.7": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận vui buồn do sự tụ hợp của các duyên,",
  "mn101:46.8": "thì chắc chắn Như Lai có sự tụ hợp tốt lành, nên nay cảm nhận sự dễ chịu vui sướng không còn dòng chảy ngầm như vậy.",
  "mn101:46.9": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận vui buồn do sinh ra trong loại nào,",
  "mn101:46.10": "thì chắc chắn Như Lai được sinh ra tốt lành, nên nay cảm nhận sự dễ chịu vui sướng không còn dòng chảy ngầm như vậy.",
  "mn101:46.11": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận vui buồn do sự gắng sức trong đời này,",
  "mn101:46.12": "thì chắc chắn Như Lai có sự gắng sức tốt lành trong đời này, nên nay cảm nhận sự dễ chịu vui sướng không còn dòng chảy ngầm như vậy.",
  "mn101:46.13": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận vui buồn do việc đã làm trước đây, thì Như Lai đáng được khen;",
  "mn101:46.14": "còn nếu chúng sinh không cảm nhận vui buồn do việc đã làm trước đây, thì Như Lai vẫn đáng được khen.",
  "mn101:46.15": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận vui buồn do đấng chủ tể tạo ra, thì Như Lai đáng được khen;",
  "mn101:46.16": "còn nếu chúng sinh không cảm nhận vui buồn do đấng chủ tể tạo ra, thì Như Lai vẫn đáng được khen.",
  "mn101:46.17": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận vui buồn do sự tụ hợp của các duyên, thì Như Lai đáng được khen;",
  "mn101:46.18": "còn nếu chúng sinh không cảm nhận vui buồn do sự tụ hợp của các duyên, thì Như Lai vẫn đáng được khen.",
  "mn101:46.19": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận vui buồn do sinh ra trong loại nào, thì Như Lai đáng được khen;",
  "mn101:46.20": "còn nếu chúng sinh không cảm nhận vui buồn do sinh ra trong loại nào, thì Như Lai vẫn đáng được khen.",
  "mn101:46.21": "Này các Tỳ Kheo, nếu chúng sinh cảm nhận vui buồn do sự gắng sức trong đời này, thì Như Lai đáng được khen;",
  "mn101:46.22": "còn nếu chúng sinh không cảm nhận vui buồn do sự gắng sức trong đời này, thì Như Lai vẫn đáng được khen.",
  "mn101:46.23": "Này các Tỳ Kheo, Như Lai nói như vậy.",
  "mn101:46.24": "Này các Tỳ Kheo, với những Như Lai nói như vậy, có mười chỗ đáng được khen hợp với lẽ thật này đi đến.’",
  "mn101:46.25": "Đức Thế Tôn đã nói như vậy.",
  "mn101:46.26": "Các Tỳ Kheo vui mừng, ưa thích lời Đức Thế Tôn đã nói.",
  "mn101:46.27": "Kinh ở Devadaha thứ nhất đến đây là hết."
}
window.BILARA["mn101"]["vi"]["mn101:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
