window.BILARA = window.BILARA || {};
window.BILARA["mn11"] = window.BILARA["mn11"] || {};
window.BILARA["mn11"]["vi"] = {
  "mn11:0.1": "Trung Bộ Kinh 11",
  "mn11:0.2": "Kinh Tiếng Rống Sư Tử Nhỏ",
  "mn11:1.1": "Tôi nghe như vầy—",
  "mn11:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, tại Kỳ Viên, vườn của ông Cấp Cô Độc.",
  "mn11:1.3": "Tại đó, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn11:1.4": "“Này các Tỳ Kheo.”",
  "mn11:1.5": "Các Tỳ Kheo ấy thưa với Đức Thế Tôn: “Thưa vâng.”",
  "mn11:1.6": "Đức Thế Tôn nói như sau:",
  "mn11:2.1": "“Này các Tỳ Kheo, chỉ ở đây mới có vị sống đời sạch thứ nhất, ở đây có vị sống đời sạch thứ hai, ở đây có vị sống đời sạch thứ ba, ở đây có vị sống đời sạch thứ tư;",
  "mn11:2.2": "các lời dạy khác đều trống không, không có những người sống đời sạch ấy.",
  "mn11:2.3": "Này các Tỳ Kheo, các thầy hãy cất lên tiếng rống sư tử đúng như vậy.",
  "mn11:3.1": "Nhưng này các Tỳ Kheo, có thể có chuyện những người du sĩ theo giáo phái khác sẽ nói như vầy:",
  "mn11:3.2": "‘Thưa các ngài, các ngài dựa vào đâu, sức mạnh nào khiến các ngài nói như vậy—",
  "mn11:3.3": "chỉ ở đây mới có vị sống đời sạch thứ nhất, ở đây có vị sống đời sạch thứ hai, ở đây có vị sống đời sạch thứ ba, ở đây có vị sống đời sạch thứ tư;",
  "mn11:3.4": "các lời dạy khác đều trống không, không có những người sống đời sạch ấy?’",
  "mn11:3.5": "Này các Tỳ Kheo, khi những người du sĩ theo giáo phái khác nói như vậy, các thầy nên đáp lại họ như vầy:",
  "mn11:3.6": "‘Này bạn, chúng tôi có bốn điều được Đức Thế Tôn, bậc tự mình tỉnh ngộ trọn vẹn, bậc biết rõ thấy rõ, bậc đáng kính, chỉ dạy; khi tự mình thấy có đủ trong mình, chúng tôi nói như vầy—",
  "mn11:3.7": "chỉ ở đây mới có vị sống đời sạch thứ nhất, ở đây có vị sống đời sạch thứ hai, ở đây có vị sống đời sạch thứ ba, ở đây có vị sống đời sạch thứ tư;",
  "mn11:3.8": "các lời dạy khác đều trống không, không có những người sống đời sạch ấy.",
  "mn11:3.9": "Bốn điều ấy là gì?",
  "mn11:3.10": "Này bạn, chúng tôi có lòng tin vững nơi bậc Thầy, có lòng tin vững nơi lời dạy, có sự làm cho trọn vẹn trong nếp sống đúng mực;",
  "mn11:3.11": "hơn nữa, những người cùng đi theo lời dạy này đều đáng mến, dễ thương—",
  "mn11:3.12": "cả người tại nhà lẫn người đã rời nhà sống không nhà.",
  "mn11:3.13": "Này bạn, đó là bốn điều được Đức Thế Tôn, bậc biết rõ thấy rõ, bậc đáng kính, bậc tự mình tỉnh ngộ trọn vẹn, chỉ dạy; khi tự mình thấy có đủ trong mình, chúng tôi nói như vầy—",
  "mn11:3.14": "chỉ ở đây mới có vị sống đời sạch thứ nhất, ở đây có vị sống đời sạch thứ hai, ở đây có vị sống đời sạch thứ ba, ở đây có vị sống đời sạch thứ tư;",
  "mn11:3.15": "các lời dạy khác đều trống không, không có những người sống đời sạch ấy.’",
  "mn11:4.1": "Nhưng này các Tỳ Kheo, có thể có chuyện những người du sĩ theo giáo phái khác sẽ nói như vầy:",
  "mn11:4.2": "‘Này bạn, chúng tôi cũng có lòng tin vững nơi bậc Thầy của chúng tôi, chúng tôi cũng có lòng tin vững nơi lời dạy của chúng tôi, chúng tôi cũng làm cho trọn vẹn những nếp sống đúng mực của chúng tôi,",
  "mn11:4.3": "những người cùng đi theo lời dạy của chúng tôi cũng đáng mến, dễ thương—",
  "mn11:4.4": "cả người tại nhà lẫn người đã rời nhà sống không nhà.’",
  "mn11:4.5": "Ở đây, này các bạn, có gì khác, có gì hơn, có gì không giống nhau giữa các ông và chúng tôi?",
  "mn11:5.1": "Này các Tỳ Kheo, khi những người du sĩ ngoại đạo nói như vậy, hãy hỏi họ như sau:",
  "mn11:5.2": "‘Này các bạn, chỗ đến cuối cùng là một hay là nhiều?’",
  "mn11:5.3": "Này các Tỳ Kheo, nếu trả lời đúng, những người du sĩ ngoại đạo ấy sẽ trả lời như sau:",
  "mn11:5.4": "‘Này các bạn, chỗ đến cuối cùng là một, không phải nhiều.’",
  "mn11:5.5": "‘Này các bạn, chỗ đến cuối cùng ấy là của người còn ham muốn hay của người đã hết ham muốn?’",
  "mn11:5.6": "Này các Tỳ Kheo, nếu trả lời đúng, những người du sĩ ngoại đạo ấy sẽ trả lời như sau:",
  "mn11:5.7": "‘Này các bạn, chỗ đến cuối cùng ấy là của người đã hết ham muốn, không phải của người còn ham muốn.’",
  "mn11:5.8": "‘Này các bạn, chỗ đến cuối cùng ấy là của người còn giận dữ hay của người đã hết giận dữ?’",
  "mn11:5.9": "Này các Tỳ Kheo, nếu trả lời đúng, những người du sĩ ngoại đạo ấy sẽ trả lời như sau:",
  "mn11:5.10": "‘Này các bạn, chỗ đến cuối cùng ấy là của người đã hết giận dữ, không phải của người còn giận dữ.’",
  "mn11:5.11": "‘Này các bạn, chỗ đến cuối cùng ấy là của người còn mê mờ hay của người đã hết mê mờ?’",
  "mn11:5.12": "Này các Tỳ Kheo, nếu trả lời đúng, những người du sĩ ngoại đạo ấy sẽ trả lời như sau:",
  "mn11:5.13": "‘Này các bạn, chỗ đến cuối cùng ấy là của người đã hết mê mờ, không phải của người còn mê mờ.’",
  "mn11:5.14": "‘Này các bạn, chỗ đến cuối cùng ấy là của người còn khát khao hay của người đã hết khát khao?’",
  "mn11:5.15": "Này các Tỳ Kheo, nếu trả lời đúng, những người du sĩ ngoại đạo ấy sẽ trả lời như sau:",
  "mn11:5.16": "‘Này các bạn, chỗ đến cuối cùng ấy là của người đã hết khát khao, không phải của người còn khát khao.’",
  "mn11:5.17": "‘Này các bạn, chỗ đến cuối cùng ấy là của người còn nắm giữ hay của người không còn nắm giữ?’",
  "mn11:5.18": "Này các Tỳ Kheo, nếu trả lời đúng, những người du sĩ ngoại đạo ấy sẽ trả lời như sau:",
  "mn11:5.19": "‘Này các bạn, chỗ đến cuối cùng ấy là của người không còn nắm giữ, không phải của người còn nắm giữ.’",
  "mn11:5.20": "‘Này các bạn, chỗ đến cuối cùng ấy là của người thấy rõ hay của người không thấy rõ?’",
  "mn11:5.21": "Này các Tỳ Kheo, nếu trả lời đúng, những người du sĩ ngoại đạo ấy sẽ trả lời như sau:",
  "mn11:5.22": "‘Này các bạn, chỗ đến cuối cùng ấy là của người thấy rõ, không phải của người không thấy rõ.’",
  "mn11:5.23": "‘Này các bạn, chỗ đến cuối cùng ấy là của người còn thuận theo và chống đối, hay của người không còn thuận theo cũng không còn chống đối?’",
  "mn11:5.24": "Này các Tỳ Kheo, nếu trả lời đúng, những người du sĩ ngoại đạo ấy sẽ trả lời như sau:",
  "mn11:5.25": "‘Này các bạn, chỗ đến cuối cùng ấy là của người không còn thuận theo cũng không còn chống đối, không phải của người còn thuận theo và chống đối.’",
  "mn11:5.26": "‘Này các bạn, chỗ đến cuối cùng ấy là của người thích sự rối rắm của tâm, vui trong sự rối rắm của tâm, hay của người không thích sự rối rắm của tâm, không vui trong sự rối rắm của tâm?’",
  "mn11:5.27": "Này các Tỳ Kheo, nếu trả lời đúng, những người du sĩ ngoại đạo ấy sẽ trả lời như sau:",
  "mn11:5.28": "‘Này các bạn, chỗ đến cuối cùng ấy là của người không thích sự rối rắm của tâm, không vui trong sự rối rắm của tâm, không phải của người thích sự rối rắm của tâm, vui trong sự rối rắm của tâm.’",
  "mn11:6.1": "Này các Tỳ Kheo, có hai cách thấy—",
  "mn11:6.2": "cái thấy cho rằng còn mãi và cái thấy cho rằng mất hẳn. ",
  "mn11:6.3": "Này các Tỳ Kheo, bất cứ sa môn hay bà la môn nào dính vào cái thấy cho rằng còn mãi, theo về cái thấy cho rằng còn mãi, ôm chặt cái thấy cho rằng còn mãi, thì họ chống trái với cái thấy cho rằng mất hẳn. ",
  "mn11:6.4": "Này các Tỳ Kheo, bất cứ sa môn hay bà la môn nào dính vào cái thấy cho rằng mất hẳn, theo về cái thấy cho rằng mất hẳn, ôm chặt cái thấy cho rằng mất hẳn, thì họ chống trái với cái thấy cho rằng còn mãi. ",
  "mn11:7.1": "Này các Tỳ Kheo, bất cứ sa môn hay bà la môn nào không biết đúng như thật về sự sinh khởi, sự tan đi, vị ngọt, mặt hại, và lối ra khỏi hai cái thấy này, thì họ còn ham muốn, còn giận dữ, còn mê mờ, còn khát khao, còn nắm giữ, không phải người thấy rõ, còn thuận theo cái này và chống lại cái kia, ưa sự lan man, thích sự lan man; ",
  "mn11:7.2": "họ không thoát khỏi sinh ra, già đi, chết, buồn sầu, than khóc, khổ đau, bực bội, và tuyệt vọng; ",
  "mn11:7.3": "Ta nói rằng họ không thoát khỏi khổ đau. ",
  "mn11:8.1": "Nhưng này các Tỳ Kheo, bất cứ sa môn hay bà la môn nào biết đúng như thật về sự sinh khởi, sự tan đi, vị ngọt, mặt hại, và lối ra khỏi hai cái thấy này, thì họ đã hết ham muốn, hết giận dữ, hết mê mờ, hết khát khao, không còn nắm giữ, là người thấy rõ, không thuận theo cũng không chống lại, không ưa sự lan man, không thích sự lan man; ",
  "mn11:8.2": "họ thoát khỏi sinh ra, già đi, chết, buồn sầu, than khóc, khổ đau, bực bội, và tuyệt vọng; ",
  "mn11:8.3": "Ta nói rằng họ thoát khỏi khổ đau. ",
  "mn11:9.1": "Này các Tỳ Kheo, có bốn thứ nắm giữ này. ",
  "mn11:9.2": "Bốn thứ ấy là gì? ",
  "mn11:9.3": "Nắm giữ dục lạc, nắm giữ cái thấy, nắm giữ giới cấm và nghi thức, nắm giữ ý nghĩ về cái ta. ",
  "mn11:10.1": "Này các Tỳ Kheo, có một số sa môn và bà la môn tự nhận là nói về sự hiểu thấu mọi thứ nắm giữ. ",
  "mn11:10.2": "Nhưng họ không chỉ bày đúng về sự hiểu thấu mọi thứ nắm giữ—",
  "mn11:10.3": "họ chỉ bày sự hiểu thấu nắm giữ dục lạc, nhưng không chỉ bày sự hiểu thấu nắm giữ cái thấy, không chỉ bày sự hiểu thấu nắm giữ giới cấm và nghi thức, không chỉ bày sự hiểu thấu nắm giữ ý nghĩ về cái ta. ",
  "mn11:10.4": "Vì sao vậy? ",
  "mn11:10.5": "Vì các sa môn và bà la môn ấy không biết đúng như thật ba chỗ này. ",
  "mn11:10.6": "Cho nên các sa môn và bà la môn ấy tuy tự nhận là nói về sự hiểu thấu mọi thứ nắm giữ; ",
  "mn11:10.7": "nhưng họ không chỉ bày đúng về sự hiểu thấu mọi thứ nắm giữ—",
  "mn11:10.8": "họ chỉ bày sự hiểu thấu nắm giữ dục lạc, nhưng không chỉ bày sự hiểu thấu nắm giữ cái thấy, không chỉ bày sự hiểu thấu nắm giữ giới cấm và nghi thức, không chỉ bày sự hiểu thấu nắm giữ ý nghĩ về cái ta. ",
  "mn11:11.1": "Này các Tỳ Kheo, có một số sa môn và bà la môn tự nhận là nói về sự hiểu thấu mọi thứ nắm giữ. ",
  "mn11:11.2": "Nhưng họ không chỉ bày đúng về sự hiểu thấu mọi thứ nắm giữ—",
  "mn11:11.3": "họ chỉ bày sự hiểu thấu nắm giữ dục lạc, chỉ bày sự hiểu thấu nắm giữ cái thấy, nhưng không chỉ bày sự hiểu thấu nắm giữ giới cấm và nghi thức, không chỉ bày sự hiểu thấu nắm giữ ý nghĩ về cái ta. ",
  "mn11:11.4": "Vì sao vậy? ",
  "mn11:11.5": "Vì các sa môn và bà la môn ấy không biết đúng như thật hai chỗ này. ",
  "mn11:11.6": "Cho nên các sa môn và bà la môn ấy tuy tự nhận là nói về sự hiểu thấu mọi thứ nắm giữ; ",
  "mn11:11.7": "nhưng họ không chỉ bày đúng về sự hiểu thấu mọi thứ nắm giữ—",
  "mn11:11.8": "họ chỉ bày sự hiểu thấu nắm giữ dục lạc, chỉ bày sự hiểu thấu nắm giữ cái thấy, nhưng không chỉ bày sự hiểu thấu nắm giữ giới cấm và nghi thức, không chỉ bày sự hiểu thấu nắm giữ ý nghĩ về cái ta. ",
  "mn11:12.1": "Này các Tỳ Kheo, có một số sa môn và bà la môn tự nhận là nói về sự hiểu thấu mọi thứ nắm giữ. ",
  "mn11:12.2": "Nhưng họ không chỉ bày đúng về sự hiểu thấu mọi thứ nắm giữ—",
  "mn11:12.3": "Họ nói đến việc hiểu thấu sự nắm giữ dục lạc, nói đến việc hiểu thấu sự nắm giữ quan điểm, nói đến việc hiểu thấu sự nắm giữ giới cấm và nghi thức, nhưng không nói đến việc hiểu thấu sự nắm giữ ý nghĩ về cái ta.",
  "mn11:12.4": "Vì sao vậy?",
  "mn11:12.5": "Vì các vị sa môn, bà la môn ấy không biết đúng như thật một điểm này.",
  "mn11:12.6": "Cho nên, dù tự nhận là nói về việc hiểu thấu mọi sự nắm giữ,",
  "mn11:12.7": "các vị sa môn, bà la môn ấy không nói đúng về việc hiểu thấu mọi sự nắm giữ—",
  "mn11:12.8": "họ nói đến việc hiểu thấu sự nắm giữ dục lạc, nói đến việc hiểu thấu sự nắm giữ quan điểm, nói đến việc hiểu thấu sự nắm giữ giới cấm và nghi thức, nhưng không nói đến việc hiểu thấu sự nắm giữ ý nghĩ về cái ta.",
  "mn11:13.1": "Này các Tỳ Kheo, trong giáo pháp và nếp sống như vậy, lòng tin nơi bậc thầy không được gọi là đi đúng hướng;",
  "mn11:13.2": "lòng tin nơi lời dạy không được gọi là đi đúng hướng;",
  "mn11:13.3": "sự làm cho trọn vẹn các nết tốt không được gọi là đi đúng hướng;",
  "mn11:13.4": "sự mến thương, vừa lòng đối với những người cùng sống theo lời dạy ấy không được gọi là đi đúng hướng.",
  "mn11:13.5": "Vì sao vậy?",
  "mn11:13.6": "Này các Tỳ Kheo, là vì giáo pháp và nếp sống ấy được nói không khéo, chỉ bày không rõ, không đưa đến vượt thoát, không đưa đến lắng yên, không do bậc tự mình biết trọn vẹn mà chỉ bày.",
  "mn11:14.1": "Này các Tỳ Kheo, còn Như Lai, bậc đáng kính, bậc tự mình biết trọn vẹn, khi nhận là nói về việc hiểu thấu mọi sự nắm giữ, thì nói đúng về việc hiểu thấu mọi sự nắm giữ—",
  "mn11:14.2": "Ngài nói đến việc hiểu thấu sự nắm giữ dục lạc, nói đến việc hiểu thấu sự nắm giữ quan điểm, nói đến việc hiểu thấu sự nắm giữ giới cấm và nghi thức, và nói đến việc hiểu thấu sự nắm giữ ý nghĩ về cái ta.",
  "mn11:15.1": "Này các Tỳ Kheo, trong giáo pháp và nếp sống như vậy, lòng tin nơi bậc thầy được gọi là đi đúng hướng;",
  "mn11:15.2": "lòng tin nơi lời dạy được gọi là đi đúng hướng;",
  "mn11:15.3": "sự làm cho trọn vẹn các nết tốt được gọi là đi đúng hướng;",
  "mn11:15.4": "sự mến thương, vừa lòng đối với những người cùng sống theo lời dạy ấy được gọi là đi đúng hướng.",
  "mn11:15.5": "Vì sao vậy?",
  "mn11:15.6": "Này các Tỳ Kheo, là vì giáo pháp và nếp sống ấy được nói khéo, chỉ bày rõ, đưa đến vượt thoát, đưa đến lắng yên, do bậc tự mình biết trọn vẹn mà chỉ bày.",
  "mn11:16.1": "Này các Tỳ Kheo, đây là bốn sự nắm giữ. Chúng lấy gì làm gốc, do gì mà sinh lên, từ gì mà có mặt, từ gì mà phát ra?",
  "mn11:16.2": "Này các Tỳ Kheo, bốn sự nắm giữ này lấy sự ham muốn làm gốc, do sự ham muốn mà sinh lên, từ sự ham muốn mà có mặt, từ sự ham muốn mà phát ra.",
  "mn11:16.3": "Này các Tỳ Kheo, còn sự ham muốn này lấy gì làm gốc, do gì mà sinh lên, từ gì mà có mặt, từ gì mà phát ra?",
  "mn11:16.4": "Sự ham muốn lấy cảm nhận làm gốc, do cảm nhận mà sinh lên, từ cảm nhận mà có mặt, từ cảm nhận mà phát ra.",
  "mn11:16.5": "Này các Tỳ Kheo, còn cảm nhận này lấy gì làm gốc, do gì mà sinh lên, từ gì mà có mặt, từ gì mà phát ra?",
  "mn11:16.6": "Cảm nhận lấy sự đụng chạm làm gốc, do sự đụng chạm mà sinh lên, từ sự đụng chạm mà có mặt, từ sự đụng chạm mà phát ra.",
  "mn11:16.7": "Này các Tỳ Kheo, còn sự đụng chạm này lấy gì làm gốc, do gì mà sinh lên, từ gì mà có mặt, từ gì mà phát ra?",
  "mn11:16.8": "Sự đụng chạm lấy sáu cửa nhận biết làm gốc, do sáu cửa nhận biết mà sinh lên, từ sáu cửa nhận biết mà có mặt, từ sáu cửa nhận biết mà phát ra.",
  "mn11:16.9": "Này các Tỳ Kheo, còn sáu cửa nhận biết này lấy gì làm gốc, do gì mà sinh lên, từ gì mà có mặt, từ gì mà phát ra?",
  "mn11:16.10": "Sáu cửa nhận biết lấy danh và sắc làm gốc, do danh và sắc mà sinh lên, từ danh và sắc mà có mặt, từ danh và sắc mà phát ra.",
  "mn11:16.11": "Này các Tỳ Kheo, phần gọi là tên gọi và hình sắc này lấy gì làm gốc, từ gì mà sinh ra, do gì mà có mặt, từ gì mà khởi lên?",
  "mn11:16.12": "Tên gọi và hình sắc lấy sự nhận biết làm gốc, từ sự nhận biết mà sinh ra, do sự nhận biết mà có mặt, từ sự nhận biết mà khởi lên.",
  "mn11:16.13": "Này các Tỳ Kheo, phần gọi là sự nhận biết này lấy gì làm gốc, từ gì mà sinh ra, do gì mà có mặt, từ gì mà khởi lên?",
  "mn11:16.14": "Sự nhận biết lấy các hoạt động tạo tác làm gốc, từ các hoạt động tạo tác mà sinh ra, do các hoạt động tạo tác mà có mặt, từ các hoạt động tạo tác mà khởi lên.",
  "mn11:16.15": "Này các Tỳ Kheo, các hoạt động tạo tác này lấy gì làm gốc, từ gì mà sinh ra, do gì mà có mặt, từ gì mà khởi lên?",
  "mn11:16.16": "Các hoạt động tạo tác lấy sự không thấy rõ làm gốc, từ sự không thấy rõ mà sinh ra, do sự không thấy rõ mà có mặt, từ sự không thấy rõ mà khởi lên.",
  "mn11:17.1": "Nhưng này các Tỳ Kheo, khi một Tỳ Kheo đã dứt sự không thấy rõ, và sự thấy rõ đã sinh khởi, thì do đã lìa sự không thấy rõ, do sự thấy rõ sinh khởi, vị ấy không còn nắm giữ sự bám víu vào dục lạc, không còn nắm giữ sự bám víu vào cái thấy, không còn nắm giữ sự bám víu vào giới cấm và nghi thức, không còn nắm giữ sự bám víu vào ý nghĩ về một cái ta.",
  "mn11:17.2": "Không còn nắm giữ thì không run sợ. Không run sợ thì tự mình lặng tắt hẳn ngay trong hiện đời.",
  "mn11:17.3": "Vị ấy hiểu rõ: ‘Sự sinh đã dứt, đời sống phạm hạnh đã sống xong, việc cần làm đã làm xong, không còn trở lui trạng thái này nữa.’",
  "mn11:17.4": "Đức Thế Tôn nói như vậy.",
  "mn11:17.5": "Các Tỳ Kheo ấy vui mừng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn11:17.6": "Kinh Tiếng Gầm Sư Tử Nhỏ chấm dứt."
}
window.BILARA["mn11"]["vi"]["mn11:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";