window.BILARA = window.BILARA || {};
window.BILARA["mn120"] = window.BILARA["mn120"] || {};
window.BILARA["mn120"]["vi"] = {
  "mn120:0.1": "Trung Bộ Kinh 120",
  "mn120:0.2": "Kinh Sinh Về Do Tạo Tác",
  "mn120:1.1": "Tôi nghe như vầy—",
  "mn120:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, trong rừng Kỳ Đà, tại vườn của ông Cấp Cô Độc.",
  "mn120:1.3": "Tại đó, Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn120:1.4": "“Này các Tỳ Kheo.”",
  "mn120:1.5": "Các Tỳ Kheo ấy thưa với Đức Thế Tôn: “Dạ, bạch Thế Tôn.”",
  "mn120:1.6": "Đức Thế Tôn nói như vầy:",
  "mn120:2.1": "“Này các Tỳ Kheo, Ta sẽ giảng cho các ông về sự sinh đến do tạo tác.",
  "mn120:2.2": "Hãy nghe cho kỹ, khéo để tâm, Ta sẽ nói.”",
  "mn120:2.3": "“Dạ, bạch Thế Tôn,” các Tỳ Kheo ấy vâng đáp Đức Thế Tôn.",
  "mn120:2.4": "Đức Thế Tôn nói như vầy:",
  "mn120:3.1": "“Ở đây, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết tốt, nghe học nhiều, biết cho đi, có sự hiểu rõ.",
  "mn120:3.2": "Vị ấy nghĩ như vầy:",
  "mn120:3.3": "‘Mong sao sau khi thân tan rã, sau khi chết, ta được sinh vào cùng chỗ với các nhà quyền quý lớn.’",
  "mn120:3.4": "Vị ấy giữ tâm ấy, đặt tâm ấy vững lại, làm cho tâm ấy lớn mạnh.",
  "mn120:3.5": "Những tạo tác ấy của vị ấy và cách ở tâm ấy, khi được làm cho lớn mạnh, được làm cho nhiều lên như vậy, sẽ đưa đến sự sinh về chỗ ấy.",
  "mn120:3.6": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến sự sinh về chỗ ấy.",
  "mn120:4-5.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết tốt, nghe học nhiều, biết cho đi, có sự hiểu rõ.",
  "mn120:4-5.2": "Vị ấy nghĩ như vầy:",
  "mn120:4-5.3": "‘Mong sao sau khi thân tan rã, sau khi chết, ta được sinh vào cùng chỗ với các nhà Bà-la-môn lớn …",
  "mn120:4-5.4": "hay các nhà chủ lớn.’",
  "mn120:4-5.5": "Vị ấy giữ tâm ấy, đặt tâm ấy vững lại, làm cho tâm ấy lớn mạnh.",
  "mn120:4-5.6": "Những tạo tác ấy của vị ấy và cách ở tâm ấy, khi được làm cho lớn mạnh, được làm cho nhiều lên như vậy, sẽ đưa đến sự sinh về chỗ ấy.",
  "mn120:4-5.7": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến sự sinh về chỗ ấy.",
  "mn120:6.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết tốt, nghe học nhiều, biết cho đi, có sự hiểu rõ.",
  "mn120:6.2": "Vị ấy đã nghe rằng:",
  "mn120:6.3": "‘Các vị trời thuộc nhóm Bốn Vua Trời sống lâu, đẹp đẽ, có nhiều sự dễ chịu.’",
  "mn120:6.4": "Vị ấy nghĩ như vầy:",
  "mn120:6.5": "‘Mong sao sau khi thân tan rã, sau khi chết, ta được sinh vào cùng chỗ với các vị trời thuộc nhóm Bốn Vua Trời.’",
  "mn120:6.6": "Vị ấy hướng tâm đến điều đó, đặt tâm vững vào điều đó, làm cho tâm ấy lớn mạnh.",
  "mn120:6.7": "Những tác ý và cách an trú ấy, khi được làm cho lớn mạnh và lặp đi lặp lại như vậy, sẽ đưa đến việc sinh về cõi ấy.",
  "mn120:6.8": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến việc sinh về cõi ấy.",
  "mn120:7-11.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết tốt, nghe học nhiều, biết cho đi, có sự hiểu rõ.",
  "mn120:7-11.2": "Vị ấy được nghe rằng:",
  "mn120:7-11.3": "chư thiên cõi Ba Mươi Ba …",
  "mn120:7-11.4": "chư thiên cõi Dạ Ma …",
  "mn120:7-11.5": "chư thiên cõi Đâu Suất …",
  "mn120:7-11.6": "chư thiên cõi thích vui với những gì mình tạo ra …",
  "mn120:7-11.7": "chư thiên cõi hưởng quyền trên những gì kẻ khác tạo ra sống lâu, đẹp đẽ, có nhiều sự dễ chịu.",
  "mn120:7-11.8": "Vị ấy nghĩ rằng:",
  "mn120:7-11.9": "‘Mong sao sau khi thân tan rã, sau khi chết, ta được sinh chung với chư thiên cõi hưởng quyền trên những gì kẻ khác tạo ra.’",
  "mn120:7-11.10": "Vị ấy hướng tâm đến điều đó, đặt tâm vững vào điều đó, làm cho tâm ấy lớn mạnh.",
  "mn120:7-11.11": "Những tác ý và cách an trú ấy, khi được làm cho lớn mạnh và lặp đi lặp lại như vậy, sẽ đưa đến việc sinh về cõi ấy.",
  "mn120:7-11.12": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến việc sinh về cõi ấy.",
  "mn120:12.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết tốt, nghe học nhiều, biết cho đi, có sự hiểu rõ.",
  "mn120:12.2": "Vị ấy được nghe rằng:",
  "mn120:12.3": "‘Phạm thiên một ngàn sống lâu, đẹp đẽ, có nhiều sự dễ chịu.’",
  "mn120:12.4": "Này các Tỳ Kheo, Phạm thiên một ngàn trùm khắp một ngàn thế giới và an trú với tâm mở rộng đến đó.",
  "mn120:12.5": "Những chúng sinh nào sinh về đó, vị ấy cũng trùm khắp họ và an trú với tâm mở rộng đến đó.",
  "mn120:12.6": "Ví như, này các Tỳ Kheo, một người mắt sáng cầm một quả am-la trong tay rồi nhìn kỹ nó;",
  "mn120:12.7": "cũng vậy, này các Tỳ Kheo, Phạm thiên một ngàn trùm khắp một ngàn thế giới và an trú với tâm mở rộng đến đó.",
  "mn120:12.8": "Những chúng sinh nào sinh về đó, vị ấy cũng trùm khắp họ và an trú với tâm mở rộng đến đó.",
  "mn120:12.9": "Vị ấy nghĩ rằng:",
  "mn120:12.10": "‘Mong sao sau khi thân tan rã, sau khi chết, ta được sinh chung với Phạm thiên một ngàn.’",
  "mn120:12.11": "Vị ấy hướng tâm đến điều đó, đặt tâm vững vào điều đó, làm cho tâm ấy lớn mạnh.",
  "mn120:12.12": "Những tác ý và cách an trú ấy, khi được làm cho lớn mạnh và lặp đi lặp lại như vậy, sẽ đưa đến việc sinh về cõi ấy.",
  "mn120:12.13": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến việc sinh về cõi ấy.",
  "mn120:13-16.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết tốt, nghe học nhiều, …",
  "mn120:13-16.2": "biết cho đi, …",
  "mn120:13-16.3": "có sự hiểu rõ.",
  "mn120:13-16.4": "Vị ấy được nghe rằng:",
  "mn120:13-16.5": "Phạm thiên hai ngàn …",
  "mn120:13-16.6": "Phạm thiên ba ngàn …",
  "mn120:13-16.7": "Phạm thiên bốn ngàn …",
  "mn120:13-16.8": "Phạm thiên năm ngàn sống lâu, đẹp đẽ, có nhiều sự dễ chịu.",
  "mn120:13-16.9": "Này các Tỳ Kheo, Phạm thiên năm ngàn trùm khắp một cõi đời gồm năm ngàn thế giới và an trú với tâm hướng đến đó.",
  "mn120:13-16.10": "Những chúng sanh sinh về đó cũng trùm khắp cõi ấy và an trú với tâm hướng đến đó.",
  "mn120:13-16.11": "Ví như, này các Tỳ Kheo, một người mắt sáng cầm năm trái amanda trong tay mà nhìn kỹ;",
  "mn120:13-16.12": "cũng vậy, này các Tỳ Kheo, Phạm thiên năm ngàn trùm khắp một cõi đời gồm năm ngàn thế giới và an trú với tâm hướng đến đó.",
  "mn120:13-16.13": "Những chúng sanh sinh về đó cũng trùm khắp cõi ấy và an trú với tâm hướng đến đó.",
  "mn120:13-16.14": "Vị ấy nghĩ rằng:",
  "mn120:13-16.15": "‘Mong sao sau khi thân tan rã, sau khi chết, ta được sinh chung với Phạm thiên năm ngàn.’",
  "mn120:13-16.16": "Vị ấy nung nấu tâm ấy, giữ vững tâm ấy, làm cho tâm ấy lớn mạnh.",
  "mn120:13-16.17": "Những tạo tác của tâm và cách an trú ấy, khi được làm cho lớn mạnh như vậy, được lặp đi lặp lại như vậy, sẽ đưa đến việc sinh về đó.",
  "mn120:13-16.18": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến việc sinh về đó.",
  "mn120:17.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết tốt, được nghe nhiều…",
  "mn120:17.2": "biết cho đi…",
  "mn120:17.3": "có sự hiểu rõ.",
  "mn120:17.4": "Vị ấy được nghe rằng:",
  "mn120:17.5": "‘Phạm thiên mười ngàn sống lâu, đẹp đẽ, có nhiều sự dễ chịu.’",
  "mn120:17.6": "Này các Tỳ Kheo, Phạm thiên mười ngàn trùm khắp một cõi đời gồm mười ngàn thế giới và an trú với tâm hướng đến đó.",
  "mn120:17.7": "Những chúng sanh sinh về đó cũng trùm khắp cõi ấy và an trú với tâm hướng đến đó.",
  "mn120:17.8": "Ví như, này các Tỳ Kheo, một viên ngọc lưu ly đẹp, trong sáng, có tám mặt, được mài giũa khéo, đặt trên tấm vải vàng thì chiếu sáng, tỏa rạng, sáng chói;",
  "mn120:17.9": "cũng vậy, này các Tỳ Kheo, Phạm thiên mười ngàn trùm khắp một cõi đời gồm mười ngàn thế giới và an trú với tâm hướng đến đó.",
  "mn120:17.10": "Những chúng sanh sinh về đó cũng trùm khắp cõi ấy và an trú với tâm hướng đến đó.",
  "mn120:17.11": "Vị ấy nghĩ rằng:",
  "mn120:17.12": "‘Mong sao sau khi thân tan rã, sau khi chết, ta được sinh chung với Phạm thiên mười ngàn.’",
  "mn120:17.13": "Vị ấy nung nấu tâm ấy, giữ vững tâm ấy, làm cho tâm ấy lớn mạnh.",
  "mn120:17.14": "Những tạo tác của tâm và cách an trú ấy, khi được làm cho lớn mạnh như vậy, được lặp đi lặp lại như vậy, sẽ đưa đến việc sinh về đó.",
  "mn120:17.15": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến chỗ sinh về nơi ấy.",
  "mn120:18.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết sống tốt…",
  "mn120:18.2": "được nghe nhiều…",
  "mn120:18.3": "biết cho đi…",
  "mn120:18.4": "có sự hiểu rõ.",
  "mn120:18.5": "Vị ấy được nghe rằng:",
  "mn120:18.6": "‘Phạm thiên một trăm ngàn sống lâu, đẹp đẽ, có nhiều sự dễ chịu.’",
  "mn120:18.7": "Này các Tỳ Kheo, Phạm thiên một trăm ngàn bao trùm và an trú khắp một trăm ngàn thế giới.",
  "mn120:18.8": "Những chúng sinh sinh về đó cũng bao trùm và an trú như vậy.",
  "mn120:18.9": "Ví như, này các Tỳ Kheo, một món vàng ròng từ sông Jambu, do người thợ khéo luyện rất giỏi nung khéo, được đặt trên tấm vải vàng nhạt, thì sáng chói, rực lên, tỏa ra ánh sáng;",
  "mn120:18.10": "cũng vậy, này các Tỳ Kheo, Phạm thiên một trăm ngàn bao trùm và an trú khắp một trăm ngàn thế giới.",
  "mn120:18.11": "Những chúng sinh sinh về đó cũng bao trùm và an trú như vậy.",
  "mn120:18.12": "Vị ấy nghĩ rằng:",
  "mn120:18.13": "‘Ước gì, khi thân này tan rã, sau khi chết, ta được sinh cùng chỗ với Phạm thiên một trăm ngàn.’",
  "mn120:18.14": "Vị ấy nung nấu tâm ấy, đặt vững tâm ấy, làm cho tâm ấy lớn lên.",
  "mn120:18.15": "Những tạo tác của tâm và cách an trú ấy, khi được làm cho lớn lên và được làm nhiều như vậy, thì đưa đến chỗ sinh về nơi ấy.",
  "mn120:18.16": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến chỗ sinh về nơi ấy.",
  "mn120:19.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết sống tốt…",
  "mn120:19.2": "được nghe nhiều…",
  "mn120:19.3": "biết cho đi…",
  "mn120:19.4": "có sự hiểu rõ.",
  "mn120:19.5": "Vị ấy được nghe rằng:",
  "mn120:19.6": "các vị trời Ánh Sáng…",
  "mn120:19.7": "các vị trời Ánh Sáng ít…",
  "mn120:19.8": "các vị trời Ánh Sáng vô lượng…",
  "mn120:19.9": "các vị trời Rực Sáng sống lâu, đẹp đẽ, có nhiều sự dễ chịu.",
  "mn120:19.10": "Vị ấy nghĩ rằng:",
  "mn120:19.11": "‘Ước gì, khi thân này tan rã, sau khi chết, ta được sinh cùng chỗ với các vị trời Rực Sáng.’",
  "mn120:19.12": "Vị ấy nung nấu tâm ấy, đặt vững tâm ấy, làm cho tâm ấy lớn lên.",
  "mn120:19.13": "Những tạo tác của tâm và cách an trú ấy, khi được làm cho lớn lên và được làm nhiều như vậy, thì đưa đến chỗ sinh về nơi ấy.",
  "mn120:19.14": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến chỗ sinh về nơi ấy.",
  "mn120:20.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết ở tốt,",
  "mn120:20.2": "nghe học nhiều,",
  "mn120:20.3": "biết cho đi,",
  "mn120:20.4": "có sự hiểu rõ.",
  "mn120:20.5": "Vị ấy được nghe rằng:",
  "mn120:20.6": "các vị trời có ánh sáng đẹp ít ỏi…",
  "mn120:20.7": "các vị trời có ánh sáng đẹp vô lượng…",
  "mn120:20.8": "các vị trời toàn ánh sáng đẹp sống lâu, đẹp đẽ, có nhiều sự dễ chịu.",
  "mn120:20.9": "Vị ấy nghĩ rằng:",
  "mn120:20.10": "‘Ước gì sau khi thân tan rã, sau khi chết, ta được sinh chung với các vị trời toàn ánh sáng đẹp.’",
  "mn120:20.11": "Vị ấy hướng tâm đến điều ấy, đặt tâm vững vào điều ấy, làm cho tâm ấy lớn mạnh.",
  "mn120:20.12": "Những tạo tác của tâm và cách an trú ấy, khi được làm cho lớn mạnh, được làm cho nhiều lên như vậy, sẽ đưa đến chỗ sinh về nơi ấy.",
  "mn120:20.13": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến chỗ sinh về nơi ấy.",
  "mn120:21-30.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết ở tốt,",
  "mn120:21-30.2": "nghe học nhiều,",
  "mn120:21-30.3": "biết cho đi,",
  "mn120:21-30.4": "có sự hiểu rõ.",
  "mn120:21-30.5": "Vị ấy được nghe rằng:",
  "mn120:21-30.6": "các vị trời quả lớn…",
  "mn120:21-30.7": "các vị trời không rơi xuống…",
  "mn120:21-30.8": "các vị trời không bị nung nấu…",
  "mn120:21-30.9": "các vị trời dễ thấy…",
  "mn120:21-30.10": "các vị trời thấy rõ…",
  "mn120:21-30.11": "các vị trời cao nhất sống lâu, đẹp đẽ, có nhiều sự dễ chịu.",
  "mn120:21-30.12": "Vị ấy nghĩ rằng:",
  "mn120:21-30.13": "‘Ước gì sau khi thân tan rã, sau khi chết, ta được sinh chung với các vị trời cao nhất.’",
  "mn120:21-30.14": "Vị ấy hướng tâm đến điều ấy, đặt tâm vững vào điều ấy, làm cho tâm ấy lớn mạnh.",
  "mn120:21-30.15": "Những tạo tác của tâm và cách an trú ấy, khi được làm cho lớn mạnh, được làm cho nhiều lên như vậy, sẽ đưa đến chỗ sinh về nơi ấy.",
  "mn120:21-30.16": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến chỗ sinh về nơi ấy.",
  "mn120:31.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết sống tốt…",
  "mn120:31.2": "có điều đã nghe học…",
  "mn120:31.3": "có lòng buông cho…",
  "mn120:31.4": "có sự hiểu rõ.",
  "mn120:31.5": "Vị ấy được nghe rằng:",
  "mn120:31.6": "‘Các vị trời ở cõi không gian vô biên sống rất lâu, ở rất dài, có nhiều sự dễ chịu.’",
  "mn120:31.7": "Vị ấy nghĩ như vầy:",
  "mn120:31.8": "‘Ước gì sau khi thân tan rã, sau khi chết, ta được sinh chung với các vị trời ở cõi không gian vô biên.’",
  "mn120:31.9": "Vị ấy hướng tâm đến điều ấy, đặt vững tâm vào điều ấy, làm cho tâm ấy lớn mạnh.",
  "mn120:31.10": "Những tạo tác của tâm và cách an trú ấy, khi được làm cho lớn mạnh, được làm cho nhiều lên như vậy, sẽ đưa đến việc sinh về cõi ấy.",
  "mn120:31.11": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến việc sinh về cõi ấy.",
  "mn120:32.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết sống tốt…",
  "mn120:32.2": "có điều đã nghe học…",
  "mn120:32.3": "có lòng buông cho…",
  "mn120:32.4": "có sự hiểu rõ.",
  "mn120:32.5": "Vị ấy được nghe rằng:",
  "mn120:32.6": "‘Các vị trời ở cõi nhận biết vô biên sống rất lâu, ở rất dài, có nhiều sự dễ chịu.’",
  "mn120:32.7": "Vị ấy nghĩ như vầy:",
  "mn120:32.8": "‘Ước gì sau khi thân tan rã, sau khi chết, ta được sinh chung với các vị trời ở cõi nhận biết vô biên.’",
  "mn120:32.9": "Vị ấy hướng tâm đến điều ấy, đặt vững tâm vào điều ấy, làm cho tâm ấy lớn mạnh.",
  "mn120:32.10": "Những tạo tác của tâm và cách an trú ấy, khi được làm cho lớn mạnh, được làm cho nhiều lên như vậy, sẽ đưa đến việc sinh về cõi ấy.",
  "mn120:32.11": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến việc sinh về cõi ấy.",
  "mn120:33-36.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết sống tốt…",
  "mn120:33-36.2": "có điều đã nghe học…",
  "mn120:33-36.3": "có lòng buông cho…",
  "mn120:33-36.4": "có sự hiểu rõ.",
  "mn120:33-36.5": "Vị ấy được nghe rằng—",
  "mn120:33-36.6": "các vị trời ở cõi không có gì…",
  "mn120:33-36.7": "các vị trời ở cõi không phải còn nhận ra mà cũng không phải không còn nhận ra sống rất lâu, ở rất dài, có nhiều sự dễ chịu.",
  "mn120:33-36.8": "Vị ấy nghĩ như vầy:",
  "mn120:33-36.9": "‘Ước gì sau khi thân này tan rã, sau khi chết, ta được sinh chung với các vị trời ở cõi không còn nói là còn nhận biết hay không còn nhận biết.’",
  "mn120:33-36.10": "Vị ấy hướng tâm đến điều đó, đặt tâm vững vào điều đó, làm cho điều đó lớn mạnh.",
  "mn120:33-36.11": "Những tạo tác của tâm và cách an trú ấy, khi được làm cho lớn mạnh như vậy, được lặp đi lặp lại như vậy, sẽ đưa đến chỗ sinh về nơi ấy.",
  "mn120:33-36.12": "Này các Tỳ Kheo, đây là con đường, đây là cách làm đưa đến chỗ sinh về nơi ấy.",
  "mn120:37.1": "Lại nữa, này các Tỳ Kheo, một Tỳ Kheo có lòng tin, có nết tốt…",
  "mn120:37.2": "có học rộng…",
  "mn120:37.3": "biết cho đi…",
  "mn120:37.4": "có sự hiểu rõ.",
  "mn120:37.5": "Vị ấy nghĩ như vầy:",
  "mn120:37.6": "‘Ước gì do dứt sạch các dòng rỉ chảy, ngay trong đời này, tự mình biết rõ, tự mình thấy ra, rồi sống an trú với tâm được buông thoát, với sự hiểu rõ được buông thoát, không còn các dòng rỉ chảy.’",
  "mn120:37.7": "Vị ấy do dứt sạch các dòng rỉ chảy, ngay trong đời này, tự mình biết rõ, tự mình thấy ra, rồi sống an trú với tâm được buông thoát, với sự hiểu rõ được buông thoát, không còn các dòng rỉ chảy.",
  "mn120:37.8": "Này các Tỳ Kheo, vị Tỳ Kheo này không còn sinh về đâu nữa.”",
  "mn120:37.9": "Đức Thế Tôn nói như vậy.",
  "mn120:37.10": "Các Tỳ Kheo ấy vui mừng, hoan hỷ đón nhận lời Đức Thế Tôn dạy.",
  "mn120:37.11": "Kinh Nói Về Sự Sinh Ra Do Tạo Tác của Tâm chấm dứt, bài thứ mười.",
  "mn120:37.12": "Phẩm Theo Từng Bước chấm dứt, phần thứ hai.",
  "mn120:38.0": "Bài tóm lược:",
  "mn120:38.1": "Theo từng bước, làm cho sạch, người chân thật,",
  "mn120:38.2": "điều nên gần gũi, nhiều giới phần, chia rõ;",
  "mn120:38.3": "tên tiếng của Đức Phật, bốn mươi,",
  "mn120:38.4": "hơi thở vào ra, nhớ biết rõ nơi thân, sự sinh ra."
}
window.BILARA["mn120"]["vi"]["mn120:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
