window.BILARA = window.BILARA || {};
window.BILARA["mn135"] = window.BILARA["mn135"] || {};
window.BILARA["mn135"]["vi"] = {
  "mn135:0.1": "Trung Bộ Kinh 135 ",
  "mn135:0.2": "Tiểu Nghiệp Phân Biệt Sutta ",
  "mn135:1.1": "Tôi nghe như vầy—",
  "mn135:1.2": "Một thời, Thế Tôn trú ở Sāvatthī, tại Jetavana, khu vườn của Anāthapiṇḍika. ",
  "mn135:2.1": "Rồi Subha thanh niên, con của Todeyya, đi đến chỗ Thế Tôn; sau khi đến, đàm đạo thân mật với Thế Tôn. ",
  "mn135:2.2": "Sau khi nói lên những lời chào hỏi thân mật, đáng ghi nhớ, rồi ngồi xuống một bên. Ngồi xuống một bên, Subha thanh niên, con của Todeyya, bạch Thế Tôn: ",
  "mn135:3.1": "“Thưa Tôn giả Gotama, nguyên nhân nào, duyên cớ nào khiến cho giữa loài người, những người đang sống làm người, lại thấy có sự khác biệt thấp kém và cao quý? ",
  "mn135:3.2": "Thưa Tôn giả Gotama, có những người đoản mạng, có những người trường mạng; ",
  "mn135:3.3": "có những người nhiều bệnh, có những người ít bệnh; ",
  "mn135:3.4": "có những người xấu xí, có những người đẹp đẽ; ",
  "mn135:3.5": "có những người ít uy tín, có những người nhiều uy tín; ",
  "mn135:3.6": "có những người ít tài sản, có những người nhiều tài sản; ",
  "mn135:3.7": "có những người dòng dõi thấp kém, có những người dòng dõi cao quý; ",
  "mn135:3.8": "có những người kém trí tuệ, có những người có trí tuệ. ",
  "mn135:3.9": "Thưa Tôn giả Gotama, nguyên nhân nào, duyên cớ nào khiến cho giữa loài người, những người đang sống làm người, lại thấy có sự khác biệt thấp kém và cao quý?” ",
  "mn135:4.1": "“Này thanh niên, các loài hữu tình là chủ nhân của nghiệp, là thừa tự của nghiệp, nghiệp là thai tạng, nghiệp là quyến thuộc, nghiệp là nơi nương tựa. ",
  "mn135:4.2": "Nghiệp phân chia các loài hữu tình, tức là—",
  "mn135:4.3": "sự thấp kém và cao quý.” ",
  "mn135:4.4": "“Thưa Tôn giả Gotama, tôi không hiểu rõ ý nghĩa chi tiết của lời nói vắn tắt này của Tôn giả Gotama, khi chưa được phân tích rõ ràng. ",
  "mn135:4.5": "Lành thay, Tôn giả Gotama hãy thuyết pháp cho tôi để tôi có thể hiểu rõ ý nghĩa chi tiết của lời nói vắn tắt này của Tôn giả Gotama, khi đã được phân tích rõ ràng.” ",
  "mn135:4.6": "“Vậy thì, này thanh niên, hãy lắng nghe, hãy chú ý kỹ; Ta sẽ nói.” ",
  "mn135:4.7": "“Vâng, thưa Tôn giả,” Subha thanh niên, con của Todeyya, vâng lời Thế Tôn. ",
  "mn135:4.8": "Thế Tôn nói như sau: ",
  "mn135:5.1": "“Này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó sát sinh, tàn nhẫn, tay lấm máu, chuyên sát hại, không có lòng từ bi đối với các loài hữu tình. ",
  "mn135:5.2": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn135:5.3": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi dữ, ác thú, đọa xứ, địa ngục, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ đoản mạng. ",
  "mn135:5.4": "Này thanh niên, đây là con đường đưa đến đoản mạng, tức là—",
  "mn135:5.5": "sát sinh, tàn nhẫn, tay lấm máu, chuyên sát hại, không có lòng từ bi đối với các loài hữu tình. ",
  "mn135:6.1": "Nhưng này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó từ bỏ sát sinh, tránh xa sát sinh, đặt gậy xuống, đặt vũ khí xuống, biết hổ thẹn, có lòng từ bi, sống thương xót đến hạnh phúc của tất cả chúng sinh. ",
  "mn135:6.2": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi lành, cõi trời. ",
  "mn135:6.3": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi lành, cõi trời, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ trường mạng. ",
  "mn135:6.4": "Này thanh niên, đây là con đường đưa đến trường mạng, tức là—",
  "mn135:6.5": "từ bỏ sát sinh, tránh xa sát sinh, đặt gậy xuống, đặt vũ khí xuống, biết hổ thẹn, có lòng từ bi, sống thương xót đến hạnh phúc của tất cả chúng sinh. ",
  "mn135:7.1": "Này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó có tính hay làm hại chúng sinh, bằng tay, bằng cục đất, bằng gậy, hay bằng dao. ",
  "mn135:7.2": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn135:7.3": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi dữ, ác thú, đọa xứ, địa ngục, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ nhiều bệnh. ",
  "mn135:7.4": "Này thanh niên, đây là con đường đưa đến nhiều bệnh, tức là—",
  "mn135:7.5": "có tính hay làm hại chúng sinh, bằng tay, bằng cục đất, bằng gậy, hay bằng dao. ",
  "mn135:8.1": "Nhưng này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó không có tính hay làm hại chúng sinh, bằng tay, bằng cục đất, bằng gậy, hay bằng dao. ",
  "mn135:8.2": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi lành, cõi trời. ",
  "mn135:8.3": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi lành, cõi trời, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ ít bệnh. ",
  "mn135:8.4": "Này thanh niên, đây là con đường đưa đến ít bệnh, tức là—",
  "mn135:8.5": "không có tính hay làm hại chúng sinh, bằng tay, bằng cục đất, bằng gậy, hay bằng dao. ",
  "mn135:9.1": "Này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó hay nóng giận, nhiều phiền muộn. ",
  "mn135:9.2": "Dù bị nói ít, người ấy cũng nổi giận, bực tức, thù hằn, cố chấp, biểu lộ sự giận dữ, oán hận và bất mãn. ",
  "mn135:9.3": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn135:9.4": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi dữ, ác thú, đọa xứ, địa ngục, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ xấu xí. ",
  "mn135:9.5": "Này thanh niên, đây là con đường đưa đến xấu xí, tức là—",
  "mn135:9.6": "hay nóng giận, nhiều phiền muộn; ",
  "mn135:9.7": "dù bị nói ít, người ấy cũng nổi giận, bực tức, thù hằn, cố chấp, biểu lộ sự giận dữ, oán hận và bất mãn. ",
  "mn135:10.1": "Nhưng này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó không hay nóng giận, không nhiều phiền muộn; ",
  "mn135:10.2": "dù bị nói nhiều, người ấy cũng không nổi giận, không bực tức, không thù hằn, không cố chấp, không biểu lộ sự giận dữ, oán hận và bất mãn. ",
  "mn135:10.3": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi lành, cõi trời. ",
  "mn135:10.4": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi lành, cõi trời, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ đẹp đẽ. ",
  "mn135:10.5": "Này thanh niên, đây là con đường đưa đến đẹp đẽ, tức là—",
  "mn135:10.6": "không hay nóng giận, không nhiều phiền muộn; ",
  "mn135:10.7": "dù bị nói nhiều, người ấy cũng không nổi giận, không bực tức, không thù hằn, không cố chấp, không biểu lộ sự giận dữ, oán hận và bất mãn. ",
  "mn135:11.1": "Này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó có tính ganh tị; ",
  "mn135:11.2": "ganh tị, bực tức, và ôm giữ sự ganh tị đối với lợi lộc, sự kính trọng, sự tôn kính, sự cúng dường, sự đảnh lễ, sự cung kính của người khác. ",
  "mn135:11.3": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn135:11.4": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi dữ, ác thú, đọa xứ, địa ngục, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ ít uy tín. ",
  "mn135:11.5": "Này thanh niên, đây là con đường đưa đến ít uy tín, tức là—",
  "mn135:11.6": "có tính ganh tị; ",
  "mn135:11.7": "ganh tị, bực tức, và ôm giữ sự ganh tị đối với lợi lộc, sự kính trọng, sự tôn kính, sự cúng dường, sự đảnh lễ, sự cung kính của người khác. ",
  "mn135:12.1": "Nhưng này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó không có tính ganh tị; ",
  "mn135:12.2": "không ganh tị, không bực tức, không ôm giữ sự ganh tị đối với lợi lộc, sự kính trọng, sự tôn kính, sự cúng dường, sự đảnh lễ, sự cung kính của người khác. ",
  "mn135:12.3": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi lành, cõi trời. ",
  "mn135:12.4": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi lành, cõi trời, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ nhiều uy tín. ",
  "mn135:12.5": "Này thanh niên, đây là con đường đưa đến nhiều uy tín, tức là—",
  "mn135:12.6": "không có tính ganh tị; ",
  "mn135:12.7": "không ganh tị, không bực tức, không ôm giữ sự ganh tị đối với lợi lộc, sự kính trọng, sự tôn kính, sự cúng dường, sự đảnh lễ, sự cung kính của người khác. ",
  "mn135:13.1": "Này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó không bố thí cho các Sa-môn hay Bà-la-môn thức ăn, đồ uống, y phục, xe cộ, vòng hoa, hương liệu, phấn sáp, giường nằm, chỗ ở, đèn đuốc. ",
  "mn135:13.2": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn135:13.3": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi dữ, ác thú, đọa xứ, địa ngục, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ ít tài sản. ",
  "mn135:13.4": "Này thanh niên, đây là con đường đưa đến ít tài sản, tức là—",
  "mn135:13.5": "không bố thí cho các Sa-môn hay Bà-la-môn thức ăn, đồ uống, y phục, xe cộ, vòng hoa, hương liệu, phấn sáp, giường nằm, chỗ ở, đèn đuốc. ",
  "mn135:14.1": "Nhưng này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó bố thí cho các Sa-môn hay Bà-la-môn thức ăn, đồ uống, y phục, xe cộ, vòng hoa, hương liệu, phấn sáp, giường nằm, chỗ ở, đèn đuốc. ",
  "mn135:14.2": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi lành, cõi trời. ",
  "mn135:14.3": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi lành, cõi trời, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ nhiều tài sản. ",
  "mn135:14.4": "Này thanh niên, đây là con đường đưa đến nhiều tài sản, tức là—",
  "mn135:14.5": "bố thí cho các Sa-môn hay Bà-la-môn thức ăn, đồ uống, y phục, xe cộ, vòng hoa, hương liệu, phấn sáp, giường nằm, chỗ ở, đèn đuốc. ",
  "mn135:15.1": "Này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó cứng đầu, quá kiêu mạn—",
  "mn135:15.2": "không đảnh lễ người đáng đảnh lễ, không đứng dậy đón người đáng đứng dậy đón, không nhường chỗ cho người đáng được nhường chỗ, không nhường đường cho người đáng được nhường đường, không kính trọng người đáng kính trọng, không tôn kính người đáng tôn kính, không cung kính người đáng cung kính, không cúng dường người đáng cúng dường. ",
  "mn135:15.3": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn135:15.4": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi dữ, ác thú, đọa xứ, địa ngục, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ dòng dõi thấp kém. ",
  "mn135:15.5": "Này thanh niên, đây là con đường đưa đến dòng dõi thấp kém, tức là—",
  "mn135:15.6": "cứng đầu, quá kiêu mạn; ",
  "mn135:15.7": "không đảnh lễ người đáng đảnh lễ, không đứng dậy đón người đáng đứng dậy đón, không nhường chỗ cho người đáng được nhường chỗ, không nhường đường cho người đáng được nhường đường, không kính trọng người đáng kính trọng, không tôn kính người đáng tôn kính, không cung kính người đáng cung kính, không cúng dường người đáng cúng dường. ",
  "mn135:16.1": "Nhưng này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó không cứng đầu, không quá kiêu mạn; ",
  "mn135:16.2": "đảnh lễ người đáng đảnh lễ, đứng dậy đón người đáng đứng dậy đón, nhường chỗ cho người đáng được nhường chỗ, nhường đường cho người đáng được nhường đường, kính trọng người đáng kính trọng, tôn kính người đáng tôn kính, cung kính người đáng cung kính, cúng dường người đáng cúng dường. ",
  "mn135:16.3": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi lành, cõi trời. ",
  "mn135:16.4": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi lành, cõi trời, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ dòng dõi cao quý. ",
  "mn135:16.5": "Này thanh niên, đây là con đường đưa đến dòng dõi cao quý, tức là—",
  "mn135:16.6": "không cứng đầu, không quá kiêu mạn; ",
  "mn135:16.7": "đảnh lễ người đáng đảnh lễ, đứng dậy đón người đáng đứng dậy đón, nhường chỗ cho người đáng được nhường chỗ, nhường đường cho người đáng được nhường đường, kính trọng người đáng kính trọng, tôn kính người đáng tôn kính, cung kính người đáng cung kính, cúng dường người đáng cúng dường. ",
  "mn135:17.1": "Này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó đi đến các Sa-môn hay Bà-la-môn và không hỏi: ",
  "mn135:17.2": "‘Thưa Tôn giả, điều gì là thiện, điều gì là bất thiện; ",
  "mn135:17.3": "điều gì là đáng trách, điều gì là không đáng trách; ",
  "mn135:17.4": "điều gì nên làm, điều gì không nên làm; ",
  "mn135:17.5": "điều gì khi tôi làm sẽ đưa đến bất lợi, đau khổ lâu dài, hay điều gì khi tôi làm sẽ đưa đến lợi ích, an lạc lâu dài?’ ",
  "mn135:17.6": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi dữ, ác thú, đọa xứ, địa ngục. ",
  "mn135:17.7": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi dữ, ác thú, đọa xứ, địa ngục, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ kém trí tuệ. ",
  "mn135:17.8": "Này thanh niên, đây là con đường đưa đến kém trí tuệ, tức là—",
  "mn135:17.9": "đi đến các Sa-môn hay Bà-la-môn và không hỏi: ",
  "mn135:17.10": "‘Thưa Tôn giả, điều gì là thiện, điều gì là bất thiện; ",
  "mn135:17.11": "điều gì là đáng trách, điều gì là không đáng trách; ",
  "mn135:17.12": "điều gì nên làm, điều gì không nên làm; ",
  "mn135:17.13": "điều gì khi tôi làm sẽ đưa đến bất lợi, đau khổ lâu dài, hay điều gì khi tôi làm sẽ đưa đến lợi ích, an lạc lâu dài?’ ",
  "mn135:18.1": "Nhưng này thanh niên, ở đây, có người đàn bà hay đàn ông nào đó đi đến các Sa-môn hay Bà-la-môn và hỏi: ",
  "mn135:18.2": "‘Thưa Tôn giả, điều gì là thiện, điều gì là bất thiện; ",
  "mn135:18.3": "điều gì là đáng trách, điều gì là không đáng trách; ",
  "mn135:18.4": "điều gì nên làm, điều gì không nên làm; ",
  "mn135:18.5": "điều gì khi tôi làm sẽ đưa đến bất lợi, đau khổ lâu dài, hay điều gì khi tôi làm sẽ đưa đến lợi ích, an lạc lâu dài?’ ",
  "mn135:18.6": "Do nghiệp ấy, đã được thực hiện như vậy, đã được chấp nhận như vậy, sau khi thân hoại mạng chung, người ấy sinh vào cõi lành, cõi trời. ",
  "mn135:18.7": "Nếu sau khi thân hoại mạng chung, người ấy không sinh vào cõi lành, cõi trời, mà được sinh làm người, thì ở bất cứ nơi nào người ấy tái sinh, người ấy sẽ có trí tuệ. ",
  "mn135:18.8": "Này thanh niên, đây là con đường đưa đến có trí tuệ, tức là—",
  "mn135:18.9": "đi đến các Sa-môn hay Bà-la-môn và hỏi: ",
  "mn135:18.10": "‘Thưa Tôn giả, điều gì là thiện, điều gì là bất thiện; ",
  "mn135:18.11": "điều gì là đáng trách, điều gì là không đáng trách; ",
  "mn135:18.12": "điều gì nên làm, điều gì không nên làm; ",
  "mn135:18.13": "'Điều gì tôi làm sẽ là bất lợi, là khổ đau lâu dài cho tôi, hay điều gì tôi làm sẽ là lợi ích, là an lạc lâu dài cho tôi?'",
  "mn135:19.1": "Này thanh niên, con đường dẫn đến đoản thọ đưa đến đoản thọ, con đường dẫn đến trường thọ đưa đến trường thọ;",
  "mn135:19.2": "con đường dẫn đến nhiều bệnh tật đưa đến nhiều bệnh tật, con đường dẫn đến ít bệnh tật đưa đến ít bệnh tật;",
  "mn135:19.3": "con đường dẫn đến xấu xí đưa đến xấu xí, con đường dẫn đến ưa nhìn đưa đến ưa nhìn;",
  "mn135:19.4": "con đường dẫn đến ít quyền lực đưa đến ít quyền lực, con đường dẫn đến nhiều quyền lực đưa đến nhiều quyền lực;",
  "mn135:19.5": "con đường dẫn đến ít tài sản đưa đến ít tài sản, con đường dẫn đến nhiều tài sản đưa đến nhiều tài sản;",
  "mn135:19.6": "con đường dẫn đến dòng dõi thấp kém đưa đến dòng dõi thấp kém, con đường dẫn đến dòng dõi cao quý đưa đến dòng dõi cao quý;",
  "mn135:19.7": "con đường dẫn đến kém trí tuệ đưa đến kém trí tuệ, con đường dẫn đến nhiều trí tuệ đưa đến nhiều trí tuệ.",
  "mn135:20.1": "Này thanh niên, các chúng sinh là chủ của nghiệp, là thừa tự của nghiệp, là thai tạng của nghiệp, là bà con của nghiệp, là nơi nương tựa của nghiệp.",
  "mn135:20.2": "Nghiệp phân chia các chúng sinh, tức là—",
  "mn135:20.3": "thành thấp kém hay cao quý.”",
  "mn135:21.1": "Khi được nói như vậy, thanh niên Subha, con của Todeyya, đã nói với Thế Tôn điều này:",
  "mn135:21.2": "“Tuyệt vời thay, thưa Tôn giả Gotama! Tuyệt vời thay, thưa Tôn giả Gotama!",
  "mn135:21.3": "Ví như, thưa Tôn giả Gotama, người ta lật ngửa cái bị úp, hay mở ra cái bị che đậy, hay chỉ đường cho người lạc lối, hay cầm đèn dầu trong bóng tối để những người có mắt có thể thấy các hình sắc; cũng vậy, Tôn giả Gotama đã thuyết giảng giáo pháp bằng nhiều cách khác nhau.",
  "mn135:21.4": "Con xin quy y Tôn giả Gotama, và giáo pháp, và Tăng đoàn.",
  "mn135:21.5": "Xin Tôn giả Gotama hãy nhận con làm một cư sĩ đã quy y từ nay cho đến trọn đời.”",
  "mn135:21.6": "Tiểu Nghiệp Phân Biệt Kinh, thứ năm, đã hoàn tất."
}
window.BILARA["mn135"]["vi"]["mn135:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
