window.BILARA = window.BILARA || {};
window.BILARA["mn130"] = window.BILARA["mn130"] || {};
window.BILARA["mn130"]["vi"] = {
  "mn130:0.1": "Trung Bộ Kinh 130 ",
  "mn130:0.2": "Kinh Sứ Giả Của Chư Thiên ",
  "mn130:1.1": "Như vầy tôi nghe—",
  "mn130:1.2": "Một thời Thế Tôn trú ở Sāvatthī, tại Jetavana, khu vườn của ông Anāthapiṇḍika. ",
  "mn130:1.3": "Tại đấy, Thế Tôn gọi các Tỳ-kheo: ",
  "mn130:1.4": "“Này các Tỳ-kheo.” ",
  "mn130:1.5": "Các Tỳ-kheo ấy vâng đáp Thế Tôn: “Bạch Thế Tôn.” ",
  "mn130:1.6": "Thế Tôn nói như sau: ",
  "mn130:2.1": "“Này các Tỳ-kheo, ví như có hai ngôi nhà có cửa, tại đấy một người có mắt đứng ở giữa có thể thấy những người đi vào nhà, đi ra khỏi nhà, đi tới đi lui, đi quanh quẩn; ",
  "mn130:2.2": "Cũng vậy, này các Tỳ-kheo, với thiên nhãn thanh tịnh, siêu việt loài người, Ta thấy các chúng sinh chết đi và sinh lại, kẻ hạ liệt người cao sang, kẻ đẹp đẽ người xấu xí, kẻ may mắn người bất hạnh, Ta biết rõ các chúng sinh tùy theo nghiệp của họ: ‘Thật sự, những chúng sinh này đã làm các việc thiện về thân, làm các việc thiện về lời nói, làm các việc thiện về ý nghĩ, không chê bai các bậc Thánh, có chánh kiến, đã thực hành các nghiệp theo chánh kiến; sau khi thân hoại mạng chung, họ sinh vào cõi lành, cảnh trời. Hoặc những chúng sinh này đã làm các việc thiện về thân, làm các việc thiện về lời nói, làm các việc thiện về ý nghĩ, không chê bai các bậc Thánh, có chánh kiến, đã thực hành các nghiệp theo chánh kiến; sau khi thân hoại mạng chung, họ sinh vào loài người. Thật sự, những chúng sinh này đã làm các việc ác về thân, làm các việc ác về lời nói, làm các việc ác về ý nghĩ, chê bai các bậc Thánh, có tà kiến, đã thực hành các nghiệp theo tà kiến; sau khi thân hoại mạng chung, họ sinh vào cõi ngạ quỷ. Hoặc những chúng sinh này đã làm các việc ác về thân, làm các việc ác về lời nói, làm các việc ác về ý nghĩ, chê bai các bậc Thánh, có tà kiến, đã thực hành các nghiệp theo tà kiến; sau khi thân hoại mạng chung, họ sinh vào loài súc sinh. Hoặc những chúng sinh này đã làm các việc ác về thân, làm các việc ác về lời nói, làm các việc ác về ý nghĩ, chê bai các bậc Thánh, có tà kiến, đã thực hành các nghiệp theo tà kiến; sau khi thân hoại mạng chung, họ sinh vào cõi dữ, ác thú, đọa xứ, địa ngục.’ ",
  "mn130:3.1": "Này các Tỳ-kheo, các người giữ địa ngục nắm lấy người ấy ở nhiều cánh tay, dẫn đến trình vua Yama: ",
  "mn130:3.2": "‘Thưa Đại vương, người này không hiếu thảo với mẹ, không hiếu thảo với cha, không kính trọng Sa-môn, không kính trọng Bà-la-môn, không tôn kính người lớn trong gia đình. ",
  "mn130:3.3": "Xin Đại vương hãy xử phạt người này.’ ",
  "mn130:3.4": "Này các Tỳ-kheo, vua Yama hỏi, tra vấn, nói chuyện với người ấy về sứ giả đầu tiên của chư thiên: ",
  "mn130:3.5": "‘Này người kia, ngươi không thấy sứ giả đầu tiên của chư thiên xuất hiện giữa loài người sao?’ ",
  "mn130:3.6": "Người ấy nói: ",
  "mn130:3.7": "‘Bạch Đại vương, tôi không thấy.’ ",
  "mn130:4.1": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:4.2": "‘Này người kia, ngươi không thấy giữa loài người một đứa bé sơ sinh, yếu ớt, nằm ngửa, bị vấy bẩn trong nước tiểu và phân của chính nó sao?’ ",
  "mn130:4.3": "Người ấy nói: ",
  "mn130:4.4": "‘Bạch Đại vương, tôi có thấy.’ ",
  "mn130:4.5": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:4.6": "‘Này người kia, khi ngươi đã có nhận thức, đã lớn, ngươi không nghĩ như vầy sao—",
  "mn130:4.7": "Ta cũng phải chịu sinh, chưa thoát khỏi sinh. Vậy ta hãy làm điều thiện bằng thân, lời nói, ý nghĩ’? ",
  "mn130:4.8": "Người ấy nói: ",
  "mn130:4.9": "‘Bạch Đại vương, tôi không thể, tôi đã lơ là.’ ",
  "mn130:4.10": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:4.11": "‘Này người kia, vì ngươi đã lơ là nên không làm điều thiện bằng thân, lời nói, ý nghĩ. ",
  "mn130:4.12": "Chắc chắn, này người kia, họ sẽ đối xử với ngươi như một kẻ lơ là. ",
  "mn130:4.13": "Và này người kia, nghiệp ác ấy không phải do mẹ ngươi làm, không phải do cha ngươi làm, không phải do anh em ngươi làm, không phải do chị em ngươi làm, không phải do bạn bè thân hữu ngươi làm, không phải do bà con huyết thống ngươi làm, không phải do các Sa-môn Bà-la-môn làm, không phải do các vị trời làm; chính ngươi đã làm nghiệp ác ấy, chính ngươi sẽ cảm nhận quả báo của nó.’ ",
  "mn130:5.1": "Này các Tỳ-kheo, sau khi hỏi, tra vấn, nói chuyện với người ấy về sứ giả đầu tiên của chư thiên, vua Yama hỏi, tra vấn, nói chuyện về sứ giả thứ hai của chư thiên: ",
  "mn130:5.2": "‘Này người kia, ngươi không thấy sứ giả thứ hai của chư thiên xuất hiện giữa loài người sao?’ ",
  "mn130:5.3": "Người ấy nói: ",
  "mn130:5.4": "‘Bạch Đại vương, tôi không thấy.’ ",
  "mn130:5.5": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:5.6": "‘Này người kia, ngươi không thấy giữa loài người một người đàn bà hay đàn ông (…) già yếu, lưng còng như mái nhà, cong vẹo, phải chống gậy, run rẩy bước đi, bệnh tật, tuổi trẻ đã qua, răng rụng, tóc bạc, đầu hói, da nhăn nheo, thân thể lốm đốm tàn nhang sao?’ ",
  "mn130:5.7": "Người ấy nói: ",
  "mn130:5.8": "‘Bạch Đại vương, tôi có thấy.’ ",
  "mn130:5.9": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:5.10": "‘Này người kia, khi ngươi đã có nhận thức, đã lớn, ngươi không nghĩ như vầy sao—",
  "mn130:5.11": "Ta cũng phải chịu già, chưa thoát khỏi già. Vậy ta hãy làm điều thiện bằng thân, lời nói, ý nghĩ’? ",
  "mn130:5.12": "Người ấy nói: ",
  "mn130:5.13": "‘Bạch Đại vương, tôi không thể, tôi đã lơ là.’ ",
  "mn130:5.14": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:5.15": "‘Này người kia, vì ngươi đã lơ là nên không làm điều thiện bằng thân, lời nói, ý nghĩ. ",
  "mn130:5.16": "Chắc chắn, này người kia, họ sẽ đối xử với ngươi như một kẻ lơ là. ",
  "mn130:5.17": "Và này người kia, nghiệp ác ấy không phải do mẹ ngươi làm, không phải do cha ngươi làm, không phải do anh em ngươi làm, không phải do chị em ngươi làm, không phải do bạn bè thân hữu ngươi làm, không phải do bà con huyết thống ngươi làm, không phải do các Sa-môn Bà-la-môn làm, không phải do các vị trời làm; chính ngươi đã làm nghiệp ác ấy, chính ngươi sẽ cảm nhận quả báo của nó.’ ",
  "mn130:6.1": "Này các Tỳ-kheo, sau khi hỏi, tra vấn, nói chuyện với người ấy về sứ giả thứ hai của chư thiên, vua Yama hỏi, tra vấn, nói chuyện về sứ giả thứ ba của chư thiên: ",
  "mn130:6.2": "‘Này người kia, ngươi không thấy sứ giả thứ ba của chư thiên xuất hiện giữa loài người sao?’ ",
  "mn130:6.3": "Người ấy nói: ",
  "mn130:6.4": "‘Bạch Đại vương, tôi không thấy.’ ",
  "mn130:6.5": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:6.6": "‘Này người kia, ngươi không thấy giữa loài người một người đàn bà hay đàn ông bệnh tật, đau khổ, ốm nặng, nằm trong nước tiểu và phân của chính mình, được người khác đỡ dậy, được người khác đặt nằm xuống sao?’ ",
  "mn130:6.7": "Người ấy nói: ",
  "mn130:6.8": "‘Bạch Đại vương, tôi có thấy.’ ",
  "mn130:6.9": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:6.10": "‘Này người kia, khi ngươi đã có nhận thức, đã lớn, ngươi không nghĩ như vầy sao—",
  "mn130:6.11": "Ta cũng phải chịu bệnh, chưa thoát khỏi bệnh. ",
  "mn130:6.12": "Vậy ta hãy làm điều thiện bằng thân, lời nói, ý nghĩ’? Người ấy nói: ",
  "mn130:6.13": "‘Bạch Đại vương, tôi không thể, tôi đã lơ là.’ ",
  "mn130:6.14": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:6.15": "‘Này người kia, vì ngươi đã lơ là nên không làm điều thiện bằng thân, lời nói, ý nghĩ. ",
  "mn130:6.16": "Chắc chắn, này người kia, họ sẽ đối xử với ngươi như một kẻ lơ là. ",
  "mn130:6.17": "Và này người kia, nghiệp ác ấy không phải do mẹ ngươi làm, không phải do cha ngươi làm, không phải do anh em ngươi làm, không phải do chị em ngươi làm, không phải do bạn bè thân hữu ngươi làm, không phải do bà con huyết thống ngươi làm, không phải do các Sa-môn Bà-la-môn làm, không phải do các vị trời làm; chính ngươi đã làm nghiệp ác ấy, chính ngươi sẽ cảm nhận quả báo của nó.’ ",
  "mn130:7.1": "Này các Tỳ-kheo, sau khi hỏi, tra vấn, nói chuyện với người ấy về sứ giả thứ ba của chư thiên, vua Yama hỏi, tra vấn, nói chuyện về sứ giả thứ tư của chư thiên: ",
  "mn130:7.2": "‘Này người kia, ngươi không thấy sứ giả thứ tư của chư thiên xuất hiện giữa loài người sao?’ ",
  "mn130:7.3": "Người ấy nói: ",
  "mn130:7.4": "‘Bạch Đại vương, tôi không thấy.’ ",
  "mn130:7.5": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:7.6": "‘Này người kia, ngươi không thấy giữa loài người các vua bắt kẻ trộm, kẻ phạm tội, và thi hành nhiều hình phạt khác nhau—",
  "mn130:7.7": "đánh bằng roi, đánh bằng gậy, đánh bằng dùi cui, chặt tay, chặt chân, chặt cả tay lẫn chân, cắt tai, cắt mũi, cắt cả tai lẫn mũi, làm thành “chén cám”, làm thành “vỏ ốc”, làm thành “miệng rāhu”, làm thành “vòng lửa”, làm thành “đèn tay”, làm thành “dây gai”, làm thành “áo vỏ cây”, làm thành “nai”, làm thành “móc câu”, làm thành “đồng tiền”, làm thành “thuốc kiềm”, làm thành “cọc quay”, làm thành “giường rơm”, đổ dầu sôi lên, cho chó ăn thịt, đóng cọc xuyên người còn sống, chém đầu bằng gươm sao?’ ",
  "mn130:7.8": "Người ấy nói: ",
  "mn130:7.9": "‘Bạch Đại vương, tôi có thấy.’ ",
  "mn130:7.10": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:7.11": "‘Này người kia, khi ngươi đã có nhận thức, đã lớn, ngươi không nghĩ như vầy sao—",
  "mn130:7.12": "Những ai làm các nghiệp ác, này người kia, họ phải chịu những hình phạt khác nhau như vậy ngay trong đời này, huống chi ở đời sau. Vậy ta hãy làm điều thiện bằng thân, lời nói, ý nghĩ’? ",
  "mn130:7.13": "Người ấy nói: ",
  "mn130:7.14": "‘Bạch Đại vương, tôi không thể, tôi đã lơ là.’ ",
  "mn130:7.15": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:7.16": "‘Này người kia, vì ngươi đã lơ là nên không làm điều thiện bằng thân, lời nói, ý nghĩ. ",
  "mn130:7.17": "Chắc chắn, này người kia, họ sẽ đối xử với ngươi như một kẻ lơ là. ",
  "mn130:7.18": "Và này người kia, nghiệp ác ấy không phải do mẹ ngươi làm, không phải do cha ngươi làm, không phải do anh em ngươi làm, không phải do chị em ngươi làm, không phải do bạn bè thân hữu ngươi làm, không phải do bà con huyết thống ngươi làm, không phải do các Sa-môn Bà-la-môn làm, không phải do các vị trời làm; chính ngươi đã làm nghiệp ác ấy, chính ngươi sẽ cảm nhận quả báo của nó.’ ",
  "mn130:8.1": "Này các Tỳ-kheo, sau khi hỏi, tra vấn, nói chuyện với người ấy về sứ giả thứ tư của chư thiên, vua Yama hỏi, tra vấn, nói chuyện về sứ giả thứ năm của chư thiên: ",
  "mn130:8.2": "‘Này người kia, ngươi không thấy sứ giả thứ năm của chư thiên xuất hiện giữa loài người sao?’ ",
  "mn130:8.3": "Người ấy nói: ",
  "mn130:8.4": "‘Bạch Đại vương, tôi không thấy.’ ",
  "mn130:8.5": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:8.6": "‘Này người kia, ngươi không thấy giữa loài người một người đàn bà hay đàn ông chết một ngày, hai ngày, hay ba ngày, thân thể trương phình, xanh xám, đầy mủ sao?’ ",
  "mn130:8.7": "Người ấy nói: ",
  "mn130:8.8": "‘Bạch Đại vương, tôi có thấy.’ ",
  "mn130:8.9": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:8.10": "‘Này người kia, khi ngươi đã có nhận thức, đã lớn, ngươi không nghĩ như vầy sao—",
  "mn130:8.11": "Ta cũng phải chịu chết, chưa thoát khỏi chết. Vậy ta hãy làm điều thiện bằng thân, lời nói, ý nghĩ’? ",
  "mn130:8.12": "Người ấy nói: ",
  "mn130:8.13": "‘Bạch Đại vương, tôi không thể, tôi đã lơ là.’ ",
  "mn130:8.14": "Này các Tỳ-kheo, vua Yama nói với người ấy: ",
  "mn130:8.15": "‘Này người kia, vì ngươi đã lơ là nên không làm điều thiện bằng thân, lời nói, ý nghĩ. ",
  "mn130:8.16": "Chắc chắn, này người kia, họ sẽ đối xử với ngươi như một kẻ lơ là. ",
  "mn130:8.17": "Và này người kia, nghiệp ác ấy không phải do mẹ ngươi làm, không phải do cha ngươi làm, không phải do anh em ngươi làm, không phải do chị em ngươi làm, không phải do bạn bè thân hữu ngươi làm, không phải do bà con huyết thống ngươi làm, không phải do các Sa-môn Bà-la-môn làm, không phải do các vị trời làm; chính ngươi đã làm nghiệp ác ấy, chính ngươi sẽ cảm nhận quả báo của nó.’ ",
  "mn130:9.1": "Này các Tỳ-kheo, sau khi hỏi, tra vấn, nói chuyện với người ấy về sứ giả thứ năm của chư thiên, vua Yama im lặng. ",
  "mn130:10.1": "Này các Tỳ-kheo, các người giữ địa ngục thi hành hình phạt gọi là năm cách trói buộc—",
  "mn130:10.2": "họ đóng một cây đinh sắt nung đỏ vào một tay, đóng một cây đinh sắt nung đỏ vào tay kia, đóng một cây đinh sắt nung đỏ vào một chân, đóng một cây đinh sắt nung đỏ vào chân kia, đóng một cây đinh sắt nung đỏ vào giữa ngực. ",
  "mn130:10.3": "Người ấy ở đấy cảm nhận những cảm giác đau đớn, dữ dội, khốc liệt, cay đắng, nhưng chưa chết cho đến khi nghiệp ác ấy chưa chấm dứt. ",
  "mn130:11.1": "Này các Tỳ-kheo, các người giữ địa ngục đặt người ấy nằm xuống và dùng rìu chặt… ",
  "mn130:12.1": "Này các Tỳ-kheo, các người giữ địa ngục nắm lấy người ấy, đầu chúc xuống, chân giơ lên, và dùng đục đẽo… ",
  "mn130:13.1": "Này các Tỳ-kheo, các người giữ địa ngục buộc người ấy vào xe, và kéo đi kéo lại trên mặt đất đang cháy, đang bốc lửa, đang rực sáng… ",
  "mn130:14.1": "Này các Tỳ-kheo, các người giữ địa ngục đẩy người ấy lên và kéo xuống một ngọn núi than hồng lớn đang cháy, đang bốc lửa, đang rực sáng… ",
  "mn130:15.1": "Này các Tỳ-kheo, các người giữ địa ngục nắm lấy người ấy, đầu chúc xuống, chân giơ lên, và ném vào một vạc sắt nung đỏ đang cháy, đang bốc lửa, đang rực sáng. ",
  "mn130:15.2": "Người ấy ở đấy bị nấu sôi sùng sục. ",
  "mn130:15.3": "Người ấy ở đấy bị nấu sôi sùng sục, có lúc nổi lên trên, có lúc chìm xuống dưới, có lúc trôi ngang. ",
  "mn130:15.4": "Người ấy ở đấy cảm nhận những cảm giác đau đớn, dữ dội, khốc liệt, cay đắng, nhưng chưa chết cho đến khi nghiệp ác ấy chưa chấm dứt. ",
  "mn130:16.1": "Này các Tỳ-kheo, các người giữ địa ngục ném người ấy vào đại địa ngục. ",
  "mn130:16.2": "Và này các Tỳ-kheo, đại địa ngục ấy—",
  "mn130:16.3": "Có bốn góc, bốn cửa, ",
  "mn130:16.4": "Được chia thành từng phần, có kích thước; ",
  "mn130:16.5": "Có tường bao quanh bằng sắt, ",
  "mn130:16.6": "Được che kín bằng sắt. ",
  "mn130:16.7": "Đất của nó làm bằng sắt, ",
  "mn130:16.8": "Cháy rực với sức nóng; ",
  "mn130:16.9": "Rộng một trăm do-tuần khắp mọi phía, ",
  "mn130:16.10": "luôn luôn bao trùm. ",
  "mn130:17.1": "Này các Tỳ-kheo, ngọn lửa từ bức tường phía đông của đại địa ngục ấy bốc lên đập vào bức tường phía tây; ngọn lửa từ bức tường phía tây bốc lên đập vào bức tường phía đông; ngọn lửa từ bức tường phía bắc bốc lên đập vào bức tường phía nam; ngọn lửa từ bức tường phía nam bốc lên đập vào bức tường phía bắc; ngọn lửa từ dưới bốc lên đập vào phía trên; ngọn lửa từ trên bốc xuống đập vào phía dưới. ",
  "mn130:17.2": "Người ấy ở đó chịu những cảm thọ khổ đau, dữ dội, gay gắt, cay đắng, và chưa chết cho đến khi nghiệp ác ấy chưa chấm dứt. ",
  "mn130:18.1": "Này các Tỳ-kheo, có lúc, có thời, sau một thời gian dài, cánh cửa phía đông của đại địa ngục ấy mở ra. ",
  "mn130:18.2": "Người ấy ở đó chạy nhanh như gió. ",
  "mn130:18.3": "Khi người ấy chạy nhanh như gió, da cũng bị cháy, thịt cũng bị cháy, gân cũng bị cháy, xương cũng bốc khói, và khi được nhấc lên thì cũng như vậy. ",
  "mn130:18.4": "Này các Tỳ-kheo, khi người ấy vừa đến gần, cánh cửa ấy đóng lại. ",
  "mn130:18.5": "Người ấy ở đó chịu những cảm thọ khổ đau, dữ dội, gay gắt, cay đắng, và chưa chết cho đến khi nghiệp ác ấy chưa chấm dứt. ",
  "mn130:18.6": "Này các Tỳ-kheo, có lúc, có thời, sau một thời gian dài, cánh cửa phía tây của đại địa ngục ấy mở ra …v.v… ",
  "mn130:18.7": "cánh cửa phía bắc mở ra …v.v… ",
  "mn130:18.8": "cánh cửa phía nam mở ra. ",
  "mn130:18.9": "Người ấy ở đó chạy nhanh như gió. ",
  "mn130:18.10": "Khi người ấy chạy nhanh như gió, da cũng bị cháy, thịt cũng bị cháy, gân cũng bị cháy, xương cũng bốc khói, và khi được nhấc lên thì cũng như vậy. ",
  "mn130:18.11": "Này các Tỳ-kheo, khi người ấy vừa đến gần, cánh cửa ấy đóng lại. ",
  "mn130:18.12": "Người ấy ở đó chịu những cảm thọ khổ đau, dữ dội, gay gắt, cay đắng, và chưa chết cho đến khi nghiệp ác ấy chưa chấm dứt. ",
  "mn130:19.1": "Này các Tỳ-kheo, có lúc, có thời, sau một thời gian dài, cánh cửa phía đông của đại địa ngục ấy mở ra. ",
  "mn130:19.2": "Người ấy ở đó chạy nhanh như gió. ",
  "mn130:19.3": "Khi người ấy chạy nhanh như gió, da cũng bị cháy, thịt cũng bị cháy, gân cũng bị cháy, xương cũng bốc khói, và khi được nhấc lên thì cũng như vậy. ",
  "mn130:19.4": "Người ấy đi ra bằng cánh cửa đó. ",
  "mn130:20.1": "Này các Tỳ-kheo, ngay sau đại địa ngục ấy là một đại địa ngục phân. ",
  "mn130:20.2": "Người ấy rơi vào đó. ",
  "mn130:20.3": "Này các Tỳ-kheo, trong địa ngục phân ấy, những loài vật có miệng như kim châm xuyên qua da, xuyên qua da rồi xuyên qua thịt, xuyên qua thịt rồi xuyên qua gân, xuyên qua gân rồi xuyên qua xương, xuyên qua xương rồi ăn tủy xương. ",
  "mn130:20.4": "Người ấy ở đó chịu những cảm thọ khổ đau, dữ dội, gay gắt, cay đắng, và chưa chết cho đến khi nghiệp ác ấy chưa chấm dứt. ",
  "mn130:21.1": "Này các Tỳ-kheo, ngay sau địa ngục phân ấy là một đại địa ngục tro nóng. ",
  "mn130:21.2": "Người ấy rơi vào đó. ",
  "mn130:21.3": "Người ấy ở đó chịu những cảm thọ khổ đau, dữ dội, gay gắt, cay đắng, và chưa chết cho đến khi nghiệp ác ấy chưa chấm dứt. ",
  "mn130:22.1": "Này các Tỳ-kheo, ngay sau địa ngục tro nóng ấy là một rừng cây bông gòn lớn, cao một do tuần, có gai dài mười sáu ngón tay, đang cháy rực, bốc lửa, sáng chói. ",
  "mn130:22.2": "Ở đó, họ bị đẩy lên rồi lại bị kéo xuống. ",
  "mn130:22.3": "Người ấy ở đó chịu những cảm thọ khổ đau, dữ dội, gay gắt, cay đắng, và chưa chết cho đến khi nghiệp ác ấy chưa chấm dứt. ",
  "mn130:23.1": "Này các Tỳ-kheo, ngay sau rừng cây bông gòn ấy là một rừng cây lá kiếm lớn. ",
  "mn130:23.2": "Người ấy đi vào đó. ",
  "mn130:23.3": "Những chiếc lá bị gió thổi rụng xuống cắt đứt tay, cắt đứt chân, cắt đứt tay chân, cắt đứt tai, cắt đứt mũi, cắt đứt tai mũi của người ấy. ",
  "mn130:23.4": "Người ấy ở đó chịu những cảm thọ khổ đau, dữ dội, gay gắt, cay đắng, và chưa chết cho đến khi nghiệp ác ấy chưa chấm dứt. ",
  "mn130:24.1": "Này các Tỳ-kheo, ngay sau rừng cây lá kiếm ấy là một con sông nước kiềm lớn. ",
  "mn130:24.2": "Người ấy rơi vào đó. ",
  "mn130:24.3": "Người ấy ở đó bị trôi xuôi dòng, bị trôi ngược dòng, bị trôi xuôi ngược dòng. ",
  "mn130:24.4": "Người ấy ở đó chịu những cảm thọ khổ đau, dữ dội, gay gắt, cay đắng, và chưa chết cho đến khi nghiệp ác ấy chưa chấm dứt. ",
  "mn130:25.1": "Này các Tỳ-kheo, các người giữ địa ngục dùng lưỡi câu kéo người ấy lên, đặt trên bờ và nói như sau: ",
  "mn130:25.2": "‘Này người kia, ngươi muốn gì?’ ",
  "mn130:25.3": "Người ấy nói như sau: ",
  "mn130:25.4": "‘Thưa ngài, tôi đói.’ ",
  "mn130:25.5": "Này các Tỳ-kheo, các người giữ địa ngục dùng một cái kẹp sắt nung đỏ, đang cháy rực, bốc lửa, sáng chói, mở miệng người ấy ra và đặt một viên sắt nung đỏ, đang cháy rực, bốc lửa, sáng chói vào miệng. ",
  "mn130:25.6": "Nó đốt cháy môi, đốt cháy miệng, đốt cháy cổ họng, đốt cháy ngực, mang theo ruột và màng ruột đi ra từ phía dưới. ",
  "mn130:25.7": "Người ấy ở đó chịu những cảm thọ khổ đau, dữ dội, gay gắt, cay đắng, và chưa chết cho đến khi nghiệp ác ấy chưa chấm dứt. ",
  "mn130:26.1": "Này các Tỳ-kheo, các người giữ địa ngục nói với người ấy như sau: ",
  "mn130:26.2": "‘Này người kia, ngươi muốn gì?’ ",
  "mn130:26.3": "Người ấy nói như sau: ",
  "mn130:26.4": "‘Thưa ngài, tôi khát.’ ",
  "mn130:26.5": "Này các Tỳ-kheo, các người giữ địa ngục dùng một cái kẹp sắt nung đỏ, đang cháy rực, bốc lửa, sáng chói, mở miệng người ấy ra và đổ đồng nóng chảy, đang cháy rực, bốc lửa, sáng chói vào miệng. ",
  "mn130:26.6": "Nó đốt cháy môi, đốt cháy miệng, đốt cháy cổ họng, đốt cháy ngực, mang theo ruột và màng ruột đi ra từ phía dưới. ",
  "mn130:26.7": "Người ấy ở đó chịu những cảm thọ khổ đau, dữ dội, gay gắt, cay đắng, và chưa chết cho đến khi nghiệp ác ấy chưa chấm dứt. ",
  "mn130:27.1": "Này các Tỳ-kheo, các người giữ địa ngục lại ném người ấy vào đại địa ngục. ",
  "mn130:28.1": "Này các Tỳ-kheo, thuở xưa, vua Diêm Ma đã nghĩ như sau: ",
  "mn130:28.2": "‘Này chư vị, những ai làm các nghiệp ác, bất thiện trên đời, họ sẽ phải chịu những hình phạt khác nhau như thế này. ",
  "mn130:28.3": "Ước gì tôi được làm người. Và một vị Như Lai, A-la-hán, Chánh Đẳng Giác xuất hiện trên đời. Và tôi sẽ đến gần vị Thế Tôn ấy. ",
  "mn130:28.4": "Và vị Thế Tôn ấy sẽ thuyết pháp cho tôi. Và tôi sẽ hiểu được giáo pháp của vị Thế Tôn ấy.’ ",
  "mn130:29.1": "Này các Tỳ-kheo, điều này tôi không nói ra sau khi nghe từ một vị Sa-môn hay Bà-la-môn nào khác, mà chính tôi đã tự biết, tự thấy, tự chứng ngộ, nên tôi nói ra.” ",
  "mn130:30.1": "Thế Tôn đã nói điều này. ",
  "mn130:30.2": "Sau khi nói điều này, Thiện Thệ, bậc Đạo Sư, lại nói thêm điều này: ",
  "mn130:30.3": "“Những người bị sứ giả chư thiên nhắc nhở, ",
  "mn130:30.4": "mà còn lơ là, phóng dật; ",
  "mn130:30.5": "Họ sẽ phải đau khổ dài lâu, ",
  "mn130:30.6": "những người ấy sẽ tái sinh vào cảnh giới thấp kém. ",
  "mn130:30.7": "Còn những người thiện trí, bậc chân nhân, ",
  "mn130:30.8": "ở đây, bị sứ giả chư thiên nhắc nhở; ",
  "mn130:30.9": "Họ không bao giờ lơ là, phóng dật, ",
  "mn130:30.10": "trong giáo pháp cao quý. ",
  "mn130:30.11": "Thấy sự nguy hiểm trong chấp thủ, ",
  "mn130:30.12": "trong sự sinh và chết; ",
  "mn130:30.13": "Không chấp thủ, họ được giải thoát, ",
  "mn130:30.14": "trong sự chấm dứt sinh và chết. ",
  "mn130:30.15": "Họ đạt đến sự an toàn, hạnh phúc, ",
  "mn130:30.16": "đã chứng ngộ Niết-bàn ngay trong đời này; ",
  "mn130:30.17": "Vượt qua mọi oán thù và sợ hãi, ",
  "mn130:30.18": "họ đã vượt qua mọi khổ đau.” ",
  "mn130:30.19": "Kinh Sứ Giả Chư Thiên, thứ mười, chấm dứt. ",
  "mn130:30.20": "Phẩm Không, thứ ba, chấm dứt. ",
  "mn130:31.0": "Tóm tắt phẩm ấy: ",
  "mn130:31.1": "Không có hai loại, ",
  "mn130:31.2": "Pháp lạ lùng, hỗn loạn; ",
  "mn130:31.3": "Tên đất Aciravatī, ",
  "mn130:31.4": "Phiền não của Anuruddha; ",
  "mn130:31.5": "Kẻ ngu và người trí, và Sứ giả chư thiên, đó là mười."
}
window.BILARA["mn130"]["vi"]["mn130:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
