window.BILARA = window.BILARA || {};
window.BILARA["mn149"] = window.BILARA["mn149"] || {};
window.BILARA["mn149"]["vi"] = {
  "mn149:0.1": "Kinh Trung Bộ 149 ",
  "mn149:0.2": "Kinh Đại Lục Xứ ",
  "mn149:1.1": "Tôi nghe như vầy—",
  "mn149:1.2": "một thời Thế Tôn ở Sāvatthi, tại rừng Jeta, tu viện của Anāthapiṇḍika. ",
  "mn149:1.3": "Tại đó, Thế Tôn gọi các tỳ-kheo: ",
  "mn149:1.4": "“Này các tỳ-kheo.” ",
  "mn149:1.5": "“Bạch Thế Tôn,” các tỳ-kheo ấy đáp lời Thế Tôn. ",
  "mn149:1.6": "Thế Tôn nói điều này: ",
  "mn149:2.1": "“Này các tỳ-kheo, Ta sẽ giảng cho các ông về sáu nội ngoại xứ lớn. ",
  "mn149:2.2": "Hãy nghe và khéo suy nghiệm, Ta sẽ nói.” ",
  "mn149:2.3": "“Thưa vâng, bạch Thế Tôn,” các tỳ-kheo ấy đáp lời Thế Tôn. ",
  "mn149:2.4": "Thế Tôn nói điều này: ",
  "mn149:3.1": "“Này các tỳ-kheo, khi không biết, không thấy mắt đúng như thật, không biết, không thấy các hình sắc đúng như thật, không biết, không thấy nhãn thức đúng như thật, không biết, không thấy nhãn xúc đúng như thật, và bất cứ cảm thọ nào khởi lên do duyên nhãn xúc là lạc, khổ hay không khổ không lạc, cũng không biết, không thấy đúng như thật; thì người ấy đắm nhiễm vào mắt, đắm nhiễm vào các hình sắc, đắm nhiễm vào nhãn thức, đắm nhiễm vào nhãn xúc, và bất cứ cảm thọ nào khởi lên do duyên nhãn xúc là lạc, khổ hay không khổ không lạc, người ấy cũng đắm nhiễm vào đó. ",
  "mn149:3.2": "Với người sống quan sát vị ngọt, bị đắm nhiễm, bị trói buộc, bị mê mờ như vậy, trong tương lai năm thủ uẩn sẽ đi đến sự tích tụ. ",
  "mn149:3.3": "Và tham ái đưa đến tái sinh, đi kèm với hỷ và tham, tìm cầu sự thích thú chỗ này chỗ kia, tham ái ấy tăng trưởng trong người đó. ",
  "mn149:3.4": "Những nỗi khổ nhọc về thân tăng trưởng, những nỗi khổ nhọc về tâm tăng trưởng; ",
  "mn149:3.5": "những sự thiêu đốt về thân tăng trưởng, những sự thiêu đốt về tâm tăng trưởng; ",
  "mn149:3.6": "những sự nóng nảy về thân tăng trưởng, những sự nóng nảy về tâm tăng trưởng. ",
  "mn149:3.7": "Người ấy cảm nhận cả khổ thân lẫn khổ tâm. ",
  "mn149:4-7.1": "Này các tỳ-kheo, khi không biết, không thấy tai đúng như thật …pe… ",
  "mn149:4-7.2": "Này các tỳ-kheo, khi không biết, không thấy mũi đúng như thật …pe… ",
  "mn149:4-7.3": "Này các tỳ-kheo, khi không biết, không thấy lưỡi đúng như thật …pe… ",
  "mn149:4-7.4": "Này các tỳ-kheo, khi không biết, không thấy thân đúng như thật …pe… ",
  "mn149:4-7.5": "Này các tỳ-kheo, khi không biết, không thấy ý đúng như thật, không biết, không thấy các pháp đúng như thật, không biết, không thấy ý thức đúng như thật, không biết, không thấy ý xúc đúng như thật, và bất cứ cảm thọ nào khởi lên do duyên ý xúc là lạc, khổ hay không khổ không lạc, cũng không biết, không thấy đúng như thật; thì người ấy đắm nhiễm vào ý, đắm nhiễm vào các pháp, đắm nhiễm vào ý thức, đắm nhiễm vào ý xúc, và bất cứ cảm thọ nào khởi lên do duyên ý xúc là lạc, khổ hay không khổ không lạc, người ấy cũng đắm nhiễm vào đó. ",
  "mn149:8.1": "Với người sống quan sát vị ngọt, bị đắm nhiễm, bị trói buộc, bị mê mờ như vậy, trong tương lai năm thủ uẩn sẽ đi đến sự tích tụ. ",
  "mn149:8.2": "Và tham ái đưa đến tái sinh, đi kèm với hỷ và tham, tìm cầu sự thích thú chỗ này chỗ kia, tham ái ấy tăng trưởng trong người đó. ",
  "mn149:8.3": "Những nỗi khổ nhọc về thân tăng trưởng, những nỗi khổ nhọc về tâm tăng trưởng; ",
  "mn149:8.4": "những sự thiêu đốt về thân tăng trưởng, những sự thiêu đốt về tâm tăng trưởng; ",
  "mn149:8.5": "những sự nóng nảy về thân tăng trưởng, những sự nóng nảy về tâm tăng trưởng. ",
  "mn149:8.6": "Người ấy cảm nhận cả khổ thân lẫn khổ tâm. ",
  "mn149:9.1": "Nhưng này các tỳ-kheo, khi biết và thấy mắt đúng như thật, biết và thấy các hình sắc đúng như thật, biết và thấy nhãn thức đúng như thật, biết và thấy nhãn xúc đúng như thật, và bất cứ cảm thọ nào khởi lên do duyên nhãn xúc là lạc, khổ hay không khổ không lạc, cũng biết và thấy đúng như thật; thì người ấy không đắm nhiễm vào mắt, không đắm nhiễm vào các hình sắc, không đắm nhiễm vào nhãn thức, không đắm nhiễm vào nhãn xúc, và bất cứ cảm thọ nào khởi lên do duyên nhãn xúc là lạc, khổ hay không khổ không lạc, người ấy cũng không đắm nhiễm vào đó. ",
  "mn149:9.2": "Với người sống quan sát sự nguy hại, không bị đắm nhiễm, không bị trói buộc, không bị mê mờ như vậy, trong tương lai năm thủ uẩn sẽ đi đến sự giảm trừ. ",
  "mn149:9.3": "Và tham ái đưa đến tái sinh, đi kèm với hỷ và tham, tìm cầu sự thích thú chỗ này chỗ kia, tham ái ấy được đoạn tận trong người đó. ",
  "mn149:9.4": "Những nỗi khổ nhọc về thân được đoạn tận, những nỗi khổ nhọc về tâm được đoạn tận; ",
  "mn149:9.5": "những sự thiêu đốt về thân được đoạn tận, những sự thiêu đốt về tâm được đoạn tận; ",
  "mn149:9.6": "những sự nóng nảy về thân được đoạn tận, những sự nóng nảy về tâm được đoạn tận. ",
  "mn149:9.7": "Người ấy cảm nhận cả lạc về thân lẫn lạc về tâm. ",
  "mn149:10.1": "Cái thấy của người như thật ấy là chánh kiến; ",
  "mn149:10.2": "tư duy của người như thật ấy là chánh tư duy; ",
  "mn149:10.3": "nỗ lực của người như thật ấy là chánh tinh tấn; ",
  "mn149:10.4": "niệm của người như thật ấy là chánh niệm; ",
  "mn149:10.5": "định của người như thật ấy là chánh định. ",
  "mn149:10.6": "Trước đó, thân nghiệp, khẩu nghiệp và mạng sống của người ấy đã hoàn toàn thanh tịnh. ",
  "mn149:10.7": "Như vậy, con đường tám chánh cao quý này đi đến sự viên mãn nhờ tu tập. ",
  "mn149:10.8": "Với người tu tập con đường tám chánh cao quý này như vậy, bốn niệm xứ cũng đi đến sự viên mãn nhờ tu tập, bốn chánh cần cũng đi đến sự viên mãn nhờ tu tập, bốn thần túc cũng đi đến sự viên mãn nhờ tu tập, năm căn cũng đi đến sự viên mãn nhờ tu tập, năm lực cũng đi đến sự viên mãn nhờ tu tập, bảy yếu tố giác ngộ cũng đi đến sự viên mãn nhờ tu tập. ",
  "mn149:10.9": "Hai pháp này vận hành song hành đối với người ấy— ",
  "mn149:10.10": "chỉ và quán. ",
  "mn149:10.11": "Người ấy thấu hiểu bằng thắng trí những pháp cần phải thấu hiểu bằng thắng trí. ",
  "mn149:10.12": "Người ấy đoạn tận bằng thắng trí những pháp cần phải đoạn tận bằng thắng trí. ",
  "mn149:10.13": "Người ấy tu tập bằng thắng trí những pháp cần phải tu tập bằng thắng trí. ",
  "mn149:10.14": "Người ấy chứng ngộ bằng thắng trí những pháp cần phải chứng ngộ bằng thắng trí. ",
  "mn149:11.1": "Và này các tỳ-kheo, những pháp nào cần phải thấu hiểu bằng thắng trí? ",
  "mn149:11.2": "Cần phải nói rằng đó là ‘năm thủ uẩn’, ",
  "mn149:11.3": "tức là—sắc thủ uẩn, thọ thủ uẩn, tưởng thủ uẩn, hành thủ uẩn, thức thủ uẩn. ",
  "mn149:11.4": "Những pháp này cần phải thấu hiểu bằng thắng trí. ",
  "mn149:11.5": "Và này các tỳ-kheo, những pháp nào cần phải đoạn tận bằng thắng trí? ",
  "mn149:11.6": "Vô minh và hữu ái— ",
  "mn149:11.7": "những pháp này cần phải đoạn tận bằng thắng trí. ",
  "mn149:11.8": "Và này các tỳ-kheo, những pháp nào cần phải tu tập bằng thắng trí? ",
  "mn149:11.9": "Chỉ và quán— ",
  "mn149:11.10": "những pháp này cần phải tu tập bằng thắng trí. ",
  "mn149:11.11": "Và này các tỳ-kheo, những pháp nào cần phải chứng ngộ bằng thắng trí? ",
  "mn149:11.12": "Minh và giải thoát— ",
  "mn149:11.13": "những pháp này cần phải chứng ngộ bằng thắng trí. ",
  "mn149:12-18.1": "Này các tỳ-kheo, khi biết và thấy tai đúng như thật …pe… ",
  "mn149:12-18.2": "Này các tỳ-kheo, khi biết và thấy mũi đúng như thật …pe… ",
  "mn149:12-18.3": "Này các tỳ-kheo, khi biết và thấy lưỡi đúng như thật …pe… ",
  "mn149:12-18.4": "Này các tỳ-kheo, khi biết và thấy thân đúng như thật …pe… ",
  "mn149:12-18.5": "Này các tỳ-kheo, khi biết và thấy ý đúng như thật, biết và thấy các pháp đúng như thật, biết và thấy ý thức đúng như thật, biết và thấy ý xúc đúng như thật, và bất cứ cảm thọ nào khởi lên do duyên ý xúc là lạc, khổ hay không khổ không lạc, cũng biết và thấy đúng như thật; thì người ấy không đắm nhiễm vào ý, không đắm nhiễm vào các pháp, không đắm nhiễm vào ý thức, không đắm nhiễm vào ý xúc, và bất cứ cảm thọ nào khởi lên do duyên ý xúc là lạc, khổ hay không khổ không lạc, người ấy cũng không đắm nhiễm vào đó. ",
  "mn149:19.1": "Với người sống quan sát sự nguy hại, không bị đắm nhiễm, không bị trói buộc, không bị mê mờ như vậy, trong tương lai năm thủ uẩn sẽ đi đến sự giảm trừ. ",
  "mn149:19.2": "Và tham ái đưa đến tái sinh, đi kèm với hỷ và tham, tìm cầu sự thích thú chỗ này chỗ kia, tham ái ấy được đoạn tận trong người đó. ",
  "mn149:19.3": "Những nỗi khổ nhọc về thân được đoạn tận, những nỗi khổ nhọc về tâm được đoạn tận; ",
  "mn149:19.4": "những sự thiêu đốt về thân được đoạn tận, những sự thiêu đốt về tâm được đoạn tận; ",
  "mn149:19.5": "những sự nóng nảy về thân được đoạn tận, những sự nóng nảy về tâm được đoạn tận. ",
  "mn149:19.6": "Người ấy cảm nhận cả lạc về thân lẫn lạc về tâm. ",
  "mn149:20.1": "Cái thấy của người như thật ấy là chánh kiến; ",
  "mn149:20.2": "tư duy của người như thật ấy là chánh tư duy; ",
  "mn149:20.3": "nỗ lực của người như thật ấy là chánh tinh tấn; ",
  "mn149:20.4": "niệm của người như thật ấy là chánh niệm; ",
  "mn149:20.5": "định của người như thật ấy là chánh định. ",
  "mn149:20.6": "Trước đó, thân nghiệp, khẩu nghiệp và mạng sống của người ấy đã hoàn toàn thanh tịnh. ",
  "mn149:20.7": "Như vậy, con đường tám chánh cao quý này đi đến sự viên mãn nhờ tu tập. ",
  "mn149:21.1": "Với người tu tập con đường tám chánh cao quý này như vậy, bốn niệm xứ cũng đi đến sự viên mãn nhờ tu tập, bốn chánh cần cũng đi đến sự viên mãn nhờ tu tập, bốn thần túc cũng đi đến sự viên mãn nhờ tu tập, năm căn cũng đi đến sự viên mãn nhờ tu tập, năm lực cũng đi đến sự viên mãn nhờ tu tập, bảy yếu tố giác ngộ cũng đi đến sự viên mãn nhờ tu tập. ",
  "mn149:22.1": "Hai pháp này vận hành song hành đối với người ấy— ",
  "mn149:22.2": "chỉ và quán. ",
  "mn149:22.3": "Người ấy thấu hiểu bằng thắng trí những pháp cần phải thấu hiểu bằng thắng trí. ",
  "mn149:22.4": "Người ấy đoạn tận bằng thắng trí những pháp cần phải đoạn tận bằng thắng trí. ",
  "mn149:22.5": "Người ấy tu tập bằng thắng trí những pháp cần phải tu tập bằng thắng trí. ",
  "mn149:22.6": "Người ấy chứng ngộ bằng thắng trí những pháp cần phải chứng ngộ bằng thắng trí. ",
  "mn149:23.1": "Và này các tỳ-kheo, những pháp nào cần phải thấu hiểu bằng thắng trí? ",
  "mn149:23.2": "Cần phải nói rằng đó là ‘năm thủ uẩn’, tức là— ",
  "mn149:23.3": "sắc thủ uẩn, thọ thủ uẩn, tưởng thủ uẩn, hành thủ uẩn, thức thủ uẩn. ",
  "mn149:23.4": "Những pháp này cần phải thấu hiểu bằng thắng trí. ",
  "mn149:24.1": "Và này các tỳ-kheo, những pháp nào cần phải đoạn tận bằng thắng trí? ",
  "mn149:24.2": "Vô minh và hữu ái— ",
  "mn149:24.3": "những pháp này cần phải đoạn tận bằng thắng trí. ",
  "mn149:25.1": "Và này các tỳ-kheo, những pháp nào cần phải tu tập bằng thắng trí? ",
  "mn149:25.2": "Chỉ và quán— ",
  "mn149:25.3": "những pháp này cần phải tu tập bằng thắng trí. ",
  "mn149:26.1": "Và này các tỳ-kheo, những pháp nào cần phải chứng ngộ bằng thắng trí? ",
  "mn149:26.2": "Minh và giải thoát— ",
  "mn149:26.3": "những pháp này cần phải chứng ngộ bằng thắng trí.” ",
  "mn149:26.4": "Thế Tôn đã nói như vậy. ",
  "mn149:26.5": "Các tỳ-kheo ấy hoan hỷ, vui mừng trước lời dạy của Thế Tôn. ",
  "mn149:26.6": "Kinh Đại Lục Xứ là thứ bảy, đã kết thúc. "
}
window.BILARA["mn149"]["vi"]["mn149:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
