window.BILARA = window.BILARA || {};
window.BILARA["mn148"] = window.BILARA["mn148"] || {};
window.BILARA["mn148"]["vi"] = {
  "mn148:0.1": "Majjhima Nikāya 148 ",
  "mn148:0.2": "Kinh Sáu Sáu ",
  "mn148:1.1": "Tôi nghe như vầy—",
  "mn148:1.2": "một thời Đức Thế Tôn ở Xá-vệ, tại rừng Kỳ-đà, vườn của ông Cấp Cô Độc. ",
  "mn148:1.3": "Tại đó, Đức Thế Tôn gọi các tỳ-kheo: ",
  "mn148:1.4": "“Này các tỳ-kheo.” ",
  "mn148:1.5": "“Thưa Ngài,” các tỳ-kheo ấy đáp lời Đức Thế Tôn. ",
  "mn148:1.6": "Đức Thế Tôn nói điều này: ",
  "mn148:2.1": "“Này các tỳ-kheo, Ta sẽ dạy các ông lời dạy tốt đẹp ở chặng đầu, tốt đẹp ở chặng giữa, tốt đẹp ở chặng cuối, có ý nghĩa, có văn từ, Ta sẽ trình bày đời sống thanh tịnh hoàn toàn đầy đủ và trong sạch, đó là—",
  "mn148:2.2": "sáu nhóm sáu. ",
  "mn148:2.3": "Hãy nghe điều đó, hãy khéo léo chú tâm, Ta sẽ nói.” ",
  "mn148:2.4": "“Thưa vâng, bạch Ngài,” các tỳ-kheo ấy đáp lời Đức Thế Tôn. ",
  "mn148:2.5": "Đức Thế Tôn nói điều này: ",
  "mn148:3.1": "“Sáu cửa ngõ bên trong cần được biết, sáu cửa ngõ bên ngoài cần được biết, sáu nhóm nhận biết cần được biết, sáu nhóm tiếp chạm cần được biết, sáu nhóm cảm thọ cần được biết, sáu nhóm ham muốn cần được biết. ",
  "mn148:4.1": "‘Sáu cửa ngõ bên trong cần được biết’—",
  "mn148:4.2": "điều này đã được nói như vậy. Điều này được nói dựa trên cái gì? ",
  "mn148:4.3": "Cửa ngõ mắt, cửa ngõ tai, cửa ngõ mũi, cửa ngõ lưỡi, cửa ngõ thân, cửa ngõ tâm ý. ",
  "mn148:4.4": "‘Sáu cửa ngõ bên trong cần được biết’—",
  "mn148:4.5": "những gì đã được nói như vậy, chính là dựa trên điều này mà nói. ",
  "mn148:4.6": "Đây là nhóm sáu thứ nhất. ",
  "mn148:5.1": "‘Sáu cửa ngõ bên ngoài cần được biết’—",
  "mn148:5.2": "điều này đã được nói như vậy. Điều này được nói dựa trên cái gì? ",
  "mn148:5.3": "Cửa ngõ hình ảnh, cửa ngõ âm thanh, cửa ngõ mùi, cửa ngõ vị, cửa ngõ sự chạm, cửa ngõ đối tượng tâm ý. ",
  "mn148:5.4": "‘Sáu cửa ngõ bên ngoài cần được biết’—",
  "mn148:5.5": "những gì đã được nói như vậy, chính là dựa trên điều này mà nói. ",
  "mn148:5.6": "Đây là nhóm sáu thứ hai. ",
  "mn148:6.1": "‘Sáu nhóm nhận biết cần được biết’—",
  "mn148:6.2": "điều này đã được nói như vậy. Điều này được nói dựa trên cái gì? ",
  "mn148:6.3": "Dựa trên mắt và các hình ảnh, sự nhận biết của mắt khởi lên, ",
  "mn148:6.4": "dựa trên tai và các âm thanh, sự nhận biết của tai khởi lên, ",
  "mn148:6.5": "dựa trên mũi và các mùi, sự nhận biết của mũi khởi lên, ",
  "mn148:6.6": "dựa trên lưỡi và các vị, sự nhận biết của lưỡi khởi lên, ",
  "mn148:6.7": "dựa trên thân và các sự chạm, sự nhận biết của thân khởi lên, ",
  "mn148:6.8": "dựa trên tâm ý và các đối tượng tâm ý, sự nhận biết của tâm ý khởi lên. ",
  "mn148:6.9": "‘Sáu nhóm nhận biết cần được biết’—",
  "mn148:6.10": "những gì đã được nói như vậy, chính là dựa trên điều này mà nói. ",
  "mn148:6.11": "Đây là nhóm sáu thứ ba. ",
  "mn148:7.1": "‘Sáu nhóm tiếp chạm cần được biết’—",
  "mn148:7.2": "điều này đã được nói như vậy. Điều này được nói dựa trên cái gì? ",
  "mn148:7.3": "Dựa trên mắt và các hình ảnh, sự nhận biết của mắt khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm; ",
  "mn148:7.4": "dựa trên tai và các âm thanh, sự nhận biết của tai khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm; ",
  "mn148:7.5": "dựa trên mũi và các mùi, sự nhận biết của mũi khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm; ",
  "mn148:7.6": "dựa trên lưỡi và các vị, sự nhận biết của lưỡi khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm; ",
  "mn148:7.7": "dựa trên thân và các sự chạm, sự nhận biết của thân khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm; ",
  "mn148:7.8": "dựa trên tâm ý và các đối tượng tâm ý, sự nhận biết của tâm ý khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm. ",
  "mn148:7.9": "‘Sáu nhóm tiếp chạm cần được biết’—",
  "mn148:7.10": "những gì đã được nói như vậy, chính là dựa trên điều này mà nói. ",
  "mn148:7.11": "Đây là nhóm sáu thứ tư. ",
  "mn148:8.1": "‘Sáu nhóm cảm thọ cần được biết’—",
  "mn148:8.2": "điều này đã được nói như vậy. Điều này được nói dựa trên cái gì? ",
  "mn148:8.3": "Dựa trên mắt và các hình ảnh, sự nhận biết của mắt khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm, do sự tiếp chạm làm điều kiện mà có cảm thọ; ",
  "mn148:8.4": "dựa trên tai và các âm thanh, sự nhận biết của tai khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm, do sự tiếp chạm làm điều kiện mà có cảm thọ; ",
  "mn148:8.5": "dựa trên mũi và các mùi, sự nhận biết của mũi khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm, do sự tiếp chạm làm điều kiện mà có cảm thọ; ",
  "mn148:8.6": "dựa trên lưỡi và các vị, sự nhận biết của lưỡi khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm, do sự tiếp chạm làm điều kiện mà có cảm thọ; ",
  "mn148:8.7": "dựa trên thân và các sự chạm, sự nhận biết của thân khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm, do sự tiếp chạm làm điều kiện mà có cảm thọ; ",
  "mn148:8.8": "dựa trên tâm ý và các đối tượng tâm ý, sự nhận biết của tâm ý khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm, do sự tiếp chạm làm điều kiện mà có cảm thọ. ",
  "mn148:8.9": "‘Sáu nhóm cảm thọ cần được biết’—",
  "mn148:8.10": "những gì đã được nói như vậy, chính là dựa trên điều này mà nói. ",
  "mn148:8.11": "Đây là nhóm sáu thứ năm. ",
  "mn148:9.1": "‘Sáu nhóm ham muốn cần được biết’—",
  "mn148:9.2": "điều này đã được nói như vậy. Điều này được nói dựa trên cái gì? ",
  "mn148:9.3": "Dựa trên mắt và các hình ảnh, sự nhận biết của mắt khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm, do sự tiếp chạm làm điều kiện mà có cảm thọ, do cảm thọ làm điều kiện mà có ham muốn; ",
  "mn148:9.4": "dựa trên tai và các âm thanh, sự nhận biết của tai khởi lên …v.v… ",
  "mn148:9.5": "dựa trên mũi và các mùi, sự nhận biết của mũi khởi lên … ",
  "mn148:9.6": "dựa trên lưỡi và các vị, sự nhận biết của lưỡi khởi lên … ",
  "mn148:9.7": "dựa trên thân và các sự chạm, sự nhận biết của thân khởi lên … ",
  "mn148:9.8": "dựa trên tâm ý và các đối tượng tâm ý, sự nhận biết của tâm ý khởi lên, sự gặp gỡ của ba cái này là sự tiếp chạm, do sự tiếp chạm làm điều kiện mà có cảm thọ, do cảm thọ làm điều kiện mà có ham muốn. ",
  "mn148:9.9": "‘Sáu nhóm ham muốn cần được biết’—",
  "mn148:9.10": "những gì đã được nói như vậy, chính là dựa trên điều này mà nói. ",
  "mn148:9.11": "Đây là nhóm sáu thứ sáu. ",
  "mn148:10.1": "Nếu ai nói rằng ‘Mắt là cái tôi’, điều đó không đúng. ",
  "mn148:10.2": "Sự sinh ra và sự mất đi của mắt được nhận thấy. ",
  "mn148:10.3": "Nhưng với cái gì mà sự sinh ra và sự mất đi được nhận thấy, người ta sẽ phải đi đến kết luận rằng: ‘Cái tôi của tôi sinh ra và mất đi’. ",
  "mn148:10.4": "Do đó, điều này không đúng: ",
  "mn148:10.5": "nếu ai nói rằng ‘mắt là cái tôi’. ",
  "mn148:10.6": "Như vậy, mắt không phải là cái tôi. ",
  "mn148:10.7": "Nếu ai nói rằng ‘Các hình ảnh là cái tôi’, điều đó không đúng. ",
  "mn148:10.8": "Sự sinh ra và sự mất đi của các hình ảnh được nhận thấy. ",
  "mn148:10.9": "Nhưng với cái gì mà sự sinh ra và sự mất đi được nhận thấy, người ta sẽ phải đi đến kết luận rằng: ‘Cái tôi của tôi sinh ra và mất đi’. ",
  "mn148:10.10": "Do đó, điều này không đúng: ",
  "mn148:10.11": "nếu ai nói rằng ‘các hình ảnh là cái tôi’. ",
  "mn148:10.12": "Như vậy, mắt không phải là cái tôi, các hình ảnh không phải là cái tôi. ",
  "mn148:10.13": "Nếu ai nói rằng ‘Sự nhận biết của mắt là cái tôi’, điều đó không đúng. ",
  "mn148:10.14": "Sự sinh ra và sự mất đi của sự nhận biết của mắt được nhận thấy. ",
  "mn148:10.15": "Nhưng với cái gì mà sự sinh ra và sự mất đi được nhận thấy, người ta sẽ phải đi đến kết luận rằng: ‘Cái tôi của tôi sinh ra và mất đi’. ",
  "mn148:10.16": "Do đó, điều này không đúng: ",
  "mn148:10.17": "nếu ai nói rằng ‘sự nhận biết của mắt là cái tôi’. ",
  "mn148:10.18": "Như vậy, mắt không phải là cái tôi, các hình ảnh không phải là cái tôi, sự nhận biết của mắt không phải là cái tôi. ",
  "mn148:10.19": "Nếu ai nói rằng ‘Sự tiếp chạm của mắt là cái tôi’, điều đó không đúng. ",
  "mn148:10.20": "Sự sinh ra và sự mất đi của sự tiếp chạm của mắt được nhận thấy. ",
  "mn148:10.21": "Nhưng với cái gì mà sự sinh ra và sự mất đi được nhận thấy, người ta sẽ phải đi đến kết luận rằng: ‘Cái tôi của tôi sinh ra và mất đi’. ",
  "mn148:10.22": "Do đó, điều này không đúng: ",
  "mn148:10.23": "nếu ai nói rằng ‘sự tiếp chạm của mắt là cái tôi’. ",
  "mn148:10.24": "Như vậy, mắt không phải là cái tôi, các hình ảnh không phải là cái tôi, sự nhận biết của mắt không phải là cái tôi, sự tiếp chạm của mắt không phải là cái tôi. ",
  "mn148:10.25": "Nếu ai nói rằng ‘Cảm thọ là cái tôi’, điều đó không đúng. ",
  "mn148:10.26": "Sự sinh ra và sự mất đi của cảm thọ được nhận thấy. ",
  "mn148:10.27": "Nhưng với cái gì mà sự sinh ra và sự mất đi được nhận thấy, người ta sẽ phải đi đến kết luận rằng: ‘Cái tôi của tôi sinh ra và mất đi’. ",
  "mn148:10.28": "Do đó, điều này không đúng: ",
  "mn148:10.29": "nếu ai nói rằng ‘cảm thọ là cái tôi’. ",
  "mn148:10.30": "Như vậy, mắt không phải là cái tôi, các hình ảnh không phải là cái tôi, sự nhận biết của mắt không phải là cái tôi, sự tiếp chạm của mắt không phải là cái tôi, cảm thọ không phải là cái tôi. ",
  "mn148:10.31": "Nếu ai nói rằng ‘Ham muốn là cái tôi’, điều đó không đúng. ",
  "mn148:10.32": "Sự sinh ra và sự mất đi của ham muốn được nhận thấy. ",
  "mn148:10.33": "Nhưng với cái gì mà sự sinh ra và sự mất đi được nhận thấy, người ta sẽ phải đi đến kết luận rằng: ‘Cái tôi của tôi sinh ra và mất đi’. ",
  "mn148:10.34": "Do đó, điều này không đúng: ",
  "mn148:10.35": "nếu ai nói rằng ‘ham muốn là cái tôi’. ",
  "mn148:10.36": "Như vậy, mắt không phải là cái tôi, các hình ảnh không phải là cái tôi, sự nhận biết của mắt không phải là cái tôi, sự tiếp chạm của mắt không phải là cái tôi, cảm thọ không phải là cái tôi, ham muốn không phải là cái tôi. ",
  "mn148:11.1": "Nếu ai nói rằng ‘Tai là cái tôi’ …v.v… ",
  "mn148:11.2": "Nếu ai nói rằng ‘Mũi là cái tôi’ …v.v… ",
  "mn148:11.3": "Nếu ai nói rằng ‘Lưỡi là cái tôi’ …v.v… ",
  "mn148:11.4": "Nếu ai nói rằng ‘Thân là cái tôi’ …v.v… ",
  "mn148:11.5": "Nếu ai nói rằng ‘Tâm ý là cái tôi’, điều đó không đúng. ",
  "mn148:11.6": "Sự sinh ra và sự mất đi của tâm ý được nhận thấy. ",
  "mn148:11.7": "Nhưng với cái gì mà sự sinh ra và sự mất đi được nhận thấy, người ta sẽ phải đi đến kết luận rằng: ‘Cái tôi của tôi sinh ra và mất đi’. ",
  "mn148:11.8": "Do đó, điều này không đúng: ",
  "mn148:11.9": "nếu ai nói rằng ‘tâm ý là cái tôi’. ",
  "mn148:11.10": "Như vậy, tâm ý không phải là cái tôi. ",
  "mn148:12.1": "Nếu ai nói rằng ‘Các đối tượng tâm ý là cái tôi’, điều đó không đúng. ",
  "mn148:12.2": "Sự sinh ra và sự mất đi của các đối tượng tâm ý được nhận thấy. ",
  "mn148:12.3": "Nhưng với cái gì mà sự sinh ra và sự mất đi được nhận thấy, người ta sẽ phải đi đến kết luận rằng: ‘Cái tôi của tôi sinh ra và mất đi’. ",
  "mn148:12.4": "Do đó, điều này không đúng: ",
  "mn148:12.5": "‘Các pháp là tự ngã’, ai nói như vậy.",
  "mn148:12.6": "Như vậy, ý không phải tự ngã, các pháp không phải tự ngã.",
  "mn148:13.1": "‘Ý thức là tự ngã’, ai nói như vậy thì không hợp lý.",
  "mn148:13.2": "Sự sinh và sự diệt của ý thức được nhận thấy rõ.",
  "mn148:13.3": "Với cái gì mà sự sinh và sự diệt được nhận thấy rõ, người ấy sẽ đi đến kết luận rằng: ‘Tự ngã của tôi sinh lên và diệt đi’.",
  "mn148:13.4": "Vì thế, điều này không hợp lý:",
  "mn148:13.5": "ai nói rằng ‘ý thức là tự ngã’.",
  "mn148:13.6": "Như vậy, ý không phải tự ngã, các pháp không phải tự ngã, ý thức không phải tự ngã.",
  "mn148:14.1": "‘Ý tiếp chạm là tự ngã’, ai nói như vậy thì không hợp lý.",
  "mn148:14.2": "Sự sinh và sự diệt của ý tiếp chạm được nhận thấy rõ.",
  "mn148:14.3": "Với cái gì mà sự sinh và sự diệt được nhận thấy rõ, người ấy sẽ đi đến kết luận rằng: ‘Tự ngã của tôi sinh lên và diệt đi’.",
  "mn148:14.4": "Vì thế, điều này không hợp lý:",
  "mn148:14.5": "ai nói rằng ‘ý tiếp chạm là tự ngã’.",
  "mn148:14.6": "Như vậy, ý không phải tự ngã, các pháp không phải tự ngã, ý thức không phải tự ngã, ý tiếp chạm không phải tự ngã.",
  "mn148:15.1": "‘Cảm thọ là tự ngã’, ai nói như vậy thì không hợp lý.",
  "mn148:15.2": "Sự sinh và sự diệt của cảm thọ được nhận thấy rõ.",
  "mn148:15.3": "Với cái gì mà sự sinh và sự diệt được nhận thấy rõ, người ấy sẽ đi đến kết luận rằng: ‘Tự ngã của tôi sinh lên và diệt đi’.",
  "mn148:15.4": "Vì thế, điều này không hợp lý:",
  "mn148:15.5": "ai nói rằng ‘cảm thọ là tự ngã’.",
  "mn148:15.6": "Như vậy, ý không phải tự ngã, các pháp không phải tự ngã, ý thức không phải tự ngã, ý tiếp chạm không phải tự ngã, cảm thọ không phải tự ngã.",
  "mn148:15.7": "‘Tham ái là tự ngã’, ai nói như vậy thì không hợp lý.",
  "mn148:15.8": "Sự sinh và sự diệt của tham ái được nhận thấy rõ.",
  "mn148:15.9": "Với cái gì mà sự sinh và sự diệt được nhận thấy rõ, người ấy sẽ đi đến kết luận rằng: ‘Tự ngã của tôi sinh lên và diệt đi’.",
  "mn148:15.10": "Vì thế, điều này không hợp lý:",
  "mn148:15.11": "ai nói rằng ‘tham ái là tự ngã’.",
  "mn148:15.12": "Như vậy, ý không phải tự ngã, các pháp không phải tự ngã, ý thức không phải tự ngã, ý tiếp chạm không phải tự ngã, cảm thọ không phải tự ngã, tham ái không phải tự ngã.",
  "mn148:16.1": "Này các tỳ-kheo, đây là con đường dẫn đến sự hình thành thân kiến—",
  "mn148:16.2": "xem mắt là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’;",
  "mn148:17-21.1": "xem các hình sắc là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’;",
  "mn148:17-21.2": "xem nhãn thức là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’;",
  "mn148:17-21.3": "xem nhãn xúc là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’;",
  "mn148:17-21.4": "xem cảm thọ là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’;",
  "mn148:17-21.5": "xem tham ái là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’;",
  "mn148:17-21.6": "xem tai là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’ …pe… ",
  "mn148:17-21.7": "xem mũi là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’ …pe… ",
  "mn148:17-21.8": "xem lưỡi là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’ …pe… ",
  "mn148:17-21.9": "xem thân là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’ …pe… ",
  "mn148:17-21.10": "xem ý là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’, xem các pháp là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’, xem ý thức là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’, xem ý tiếp chạm là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’, xem cảm thọ là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’, xem tham ái là: ‘Cái này là của tôi, cái này là tôi, cái này là tự ngã của tôi’.",
  "mn148:22.1": "Này các tỳ-kheo, đây là con đường dẫn đến sự chấm dứt thân kiến—",
  "mn148:22.2": "xem mắt là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’.",
  "mn148:23-27.1": "Xem các hình sắc là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’.",
  "mn148:23-27.2": "Xem nhãn thức là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’.",
  "mn148:23-27.3": "Xem nhãn xúc là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’.",
  "mn148:23-27.4": "Xem cảm thọ là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’.",
  "mn148:23-27.5": "Xem tham ái là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’.",
  "mn148:23-27.6": "Xem tai là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’ …pe… ",
  "mn148:23-27.7": "xem mũi là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’ …pe… ",
  "mn148:23-27.8": "xem lưỡi là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’ …pe… ",
  "mn148:23-27.9": "xem thân là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’ …pe… ",
  "mn148:23-27.10": "xem ý là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’.",
  "mn148:23-27.11": "Xem các pháp là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’.",
  "mn148:23-27.12": "Xem ý thức là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’.",
  "mn148:23-27.13": "Xem ý tiếp chạm là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’.",
  "mn148:23-27.14": "Xem cảm thọ là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’.",
  "mn148:23-27.15": "Xem tham ái là: ‘Cái này không phải của tôi, cái này không phải là tôi, cái này không phải tự ngã của tôi’.",
  "mn148:28.1": "Này các tỳ-kheo, do duyên mắt và các hình sắc, nhãn thức khởi lên; sự gặp gỡ của ba pháp này là sự tiếp chạm; do duyên tiếp chạm khởi lên cảm giác lạc, khổ, hay không khổ không lạc.",
  "mn148:28.2": "Khi được chạm bởi cảm giác lạc, người ấy hoan hỷ, ca ngợi và đắm chìm trong đó.",
  "mn148:28.3": "Khuynh hướng tham muốn ngủ ngầm trong người ấy.",
  "mn148:28.4": "Khi được chạm bởi cảm giác khổ, người ấy sầu muộn, than vãn, khóc lóc, đấm ngực, rơi vào mê mờ.",
  "mn148:28.5": "Khuynh hướng giận dữ ngủ ngầm trong người ấy.",
  "mn148:28.6": "Khi được chạm bởi cảm giác không khổ không lạc, người ấy không hiểu rõ như thật về sự sinh, sự diệt, vị ngọt, sự nguy hại và sự thoát ly của cảm giác đó.",
  "mn148:28.7": "Khuynh hướng mê mờ ngủ ngầm trong người ấy.",
  "mn148:28.8": "Này các tỳ-kheo, thật vậy, nếu không từ bỏ khuynh hướng tham muốn ngủ ngầm đối với cảm giác lạc, không tẩy trừ khuynh hướng giận dữ ngủ ngầm đối với cảm giác khổ, không nhổ tận gốc khuynh hướng mê mờ ngủ ngầm đối với cảm giác không khổ không lạc, không từ bỏ vô minh, không làm khởi sinh minh, mà có thể chấm dứt khổ đau ngay trong đời này—điều đó không thể xảy ra.",
  "mn148:29-33.1": "Này các tỳ-kheo, do duyên tai và các âm thanh, nhĩ thức khởi lên …pe… ",
  "mn148:29-33.2": "Này các tỳ-kheo, do duyên mũi và các mùi, tỷ thức khởi lên …pe… ",
  "mn148:29-33.3": "Này các tỳ-kheo, do duyên lưỡi và các vị, thiệt thức khởi lên …pe… ",
  "mn148:29-33.4": "Này các tỳ-kheo, do duyên thân và các xúc chạm, thân thức khởi lên …pe… ",
  "mn148:29-33.5": "Này các tỳ-kheo, do duyên ý và các pháp, ý thức khởi lên; sự gặp gỡ của ba pháp này là sự tiếp chạm; do duyên tiếp chạm khởi lên cảm giác lạc, khổ, hay không khổ không lạc.",
  "mn148:29-33.6": "Khi được chạm bởi cảm giác lạc, người ấy hoan hỷ, ca ngợi và đắm chìm trong đó.",
  "mn148:29-33.7": "Khuynh hướng tham muốn ngủ ngầm trong người ấy.",
  "mn148:29-33.8": "Khi được chạm bởi cảm giác khổ, người ấy sầu muộn, than vãn, khóc lóc, đấm ngực, rơi vào mê mờ.",
  "mn148:29-33.9": "Khuynh hướng giận dữ ngủ ngầm trong người ấy.",
  "mn148:29-33.10": "Khi được chạm bởi cảm giác không khổ không lạc, người ấy không hiểu rõ như thật về sự sinh, sự diệt, vị ngọt, sự nguy hại và sự thoát ly của cảm giác đó.",
  "mn148:29-33.11": "Khuynh hướng mê mờ ngủ ngầm trong người ấy.",
  "mn148:29-33.12": "Này các tỳ-kheo, thật vậy, nếu không từ bỏ khuynh hướng tham muốn ngủ ngầm đối với cảm giác lạc, không tẩy trừ khuynh hướng giận dữ ngủ ngầm đối với cảm giác khổ, không nhổ tận gốc khuynh hướng mê mờ ngủ ngầm đối với cảm giác không khổ không lạc, không từ bỏ vô minh, không làm khởi sinh minh, mà có thể chấm dứt khổ đau ngay trong đời này—điều đó không thể xảy ra.",
  "mn148:34.1": "Này các tỳ-kheo, do duyên mắt và các hình sắc, nhãn thức khởi lên; sự gặp gỡ của ba pháp này là sự tiếp chạm; do duyên tiếp chạm khởi lên cảm giác lạc, khổ, hay không khổ không lạc.",
  "mn148:34.2": "Khi được chạm bởi cảm giác lạc, người ấy không hoan hỷ, không ca ngợi, không đắm chìm trong đó.",
  "mn148:34.3": "Khuynh hướng tham muốn không ngủ ngầm trong người ấy.",
  "mn148:34.4": "Khi được chạm bởi cảm giác khổ, người ấy không sầu muộn, không than vãn, không khóc lóc, không đấm ngực, không rơi vào mê mờ.",
  "mn148:34.5": "Khuynh hướng giận dữ không ngủ ngầm trong người ấy.",
  "mn148:34.6": "Khi được chạm bởi cảm giác không khổ không lạc, người ấy hiểu rõ như thật về sự sinh, sự diệt, vị ngọt, sự nguy hại và sự thoát ly của cảm giác đó.",
  "mn148:34.7": "Khuynh hướng mê mờ không ngủ ngầm trong người ấy.",
  "mn148:34.8": "Này các tỳ-kheo, thật vậy, nếu từ bỏ khuynh hướng tham muốn ngủ ngầm đối với cảm giác lạc, tẩy trừ khuynh hướng giận dữ ngủ ngầm đối với cảm giác khổ, nhổ tận gốc khuynh hướng mê mờ ngủ ngầm đối với cảm giác không khổ không lạc, từ bỏ vô minh, làm khởi sinh minh, mà có thể chấm dứt khổ đau ngay trong đời này—điều đó có thể xảy ra.",
  "mn148:35.1": "Này các tỳ-kheo, do duyên tai và các âm thanh, nhĩ thức khởi lên …pe….",
  "mn148:36.1": "Này các tỳ-kheo, do duyên mũi và các mùi, tỷ thức khởi lên …pe….",
  "mn148:37.1": "Này các tỳ-kheo, do duyên lưỡi và các vị, thiệt thức khởi lên …pe….",
  "mn148:38.1": "Này các tỳ-kheo, do duyên thân và các xúc chạm, thân thức khởi lên …pe….",
  "mn148:39.1": "“Này các tỳ-kheo, do duyên ý và các pháp, ý thức khởi lên; sự gặp gỡ của ba pháp này là sự tiếp chạm; do duyên tiếp chạm khởi lên cảm giác lạc, khổ, hay không khổ không lạc.",
  "mn148:39.2": "Khi được chạm bởi cảm giác lạc, người ấy không hoan hỷ, không ca ngợi, không đắm chìm trong đó.",
  "mn148:39.3": "Khuynh hướng tham muốn không ngủ ngầm trong người ấy.",
  "mn148:39.4": "Khi được chạm bởi cảm giác khổ, người ấy không sầu muộn, không than vãn, không khóc lóc, không đấm ngực, không rơi vào mê mờ.",
  "mn148:39.5": "Khuynh hướng giận dữ không ngủ ngầm trong người ấy.",
  "mn148:39.6": "Khi được chạm bởi cảm giác không khổ không lạc, người ấy hiểu rõ như thật về sự sinh, sự diệt, vị ngọt, sự nguy hại và sự thoát ly của cảm giác đó.",
  "mn148:39.7": "Khuynh hướng mê mờ không ngủ ngầm trong người ấy.",
  "mn148:39.8": "Này các tỳ-kheo, thật vậy, nếu từ bỏ khuynh hướng tham muốn ngủ ngầm đối với cảm giác lạc, tẩy trừ khuynh hướng giận dữ ngủ ngầm đối với cảm giác khổ, nhổ tận gốc khuynh hướng mê mờ ngủ ngầm đối với cảm giác không khổ không lạc, từ bỏ vô minh, làm khởi sinh minh, mà có thể chấm dứt khổ đau ngay trong đời này—điều đó có thể xảy ra.",
  "mn148:40.1": "Thấy như vậy, này các tỳ-kheo, vị thánh đệ tử có nghe biết nhàm chán đối với mắt, nhàm chán đối với các hình sắc, nhàm chán đối với nhãn thức, nhàm chán đối với nhãn xúc, nhàm chán đối với cảm thọ, nhàm chán đối với tham ái.",
  "mn148:41.1": "Nhàm chán đối với tai, nhàm chán đối với các âm thanh …pe… ",
  "mn148:41.2": "nhàm chán đối với mũi, nhàm chán đối với các mùi … ",
  "mn148:41.3": "nhàm chán đối với lưỡi, nhàm chán đối với các vị … ",
  "mn148:41.4": "nhàm chán đối với thân, nhàm chán đối với các xúc chạm … ",
  "mn148:41.5": "nhàm chán đối với ý, nhàm chán đối với các pháp, nhàm chán đối với ý thức, nhàm chán đối với ý tiếp chạm, nhàm chán đối với cảm thọ, nhàm chán đối với tham ái.",
  "mn148:41.6": "Do nhàm chán, vị ấy rời bỏ tham muốn; do rời bỏ tham muốn, vị ấy giải thoát. Trong sự giải thoát, khởi lên hiểu biết rằng: ‘Đã giải thoát’.",
  "mn148:41.7": "Vị ấy hiểu rõ: ‘Sự sinh đã tận, phạm hạnh đã thành, việc cần làm đã làm xong, không còn trở lại trạng thái này nữa’.”",
  "mn148:41.8": "Thế Tôn đã thuyết như vậy.",
  "mn148:41.9": "Các tỳ-kheo ấy vui mừng, hoan hỷ trước lời dạy của Thế Tôn.",
  "mn148:41.10": "Trong khi lời giảng giải này đang được thuyết, tâm của khoảng sáu mươi tỳ-kheo đã được giải thoát khỏi các lậu hoặc nhờ không chấp thủ.",
  "mn148:41.11": "Kinh Sáu Nhóm Sáu kết thúc, là kinh thứ sáu."
}
window.BILARA["mn148"]["vi"]["mn148:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
