window.BILARA = window.BILARA || {};
window.BILARA["mn22"] = window.BILARA["mn22"] || {};
window.BILARA["mn22"]["vi"] = {
  "mn22:0.1": "Trung Bộ Kinh 22",
  "mn22:0.2": "Kinh Ví Dụ Con Rắn Nước",
  "mn22:1.1": "Tôi nghe như vầy—",
  "mn22:1.2": "Một thời, Đức Thế Tôn ở Xá Vệ, tại Kỳ Viên, trong vườn của ông Cấp Cô Độc.",
  "mn22:2.1": "Lúc bấy giờ, một Tỳ Kheo tên là Arittha, trước kia là người bắt chim kên kên, khởi lên một cách thấy sai xấu ác như vầy:",
  "mn22:2.2": "“Tôi hiểu lời Đức Thế Tôn dạy như thế này: những điều gây chướng ngại mà Đức Thế Tôn nói đến, nếu làm theo thì không đủ để thành chướng ngại.”",
  "mn22:2.3": "Nhiều Tỳ Kheo nghe được rằng:",
  "mn22:2.4": "“Nghe nói Tỳ Kheo Arittha, trước kia là người bắt chim kên kên, đã khởi lên một cách thấy sai xấu ác như vầy:",
  "mn22:2.5": "‘Tôi hiểu lời Đức Thế Tôn dạy như thế này: những điều gây chướng ngại mà Đức Thế Tôn nói đến, nếu làm theo thì không đủ để thành chướng ngại.’”",
  "mn22:3.1": "Rồi các Tỳ Kheo ấy đi đến chỗ Tỳ Kheo Arittha, người trước kia là người bắt chim kên kên. Đến nơi, họ nói với Tỳ Kheo Arittha như vầy:",
  "mn22:3.2": "“Này hiền giả Arittha, có thật là thầy đã khởi lên một cách thấy sai xấu ác như vầy chăng:",
  "mn22:3.3": "‘Tôi hiểu lời Đức Thế Tôn dạy như thế này: những điều gây chướng ngại mà Đức Thế Tôn nói đến, nếu làm theo thì không đủ để thành chướng ngại’?”",
  "mn22:3.4": "“Đúng vậy, này các hiền giả, tôi hiểu lời Đức Thế Tôn dạy như thế này: những điều gây chướng ngại mà Đức Thế Tôn nói đến, nếu làm theo thì không đủ để thành chướng ngại.”",
  "mn22:3.5": "Khi ấy, các Tỳ Kheo ấy muốn kéo Tỳ Kheo Arittha, người trước kia là người bắt chim kên kên, ra khỏi cách thấy sai xấu ác ấy, nên đã gạn hỏi, khuyên can và nói rõ với vị ấy:",
  "mn22:3.6": "“Này hiền giả Arittha, chớ nói như vậy, chớ gán cho Đức Thế Tôn điều ấy; gán sai cho Đức Thế Tôn là không nên, vì Đức Thế Tôn không nói như vậy.",
  "mn22:3.7": "Này hiền giả Arittha, bằng nhiều cách, Đức Thế Tôn đã nói rằng những điều ấy là gây chướng ngại, và nếu làm theo thì đủ để thành chướng ngại.",
  "mn22:3.8": "Đức Thế Tôn đã nói các thú vui giác quan là ít vị ngọt, nhiều khổ đau, nhiều nhọc nhằn, và mối hại trong đó còn nhiều hơn nữa.",
  "mn22:3.9": "Đức Thế Tôn đã nói các thú vui giác quan giống như bộ xương khô…",
  "mn22:3.10": "Đức Thế Tôn đã nói các thú vui giác quan giống như miếng thịt…",
  "mn22:3.11": "Đức Thế Tôn đã nói các thú vui giác quan giống như bó đuốc cỏ…",
  "mn22:3.12": "Đức Thế Tôn đã nói các thú vui giác quan giống như hố than hồng…",
  "mn22:3.13": "Đức Thế Tôn đã nói các thú vui giác quan giống như giấc mơ…",
  "mn22:3.14": "Đức Thế Tôn đã nói các thú vui giác quan giống như đồ đi mượn…",
  "mn22:3.15": "Đức Thế Tôn đã nói các thú vui giác quan giống như trái trên cây…",
  "mn22:3.16": "Đức Thế Tôn đã nói các thú vui giác quan giống như dao và thớt chém…",
  "mn22:3.17": "Đức Thế Tôn đã nói các thú vui giác quan giống như giáo mác đâm vào…",
  "mn22:3.18": "Đức Thế Tôn đã nói các thú vui giác quan giống như đầu rắn, nhiều khổ đau, nhiều nhọc nhằn, và mối hại trong đó còn nhiều hơn nữa.”",
  "mn22:3.19": "Dù được các Tỳ Kheo ấy gạn hỏi, khuyên can và nói rõ như vậy, Tỳ Kheo Arittha, người trước kia là người bắt chim kên kên, vẫn cố chấp, bám chặt, ôm giữ đúng cách thấy sai xấu ác ấy mà nói rằng:",
  "mn22:3.20": "“Đúng vậy, này các hiền giả, tôi hiểu lời Đức Thế Tôn dạy như thế này: những điều gây chướng ngại mà Đức Thế Tôn nói đến, nếu làm theo thì không đủ để thành chướng ngại.”",
  "mn22:3.21": "Khi các Tỳ Kheo ấy không thể kéo Tỳ Kheo Arittha, người trước kia là người bắt chim kên kên, ra khỏi cách thấy sai xấu ác ấy, họ đi đến chỗ Đức Thế Tôn. Đến nơi, họ đảnh lễ Đức Thế Tôn rồi ngồi xuống một bên. Khi đã ngồi xuống một bên, các Tỳ Kheo ấy thưa với Đức Thế Tôn như vầy:",
  "mn22:3.22": "“Bạch Đức Thế Tôn, Tỳ Kheo Arittha, trước kia là người bắt kên kên, đã khởi lên một cách thấy xấu ác như vầy:",
  "mn22:3.23": "‘Tôi hiểu lời Đức Thế Tôn dạy như sau: những điều gây ngăn trở mà Đức Thế Tôn nói đến, nếu làm theo thì không đủ để gây ngăn trở.’",
  "mn22:3.24": "Bạch Đức Thế Tôn, chúng con đã nghe rằng:",
  "mn22:3.25": "‘Tỳ Kheo Arittha, trước kia là người bắt kên kên, đã khởi lên một cách thấy xấu ác như vầy—",
  "mn22:3.26": "tôi hiểu lời Đức Thế Tôn dạy như sau: những điều gây ngăn trở mà Đức Thế Tôn nói đến, nếu làm theo thì không đủ để gây ngăn trở.’",
  "mn22:3.27": "Rồi bạch Đức Thế Tôn, chúng con đi đến chỗ Tỳ Kheo Arittha, trước kia là người bắt kên kên; đến nơi, chúng con nói với Tỳ Kheo Arittha, trước kia là người bắt kên kên, như vầy:",
  "mn22:3.28": "‘Có thật chăng, hiền giả Arittha, thầy đã khởi lên một cách thấy xấu ác như vầy—",
  "mn22:3.29": "tôi hiểu lời Đức Thế Tôn dạy như sau: những điều gây ngăn trở mà Đức Thế Tôn nói đến, nếu làm theo thì không đủ để gây ngăn trở?’",
  "mn22:3.30": "Khi được nói vậy, bạch Đức Thế Tôn, Tỳ Kheo Arittha, trước kia là người bắt kên kên, nói với chúng con như vầy:",
  "mn22:3.31": "‘Đúng vậy, các hiền giả, tôi hiểu lời Đức Thế Tôn dạy như sau: những điều gây ngăn trở mà Đức Thế Tôn nói đến, nếu làm theo thì không đủ để gây ngăn trở.’",
  "mn22:3.32": "Rồi bạch Đức Thế Tôn, vì muốn kéo Tỳ Kheo Arittha, trước kia là người bắt kên kên, ra khỏi cách thấy xấu ác ấy, chúng con đã hỏi đi hỏi lại, gặng hỏi, và khuyên nhủ ông ấy:",
  "mn22:3.33": "‘Đừng nói như vậy, hiền giả Arittha, đừng gán lời ấy cho Đức Thế Tôn; gán sai lời cho Đức Thế Tôn là không nên, vì Đức Thế Tôn không nói như vậy.",
  "mn22:3.34": "Này hiền giả Arittha, bằng nhiều cách, Đức Thế Tôn đã nói rõ rằng những điều gây ngăn trở là thật sự gây ngăn trở, và nếu làm theo thì đủ để gây ngăn trở.",
  "mn22:3.35": "Đức Thế Tôn đã nói rằng các thú vui giác quan đem lại ít vị ngọt, nhưng nhiều khổ đau, nhiều nhọc nhằn; mặt hại trong đó lại còn nhiều hơn.",
  "mn22:3.36": "Đức Thế Tôn đã nói rằng các thú vui giác quan giống như bộ xương …",
  "mn22:3.37": "Đức Thế Tôn đã nói rằng các thú vui giác quan giống như đầu rắn, đem lại nhiều khổ đau, nhiều nhọc nhằn; mặt hại trong đó lại còn nhiều hơn.’",
  "mn22:3.38": "Dù vậy, bạch Đức Thế Tôn, khi bị chúng con hỏi đi hỏi lại, gặng hỏi, và khuyên nhủ, Tỳ Kheo Arittha, trước kia là người bắt kên kên, vẫn bám chặt lấy đúng cách thấy xấu ác ấy, nắm giữ cứng chắc và nói rằng:",
  "mn22:3.39": "‘Đúng vậy, các hiền giả, tôi hiểu lời Đức Thế Tôn dạy như sau: những điều gây ngăn trở mà Đức Thế Tôn nói đến, nếu làm theo thì không đủ để gây ngăn trở.’",
  "mn22:4.1": "Bạch Đức Thế Tôn, vì chúng con không thể kéo Tỳ Kheo Arittha, trước kia là người bắt kên kên, ra khỏi cách thấy xấu ác ấy, nên chúng con trình việc này lên Đức Thế Tôn.”",
  "mn22:5.1": "Rồi Đức Thế Tôn gọi một Tỳ Kheo khác:",
  "mn22:5.2": "“Này Tỳ Kheo, hãy đi, nhân danh Ta gọi Tỳ Kheo Arittha, trước kia là người bắt kên kên, rằng:",
  "mn22:5.3": "‘Bậc Thầy gọi hiền giả Arittha.’”",
  "mn22:5.4": "“Dạ, bạch Đức Thế Tôn,” vị Tỳ Kheo ấy đáp lời Đức Thế Tôn, rồi đi đến chỗ Tỳ Kheo Arittha, trước kia là người bắt kên kên; đến nơi, vị ấy nói với Tỳ Kheo Arittha, trước kia là người bắt kên kên, như vầy:",
  "mn22:5.5": "“Bậc Thầy gọi hiền giả Arittha.”",
  "mn22:5.6": "“Vâng, hiền giả,” Tỳ Kheo Arittha, trước kia là người bắt kên kên, đáp lời vị Tỳ Kheo ấy, rồi đi đến chỗ Đức Thế Tôn; đến nơi, ông đảnh lễ Đức Thế Tôn rồi ngồi xuống một bên. Khi Tỳ Kheo Arittha, trước kia là người bắt kên kên, ngồi xuống một bên, Đức Thế Tôn nói với ông ấy như vầy:",
  "mn22:5.7": "“Có thật chăng, Arittha, thầy đã khởi lên một cách thấy xấu ác như vầy:",
  "mn22:5.8": "‘Tôi hiểu lời Đức Thế Tôn dạy như sau: những điều gây ngăn trở mà Đức Thế Tôn nói đến, nếu làm theo thì không đủ để gây ngăn trở’?”",
  "mn22:5.9": "“Đúng vậy, bạch Đức Thế Tôn, tôi hiểu lời Đức Thế Tôn dạy như sau: ‘những điều gây ngăn trở mà Đức Thế Tôn nói đến, nếu làm theo thì không đủ để gây ngăn trở.’”",
  "mn22:6.1": "“Này người kia ngu muội, ai mà thầy lại hiểu rằng Ta đã dạy như vậy?",
  "mn22:6.2": "Này người kia ngu muội, chẳng phải Ta đã nhiều lần nói rõ rằng những điều gây ngăn trở là thật sự gây ngăn trở sao? Và nếu làm theo thì đủ để gây ngăn trở.”",
  "mn22:6.3": "Ta đã nói rằng các thú vui giác quan có rất ít vị ngọt, nhưng nhiều khổ đau, nhiều nhọc nhằn, và điều nguy hại trong đó còn nhiều hơn nữa.",
  "mn22:6.4": "Ta đã nói rằng các thú vui giác quan giống như bộ xương khô…",
  "mn22:6.5": "Ta đã nói rằng các thú vui giác quan giống như miếng thịt…",
  "mn22:6.6": "Ta đã nói rằng các thú vui giác quan giống như bó đuốc cỏ khô…",
  "mn22:6.7": "Ta đã nói rằng các thú vui giác quan giống như hố than hồng…",
  "mn22:6.8": "Ta đã nói rằng các thú vui giác quan giống như giấc mơ…",
  "mn22:6.9": "Ta đã nói rằng các thú vui giác quan giống như đồ đi xin được dùng tạm…",
  "mn22:6.10": "Ta đã nói rằng các thú vui giác quan giống như trái trên cây…",
  "mn22:6.11": "Ta đã nói rằng các thú vui giác quan giống như dao và thớt chém…",
  "mn22:6.12": "Ta đã nói rằng các thú vui giác quan giống như giáo mác đâm vào người…",
  "mn22:6.13": "Ta đã nói rằng các thú vui giác quan giống như đầu rắn, có rất nhiều khổ đau, nhiều nhọc nhằn, và điều nguy hại trong đó còn nhiều hơn nữa.",
  "mn22:6.14": "Thế mà này người ngu kia, do tự nắm sai, ngươi lại vu cho Ta, tự đào hố cho mình, và còn gây ra nhiều điều xấu.",
  "mn22:6.15": "Điều ấy sẽ đưa ngươi đến bất lợi và khổ đau trong thời gian dài.”",
  "mn22:7.1": "Rồi Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn22:7.2": "“Này các Tỳ Kheo, các ông nghĩ sao,",
  "mn22:7.3": "Tỳ Kheo Ariṭṭha này, trước kia là người bắt kền kền, có hiểu được dù chỉ chút ít giáo pháp và nếp sống này không?”",
  "mn22:7.4": "“Bạch Thế Tôn, làm sao có thể như vậy được;",
  "mn22:7.5": "thưa Thế Tôn, không phải vậy.”",
  "mn22:7.6": "Khi được nói vậy, Tỳ Kheo Ariṭṭha, người trước kia bắt kền kền, ngồi im, bối rối, vai sụp xuống, cúi mặt, buồn bã, không đáp được.",
  "mn22:7.7": "Rồi Đức Thế Tôn, biết Tỳ Kheo Ariṭṭha, người trước kia bắt kền kền, đang ngồi im, bối rối, vai sụp xuống, cúi mặt, buồn bã, không đáp được, liền nói với Tỳ Kheo Ariṭṭha, người trước kia bắt kền kền:",
  "mn22:7.8": "“Này người ngu kia, ngươi sẽ bị người ta nhận ra qua cái thấy sai xấu ác của chính mình.",
  "mn22:7.9": "Ở đây Ta sẽ hỏi các Tỳ Kheo.”",
  "mn22:8.1": "Rồi Đức Thế Tôn gọi các Tỳ Kheo:",
  "mn22:8.2": "“Này các Tỳ Kheo, các ông có hiểu lời Ta dạy theo cách như Tỳ Kheo Ariṭṭha, người trước kia bắt kền kền, do tự nắm sai mà vu cho Ta, tự đào hố cho mình, và còn gây ra nhiều điều xấu không?”",
  "mn22:8.3": "“Thưa không, bạch Thế Tôn.",
  "mn22:8.4": "Vì, bạch Thế Tôn, Đức Thế Tôn đã nhiều lần nói với chúng con rằng những điều gây ngăn trở là những điều gây ngăn trở;",
  "mn22:8.5": "và nếu cứ theo đuổi chúng thì đủ để thành ra ngăn trở.",
  "mn22:8.6": "Đức Thế Tôn đã nói rằng các thú vui giác quan có rất ít vị ngọt, nhưng nhiều khổ đau, nhiều nhọc nhằn, và điều nguy hại trong đó còn nhiều hơn nữa.",
  "mn22:8.7": "Đức Thế Tôn đã nói rằng các thú vui giác quan giống như bộ xương khô…",
  "mn22:8.8": "Đức Thế Tôn đã nói rằng các thú vui giác quan giống như đầu rắn, có rất nhiều khổ đau, nhiều nhọc nhằn, và điều nguy hại trong đó còn nhiều hơn nữa.”",
  "mn22:8.9": "“Lành thay, lành thay, này các Tỳ Kheo, thật tốt khi các thầy hiểu lời dạy này của ta như vậy.",
  "mn22:8.10": "Này các Tỳ Kheo, bằng nhiều cách ta đã nói về những điều gây ngăn trở, và khi chạy theo chúng thì đủ để đưa đến ngăn trở.",
  "mn22:8.11": "Ta đã nói rằng các thú vui giác quan chỉ có ít vị ngọt, nhưng nhiều khổ đau, nhiều nhọc nhằn, và mối hại trong đó còn nhiều hơn nữa.",
  "mn22:8.12": "Ta đã nói rằng các thú vui giác quan giống như bộ xương khô …",
  "mn22:8.13": "ta đã nói rằng các thú vui giác quan giống như đầu rắn, nhiều khổ đau, nhiều nhọc nhằn, và mối hại trong đó còn nhiều hơn nữa.",
  "mn22:8.14": "Thế mà Tỳ Kheo Ariṭṭha này, trước kia là người bắt kền kền, do nắm sai bằng chính mình, lại còn gán lời cho ta, tự làm hại mình, và chất chứa nhiều điều xấu.",
  "mn22:8.15": "Điều ấy sẽ đưa người ngu ấy đến bất lợi và khổ đau trong thời gian dài.",
  "mn22:9.1": "Này các Tỳ Kheo, chuyện một người vẫn chạy theo các thú vui giác quan mà lại tách khỏi các thú vui giác quan, tách khỏi cái nhìn về thú vui giác quan, tách khỏi những nghĩ ngợi về thú vui giác quan, thì không thể có.",
  "mn22:10.1": "Này các Tỳ Kheo, ở đây có một số người ngu học thuộc lời dạy—",
  "mn22:10.2": "bài giảng xuôi, bài giảng nửa xuôi nửa kệ, phần giải nói, bài kệ, lời cảm hứng thốt ra, lời nói bắt đầu bằng “như vầy đã được nói”, chuyện đời trước, chuyện lạ hiếm có, và phần hỏi đáp.",
  "mn22:10.3": "Nhưng sau khi học thuộc lời dạy ấy, họ không dùng sự hiểu rõ để xem xét ý nghĩa của những lời dạy đó.",
  "mn22:10.4": "Vì không xem xét ý nghĩa bằng sự hiểu rõ, nên những lời dạy ấy không được họ suy ngẫm cho thấu.",
  "mn22:10.5": "Họ học lời dạy chỉ vì muốn bắt bẻ người khác và vì muốn thoát khỏi lời chê trách trong tranh cãi.",
  "mn22:10.6": "Và mục đích vì đó họ học lời dạy, thì họ không đạt được ý nghĩa ấy.",
  "mn22:10.7": "Những lời dạy bị nắm sai như vậy sẽ đưa họ đến bất lợi và khổ đau trong thời gian dài.",
  "mn22:10.8": "Vì sao vậy?",
  "mn22:10.9": "Vì, này các Tỳ Kheo, là do nắm sai lời dạy.",
  "mn22:10.10": "Ví như, này các Tỳ Kheo, có người cần bắt rắn, đi tìm rắn, lang thang kiếm rắn.",
  "mn22:10.11": "Người ấy thấy một con rắn lớn.",
  "mn22:10.12": "Người ấy nắm nó ở thân hoặc ở đuôi.",
  "mn22:10.13": "Con rắn ấy liền quay lại cắn vào tay, hoặc cánh tay, hoặc một chỗ nào khác trên thân người ấy.",
  "mn22:10.14": "Do đó, người ấy có thể chết, hoặc chịu đau đớn gần chết.",
  "mn22:10.15": "Vì sao vậy?",
  "mn22:10.16": "Vì, này các Tỳ Kheo, là do nắm rắn sai cách.",
  "mn22:10.17": "Cũng vậy, này các Tỳ Kheo, ở đây có một số người ngu học thuộc lời dạy—",
  "mn22:10.18": "bài giảng xuôi, bài giảng nửa xuôi nửa kệ, phần giải nói, bài kệ, lời cảm hứng thốt ra, lời nói bắt đầu bằng “như vầy đã được nói”, chuyện đời trước, chuyện lạ hiếm có, và phần hỏi đáp.",
  "mn22:10.19": "Nhưng sau khi học thuộc lời dạy ấy, họ không dùng sự hiểu rõ để xem xét ý nghĩa của những lời dạy đó.",
  "mn22:10.20": "Vì không xem xét ý nghĩa bằng sự hiểu rõ, nên những lời dạy ấy không được họ suy ngẫm cho thấu.",
  "mn22:10.21": "Họ học lời dạy chỉ vì muốn bắt bẻ người khác và vì muốn thoát khỏi lời chê trách trong tranh cãi.",
  "mn22:10.22": "Và mục đích vì đó họ học lời dạy, thì họ không đạt được ý nghĩa ấy.",
  "mn22:10.23": "Những lời dạy ấy, khi nắm sai, sẽ lâu dài đưa đến điều không lợi ích và khổ đau.",
  "mn22:10.24": "Vì sao vậy?",
  "mn22:10.25": "Này các Tỳ Kheo, vì những lời dạy đã bị nắm sai.",
  "mn22:11.1": "Nhưng ở đây, này các Tỳ Kheo, có một số người con trai trong gia đình tốt học thuộc lời dạy—",
  "mn22:11.2": "bài kinh xuôi, bài kinh nửa xuôi nửa kệ, phần giảng giải, bài kệ, lời nói bật ra, lời dạy mở đầu bằng “đây là điều đã được nói”, chuyện đời trước, chuyện lạ hiếm có, và phần hỏi đáp.",
  "mn22:11.3": "Sau khi học thuộc lời dạy ấy, họ dùng sự hiểu rõ để xem xét ý nghĩa của những lời dạy đó.",
  "mn22:11.4": "Khi ý nghĩa của những lời dạy ấy được xem xét bằng sự hiểu rõ, chúng chịu được sự suy ngẫm kỹ.",
  "mn22:11.5": "Họ học lời dạy không phải để bắt bẻ người khác, cũng không phải để hơn thua trong lời nói.",
  "mn22:11.6": "Và họ cảm nhận được điều lợi ích mà vì đó họ học lời dạy.",
  "mn22:11.7": "Những lời dạy ấy, khi được nắm đúng, sẽ lâu dài đưa đến điều lợi ích và sự dễ chịu.",
  "mn22:11.8": "Vì sao vậy?",
  "mn22:11.9": "Này các Tỳ Kheo, vì những lời dạy đã được nắm đúng.",
  "mn22:11.10": "Ví như, này các Tỳ Kheo, có người cần bắt rắn, đi tìm rắn, lang thang để kiếm rắn.",
  "mn22:11.11": "Người ấy thấy một con rắn lớn.",
  "mn22:11.12": "Người ấy dùng một cây gậy chẻ đầu, khéo ghìm nó xuống rồi bắt lấy nó.",
  "mn22:11.13": "Sau khi dùng cây gậy chẻ đầu khéo ghìm nó xuống, người ấy nắm đúng ở cổ nó.",
  "mn22:11.14": "Dù con rắn ấy có quấn quanh tay, cánh tay, hay phần nào khác trên thân người ấy bằng các vòng cuộn của nó, thì người ấy cũng không vì vậy mà đi đến chết hay khổ đau gần chết.",
  "mn22:11.15": "Vì sao vậy?",
  "mn22:11.16": "Này các Tỳ Kheo, vì con rắn đã được nắm đúng.",
  "mn22:11.17": "Cũng vậy, này các Tỳ Kheo, ở đây có một số người con trai trong gia đình tốt học thuộc lời dạy—",
  "mn22:11.18": "bài kinh xuôi, bài kinh nửa xuôi nửa kệ, phần giảng giải, bài kệ, lời nói bật ra, lời dạy mở đầu bằng “đây là điều đã được nói”, chuyện đời trước, chuyện lạ hiếm có, và phần hỏi đáp.",
  "mn22:11.19": "Sau khi học thuộc lời dạy ấy, họ dùng sự hiểu rõ để xem xét ý nghĩa của những lời dạy đó.",
  "mn22:11.20": "Khi ý nghĩa của những lời dạy ấy được xem xét bằng sự hiểu rõ, chúng chịu được sự suy ngẫm kỹ.",
  "mn22:11.21": "Họ học lời dạy không phải để bắt bẻ người khác, cũng không phải để hơn thua trong lời nói.",
  "mn22:11.22": "Và họ cảm nhận được điều lợi ích mà vì đó họ học lời dạy.",
  "mn22:11.23": "Những lời dạy ấy, khi được nắm đúng, sẽ lâu dài đưa đến điều lợi ích, điều tốt lành, và sự dễ chịu.",
  "mn22:11.24": "Vì sao vậy?",
  "mn22:11.25": "Này các Tỳ Kheo, vì những lời dạy đã được nắm đúng.",
  "mn22:12.1": "Vậy nên, này các Tỳ Kheo, nếu các ông hiểu được ý nghĩa trong lời Ta nói, thì hãy ghi nhớ đúng như vậy.",
  "mn22:12.2": "Còn nếu các ông không hiểu được ý nghĩa trong lời Ta nói, thì hãy hỏi lại Ta về chỗ ấy, hoặc hỏi các Tỳ Kheo khéo hiểu khác.",
  "mn22:13.1": "Này các Tỳ Kheo, Ta sẽ giảng cho các ông lời dạy ví như chiếc bè, để vượt qua, không phải để nắm giữ.",
  "mn22:13.2": "Hãy lắng nghe, hãy để tâm cho kỹ, Ta sẽ nói.",
  "mn22:13.3": "“Dạ vâng, bạch Đức Thế Tôn”, các Tỳ Kheo đáp lời Đức Thế Tôn.",
  "mn22:13.4": "Đức Thế Tôn nói như sau:",
  "mn22:13.5": "“Ví như, này các Tỳ Kheo, có một người đang đi đường xa.",
  "mn22:13.6": "Người ấy thấy một vùng nước mênh mông; bờ bên này đầy hiểm nguy, đáng sợ; bờ bên kia yên ổn, không đáng sợ.",
  "mn22:13.7": "Nhưng không có thuyền để qua, cũng không có cầu bắc sang bờ bên kia.",
  "mn22:13.8": "Người ấy nghĩ rằng:",
  "mn22:13.9": "‘Vùng nước lớn này thật mênh mông, bờ bên này đầy hiểm nguy, đáng sợ; bờ bên kia yên ổn, không đáng sợ.",
  "mn22:13.10": "Nhưng không có thuyền để qua, cũng không có cầu bắc sang bờ bên kia.",
  "mn22:13.11": "Hay là ta gom cỏ, cây, cành và lá lại, kết thành một chiếc bè; rồi nương vào chiếc bè ấy, dùng tay và chân ra sức, để qua đến bờ bên kia được an lành.’",
  "mn22:13.12": "Rồi, này các Tỳ Kheo, người ấy gom cỏ, cây, cành và lá lại, kết thành một chiếc bè; rồi nương vào chiếc bè ấy, dùng tay và chân ra sức, và qua đến bờ bên kia được an lành.",
  "mn22:13.13": "Khi đã qua được và đã đến bờ bên kia, người ấy nghĩ rằng:",
  "mn22:13.14": "‘Chiếc bè này đã giúp ta rất nhiều.",
  "mn22:13.15": "Nhờ nương vào chiếc bè này, dùng tay và chân ra sức, ta đã qua đến bờ bên kia được an lành.",
  "mn22:13.16": "Hay là ta đội chiếc bè này lên đầu, hoặc vác lên vai, rồi đi đâu tùy ý.’",
  "mn22:13.17": "Các ông nghĩ sao, này các Tỳ Kheo,",
  "mn22:13.18": "người ấy làm như vậy có phải là dùng chiếc bè đúng cách không?”",
  "mn22:13.19": "“Thưa không, bạch Đức Thế Tôn.”",
  "mn22:13.20": "“Vậy, này các Tỳ Kheo, người ấy phải làm thế nào mới là dùng chiếc bè đúng cách?",
  "mn22:13.21": "Ở đây, này các Tỳ Kheo, khi đã qua được và đã đến bờ bên kia, người ấy nghĩ rằng:",
  "mn22:13.22": "‘Chiếc bè này đã giúp ta rất nhiều.",
  "mn22:13.23": "Nhờ nương vào chiếc bè này, dùng tay và chân ra sức, ta đã qua đến bờ bên kia được an lành.",
  "mn22:13.24": "Hay là ta kéo chiếc bè này lên bờ, hoặc thả lại xuống nước, rồi đi đâu tùy ý.’",
  "mn22:13.25": "Làm như vậy, này các Tỳ Kheo, người ấy mới là dùng chiếc bè đúng cách.",
  "mn22:13.26": "Cũng vậy, này các Tỳ Kheo, lời dạy ví như chiếc bè đã được Ta giảng ra là để vượt qua, không phải để nắm giữ.",
  "mn22:14.1": "Này các Tỳ Kheo, khi đã hiểu lời dạy ví như chiếc bè, thì ngay cả những điều dạy cũng phải buông bỏ, huống nữa là những điều không đúng.",
  "mn22:15.1": "Này các Tỳ Kheo, có sáu chỗ để bám vào cái thấy.",
  "mn22:15.2": "Sáu chỗ ấy là gì?",
  "mn22:15.3": "Ở đây, này các Tỳ Kheo, một người thường, ít nghe học, không gặp bậc cao quý, không biết lời dạy của bậc cao quý, không được rèn luyện trong lời dạy của bậc cao quý; không gặp người tốt, không biết nếp sống của người tốt, không được rèn luyện trong nếp sống của người tốt,",
  "mn22:15.4": "Người ấy nhìn thân này như vầy: ‘Cái này là của tôi, tôi là cái này, cái này là mình tôi.’",
  "mn22:15.5": "Người ấy nhìn cảm giác như vầy: ‘Cái này là của tôi, tôi là cái này, cái này là mình tôi.’",
  "mn22:15.6": "Người ấy nhìn sự ghi nhận như vầy: ‘Cái này là của tôi, tôi là cái này, cái này là mình tôi.’",
  "mn22:15.7": "Người ấy nhìn các hoạt động của tâm như vầy: ‘Cái này là của tôi, tôi là cái này, cái này là mình tôi.’",
  "mn22:15.8": "Dù là cái gì được thấy, được nghe, được cảm nhận, được biết, được đạt tới, được tìm cầu, được tâm suy xét, người ấy cũng nhìn cái đó như vầy: ‘Cái này là của tôi, tôi là cái này, cái này là mình tôi.’",
  "mn22:15.9": "Dù là chỗ bám của cái thấy, như là:",
  "mn22:15.10": "‘Thế giới ấy là mình, sau khi chết tôi sẽ là như vậy, còn mãi, bền mãi, luôn luôn như thế, không đổi khác, và sẽ đứng y như vậy suốt đời đời’—",
  "mn22:15.11": "người ấy cũng nhìn cả cái đó như vầy: ‘Cái này là của tôi, tôi là cái này, cái này là mình tôi.’",
  "mn22:16.1": "Này các Tỳ Kheo, người đệ tử nghe nhiều, thuộc hàng bậc thánh, đã gặp người cao quý, khéo rõ lời dạy của người cao quý, được rèn luyện kỹ trong lời dạy của người cao quý; đã gặp người tốt, khéo rõ nếp sống của người tốt, được rèn luyện kỹ trong nếp sống của người tốt,",
  "mn22:16.2": "nhìn thân như vầy: ‘Cái này không phải của tôi, tôi không phải là cái này, cái này không phải là mình tôi.’",
  "mn22:16.3": "nhìn cảm giác như vầy: ‘Cái này không phải của tôi, tôi không phải là cái này, cái này không phải là mình tôi.’",
  "mn22:16.4": "nhìn sự ghi nhận như vầy: ‘Cái này không phải của tôi, tôi không phải là cái này, cái này không phải là mình tôi.’",
  "mn22:16.5": "nhìn các hoạt động của tâm như vầy: ‘Cái này không phải của tôi, tôi không phải là cái này, cái này không phải là mình tôi.’",
  "mn22:16.6": "Dù là cái gì được thấy, được nghe, được cảm nhận, được biết, được đạt tới, được tìm cầu, được tâm suy xét, người ấy cũng nhìn cái đó như vầy: ‘Cái này không phải của tôi, tôi không phải là cái này, cái này không phải là mình tôi.’",
  "mn22:16.7": "Dù là chỗ bám của cái thấy, như là:",
  "mn22:16.8": "‘Thế giới ấy là mình, sau khi chết tôi sẽ là như vậy, còn mãi, bền mãi, luôn luôn như thế, không đổi khác, và sẽ đứng y như vậy suốt đời đời’—",
  "mn22:16.9": "người ấy cũng nhìn cả cái đó như vầy: ‘Cái này không phải của tôi, tôi không phải là cái này, cái này không phải là mình tôi.’",
  "mn22:17.1": "Người thấy như vậy thì khi không có gì cũng không run sợ.",
  "mn22:18.1": "Khi được nói như vậy, một vị Tỳ Kheo thưa với Đức Thế Tôn rằng:",
  "mn22:18.2": "“Bạch Thế Tôn, có thể nào vì bên ngoài không có mà sinh run sợ không?”",
  "mn22:18.3": "“Có thể, này Tỳ Kheo,” Đức Thế Tôn nói.",
  "mn22:18.4": "“Ở đây, này Tỳ Kheo, có người nghĩ như vầy:",
  "mn22:18.5": "‘Ước gì cái ấy là của tôi, nhưng cái ấy nay không có với tôi;",
  "mn22:18.6": "ước gì tôi có được cái ấy, nhưng tôi lại không được.’",
  "mn22:18.7": "Người ấy buồn rầu, mòn mỏi, than khóc, đấm ngực mà khóc, rồi rơi vào mê loạn.",
  "mn22:18.8": "Này Tỳ Kheo, như vậy là vì bên ngoài không có mà sinh run sợ.”",
  "mn22:19.1": "“Nhưng bạch Thế Tôn, có thể nào vì bên ngoài không có mà không sinh run sợ không?”",
  "mn22:19.2": "“Có thể, này Tỳ Kheo,” Đức Thế Tôn nói.",
  "mn22:19.3": "“Ở đây, này Tỳ Kheo, có người không nghĩ như vầy:",
  "mn22:19.4": "‘Ước gì cái ấy là của tôi, nhưng cái ấy nay không có với tôi;’",
  "mn22:19.5": "Mong sao tôi có được cái ấy, nhưng tôi không được cái ấy.’",
  "mn22:19.6": "Người ấy không buồn, không héo mòn, không than khóc, không đấm ngực khóc lóc, không rối loạn tâm trí.",
  "mn22:19.7": "Này Tỳ Kheo, như vậy là khi không có cái ở bên ngoài thì không bấn loạn.",
  "mn22:20.1": "“Bạch Thế Tôn, có khi nào vì không có cái ở bên trong mà bấn loạn không?”",
  "mn22:20.2": "“Có, này các Tỳ Kheo,” Đức Thế Tôn nói.",
  "mn22:20.3": "“Ở đây, này Tỳ Kheo, có người có cách thấy như vầy:",
  "mn22:20.4": "‘Thế giới ấy là ta, ta ấy; sau khi chết, tôi sẽ còn mãi, bền chắc, đời đời, không đổi khác, và sẽ đứng y như vậy mãi mãi.’",
  "mn22:20.5": "Người ấy nghe Đức Như Lai hoặc đệ tử của Đức Như Lai nói lời dạy nhằm nhổ sạch mọi chỗ bám của cách thấy, mọi chỗ dựng lập của cách thấy, mọi thứ bị che phủ, dính chặt và ngấm ngầm nằm sâu; nhằm làm lắng yên mọi tạo tác; nhằm buông hết mọi chỗ nắm giữ; nhằm làm tắt hẳn lòng ham muốn; nhằm phai nhạt dính mắc; nhằm chấm dứt; nhằm đạt đến Niết-bàn.",
  "mn22:20.6": "Người ấy nghĩ như vầy:",
  "mn22:20.7": "‘Thế là tôi sẽ bị dứt mất, sẽ bị tiêu tan, sẽ không còn nữa.’",
  "mn22:20.8": "Người ấy buồn, héo mòn, than khóc, đấm ngực khóc lóc, rối loạn tâm trí.",
  "mn22:20.9": "Này Tỳ Kheo, như vậy là khi không có cái ở bên trong thì có bấn loạn.”",
  "mn22:21.1": "“Nhưng bạch Thế Tôn, có khi nào vì không có cái ở bên trong mà không bấn loạn không?”",
  "mn22:21.2": "“Có, này các Tỳ Kheo,” Đức Thế Tôn nói.",
  "mn22:21.3": "“Ở đây, này Tỳ Kheo, có người không có cách thấy như vầy:",
  "mn22:21.4": "‘Thế giới ấy là ta, ta ấy; sau khi chết, tôi sẽ còn mãi, bền chắc, đời đời, không đổi khác, và sẽ đứng y như vậy mãi mãi.’",
  "mn22:21.5": "Người ấy nghe Đức Như Lai hoặc đệ tử của Đức Như Lai nói lời dạy nhằm nhổ sạch mọi chỗ bám của cách thấy, mọi chỗ dựng lập của cách thấy, mọi thứ bị che phủ, dính chặt và ngấm ngầm nằm sâu; nhằm làm lắng yên mọi tạo tác; nhằm buông hết mọi chỗ nắm giữ; nhằm làm tắt hẳn lòng ham muốn; nhằm phai nhạt dính mắc; nhằm chấm dứt; nhằm đạt đến Niết-bàn.",
  "mn22:21.6": "Người ấy không nghĩ như vầy:",
  "mn22:21.7": "‘Thế là tôi sẽ bị dứt mất, sẽ bị tiêu tan, sẽ không còn nữa.’",
  "mn22:21.8": "Người ấy không buồn, không héo mòn, không than khóc, không đấm ngực khóc lóc, không rối loạn tâm trí.",
  "mn22:21.9": "Này Tỳ Kheo, như vậy là khi không có cái ở bên trong thì không bấn loạn.",
  "mn22:22.1": "Này các Tỳ Kheo, nếu có một cái nắm giữ mà cái được nắm giữ ấy là còn mãi, bền chắc, đời đời, không đổi khác, và sẽ đứng y như vậy mãi mãi, thì các ông có thể nắm giữ cái ấy.",
  "mn22:22.2": "Này các Tỳ Kheo, các ông có thấy một cái nắm giữ nào mà cái được nắm giữ ấy là còn mãi, bền chắc, đời đời, không đổi khác, và sẽ đứng y như vậy mãi mãi không?”",
  "mn22:22.3": "“Thưa không, bạch Thế Tôn.”",
  "mn22:22.4": "“Lành thay, này các Tỳ Kheo.",
  "mn22:22.5": "Này các Tỳ Kheo, chính Ta cũng không thấy một cái nắm giữ nào mà cái được nắm giữ ấy là còn mãi, bền chắc, đời đời, không đổi khác, và sẽ đứng y như vậy mãi mãi.",
  "mn22:23.1": "Này các Tỳ Kheo, nếu có một sự bám lấy ý nghĩ về cái ta mà khi bám lấy nó, buồn than, than khóc, khổ đau, lòng buồn bực và quẫn bách sẽ không sinh ra, thì các ông có thể bám lấy sự bám chặt vào ý nghĩ về cái ta ấy.",
  "mn22:23.2": "Này các Tỳ Kheo, các ông có thấy một sự bám lấy ý nghĩ về cái ta nào mà khi bám lấy nó, buồn than, than khóc, khổ đau, lòng buồn bực và quẫn bách sẽ không sinh ra không?”",
  "mn22:23.3": "“Thưa không, bạch Thế Tôn.”",
  "mn22:23.4": "“Lành thay, này các Tỳ Kheo.”",
  "mn22:23.5": "Này các Tỳ Kheo, Ta cũng không thấy có một chỗ nắm giữ nào về cái ta mà khi nắm giữ chỗ ấy lại không sinh ra buồn rầu, than khóc, khổ đau, bứt rứt và não nề.",
  "mn22:24.1": "Này các Tỳ Kheo, hãy nương vào một cách thấy nào mà khi nương vào cách thấy ấy sẽ không sinh ra buồn rầu, than khóc, khổ đau, bứt rứt và não nề.",
  "mn22:24.2": "Này các Tỳ Kheo, các ông có thấy một cách thấy như vậy không, một cách thấy mà khi nương vào đó sẽ không sinh ra buồn rầu, than khóc, khổ đau, bứt rứt và não nề chăng?",
  "mn22:24.3": "Thưa không, bạch Thế Tôn.",
  "mn22:24.4": "Lành thay, này các Tỳ Kheo.",
  "mn22:24.5": "Này các Tỳ Kheo, Ta cũng không thấy có một cách thấy nào mà khi nương vào đó sẽ không sinh ra buồn rầu, than khóc, khổ đau, bứt rứt và não nề.",
  "mn22:25.1": "Này các Tỳ Kheo, nếu có cái ta, thì có thể có ý nghĩ: ‘Cái này là của ta’, phải không?",
  "mn22:25.2": "Thưa phải, bạch Thế Tôn.",
  "mn22:25.3": "Này các Tỳ Kheo, nếu có cái thuộc về ta, thì có thể có ý nghĩ: ‘Đây là ta’, phải không?",
  "mn22:25.4": "Thưa phải, bạch Thế Tôn.",
  "mn22:25.5": "Này các Tỳ Kheo, khi cái ta và cái thuộc về ta thật sự không tìm thấy được,",
  "mn22:25.6": "thì chỗ bám víu của cách thấy này: ‘Thế gian là ta, sau khi chết ta sẽ là như vậy, còn mãi, bền mãi, luôn luôn như thế, không đổi khác, và sẽ đứng y như vậy mãi mãi’—",
  "mn22:25.7": "này các Tỳ Kheo, chẳng phải đó chỉ là trọn vẹn một lối nghĩ của kẻ ngu sao?",
  "mn22:25.8": "Còn là gì khác được nữa, bạch Thế Tôn? Thưa bạch Thế Tôn, đó thật sự chỉ là trọn vẹn một lối nghĩ của kẻ ngu.",
  "mn22:26.1": "Này các Tỳ Kheo, các ông nghĩ sao,",
  "mn22:26.2": "thân là còn mãi hay đổi thay?",
  "mn22:26.3": "Là đổi thay, bạch Thế Tôn.",
  "mn22:26.4": "Cái gì đổi thay thì là khổ đau hay dễ chịu?",
  "mn22:26.5": "Là khổ đau, bạch Thế Tôn.",
  "mn22:26.6": "Cái gì đổi thay, khổ đau, có tính chất đổi khác, thì có hợp để xem như vầy không:",
  "mn22:26.7": "‘Cái này là của ta, cái này là ta, cái này là chính mình ta’?",
  "mn22:26.8": "Thưa không, bạch Thế Tôn.",
  "mn22:26.9": "Này các Tỳ Kheo, các ông nghĩ sao,",
  "mn22:26.10": "cảm giác …",
  "mn22:26.11": "ghi nhận …",
  "mn22:26.12": "các hoạt động của tâm …",
  "mn22:26.13": "sự nhận biết là còn mãi hay đổi thay?",
  "mn22:26.14": "Là đổi thay, bạch Thế Tôn.",
  "mn22:26.15": "Cái gì đổi thay thì là khổ đau hay dễ chịu?",
  "mn22:26.16": "Là khổ đau, bạch Thế Tôn.",
  "mn22:26.17": "“Nhưng cái gì không bền, khổ đau, có tính đổi khác, có hợp để nhìn như vầy không—",
  "mn22:26.18": "‘cái này là của tôi, cái này là tôi, cái này là mình tôi’?”",
  "mn22:26.19": "“Thưa Thế Tôn, không ạ.”",
  "mn22:27.1": "“Vậy nên, này các Tỳ Kheo, bất cứ sắc nào thuộc quá khứ, tương lai hay hiện tại, ở trong mình hay ở ngoài, thô hay mịn, kém hay tốt, xa hay gần, mọi sắc đều phải được thấy đúng như thật bằng sự hiểu rõ đúng đắn rằng: ‘cái này không phải của tôi, cái này không phải là tôi, cái này không phải là mình tôi’.",
  "mn22:27.2": "Bất cứ cảm giác nào …",
  "mn22:27.3": "bất cứ ghi nhận nào …",
  "mn22:27.4": "bất cứ các hoạt động của tâm nào …",
  "mn22:27.5": "bất cứ sự nhận biết nào thuộc quá khứ, tương lai hay hiện tại, ở trong mình hay ở ngoài, thô hay mịn, kém hay tốt, xa hay gần, mọi sự nhận biết đều phải được thấy đúng như thật bằng sự hiểu rõ đúng đắn rằng: ‘cái này không phải của tôi, cái này không phải là tôi, cái này không phải là mình tôi’.",
  "mn22:28.1": "Thấy như vậy, này các Tỳ Kheo, người đệ tử bậc thánh đã nghe hiểu thì chán lìa đối với sắc, chán lìa đối với cảm giác, chán lìa đối với ghi nhận, chán lìa đối với các hoạt động của tâm, chán lìa đối với sự nhận biết,",
  "mn22:29.1": "do chán lìa nên phai nhạt ham muốn, do ham muốn phai nhạt nên được buông thoát; khi đã buông thoát thì biết rõ rằng: ‘đã buông thoát’.",
  "mn22:29.2": "Vị ấy hiểu rõ: ‘sự sinh đã dứt, đời sống phạm hạnh đã sống xong, việc cần làm đã làm xong, không còn trở lại trạng thái này nữa’.",
  "mn22:30.1": "Này các Tỳ Kheo, vị Tỳ Kheo ấy được gọi là người đã nhấc thanh chặn lên, cũng được gọi là người đã lấp đầy hào rãnh, cũng được gọi là người đã nhổ cột trụ lên, cũng được gọi là người không còn then cài, cũng được gọi là bậc thánh đã hạ cờ xuống, đã đặt gánh nặng xuống, đã thoát mọi trói buộc.",
  "mn22:31.1": "Và này các Tỳ Kheo, thế nào là vị Tỳ Kheo đã nhấc thanh chặn lên?",
  "mn22:31.2": "Ở đây, này các Tỳ Kheo, nơi một vị Tỳ Kheo, sự không biết rõ đã được dứt bỏ, bị chặt tận gốc, bị làm như gốc cây thốt nốt, bị làm cho không còn nữa, không thể sinh ra lại trong tương lai.",
  "mn22:31.3": "Như vậy, này các Tỳ Kheo, là vị Tỳ Kheo đã nhấc thanh chặn lên.",
  "mn22:32.1": "Và này các Tỳ Kheo, thế nào là vị Tỳ Kheo đã lấp đầy hào rãnh?",
  "mn22:32.2": "Ở đây, này các Tỳ Kheo, nơi một vị Tỳ Kheo, vòng luân chuyển sinh ra rồi lại sinh ra nữa đã được dứt bỏ, bị chặt tận gốc, bị làm như gốc cây thốt nốt, bị làm cho không còn nữa, không thể sinh ra lại trong tương lai.",
  "mn22:32.3": "Như vậy, này các Tỳ Kheo, là vị Tỳ Kheo đã lấp đầy hào rãnh.",
  "mn22:33.1": "Và này các Tỳ Kheo, thế nào là vị Tỳ Kheo đã nhổ cột trụ lên?",
  "mn22:33.2": "Ở đây, này các Tỳ Kheo, nơi một vị Tỳ Kheo, sự thèm muốn đã được dứt bỏ, bị chặt tận gốc, bị làm như gốc cây thốt nốt, bị làm cho không còn nữa, không thể sinh ra lại trong tương lai.",
  "mn22:33.3": "Như vậy, này các Tỳ Kheo, là vị Tỳ Kheo đã nhổ cột trụ lên.",
  "mn22:34.1": "Và này các Tỳ Kheo, thế nào là vị Tỳ Kheo không còn then cài?",
  "mn22:34.2": "Ở đây, này các Tỳ Kheo, nơi một vị Tỳ Kheo, năm trói buộc kéo xuống phần thấp đã được dứt bỏ, bị chặt tận gốc, bị làm như gốc cây thốt nốt, bị làm cho không còn nữa, không thể sinh ra lại trong tương lai.",
  "mn22:34.3": "Như vậy, này các Tỳ Kheo, là vị Tỳ Kheo không còn then cài.",
  "mn22:35.1": "Và này các Tỳ Kheo, thế nào là vị Tỳ Kheo, bậc thánh đã hạ cờ xuống, đã đặt gánh nặng xuống, đã thoát mọi trói buộc?",
  "mn22:35.2": "Ở đây, này các Tỳ Kheo, nơi một vị Tỳ Kheo, cái ngã mạn ‘ta là’ đã được dứt bỏ, bị chặt tận gốc, bị làm như gốc cây thốt nốt, bị làm cho không còn nữa, không thể sinh ra lại trong tương lai.",
  "mn22:35.3": "Như vậy, này các Tỳ Kheo, là vị Tỳ Kheo, bậc thánh đã hạ cờ xuống, đã đặt gánh nặng xuống, đã thoát mọi trói buộc.",
  "mn22:36.1": "Này các Tỳ Kheo, một vị Tỳ Kheo có lòng đã được buông thoát như vậy, thì chư thiên cùng với Ma vương, cùng với Phạm thiên, cùng với Pajāpati, có tìm kiếm cũng không thấy được rằng:",
  "mn22:36.2": "‘sự nhận biết của Như Lai nương vào cái này’.",
  "mn22:36.3": "Vì sao vậy?",
  "mn22:36.4": "Này các Tỳ Kheo, Ta nói rằng ngay trong đời này, Như Lai không thể bị nắm bắt.",
  "mn22:37.1": "Này các Tỳ Kheo, có một số sa môn, bà la môn vu khống Ta bằng điều không thật, rỗng không, dối trá, không có thật, khi Ta nói như vậy và chỉ dạy như vậy:",
  "mn22:37.2": "‘Sa môn Gotama là người dạy sự dứt bỏ, chủ trương rằng một chúng sinh có thật sẽ bị cắt đứt, tiêu tan, không còn nữa.’",
  "mn22:37.3": "Này các Tỳ Kheo, điều Ta không nói, điều Ta không dạy, thì các sa môn, bà la môn ấy lại vu khống Ta bằng điều không thật, rỗng không, dối trá, không có thật như thế này:",
  "mn22:37.4": "‘Sa môn Gotama là người dạy sự dứt bỏ, chủ trương rằng một chúng sinh có thật sẽ bị cắt đứt, tiêu tan, không còn nữa.’",
  "mn22:37.5": "Này các Tỳ Kheo, trước kia cũng như bây giờ, Ta chỉ chỉ bày sự khổ đau và sự chấm dứt khổ đau.",
  "mn22:37.6": "Nếu người khác mắng chửi, nhục mạ, chọc giận, quấy rầy Như Lai, thì Như Lai không có bực tức, không có điều trái ý, không có sự khó chịu trong lòng.",
  "mn22:38.1": "Nếu người khác kính trọng, xem là cao quý, tôn kính, cúng dường Như Lai, thì Như Lai không có mừng vui, không có vui sướng trong lòng, không có tâm bị dâng lên.",
  "mn22:38.2": "Nếu người khác kính trọng, xem là cao quý, tôn kính, cúng dường Như Lai, thì Như Lai nghĩ như vầy:",
  "mn22:38.3": "‘Đây chỉ là những việc người ta làm đối với điều đã được hiểu rõ từ trước nơi Ta.’",
  "mn22:39.1": "Vậy nên, này các Tỳ Kheo, nếu người khác có mắng chửi, nhục mạ, chọc giận, quấy rầy các ông, thì các ông không nên khởi bực tức, không nên trái ý, không nên khó chịu trong lòng.",
  "mn22:39.2": "Vậy nên, này các Tỳ Kheo, nếu người khác có kính trọng, xem là cao quý, tôn kính, cúng dường các ông, thì các ông không nên mừng vui, không nên vui sướng trong lòng, không nên để tâm dâng lên.",
  "mn22:39.3": "Vậy nên, này các Tỳ Kheo, nếu người khác có kính trọng, xem là cao quý, tôn kính, cúng dường các ông, thì các ông nên nghĩ như vầy:",
  "mn22:39.4": "‘Đây chỉ là những việc người ta làm đối với điều đã được hiểu rõ từ trước nơi ta.’",
  "mn22:40.1": "Vậy nên, này các Tỳ Kheo, cái gì không phải của các ông, hãy buông nó đi;",
  "mn22:40.2": "khi đã buông nó rồi, điều ấy sẽ đem lại lợi ích và sự yên vui lâu dài cho các ông.",
  "mn22:41.1": "Này các Tỳ Kheo, cái gì không phải của các ông?",
  "mn22:41.2": "Thân này không phải của các ông, hãy buông nó đi;",
  "mn22:41.3": "khi đã buông nó rồi, điều ấy sẽ đem lại lợi ích và sự yên vui lâu dài cho các ông.",
  "mn22:41.4": "Cảm giác không phải của các ông, hãy buông nó đi;",
  "mn22:41.5": "khi đã buông nó rồi, điều ấy sẽ đem lại lợi ích và sự yên vui lâu dài cho các ông.",
  "mn22:41.6": "Sự ghi nhận không phải của các ông, hãy buông nó đi;",
  "mn22:41.7": "khi đã buông nó rồi, điều ấy sẽ đem lại lợi ích và sự yên vui lâu dài cho các ông.",
  "mn22:41.8": "Các hoạt động của tâm không phải của các ông, hãy buông chúng đi;",
  "mn22:41.9": "khi đã buông chúng rồi, chúng sẽ đem lại lợi ích và sự yên vui lâu dài cho các ông.",
  "mn22:41.10": "Sự nhận biết không phải của các ông, hãy buông nó đi;",
  "mn22:41.11": "khi đã buông nó rồi, điều ấy sẽ đem lại lợi ích và sự yên vui lâu dài cho các ông.",
  "mn22:41.12": "Các ông nghĩ sao, này các Tỳ Kheo,",
  "mn22:41.13": "cỏ, củi, cành, lá trong rừng Kỳ Đà này, nếu người ta mang đi, đốt đi, hay dùng vào việc gì tùy ý,",
  "mn22:41.14": "thì các ông có nghĩ rằng:",
  "mn22:41.15": "‘người ta có mang chúng tôi đi, hay đốt đi, hay làm gì tùy ý’ không?”",
  "mn22:41.16": "“Thưa không, bạch Đức Thế Tôn.”",
  "mn22:41.17": "“Vì sao vậy?”",
  "mn22:41.18": "“Vì đó không phải là mình, cũng không phải là cái thuộc về mình, bạch Đức Thế Tôn.”",
  "mn22:41.19": "“Cũng vậy đó, này các Tỳ Kheo, cái gì không phải của các ông thì hãy buông nó đi;",
  "mn22:41.20": "khi đã buông nó rồi, điều đó sẽ đem lại điều lành và sự yên vui lâu dài cho các ông.",
  "mn22:41.21": "Và này các Tỳ Kheo, cái gì không phải của các ông?",
  "mn22:41.22": "Thân này, này các Tỳ Kheo, không phải của các ông, hãy buông nó đi;",
  "mn22:41.23": "khi đã buông nó rồi, điều đó sẽ đem lại điều lành và sự yên vui lâu dài cho các ông.",
  "mn22:41.24": "Cảm giác, này các Tỳ Kheo …",
  "mn22:41.25": "sự ghi nhận, này các Tỳ Kheo …",
  "mn22:41.26": "các hoạt động của tâm, này các Tỳ Kheo …",
  "mn22:41.27": "sự nhận biết, này các Tỳ Kheo, không phải của các ông, hãy buông nó đi;",
  "mn22:41.28": "khi đã buông nó rồi, điều đó sẽ đem lại điều lành và sự yên vui lâu dài cho các ông.",
  "mn22:42.1": "Này các Tỳ Kheo, điều ta chỉ dạy đã được nói khéo như vậy, rõ ràng, mở ra, soi sáng, như đã lột bỏ lớp bọc.",
  "mn22:42.2": "Này các Tỳ Kheo, khi điều ta chỉ dạy đã được nói khéo như vậy, rõ ràng, mở ra, soi sáng, như đã lột bỏ lớp bọc, thì những Tỳ Kheo nào là bậc đã sạch hết lậu hoặc, đã sống trọn đời sống này, việc cần làm đã làm xong, đã đặt gánh nặng xuống, đã đạt tới mục đích của mình, đã dứt sạch mọi trói buộc của đời sống, đã được giải thoát nhờ hiểu đúng, thì không còn vòng quay nào để nói về các vị ấy nữa.",
  "mn22:43.1": "Này các Tỳ Kheo, điều ta chỉ dạy đã được nói khéo như vậy, rõ ràng, mở ra, soi sáng, như đã lột bỏ lớp bọc.",
  "mn22:43.2": "Này các Tỳ Kheo, khi điều ta chỉ dạy đã được nói khéo như vậy, rõ ràng, mở ra, soi sáng, như đã lột bỏ lớp bọc, thì những Tỳ Kheo nào đã buông bỏ năm trói buộc kéo xuống phần dưới, tất cả các vị ấy sẽ hóa sinh, sẽ tắt hẳn ngay tại đó, không còn trở lui khỏi cõi ấy nữa.",
  "mn22:44.1": "Này các Tỳ Kheo, điều ta chỉ dạy đã được nói khéo như vậy, rõ ràng, mở ra, soi sáng, như đã lột bỏ lớp bọc.",
  "mn22:44.2": "Này các Tỳ Kheo, khi điều ta chỉ dạy đã được nói khéo như vậy, rõ ràng, mở ra, soi sáng, như đã lột bỏ lớp bọc, thì những Tỳ Kheo nào đã buông bỏ ba trói buộc, và lòng ham muốn, sự bực tức, sự mờ tối đã mỏng đi, tất cả các vị ấy là bậc chỉ còn trở lại đời này một lần nữa, rồi sẽ chấm dứt khổ đau.",
  "mn22:45.1": "Này các Tỳ Kheo, điều ta chỉ dạy đã được nói khéo như vậy, rõ ràng, mở ra, soi sáng, như đã lột bỏ lớp bọc.",
  "mn22:45.2": "Này các Tỳ Kheo, khi điều ta chỉ dạy đã được nói khéo như vậy, rõ ràng, mở ra, soi sáng, như đã lột bỏ lớp bọc, thì những Tỳ Kheo nào đã buông bỏ ba trói buộc, tất cả các vị ấy là bậc đã vào dòng, không còn rơi xuống chỗ dữ, chắc chắn sẽ hướng tới sự tỉnh sáng trọn vẹn.",
  "mn22:46.1": "Này các Tỳ Kheo, điều ta chỉ dạy đã được nói khéo như vậy, rõ ràng, mở ra, soi sáng, như đã lột bỏ lớp bọc.",
  "mn22:46.2": "Này các Tỳ Kheo, khi điều ta chỉ dạy đã được nói khéo như vậy, rõ ràng, mở ra, soi sáng, như đã lột bỏ lớp bọc, thì những Tỳ Kheo nào đi theo nhờ hiểu điều được dạy, hay đi theo nhờ lòng tin, tất cả các vị ấy đều hướng tới sự tỉnh sáng trọn vẹn.",
  "mn22:47.1": "Này các Tỳ Kheo, điều ta chỉ dạy đã được nói khéo như vậy, rõ ràng, mở ra, soi sáng, như đã lột bỏ lớp bọc.",
  "mn22:47.2": "Này các Tỳ Kheo, khi điều ta chỉ dạy đã được nói khéo như vậy, rõ ràng, mở ra, soi sáng, như đã lột bỏ lớp bọc, thì những ai chỉ có lòng tin nơi ta, chỉ có lòng mến nơi ta, tất cả những người ấy đều hướng tới cõi trời.”",
  "mn22:47.3": "Đức Thế Tôn nói như vậy.",
  "mn22:47.4": "Các Tỳ Kheo hoan hỷ, vui mừng đón nhận lời Đức Thế Tôn dạy.",
  "mn22:47.5": "Kinh Ví Dụ Con Rắn kết thúc."
}
window.BILARA["mn22"]["vi"]["mn22:source"] =
  "Dịch từ nguồn Pali https://suttacentral.net/";