window.BILARA = window.BILARA || {};
window.BILARA["mn28"] = window.BILARA["mn28"] || {};
window.BILARA["mn28"]["vi"] = {
  "mn28:0.1": "Trung Bộ Kinh 28 ",
  "mn28:0.2": "Kinh Ví Dụ Dấu Chân Voi Lớn ",
  "mn28:1.1": "Như vầy tôi nghe—",
  "mn28:1.2": "một thời Thế Tôn trú ở Sāvatthī, tại rừng Jetavana, tịnh xá của ông Anāthapiṇḍika. ",
  "mn28:1.3": "Tại đấy, Tôn giả Sāriputta gọi các Tỳ-kheo: ",
  "mn28:1.4": "“Này các Hiền giả Tỳ-kheo.” ",
  "mn28:1.5": "Các Tỳ-kheo ấy vâng đáp Tôn giả Sāriputta: “Thưa Hiền giả.” ",
  "mn28:1.6": "Tôn giả Sāriputta nói như sau: ",
  "mn28:2.1": "“Này các Hiền giả, ví như tất cả dấu chân của các loài vật sống trong rừng đều nằm gọn trong dấu chân voi, dấu chân voi được xem là lớn nhất trong số đó vì sự to lớn của nó; ",
  "mn28:2.2": "cũng vậy, này các Hiền giả, tất cả các pháp thiện đều nằm gọn trong bốn sự thật cao quý. ",
  "mn28:2.3": "Bốn sự thật nào? ",
  "mn28:2.4": "Sự thật cao quý về khổ, sự thật cao quý về nguyên nhân của khổ, sự thật cao quý về sự chấm dứt khổ, sự thật cao quý về con đường đưa đến sự chấm dứt khổ. ",
  "mn28:3.1": "Này các Hiền giả, sự thật cao quý về khổ là gì? ",
  "mn28:3.2": "Sinh là khổ, già là khổ, chết là khổ, sầu bi khổ ưu não là khổ, điều mong muốn mà không đạt được cũng là khổ; tóm lại, năm uẩn chấp thủ là khổ. ",
  "mn28:3.3": "Này các Hiền giả, năm uẩn chấp thủ là gì? ",
  "mn28:3.4": "Đó là—sắc uẩn chấp thủ, thọ uẩn chấp thủ, tưởng uẩn chấp thủ, hành uẩn chấp thủ, thức uẩn chấp thủ. ",
  "mn28:4.1": "Này các Hiền giả, sắc uẩn chấp thủ là gì? ",
  "mn28:4.2": "Bốn đại và sắc do bốn đại tạo thành. ",
  "mn28:5.1": "Này các Hiền giả, bốn đại là gì? ",
  "mn28:5.2": "Địa giới, thủy giới, hỏa giới, phong giới. ",
  "mn28:6.1": "Này các Hiền giả, địa giới là gì? ",
  "mn28:6.2": "Địa giới có thể là nội, có thể là ngoại. ",
  "mn28:6.3": "Này các Hiền giả, địa giới nội là gì? ",
  "mn28:6.4": "Cái gì bên trong, thuộc về cá nhân, cứng rắn, thô ráp, bị chấp thủ, đó là—",
  "mn28:6.5": "tóc, lông, móng, răng, da, thịt, gân, xương, tủy xương, thận, tim, gan, hoành cách mô, lá lách, phổi, ruột, màng ruột, dạ dày, phân, hoặc bất cứ cái gì khác bên trong, thuộc về cá nhân, cứng rắn, thô ráp, bị chấp thủ. ",
  "mn28:6.6": "Này các Hiền giả, đây gọi là địa giới nội. ",
  "mn28:6.7": "Địa giới nội và địa giới ngoại, tất cả đều là địa giới. ",
  "mn28:6.8": "‘Cái đó không phải của tôi, tôi không phải là cái đó, cái đó không phải tự ngã của tôi’—phải thấy điều này đúng như thật bằng trí tuệ chân chính. ",
  "mn28:6.9": "Thấy điều này đúng như thật bằng trí tuệ chân chính, người ấy nhàm chán địa giới, tâm lìa tham ái đối với địa giới. ",
  "mn28:7.1": "Này các Hiền giả, có lúc thủy giới ngoại nổi lên. ",
  "mn28:7.2": "Vào lúc ấy, địa giới ngoại biến mất. ",
  "mn28:7.3": "Này các Hiền giả, ngay cả địa giới ngoại to lớn như vậy cũng sẽ được thấy là vô thường, có tính chất hoại diệt, có tính chất tiêu tan, có tính chất biến đổi. ",
  "mn28:7.4": "Huống chi cái thân thể nhỏ bé này, bị tham ái chấp thủ, lại có thể nói ‘tôi’ hay ‘của tôi’ hay ‘tôi là’? Không có điều đó ở đây. ",
  "mn28:8.1": "Này các Hiền giả, nếu các người khác mắng chửi, phỉ báng, làm tức giận, làm hại một Tỳ-kheo, vị ấy biết như sau: ",
  "mn28:8.2": "‘Cảm thọ khổ này do xúc chạm với tai đã khởi lên nơi tôi. ",
  "mn28:8.3": "Cảm thọ ấy có duyên, không phải không duyên. ",
  "mn28:8.4": "Duyên gì? ",
  "mn28:8.5": "Duyên xúc.’ ",
  "mn28:8.6": "Vị ấy thấy xúc là vô thường, thấy thọ là vô thường, thấy tưởng là vô thường, thấy hành là vô thường, thấy thức là vô thường. ",
  "mn28:8.7": "Tâm của vị ấy hướng về giới, tịnh tín, an trú, quyết định. ",
  "mn28:9.1": "Này các Hiền giả, nếu các người khác đối xử với Tỳ-kheo bằng những điều không mong muốn, không ưa thích, không vừa ý—",
  "mn28:9.2": "bằng cách chạm tay, chạm đất, chạm gậy, chạm dao. ",
  "mn28:9.3": "Vị ấy biết như sau: ",
  "mn28:9.4": "‘Thân này là như vậy, trong thân như vậy, sự chạm tay cũng đến, sự chạm đất cũng đến, sự chạm gậy cũng đến, sự chạm dao cũng đến. ",
  "mn28:9.5": "Thế Tôn đã nói trong lời khuyên ví dụ cái cưa: ",
  "mn28:9.6": "“Này các Tỳ-kheo, dù cho bọn cướp, bọn du côn có dùng cưa hai tay mà cưa từng bộ phận thân thể, nếu ai để tâm sân hận, người ấy không phải là người làm theo lời dạy của Ta.” ",
  "mn28:9.7": "Nỗ lực của tôi sẽ được khởi lên, không lười biếng; chánh niệm sẽ được thiết lập, không quên lãng; thân sẽ được an tịnh, không xao động; tâm sẽ được định tĩnh, nhất tâm. ",
  "mn28:9.8": "Dù cho bây giờ trong thân này, sự chạm tay có đến, sự chạm đất có đến, sự chạm gậy có đến, sự chạm dao có đến, đây là lời dạy của các vị Phật cần phải thực hành.’ ",
  "mn28:10.1": "Này các Hiền giả, nếu một Tỳ-kheo khi niệm Phật như vậy, niệm Pháp như vậy, niệm Tăng như vậy mà tâm xả dựa trên thiện pháp không an trú. ",
  "mn28:10.2": "Vị ấy do đó kinh hãi, khởi lên sự xúc động: ",
  "mn28:10.3": "‘Thật là bất lợi cho tôi, thật không phải là lợi lộc cho tôi; thật là điều tệ hại cho tôi, thật không phải là điều tốt đẹp cho tôi, ",
  "mn28:10.4": "khi tôi niệm Phật như vậy, niệm Pháp như vậy, niệm Tăng như vậy mà tâm xả dựa trên thiện pháp không an trú.’ ",
  "mn28:10.5": "Này các Hiền giả, ví như một nàng dâu khi thấy cha chồng thì kinh hãi, khởi lên sự xúc động; ",
  "mn28:10.6": "cũng vậy, này các Hiền giả, nếu một Tỳ-kheo khi niệm Phật như vậy, niệm Pháp như vậy, niệm Tăng như vậy mà tâm xả dựa trên thiện pháp không an trú, vị ấy do đó kinh hãi, khởi lên sự xúc động: ",
  "mn28:10.7": "‘Thật là bất lợi cho tôi, thật không phải là lợi lộc cho tôi; thật là điều tệ hại cho tôi, thật không phải là điều tốt đẹp cho tôi, khi tôi niệm Phật như vậy, niệm Pháp như vậy, niệm Tăng như vậy mà tâm xả dựa trên thiện pháp không an trú.’ ",
  "mn28:10.8": "Này các Hiền giả, nếu một Tỳ-kheo khi niệm Phật như vậy, niệm Pháp như vậy, niệm Tăng như vậy mà tâm xả dựa trên thiện pháp an trú, vị ấy do đó hoan hỷ. ",
  "mn28:10.9": "Này các Hiền giả, chừng đó cũng là điều lớn lao đối với một Tỳ-kheo. ",
  "mn28:11.1": "Này các Hiền giả, thủy giới là gì? ",
  "mn28:11.2": "Thủy giới có thể là nội, có thể là ngoại. ",
  "mn28:11.3": "Này các Hiền giả, thủy giới nội là gì? ",
  "mn28:11.4": "Cái gì bên trong, thuộc về cá nhân, là nước, có tính chất nước, bị chấp thủ, đó là—",
  "mn28:11.5": "mật, đờm, mủ, máu, mồ hôi, mỡ, nước mắt, mỡ da, nước bọt, nước mũi, dịch khớp, nước tiểu, hoặc bất cứ cái gì khác bên trong, thuộc về cá nhân, là nước, có tính chất nước, bị chấp thủ—",
  "mn28:11.6": "Này các Hiền giả, đây gọi là thủy giới nội. ",
  "mn28:11.7": "Thủy giới nội và thủy giới ngoại, tất cả đều là thủy giới. ",
  "mn28:11.8": "‘Cái đó không phải của tôi, tôi không phải là cái đó, cái đó không phải tự ngã của tôi’—phải thấy điều này đúng như thật bằng trí tuệ chân chính. ",
  "mn28:11.9": "Thấy điều này đúng như thật bằng trí tuệ chân chính, người ấy nhàm chán thủy giới, tâm lìa tham ái đối với thủy giới. ",
  "mn28:12.1": "Này các Hiền giả, có lúc thủy giới ngoại nổi lên. ",
  "mn28:12.2": "Nó cuốn trôi làng mạc, cuốn trôi thị trấn, cuốn trôi thành phố, cuốn trôi quốc gia, cuốn trôi các vùng của quốc gia. ",
  "mn28:12.3": "Này các Hiền giả, có lúc nước trong đại dương rút xuống hàng trăm do tuần, rút xuống hai trăm do tuần, rút xuống ba trăm do tuần, rút xuống bốn trăm do tuần, rút xuống năm trăm do tuần, rút xuống sáu trăm do tuần, rút xuống bảy trăm do tuần. ",
  "mn28:12.4": "Này các Hiền giả, có lúc nước trong đại dương chỉ còn bảy cây thốt nốt, còn sáu cây thốt nốt, còn năm cây thốt nốt, còn bốn cây thốt nốt, còn ba cây thốt nốt, còn hai cây thốt nốt, còn một cây thốt nốt. ",
  "mn28:12.5": "Này các Hiền giả, có lúc nước trong đại dương chỉ còn bảy tầm người, còn sáu tầm người, còn năm tầm người, còn bốn tầm người, còn ba tầm người, còn hai tầm người, còn một tầm người. ",
  "mn28:12.6": "Này các Hiền giả, có lúc nước trong đại dương chỉ còn nửa tầm người, còn ngang thắt lưng, còn ngang đầu gối, còn ngang mắt cá chân. ",
  "mn28:12.7": "Này các Hiền giả, có lúc nước trong đại dương không còn dù chỉ bằng một đốt ngón tay. ",
  "mn28:12.8": "Này các Hiền giả, ngay cả thủy giới ngoại to lớn như vậy cũng sẽ được thấy là vô thường, có tính chất hoại diệt, có tính chất tiêu tan, có tính chất biến đổi. ",
  "mn28:13.1": "Huống chi cái thân thể nhỏ bé này, bị tham ái chấp thủ, lại có thể nói ‘tôi’ hay ‘của tôi’ hay ‘tôi là’? Không có điều đó ở đây… ",
  "mn28:14.1": "Này các Hiền giả, nếu một Tỳ-kheo khi niệm Phật như vậy, niệm Pháp như vậy, niệm Tăng như vậy mà tâm xả dựa trên thiện pháp an trú, vị ấy do đó hoan hỷ. ",
  "mn28:15.1": "Này các Hiền giả, chừng đó cũng là điều lớn lao đối với một Tỳ-kheo. ",
  "mn28:16.1": "Này các Hiền giả, hỏa giới là gì? ",
  "mn28:16.2": "Hỏa giới có thể là nội, có thể là ngoại. ",
  "mn28:16.3": "Này các Hiền giả, hỏa giới nội là gì? ",
  "mn28:16.4": "Cái gì bên trong, thuộc về cá nhân, là lửa, có tính chất lửa, bị chấp thủ, đó là—",
  "mn28:16.5": "cái làm cho thân ấm lên, cái làm cho thân già đi, cái làm cho thân bị thiêu đốt, cái làm cho thức ăn, đồ uống, đồ nhai, đồ nếm được tiêu hóa đúng cách, hoặc bất cứ cái gì khác bên trong, thuộc về cá nhân, là lửa, có tính chất lửa, bị chấp thủ—",
  "mn28:16.6": "Này các Hiền giả, đây gọi là hỏa giới nội. ",
  "mn28:16.7": "Hỏa giới nội và hỏa giới ngoại, tất cả đều là hỏa giới. ",
  "mn28:16.8": "‘Cái đó không phải của tôi, tôi không phải là cái đó, cái đó không phải tự ngã của tôi’—phải thấy điều này đúng như thật bằng trí tuệ chân chính. ",
  "mn28:16.9": "Thấy điều này đúng như thật bằng trí tuệ chân chính, người ấy nhàm chán hỏa giới, tâm lìa tham ái đối với hỏa giới. ",
  "mn28:17.1": "Này các Hiền giả, có lúc hỏa giới ngoại nổi lên. ",
  "mn28:17.2": "Nó đốt cháy làng mạc, đốt cháy thị trấn, đốt cháy thành phố, đốt cháy quốc gia, đốt cháy các vùng của quốc gia. ",
  "mn28:17.3": "Nó đến một nơi có cỏ xanh, một con đường, một tảng đá, một vùng nước, hoặc một vùng đất dễ chịu, rồi không có nhiên liệu thì tắt. ",
  "mn28:17.4": "Này các Hiền giả, có lúc người ta phải tìm lửa bằng một chiếc lông gà hay một miếng gân khô. ",
  "mn28:17.5": "Này các Hiền giả, ngay cả hỏa giới ngoại to lớn như vậy cũng sẽ được thấy là vô thường, có tính chất hoại diệt, có tính chất tiêu tan, có tính chất biến đổi. ",
  "mn28:17.6": "Huống chi cái thân thể nhỏ bé này, bị tham ái chấp thủ, lại có thể nói ‘tôi’ hay ‘của tôi’ hay ‘tôi là’? ",
  "mn28:18-20.1": "Không có điều đó ở đây… Này các Hiền giả, nếu một Tỳ-kheo khi niệm Phật như vậy, niệm Pháp như vậy, niệm Tăng như vậy mà tâm xả dựa trên thiện pháp an trú, vị ấy do đó hoan hỷ. ",
  "mn28:18-20.2": "Này các Hiền giả, chừng đó cũng là điều lớn lao đối với một Tỳ-kheo. ",
  "mn28:21.1": "Này các Hiền giả, phong giới là gì? ",
  "mn28:21.2": "Phong giới có thể là nội, có thể là ngoại. ",
  "mn28:21.3": "Này các Hiền giả, phong giới nội là gì? ",
  "mn28:21.4": "Cái gì bên trong, thuộc về cá nhân, là gió, có tính chất gió, bị chấp thủ, đó là—",
  "mn28:21.5": "gió thổi lên, gió thổi xuống, gió trong bụng, gió trong ruột, gió chạy khắp các chi, hơi thở vào, hơi thở ra, hoặc bất cứ cái gì khác bên trong, thuộc về cá nhân, là gió, có tính chất gió, bị chấp thủ—",
  "mn28:21.6": "Này các Hiền giả, đây gọi là phong giới nội. ",
  "mn28:21.7": "Phong giới nội và phong giới ngoại, tất cả đều là phong giới. ",
  "mn28:21.8": "‘Cái đó không phải của tôi, tôi không phải là cái đó, cái đó không phải tự ngã của tôi’—phải thấy điều này đúng như thật bằng trí tuệ chân chính. ",
  "mn28:21.9": "Thấy điều này đúng như thật bằng trí tuệ chân chính, người ấy nhàm chán phong giới, tâm lìa tham ái đối với phong giới. ",
  "mn28:22.1": "Này các Hiền giả, có lúc phong giới ngoại nổi lên. ",
  "mn28:22.2": "Nó cuốn trôi làng mạc, cuốn trôi thị trấn, cuốn trôi thành phố, cuốn trôi quốc gia, cuốn trôi các vùng của quốc gia. ",
  "mn28:22.3": "Này các Hiền giả, có lúc vào tháng cuối mùa hè, người ta phải tìm gió bằng quạt lá thốt nốt hay quạt tay, và không muốn cỏ bị ướt. ",
  "mn28:22.4": "Này các Hiền giả, ngay cả phong giới ngoại to lớn như vậy cũng sẽ được thấy là vô thường, có tính chất hoại diệt, có tính chất tiêu tan, có tính chất biến đổi. ",
  "mn28:22.5": "Huống chi cái thân thể nhỏ bé này, bị tham ái chấp thủ, lại có thể nói ‘tôi’ hay ‘của tôi’ hay ‘tôi là’? Không có điều đó ở đây. ",
  "mn28:23.1": "Này các Hiền giả, nếu các người khác mắng chửi, phỉ báng, làm tức giận, làm hại một Tỳ-kheo. ",
  "mn28:23.2": "Vị ấy biết như sau: ‘Cảm thọ khổ này do xúc chạm với tai đã khởi lên nơi tôi. ",
  "mn28:23.3": "Cảm thọ ấy có duyên, không phải không duyên. ",
  "mn28:23.4": "Duyên gì? ",
  "mn28:23.5": "Duyên xúc. ",
  "mn28:23.6": "Vị ấy thấy xúc là vô thường, thấy thọ là vô thường, thấy tưởng là vô thường, thấy hành là vô thường, thấy thức là vô thường. ",
  "mn28:23.7": "Tâm của vị ấy hướng về giới, tịnh tín, an trú, quyết định. ",
  "mn28:24.1": "Này các Hiền giả, nếu các người khác đối xử với Tỳ-kheo bằng những điều không mong muốn, không ưa thích, không vừa ý, bằng cách chạm tay, chạm đất, chạm gậy, chạm dao. ",
  "mn28:24.2": "Vị ấy biết như sau: ‘Thân này là như vậy, trong thân như vậy, sự chạm tay cũng đến, sự chạm đất cũng đến, sự chạm gậy cũng đến, sự chạm dao cũng đến. ",
  "mn28:24.3": "Thế Tôn đã nói trong lời khuyên ví dụ cái cưa: “Này các Tỳ-kheo, dù cho bọn cướp, bọn du côn có dùng cưa hai tay mà cưa từng bộ phận thân thể. Nếu ai để tâm sân hận, người ấy không phải là người làm theo lời dạy của Ta.” ",
  "mn28:24.4": "Nỗ lực của tôi sẽ được khởi lên, không lười biếng; chánh niệm sẽ được thiết lập, không quên lãng; thân sẽ được an tịnh, không xao động; tâm sẽ được định tĩnh, nhất tâm. ",
  "mn28:24.5": "Dù cho bây giờ trong thân này, sự chạm tay có đến, sự chạm đất có đến, sự chạm gậy có đến, sự chạm dao có đến. Đây là lời dạy của các vị Phật cần phải thực hành.’ ",
  "mn28:25.1": "Này các bạn, nếu vị tỳ khưu ấy, khi nhớ Phật như vậy, nhớ Pháp như vậy, nhớ Tăng như vậy, tâm xả nương tựa thiện pháp không an trú. ",
  "mn28:25.2": "Vị ấy do đó cảm thấy hổ thẹn, khởi lên sự xúc động: ",
  "mn28:25.3": "‘Thật là bất lợi cho ta, thật là không có lợi cho ta; thật là ta đã nhận được điều xấu, thật là ta đã không nhận được điều tốt. ",
  "mn28:25.4": "Khi ta nhớ Phật như vậy, nhớ Pháp như vậy, nhớ Tăng như vậy, tâm xả nương tựa thiện pháp không an trú.’ ",
  "mn28:25.5": "Này các bạn, ví như một nàng dâu khi thấy cha chồng cảm thấy hổ thẹn, khởi lên sự xúc động; ",
  "mn28:25.6": "cũng vậy, này các bạn, nếu vị tỳ khưu ấy, khi nhớ Phật như vậy, nhớ Pháp như vậy, nhớ Tăng như vậy, tâm xả nương tựa thiện pháp không an trú. ",
  "mn28:25.7": "Vị ấy do đó cảm thấy hổ thẹn, khởi lên sự xúc động: ",
  "mn28:25.8": "‘Thật là bất lợi cho ta, thật là không có lợi cho ta; thật là ta đã nhận được điều xấu, thật là ta đã không nhận được điều tốt. ",
  "mn28:25.9": "Khi ta nhớ Phật như vậy, nhớ Pháp như vậy, nhớ Tăng như vậy, tâm xả nương tựa thiện pháp không an trú.’ ",
  "mn28:25.10": "Này các bạn, nếu vị tỳ khưu ấy, khi nhớ Phật như vậy, nhớ Pháp như vậy, nhớ Tăng như vậy, tâm xả nương tựa thiện pháp an trú, vị ấy do đó hoan hỷ. ",
  "mn28:25.11": "Này các bạn, chỉ với chừng ấy thôi, vị tỳ khưu đã làm được nhiều việc. ",
  "mn28:26.1": "Này các bạn, ví như nương vào gỗ, nương vào dây leo, nương vào cỏ, nương vào đất sét, không gian được bao bọc được gọi là nhà; ",
  "mn28:26.2": "cũng vậy, này các bạn, nương vào xương, nương vào gân, nương vào thịt, nương vào da, không gian được bao bọc được gọi là sắc. ",
  "mn28:27.1": "Này các bạn, mắt bên trong không bị hư hoại, các sắc bên ngoài không đi vào tầm nhìn, và không có sự chú ý tương ứng, thì chưa có sự xuất hiện của phần thức tương ứng. ",
  "mn28:27.2": "Này các bạn, mắt bên trong không bị hư hoại, các sắc bên ngoài đi vào tầm nhìn, nhưng không có sự chú ý tương ứng, thì chưa có sự xuất hiện của phần thức tương ứng. ",
  "mn28:27.3": "Này các bạn, khi mắt bên trong không bị hư hoại, các sắc bên ngoài đi vào tầm nhìn, và có sự chú ý tương ứng. Như vậy, sự xuất hiện của phần thức tương ứng sẽ có. ",
  "mn28:28.1": "Sắc của người như vậy được tập hợp vào sắc uẩn chấp thủ, thọ của người như vậy được tập hợp vào thọ uẩn chấp thủ, tưởng của người như vậy được tập hợp vào tưởng uẩn chấp thủ, các hành của người như vậy được tập hợp vào hành uẩn chấp thủ, thức của người như vậy được tập hợp vào thức uẩn chấp thủ. ",
  "mn28:28.2": "Vị ấy biết như vậy: ",
  "mn28:28.3": "‘Thật vậy, sự tập hợp, sự tụ hội, sự kết hợp của năm uẩn chấp thủ này là như vậy. ",
  "mn28:28.4": "Điều này đã được Thế Tôn nói: ",
  "mn28:28.5": "“Ai thấy duyên khởi là thấy Pháp; ",
  "mn28:28.6": "ai thấy Pháp là thấy duyên khởi.” ",
  "mn28:28.7": "Năm uẩn chấp thủ này là do duyên khởi. ",
  "mn28:28.8": "Cái gì là dục, là ái, là tùy miên, là chấp thủ trong năm uẩn chấp thủ này, đó là sự tập khởi của khổ. ",
  "mn28:28.9": "Cái gì là sự diệt trừ dục ái, sự từ bỏ dục ái trong năm uẩn chấp thủ này, đó là sự diệt khổ.’ ",
  "mn28:28.10": "Này các bạn, chỉ với chừng ấy thôi, vị tỳ khưu đã làm được nhiều việc. ",
  "mn28:29-30.1": "Này các bạn, tai bên trong không bị hư hoại… ",
  "mn28:31-32.1": "mũi không bị hư hoại… ",
  "mn28:33-34.1": "lưỡi không bị hư hoại… ",
  "mn28:35-36.1": "thân không bị hư hoại… ",
  "mn28:37.1": "ý không bị hư hoại, các pháp bên ngoài không đi vào tầm nhận biết, và không có sự chú ý tương ứng, thì chưa có sự xuất hiện của phần thức tương ứng. ",
  "mn28:38.1": "Này các bạn, ý bên trong không bị hư hoại, các pháp bên ngoài đi vào tầm nhận biết, nhưng không có sự chú ý tương ứng, thì chưa có sự xuất hiện của phần thức tương ứng. ",
  "mn28:38.2": "Này các bạn, khi ý bên trong không bị hư hoại, các pháp bên ngoài đi vào tầm nhận biết, và có sự chú ý tương ứng, như vậy, sự xuất hiện của phần thức tương ứng sẽ có. ",
  "mn28:38.3": "Sắc của người như vậy được tập hợp vào sắc uẩn chấp thủ, thọ của người như vậy được tập hợp vào thọ uẩn chấp thủ, tưởng của người như vậy được tập hợp vào tưởng uẩn chấp thủ, các hành của người như vậy được tập hợp vào hành uẩn chấp thủ, thức của người như vậy được tập hợp vào thức uẩn chấp thủ. ",
  "mn28:38.4": "Vị ấy biết như vậy: ",
  "mn28:38.5": "‘Thật vậy, sự tập hợp, sự tụ hội, sự kết hợp của năm uẩn chấp thủ này là như vậy. ",
  "mn28:38.6": "Điều này đã được Thế Tôn nói: ",
  "mn28:38.7": "“Ai thấy duyên khởi là thấy Pháp; ",
  "mn28:38.8": "ai thấy Pháp là thấy duyên khởi.” ",
  "mn28:38.9": "Năm uẩn chấp thủ này là do duyên khởi. ",
  "mn28:38.10": "Cái gì là dục, là ái, là tùy miên, là chấp thủ trong năm uẩn chấp thủ này, đó là sự tập khởi của khổ. ",
  "mn28:38.11": "Cái gì là sự diệt trừ dục ái, sự từ bỏ dục ái trong năm uẩn chấp thủ này, đó là sự diệt khổ.’ ",
  "mn28:38.12": "Này các bạn, chỉ với chừng ấy thôi, vị tỳ khưu đã làm được nhiều việc.’ ",
  "mn28:38.13": "Tôn giả Sāriputta đã nói điều này. ",
  "mn28:38.14": "Các vị tỳ khưu ấy hoan hỷ, tán thán lời Tôn giả Sāriputta nói. ",
  "mn28:38.15": "Kinh Ví Dụ Dấu Chân Voi Lớn, thứ tám, chấm dứt. "
}
window.BILARA["mn28"]["vi"]["mn28:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
