window.BILARA = window.BILARA || {};
window.BILARA["mn51"] = window.BILARA["mn51"] || {};
window.BILARA["mn51"]["vi"] = {
  "mn51:0.1": "Trung Bộ Kinh 51 ",
  "mn51:0.2": "Kinh Kandarakaka ",
  "mn51:1.1": "Tôi nghe như vầy—",
  "mn51:1.2": "Một thời, Thế Tôn trú ở Campā, bên bờ hồ Gaggara, cùng với đại chúng Tỳ-kheo. ",
  "mn51:1.3": "Rồi Pessa, con người huấn luyện voi, và Kandarakaka, du sĩ, đi đến chỗ Thế Tôn; sau khi đến, Pessa, con người huấn luyện voi, đảnh lễ Thế Tôn rồi ngồi xuống một bên. ",
  "mn51:1.4": "Còn du sĩ Kandarakaka thì chào hỏi Thế Tôn. Sau khi nói lên những lời chào hỏi thân mật, đáng ghi nhớ, ông đứng một bên. ",
  "mn51:1.5": "Đứng một bên, du sĩ Kandarakaka nhìn khắp chúng Tỳ-kheo đang im lặng, im lặng, rồi bạch Thế Tôn: ",
  "mn51:2.1": "“Lạ lùng thay, này Gotama, phi thường thay, này Gotama. ",
  "mn51:2.2": "Thật là khéo léo, này Gotama, Thế Tôn đã hướng dẫn chúng Tỳ-kheo. ",
  "mn51:2.3": "Những vị A-la-hán, Chánh Đẳng Giác trong quá khứ, này Gotama, các vị Thế Tôn ấy cũng đã hướng dẫn chúng Tỳ-kheo đến mức độ này—",
  "mn51:2.4": "như hiện nay, này Gotama, Thế Tôn đã hướng dẫn chúng Tỳ-kheo. ",
  "mn51:2.5": "Những vị A-la-hán, Chánh Đẳng Giác trong tương lai, này Gotama, các vị Thế Tôn ấy cũng sẽ hướng dẫn chúng Tỳ-kheo đến mức độ này—",
  "mn51:2.6": "như hiện nay, này Gotama, Thế Tôn đã hướng dẫn chúng Tỳ-kheo.” ",
  "mn51:3.1": "“Đúng vậy, này Kandarakaka, đúng vậy, này Kandarakaka. ",
  "mn51:3.2": "Những vị A-la-hán, Chánh Đẳng Giác trong quá khứ, này Kandarakaka, các vị Thế Tôn ấy cũng đã hướng dẫn chúng Tỳ-kheo đến mức độ này—",
  "mn51:3.3": "như hiện nay Ta đã hướng dẫn chúng Tỳ-kheo. ",
  "mn51:3.4": "Những vị A-la-hán, Chánh Đẳng Giác trong tương lai, này Kandarakaka, các vị Thế Tôn ấy cũng sẽ hướng dẫn chúng Tỳ-kheo đến mức độ này—",
  "mn51:3.5": "như hiện nay Ta đã hướng dẫn chúng Tỳ-kheo. ",
  "mn51:3.6": "Thật vậy, này Kandarakaka, trong chúng Tỳ-kheo này có những Tỳ-kheo là A-la-hán, các lậu hoặc đã tận, đã sống Phạm hạnh, đã làm những việc cần làm, đã đặt gánh nặng xuống, đã đạt được mục đích của mình, đã đoạn tận các kiết sử của đời sống, đã được giải thoát nhờ chánh trí. ",
  "mn51:3.7": "Thật vậy, này Kandarakaka, trong chúng Tỳ-kheo này có những Tỳ-kheo còn là bậc Hữu học, giới hạnh liên tục, hành xử liên tục, khéo léo, hành xử khéo léo; ",
  "mn51:3.8": "các vị ấy sống với tâm an trú vững chắc trên bốn niệm xứ. ",
  "mn51:3.9": "Trên bốn niệm xứ nào? ",
  "mn51:3.10": "Ở đây, này Kandarakaka, Tỳ-kheo sống quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời; ",
  "mn51:3.11": "sống quán thọ trên các thọ, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời; ",
  "mn51:3.12": "sống quán tâm trên tâm, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời; ",
  "mn51:3.13": "sống quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời.” ",
  "mn51:4.1": "Khi được nói vậy, Pessa, con người huấn luyện voi, bạch Thế Tôn: ",
  "mn51:4.2": "“Lạ lùng thay, bạch Thế Tôn, phi thường thay, bạch Thế Tôn. ",
  "mn51:4.3": "Thật là khéo léo, bạch Thế Tôn, bốn niệm xứ này đã được Thế Tôn thuyết giảng để làm thanh tịnh chúng sinh, để vượt qua sầu bi, để diệt trừ khổ ưu, để đạt được chánh trí, để chứng ngộ Niết-bàn. ",
  "mn51:4.4": "Thật vậy, bạch Thế Tôn, chúng con là cư sĩ mặc áo trắng, thỉnh thoảng cũng sống với tâm an trú vững chắc trên bốn niệm xứ này. ",
  "mn51:4.5": "Ở đây, bạch Thế Tôn, chúng con sống quán thân trên thân, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời; ",
  "mn51:4.6": "sống quán thọ trên các thọ, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời; ",
  "mn51:4.7": "sống quán tâm trên tâm, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời; ",
  "mn51:4.8": "sống quán pháp trên các pháp, nhiệt tâm, tỉnh giác, chánh niệm, nhiếp phục tham ưu ở đời. ",
  "mn51:4.9": "Lạ lùng thay, bạch Thế Tôn, phi thường thay, bạch Thế Tôn. ",
  "mn51:4.10": "Thật vậy, bạch Thế Tôn, Thế Tôn biết được lợi hại của chúng sinh khi họ đang sống trong sự phức tạp của con người, trong sự dơ bẩn của con người, trong sự lừa dối của con người. ",
  "mn51:4.11": "Thật vậy, bạch Thế Tôn, con người là phức tạp; ",
  "mn51:4.12": "thật vậy, bạch Thế Tôn, loài vật là đơn giản. ",
  "mn51:4.13": "Thật vậy, bạch Thế Tôn, con có thể huấn luyện voi. ",
  "mn51:4.14": "Trong khoảng thời gian nó đi đi về về Campā, nó sẽ bộc lộ tất cả những sự lừa dối, gian xảo, quanh co, xảo trá của nó. ",
  "mn51:4.15": "Nhưng, bạch Thế Tôn, những người nô lệ, người làm công, người giúp việc của chúng con, họ hành động bằng thân một cách khác, bằng lời nói một cách khác, và tâm của họ cũng khác. ",
  "mn51:4.16": "Lạ lùng thay, bạch Thế Tôn, phi thường thay, bạch Thế Tôn. ",
  "mn51:4.17": "Thật vậy, bạch Thế Tôn, Thế Tôn biết được lợi hại của chúng sinh khi họ đang sống trong sự phức tạp của con người, trong sự dơ bẩn của con người, trong sự lừa dối của con người. ",
  "mn51:4.18": "Thật vậy, bạch Thế Tôn, con người là phức tạp; ",
  "mn51:4.19": "thật vậy, bạch Thế Tôn, loài vật là đơn giản.” ",
  "mn51:5.1": "“Đúng vậy, này Pessa, đúng vậy, này Pessa. ",
  "mn51:5.2": "Thật vậy, này Pessa, con người là phức tạp; ",
  "mn51:5.3": "thật vậy, này Pessa, loài vật là đơn giản. ",
  "mn51:5.4": "Này Pessa, có bốn hạng người này hiện hữu, có mặt trên đời. ",
  "mn51:5.5": "Bốn hạng nào? ",
  "mn51:5.6": "Ở đây, này Pessa, có người tự hành hạ mình, chuyên tâm vào việc tự hành hạ mình; ",
  "mn51:5.7": "nhưng ở đây, này Pessa, có người hành hạ người khác, chuyên tâm vào việc hành hạ người khác; ",
  "mn51:5.8": "nhưng ở đây, này Pessa, có người tự hành hạ mình, chuyên tâm vào việc tự hành hạ mình, và hành hạ người khác, chuyên tâm vào việc hành hạ người khác; ",
  "mn51:5.9": "nhưng ở đây, này Pessa, có người không tự hành hạ mình, không chuyên tâm vào việc tự hành hạ mình, không hành hạ người khác, không chuyên tâm vào việc hành hạ người khác. ",
  "mn51:5.10": "Người ấy không tự hành hạ mình, không hành hạ người khác, ngay trong hiện tại đã được mát mẻ, tịch tịnh, an lạc, cảm nhận hạnh phúc, sống với tự ngã như Phạm thiên. ",
  "mn51:5.11": "Trong bốn hạng người này, này Pessa, hạng người nào làm cho tâm ông hoan hỷ?” ",
  "mn51:5.12": "“Bạch Thế Tôn, hạng người tự hành hạ mình, chuyên tâm vào việc tự hành hạ mình, hạng người này không làm cho tâm con hoan hỷ. ",
  "mn51:5.13": "Bạch Thế Tôn, hạng người hành hạ người khác, chuyên tâm vào việc hành hạ người khác, hạng người này cũng không làm cho tâm con hoan hỷ. ",
  "mn51:5.14": "Bạch Thế Tôn, hạng người tự hành hạ mình, chuyên tâm vào việc tự hành hạ mình, và hành hạ người khác, chuyên tâm vào việc hành hạ người khác, hạng người này cũng không làm cho tâm con hoan hỷ. ",
  "mn51:5.15": "Còn hạng người, bạch Thế Tôn, không tự hành hạ mình, không chuyên tâm vào việc tự hành hạ mình, không hành hạ người khác, không chuyên tâm vào việc hành hạ người khác, người ấy không tự hành hạ mình, không hành hạ người khác, ngay trong hiện tại đã được mát mẻ, tịch tịnh, an lạc, cảm nhận hạnh phúc, sống với tự ngã như Phạm thiên—",
  "mn51:5.16": "chính hạng người này làm cho tâm con hoan hỷ.” ",
  "mn51:6.1": "“Nhưng vì sao, này Pessa, ba hạng người này không làm cho tâm ông hoan hỷ?” ",
  "mn51:6.2": "“Bạch Thế Tôn, hạng người tự hành hạ mình, chuyên tâm vào việc tự hành hạ mình, người ấy hành hạ, làm khổ mình, vốn là người ưa thích hạnh phúc, ghét bỏ đau khổ—",
  "mn51:6.3": "vì vậy, hạng người này không làm cho tâm con hoan hỷ. ",
  "mn51:6.4": "Bạch Thế Tôn, hạng người hành hạ người khác, chuyên tâm vào việc hành hạ người khác, người ấy hành hạ, làm khổ người khác, vốn là người ưa thích hạnh phúc, ghét bỏ đau khổ—",
  "mn51:6.5": "vì vậy, hạng người này không làm cho tâm con hoan hỷ. ",
  "mn51:6.6": "Bạch Thế Tôn, hạng người tự hành hạ mình, chuyên tâm vào việc tự hành hạ mình, và hành hạ người khác, chuyên tâm vào việc hành hạ người khác, người ấy hành hạ, làm khổ mình và người khác, vốn là người ưa thích hạnh phúc, ghét bỏ đau khổ—",
  "mn51:6.7": "vì vậy, hạng người này không làm cho tâm con hoan hỷ. ",
  "mn51:6.8": "Còn hạng người, bạch Thế Tôn, không tự hành hạ mình, không chuyên tâm vào việc tự hành hạ mình, không hành hạ người khác, không chuyên tâm vào việc hành hạ người khác, người ấy không tự hành hạ mình, không hành hạ người khác, ngay trong hiện tại đã được mát mẻ, tịch tịnh, an lạc, cảm nhận hạnh phúc, sống với tự ngã như Phạm thiên; ",
  "mn51:6.9": "người ấy không hành hạ, không làm khổ mình và người khác, vốn là người ưa thích hạnh phúc, ghét bỏ đau khổ—",
  "mn51:6.10": "vì vậy, hạng người này làm cho tâm con hoan hỷ. ",
  "mn51:6.11": "Bây giờ, bạch Thế Tôn, chúng con xin đi; ",
  "mn51:6.12": "chúng con có nhiều việc phải làm, nhiều bổn phận.” ",
  "mn51:6.13": "“Này Pessa, bây giờ ông hãy làm những gì ông cho là phải thời.” ",
  "mn51:6.14": "Rồi Pessa, con người huấn luyện voi, hoan hỷ và tùy hỷ với lời Thế Tôn dạy, từ chỗ ngồi đứng dậy, đảnh lễ Thế Tôn, đi nhiễu bên phải rồi ra đi. ",
  "mn51:7.1": "Rồi Thế Tôn, không lâu sau khi Pessa, con người huấn luyện voi, ra đi, gọi các Tỳ-kheo: ",
  "mn51:7.2": "“Này các Tỳ-kheo, Pessa, con người huấn luyện voi, là người trí; ",
  "mn51:7.3": "này các Tỳ-kheo, Pessa, con người huấn luyện voi, là người có đại trí. ",
  "mn51:7.4": "Này các Tỳ-kheo, nếu Pessa, con người huấn luyện voi, ngồi lại một lát cho đến khi Ta phân tích chi tiết bốn hạng người này, thì ông ấy đã được lợi ích lớn. ",
  "mn51:7.5": "Tuy nhiên, này các Tỳ-kheo, chỉ với chừng ấy, Pessa, con người huấn luyện voi, cũng đã được lợi ích lớn.” ",
  "mn51:7.6": "“Bạch Thế Tôn, đã đến lúc, bạch Thiện Thệ, đã đến lúc, ",
  "mn51:7.7": "Thế Tôn nên phân tích chi tiết bốn hạng người này. Sau khi nghe Thế Tôn, các Tỳ-kheo sẽ ghi nhớ.” ",
  "mn51:7.8": "“Vậy thì, này các Tỳ-kheo, hãy lắng nghe, hãy chú ý kỹ, Ta sẽ nói.” ",
  "mn51:7.9": "“Vâng, bạch Thế Tôn,” các Tỳ-kheo ấy vâng lời Thế Tôn. ",
  "mn51:7.10": "Thế Tôn nói như sau: ",
  "mn51:8.1": "“Này các Tỳ-kheo, hạng người nào tự hành hạ mình, chuyên tâm vào việc tự hành hạ mình? Ở đây, này các Tỳ-kheo, có người sống trần truồng, hành xử phóng túng, liếm tay, không đến khi được mời, không đứng lại khi được mời; không nhận thức ăn mang đến, không nhận thức ăn dành riêng, không nhận thức ăn được mời; ",
  "mn51:8.2": "người ấy không nhận thức ăn từ miệng nồi, không nhận thức ăn từ miệng bát, không nhận thức ăn giữa hai ngưỡng cửa, không nhận thức ăn giữa hai cây gậy, không nhận thức ăn giữa hai người đang ăn, không nhận thức ăn từ người phụ nữ có thai, không nhận thức ăn từ người phụ nữ đang cho con bú, không nhận thức ăn từ người phụ nữ đang có chồng, không nhận thức ăn từ nơi có nhiều người tụ tập, không nhận thức ăn từ nơi có chó đứng, không nhận thức ăn từ nơi có ruồi bay thành đàn; không ăn cá, không ăn thịt, không uống rượu, không uống rượu mạnh, không uống nước gạo. ",
  "mn51:8.3": "Người ấy hoặc chỉ ăn một nhà, một miếng; hoặc ăn hai nhà, hai miếng… hoặc ăn bảy nhà, bảy miếng; ",
  "mn51:8.4": "người ấy sống bằng một lần bố thí, sống bằng hai lần bố thí… hoặc sống bằng bảy lần bố thí; ",
  "mn51:8.5": "người ấy ăn một ngày một bữa, ăn hai ngày một bữa… hoặc ăn bảy ngày một bữa—cứ như vậy, người ấy sống chuyên tâm vào việc ăn uống theo chu kỳ nửa tháng. ",
  "mn51:8.6": "Người ấy hoặc ăn rau, hoặc ăn kê, hoặc ăn lúa hoang, hoặc ăn cám, hoặc ăn bã, hoặc ăn trấu, hoặc ăn nước cháo, hoặc ăn bột đậu, hoặc ăn cỏ, hoặc ăn phân bò; người ấy sống bằng cách ăn rễ cây và trái cây rừng, ăn những trái cây tự rụng. ",
  "mn51:8.7": "Người ấy hoặc mặc vải gai, hoặc mặc vải thô, hoặc mặc vải liệm, hoặc mặc vải nhặt từ đống rác, hoặc mặc vỏ cây, hoặc mặc da thú, hoặc mặc mảnh da thú, hoặc mặc áo bằng cỏ, hoặc mặc áo bằng vỏ cây, hoặc mặc áo bằng ván cây, hoặc mặc áo bằng tóc, hoặc mặc áo bằng lông thú, hoặc mặc áo bằng lông cú; ",
  "mn51:8.8": "người ấy cũng nhổ tóc và râu, chuyên tâm vào việc nhổ tóc và râu, ",
  "mn51:8.9": "người ấy cũng đứng thẳng, từ chối chỗ ngồi, ",
  "mn51:8.10": "người ấy cũng ngồi xổm, chuyên tâm vào việc ngồi xổm, ",
  "mn51:8.11": "người ấy cũng nằm trên giường gai, nằm trên giường gai; ",
  "mn51:8.12": "người ấy cũng sống chuyên tâm vào việc tắm nước ba lần một ngày—",
  "mn51:8.13": "cứ như vậy, người ấy sống chuyên tâm vào nhiều cách hành hạ và làm khổ thân. ",
  "mn51:8.14": "Này các Tỳ-kheo, hạng người này được gọi là tự hành hạ mình, chuyên tâm vào việc tự hành hạ mình. ",
  "mn51:9.1": "Này các Tỳ-kheo, hạng người nào hành hạ người khác, chuyên tâm vào việc hành hạ người khác? ",
  "mn51:9.2": "Ở đây, này các Tỳ-kheo, có người là người giết cừu, người giết heo, người bắt chim, người săn thú, người đánh cá, kẻ trộm, kẻ giết trộm, người giết bò, người cai ngục, hoặc bất kỳ ai làm những nghề nghiệp tàn ác khác. ",
  "mn51:9.3": "Này các Tỳ-kheo, hạng người này được gọi là hành hạ người khác, chuyên tâm vào việc hành hạ người khác. ",
  "mn51:10.1": "Này các Tỳ-kheo, hạng người nào tự hành hạ mình, chuyên tâm vào việc tự hành hạ mình, và hành hạ người khác, chuyên tâm vào việc hành hạ người khác? ",
  "mn51:10.2": "Ở đây, này các Tỳ-kheo, có người là vua Sát-đế-lợi đã được xức dầu, hoặc là Bà-la-môn đại phú. ",
  "mn51:10.3": "Người ấy cho xây một ngôi nhà hội mới ở phía đông thành phố, cạo tóc và râu, mặc da thú thô, xoa dầu bơ lên thân, gãi lưng bằng sừng nai, rồi đi vào ngôi nhà hội mới cùng với hoàng hậu và vị Bà-la-môn chủ tế. ",
  "mn51:10.4": "Ở đó, người ấy nằm trên nền đất đã được trát bằng cỏ tươi, không có vật ngăn cách. ",
  "mn51:10.5": "Với một con bò cái có con bê cùng màu, sữa từ một vú được vua dùng, sữa từ vú thứ hai được hoàng hậu dùng, sữa từ vú thứ ba được vị Bà-la-môn chủ tế dùng, sữa từ vú thứ tư được dùng để cúng lửa, phần còn lại thì con bê dùng. ",
  "mn51:10.6": "Người ấy nói như sau: ",
  "mn51:10.7": "‘Hãy giết chừng này bò đực để cúng tế, hãy giết chừng này bê đực để cúng tế, hãy giết chừng này bê cái để cúng tế, hãy giết chừng này dê để cúng tế, hãy giết chừng này cừu để cúng tế, hãy giết chừng này ngựa để cúng tế, hãy chặt chừng này cây để làm cột tế, hãy cắt chừng này cỏ để làm thảm tế.’ ",
  "mn51:10.8": "Và những người nô lệ, người làm công, người giúp việc của người ấy, họ bị roi vọt đe dọa, bị sợ hãi đe dọa, mặt đẫm lệ, khóc lóc mà làm các công việc. ",
  "mn51:10.9": "Này các Tỳ-kheo, hạng người này được gọi là tự hành hạ mình, chuyên tâm vào việc tự hành hạ mình, và hành hạ người khác, chuyên tâm vào việc hành hạ người khác. ",
  "mn51:11.1": "Này các Tỳ-kheo, hạng người nào không tự hành hạ mình, không chuyên tâm vào việc tự hành hạ mình, không hành hạ người khác, không chuyên tâm vào việc hành hạ người khác, người ấy không tự hành hạ mình, không hành hạ người khác, ngay trong hiện tại đã được mát mẻ, tịch tịnh, an lạc, cảm nhận hạnh phúc, sống với tự ngã như Phạm thiên? ",
  "mn51:12.1": "Ở đây, này các Tỳ-kheo, một Như Lai xuất hiện trên đời, là bậc A-la-hán, Chánh Đẳng Giác, đầy đủ Minh Hạnh, Thiện Thệ, Thế Gian Giải, Vô Thượng Sĩ, Điều Ngự Trượng Phu, Thiên Nhân Sư, Phật, Thế Tôn. ",
  "mn51:12.2": "Người ấy tự mình chứng ngộ, thực chứng rồi tuyên bố thế giới này cùng với chư Thiên, Ma vương, Phạm thiên, cùng với quần chúng Sa-môn, Bà-la-môn, chư Thiên và loài người. ",
  "mn51:12.3": "Người ấy thuyết giảng giáo pháp tốt đẹp ở phần đầu, tốt đẹp ở phần giữa, tốt đẹp ở phần cuối, có ý nghĩa và có lời lẽ, tuyên bố một đời sống Phạm hạnh hoàn toàn đầy đủ và thanh tịnh. ",
  "mn51:13.1": "Một gia chủ hoặc con của gia chủ, hoặc một người sinh ra trong một gia đình nào đó, nghe giáo pháp ấy. ",
  "mn51:13.2": "Sau khi nghe giáo pháp ấy, người ấy có niềm tin vào Như Lai. ",
  "mn51:13.3": "Người ấy, được niềm tin ấy đầy đủ, suy nghĩ như sau: ",
  "mn51:13.4": "‘Đời sống gia đình là chật chội, là con đường đầy bụi bặm, còn xuất gia là khoảng không rộng mở. ",
  "mn51:13.5": "Thật không dễ dàng cho người sống tại gia để sống một đời Phạm hạnh hoàn toàn đầy đủ, hoàn toàn thanh tịnh, như vỏ ốc được mài nhẵn.’ ",
  "mn51:13.6": "Hay là ta cạo bỏ râu tóc, đắp y cà sa, từ bỏ gia đình, sống không gia đình, xuất gia chăng?",
  "mn51:13.7": "Rồi một thời gian sau, người ấy từ bỏ ít tài sản hay nhiều tài sản, từ bỏ ít bà con hay nhiều bà con, cạo bỏ râu tóc, đắp y cà sa, từ bỏ gia đình, sống không gia đình, xuất gia.",
  "mn51:14.1": "Sau khi xuất gia như vậy, người ấy sống theo giới luật và nếp sống của các tỳ khưu, từ bỏ sát sinh, tránh xa sát sinh, đặt gậy xuống, đặt kiếm xuống, biết hổ thẹn, có lòng từ bi, sống thương xót tất cả chúng sinh.",
  "mn51:14.2": "Từ bỏ trộm cắp, tránh xa trộm cắp, chỉ nhận những gì được cho, mong đợi những gì được cho, sống trong sạch, không trộm cắp.",
  "mn51:14.3": "Từ bỏ phi phạm hạnh, sống phạm hạnh, sống xa lánh, tránh xa dâm dục, pháp của làng.",
  "mn51:14.4": "Từ bỏ nói dối, tránh xa nói dối, nói lời chân thật, giữ lời chân thật, đáng tin cậy, đáng tin, không lừa dối thế gian.",
  "mn51:14.5": "Từ bỏ lời nói chia rẽ, tránh xa lời nói chia rẽ, nghe điều này không nói với người kia để gây chia rẽ cho những người này, hay nghe điều kia không nói với người này để gây chia rẽ cho những người kia—như vậy, người ấy hòa giải những người chia rẽ, khuyến khích những người hòa hợp, thích hòa hợp, vui thích hòa hợp, hoan hỷ hòa hợp, nói lời làm cho hòa hợp.",
  "mn51:14.6": "Từ bỏ lời nói thô tục, tránh xa lời nói thô tục, người ấy nói lời dịu dàng, dễ nghe, đáng yêu, đi vào lòng người, lịch sự, được nhiều người ưa thích, được nhiều người hoan hỷ.",
  "mn51:14.7": "Từ bỏ lời nói vô ích, tránh xa lời nói vô ích, nói đúng lúc, nói đúng sự thật, nói có ý nghĩa, nói về Chánh pháp, nói về Giới luật, nói lời đáng ghi nhớ, đúng lúc, có lý do, có giới hạn, có lợi ích.",
  "mn51:14.8": "Người ấy tránh xa việc làm tổn hại đến hạt giống và cây cối,",
  "mn51:14.9": "chỉ ăn một bữa, tránh xa ăn phi thời, không ăn vào ban đêm;",
  "mn51:14.10": "tránh xa xem múa, hát, nhạc và các trò giải trí;",
  "mn51:14.11": "tránh xa việc đeo vòng hoa, dùng hương liệu, thoa dầu, trang sức và làm đẹp;",
  "mn51:14.12": "tránh xa giường cao, chỗ nằm lớn;",
  "mn51:14.13": "tránh xa việc nhận vàng bạc;",
  "mn51:14.14": "tránh xa việc nhận ngũ cốc sống;",
  "mn51:14.15": "tránh xa việc nhận thịt sống;",
  "mn51:14.16": "tránh xa việc nhận phụ nữ và trẻ em gái;",
  "mn51:14.17": "tránh xa việc nhận nô tỳ nam nữ;",
  "mn51:14.18": "tránh xa việc nhận dê và cừu;",
  "mn51:14.19": "tránh xa việc nhận gà và heo;",
  "mn51:14.20": "tránh xa việc nhận voi, bò, ngựa và ngựa cái;",
  "mn51:14.21": "tránh xa việc nhận ruộng đất;",
  "mn51:14.22": "tránh xa việc làm sứ giả, đi lại sai vặt;",
  "mn51:14.23": "tránh xa việc mua bán;",
  "mn51:14.24": "tránh xa việc cân lường gian lận, đong đếm gian lận;",
  "mn51:14.25": "tránh xa việc hối lộ, lừa đảo, gian lận, mánh khóe;",
  "mn51:14.26": "tránh xa việc cắt xén, giết hại, trói buộc, cướp bóc, trấn lột, bạo hành.",
  "mn51:15.1": "Người ấy biết đủ với y phục che thân, với đồ ăn khất thực nuôi bụng. Người ấy đi đâu cũng mang theo (những thứ đó).",
  "mn51:15.2": "Ví như chim chóc, bay đi đâu cũng chỉ mang theo đôi cánh của mình;",
  "mn51:15.3": "cũng vậy, vị tỳ khưu biết đủ với y phục che thân, với đồ ăn khất thực nuôi bụng. Người ấy đi đâu cũng mang theo (những thứ đó).",
  "mn51:15.4": "Người ấy, với giới hạnh cao thượng này, cảm nhận được niềm vui không lỗi lầm trong nội tâm.",
  "mn51:16.1": "Người ấy, khi thấy sắc bằng mắt, không nắm giữ tướng chung, không nắm giữ tướng riêng.",
  "mn51:16.2": "Vì nếu nhãn căn không được hộ trì, khi sống không hộ trì, những pháp ác bất thiện như tham lam và ưu phiền sẽ xâm nhập, nên người ấy thực hành để hộ trì, bảo vệ nhãn căn, chế ngự nhãn căn.",
  "mn51:16.3": "Khi nghe tiếng bằng tai…v.v…",
  "mn51:16.4": "Khi ngửi mùi bằng mũi…v.v…",
  "mn51:16.5": "Khi nếm vị bằng lưỡi…v.v…",
  "mn51:16.6": "Khi xúc chạm bằng thân…v.v…",
  "mn51:16.7": "Khi nhận biết pháp bằng ý, không nắm giữ tướng chung, không nắm giữ tướng riêng.",
  "mn51:16.8": "Vì nếu ý căn không được hộ trì, khi sống không hộ trì, những pháp ác bất thiện như tham lam và ưu phiền sẽ xâm nhập, nên người ấy thực hành để hộ trì, bảo vệ ý căn, chế ngự ý căn.",
  "mn51:16.9": "Người ấy, với sự chế ngự các căn cao thượng này, cảm nhận được niềm vui không bị quấy nhiễu trong nội tâm.",
  "mn51:17.1": "Người ấy, khi đi tới, khi đi lui, đều tỉnh giác; khi nhìn thẳng, khi nhìn quanh, đều tỉnh giác; khi co tay, khi duỗi tay, đều tỉnh giác; khi mang y tăng-già-lê, bát, y, đều tỉnh giác; khi ăn, khi uống, khi nhai, khi nếm, đều tỉnh giác; khi đại tiện, khi tiểu tiện, đều tỉnh giác; khi đi, khi đứng, khi ngồi, khi ngủ, khi thức, khi nói, khi im lặng, đều tỉnh giác.",
  "mn51:18.1": "Người ấy, với giới hạnh cao thượng này, với sự biết đủ cao thượng này, với sự chế ngự các căn cao thượng này, và với chánh niệm tỉnh giác cao thượng này",
  "mn51:18.2": "tìm đến chỗ ở vắng vẻ: rừng, gốc cây, núi, khe núi, hang đá, nghĩa địa, rừng cây, khoảng đất trống, đống rơm.",
  "mn51:19.1": "Sau bữa ăn, sau khi đi khất thực về, người ấy ngồi kiết già, thân thẳng, thiết lập chánh niệm trước mặt.",
  "mn51:19.2": "Người ấy từ bỏ tham lam trong đời, sống với tâm không tham lam, làm cho tâm thanh tịnh khỏi tham lam,",
  "mn51:19.3": "từ bỏ sân hận và ác ý, sống với tâm không sân hận, thương xót tất cả chúng sinh, làm cho tâm thanh tịnh khỏi sân hận và ác ý;",
  "mn51:19.4": "từ bỏ hôn trầm và thụy miên, sống không hôn trầm và thụy miên, có tưởng ánh sáng, chánh niệm, tỉnh giác, làm cho tâm thanh tịnh khỏi hôn trầm và thụy miên;",
  "mn51:19.5": "từ bỏ trạo cử và hối hận, sống không trạo cử, tâm an tịnh nội tại, làm cho tâm thanh tịnh khỏi trạo cử và hối hận;",
  "mn51:19.6": "từ bỏ nghi ngờ, sống vượt qua nghi ngờ, không do dự về các pháp thiện, làm cho tâm thanh tịnh khỏi nghi ngờ.",
  "mn51:20.1": "Người ấy từ bỏ năm triền cái này, những cấu uế của tâm, làm suy yếu trí tuệ,",
  "mn51:20.2": "ly dục, ly bất thiện pháp, chứng và trú thiền thứ nhất, có tầm có tứ, do ly dục sinh hỷ lạc;",
  "mn51:21.1": "diệt tầm diệt tứ, nội tĩnh nhất tâm, chứng và trú thiền thứ hai, không tầm không tứ, do định sinh hỷ lạc;",
  "mn51:22.1": "ly hỷ, sống xả, chánh niệm, tỉnh giác, thân cảm thọ lạc, mà các bậc Thánh gọi là: ‘người sống xả, chánh niệm, an lạc’—chứng và trú thiền thứ ba;",
  "mn51:23.1": "xả lạc xả khổ, trước đã diệt hỷ ưu, chứng và trú thiền thứ tư, không khổ không lạc, xả niệm thanh tịnh.",
  "mn51:24.1": "Với tâm định tĩnh như vậy, thanh tịnh, trong sáng, không cấu uế, không phiền não, mềm mại, dễ sử dụng, vững chắc, bất động, người ấy hướng tâm đến túc mạng trí.",
  "mn51:24.2": "Người ấy nhớ lại nhiều đời sống quá khứ khác nhau, như là—một đời, hai đời, ba đời, bốn đời, năm đời, mười đời, hai mươi đời, ba mươi đời, bốn mươi đời, năm mươi đời, một trăm đời, một ngàn đời, một trăm ngàn đời, nhiều kiếp hoại, nhiều kiếp thành, nhiều kiếp hoại và thành: ‘Ta đã từng ở chỗ kia, tên như thế này, dòng họ như thế này, màu da như thế này, ăn uống như thế này, cảm thọ khổ lạc như thế này, tuổi thọ như thế này. Từ đó chết đi, ta sinh vào chỗ kia; ở đó ta tên như thế này, dòng họ như thế này, màu da như thế này, ăn uống như thế này, cảm thọ khổ lạc như thế này, tuổi thọ như thế này. Từ đó chết đi, ta sinh vào đây’. Như vậy, người ấy nhớ lại nhiều đời sống quá khứ khác nhau với đầy đủ chi tiết và đặc điểm.",
  "mn51:25.1": "Với tâm định tĩnh như vậy, thanh tịnh, trong sáng, không cấu uế, không phiền não, mềm mại, dễ sử dụng, vững chắc, bất động, người ấy hướng tâm đến trí tuệ về sự chết và tái sinh của chúng sinh.",
  "mn51:25.2": "Người ấy, với thiên nhãn thanh tịnh, siêu việt hơn mắt người, thấy chúng sinh chết đi, sinh lại, thấp hèn, cao quý, đẹp đẽ, xấu xí, may mắn, bất hạnh, biết rõ chúng sinh tùy theo nghiệp của họ: ‘Ôi, những chúng sinh này đã làm ác bằng thân, làm ác bằng lời, làm ác bằng ý, phỉ báng các bậc Thánh, có tà kiến, chấp giữ tà kiến, sau khi thân hoại mạng chung, họ sinh vào cõi dữ, ác thú, đọa xứ, địa ngục; còn những chúng sinh này đã làm thiện bằng thân, làm thiện bằng lời, làm thiện bằng ý, không phỉ báng các bậc Thánh, có chánh kiến, chấp giữ chánh kiến, sau khi thân hoại mạng chung, họ sinh vào cõi lành, thiên giới’. Như vậy, với thiên nhãn thanh tịnh, siêu việt hơn mắt người, người ấy thấy chúng sinh chết đi, sinh lại, thấp hèn, cao quý, đẹp đẽ, xấu xí, may mắn, bất hạnh, biết rõ chúng sinh tùy theo nghiệp của họ.",
  "mn51:26.1": "Với tâm định tĩnh như vậy, thanh tịnh, trong sáng, không cấu uế, không phiền não, mềm mại, dễ sử dụng, vững chắc, bất động, người ấy hướng tâm đến trí tuệ diệt trừ các lậu hoặc.",
  "mn51:26.2": "Người ấy biết rõ ‘Đây là khổ’ như thật. Người ấy biết rõ ‘Đây là nguyên nhân của khổ’ như thật. Người ấy biết rõ ‘Đây là sự diệt khổ’ như thật. Người ấy biết rõ ‘Đây là con đường đưa đến sự diệt khổ’ như thật.",
  "mn51:27.1": "Người ấy biết rõ ‘Đây là các lậu hoặc’ như thật. Người ấy biết rõ ‘Đây là nguyên nhân của các lậu hoặc’ như thật. Người ấy biết rõ ‘Đây là sự diệt trừ các lậu hoặc’ như thật. Người ấy biết rõ ‘Đây là con đường đưa đến sự diệt trừ các lậu hoặc’ như thật.",
  "mn51:27.2": "Khi người ấy biết như vậy, thấy như vậy, tâm người ấy giải thoát khỏi lậu hoặc dục, tâm người ấy giải thoát khỏi lậu hoặc hữu, tâm người ấy giải thoát khỏi lậu hoặc vô minh.",
  "mn51:27.3": "Khi giải thoát, người ấy biết mình đã giải thoát.",
  "mn51:27.4": "‘Sanh đã tận, phạm hạnh đã thành, việc cần làm đã làm, không còn trở lại trạng thái này nữa’—người ấy biết rõ.",
  "mn51:28.1": "Này các tỳ khưu, người này được gọi là không tự hành khổ, không chuyên tâm vào việc tự hành khổ, không hành khổ người khác, không chuyên tâm vào việc hành khổ người khác.",
  "mn51:28.2": "Người ấy không tự hành khổ, không hành khổ người khác, ngay trong hiện tại đã được tịch tịnh, niết bàn, mát mẻ, cảm nhận được an lạc, sống với tự ngã đã trở thành Phạm thiên.”",
  "mn51:28.3": "Đức Thế Tôn đã nói điều này.",
  "mn51:28.4": "Các tỳ khưu ấy hoan hỷ, tán thán lời Đức Thế Tôn đã nói.",
  "mn51:28.5": "Kinh Kandarakasutta, phần thứ nhất, đã chấm dứt."
}
window.BILARA["mn51"]["vi"]["mn51:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
