window.BILARA = window.BILARA || {};
window.BILARA["mn59"] = window.BILARA["mn59"] || {};
window.BILARA["mn59"]["vi"] = {
  "mn59:0.1": "Trung Bộ Kinh 59 ",
  "mn59:0.2": "Kinh Nhiều Cảm Thọ ",
  "mn59:1.1": "Tôi nghe như vầy—",
  "mn59:1.2": "Một thời Thế Tôn trú ở Sāvatthī, tại Jetavana, khu vườn của Anāthapiṇḍika. ",
  "mn59:1.3": "Rồi gia chủ Pañcakaṅga đi đến chỗ Tôn giả Udāyī; sau khi đến, đảnh lễ Tôn giả Udāyī rồi ngồi xuống một bên. Ngồi xuống một bên, gia chủ Pañcakaṅga nói với Tôn giả Udāyī: ",
  "mn59:1.4": "“Bạch Tôn giả Udāyī, Thế Tôn đã nói có bao nhiêu cảm thọ?” ",
  "mn59:1.5": "“Này gia chủ, Thế Tôn đã nói có ba cảm thọ. ",
  "mn59:1.6": "Cảm thọ lạc, cảm thọ khổ, cảm thọ không khổ không lạc—",
  "mn59:1.7": "Này gia chủ, Thế Tôn đã nói có ba cảm thọ này.” ",
  "mn59:1.8": "Khi được nói vậy, gia chủ Pañcakaṅga nói với Tôn giả Udāyī: ",
  "mn59:1.9": "“Bạch Tôn giả Udāyī, Thế Tôn đã không nói có ba cảm thọ; ",
  "mn59:1.10": "Thế Tôn đã nói có hai cảm thọ—",
  "mn59:1.11": "cảm thọ lạc, cảm thọ khổ. ",
  "mn59:1.12": "Bạch Tôn giả, cái cảm thọ không khổ không lạc này, Thế Tôn đã nói là lạc cao thượng trong sự an tịnh.” ",
  "mn59:2.1": "Lần thứ hai, Tôn giả Udāyī nói với gia chủ Pañcakaṅga: ",
  "mn59:2.2": "“Này gia chủ, Thế Tôn đã không nói có hai cảm thọ; ",
  "mn59:2.3": "Thế Tôn đã nói có ba cảm thọ. ",
  "mn59:2.4": "Cảm thọ lạc, cảm thọ khổ, cảm thọ không khổ không lạc—",
  "mn59:2.5": "Này gia chủ, Thế Tôn đã nói có ba cảm thọ này.” ",
  "mn59:2.6": "Lần thứ hai, gia chủ Pañcakaṅga nói với Tôn giả Udāyī: ",
  "mn59:2.7": "“Bạch Tôn giả Udāyī, Thế Tôn đã không nói có ba cảm thọ; ",
  "mn59:2.8": "Thế Tôn đã nói có hai cảm thọ—",
  "mn59:2.9": "cảm thọ lạc, cảm thọ khổ. ",
  "mn59:2.10": "Bạch Tôn giả, cái cảm thọ không khổ không lạc này, Thế Tôn đã nói là lạc cao thượng trong sự an tịnh.” ",
  "mn59:3.1": "Lần thứ ba, Tôn giả Udāyī nói với gia chủ Pañcakaṅga: ",
  "mn59:3.2": "“Này gia chủ, Thế Tôn đã không nói có hai cảm thọ; ",
  "mn59:3.3": "Thế Tôn đã nói có ba cảm thọ. ",
  "mn59:3.4": "Cảm thọ lạc, cảm thọ khổ, cảm thọ không khổ không lạc—",
  "mn59:3.5": "Này gia chủ, Thế Tôn đã nói có ba cảm thọ này.” ",
  "mn59:3.6": "Lần thứ ba, gia chủ Pañcakaṅga nói với Tôn giả Udāyī: ",
  "mn59:3.7": "“Bạch Tôn giả Udāyī, Thế Tôn đã không nói có ba cảm thọ, ",
  "mn59:3.8": "Thế Tôn đã nói có hai cảm thọ—",
  "mn59:3.9": "cảm thọ lạc, cảm thọ khổ. ",
  "mn59:3.10": "Bạch Tôn giả, cái cảm thọ không khổ không lạc này, Thế Tôn đã nói là lạc cao thượng trong sự an tịnh.” ",
  "mn59:3.11": "Tôn giả Udāyī không thể thuyết phục gia chủ Pañcakaṅga, và gia chủ Pañcakaṅga cũng không thể thuyết phục Tôn giả Udāyī. ",
  "mn59:4.1": "Tôn giả Ānanda nghe cuộc nói chuyện này giữa Tôn giả Udāyī và gia chủ Pañcakaṅga. ",
  "mn59:4.2": "Rồi Tôn giả Ānanda đi đến chỗ Thế Tôn; sau khi đến, đảnh lễ Thế Tôn rồi ngồi xuống một bên. ",
  "mn59:4.3": "Ngồi xuống một bên, Tôn giả Ānanda kể lại tất cả cuộc nói chuyện giữa Tôn giả Udāyī và gia chủ Pañcakaṅga cho Thế Tôn nghe. ",
  "mn59:4.4": "Khi được nói vậy, Thế Tôn nói với Tôn giả Ānanda: ",
  "mn59:5.1": "“Này Ānanda, gia chủ Pañcakaṅga đã không chấp nhận cách nói của Udāyī, và Udāyī cũng đã không chấp nhận cách nói của gia chủ Pañcakaṅga. ",
  "mn59:5.2": "Này Ānanda, Ta đã nói có hai cảm thọ theo một cách, Ta cũng đã nói có ba cảm thọ theo một cách, Ta cũng đã nói có năm cảm thọ theo một cách, Ta cũng đã nói có sáu cảm thọ theo một cách, Ta cũng đã nói có mười tám cảm thọ theo một cách, Ta cũng đã nói có ba mươi sáu cảm thọ theo một cách, Ta cũng đã nói có một trăm lẻ tám cảm thọ theo một cách. ",
  "mn59:5.3": "Này Ānanda, Pháp do Ta thuyết giảng theo nhiều cách như vậy. ",
  "mn59:5.4": "Này Ānanda, trong Pháp do Ta thuyết giảng theo nhiều cách như vậy, những ai không chấp nhận, không tán thành, không hoan hỷ lời nói hay, lời nói khéo của nhau, thì điều này có thể xảy ra cho họ—họ sẽ sống trong tranh cãi, cãi vã, bất đồng, đâm chọc nhau bằng những mũi tên miệng lưỡi. ",
  "mn59:5.5": "Này Ānanda, Pháp do Ta thuyết giảng theo nhiều cách như vậy. ",
  "mn59:5.6": "Này Ānanda, trong Pháp do Ta thuyết giảng theo nhiều cách như vậy, những ai chấp nhận, tán thành, hoan hỷ lời nói hay, lời nói khéo của nhau, thì điều này có thể xảy ra cho họ—họ sẽ sống hòa hợp, vui vẻ, không tranh cãi, như sữa với nước, nhìn nhau bằng con mắt yêu thương. ",
  "mn59:6.1": "Này Ānanda, có năm dục công đức này. ",
  "mn59:6.2": "Năm nào? ",
  "mn59:6.3": "Sắc do mắt nhận biết, khả ái, khả hỷ, khả lạc, khả ái hình sắc, liên hệ đến dục, hấp dẫn; ",
  "mn59:6.4": "tiếng do tai nhận biết …pe… ",
  "mn59:6.5": "hương do mũi nhận biết …pe… ",
  "mn59:6.6": "vị do lưỡi nhận biết …pe… ",
  "mn59:6.7": "xúc do thân nhận biết, khả ái, khả hỷ, khả lạc, khả ái hình sắc, liên hệ đến dục, hấp dẫn—",
  "mn59:6.8": "Này Ānanda, đây là năm dục công đức. ",
  "mn59:6.9": "Này Ānanda, cái lạc và hỷ phát sinh do duyên năm dục công đức này, đó gọi là dục lạc. ",
  "mn59:7.1": "Này Ānanda, nếu ai nói rằng: ‘Chúng sinh chỉ cảm nhận lạc và hỷ đến mức này thôi’, thì Ta không chấp nhận điều đó. ",
  "mn59:7.2": "Vì sao? ",
  "mn59:7.3": "Này Ānanda, có một lạc khác cao thượng hơn và vi diệu hơn lạc này. ",
  "mn59:7.4": "Và này Ānanda, lạc nào khác cao thượng hơn và vi diệu hơn lạc này? ",
  "mn59:7.5": "Ở đây, này Ānanda, Tỳ-kheo ly dục, ly bất thiện pháp …pe… chứng và trú Thiền thứ nhất. ",
  "mn59:7.6": "Này Ānanda, đây là một lạc khác cao thượng hơn và vi diệu hơn lạc này. ",
  "mn59:8.1": "Này Ānanda, nếu ai nói rằng: ‘Chúng sinh chỉ cảm nhận lạc và hỷ đến mức này thôi’, thì Ta không chấp nhận điều đó. ",
  "mn59:8.2": "Vì sao? ",
  "mn59:8.3": "Này Ānanda, có một lạc khác cao thượng hơn và vi diệu hơn lạc này. ",
  "mn59:8.4": "Và này Ānanda, lạc nào khác cao thượng hơn và vi diệu hơn lạc này? ",
  "mn59:8.5": "Ở đây, này Ānanda, Tỳ-kheo diệt tầm và tứ …pe… chứng và trú Thiền thứ hai. ",
  "mn59:8.6": "Này Ānanda, đây là một lạc khác cao thượng hơn và vi diệu hơn lạc này. ",
  "mn59:9.1": "Này Ānanda, nếu ai nói rằng … ",
  "mn59:9.2": "pe…. ",
  "mn59:9.3": "Và này Ānanda, lạc nào khác cao thượng hơn và vi diệu hơn lạc này? ",
  "mn59:9.4": "Ở đây, này Ānanda, Tỳ-kheo ly hỷ …pe… chứng và trú Thiền thứ ba. ",
  "mn59:9.5": "Này Ānanda, đây là một lạc khác cao thượng hơn và vi diệu hơn lạc này. ",
  "mn59:10.1": "Này Ānanda, nếu ai nói rằng … ",
  "mn59:10.2": "pe…. ",
  "mn59:10.3": "Và này Ānanda, lạc nào khác cao thượng hơn và vi diệu hơn lạc này? ",
  "mn59:10.4": "Ở đây, này Ānanda, Tỳ-kheo xả lạc …pe… chứng và trú Thiền thứ tư. ",
  "mn59:10.5": "Này Ānanda, đây là một lạc khác cao thượng hơn và vi diệu hơn lạc này. ",
  "mn59:11.1": "Này Ānanda, nếu ai nói rằng … ",
  "mn59:11.2": "pe…. ",
  "mn59:11.3": "Và này Ānanda, lạc nào khác cao thượng hơn và vi diệu hơn lạc này? ",
  "mn59:11.4": "Ở đây, này Ānanda, Tỳ-kheo hoàn toàn vượt qua các tưởng về sắc, các tưởng về đối ngại diệt mất, không tác ý các tưởng về sai biệt, với ý nghĩ ‘không gian là vô biên’, chứng và trú Không vô biên xứ. ",
  "mn59:11.5": "Này Ānanda, đây là một lạc khác cao thượng hơn và vi diệu hơn lạc này. ",
  "mn59:12.1": "Này Ānanda, nếu ai nói rằng … ",
  "mn59:12.2": "pe…. ",
  "mn59:12.3": "Và này Ānanda, lạc nào khác cao thượng hơn và vi diệu hơn lạc này? ",
  "mn59:12.4": "Ở đây, này Ānanda, Tỳ-kheo hoàn toàn vượt qua Không vô biên xứ, với ý nghĩ ‘thức là vô biên’, chứng và trú Thức vô biên xứ. ",
  "mn59:12.5": "Này Ānanda, đây là một lạc khác cao thượng hơn và vi diệu hơn lạc này. ",
  "mn59:13.1": "Này Ānanda, nếu ai nói rằng … ",
  "mn59:13.2": "pe…. ",
  "mn59:13.3": "Và này Ānanda, lạc nào khác cao thượng hơn và vi diệu hơn lạc này? ",
  "mn59:13.4": "Ở đây, này Ānanda, Tỳ-kheo hoàn toàn vượt qua Thức vô biên xứ, với ý nghĩ ‘không có gì cả’, chứng và trú Vô sở hữu xứ. ",
  "mn59:13.5": "Này Ānanda, đây là một lạc khác cao thượng hơn và vi diệu hơn lạc này. ",
  "mn59:14.1": "Này Ānanda, nếu ai nói rằng … ",
  "mn59:14.2": "pe…. ",
  "mn59:14.3": "Và này Ānanda, lạc nào khác cao thượng hơn và vi diệu hơn lạc này? ",
  "mn59:14.4": "Ở đây, này Ānanda, Tỳ-kheo hoàn toàn vượt qua Vô sở hữu xứ, chứng và trú Phi tưởng phi phi tưởng xứ. ",
  "mn59:14.5": "Này Ānanda, đây là một lạc khác cao thượng hơn và vi diệu hơn lạc này. ",
  "mn59:15.1": "Này Ānanda, nếu ai nói rằng: ‘Chúng sinh chỉ cảm nhận lạc và hỷ đến mức này thôi’, thì Ta không chấp nhận điều đó. ",
  "mn59:15.2": "Vì sao? ",
  "mn59:15.3": "Này Ānanda, có một lạc khác cao thượng hơn và vi diệu hơn lạc này. ",
  "mn59:15.4": "Và này Ānanda, lạc nào khác cao thượng hơn và vi diệu hơn lạc này? ",
  "mn59:15.5": "Ở đây, này Ānanda, Tỳ-kheo hoàn toàn vượt qua Phi tưởng phi phi tưởng xứ, chứng và trú Diệt thọ tưởng định. ",
  "mn59:15.6": "Này Ānanda, đây là một lạc khác cao thượng hơn và vi diệu hơn lạc này. ",
  "mn59:16.1": "Này Ānanda, có trường hợp các du sĩ ngoại đạo có thể nói như vầy: ",
  "mn59:16.2": "‘Sa-môn Gotama nói về Diệt thọ tưởng định; và Ngài tuyên bố đó là lạc. ",
  "mn59:16.3": "Điều này là gì, điều này như thế nào?’ ",
  "mn59:16.4": "Này Ānanda, khi các du sĩ ngoại đạo nói như vậy, họ nên được trả lời như sau: ",
  "mn59:16.5": "‘Này các bạn, Thế Tôn không phải chỉ nói về cảm thọ lạc mà tuyên bố đó là lạc; ",
  "mn59:16.6": "mà này các bạn, bất cứ nơi nào có lạc được tìm thấy, ở đâu có lạc, Như Lai tuyên bố đó là lạc.’” ",
  "mn59:16.7": "Thế Tôn đã nói như vậy. ",
  "mn59:16.8": "Tôn giả Ānanda hoan hỷ, tùy hỷ lời Thế Tôn dạy. ",
  "mn59:16.9": "Kinh Nhiều Cảm Thọ, thứ chín, chấm dứt. "
}
window.BILARA["mn59"]["vi"]["mn59:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
