window.BILARA = window.BILARA || {};
window.BILARA["mn69"] = window.BILARA["mn69"] || {};
window.BILARA["mn69"]["vi"] = {
  "mn69:0.1": "Trung Bộ Kinh 69 ",
  "mn69:0.2": "Kinh Goliyāni ",
  "mn69:1.1": "Tôi nghe như vầy—",
  "mn69:1.2": "Một thời Thế Tôn trú ở Rājagaha (Vương Xá), tại Veluvana (Trúc Lâm), chỗ nuôi dưỡng sóc. ",
  "mn69:2.1": "Lúc bấy giờ, Tôn giả Goliyāni, một tỳ kheo sống ở rừng, có hạnh đầu đà, vì một việc gì đó mà đến ở giữa Tăng chúng. ",
  "mn69:2.2": "Tại đấy, Tôn giả Sāriputta (Xá Lợi Phất) nhân Tỳ kheo Goliyāni mà gọi các Tỳ kheo: ",
  "mn69:3.1": "“Này các bạn, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, phải có lòng kính trọng, có lòng tôn kính đối với các bạn đồng phạm hạnh. ",
  "mn69:3.2": "Này các bạn, nếu một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng mà không có lòng kính trọng, không có lòng tôn kính đối với các bạn đồng phạm hạnh, thì người ta sẽ nói về vị ấy. ",
  "mn69:3.3": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này không có lòng kính trọng, không có lòng tôn kính đối với các bạn đồng phạm hạnh?’—",
  "mn69:3.4": "Người ta sẽ nói về vị ấy. ",
  "mn69:3.5": "Do vậy, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, phải có lòng kính trọng, có lòng tôn kính đối với các bạn đồng phạm hạnh. ",
  "mn69:4.1": "Này các bạn, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, phải khéo léo trong việc chỗ ngồi: ",
  "mn69:4.2": "‘Ta sẽ không chen lấn các Tỳ kheo lớn tuổi, và sẽ không từ chối chỗ ngồi của các Tỳ kheo mới.’ ",
  "mn69:4.3": "Này các bạn, nếu một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng mà không khéo léo trong việc chỗ ngồi, thì người ta sẽ nói về vị ấy. ",
  "mn69:4.4": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này không khéo léo trong việc chỗ ngồi?’—",
  "mn69:4.5": "Người ta sẽ nói về vị ấy. ",
  "mn69:4.6": "Do vậy, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, phải khéo léo trong việc chỗ ngồi. ",
  "mn69:4.7": "Này các bạn, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, cũng phải biết phép tắc ứng xử. ",
  "mn69:4.8": "Này các bạn, nếu một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng mà không biết phép tắc ứng xử, thì người ta sẽ nói về vị ấy. ",
  "mn69:4.9": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này không biết cả phép tắc ứng xử?’—",
  "mn69:4.10": "Người ta sẽ nói về vị ấy. ",
  "mn69:4.11": "Do vậy, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, cũng phải biết phép tắc ứng xử. ",
  "mn69:5.1": "Này các bạn, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, không nên vào làng quá muộn, không nên trở về quá sớm. ",
  "mn69:5.2": "Này các bạn, nếu một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng mà vào làng quá muộn, trở về quá sớm, thì người ta sẽ nói về vị ấy. ",
  "mn69:5.3": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này vào làng quá muộn, trở về quá sớm?’—",
  "mn69:5.4": "Người ta sẽ nói về vị ấy. ",
  "mn69:5.5": "Do vậy, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, không nên vào làng quá muộn, không nên trở về quá sớm. ",
  "mn69:6.1": "Này các bạn, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, không nên đi lại các gia đình trước bữa ăn và sau bữa ăn. ",
  "mn69:6.2": "Này các bạn, nếu một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng mà đi lại các gia đình trước bữa ăn và sau bữa ăn, thì người ta sẽ nói về vị ấy. ",
  "mn69:6.3": "‘Chắc chắn vị Tôn giả sống ở rừng một mình tự do này đã quen với việc đi lại phi thời, nên khi đến Tăng chúng cũng hành xử như vậy.’—",
  "mn69:6.4": "Người ta sẽ nói về vị ấy. ",
  "mn69:6.5": "Do vậy, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, không nên đi lại các gia đình trước bữa ăn và sau bữa ăn. ",
  "mn69:7.1": "Này các bạn, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, phải không phóng dật, không xao động. ",
  "mn69:7.2": "Này các bạn, nếu một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng mà phóng dật, xao động, thì người ta sẽ nói về vị ấy. ",
  "mn69:7.3": "‘Chắc chắn vị Tôn giả sống ở rừng một mình tự do này đã quen với sự phóng dật, xao động, nên khi đến Tăng chúng cũng hành xử như vậy.’—",
  "mn69:7.4": "Người ta sẽ nói về vị ấy. ",
  "mn69:7.5": "Do vậy, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, phải không phóng dật, không xao động. ",
  "mn69:8.1": "Này các bạn, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, phải không nói nhiều, không nói lời lộn xộn. ",
  "mn69:8.2": "Này các bạn, nếu một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng mà nói nhiều, nói lời lộn xộn, thì người ta sẽ nói về vị ấy. ",
  "mn69:8.3": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này nói nhiều, nói lời lộn xộn?’—",
  "mn69:8.4": "Người ta sẽ nói về vị ấy. ",
  "mn69:8.5": "Do vậy, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, phải không nói nhiều, không nói lời lộn xộn. ",
  "mn69:9.1": "Này các bạn, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, phải dễ dạy, có bạn lành. ",
  "mn69:9.2": "Này các bạn, nếu một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng mà khó dạy, có bạn ác, thì người ta sẽ nói về vị ấy. ",
  "mn69:9.3": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này khó dạy, có bạn ác?’—",
  "mn69:9.4": "Người ta sẽ nói về vị ấy. ",
  "mn69:9.5": "Do vậy, một Tỳ kheo sống ở rừng, khi đến Tăng chúng, sống trong Tăng chúng, phải dễ dạy, có bạn lành. ",
  "mn69:10.1": "Này các bạn, một Tỳ kheo sống ở rừng, phải giữ gìn các căn. ",
  "mn69:10.2": "Này các bạn, nếu một Tỳ kheo sống ở rừng mà không giữ gìn các căn, thì người ta sẽ nói về vị ấy. ",
  "mn69:10.3": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này không giữ gìn các căn?’—",
  "mn69:10.4": "Người ta sẽ nói về vị ấy. ",
  "mn69:10.5": "Do vậy, một Tỳ kheo sống ở rừng, phải giữ gìn các căn. ",
  "mn69:11.1": "Này các bạn, một Tỳ kheo sống ở rừng, phải tiết độ trong ăn uống. ",
  "mn69:11.2": "Này các bạn, nếu một Tỳ kheo sống ở rừng mà không tiết độ trong ăn uống, thì người ta sẽ nói về vị ấy. ",
  "mn69:11.3": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này không tiết độ trong ăn uống?’—",
  "mn69:11.4": "Người ta sẽ nói về vị ấy. ",
  "mn69:11.5": "Do vậy, một Tỳ kheo sống ở rừng, phải tiết độ trong ăn uống. ",
  "mn69:12.1": "Này các bạn, một Tỳ kheo sống ở rừng, phải chuyên cần thức tỉnh. ",
  "mn69:12.2": "Này các bạn, nếu một Tỳ kheo sống ở rừng mà không chuyên cần thức tỉnh, thì người ta sẽ nói về vị ấy. ",
  "mn69:12.3": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này không chuyên cần thức tỉnh?’—",
  "mn69:12.4": "Người ta sẽ nói về vị ấy. ",
  "mn69:12.5": "Do vậy, một Tỳ kheo sống ở rừng, phải chuyên cần thức tỉnh. ",
  "mn69:13.1": "Này các bạn, một Tỳ kheo sống ở rừng, phải tinh tấn. ",
  "mn69:13.2": "Này các bạn, nếu một Tỳ kheo sống ở rừng mà lười biếng, thì người ta sẽ nói về vị ấy. ",
  "mn69:13.3": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này lười biếng?’—",
  "mn69:13.4": "Người ta sẽ nói về vị ấy. ",
  "mn69:13.5": "Do vậy, một Tỳ kheo sống ở rừng, phải tinh tấn. ",
  "mn69:14.1": "Này các bạn, một Tỳ kheo sống ở rừng, phải có niệm tỉnh giác. ",
  "mn69:14.2": "Này các bạn, nếu một Tỳ kheo sống ở rừng mà thất niệm, thì người ta sẽ nói về vị ấy. ",
  "mn69:14.3": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này thất niệm?’—",
  "mn69:14.4": "Người ta sẽ nói về vị ấy. ",
  "mn69:14.5": "Do vậy, một Tỳ kheo sống ở rừng, phải có niệm tỉnh giác. ",
  "mn69:15.1": "Này các bạn, một Tỳ kheo sống ở rừng, phải có định. ",
  "mn69:15.2": "Này các bạn, nếu một Tỳ kheo sống ở rừng mà không có định, thì người ta sẽ nói về vị ấy. ",
  "mn69:15.3": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này không có định?’—",
  "mn69:15.4": "Người ta sẽ nói về vị ấy. ",
  "mn69:15.5": "Do vậy, một Tỳ kheo sống ở rừng, phải có định. ",
  "mn69:16.1": "Này các bạn, một Tỳ kheo sống ở rừng, phải có trí tuệ. ",
  "mn69:16.2": "Này các bạn, nếu một Tỳ kheo sống ở rừng mà kém trí tuệ, thì người ta sẽ nói về vị ấy. ",
  "mn69:16.3": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này kém trí tuệ?’—",
  "mn69:16.4": "Người ta sẽ nói về vị ấy. ",
  "mn69:16.5": "Do vậy, một Tỳ kheo sống ở rừng, phải có trí tuệ. ",
  "mn69:17.1": "Này các bạn, một Tỳ kheo sống ở rừng, phải chuyên tâm vào Vi Diệu Pháp và Thắng Giới Luật. ",
  "mn69:17.2": "Này các bạn, sẽ có người hỏi Tỳ kheo sống ở rừng về Vi Diệu Pháp và Thắng Giới Luật. ",
  "mn69:17.3": "Này các bạn, nếu một Tỳ kheo sống ở rừng, khi được hỏi về Vi Diệu Pháp và Thắng Giới Luật mà không trả lời được, thì người ta sẽ nói về vị ấy. ",
  "mn69:17.4": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này được hỏi về Vi Diệu Pháp và Thắng Giới Luật mà không trả lời được?’—",
  "mn69:17.5": "Người ta sẽ nói về vị ấy. ",
  "mn69:17.6": "Do vậy, một Tỳ kheo sống ở rừng, phải chuyên tâm vào Vi Diệu Pháp và Thắng Giới Luật. ",
  "mn69:18.1": "Này các bạn, một Tỳ kheo sống ở rừng, phải chuyên tâm vào các giải thoát an tịnh, vượt qua sắc, thuộc vô sắc. ",
  "mn69:18.2": "Này các bạn, sẽ có người hỏi Tỳ kheo sống ở rừng về các giải thoát an tịnh, vượt qua sắc, thuộc vô sắc. ",
  "mn69:18.3": "Này các bạn, nếu một Tỳ kheo sống ở rừng, khi được hỏi về các giải thoát an tịnh, vượt qua sắc, thuộc vô sắc mà không trả lời được, thì người ta sẽ nói về vị ấy. ",
  "mn69:18.4": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này được hỏi về các giải thoát an tịnh, vượt qua sắc, thuộc vô sắc mà không trả lời được?’—",
  "mn69:18.5": "Người ta sẽ nói về vị ấy. ",
  "mn69:18.6": "Do vậy, một Tỳ kheo sống ở rừng, phải chuyên tâm vào các giải thoát an tịnh, vượt qua sắc, thuộc vô sắc. ",
  "mn69:19.1": "Này các bạn, một Tỳ kheo sống ở rừng, phải chuyên tâm vào các pháp siêu nhân. ",
  "mn69:19.2": "Này các bạn, sẽ có người hỏi Tỳ kheo sống ở rừng về các pháp siêu nhân. ",
  "mn69:19.3": "Này các bạn, nếu một Tỳ kheo sống ở rừng, khi được hỏi về các pháp siêu nhân mà không trả lời được, thì người ta sẽ nói về vị ấy. ",
  "mn69:19.4": "‘Vị Tôn giả sống ở rừng một mình tự do này có ích gì, khi vị Tôn giả này không biết mục đích mình xuất gia?’—",
  "mn69:19.5": "Người ta sẽ nói về vị ấy. ",
  "mn69:19.6": "Do vậy, một Tỳ kheo sống ở rừng, phải chuyên tâm vào các pháp siêu nhân.” ",
  "mn69:19.7": "Khi được nói vậy, Tôn giả Mahāmoggallāna (Đại Mục Kiền Liên) nói với Tôn giả Sāriputta: ",
  "mn69:19.8": "“Này bạn Sāriputta, phải chăng chỉ Tỳ kheo sống ở rừng mới phải giữ gìn những pháp này, hay cả Tỳ kheo sống gần làng cũng vậy?” ",
  "mn69:19.9": "“Này bạn Moggallāna, Tỳ kheo sống ở rừng cũng phải giữ gìn những pháp này, huống chi Tỳ kheo sống gần làng.” ",
  "mn69:19.10": "Kinh Goliyāni chấm dứt, thứ chín. "
}
window.BILARA["mn69"]["vi"]["mn69:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
