window.BILARA = window.BILARA || {};
window.BILARA["mn75"] = window.BILARA["mn75"] || {};
window.BILARA["mn75"]["vi"] = {
  "mn75:0.1": "Trung Bộ Kinh 75 ",
  "mn75:0.2": "Kinh Māgaṇḍiya ",
  "mn75:1.1": "Như vầy tôi nghe—",
  "mn75:1.2": "một thời Thế Tôn trú ở xứ Kuru, tại thị trấn Kammāsadhamma của người Kuru, trong nhà lửa của Bà La Môn dòng Bhāradvāja, trên một đống cỏ. ",
  "mn75:2.1": "Rồi Thế Tôn vào buổi sáng, đắp y, cầm bát và y, đi vào Kammāsadhamma để khất thực. ",
  "mn75:2.2": "Sau khi khất thực ở Kammāsadhamma, và sau bữa ăn, Thế Tôn trở về từ cuộc khất thực, đi đến một khu rừng để nghỉ trưa. ",
  "mn75:2.3": "Đi sâu vào khu rừng đó, Thế Tôn ngồi nghỉ trưa dưới gốc cây. ",
  "mn75:3.1": "Rồi du sĩ Māgaṇḍiya, đang đi bộ lang thang, đi đến nhà lửa của Bà La Môn dòng Bhāradvāja. ",
  "mn75:3.2": "Du sĩ Māgaṇḍiya thấy một đống cỏ được trải trong nhà lửa của Bà La Môn dòng Bhāradvāja. ",
  "mn75:3.3": "Thấy vậy, ông nói với Bà La Môn dòng Bhāradvāja: ",
  "mn75:3.4": "“Thưa ngài Bhāradvāja, đống cỏ này được trải trong nhà lửa của ngài là của ai vậy? Tôi nghĩ đây là chỗ nằm của một vị Sa Môn.” ",
  "mn75:4.1": "“Thưa ngài Māgaṇḍiya, có một Sa Môn Gotama, con của dòng Sakya, đã xuất gia từ gia tộc Sakya. ",
  "mn75:4.2": "Tiếng tốt lành về ngài Gotama ấy đã vang lên như vầy: ",
  "mn75:4.3": "‘Đức Thế Tôn ấy là Bậc A La Hán, Chánh Đẳng Giác, đầy đủ Minh Hạnh, Thiện Thệ, hiểu biết thế gian, Vô Thượng Sĩ điều ngự trượng phu, Bậc Đạo Sư của trời và người, Phật, Thế Tôn.’ ",
  "mn75:4.4": "Đây là chỗ nằm được trải cho ngài Gotama ấy.” ",
  "mn75:5.1": "“Ôi, thưa ngài Bhāradvāja, chúng tôi đã thấy một điều thật tệ; ",
  "mn75:5.2": "ôi, thưa ngài Bhāradvāja, chúng tôi đã thấy một điều thật tệ. ",
  "mn75:5.3": "Chúng tôi đã thấy chỗ nằm của Sa Môn Gotama, kẻ hủy diệt sự sống.” ",
  "mn75:5.4": "“Thưa ngài Māgaṇḍiya, hãy giữ lời nói đó; ",
  "mn75:5.5": "thưa ngài Māgaṇḍiya, hãy giữ lời nói đó. ",
  "mn75:5.6": "Vì nhiều vị vua chúa trí thức, Bà La Môn trí thức, gia chủ trí thức, và Sa Môn trí thức đã tin tưởng và được giáo hóa bởi ngài Gotama ấy, thành thạo trong giáo pháp cao quý.” ",
  "mn75:5.7": "“Thưa ngài Bhāradvāja, ngay cả khi chúng tôi gặp trực tiếp ngài Gotama ấy, chúng tôi cũng sẽ nói thẳng với ngài ấy: ",
  "mn75:5.8": "‘Sa Môn Gotama là kẻ hủy diệt sự sống.’ ",
  "mn75:5.9": "Vì lý do gì? ",
  "mn75:5.10": "Vì trong kinh điển của chúng tôi, điều đó được nói đến như vậy.” ",
  "mn75:5.11": "“Nếu ngài Māgaṇḍiya không phiền, tôi sẽ báo cáo điều đó cho Sa Môn Gotama.” ",
  "mn75:5.12": "“Thưa ngài Bhāradvāja, ngài cứ nói điều đó mà không cần lo lắng.” ",
  "mn75:6.1": "Thế Tôn, với thiên nhĩ thanh tịnh vượt xa tai người, đã nghe cuộc trò chuyện này giữa Bà La Môn dòng Bhāradvāja và du sĩ Māgaṇḍiya. ",
  "mn75:6.2": "Rồi Thế Tôn, vào buổi chiều, sau khi ra khỏi chỗ thiền định, đi đến nhà lửa của Bà La Môn dòng Bhāradvāja; sau khi đến, Thế Tôn ngồi trên đống cỏ đã được trải. ",
  "mn75:6.3": "Rồi Bà La Môn dòng Bhāradvāja đi đến chỗ Thế Tôn; sau khi đến, ông chào hỏi Thế Tôn. ",
  "mn75:6.4": "Sau khi trao đổi những lời chào hỏi thân mật, ông ngồi xuống một bên. Khi Bà La Môn dòng Bhāradvāja đã ngồi xuống một bên, Thế Tôn nói với ông: ",
  "mn75:6.5": "“Này Bhāradvāja, ông có cuộc trò chuyện nào với du sĩ Māgaṇḍiya liên quan đến chính đống cỏ này không?” ",
  "mn75:6.6": "Khi được nói vậy, Bà La Môn dòng Bhāradvāja kinh ngạc, lông tóc dựng đứng, nói với Thế Tôn: ",
  "mn75:6.7": "“Chính điều này chúng tôi muốn báo cáo cho ngài Gotama. ",
  "mn75:6.8": "Nhưng ngài Gotama đã nói ra điều chưa được nói.” ",
  "mn75:7.1": "Và cuộc trò chuyện giữa Thế Tôn và Bà La Môn dòng Bhāradvāja đã bị gián đoạn. ",
  "mn75:7.2": "Rồi du sĩ Māgaṇḍiya, đang đi bộ lang thang, đi đến nhà lửa của Bà La Môn dòng Bhāradvāja, đến chỗ Thế Tôn; sau khi đến, ông chào hỏi Thế Tôn. ",
  "mn75:7.3": "Sau khi trao đổi những lời chào hỏi thân mật, ông ngồi xuống một bên. Khi du sĩ Māgaṇḍiya đã ngồi xuống một bên, Thế Tôn nói với ông: ",
  "mn75:8.1": "“Này Māgaṇḍiya, mắt ưa thích sắc, vui thích sắc, hoan hỷ với sắc. ",
  "mn75:8.2": "Điều đó đã được Như Lai điều phục, bảo vệ, giữ gìn, chế ngự, và Như Lai thuyết pháp để chế ngự điều đó. ",
  "mn75:8.3": "Này Māgaṇḍiya, có phải ông đã nói điều này với ý đó: ",
  "mn75:8.4": "‘Sa Môn Gotama là kẻ hủy diệt sự sống’?” ",
  "mn75:8.5": "“Chính điều đó, thưa ngài Gotama, tôi đã nói với ý đó: ",
  "mn75:8.6": "‘Sa Môn Gotama là kẻ hủy diệt sự sống.’ ",
  "mn75:8.7": "Vì lý do gì? ",
  "mn75:8.8": "Vì trong kinh điển của chúng tôi, điều đó được nói đến như vậy.” ",
  "mn75:8.9": "“Này Māgaṇḍiya, tai ưa thích tiếng… ",
  "mn75:8.10": "mũi ưa thích mùi… ",
  "mn75:8.11": "lưỡi ưa thích vị, vui thích vị, hoan hỷ với vị. ",
  "mn75:8.12": "Điều đó đã được Như Lai điều phục, bảo vệ, giữ gìn, chế ngự, và Như Lai thuyết pháp để chế ngự điều đó. ",
  "mn75:8.13": "Này Māgaṇḍiya, có phải ông đã nói điều này với ý đó: ",
  "mn75:8.14": "‘Sa Môn Gotama là kẻ hủy diệt sự sống’?” ",
  "mn75:8.15": "“Chính điều đó, thưa ngài Gotama, tôi đã nói với ý đó: ",
  "mn75:8.16": "‘Sa Môn Gotama là kẻ hủy diệt sự sống.’ ",
  "mn75:8.17": "Vì lý do gì? ",
  "mn75:8.18": "Vì trong kinh điển của chúng tôi, điều đó được nói đến như vậy.” ",
  "mn75:8.19": "“Này Māgaṇḍiya, thân ưa thích xúc, vui thích xúc… ",
  "mn75:8.20": "ý ưa thích pháp, vui thích pháp, hoan hỷ với pháp. ",
  "mn75:8.21": "Điều đó đã được Như Lai điều phục, bảo vệ, giữ gìn, chế ngự, và Như Lai thuyết pháp để chế ngự điều đó. ",
  "mn75:8.22": "Này Māgaṇḍiya, có phải ông đã nói điều này với ý đó: ",
  "mn75:8.23": "‘Sa Môn Gotama là kẻ hủy diệt sự sống’?” ",
  "mn75:8.24": "“Chính điều đó, thưa ngài Gotama, tôi đã nói với ý đó: ",
  "mn75:8.25": "‘Sa Môn Gotama là kẻ hủy diệt sự sống.’ ",
  "mn75:8.26": "Vì lý do gì? ",
  "mn75:8.27": "Vì trong kinh điển của chúng tôi, điều đó được nói đến như vậy.” ",
  "mn75:9.1": "“Này Māgaṇḍiya, ông nghĩ sao: ",
  "mn75:9.2": "‘Ở đây, có người trước đây đã từng hưởng thụ các sắc do mắt nhận biết, những sắc đáng ưa, đáng thích, đáng mến, đáng yêu, liên quan đến dục, làm say đắm; sau đó, người ấy, sau khi biết rõ sự sinh khởi, sự diệt tận, vị ngọt, sự nguy hiểm và sự thoát ly của các sắc ấy như thật, đã từ bỏ tham ái sắc, đã loại bỏ sự nóng bức do sắc, sống không khát khao, với tâm an tịnh bên trong. ",
  "mn75:9.3": "Này Māgaṇḍiya, ông sẽ nói gì về người này?” ",
  "mn75:9.4": "“Không có gì, thưa ngài Gotama.” ",
  "mn75:9.5": "“Này Māgaṇḍiya, ông nghĩ sao: ",
  "mn75:9.6": "‘Ở đây, có người trước đây đã từng hưởng thụ các tiếng do tai nhận biết… ",
  "mn75:9.7": "các mùi do mũi nhận biết… ",
  "mn75:9.8": "các vị do lưỡi nhận biết… ",
  "mn75:9.9": "các xúc do thân nhận biết, những xúc đáng ưa, đáng thích, đáng mến, đáng yêu, liên quan đến dục, làm say đắm; ",
  "mn75:9.10": "sau đó, người ấy, sau khi biết rõ sự sinh khởi, sự diệt tận, vị ngọt, sự nguy hiểm và sự thoát ly của các xúc ấy như thật, đã từ bỏ tham ái xúc, đã loại bỏ sự nóng bức do xúc, sống không khát khao, với tâm an tịnh bên trong. ",
  "mn75:9.11": "Này Māgaṇḍiya, ông sẽ nói gì về người này?” ",
  "mn75:9.12": "“Không có gì, thưa ngài Gotama.” ",
  "mn75:10.1": "“Này Māgaṇḍiya, trước đây, khi còn là người tại gia, tôi đã được cung phụng đầy đủ năm dục công đức: các sắc do mắt nhận biết, đáng ưa, đáng thích, đáng mến, đáng yêu, liên quan đến dục, làm say đắm; các tiếng do tai nhận biết… ",
  "mn75:10.2": "các mùi do mũi nhận biết… ",
  "mn75:10.3": "các vị do lưỡi nhận biết… ",
  "mn75:10.4": "các xúc do thân nhận biết, đáng ưa, đáng thích, đáng mến, đáng yêu, liên quan đến dục, làm say đắm. ",
  "mn75:10.5": "Này Māgaṇḍiya, tôi có ba cung điện—",
  "mn75:10.6": "một cho mùa mưa, một cho mùa đông, một cho mùa hè. ",
  "mn75:10.7": "Này Māgaṇḍiya, trong cung điện mùa mưa, tôi được cung phụng bởi các nhạc cụ không có người chơi trong bốn tháng mùa mưa, và tôi không xuống tầng dưới của cung điện. ",
  "mn75:10.8": "Sau đó, tôi, sau khi biết rõ sự sinh khởi, sự diệt tận, vị ngọt, sự nguy hiểm và sự thoát ly của các dục ấy như thật, đã từ bỏ tham ái dục, đã loại bỏ sự nóng bức do dục, sống không khát khao, với tâm an tịnh bên trong. ",
  "mn75:10.9": "Tôi thấy những chúng sinh khác chưa thoát khỏi tham ái dục, bị tham ái dục giày vò, bị sự nóng bức do dục thiêu đốt, đang hưởng thụ các dục. ",
  "mn75:10.10": "Tôi không thèm muốn họ, không vui thích ở đó. ",
  "mn75:10.11": "Vì lý do gì? ",
  "mn75:10.12": "Này Māgaṇḍiya, niềm vui này, khác với các dục, khác với các pháp bất thiện—",
  "mn75:10.13": "thậm chí vượt qua cả hạnh phúc của chư thiên—",
  "mn75:10.14": "khi tôi vui thích với niềm vui đó, tôi không thèm muốn điều thấp kém, không vui thích ở đó. ",
  "mn75:11.1": "Ví như, này Māgaṇḍiya, một gia chủ hay con của gia chủ, giàu có, nhiều tài sản, nhiều của cải, được cung phụng đầy đủ năm dục công đức: các sắc do mắt nhận biết… ",
  "mn75:11.2": "v.v… ",
  "mn75:11.3": "các xúc, đáng ưa, đáng thích, đáng mến, đáng yêu, liên quan đến dục, làm say đắm. ",
  "mn75:11.4": "Người ấy, sau khi thực hành thiện hạnh bằng thân, thiện hạnh bằng lời, thiện hạnh bằng ý, sau khi thân hoại mạng chung, sẽ tái sinh vào cõi thiện, cõi trời, làm bạn với chư thiên cõi Ba Mươi Ba. ",
  "mn75:11.5": "Ở đó, trong vườn Nandana, người ấy được vây quanh bởi các nhóm tiên nữ, được cung phụng đầy đủ năm dục công đức của chư thiên. ",
  "mn75:11.6": "Người ấy thấy một gia chủ hay con của gia chủ đang được cung phụng đầy đủ năm dục công đức. ",
  "mn75:11.7": "Này Māgaṇḍiya, ông nghĩ sao, vị thiên tử đó, đang ở trong vườn Nandana, được vây quanh bởi các nhóm tiên nữ, được cung phụng đầy đủ năm dục công đức của chư thiên, liệu có thèm muốn gia chủ hay con của gia chủ kia, hay có bị thu hút bởi năm dục công đức của loài người, hay bởi các dục của loài người không?” ",
  "mn75:11.8": "“Không, thưa ngài Gotama. ",
  "mn75:11.9": "Vì lý do gì? ",
  "mn75:11.10": "Thưa ngài Gotama, các dục của chư thiên vượt trội và vi diệu hơn các dục của loài người.” ",
  "mn75:12.1": "“Cũng vậy, này Māgaṇḍiya, trước đây, khi còn là người tại gia, tôi đã được cung phụng đầy đủ năm dục công đức: các sắc do mắt nhận biết, đáng ưa, đáng thích, đáng mến, đáng yêu, liên quan đến dục, làm say đắm; các tiếng do tai nhận biết… ",
  "mn75:12.2": "các mùi do mũi nhận biết… ",
  "mn75:12.3": "các vị do lưỡi nhận biết… ",
  "mn75:12.4": "các xúc do thân nhận biết, đáng ưa, đáng thích, đáng mến, đáng yêu, liên quan đến dục, làm say đắm. ",
  "mn75:12.5": "Sau đó, tôi, sau khi biết rõ sự sinh khởi, sự diệt tận, vị ngọt, sự nguy hiểm và sự thoát ly của các dục ấy như thật, đã từ bỏ tham ái dục, đã loại bỏ sự nóng bức do dục, sống không khát khao, với tâm an tịnh bên trong. ",
  "mn75:12.6": "Tôi thấy những chúng sinh khác chưa thoát khỏi tham ái dục, bị tham ái dục giày vò, bị sự nóng bức do dục thiêu đốt, đang hưởng thụ các dục, tôi không thèm muốn họ, không vui thích ở đó. ",
  "mn75:12.7": "Vì lý do gì? ",
  "mn75:12.8": "Này Māgaṇḍiya, niềm vui này, khác với các dục, khác với các pháp bất thiện—",
  "mn75:12.9": "thậm chí vượt qua cả hạnh phúc của chư thiên—",
  "mn75:12.10": "khi tôi vui thích với niềm vui đó, tôi không thèm muốn điều thấp kém, không vui thích ở đó. ",
  "mn75:13.1": "Ví như, này Māgaṇḍiya, một người bị bệnh phong, thân thể lở loét, mưng mủ, bị giòi bọ ăn, dùng móng tay cào các vết thương, và hơ thân thể trên đống than hồng. ",
  "mn75:13.2": "Bạn bè, người thân, bà con huyết thống của người ấy sẽ đưa người ấy đến một thầy thuốc phẫu thuật. ",
  "mn75:13.3": "Thầy thuốc phẫu thuật đó sẽ chữa bệnh cho người ấy. ",
  "mn75:13.4": "Nhờ thuốc đó, người ấy sẽ thoát khỏi bệnh phong, trở nên khỏe mạnh, hạnh phúc, tự do, tự chủ, có thể đi đến bất cứ nơi nào mình muốn. ",
  "mn75:13.5": "Người ấy thấy một người bị bệnh phong khác, thân thể lở loét, mưng mủ, bị giòi bọ ăn, dùng móng tay cào các vết thương, và hơ thân thể trên đống than hồng. ",
  "mn75:13.6": "Này Māgaṇḍiya, ông nghĩ sao, ",
  "mn75:13.7": "liệu người ấy có thèm muốn người bị bệnh phong kia, hay thèm muốn đống than hồng, hay thèm muốn việc dùng thuốc không?” ",
  "mn75:13.8": "“Không, thưa ngài Gotama. ",
  "mn75:13.9": "Vì lý do gì? ",
  "mn75:13.10": "Thưa Tôn giả Gotama, khi có bệnh thì cần thuốc, khi không có bệnh thì không cần thuốc.”",
  "mn75:14.1": "“Cũng vậy, này Māgaṇḍiya, trước đây khi còn là người tại gia, ta đã hưởng thụ năm dục lạc, được cung cấp đầy đủ, gắn liền với các sắc do mắt nhận biết, khả ái, khả lạc, khả ý, đáng yêu, liên hệ đến dục, gợi dục; với các tiếng do tai nhận biết…pe…",
  "mn75:14.2": "với các mùi do mũi nhận biết…",
  "mn75:14.3": "với các vị do lưỡi nhận biết…",
  "mn75:14.4": "với các xúc do thân nhận biết, khả ái, khả lạc, khả ý, đáng yêu, liên hệ đến dục, gợi dục.",
  "mn75:14.5": "Sau một thời gian, ta đã như thật biết sự sinh, sự diệt, vị ngọt, sự nguy hiểm và sự thoát ly của các dục, từ bỏ khát ái dục, dập tắt sự nóng bức của dục, không còn khát khao, tâm an tịnh bên trong mà sống.",
  "mn75:14.6": "Ta thấy những chúng sinh khác chưa ly tham đối với các dục, bị khát ái dục giày vò, bị sự nóng bức của dục thiêu đốt, đang hưởng thụ các dục.",
  "mn75:14.7": "Ta không thèm muốn họ, không vui thích ở đó.",
  "mn75:14.8": "Vì lý do gì?",
  "mn75:14.9": "Này Māgaṇḍiya, niềm vui này, khác với các dục, khác với các pháp bất thiện—",
  "mn75:14.10": "thậm chí vượt lên cả hạnh phúc cõi trời—",
  "mn75:14.11": "khi hưởng thụ niềm vui ấy, ta không thèm muốn cái thấp kém, không vui thích ở đó.",
  "mn75:15.1": "Ví như, này Māgaṇḍiya, một người bị bệnh phong cùi, thân thể lở loét, mưng mủ, bị giòi bọ ăn, dùng móng tay cào các vết thương, rồi hơ thân thể trên đống than hồng.",
  "mn75:15.2": "Bạn bè, thân quyến, bà con của người ấy sẽ mời một thầy thuốc phẫu thuật đến.",
  "mn75:15.3": "Thầy thuốc phẫu thuật ấy sẽ chữa bệnh cho người ấy.",
  "mn75:15.4": "Nhờ thuốc ấy, người ấy thoát khỏi bệnh phong cùi, trở nên không bệnh, hạnh phúc, tự do, tự chủ, muốn đi đâu thì đi.",
  "mn75:15.5": "Hai người đàn ông khỏe mạnh sẽ nắm hai cánh tay người ấy kéo đến đống than hồng.",
  "mn75:15.6": "Này Māgaṇḍiya, ông nghĩ sao,",
  "mn75:15.7": "người ấy có co rúm thân thể lại không?”",
  "mn75:15.8": "“Thưa Tôn giả Gotama, có.",
  "mn75:15.9": "Vì lý do gì?",
  "mn75:15.10": "Thưa Tôn giả Gotama, lửa ấy có sự xúc chạm khổ, rất nóng và rất thiêu đốt.”",
  "mn75:15.11": "“Này Māgaṇḍiya, ông nghĩ sao,",
  "mn75:15.12": "phải chăng chỉ bây giờ lửa ấy có sự xúc chạm khổ, rất nóng và rất thiêu đốt, hay trước đây lửa ấy cũng có sự xúc chạm khổ, rất nóng và rất thiêu đốt?”",
  "mn75:15.13": "“Thưa Tôn giả Gotama, bây giờ lửa ấy có sự xúc chạm khổ, rất nóng và rất thiêu đốt, trước đây lửa ấy cũng có sự xúc chạm khổ, rất nóng và rất thiêu đốt.",
  "mn75:15.14": "Và thưa Tôn giả Gotama, người bị bệnh phong cùi, thân thể lở loét, mưng mủ, bị giòi bọ ăn, dùng móng tay cào các vết thương, các căn bị tổn hại, đã nhận thức sai lầm rằng lửa có sự xúc chạm khổ là hạnh phúc.”",
  "mn75:16.1": "“Cũng vậy, này Māgaṇḍiya, trong thời quá khứ, các dục có sự xúc chạm khổ, rất nóng và rất thiêu đốt; trong thời vị lai, các dục có sự xúc chạm khổ, rất nóng và rất thiêu đốt; và trong thời hiện tại, các dục có sự xúc chạm khổ, rất nóng và rất thiêu đốt.",
  "mn75:16.2": "Và này Māgaṇḍiya, những chúng sinh này chưa ly tham đối với các dục, bị khát ái dục giày vò, bị sự nóng bức của dục thiêu đốt, các căn bị tổn hại, đã nhận thức sai lầm rằng các dục có sự xúc chạm khổ là hạnh phúc.",
  "mn75:17.1": "Ví như, này Māgaṇḍiya, một người bị bệnh phong cùi, thân thể lở loét, mưng mủ, bị giòi bọ ăn, dùng móng tay cào các vết thương, rồi hơ thân thể trên đống than hồng.",
  "mn75:17.2": "Này Māgaṇḍiya, người bị bệnh phong cùi, thân thể lở loét, mưng mủ, bị giòi bọ ăn, dùng móng tay cào các vết thương, rồi hơ thân thể trên đống than hồng, càng hơ như vậy thì các vết thương ấy càng trở nên dơ bẩn hơn, hôi thối hơn, mưng mủ hơn, và có một chút dễ chịu, một chút vị ngọt—đó là do việc gãi các vết thương; ",
  "mn75:17.3": "cũng vậy, này Māgaṇḍiya, những chúng sinh chưa ly tham đối với các dục, bị khát ái dục giày vò, bị sự nóng bức của dục thiêu đốt, đang hưởng thụ các dục.",
  "mn75:17.4": "Này Māgaṇḍiya, những chúng sinh chưa ly tham đối với các dục, bị khát ái dục giày vò, bị sự nóng bức của dục thiêu đốt, càng hưởng thụ các dục như vậy thì khát ái dục của họ càng tăng trưởng, và họ càng bị sự nóng bức của dục thiêu đốt, và có một chút dễ chịu, một chút vị ngọt—đó là do năm dục lạc.",
  "mn75:18.1": "Này Māgaṇḍiya, ông nghĩ sao,",
  "mn75:18.2": "ông có từng thấy hay nghe về một vị vua hay đại thần nào, đang hưởng thụ năm dục lạc, được cung cấp đầy đủ, gắn liền với chúng, mà không từ bỏ khát ái dục, không dập tắt sự nóng bức của dục, không còn khát khao, tâm an tịnh bên trong mà đã sống, đang sống, hay sẽ sống không?”",
  "mn75:18.3": "“Thưa Tôn giả Gotama, không có.”",
  "mn75:18.4": "“Tốt lắm, này Māgaṇḍiya.",
  "mn75:18.5": "Này Māgaṇḍiya, ta cũng chưa từng thấy hay nghe về một vị vua hay đại thần nào, đang hưởng thụ năm dục lạc, được cung cấp đầy đủ, gắn liền với chúng, mà không từ bỏ khát ái dục, không dập tắt sự nóng bức của dục, không còn khát khao, tâm an tịnh bên trong mà đã sống, đang sống, hay sẽ sống.",
  "mn75:18.6": "Nhưng này Māgaṇḍiya, bất cứ vị sa môn hay bà la môn nào đã sống, đang sống, hay sẽ sống mà không còn khát khao, tâm an tịnh bên trong, tất cả họ đều đã như thật biết sự sinh, sự diệt, vị ngọt, sự nguy hiểm và sự thoát ly của các dục, từ bỏ khát ái dục, dập tắt sự nóng bức của dục, không còn khát khao, tâm an tịnh bên trong mà đã sống, đang sống, hay sẽ sống.”",
  "mn75:19.1": "Rồi Thế Tôn, vào lúc ấy, đã thốt lên lời cảm hứng này:",
  "mn75:19.2": "“Không bệnh là lợi ích tối thượng,",
  "mn75:19.3": "Niết Bàn là hạnh phúc tối thượng;",
  "mn75:19.4": "Con đường tám chi là con đường,",
  "mn75:19.5": "an toàn dẫn đến bất tử.”",
  "mn75:19.6": "Khi được nói vậy, du sĩ Māgaṇḍiya bạch Thế Tôn:",
  "mn75:19.7": "“Thật kỳ diệu thay, thưa Tôn giả Gotama! Thật phi thường thay, thưa Tôn giả Gotama!",
  "mn75:19.8": "Lời này của Tôn giả Gotama thật là khéo nói:",
  "mn75:19.9": "‘Không bệnh là lợi ích tối thượng, Niết Bàn là hạnh phúc tối thượng.’",
  "mn75:19.10": "Thưa Tôn giả Gotama, tôi cũng đã nghe các du sĩ tiền bối, các thầy và thầy của các thầy nói rằng:",
  "mn75:19.11": "‘Không bệnh là lợi ích tối thượng, Niết Bàn là hạnh phúc tối thượng’;",
  "mn75:19.12": "điều này, thưa Tôn giả Gotama, trùng hợp với nhau.”",
  "mn75:19.13": "“Nhưng này Māgaṇḍiya, điều mà ông đã nghe các du sĩ tiền bối, các thầy và thầy của các thầy nói rằng:",
  "mn75:19.14": "‘Không bệnh là lợi ích tối thượng, Niết Bàn là hạnh phúc tối thượng’, vậy cái không bệnh ấy là gì, cái Niết Bàn ấy là gì?”",
  "mn75:19.15": "Khi được nói vậy, du sĩ Māgaṇḍiya liền dùng tay xoa khắp thân thể mình:",
  "mn75:19.16": "“Thưa Tôn giả Gotama, đây là không bệnh, đây là Niết Bàn.",
  "mn75:19.17": "Vì thưa Tôn giả Gotama, hiện giờ tôi không bệnh, hạnh phúc, không có gì làm tôi đau đớn.”",
  "mn75:20.1": "“Ví như, này Māgaṇḍiya, một người mù bẩm sinh;",
  "mn75:20.2": "người ấy không thấy các sắc đen trắng, không thấy các sắc xanh, không thấy các sắc vàng, không thấy các sắc đỏ, không thấy các sắc đỏ thẫm, không thấy chỗ bằng phẳng hay gồ ghề, không thấy hình dạng các vì sao, không thấy mặt trăng mặt trời.",
  "mn75:20.3": "Người ấy nghe một người có mắt nói:",
  "mn75:20.4": "‘Thật khéo léo thay, này bạn, tấm vải trắng đẹp đẽ, không tỳ vết, sạch sẽ!’",
  "mn75:20.5": "Người ấy sẽ đi tìm kiếm vải trắng.",
  "mn75:20.6": "Một người khác sẽ lừa dối người ấy bằng một tấm giẻ bẩn dính dầu:",
  "mn75:20.7": "‘Này bạn, đây là tấm vải trắng đẹp đẽ, không tỳ vết, sạch sẽ của bạn.’",
  "mn75:20.8": "Người ấy sẽ nhận lấy nó, nhận lấy rồi khoác lên người, khoác lên người rồi vui mừng thốt lên lời vui mừng:",
  "mn75:20.9": "‘Thật khéo léo thay, này bạn, tấm vải trắng đẹp đẽ, không tỳ vết, sạch sẽ!’",
  "mn75:20.10": "Này Māgaṇḍiya, ông nghĩ sao,",
  "mn75:20.11": "phải chăng người mù bẩm sinh ấy, biết và thấy, mà nhận lấy tấm giẻ bẩn dính dầu ấy, nhận lấy rồi khoác lên người, khoác lên người rồi vui mừng thốt lên lời vui mừng:",
  "mn75:20.12": "‘Thật khéo léo thay, này bạn, tấm vải trắng đẹp đẽ, không tỳ vết, sạch sẽ!’ hay là do tin lời người có mắt?”",
  "mn75:20.13": "“Thưa Tôn giả Gotama, người mù bẩm sinh ấy, không biết và không thấy, mà nhận lấy tấm giẻ bẩn dính dầu ấy, nhận lấy rồi khoác lên người, khoác lên người rồi vui mừng thốt lên lời vui mừng:",
  "mn75:20.14": "‘Thật khéo léo thay, này bạn, tấm vải trắng đẹp đẽ, không tỳ vết, sạch sẽ!’, là do tin lời người có mắt.”",
  "mn75:21.1": "“Cũng vậy, này Māgaṇḍiya, các du sĩ ngoại đạo là những người mù, không có mắt, không biết không bệnh, không thấy Niết Bàn, vậy mà họ lại nói bài kệ này:",
  "mn75:21.2": "‘Không bệnh là lợi ích tối thượng, Niết Bàn là hạnh phúc tối thượng.’",
  "mn75:21.3": "Này Māgaṇḍiya, bài kệ này đã được các vị A-la-hán Chánh Đẳng Giác thời xưa nói:",
  "mn75:21.4": "‘Không bệnh là lợi ích tối thượng,",
  "mn75:21.5": "Niết Bàn là hạnh phúc tối thượng;",
  "mn75:21.6": "Con đường tám chi là con đường,",
  "mn75:21.7": "an toàn dẫn đến bất tử.’",
  "mn75:21.8": "Nhưng bây giờ, dần dần, nó đã trở thành bài kệ của phàm phu.",
  "mn75:21.9": "Và này Māgaṇḍiya, thân này là bệnh, là mụn nhọt, là mũi tên, là đau khổ, là bệnh hoạn, vậy mà ông lại nói về thân này là bệnh, là mụn nhọt, là mũi tên, là đau khổ, là bệnh hoạn:",
  "mn75:21.10": "‘Thưa Tôn giả Gotama, đây là không bệnh, đây là Niết Bàn.’",
  "mn75:21.11": "Vì này Māgaṇḍiya, ông không có con mắt thánh, nhờ đó ông có thể biết không bệnh, thấy Niết Bàn.”",
  "mn75:22.1": "“Con rất tin tưởng Tôn giả Gotama.",
  "mn75:22.2": "Tôn giả Gotama có thể thuyết pháp cho con để con có thể biết không bệnh, thấy Niết Bàn.”",
  "mn75:22.3": "“Ví như, này Māgaṇḍiya, một người mù bẩm sinh;",
  "mn75:22.4": "người ấy không thấy các sắc đen trắng, không thấy các sắc xanh, không thấy các sắc vàng, không thấy các sắc đỏ, không thấy các sắc đỏ thẫm, không thấy chỗ bằng phẳng hay gồ ghề, không thấy hình dạng các vì sao, không thấy mặt trăng mặt trời.",
  "mn75:22.5": "Bạn bè, thân quyến, bà con của người ấy sẽ mời một thầy thuốc phẫu thuật đến.",
  "mn75:22.6": "Thầy thuốc phẫu thuật ấy sẽ chữa bệnh cho người ấy.",
  "mn75:22.7": "Nhờ thuốc ấy, người ấy không thể làm cho mắt sinh ra, không thể làm cho mắt trong sáng.",
  "mn75:22.8": "Này Māgaṇḍiya, ông nghĩ sao,",
  "mn75:22.9": "chẳng phải thầy thuốc ấy chỉ chịu phần mệt nhọc và thất bại sao?”",
  "mn75:22.10": "“Thưa Tôn giả Gotama, đúng vậy.”",
  "mn75:22.11": "“Cũng vậy, này Māgaṇḍiya, nếu ta thuyết pháp cho ông:",
  "mn75:22.12": "‘Đây là không bệnh, đây là Niết Bàn’, thì ông sẽ không biết không bệnh, không thấy Niết Bàn.",
  "mn75:22.13": "Đó sẽ là sự mệt nhọc của ta, đó sẽ là sự phiền toái của ta.”",
  "mn75:23.1": "“Con rất tin tưởng Tôn giả Gotama.",
  "mn75:23.2": "Tôn giả Gotama có thể thuyết pháp cho con để con có thể biết không bệnh, thấy Niết Bàn.”",
  "mn75:23.3": "“Ví như, này Māgaṇḍiya, một người mù bẩm sinh;",
  "mn75:23.4": "người ấy không thấy các sắc đen trắng, không thấy các sắc xanh, không thấy các sắc vàng, không thấy các sắc đỏ, không thấy các sắc đỏ thẫm, không thấy chỗ bằng phẳng hay gồ ghề, không thấy hình dạng các vì sao, không thấy mặt trăng mặt trời.",
  "mn75:23.5": "Người ấy nghe một người có mắt nói:",
  "mn75:23.6": "‘Thật khéo léo thay, này bạn, tấm vải trắng đẹp đẽ, không tỳ vết, sạch sẽ!’",
  "mn75:23.7": "Người ấy sẽ đi tìm kiếm vải trắng.",
  "mn75:23.8": "Một người khác sẽ lừa dối người ấy bằng một tấm giẻ bẩn dính dầu:",
  "mn75:23.9": "‘Này bạn, đây là tấm vải trắng đẹp đẽ, không tỳ vết, sạch sẽ của bạn.’",
  "mn75:23.10": "Người ấy sẽ nhận lấy nó, nhận lấy rồi khoác lên người.",
  "mn75:23.11": "Bạn bè, thân quyến, bà con của người ấy sẽ mời một thầy thuốc phẫu thuật đến.",
  "mn75:23.12": "Thầy thuốc phẫu thuật ấy sẽ chữa bệnh cho người ấy—",
  "mn75:23.13": "thuốc xổ trên, thuốc xổ dưới, thuốc nhỏ mắt, thuốc bôi mắt, thuốc nhỏ mũi.",
  "mn75:23.14": "Nhờ thuốc ấy, người ấy có thể làm cho mắt sinh ra, làm cho mắt trong sáng.",
  "mn75:23.15": "Ngay khi mắt sinh ra, sự ham muốn và tham ái của người ấy đối với tấm giẻ bẩn dính dầu ấy sẽ biến mất.",
  "mn75:23.16": "Và người ấy sẽ xem người kia như kẻ thù, như đối thủ, thậm chí nghĩ rằng nên tước đoạt mạng sống của hắn:",
  "mn75:23.17": "‘Thật vậy, này bạn, ta đã bị người này lừa dối, gạt gẫm, mê hoặc bằng tấm giẻ bẩn dính dầu ấy suốt một thời gian dài—",
  "mn75:23.18": "Này bạn, đây là tấm vải trắng đẹp đẽ, không tỳ vết, sạch sẽ của bạn.’",
  "mn75:24.1": "Cũng vậy, này Māgaṇḍiya, nếu ta thuyết pháp cho ông:",
  "mn75:24.2": "‘Đây là không bệnh, đây là Niết Bàn.’",
  "mn75:24.3": "Thì ông sẽ biết không bệnh, thấy Niết Bàn.",
  "mn75:24.4": "Ngay khi mắt ông sinh ra, sự ham muốn và tham ái của ông đối với năm uẩn chấp thủ sẽ biến mất;",
  "mn75:24.5": "và ông sẽ nghĩ như thế này:",
  "mn75:24.6": "‘Thật vậy, này bạn, ta đã bị tâm này lừa dối, gạt gẫm, mê hoặc suốt một thời gian dài.",
  "mn75:24.7": "Vì ta đã chấp thủ sắc, chấp thủ thọ, chấp thủ tưởng, chấp thủ hành, chấp thủ thức.",
  "mn75:24.8": "Do duyên chấp thủ mà có hữu, do duyên hữu mà có sinh, do duyên sinh mà có già, chết, sầu, bi, khổ, ưu, não sinh khởi;",
  "mn75:24.9": "như vậy là sự tập khởi của toàn bộ khối khổ này.’”",
  "mn75:25.1": "“Con tin tưởng như vậy vào Tôn giả Gotama. ",
  "mn75:25.2": "Tôn giả Gotama có thể thuyết pháp cho con để con có thể đứng dậy khỏi chỗ ngồi này mà không còn mù quáng nữa.”",
  "mn75:25.3": "“Vậy thì, Māgaṇḍiya, ông hãy thân cận bậc thiện nhân. ",
  "mn75:25.4": "Này Māgaṇḍiya, khi ông thân cận bậc thiện nhân, thì ông sẽ nghe chánh pháp; ",
  "mn75:25.5": "này Māgaṇḍiya, khi ông nghe chánh pháp, thì ông sẽ thực hành pháp và tùy pháp; ",
  "mn75:25.6": "này Māgaṇḍiya, khi ông thực hành pháp và tùy pháp, thì ông sẽ tự mình biết, tự mình thấy—",
  "mn75:25.7": "đây là những bệnh tật, mụn nhọt, mũi tên; ",
  "mn75:25.8": "ở đây, những bệnh tật, mụn nhọt, mũi tên này diệt tận không còn sót lại. ",
  "mn75:25.9": "Với sự diệt trừ chấp thủ của ta, sự tái sinh diệt trừ; với sự tái sinh diệt trừ, sự sinh diệt trừ; với sự sinh diệt trừ, già chết, sầu bi, khổ ưu, tuyệt vọng diệt trừ; ",
  "mn75:25.10": "như vậy, toàn bộ khối khổ này được diệt trừ.”",
  "mn75:26.1": "Khi được nói như vậy, du sĩ Māgaṇḍiya bạch Thế Tôn: ",
  "mn75:26.2": "“Tuyệt vời thay, Tôn giả Gotama! Tuyệt vời thay, Tôn giả Gotama! ",
  "mn75:26.3": "Ví như, Tôn giả Gotama, người ta lật ngửa cái bị úp xuống, hay mở ra cái bị che đậy, hay chỉ đường cho người lạc lối, hay cầm đèn dầu trong bóng tối để những người có mắt có thể thấy các hình sắc; cũng vậy, Tôn giả Gotama đã thuyết pháp bằng nhiều cách khác nhau. ",
  "mn75:26.4": "Con xin quy y Tôn giả Gotama, quy y Pháp và quy y Tăng chúng. ",
  "mn75:26.5": "Con xin được xuất gia trong giáo pháp của Tôn giả Gotama, con xin được thọ giới Tỳ-kheo.”",
  "mn75:27.1": "“Này Māgaṇḍiya, người nào trước đây là ngoại đạo, muốn xuất gia, muốn thọ giới Tỳ-kheo trong giáo pháp này, thì phải sống thử bốn tháng; sau bốn tháng, các Tỳ-kheo sẽ cho xuất gia, cho thọ giới Tỳ-kheo nếu họ có tâm hoan hỷ. ",
  "mn75:27.2": "Tuy nhiên, ở đây ta cũng biết có sự khác biệt giữa các cá nhân.”",
  "mn75:27.3": "“Bạch Ngài, nếu những người trước đây là ngoại đạo, muốn xuất gia, muốn thọ giới Tỳ-kheo trong giáo pháp này phải sống thử bốn tháng, sau bốn tháng các Tỳ-kheo sẽ cho xuất gia, cho thọ giới Tỳ-kheo nếu họ có tâm hoan hỷ; thì con sẽ sống thử bốn năm, sau bốn năm, xin các Tỳ-kheo hãy cho con xuất gia, cho con thọ giới Tỳ-kheo nếu họ có tâm hoan hỷ.”",
  "mn75:28.1": "Du sĩ Māgaṇḍiya đã được xuất gia trong giáo pháp của Thế Tôn, đã được thọ giới Tỳ-kheo. ",
  "mn75:28.2": "Không lâu sau khi thọ giới, Tôn giả Māgaṇḍiya sống một mình, xa lánh, không phóng dật, tinh cần, tự mình tinh tấn, và không bao lâu sau, ngay trong hiện tại, với thắng trí của mình, đã chứng đạt và an trú vào mục đích tối thượng của đời sống phạm hạnh mà các thiện nam tử xuất gia từ bỏ gia đình để sống không gia đình, đó là sự chấm dứt của đời sống phạm hạnh. ",
  "mn75:28.3": "Ngài đã biết: “Sự sinh đã tận, đời sống phạm hạnh đã hoàn thành, việc cần làm đã làm, không còn trở lại trạng thái này nữa.”",
  "mn75:28.4": "Và Tôn giả Māgaṇḍiya đã trở thành một trong các vị A-la-hán. ",
  "mn75:28.5": "Kinh Māgaṇḍiya, thứ năm, chấm dứt. "
}
window.BILARA["mn75"]["vi"]["mn75:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/";
