window.BILARA = window.BILARA || {};
window.BILARA["sn1_v4"] = window.BILARA["sn1_v4"] || {};
window.BILARA["sn1_v4"]["vi"] = {
  "sn1.31:0.1": "Tương Ưng Bộ 1.31",
  "sn1.31:0.2": "4. Phẩm Nhóm Thiên Thần Satullapa",
  "sn1.31:0.3": "Kinh Người Hiền Lành",
  "sn1.31:1.1": "Tôi đã được nghe như vầy",
  "sn1.31:1.2": "Một thuở nọ, Đức Thế Tôn đang trú tại thành Sāvatthī, trong rừng Jetavana, tại tinh xá của ông Anāthapiṇḍika.",
  "sn1.31:1.3": "Khi đêm đã khuya, một nhóm đông các vị thiên thần thuộc hội chúng Satullapa xuất hiện với hào quang rực rỡ, soi sáng khắp rừng Jetavana, rồi đến chỗ Đức Thế Tôn, đảnh lễ và đứng sang một bên.",
  "sn1.31:1.4": "Đứng sang một bên, một vị thiên thần thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.31:2.1": "Hãy chỉ giao du với người hiền lành,",
  "sn1.31:2.2": "Hãy kết thân mật với người hiền lành;",
  "sn1.31:2.3": "Nhờ học hỏi chánh pháp từ người hiền,",
  "sn1.31:2.4": "'Người ta trở nên tốt hơn, không xấu đi.'",
  "sn1.31:3.1": "Rồi một vị thiên thần khác thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.31:4.1": "Hãy chỉ giao du với người hiền lành,",
  "sn1.31:4.2": "Hãy kết thân mật với người hiền lành;",
  "sn1.31:4.3": "Nhờ học hỏi chánh pháp từ người hiền,",
  "sn1.31:4.4": "'Trí tuệ được sinh ra  không từ đâu khác.'",
  "sn1.31:5.1": "Rồi một vị thiên thần khác thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.31:6.1": "Hãy chỉ giao du với người hiền lành,",
  "sn1.31:6.2": "Hãy kết thân mật với người hiền lành;",
  "sn1.31:6.3": "Nhờ học hỏi chánh pháp từ người hiền,",
  "sn1.31:6.4": "'Dù sống giữa đau khổ, người ta không còn sầu não.'",
  "sn1.31:7.1": "Rồi một vị thiên thần khác thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.31:8.1": "Hãy chỉ giao du với người hiền lành,",
  "sn1.31:8.2": "Hãy kết thân mật với người hiền lành;",
  "sn1.31:8.3": "Nhờ học hỏi chánh pháp từ người hiền,",
  "sn1.31:8.4": "'Người ta tỏa sáng giữa bà con thân thuộc.'",
  "sn1.31:9.1": "Rồi một vị thiên thần khác thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.31:10.1": "Hãy chỉ giao du với người hiền lành,",
  "sn1.31:10.2": "Hãy kết thân mật với người hiền lành;",
  "sn1.31:10.3": "Nhờ học hỏi chánh pháp từ người hiền,",
  "sn1.31:10.4": "'Chúng sinh được dẫn đến cõi lành.'",
  "sn1.31:11.1": "Rồi một vị thiên thần khác thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.31:12.1": "Hãy chỉ giao du với người hiền lành,",
  "sn1.31:12.2": "Hãy kết thân mật với người hiền lành;",
  "sn1.31:12.3": "Nhờ học hỏi chánh pháp từ người hiền,",
  "sn1.31:12.4": "'Chúng sinh an trú trong hạnh phúc lâu dài.'",
  "sn1.31:13.1": "Rồi một vị thiên thần khác hỏi Đức Thế Tôn:",
  "sn1.31:13.2": "'Thưa Đức Thế Tôn, bài kệ của ai là hay nhất?'",
  "sn1.31:14.1": "Tất cả các bài kệ của các vị đều hay, mỗi bài theo cách riêng của mình. Nhưng hãy nghe bài kệ của Ta:",
  "sn1.31:15.1": "Hãy chỉ giao du với người hiền lành,",
  "sn1.31:15.2": "Hãy kết thân mật với người hiền lành;",
  "sn1.31:15.3": "Nhờ học hỏi chánh pháp từ người hiền,",
  "sn1.31:15.4": "'Người ta thoát khỏi tất cả mọi khổ đau.'",
  "sn1.31:16.1": "Đức Thế Tôn đã dạy như vậy.",
  "sn1.31:16.2": "Các vị thiên thần hoan hỷ, đảnh lễ Đức Thế Tôn, đi nhiễu quanh theo chiều phải rồi biến mất ngay tại chỗ.",
  "sn1.32:0.1": "Tương Ưng Bộ 1.32",
  "sn1.32:0.2": "4. Phẩm Nhóm Thiên Thần Satullapa",
  "sn1.32:0.3": "Kinh Bủn Xỉn",
  "sn1.32:1.1": "Một thuở nọ, Đức Thế Tôn đang trú tại thành Sāvatthī, trong rừng Jetavana, tại tinh xá của ông Anāthapiṇḍika.",
  "sn1.32:1.2": "Khi đêm đã khuya, một nhóm đông các vị thiên thần thuộc hội chúng Satullapa xuất hiện với hào quang rực rỡ, soi sáng khắp rừng Jetavana, rồi đến chỗ Đức Thế Tôn, đảnh lễ và đứng sang một bên.",
  "sn1.32:1.3": "Đứng sang một bên, một vị thiên thần thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.32:2.1": "Vì bủn xỉn và vì lơ là, buông thả,",
  "sn1.32:2.2": "Mà việc bố thí không được thực hiện;",
  "sn1.32:2.3": "Người nào mong cầu phước báu",
  "sn1.32:2.4": "'Hãy biết mà cho đi những gì đáng cho.'",
  "sn1.32:3.1": "Rồi một vị thiên thần khác thưa với Đức Thế Tôn bằng những bài kệ này:",
  "sn1.32:4.1": "Điều mà kẻ bủn xỉn sợ hãi nên không cho,",
  "sn1.32:4.2": "Chính điều đó trở thành nỗi sợ của kẻ không cho;",
  "sn1.32:4.3": "Cái đói và cái khát",
  "sn1.32:4.4": "Mà kẻ bủn xỉn lo sợ",
  "sn1.32:4.5": "Chính những thứ đó sẽ giáng xuống kẻ ngu ấy,",
  "sn1.32:4.6": "Cả ở đời này lẫn đời sau.",
  "sn1.32:5.1": "Vì vậy hãy dẹp bỏ tính bủn xỉn,",
  "sn1.32:5.2": "Hãy bố thí, vượt qua cấu uế này;",
  "sn1.32:5.3": "Những việc phước lành ở đời sau",
  "sn1.32:5.4": "'Chính là chỗ nương tựa cho chúng sinh.'",
  "sn1.32:6.1": "Rồi một vị thiên thần khác thưa với Đức Thế Tôn bằng những bài kệ này:",
  "sn1.32:7.1": "Những người cho đi không chết đi trong lòng người đã mất,",
  "sn1.32:7.2": "Như người bạn đồng hành trên con đường;",
  "sn1.32:7.3": "Những ai cho đi dù chỉ có ít,",
  "sn1.32:7.4": "Đó là pháp bất diệt từ ngàn xưa.",
  "sn1.32:8.1": "Có người cho đi dù chỉ có ít,",
  "sn1.32:8.2": "Có người dù giàu cũng không cho;",
  "sn1.32:8.3": "Vật cúng dường được trao từ cái ít ỏi,",
  "sn1.32:8.4": "'Có giá trị ngang bằng với ngàn lần.'",
  "sn1.32:9.1": "Rồi một vị thiên thần khác thưa với Đức Thế Tôn bằng những bài kệ này:",
  "sn1.32:10.1": "Cho đi điều khó cho  đó là việc khó làm,",
  "sn1.32:10.2": "Làm điều khó làm  đó là hành động cao quý;",
  "sn1.32:10.3": "Kẻ xấu không bắt chước được,",
  "sn1.32:10.4": "Vì pháp của người hiền thật khó noi theo.",
  "sn1.32:11.1": "Vì vậy, giữa người hiền và kẻ xấu,",
  "sn1.32:11.2": "Con đường đi từ đây hoàn toàn khác nhau;",
  "sn1.32:11.3": "Kẻ xấu đi xuống địa ngục,",
  "sn1.32:11.4": "'Người hiền hướng về cõi trời.'",
  "sn1.32:12.1": "Rồi một vị thiên thần khác hỏi Đức Thế Tôn:",
  "sn1.32:12.2": "'Thưa Đức Thế Tôn, bài kệ của ai là hay nhất?'",
  "sn1.32:13.1": "Tất cả các bài kệ của các vị đều hay, mỗi bài theo cách riêng. Nhưng hãy nghe bài kệ của Ta:",
  "sn1.32:14.1": "Người sống đúng theo Chánh pháp, dù phải đi xin từng chút một,",
  "sn1.32:14.2": "Nuôi sống vợ con từ chút ít mình có;",
  "sn1.32:14.3": "Một trăm ngàn người tế lễ với ngàn lễ vật lớn lao,",
  "sn1.32:14.4": "'Cũng không đáng một phần nhỏ của người như vậy.'",
  "sn1.32:15.1": "Rồi một vị thiên thần khác hỏi lại Đức Thế Tôn bằng bài kệ:",
  "sn1.32:16.1": "Tại sao cuộc tế lễ lớn lao, đồ sộ như vậy,",
  "sn1.32:16.2": "Lại không bằng những gì được trao với tâm chân thật?",
  "sn1.32:16.3": "Tại sao một trăm ngàn người tế lễ với ngàn lễ vật,",
  "sn1.32:16.4": "'Lại không bằng một phần nhỏ của người đó?'",
  "sn1.32:17.1": "Vì có người bố thí trong khi đang làm điều bất chính",
  "sn1.32:17.2": "Chém giết, hành hạ, gây đau khổ cho người khác;",
  "sn1.32:17.3": "Vật cúng dường như vậy đẫm nước mắt và bạo lực,",
  "sn1.32:17.4": "Không thể nào bằng những gì được trao với tâm trong sạch.",
  "sn1.32:18.1": "Vì vậy, một trăm ngàn người tế lễ với ngàn lễ vật lớn lao,",
  "sn1.32:18.2": "'Cũng không đáng một phần nhỏ của người bố thí với tâm chân thật.'",
  "sn1.33:0.1": "Tương Ưng Bộ 1.33",
  "sn1.33:0.2": "4. Phẩm Nhóm Thiên Thần Satullapa",
  "sn1.33:0.3": "Kinh Lành Thay",
  "sn1.33:1.1": "Xuất xứ tại thành Sāvatthī.",
  "sn1.33:1.2": "Khi đêm đã khuya, một nhóm đông các vị thiên thần thuộc hội chúng Satullapa xuất hiện với hào quang rực rỡ, soi sáng khắp rừng Jetavana, rồi đến chỗ Đức Thế Tôn, đảnh lễ và đứng sang một bên.",
  "sn1.33:1.3": "Đứng sang một bên, một vị thiên thần thốt lên lời cảm hứng trước Đức Thế Tôn:",
  "sn1.33:2.1": "Lành thay, thưa Ngài, bố thí thật tốt đẹp!",
  "sn1.33:2.2": "Nhưng vì bủn xỉn và lơ là, buông thả,",
  "sn1.33:2.3": "Mà việc bố thí không được thực hiện.",
  "sn1.33:2.4": "Người mong cầu phước báu",
  "sn1.33:2.5": "'Hãy biết mà cho đi những gì đáng cho.'",
  "sn1.33:3.1": "Rồi một vị thiên thần khác thốt lên lời cảm hứng trước Đức Thế Tôn:",
  "sn1.33:4.1": "Lành thay, thưa Ngài, bố thí thật tốt đẹp!",
  "sn1.33:4.2": "Và lành thay, bố thí dù chỉ có ít ỏi cũng tốt.",
  "sn1.33:5.1": "Có người cho đi dù chỉ có ít,",
  "sn1.33:5.2": "Có người dù giàu cũng không chịu cho;",
  "sn1.33:5.3": "Vật cúng dường được trao từ cái ít ỏi,",
  "sn1.33:5.4": "'Có giá trị ngang bằng với ngàn lần.'",
  "sn1.33:6.1": "Rồi một vị thiên thần khác thốt lên lời cảm hứng trước Đức Thế Tôn:",
  "sn1.33:7.1": "Lành thay, thưa Ngài, bố thí thật tốt đẹp!",
  "sn1.33:7.2": "Lành thay, bố thí dù chỉ có ít ỏi cũng tốt;",
  "sn1.33:7.3": "Và lành thay, bố thí với lòng tin cũng tốt.",
  "sn1.33:7.4": "Người ta nói bố thí và chiến đấu có điểm giống nhau",
  "sn1.33:7.5": "Dù ít người vẫn có thể thắng đám đông;",
  "sn1.33:7.6": "Dù chỉ cho ít mà có lòng tin,",
  "sn1.33:7.7": "'Chính nhờ đó người ấy được hạnh phúc ở đời sau.'",
  "sn1.33:8.1": "Rồi một vị thiên thần khác thốt lên lời cảm hứng trước Đức Thế Tôn:",
  "sn1.33:9.1": "Lành thay, thưa Ngài, bố thí thật tốt đẹp!",
  "sn1.33:9.2": "Lành thay, bố thí dù chỉ có ít ỏi cũng tốt;",
  "sn1.33:9.3": "Lành thay, bố thí với lòng tin cũng tốt;",
  "sn1.33:9.4": "Và lành thay, bố thí từ những gì kiếm được chân chính cũng tốt.",
  "sn1.33:10.1": "Người nào bố thí từ của cải kiếm được chân chính,",
  "sn1.33:10.2": "Nhờ sự siêng năng và nỗ lực của chính mình;",
  "sn1.33:10.3": "Người ấy vượt qua dòng sông Vetaraṇī của Thần Chết,",
  "sn1.33:10.4": "'Và đạt đến những cõi trời tốt lành.'",
  "sn1.33:11.1": "Rồi một vị thiên thần khác thốt lên lời cảm hứng trước Đức Thế Tôn:",
  "sn1.33:12.1": "Lành thay, thưa Ngài, bố thí thật tốt đẹp!",
  "sn1.33:12.2": "Lành thay, bố thí dù chỉ có ít ỏi cũng tốt;",
  "sn1.33:12.3": "Lành thay, bố thí với lòng tin cũng tốt;",
  "sn1.33:12.4": "Lành thay, bố thí từ những gì kiếm được chân chính cũng tốt;",
  "sn1.33:12.5": "Và lành thay, bố thí có suy xét, chọn lựa kỹ cũng tốt.",
  "sn1.33:13.1": "Bố thí có suy xét được Đấng Thiện Thệ (Đức Phật) ca ngợi,",
  "sn1.33:13.2": "Dành cho những bậc xứng đáng thọ nhận ở đời này;",
  "sn1.33:13.3": "Những gì được trao cho các bậc ấy mang lại quả lớn,",
  "sn1.33:13.4": "'Như hạt giống gieo vào ruộng tốt.'",
  "sn1.33:14.1": "Rồi một vị thiên thần khác thốt lên lời cảm hứng trước Đức Thế Tôn:",
  "sn1.33:15.1": "Lành thay, thưa Ngài, bố thí thật tốt đẹp!",
  "sn1.33:15.2": "Lành thay, bố thí dù chỉ có ít ỏi cũng tốt;",
  "sn1.33:15.3": "Lành thay, bố thí với lòng tin cũng tốt;",
  "sn1.33:15.4": "Lành thay, bố thí từ những gì kiếm được chân chính cũng tốt;",
  "sn1.33:15.5": "Lành thay, bố thí có suy xét chọn lựa cũng tốt;",
  "sn1.33:15.6": "Và lành thay, hãy thêm vào đó sự kiềm chế, không làm hại chúng sinh.",
  "sn1.33:16.1": "Người nào sống không gây hại cho các chúng sinh,",
  "sn1.33:16.2": "Không làm ác bằng cách đổ lỗi hay chê bai người khác;",
  "sn1.33:16.3": "Người ta ca ngợi kẻ biết sợ (làm điều ác), chứ không ca ngợi kẻ liều lĩnh,",
  "sn1.33:16.4": "'Vì người hiền tránh làm ác chính là vì sợ hậu quả xấu.'",
  "sn1.33:17.1": "Rồi một vị thiên thần khác hỏi Đức Thế Tôn:",
  "sn1.33:17.2": "'Thưa Đức Thế Tôn, bài kệ của ai là hay nhất?'",
  "sn1.33:18.1": "Tất cả các bài kệ của các vị đều hay, mỗi bài theo cách riêng. Nhưng hãy nghe bài kệ của Ta:",
  "sn1.33:19.1": "Bố thí với lòng tin được ca ngợi theo nhiều cách,",
  "sn1.33:19.2": "Nhưng hơn cả bố thí chính là con đường Chánh pháp;",
  "sn1.33:19.3": "Vì xưa nay và từ thuở xa xưa, những bậc hiền trí,",
  "sn1.33:19.4": "'Chính nhờ trí tuệ mà đạt đến Niết-bàn.'",
  "sn1.34:0.1": "Tương Ưng Bộ 1.34",
  "sn1.34:0.2": "4. Phẩm Nhóm Thiên Thần Satullapa",
  "sn1.34:0.3": "Kinh Không Có Gì Là Thường",
  "sn1.34:1.1": "Một thuở nọ, Đức Thế Tôn đang trú tại thành Sāvatthī, trong rừng Jetavana, tại tinh xá của ông Anāthapiṇḍika.",
  "sn1.34:1.2": "Khi đêm đã khuya, một nhóm đông các vị thiên thần thuộc hội chúng Satullapa xuất hiện với hào quang rực rỡ, soi sáng khắp rừng Jetavana, rồi đến chỗ Đức Thế Tôn, đảnh lễ và đứng sang một bên.",
  "sn1.34:1.3": "Đứng sang một bên, một vị thiên thần thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.34:2.1": "Những dục lạc trong đời người không có gì là thường còn,",
  "sn1.34:2.2": "Nhưng ở đây có những thứ hấp dẫn trói buộc con người;",
  "sn1.34:2.3": "Ai mê đắm trong đó mà không tỉnh thức,",
  "sn1.34:2.4": "'Sẽ không thoát được khỏi cõi chết.'",
  "sn1.34:3.1": "Khổ đau sinh ra từ ham muốn, đau khổ sinh ra từ ham muốn;",
  "sn1.34:3.2": "Diệt trừ ham muốn thì diệt trừ được khổ đau;",
  "sn1.34:3.3": "'Diệt trừ khổ đau thì diệt trừ được đau khổ.'",
  "sn1.34:4.1": "Dục lạc không phải là những thứ đẹp đẽ hào nhoáng ngoài đời,",
  "sn1.34:4.2": "Mà dục lạc của con người chính là lòng tham ái phát sinh từ suy nghĩ;",
  "sn1.34:4.3": "Những thứ đẹp đẽ kia vẫn cứ ở đó trong thế gian,",
  "sn1.34:4.4": "Chính người trí mới biết dẹp bỏ ham muốn đối với chúng.",
  "sn1.34:5.1": "Hãy từ bỏ giận dữ, hãy hoàn toàn dứt bỏ ngã mạn,",
  "sn1.34:5.2": "Hãy vượt qua tất cả mọi xiềng xích trói buộc;",
  "sn1.34:5.3": "Người không còn bám víu vào thân tâm (danh và sắc),",
  "sn1.34:5.4": "Không còn sở hữu gì  khổ đau không còn bén mảng.",
  "sn1.34:6.1": "Người ấy đã buông bỏ mọi quan niệm, không còn kiêu ngạo,",
  "sn1.34:6.2": "Đã cắt đứt tham ái đối với thân tâm ở đây;",
  "sn1.34:6.3": "Người ấy đã cắt đứt mọi ràng buộc, không còn khổ não, không còn mong cầu",
  "sn1.34:6.4": "Dù có tìm kiếm cũng không thể thấy được người ấy;",
  "sn1.34:6.5": "Dù là chư thiên hay con người, ở đây hay ở cõi kia,",
  "sn1.34:6.6": "'Hay ở trên các cõi trời, trong tất cả mọi nơi cư trú.'",
  "sn1.34:7.1": "Nếu chư thiên và con người, ở đây hay ở cõi kia,",
  "sn1.34:7.2": "(Tôn giả Mogharāja nói)",
  "sn1.34:7.3": "Đều không thể thấy được vị giải thoát như vậy;",
  "sn1.34:7.4": "Thì những ai đảnh lễ bậc cao quý nhất trong loài người, người đi vì lợi ích của nhân loại",
  "sn1.34:7.5": "'Những người đó thật đáng được ca ngợi.'",
  "sn1.34:8.1": "Những vị tỳ-kheo đó cũng đáng được ca ngợi,",
  "sn1.34:8.2": "(Đức Thế Tôn đáp lời Mogharāja)",
  "sn1.34:8.3": "Những ai đảnh lễ vị đã giải thoát như vậy;",
  "sn1.34:8.4": "Vì đã thông hiểu Chánh pháp và đã dứt bỏ mọi nghi ngờ,",
  "sn1.34:8.5": "'Những vị tỳ-kheo đó cũng đã vượt qua bộc lưu (dòng lũ phiền não).'",
  "sn1.35:0.1": "Tương Ưng Bộ 1.35",
  "sn1.35:0.2": "4. Phẩm Nhóm Thiên Thần Satullapa",
  "sn1.35:0.3": "Kinh Thiên Thần Hay Gây Sự",
  "sn1.35:1.1": "Một thuở nọ, Đức Thế Tôn đang trú tại thành Sāvatthī, trong rừng Jetavana, tại tinh xá của ông Anāthapiṇḍika.",
  "sn1.35:1.2": "Khi đêm đã khuya, một nhóm đông các vị thiên thần hay gây sự, hay bắt bẻ người khác, xuất hiện với hào quang rực rỡ, soi sáng khắp rừng Jetavana, rồi đến chỗ Đức Thế Tôn  nhưng họ lơ lửng trên không, không chịu xuống đất hay đảnh lễ.",
  "sn1.35:1.3": "Đứng lơ lửng trên không, một vị thiên thần thưa với Đức Thế Tôn bằng bài kệ (ý muốn chỉ trích):",
  "sn1.35:2.1": "Người bên trong một đằng,",
  "sn1.35:2.2": "Mà ra ngoài lại nói một nẻo;",
  "sn1.35:2.3": "Chẳng khác gì tên lừa đảo khéo léo,",
  "sn1.35:2.4": "Những gì hắn hưởng thụ đều là ăn cắp mà có.",
  "sn1.35:3.1": "Làm gì thì hãy nói điều đó,",
  "sn1.35:3.2": "Điều gì không làm thì đừng nói;",
  "sn1.35:3.3": "Kẻ nói mà không làm,",
  "sn1.35:3.4": "'Người trí đều nhận ra ngay.'",
  "sn1.35:4.1": "Không phải chỉ bằng lời nói suông,",
  "sn1.35:4.2": "Hay chỉ nghe một chiều,",
  "sn1.35:4.3": "Mà có thể bước đi trên",
  "sn1.35:4.4": "Con đường vững chắc này",
  "sn1.35:4.5": "Con đường mà nhờ đó các bậc trí tuệ thoát khỏi",
  "sn1.35:4.6": "Xiềng xích của Ma vương, nhờ thiền định.",
  "sn1.35:5.1": "Thật vậy, bậc trí không khoe khoang khoác lác,",
  "sn1.35:5.2": "Vì các Ngài đã thấu hiểu cách vận hành của thế gian;",
  "sn1.35:5.3": "Đã giác ngộ, đã được nguội lạnh (thoát khổ),",
  "sn1.35:5.4": "'Đã vượt qua sự bám víu của thế gian.'",
  "sn1.35:6.1": "Khi ấy, các vị thiên thần đó xuống đất, cúi đầu đảnh lễ dưới chân Đức Thế Tôn và thưa rằng:",
  "sn1.35:6.2": "Bạch Đức Thế Tôn, chúng con đã phạm lỗi  đã hành động như kẻ ngu si, mê muội, thiếu thiện xảo, khi dám nghĩ rằng Đức Thế Tôn đáng bị công kích, chỉ trích.",
  "sn1.35:6.3": "'Bạch Đức Thế Tôn, xin Ngài hãy nhận lỗi của chúng con là lỗi lầm thật sự, để chúng con được thu thúc trong tương lai.'",
  "sn1.35:6.4": "Khi đó, Đức Thế Tôn mỉm cười.",
  "sn1.35:6.5": "Thấy vậy, các vị thiên thần lại càng lên tiếng gây sự hơn, rồi bay trở lên không trung.",
  "sn1.35:6.6": "Một vị thiên thần lại thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.35:7.1": "Khi ai đó thú nhận lỗi lầm của mình,",
  "sn1.35:7.2": "Mà người kia không chịu chấp nhận lời xin lỗi;",
  "sn1.35:7.3": "Người đó bên trong đang tức giận, nặng nề sân hận",
  "sn1.35:7.4": "'Chính họ đang gieo oán thù.'",
  "sn1.35:8.1": "Nếu không có lỗi lầm,",
  "sn1.35:8.2": "Và cũng không có gì để buông bỏ ở đây;",
  "sn1.35:8.3": "Thì oán thù sẽ không bao giờ chấm dứt",
  "sn1.35:8.4": "'Ai trong đời này có thể được gọi là người thiện xảo?'",
  "sn1.35:9.1": "Với ai thì không có lỗi lầm nào?",
  "sn1.35:9.2": "Với ai thì không có gì phải buông bỏ?",
  "sn1.35:9.3": "Ai là người chưa từng rơi vào si mê?",
  "sn1.35:9.4": "'Và ai là bậc trí luôn luôn chánh niệm?'",
  "sn1.35:10.1": "Đức Như Lai, bậc Giác Ngộ,",
  "sn1.35:10.2": "Người có lòng bi mẫn đối với tất cả chúng sinh;",
  "sn1.35:10.3": "Với Ngài, không có lỗi lầm nào,",
  "sn1.35:10.4": "Với Ngài, không có gì phải buông bỏ;",
  "sn1.35:10.5": "Ngài không bao giờ rơi vào si mê,",
  "sn1.35:10.6": "Chính Ngài là bậc trí luôn luôn chánh niệm.",
  "sn1.35:11.1": "Khi ai đó thú nhận lỗi lầm của mình,",
  "sn1.35:11.2": "Mà người kia không chịu chấp nhận;",
  "sn1.35:11.3": "Người đó bên trong đang tức giận, nặng nề sân hận",
  "sn1.35:11.4": "Chính họ đang gieo oán thù;",
  "sn1.35:11.5": "Oán thù đó Ta không chấp nhận",
  "sn1.35:11.6": "'Ta chấp nhận lời thú nhận lỗi lầm của các vị.'",
  "sn1.36:0.1": "Tương Ưng Bộ 1.36",
  "sn1.36:0.2": "4. Phẩm Nhóm Thiên Thần Satullapa",
  "sn1.36:0.3": "Kinh Lòng Tin",
  "sn1.36:1.1": "Một thuở nọ, Đức Thế Tôn đang trú tại thành Sāvatthī, trong rừng Jetavana, tại tinh xá của ông Anāthapiṇḍika.",
  "sn1.36:1.2": "Khi đêm đã khuya, một nhóm đông các vị thiên thần thuộc hội chúng Satullapa xuất hiện với hào quang rực rỡ, soi sáng khắp rừng Jetavana, rồi đến chỗ Đức Thế Tôn, đảnh lễ và đứng sang một bên.",
  "sn1.36:1.3": "Đứng sang một bên, một vị thiên thần thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.36:2.1": "Lòng tin là người bạn đồng hành của con người,",
  "sn1.36:2.2": "Miễn là sự thiếu tin không bén rễ trong tâm;",
  "sn1.36:2.3": "Danh tiếng và tiếng thơm sẽ đến với người ấy,",
  "sn1.36:2.4": "'Và khi lìa bỏ thân xác, người ấy sẽ sinh lên cõi trời.'",
  "sn1.36:3.1": "Rồi một vị thiên thần khác thưa với Đức Thế Tôn bằng những bài kệ này:",
  "sn1.36:4.1": "Hãy từ bỏ giận dữ, hãy hoàn toàn dứt bỏ ngã mạn,",
  "sn1.36:4.2": "Hãy vượt qua tất cả mọi xiềng xích trói buộc;",
  "sn1.36:4.3": "Người không còn bám víu vào thân tâm (danh và sắc),",
  "sn1.36:4.4": "'Không còn sở hữu gì  sự vướng bận không còn bén mảng.'",
  "sn1.36:5.1": "Kẻ ngu si, thiếu trí tuệ",
  "sn1.36:5.2": "Cứ mải mê đắm chìm trong sự lơ là, buông thả;",
  "sn1.36:5.3": "Còn người có trí tuệ thì giữ gìn sự không buông thả,",
  "sn1.36:5.4": "Như người bảo vệ kho báu quý giá nhất.",
  "sn1.36:6.1": "Đừng đắm mình trong sự lơ là, buông thả,",
  "sn1.36:6.2": "Đừng mê đắm, thân thiết với những thú vui dục lạc;",
  "sn1.36:6.3": "Người không buông thả, chuyên tâm thiền định,",
  "sn1.36:6.4": "'Sẽ đạt được hạnh phúc tối thượng.'",
  "sn1.37:0.1": "Tương Ưng Bộ 1.37",
  "sn1.37:0.2": "4. Phẩm Nhóm Thiên Thần Satullapa",
  "sn1.37:0.3": "Kinh Đại Hội",
  "sn1.37:1.1": "Tôi đã được nghe như vầy",
  "sn1.37:1.2": "Một thuở nọ, Đức Thế Tôn đang trú tại Kapilavatthu (Ca-tỳ-la-vệ), trong Đại Lâm (rừng lớn) giữa xứ Sakya (Thích Ca), cùng với đại chúng tỳ-kheo gồm khoảng năm trăm vị  tất cả đều là bậc A-la-hán;",
  "sn1.37:1.3": "Và các vị chư thiên từ mười thế giới hầu hết đều tập hội lại để đến chiêm ngưỡng Đức Thế Tôn và đại chúng tỳ-kheo.",
  "sn1.37:1.4": "Khi ấy, bốn vị thiên thần thuộc Tịnh Cư Thiên (Suddhāvāsa  cõi trời cao nhất trong sắc giới) nghĩ rằng:",
  "sn1.37:1.5": "Đức Thế Tôn đang trú tại Kapilavatthu trong Đại Lâm, cùng với năm trăm vị tỳ-kheo A-la-hán;",
  "sn1.37:1.6": "Và chư thiên từ mười thế giới hầu hết đã tụ hội về đây để chiêm ngưỡng Đức Thế Tôn và đại chúng.",
  "sn1.37:1.7": "'Vậy chúng ta hãy cùng đến gặp Đức Thế Tôn và mỗi người đọc một bài kệ trước Ngài.'",
  "sn1.37:2.1": "Rồi các vị thiên thần ấy  nhanh như một người lực lưỡng duỗi cánh tay đang co ra hay co cánh tay đang duỗi lại  biến mất khỏi cõi Tịnh Cư Thiên và hiện ra trước mặt Đức Thế Tôn.",
  "sn1.37:2.2": "Các vị đó đảnh lễ Đức Thế Tôn rồi đứng sang một bên.",
  "sn1.37:2.3": "Đứng sang một bên, một vị thiên thần thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.37:3.1": "Đây là đại hội trang trọng trong rừng,",
  "sn1.37:3.2": "Các thiên chúng từ khắp nơi đã tụ hội;",
  "sn1.37:3.3": "Chúng con đến đây dự hội Chánh pháp này,",
  "sn1.37:3.4": "'Để chiêm ngưỡng đại chúng bất khả chiến bại.'",
  "sn1.37:4.1": "Rồi một vị thiên thần khác thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.37:5.1": "Ở đó các vị tỳ-kheo đã định tâm,",
  "sn1.37:5.2": "Đã làm cho tâm mình ngay thẳng, vững vàng;",
  "sn1.37:5.3": "Như người đánh xe nắm chặt cương ngựa,",
  "sn1.37:5.4": "'Các bậc trí canh giữ các căn (mắt, tai, mũi, lưỡi, thân, ý).'",
  "sn1.37:6.1": "Rồi một vị thiên thần khác thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.37:7.1": "Đã chặt đứt cọc (tà kiến về ngã), đã phá tan chốt cửa (vô minh),",
  "sn1.37:7.2": "Đã nhổ bật cột trụ lớn (ngã mạn), không còn dao động;",
  "sn1.37:7.3": "Các Ngài đi trong sạch và tinh khiết,",
  "sn1.37:7.4": "'Những bậc voi chúa thuần thục dưới mắt bậc Giác Ngộ.'",
  "sn1.37:8.1": "Rồi một vị thiên thần khác thưa với Đức Thế Tôn bằng bài kệ:",
  "sn1.37:9.1": "Bất kỳ ai đã quy y Đức Phật,",
  "sn1.37:9.2": "Họ sẽ không đi đến các cõi khổ (địa ngục, ngạ quỷ, súc sinh);",
  "sn1.37:9.3": "Khi từ bỏ thân người này,",
  "sn1.37:9.4": "'Họ sẽ tràn đầy trong hàng ngũ chư thiên.'",
  "sn1.38:0.1": "Tương Ưng Bộ 1.38",
  "sn1.38:0.2": "4. Phẩm Nhóm Thiên Thần Satullapa",
  "sn1.38:0.3": "Kinh Mảnh Đá",
  "sn1.38:1.1": "Tôi đã được nghe như vầy",
  "sn1.38:1.2": "Một thuở nọ, Đức Thế Tôn đang trú tại Rājagaha (Vương Xá), trong vườn nai ở Maddakucchi.",
  "sn1.38:1.3": "Lúc bấy giờ, bàn chân của Đức Thế Tôn bị một mảnh đá đâm vào.",
  "sn1.38:1.4": "Đức Thế Tôn phải chịu đựng những cảm giác thân xác rất dữ dội  đau đớn, nhói buốt, dữ dằn, chua xót, khó chịu, bất an;",
  "sn1.38:1.5": "Nhưng Ngài vẫn nhẫn chịu với chánh niệm và tỉnh giác hoàn toàn, không bị khổ sở lay chuyển.",
  "sn1.38:1.6": "Đức Thế Tôn gấp tấm y tăng-già-lê thành bốn lớp, rồi nằm xuống bên phải theo tư thế sư tử nằm, chân này đặt lên chân kia, với chánh niệm và tỉnh giác.",
  "sn1.38:2.1": "Khi đêm đã khuya, bảy trăm vị thiên thần thuộc hội chúng Satullapa xuất hiện với hào quang rực rỡ, soi sáng khắp vườn nai Maddakucchi, rồi đến chỗ Đức Thế Tôn, đảnh lễ và đứng sang một bên.",
  "sn1.38:2.2": "Đứng sang một bên, một vị thiên thần thốt lên lời cảm hứng trước Đức Thế Tôn:",
  "sn1.38:2.3": "Thật sự vị sa-môn Gotama là một bậc vĩ đại như voi chúa!",
  "sn1.38:2.4": "'Với sức chịu đựng của bậc vĩ đại như voi chúa  những cảm giác thân xác đau đớn, nhói buốt, dữ dằn, chua xót, khó chịu, bất an đã khởi lên  mà Ngài vẫn nhẫn chịu với chánh niệm và tỉnh giác, không bị lay chuyển!'",
  "sn1.38:3.1": "Rồi một vị thiên thần khác thốt lên:",
  "sn1.38:3.2": "Thật sự vị sa-môn Gotama là một bậc dũng mãnh như sư tử!",
  "sn1.38:3.3": "'Với sức chịu đựng của sư tử  những cảm giác đau đớn ấy đã khởi lên  mà Ngài vẫn nhẫn chịu với chánh niệm và tỉnh giác, không bị lay chuyển!'",
  "sn1.38:4.1": "Rồi một vị thiên thần khác thốt lên:",
  "sn1.38:4.2": "Thật sự vị sa-môn Gotama là một con tuấn mã thuần chủng!",
  "sn1.38:4.3": "'Với sức chịu đựng của tuấn mã thuần chủng  những cảm giác đau đớn ấy đã khởi lên  mà Ngài vẫn nhẫn chịu với chánh niệm và tỉnh giác, không bị lay chuyển!'",
  "sn1.38:5.1": "Rồi một vị thiên thần khác thốt lên:",
  "sn1.38:5.2": "Thật sự vị sa-môn Gotama là một con bò đực cường tráng!",
  "sn1.38:5.3": "'Với sức chịu đựng của bò đực cường tráng  những cảm giác đau đớn ấy đã khởi lên  mà Ngài vẫn nhẫn chịu với chánh niệm và tỉnh giác, không bị lay chuyển!'",
  "sn1.38:6.1": "Rồi một vị thiên thần khác thốt lên:",
  "sn1.38:6.2": "Thật sự vị sa-môn Gotama là một con vật gánh nặng bền bỉ!",
  "sn1.38:6.3": "'Với sức chịu đựng bền bỉ  những cảm giác đau đớn ấy đã khởi lên  mà Ngài vẫn nhẫn chịu với chánh niệm và tỉnh giác, không bị lay chuyển!'",
  "sn1.38:7.1": "Rồi một vị thiên thần khác thốt lên:",
  "sn1.38:7.2": "Thật sự vị sa-môn Gotama là bậc đã được điều phục hoàn toàn!",
  "sn1.38:7.3": "'Với sức chịu đựng của bậc đã được điều phục  những cảm giác đau đớn ấy đã khởi lên  mà Ngài vẫn nhẫn chịu với chánh niệm và tỉnh giác, không bị lay chuyển!'",
  "sn1.38:8.1": "Rồi một vị thiên thần khác thốt lên:",
  "sn1.38:8.2": "Hãy nhìn xem  tâm định đã được tu tập hoàn hảo, tâm đã được giải thoát thật sự  không nghiêng về phía trước, không nghiêng về phía sau, không bị kìm hãm hay chặn đứng bởi sức mạnh cưỡng bức.",
  "sn1.38:8.3": "'Ai có thể nghĩ rằng mình có thể vượt qua được bậc vĩ đại như vậy  voi chúa trong loài người, sư tử trong loài người, tuấn mã trong loài người, bò đực trong loài người, người gánh nặng trong loài người, bậc điều phục trong loài người  trừ phi người đó không nhìn thấy (không hiểu biết gì)?'",
  "sn1.38:9.1": "Năm trăm Bà-la-môn tu khổ hạnh suốt trăm năm,",
  "sn1.38:9.2": "Đi theo con đường khổ hạnh của các nhà tu hành;",
  "sn1.38:9.3": "Nhưng tâm của họ không được giải thoát đúng đắn",
  "sn1.38:9.4": "Tầm thường trong mục tiêu, họ không đến được bờ kia.",
  "sn1.38:10.1": "Bị tham ái chi phối, bị trói buộc bởi giới cấm,",
  "sn1.38:10.2": "Tu khổ hạnh khắc nghiệt suốt trăm năm;",
  "sn1.38:10.3": "Nhưng tâm của họ không được giải thoát đúng đắn",
  "sn1.38:10.4": "Tầm thường trong mục tiêu, họ không đến được bờ kia.",
  "sn1.38:11.1": "Người còn ham muốn danh dự thì không có sự điều phục thật sự,",
  "sn1.38:11.2": "Người tâm không định tĩnh thì không có trí tuệ;",
  "sn1.38:11.3": "Sống một mình trong rừng mà buông thả, lơ đễnh",
  "sn1.38:11.4": "'Người đó không thể vượt qua bờ kia của cõi chết.'",
  "sn1.38:12.1": "Người đã từ bỏ ngã mạn, tâm được định tĩnh hoàn toàn,",
  "sn1.38:12.2": "Tâm trong sáng, giải thoát khắp mọi phía;",
  "sn1.38:12.3": "Sống một mình trong rừng với tâm không buông thả",
  "sn1.38:12.4": "'Chính người đó có thể vượt qua bờ kia của cõi chết.'",
  "sn1.39:0.1": "Tương Ưng Bộ 1.39",
  "sn1.39:0.2": "4. Phẩm Nhóm Thiên Thần Satullapa",
  "sn1.39:0.3": "Kinh Con Gái Pajjunna (Lần Một)",
  "sn1.39:1.1": "Tôi đã được nghe như vầy",
  "sn1.39:1.2": "Một thuở nọ, Đức Thế Tôn đang trú tại Vesālī (Tỳ-xá-ly), trong Đại Lâm, tại Giảng đường Có Mái Nhọn.",
  "sn1.39:1.3": "Khi đêm đã khuya, vị thiên thần Kokanadā, con gái của Pajjunna (vị thần mưa), xuất hiện với hào quang rực rỡ, soi sáng khắp Đại Lâm, rồi đến chỗ Đức Thế Tôn, đảnh lễ và đứng sang một bên.",
  "sn1.39:1.4": "Đứng sang một bên, thiên thần Kokanadā, con gái của Pajjunna, thưa với Đức Thế Tôn bằng những bài kệ này:",
  "sn1.39:2.1": "Ngài đang trú trong rừng tại Vesālī,",
  "sn1.39:2.2": "Bậc Giác Ngộ tối thượng trong tất cả chúng sinh;",
  "sn1.39:2.3": "Con là Kokanadā xin kính cẩn đảnh lễ,",
  "sn1.39:2.4": "Con là Kokanadā, con gái của Pajjunna.",
  "sn1.39:3.1": "Trước đây con chỉ được nghe kể lại,",
  "sn1.39:3.2": "Rằng Chánh pháp đã được bậc Có Mắt Tuệ giác ngộ;",
  "sn1.39:3.3": "Nhưng nay chính con được trực tiếp chứng kiến,",
  "sn1.39:3.4": "Bậc Mâu-ni, Đấng Thiện Thệ đang giảng dạy.",
  "sn1.39:4.1": "Những ai kẻ ngu si đi khắp nơi",
  "sn1.39:4.2": "Chê bai, phỉ báng Chánh pháp cao quý;",
  "sn1.39:4.3": "Họ sẽ đi đến địa ngục Roruva khủng khiếp,",
  "sn1.39:4.4": "Và phải chịu đựng khổ đau trong thời gian rất dài.",
  "sn1.39:5.1": "Còn những ai trong Chánh pháp cao quý,",
  "sn1.39:5.2": "Được trang bị bằng nhẫn nhục và tâm bình thản;",
  "sn1.39:5.3": "Khi từ bỏ thân người này,",
  "sn1.39:5.4": "'Họ sẽ tràn đầy trong hàng ngũ chư thiên.'",
  "sn1.40:0.1": "Tương Ưng Bộ 1.40",
  "sn1.40:0.2": "4. Phẩm Nhóm Thiên Thần Satullapa",
  "sn1.40:0.3": "Kinh Con Gái Pajjunna (Lần Hai)",
  "sn1.40:1.1": "Tôi đã được nghe như vầy",
  "sn1.40:1.2": "Một thuở nọ, Đức Thế Tôn đang trú tại Vesālī (Tỳ-xá-ly), trong Đại Lâm, tại Giảng đường Có Mái Nhọn.",
  "sn1.40:1.3": "Khi đêm đã khuya, thiên thần Cūḷakokanadā (Tiểu Kokanadā), con gái của Pajjunna, xuất hiện với hào quang rực rỡ, soi sáng khắp Đại Lâm, rồi đến chỗ Đức Thế Tôn, đảnh lễ và đứng sang một bên.",
  "sn1.40:1.4": "Đứng sang một bên, thiên thần Cūḷakokanadā, con gái của Pajjunna, thưa với Đức Thế Tôn bằng những bài kệ này:",
  "sn1.40:2.1": "Con đến đây với ánh sáng rực rỡ như tia chớp,",
  "sn1.40:2.2": "Kokanadā, con gái của Pajjunna;",
  "sn1.40:2.3": "Kính lễ Đức Phật và Chánh pháp,",
  "sn1.40:2.4": "Con xin nói lên những bài kệ có ý nghĩa này.",
  "sn1.40:3.1": "Con có thể phân tích điều này theo nhiều cách,",
  "sn1.40:3.2": "Vì Chánh pháp có thể được giải thích theo nhiều phương diện;",
  "sn1.40:3.3": "Nhưng con sẽ nói ngắn gọn những điểm cốt lõi,",
  "sn1.40:3.4": "Chỉ trong phạm vi những gì con đã thông hiểu trong tâm.",
  "sn1.40:4.1": "Chớ làm bất cứ điều ác nào bằng lời nói hay bằng tâm ý,",
  "sn1.40:4.2": "Hay bằng thân xác, bất cứ điều gì trong toàn thế giới;",
  "sn1.40:4.3": "Hãy từ bỏ dục lạc, sống với chánh niệm và tỉnh giác,",
  "sn1.40:4.4": "'Chớ theo đuổi khổ đau  điều chỉ mang lại bất lợi mà thôi.'",
  "sn1.40:4.5": "Phẩm Nhóm Thiên Thần Satullapa  Phẩm thứ tư.",
  "sn1.40:5.0": "Kệ tóm tắt phẩm:",
  "sn1.40:5.1": "Người Hiền Lành, Bủn Xỉn, Lành Thay,",
  "sn1.40:5.2": "Không Có Gì Là Thường, Thiên Thần Hay Gây Sự;",
  "sn1.40:5.3": "Lòng Tin, Đại Hội, Mảnh Đá,",
  "sn1.40:5.4": "'Và hai kinh về hai con gái của Pajjunna.'"
}
window.BILARA["sn1_v4"]["vi"]["sn1_v4:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com;"
