window.BILARA = window.BILARA || {};
window.BILARA["sn2_v2"] = window.BILARA["sn2_v2"] || {};
window.BILARA["sn2_v2"]["vi"] = {
  "sn2.11:0.1": "Tương Ưng Bộ Kinh 2.11",
  "sn2.11:0.2": "2. Phẩm Anāthapiṇḍika",
  "sn2.11:0.3": "Kinh Candimasa",
  "sn2.11:1.1": "Duyên khởi tại thành Sāvatthī.",
  "sn2.11:1.2": "Khi ấy, thiên tử Candimasa, vào lúc đêm đã về khuya, với ánh hào quang rực rỡ chiếu sáng toàn khu vườn Jetavana, đến chỗ Đức Thế Tôn, đảnh lễ Ngài rồi đứng sang một bên.",
  "sn2.11:1.3": "Đứng sang một bên, thiên tử Candimasa đọc bài kệ này trước mặt Đức Thế Tôn:",
  "sn2.11:2.1": "Những vị ấy chắc chắn sẽ đi đến an ổn,",
  "sn2.11:2.2": "như những con nai trên bãi cỏ xanh mướt;",
  "sn2.11:2.3": "Những ai chứng đạt và an trú thiền định,",
  "sn2.11:2.4": "'với tâm chuyên nhất, sáng suốt và chánh niệm.'",
  "sn2.11:3.1": "Những vị ấy chắc chắn sẽ đến được bờ kia,",
  "sn2.11:3.2": "như loài sen vươn lên khỏi mặt nước chặt đứt lưới bẫy;",
  "sn2.11:3.3": "Những ai chứng đạt và an trú thiền định,",
  "sn2.11:3.4": "'không phóng dật, đã buông bỏ mọi tranh chấp.'",
  "sn2.12:0.1": "Tương Ưng Bộ Kinh 2.12",
  "sn2.12:0.2": "2. Phẩm Anāthapiṇḍika",
  "sn2.12:0.3": "Kinh Veṇḍu",
  "sn2.12:1.1": "Đứng sang một bên, thiên tử Veṇḍu đọc bài kệ này trước mặt Đức Thế Tôn:",
  "sn2.12:2.1": "Thật hạnh phúc thay những con người ấy,",
  "sn2.12:2.2": "được thân cận gần gũi bậc Thiện Thệ;",
  "sn2.12:2.3": "Chuyên tâm tu tập theo lời dạy của Gotama,",
  "sn2.12:2.4": "'không phóng dật, học hỏi tu tập từng bước.'",
  "sn2.12:3.1": "Những ai học tập theo lời dạy đúng đắn mà Ta đã tuyên thuyết,",
  "sn2.12:3.2": "(Đức Thế Tôn đáp  này Veṇḍu)",
  "sn2.12:3.3": "với tâm chuyên chú thiền định;",
  "sn2.12:3.4": "Những vị ấy không phóng dật đúng lúc đúng thời,",
  "sn2.12:3.5": "'sẽ không còn bị rơi vào vòng kiểm soát của thần Chết nữa.'",
  "sn2.13:0.1": "Tương Ưng Bộ Kinh 2.13",
  "sn2.13:0.2": "2. Phẩm Anāthapiṇḍika",
  "sn2.13:0.3": "Kinh Dīghalaṭṭhi",
  "sn2.13:1.1": "Tôi nghe như vầy",
  "sn2.13:1.2": "Một thời, Đức Thế Tôn đang trú tại thành Rājagaha, trong rừng Trúc Lâm, vườn Kalandakanivāpa.",
  "sn2.13:1.3": "Khi ấy, thiên tử Dīghalaṭṭhi, vào lúc đêm đã về khuya, với ánh hào quang rực rỡ chiếu sáng toàn khu rừng Trúc Lâm, đến chỗ Đức Thế Tôn, đảnh lễ Ngài rồi đứng sang một bên.",
  "sn2.13:1.4": "Đứng sang một bên, thiên tử Dīghalaṭṭhi đọc bài kệ này trước mặt Đức Thế Tôn:",
  "sn2.13:2.1": "Vị tỳ kheo nên thiền định với tâm hoàn toàn giải thoát,",
  "sn2.13:2.2": "nếu mong muốn đạt đến điều thấm sâu trong tâm;",
  "sn2.13:2.3": "Sau khi thấu rõ sự sinh khởi và hoại diệt của thế gian,",
  "sn2.13:2.4": "'với tâm trong sạch, không bám víu  đó chính là lợi ích thật sự.'",
  "sn2.14:0.1": "Tương Ưng Bộ Kinh 2.14",
  "sn2.14:0.2": "2. Phẩm Anāthapiṇḍika",
  "sn2.14:0.3": "Kinh Nandana",
  "sn2.14:1.1": "Đứng sang một bên, thiên tử Nandana đọc bài kệ thưa với Đức Thế Tôn rằng:",
  "sn2.14:2.1": "Con xin hỏi Ngài, Gotama bậc đại trí tuệ,",
  "sn2.14:2.2": "với trí tuệ và nhãn kiến của Thế Tôn không bị che ngăn;",
  "sn2.14:2.3": "Người như thế nào được gọi là người có giới hạnh,",
  "sn2.14:2.4": "người như thế nào được gọi là người có trí tuệ;",
  "sn2.14:2.5": "Người như thế nào vượt qua được khổ đau mà sống,",
  "sn2.14:2.6": "'người như thế nào được chư thiên tôn kính cúng dường?'",
  "sn2.14:3.1": "Người có giới hạnh, có trí tuệ, đã tu tập tự thân hoàn thiện,",
  "sn2.14:3.2": "tâm định tĩnh, vui thích thiền định, luôn chánh niệm;",
  "sn2.14:3.3": "Mọi sầu khổ đều đã được đoạn trừ và buông bỏ hoàn toàn,",
  "sn2.14:3.4": "đã đoạn tận các lậu hoặc, đang mang thân xác cuối cùng.",
  "sn2.14:4.1": "Người như vậy được gọi là người có giới hạnh,",
  "sn2.14:4.2": "người như vậy được gọi là người có trí tuệ;",
  "sn2.14:4.3": "Người như vậy vượt qua được khổ đau mà sống,",
  "sn2.14:4.4": "'người như vậy được chư thiên tôn kính cúng dường.'",
  "sn2.15:0.1": "Tương Ưng Bộ Kinh 2.15",
  "sn2.15:0.2": "2. Phẩm Anāthapiṇḍika",
  "sn2.15:0.3": "Kinh Candana",
  "sn2.15:1.1": "Đứng sang một bên, thiên tử Candana đọc bài kệ thưa với Đức Thế Tôn rằng:",
  "sn2.15:2.1": "Làm thế nào để vượt qua được dòng lũ,",
  "sn2.15:2.2": "ngày đêm không mệt mỏi biếng lười;",
  "sn2.15:2.3": "Không có chỗ đứng, không có chỗ bám víu,",
  "sn2.15:2.4": "'ai là người không bị chìm đắm giữa chốn sâu thẳm?'",
  "sn2.15:3.1": "Người luôn luôn đầy đủ giới hạnh,",
  "sn2.15:3.2": "có trí tuệ, tâm định tĩnh vững vàng;",
  "sn2.15:3.3": "Tinh tấn nỗ lực, tự thân chuyên chú tu tập,",
  "sn2.15:3.4": "sẽ vượt qua được dòng lũ khó vượt.",
  "sn2.15:4.1": "Người đã từ bỏ các tưởng về dục lạc,",
  "sn2.15:4.2": "vượt thoát khỏi mọi ràng buộc của sắc pháp;",
  "sn2.15:4.3": "Đã đoạn tận hoàn toàn tham ái và hỷ lạc,",
  "sn2.15:4.4": "'người đó sẽ không bị chìm đắm giữa chốn sâu thẳm.'",
  "sn2.16:0.1": "Tương Ưng Bộ Kinh 2.16",
  "sn2.16:0.2": "2. Phẩm Anāthapiṇḍika",
  "sn2.16:0.3": "Kinh Vāsudatta",
  "sn2.16:1.1": "Đứng sang một bên, thiên tử Vāsudatta đọc bài kệ này trước mặt Đức Thế Tôn:",
  "sn2.16:2.1": "Như bị ngọn giáo đâm vào thân,",
  "sn2.16:2.2": "như ngọn lửa đang bốc cháy trên đầu;",
  "sn2.16:2.3": "Để đoạn trừ lòng tham ái dục lạc,",
  "sn2.16:2.4": "'vị tỳ kheo hãy chánh niệm mà du hành.'",
  "sn2.16:3.1": "Như bị ngọn giáo đâm vào thân,",
  "sn2.16:3.2": "như ngọn lửa đang bốc cháy trên đầu;",
  "sn2.16:3.3": "Để đoạn trừ tà kiến về thân này là thật có,",
  "sn2.16:3.4": "'vị tỳ kheo hãy chánh niệm mà du hành.'",
  "sn2.17:0.1": "Tương Ưng Bộ Kinh 2.17",
  "sn2.17:0.2": "2. Phẩm Anāthapiṇḍika",
  "sn2.17:0.3": "Kinh Subrahmā",
  "sn2.17:1.1": "Đứng sang một bên, thiên tử Subrahmā đọc bài kệ thưa với Đức Thế Tôn rằng:",
  "sn2.17:2.1": "Tâm này luôn luôn bất an lo sợ,",
  "sn2.17:2.2": "ý này luôn luôn xao động không yên;",
  "sn2.17:2.3": "Dù là những khó khăn chưa xảy đến,",
  "sn2.17:2.4": "hay những khó khăn đã ập tới rồi;",
  "sn2.17:2.5": "Nếu có cách nào để thoát khỏi sự lo âu bất an này,",
  "sn2.17:2.6": "'xin hãy chỉ dạy cho con khi được hỏi.'",
  "sn2.17:3.1": "Không có con đường nào khác ngoài giác ngộ và khổ hạnh tinh tấn,",
  "sn2.17:3.2": "không có con đường nào khác ngoài sự thu thúc các căn;",
  "sn2.17:3.3": "Không có con đường nào khác ngoài việc buông bỏ tất cả mọi thứ,",
  "sn2.17:3.4": "'Ta không thấy con đường nào khác dẫn đến sự an ổn cho chúng sinh.'",
  "sn2.17:4.1": "Thiên tử Subrahmā nói như vậy…",
  "sn2.17:4.2": "rồi biến mất ngay tại chỗ đó.",
  "sn2.18:0.1": "Tương Ưng Bộ Kinh 2.18",
  "sn2.18:0.2": "2. Phẩm Anāthapiṇḍika",
  "sn2.18:0.3": "Kinh Kakudha",
  "sn2.18:1.1": "Tôi nghe như vầy",
  "sn2.18:1.2": "Một thời, Đức Thế Tôn đang trú tại thành Sāketa, trong rừng Añjana, vườn nai.",
  "sn2.18:1.3": "Khi ấy, thiên tử Kakudha, vào lúc đêm đã về khuya, với ánh hào quang rực rỡ chiếu sáng toàn khu rừng Añjana, đến chỗ Đức Thế Tôn, đảnh lễ Ngài rồi đứng sang một bên. Đứng sang một bên, thiên tử Kakudha thưa với Đức Thế Tôn rằng:",
  "sn2.18:1.4": "'Này Sa-môn, Ngài có vui không?'",
  "sn2.18:1.5": "'Này hiền giả, vui vì được gì?'",
  "sn2.18:1.6": "'Vậy thì, này Sa-môn, Ngài có buồn không?'",
  "sn2.18:1.7": "'Này hiền giả, buồn vì mất gì?'",
  "sn2.18:1.8": "'Vậy thì, này Sa-môn, Ngài không vui cũng không buồn?'",
  "sn2.18:1.9": "'Đúng vậy, này hiền giả.'",
  "sn2.18:2.1": "Thưa tỳ kheo, có phải Ngài không còn phiền não,",
  "sn2.18:2.2": "có phải không còn tìm thấy niềm vui nào nữa;",
  "sn2.18:2.3": "Có phải khi Ngài ngồi một mình,",
  "sn2.18:2.4": "'sự chán nản không còn xâm chiếm Ngài nữa?'",
  "sn2.18:3.1": "Đúng vậy, này thiên tử, ta không còn phiền não,",
  "sn2.18:3.2": "và cũng không còn tìm thấy niềm vui nào nữa;",
  "sn2.18:3.3": "Và khi ta ngồi một mình,",
  "sn2.18:3.4": "'sự chán nản không còn xâm chiếm ta nữa.'",
  "sn2.18:4.1": "Này tỳ kheo, làm thế nào mà Ngài không còn phiền não,",
  "sn2.18:4.2": "làm thế nào mà không còn tìm thấy niềm vui nào;",
  "sn2.18:4.3": "Làm thế nào mà khi Ngài ngồi một mình,",
  "sn2.18:4.4": "'sự chán nản không còn xâm chiếm Ngài nữa?'",
  "sn2.18:5.1": "Niềm vui sinh ra từ phiền não khổ đau,",
  "sn2.18:5.2": "phiền não khổ đau sinh ra từ niềm vui;",
  "sn2.18:5.3": "Vị tỳ kheo không còn niềm vui cũng không còn phiền não,",
  "sn2.18:5.4": "'này hiền giả, hãy hiểu như vậy.'",
  "sn2.18:6.1": "Thật lâu lắm rồi mới được thấy,",
  "sn2.18:6.2": "một bậc Bà-la-môn đã hoàn toàn Niết-bàn;",
  "sn2.18:6.3": "Vị tỳ kheo không còn niềm vui, không còn phiền não,",
  "sn2.18:6.4": "'đã vượt qua mọi ràng buộc chấp thủ ở đời.'",
  "sn2.19:0.1": "Tương Ưng Bộ Kinh 2.19",
  "sn2.19:0.2": "2. Phẩm Anāthapiṇḍika",
  "sn2.19:0.3": "Kinh Uttara",
  "sn2.19:1.1": "Duyên khởi tại thành Rājagaha.",
  "sn2.19:1.2": "Đứng sang một bên, thiên tử Uttara đọc bài kệ này trước mặt Đức Thế Tôn:",
  "sn2.19:2.1": "Cuộc đời ngắn ngủi đang dần trôi qua,",
  "sn2.19:2.2": "người đã bị già xâm chiếm thì không còn chỗ nương tựa;",
  "sn2.19:2.3": "Nhìn thấy mối hiểm nguy này trong cái chết,",
  "sn2.19:2.4": "'hãy làm các việc phước lành mang lại hạnh phúc an vui.'",
  "sn2.19:3.1": "Cuộc đời ngắn ngủi đang dần trôi qua,",
  "sn2.19:3.2": "người đã bị già xâm chiếm thì không còn chỗ nương tựa;",
  "sn2.19:3.3": "Nhìn thấy mối hiểm nguy này trong cái chết,",
  "sn2.19:3.4": "'người mong cầu an tịch hãy buông bỏ mọi ham muốn thế gian.'",
  "sn2.20:0.1": "Tương Ưng Bộ Kinh 2.20",
  "sn2.20:0.2": "2. Phẩm Anāthapiṇḍika",
  "sn2.20:0.3": "Kinh Anāthapiṇḍika",
  "sn2.20:1.1": "Đứng sang một bên, thiên tử Anāthapiṇḍika đọc những bài kệ này trước mặt Đức Thế Tôn:",
  "sn2.20:2.1": "Đây chính là khu vườn Jetavana ấy,",
  "sn2.20:2.2": "nơi được đoàn thánh nhân thường lui tới;",
  "sn2.20:2.3": "Nơi mà Pháp vương đang ngự trị,",
  "sn2.20:2.4": "khiến lòng con tràn đầy hỷ lạc.",
  "sn2.20:3.1": "Nghiệp lành, trí tuệ và Chánh pháp,",
  "sn2.20:3.2": "giới hạnh  đó mới là cuộc sống cao quý nhất;",
  "sn2.20:3.3": "Nhờ những điều này mà con người được thanh tịnh,",
  "sn2.20:3.4": "chứ không phải nhờ dòng dõi hay tài sản.",
  "sn2.20:4.1": "Vì vậy, người trí khi nhìn thấy lợi ích thật sự cho mình,",
  "sn2.20:4.2": "hãy khéo léo suy xét Chánh pháp một cách thấu đáo,",
  "sn2.20:4.3": "hãy khéo léo tìm hiểu Chánh pháp từ gốc rễ,",
  "sn2.20:4.4": "như vậy mới được thanh tịnh trong Chánh pháp đó.",
  "sn2.20:5.1": "Cũng như tôn giả Sāriputta với trí tuệ,",
  "sn2.20:5.2": "giới hạnh và sự an tịnh;",
  "sn2.20:5.3": "Dù là vị tỳ kheo đã đến bờ kia,",
  "sn2.20:5.4": "'cũng chỉ đạt đến mức tối cao là như vậy thôi.'",
  "sn2.20:6.1": "Thiên tử Anāthapiṇḍika nói như vậy.",
  "sn2.20:6.2": "Nói xong, đảnh lễ Đức Thế Tôn, đi nhiễu quanh Ngài theo chiều bên phải rồi biến mất ngay tại chỗ đó.",
  "sn2.20:7.1": "Sau đó, khi đêm qua, Đức Thế Tôn gọi các tỳ kheo lại và nói:",
  "sn2.20:7.2": "Này các tỳ kheo, đêm qua có một thiên tử, vào lúc đêm đã về khuya, với ánh hào quang rực rỡ chiếu sáng toàn khu vườn Jetavana, đến chỗ Ta, đảnh lễ Ta rồi đứng sang một bên.",
  "sn2.20:7.3": "Đứng sang một bên, này các tỳ kheo, vị thiên tử ấy đọc những bài kệ này trước mặt Ta:",
  "sn2.20:8.1": "'Đây chính là khu vườn Jetavana ấy,'",
  "sn2.20:8.2": "nơi được đoàn thánh nhân thường lui tới;",
  "sn2.20:8.3": "Nơi mà Pháp vương đang ngự trị,",
  "sn2.20:8.4": "khiến lòng ta tràn đầy hỷ lạc.",
  "sn2.20:9.1": "Nghiệp lành, trí tuệ và Chánh pháp,",
  "sn2.20:9.2": "giới hạnh  đó mới là cuộc sống cao quý nhất;",
  "sn2.20:9.3": "Nhờ những điều này mà con người được thanh tịnh,",
  "sn2.20:9.4": "chứ không phải nhờ dòng dõi hay tài sản.",
  "sn2.20:10.1": "Vì vậy, người trí khi nhìn thấy lợi ích thật sự cho mình,",
  "sn2.20:10.2": "hãy khéo léo suy xét Chánh pháp một cách thấu đáo,",
  "sn2.20:10.3": "hãy khéo léo tìm hiểu Chánh pháp từ gốc rễ,",
  "sn2.20:10.4": "như vậy mới được thanh tịnh trong Chánh pháp đó.",
  "sn2.20:11.1": "Cũng như tôn giả Sāriputta với trí tuệ,",
  "sn2.20:11.2": "giới hạnh và sự an tịnh;",
  "sn2.20:11.3": "Dù là vị tỳ kheo đã đến bờ kia,",
  "sn2.20:11.4": "'cũng chỉ đạt đến mức tối cao là như vậy thôi.'",
  "sn2.20:12.1": "Này các tỳ kheo, vị thiên tử ấy đã nói như vậy.",
  "sn2.20:12.2": "'Nói xong, đảnh lễ Ta, đi nhiễu quanh theo chiều bên phải rồi biến mất ngay tại chỗ đó.'",
  "sn2.20:13.1": "Khi nghe vậy, tôn giả Ānanda thưa với Đức Thế Tôn rằng:",
  "sn2.20:13.2": "Bạch Thế Tôn, chắc chắn đó là thiên tử Anāthapiṇḍika.",
  "sn2.20:13.3": "'Vì trưởng giả Anāthapiṇḍika có lòng tịnh tín sâu sắc đối với tôn giả Sāriputta.'",
  "sn2.20:13.4": "Lành thay, lành thay, này Ānanda! Này Ānanda, ông đã suy luận đúng đến mức có thể suy luận được.",
  "sn2.20:13.5": "'Này Ānanda, đó chính là thiên tử Anāthapiṇḍika.'",
  "sn2.20:13.6": "Hết Phẩm Anāthapiṇḍika, phẩm thứ hai.",
  "sn2.20:14.0": "Tóm lược phẩm này:",
  "sn2.20:14.1": "Candimasa và Veṇḍu,",
  "sn2.20:14.2": "Dīghalaṭṭhi và Nandana;",
  "sn2.20:14.3": "Candana và Vāsudatta,",
  "sn2.20:14.4": "Subrahmā và Kakudha;",
  "sn2.20:14.5": "Uttara là kinh thứ chín,",
  "sn2.20:14.6": "'Anāthapiṇḍika là kinh thứ mười.'"
}
window.BILARA["sn2_v2"]["vi"]["sn2_v2:source"] =
"Dịch từ nguồn Pali https://suttacentral.net/ .Trong quá trình dịch có thể có sai sót, vui lòng đối chiếu bản gốc Pali, và tiếng Anh. Mọi góp ý chỉnh sửa xin vui lòng email: tuanctvn199@gmail.com";
